### ISSUE TITLE
Not updated to 1.16

### ISSUE THREAD

**Issue by Lord-Memester** [Fabricators-of-Create/Create#10]
While I know it's not _really_ an issue, I'd still like a version for 1.16(.5). Pretty please?

**Comment by YTG1234** [comment]
https://github.com/Create-Fabric/Create-Refabricated/blob/b4e86ed1b4b4776f8e59b95d0da3990059053a4e/gradle.properties#L7

**Comment by Lord-Memester** [comment]
### **Oh.** 
Is there a release for it?

**Comment by YTG1234** [comment]
The port is currently incomplete and is lacking in functionality. If you want to test it or contribute yourself, compile it from source.

**Comment by Lord-Memester** [comment]
Cool. Sorry.
###### _How I wish I could figure out how to compile._
