### ISSUE TITLE
Engineer goggles overlay doesn't work

### ISSUE THREAD

**Issue by Pewchenka** [Fabricators-of-Create/Create#1000]
### Describe the Bug

I play with mod pack with my friends and my engineer goggles overlay doesn't work but everything works for my friends

### Reproduction Steps

Wear Engineer goggles

### Expected Result

Engineer goggles overlay doesn't work

### Screenshots and Videos

<img width="1920" alt="image" src="https://github.com/Fabricators-of-Create/Create/assets/60707825/a198c2f7-e753-4308-ad6c-ab57f131acbe">

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.18.2

### Other Mods

[Iris Shaders (by coderbot)](https://www.curseforge.com/minecraft/mc-mods/irisshaders)
[Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[Forgotten Graves (by Syhlo)](https://www.curseforge.com/minecraft/mc-mods/forgotten-graves)
[Cloth Config API (UNUSED) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config-legacy)
[Immersive Armors [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Simple Hats (by fonnymunkey)](https://www.curseforge.com/minecraft/mc-mods/simplehats)
[YUNG's Better Witch Huts (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts-fabric)
[Guard Villagers (Fabric/Quilt) (by MrSterner_)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers-fabric)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Iron Chests: Restocked (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/ironchests)
[Drink Beer Unofficial: Clockwerk Edition (by ClockwerkKaiser)](https://www.curseforge.com/minecraft/mc-mods/drink-beer-unofficial-clockwerk-edition)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Small Ships [Fabric & Forge] (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[Coffee Delight (by someoneice)](https://www.curseforge.com/minecraft/mc-mods/coffee-delight)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Paradise Lost (by ImmortalDevs)](https://www.curseforge.com/minecraft/mc-mods/paradise-lost)
[Explorations [Forge|Fabric] (by Buecher_wurm)](https://www.curseforge.com/minecraft/mc-mods/explorations)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Jade Addons (Fabric) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade-addons-fabric)
[Mod Menu (by Prospector)](https://www.curseforge.com/minecraft/mc-mods/modmenu)
[Variety API (by texboobcat)](https://www.curseforge.com/minecraft/mc-mods/varietyapi)
[YUNG's Better Desert Temples (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples-fabric)
[Mystical Oak Tree (by plantspookable)](https://www.curseforge.com/minecraft/mc-mods/mystical-oak-tree)
[ewewukek's Musket mod (by ewewukek)](https://www.curseforge.com/minecraft/mc-mods/ewewukeks-musket-mod)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[So Many Enchantments (by ShelterRin)](https://www.curseforge.com/minecraft/mc-mods/so-many-enchantments)
[Lanterns Belong on Walls (by CoalTheBurnRock)](https://www.curseforge.com/minecraft/mc-mods/lanterns-bow)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[WTHIT (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit)
[Sodium (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/sodium)
[More Geodes (by TheDeathlyCow)](https://www.curseforge.com/minecraft/mc-mods/emerald-geodes)
[Cloth API (Fabric) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-api)
[YUNG's API (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Prefab - Fabric (by MoonliteDelight)](https://www.curseforge.com/minecraft/mc-mods/prefab-fabric)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Variety Aquatic (by texboobcat)](https://www.curseforge.com/minecraft/mc-mods/variety-aquatic)
[HT's TreeChop (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechop)
[Forge Config API Port [Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Emotecraft (Fabric) (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/emotecraft)
[Trinkets (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/trinkets)
[Another Furniture (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/another-furniture)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[Hephaestus Fabric (by thatguynamedalpha)](https://www.curseforge.com/minecraft/mc-mods/hephaestus-fabric)
[Create Fabric (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
[Simple Backpack [FABRIC] (by kwpugh)](https://www.curseforge.com/minecraft/mc-mods/simple-backpack-fabric)
[MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
[Chest Tracker (by JackFred2)](https://www.curseforge.com/minecraft/mc-mods/chest-tracker)
[Just Player Heads (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/just-player-heads)
[ToroHealth Damage Indicators (by ToroCraft)](https://www.curseforge.com/minecraft/mc-mods/torohealth-damage-indicators)
[Marium's Soulslike Weaponry (by mariumbacchus)](https://www.curseforge.com/minecraft/mc-mods/mariums-soulslike-weaponry)
[Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Climb Ladders Fast [Fabric/Forge] (by spoorn)](https://www.curseforge.com/minecraft/mc-mods/climb-ladders-fast)

**Comment by electricsteve** [comment]
Is it a custom modpack or is it a public one? Can you try without shaders on

**Comment by BlazeHunterVN1610** [comment]
I thinks it's because Jade Addon's integration with Create, did you turn the Integrate Goggles with Detail-Only on?
Btw, here is a video about the bug:

https://github.com/Fabricators-of-Create/Create/assets/111768452/0fe21c13-9ed4-47d2-a939-8eca66f7bb5d

**Comment by TropheusJ** [comment]
it's been a while, mods have updated and bugs have been fixed. There has been no response to the above comment. going to close this.
