### ISSUE TITLE
Two Elevator Contacts being powered simultaneously

### ISSUE THREAD

**Issue by AJ-P22** [Fabricators-of-Create/Create#1002]
### Describe the Bug

In an elevator built using the new Elevator Pulley and Elevator Contact blocks, the contact below the one the elevator is at is also activated. For example, if the elevator is at floor 7, the contact at floor 7 will produce a redstone signal as it should, but the contact at floor 6 will also produce a signal.

### Reproduction Steps

Place an elevator pulley above a superglued elevator cab, powered with a creative motor. Elevator contacts are placed in a single point on the X/Z axis, 4 blocks apart on the Y axis. When the elevator is moved to a different floor, either by powering a contact or by using Contraption Controls, all elevator contacts stop producing a signal, but when the elevator stops, the contact at its floor _and_ the contact at the floor below it will be producing power, and visibly illuminated.

### Expected Result

Only the elevator contact at the floor the elevator is at should be powered, no other ones.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/128918729/073cf2c4-0442-4f25-bcaf-45dbd810c695)

### Operating System

Windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

Accurate Block Placement, Ambient Sounds, Block Meter, Carpet Mod, Create, Create Track Map, Create Train Trapdoor Disabler, Create: Steam N Rails, Do A Barrel Roll, Extended Block Shapes, Immersive Aircraft, Indium, Jade, JEI, LambDynamicLights, LazyDFU, Light Emitting Diode, Lithium, Logicates, Mod Menu, Mouse Tweaks, Red Bits, Redstone Bits, Redstone Pen, Reese's Sodium Options, Replay Mod, Simple Chunkloader, Sodium, Sodium Extra, Sound Physics Remastered, Starlight, Supplementaries, Xaero's MiniMap/WorldMap, Zoomify, and _all necessary libraries/API's_

### Additional Context

The issue persists after logging out, restarting PC, disassembling and reassembling the elevator, or breaking and replacing all elevator-related blocks. The issue occurs with different elevators in different worlds. All elevator contacts stop producing a signal while the elevator is in motion, but when the elevator stops at a floor, both the current floor's contact and the contact of the floor below start producing a signal.

**Comment by AJ-P22** [comment]
I can confirm this issue exists on both 0.5.1b Patch 1 and Patch 2

**Comment by electricsteve** [comment]
It looks like it's an upstream issue

**Comment by TropheusJ** [comment]
This has been fixed in newer versions
