### ISSUE TITLE
Mechanical Crafter Recipes Not Appearing in REI

### ISSUE THREAD

**Issue by Zachattack525** [Fabricators-of-Create/Create#1003]
### Describe the Bug

As the name says, recipes aren't appearing in REI. Recipes do function, but they do not appear when requested

### Reproduction Steps

Try to view the recipe of an item that requires the use of a mechanical crafter or that can be made in a mechanical crafter.

### Expected Result

A tab in the recipe window for the mechanical crafter should appear.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/6627808/247f8684-b067-4ca5-ad64-6cec9bebb36c)

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Additional Context

I ran into this when trying to find the recipe for some items from Create Crafts and Additions. When no recipe appeared for relevant items, I went to check recipes for things like the crushing wheel and found that there was no tab for mechanical crafting.

**Comment by electricsteve** [comment]
Pls provide other mods you have installed

**Comment by xXNightsecretXx** [comment]
Again, Create recipes are only officaly available through JEI

**Comment by electricsteve** [comment]
and this doesn't look like rei

**Comment by electricsteve** [comment]
> Again, Create recipes are only officaly available through JEI

create fabric has darkmode support for rei, so you are part right. part wrong

**Comment by TropheusJ** [comment]
see #1616
