### ISSUE TITLE
Mechanical Pump not change its arrow when reverse the input direction

### ISSUE THREAD

**Issue by BlazeHunterVN1610** [Fabricators-of-Create/Create#1004]
### Describe the Bug

Before v0.5.1, when reverse the input rotational source direction using Gearshift or Rotational Speed Controller, the Mechanical Pump that connects to the rotational source will change its arrow direction. Flipping the pump using the wrench will have the same result.
But in v0.5.1, reversing the input source direction will not cause the Mechanical Pump to change its arrow direction, the only way to make the arrow direction rotated is using the wrench.
By the way, i'm using v0.5.1 patch 2

### Reproduction Steps

1. Connect the pump to any input source such as Creative Motor
2. Change the source direction

### Expected Result

The Mechanical Pump's arrow direction should be rotated when reversed input direction

### Screenshots and Videos

This is before v0.5.1:

https://github.com/Fabricators-of-Create/Create/assets/111768452/4204b7fe-1656-4a6f-96d0-8967e5bab1e5

This is after v0.5.1:

https://github.com/Fabricators-of-Create/Create/assets/111768452/9eb4b61b-08e2-43e5-b54a-522465e15539

### Operating System

Windows 11

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

![Screenshot (62)](https://github.com/Fabricators-of-Create/Create/assets/111768452/7479124a-7edc-4045-9ec7-f6504f41b71e)

**Comment by TropheusJ** [comment]
this is an intended feature
