### ISSUE TITLE
Achievement goal "Field Trip" doesn't work through the nether

### ISSUE THREAD

**Issue by othello777** [Fabricators-of-Create/Create#1005]
### Describe the Bug

just built a train track in the nether that goes 1k blocks and comes out in the overworld on both ends. the idea is that it goes over 5k blocks in the overworld, so the goal worded "leave a train seat over 5000 blocks away from where you started traveling" should be achieved right? for some reason I didnt get it. I'm guessing it's because I went through the nether, but that doesnt match the wording of the goal. I looked at the code (line [210 of AbstractContraptionEntity.java](https://github.com/Fabricators-of-Create/Create/blob/e37a012bc4ab3d98703c8f172b044f37fffa5402/src/main/java/com/simibubi/create/content/contraptions/AbstractContraptionEntity.java#L210)) and it seems like it should work. maybe the mounting is getting reset when changing dimensions? 

I think this should either be patched or the wording should be revised to fit the requirements. Thanks

### Reproduction Steps

1. create a 1.19.2 fabric server
2. build a nether pathway that is long enough that it comes out as 5k blocks apart in the overworld on both ends
3. travel it
4. no goal

### Expected Result

When you arrive at a destination that is over 5k blocks away from where you started in the same dimension as you started, you should get the goal. or the goal should specify you must remain in the same dimension (or be reworded in some other way)

### Operating System

Debian Test Linux (client) Debian Stable Linux (Server)

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

3dskinlayers-fabric-1.5.2-mc1.19.1.jar
ad_astra-fabric-1.19.2-1.12.6.jar
AdditionalStructures-1.19.x-(v.4.1.1).jar
amwplushies-fabric-1.19.2-2.0.13.jar
appleskin-fabric-mc1.19-2.4.1.jar
architectury-6.5.85-fabric.jar
artifacts-7.1.1+fabric.jar
Base Origins Tweaks 1.0.0 1.19.jar
BetterF3-4.0.0-Fabric-1.19.2.jar
BetterThirdPerson-Fabric-1.19-1.9.0.jar
Bookshelf-Fabric-1.19.2-16.3.20.jar
BotanyPots-Fabric-1.19.2-9.0.33.jar
BotanyTrees-Fabric-1.19.2-5.0.8.jar
botarium-fabric-1.19.2-1.8.2.jar
bwncr-fabric-1.19.2-3.14.1.jar
chat_heads-0.10.16-fabric-1.19.2.jar
cloth-config-8.2.88-fabric.jar
Clumps-fabric-1.19.2-9.0.0+14.jar
cobblemonbreakouts-fabric-1.0.4-1.19.2.jar
Cobblemon-fabric-1.3.2+1.19.2.jar
cobblemoninfo-fabric-1.19.2-1.0.2.jar
Cobblepedia-fabric-0.4.4+1.19.2.jar
collective-1.19.2-6.62.jar
configured-fabric-2.0.0-1.19.2.jar
continuity-2.0.2+1.19.jar
Controlling-fabric-1.19.2-10.0+7.jar
CorgiLib-fabric-1.19.2-1.0.0.34.jar
Create-Cobblemon-Fabric-v0.02.jar
create-fabric-0.5.1-b-build.1089+mc1.19.2.jar.disabled
digs_dnd_origins-1.19.2-0.0.8.jar
dragonloot-1.1.2.jar
duckling-2.0.8-fabric.jar
EasyAnvils-v4.0.11-1.19.2-Fabric.jar
Essential-fabric_1-19.jar
expandedstorage-8.3.4+1.19.2-fabric.jar
ExplorersCompass-1.19.2-2.2.0-fabric.jar
extraorigins-1.19-2.jar
fabric-api-0.76.0+1.19.2.jar
findme-3.1.0-fabric.jar
ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar
ftb-essentials-fabric-1902.3.3-build.100.jar
ftb-library-fabric-1902.3.19-build.214.jar
ftb-ultimine-fabric-1902.4.1-build.90.jar
geckolib-fabric-1.19-3.1.40.jar
go-fish-1.6.0-1.19.1.jar
immersive_aircraft-0.5.1+1.19.2-fabric.jar
immersive_paintings-0.6.1+1.19.2-fabric.jar
impaled-1.1.4.jar
Jade-1.19.1-fabric-8.7.3.jar
jamlib-0.6.0+1.19.jar
jei-1.19.2-fabric-11.6.0.1016.jar
journeymap-1.19.2-5.9.7-fabric.jar
JustEnoughResources-Fabric-1.19.2-1.2.2.200.jar
lambdynamiclights-2.2.0+1.19.2.jar
light-overlay-7.0.0.jar
lootr-1.19-0.4.27.67.jar
memoryleakfix-fabric-1.17+-1.0.0.jar
midnightlib-fabric-1.0.0.jar
MissingWilds-fabric-1.19-1.1.2.jar
moborigins-1.10.0.jar
modmenu-4.2.0-beta.2.jar
moonlight-1.19.2-2.2.43-fabric.jar
mostructures-1.4.3+1.19.2.jar
MouseTweaks-fabric-mc1.19-2.22.jar
Multi-Trident 1.19.2 v1.3.0.jar
musketmod-1.19.2-fabric-1.4.6.jar
NaturesCompass-1.19.2-2.1.0-fabric.jar
netherdepthsupgrade-fabric-3.0.0-1.19.2.jar
nicer-skies-1.2.0+1.19.2.jar
NoChatReports-FABRIC-1.19.2-v1.13.12.jar
Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.4.jar
Origins-1.19.2-1.7.1.jar
owo-lib-0.8.5+1.19.jar
Patchouli-1.19.2-77-FABRIC.jar
Pehkui-3.7.6+1.14.4-1.20.1.jar
polymorph-fabric-0.46.3+1.19.2.jar
PuzzlesLib-v4.4.3-1.19.2-Fabric.jar
repurposed_structures_fabric-6.3.24+1.19.2.jar
resourcefulconfig-fabric-1.19.2-1.0.20.jar
resourcefullib-fabric-1.19.2-1.1.24.jar
right-click-harvest-3.2.2+1.19.x-1.20.1-fabric.jar
show-me-your-skin-1.6.31.19.2.jar
SimpleBackpack_Fabric-1.19.2-1.3.25.jar
smallships-fabric-1.19.2-2.0.0-a2.3.jar
smoothboot-fabric-1.19-1.7.1.jar
starterkit-1.19.2-5.2.jar
supplementaries-1.19.2-2.3.20-fabric.jar
TerraBlender-fabric-1.19.2-2.0.1.136.jar
time-in-a-bottle-1.6.2+mc1.19-fabric.jar
toms_storage_fabric-1.19-1.5.8.jar
trade-cycling-fabric-1.19.2-1.0.5.jar
trinkets-3.4.2.jar
twilightforest-fabric-1.19.2-4.2.357.jar
[Universal]Immersive Structures-2.0.7a.jar
vcinteraction-1.19.2-1.0.3.jar
voicechat-fabric-1.19.2-2.4.13.jar
WhereAreMyTMs-1.0.2.jar
wondrouswilds-1.19.2-1.1.6.jar
wraith-waystones-3.0.8+mc1.19.2.jar
yosbr-0.1.2.jar
youre-in-grave-danger-1.4.9.jar

### Additional Context

Prism Launcher 7.1 (client)
fabric server: `fabric-server-mc.1.19.2-loader.0.14.21-launcher.0.11.2.jar`

**Comment by James103** [comment]
If you were to build a train track 5,100+ blocks long on the Nether roof, connect it to a track in the Overworld at one end and get on a train at the other end, does the advancement complete as soon as you leave the Nether while riding the train, or does it complete once you get off the train in the Overworld?

**Comment by IThundxr** [comment]
```java
		Vec3 prevPosition = VecHelper.readNBT(data.getList("ContraptionMountLocation", Tag.TAG_DOUBLE));
		data.remove("ContraptionMountLocation");
		if (entityLiving instanceof Player player && !prevPosition.closerThan(position, 5000))
			AllAdvancements.LONG_TRAVEL.awardTo(player);
```

The advancement only checks for the players position, in this case across dimensions it will not match up, If you mount the train in the overworld, travel through the nether and then come back outside in the overworld and dismount it'll work fine
