### ISSUE TITLE
version 1.20.1 is not compatible with Sodium,and render errors in vanilla render

### ISSUE THREAD

**Issue by htrskmiku** [Fabricators-of-Create/Create#1007]
### Describe the Bug

1.in Fabric,Create 1.20.1 is not compatible with Sodium,crash report: https://pastebin.com/N9PbzQy7
2.in "vanilla" renderer(Fabric loader with Create and Fabric API),there're lots of black lines away from players,and many blocks in create can't be rendered in a right way(textures are invisible)

### Reproduction Steps

1.clone and build 1.20.1 branch
2.add mod to Minecraft
3.create or join a world
...

### Expected Result

Create works well with Sodium
Every block and blockentity can be seen
No black lines away from players

### Crash Report or Log

Sodium crash:https://pastebin.com/N9PbzQy7

### Operating System

Windows 11

### Mod Version

0.5.1c

### Minecraft Version

1.20.1

**Comment by Jvluoyeah** [comment]
yea ,thanks for your issue/ww

**Comment by TropheusJ** [comment]
you need indium with sodium
