### ISSUE TITLE
Shaders cause problem with waterwheels

### ISSUE THREAD

**Issue by HollowCompanion** [Fabricators-of-Create/Create#1008]
### Describe the Bug

When looking in the direct of a water wheel, moving or not, iris with complementary shaders will significantly decrease frame rate

### Reproduction Steps

1. Turn shader on
2. Place multiple water wheels

### Expected Result

Not extra lag

### Operating System

Windows 11

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
shaders disable flywheel's optimizations. nothing we can do.

**Comment by Type-32** [comment]
You can try using the Flywheel Compat mod as a potential solution: https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat
This mod force enables the flywheel optimization so using shaderpacks would still have the optimizations on.
