### ISSUE TITLE
Cogwheel+Shaft Models Doubled Up

### ISSUE THREAD

**Issue by soup587** [Fabricators-of-Create/Create#101]
### Describe the Bug

Using the latest release of Sodium (0.4.0 Alpha6 Build 14) alongside the latest artifact of Refabricated renders the models of cogwheels, large cogwheels and shafts two times, once in their 'correct' rotation and a second time in a fullbright at a default rotation.

### Reproduction Steps

1. Load the latest Sodium release and Create Refabricated together
2. Place down cogwheel/shaft

### Expected Result

Models render correctly

### Screenshots and Videos

![2022-01-22_20 38 14](https://user-images.githubusercontent.com/41347805/150654773-e6ebacd2-1ca3-4495-95a2-ee3122b39a9e.png)

### Crash Report or Log

https://pastebin.com/HBffrKnT

### Operating System

Windows 11

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

Fabric API

**Comment by soup587** [comment]
Update: Interestingly, the models render as normal if Indium is installed.

**Comment by AlphaMode** [comment]
Duplicate of #54
