### ISSUE TITLE
1.20.1 : Local build : Super glue : Cant serialize unregistered packet

### ISSUE THREAD

**Issue by zaped212** [Fabricators-of-Create/Create#1010]
### Describe the Bug

Using super glue for a 1.20.1 build causes a serialization issue and ends up "soft banning" users as they cannot log back in due to the serialization issue.

### Reproduction Steps

1. Build 1.20.1 from tips of 1.20.1/fabric/dev ( last tested at ad0aadfccfb6e650d857f022c6a0093862efed29 )
2. Have no other mods installed besides fabric
3. Generate new world
4. Login, give the use superglue and glue any two blocks together
5. Experience Serialization issue
...

### Expected Result

Glue should behave properly and players are not kicked due to serialization issues.

### Crash Report or Log

https://pastebin.com/zj4F3TmY

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

[08:31:59] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
[08:32:00] [main/INFO]: Loading 76 mods:
        - create 0.5.1-c-local+mc1.20.1
           |-- com_electronwill_night-config_core 3.6.3
           |-- com_electronwill_night-config_toml 3.6.3
           |-- com_google_code_findbugs_jsr305 3.0.2
           |-- flywheel 0.6.9-1
           |-- forgeconfigapiport 8.0.0
           |-- milk 1.2.60
           |    \-- dripstone_fluid_lib 3.0.2
           |-- porting_lib_accessors 2.1.1073+1.20
           |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
           |    |-- porting_lib_core 2.1.1073+1.20
           |    \-- porting_lib_gametest 2.1.1073+1.20
           |-- porting_lib_base 2.1.1073+1.20
           |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
           |    |-- mm_shedaniel 2.4.1
           |    |-- porting_lib_attributes 2.1.1073+1.20
           |    |-- porting_lib_common 2.1.1073+1.20
           |    |-- porting_lib_core 2.1.1073+1.20
           |    |-- porting_lib_gametest 2.1.1073+1.20
           |    |-- porting_lib_lazy_registration 2.1.1073+1.20
           |    \-- porting_lib_utility 2.1.1073+1.20
           |-- porting_lib_brewing 2.1.1073+1.20
           |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
           |    |-- porting_lib_core 2.1.1073+1.20
           |    \-- porting_lib_gametest 2.1.1073+1.20
           |-- porting_lib_client_events 2.1.1073+1.20
           |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
           |    |-- mm 2.3
           |    |-- porting_lib_core 2.1.1073+1.20
           |    \-- porting_lib_gametest 2.1.1073+1.20
           |-- porting_lib_entity 2.1.1073+1.20
           |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
           |    |-- porting_lib_core 2.1.1073+1.20
           |    \-- porting_lib_gametest 2.1.1073+1.20
           |-- porting_lib_extensions 2.1.1073+1.20
           |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
           |    |-- porting_lib_attributes 2.1.1073+1.20
           |    |-- porting_lib_common 2.1.1073+1.20
           |    |-- porting_lib_core 2.1.1073+1.20
           |    \-- porting_lib_gametest 2.1.1073+1.20
           |-- porting_lib_fake_players 2.1.1073+1.20
           |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
           |    |-- porting_lib_core 2.1.1073+1.20
           |    \-- porting_lib_gametest 2.1.1073+1.20
           |-- porting_lib_models 2.1.1073+1.20
           |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
           |    |-- porting_lib_core 2.1.1073+1.20
           |    |-- porting_lib_gametest 2.1.1073+1.20
           |    \-- porting_lib_model_loader 2.1.1073+1.20
           |-- porting_lib_networking 2.1.1073+1.20
           |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
           |    |-- porting_lib_core 2.1.1073+1.20
           |    \-- porting_lib_gametest 2.1.1073+1.20
           |-- porting_lib_obj_loader 2.1.1073+1.20
           |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
           |    |-- porting_lib_attributes 2.1.1073+1.20
           |    |-- porting_lib_common 2.1.1073+1.20
           |    |-- porting_lib_core 2.1.1073+1.20
           |    |-- porting_lib_gametest 2.1.1073+1.20
           |    \-- porting_lib_model_loader 2.1.1073+1.20
           |-- porting_lib_tags 3.0
           |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
           |    |-- porting_lib_core 2.1.1073+1.20
           |    \-- porting_lib_gametest 2.1.1073+1.20
           |-- porting_lib_tool_actions 2.1.1073+1.20
           |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
           |    |-- porting_lib_core 2.1.1073+1.20
           |    \-- porting_lib_gametest 2.1.1073+1.20
           |-- porting_lib_transfer 2.1.1073+1.20
           |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
           |    |-- porting_lib_core 2.1.1073+1.20
           |    \-- porting_lib_gametest 2.1.1073+1.20
           |-- reach-entity-attributes 2.4.0
           \-- registrate-fabric 1.3.61-MC1.20
                |-- porting_lib_data 2.1.1021+1.20
                \-- porting_lib_model_generators 2.1.1021+1.20
                     \-- porting_lib_model_materials 2.1.1021+1.20
        - fabric-api 0.86.0+1.20.1
           |-- fabric-api-base 0.4.30+7abfd51577
           |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
           |-- fabric-biome-api-v1 13.0.10+b3afc78b77
           |-- fabric-block-api-v1 1.0.9+e022e5d177
           |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
           |-- fabric-client-tags-api-v1 1.1.1+97bb207577
           |-- fabric-command-api-v1 1.2.33+f71b366f77
           |-- fabric-command-api-v2 2.2.12+b3afc78b77
           |-- fabric-commands-v0 0.2.50+df3654b377
           |-- fabric-containers-v0 0.1.62+df3654b377
           |-- fabric-content-registries-v0 4.0.9+b3afc78b77
           |-- fabric-convention-tags-v1 1.5.4+a1a980da77
           |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
           |-- fabric-data-generation-api-v1 12.2.0+6c31357e77
           |-- fabric-dimensions-v1 2.1.52+b3afc78b77
           |-- fabric-entity-events-v1 1.5.22+b3afc78b77
           |-- fabric-events-interaction-v0 0.6.1+e91849a877
           |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
           |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
           |-- fabric-item-api-v1 2.1.27+b3afc78b77
           |-- fabric-item-group-api-v1 4.0.9+132c48c177
           |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
           |-- fabric-keybindings-v0 0.2.34+df3654b377
           |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
           |-- fabric-loot-api-v2 1.1.39+b3afc78b77
           |-- fabric-loot-tables-v1 1.1.43+9e7660c677
           |-- fabric-message-api-v1 5.1.7+3265161977
           |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
           |-- fabric-model-loading-api-v1 1.0.1+9386d8a777
           |-- fabric-models-v0 0.4.0+9386d8a777
           |-- fabric-networking-api-v1 1.3.9+b3afc78b77
           |-- fabric-networking-v0 0.3.49+df3654b377
           |-- fabric-object-builder-api-v1 11.1.1+6beca84877
           |-- fabric-particles-v1 1.1.1+201a23a077
           |-- fabric-recipe-api-v1 1.0.19+b3afc78b77
           |-- fabric-registry-sync-v0 2.3.0+2e061fd477
           |-- fabric-renderer-api-v1 3.1.1+9386d8a777
           |-- fabric-renderer-indigo 1.4.1+9172968c77
           |-- fabric-renderer-registries-v1 3.2.45+df3654b377
           |-- fabric-rendering-data-attachment-v1 0.3.34+b3afc78b77
           |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
           |-- fabric-rendering-v0 1.1.48+df3654b377
           |-- fabric-rendering-v1 3.0.7+b3afc78b77
           |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
           |-- fabric-resource-loader-v0 0.11.9+132c48c177
           |-- fabric-screen-api-v1 2.0.7+b3afc78b77
           |-- fabric-screen-handler-api-v1 1.3.28+b3afc78b77
           |-- fabric-sound-api-v1 1.0.12+b3afc78b77
           |-- fabric-transfer-api-v1 3.3.0+cdf060b277
           \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
        - fabricloader 0.14.21
        - java 19
        - minecraft 1.20.1

**Comment by TropheusJ** [comment]
already fixed
