### ISSUE TITLE
Create 0.5.1-b Game did not initialize

### ISSUE THREAD

**Issue by FatalityWar** [Fabricators-of-Create/Create#1015]
### Describe the Bug

After clicking Start the game quickly appears the error prompt. 
Modpack with 340 mods.

### Reproduction Steps

1. I clicked to start
2. Error prompt
3. Log error.
...

### Expected Result

Game should be started

### Crash Report or Log

https://gist.github.com/FatalityWar/f26a7c8c5a39fd53d9ac55c55b0adf54

### Operating System

windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.19.2

### Other Mods

- additionalstructures 4.1.1
	- advdebug 2.3.0
	- adventurez 1.4.18
	- alternate-current 1.5.0
	- animatica 0.5+1.19
	- another_furniture 2.1.2-1.19.2
	- architects_palette 3.0.0
	- architectury 6.5.85
	- artifacts 7.1.1+fabric
	   |-- expandability 6.0.0
	   \-- step-height-entity-attribute 1.0.0
	- attributefix 17.2.6
	- awesomedungeon 3.2.0
	- awesomedungeonend 3.1.1
	- awesomedungeonnether 3.1.1
	- awesomedungeonocean 3.2.0
	- backslot 1.2.11
	   \-- amecsapi 1.3.6+mc22w17a
	- backslotaddon 1.0.10
	- badpackets 0.2.1
	- balm-fabric 4.5.7
	- barteringstation 4.0.3
	- bcc 2.0.2-build.16+mc1.19.1
	- bclib 2.1.6
	- beekeeperhut 1.2.0
	- betteradvancements 0.2.2.147
	- betterdeserttemples 1.19.2-Fabric-2.2.2
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.19.2-Fabric-3.2.1
	- betterend 2.1.5
	- betterfortresses 1.19.2-Fabric-1.0.5
	- betterfpsdist 1.19-2.4
	- bettermineshafts 1.19.2-Fabric-3.2.0
	- bettermounthud 1.2.0
	- betternether 7.1.3
	- betteroceanmonuments 1.19.2-Fabric-2.1.0
	- betterstats 2.7.2+1.19.2
	   \-- tcdcommons 2.7+1.19.2
	- betterstrongholds 1.19.2-Fabric-3.2.0
	- bettertridents 4.0.2
	- bettervillage 3.0.0
	- betterwitchhuts 1.19.2-Fabric-2.1.0
	- bhmenu 1.19.2-2.3.1
	- biomemakeover 1.19.2-1.6.4
	- blur 2.6.0
	- boatbreakfix 1.0.11
	- boatiview 0.0.4
	- bobby 4.0.1
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- bookshelf 16.3.20
	- bosses_of_mass_destruction 1.4.6-1.19.2
	   |-- maelstrom_library 1.3-1.19-pre1
	   \-- multipart_entities 1.2-1.19-pre1
	- bountiful 3.0.0
	- brutalbosses 1.19.2-6.4
	- byg 2.0.1.1
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- bygonenether 1.2.2
	- cardinal-components 5.0.2
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   |-- cardinal-components-item 5.0.2
	   |-- cardinal-components-level 5.0.2
	   |-- cardinal-components-scoreboard 5.0.2
	   \-- cardinal-components-world 5.0.2
	- carryon 2.0.5.11
	- cem 0.7.3-1.19
	   |-- completeconfig-base 2.2.0
	   \-- completeconfig-gui-cloth 2.2.0
	- charm 4.4.4
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- charmofundying 6.2.0+1.19.2
	- charmonium 4.2.1
	- chat_heads 0.10.14
	- chefsdelight 1.0.3-fabric-1.19.2
	   \-- structurized-reborn 1.19-01
	- cherishedworlds 6.0.1+1.19.2
	- chunksending 1.19-2.5
	- chunksfadein 3.0.11-1.19
	- citresewn 1.1.2+1.19.2
	   \-- citresewn-defaults 1.1.2+1.19.2
	- cleancut 1.19.2-5.1-fabric
	- cloth-api 4.0.65
	   |-- cloth-basic-math 0.6.1
	   |-- cloth-client-events-v0 4.0.65
	   |-- cloth-common-events-v1 4.0.65
	   |-- cloth-scissors-api-v1 4.0.65
	   \-- cloth-utils-v1 4.0.65
	- cloth-config 8.2.88
	   \-- cloth-basic-math 0.6.1
	- clumps 9.0.0+14
	- collective 6.65
	- colormatic 3.1.2+mc.1.19
	- comforts 6.0.4+1.19.2
	   \-- spectrelib 0.12.4+1.19.2
	- configured 2.0.0
	- connectivity 1.19.2-4.2
	- continuity 2.0.2+1.19
	- controlling 10.0+7
	- corgilib 1.0.0.34
	- cosmetic-armor 1.4.2
	- cpm 0.6.8a
	- crafttweaker 10.1.48
	   \-- org_javassist_javassist 3.29.0-GA
	- crawl 0.11.1
	   \-- mm 2.3
	- create 0.5.1-b-build.1089+mc1.19.2
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.8.a-5
	   |-- forge_tags 3.0
	   |-- milk 1.0.51
	   |    \-- dripstone_fluid_lib 2.0.1
	   |-- porting_lib_accessors 2.1.1038+1.19.2
	   |-- porting_lib_base 2.1.1038+1.19.2
	   |    |-- mm 2.3
	   |    |-- porting_lib_attributes 2.1.1038+1.19.2
	   |    |-- porting_lib_common 2.1.1038+1.19.2
	   |    |-- porting_lib_constants 2.1.1038+1.19.2
	   |    |-- porting_lib_lazy_registration 2.1.1038+1.19.2
	   |    |-- porting_lib_loot 2.1.1038+1.19.2
	   |    |-- porting_lib_model_generators 2.1.1038+1.19.2
	   |    |-- porting_lib_model_loader 2.1.1038+1.19.2
	   |    \-- porting_lib_models 2.1.1038+1.19.2
	   |-- porting_lib_entity 2.1.1038+1.19.2
	   |    \-- porting_lib_constants 2.1.1038+1.19.2
	   |-- porting_lib_extensions 2.1.1038+1.19.2
	   |    |-- porting_lib_attributes 2.1.1038+1.19.2
	   |    |-- porting_lib_common 2.1.1038+1.19.2
	   |    \-- porting_lib_constants 2.1.1038+1.19.2
	   |-- porting_lib_fake_players 2.1.1038+1.19.2
	   |-- porting_lib_networking 2.1.1038+1.19.2
	   |-- porting_lib_obj_loader 2.1.1038+1.19.2
	   |    |-- porting_lib_attributes 2.1.1038+1.19.2
	   |    |-- porting_lib_common 2.1.1038+1.19.2
	   |    |-- porting_lib_constants 2.1.1038+1.19.2
	   |    \-- porting_lib_model_loader 2.1.1038+1.19.2
	   |-- porting_lib_transfer 2.1.1038+1.19.2
	   |    |-- porting_lib_attributes 2.1.1038+1.19.2
	   |    |-- porting_lib_common 2.1.1038+1.19.2
	   |    \-- porting_lib_constants 2.1.1038+1.19.2
	   |-- reach-entity-attributes 2.3.0
	   \-- registrate-fabric 1.1.58-MC1.19.2
	- creativecore 2.9.3
	- creeperoverhaul 2.0.9
	- culturaldelights 0.14.9+1.19.2
	   \-- terraform-wood-api-v1 4.2.0
	- darkbindings 1.3.0
	- darkpaintings 13.1.5
	- dawn 3.5.0
	- debugify 2.8.0
	- decorative_blocks 3.0.0
	- deeperdarker 1.1.6
	   |-- customportalapi 0.0.1-beta54-1.19
	   \-- paragon 3.0.2
	        \-- org_yaml_snakeyaml 1.27
	- deepslatecutting 1.5.0
	- deuf_refabricated 1.0.0
	- diagonalfences 4.2.5
	- dragonfight 1.19.2-2.8
	- dragonloot 1.1.2
	- drippyloadingscreen 2.2.1
	- duckling 2.0.8
	- dungeon_difficulty 2.0.3+1.19
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- dungeons_andtaverns_mr 2.0.2
	- dungeons_arise 2.1.55
	- easyanvils 4.0.11
	- easymagic 4.3.3
	- ecologics 2.1.11
	- edenring 0.6.4
	- eldritch_mobs 1.13.1
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   |-- polymer 0.2.18+1.19.2
	   |    |-- packet_tweaker 0.3.0+1.18.2
	   |    \-- polymer-registry-sync-manipulator 0.0.3+1.19.2
	   |-- polymer-blocks-ext 0.1.0-alpha.9+1.19.2
	   \-- server_translations_api 1.4.18+1.19.2
	        \-- packet_tweaker 0.3.0+1.18.2
	- elytraslot 6.1.1+1.19.2
	- emotecraft 2.2.7-b.build.48
	   |-- bendy-lib 2.1.3-test2
	   \-- player-animator 1.0.2
	- enchantwithmob 1.19.2+1.1.0
	- enchdesc 13.0.14
	- endportalrecipe 5.0
	- endrem 5.2.0
	- entity_texture_features 4.4.4
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entitycollisionfpsfix 2.0.0.0
	- entityculling 1.6.1-mc1.19.2
	- equipmentcompare 1.3.1
	- everycomp 1.19.2-2.4.8
	- expandeddelight 0.2.5.2
	- explorify-fabric 1.19-1.3.0
	- extrasounds 2.3.1+1.19.2-1.19.1
	   |-- advanced_runtime_resource_pack 0.6.2
	   \-- soundcategories 1.2.4+1.19
	- fabric-api 0.76.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.41+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.8+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.11+10eb22f490
	   |-- fabric-networking-v0 0.3.28+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.1+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.32+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.21
	- fabricshieldlib 1.6.1-1.19
	   \-- mm 2.3
	- fabrishot 1.9.2
	- fallingtree 3.10.0
	- fancymenu 2.14.7
	- farmersdelight 1.19.2-1.3.9
	- farmersknives 2.4
	- farmersrespite 2.2.4
	- ferritecore 5.0.3
	- forgeconfigapiport 4.2.11
	- frame 0.26.1+1.19-fabric
	   |-- frame-api-base 0.2.1+906ebc04a9
	   |-- frame-blocks-v0 0.1.3+233e7428a9
	   |-- frame-config-v0 0.3.1+0fa45150a9
	   |-- frame-content-registries-v0 0.4.0+2876b511a9
	   |-- frame-enchantments-v0 0.1.0+4093105da9
	   |    \-- mm 2.3
	   |-- frame-game-rules-v0 0.2.4+e7ce56a6a9
	   |-- frame-items-v0 0.1.3+906ebc04a9
	   |-- frame-loot-tables-v0 0.1.4+4f7341eca9
	   |-- frame-registries-v0 0.1.1+0e0ec74ea9
	   |-- frame-rendering-v0 0.1.5+906ebc04a9
	   |-- frame-tabbed-item-groups-v0 0.2.4+0aca9b56a9
	   |-- frame-toymaker-v0 0.6.1+b13741c3a9
	   \-- frame-woods-v0 0.2.1+6a33fbada9
	- friendsandfoes 1.8.2
	- frostiful 0.5.4
	   \-- mm 2.3
	- ftblibrary 1902.3.19-build.214
	- ftbquests 1902.4.16-build.235
	   \-- team_reborn_energy 2.2.0
	- ftbteams 1902.2.13-build.100
	- fusion 1.0.3
	- fwaystones 3.0.7+mc1.19.2
	- galosphere 1.19.2-1.2.2
	- geckolib3 3.1.40
	   \-- com_eliotlash_mclib_mclib 20
	- geodes 1.7+1.19
	- geophilic 1.19-2.0.0b
	- giantspawn 4.6
	- go-fish 1.6.0-1.19.1
	- goblintraders 1.8.1
	- goodall 1.2.0
	- graveyard 2.3.3
	- graveyard_biomes 1.6
	- guardvillagers 1.19.2-1.1.2
	- handcrafted 2.0.6
	- highlighter 1.1.4
	- hopobetterunderwaterruins 1.1.1
	- huskspawn 3.3
	- iceberg 1.0.46
	- illuminations 1.10.11
	- immediatelyfast 1.1.12
	   \-- net_lenni0451_reflect 1.1.0
	- immersive_armors 1.5.5+1.19.2
	- immersive_weathering 1.19.2-1.2.9
	- incendium 5.1.6
	- indium 1.0.9+mc1.19.2
	- ingredient-extension-api 3.0.6
	- inmis 2.7.1-1.19
	- inmisaddon 1.0.4
	- inventoryhud 3.4.7
	- iris 1.6.1
	   |-- io_github_douira_glsl-transformer 2.0.0-pre12
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- itemfilters 1902.2.9-build.51
	- itemmodelfix 1.0.3+1.19
	- itemphysic 1.6.6
	- jade 8.7.3
	- jamlib 0.6.0+1.19
	- java 18
	- kambrik 4.0-1.19.2
	- kiwi 8.3.3
	- kleeslabs 12.3.0
	- konkrete 1.6.1
	- krypton 0.2.1
	   \-- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT
	- lambdabettergrass 1.3.0+1.19
	- lambdynlights 2.2.0+1.19.2
	   |-- pride 1.1.2+1.19
	   \-- spruceui 4.1.0+1.19.2
	- languagereload 1.5.6+1.19.2
	- lazydfu 0.1.3
	- leavesbegone 4.0.1
	- letmedespawn fabric-1.0.2
	- libraryferret 4.0.0
	- lithium 0.11.1
	- logbegone 1.0.6
	- lootintegrations 1.19.3-3.1
	- lootr 0.4.26.65
	- magnumtorch 4.2.2
	- meadow 1.1.1
	   \-- terraform-wood-api-v1 4.2.0
	- memoryleakfix 1.0.0
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.6
	- midnightlib 1.0.0
	- mindfuldarkness 4.0.8
	- minecells 1.5.2
	- minecraft 1.19.2
	- mineralchance 3.2
	- mixintrace 1.1.1+1.17
	- mobscarecrow 2.2.1-1.19.1
	- mobz 3.3.5
	- modernfix 3.6.0
	- modmenu 4.2.0-beta.2
	- modpack-update-checker 0.5.1
	- moonlight 1.19.2-2.2.34
	- more_babies 1.0.0
	- moreculling 1.19.1-0.17.0
	   \-- conditional-mixin 0.3.0
	- mousetweaks 2.22
	- mru 0.1.5+1.19.2
	   \-- com_sksamuel_scrimage_scrimage-core 4.0.31
	- mythicmounts 1.19.2-7.2
	- naturalist 3.0.3a
	- naturallychargedcreepers 3.2
	- naturescompass 1.19.2-2.1.0-fabric
	- netherchested 4.0.4
	- netherdepthsupgrade fabric-3.0.0-1.19.2
	- netherportalfix 10.0.1
	- nethersdelight 1.0.1
	   \-- disable_custom_worlds_advice 3.0
	- new_crafting_recipes 1.0.0
	- nicer-skies 1.2.0
	- nightconfigfixes 4.0.7
	- nochatreports 1.19.2-v1.13.12
	- noenchantcap 2.2.4
	- nofade 1.18-2.0.1
	- notenoughanimations 1.6.2
	- nullscape 1.2.1
	- oceansdelight 1.0.0
	- onsoulfire 1.19-2
	- openpartiesandclaims 0.17.3
	- overflowingbars 4.0.1
	- owo 0.9.3+1.19
	   \-- blue_endless_jankson 1.2.1
	- oxidized 1.7.2
	- packetpray 1.0-SNAPSHOT
	- paintings 10.2.4.0
	- paradise_lost 2.1.0-beta+1.19.2
	   |-- customportalapi 0.0.1-beta54-1.19
	   |-- gud_recipe_confidence 1.0.2
	   |-- incubus_core 1.9.4
	   \-- reach-entity-attributes 2.3.0
	- patchouli 1.19.2-77-FABRIC
	   \-- fiber 0.23.0-2
	- paxi 1.19.2-Fabric-3.0.1
	- philipsruins 1.19.2
	- pickupnotifier 4.2.4
	- ping-wheel 1.3.0
	- plushies 1.2
	- polymorph 0.46.1+1.19.2
	- presencefootsteps 1.6.4
	   \-- kirin 1.11.1
	- probablychests 0.5.5-1.19.2
	- projectile_damage 3.2.1+1.19
	- promenade 2.7.1
	- publicguiannouncement 4.3.3
	- puzzle 1.4.2-1.19
	   |-- puzzle-base 1.4.2-1.19
	   |-- puzzle-gui 1.4.2-1.19
	   |-- puzzle-models 1.4.2-1.19
	   \-- puzzle-splashscreen 1.4.2-1.19
	- puzzleslib 4.4.0
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cardinal-components-world 5.0.2
	- quartzelv 2.1.5+1.19
	- reacharound 1.1.2
	- rebind_narrator 2.0.0
	- rechiseled 1.1.2
	- reeses-sodium-options 1.4.9+mc1.19.2-build.67
	- repurposed_structures 6.3.24+1.19.2
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.6
	- resourcefulconfig 1.0.20
	- resourcefullib 1.1.24
	- resourcepackoverrides 4.0.4
	- revive 1.0.5
	- rhino 1902.2.2-build.268
	- rightclickharvest 3.2.0+1.19.x
	- rottencreatures 1.0.1
	   \-- reach-entity-attributes 2.3.0
	- roughly_enough_loot_tables 1.19-1.0
	- roughly_enough_trades 1.19-1.0
	- roughlyenoughitems 9.1.610
	   \-- error_notifier 1.0.9
	- roughlyenoughprofessions 1.1.4
	- roughlyenoughresources 2.6.0
	- satin 1.9.0
	- sdrp 3.0.4-build.27+mc1.19.2
	- serverbrowser 1.1.0
	- skeletalremains 1.3.3
	   \-- omega-config 1.3.0+1.19.2
	- skeletonhorsespawn 3.6
	- smarterfarmers 1.19.2-1.7.2
	- smoothchunk 1.19.1-2.0
	- snowrealmagic 5.1.1
	- snowundertrees 1.0.0+1.19.2
	- snowyspirit 1.19.2-2.1.10
	- sod 23.5.28
	- sodium 0.4.4+build.18
	   \-- org_joml_joml 1.10.4
	- sodium-extra 0.4.16+mc1.19.2-build.90
	   \-- caffeineconfig 1.0.0+1.17
	- soulsweapons 0.9.9.3
	- sound_physics_remastered 1.19.2-1.0.18
	- spark 1.10.37
	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
	- spiderstpo 1.19.2-2.0.3
	- spirit 2.2.6
	- stackdeobfuscator 1.3.2+fabric.4bca927
	   \-- net_fabricmc_mapping-io 0.3.0
	- starlight 1.1.1+fabric.ae22326
	- starterkit 5.2
	- stoneworks 4.0.1
	- strawgolem 2.0.0-beta.5
	- strayspawn 3.3
	- structory 1.0.1
	- structory_towers 1.0.2
	- structureessentials 1.19.2-2.8
	- supermartijn642configlib 1.1.7
	- supermartijn642corelib 1.1.12
	- supplementaries 1.19.2-2.3.14a
	- t_and_t 1.10
	- takesapillage 1.0.4
	- terrablender 2.0.1.136
	- terrestria 5.0.9
	   |-- terraform-biome-remapper-api-v1 4.2.0
	   |-- terraform-config-api-v1 4.2.0
	   |-- terraform-dirt-api-v1 4.2.0
	   |-- terraform-shapes-api-v1 4.2.0
	   |-- terraform-surfaces-api-v1 4.2.0
	   |-- terraform-tree-api-v1 4.2.0
	   |-- terraform-wood-api-v1 4.2.0
	   |-- terrestria-client 5.0.9
	   |-- terrestria-common 5.0.9
	   \-- terrestria-worldgen 5.0.9
	- the_bumblezone 6.7.20+1.19.2
	   \-- fake-player-api 0.5.0
	- thermoo 1.4
	- thonkutil 2.15.4+1.19
	   |-- thonkutil-base 1.13.2+4a8c408a57
	   |-- thonkutil-capes-v1 1.4.2+3eb2749857
	   |-- thonkutil-coords-v1 1.1.2+8ff533c957
	   |-- thonkutil-customization-v1 1.1.2+8ff533c957
	   |-- thonkutil-legacy 1.1.2+5d4263f557
	   |-- thonkutil-modchecker-v1 1.1.3+bd4b387957
	   |-- thonkutil-potions-v0 1.5.2+8ff533c957
	   |-- thonkutil-titlescreen-v1 1.2.2+8ff533c957
	   \-- thonkutil-trades-v1 1.2.2+8ff533c957
	- tipsmod 8.0.27
	- tlc 1.0.0
	- toms_storage 1.5.6
	- toolstats 12.0.2
	- trade_cycling 1.19.2-1.0.5
	- tradingpost 4.2.0
	- transparent 5.1.2
	- transparent_cosmetics 1.5.1+1.19
	- trashslot 12.0.2
	- travelersbackpack 1.19.2-8.2.23
	   \-- reach-entity-attributes 2.3.0
	- travelerstitles 1.19.2-Fabric-3.1.0
	- trinkets 3.4.2
	- twigs 3.0.0
	- twilightforest 4.2.357
	   |-- here-be-no-dragons 1.0.0
	   |-- javax_annotation_javax_annotation-api 1.3.2
	   |-- mm 2.3
	   |-- porting_lib 2.1.727+1.19.2
	   |    \-- serialization_hooks 0.3.26
	   \-- reach-entity-attributes 2.3.0
	- ultris_mr 5.6.7f
	- universal_ores 1.4.2
	- unsafe-world-random-access-detector 1.1.0
	- variantcraftingtables 3.3.2
	- varietyaquatic 1.0.4.2
	- vc_gliders 1.0.2
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- palladiumcore 1.19.2-1.2.3.4
	- veinmining 1.1.1+1.19.2
	- villagernames 4.5.1
	   |-- cardinal-components-base 5.0.2
	   \-- cardinal-components-level 5.0.2
	- villagersplus 1.9
	- vinery 1.2.11
	   \-- doapi 1.0.4
	        \-- terraform-wood-api-v1 4.2.0
	- visuality 0.5.6
	- visualworkbench 4.2.4
	- voidtotem 2.1.0
	- voidz 1.0.9
	- wildlife 1.19.2-2.2
	- windchimes 1.2.1
	- winterly 0.8.3
	   \-- cardinal-components-world 5.0.2
	- wolfarmorcompat 1.0.2-1.19.2
	- wolveswitharmor 1.8.0-1.19
	   |-- maybe-data 1.3.2-1.19-rc2
	   \-- static-content 1.0.1-1.16.2
	        \-- staticdata 1.1.2
	- wondrouswilds 1.19.2-1.1.6
	- woof 4.0.1-1.19.2
	- xaerominimap 23.4.4
	- xaeroworldmap 1.30.3
	- xlpackets 1.19.2-4
	- xp_storage 1.4.3+1.19
	- xp_storage_trinkets 0.1+1.19
	- yet-another-config-lib 2.2.0-for-1.19.2
	- yigd 1.4.9
	- yosbr 0.1.1
	- ysns 1.0.3
	- yungsapi 1.19.2-Fabric-3.8.9
	- yungsbridges 1.19.2-Fabric-3.1.0
	- yungsextras 1.19.2-Fabric-3.1.0
	- zombiehorsespawn 4.6
	- zoomify 2.9.0
	   |-- dev_isxander_settxi_settxi-core 2.10.5
	   |-- dev_isxander_settxi_settxi-gui 2.10.5
	   |-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.5
	   \-- settxi-gui-yacl 2.10.5

**Comment by electricsteve** [comment]
probably a problem on everycompat's side

**Comment by TropheusJ** [comment]
update it or remove it
