### ISSUE TITLE
Disappearing Contraptions

### ISSUE THREAD

**Issue by MCAlexisYT** [Fabricators-of-Create/Create#1017]
### Describe the Bug

I tried to move a mass of blocks higher up with a mechanical piston, only for the whole contraption to disappear and then turn back into blocks.
One thing that might be causing this issue is that I raised the max amount of blocks on an individual contraption to a 5-digit number, causing weird stuff to happen.

### Reproduction Steps

1. Download the Fabric 1.19.2 version of all the mods listed in the "Other Mods" section, including Fabric API and Create 0.5.1b patch 2 to in order to get the results that I got
2. Start the game
3. Load or create a new world
4. Raise the maximum amount of blocks on a contraption to an absurd amount
5. Make a huge cube of blocks (preferably using WorldEdit)
6. Put a Mechanical Piston on top or bottom
7. Super Glue the side on which you have your Mechanical Piston
8. Place a Creative Motor or any other power source in the right spot (otherwise nothing will happen*)
*other than if you flip the rotation of the motor/power source when its in the wrong spot

### Expected Result

The contraptions looks like blocks moving, a bit like falling sand, except with collision detection.

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/78766083/eb6db3f1-5851-44a4-a870-1beae3d9232c

### Operating System

Windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

3D Skin Layers
Accurate Block Placement
Architectury API (Makes it easier to make multi-platform mods)
Charm (Quark-inspired mod adding features that can be individually enabled and/or disabled to get the experience that you'd like)
Chipped (Adds way, **WAY** more variants of certain vanilla blocks than you can shake a stick at)
Cloth Config API (Config API mod)
Continuity (Connected Textures in Optifine/MCPatcher format)
Create Crafts & Additions
Create Enchantment Idustry Fabric
Decorative Blocks
Emoji Type (Apparently makes it easier to type-in emojis... Maybe they meant that it adds emojis to the game?)
Fabric API
Fabric Language Kotlin
FabricSkyboxes
FancyMenu (In-game GUI customization mod)
Indium (Fabric Rendering API Compatibility layer for Sodium
Iris Shaders (Optifine Shader compatibility for Sodium)
Konkrete (library mod for FancyMenu and a few others)
LambDynamicLights
Macaw's Fences and Walls
Macaw's Lights and Lamps
Mod Menu
No Chat Reports
No Resource Pack Warnings (Literally disables the "this pack may not work correctly" message)
OptiGUI (Modified GUIs in Optifine/MCPatcher format)
Puzzle (Unified config for Optifine alternatives
Raised (Raises the hotbar by 1 in-game pixel, as it depends on GUI scale)
Reeses's Sodium Options (Alternative options menu for Sodium)
Resourceful Lib (Just another library, I don't know for what)
Roughly Enough Items (JEI alternative)
Sodium (Performance-enhancing mod)
Sodium Extra (Adds some of Optifine's eye-candy features along with some other stuff)
Trinkets (Data-driven accessory mod)
WTHIT (Shows what block/entity you're looking at, and that's it.)
WorldEdit
WorldEdit Items (Adds items whose purpose is to separate vanilla items with ones that work with WorldEdit)
bad packets (Allows packet messaging between different modding platforms)
lazy-language-loader (Makes it so that when you change the game's language, it only changes the language and not all of the game's resources)

### Additional Context

I was trying to recreate a computer called the "PowerMac G4 Cube", and realized that the scale of the coloured glass apple logo recreation relative to the rest of the build was way out of wack, which is why I tried moving that mass of smooth quartz blocks in the first place.

**Comment by TropheusJ** [comment]
this just looks like lag, which is pretty normal for a huge contraption
