### ISSUE TITLE
Train station flags do not disappear when destroyed

### ISSUE THREAD

**Issue by DangerZon3** [Fabricators-of-Create/Create#1018]
### Describe the Bug

When you make a new bogey with a train station and destroy the station(preferably with a wrench), it will leave behind its flag.

![Train Station Error](https://github.com/Fabricators-of-Create/Create/assets/140682841/62fc418b-711a-4256-8747-9d6732fe66ba)

Also, the train track highlighted to show here a bogey can be made leaves behind the mark even when the track is destroyed.

![Train Track Error](https://github.com/Fabricators-of-Create/Create/assets/140682841/29c0c08f-98bf-4d01-8b01-5980580905fd)

### Reproduction Steps

First bug:

1. Make a train station.
2. Open its interface, and select "Create new Train."
3. Use a wrench to destroy the train station.

Second bug:
1. First follow steps 1 - 2 in the first bug.
2. Instead of destroying the station, destroy the train track.

### Expected Result

The flag/train track mark disappears.

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Appleskin
Better Fabric Drawers
Elitia (Create addon)
Farmers Delight
Immersive Portals
JEI
Macaw Bridges

**Comment by TropheusJ** [comment]
can't reproduce. does it happen with newer versions or with just Create?

**Comment by IThundxr** [comment]
Open a new issue if this still occurs ~ cannot reproduce myself either
