### ISSUE TITLE
Game crash when I have opened chest

### ISSUE THREAD

**Issue by benio1394** [Fabricators-of-Create/Create#1019]
### Describe the Bug

Game crash when I have opened chest generated in world from lootr

### Reproduction Steps

1. Open any chest generated in the world

### Expected Result

Game crashes

### Crash Report or Log

https://pastebin.com/jwimTyBr

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.19.2

### Other Mods

List of mod is in the crash log

**Comment by TropheusJ** [comment]
Text Utilities is built for an older version of Create
