### ISSUE TITLE
Saws destroy non-solid blocks (saplings)

### ISSUE THREAD

**Issue by Vedemin** [Fabricators-of-Create/Create#102]
### Describe the Bug

When in use the saws destroy non-solid blocks (saplings) despite the fact they shouldn't (like in Forge version).

### Reproduction Steps

1. Place sapling
2. Place saw either stationary or on a contraption
3. Turn on the saw/contraption
4. Sapling is destroyed

### Expected Result

Sapling is untouched by the saw

This video presents the expected result:
https://www.youtube.com/watch?v=quXInFl2Koc

### Operating System

Windows 10

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
do you have terralith installed?

**Comment by Vedemin** [comment]
I do indeed, do you think this might be the cause of the issue? Didn't
cross my mind in the slightest

niedz., 23 sty 2022 o 02:59 TropheusJ ***@***.***> napisał(a):

**Comment by TropheusJ** [comment]
[Inherited from upstream](https://github.com/Creators-of-Create/Create/issues/2636)
