### ISSUE TITLE
Create 0.5.1 on branch mc1.19/fabric/dev - Latest source code cannot build, cardinal-components dependency is broken.

### ISSUE THREAD

**Issue by Kaloyan501** [Fabricators-of-Create/Create#1020]
### Describe the Bug

When trying to build the latest source code in the mc1.19/fabric/dev branch using ./gradlew build, it gives an error about unable to download ```cardinal-components-entity-5.0.2.pom``` and ```cardinal-components-base-5.0.2.rom```. Right now the build.gradle script is trying to download them from ladysnake.jfrog.io/artifactory/mods, but when you open this page in a web browser, it says that ```JFrog's Free-Tier subscription has been deactivated.```. As stated in issue #966 , the source code is vital to actually running the mod right now, as the .jars on the Curseforge website are broken. Thankfully, I have .jar files from a previous version of the source code from the mc1.19/fabric/dev branch and I can use the mod, but many people may not. If someone has a workaround for this issue, please post it here, because this issue and issue #966 need to be fixed ASAP, because they break the experiance for many people.

### Reproduction Steps

1.Download the latest source code from the mc1.19/fabric/dev branch.
2.Open it in IntelliJ IDEA (I don't know if it's specific to IDEA or not)
3.Wait for the project to import.
4.Try to build using ./gradlew build
5.Error :(

### Expected Result

Building fine and actually creating the .jar files instead of erroring out.

### Operating System

Windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

The bug is in the build process, so except the dependecy mods, nothing else was used.

**Comment by Kaloyan501** [comment]
UPDATE: For anyone wondering, I found the issue with the jars on the Curseforge website. As stated in issue #993 , just update Fabric API. But the problem with the code not compiling still persists and needs to be fixed.

**Comment by electricsteve** [comment]
![image](https://github.com/Fabricators-of-Create/Create/assets/96793824/fb1a1baf-99e4-40c3-b4dc-281b126277c3)
Indeed, it even states it on the github.
![image](https://github.com/Fabricators-of-Create/Create/assets/96793824/9abb7772-be1b-4b73-81a8-a917fe5ae37d)
Just update it in the build.gradle, it's an easy fix. Currently have bad internet so someone else can maybe do it?

**Comment by TropheusJ** [comment]
was fixed
