### ISSUE TITLE
Lambdynamiclights and Create handheld torch bug

### ISSUE THREAD

**Issue by LittleManDiscord** [Fabricators-of-Create/Create#1021]
### Describe the Bug

Using Lambdynamiclights and Create makes it so chests and other similar objects like bells have buggy lighting. They no longer respond to the dynamic lights and can appear pitch black in dark areas even when a light is near them.

### Reproduction Steps

1. Install lambdynamiclights
2. Install Create

### Expected Result

Chests, bells, and other objects don't react correctly to handheld lights

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/124035152/924145b8-064d-4557-aa7a-8e250987e419)

### Operating System

Windows 11

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

Lambdynamiclights

**Comment by electricsteve** [comment]
does it also happen when you dont have a texture pack on?

**Comment by LittleManDiscord** [comment]
Hello, and yes, it does. I have no texture packs relating to chests specifically.

**Comment by TropheusJ** [comment]
is it fixed if you remove Create

**Comment by TropheusJ** [comment]
actually this is because the chest is rendered by Flywheel. flywheel instances are not affected by dynamic lighting.

**Comment by TropheusJ** [comment]
https://github.com/Jozufozu/Flywheel/issues/120
