### ISSUE TITLE
please 

### ISSUE THREAD

**Issue by hackingrulessodobipeople** [Fabricators-of-Create/Create#1022]
### Describe the Suggestion

update to 1.20

### Screenshots and Videos

just do it bro

### Additional Context

bro please

**Comment by hackingrulessodobipeople** [comment]
he's got a point

**Comment by xllifi** [comment]
@hackingrulessodobipeople download [latest development build](https://github.com/Fabricators-of-Create/Create/actions/runs/5684883554)
