### ISSUE TITLE
Crash when opening canon GUI (and sometimes happens with notebooks)

### ISSUE THREAD

**Issue by antoni0C0des** [Fabricators-of-Create/Create#1023]
### Describe the Bug

Sometimes when you attempt to open the canon GUI or a notebook, Minecraft crashes.

### Reproduction Steps

1. Play for a while in a server 
2. Open a notebook or the canon
You can try to open and close many times the UI until it happens 

### Expected Result

Excepted result shouldn't be a crash 

### Crash Report or Log

https://mclo.gs/LDcsuWG

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.19.2

### Other Mods

You can check the mods in the log since used mods always get logged.

### Additional Context

We are using crafts and additions addon and steam n rails addon if that's helpful

**Comment by TropheusJ** [comment]
vanilla bug, fixed by [this](https://modrinth.com/mod/bugjump)
