### ISSUE TITLE
The mechanical arm cannot deposit or extract items from an andesite funnel or a brass funnel.

### ISSUE THREAD

**Issue by PinhaCosmica** [Fabricators-of-Create/Create#1026]
### Describe the Bug

The mechanical arm cannot deposit or extract items from an andesite funnel or a brass funnel.
Regarding the associated entries, it shows that they can be linked to these; if it is not an error, and it was an intentional change, it should be removed from the guide as it causes confusion.
Version: 0.5.1.b Patch 2

### Reproduction Steps

1.Right-click on the andesite funnel or the brass funnel.
2.
3.
...

### Expected Result

I would like the error to be fixed in an upcoming bug fix update.

### Screenshots and Videos

![imagen_2023-07-31_214845832](https://github.com/Fabricators-of-Create/Create/assets/141098424/03721ce3-9416-45ef-b386-69832727c7ee)

### Operating System

windows 11

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
working fine for me.
they can only insert, and can only insert to inward-facing funnels.
![image](https://github.com/Fabricators-of-Create/Create/assets/60247969/0bbe71f7-d654-4cef-86a7-6a3ce94e268a)
