### ISSUE TITLE
Wrong fluid amounts in mixer, REI, with two fluid ingredients

### ISSUE THREAD

**Issue by Abalieno** [Fabricators-of-Create/Create#1030]
### Describe the Bug

I'll report here because I was told REI's plugin is still Create-fabric responsibility.

The recipe is being shown correctly in EMI, but not in REI. I'm not even entirely sure if it's maybe a limit of Create.

Setting a mixer recipe with kubejs, adding two different fluid ingredients with different amounts, the amount of the FIRST fluid seems to override the second, and the fluid output.

So for example I had 250mB water and 1000mB of a custom fluid as ingredients, with an output also at 1000mB.

The tooltip for that recipe in REI would show all these three slots being 250mB.

What's even more weird is that the icon of the fluid is filled accordingly to its amount, so if the ingredient is at 500 it shows the icon half filled, and so on. In this case the two slots that are 1000mB in my recipe show correctly a filled icon in REI, BUT they show 250mB in the tooltip.

That means that for some reason REI reads the amount correctly, but then shows it wrong in the tooltip.

### Reproduction Steps

Kubejs recipe

### Expected Result

Correct fluid amounts shown.

### Operating System

Windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
see #1616
