### ISSUE TITLE
(1.20.1) Incompatible with continuity

### ISSUE THREAD

**Issue by Syclusion** [Fabricators-of-Create/Create#1031]
### Describe the Bug

When activating a resource pack with ctm support, or continuity integrated it errors out and fails to apply.

### Reproduction Steps

1.Install create, sodium, indium, and continuity.
2.Activate continuity / ctm resource pack and error out

...

### Expected Result

Not fail when applying resource pack

### Crash Report or Log

https://pastebin.com/7Jreg4vL

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Sodium, continuity, indium, fabric api

**Comment by TropheusJ** [comment]
should be fixed
