### ISSUE TITLE
Bricking worlds with waterwheels 

### ISSUE THREAD

**Issue by Choolemal** [Fabricators-of-Create/Create#1033]
### Describe the Bug

I built the 1.20.1 version on my own from the GitHub in VScode so I understand this version is still being worked on but just something to look at. You can brick a world with a water wheel by placing it in a world.

### Reproduction Steps

1. Create a world
2. Place a water wheel
3. Game crashes

### Expected Result

Game saves then forcefully quits, even after relogging, exiting with code 1

### Screenshots and Videos

[Refer to the Additional content for it being listed 0.5.1c instead of D](https://imgur.com/a/Tf6wh5E)

### Crash Report or Log

https://pastebin.com/nSJCFQEZ

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.20.1

### Other Mods

N/A other than the C418 music resource pack.

### Additional Context

I believe it to be the 0.5.1c version due to the files name even though it is listed under 0.5.1d. the .jar file is [here](https://drive.google.com/file/d/19Ql8sM6Sggdy9JT3a8SZR-uRS1apg1vp/view) it is understandable if you dont want do download it.

**Comment by TropheusJ** [comment]
was already fixed
