### ISSUE TITLE
Crash with dashloader

### ISSUE THREAD

**Issue by AxionQc** [Fabricators-of-Create/Create#1034]
### Describe the Bug

Crash with all 1.20 versions

### Reproduction Steps

1.Launch
2.crash

### Expected Result

Game should load

### Crash Report or Log

https://mclo.gs/5Tykw5l

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Dashloader

### Additional Context

Nothing

**Comment by TropheusJ** [comment]
Create is not mentioned at all and this looks like it's purely dashloader's issue
