### ISSUE TITLE
[1.20.1] creating train contraption with starlight installed causes crash

### ISSUE THREAD

**Issue by ianm1647** [Fabricators-of-Create/Create#1041]
### Describe the Bug

as the title says, creating a train with starlight installed causes a crash. the crash does not happen without starlight. whenever starlight is readded AFTER the contraption is formed , the game still crashes. i haven't tested this with other contraptions yet but i will edit this post if i do run into problems with other contraptions

### Reproduction Steps

1. install starlight along with create
2. create a train , and assemble it in train station
3. CRASH!

### Expected Result

a working train contraption

### Crash Report or Log

https://pastebin.com/hsHADBrs

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Sodium, Lithium, and Indium (and Fabric API of course)

**Comment by Eklip5e** [comment]
i don't even know how did you get the 1.20.1 version

**Comment by IThundxr** [comment]
Fixed in patch f (next release)
