### ISSUE TITLE
Overlays do not render properly

### ISSUE THREAD

**Issue by MistGo** [Fabricators-of-Create/Create#1042]
### Describe the Bug

When I aim at some blocks like windmill bearing, creative motor, mechanical piston, brass funnel, etc, their interface doesn't appear. In old 1130 build it's perfectly works.

### Reproduction Steps

1. Aim at windmill bearing/creative motor/mechanical piston
2. Interface appears for a few milliseconds

### Expected Result

Interface appearance

### Screenshots and Videos

https://youtu.be/8Ei-KeUDqOU

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

iris-flywheel-compat-1.20.1-0.2.1
clientcommands-2.8.3
create-fabric-0.5.1-d-build.1134+mc1.20.1
indium-1.0.21+mc1.20.1
iris-mc1.20-1.6.4
sodium-fabric-mc1.20-0.4.10+build.27
litematica-fabric-1.20.1-0.15.3
malilib-fabric-1.20.1-0.16.1
Xaeros_Minimap_23.6.0_Fabric_1.20
XaerosWorldMap_1.31.0_Fabric_1.20
fabric-api-0.86.1+1.20.1
advancementinfo-1.20-fabric0.83.0-1.4
continuity-3.0.0-beta.3+1.20.1
jei-1.20.1-fabric-15.2.0.23
shulkerboxtooltip-fabric-4.0.4+1.20.1
modmenu-7.2.1
fabric-language-kotlin-1.10.8+kotlin.1.9.0
yet-another-config-lib-fabric-3.1.0+1.20
Zoomify-2.11.0

**Comment by TropheusJ** [comment]
The hud hasn’t changed since 1130. Try without other mods.

**Comment by MistGo** [comment]
I tried without other mods (I left only create 1134, fabric api 0.86.1 and JEI 15.2.0.23), nothing has changed. Also I reinstall create.

**Comment by TropheusJ** [comment]
fixed in latest commit
