### ISSUE TITLE
Crash that might be caused by create (or an addon of create?) (Uncertain source)

### ISSUE THREAD

**Issue by antoni0C0des** [Fabricators-of-Create/Create#1047]
### Describe the Bug

Minecraft client from a player will often crash. We do not know what could be the source but it points to create

### Reproduction Steps

Unsure how to replicate ..

### Expected Result

Expected results should be no crashes 

### Crash Report or Log

https://mclo.gs/LsR7LBC

### Operating System

Windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

All mods are listed on the log but we use crafts and additions and steam n rails. 

### Additional Context

I assume the player has contraptions near him

**Comment by antoni0C0des** [comment]
Although the logs are also reporting errors from Connectivity or poliymer, the creator of polymer told me that their mod was not a cause of the crash

**Comment by antoni0C0des** [comment]
As context, this was their explication https://github.com/Patbox/polymer/issues/83#issuecomment-1671325482

**Comment by antoni0C0des** [comment]
https://mclo.gs/y5Pck6G it also happened again, it seems to be the same message btw

**Comment by antoni0C0des** [comment]
This one happened after breaking a windmill piece btw

**Comment by TropheusJ** [comment]
this should be fixed in the next update: https://github.com/Jozufozu/Flywheel/issues/181

**Comment by antoni0C0des** [comment]
So, the next create update might fix this? Yay 

When is it coming out if I may ask?
