### ISSUE TITLE
[1.20.1] Parts of all create items disappear when using iris mod

### ISSUE THREAD

**Issue by holydam** [Fabricators-of-Create/Create#1051]
### Describe the Bug

My package only used iris and sodium, fabric api, and the latest build1143 create of 1.20.1. After entering the world, when entering another dimension or leaving these items, you will find that some of them are invisible when you come back .If you break them and place them again, they will return to their original state, but they will still become invisible when you come back after leaving

### Reproduction Steps

1.Download the latest build 1143, sodium, iris
2.Create a new world, place a create item, such as a baler
3.Exit the world or go to another dimension and back
...

### Expected Result

i thought it could be normal .

### Screenshots and Videos

![微信图片_20230811005126](https://github.com/Fabricators-of-Create/Create/assets/101784515/d1e99a02-c5af-4daa-9cfe-94d34900b352)
![微信图片_20230811005131](https://github.com/Fabricators-of-Create/Create/assets/101784515/a4d538c5-11f4-4bfd-8751-abf9812dd0b9)

### Operating System

Window11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
#1039
