### ISSUE TITLE
Visual Workbench breaks rendering of some items

### ISSUE THREAD

**Issue by EmpressAutumn** [Fabricators-of-Create/Create#1052]
### Describe the Bug

I decided to download the most recent build artifact so I could test it out in 1.20.1, but when I opened the creative inventory, many of Create's components were not rendered. I placed down a few, notably the water wheel and some curved and diagonal train tracks, and they were invisible when placed in the world. After more testing, the components functioned properly but remained unrendered.

### Reproduction Steps

1. Download the latest build artifact: https://github.com/Fabricators-of-Create/Create/suites/14996952850/artifacts/855904306
2. Place the mod into the mods folder
3. Launch Fabric 1.20.1
4. Open a creative mode world
5. Open the creative inventory and look at the Create tab

### Expected Result

All items in the Create tab should be rendered properly, and they should also render when I place them on the ground.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/61087185/751f47ff-f132-4b90-b901-3a52c9072cf6)

### Operating System

Windows 10

### Mod Version

0.5.1-d-build.1144

### Minecraft Version

1.20.1

### Other Mods

Ad Astra
Ambient Sounds
Architectury API
Auto Third Person
Better Advancements
Better Third Person
Boosted Brightness
Botarium
Camera Overhaul
Camera Utilities
Fabric Capes
Cloth Config
Continuity
Creative Core
Disable Custom Worlds Advice
Dynamic Crosshair
Eating Animation
Enhanced Visuals
Entity Model Features
Entity Texture Features
Essential
Fabric API
Fabric Language Kotlin
Forge Config API Port
Iceberg
Legendary Tooltips
Litematica
Make Bubbles Pop
Malilib
Modmenu
No Chat Reports
Not Enough Animations
Player Animations Library
Presence Footsteps
Prism
Puzzles Lib
Resourceful Config
Resourceful Lib
Roughly Enough Items
Sound Physics
Time and Wind
Vanilla Refresh
Visuality
Visual Workbench

**Comment by EmpressAutumn** [comment]
After some testing this morning, I narrowed the problem down to an incompatibility between Create and Visual Workbench: https://www.curseforge.com/minecraft/mc-mods/visual-workbench

Visual Workbench and its dependency Puzzles Lib alter the way blocks are rendered, rendering the items used in crafting recipes, so I can see why this causes Create's rendering to not function.

**Comment by PepperCode1** [comment]
This issue may be caused by Puzzles Lib reimplementing and using the Forge model events on Fabric. It should be using the model events provided by the new Fabric Model Loading API v1 instead as they have better compatibility.

**Comment by EmpressAutumn** [comment]
I'll post an issue on Puzzles Lib mentioning this. Thank you!

**Comment by Eklip5e** [comment]
Hey! I think we both fixed this issue, there's a new version of Puzzles Lib's that doesn't give this problem anymore!

**Comment by IThundxr** [comment]
Does this still occur?

**Comment by IThundxr** [comment]
It's been a little over 2 weeks with no response so im gonna assume this doesn't occur anymore. In the event it does please open a new issue.
