### ISSUE TITLE
Vehicle Fix causes cart contraptions to stop when they hit something

### ISSUE THREAD

**Issue by chudders1231** [Fabricators-of-Create/Create#1053]
### Describe the Bug

Cart contraptions seem to stop if the front of the contraption's hitbox meets an entity / block.
The hitbox is particularly large which, i am new to create, seems to be overly large. This stops 99% of cart contraptions from doing it's job. The cart contraption stops, and is unable to be pushed until the "obstacle" is removed from its path

### Reproduction Steps

1. Create minecart contraption with blocks in a line from left to right.
2. Add some blocks / entities in its path
3. Enable hitboxes in the debug menu
4. Set the cart contraption off

### Expected Result

Cart contraptions are unaffected by mobs / entities and contraptions move right up to the block for drills and break blocks as expected.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/6697509/d7de50c7-1711-44ca-b76e-2ee1f2092cbb)
![image](https://github.com/Fabricators-of-Create/Create/assets/6697509/ee0cdcd3-b977-4096-870c-1ee582415301)
![image](https://github.com/Fabricators-of-Create/Create/assets/6697509/8d5e73b1-d489-4a75-98bb-9ad9bcbf20db)

### Operating System

Windows 11

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
need your mod list

**Comment by chudders1231** [comment]
I found out the mod, its [Vehicle Fix](https://github.com/CammiePone/VehicleFix/issues/2). Someone raised an issue on the mod github, and the author's response was to make a datapack to fix it.

Idk if there is something that can be done on your end, but yeah...

**Comment by electricsteve** [comment]
This is easily fixable, could fix it and make a pr when im home

**Comment by ChickenDestroyer** [comment]
Any kind of update on this?

**Comment by electricsteve** [comment]
Oops.... forgot, im gonna sleep now but maybe im gonna do it tomorrow

**Comment by ChickenDestroyer** [comment]
Any progress update?

**Comment by electricsteve** [comment]
So, I tried fixing this on the mods side, but the thing is create pretends the create contraption is a minecart, so it doesn't work. I currently don't know how to get if the minecart really is a minecart or a create contraption.

**Comment by IThundxr** [comment]
Should be fixed by Vehicle Fix
