### ISSUE TITLE
IndexOutOfBoundExceptions after updating to create 0.5.1/fabric

### ISSUE THREAD

**Issue by joernott** [Fabricators-of-Create/Create#1055]
### Describe the Bug

Since we updated our modpack for a private server, we encounter quite a lot of crashes, e.g. when looking at create items in REI. 

### Reproduction Steps

1. Use our modpack (https://modrinth.com/modpack/explorerflotte-create/version/0.1.3)
2. Start a local world with it
3. Open REI and filter "@create", then move the mouse over some items

...

### Expected Result

The game should continue to work

### Crash Report or Log

https://gist.github.com/joernott/4a3b38c17a2b284bf8c8ef1137dee6e8

### Operating System

Windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

  [✔️] advancementinfo-1.19.1-fabric0.58.5-1.3.1.jar
  [✔️] AE2WTLib-12.9.5.jar
  [✔️] appliedenergistics2-fabric-12.9.6.jar
  [✔️] architectury-6.5.85-fabric.jar
  [✔️] BetterAdvancements-Fabric-1.19.2-0.2.2.147.jar
  [✔️] BetterF3-4.0.0-Fabric-1.19.2.jar
  [❌] bobby-4.0.1.jar.disabled (disabled)
  [❌] camerautils-1.19.2-1.0.3.jar.disabled (disabled)
  [✔️] cardinal-components-api-5.0.2.jar
  [✔️] carryon-fabric-1.19.2-2.1.0.20.jar
  [✔️] chisel-1.4.7+1.19.2.jar
  [✔️] cloth-config-8.3.103-fabric.jar
  [❌] Controlling-fabric-1.19.2-10.0+7.jar.disabled (disabled)
  [✔️] CorgiLib-fabric-1.19.2-1.0.0.34.jar
  [✔️] CraftTweaker-fabric-1.19.2-10.1.48.jar
  [✔️] create-fabric-0.5.1-b-build.1089+mc1.19.2.jar
  [✔️] extremesoundmuffler-3.37-fabric-1.19.2.jar
  [✔️] fabric-api-0.76.0+1.19.2.jar
  [✔️] fabric-carpet-1.19.2-1.4.84+v221018.jar
  [✔️] FauxCustomEntityData-fabric-1.19.2-2.0.2.jar
  [❌] freecam-modrinth-1.1.6+1.19.jar.disabled (disabled)
  [✔️] geckolib-fabric-1.19-3.1.40.jar
  [✔️] gravestones-v1.13.jar
  [✔️] handcrafted-fabric-1.19.2-2.0.6.jar
  [✔️] immersive-portals-2.3.2-mc1.19.2-fabric.jar
  [✔️] indium-1.0.9+mc1.19.2.jar
  [✔️] IngredientExtensionAPI-fabric-1.19.2-3.0.6.jar
  [✔️] litematica-fabric-1.19.2-0.12.7.jar
  [✔️] lithium-fabric-mc1.19.2-0.11.1.jar
  [✔️] malilib-fabric-1.19.2-0.13.0.jar
  [✔️] merequester-fabric-1.19.2-1.1.3.jar
  [✔️] minecraft-comes-alive-7.5.5+1.19.2-universal.jar
  [✔️] modmenu-4.2.0-beta.2.jar
  [✔️] Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.4.jar
  [✔️] owo-lib-0.9.3+1.19.jar
  [✔️] Philips-Ruins1.19.2-7.2[Fabric].jar
  [✔️] phosphor-fabric-mc1.19.x-0.8.1.jar
  [✔️] resourcefullib-fabric-1.19.2-1.1.24.jar
  [✔️] RoughlyEnoughItems-9.1.643.jar
  [❌] shifty-hotbar-mc1.19-1.1.jar.disabled (disabled)
  [✔️] sodium-fabric-mc1.19.2-0.4.4+build.18.jar
  [✔️] supermartijn642corelib-1.1.12-fabric-mc1.19.2.jar
  [✔️] TerraBlender-fabric-1.19.2-2.0.1.166.jar
  [✔️] theoneprobe-fabric-1.19-6.2.2.jar
  [✔️] trashcans-1.0.18-fabric-mc1.19.2.jar
  [✔️] travelers-backpack-1.19.2-8.2.26.jar
  [✔️] trinkets-3.4.2.jar
  [✔️] wraith-waystones-3.0.8+mc1.19.2.jar
  [✔️] Xaeros_Minimap_23.6.1_Fabric_1.19.1.jar
  [✔️] XaerosWorldMap_1.32.0_Fabric_1.19.1.jar

### Additional Context

We are running on fabric and the crash reports all contain
```
	at com.simibubi.create.content.equipment.goggles.GoggleOverlayRenderer.renderOverlay(GoggleOverlayRenderer.java:162)
	at com.simibubi.create.CreateClient.lambda$registerOverlays$4(CreateClient.java:132)
	at io.github.fabricators_of_create.porting_lib.event.client.OverlayRenderCallback.lambda$static$0(OverlayRenderCallback.java:17)
	at net.minecraft.class_329.handler$zfp000$porting_lib_base$port_lib$renderCrosshair(class_329.java:2031)
```
which makes me guess, that we have something conflicting with the Goggles

**Comment by TropheusJ** [comment]
vanilla bug, [this](https://modrinth.com/mod/bugjump) fixes it

**Comment by joernott** [comment]
Thank you @TropheusJ, That was a fast response and it fixes our problems!
