### ISSUE TITLE
[1.20.1] Rogue Deployer returns

### ISSUE THREAD

**Issue by Aquaeyes** [Fabricators-of-Create/Create#1056]
### Describe the Bug

Like in #1013, but with different reproduction steps. 'a rogue deployer' replaces the player name in advancements.

I saw some other reports and the version below, but if I was incorrect in posting this issue before release I apologise!

### Reproduction Steps

1. Get advancement for mining stone with wooden pickaxe, is player name.
2. Place deployer in the world.
3. Craft stone pickaxe, is now attributed to the deployer.
...

### Expected Result

The player's advancement would be attributed to them.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/10935410/578c1416-4a6d-4584-8513-0c9f39a298ff)

### Operating System

MacOS 13.1 (22C65)

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Architectury 9.1.12
QSL 7.1.1+0.86.1-1.20.1

### Additional Context

This is *after* the fix for the prior bug was merged into 1.20.1, from what I can tell, so I'm assuming this is a different one.

**Comment by TropheusJ** [comment]
the fix has not been merged into 1.20 yet

**Comment by TropheusJ** [comment]
and now it has
