### ISSUE TITLE
gearbox is non-sticky (like glazed terracotta)

### ISSUE THREAD

**Issue by drwoops** [Fabricators-of-Create/Create#1057]
### Describe the Bug

is it intended that gearboxes can be pushed by sticky mechanical pistons but not pulled?

### Reproduction Steps

pretty obvious from the above

### Expected Result

i dont know which is why i am asking

### Operating System

Linux

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
intended, matches forge
