### ISSUE TITLE
Piston does not allow retract after placed block

### ISSUE THREAD

**Issue by extract** [Fabricators-of-Create/Create#1058]
### Describe the Bug

Hi,

**NOTE: This is in Minecraft 1.20.1 using the dev branch (commit id: 74f86936 ...) build and not any official release.**

I have a small example set up in a creative world with only Create and Fabric API. No other mods.

![Example of contraption](https://github.com/Fabricators-of-Create/Create/assets/4999714/b596e91a-9225-4368-93e4-ce67a44c531b)

This mechanical piston does extend but once it reaches a limit it "solidifies" the pushed block and the piston breaks. It refuses to go back or further forth.
Rebuilding the piston or adding another piston extender and extending the piston further temporarily makes it work until it collides with another block.

### Reproduction Steps

1. Build the contraption seen in the image.
2. Extend piston until it's at the max or it collides.
3. Piston is broken

### Expected Result

After saw is done cutting I want to be able to retract the piston again.

### Operating System

Arch Linux

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Fabric API
Create

**Comment by UQuark** [comment]
Hi! I use commit d9c630d8ca6429f515ff5541d6b358f76bab2984 and I can reproduce the issue.
Further experiments show that a piston with only one extension pole works, but 2+ extension poles cause the bug to appear.
![image](https://github.com/Fabricators-of-Create/Create/assets/20577158/97f1efb0-c0d7-4567-a812-6995c9f07c4f)

I managed to unlock the piston by adding one extension pole, pushing it forward and then pulling it back before it stops.

**Comment by UQuark** [comment]
After a brief debugging I found this state:
![image](https://github.com/Fabricators-of-Create/Create/assets/20577158/84721ca1-0b19-49b1-94e2-61c7cc0239e0)
It seems that extension pole somehow passes isBrittle check
After debugging further, I found that block movement checks are not registered:
![image](https://github.com/Fabricators-of-Create/Create/assets/20577158/6548b7b3-346e-4fb6-9ae7-69248af01ba0)
I'm not sure where exactly I should register them, further investigation needed

**Comment by UQuark** [comment]
After further investigation I found out that PistonContraption's `initialExtensionProgress` (int) field behaves weird:
- `writeNBT` is called only in the start of the movement, not in the end
- for some reason `initialExtensionProgress` resets to zero after full extension (still no clue how)
