### ISSUE TITLE
1.20.1 issues do not get a version tag

### ISSUE THREAD

**Issue by drwoops** [Fabricators-of-Create/Create#1059]
### Describe the Bug

... and i am making a guess here: but as a consequence, they also are never forwarded to the #github channel.
@simibubi

### Reproduction Steps

obviously make a 1.20.1 issue

### Expected Result

the issue and all comment are forwarded to the #github channel on discord.

### Operating System

Linux

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by warior456** [comment]
because 1.20.1 is not released

**Comment by TropheusJ** [comment]
report to the forge repo too

**Comment by Losi25** [comment]
Same Issue, I made a Report for 1.20.1 (0.5.1) and the bot added the 1.19 tag.
Maybe because I mentioned 1.19.2 ? (Issue relates to updating)

**Comment by TropheusJ** [comment]
Issues that occur on Forge as well are no longer being tracked on this repo, so it is being closed.

Forge does not have an issue open for this as far as I know, and one shouldn't be opened. The issue templates are being redone, and there will not be version tags anymore.
