### ISSUE TITLE
issues with toolbox 1.18

### ISSUE THREAD

**Issue by Noplace0** [Fabricators-of-Create/Create#106]
### Describe the Bug

When I Right-clicked the toolbox, the container interface did not show up. 
Not sure what problem this is.

From wiki/ in-game:
When R-clicked
Opens the Container Interface.

### Reproduction Steps

1. Place a toolbox
2. Rename it or do not rename it
3. Right-click the toolbox
4. No interface showing up
...

### Expected Result

I expected I can see something like this
![image](https://user-images.githubusercontent.com/30548562/150738442-785fae7d-d120-4ec2-8fd9-410d93d3f8f4.png)

But in-game I after r-clicked, nothing happens, but the toolbox animation part is opened 
![image](https://user-images.githubusercontent.com/30548562/150738649-d74359f7-ff6f-4a32-bf4c-5d714b131987.png)

### Operating System

Win 10

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

Better Minecraft 1.8.1 fabric version 11

**Comment by TropheusJ** [comment]
Disable shaders and try again.

**Comment by Noplace0** [comment]
> Disable shaders and try again.

nothing changed

**Comment by AeiouEnigma** [comment]
This is an incompatibility issue with Inventory Sorter. I've PR'd a fix to them.

**Comment by TropheusJ** [comment]
this is out of our hands now - closing.
