### ISSUE TITLE
[1.20.1]Conflict between Create and Hephaestus causing server startup failure

### ISSUE THREAD

**Issue by windy664** [Fabricators-of-Create/Create#1061]
### Describe the Bug

When both Create and Hephaestus mods are present, the server fails to start due to a NoClassDefFoundError. Specifically, Hephaestus seems to be looking for a class from the Create mod (io/github/fabricators_of_create/porting_lib/entity/events/LivingEntityEvents) which it cannot find, causing the server to crash.

### Reproduction Steps

1. Install both Create (version 0.5.1d) and Hephaestus (version 1.20.1-3.6.3.222) on a Fabric server.
2. Attempt to start the server.
3. Observe the crash during the server startup process.

### Expected Result

The server should start successfully with both mods without any conflicts or crashes.

### Crash Report or Log

[latest.log](https://github.com/Fabricators-of-Create/Create/files/12385245/latest.log)

### Operating System

Windows10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
Hephaestus and Create are using different branches of porting lib

**Comment by CGMejia2001** [comment]
> Hephaestus and Create are using different branches of porting lib

are there any plans to make create fabric work with hephaestus? or it's on the hephaestus devs?

**Comment by TropheusJ** [comment]
Hephaestus needs to update

**Comment by TropheusJ** [comment]
this should be fixed with patch f
