### ISSUE TITLE
How to open jar?(Not closed)

### ISSUE THREAD

**Issue by Bruce6131** [Fabricators-of-Create/Create#1063]
I downloaded the zip but there is no create.jar! how do I put this in my mods folder!

**Comment by MimzyFang** [comment]
You probably downloaded the source code please download the mod from 
https://www.curseforge.com/minecraft/mc-mods/create-fabric
or
https://modrinth.com/mod/create-fabric

**Comment by Bruce6131** [comment]
But the only 1.20 version is the source code! I need 1.20! What do I do with the source code? how do I make it into a jar!

**Comment by TropheusJ** [comment]
Wait for the release

**Comment by Bruce6131** [comment]
When will the release be?

**Comment by Bruce6131** [comment]
Thanks for releasing it!
