### ISSUE TITLE
Incompatible with Compact Machines 5

### ISSUE THREAD

**Issue by shanoaice** [Fabricators-of-Create/Create#1064]
### Describe the Bug

When loaded together with Compact Machines 5, game crashes during start.

### Reproduction Steps

1. Install Compact Machines 5 and Create Fabric
2. Launch the game

### Expected Result

Game launches successfully.

### Crash Report or Log

https://mclo.gs/Ft2bdEL

### Operating System

Windows 11

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

Reproducible with only Fabric API, Create and Compact Machines 5 installed.

### Additional Context

This issue https://github.com/AlphaMode/CompactMachines-Fabric/issues/7 seems to be relevant, though it does not crash on start.

**Comment by TropheusJ** [comment]
same reason as #1061
