### ISSUE TITLE
Not compatible with sodium 0.5.2

### ISSUE THREAD

**Issue by iamnewcar** [Fabricators-of-Create/Create#1065]
### Describe the Bug

Im not sure if this is a bug or not, but the MC Log says that create is not compatible with sodium, then if i downgrade the other mods like iris, indium etc. stop working and tells me to just remove the create mod

Sorry if this isnt the correct way to submit this error, ive never used github before now

### Reproduction Steps

1. install Create and sodium 0.5.2
2. hit play
3. crashes

### Expected Result

Game launches, and works

### Before downgrading sodium
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with any version that is compatible with:
		 - porting_lib_accessors 2.1.1070+1.20
		 - porting_lib_base 2.1.1070+1.20
		 - porting_lib_entity 2.1.1070+1.20
		 - porting_lib_extensions 2.1.1070+1.20
		 - porting_lib_fake_players 2.1.1070+1.20
		 - porting_lib_transfer 2.1.1070+1.20
		 - sodium 0.5.2
Unmet dependency listing:
	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.2!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### After downgrading sodium
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 (C:\Users\tevor\AppData\Roaming\com.modrinth.theseus\profiles\Fabulously Optimized\mods\create-fabric-0.5.1-d-build.1161+mc1.20.1.jar).
	 - Replace mod 'Sodium' (sodium) 0.4.10+build.27 with version 0.5.2.
Unmet dependency listing:
	 - Mod 'Indium' (indium) 1.0.25+mc1.20.1 requires version 0.5.2 of mod 'Sodium' (sodium), but only the wrong version is present: 0.4.10+build.27!
	 - Mod 'Iris' (iris) 1.6.8 requires version 0.5.2 of mod 'Sodium' (sodium), but only the wrong version is present: 0.4.10+build.27!
	 - Mod 'Reese's Sodium Options' (reeses-sodium-options) 1.6.5+mc1.20.1-build.95 is incompatible with any version before 0.5.0 of mod 'Sodium' (sodium), but a matching version is present: 0.4.10+build.27!
	 - Mod 'Sodium Extra' (sodium-extra) 0.5.1+mc1.20.1-build.112 requires version 0.5.1 or later of mod 'Sodium' (sodium), but only the wrong version is present: 0.4.10+build.27!
	 - Mod 'Statement Vanilla Compatibility Module' (statement_vanilla_compatibility) 1.0.1+1.14.4-1.15.2 requires any version between 1.14.0-0 (inclusive) and 1.16.0-0 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Sodium 0.5.2
Porting_lib_accessors 2.1.1070+1.20
Porting_lib_base 2.1.1070+1.20
Porting_lib_entity 2.1.1070+1.20
Porting_lib_extensions 2.1.1070+1.20
Porting_lib_fake_players 2.1.1070+1.20
Porting_lib_transfer 2.1.1070+1.20

Not sure where the "porting lib" mods came from, they arent anywhere else in the mod loader or mod manager

**Comment by TropheusJ** [comment]
#1039
