### ISSUE TITLE
Incompatible with Sodium 0.5.0+

### ISSUE THREAD

**Issue by itsARprod** [Fabricators-of-Create/Create#1067]
### Describe the Bug

Create Fabric Requires Indium To Work With Sodium Properly
Indium Needs Sodium 0.5.0+ to work
Create Fabric Is Incompatible with Sodium 0.5.0+
This makes no sense.

### Reproduction Steps

1. Install The Following Mods:
    - Create Fabric 0.5.1-d-build.1161
    - Sodium 0.5.0 or later (0.5.2 in my case)
    - Indium 1.0.25
2. Launch The Game
3. The Game Crashes And Shows a Fabric Popup

### Expected Result

The Game Runs Normally

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/143180333/1118a344-1a32-4ac2-b96a-855fcc2e8cc1)

### Crash Report or Log

Incompatible mod set! net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set! A potential solution has been determined: 	 - Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with any version that is compatible with: 		 - sodium 0.5.2 Unmet dependency listing: 	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.2! 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Here's An Image Of The mods Folder 
![image](https://github.com/Fabricators-of-Create/Create/assets/143180333/67df218c-eae0-4fe8-b1a8-e75fc3bac268)

**Comment by Felix14-v2** [comment]
> Requires Indium To Work With Sodium ... This makes no sense.

Just downgrade Sodium to 0.4.10 and use compatible Indium version

**Comment by XieDeWu** [comment]
Very much looking forward to this issus being fixed closed

**Comment by mairangh** [comment]
> > Requires Indium To Work With Sodium ... This makes no sense.
> 
> Just downgrade Sodium to 0.4.10 and use compatible Indium version

with Sodium to 0.4.10 crash when loading the world
[crash-2023-08-25_15.50.24-client.txt](https://github.com/Fabricators-of-Create/Create/files/12439269/crash-2023-08-25_15.50.24-client.txt)

**Comment by liamwerk7676** [comment]
**create pls fix this alredy this is the only thing preventing me from moving to fabric**

**Comment by AkashiiKun** [comment]
It's not even released, be patient.

**Comment by TropheusJ** [comment]
#1039 - duplicate 3

**Comment by Feliks-WR** [comment]
Just remove create.
Sodium will not be affected.
Let it either be updated, or die out.
