### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by PinkBunny8** [Fabricators-of-Create/Create#1068]
### Describe the Bug

there are some missing textures for the following items:
water wheel, large water wheel, crushing wheel, blaze burner, empty blaze burner, copper valve handle, mechanical roller, flywheel, display link, nixie tube, 

### Reproduction Steps

load the game and open inventory

### Expected Result

you'll see whats shown in the images

### Screenshots and Videos

![2023-08-25_15 57 35](https://github.com/Fabricators-of-Create/Create/assets/137655159/0cc98b09-d1d1-4c37-9926-8830585c2f13)
![2023-08-25_15 57 44](https://github.com/Fabricators-of-Create/Create/assets/137655159/7db89bd0-16ac-40e2-97f9-7252f7117f69)

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
need the mod list

**Comment by PinkBunny8** [comment]
> need the mod list


Architectury
Athena
Bad packets
Balm
Bclib
Botarium
Cardinal components
Collective
Creative Core
Fabric api
Forge Config APIPort
Fusion 
GeckoLib
Indium 
Iris
Lithium 
Malilib
Midnight Lib
Moonlight
Owo lib
Pehkui
Puzzles Lib
Reeses Sodium options
ResourceFullLib
ResourceConfigLib
Sodium extra
Sodium Fabric
Yet another Config lib
3d skin layers
Alternate Origin Mod GUI
Appleskin
Armor Chroma
Better F3
Continuity 
Double doors 
Easy magic
Easy Anvils
Eating animations
Inventory HUD
Just Enough Items
Lamb Dynamic Lights
Litematica 
Mod menu
Notes 
Polymorph 
Replay Mod
ShulkerBoxToolTip
Simple Hud
Stack refill
Third Person Maps
WTHIT (What the hell is that)
Zoomify
Ambient Sounds 
Blahaj
Comforts
Craftable potion combinations
Dramatic doors 
Elytra trims  
Expanded trident enchanting 
Expanded weapon enchanting 
Falling leaves
Forgotten graves
Immersive paintings 
Measurements 
Mo' Glass 
More doors
More mob variants
Pack It Up 
Plushables
Replanting Crops
Splash milk
Surface Mushrooms
Travelers Backpack
Waystones
Weird Equipment
Vertical slabs 
Additional structures 
Adorn 
AD Astra 
Armour Abilities
Better archeology
Better End 
Better Nether 
Chipped 
Clutter 
Cooking for blockheads 
Croptopia
Culinary construct 
Extra origins
Farmers Delight 
Recipe Book Delight 
Farmers Knives 
Expanded Delight
Corn Delight 
Fish of thieves
Food plus
Friends and foes - beekeeper hut
Friends and foes
Friends and foes - flowery mooblooms
Handcrafted 
Macaws - Bridges, Fences, Lights, Paths, Roofs, Trapdoors
Missing Wilds 
Mob Origins
Origins 
Origins Plus
Plenty of armours 
Qu-enchantments 
Reinforced Barrels
Reinforced Chests
Repurposed Structures
Sniffer+
Snowy Spirit
Structory
Structory towers
Supplementaries
Terrestria 
Tom's Storage 
Traverse 



Datapacks

Afk Display
Anti Enderman Grief
Count Mob Deaths
Double Shulker Shells
Dragon Drops
Invisible Item Frame
Larger Phantom
More Mob Heads
Origins+++Mod+Compatibility+
Player Head Drops
Silence Mobs
Timber
Track Raw Statistics
Track Statistics
Treasure Gems 
Villager Death Messages
Villager Workstation Highlights
Wandering Trades (mini blocks)

**Comment by TropheusJ** [comment]
#1039 - duplicate 6

**Comment by PinkBunny8** [comment]
what exactly is the fix?

**Comment by mxKeaton** [comment]
https://github.com/Fabricators-of-Create/Create/issues/1039 got closed so I will post it here.

The issue does also occure on sodium 0.4.10 and Iris 1.6.4 with puzzlelib 8.0.24 (said to be the issue in some reports)
