### ISSUE TITLE
cogwheels don't become faster when placed together

### ISSUE THREAD

**Issue by PinkBunny8** [Fabricators-of-Create/Create#1069]
### Describe the Bug

when I placed 2 or more cogwheels next to eachother they all go the same speed and from what i know it should of gone faster

### Reproduction Steps

create a power source
place a cogwheel
attach another one

### Expected Result

moving at the same speed as the first one

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by DarianLStephens** [comment]
Any screenshots? For all we know, you're placing cogwheels of the same size next to eachother because you have no idea how gear ratios work.

**Comment by PinkBunny8** [comment]
I have tried copying what I have seen from videos but I have discovered the issue and it is now all working properly. Sorry for the inconvinience

**Comment by DarianLStephens** [comment]
But... what was the issue?

**Comment by PinkBunny8** [comment]
the gear placement and the ratio between them - i placed them completely the wrong way
