### ISSUE TITLE
Mechanical Saw works in reverse direction

### ISSUE THREAD

**Issue by RedWideWeb** [Fabricators-of-Create/Create#107]
### Describe the Bug

Usually Mechanical Saw cut items in the direction that their shaft is rotating. I have downloaded the latest build but the bug is present in previous builds as well

### Reproduction Steps

1. Place down a Mechanical Saw 
2. Give it rotation force
3. Put an item on it

### Expected Result

Item cutting follows the direction of the rotational force

### Screenshots and Videos

https://user-images.githubusercontent.com/58992150/150753053-6466da83-5fcb-4fcc-8488-a4bdc844b981.mp4

### Operating System

Windows 10 1809

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

Fabric API 0.46.1

**Comment by JieningYu** [comment]
This is not a bug but a feature of Create. It exists in forge version too for a long time.
If item cutting follows the direction of the rotational force as you expected, it will be a bug.

**Comment by RedWideWeb** [comment]
> This is not a bug but a feature of Create. It exists in forge version too for a long time. If item cutting follows the direction of the rotational force as you expected, it will be a bug.

Hmm, okay
