### ISSUE TITLE
Support ‘Sodium’ versions higher than 0.5

### ISSUE THREAD

**Issue by Wanye-7300** [Fabricators-of-Create/Create#1071]
### Describe the Suggestion

Sodium version above version 0.5 are not supported

### Screenshots and Videos

<img width="591" alt="image" src="https://github.com/Fabricators-of-Create/Create/assets/88421542/426d8819-8433-47df-9e7d-a7fac9f2c48e">

### Additional Context

version: 1.20.1
mods:
- create 0.5.1
- sodium 0.5.2
- indium 1.0.25
- fabric-api 0.87.0
- iris 1.6.8

**Comment by TropheusJ** [comment]
#1039 - duplicate 4
