### ISSUE TITLE
Jetpack disapearing from Forge -> Fabric port

### ISSUE THREAD

**Issue by Chopineln** [Fabricators-of-Create/Create#1072]
### Describe the Bug

Hello,

I had a save i made on create forge:

forge 47.1.44
create forge 0.5.1.d

on the forge version there is an enchanted jetpack (capacity III)
when i put the forge save on my fabric create MC the jetpack disapear

### Reproduction Steps

1. on forge make a jetpack
2.port to fabric
3. jetpack desapeared
...

### Expected Result

no disapearing of jetpack

### Operating System

WIN11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
create does not have jetpacks
