### ISSUE TITLE
Create bug with sodium 0.5.0 or later.

### ISSUE THREAD

**Issue by Crafty1340** [Fabricators-of-Create/Create#1073]
### Describe the Bug

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with any version that is compatible with:
		 - sodium 0.5.2
Unmet dependency listing:
	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.2!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Reproduction Steps

1. N/A
2. N/A
3. N/A
...

### Expected Result

The game to load.

### Screenshots and Videos

N/A

### Crash Report or Log

Exit code 1. (Probaly from me closing the game while it was loading).

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Sodium and Create and a few others. But they are not in the error message.

### Additional Context

N/A

**Comment by MetaForge** [comment]
Same problem here :/

**Comment by ORPHEDEUUS** [comment]
same

**Comment by TropheusJ** [comment]
#1039 - duplicate 5

**Comment by skunkmommy** [comment]
this needs more attention, it's a really bad look to not support a mod that's so widely used, i know u can downgrade but still
EDIT: read the "duplicate" and that's not a reason to completely break compat, just force flywheel off if a newer sodium version is detected for now, when it's fixed just remove the forcing

**Comment by skunkmommy** [comment]
immersive portals causes the same behaviour as described in #1039, so you aren't even being consistent with what is and isn't enough to warrant breaking compat (_**THIS IS NOT.**_)
My perception of this devteam is ruined by the utter stupidity of this decision.
Get your act together and **force flywheel off on 0.5.x**.
