### ISSUE TITLE
DirectBeltInputBehaviour(this) doesn't do anything

### ISSUE THREAD

**Issue by ghasto69** [Fabricators-of-Create/Create#1075]
### Describe the Bug

adding the DirectBeltInputBehaviour to the behaviours of a block entity does nothinh

### Reproduction Steps

1. Make a block entity that can hold items
2.add the DirectBeltInputBehaviour
3. launch minecraft

### Expected Result

When the block is placed on a belt, items moving on it will go into the item storage of that block entity

### Operating System

Macos

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
works for everything in Create that uses it. can't do anything about an "it doesn't work"
