### ISSUE TITLE
Not compatible with Sodium 0.5.2

### ISSUE THREAD

**Issue by Nohmarr** [Fabricators-of-Create/Create#1076]
### Describe the Bug

Not compatible with Sodium 0.5.2

### Reproduction Steps

1.Run minecraft
2.See error
3.
...

### Expected Result

Minecraft run.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/67859106/228f8fdc-f778-4092-9644-13c4132e38fa)

### Crash Report or Log

https://pastebin.com/2hBqwR6r

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/67859106/a484250d-0341-44a2-87db-298d14ebb7e0)

**Comment by TropheusJ** [comment]
#1039 - duplicate 7
