### ISSUE TITLE
`AbstractSimiWidget.renderButton` is incompatible with yarn mapping

### ISSUE THREAD

**Issue by Phoupraw** [Fabricators-of-Create/Create#1078]
### Describe the Suggestion

`AbstractSimiWidget.renderButton` has the same method signature with `Widget.renderButton` (mojmap: `AbstractWidget.renderWidget`), causing all projects which use yarn mapping to fail to load.

**Comment by TropheusJ** [comment]
renderButton overrides renderButton in AbstractWidget. If that's not being remapped to renderWidget in yarn, that sounds like a bug in loom.

**Comment by TropheusJ** [comment]
wait, wrong branch, let me see if it's changed

**Comment by TropheusJ** [comment]
okay, that has changed. It should probably be renamed on forge too.

**Comment by TropheusJ** [comment]
fix PR opened: https://github.com/Creators-of-Create/Create/pull/5558
