### ISSUE TITLE
Most of the mod's blocks aren't displaying at all

### ISSUE THREAD

**Issue by Eklip5e** [Fabricators-of-Create/Create#1079]
### Describe the Bug

As the bug's title can tell, when I play the mod, the game doesn't display all the block models right.

**This problem also involves when those blocks are placed:** sometimes only the shadows are displayed when places, otherwise some corrupted version of some already existent Create's block.

All the blocks that have this issue:

- Water Wheel
- Large Water Wheel
- Crushing Wheel
- Empty Blaze Burner
- Blaze Burner
- All the Copper Valves
- Mechanical Roller
- Flywheel
- Display Link
- Nixie Tube

### Reproduction Steps

1. Launch Minecraft
2. Open a Singleplayer/Multiplayer world
3. Open your Inventory or scroll inside your "X Enough Recipes" mod
4. Voilà

### Expected Result

The expected result was to have all the blocks displayed right and not having them transparent or corrupted.

### Screenshots and Videos

![javaw_7PeyWykXtJ](https://github.com/Fabricators-of-Create/Create/assets/38536104/b45437b2-05db-43ca-96cd-73903dfafc2f)
![javaw_IS67sYwyZE](https://github.com/Fabricators-of-Create/Create/assets/38536104/4177a5fc-26ee-4abb-9437-6f98fa8bf1a6)
![zTaBTax5wM](https://github.com/Fabricators-of-Create/Create/assets/38536104/80bdf0d7-471b-4672-a4a7-6576afaaed07)

![javaw_UC1zGI9cbk](https://github.com/Fabricators-of-Create/Create/assets/38536104/930d7364-9bb2-4d74-9985-c39e6890c41e)
![javaw_Wt3RAfVZ9I](https://github.com/Fabricators-of-Create/Create/assets/38536104/72b0e5fd-c2c1-4b1e-8269-20f55828168c)
![javaw_SW88Leaz79](https://github.com/Fabricators-of-Create/Create/assets/38536104/13c13fe9-23e3-44ba-81a1-48a2466ed396)

### Crash Report or Log

https://gist.github.com/ProxySoul0302/85615af71c53e71577660bcc8b55a91d

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

- advancementinfo 1.20-fabric0.83.0-1.4
	- animatica 0.6+1.20
	- antighost 1.20-fabric0.83.0-1.1.5
	   \-- crowdin-translate 1.4+1.19.3
	- appleskin 2.5.0+mc1.20
	- architectury 9.1.12
	- audioplayer 1.20.1-1.6.0
	- balm-fabric 7.0.4
	- bettermounthud 1.2.2
	- blur 3.1.0
	   |-- midnightlib 1.4.1
	   \-- satin 1.13.0
	- bobby 5.0.0
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- borderlessmining 1.1.8+1.20.1
	- capes 1.5.2+1.20
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	- cherishedworlds 6.1.1+1.20.1
	- citresewn 1.1.3+1.20
	   \-- citresewn-defaults 1.1.3+1.20
	- cloth-config 11.1.106
	   \-- cloth-basic-math 0.6.1
	- connectiblechains 2.2.1+1.20.1
	- continuity 3.0.0-beta.3+1.20.1
	- controlify 1.4.4+1.20
	   |-- dev_isxander_sdl2-jni 2.26.5-24
	   |-- org_hid4java_hid4java 0.7.0
	   \-- org_quiltmc_quilt-json5 1.0.3
	- couplings 1.9.5+1.20
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- create 0.5.1-d-build.1161+mc1.20.1
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.9-1
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_accessors 2.1.1127+1.20
	   |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_base 2.1.1127+1.20
	   |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    |-- porting_lib_lazy_registration 2.1.1127+1.20
	   |    \-- porting_lib_utility 2.1.1127+1.20
	   |-- porting_lib_brewing 2.1.1127+1.20
	   |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_client_events 2.1.1127+1.20
	   |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |    |-- mm 2.3
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_entity 2.1.1127+1.20
	   |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_mixin_extensions 2.1.1127+1.20
	   |-- porting_lib_extensions 2.1.1127+1.20
	   |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_fake_players 2.1.1127+1.20
	   |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_models 2.1.1127+1.20
	   |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_model_loader 2.1.1127+1.20
	   |-- porting_lib_networking 2.1.1127+1.20
	   |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_obj_loader 2.1.1127+1.20
	   |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_model_loader 2.1.1127+1.20
	   |-- porting_lib_tags 3.0
	   |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_tool_actions 2.1.1127+1.20
	   |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_transfer 2.1.1127+1.20
	   |    |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        |-- porting_lib_data 2.1.1090+1.20
	        |    \-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- culturaldelights 0.14.11+1.20.1
	   \-- terraform-wood-api-v1 7.0.1
	- customskinloader 14.17
	- debugify 1.20.1+2.0
	- desiredservers 1.2.0
	- drippyloadingscreen 2.2.2
	- dynamicfps 2.4.0
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- e4mc_minecraft 3.2.0
	   \-- org_java-websocket_java-websocket 1.5.3
	- easyanvils 8.0.0
	- easymagic 8.0.0
	- eatinganimationid 1.9.4+1.20
	- enhancedblockentities 0.9+1.20
	   |-- advanced_runtime_resource_pack 0.6.7
	   \-- spruceui 5.0.0+1.20
	- entity_model_features 0.2.13
	- entity_texture_features 4.5.1
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.2-mc1.20
	- expandeddelight 0.3.0.2
	- fabric-api 0.87.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.2.2+1e61dba177
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.10+23d9108177
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
	   |-- fabric-message-api-v1 5.1.7+3265161977
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.1.2+6bdb2ed077
	   |-- fabric-renderer-indigo 1.4.2+6bdb2ed077
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.34+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.0+cdf060b277
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabric-language-kotlin 1.10.0+kotlin.1.9.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.21.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.2
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1
	- fabricloader 0.14.22
	- fabricskyboxes 0.7.2+mc1.20.1
	- fabrictailor 2.1.2
	   |-- config2brigadier 1.2.3
	   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
	- fabrishot 1.10.0
	- fadeless 1.0.1
	- fancymenu 2.14.7
	- farmersdelight 1.20.1-1.4.2
	- fastquit 3.0.0-beta.2+1.20+
	- ferritecore 6.0.0
	- forgeconfigapiport 8.0.0
	- fsb-interop 1.3.2+mc1.20-build.36
	- geophilic v2.0.0-mc1.20u1.20.1
	- globalpacks 1.16.1_fabric
	- held-item-info 1.5.0
	- holdthatchunk 2.0.1
	- immediatelyfast 1.1.16+1.20.1
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   \-- net_lenni0451_reflect 1.2.1
	- indium 1.0.21+mc1.20.1
	- inventoryessentials 8.0.0
	- inventorysorter 1.9.0-1.20
	   \-- kyrptconfig 1.5.6-1.20
	- iris 1.6.4
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- isxander-main-menu-credits 1.1.2
	- jade 11.2.2
	- java 17
	- konkrete 1.6.1
	- lambdynlights 2.3.1+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- languagereload 1.5.8+1.20.1
	- lazydfu 0.1.3
	- lithium 0.11.2
	- memoryleakfix 1.1.1
	- minecraft 1.20.1
	- mixintrace 1.1.1+1.17
	- modelfix 1.14
	- modern_glass_doors 5.1.1+1.20-and-later
	- modmenu 7.1.0
	- morechathistory 1.1.1
	- moreculling 1.20-0.18.1
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   \-- conditional-mixin 0.3.2
	- mousetweaks 2.25
	- nochatreports 1.20.1-v2.2.2
	- optigui 2.1.2
	   |-- optiglue 2.1.2-mc.1.19.3
	   |-- org_apache_commons_commons-text 1.10.0
	   \-- org_ini4j_ini4j 0.5.4
	- presencefootsteps 1.9.0
	   \-- kirin 1.15.0
	- puzzle 1.5.2+1.20
	   |-- midnightlib 1.4.1
	   |-- puzzle-base 1.5.2+1.20
	   |-- puzzle-gui 1.5.2+1.20
	   |-- puzzle-models 1.5.2+1.20
	   \-- puzzle-splashscreen 1.5.2+1.20
	- puzzleslib 8.0.7
	- reeses-sodium-options 1.5.1+mc1.20-build.74
	- roughlyenoughitems 12.0.634
	   \-- error_notifier 1.0.9
	- rrls 1.20.1-3.1.0-fabric
	- skinlayers 1.5.4-mc1.20.1
	- sodium 0.4.10+build.27
	- sodium-extra 0.4.26+mc1.20.1-build.109
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- starlight 1.1.2+fabric.dbc156f
	- visualworkbench 8.0.0
	- voicechat 1.20.1-2.4.23
	- xaerominimap 23.5.0
	- xaeroworldmap 1.30.6
	- yet_another_config_lib_v3 3.0.3+1.20
	   |-- com_twelvemonkeys_common_common-image 3.9.4
	   |-- com_twelvemonkeys_common_common-io 3.9.4
	   |-- com_twelvemonkeys_common_common-lang 3.9.4
	   |-- com_twelvemonkeys_imageio_imageio-core 3.9.4
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.9.4
	   \-- com_twelvemonkeys_imageio_imageio-webp 3.9.4
	- yosbr 0.1.2
	- zoomify 2.10.0
	   |-- com_akuleshov7_ktoml-core-jvm 0.4.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6

**Comment by Eklip5e** [comment]
As far as I know, this problem can be caused by Sodium or Iris, but even if Iris is disabled as mod, the problem still occurs.

Worst of all, while I was testing this bug, I've found a second one where, if I assemble any contraption, from a windmill to a train, the game crashes.

**Comment by TropheusJ** [comment]
sodium, iris, and indium look fine
starlight is incompatible
that's probably not it though, some other incompat. You'll have to figure out what mod causes it.

**Comment by TropheusJ** [comment]
ah, duplicate of #1052
