### ISSUE TITLE
Fabric server crashing when disassembly contraption

### ISSUE THREAD

**Issue by MistGo** [Fabricators-of-Create/Create#1080]
### Describe the Bug

When I disassembly the contraption, my server crashing. After restarting, all contraption duped with the items in his chests.

### Reproduction Steps

1. Make contraption using cart assembler
2. Assembly contraption and add some items
3. Disassembly contraption using cart assembler

### Expected Result

Disassembly without crashing the server.

### Crash Report or Log

https://gist.github.com/MistGo/67cf600db959b843232aaafdc4cafb3a

### Operating System

Ubuntu 22.04

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

create-fabric-0.5.1-d-build.1161+mc1.20.1.jar
fabric-api-0.87.0+1.20.1.jar
jei-1.20.1-fabric-15.2.0.27.jar
lithium-fabric-mc1.20.1-0.11.2.jar
memoryleakfix-fabric-1.17+-1.1.1.jar
noelytra-v1.jar
player-events-api-2.4.5.jar
spark-1.10.49-fabric.jar
Steam_Rails-1.5.0+fabric-mc1.20.1-build.547.jar
tabtps-fabric-mc1.20.1-1.3.18.jar
tsasatus-1.0.0.jar -- private mod

**Comment by TropheusJ** [comment]
what inventories are on the contraption

**Comment by MistGo** [comment]
> what inventories are on the contraption

only chests

**Comment by metalpietie** [comment]
I have a similar issue. It happened when a rope pulley contraption with chests attached came back up to its original position. When the server started again all items duped. Super glue is still in the air even after picking up the contraption.

**Comment by OffsetMonkey538** [comment]
Similar issue. I have a miner thing and when I put it in a `Cart Assembler`, the server crashed and when I restarted it, all the blocks in the contraption got duplicated as items on the ground. https://mclo.gs/As34vSi

**Comment by OffsetMonkey538** [comment]
With more testing, it seems to happen if there are blocks in the way of the creation

**Comment by ThatVoidUpdate** [comment]
Can confirm this occurs with the rope pulley, however I don't have any blocks in the way at the time of disassembly

**Comment by ThatVoidUpdate** [comment]
I think this is a dupe of #1038

**Comment by misigno** [comment]
From my testing a crash occurs on any contraption that goes back to solid blocks after a mounted inventory has had items taken out of using shift-click when it still is an entity.

**Comment by vaniron** [comment]
Any plans to fix this? Really number 1 problem crashing server all the time.

**Comment by RanolP** [comment]
Is anyone working on this? I suggested two ways to fix this in #1264 but the issue was marked as duplicated so I moved here for further debates. imho just double-checking emptiness in ItemStackHandler#nonEmptyViews/ItemStackHandler#nonEmptyIterator on the porting-lib is the best way to remove bugs without any side effects.

**Comment by IThundxr** [comment]
Confirmed on patch f

**Comment by schultzy51** [comment]
This occurs very regularly for me as well

**Comment by vbaier** [comment]
Could somebody help me with where this fix gets applied? I didn't see it in the changelog for Patch F on the forge variant and @IThundxr says it's confirmed on F. I also don't see the relevant change cherry picked into the 1.20.1/fabric/dev branch. Am I missing something? Thanks in advance!

**Comment by IThundxr** [comment]
Already fixed in patch F, not sure if it was a change in porting lib or create
