### ISSUE TITLE
Incompatable with Sodium(0.5.0 or later versions)

### ISSUE THREAD

**Issue by luanyufei** [Fabricators-of-Create/Create#1081]
### Describe the Suggestion

Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium),but a matching version is present: 0.5.2!

### Screenshots and Videos

<img width="912" alt="截屏2023-08-29 00 40 50" src="https://github.com/Fabricators-of-Create/Create/assets/79290667/5b1a84f8-4060-4973-b362-1438ceb8246d">

**Comment by TropheusJ** [comment]
#1039 - duplicate 8

**Comment by LokeYourC3PH** [comment]
> #1039 - duplicate 8

There will be duplicate 9+ , so why not post an update to let people know what's going on instead of always just closing with "#id - duplicate n+1"?

**Comment by TropheusJ** [comment]
nothing to update? The issue is known, it will be fixed eventually.
