### ISSUE TITLE
Worldgen crash with Tectonic

### ISSUE THREAD

**Issue by DeenOConnor** [Fabricators-of-Create/Create#1082]
### Describe the Bug

The game starts up and generates the world just fine with Tectonic and Create installed separately, but once i enable both of them at the same time i get java.lang.IllegalStateException: Feature order cycle found

### Reproduction Steps

1. Install Minecraft 1.20.1 with Fabric and Fabric API
2. Install Tectonic 
3. Verify that world generates
4. Install Create and disable/uninstall Tectonic
5. Verify that world generates
6. Now enable/install Tectonic alongside Create

Result: game crashes before it's able to generate the world

### Expected Result

I expected the world to be generated without issues

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Tectonic

**Comment by TropheusJ** [comment]
can't do anything without logs, but because of this issue's age I probably won't get one
