### ISSUE TITLE
Cherry wood missing from `stripped_logs` block tag.

### ISSUE THREAD

**Issue by OffsetMonkey538** [Fabricators-of-Create/Create#1085]
### Describe the Bug

Can't create casings out of stripped cherry logs because they aren't added to the `stripped_logs` tag.

### Reproduction Steps

1. Try to apply andesite alloy to a stripped cherry log, it won't turn it into andesite casing

### Expected Result

Stripped cherry logs should be in the `c:stripped_logs` tag and it should be possible to turn stripped cherry logs into casing.

### Operating System

Nobara Linux

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by OffsetMonkey538** [comment]
Seems like cherry logs are missing from many places. Putting them in a saw doesn't turn them into planks

**Comment by TropheusJ** [comment]
this should be fixed in patch f
