### ISSUE TITLE
Symmetry wand placing double slabs

### ISSUE THREAD

**Issue by mmiser** [Fabricators-of-Create/Create#1086]
### Describe the Bug

When you place a slab with the symmetry wand active, the copies it creates instntly transform into a double slab as if u placed it twice. (Only happens in Fabric create)

### Reproduction Steps

1.Place symmetry wand
2.Place a slab

### Expected Result

Two half slabs instead a half slab and a full block of slabs

### Screenshots and Videos

![2023-08-31_11 58 34](https://github.com/Fabricators-of-Create/Create/assets/143705673/78251df3-e4f9-4721-923d-254a1eb84115)

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

create-fabric-0.5.1-c-build.1160+mc1.19.2

### Additional Context

First I thought it was an incompatibility with any other mod from my modpack, but then I tried with just the cerate mod and the bug was still there.

**Comment by Poly-0000** [comment]
yeah this is a pretty serious bug given it allows players to dupe items (slab recycling)

**Comment by IThundxr** [comment]
Try to recreate in forge, if you can then this should be reported to the forge repo

**Comment by mmiser** [comment]
> Try to recreate in forge, if you can then this should be reported to the forge repo

On forge works fine, It right be something wrong with the fabric version, because it still persists in the 1.20.1
