### ISSUE TITLE
Crashing when interacting with anything

### ISSUE THREAD

**Issue by KromGa** [Fabricators-of-Create/Create#1087]
### Describe the Bug

After opening ANY block interface like waystone or smithing table or lectern game freezes and crashes

### Reproduction Steps

1. TP to nearest village
2. RMB Waystone (Fabric Waystones) or lectern
3. Game Crashes

### Expected Result

Normally open the waystone or lectern interface

### Crash Report or Log

---- Minecraft Crash Report ---- // Would you like a cupcake?  Time: 2023-08-31 18:57:54 Description: Unexpected error  java.lang.NoClassDefFoundError: com/simibubi/create/content/curiosities/deco/PlacardTileEntity 	at io.chaws.textutilities.handlers.ClickThroughHandler.canClickThroughBlockEntity(ClickThroughHandler.java:153) 	at io.chaws.textutilities.handlers.ClickThroughHandler.tryClickThrough(ClickThroughHandler.java:115) 	at io.chaws.textutilities.handlers.ClickThroughHandler.handleUseBlock(ClickThroughHandler.java:55) 	at net.fabricmc.fabric.api.event.player.UseBlockCallback.lambda$static$0(UseBlockCallback.java:41) 	at net.minecraft.class_636.handler$dhk000$fabric-events-interaction-v0$interactBlock(class_636.java:2684) 	at net.minecraft.class_636.method_2896(class_636.java:327) 	at net.minecraft.class_310.redirect$cdp000$cleancut$onItemUse(class_310.java:12013) 	at net.minecraft.class_310.method_1583(class_310.java:1748) 	at net.minecraft.class_310.redirect$bgl000$betterthirdperson$onDoItemUse(class_310.java:10030) 	at net.minecraft.class_310.method_1508(class_310.java:2002) 	at net.minecraft.class_310.method_1574(class_310.java:1829) 	at net.minecraft.class_310.method_1523(class_310.java:1135) 	at net.minecraft.class_310.method_1514(class_310.java:768) 	at net.minecraft.client.main.Main.method_44604(Main.java:244) 	at net.minecraft.client.main.Main.main(Main.java:51) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) Caused by: java.lang.ClassNotFoundException: com.simibubi.create.content.curiosities.deco.PlacardTileEntity 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 	... 18 more

### Operating System

Win 11

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

Fabric Waystones

### Additional Context

This happened on both 0.5.1b and 0.5.1c (have not tested the other ones)

**Comment by TropheusJ** [comment]
text utilities is outdated
