### ISSUE TITLE
crash on client side or singleplayer when using create blocks which cause movements

### ISSUE THREAD

**Issue by WorldsOfRosefire** [Fabricators-of-Create/Create#1088]
### Describe the Bug

tested blocks: mechanical piston, windmill 
first I thought its could be issue with valkyrienskies, but its the same without it. since this mod changes a lot I inclue the file with and without it.
the singleplayer and client side are crashing, the serverside is fine, but no movements, the construction never got activated

### Reproduction Steps

1. place the mentioned blocks
2.try to interact/activating
3.
...

### Expected Result

working movement as intended

### Crash Report or Log

https://gist.github.com/WorldsOfRosefire/29490c91a74637558d0c1381e69ac89d

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

We currently build a test a private modpack,, this is a small selection we always use, it occured the same ways is it did in you pack.
fabric version 0.14.21
  [✔️] cem-0.8.0.jar
  [✔️] chat_heads-0.10.16-fabric-1.20.jar
  [✔️] CITResewn-1.1.3+1.20.jar
  [✔️] Clumps-fabric-1.20.1-12.0.0.2.jar
  [✔️] create-fabric-0.5.1-d-build.1161+mc1.20.1.jar
  [✔️] fabric-api-0.86.1+1.20.1.jar
  [✔️] fallingleaves-1.15.1+1.20.1.jar
  [✔️] ferritecore-6.0.0-fabric.jar
  [✔️] iris-mc1.20-1.6.4.jar
  [✔️] lambdynamiclights-2.3.1+1.20.1.jar
  [✔️] lazydfu-0.1.3.jar
  [✔️] logical_zoom-0.0.20.jar
  [✔️] notenoughanimations-fabric-1.6.4-mc1.20.jar
  [✔️] OpenLoader-Fabric-1.20.1-19.0.1.jar
  [✔️] Origins-fabric1.20.1-1.10.0.jar
  [✔️] Pehkui-3.7.6+1.14.4-fabric1.20.1.jar
  [✔️] replaymod-1.20.1-2.6.13.jar
  [✔️] sit-1.20-24.jar
  [✔️] Skin-Layers-3D-Mod-Fabric-1.20.1.jar
  [✔️] sodium-fabric-mc1.20-0.4.10+build.27.jar
  [✔️] starlight-1.1.2+fabric.dbc156f.jar
  [✔️] voicechat-fabric-1.20.1-2.4.11.jar

**Comment by TropheusJ** [comment]
starlight is incompatible and unnecessary on 1.20+
