### ISSUE TITLE
a crash caused by Cart Assembler

### ISSUE THREAD

**Issue by smallthe** [Fabricators-of-Create/Create#109]
### Describe the Bug

A crash was caused when I finished assembling combination of blocks on cart assembler.

### Reproduction Steps

1.put blocks on cart assembler
2.use glue to stick the Radial Chassis
3.put a cart under the assembler
4.push the cart
...

### Expected Result

a train combining blocks moved instead of crash

### Crash Report or Log

https://bytebin.lucko.me/DdukxPzCLA

### Operating System

Windows 10

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

create
flywheel
fabric lifecycle events(v1)
starlight 
sodium
iris
indium

### Additional Context

if the crash did not occur, the train was always invisible.

**Comment by RedWideWeb** [comment]
Create contraptions are currently incompatible with starlight. Try without it and if no crash occurs please close the issue
![изображение](https://user-images.githubusercontent.com/58992150/150777723-9b77c30b-727c-4762-ac0e-decc574bc268.png)

**Comment by smallthe** [comment]
ok, I will try it again.

**Comment by TropheusJ** [comment]
Not true, update starlight to 1.0.1.

**Comment by RedWideWeb** [comment]
> Not true, update starlight to 1.0.1.

Yes, I forgot I was using starlight 1.0.1 by your suggestion. Thanks!

**Comment by RedWideWeb** [comment]
> ok, I will try it again.

Upgrade to starlight 1.0.1 which is available only on CurseForge: [https://www.curseforge.com/minecraft/mc-mods/starlight/files/3599857](https://www.curseforge.com/minecraft/mc-mods/starlight/files/3599857)

**Comment by smallthe** [comment]
> > ok, I will try it again.
> 
> Upgrade to starlight 1.0.1 which is available only on CurseForge: https://www.curseforge.com/minecraft/mc-mods/starlight/files/3599857

emmm,I deleted starlight and tried again, but the game crashed again. haha. However, I used two assemblers to make the train, is there relationship between the crash and the two assemblers?

**Comment by RedWideWeb** [comment]
> emmm,I deleted starlight and tried again, but the game crashed again. haha. However, I used two assemblers to make the train, is there relationship between the crash and the two assemblers?

@smallthe  Post a screenshot please. I cannot reproduce

![изображение](https://user-images.githubusercontent.com/58992150/150781138-10407004-1221-4faf-a722-a538a34e9540.png)

**Comment by smallthe** [comment]
> > emmm,I deleted starlight and tried again, but the game crashed again. haha. However, I used two assemblers to make the train, is there relationship between the crash and the two assemblers?
> 
> @smallthe Post a screenshot please. I cannot reproduce
> 
> ![изображение](https://user-images.githubusercontent.com/58992150/150781138-10407004-1221-4faf-a722-a538a34e9540.png)

I will try to make a video.

**Comment by TropheusJ** [comment]
Footage is useless, I need a log.

**Comment by RedWideWeb** [comment]
> Footage is useless, I need a log.

I want to reproduce it

**Comment by smallthe** [comment]
aha, I find if I choose English as game language, the game will not crash , but if I choose other language, the game will crash.

**Comment by RedWideWeb** [comment]
> aha, I find if I choose English as game language, the game will not crash , but if I choose other language, the game will crash.

Specify the language. Russian is okay

**Comment by TropheusJ** [comment]
Please send a crash log.

**Comment by smallthe** [comment]
It is the crash report.

**Comment by smallthe** [comment]
[crash-2022-01-24_20.02.44-client.txt](https://github.com/Fabricators-of-Create/Create/files/7926373/crash-2022-01-24_20.02.44-client.txt)

**Comment by smallthe** [comment]
> 

I chose Chinese which led to this crash.

**Comment by smallthe** [comment]
https://user-images.githubusercontent.com/97573143/150808093-f847fd00-5877-40fe-aaa4-2f8b589ce129.mp4

It is the video before the crash occurred.

**Comment by smallthe** [comment]
[crash-2022-01-24_21.32.42-client.txt](https://github.com/Fabricators-of-Create/Create/files/7926468/crash-2022-01-24_21.32.42-client.txt)
It is the latest crash report.

**Comment by RedWideWeb** [comment]
@smallthe please try latest build from actions folder [https://github.com/Fabricators-of-Create/Create/actions/runs/1738155175](https://github.com/Fabricators-of-Create/Create/actions/runs/1738155175)
I cannot reproduce your issues. Tried all three Chinese languages

**Comment by TropheusJ** [comment]
This is an incompatibility with iris that should have been fixed already. Try updating everything.

**Comment by smallthe** [comment]
aha, it works. thank you very much.

**Comment by RedWideWeb** [comment]
> aha, it works. thank you very much.

You are welcome☺️
