### ISSUE TITLE
1.20.1 Instant Crash. (SODIUM INCOMPATIBLE)

### ISSUE THREAD

**Issue by Naniwara** [Fabricators-of-Create/Create#1090]
### Describe the Bug

Hello! first time using github, sorry if i mess up, the game has an instant crash, Image given.

### Reproduction Steps

1.
2.
3.
...

### Expected Result

Smooth Game Boot, Preferably just useable from the start with FPS friendly mods.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/143756167/8879a1e2-da9e-4740-99f4-9e69ef381fa6)

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Additional Context

Sorry for the troubles, it's a major requirement for low end computers to run with sodium, otherwise fabric's benefits are less notable.

**Comment by TropheusJ** [comment]
use 0.4.10
