### ISSUE TITLE
ThreadLocalRandom accessed from a different thread

### ISSUE THREAD

**Issue by purejosh** [Fabricators-of-Create/Create#1091]
### Describe the Bug

Loglines showing that Create isn't being threadsafe. 

### Reproduction Steps

Use create with something that requires threasafe, like C2ME.

### Expected Result

Be threadsafe. 

### Crash Report or Log

https://gist.github.com/purejosh/a17fea67d60698ac58204fcb32816f50

### Operating System

n/a

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

**Comment by IThundxr** [comment]
This seems like it should be reported to C2ME, its crashing at `Bee.this.level.random.nextInt(10);` which is in a vanilla class and this would eventually get called anyway if mc places structures from a different thread(?)

**Comment by IThundxr** [comment]
Closing since i cant reproduce and doesnt seem like a create/porting lib bug

**Comment by TropheusJ** [comment]
I'm pretty sure it is, I need to investigate the relevant code

**Comment by TropheusJ** [comment]
The relevant code no longer exists.

**Comment by purejosh** [comment]
Thanks!
