### ISSUE TITLE
Create causing game to not Launch

### ISSUE THREAD

**Issue by Wis3Girl05** [Fabricators-of-Create/Create#1092]
[2023-09-02-4.log](https://github.com/Fabricators-of-Create/Create/files/12504144/2023-09-02-4.log)
Create is causing the game to not launch and it doesn't generate a crash report. I was told that it wants an iwrenchable class but isn't getting it. I am using the Modrinth launcher.

**Comment by Brickmaster1** [comment]
I have this too but it wants the IAnimatable class.

**Comment by TropheusJ** [comment]
update your addons
