### ISSUE TITLE
Many items and blocks with missing textures on the fabric version of create

### ISSUE THREAD

**Issue by BrensenGaming** [Fabricators-of-Create/Create#1094]
### Describe the Bug

Many items in the create section of the inventory have missing textures as well as their block counterpart. The list of items with missing textures are:
Water wheel
Large water wheel
Crushing wheel
Empty blaze burner
Blaze Burner
Copper valve handle
Mechanical roller
Flywheel

The rail when placed on a turn or goin diagonally has a missing texture
Bogeys Have a missing texture
You cannot see through any modded window thats on train (unless its on a door)
Modded glass does not connect to each other when placed next to each other

### Reproduction Steps

1. To see any missing textures go into your inventory and look at the create items
2. To see rails having missing textures place any rail goin diagonally or connect it on a turn
3. To see glass not being transparent create a train with glass on it
4. To see modded glass doesnt connect put two of the same modded glass next to each other
...

### Expected Result

I was suspecting to see no items with missing textures, glass being transparent on trains, and seeing modded glass connect to each other when placed next to each other.

### Screenshots and Videos

<img width="321" alt="Screenshot 2023-09-02 175010" src="https://github.com/Fabricators-of-Create/Create/assets/135933997/f84ed467-decc-402e-84be-017509bb0538">
Missing textures:
<img width="216" alt="Screenshot 2023-09-02 175029" src="https://github.com/Fabricators-of-Create/Create/assets/135933997/139983e5-9e55-4c5f-9fa8-1223e1ed8b72">

Missing texture on train tracks:
<img width="744" alt="Screenshot 2023-09-02 174925" src="https://github.com/Fabricators-of-Create/Create/assets/135933997/1cee7a15-5528-4797-b5fd-230138b7dba9">

Glass on train:
<img width="489" alt="Screenshot 2023-09-02 175107" src="https://github.com/Fabricators-of-Create/Create/assets/135933997/f2e36940-2ffb-4e37-b1e2-a5014a351643">

Modded Glass next to each other not connecting
![image_2023-09-02_175616427](https://github.com/Fabricators-of-Create/Create/assets/135933997/d058b58c-7a53-4e85-8b58-c71a5c54d9cc)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image_2023-09-02_175843017](https://github.com/Fabricators-of-Create/Create/assets/135933997/b5d8ba4f-b14e-4db4-9865-bc5f32b3418b)

**Comment by AkashiiKun** [comment]
You need indium mod if you're using sodium mod.

**Comment by BrensenGaming** [comment]
> You need indium mod if you're using sodium mod.

Ok, will that fix the issue?

**Comment by Juancraft567** [comment]
I have the same problem and i put indum and sodium (in client and server side) and it still doesnt work

**Comment by Gvmmx** [comment]
> You need indium mod if you're using sodium mod.

thats crashes my game
