### ISSUE TITLE
Game keeps crashing when i make elevators or rope pulley elevators

### ISSUE THREAD

**Issue by MasonWilly** [Fabricators-of-Create/Create#1097]
### Describe the Bug

I think just the overall moving of blocks is breaking my game it only happens when i make the rope pulley actually move a platform and i just made an actual elevator and when i right clicked on the pulley it crashed my game and now will not let anyone rejoin the server
[latest.log](https://github.com/Fabricators-of-Create/Create/files/12514743/latest.log)

### Reproduction Steps

1.activating elevator contraption
2.game crashes
3.cant join back
...

### Expected Result

i want the elevators to work but now my game keeps crashing after i made one

### Operating System

windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

ad astra
alloy forgery
amecs
applied energistics
architectury API
armor abilities
azurelib
balm
bclib
better end
bookshelf
botany pots
botarium
cardinal components api
cavedweller
cloth config
compressed blocks
continuity 
dark utilities
elytraslot
emi
enderchest
endertanks 
entity culling 
expanded armor enchanting
expanded axe enchanting
expanded bow enchanting
expanded enderchest
expanded trident enchanting
expanded weapon enchanting
extended drawers
fabric api 
carpet modfabric language kotlin
farmers delight
feather fabric
forge config api port 
gecko lib
gilded armor
gravestones
Happiness is a warm gun
inventory profiles next
iron chests
item collectors
jamlib
jei
journey map
lambdynamiclights
lanterns belong on walls
libipn
lost features
mcpitanlibarch
mob lassos
mod menu
moonlight
more mob variants
owo.lib
packed up
patchouli
physics mod
pig pen fabric
puzzles .lib 
quick shulker
reinforced barrels
reinforced chests
reinforced shulker boxes
reinforced upgrade
resourceful config
resourceful lib
right click harvest
roughly enough items
runelic
shetiphiancore
shulker boxes tool tip
simple copper pipes
simply swords 
smart brain lib
starlight
statement
supermartijn642configlib
supermarijn642corelib
tempad
trashcans
travelers backpack
trinkets
ubes delight
upgradable backpack
villagers plus
waystones

**Comment by xXNightsecretXx** [comment]
Could you please send the crash log?

**Comment by TropheusJ** [comment]
starlight is incompatible and unnecessary
