### ISSUE TITLE
Crash with KubeJS when placing down a Basin

### ISSUE THREAD

**Issue by skippyall** [Fabricators-of-Create/Create#1098]
### Describe the Bug

When placing down a Basin with KubeJS installed, the game crashes with this crash report. (Issue on KubeJS: https://github.com/KubeJS-Mods/KubeJS/issues/697)
[crash-2023-09-06_16.04.17-client.txt](https://github.com/Fabricators-of-Create/Create/files/12538788/crash-2023-09-06_16.04.17-client.txt)

### Reproduction Steps

1. Install Create and KubeJS
2. Place down a Basin

### Expected Result

The Basin to be placeable like normal

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

KubeJS 2001.6.3-build.23

**Comment by MaxNeedsSnacks** [comment]
Note we don't modify anything about Create nor Fabric's transfer API, so I'm at a loss as to why this issue should be stemming from KubeJS' end? Maybe porting-lib or Create Fabric isn't up to speed with a new (breaking) change in Fabric Transfer API?

**Comment by skippyall** [comment]
Crashes with Fabric API v0.88.1+1.20.1 and v0.86.0+1.20.1.

**Comment by skippyall** [comment]
I got an other crash report in my modpack where this issue first occured to me. Maybe this is more helpful (although this can't be well reproduced) [crash-2023-09-08_09.48.35-server.txt](https://github.com/Fabricators-of-Create/Create/files/12557132/crash-2023-09-08_09.48.35-server.txt)

**Comment by skippyall** [comment]
I found the problem: ItemStackHandlerContainer from Porting Lib both extends from ItemStackHandler and implements Container. KubeJS' ContainerMixin injects an interator() method (inherited from InventoryKJS) and Porting Lib's ItemStackHandler inherits another iterator() method, so that Java doesn't know which one to call.

**Comment by LatvianModder** [comment]
This was probably leftover when every class was wrapped by KubeJS (old InventoryJS was iterable) and forgotten when porting, I will fix that
