### ISSUE TITLE
Some Create Recipes added by Datapacks don't display correctly in EMI

### ISSUE THREAD

**Issue by PersuGames** [Fabricators-of-Create/Create#1100]
### Describe the Bug

I've found an inconsistency which is most likely not meant to be a thing. From what I've seen some Create Datapack Recipes that use the chance variable in other recipes than washing (where it works correctly) don't display the chance and don't take it into account.

### Reproduction Steps

1. add a custom recipe with chance variable
2. look into emi for that recipe

### Expected Result

Both recipes should show the chance on the output yet only the create mod's recipe does and the custom one doesn't.

### Screenshots and Videos

![Zrzut ekranu 2023-09-07 230715](https://github.com/Fabricators-of-Create/Create/assets/67759479/b471c216-5007-405a-8fe8-0a1a02e3a408)
![Zrzut ekranu 2023-09-07 230343](https://github.com/Fabricators-of-Create/Create/assets/67759479/2cb5b58d-5eeb-40dc-be9c-7d934e95caee)

### Operating System

Win 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

EMI

**Comment by skippyall** [comment]
I don't think that chance has ever worked with compacting recipes in general.

**Comment by MbtMarco** [comment]
I think is EMI issue or u need specific addon for that

**Comment by PersuGames** [comment]
> I think is EMI issue or u need specific addon for that

EMI people told me to report it here as they aren't responsible for the compat

**Comment by TropheusJ** [comment]
pretty sure compacting doesn't support chances
