### ISSUE TITLE
ponder crash

### ISSUE THREAD

**Issue by Yoren7** [Fabricators-of-Create/Create#1101]
### Describe the Bug

the game crashes when i ponder in Fabric version

### Reproduction Steps

1.be in a minecraft world
2.have create
3.ponder
...

### Expected Result

i expected to get a quick overview of the block

### Operating System

windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
Well it works for me.
If you give 0 information, there's nothing I can tell you.
