### ISSUE TITLE
Game Crash when using Brass-Filter

### ISSUE THREAD

**Issue by Losi25** [Fabricators-of-Create/Create#1103]
### Describe the Bug

In the Recent release for MC 1.20.1 the Filter Tag for the vanilla Creative Mod tabs aren't possivle to use anymore. If you try to alter or save an old Filter with one of the old Arguments the Game Crashes. (Client and Server)
Please add the Creative-Tabs-Filter back. 

### Reproduction Steps

1.Create a Brass-Filter in for example 1.19.2 (Create 0.5.1) and add the Argument "is in the Cattegory Redstone" 
2.Update to 1.20.1 (Create 0.5.1)
3.Try to alter and save the Folter with the old Argument
...

### Expected Result

Game Crash

### Operating System

Windows 10 (Client and PC) 

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Server:
architectury 9.1.12 fabric
Cloth Config 11.1.106 fabric
Fabric api 0.87.0
Lithium-fabric-mc1.20.1-0.11.2
restart-server-1.2.0
Xaeros Minimap 23.7.0 Fabric 1.20
Client:
architectury 9.1.12 fabric
Cloth Config 11.1.106 fabric
continuity 3.0.0 beta 3
Fabric api 0.87.0
indium 1.0.21
Iris 1.6.4
Lithium-fabric-mc1.20.1-0.11.2
maililib Fabric 0.16.0
Minihud 0.27.0
Replay-mod 2.6.13
RoughlyEnoughItems 12.0.652
Sodium 0.4.10
Tweaker 0.17.0
Xaeros Minimap 23.7.0 Fabric 1.20

### Additional Context

Server and Client are on different PC, both crashed.

**Comment by Losi25** [comment]
[crash-2023-09-10_10.15.27-server.txt](https://github.com/Fabricators-of-Create/Create/files/12568173/crash-2023-09-10_10.15.27-server.txt)
Just wanted to add the Crash Report

**Comment by IThundxr** [comment]
happens on forge aswell
