### ISSUE TITLE
Create Fabric not working with latest verison of sodium

### ISSUE THREAD

**Issue by kaidenart** [Fabricators-of-Create/Create#1105]
### Describe the Bug

Game won't launch with latest version of Sodium.

### Reproduction Steps

1. Install Create Fabric
2. Install Sodium
3. Run Game
...

### Expected Result

Game wont run and you will get error code 1

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/69740669/80c5b102-8cae-4dd6-99a7-4d1e595a919c)

### Crash Report or Log

Prism Launcher version: 7.2 (official)   Launched instance in online mode  authserver.mojang.com resolves to:     [18.161.6.111, 18.161.6.63, 18.161.6.107, 18.161.6.124]  session.minecraft.net resolves to:     [2620:1ec:bdf::70, 2620:1ec:46::70, 13.107.213.70, 13.107.246.70]  textures.minecraft.net resolves to:     [2620:1ec:bdf::70, 2620:1ec:46::70, 13.107.246.70, 13.107.213.70]  api.mojang.com resolves to:     [2620:1ec:46::70, 2620:1ec:bdf::70, 13.107.246.70, 13.107.213.70]   Minecraft folder is: E:/Prism/instances/1.20.1 Create Fabric(1)/.minecraft   Java path is: C:/Program Files/Java/jdk-17/bin/javaw.exe   Java is version 17.0.6, using 64 (amd64) architecture, from Oracle Corporation.   Main Class:   net.fabricmc.loader.impl.launch.knot.KnotClient  Native path:   E:/Prism/instances/1.20.1 Create Fabric(1)/natives  Traits: traits XR:Initial traits FirstThreadOnMacOS  Libraries:   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.1/lwjgl-glfw-natives-windows-x86-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.1/lwjgl-glfw-natives-windows-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.1/lwjgl-jemalloc-natives-windows-x86-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows/3.3.1/lwjgl-jemalloc-natives-windows-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-windows-x86/3.3.1/lwjgl-natives-windows-x86-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-windows/3.3.1/lwjgl-natives-windows-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-windows-x86/3.3.1/lwjgl-openal-natives-windows-x86-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-windows/3.3.1/lwjgl-openal-natives-windows-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-windows-x86/3.3.1/lwjgl-opengl-natives-windows-x86-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-windows/3.3.1/lwjgl-opengl-natives-windows-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-windows-x86/3.3.1/lwjgl-stb-natives-windows-x86-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-windows/3.3.1/lwjgl-stb-natives-windows-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-x86/3.3.1/lwjgl-tinyfd-natives-windows-x86-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows/3.3.1/lwjgl-tinyfd-natives-windows-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/intermediary/1.20.1/intermediary-1.20.1.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/fabric-loader/0.14.22/fabric-loader-0.14.22.jar   C:/Users/jwc/AppData/Roaming/PrismLauncher/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar  Native libraries:  Mods:   [✔] 3dskinlayers-fabric-1.5.4-mc1.20.1   [✔] AdvancementPlaques-1.20.1-fabric-1.4.11   [✔] AmbientSounds_FABRIC_v5.2.22_mc1.20.1   [✔] appleskin-fabric-mc1.20-2.5.0   [✔] architectury-9.1.12-fabric   [✔] balm-fabric-1.20-7.0.7   [✔] bclib-3.0.13   [✔] bettercombat-fabric-1.7.3+1.20.1   [✔] better-end-4.0.10   [✔] BetterF3-7.0.1-Fabric-1.20.1   [✔] better-nether-9.0.9   [✔] blur-3.1.0   [✔] c2me-fabric-mc1.20.1-0.2.0+alpha.10.100   [✔] chat_heads-0.10.20-fabric-1.20   [✔] CITResewn-1.1.3+1.20   [✔] cloth-config-11.1.106-fabric   [✔] combatroll-fabric-1.2.1+1.20.1   [✔] comforts-fabric-6.3.3+1.20.1   [✔] continuity-3.0.0-beta.3+1.20.1   [✔] Controlling-fabric-1.20.1-12.0.2   [✔] createaddition-fabric+1.20.1-0.9.0   [✔] createchunkloading-1.6.0-fabric   [✔] create-fabric-0.5.1-d-build.1161+mc1.20.1   [✔] CreativeCore_FABRIC_v2.10.28_mc1.20.1   [✔] cullleaves-fabric-3.2.0   [✔] dynamic-fps-3.1.0+minecraft-1.20.0   [✔] EasyAnvils-v8.0.1-1.20.1-Fabric   [✔] EasyMagic-v8.0.1-1.20.1-Fabric   [✔] EasyShulkerBoxes-v8.0.0-1.20.1-Fabric   [✔] elytra_trinket-1.0.3   [✔] enhancedblockentities-0.9+1.20   [✔] entity_model_features_fabric_1.20-0.RC.2   [✔] entity_texture_features_fabric_1.20-4.5.1   [✔] entityculling-fabric-1.6.2-mc1.20   [✔] essential_1-2-2_fabric_1-20-1   [✔] fabric-api-0.88.1+1.20.1   [✔] fabric-language-kotlin-1.10.10+kotlin.1.9.10   [✔] fallingleaves-1.15.3+1.20.1   [✔] FallingTree-1.20.1-4.3.0   [✔] farmers-delight-fabric-mc1.20.1-1.4.2   [✔] farmersknives-3.0.2   [✔] Farmersrespite-Fabric-2.3.3   [✔] figura-0.1.2+1.20.1   [✔] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric   [✔] fusion-1.0.5a-fabric-mc1.20   [✔] HangGlider-v8.0.1-1.20.1-Fabric   [✔] Iceberg-1.20.1-fabric-1.1.15   [✔] indium-1.0.25+mc1.20.1   [✔] iris-mc1.20.1-1.6.8   [✔] Jade-1.20-fabric-11.6.0   [✔] jei-1.20.1-fabric-15.2.0.27   [✔] JustEnoughFarmersRecipes-1.20.1-1.0.1   [✔] krypton-0.2.3   [✔] lambdynamiclights-2.3.1+1.20.1   [✔] lazydfu-0.1.3   [✔] LegendaryTooltips-1.20.1-fabric-1.4.4   [✔] lithium-fabric-mc1.20.1-0.11.2   [✔] memoryleakfix-fabric-1.17+-1.1.2   [✔] modelfix-1.14-fabric   [✔] modmenu-7.2.2   [✔] moonlight-1.20-2.8.20-fabric   [✔] moreculling-1.20.1-0.19.0   [✔] MouseTweaks-fabric-mc1.20-2.25   [✔] notenoughanimations-fabric-1.6.4-mc1.20   [✔] player-animation-lib-fabric-1.0.2-rc1+1.20   [✔] players-drop-heads-15.1   [✔] Prism-1.20.1-fabric-1.0.5   [✔] PuzzlesLib-v8.0.24-1.20.1-Fabric   [✔] rechiseled-1.1.2a-fabric-mc1.20   [✔] rechiseledcreate-1.0.0-fabric-mc1.20   [✔] reeses_sodium_options-1.6.5+mc1.20.1-build.95   [✔] Searchables-fabric-1.20.1-1.0.1   [✔] sliceanddice-fabric-3.0.0   [✔] sodium-extra-0.5.1+mc1.20.1-build.112   [✔] sodium-fabric-mc1.20.1-0.5.2   [✔] starlight-1.1.2+fabric.dbc156f   [✔] Steam_Rails-1.5.1+fabric-mc1.20.1   [✔] supermartijn642configlib-1.1.8-fabric-mc1.20   [✔] supermartijn642corelib-1.1.12d-fabric-mc1.20   [✔] supplementaries-1.20-2.5.28-fabric   [✔] trinkets-3.7.1   [✔] VisualWorkbench-v8.0.0-1.20.1-Fabric   [✔] voicechat-fabric-1.20.1-2.4.24   [✔] yet-another-config-lib-fabric-3.1.1+1.20  Params:   --username  --version 1.20.1 --gameDir E:/Prism/instances/1.20.1 Create Fabric(1)/.minecraft --assetsDir C:/Users/jwc/AppData/Roaming/PrismLauncher/assets --assetIndex 5 --uuid  --accessToken  --userType  --versionType release  Window size: max (if available)  Launcher: standard  Java Arguments: [-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]   Minecraft process ID: 1436   [14:15:48] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.22 [14:15:49] [ForkJoinPool-1-worker-2/WARN]: Mod entity_model_features uses the version 0.RC.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'RC'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version [14:15:49] [main/WARN]: Mod resolution failed [14:15:49] [main/INFO]: Immediate reason: [NEG_HARD_DEP create 0.5.1-d-build.1161+mc1.20.1 {breaks sodium @ [>=0.5.0]}, HARD_DEP indium 1.0.25+mc1.20.1 {depends sodium @ [0.5.2]}, ROOT_FORCELOAD_SINGLE create 0.5.1-d-build.1161+mc1.20.1, ROOT_FORCELOAD_SINGLE indium 1.0.25+mc1.20.1] [14:15:49] [main/INFO]: Reason: [NEG_HARD_DEP create 0.5.1-d-build.1161+mc1.20.1 {breaks sodium @ [>=0.5.0]}] [14:15:49] [main/INFO]: Fix: add [], remove [createaddition 0.9.0], replace [[create 0.5.1-d-build.1161+mc1.20.1] -> add:create 0.5.1-d ([[0.5.1-d,?)])] [14:15:49] [main/ERROR]: Incompatible mod set! net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set! A potential solution has been determined: 	 - Remove mod 'Create Crafts & Additions' (createaddition) 0.9.0 (E:\Prism\instances\1.20.1 Create Fabric(1)\.minecraft\mods\createaddition-fabric+1.20.1-0.9.0.jar). 	 - Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with version 0.5.1-d or later that is compatible with: 		 - sodium 0.5.2 Unmet dependency listing: 	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.2! 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.22.jar:?] 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.22.jar:?] 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.22.jar:?] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.22.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?] 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[?:?] 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[?:?] 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[?:?] Process exited with code 1. Clipboard copy at: 10 Sep 2023 14:16:02 -0700

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/69740669/64f9cc7d-bf24-4a9b-8cbe-6c6f39b79374)
![image](https://github.com/Fabricators-of-Create/Create/assets/69740669/a3971a44-dd92-423d-95cb-955af50581f7)

**Comment by EthanRStokes** [comment]
duplicate of #1039

**Comment by mindryder** [comment]
Same issue
