### ISSUE TITLE
EMI incorrectly displaying potion recipes

### ISSUE THREAD

**Issue by PersuGames** [Fabricators-of-Create/Create#1106]
### Describe the Bug

The fluid version of a potion is missing in emi interface while working as intended in practice

### Reproduction Steps

1.Run latest EMI and Create Fabric together
2.open any recipe involving potion brewing

### Expected Result

the fluids should have correct names and colors corresponding to their potions as they do in JEI for example.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/67759479/a9f2caa5-f84a-409a-9088-170f4f741c13)

### Operating System

Win 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

EMI

**Comment by MrRedstone4848** [comment]
emilyploszaj/emi#433

**Comment by IThundxr** [comment]
For me: Only affects 1.20.1, tested on patch f
