### ISSUE TITLE
Game Crashes when using the mechanical bearing

### ISSUE THREAD

**Issue by HenryBGit** [Fabricators-of-Create/Create#1107]
### Describe the Bug

My game crashed while I was trying to use the mechanical bearing to make a door. It crashed as soon as I pushed the button to activate the bearing. It crashes with the Starlight mod installed. 

### Reproduction Steps

1. Place a mechanical bearing with a sequenced gearshift
2. Place some blocks on the mechanical bearing
3. Place a button on the gearshift
4. Then activate the button

![2023-09-11_16 49 23](https://github.com/Fabricators-of-Create/Create/assets/79766960/b1ed1984-5082-4772-8a0b-eab28c630e74)

### Expected Result

When I clicked the button I was expecting to see the blocks turn however when I pressed the button the game instead crashed

### Screenshots and Videos

 This was the error message that I got after the game had crashed
 
 
![image](https://github.com/Fabricators-of-Create/Create/assets/79766960/f53f488c-4521-4eda-bf56-6f7c3f378dcf)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

I was using the fabulously optimized modpack, however I removed fabrishot and fastquit. I also changed the versions for sodium, indium, resse's sodium options and sodium extra's, these mods were downgraded to their earliest versions so they could work with the create mod. 

I also added the chipped mod, worldedit, xaeros minimap and worldmap, litematica, phantom flames and wriath waystones.

### Additional Context
I figured out that the mod it crashes with is the starlight mod version Starlight 1.1.2 1.20.x (Fabric)

**Comment by Steveplays28** [comment]
Seems like an issue with Starlight, here's a [log file (mclo.gs)](https://mclo.gs/QbJL4VP).

**Comment by Poopooracoocoo** [comment]
There's no point in Create supporting Starlight with Minecraft 1.20 now that Starlight has become redundant.
