### ISSUE TITLE
Potato cannon doesn’t show launched veggies

### ISSUE THREAD

**Issue by ruguysgoingtrickortreating** [Fabricators-of-Create/Create#1108]
### Describe the Bug

Crafted myself a potato cannon, and to my great dismay, the veggies didn't show up when launched, making it incredibly hard to aim. Literally Unplayable

Only mods were Fabric API and Create

### Reproduction Steps

1. Open Minecraft with as little mods as Fabric API + Create Fabric
2. Try to launch funny vegetables
3. Day Ruined
...

### Expected Result

I can see the potatoes slam into innocent animals

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

None

**Comment by TropheusJ** [comment]
closing in favor of #1132
