### ISSUE TITLE
Server Crash Upon Travelling with a Train to the Nether.

### ISSUE THREAD

**Issue by StevenG5** [Fabricators-of-Create/Create#1109]
### Describe the Bug

A player has reported that taking the train into the nether can cause a crash. We run a pretty large server and we've never had an issue like this before, I have 5 crash logs from the day of the error as proof. We have no idea how to replicate it, as whenever someone goes through the portal or is near the train on the otherside, it crashes the entire server. 

(All 5 crash reports are included in the paste-bin with some spaces to separate them)

### Reproduction Steps

1. We can't get close enough to replicate the bug but this is what we know:
2. A train was driven into the Nether from the Overworld
3. The upon entering the portal, the server was completely shutdown.
4. The server was able to recover, but whenever this player logs in, they crash the server again.
5. We are left to believe they are stuck somewhere in the nether on the otherside of the portal, and have no idea what to do to fix it. 
...

### Expected Result

Not crash the server, as it has behaved countless times before. 

### Crash Report or Log

https://pastebin.com/mF4eyGTN

### Operating System

Windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

[Create Goggles (Create Plus) (by Robocraft999)](https://www.curseforge.com/minecraft/mc-mods/create-goggles)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Roughly Enough Professions (REP) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-professions-rep)
[Roughly Enough Loot Tables (by GrigLog)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-loot-tables)
[Roughly Enough Resources (by theorbagain)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-resources)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Tom's Simple Storage Mod (Fabric) (by tom54541)](https://www.curseforge.com/minecraft/mc-mods/toms-storage-fabric)
[ServerCore (by Wesley8081)](https://www.curseforge.com/minecraft/mc-mods/servercore)
[MemoryLeakFix (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Debugify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/debugify)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Fabric Waystones (by LordDeatHunter)](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones)
[FerriteCore (Fabric) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric)
[BCLib (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/bclib)
[FTB Teams (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric)
[Starlight (Fabric) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight)
[YetAnotherConfigLib (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/yacl)
[BetterNether (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betternether)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Ingredient Extension API (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/ingredient-extension-api)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Inventory Sorting (by Kyrptonaught)](https://www.curseforge.com/minecraft/mc-mods/inventory-sorting)
[Farmer's Knives [Fabric] (by ianm1647)](https://www.curseforge.com/minecraft/mc-mods/farmers-knives)
[Zoomify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/zoomify)
[Vanilla Hammers (by Draylar1)](https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Dark Loading Screen (by Neecko5b84)](https://www.curseforge.com/minecraft/mc-mods/dark-loading-screen)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Smoke Suppression (by supersaiyansubtlety)](https://www.curseforge.com/minecraft/mc-mods/smoke-suppression)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Origins (Fabric) (by Apace)](https://www.curseforge.com/minecraft/mc-mods/origins)
[Dynamic FPS (by juliand665)](https://www.curseforge.com/minecraft/mc-mods/dynamic-fps)
[Patchouli (Fabric/Quilt) (by williewillus)](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
[TerraBlender (Fabric) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric)
[FTB Library (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric)
[FTB Ultimine (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-fabric)
[Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[DeepslateCutting (by NoComment1105)](https://www.curseforge.com/minecraft/mc-mods/deepslatecutting)
[Lithium (Fabric) (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/lithium)
[Expanded Storage (by MessyEllie)](https://www.curseforge.com/minecraft/mc-mods/expanded-storage)
[Extra Thicc Packets (by JaselUmena)](https://www.curseforge.com/minecraft/mc-mods/extra-thicc-packets)
[Rhino (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/rhino)
[FTB Chunks (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-fabric)
[oωo (owo-lib) (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
[FallingTree (Forge&Fabric) (by rakambda)](https://www.curseforge.com/minecraft/mc-mods/falling-tree)
[Cull Leaves (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/cull-leaves)
[WTHIT (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Falling Leaves (Fabric) (by RandomMcSomethin)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric)
[BetterEnd (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betterend)
[FastAnim (by AViewFromTheTop)](https://www.curseforge.com/minecraft/mc-mods/fastanim)
[You're in Grave Danger (by b1n_ry)](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[LazyDFU (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/lazydfu)
[Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[Roughly Enough Items Fabric/Forge (REI) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
[Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
[Krypton (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/krypton)
[Create Fabric (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
[Expanded Delight [Fabric] (by ianm1647)](https://www.curseforge.com/minecraft/mc-mods/expanded-delight)
[Building Wands (by nicguzzo)](https://www.curseforge.com/minecraft/mc-mods/building-wands)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)

**Comment by StevenG5** [comment]
No one can get anywhere near this issue. As soon as we get near that chunk the server crashes and if they try to reconnect they cause another server shutdown. This is a catastrophe.

**Comment by EvieTheOwl** [comment]
https://github.com/Creators-of-Create/Create/issues/4892#

also includes info on how to fix it. Yeah the train is given an invalid non numerical position which should never happen
