### ISSUE TITLE
Sodium 0.5.0 incompatibility, here's the list of working Sodium 0.4.10 addons:

### ISSUE THREAD

**Issue by wanesty** [Fabricators-of-Create/Create#1110]
the only fix while we wait for a Flywheel/Sodium is to downgrade back to Sodium 0.4.10, however you're probably using [Reese's Sodium Options](https://modrinth.com/mod/reeses-sodium-options), [Indium](https://modrinth.com/mod/indium) etc

so here's a list of Sodium addons compatible with the 0.4.10:

[ImmediatelyFast-1.2.3+1.20.1.jar](https://modrinth.com/mod/immediatelyfast/version/1.2.3+1.20.1)
[indium-1.0.21+mc1.20.1.jar](https://modrinth.com/mod/indium/version/1.0.21+mc1.20.1)
[iris-mc1.20-1.6.4.jar](https://modrinth.com/mod/iris/version/1.6.4+1.20)
[memoryleakfix-fabric-1.17+-1.1.2.jar](https://modrinth.com/mod/memoryleakfix/version/v1.1.2)
[reeses_sodium_options-1.6.3+mc1.20.1-build.92.jar](https://modrinth.com/mod/reeses-sodium-options/version/mc1.20.1-1.6.3)
[sodium-extra-0.4.27+mc1.20.1-build.110.jar](https://modrinth.com/mod/sodium-extra/version/mc1.20.1-0.4.27)
[sodium-fabric-mc1.20-0.4.10+build.27.jar](https://modrinth.com/mod/sodium/version/mc1.20-0.4.10)

**Comment by wanesty** [comment]
take your time king

**Comment by drakosoldier298** [comment]
problem with what you linked.
![image](https://github.com/Fabricators-of-Create/Create/assets/30358222/ad9c3fe9-e519-421d-ae73-e2c329f4ba56)

**Comment by wanesty** [comment]
can reproduce, only an issue if you're in a world, however everything is working fine it's only a UI issue
<br>

**edit** : this is only an issue with [Reese's Sodium Options](https://modrinth.com/mod/reeses-sodium-options), either get rid of it if you don't mind the default UI or deal with having to get back to the main menu and/or it being weird ingame

not ideal but it's the only version of Reese's Sodium Options compatible with the 4.10 
(it could be backported, but if someone have the knowledge to backport it they are likely able to just help with flywheel)

**Comment by CodeKartonka** [comment]
for me, i'm on the Create-Fabric-0.5.1-d-build.1161+mc1.20.1, u can edit fabric.mod.json, the file is in create (open it with 7zip)

  },
  "breaks": {
    "optifabric": "*",
    "colormatic": "\u003c\u003d3.1.1",
    "iris": "\u003c\u003d1.2.5",
    "sodium": "\u003e\u003d0.5.3"
  },
  
  [Lib]fabric-api-0.88.1+1.20.1.jar
  [Lib]fabric-language-kotlin-10.10+kotlin.1.9.10.jar
  [Optimization]exordium-fabric-1.2.1-mc1.20.1.jar
  [Optimization]ferritecore-6.0.0-fabric.jar
  [Optimization]ImmediatelyFast-1.2.4+1.20.1.jar
  [Optimization]indium-0.25+mc1.20.1.jar
  [Optimization]iris-flywheel-compat-1.20.1-0.2.1.jar
  [Optimization]iris-mc1.20.1-1.6.8.jar
  [Optimization]lithium-fabric-mc1.20.1-0.11.2.jar
  [Optimization]memoryleakfix-fabric-1.17+-1.1.2
  [Optimization]reeses_sodium_options-6.5+mc1.20.1-build.95
  [Optimization]sodium-extra-0.5.1+mc1.20.1-build.112.jar
  [Optimization]sodium-fabric-mc1.20.1-0.5.2.jar
  [Optimization]sodium-shadowy-path-blocks-3.2.1.jar
  [Optimization]starlight-1.2+fabric.dbc156f.jar
  [Optimization]threadtweak-fabric-1.20.1-0.1.0.jar
  
 for me is working fine :-)

**Comment by Allexio** [comment]
> the only fix while we wait for a Flywheel/Sodium is to downgrade back to Sodium 0.4.10, however you're probably using [Reese's Sodium Options](https://modrinth.com/mod/reeses-sodium-options), [Indium](https://modrinth.com/mod/indium) etc
> 
> so here's a list of Sodium addons compatible with the 0.4.10:
> [...]

This does not work if you are using Supplementaries (signposts) or other mods that add custom overworld content (Farmer's delight for example) as it renders the chunk invisible (game-breaking):
![image](https://github.com/Fabricators-of-Create/Create/assets/59694328/6cd88935-1e3c-44d1-bc1b-a8665f5ee5fe)


> for me, i'm on the Create-Fabric-0.5.1-d-build.1161+mc1.20.1, u can edit fabric.mod.json, the file is in create (open it with 7zip)
> 
> }, "breaks": { "optifabric": "*", "colormatic": "\u003c\u003d3.1.1", "iris": "\u003c\u003d1.2.5", "sodium": "\u003e\u003d0.5.3" },
> 
> for me is working fine :-)

This does not work well because it does this when placing waterwheels (which must be the reason it was marked as incompatible in the first place):
![image](https://github.com/Fabricators-of-Create/Create/assets/59694328/f6c1cdf2-649e-4a40-a299-d862166be749)
Notice the FPS top left dropped down to 16.

When disabling shaders, the waterwheels just disappear out of existence:
![image](https://github.com/Fabricators-of-Create/Create/assets/59694328/faf4afd0-d613-4450-80e0-290de712c4a3)

Hope it clears up any confusion about these workarounds and how they might work for you depending on your use-case.

**Comment by wanesty** [comment]
disabling flywheel with

	/flywheel backend off

should most likely fix that

**Comment by CodeKartonka** [comment]
no idea?
![2023-09-25_18 07 26](https://github.com/Fabricators-of-Create/Create/assets/12899638/e33b8e51-acc0-4d78-8aca-bf24e0beab93)
i got 5 fps with /flywheel backend off turn it bag again i have same fps and no 
![2023-09-25_18 08 20](https://github.com/Fabricators-of-Create/Create/assets/12899638/f3d78fc6-9de6-4210-938c-19db4e9ebc07)
turn it on, again i have same bug. but same fps. so for me is better with flywheel but dont use the comands from flywheel :D
![2023-09-25_18 08 56](https://github.com/Fabricators-of-Create/Create/assets/12899638/cea3835c-8b22-4dff-aeba-2042be1fe397)

**Comment by wanesty** [comment]
shaders, on any version of minecraft, iris, optifine or create are rarely compatible with flywheel

**Comment by TropheusJ** [comment]
linked on the main issue, closing

**Comment by Misaki-Akeno** [comment]
Curve rail way would disapper after reloading (F3+Q)
![image](https://github.com/Fabricators-of-Create/Create/assets/26163328/0901d6b6-d52e-4967-aa11-49980a7e2479)

**Comment by Poopooracoocoo** [comment]
If you're using Sodium 0.4.10 and have Indium 1.0.21, make sure you use Fabric API 0.88.1. 
That version of Indium is not compatible with higher versions of Fabric API.

**Comment by Misaki-Akeno** [comment]
I am using sodium 0.5.3 and iris and i changed the restriction of version. It works well and railway become visible after disabling flywheel.

**Comment by MaoDoBan** [comment]
I found a create-fabric fork that fix the incompatibility:
https://modrinth.com/mod/create-fabric-sodium-fix

**Comment by NolanHewitt** [comment]
> I found a create-fabric fork that fix the incompatibility: https://modrinth.com/mod/create-fabric-sodium-fix

YOOOOO it works! It's incompatible with dash-loader if anyone else was using that, but its a worthy trade off to get create back.

**Comment by jonask028** [comment]
As far as i can tell the issue isn't with sodium or flywheel, its with the iris/oculus flywheel compat mod

I followed the steps in [this post](https://github.com/Fabricators-of-Create/Create/issues/1039) and had no issues until i installed the iris/oculus flywheel compat and loaded into the world. previous attempts at recreating the bug all failed with the compat mod not installed.

**Comment by Misaki-Akeno** [comment]
if you are using shaders, the flywheel will be disabled. And the iris/oculus flywheel compat mod will enable the flywheel with shaders. the problem is between flywheel and sodium

**Comment by jonask028** [comment]
That makes a lot of sense, my bad.

**Comment by wanesty** [comment]
can i just allow myself and say that it's so fucking hilarious that a fabric port of a forge mod is waiting on a forge port of a fabric mod 
(flywheel is waiting for Rubidium to update so the fabric branch of flywheel can update to the corresponding sodium version)

**Comment by rilakuma123** [comment]
Rubidium 0.7.0 was the update that brought Sodium 0.5's changes to it. And Flywheel is already compatible with Rubidium 0.7.0. https://github.com/Jozufozu/Flywheel/commits/1.20/dev/

I believe we're now waiting for the Fabric fork of Flywheel to get those changes ported from the original/Forge version. 
A problem is that they currently support 1.20.1, 1.19.2 and 1.18.2. https://discord.com/channels/620934202875183104/976100492243501106/1162564469130547280 goes into more detail

**Comment by wanesty** [comment]
>Fabric fork of Flywheel

:point_up: :nerd_face: it's erm, just a branch on the flywheel repo

**Comment by ryouzue** [comment]
> YOOOOO it works! It's incompatible with dash-loader if anyone else was using that, but its a worthy trade off to get create back.

tbh I don't rly consider it a worthy trade if you can't use [Create: Interactive](https://modrinth.com/mod/interactive) along with it to enhance the Create experience
An issue from a mere [version name change](https://github.com/Treetrain1/Create/issues/14) "build.5"🗡️🗡️

**Comment by RowanSkie** [comment]
> > YOOOOO it works! It's incompatible with dash-loader if anyone else was using that, but its a worthy trade off to get create back.
> 
> tbh I don't rly consider it a worthy trade if you can't use [Create: Interactive](https://modrinth.com/mod/interactive) along with it to enhance the Create experience An issue from a mere [version name change](https://github.com/Treetrain1/Create/issues/14) "build.5"🗡️🗡️

Even if the version name change is fixed, Interactive requires Valkyrian Skies 2, which currently doesn't support Sodium 0.5 unfortunately (https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/556). It still works for me though.

**Comment by rilakuma123** [comment]
> > YOOOOO it works! It's incompatible with dash-loader if anyone else was using that, but its a worthy trade off to get create back.
> 
> tbh I don't rly consider it a worthy trade if you can't use [Create: Interactive](https://modrinth.com/mod/interactive) along with it to enhance the Create experience An issue from a mere [version name change](https://github.com/Treetrain1/Create/issues/14) "build.5"🗡️🗡️

It's very easy to work around that by using a Fabric Dependency Override.

**Comment by rilakuma123** [comment]
https://www.reddit.com/r/fabricmc/comments/1aiuy7w/sodium_0410_mods_for_minecraft_1201/ is a really comprehensive list
