### ISSUE TITLE
Ticking block entity

### ISSUE THREAD

**Issue by Grimmo143** [Fabricators-of-Create/Create#1111]
### Describe the Bug

When we log onto the world it instantly crashes the world as we render in the area we are in

### Reproduction Steps

1.Place Item drain with lava buckets incoming from assembly line
2.placed pipe directly under item drain to drain lava
3.pipe is connected to hose pullys that dump lava into hole
...

### Expected Result

I expected lava to drain and buckets to go back onto the conveyer belts and go back into the nether

### Crash Report or Log

https://gist.github.com/Grimmo143/558b7a64d97d74ba87465e7b16d12238

### Operating System

Windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

**Comment by Grimmo143** [comment]
btw we just noticed this issue too
-- Block entity being ticked --
Details:
    Name: create:glass_fluid_pipe // com.simibubi.create.content.fluids.pipes.StraightPipeBlockEntity
    Block: Block{create:glass_fluid_pipe}[alt=false,axis=x,waterlogged=false]
    Block location: World: (17,-33,-1864), Section: (at 1,15,8 in 1,-3,-117; chunk contains blocks 16,-64,-1872 to 31,319,-1857), Region: (0,-4; contains chunks 0,-128 to 31,-97, blocks 0,-64,-2048 to 511,319,-1537)
    Block: Block{create:glass_fluid_pipe}[alt=false,axis=x,waterlogged=false]
    Block location: World: (17,-33,-1864), Section: (at 1,15,8 in 1,-3,-117; chunk contains blocks 16,-64,-1872 to 31,319,-1857), Region: (0,-4; contains chunks 0,-128 to 31,-97, blocks 0,-64,-2048 to 511,319,-1537)

**Comment by TropheusJ** [comment]
this should be fixed with patch f
