### ISSUE TITLE
Create 0.5.1(1.19.2) not compatible with Immersive-Weathering v.1.19.2-1.2.10 

### ISSUE THREAD

**Issue by ebaystudio** [Fabricators-of-Create/Create#1113]
### Describe the Bug

Game crashes when updating Immersive-Weathering to version 1.2.10. Last working version is. 1.2.9.

> The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create'!

[crash-2023-09-12_22.54.41-client.txt](https://github.com/Fabricators-of-Create/Create/files/12605016/crash-2023-09-12_22.54.41-client.txt)

### Reproduction Steps

1.with create 0.5.1c 
2.Installing/updating to Immersive-Weathering v.1.19.2-1.2.10 
3.=crash
...

### Expected Result

Not to crash....

### Operating System

widows 10 

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

Better Minecraft Fabric modpack 1.19.2 most recent version.

**Comment by TropheusJ** [comment]
terrestria

**Comment by ebaystudio** [comment]
How is this closed as completed? Was there an update to 1.19.2 and it's not up on Curseforge yet? And Terrestria hasn't updated since June. I'm assuming its a pass-the-buck thing so you closed it? No offense just my impression.

**Comment by TropheusJ** [comment]
Terrestria is crashing, create is uninvolved
