### ISSUE TITLE
Fabric Create v1.20.1

### ISSUE THREAD

**Issue by romanempire12** [Fabricators-of-Create/Create#1114]
### Describe the Bug

Fabric Create v1.20.1 is not compatible with the latest version of Sodium 0.5.2

### Reproduction Steps

When downloading modrinth's sodium 0.5.2 a crash error appears stating that the create v1.20.1 is not supported with the lastest version of sodium

### Expected Result

I expected them to be compatible with each other.

### Crash Report or Log

https://mclo.gs/p0qfZYg

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TheZennou** [comment]
Downgrade sodium and all dependencies to pre-1.5.0 sodium and it'll work.
Not ideal, hoping for an update.

**Comment by LittleCircleOO** [comment]
duplicate of #1039

**Comment by SirTwsted** [comment]
I get the same error.
I was forced to disable create and 11 addons for create mod.
When I go back to v0.4.10 of Sodium,  then other mods starts screaming.
I'll wait for an update  😋
