### ISSUE TITLE
Broken advancements after updating from 1.18.2 to 1.19.2

### ISSUE THREAD

**Issue by RareScrap** [Fabricators-of-Create/Create#1115]
### Describe the Bug

After replacing `create-fabric-0.5.0.i-1016+1.18.2.jar` with `create-fabric-0.5.1-b-build.1089+mc1.19.2.jar` I faced **A LOT** (368) of missing advancements.

I don't want my players to lose they advancements. So I think this bug may lead to progression losses on servers and singe player worlds after update.

### Reproduction Steps

1. Setup a Minecraft 1.18.2 dedicated fabric server
2. Install `create-fabric-0.5.0.i-1016+1.18.2.jar` on the server and client
3. Join server
4. Give all advancements to player using `/advancement grant @a everything`
5. Shutdown server
6. Update the server to 1.19.2
7. Install `create-fabric-0.5.1-b-build.1089+mc1.19.2.jar` on the server and client
8. Join server with 1.19.2 client
9. See a console madness

### Expected Result

All advancements recognize correctly

### Crash Report or Log

https://pastebin.com/n5SxY2Ui

### Operating System

CentOS 7

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by RareScrap** [comment]
Bump

**Comment by TropheusJ** [comment]
advancements were changed. not a bug

**Comment by RareScrap** [comment]
> advancements were changed. not a bug

So I can safely remove them and this wouldn't affect the user's progress?

**Comment by RareScrap** [comment]
Data migration tool won't be provided. Based on Discrord discussion (starts [here](https://discord.com/channels/620934202875183104/620937113554124801/1156984157319209071)):

> [keeping progress doesn't make sense](https://discord.com/channels/620934202875183104/620937113554124801/1156984455433568346)
> -- <cite>Tropheus Jay</cite>

> [And honestly it'd probs be a waste of time to data fixer advancements](https://discord.com/channels/620934202875183104/620937113554124801/1156989241616777247)
> -- <cite>IThundxr || Steam 'n' Rails</cite>

Moreover, you will most likely face this issue during version update:

> [You updated from 1.18 -> 1.19](https://discord.com/channels/620934202875183104/620937113554124801/1156986082865455216)
> [2 very different versions so this is kinda expected](https://discord.com/channels/620934202875183104/620937113554124801/1156986116193407066)
> -- <cite>IThundxr || Steam 'n' Rails</cite>

So you have several options:
1) Drop unrecognized advancements (IMHO, it's not so bad because players will lose only craft recipes)
2) Manually migrate broken advancements like this:
In `0.5.0.i` there was such an advancement:
```
"create:recipes/create.palettes/cut_diorite_bricks_from_diorite_stonecutting": {
    "criteria": {
      "has_diorite": "2023-08-30 02:41:37 -0400"
    },
    "done": true
  },
```

And in `0.5.1.b` it's changed to this:
```
"create:recipes/create.palettes/cut_diorite_bricks_from_stone_types_diorite_stonecutting": {
    "criteria": {
      "has_stone_types_diorite": "2023-08-30 02:41:37 -0400"
    },
    "done": true
  },
```
3) Develop and maintain your own custom datafixer

Hope the development team will value their player data more in the future.
