### ISSUE TITLE
Elevator activates the floor below

### ISSUE THREAD

**Issue by Katranune** [Fabricators-of-Create/Create#1116]
### Describe the Bug

Whenever i send an elevator to the third floor (out of 4) (3 being the highest with 1 negative)

the elevator activates the contact below it causing it to move to the 2nd floor

this only happens when i have redstone line connecting to a door (though the 2nd floor DOES light up as if it was activated)

i have no clue why

### Reproduction Steps

1.make elevator
2.add floor
3.add redstone line to door
4. call/send elevator to 2nd floor

(this is all guesswork it might only happen here)

### Expected Result

2nd floor does not get activated when elevator is on third floor

### Screenshots and Videos

![2023-09-16_23 30 12](https://github.com/Fabricators-of-Create/Create/assets/142047833/1ff0ba56-cfd4-4911-90fa-834eaa1f7d14)
![2023-09-16_23 32 29](https://github.com/Fabricators-of-Create/Create/assets/142047833/fe1864e3-4a38-4afa-858a-43a739b09398)
![2023-09-16_23 32 42](https://github.com/Fabricators-of-Create/Create/assets/142047833/664c2eca-1ec5-42e3-a14d-b9dea8c716b2)

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Indium
Moonlight Lib
Alternate Origin GUI
Appleskin
Athena
Backpacked (Fabric)
Better Archeology
Better Days
Better Smithing Table
Better Trim Tooltips
Better Trims
Chimes
Chipped
Cloth Config API (Fabric/Forge)
Collective
Comforts (Fabric/Forge/Quilt)
Continuity
Controlling
CorgiLib
Create Fabric
Create Slice & Dice
Create: Extended Cogwheels Fabric
Cristel Lib
Cupboard
Diamond In the Rough (as in obsidian)
Easy Anviles [Forge & Fabric]
Easy Elytra Takeoff
Easy Magic [Fabric & Forge]
EMI
EMI Extra Integrations
End remastered [Fabric]
Enhanced Celestials(Fabric) - Blood Moons & Harvest Moons
Enhanced Mob Spawners
ESSENTIAL Mod
Explorify - Dungeons & Structures
Extra Origins
Fabric API
Fabric Languages Kotlin
Farmers Delight [Fabric]
Forge Config API port [Fabric]
Forge Config Screens [Forge & Fabric]
FPS Reducer
Framework (Fabric)
Friends&Foes (Fabric) (Copper Golem, Glare, Moobloom, Iceologer, Barnacle, Wildfire, Illusioner, Rascal and Tuff Golem)
Fusion (Connected Textures)
Geophilic - Biome Overhauls
Goblin Traders [Fabric]
Grass Overhaul (Sod)
Guarding
Head in the Clouds
High-Speed Rail
Highlight
Icarus
Iris Shaders
LambDynamicLights
MES - Moog's End Structures
MidnightLib
Mod Menu
Origins (Fabric)
Origins Classes
Pehkui
Puzzles Lib [Forge & Fabric]
Recipe Book Delight
Recipe Book is Pain
Resourceful Lib
Savage Ender Dragon[Forge/Fabric]
Searchables
Simple Voice Chat
Sodium
Spyglass Astronomy
Stacked Armor Trims
Starter Kit
SuperMartijn642's Config Lib
SuperMartijn642's Core Lib
The Lost Castle [Fabric]
Towns and Towers
Trinkets (Fabric)
Village Spawn Point
Visual Workbench [Forge & Fabric]
Xaero's Minimap
Xaero's World Map
YetAnotherConfigLib
YUNG's API
YUNG's Better End Island (Fabric)
YUNG's Better Mineshafts (Fabric)
YUNG's Better Nether Fortress (Fabric)
YUNG's Better Extras (Fabric)

Modrinth Mods not listed on curseforge mod list:

Better Clouds
Create Mod Trims

### Additional Context

i have no clue what could even cause this

**Comment by Katranune** [comment]
(sorry for long mod list)

**Comment by Allexio** [comment]
This is a duplicate:
https://github.com/Fabricators-of-Create/Create/issues/1002
