### ISSUE TITLE
Mechincal belt sometimes creates uninteractable/unbreakable ghost block when placed.

### ISSUE THREAD

**Issue by ChosenGible** [Fabricators-of-Create/Create#1118]
### Describe the Bug

When a mechanical belt is place (via right clicking onto shafts with the mechanical belt item). A ghost mechanical belt block will be placed down alongside a working mechanical belt. 

This ghost belt only appears in the same space as second shaft right clicked in the mechanical belt creation process. It cannot be destroyed by breaking the shaft it is on, nor can it be interacted with. 

Reloading the world seems to remove the ghost belt. 

### Reproduction Steps

1. Place two shafts
2. Hold a mechanical belt item
3. Select one shaft
4. Select the other shaft
5. (If a ghost belt is not created try again)

### Expected Result

No ghost belt should be created during the mechanical belt placement process.

### Screenshots and Videos

![2023-09-17_20 36 02](https://github.com/Creators-of-Create/Create/assets/46504818/53638629-30b5-497d-b93d-c56526bb9f79)
![2023-09-17_20 36 07](https://github.com/Creators-of-Create/Create/assets/46504818/97678d2e-c0d3-467a-aae1-2c24261dc47c)

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/46504818/7405610e-1955-4d82-8cf9-d27bd2dc09e2)

### Additional Context

༼ つ ╹ ╹ ༽つ So there you have it a spooky ghost just in time for Halloween.

**Comment by TropheusJ** [comment]
send the log

**Comment by ChosenGible** [comment]
https://mclo.gs/mBTMLqx

**Comment by liangmoe** [comment]
i have the same issue and it caused my game crash
[crash-2023-11-06_15.54.26-client.txt](https://github.com/Fabricators-of-Create/Create/files/13263985/crash-2023-11-06_15.54.26-client.txt)
[2023-11-06-3.log](https://github.com/Fabricators-of-Create/Create/files/13264004/2023-11-06-3.log)

**Comment by Allexio** [comment]
FWIW I have the same issue, and yes it also made my game crash (I've had the issue multiple times, but it only made my game crash once -- I assumed it was something to do with Sodium/shaders as it seems the people who are using my modpack without the shaders do not get this issue).

**Comment by TropheusJ** [comment]
duplicate of https://github.com/Fabricators-of-Create/Create/issues/1244
