### ISSUE TITLE
Compatibility issue with Sodium 0.5.2?

### ISSUE THREAD

**Issue by chillen6918** [Fabricators-of-Create/Create#1119]
### Describe the Bug

When launching the game it crashes and says to install the (Create) 0.5.1-d-build. 1161 +mc1.20.1 but it shows the version that is needed as installed

### Reproduction Steps

1. Uninstalled the create mode and re installed
2. Confirmed the versions that where needed
3. Uninstalled the Sodium 0.5.2 and tried to reinstall it
4.  Uninstalled the Sodium 0.5.2 and tried the Sodium 0.5.3
...

### Expected Result

I was hoping that reinstalling and trying the newer versions would fix this or at least remove that issue.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/58891958/0a0f17b5-4846-4ba1-9d63-3f6474237fcd)
![image](https://github.com/Fabricators-of-Create/Create/assets/58891958/5e67b64a-2c8c-445d-885a-41dda2c052c4)
![image](https://github.com/Fabricators-of-Create/Create/assets/58891958/4bf74428-20da-4418-b999-1db1596168af)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

I added this to the DarkRPG modpack that i use

**Comment by drwoops** [comment]
you need sodium 0.4.10

**Comment by chillen6918** [comment]
> you need sodium 0.4.10

I installed that and tried again but it gave the same error tho some of the other mods requires the Sodium 0.5.2 version so i am unable to remove that thersion entirely. 
Will this be somethinf that might be able to be adjusted in the future?

**Comment by drwoops** [comment]
that is the only version of sodium that will work with create. so you will have to choose

**Comment by chillen6918** [comment]
Oh. Thank you for the information. Ill just need to remove the create mod then as the other mods in the list wont work otherwise.

**Comment by drwoops** [comment]
cool. please remember to close this issue
