### ISSUE TITLE
[1.19.2] [Fabric 0.14.22] [Create v0.5.1.c] mod causes debugged walls to be weird

### ISSUE THREAD

**Issue by glittermutt** [Fabricators-of-Create/Create#1122]
### Describe the Bug

i'm running only create and fabric api; whenever i use the debug stick on walls (only walls for some reason), it doesn't show all the blockstates - only "north", "west" and "up"; the expected result is that it'd show all the other directional blockstates, as well as the "waterlogged" state. this may seem insignificant, however the debug stick is utilized by many builders heavily, so it'd be lovely if it worked as intended

### Reproduction Steps

1. install fabric and create mod
2. place down a wall and try debugging it
3. profit

### Expected Result

the wall shows all the other directional blockstates, as well as the "waterlogged" state

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/134949309/db55a863-91ad-4141-b1d9-5a9963d7e247

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
this is fixed on 1.20. it would require significant refactors to backport.
