### ISSUE TITLE
1.20 is not working?

### ISSUE THREAD

**Issue by ttramdriver** [Fabricators-of-Create/Create#1124]
### Describe the Bug

Im using QUILT server for 1.20 and when i open the server it crashes because the mod create fabric and mods inside it are made for 1.20.1, could you make it compatible with 1.20?

### Reproduction Steps

1.install quilt server 1.20
2.install qfapi (quilted fabric api)
3.install create fabric
4. run the server

### Expected Result

Server should launch normally

### Operating System

Windos 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

https://www.dropbox.com/scl/fi/na0tljmctn61s5bbib3p0/mods.rar?rlkey=y7ldhry4ldkzeofudca8w1nq0&dl=0

**Comment by Hugowertop2** [comment]
Change the quilt server to 1.20.1 then, there is nothing wrong with the create version in ur case its just you using the wrong version of quilt

**Comment by ttramdriver** [comment]
thanks for response! I'll try to make my mods updated to 1.20.1, if you know any site that could do it for me, it would be grately appreciated, firstly I need to check do I even need to update the mod.

**Comment by TropheusJ** [comment]
.1 changed like nothing, mods will work fine. you're using old versions and should update anyway.

**Comment by ttramdriver** [comment]
2 mods do need an update but create didnt gave an error so far

**Comment by ttramdriver** [comment]
wait nvm that is far more than 2
![image](https://github.com/Fabricators-of-Create/Create/assets/95749943/11eef161-4c89-4234-bd6a-b5402390353c)

**Comment by ttramdriver** [comment]
well thats uhh helping https://github.com/gorilla-devs/ferium

**Comment by ttramdriver** [comment]
nuh uh, not doing that, have to add mods manually to there

**Comment by ttramdriver** [comment]
ok this is what im looking for (https://modrinth.com/mod/addadd/version/6.0.1)

**Comment by ttramdriver** [comment]
it doesnt work sadly

**Comment by ttramdriver** [comment]
FINNALY https://mc-mod-updater.vercel.app/

**Comment by ttramdriver** [comment]
ok it took some time but it works, thank

**Comment by slodkipiesio** [comment]
ok uhh it took some time but everything works now, thanks!
