### ISSUE TITLE
placing a Mechanical Saw crashes the game

### ISSUE THREAD

**Issue by AfterSchoolSncks0KJ** [Fabricators-of-Create/Create#1126]
### Describe the Bug

If I place a mechanical saw the game crashes immediately

### Reproduction Steps

1. Get a mechanical saw
2. Place mechanical saw
3. Game crashes
...

### Expected Result

that the bug doesn't appear again

### Crash Report or Log

https://mclo.gs/rymTumq

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![Screenshot_20230924-210743](https://github.com/Fabricators-of-Create/Create/assets/80837417/39214ee2-7234-442b-8f01-243427f14c16)

**Comment by drwoops** [comment]
try downgrading fabric api to 0.88.1.  if you still get a crash, please post the crash report, not the log.

**Comment by AfterSchoolSncks0KJ** [comment]
[crash-2023-09-24_20.56.17-client.txt](https://github.com/Fabricators-of-Create/Create/files/12709477/crash-2023-09-24_20.56.17-client.txt)

**Comment by drwoops** [comment]
you did not downgrade fabric api

**Comment by AfterSchoolSncks0KJ** [comment]
it's the crash report befor downgrade, after downgrade it works normaly but if the cunk gets unloaded the shaft and the saw are not connected

**Comment by drwoops** [comment]
i dont know what that means. can you show screenshots

**Comment by AfterSchoolSncks0KJ** [comment]
![2023-09-24_21 43 42](https://github.com/Fabricators-of-Create/Create/assets/80837417/9df83d69-95f1-4125-b61b-f645728d1ed4)

**Comment by drwoops** [comment]
and what do you mean when you say "not connected". is the shaft broken or invisible?

**Comment by AfterSchoolSncks0KJ** [comment]
the saw gets no energy, but the shaft rotates

**Comment by drwoops** [comment]
try F3+A

**Comment by AfterSchoolSncks0KJ** [comment]
I've already tried. To fix the problem you have to dismantle the saw and put it back in place, but this only happens when the chunk is unloaded

**Comment by drwoops** [comment]
is this on a chunk boundary?

**Comment by AfterSchoolSncks0KJ** [comment]
yes it happens when it places chunks in the boundary

**Comment by TropheusJ** [comment]
send a new log

**Comment by AfterSchoolSncks0KJ** [comment]
what kind of log?

**Comment by TropheusJ** [comment]
latest.log from the logs folder

**Comment by AfterSchoolSncks0KJ** [comment]
[latest.log](https://github.com/Fabricators-of-Create/Create/files/12742700/latest.log)

**Comment by TropheusJ** [comment]
open a world and get the issue to occur, then send the log. If you're on a server, I need the server's log.

**Comment by MarvinnivraM** [comment]
[server-latest.log](https://github.com/Fabricators-of-Create/Create/files/12742775/server-latest.log)

**Comment by TropheusJ** [comment]
full thing, please. put it on https://mclo.gs/ to remove sensitive info.

**Comment by AfterSchoolSncks0KJ** [comment]
https://mclo.gs/Pyink1U

**Comment by TropheusJ** [comment]
This is still not the full thing, but it is pretty weird.
There's some errors from before the player joining that mean that an unknown packet was sent.
No idea without more info. At least the mod list.

**Comment by AfterSchoolSncks0KJ** [comment]
![Screenshot_20230929-013405.png](https://github.com/Fabricators-of-Create/Create/assets/80837417/947bdbcc-9485-40bf-b364-ded135f35781)

**Comment by TropheusJ** [comment]
this was probably some incompatibility. It's been over a year with no new reports
