### ISSUE TITLE
Game is not Compatctible with Sodium .53

### ISSUE THREAD

**Issue by Keltjin** [Fabricators-of-Create/Create#1128]
### Describe the Bug

When I try to run the mod with Sodium it is unable to be combatible.

### Reproduction Steps

1.Download Sodium 0.53
2. Dowload Create
3. Run Minecraft
...

### Expected Result

I expected that Create should be able to run with Sodium.

### Operating System

Linux Mint

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by LittleCircleOO** [comment]
duplicate of #1039
