### ISSUE TITLE
Cannot detect all inventory slots with Content Observers or Stockpile Switches - FAPI transfer does not have a concept of "not sided"

### ISSUE THREAD

**Issue by JieningYu** [Fabricators-of-Create/Create#113]
### Describe the Bug

Content Observers can't detect the fuel slot of furnaces/blast furnaces/smokers.
In Forge version of create, they can.

### Reproduction Steps

1. Put a furnace/blast furnace/smoker.
2. Put a carpet in the fuel slot.
3. Put a content observer and let it detect the furnace.
4. It can't detect the carpet.

### Expected Result

It should detect the carpet properly like the forge version.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/61787533/151309784-b687944d-26a7-42e7-9fc2-6a0c2cc55687.png)
![image](https://user-images.githubusercontent.com/61787533/151309905-b588ff09-24f6-4878-86dd-ed6f70d4338d.png)

### Operating System

macOS 12.2 Beta (21D5039d)

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

  [✔️] architectury-3.4.9
  [✔️] c2me-fabric-mc1.18.1-0.2.0+alpha.6.1-all
  [✔️] cloth-api-3.0.55
  [✔️] cloth-config-6.1.48-fabric
  [✔️] create-mc1.18.1_v0.4c
  [✔️] EntityCulling-Fabric-1.3.3
  [✔️] fabric-api-0.46.1+1.18
  [✔️] Flywheel-Fabric-1.18-0.6.0.16
  [✔️] indium-1.0.2-alpha2+mc1.18.1
  [✔️] krypton-0.1.6
  [✔️] lazydfu-0.1.2
  [✔️] lithium-fabric-mc1.18.1-0.7.7
  [✔️] mcwifipnp-1.5.3-1.18-fabric
  [✔️] modmenu-3.0.1
  [✔️] notenoughcrashes-4.1.4+1.18.1-fabric
  [✔️] rer-2.3.0
  [✔️] RoughlyEnoughItems-7.1.380
  [✔️] slight-gui-modifications-2.0.2
  [✔️] smoothboot-fabric-1.18-1.7.0
  [✔️] sodium-extra-mc1.18.1-0.3.8
  [✔️] sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14
  [✔️] starlight-1.0.1+fabric.0583973
  [✔️] wthit-fabric-4.4.1

**Comment by TropheusJ** [comment]
This is due to a limitation with FAPI transfer. Fabric simply doesn't have a concept of "not-sided."  
I've mitigated this with [this commit](https://github.com/Fabricators-of-Create/Create/commit/6fe91adee65fa8ffa1e8b45828769bdfbf8942f4), however now you won't be able to detect the input slot or the output slot. It'll behave more as expected, but not exactly the same as forge.

**Comment by TropheusJ** [comment]
There is no way for us to fix this - either FAPI changes (not happening) or upstream changes (plausible). I've already brought it up to the forge team. If neither change, this has been promoted to Feature™️.

**Comment by TropheusJ** [comment]
Nevermind! I managed to throw something together that emulates forge's no sides by getting all sides and merging them. It seems pretty unstable though, testing appreciated. fixed in [this commit](https://github.com/Fabricators-of-Create/Create/commit/e481507c350d621b81b7da21e47e0f4c438a1d13).

**Comment by RedWideWeb** [comment]
Will test it! Thanks a lot!
