### ISSUE TITLE
Crashing when placing traintrack.

### ISSUE THREAD

**Issue by DESTROY3R05** [Fabricators-of-Create/Create#1130]
### Describe the Bug

Game instantly crashes when placing a straight train track. Upon relogging, it corrupts the chunk it was placed in, and appears invisible. placing another track will crash it again.

### Reproduction Steps

1.Open world.
2. Place Straight facing Train Track.
3. Crashes.

### Expected Result

Not Crashing or corrupting chunk.

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/146142495/2c2df824-fc9e-4a08-a8ec-932557b9e37b

![image](https://github.com/Fabricators-of-Create/Create/assets/146142495/8ccb9da9-0d75-40f8-bae3-89757e4705bf)

![image](https://github.com/Fabricators-of-Create/Create/assets/146142495/9bf67f03-7320-42af-b441-97e6d2934a3c)

### Crash Report or Log

https://pastebin.com/HDj7Z3g7

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/146142495/3c3398f9-3873-4525-86e0-4d83db9fa37f)
![image](https://github.com/Fabricators-of-Create/Create/assets/146142495/4043648e-882a-4d0e-95a9-54e6b495b6a9)

### Additional Context

I re-did the bug on 4 separate worlds, placing the track around spawn and got the same results.

**Comment by drwoops** [comment]
please downgrade fabric api to 0.88.1 and try again

**Comment by DESTROY3R05** [comment]
Fixed it, Thanks! 
![image](https://github.com/Fabricators-of-Create/Create/assets/146142495/95a59ee7-303b-481b-9d29-15493605ed6e)
