### ISSUE TITLE
Potato Gun Projectile Texture not Found

### ISSUE THREAD

**Issue by Type-32** [Fabricators-of-Create/Create#1132]
### Describe the Bug

Create 0.5.1d for Minecraft Fabric 1.20.1
RTX3050, i7-13700H

With Resource Packs Enabled: https://youtu.be/eeiNQ6wFGnI
Without Resource Packs Enabled: https://youtu.be/-z3UsI0q5Kc

When shooting any projectiles from the potato gun, nothing would appear up and my guess is that Create doesn't have a texture for the projectile. I also don't have any shaders enabled, as you can see in the video.

Also I hate the fact that Create doesn't support Sodium 0.5.3, so I had to use 0.4.10 instead and many bugs came up and everything was made inconvenient.

### Reproduction Steps

1. Install Sodium 0.4.10, the correspoding Indium Version, Iris 1.6.5, no starlight, and Create 0.5.1d for Minecraft Fabric 1.20.1
2. Open up a singleplayer world and get a potato gun
3. Start shooting and you'll see no textures for projectiles and they'll look transparent

### Expected Result

The Projectile Entity should show as the corresponding shot catridge item, like a potato or beetroot, but it doesn't show anything.

### Screenshots and Videos

With Resource Packs Enabled: https://youtu.be/eeiNQ6wFGnI
Without Resource Packs Enabled: https://youtu.be/-z3UsI0q5Kc

### Crash Report or Log

N/A

### Operating System

Windows 11 Dev Channel

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Sodium 0.4.10
Indium for Sodium 0.4.10
Iris 1.6.5
Lithium
BetterF3
MoreCulling
Create for Fabric 0.5.1d

**Comment by electricsteve** [comment]
how do you have your video settings?

**Comment by TropheusJ** [comment]
#1334
