### ISSUE TITLE
Sodium and Create[fabric] is incompatible

### ISSUE THREAD

**Issue by Dr-Complex** [Fabricators-of-Create/Create#1133]
### Describe the Bug

The Fabric loader showed that Create was incompatible to Sodium (0.5.3)

### Reproduction Steps

1. Have Sodium (0.5.3) installed on a Fabric loader of Minecraft (1.20.1).
2. Have Create (0.5.1-d) installed.
3. Load the game.

### Expected Result

Sodium and Create are the newest versions are and the other mods I are as well. I thought it would have worked, but at last it did not.

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

additional redstone
alloy-forgery
alternate-current
amthyst-update
appleskin
architectuy api
attracion
badpackets
bedshreads
better combat
better F3
bushier flowers
chisel reborn
cloth-config
collective
comforts
continuity
copper horns
customizable elytra
dummmmmmy
eating animations
elytra slot
emi
emi effect
Enchanting Infuser
enchant tweaker
fabric api
fabric language kotlin
footprint particle
forbidden Potions
forge config api port
gecko lib
grappelhook
hangglider
immersive melodies
immersive portals
incantationem
Idium
iris
just mob heads
lamb dynamic lights
lazydfu
lithium
magic sorting system
mod menu
moonlight lib
more banner features
more bows
mystic potions
mythic metals
origins
owo lib
Pehkui
player animation
polymorph
portal gun
puzzel lib
realistic sleep
redstone bits
redstone pen
reeses sodium options
reimagined trims
reinfored chests , barrel, shulker boxes
simple copper horns
simply swords
sodium extra 
Sodium (the problem)
sound physics
supplementaries
tool tip fix
trinkets
uncrafables
vanilla refresh
voice chat
color me outlines
wthit (what the hell is that)
yet another config lib
Zoomify
[All the mods above are the newest version]

**Comment by TropheusJ** [comment]
#1039
