### ISSUE TITLE
Maincraft does not start

### ISSUE THREAD

**Issue by Minortyy** [Fabricators-of-Create/Create#1135]
### Describe the Bug

This error pops up: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.5.3 with version 0.5.2.
	 - Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with any version that is compatible with:
		 - sodium, version 0.5.2
Unmet dependency listing:
	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.3!
	 - Mod 'Indium' (indium) 1.0.25+mc1.20.1 requires version 0.5.2 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.3!
	 - Mod 'Iris' (iris) 1.6.8 requires version 0.5.2 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Reproduction Steps

1.
2.
3.
...
/

### Expected Result

/

### Screenshots and Videos

/

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![2023-10-03_14-07-45](https://github.com/Fabricators-of-Create/Create/assets/146833350/acb54c2d-6b14-4d3c-a5f3-16e92fc63acc)
![2023-10-03_14-07-54](https://github.com/Fabricators-of-Create/Create/assets/146833350/84499d8f-6a5c-4453-933d-b37c6e2a9f1d)
![2023-10-03_14-08-09](https://github.com/Fabricators-of-Create/Create/assets/146833350/d956f79d-0c53-417a-9a66-8d322641406f)
![2023-10-03_14-08-17](https://github.com/Fabricators-of-Create/Create/assets/146833350/8016e9c1-8d16-4ef1-946a-bacae34e6c4f)

### Additional Context

I also don't run with the version of sodium 0.52, 0.51, 0.50

**Comment by TropheusJ** [comment]
>Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium)

**Comment by Minortyy** [comment]
That is, I need to download the Sodium version below 0.50?

**Comment by Minortyy** [comment]
That is, I need to download the Sodium version below 0.50?

**Comment by TropheusJ** [comment]
until the next update, yes
