### ISSUE TITLE
Game crashes when having Create Fabric installed on 1.20.1

### ISSUE THREAD

**Issue by YejiYeah** [Fabricators-of-Create/Create#1137]
### Describe the Bug

I have in a modpack installed Create for 1.20.1, however I am not able to use any version of sodium (in 1.20.1), the game crashes when just loading.

### Reproduction Steps

1.- Install any version of Sodium for 1.20.1 (while having create Fabric installed)
2.- Start the game
3.- Game crashes

### Expected Result

Having  a new version of create compatible with the current 1.20.1 version of sodium

### Crash Report or Log

https://www.dropbox.com/scl/fi/looh78svjltnd412vecjk/latest.log?rlkey=o7uv2y8o4jllxa7kspoh6rfit&dl=0

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
> Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium)
