### ISSUE TITLE
Server crashes when placing deployer between mismatched RPMs with Jade installed

### ISSUE THREAD

**Issue by object-Object** [Fabricators-of-Create/Create#1139]
### Describe the Bug

When Jade is installed, placing a deployer between two cogs rotating at different speeds causes the game/server to crash. The issue does not occur without Jade.

### Reproduction Steps

1. Set up two inline cogs rotating at different speeds.
2. Place a deployer between them, connected to both cogs.

### Expected Result

The game should not crash.

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/37044997/fde3173a-3114-4f03-adce-61af5807b7af

### Crash Report or Log

https://mclo.gs/HSCSXkG

### Operating System

Windows 11

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

Fabric Loader: `0.14.23`
Fabric API: `0.76.1+1.19.2`
Jade: `8.7.3`

### Additional Context

Full log: https://mclo.gs/f4YGrir

**Comment by object-Object** [comment]
Addendum: I was just able to reproduce the crash on 1.20.1 as well.

Crash report: https://mclo.gs/4Ig6JFe

Fabric API: `0.86.1+1.20.1`
Create: `0.5.1-d`
Jade: `11.6.1`

**Comment by TropheusJ** [comment]
This issue occurs on Forge 1.18 too. Please open an issue on the Forge repo.

**Comment by TropheusJ** [comment]
Should probably open one for Jade too

**Comment by IThundxr** [comment]
Reopening to remind me to make a matching issue on the forge repo

**Comment by IThundxr** [comment]
reported to forge repo at https://github.com/Creators-of-Create/Create/issues/6244
