### ISSUE TITLE
Incorrect Face Culling

### ISSUE THREAD

**Issue by Phoupraw** [Fabricators-of-Create/Create#1142]
### Describe the Bug

Mechanical saw causes incorrect face culling.

### Reproduction Steps

1. Place a mechanical saw.
2. Place a slab or stonecutter adjacent to the shaft face.
3. The face of slab or stonecutter adjacent to the saw is culled.

### Expected Result

The face shouldn't be culled.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/50520903/8fc37594-6448-4f4e-96c8-a3531a17cf7e)
![image](https://github.com/Fabricators-of-Create/Create/assets/50520903/f54297f4-510b-45f4-a7e6-b11b6497424a)

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Loading 147 mods:
- amecs 1.3.9+mc.1.20-pre2
   \-- amecsapi 1.4.0+mc1.20-pre1
- appleskin 2.5.0+mc1.20
   \-- cloth-config 11.0.99
        \-- cloth-basic-math 0.6.1
- ash 2.0.0-rc.2
- carpet 1.4.112+v230608
- carpet-tis-addition 1.48.0
   \-- conditional-mixin 0.3.2
- chat_heads 0.10.15
- colormeoutlines 1.1.2
- create 0.5.1-d-build.1161+mc1.20.1
   |-- com_electronwill_night-config_core 3.6.3
   |-- com_electronwill_night-config_toml 3.6.3
   |-- com_google_code_findbugs_jsr305 3.0.2
   |-- flywheel 0.6.9-1
   |-- milk 1.2.60
   |    \-- dripstone_fluid_lib 3.0.2
   |-- porting_lib_accessors 2.1.1127+1.20
   |    |-- porting_lib_core 2.1.1127+1.20
   |    \-- porting_lib_gametest 2.1.1127+1.20
   |-- porting_lib_base 2.1.1127+1.20
   |    |-- porting_lib_attributes 2.1.1127+1.20
   |    |-- porting_lib_common 2.1.1127+1.20
   |    |-- porting_lib_core 2.1.1127+1.20
   |    |-- porting_lib_gametest 2.1.1127+1.20
   |    |-- porting_lib_lazy_registration 2.1.1127+1.20
   |    \-- porting_lib_utility 2.1.1127+1.20
   |-- porting_lib_brewing 2.1.1127+1.20
   |    |-- porting_lib_core 2.1.1127+1.20
   |    \-- porting_lib_gametest 2.1.1127+1.20
   |-- porting_lib_client_events 2.1.1127+1.20
   |    |-- mm 2.3
   |    |-- porting_lib_core 2.1.1127+1.20
   |    \-- porting_lib_gametest 2.1.1127+1.20
   |-- porting_lib_entity 2.1.1127+1.20
   |    |-- porting_lib_core 2.1.1127+1.20
   |    |-- porting_lib_gametest 2.1.1127+1.20
   |    \-- porting_lib_mixin_extensions 2.1.1127+1.20
   |-- porting_lib_extensions 2.1.1127+1.20
   |    |-- porting_lib_attributes 2.1.1127+1.20
   |    |-- porting_lib_common 2.1.1127+1.20
   |    |-- porting_lib_core 2.1.1127+1.20
   |    \-- porting_lib_gametest 2.1.1127+1.20
   |-- porting_lib_fake_players 2.1.1127+1.20
   |    |-- porting_lib_core 2.1.1127+1.20
   |    \-- porting_lib_gametest 2.1.1127+1.20
   |-- porting_lib_models 2.1.1127+1.20
   |    |-- porting_lib_core 2.1.1127+1.20
   |    |-- porting_lib_gametest 2.1.1127+1.20
   |    \-- porting_lib_model_loader 2.1.1127+1.20
   |-- porting_lib_networking 2.1.1127+1.20
   |    |-- porting_lib_core 2.1.1127+1.20
   |    \-- porting_lib_gametest 2.1.1127+1.20
   |-- porting_lib_obj_loader 2.1.1127+1.20
   |    |-- porting_lib_attributes 2.1.1127+1.20
   |    |-- porting_lib_common 2.1.1127+1.20
   |    |-- porting_lib_core 2.1.1127+1.20
   |    |-- porting_lib_gametest 2.1.1127+1.20
   |    \-- porting_lib_model_loader 2.1.1127+1.20
   |-- porting_lib_tags 3.0
   |    |-- porting_lib_core 2.1.1127+1.20
   |    \-- porting_lib_gametest 2.1.1127+1.20
   |-- porting_lib_tool_actions 2.1.1127+1.20
   |    |-- porting_lib_core 2.1.1127+1.20
   |    \-- porting_lib_gametest 2.1.1127+1.20
   |-- porting_lib_transfer 2.1.1127+1.20
   |    |-- porting_lib_core 2.1.1127+1.20
   |    \-- porting_lib_gametest 2.1.1127+1.20
   |-- reach-entity-attributes 2.4.0
   \-- registrate-fabric 1.3.62-MC1.20.1
        |-- fabric-data-generation-api-v1 12.2.0+6c31357e77
        |-- porting_lib_data 2.1.1090+1.20
        \-- porting_lib_model_generators 2.1.1090+1.20
             \-- porting_lib_model_materials 2.1.1090+1.20
- createsdelight 0.2.0-pre2
   \-- com_github_llamalad7_mixinextras 0.2.0-rc.4
- creativecore 2.10.23
   \-- net_minecraftforge_eventbus 6.0.3
- emi 1.0.21+1.20.1+fabric
- entityculling 1.6.2-mc1.20
- fabric-api 0.86.0+1.20.1
   |-- fabric-api-base 0.4.30+7abfd51577
   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
   |-- fabric-block-api-v1 1.0.9+e022e5d177
   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
   |-- fabric-command-api-v1 1.2.33+f71b366f77
   |-- fabric-command-api-v2 2.2.12+b3afc78b77
   |-- fabric-commands-v0 0.2.50+df3654b377
   |-- fabric-containers-v0 0.1.62+df3654b377
   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
   |-- fabric-data-generation-api-v1 12.2.0+6c31357e77
   |-- fabric-dimensions-v1 2.1.52+b3afc78b77
   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
   |-- fabric-events-interaction-v0 0.6.1+e91849a877
   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
   |-- fabric-item-api-v1 2.1.27+b3afc78b77
   |-- fabric-item-group-api-v1 4.0.9+132c48c177
   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
   |-- fabric-keybindings-v0 0.2.34+df3654b377
   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
   |-- fabric-message-api-v1 5.1.7+3265161977
   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
   |-- fabric-model-loading-api-v1 1.0.1+9386d8a777
   |-- fabric-models-v0 0.4.0+9386d8a777
   |-- fabric-networking-api-v1 1.3.9+b3afc78b77
   |-- fabric-networking-v0 0.3.49+df3654b377
   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
   |-- fabric-particles-v1 1.1.1+201a23a077
   |-- fabric-recipe-api-v1 1.0.19+b3afc78b77
   |-- fabric-registry-sync-v0 2.3.0+2e061fd477
   |-- fabric-renderer-api-v1 3.1.1+9386d8a777
   |-- fabric-renderer-indigo 1.4.1+9172968c77
   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
   |-- fabric-rendering-data-attachment-v1 0.3.34+b3afc78b77
   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
   |-- fabric-rendering-v0 1.1.48+df3654b377
   |-- fabric-rendering-v1 3.0.7+b3afc78b77
   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
   |-- fabric-resource-loader-v0 0.11.9+132c48c177
   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
   |-- fabric-screen-handler-api-v1 1.3.28+b3afc78b77
   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
   |-- fabric-transfer-api-v1 3.3.0+cdf060b277
   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
- fabric-language-kotlin 1.9.6+kotlin.1.8.22
   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.22
   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.22
   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.22
   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.22
   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.21.0
   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.1
   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.1
   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1
   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1
   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1
- fabricloader 0.14.21
- ferritecore 6.0.0
- forgeconfigapiport 8.0.0
- imblocker 1.0.23
- indium 1.0.18+mc1.20
- inventoryprofilesnext 1.10.5
- itemscroller 0.20.0
- java 17
- libipn 3.0.2
- litematica 0.15.0
- magiclib 0.7.342+d9ab137-beta
   \-- magiclib-1_20_1 0.7.342+d9ab137-beta
- malilib 0.16.0
- masa_gadget_mod 3.2.312+d94b097-beta
   \-- masa_gadget_mod-1_20_1 3.2.312+d94b097-beta
- mcwifipnp 1.6.5
- minecraft 1.20.1
- minihud 0.27.0
- modmenu 7.1.0
- nochatreports 1.20.1-v2.2.1
- ommc 0.5.289+be50024-dev
   \-- ommc-1_20 0.5.289+be50024-dev
- pca 0.3.166+0c5bf4c-beta
- reeses-sodium-options 1.5.0+mc1.20-build.73
- showdurability 1.1.0+1.20.1
- sodium 0.4.10+build.27
- tweakermore 3.13.1
   \-- conditional-mixin 0.3.2
- tweakeroo 0.17.0
- xaero_map_addition 0.2.75+f01c92f-dev
   \-- xaero_map_addition-1_20 0.2.74+4879973-dev
- xaerominimap 23.4.4
- xaeroworldmap 1.30.4

### Additional Context

I didn't test it in forge.

**Comment by Poopooracoocoo** [comment]
Would you please test again with Indium 1.0.21 and Fabric API 0.88.1?

**Comment by Phoupraw** [comment]
> Would you please test again with Indium 1.0.21 and Fabric API 0.88.1?

- fabric-api-0.89.3+1.20.1
- sodium-fabric-mc1.20.1-0.5.3
- indium-1.0.27+mc1.20.1
- create-fabric-0.5.1-d-build.1161+mc1.20.1

> Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with any version that is compatible with:
		 - sodium 0.5.3
Unmet dependency listing:
	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.3!

**Comment by Poopooracoocoo** [comment]
What happened there?! How did you get the latest versions of those mods??

**Comment by Phoupraw** [comment]
> What happened there?! How did you get the latest versions of those mods??

I have no idea. From modrinth.

**Comment by Poopooracoocoo** [comment]
Oh so you clicked the dreaded 'update all mods' button... I've always hated that...

**Comment by Phoupraw** [comment]
> Oh so you clicked the dreaded 'update all mods' button... I've always hated that...

What's this button? I have never heard of that. We're definitely not talking about the same launcher. My launcher doesn't have this button. I download these versions manually.

**Comment by Poopooracoocoo** [comment]
I have no idea how you randomly updated those mods to the latest version then. :/

I'd still like you to test whether you see this with Sodium 0.4.10, Indium 1.0.21 and Fabric API 0.88.1.

**Comment by Phoupraw** [comment]
> I have no idea how you randomly updated those mods to the latest version then. :/
> 
> I'd still like you to test whether you see this with Sodium 0.4.10, Indium 1.0.21 and Fabric API 0.88.1.

OK. I switched to these versions, successfully launched game and entered world now, and the face is still culled.

**Comment by IThundxr** [comment]
Try removing entity culling/more culling, also is this specific to the fabric version or does forge suffer from this aswell?

**Comment by IThundxr** [comment]
This affects forge aswell.

**Comment by IThundxr** [comment]
Upstream at https://github.com/Creators-of-Create/Create/issues/6117
