### ISSUE TITLE
Client wont start with fabric beta build 0.5.1 for 1.20.1 when sodium is installed

### ISSUE THREAD

**Issue by scarcekoi** [Fabricators-of-Create/Create#1144]
### Describe the Bug

My client does not start when I have Create (Fabric) (beta build 0.5.1 for 1.20.1) and sodium. It just crashes.

### Reproduction Steps

1. Install Create (Fabric)
2. Install Fabric Api
3. Install sodium
4. Run the instance

### Expected Result

Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with any version that is compatible with:
sodium 0.5.3
Unmet dependency listing:
<html>Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium),<br>but a matching version is present: 0.5.3!</html>

### Screenshots and Videos

![Screenshot 2023-10-07 152354](https://github.com/Fabricators-of-Create/Create/assets/111240985/110c6366-5c5b-4fc1-973f-e927966cf448)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Nothing except for create (fabric), sodium, and fabric api.

**Comment by drwoops** [comment]
use sodium 0.4.10 and fabric api 0.88.1

**Comment by Poopooracoocoo** [comment]
Not an issue. It's the breaks section in the fabric.mod.json working as intended. @CuteFox8302 This is NOT a crash. 

You want Sodium 0.4.10, Indium 1.0.21, and Fabric API 0.88.1. And optionally Iris 1.6.4, if you want shaders.
