### ISSUE TITLE
Minecraft startup crash

### ISSUE THREAD

**Issue by KlaraChaos** [Fabricators-of-Create/Create#1147]
### Describe the Bug

minecraft wont get part the staring phase 

### Reproduction Steps

1.start the game
2.crash

### Expected Result

minecraft starting up

### Crash Report or Log

https://pastebin.com/J5kwTnE4

### Operating System

win 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

the full mod list is in the crash report because there are a lot of mods in it (using prominese II as a base i added a lot of mods so there might be an incompatibility happing)

**Comment by drwoops** [comment]
use sodium 0.4.10 iris 1.6.4 fabric api 0.88.1 Indium 1.0.21. remove cccbridge it is no longer needed.

**Comment by KlaraChaos** [comment]
that did not fix it sadly  here the new crash log https://pastebin.com/P5rmdEHU also here is the main log as it maybe helps
[latest.log](https://github.com/Fabricators-of-Create/Create/files/12841123/latest.log)

**Comment by drwoops** [comment]
could you please disable vivecraft and transparent, until the rest loads?

**Comment by TropheusJ** [comment]
this is a conflict between transparent and sodium extra
