### ISSUE TITLE
Cannot compile shader because 'flywheel:model' is not recognized.

### ISSUE THREAD

**Issue by MKemalCam** [Fabricators-of-Create/Create#1149]
### Describe the Bug

My friend uses his onboard gpu and it crashes every single time. I tried changing apis, shader and render mods. It works for everyone else but for this guy it crashes every single time.

### Reproduction Steps

1.Open the game
2.Try to join a multiplayer game / singleplayer game
3.Crash after 5 seconds
(Also it crashes when you click the google icon on main menu. The ponder index)

### Expected Result

Should have not crashed

### Crash Report or Log

https://pastebin.com/vjiJdG4Q

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

advancement plaques
ambient sounds
areas
armor statues
autohud
better animations collection
better combat
better trees
blockrunner
cloth config
collective
comforts fabric
connectible chains
creative core fabric
cristellib
ct overhauled villages
deppslatecutting fabric
diagonal fences
eating animation
enchanting infuser
enhanced visuals fabric
fabric api
falling leaves
forge config api port
handcrafted fabric
iceberg
immersive structures
indium
invmove
iris
jamlib
just enough items
macaw's bridges, doors, fences, furniture, lights, paintings, paths, roofs, trapdoors, windows
modmenu
moonlight
moremobvariants
notenoughanimations
nyf's spiders
pickupnotifier
player animation lib
presence footsteps
puzzleslib
resourcefullib
right click harvest
shulkerbox tooltip
sno! real magic
sodium
sound physics
spawn animations
spyglass astronomy
status effect bars
supplementaries
tectonic
treechop
trinkets
vanilla refresh
vanilla tweaks
visuality
voicechat
wakes
weaponmaster
wi-zoom
wwoo
yungsapi, better dungeons, mineshafts, strongholds, bridges, extras
ALL FABRIC MODS, 1.20.1 FABRIC LOADER VERSION 0.14.22

### Additional Context

im going to tear my hair please i need to know why

**Comment by rilakuma123** [comment]
I don't know if it'll fix it but it's worth updating the graphics drivers: https://www.intel.com/content/www/us/en/download/776137/intel-7th-10th-gen-processor-graphics-windows.html

**Comment by garv-shah** [comment]
were you able to fix this? having the same issue here and no idea what else to try

**Comment by MKemalCam** [comment]
> were you able to fix this? having the same issue here and no idea what else to try

i couldn't make him download drivers and try to fix the issue
he lost interest lmao we'll never know

**Comment by MKemalCam** [comment]
try to update your drivers ppl idk what else

**Comment by garv-shah** [comment]
I've updated my drivers to the latest version, and I've tried just running just stock fabric too, doesn't seem to help :/
Any ideas?

**Comment by drwoops** [comment]
update fabric api to 0.88.1

**Comment by garv-shah** [comment]
that might have been the fix, for us we just deleted the `.minecraft` folder and reinstalled, seems to work now! ty 👍

**Comment by PepperCode1** [comment]
Before everyone starts deleting their `.minecraft` directory, know that it contains your worlds, mods, options, and more.
