### ISSUE TITLE
Content Observer can‘t read furnace's fuel tank.

### ISSUE THREAD

**Issue by meishiffx** [Fabricators-of-Create/Create#115]
### Describe the Suggestion

Content Observer can‘t read furnace's fuel tank.

Put the carpet in the furnace as fuel.
Content Observer cannot read the carpet.
Content Observer can read in forge.

**Comment by TropheusJ** [comment]
This should have been fixed last night, please test on the latest build.

**Comment by JieningYu** [comment]
这个bug在最新的commit里（two birds with one stone)已经被修复，而且我之前已经提交过这个issue（修完之后被close了，请不要重复提交

This bug is already fixed in the latest commit.

**Comment by TropheusJ** [comment]
this was fixed.
