### ISSUE TITLE
ponder just disapears after a while

### ISSUE THREAD

**Issue by liamwerk7676** [Fabricators-of-Create/Create#1150]
### Describe the Bug

when i open my inventory and i go to ponder somthing the option to ponder is not there and holding w dus noting 

### Reproduction Steps

1.open creative inventory 
2.pickup any item and start building 
3.and than open inventory and the option isnt there 
...

### Expected Result

i have the option to ponder 

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/112199156/21403fa9-4cd2-4b61-bfc6-21b545b70fc9)

![image](https://github.com/Fabricators-of-Create/Create/assets/112199156/b275d284-f124-4f35-9def-86240873a9a1)

### Operating System

windows 11 insider preview aka stable beta version

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

im just going to post my modpack mods
  [✔] 3dskinlayers-fabric-1.5.4-mc1.20.1
  [✔] AdvancementPlaques-1.20.1-fabric-1.4.11
  [✔] antighost-1.20-fabric0.83.0-1.1.5
  [✔] appleskin-fabric-mc1.20.1-2.5.1
  [✔] architectury-9.1.12-fabric
  [✔] autoswitch-7.0.2
  [✔] BetterF3-7.0.1-Fabric-1.20.1
  [✔] blanket-client-tweaks-1.1.4
  [✔] boathud-1.1.4
  [✔] borderless-mining-1.1.8+1.20.1
  [✔] BridgingMod-2.1.1+1.20.x.fabric
  [✔] c2me-fabric-mc1.20.1-0.2.0+alpha.11.0
  [✔] carryon-fabric-1.20.1-2.1.2.5
  [✔] cloth-config-11.1.106-fabric
  [✔] collective-1.20.1-6.66
  [✔] colorfulhearts-fabric-1.20.1-4.0.1
  [✔] comforts-quilt-6.3.3+1.20.1
  [✔] completeconfig-2.5.0
  [✔] continuity-3.0.0-beta.4+1.20.1
  [✔] Controlify-1.7.0-beta.1+1.20
  [✔] Controlling-fabric-1.20.1-12.0.2
  [✔] createbigcannons-fabric-1.20.1-0.5.2.a
  [✔] creatediselgenerators-2.1.3
  [✔] create-fabric-0.5.1-d-build.1161+mc1.20.1
  [✔] create-mod-trims-1.0.0
  [✔] createoreexcavation-fabric-1.20-1.4.0
  [✔] cullleaves-quilt-3.2.0
  [✔] datapack-downloader-1.0.0
  [✔] DetailArmorBar-2.6.3+1.20.1-fabric
  [✔] Ding-1.20.1-Fabric-1.4.1
  [✔] do-a-barrel-roll-3.3.4+1.20-fabric
  [✔] dynamicappicon-1.20.1-0.2.1
  [✔] dynamic-fps-3.2.1+minecraft-1.20.0
  [✔] eating-animation-1.9.4+1.20
  [✔] emi_loot-0.6.5+1.20.1
  [✔] emi-1.0.22+1.20.1+fabric
  [✔] emiffect-fabric-1.1.1+mc1.20.1
  [✔] emitrades-fabric-1.2.0+mc1.20.1
  [✔] enhancedblockentities-0.9+1.20
  [✔] entity_model_features_fabric_1.20-1.0.2
  [✔] entity_texture_features_fabric_1.20-4.5.1
  [✔] entityculling-fabric-1.6.2-mc1.20.1
  [✔] essential_1-2-2-2_fabric_1-20-1
  [✔] expandingtechnologies-1.0.1
  [✔] extendedgears-2.1.0-1.20.1-0.5.1.c-fabric
  [✔] extra-mod-integrations-0.4.1+1.20.1
  [✔] extrasounds-2.3.1+1.20.1
  [✔] fallingtrees-1.19.3-1.20.1+0.5.3-beta
  [✔] fastrandom-1.3
  [✔] ferritecore-6.0.0-fabric
  [✔] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
  [✔] freecam-fabric-1.2.1+1.20
  [✔] friendsandfoes-fabric-mc1.20.1-1.9.6
  [✔] garnished-0.9+1.20.1
  [✔] guardvillagers-2.0.8-1.20.1
  [✔] Iceberg-1.20.1-fabric-1.1.15
  [✔] ImmediatelyFast-1.2.6+1.20.2
  [✔] immersive_aircraft-0.6.2+1.20.1-fabric
  [✔] immersivemc-1.4.0-beta1.1-1.20.1-fabric
  [✔] inventorymanagement-1.3.1+1.20
  [✔] inventorytotem-1.20.1-3.0
  [✔] ironchests-5.0.2-fabric
  [✔] Jade-1.20-fabric-11.6.1
  [✔] JadeAddons-1.20.1-fabric-5.2.1
  [✔] jei-1.20.1-fabric-15.2.0.27
  [✔] justenoughbreeding-fabric-1.20.x-1.0.7
  [✔] JustEnoughProfessions-fabric-1.20.1-3.0.1
  [✔] JustEnoughResources-Fabric-1.20.1-1.4.0.238
  [✔] krypton-0.2.3
  [✔] lambdynamiclights-2.3.2+1.20.1
  [✔] lazydfu-0.1.3
  [✔] letmedespawn-fabric-1.20-1.1.0
  [✔] litematica-fabric-1.20.1-0.15.3
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] loadingbackgrounds-1.1.0-fabric
  [✔] make_bubbles_pop-0.2.0-fabric-mc1.19.4+
  [✔] malilib-fabric-1.20.1-0.16.3
  [✔] memoryleakfix-fabric-1.17+-1.1.2
  [✔] minibossbars-1.1
  [✔] MixinConflictHelper-1.2.0
  [✔] mixintrace-1.1.1+1.17
  [✔] modernfix-fabric-5.7.5+mc1.20.1
  [✔] mod-loading-screen-1.0.3
  [✔] modmenu-7.2.2
  [✔] moreculling-1.20.1-0.19.0
  [✔] neruina-1.2.5-fabric+1.18.2-1.20.1
  [✔] NoChatReports-FABRIC-1.20.1-v2.2.2
  [✔] notenoughanimations-fabric-1.6.4-mc1.20
  [✔] notenoughcrashes-4.4.6+1.20.1-fabric
  [✔] NQT-1.0.1+1.20-1.20.1
  [✔] owo-lib-0.11.2+1.20
  [✔] petnames-1.20.1-3.0
  [✔] physics-mod-3.0.9a-mc-1.20.1-fabric
  [✔] PickUpNotifier-v8.0.0-1.20.1-Fabric
  [✔] players-drop-heads-15.1
  [✔] PresenceFootsteps-1.9.0
  [✔] PuzzlesLib-v8.0.24-1.20.1-Fabric
  [✔] qfapi-7.3.1_qsl-6.1.2_fapi-0.89.3_mc-1.20.1
  [✔] reimaginedmenus-1.1.0-1.20.x
  [✔] replaymod-1.20.1-2.6.13
  [✔] respawningshulkers-1.20.1-3.5
  [✔] Searchables-fabric-1.20.1-1.0.2
  [✔] slime-1.5
  [✔] soundphysics-fabric-1.20.1-1.2.1
  [✔] spawnanimations-v1.9.2-mc1.17x-1.20x-mod
  [✔] splashfox-1.1.2
  [✔] Steam_Rails-1.5.1+fabric-mc1.20.1
  [✔] travelers-backpack-1.20.1-9.1.5
  [✔] true-ending-1.0.1a
  [✔] villagerconverting-1.2.1+1.20
  [✔] villagerdeathmessages-1.20.1-3.1
  [✔] villagernames-1.20.1-5.2
  [✔] visuality-0.7.1+1.20
  [✔] vmp-fabric-mc1.20.1-0.2.0+beta.7.102-all
  [✔] wakes-0.2.0
  [✔] waveycapes-fabric-1.4.0-mc1.20
  [✔] weaponmaster-client-only-fabric-1.20.1-3.0.5
  [✔] worldedit-mod-7.2.15
  [✔] yet-another-config-lib-fabric-3.2.1+1.20
  [✔] YungsApi-1.20-Fabric-4.0.2
  [✔] YungsBetterDesertTemples-1.20-Fabric-3.0.3
  [✔] YungsBetterDungeons-1.20-Fabric-4.0.3
  [✔] YungsBetterEndIsland-1.20-Fabric-2.0.4
  [✔] YungsBetterJungleTemples-1.20-Fabric-2.0.4
  [✔] YungsBetterMineshafts-1.20-Fabric-4.0.4
  [✔] YungsBetterNetherFortresses-1.20-Fabric-2.0.5
  [✔] YungsBetterOceanMonuments-1.20-Fabric-3.0.3
  [✔] YungsBetterStrongholds-1.20-Fabric-4.0.3
  [✔] YungsBetterWitchHuts-1.20-Fabric-3.0.3
  [✔] YungsBridges-1.20-Fabric-4.0.3
  [✔] YungsExtras-1.20-Fabric-4.0.3

**Comment by MrGreenTea** [comment]
I've had this too and for me it was `JadeAddons`.

See this issue there: https://github.com/Snownee/JadeAddonsFabric/issues/11

**Comment by MrGreenTea** [comment]
This should be fixed now @liamwerk7676 . If it is please close this issue :)

**Comment by liamwerk7676** [comment]
its fixed
