### ISSUE TITLE
Game crash after pressing assemble train

### ISSUE THREAD

**Issue by muddle6969** [Fabricators-of-Create/Create#1151]
### Describe the Bug

After pressing assemble train, train disappears and within seconds, game crashes. 

### Reproduction Steps

1.Put down tracks
2.setup a basic train, superglue it
3. click assemble train
4. Game crashes
...

### Expected Result

Expected the train to assemble and be able to drive it.

### Crash Report or Log

https://gist.github.com/muddle6969/d1eebd5454874c1eb699893c0c15d6f1

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![Create fabric 1 20 1 mod list](https://github.com/Fabricators-of-Create/Create/assets/100300233/72e08420-2862-481f-b064-f772f46f0152)

**Comment by muddle6969** [comment]
I unistalled starlight, now its not crashing anymore. I guess compatibility issue with starlight.

**Comment by drwoops** [comment]
starlight is now incompatible and also unnecessary since minecraft 1.20.1 has a new lighting engine that implements the techniques from starlight. please close this issue
