### ISSUE TITLE
sodium+indium issue?

### ISSUE THREAD

**Issue by BernardGrand** [Fabricators-of-Create/Create#1152]
### Describe the Bug

i have downloaded create and sodium+indium
but no matter which versions of sodium+indium i'm using the game either:
-won't even start
-or will not load train related and other blocks and when i place one crash with this msg:
![image](https://github.com/Fabricators-of-Create/Create/assets/99039053/65203d0b-1428-4d57-9a63-a1d6cf632247)

### Reproduction Steps

1. download sodium+indium that mod says needed
2. launch game
3. place any train track or train casing (idk which other blocks cause the same issue as blaze enginges do not)
4. crash

### Expected Result

crash with indium/sodium error msg

### Crash Report or Log

https://pastebin.com/DeA2GRb3

### Operating System

windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by drwoops** [comment]
downgrade fabric api to 0.88.1

**Comment by BernardGrand** [comment]
> downgrade fabric api to 0.88.1

omg, ty so much you're a life saver
