### ISSUE TITLE
Game crashes when attempting to ponder

### ISSUE THREAD

**Issue by NERD-NATO** [Fabricators-of-Create/Create#1153]
### Describe the Bug

Whenever I try to ponder, through inventory items or EMI, the game crashes.

### Reproduction Steps

1. Enter a world
2. Open inventory
3. Search "@create" in EMI
4. Hold W to ponder item
5. crash
...

### Expected Result

I expected to be shown a quick tutorial about the item/block.

### Crash Report or Log

https://gist.github.com/NERD-NATO/020de76bae3c6f945ae7b40b4ed4632c

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Borderless Mining
EMI
EMI Loot
EMI Trades
EMIffect
Fabric API
Indium
Reese's Sodium Options
Sodium
Sodium Blending Registry
Sodium Extra

**Comment by drwoops** [comment]
downgrade fabric api to 0.88.1

**Comment by NERD-NATO** [comment]
It worked, thanks.
