### ISSUE TITLE
Create mod crashing the game in JEI menu

### ISSUE THREAD

**Issue by Kibaraty** [Fabricators-of-Create/Create#1155]
### Describe the Bug

I started a new modded minecraft server with some friends, and i came across a problem.
Every time a search something Create related in JEI the game crashes
i watched this report(https://github.com/Creators-of-Create/Create/issues/5453), but i cant downgrade Sodium(up 2, because Create work only with 0.4.10 sodium)
Can anyone help me with this?

### Reproduction Steps

1.Open inventory
2.Search mod related thing
3.Game crashes
...

### Expected Result

Just see some recipe for create mod.

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/130297723/85efd91e-6a7c-4017-bbc5-4829aeabbb5e

### Crash Report or Log

<script src="https://gist.github.com/Kibaraty/6e9141faccd241b2f9c44b4df19fc79f.js"></script>
https://gist.github.com/Kibaraty/6e9141faccd241b2f9c44b4df19fc79f

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/130297723/1db43486-de5f-4c5a-890f-08557bc906d0)
![image](https://github.com/Fabricators-of-Create/Create/assets/130297723/575a3acd-ccf2-40fc-8f8a-6fe553587566)
![image](https://github.com/Fabricators-of-Create/Create/assets/130297723/c92fc321-a0ed-4568-b904-0b53a3ced02a)

**Comment by drwoops** [comment]
downgrade fabric api to 0.88.1

**Comment by Kibaraty** [comment]
that works thanks!
