### ISSUE TITLE
Display links not writing to signs

### ISSUE THREAD

**Issue by Toast5286** [Fabricators-of-Create/Create#1157]
### Describe the Bug

Previously it was pssible to use a display link to write to a sign. In Create 0.5.1-d it doesn't work with any type of signs. Both sides of the sign stay empty. It will actully delete any text on the selected line.

### Reproduction Steps

1. Place sign
2. Place a depot
3. Select the sign using the display link and place it on the depot
4. Write on the Label inside of the display link anything or place a item on the depot
5. After closing and the UI or updating with a redstone signal it will delete any previous text.
6.
...

### Expected Result

I was expecting it to write the name of the item if it's on the depot or any other info that the display link would write to the sign.

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/81771375/5c2759ab-8a69-4a5c-84c3-47d4bef3d6f0

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

BetterF3-7.0.1-Fabric-1.20.1.jar
entityculling-fabric-1.6.2-mc1.20.jar
Bookshelf-Fabric-1.20.1-20.0.4.jar                   
extendedgears-2.1.0-1.20.1-0.5.1.c-fabric.jar
CITResewn-1.1.3+1.20.jar                             
fabric-api-0.88.1+1.20.1.jar
Controlling-fabric-1.20.1-12.0.2.jar                 
fabric-carpet-1.20-1.4.112+v230608.jar
DramaticDoors-QuiFabrge-1.20.1-3.0.1.jar             
fabric-language-kotlin-1.10.10+kotlin.1.9.10.jar
FpsReducer2-fabric-1.20-2.5.jar                      
farmers-delight-fabric-mc1.20.1-1.4.2-bytecode-patch.jar
ImmediatelyFast-1.2.4+1.20.1.jar                     
farmers-delight-fabric-mc1.20.1-1.4.2.jar.disabled
InventorySorter-1.9.0-1.20.jar                       
ferritecore-6.0.0-fabric.jar
Jade-1.20-fabric-11.6.0.jar                          
freecam-fabric-1.2.1+1.20.jar
MouseTweaks-fabric-mc1.20-2.25.jar                   
friendsandfoes-fabric-mc1.20.1-1.9.5.jar
NoChatReports-FABRIC-1.20.1-v2.2.2.jar               
holdthatchunk-2.0.1+1.19.jar
RoughlyEnoughItems-12.0.652.jar                      
indium-1.0.21+mc1.20.1.jar
RoughlyEnoughProfessions-fabric-1.20.1-2.0.1.jar     
iris-flywheel-compat-1.20.1-0.2.1.jar
Searchables-fabric-1.20.1-1.0.1.jar                  
iris-mc1.20-1.6.4.jar
Sniffer+-fabric-1.20.1-0.2.0.jar                     
lambdynamiclights-2.3.2+1.20.1.jar
Steam_Rails-1.5.1+fabric-mc1.20.1.jar                
lazydfu-0.1.3.jar
XaerosWorldMap_1.34.1_Fabric_1.20.jar                
litematica-fabric-1.20.1-0.15.3.jar
Xaeros_Minimap_23.8.0_Fabric_1.20.jar                
lithium-fabric-mc1.20.1-0.11.2.jar
YungsApi-1.20-Fabric-4.0.1.jar                       
malilib-fabric-1.20.1-0.16.2.jar
YungsBetterDesertTemples-1.20-Fabric-3.0.1.jar       
memoryleakfix-fabric-1.17+-1.1.2.jar
YungsBetterDungeons-1.20-Fabric-4.0.1.jar            
midnightlib-fabric-1.4.1.jar
YungsBetterJungleTemples-1.20-Fabric-2.0.1.jar       
mineful_coins-0.1-1.20.1.jar
YungsBetterMineshafts-1.20-Fabric-4.0.1.jar          
minihud-fabric-1.20.1-0.27.0.jar
YungsBetterOceanMonuments-1.20-Fabric-3.0.1.jar      
mixintrace-1.1.1+1.17.jar
YungsBetterStrongholds-1.20-Fabric-4.0.1.jar         
modmenu-7.2.2.jar
YungsBridges-1.20-Fabric-4.0.1.jar                   
moonlight-1.20-2.8.24-fabric.jar
YungsExtras-1.20-Fabric-4.0.1.jar                    
moremobvariants-fabric+1.20-1.2.2.jar
Zoomify-2.11.2.jar                                   
polaroidcamera-1.6.2.jar
architectury-9.1.12-fabric.jar                       
reeses_sodium_options-1.6.3+mc1.20.1-build.92.jar
audioplayer-1.20.1-1.8.1.jar                         
roughly-searchable-2.6.0+1.20.1.jar
authme-7.0.2+1.20.jar                                
shulkerplus-mc1.20.1-v1.0.7-fabric.jar
beautify-1.0.0+fabric-1.20.jar                       
simpletrims-0.2.0.jar
bwncr-fabric-1.20.1-3.17.0.jar                       
sliceanddice-fabric-3.0.0.jar
cloth-config-11.1.106-fabric.jar                     
sodium-extra-0.4.23+mc1.20.1-build.106.jar
continuity-3.0.0-beta.3+1.20.1.jar                   
sodium-fabric-mc1.20-0.4.10+build.27.jar
create-fabric-0.5.1-d-build.1161+mc1.20.1.jar        
spark-1.10.53-fabric.jar
create-mod-trims-1.0.0.jar                           
traverse-7.0.9.jar
elytratrims-1.3.3+1.20.jar                           
voicechat-fabric-1.20.1-2.4.24.jar
emotecraft-for-MC1.20.1-2.2.7-b.build.50-fabric.jar  
worldedit-mod-7.2.15.jar
entity_model_features_fabric_1.20-1.0.jar            
yet-another-config-lib-fabric-3.1.1+1.20.jar
entity_texture_features_fabric_1.20-4.5.1.jar

**Comment by IThundxr** [comment]
Occurs on forge aswell, should be reported there
