### ISSUE TITLE
Create server lag

### ISSUE THREAD

**Issue by DonorKrovi** [Fabricators-of-Create/Create#1158]
### Describe the Bug

https://spark.lucko.me/Gmdom1rAzS

### Reproduction Steps

1.idk

### Expected Result

.

### Crash Report or Log

https://spark.lucko.me/Gmdom1rAzS

### Operating System

Unbuntu 20

### Mod Version

create (v0.5.1-c-build.1160+mc1.19.2)

### Minecraft Version

1.20.1

**Comment by ARitz-Cracker** [comment]
How are the developers of this mod supposed to get any useful information from the link you provided? Also, you're only giving your minecraft server 4GB of RAM?

**Comment by DonorKrovi** [comment]
> How are the developers of this mod supposed to get any useful information from the link you provided? Also, you're only giving your minecraft server 4GB of RAM?

![image](https://github.com/Fabricators-of-Create/Create/assets/60231586/9e9b9dc2-186c-4000-a920-d45b4d623f96)

The server is allocated 16 GB of RAM, I don't know what can cause such lags on the server, here is another profile with a block due to which the TPS of the server cannot rise above 16 in some cases

https://spark.lucko.me/vKYA0JOYzQ

**Comment by DonorKrovi** [comment]
Ok I recognized the block that creates latency on the server

![image](https://github.com/Fabricators-of-Create/Create/assets/60231586/8f1c67fd-161e-4f31-872a-aade4251edd8)
![image](https://github.com/Fabricators-of-Create/Create/assets/60231586/c9eaa837-44e9-4deb-8dda-b1c529636bd3)

**Comment by DonorKrovi** [comment]
![image](https://github.com/Fabricators-of-Create/Create/assets/60231586/fea14a9f-21d0-4620-9548-e3f0149629b2)
In this case, we have a large storage with a huge number of items, which probably loads the smart chute?

**Comment by DonorKrovi** [comment]
![image](https://github.com/Fabricators-of-Create/Create/assets/60231586/c8144eb8-d596-4519-bb0b-7364c9bca8db)
Although there is an empty storage nearby, and the load is also present here, although it is inactive, it would seem

**Comment by DonorKrovi** [comment]
![image](https://github.com/Fabricators-of-Create/Create/assets/60231586/43bebc46-232a-4321-b3fc-020155dacd11)
After I removed the filter here, it seemed to get better

**Comment by Kevinello** [comment]
> ognized

i'm curious about how to visualize the tick like you?  which mod provides such feature?

**Comment by adaliszk** [comment]
> @Kevinello: i'm curious about how to visualize the tick like you? which mod provides such feature?

It is probably https://modrinth.com/mod/observable 😉

**Comment by IThundxr** [comment]
Fixed in patch f (unreleased version atm but this is a upstream issue that's been fixed in create forge)
