### ISSUE TITLE
Diagonal chutes transfer items incorrectly.

### ISSUE THREAD

**Issue by Sorontoronto** [Fabricators-of-Create/Create#1159]
### Describe the Bug

When you have a single diagonal chute, composed of 2 chutes diagonally 1 block apart, and an inventory is directly under the upper chute, items get transferred into the inventory rather than the bottom chute.

### Reproduction Steps

1.make diagonal chute
2.put chest/barrel/whatever under top chute
3.observe behavior
...

### Expected Result

Items go directly into the next chute, bypassing the inventory.

### Screenshots and Videos

[https://discord.com/channels/620934202875183104/976100492243501106/1163969155519741995](url)
video in #fabric-bugs in the discord.

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

c2me 0.2.0
carpet 1.4.112
enhancedblockentities 0.9
sodium 4.10 and iris something
entityculling 1.6.2-mc1.20.1
exordium 1.2.1
lithium 0.11.2
malilib 0.16.1
tweakeroo 0.17.1
itemscroller 0.20.0

### Additional Context

It might locationally void items as well. After I took the video thought I noticed that items were getting voided, but I replaced the dispenser and items no longer got voided. I don't know if I was just hallucinating or not.

**Comment by IThundxr** [comment]
Does this occur on forge aswell?

**Comment by IThundxr** [comment]
This is a forge issue aswell.
