### ISSUE TITLE
crash when deployer kills entity

### ISSUE THREAD

**Issue by Illyena** [Fabricators-of-Create/Create#1160]
### Describe the Bug

When a deployer kills an entity, the came crashes with this error:
The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "capturedDrops" is null

### Reproduction Steps

1.setup deployer to attack mode
2. place entity in front of deployer
3. continue until entity dies
...

### Expected Result

entity drops are processed through deployer

### Crash Report or Log

https://pastebin.com/B72U9aJf

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Fabric API 0.87.0+ 1.20.1

**Comment by madeline0706** [comment]
Getting the same crash on my server. Deployer killing mobs, had to change difficulty to peaceful to fix it, instant server crash when loaded in otherwise.

**Comment by haventhadadonutyet** [comment]
Getting a crash just like this on my server, 1.20.1 fabric as well

**Comment by drwoops** [comment]
known issue. it will be fixed in next patch.

**Comment by TropheusJ** [comment]
duplicate of #1096
