### ISSUE TITLE
Treasure Maps/Shipwrecked seems to crash games

### ISSUE THREAD

**Issue by KavisKryptic** [Fabricators-of-Create/Create#1161]
### Describe the Bug

In singleplayer, when near a shipwrecked, it seems to lag the game like crazy. 
In multiplayer you crash

### Reproduction Steps

1.Have the create mod installed
2.Go in singleplayer
3.Locate structure shipwrecked
4. Teleport and experience lag until the game crashes
...
For multiplayer seems to be holding treasure map crashes your game

### Expected Result

For it not to crash and lag

### Crash Report or Log

https://gist.github.com/KavisKryptic/4e2faf53ccbfe1fde76120f8cfb643bb

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

accelerateddecay 3.0.0+mc1.20.1
	- accurateblockplacement 1.2
	- advancementinfo 1.20-fabric0.83.0-1.4
	- advancementscreenshot 4.2
	- amethyst_core 1.2.2+1.20.1
	- amethyst_imbuement 1.20.1-10
	- appleskin 2.5.1+mc1.20
	- architectury 9.1.12
	- armor-stand-editor 2.1.2+1.20.1
	- athena 3.1.1
	- authme 7.0.2+1.20
	- auudio 1.0.3
	- azurelibarmor 1.0.3
	- balm-fabric 7.1.4
	- barteringstation 8.0.0
	- better_end_sky 0.2.1+1.20
	- bettercombat 1.7.4+1.20.1
	- betterstats 3.2+fabric-1.20.1
	- betterthirdperson 1.9.0
	- bookshelf 20.0.5
	- borderlessmining 1.1.8+1.20.1
	- bwncr 3.17.0
	- cardinal-components 5.2.2
	- casualness_delight 1.20.1-0.2a
	- cavedust 1.4.1
	- cccbridge 1.6.2b-fabric
	- chat_heads 0.10.22
	- cherishedworlds 6.1.2+1.20.1
	- chesttracker 1.1.22
	- chipped 3.0.1
	- chunksfadein 1.0.4-1.20.1
	- citresewn 1.1.3+1.20
	- cleancut 6.0+mc1.19.1-mc1.20.x
	- cleardespawn 1.1.13
	- cloth-config 11.1.106
	- clumps 12.0.0.3
	- cobblemon 1.4.0+1.20.1
	- collective 6.66
	- combatroll 1.2.2+1.20.1
	- computercraft 1.108.3
	- continuity 3.0.0-beta.4+1.20.1
	- corgilib 4.0.0.4
	- cosmetic-armor 1.6.0
	- craftingtweaks 18.2.1
	- craftpresence 2.2.3
	- create 0.5.1-d-build.5+mc1.20.1
	- ctrl-q 1.9
	- cull-less-leaves 1.3.0
	- deathcounter 2023.6.1
	- deathlog 0.3.2+1.20
	- delightfulcreators 1.1.8
	- despawningeggshatch 4.1
	- detailab 2.6.3+1.20.1-fabric
	- dismountentity 3.0
	- do_a_barrel_roll 3.3.5+1.20
	- dynamic_fps 3.2.1
	- dynamiccrosshair 7.3+1.20
	- dynamiccrosshaircompat 3.4+1.20.1
	- easymagic 8.0.1
	- echochest 8.0.0
	- enchdesc 17.0.8
	- enhanced_attack_indicator 1.0.4+1.20
	- entity_model_features 1.0.2
	- entity_texture_features 4.5.1
	- entityculling 1.6.2-mc1.20.1
	- expandeddelight 0.3.0.2
	- explosiveenhancement 1.2.1-1.20.x
	- extended_drawers 2.0.7+mc.1.20.1
	- fabric-api 0.90.0+1.20.1
	- fabric-language-kotlin 1.10.10+kotlin.1.9.10
	- fabricloader 0.14.22
	- fallingleaves 1.15.4
	- farmersdelight 1.20.1-1.4.2
	- farmersknives 3.0
	- faster_entity_animations 1.6
	- ferritecore 6.0.0
	- feytweaks 1.20-1.2.7
	- forgeconfigapiport 8.0.0
	- fusion 1.0.6
	- fwaystones 3.1.3+mc1.20
	- fzzy_core 0.2.7+1.20.1
	- geckolib 4.2.3
	- goop 1.20.1-0.2
	- guardiansgalore 1.20.1-3.1
	- handcrafted 3.0.1
	- highlight 2.0.1
	- highlighter 1.1.6
	- iceberg 1.1.15
	- immediatelyfast 1.2.6+1.20.2
	- immersive_armors 1.6.1+1.20.1
	- indium 1.0.27+mc1.20.1
	- infinitybuttons 4.0.1-mc1.20.1
	- interactic 0.2.0+1.20
	- inventoryessentials 8.2.1
	- invmove 0.8.4
	- iris 1.6.9
	- jade 11.6.2
	- jadeaddons 5.2.1
	- java 17
	- jei 15.2.0.27
	- jumpoverfences 1.3.0
	- kiwi 11.1.1
	- konkrete 1.6.1
	- krypton 0.2.3
	- lambdynlights 2.3.2+1.20.1
	- languagereload 1.5.9+1.20.1
	- lazydfu 0.1.3
	- letmedespawn fabric-1.20-1.1.0
	- lightingwand 8.0.0
	- lithium 0.11.2
	- loadmyresources 1.0.4
	- lolmcv 1.4.1
	- longerchathistory 1.3
	- lootr 0.7.29.75
	- macos_input_fixes 1.6
	- magistuarmory 7.11
	- make_bubbles_pop 0.2.0-fabric
	- mavapi 1.1.3
	- memoryleakfix 1.1.2
	- merchantmarkers 1.3.1
	- minecraft 1.20.1
	- minerally 1.20.2-1.0
	- moblassos 8.0.0
	- modernfix 5.8.1+mc1.20.1
	- modmenu 7.2.2
	- monsters_in_the_closet 1.0.3+1.20
	- moonlight 1.20-2.8.49
	- moreculling 1.20.1-0.19.0
	- mousetweaks 2.25
	- mousewheelie 1.13.0+mc1.20.1
	- mr_vanilla_refresh 1.4.17c
	- naturescompass 1.20.1-2.2.3-fabric
	- netherportalfix 13.0.0
	- notenoughanimations 1.6.4
	- owo 0.11.0+1.20
	- paladins 1.0.1+1.20.1
	- passiveshield 3.2
	- patchouli 1.20.1-81-FABRIC
	- player-animator 1.0.2-rc1+1.20
	- polymorph 0.49.0+1.20.1
	- presencefootsteps 1.9.0
	- puzzleslib 8.0.15
	- railways 1.5.1+fabric-mc1.20.1
	- reacharound 1.1.2
	- reeses-sodium-options 1.6.5+mc1.20.1-build.95
	- resourcefullib 2.1.11
	- respitecreators 1.2.0
	- runes 0.9.10+1.20.1
	- sassot 1.1.3-1.20.1+bettercombat
	- screenshot_viewer 1.2.1-fabric-mc1.20
	- seamless_loading_screen 2.0.3+1.20.1
	- showmeyourskin 1.6.11+1.20
	- shulkerboxtooltip 4.0.4+1.20.1
	- shulkerplus 1.0.7
	- signed_paintings 1.0.2-mc1.20+
	- simplehats 1.20.1-0.2.0
	- simplemagnets 1.1.10
	- skinlayers 1.5.4-mc1.20.1
	- slimyfloor 1.20-1.2.8
	- smarterfarmers 1.20-1.7.3
	- smwyg 1.1.1
	- sodium 0.5.3
	- sodium-extra 0.5.1+mc1.20.1-build.112
	- spell_engine 0.11.0+1.20.1
	- spell_power 0.9.17+1.20.1
	- spyglass_astronomy 1.0.6-mc1.20+
	- sspb 3.2.1
	- stack-to-nearby-chests 0.4.0
	- starlight 1.1.2+fabric.dbc156f
	- stendhal 1.3.9-1.20
	- superflatworldnoslimes 3.0
	- supermartijn642configlib 1.1.7
	- supermartijn642corelib 1.1.12+b
	- supplementaries 1.20-2.6.12
	- threadtweak 1.20.2-0.1.1
	- tia 1.20-1.1
	- titlefixer 1.0+1.20.1
	- toms_storage 1.6.5
	- toolstats 16.0.4
	- tooltipfix 1.1.1-1.20
	- tradingpost 8.0.1
	- travelersbackpack 1.20.1-9.1.6
	- travelerstitles 1.20-Fabric-4.0.1
	- trinkets 3.7.1
	- visuality 0.7.1+1.20
	- visualworkbench 8.0.0
	- wakes 0.2.0
	- waterdripsound 1.19-0.3.2
	- waveycapes 1.3.2
	- wizards 1.0.1+1.20.1
	- wwoo 2.0.0
	- xaerominimap 23.8.2
	- xaeroworldmap 1.34.1
	- yet_another_config_lib_v3 3.2.1+1.20
	- yosbr 0.1.2
	- yungsapi 1.20-Fabric-4.0.2
	- zoomify 2.11.2

### Additional Context

Note that I did use the create 0.5.1d build instead of the sodium fix one in multiplayer. It didn't crash me but it definitely caused serious lag.

Nevermind, it was a seperate issue entirely it seems. At least the lagging seems to be. Not sure about crashing on servers with the map.

**Comment by zaneshaw** [comment]
Did you ever resolve the crashing on servers?

**Comment by TropheusJ** [comment]
treasure map deadlock crashes are a vanilla issue that occurs whenever the game searches for treasure for over 60 seconds.

**Comment by zaneshaw** [comment]
Yeah I think my issue is unrelated then. Any player with a treasure map in their inventory won't crash, but they'll be disconnected and unable to join back. Don't remember the error code right now but it had something to do with 1 packet extra or something.

**Comment by TropheusJ** [comment]
anything less than full client and server logs is useless. make a new issue.
