### ISSUE TITLE
Game Crashes when interacting with objects

### ISSUE THREAD

**Issue by BoeyPimpin** [Fabricators-of-Create/Create#1165]
### Describe the Bug

For some reason, interacting with chests and furnaces immediately crashes my game and brings up the exit code -1. For context I am using the fabric version of create, with the additional mod Create: Steam n Rails and Create: Extended Cogwheels on the original Minecraft Launcher, running Fabric 1.19.2 with Fabric API 0.76.1
### Reproduction Steps

1. Run Minecraft
2. Open a pre-existing or new world
3. Interact with a chest, furnace, or other interactive block

### Expected Result

I expected to be able to open my chest and continue playing as normal

### Crash Report or Log

https://pastebin.com/HMjPySAy

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

Appleskin
architectury
bclib
better mount hud
blasting plus
bookshelf
boosted brightness
custom entity models (cem)
choice theorems overhauled village (CTOV)
CTOV friends and foes addon
cit resewn
cloth config
coinsje
completeconfig
couplings
croptopia
cull less leaves
diagonal fences
diagonal windows
durability viewer
dynamic fps
easy anvils
easy magic
effective
entity culling
expanded delight
explorers compass
extended gears
fabric api
fabric language kotlin
fabric loader
fancy spore blossom
farmers delight
ferrite core
forge config api port
geophilic
illuminations
indium
iris
jade
just enough items
konkrete
lamb dynamic lights
lazy dfu
leaves begone
load my resources
mcwbridges
mcwfences
mcwlights
mcwpaths
mcwwindows
minegate more blocks
mob plaques
model fix
modern fix
modmenu
moonlight
moremusic
mouse tweaks
natures compass
patchouli
polymorph
puzzles lib
reeses sodium options
your reputation
simple frames
simply swords
skin layers
slice and dice
smarter farmers
sodium
sodium extra
starlight
stylish effects
supermartijn642corelib
supplementaries
text utilities
timber
trash cans
trinkets
videotape
villager hats
visuality
visual overhaul
visual workbench
wall lanterns
worldedit
xaero's minimap
yet another config lib
zoomify

**Comment by IThundxr** [comment]
Please remove https://www.curseforge.com/minecraft/mc-mods/text-utilities
& FYI farmers delight fabric is broken and is missing a null check and NPEs when trying to use steam n rails bogey menu, we've got jars in the steam n rails discord that fixes this if you'd like the fix (this issue isn't on snr's side btw it's on FD-fabrics, I've already reported it but the dev doesn't seem to want to fix it)
