### ISSUE TITLE
[Visual] Copycats don't render transparent blocks behind them

### ISSUE THREAD

**Issue by NiXTheDev** [Fabricators-of-Create/Create#1167]
### Describe the Bug

Whenever you put a copycat block(for example, to hold water in washing setup), and apply iron bars to it, water is magically not rendering behind the copycat block, lava and glass work fine, this seems to apply to transparent liquids

### Reproduction Steps

1.Create a world and join it
2. Place water in any formation behind a vertical slab copycat block(s)
3. Apply iron bars to copycat block(s)
4. See the bug

### Expected Result

Water should be rendered behind the copycat block with a transparent item applied as it's mask

### Screenshots and Videos

![2023-10-21_20 36 19](https://github.com/Fabricators-of-Create/Create/assets/105677206/6e1d29e3-665b-4782-b821-46f34fae955c)
![2023-10-21_20 50 55](https://github.com/Fabricators-of-Create/Create/assets/105677206/77f9e003-1130-4af0-a1ea-09dad181ad30)
![2023-10-21_20 51 02](https://github.com/Fabricators-of-Create/Create/assets/105677206/a019115c-1522-49ea-9498-76e8e024346b)
![2023-10-21_20 50 49](https://github.com/Fabricators-of-Create/Create/assets/105677206/cc558cfd-b655-4f69-82e8-2f01abdff1d1)

### Crash Report or Log

None, doesn't crash the game

### Operating System

Windows 10 64 bit

### Mod Version

0.5.1d

### Minecraft Version

1.19.2

**Comment by Mcjiprock** [comment]
This also happens with other copycat panels or steps whenever placed on a train.
