### ISSUE TITLE
[1.20.1] Contraptions do not produce footsteps

### ISSUE THREAD

**Issue by Sollace** [Fabricators-of-Create/Create#1169]
### Describe the Bug

Some backstory:
I was working on implementing a proper solution to generating footsteps when walking on contraptions with Presence Footsteps, but I was unable to get any sounds to play at all.

I had some success with adding a mapping to the blockmap.json to use the existing function, and removing the part that blocks sounds from coming over the network, but for some reason it only worked for other players in multiplayer and only _sometimes_ for yourself, and wouldn't produce steps appropriate to the blocks in the contraption.

I also noticed that footsteps would also not play when PF itself was turned off, so I left it.

Then today I was looking at it again, and after working out a proper solution that integrates with Create directly... It still wouldn't play.

So I decided to just remove PF completely from the environment and test it like that.

Turns out Create's contraptions don't produce footsteps _at all_ even with the mod loaded on its own with nothing besides Create, Mod Menu, and Quilted Fabric API.

### Reproduction Steps

The setup I used looks like this:

![image](https://github.com/Fabricators-of-Create/Create/assets/6429283/c7c05f3f-b5d0-4357-91f0-b1e720208b62)

Without really knowing very much, I use a motor, axel, and bearing to rotate some blocks and stomped around on them in creative.

Footsteps work when walking on regular blocks, but nothing plays when walking on the rotated blocks.

### Expected Result

Self explanatory

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/6429283/fe465c16-2e0f-4de9-b458-8056dc1ccd5f)

### Operating System

Linux

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
A PR should be made to the forge repo adding footsteps to contraptions. Or a issue if you don't wanna make a PR

**Comment by TropheusJ** [comment]
I am pretty sure they used to make sound, which prompted my original issue about compat. Did you check if it's actually broken on forge too?

**Comment by IThundxr** [comment]
> I am pretty sure they used to make sound, which prompted my original issue about compat. Did you check if it's actually broken on forge too?

Yes its broken on forge aswell, they dont make sounds

**Comment by IThundxr** [comment]
Upstream reported at https://github.com/Creators-of-Create/Create/issues/6118

**Comment by DarianLStephens** [comment]
Yeah, this has been an issue since 1.19.
Interestingly, Valkyrien Skies had the exact same thing happen at the same time, a loss of footstep sounds when transitioning to Minecraft 1.19.
My suspicion is that something changed with how Minecraft handles them, and the mods never updated to deal with it.
