### ISSUE TITLE
Placing deployer causes crashes. (Server - TabTPS mod)

### ISSUE THREAD

**Issue by michlbro** [Fabricators-of-Create/Create#117]
### Describe the Bug

Placing the deployer in a Minecraft Server causes the Server to crash. - Server won't start up anymore.

### Reproduction Steps

1. Open up a Minecraft server.
2. Place deployer down.

### Expected Result

Erm, not to crash the server when placing down the deployer.

### Crash Report or Log

https://pastebin.com/cqdL06bS

### Operating System

Windows 11

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

bclib - 1.2.5
ferritecore - 4.0.0
indium - 1.0.2 alpha 2
starlight - 1.0.1
sodium - 0.4.0 alpha 6
iris - 1.2.0

**Comment by michlbro** [comment]
Actually scrap that ^ - I lied, I have a few other mods installed. Currently looking for the mod causing incompatibilities. + Happens on client too.

**Comment by TropheusJ** [comment]
It’s https://github.com/KyoriPowered/adventure-platform-fabric

**Comment by michlbro** [comment]
Yep, I'm guessing TabTPS uses adventure-platform-fabric, which some how breaks create.

**Comment by TropheusJ** [comment]
passed on, there's nothing we can do on our side.

**Comment by itsdinkd** [comment]
From @KyoriPowered dev

>If you look at everywhere Connections are created in vanilla (the static factory methods in Connection, and net.minecraft.server.network.ServerConnectionListener.startTcpServerListener(), you'll see that every returned Connection object is initialized with a channel by the time the method returns. This is also supported by the fact that channel is an un-annotated field in a package Mojang has annotated with FieldsAreNonnullByDefault.

>However, this issue has come up before -- see the discussion at https://github.com/gnembon/fabric-carpet/issues/1142. I expect as long as people continue rolling their own fake player systems, we'll see similar issues. Because of that, I think the most appropriate long-term solution to this issue is to get a fake player system added to Fabric API. I'll write up an issue there.


and

>It's entirely possible to resolve this issue -- Player thinks a proper fake player API is in scope, and that's something I believe he'll need himself eventually for IC2. If other mod developers want to accelerate progress on this solution, they are welcome to open a pull request to Fabric API with their own proposal for API.

https://github.com/KyoriPowered/adventure-platform-fabric/issues/14
https://github.com/KyoriPowered/adventure-platform-fabric/issues/15

Any chance to work on this for FAPI?

**Comment by HaXrDEV** [comment]
Bump. This should be looked at as the issue has indeed been fixed by other devs as mentioned above. So many server utility mods are made using the adventure library, so i think this incompatibility is a huge blow to anyone wanting to run any sort of production server with the Create mod.

**Comment by imreallybadatnames** [comment]
> passed on, there's nothing we can do on our side.

@TropheusJ reconsider what you said

**Comment by imreallybadatnames** [comment]
you know what, i will redirect this issue to the real person responsible(prev. comment removed)
nice of you to notice the real side of the issue, but seems like nothing was done.

**Comment by jpenilla** [comment]
This has been fixed in fake-player-api 0.5.1

edit: noticing that create moved to it's own fake player impl, the version I was testing with must have been from before then
