### ISSUE TITLE
Support for EMI "World Interaction" recipes

### ISSUE THREAD

**Issue by Silveere** [Fabricators-of-Create/Create#1170]
### Describe the Suggestion

EMI has the ability to display recipes for certain blocks made by interactions between fluids. For example, when viewing the recipes for cobblestone, EMI will show the interaction between water and lava as a "world interaction" recipe. Create should register similar recipes to EMI (lava + honey/chocolate).

### Screenshots and Videos

EMI "World Interaction" tab:
![image](https://github.com/Fabricators-of-Create/Create/assets/15041225/e1786002-3d02-423d-ba98-6b7555a1d704)

**Comment by electricsteve** [comment]
ah, i see this would be really simple using [this](https://github.com/emilyploszaj/emi/wiki/Adding-Recipes) tutorial, ima do that

**Comment by electricsteve** [comment]
O wait, I think this should be done upstream, so in the forge version

**Comment by BugInYourCode01** [comment]
Hello, there's a little bug left. If you go to the [limestone] world interaction recipe and click the recipe tree button on the right and want to produce 5 [limestone], EMI will tell you that you need 5 liters of lava and and 5 liters of [honey]. Please fix this. If you look at the cobble generator recipe on the same tab and hover over water or lava there's an arrow pointing to the right to the fluid. Add that and I am happy. (I'm already, but...)

_Originally posted by @MrRedstoneToGo in https://github.com/DakotaPride/create-garnished/issues/52#issuecomment-2004790929_
