### ISSUE TITLE
No Zinc Spawn in Server

### ISSUE THREAD

**Issue by SirSnizzler** [Fabricators-of-Create/Create#1172]
### Describe the Bug

I have made a server with my friends for Better Minecraft Fabric edition 1.19.2. We started the server without the Create Fabric Mod but installed it about a day into playing the server. We added it to the server and have travelled many many unloaded chunks to try and find zinc but cannot. We also can't see the crafting recipes for Create in our recipe browser mod that came with Better Minecraft. 

### Reproduction Steps

1.
2.
3.
...

### Expected Result

In hopes of resolving the issue of not being able to find zinc/see crafting recipes for Create Mod items.

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.20.1

### Other Mods

Better Minecraft Mod Pack

**Comment by electricsteve** [comment]
IDK about better minecraft, but maybe they disabled added mods or they preloaded chuncks with chunky or smt, please provide more info. Maybe also report issue on better minecraft issue tracker?

**Comment by IThundxr** [comment]
Most likely a issue with your pack, `//replacenear 100 !create:zinc_ore air` results with this 
![image](https://github.com/Fabricators-of-Create/Create/assets/74031881/b5e4e3ac-0079-4136-9efd-9dd4d09142b3)
