### ISSUE TITLE
Wiki page for Fabric

### ISSUE THREAD

**Issue by PSGitHubUser1** [Fabricators-of-Create/Create#1173]
### Describe the Suggestion

Forge Create has wiki for 'Depending on Create' but fabric doesn't have it.. Please provide a wiki for developing with create and it's APIs. Or if you don't want (maybe cuz you guys will already busy), just provide all dependants here.

And I will add 'em as MCreator plugin. Or can anybody make MCreator plugin for add support for create mod in MCreator  Fabric.

**Comment by IThundxr** [comment]
Fabric create already provides a fabric template and multiloader template

**Comment by rhysdh540** [comment]
please not mcreator :(

**Comment by PSGitHubUser1** [comment]
I mean a website with which I can implement the api. In my plugin.. Like https://mcreator.net/plugin/100514/create-api-forge-1192-1201

**Comment by IThundxr** [comment]
> I mean a website with which I can implement the api. In my plugin.. Like [mcreator.net/plugin/100514/create-api-forge-1192-1201](https://mcreator.net/plugin/100514/create-api-forge-1192-1201)

The recipes and everything are the same as forge except that fluid recipes use droplets (milibuckets * 81), the apis are more or less the same but you should take a look at the source to see how they work etc, the code is pretty self documenting

**Comment by PSGitHubUser1** [comment]
Hey, can you please change this code into fabric? pls? like what should be done when removing 'fg.deoobf'?
Just provide fabric version of this code which was on [forge wiki](https://github.com/Creators-of-Create/Create/wiki/Depending-on-Create).. please

```
dependencies {
    implementation fg.deobf("com.simibubi.create:create-${create_minecraft_version}:${create_version}:slim") { transitive = false }
    implementation fg.deobf("com.jozufozu.flywheel:flywheel-forge-${flywheel_minecraft_version}:${flywheel_version}")
    implementation fg.deobf("com.tterrag.registrate:Registrate:${registrate_version}")
}
```

**Comment by IThundxr** [comment]
> Hey, can you please change this code into fabric? pls? like what should be done when removing 'fg.deoobf'?
> 
> Just provide fabric version of this code which was on [forge wiki](https://github.com/Creators-of-Create/Create/wiki/Depending-on-Create).. please
> 
> 
> 
> ```
> 
> dependencies {
> 
>     implementation fg.deobf("com.simibubi.create:create-${create_minecraft_version}:${create_version}:slim") { transitive = false }
> 
>     implementation fg.deobf("com.jozufozu.flywheel:flywheel-forge-${flywheel_minecraft_version}:${flywheel_version}")
> 
>     implementation fg.deobf("com.tterrag.registrate:Registrate:${registrate_version}")
> 
> }
> 
> ```

This is basic fabric modding, the wiki goes over it and frankly you shouldn't be modding if you don't know this. And once again the fabric addon template shows you how to add create to your dev env

**Comment by PSGitHubUser1** [comment]
> > Hey, can you please change this code into fabric? pls? like what should be done when removing 'fg.deoobf'?
> > Just provide fabric version of this code which was on [forge wiki](https://github.com/Creators-of-Create/Create/wiki/Depending-on-Create).. please
> > ```
> > 
> > dependencies {
> > 
> >     implementation fg.deobf("com.simibubi.create:create-${create_minecraft_version}:${create_version}:slim") { transitive = false }
> > 
> >     implementation fg.deobf("com.jozufozu.flywheel:flywheel-forge-${flywheel_minecraft_version}:${flywheel_version}")
> > 
> >     implementation fg.deobf("com.tterrag.registrate:Registrate:${registrate_version}")
> > 
> > }
> > ```
> 
> This is basic fabric modding, the wiki goes over it and frankly you shouldn't be modding if you don't know this. And once again the fabric addon template shows you how to add create to your dev env

I am just making a mcreator plugin so.. and i cant waste like days just to make a plugin that nobody will know about. thats why I  asked you to tell me like if the plugin works then its good but if it doesnt then ill just delete the whole folder in anger anyways.

**Comment by PSGitHubUser1** [comment]
it would be nice if you tell me.. (please)

**Comment by IThundxr** [comment]
https://github.com/Fabricators-of-Create/create-fabric-addon-template

**Comment by PSGitHubUser1** [comment]
umm you mean this?
https://github.com/Fabricators-of-Create/create-fabric-addon-template/blob/1.18/build.gradle

**Comment by IThundxr** [comment]
> umm you mean this?
> 
> https://github.com/Fabricators-of-Create/create-fabric-addon-template/blob/1.18/build.gradle

Yes

**Comment by PSGitHubUser1** [comment]
i hope this works for this thing:
https://mcreator.net/plugin/103828/loot-modifier
