### ISSUE TITLE
blocks cant be instant mined while standing on the contraption (high efficiency tool)

### ISSUE THREAD

**Issue by liangmoe** [Fabricators-of-Create/Create#1174]
### Describe the Bug

as title

### Reproduction Steps

Place contraption, standing on it and mine any block that can be instant mined

### Expected Result

block wont be mined

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/135343248/477fef01-ed7a-49ed-9d6b-0213d156d5f2

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

**Comment by IThundxr** [comment]
occurs on forge aswell
