### ISSUE TITLE
Bars in copycats appear wrong when Continuity is installed

### ISSUE THREAD

**Issue by wool25** [Fabricators-of-Create/Create#1176]
### Describe the Bug

All bars (vanilla and create) seem to use the wrong side of the model as the copycat texture

### Reproduction Steps

1. place copycat panel
2. place bars into copycat panel
3. enjoy

### Expected Result

they should be displaying the 2-block connected texture 

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/108700081/a90ba2fe-8f88-4f47-b68e-afc3d26665b2)

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Additional Context

Has been happening for a while now (still not fixed)

**Comment by wool25** [comment]
Bars inside vertical panels also lack a side texture

**Comment by ruwaku** [comment]
I have the same issue. Disabling the 'Continuity' mod resolved the problem.

**Comment by IThundxr** [comment]
Doesn't occur on lastest commit

**Comment by acanthii** [comment]
![image](https://github.com/Fabricators-of-Create/Create/assets/62764868/8d63749f-96c3-44bd-ab54-5bb26caf58bd)
Issue still persists with 0.5.1f with Continuity installed.

EDIT: By the way, congrats on the fabric update release, guys! :)

**Comment by Cadeyrnnn** [comment]
Issue still persists with Create 1.20.1 v0.5.1.f Patch 1 on fabric. To add information : the bug only happens if a texture pack using connected textures is loaded.

**Comment by IThundxr** [comment]
Yep we know, hence why this is still open, I'll take a further look on this sometime later this week.
