### ISSUE TITLE
The train cannot assemble the chiseled blocks from the 'Chisels & Bits' mod

### ISSUE THREAD

**Issue by Cylindr306** [Fabricators-of-Create/Create#1177]
### Describe the Bug

The train cannot assemble the chiseled blocks from the 'Chisels & Bits' mod

### Reproduction Steps

1.Assembling the chiselled blocks from the 'Chisels & Bits' module

### Expected Result

Assembly failed

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/134772605/4857f68c-0d92-4779-95c0-14dabe5e8af6)
![image](https://github.com/Fabricators-of-Create/Create/assets/134772605/c0a8f906-2cef-4d87-862c-222d657559e1)

### Operating System

Windows 11

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

fabric-api-0.76.1+1.19.2
chisels-and-bits-fabric-1.3.135

### Additional Context

Full create version:create-fabric-0.5.1-c-build.1160+mc1.19.2

**Comment by IThundxr** [comment]
This is done purposely, Chisel and bit's blocks don't properly render on contraptions with any backend, this would likely need compat from their side
