### ISSUE TITLE
Game crashes when trying to access UI elements with Indium

### ISSUE THREAD

**Issue by vague2k** [Fabricators-of-Create/Create#1178]
### Describe the Bug

Game crashes when trying to access UI elements with Indium version 1.0.21

### Reproduction Steps

1. Make sure to have Mod version 0.5.1-d-build.1161 and indium-1.0.21 installed
2. Open any Tab relating to create.
3. Game crashes
...

### Expected Result

UI element is accessed

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/121782036/e7dd7403-1576-425c-887e-d2fe3435fd54

### Crash Report or Log

https://pastebin.com/MD2QdzVJ

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/121782036/4f3dd67d-e3a4-47a9-b4ea-101595cc9a62)

**Comment by rilakuma123** [comment]
Use Fabric API 0.88.1 for Indium 1.0.21 to work.

**Comment by drwoops** [comment]
create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 and indium 1.0.21 are the precise versions you want

**Comment by rilakuma123** [comment]
@vague2k Please close this as it isn't an issue with Create Fabric.

**Comment by Abalieno** [comment]
Since when forcing outdated versions "isn't an issue"?

**Comment by rilakuma123** [comment]
@Abalieno There's already an issue tracking Sodium 0.5 compatibility. It's pinned.

Older versions of Indium don't work with Fabric API 0.88.1+ and you can't expect it's developer to release an update for an older version of Sodium.
