### ISSUE TITLE
Item Vault deleting Items

### ISSUE THREAD

**Issue by smevulark** [Fabricators-of-Create/Create#1183]
### Describe the Bug

when using a schematic cannon with an item vault, I had worked out how many blocks I needed for the build and put more then enough items in the item vault but some time after the schematic cannon had started items randomly disappeared form the vault.

### Reproduction Steps

1.filled item vault with a large amount of items needed for build.
2.placed schematic cannon on top and hit start on the cannon.
3.after a while it displayed it couldn't find any of the andesite needed despite me putting more in the item vault.
(the build needed the following blocks: stone, andesite, cyan terracotta, cut deep slate, moss block, grass block)
4.checked what was inside the item vault and it had nun of the andesite i had put inside the vault.

### Expected Result

my expectation was for the item vault not to delete a random amount of the items in the vault.

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by drwoops** [comment]
could it be an issue with claims?

**Comment by smevulark** [comment]
> could it be an issue with claims?

there are no claims on the server I'm on

**Comment by IThundxr** [comment]
Unable to reproduce with any number of vaults, schematics and blocks
