### ISSUE TITLE
FPS drops on a Macbook

### ISSUE THREAD

**Issue by Petrus2407** [Fabricators-of-Create/Create#1187]
### Describe the Bug

**Problem :**
My world runs stable, until I place a waterwheel. After I placed the wheel my FPS drop down to 3.
I think this bug is only on mac (my friends PC don´t has any Problems with them).

### Reproduction Steps

1. Place a any kind of waterwheel on a mac divice

### Expected Result

No more giant FPS Drops due to the waterwheels.

### Operating System

MACos sonoma 14.1.1

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![Unbenannt1](https://github.com/Fabricators-of-Create/Create/assets/150287120/abcc8a78-4c83-4a80-ba5b-6d271f1f7c1b)
![Unbenannt2](https://github.com/Fabricators-of-Create/Create/assets/150287120/3fc34350-9508-42cc-b6d6-ae0f40412e7b)

**Comment by Hancoki** [comment]
I can confirm this issue under Windows 11 22H2 with same version of Minecraft and Create mod. The FPS drop from 100+ under 10, when placing some waterwheels.

**Comment by FoxinCode** [comment]
Same Issue, 2019 MBP I9/5500M 

Edit: Found a fix, do "/flywheel backend batching"

**Comment by TropheusJ** [comment]
batching tends to perform better on AMD GPUs. In a future flywheel update, it will no longer be needed.
