### ISSUE TITLE
Item pentupling with operate

### ISSUE THREAD

**Issue by SFort** [Fabricators-of-Create/Create#1188]
[Operate releases](https://github.com/SFort/MC-Operate/releases)
[Relavent operate code](https://github.com/SFort/MC-Operate/blob/master/src/main/java/tf/ssf/sfort/operate/pipe/EntrancePipeEntity.java#L59)

In a nutshell those pipes take items and remove them immediatly.
i probably should be waiting a tick, still create should probably not set the slot five times or maybe check if the item got removed.

https://github.com/Fabricators-of-Create/Create/assets/1879846/fe596942-e1a4-46fd-8118-2918a0de3efa

### Reproduction Steps

1. Place down a operate entrance pipe
2. Place a chute above it
3. put item in chute

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
These pipes have complex logic that's incompatible with fabric's best-effort transfer API inventory wrapper. There's nothing that can be done on Create's end.
You'll have to move away from Inventory/SidedInventory and register a provider to ItemStorage.SIDED.
