### ISSUE TITLE
Berry Bush Harvesting

### ISSUE THREAD

**Issue by Daniel99j2** [Fabricators-of-Create/Create#1190]
### Describe the Bug

When a berry bush is harvested by a mechanical harvester, the plant is replaced at [age=0]. When normally right clicking on the bush, it drops berries and goes to [age=1].

### Reproduction Steps

1. Place berry bush
2. Harvest with mechanical harvester
3.
...

### Expected Result

The replanted bush is at [age=1]

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.19.2

### Other Mods

Many, but irrelivant

**Comment by IThundxr** [comment]
Cannot reproduce on forge or fabric patch f
