### ISSUE TITLE
Minecraft crash upon pressing create menu button

### ISSUE THREAD

**Issue by hoangtanak** [Fabricators-of-Create/Create#1191]
### Describe the Bug

Minecraft crash upon pressing create menu

### Reproduction Steps

1.When ingame, press "esc" and open minecraft menu
2.Click on icon of create
3. Crash

### Expected Result

Create menu opened

### Crash Report or Log

https://mclo.gs/7UWGmXT

### Operating System

Window 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/44888463/29ec0197-7a4e-4459-b927-74d5edecb3c4)

**Comment by drwoops** [comment]
create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 and indium 1.0.21 are the precise versions you want (copied from my usual msg in the discord)
