### ISSUE TITLE
Create items turning invisible

### ISSUE THREAD

**Issue by Zeebooo** [Fabricators-of-Create/Create#1193]
Hello,

I have been playing on a server with my friend for a couple of weeks with the create mod and a whole bunch of other mods. Everything was working fine untill we downloaded some new mods. This caused some items like the water wheels, nixie tubes, crushing wheels and a whole lot more to turn invisible. I removed all the new mods, re-downloaded create but the issue remains. Anyone know what to do?

**Comment by TropheusJ** [comment]
issues are useless with no information. Please use the template, it exists for a reason.
