### ISSUE TITLE
Contraption on Rope Pulley force-pulls player down, even in Spectator.

### ISSUE THREAD

**Issue by kalutro** [Fabricators-of-Create/Create#1196]
### Describe the Bug

Contraption using a Rope Pulley and Mechanical Drills as a quasi-quarry. If I stand on the contraption as it drills it's way down, it will pull me to it when it goes down another layer. This causes the player to not be able to ascend in water and they will drown. Oddly enough, this also happens in Spectator, though the player must stand on the contraption first. The pull breaks if you are able to get a certain amount of blocks above it, or if you can move away from it horizontally. This may also be accomplished by just jumping before the drills go down. You'll notice the contraption pull you down.

### Reproduction Steps

1. Rope Pulley contraption sending drills down.
2. Stand on the drills / chests as it goes down.
3. If in water, try to swim up. If not in water, switch to spectator and try to fly up.
...

### Expected Result

I wouldn't expect to be drowned by my own creation. :D

### Operating System

Win 10

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

Modpack is StaTech Industry

**Comment by IThundxr** [comment]
Occurs on forge aswell
