### ISSUE TITLE
Some Mechanical Belt's Unable to stack

### ISSUE THREAD

**Issue by wereretot** [Fabricators-of-Create/Create#1197]
### Describe the Bug

For some reason I have multiple stacks of Mechanical Belt as they do not stack.

### Reproduction Steps

Unknown as I do not know what has caused it.

### Expected Result

I expect all Mechanical Belts to stack into a single stack.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/28990565/03a185f8-47bf-49cd-8e65-5e04d76cb5d7)

### Operating System

Manjaro Linux

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/28990565/62fdfbcb-defe-42ab-bf16-72e12cde6a01)
![image](https://github.com/Fabricators-of-Create/Create/assets/28990565/d979e370-5612-46f9-b4ca-0c71c03a00ac)
![image](https://github.com/Fabricators-of-Create/Create/assets/28990565/e1d9caa4-28c9-4b85-8a9e-31682ea3fdeb)
![image](https://github.com/Fabricators-of-Create/Create/assets/28990565/17132714-5956-49eb-a26c-f02ebd0c6947)
![image](https://github.com/Fabricators-of-Create/Create/assets/28990565/db06134c-e0d0-46e7-9785-098cd959c2df)
![image](https://github.com/Fabricators-of-Create/Create/assets/28990565/4ff130fa-939d-4b1d-a581-b37da00bdf4b)
![image](https://github.com/Fabricators-of-Create/Create/assets/28990565/755d4f91-28ae-4788-a339-2ecc43c390a0)
![image](https://github.com/Fabricators-of-Create/Create/assets/28990565/5c28ab7e-c68e-4881-af7b-e3e66bf69c5e)

**Comment by denys-duchier** [comment]
Pretty sure i have seen this same behavior. The only explication is that these belts have different nbt data somehow

**Comment by TropheusJ** [comment]
This is a common issue with mods adding empty NBT to items when trying to check for a value. There is no easy way to figure out what mod causes it. If you place and break them all, it should be fixed.
