### ISSUE TITLE
Allow mechanical belts to be places diagonally sideways

### ISSUE THREAD

**Issue by wereretot** [Fabricators-of-Create/Create#1198]
### Describe the Suggestion

As the title states it would be really helpful if instead of having to place cogs facing up side by side to transfer force, we could place mechanical belts diagonally to save on shafts and cogs.

**Comment by TropheusJ** [comment]
Suggestions that are not Fabric exclusive should be submitted to [the Forge repo](https://github.com/Creators-of-Create/Create). 
But this is an extremely common one, so don't bother.
