### ISSUE TITLE
Incompatible with Indium

### ISSUE THREAD

**Issue by MetsukiMio** [Fabricators-of-Create/Create#1199]
### Describe the Bug

Placing some blocks have complex models cause a crash

### Reproduction Steps

1. Add mod Create, Sodium, Indium and Iris
2. Place some blocks have complex models
3. Crash

### Expected Result

It should be rendered correctly

### Crash Report or Log

https://pastebin.com/uvYHBmWK

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Sodium == 0.4.10
Indium == 1.0.21
Iris == 1.6.4

### Additional Context

None

**Comment by drwoops** [comment]
downgrade fabric api to 0.88.1
