### ISSUE TITLE
QuiltMC

### ISSUE THREAD

**Issue by YTG1234** [Fabricators-of-Create/Create#12]
## Discuss in the comments!

**Comment by PepperCode1** [comment]
I say we switch when their toolchain and software is almost completely stable.

**Comment by AlphaMode** [comment]
Stay on fabric because fabric mods should still work on quilt for awhile

**Comment by GlitchSlayed** [comment]
replying to the comment above, yes they do for now but quilt won't always support fabric mods as it progresses furthur and adds new features. Right now i say that we remain on fabric and eventually if need be it can be ported to quilt (much less work than from forge cause thier very simmilar mod loaders {quilt is a hardfork of fabric})

**Comment by TropheusJ** [comment]
Looks like we're getting more attention with this, so let me organize all the info for anyone who doesn't know what Quilt is, or what porting entails:
- First, what is Quilt? Quilt is a fork of Fabric, designed to avoid the issues Fabric has, such as the poor community management and the endless bikeshedding. More info: https://quiltmc.org/faq/
- Quilt is planned to be fully backwards compatible with Fabric, at least for a while.
- porting from Fabric to Quilt should be extremely easy, it should really work right out of the box. Ideally we won't need *anything* done for it to work.
- Quilt plans to have a better API than FAPI, which we may take advantage of.
- Quilt is most likely not coming out until ~1.18 I believe, and there's a chance that we will as well.

If it was up to me, I'd be sticking with Fabric until Quilt is actually available for use, and swap over quickly once given the option. However, the rest of the team have equal say in the matter.

**Comment by LemmaEOF** [comment]
I'm in favor of Quilt if/when it comes out

**Comment by AeiouEnigma** [comment]
Locked because there's not really any way to have constructive discussion about Quilt until it's actually released.

**Comment by TropheusJ** [comment]
there's not really a point in keeping this open currently so
