### ISSUE TITLE
Mechanical Crafters do not merge on server

### ISSUE THREAD

**Issue by RedWideWeb** [Fabricators-of-Create/Create#120]
### Describe the Bug

When you click with the wrench on the back of a mechanical crafter - they merge containers.

On server when you click nothing happens

### Reproduction Steps

1. Launch Create server
2. Place two ore more mechanical crafters next to each other
3. Click with the wrench on the edge between two crafters
...

### Expected Result

Mechanical crafters merge their containers

### Operating System

Windows 10 1809

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

Fabric API 0.46.1

**Comment by AlphaMode** [comment]
Does anything get printed in console like a error?

**Comment by RedWideWeb** [comment]
> Does anything get printed in console like a error?

No. Neither error in server console, nor in client console
