### ISSUE TITLE
5.1.0c still crashes rendering.

### ISSUE THREAD

**Issue by ArtOfCombat** [Fabricators-of-Create/Create#1202]
### Describe the Bug

When running Fabric Create 1.19.2, any version, including the most recent, has an overlay render crash.

### Reproduction Steps

1. Install latest Create 1.19.2
2. Run modpack
3. Crash
...

### Expected Result

It should run - the error was supposed to be fixed.

### Crash Report or Log

https://pastebin.com/034ysW2E

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

Chipped
terrariumearth
chipped-fabric-1.19.2-2.1.5.jar
Chisel Reborn
Slaincow
chisel-1.4.7+1.19.2.jar
ClickThrough
Giselbaer
clickthrough-1.19.1-fabric0.58.5-0.4.jar
Cloth API (Fabric)
shedaniel
cloth-api-4.0.65.jar
Cloth Config API (Fabric/Forge)
shedaniel
cloth-config-8.3.103-fabric.jar
Clumps
Jaredlll08
Clumps-fabric-1.19.2-9.0.0+14.jar
Connectible Chains [Fabric]
legoatoom
connectiblechains-2.1.4+1.19.2.jar
Connectivity[Forge/Fabric]
someaddon
connectivity-fabric-1.19.2-4.5.jar
Controlling
Jaredlll08
Controlling-fabric-1.19.2-10.0+7.jar
Cooking for Blockheads (Fabric Edition)
BlayTheNinth
cookingforblockheads-fabric-1.19.2-13.3.3.jar
CorgiLib
Corgi_Taco
CorgiLib-fabric-1.19.2-1.0.0.34.jar
Cosmetic Armor [FABRIC]
Apace
CosmeticArmor-1.19-1.4.2.jar
Fabric Language Kotlin
modmuss50
fabric-language-kotlin-1.10.15+kotlin.1.9.21.jar
Farmer's Delight [Fabric]
NewHoryzon
farmers-delight-fabric-mc1.19-1.19.2-1.3.10.1.jar
Resourceful Lib
ThatGravyBoat
resourcefullib-fabric-1.19.2-1.1.24.jarTrinkets (Fabric)
EmilyPloszaj
trinkets-3.4.2.jar

**Comment by drwoops** [comment]
have you tried downgrading fabric api to 0.76.1?

**Comment by ArtOfCombat** [comment]
I have not, and I will, but I have a lot of mods relying on it, so it may break more.

**Comment by drwoops** [comment]
try it or you'll never know

**Comment by WaffleDevs** [comment]
No mods should rely directly on 0.77.x yet on 1.19.2. It was released only a handful of days ago, downgrading will work fine.
