### ISSUE TITLE
Game doesn't launch on Linux

### ISSUE THREAD

**Issue by xWires** [Fabricators-of-Create/Create#1205]
### Describe the Bug

When trying to launch Minecraft 1.18.2 with only Fabric API and Create Fabric, the game will not start.

### Reproduction Steps

1. Launch the game with Fabric API and Create Fabric

### Expected Result

The game should open.

### Crash Report or Log

https://pastebin.com/m6bDudPu

### Operating System

Arch Linux

### Mod Version

0.5.1c

### Minecraft Version

1.18.2

### Other Mods

Fabric API

**Comment by denys-duchier** [comment]
Try downgrading fabric api to 0.76.1

**Comment by xWires** [comment]
> Try downgrading fabric api to 0.76.1

I couldn't find 0.76.1, so i tried 0.76.0 and it works now, thank you.
