### ISSUE TITLE
Game crash on Start-up

### ISSUE THREAD

**Issue by Brightmoon-prime** [Fabricators-of-Create/Create#1207]
### Describe the Bug

Was trying to make a fabric modpack based around create. I was unable to launch it, so i removed mods until it was just the essentials. when i removed create it suddenly worked, so i made a new profile and added create. this is the result.

### Reproduction Steps

1. Download mod
2. Run mod
3. Crash
...

### Expected Result

Not crashing

### Crash Report or Log

https://gist.github.com/Brightmoon-prime/2ce44b17552682395cab8e188e5441cd

### Operating System

Windows 11

### Mod Version

0.5.1c

### Minecraft Version

1.18.2

### Other Mods

None, i was using a blank profile

### Additional Context

The error message:
The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$13" is null

**Comment by drwoops** [comment]
please downgrade fabric api to 0.76

**Comment by Brightmoon-prime** [comment]
ffs
Thank you

**Comment by FrostBird347** [comment]
This issue also occurs on 1.19.2.
Also, downgrading fabric api is not a long term solution as other mods are already becoming incompatible with version 0.76.

**Comment by Poopooracoocoo** [comment]
Most likely due to the changes in https://github.com/FabricMC/fabric/pull/3413 which landed in FAPI 0.77.0 for 1.19.2 and 1.18.2.

**Comment by Poopooracoocoo** [comment]
I think we can follow https://github.com/Fabricators-of-Create/Porting-Lib/issues/68

Edit: It was fixed on 1.19.2! Now we can download https://modrinth.com/mod/porting_lib/versions until Create updates :)
