### ISSUE TITLE
REI fluid recipe/usage lookup is broken

### ISSUE THREAD

**Issue by AeiouEnigma** [Fabricators-of-Create/Create#121]
Pressing 'R' while hovering over a fluid to view the recipe(s) for that fluid does not bring up any automated brewing recipe displays or draining recipe displays if the fluid is a potion. For non-potion fluids, attempting to view the recipe(s) for the fluid in this manner only displays how to craft the item *associated* with that fluid, instead of the recipe(s) for the fluid itself.

For example: pressing 'R' to see recipes for the water fluid will bring up spout filling recipes for water bucket and water bottle, when it should instead show the draining recipes for these items.

Similarly, pressing 'U' to see usages for a fluid will instead show usages for the items associated with that fluid. Looking up uses for the water fluid will instead show all uses for water buckets and water bottles.

**Comment by JieningYu** [comment]
is this a bug of rei itself?

**Comment by AlphaMode** [comment]
Pretty sure it works fine the keys are just swapped

**Comment by AlphaMode** [comment]
But yeah its a rei issue

**Comment by AeiouEnigma** [comment]
> Pretty sure it works fine the keys are just swapped

This is incorrect. Neither key shows uses of or recipes for the fluids. They instead show recipes for and uses of the *items* associated with the fluids, such as fluid buckets.

**Comment by AlphaMode** [comment]
Going to close this for now I've talked to shed about this since recipe lookup is handled by rei itself
