### ISSUE TITLE
crashing fabric 1.18.2

### ISSUE THREAD

**Issue by Teii228** [Fabricators-of-Create/Create#1210]
### Describe the Bug

I'm launching regular create-fabric-0.5.1-c-build.1159+mc1.18.2.jar and its crashing with error code -1.
"The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$13" is null"

### Reproduction Steps

1. .
2. .
3. .
...

### Expected Result

I still dont know how to fix it.

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.18.2

### Other Mods

create fabric
fabric api 0.77.0

**Comment by drwoops** [comment]
attach the crash report

**Comment by FrostBird347** [comment]
Possible duplicate of issue #1207, try downgrading fabric api to 0.76.
