### ISSUE TITLE
Threshold switch does not keep its signal when the game starts

### ISSUE THREAD

**Issue by rphsantos** [Fabricators-of-Create/Create#1213]
### Describe the Bug

Everytime I reopen my world (single player), all of my threshold switches seem to lose the last value read from the container they're attached to and send the wrong signal, for an instant.

### Reproduction Steps

1. Fill any container with items and use a threshold switch (in this example, I've also used one with the signal inverted)
![image](https://github.com/Fabricators-of-Create/Create/assets/50744896/3e52bff5-3974-4825-8c2e-84687961eef9)

2.Use the signal to control a funnel attached to another chest -  for instance:
![image](https://github.com/Fabricators-of-Create/Create/assets/50744896/f2095fca-8302-4552-b83f-ae6dfb705231)

3.Quit the game, open it again and see that one batch (depends on the funnel config) has been released:
![image](https://github.com/Fabricators-of-Create/Create/assets/50744896/ffbc214b-4030-4faa-b60f-a2f0161718ee)

My workaround for this is to use a pulse extender configured for 10 ticks, between the switch and the link.

### Expected Result

Threshold switches should maintain its signal when the world is restarted.

### Operating System

Fedora 38

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

./durabilitytooltip-1.1.5-fabric-mc1.20.jar
./lambdynamiclights-2.3.2+1.20.1.jar
./freecam-fabric-modrinth-1.2.1+1.20.jar
./lithium-fabric-mc1.20.1-0.11.2.jar
./minihud-fabric-1.20.1-0.27.0.jar
./BetterF3-7.0.1-Fabric-1.20.1.jar
./sodium-fabric-mc1.20-0.4.10+build.27.jar
./supermartijn642configlib-1.1.8a-fabric-mc1.20.jar
./modmenu-7.2.2.jar
./continuity-3.0.0-beta.4+1.20.1.jar
./Jade-1.20-fabric-11.6.2.jar
./create-fabric-0.5.1-d-build.1161+mc1.20.1.jar
./tweakeroo-fabric-1.20.1-0.17.1.jar
./malilib-fabric-1.20.1-0.16.3.jar
./fabric-api-0.88.1+1.20.1.jar
./cloth-config-11.1.106-fabric.jar
./reeses_sodium_options-1.6.2+mc1.20.1-build.85.jar
./JadeAddons-1.20.1-fabric-5.2.2.jar
./indium-1.0.21+mc1.20.1.jar
./jei-1.20.1-fabric-15.2.0.27.jar
./litematica-fabric-1.20.1-0.15.3.jar

**Comment by TropheusJ** [comment]
can't reproduce, threshold switch code was changed so I believe it was fixed

**Comment by rphsantos** [comment]
Thanks for the resolution!

Just one quick question - is the new threshold switch code present on patch v0.5.1.f, or will it be released in the next version?

**Comment by IThundxr** [comment]
it'll be released as 0.5.1.j
