### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by Cardoril** [Fabricators-of-Create/Create#1215]
### Describe the Bug

on custom mod-pack i made the game wont finish opening it will almost load the login screen and crash to a rendering error

### Reproduction Steps

1.download fabric mods and modpack
2.run modpack from curseforge
3.game crash on actual attempt to load minecraft

### Expected Result

The game actually loading past the 'minecraft' loading screen

### Crash Report or Log

https://pastebin.com/rvpKvw4e

### Operating System

Windows 11

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

fabric api 0.76.1
adorabuild:structures
advanced backups
Applied energistics 2
aquatic torches
architectuary api
areas
arrp
axes are weapons
azurelib
balm
better rotten flesh
better spawner control
bigger better end cities
blasting raw metal blocks into blocks
bookshelf
bridging mod
cardinal components api
carpeted stairs and slabs
carry on
choicetheorem's overhauled village
chunk loaders
cloth api
cloth api config
clumps
collective
configured
cooking for blockheads
cooldown coordinator
corgilib
craftable bell
creatre big cannons
create ore excavation
create slice and dice
create bells and whistles
create elitiaaaa addon
create steam n rails
darkrtp
days in the middle ages
deep underground lava fix
deeper and darker
diagnal fences
double doors
dungeons and taverns
enchantment descriptions
enchantment lore
enchantment reveal
end portal recipe
ender dragon egg respawn
even more origins
exp ore
explorify dungeons and structures
extra origins
fabric language kotlin
fabric shield lib
fairy factions revived
fish tanks
forge config api
ftb chunks
ftb library
ftb teams
fusion
gardens of the dead
gecko lib
goblin traders
grindstone sharper tools
head in the clouds
higher world deeper ocean
hopo better mineshaft
HT's treechop
immersive portals
iron chests
jamlib
just enough breeding
just enough items
lava turns sand into glass
ldshadowlady's flower breeding
liquid burner
macaw's bridges
macaw's bridges oh the biomes you will go
macaw's doors
macaw's fences and walls
macaw's fences oh the biomes you'll go
macaw's furnature
macaw's furnature oh the biomes you will go
macaw's lights and lamps
macaw's paintings
macaw's paths and pavings
macaw's roofs
macaw's roofs oh the biomes youll go
macaw's trapdoors
macaw's windows
MCA reborn
mechanical dispensers
medieval deco
medieval origins
medieval origins revival
medieval weapons
midnight lib
mobz
monsters and girls
moonlight lib
multibets
mythic mobs
naturalist
neruina
nether wart blocks to nether warts
not enough crashes
oh the biomes youll go refabricated
omni hopper
ore growth
origins
OWO
patchouli
path under fence gates
pekhui
physics mod
portable mobs
puzzles lib
realistic cities
rechiseled
respawning shulkers
right click harvest
scarecrows territory
shetiphiancore
sky villages
slabs expanded
smelting touch
supermartijn642 config lib
supermartijn642 core lib
terrablender
terralith
the twighlight forest
towns and towers
travelers backpack
villagers drop emeralds on death
waystones
y is there autojump
yetanotherconfiglib
yung's api
yung's better end
yung's better jungle temples
yung's  better mineshafts
yung's better nether fortresses
yung's  better ocean monuments
zombie villagers from spawner

### Additional Context

i have tried removing and returning a few of the mods altready, and tried updating/downgrading different mods but could not get into game with all my crash reports pointing at create, i had a few crash reports that included more mods and one that was worse then this create error

**Comment by TropheusJ** [comment]
hephaestus is currently incompatible
