### ISSUE TITLE
Copper and Netherite Backtanks are unable to have mending applied to them

### ISSUE THREAD

**Issue by FlashOfAsh** [Fabricators-of-Create/Create#1217]
### Describe the Suggestion

Mending despite it normally not being able to be applied to either backtank doesn't have a situation that matches what the elytra does (it just stops working at 0 durability) and actually breaks at 0. Making mending applicable to backtanks would definitely help with this since you can probably lose it fairly easily. There is also proof of the durability being on the backtanks if needed.

### Screenshots and Videos

Durability Proof:
![image_2023-12-08_140743435](https://github.com/Fabricators-of-Create/Create/assets/124220545/23aebba1-6a7d-4650-8bb5-f1840b042b33)

### Additional Context

There is also a glitch that would technically become a feature if you change this, netherite backtanks can be enchanted with mending through a seconday method, as shown here:
![image_2023-12-08_141054680](https://github.com/Fabricators-of-Create/Create/assets/124220545/cda9a482-3b8b-47db-ad92-c0250c9f3429)

**Comment by IThundxr** [comment]
Suggestions should be made to the forge repo if it's not a fabric specific inconsistency.

**Comment by TropheusJ** [comment]
working properly on patch F 1.18, will test newer versions later

**Comment by IThundxr** [comment]
Able to apply mending just fine on 1.20.1 patch f, them taking durability is wrong behaviour as on forge they do not lose durability
