### ISSUE TITLE
Textures are not loading on blocks

### ISSUE THREAD

**Issue by HenryBGit** [Fabricators-of-Create/Create#1218]
### Describe the Bug

Some block textures are not loading properly. They are the water wheel, large water wheel, crushing wheel, empty blaze burner, full blaze burner, copper valve handle, mechanical roller and the flywheel

### Reproduction Steps

1. Start the game and create a world
2. Place the items down in the list above
3.If bug is working correctly they should have the purple and black texture
...

### Expected Result

The textures for the block should be displayed

### Screenshots and Videos

![2023-12-09_17 49 51](https://github.com/Fabricators-of-Create/Create/assets/79766960/7a3c34a1-2b3c-4103-89b4-07a36985b819)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Mods that I am using

Audio Player mod (V1.20.1 - 1.8.5)
CIT Resewn (V1.20.1 - 1.1.3)
Iris (V1.20.1 - 1.6.4)
Jade (V1.20.1 - 11.6.2)
JEI (V1.20.1 - 15.2.0.27)
Mod Menu (V1.20.1 - 7.2.2)
Sodium (V1.20.1 - 0.4.10)
Reese's Sodium Options (V 1.20.1 - 1.5.1)
Sodium Extras (V1.20.1 - 0.4.20)
Worldedit (V1.20,1 - 7.2.15)
Xaero's Minimap (V1.20.1 - 23.9.1)
Xaero's Worldmap (V1.20.1 -1.37.1)

**Comment by drwoops** [comment]
you need indium 1.0.21
