### ISSUE TITLE
Sideways Fluid Tanks, vertical Item Vaults, configurable Vault length and the Storage Coupling

### ISSUE THREAD

**Issue by Truemudkip** [Fabricators-of-Create/Create#1221]
### Describe the Suggestion

1. Sideways Fluid Tanks and Vertical Item Vaults: change that makes Vaults able to go up and Tanks go sideways. I think this can be implemented by copying over the code that handles the multiblock placement for Tanks to Vaults and vice versa
2.  Configurable Vault length: I think everyone wants this, and given that you're already using repeating textures for the 2x2 and 3x3 midsections, this can probably be easily added (for 1x1 i'd use the middle texture as well).
3. Storage Coupling: Block, more like a pad, that lets storage blocks (most likely handled through a tag, i don't really know coding) attach to unassembled contraption like with glue, and be taken somewhere else so that on dissasembly they can easily be retrieved

**Comment by spectrapulse** [comment]
I think this issue is supposed to be submitted upstream. This is just a fork of upstream which makes Create work with Fabric.

https://github.com/creators-of-create/create
