### ISSUE TITLE
Having Create in mods folder crash game

### ISSUE THREAD

**Issue by vinhor** [Fabricators-of-Create/Create#1222]
### Describe the Bug

When I put Create in mods folder, and start game, MC will open, show loading screen for aprox. 2 minutes and crash.

### Reproduction Steps

1. Put Create in mod folder
2. Launch game
3. Wait

### Expected Result

MC won't crash and I can play.

### Crash Report or Log

https://mclo.gs/5ukNYQh

### Operating System

Windows 11 

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

sodium 0.4.4+build.18
lithium 0.11.1
indium 1.0.9+mc1.19.2
fabric-api 0.77.0+1.19.2

### Additional Context

Using Modrinth app

**Comment by drwoops** [comment]
downgrade fabric api to 0.76
