### ISSUE TITLE
Funnel/Chute first inventory slot selected

### ISSUE THREAD

**Issue by Daniel99j2** [Fabricators-of-Create/Create#1223]
### Describe the Bug

Chute/Funnels sending items into containers don't go to existing stacks, which is annoying and is inconsistent with forge, who have items going to existing stacks
![incorrect](https://github.com/Fabricators-of-Create/Create/assets/121533735/7c7a74e7-1a39-4f99-bd7d-df0581a17662)
![correct](https://github.com/Fabricators-of-Create/Create/assets/121533735/acaabcc0-4807-4549-be4a-64ac7a1e60fe)

### Reproduction Steps

Create a chest
Place items like image 1
Place a funnel in image 2
Throw a dirt into the funnel
<img width="418" alt="image" src="https://github.com/Fabricators-of-Create/Create/assets/121533735/34d8dd82-c6ad-4740-8521-ee1da5f6e04f">
<img width="1248" alt="image" src="https://github.com/Fabricators-of-Create/Create/assets/121533735/35733507-ee7a-43d8-824b-077ae5149da0">

### Expected Result

Items should go into existing stacks

### Crash Report or Log

N/A

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.19.2

### Other Mods

Many, N/A

**Comment by TropheusJ** [comment]
It matches the behavior of hoppers. I think it makes more sense to call the forge behavior a bug.
