### ISSUE TITLE
why does it look like this

### ISSUE THREAD

**Issue by V01DW3B** [Fabricators-of-Create/Create#1225]
### Describe the Bug

![2023-12-17_02 07 02](https://github.com/Fabricators-of-Create/Create/assets/68392877/94ee687d-bee6-4803-9419-2bf3bf6af36f)

### Reproduction Steps

place it

### Expected Result

normal cog

### Operating System

windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/68392877/ca42d94b-a1a2-42a3-9f2c-2d705f16749e)

**Comment by meatcereal** [comment]
Install Indium.

**Comment by V01DW3B** [comment]
when i install indium and use copper on a wood it crashes

**Comment by drwoops** [comment]
attach the crash report

**Comment by V01DW3B** [comment]
it dosent apear

**Comment by V01DW3B** [comment]
i play on a server with freands

**Comment by drwoops** [comment]
without a crash report, we can't do anything for you.  sorry, you'll just have to find it or close this issue

**Comment by V01DW3B** [comment]
is this good. its log that i got after the crash
[tl-logger4870432541432499458.txt](https://github.com/Fabricators-of-Create/Create/files/13696303/tl-logger4870432541432499458.txt)

**Comment by drwoops** [comment]
downgrade fabric api to 0.88.1

**Comment by V01DW3B** [comment]
THANKS SO MUSH
I LOVE YOU HABIBI

**Comment by AnnoyedUser420** [comment]
> is this good. its log that i got after the crash [tl-logger4870432541432499458.txt](https://github.com/Fabricators-of-Create/Create/files/13696303/tl-logger4870432541432499458.txt)

Yo dude, what does tl stand for
