### ISSUE TITLE
I can't launch Create Fabric

### ISSUE THREAD

**Issue by Sharp-Matter** [Fabricators-of-Create/Create#1226]
### Describe the Bug

When I launch Create Fabric on its own it won't launch or play.
![Screenshot 2023-12-16 225832](https://github.com/Fabricators-of-Create/Create/assets/154037310/ea1a07a2-4817-426f-8bfa-1023be60bd6f)

### Reproduction Steps

1. Download the Create Ultimate Modpack in Modrinth.

### Expected Result

I thought the game would launch like normally

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.19.2

### Other Mods

![Screenshot 2023-12-16 225902](https://github.com/Fabricators-of-Create/Create/assets/154037310/65ab569e-8fea-4142-87b7-c4f13a5b483a)

**Comment by drwoops** [comment]
downgrade fabric api to 0.76 and install indium
