### ISSUE TITLE
[Iris] Shaders break Ponder scenes

### ISSUE THREAD

**Issue by AeiouEnigma** [Fabricators-of-Create/Create#123]
![image](https://user-images.githubusercontent.com/3160746/151903008-2fba0a05-58d2-4dae-9e28-3a60af070500.png)

**Comment by PepperCode1** [comment]
This has been fixed by a recent Iris commit, but one extra thing to do is to fix ponder scene diffuse lighting while shaders are enabled.

**Comment by PepperCode1** [comment]
Ponder diffuse is also fixed now, so I will close this.
