### ISSUE TITLE
Option To Remove Configuration Menu Entirely

### ISSUE THREAD

**Issue by ADeletedUser** [Fabricators-of-Create/Create#1231]
### Describe the Suggestion

An area in the configs, or even just a guide on which files to deleted or something to remove the create configuration menu would be great! 

### Screenshots and Videos

![Screenshot 2023-12-20 195509](https://github.com/Fabricators-of-Create/Create/assets/154487873/06da0fe8-d2bf-4fcc-a05a-68ac1397

Uploading Vivecraft 1.19.2 jrbudda-NONVR-fabric-0.0.15_ 1.19.2 2023-12-20 20-01-42.mp4…

5cc0)

### Additional Context

It seems that Create doesn't work well with more fragile things like questcraft (vr minecraft) due to it's sepperate, fancy configuration menu. Because this menu is animated in different ways and is additional to the main menu, stuff like questcraft can't run create purely because it can't start the game. Whenever the game loads, It gets stuck on an infinitely looping loading screen while it's trying to load the hidden configuration menu. The ability to remove the button to get to the config menu was nice (which also fixed a seperate issue), but the config menu still has issues when rendering. I have provided a video of the loading loop and the mods that are used.

**Comment by TropheusJ** [comment]
that's not how that works. If you don't open the menu it essentially doesn't exist. Can't fix anything without logs, but it's probably a problem with running on the quest that won't be fixed.
