### ISSUE TITLE
the create mod isnt loading with fabric

### ISSUE THREAD

**Issue by azkacreate** [Fabricators-of-Create/Create#1232]
### Describe the Bug

the mod doesn`t appear in minecraft fabric :(

### Reproduction Steps

1. putting the mod up
2. starting minecraft
3.mod not appearing
...

### Expected Result

i expect a create mod menu on the creative inventory

### Operating System

windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
You probably didn't install it right, but I can't do anything with 0 information. Launcher? logs? mod folder?

**Comment by drwoops** [comment]
- did you install fabric?
- did you put the create jar in the `mods` folder
