### ISSUE TITLE
Really simple env causes on-launch crash

### ISSUE THREAD

**Issue by AoSankaku** [Fabricators-of-Create/Create#1233]
### Describe the Bug

With only the latest Fabric API and Create causes crash below.

[crash-2023-12-21_18.12.45-client.txt](https://github.com/Fabricators-of-Create/Create/files/13740111/crash-2023-12-21_18.12.45-client.txt)

### Reproduction Steps

1. Install Fabric API 0.14.21 (or 0.14.22 or 0.14.23 or 0.15.3) and Create 0.5.1-c build.1160+mc1.19.2
2. Launch Minecraft
3. The loading gauge goes back suddenly at 95%
4. Crashes!

### Expected Result

Launches normally

### Operating System

Windows 11

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

Nothing else AT ALL!

### Additional Context

Using PrismLauncher

**Comment by AoSankaku** [comment]
Removing the DISABLED mods also throws this crash report:

[crash-2023-12-21_19.01.57-client.txt](https://github.com/Fabricators-of-Create/Create/files/13740123/crash-2023-12-21_19.01.57-client.txt)

**Comment by drwoops** [comment]
downgrade fabric api to 0.76, and next time ATTACH the crash report (don't paste it in - that's unreadable)

**Comment by AoSankaku** [comment]
Thanks for quick reply, I edited the issue and the comment above.

And your advice solved the issue, thank you!

----

# An additional question

But I'm really curious about this issue, as my by far more complex modded environment I can literally launch mc normally. The below is the structure:

- Fabric Loader 0.15.1
- 1.19.2 Fabric
- Using create 0.15.1-c-build.1160+mc1.19.2
- **Using Fabric API 0.77.0+1.19.2**
- Other 170 mods are installed
- Launches completely normally **without any crash**

Here is the entire mod list:

AmbientSounds_FABRIC_v5.2.13_mc1.19.2.jar
BetterF3-4.0.1-Fabric-1.19.2.jar
Bookshelf-Fabric-1.19.2-16.3.20.jar
Bookshelf-Forge-1.19.2-16.3.20.jar
Clumps-fabric-1.19.2-9.0.0+14.jar
Coins-Fabric-1.19.2-10.1.7.jar
Controlling-fabric-1.19.2-10.0+7.jar
CorgiLib-fabric-1.19.2-1.0.0.34.jar
CraftTweaker-fabric-1.19.2-10.1.50.jar
CreativeCore_FABRIC_v2.9.4_mc1.19.2.jar
CustomWindowTitle-Fabric-1.19+v1.1.1.jar
DarkUtilities-Fabric-1.19.2-13.1.7.jar
Debugify-2.8.0.jar
DisableCustomWorldsAdvice-3.0.jar
DripSounds-1.19-0.3.0.jar
DungeonsArise-1.19.2-2.1.55-fabric-beta.jar
EasyAnvils-v4.0.11-1.19.2-Fabric.jar
EasyHopper-fabric-mc1.19.2-2.5.2.jar
Emojiful-Fabric-1.19.2-4.0.4.jar
EnchantmentDescriptions-Fabric-1.19.2-13.0.14.jar
ExplorersCompass-1.19.2-2.2.0-fabric.jar
ExtendedDrawers-1.3.9+mc.1.19.2.jar
FABRIC-Croparia-4.0.1.jar
Fastload+1.18.2-1.20-3.4.0.jar
FauxCustomEntityData-fabric-1.19.2-2.0.2.jar
FlowerPatch-fabric-1.19.2-2.0.3.jar
ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar
IngredientExtensionAPI-fabric-1.19.2-3.0.6.jar
InventoryProfilesNext-fabric-1.19-1.10.5.jar.disabled
InventoryProfilesNext-fabric-1.19-1.10.9.jar
IronChests-1.7.7.jar
ItemPhysic_FABRIC_v1.6.6_mc1.19.2.jar
JustEnoughResources-Fabric-1.19.2-1.2.1.189.jar.disabled
MTR-LU-Addon-fabric-1.19.2-3.2.0-1.11.jar
MTR-MSD-Addon-fabric-1.19.2-3.2.0-1.3.3.jar
MTR-NTE-0.4.1+1.19.2.jar
MTR-fabric-1.19.2-3.2.2-hotfix-1.jar
MTR-fabric-1.19.2-3.2.2.jar
MouseTweaks-fabric-mc1.19-2.22.jar
NaturesCompass-1.19.2-2.1.0-fabric.jar
"Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.6.jar"
Patchouli-1.19.2-77-FABRIC.jar
PigPen-Forge-1.19.2-11.1.2.jar
PuzzlesLib-v4.4.3-1.19.2-Fabric.jar
REIPluginCompatibilities-forge-9.0.48.jar
RoughlyEnoughItems-9.1.682-fabric.jar
RoughlyEnoughLootTables-1.19-1.0.jar
RoughlyEnoughProfessions-fabric-1.19.2-1.1.4.jar
RoughlyEnoughTrades-1.19-1.0.jar
Runelic-Forge-1.19.2-14.1.4.jar
SimpleCopperPipes-1.13.3-1.19.jar
SkyVillages-1.0.2.1-1.19.x-fabric.jar
Slideshow-fabric-1.19.2-1.0.2-hotfix-1.jar
Steam_Rails-1.5.1+fabric-mc1.19.2.jar
TerraBlender-fabric-1.19.2-2.0.1.166.jar
TravelersTitles-1.19.2-Fabric-3.1.0.jar
WorldEditCUI-1.19.2+01.jar
YetAnotherConfigLib-1.7.1.jar
YungsApi-1.19.2-Fabric-3.8.10.jar
YungsBetterDesertTemples-1.19.2-Fabric-2.2.2.jar
YungsBetterDungeons-1.19.2-Fabric-3.2.1.jar
YungsBetterEndIsland-1.19.2-Fabric-1.0.jar
YungsBetterJungleTemples-1.19.2-Fabric-1.0.1.jar
YungsBetterMineshafts-1.19.2-Fabric-3.2.1.jar
YungsBetterNetherFortresses-1.19.2-Fabric-1.0.6.jar
YungsBetterOceanMonuments-1.19.2-Fabric-2.1.1.jar
YungsBetterStrongholds-1.19.2-Fabric-3.2.0.jar
YungsBetterWitchHuts-1.19.2-Fabric-2.1.0.jar
YungsBridges-1.19.2-Fabric-3.1.0.jar
YungsExtras-1.19.2-Fabric-3.1.0.jar
accurate-block-placement-1.2.1.jar
advancementframes-1.19.2-2.0.0-fabric.jar
angelblockrenewed-fabric-1.3-1.19.jar
antighost-1.19.1-fabric0.58.5-1.1.5.jar
appleskin-fabric-mc1.19.2-2.5.1.jar
archers_arsenal-1.0.2v192.jar
architectury-6.5.85-fabric.jar
arrp-0.6.4.jar
'auto-workstations-[MC1.19]-v1.0-SNAPSHOT-19.jar'
autotorch-mc1.19-1.2.2+build.3.jar
badpackets-fabric-0.2.3.jar
balm-fabric-1.19.2-4.6.0.jar
bclib-2.1.7.jar
better-end-2.1.6.jar
better-nether-7.1.4.jar
betterlily.jar
bettervillage-fabric-1.19.2-3.1.0.jar
blur-2.6.0.jar
cardinal-components-api-5.0.2.jar
carryon-fabric-1.19.2-2.1.1.22.jar
cloth-config-8.3.103-fabric.jar
collective-1.19.2-7.23.jar
continuity-2.0.2+1.19.jar
copperhopper-0.0.12+1.19.2.jar
craftingtweaks-fabric-1.19.2-15.1.9.jar
create-fabric-0.5.1-c-build.1160+mc1.19.2.jar
create_jetpack-fabric-3.4.0.jar
createaddition-fabric+1.19.2-20230723a.jar
'creategoggles-1.19.2-0.5.5.e-[FABRIC].jar'
ctov-3.2.6c.jar
deeperdarker-fabric-1.19.2-1.2.5.jar
dummmmmmy-1.19.2-1.7.2-fabric.jar
dungeons-and-taverns-2.0.2.jar
durabilityviewer-1.19.1-fabric0.58.5-1.10.3.jar
dynamicvilladertrading-1.0.3-1.19.2.jar.disabled
entityculling-fabric-1.6.1-mc1.19.2.jar
exlinecopperequipment-fabric-1.19.2-v2.1.2.jar
exordium-fabric-1.0.1-mc1.19.2.jar.disabled
exordium-fabric-1.0.2-mc1.19.2-hotfix.jar.disabled
explorify-fabric-1.19-1.3.0.jar
extended-copper-1.4.2-1.19.jar
extractinator-fabric-1.19.2-2.0.1.jar
extrasounds-2.3.1+1.19.2-1.19.1.jar
fabric-api-0.77.0+1.19.2.jar
fabric-furnaces-2.2.0-1.19.2.jar
fabric-language-kotlin-1.10.16+kotlin.1.9.21.jar
farmers-delight-fabric-1.19.2-1.3.10.jar.disabled
farmers-delight-fabric-1.3.10.2.jar
farmersknives-2.4.1.jar
fastquit-2.1.0+1.19-1.19.2.jar
ferritecore-5.0.3-fabric.jar
figura-0.1.2+1.19.2.jar
findme-3.1.0-fabric.jar
ftb-library-fabric-1902.4.1-build.236.jar
ftb-ultimine-fabric-1902.4.1-build.90.jar
ftbbackups2-fabric-1.19.2-1.0.23.jar
geckolib-fabric-1.19-3.1.40.jar
gravestones-v1.13.jar
guard-villagers-fabric-1.19.2-1.1.2.jar
harvestwithease-1.19.2-8.0.0.2-fabric.jar
health-levels-1.0.3.1.jar.disabled
health-levels-1.0.3.jar.disabled
hole_filler_mod-1.2.4.1_mc-1.19.2_fabric.jar
hookshot-26.0.jar
indium-1.0.9+mc1.19.2.jar
instantblocks-fabric-1.19.2-1.6.5.jar
iris-mc1.19.2-1.6.11.jar
journeymap-1.19.2-5.9.7-fabric.jar
keybind_fix-1.0.0.jar
kleeslabs-fabric-1.19.2-12.3.0.jar
konkrete_fabric_1.6.1_MC_1.19.1-1.19.2.jar
kubejs-fabric-1902.6.2-build.45.jar
lanterns-belong-on-walls-1.4.0-1.19.jar
lazydfu-0.1.3.jar
libIPN-fabric-1.19-3.0.2.jar.disabled
libIPN-fabric-1.19-4.0.1.jar
libraryferret-fabric-1.19.2-4.0.0.jar
light-overlay-7.0.0.jar
litematica-fabric-1.19.2-0.12.7.jar
lithium-fabric-mc1.19.2-0.11.1.jar
malilib-fabric-1.19.2-0.13.0.jar
mcda-2.4.4.jar
mcdw-5.0.13-1.19.jar
memoryleakfix-fabric-1.17+-1.1.2.jar
minecraft-comes-alive-7.5.11+1.19.2-universal.jar
minekea-fabric-1.19.1-4.0.2.jar
minerally-1.19.2-1.0.jar
'modelfix-1.8-fabric (1).jar'
modernfix-fabric-5.10.1+mc1.19.2.jar
modernworldcreation_fabric_1.0.0_MC_1.19-1.19.2.jar
modmenu-4.2.0-beta.2.jar
moonlight-1.19.2-2.2.43-fabric.jar.disabled
moonlight-1.19.2-2.3.5-fabric.jar
notenoughanimations-fabric-1.6.4-mc1.19.2.jar
numismatic-overhaul-0.2.10+1.19.jar
owo-lib-0.9.3+1.19.jar
panorama
panorama-1.2.0.jar
plushie-mod-1.2.jar
polylib-fabric-1900.0.3-build.100.jar
prefab-fabric-4.2.4.jar
reeses_sodium_options-1.6.4+mc1.19.2-build.93.jar
resourcefulconfig-fabric-1.19.2-1.0.20.jar
resourcefullib-fabric-1.19.2-1.1.24.jar
respawnablepets-1.19-2.jar
rhino-fabric-1902.2.3-build.284.jar
seamless-loading-screen-2.0.3+1.19.2-fabric.jar
sliceanddice-fabric-2.3.2.jar
smoothboot-fabric-1.19-1.7.1.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
soundphysics-fabric-1.19.2-1.3.0.jar
squaremap-fabric-mc1.19.2-1.1.8.jar
starlight-1.1.1+fabric.ae22326.jar
supplementaries-1.19.2-2.4.14-fabric.jar
suppsquared-1.19.2-1.1.2-fabric.jar
takesapillage-1.19-1.0.4.jar
taterzens-1.11.1-fabric.jar
toolleveling-fabric-1.19.2-1.4.1.jar
tooltipfix-1.1.1-1.19.jar
torohealth-1.19-fabric-1.jar
trade-cycling-fabric-1.19.2-1.0.8.jar
tradernpcs-1.2.0-fabric.jar
tradeuses-1.2.1-1.19.2-FABRIC.jar
travelers-backpack-1.19.2-8.2.24.jar
umu_little_maid-2.10.jar
unofficial-sodium-biome-blending-fix-1.0.1.jar
villagernames-1.19.2-7.2.jar
worldedit-mod-7.2.12.jar
wthit-fabric-5.19.3.jar

**Comment by drwoops** [comment]
whether mc launches is often non-deterministic.  my semi-educated guess is that it depends on the order in which mixins are applied.  however, if there are orders that cause the launch to fail, you can expect runtime failures for orders that succeed.

since your issue has been resolved, please consider closing this issue.

**Comment by AoSankaku** [comment]
I see. Thanks for sharing your knowledge to me.

And thank you again for your quick response!
