### ISSUE TITLE
cant move two crashed trains

### ISSUE THREAD

**Issue by NobleSkye** [Fabricators-of-Create/Create#1236]
### Describe the Bug

two trains crahed together and now i cant move them

### Reproduction Steps

1.create 2 trains
2. have one assibemabled and the other inside that train
3. try to move the trains 
...

### Expected Result

being able to move the train

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/118846397/f6b0dd64-6781-469a-b811-9760daff9570)
![image](https://github.com/Fabricators-of-Create/Create/assets/118846397/381c9faf-99ee-43bf-9eca-74dde70922ef)
![image](https://github.com/Fabricators-of-Create/Create/assets/118846397/f8f14bc4-2f99-49f7-997d-b165a5ef8f9c)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by creeper6530** [comment]
You can't drive derailed trains, and crash derails them. You need to relocate back on track in order to drive

**Comment by NobleSkye** [comment]
Yes. I'm aware. I can't relocate it. It's just stuck.

**Comment by IThundxr** [comment]
Please send a log

**Comment by IThundxr** [comment]
Closing due to no response - most likely a issue with some addon
