### ISSUE TITLE
Mechanical Saw does not strip Cherry Wood.

### ISSUE THREAD

**Issue by water-mizuu** [Fabricators-of-Create/Create#1237]
### Describe the Bug

As stated from above, mechanical saw does not strip cherry wood.

### Reproduction Steps

In my setup:
1. Create a setup with a mechanical saw, hopper on top of the saw as input, and hopper at the side of the saw as output.
2. Put cherry logs in the input hopper.

### Expected Result

Each cherry wood would be stripped by the saw.

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
this should be fixed with the latest upstream merge
