### ISSUE TITLE
Nostalgic Tweaks puts game into infinte mojang logo Loop

### ISSUE THREAD

**Issue by Vincent392** [Fabricators-of-Create/Create#1239]
### Describe the Bug

As the title says, the game gets put into an infinite mojang logo loop, only ways to close the game is task manager, the kill button, or the X button in the titlebar

### Reproduction Steps

1. Install Nostalgic Tweaks and Create in one instance
2. Open the game
3. watch
...

### Expected Result

The game to launch reach the title as normal in about 30 seconds to a minute.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/90470156/265c09a7-69b2-4012-ab05-8e6f9bbc32e0)
> ^ With Create

![image](https://github.com/Fabricators-of-Create/Create/assets/90470156/b5649117-4b88-4889-a3ae-ff56ef31ec41)
> ^ Without Create

### Crash Report or Log

[Log](https://gist.github.com/Vincent392/f3b62d5a1b04ba1bae416d90e901a8bc)

### Operating System

Windows 8.1 Pro

### Mod Version

0.5.1c

### Minecraft Version

1.18.2

### Other Mods

architectury, fabric-api, lazy-language-loader, lazydfu and sodium.

### Additional Context

The game does NOT crash, just gets stuck in a soft lock from what it seems.

The launcher I'm using is ATLauncher, but launchers shouldn't make a difference.

**Comment by TropheusJ** [comment]
need the log

**Comment by Vincent392** [comment]
hold on

**Comment by Vincent392** [comment]
https://pastebin.com/C2HGXPDN
The log

**Comment by TropheusJ** [comment]
> Error, this is a private paste or is pending moderation

use [gist](https://gist.github.com/) or [mclogs](https://mclo.gs/)

**Comment by Vincent392** [comment]
forgot gist existed for a second.
But as a Java developer who has messed with Minecraft's source code, something is messed up.

**Comment by Vincent392** [comment]
gist:
https://gist.github.com/Vincent392/f3b62d5a1b04ba1bae416d90e901a8bc

**Comment by TropheusJ** [comment]
downgrade fabric  API to 0.76. this will be fixed in the next Create update

**Comment by Vincent392** [comment]
Huh.
**Interesting.**
