### ISSUE TITLE
Gantry carriage crash + duplication bug

### ISSUE THREAD

**Issue by ergo3983** [Fabricators-of-Create/Create#1240]
### Describe the Bug

I made a gantry contraption: a row of harvesters that move along a length of farmland, with a chest attached to it. When it reaches the end of the gantry, a redstone contact activates a redstone link, flipping the switch and reversing direction with a gearshift.

As it went down the gantry, it harvested the wheat as normal and I collected seeds from the chest while in motion. Then, when it reached the end, it made contact with the redstone contact and the game instantly crashed. Upon reloading, all the blocks that made up the gantry were both intact and a copy was dropped on the ground, duplicating the harvesters, cantry carriage, chests, and structural blocks.

Further testing:
Taking an item out of a chest attached to a moving contraption causes it to crash the game and duplicate the blocks of the contraption when the game is reloaded.
The gantry carriage can stop because it reaches the end of the gantry, or because a redstone contact reverses the direction.

### Reproduction Steps

1. Create a gantry system with a chest. Put something in the chest.
2. Start the gantry moving.
3. Take them out of the chest while the contraption is moving.
4. When it reaches the end of the gantry, the game will crash.
5. Reload and there will be two copies of the gantry system overlaid on each other. When they reach the end of the gantry, one will break and give you a copy of all the gantry blocks.
 

### Expected Result

The game does not crash and the gantry stops as normal.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/154709218/7c0e0637-718a-49ff-b8e9-4c0182455237)

This screenshot shows a mechanism that has tested to duplicate the blocks when the carriage reaches the end of the gantry.

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Appleskin 2.5.1
Architectury 9.1.12
Borderless mining 1.1.8+
Continuity 3.0.0 beta 4+
Create addition 1.0.0b
Create structures 0.1.1
Create sodium fix 0.5.1-d
Fabric API 0.91.0+
indium 1.0.27+
Lamb Dynamic Lights 2.3.2+
Memoryleakfix Fabric 1.17+
RoughlyEnoughItems 12.0.684
Sodium 0.5.3
Starlight 1.1.2+
Xaeros Minimap 23.9.3

**Comment by kyleplo** [comment]
I have experienced this issue as well

**Comment by dashiellwascool** [comment]
I've been running into this on my server. I also recreated it in singleplayer using your instructions. [Here is my crash report.](https://github.com/Fabricators-of-Create/Create/files/13797247/crash-2023-12-29_22.04.58-server.txt) I found that you have to take an entire stack out. I took just a single item of a stack out and it didn't crash. I had only Create and Fabric API installed.

This might be related to [this issue on the Forge repo](https://github.com/Creators-of-Create/Create/issues/5682). They are using Fabric despite it being on over there.

**Comment by ergo3983** [comment]
Thanks for finding out that new info about needing to take a stack out!

**Comment by TropheusJ** [comment]
duplicate of #1080
