### ISSUE TITLE
Some item and cube textures are missing and cannot be rendered properly

### ISSUE THREAD

**Issue by EmptyDreams** [Fabricators-of-Create/Create#1242]
### Describe the Bug

As you can see in the image above, there are a lot of items and squares that don't get rendered properly.

I checked the other issues and it seems I have to install indium, but when I load the game archive after installing indium-1.0.21 it crashes straight away.

### Reproduction Steps

1. Install `create`, `sodium` and `indium`.
2. Start the game and load an archive

### Expected Result

The game should work (whether or not it fixes the `create` item and cube rendering errors).

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/44894906/7e5a6782-e74b-4479-8fbd-4f68eefaec5e)

### Crash Report or Log

https://paste.ubuntu.com/p/36D29v2jzq/

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

+ fabric-api-0.91.0
+ architectury-9.1.12
+ cloth-config-11.1.106
+ sodium-0.4.10
+ indium-1.0.21
+ lithium-0.11.2
+ ferritecore-6.0.1
+ exordium-1.2.1
+ entityculling-1.6.2
+ enhancedblockentities-0.9
+ enchlevel-langpatch-2.1.2
+ Debugify-2.0
+ appleskin-2.5.0
+ journeymap-5.9.12
+ imblockerfabric-1.0.24
+ jade-11.6.4
+ jei-15.2.0.27
+ lanserverproperties-1.11.1
+ create-0.5.1d

**Comment by drwoops** [comment]
install indium 1.0.21

**Comment by EmptyDreams** [comment]
> install indium 1.0.21

Yes I installed `indium 1.0.21`, but after I install it going into the archive game crashes.

**Comment by drwoops** [comment]
then attach the crash report

**Comment by EmptyDreams** [comment]
> then attach the crash report然后附上崩溃报告

I've posted the URL for the crash log above: https://paste.ubuntu.com/p/36D29v2jzq/

**Comment by drwoops** [comment]
downgrade fabric api to 0.88.1

**Comment by EmptyDreams** [comment]
> downgrade fabric api to 0.88.1将 Fabric API 降级到 0.88.1

The game no longer crashes after downgrading. But I was wondering if `Create Fabric` has any idea about compatibility with `Sodium 0.5+` and other new APIs? It's been a few months since `sodium 0.5+` was released, but there don't seem to be any commits in `commits`.

**Comment by drwoops** [comment]
it is being worked on. please consider closing this issue.
