### ISSUE TITLE
Item Filter can kick you from server if it's too "large"

### ISSUE THREAD

**Issue by CaptainSqrBeard** [Fabricators-of-Create/Create#1243]
### Describe the Bug

Opening a too large list filter could kick you from server.

And by "too large" I mean that it has many items with large amount data inside of them. Other item filters, books or contraptions on minecarts would go

### Reproduction Steps

1. Join a create server or single-player world
2. Make a list filter and add many items with large size of data (books or other filters) in it.
3. Confirm changes
4. Open the filter
5. Kicked from the server

### Expected Result

Normal behavior: See list filter's GUI and be able to configure it

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/56765288/6414b3a8-46bf-44cc-81f3-35c9312536c5)

### Crash Report or Log

Log after using the filter: https://pastebin.com/yRANZsu2 (The rest of look unessential)

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

- Create Jetpack 4.1.0
- Fabric Language Kotlin
- Fabric API 0.90.0

### Additional Context

I was making an auto-sorting machine when this occurred

**Comment by NolanHewitt** [comment]
Does the mod XXLpackets fix this? The error it fixes looks similar: https://modrinth.com/mod/xxl-packets

**Comment by TropheusJ** [comment]
You should be able to work around this with [XXL Packets](https://modrinth.com/mod/xxl-packets) or [Packet Fixer](https://modrinth.com/mod/packet-fixer).
This is kinda a fundamental issue that can't really be fixed without design changes.

**Comment by Bam49eng** [comment]
Try [Create: Big Contraptions](https://modrinth.com/mod/big-contraptions) it should work with out installing anything on the srever

**Comment by TropheusJ** [comment]
there's really nothing that can be done about this, it's a vanilla problem, filters just let you put a lot of data in an item. It's just bookbanning
