### ISSUE TITLE
Threading issues with Sound Physics Remastered crash flywheel

### ISSUE THREAD

**Issue by creeper6530** [Fabricators-of-Create/Create#1244]
### Describe the Bug

Sometimes Create just randomly crashes with no apprent reason. No matter whether machinery is near or not, driving train or not, moving or not.

It always throws `java.lang.ArrayIndexOutOfBoundsException` everytime.

### Reproduction Steps

None known so far

### Expected Result

No crash ¯\\\_(ツ)_/¯

### Crash Report or Log

https://gist.github.com/creeper6530/9eef3edbd0c425752a2cb39cae6167dc (4 most recent crashes)

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

- appleskin: AppleSkin 2.5.1+mc1.20
- badpackets: Bad Packets 0.4.3
- chat_heads: Chat Heads 0.10.22
- chunkloaders: Chunk Loaders 1.2.8
- cloth-config: Cloth Config v11 11.1.106
- create: Create 0.5.1-d-build.1161+mc1.20.1
- create-track-map: Create Track Map 1.4
- createaddition: Create Crafts & Additions 0.9.0
- createdieselgenerators: Create Diesel Generators 2.1.3
- dark-loading-screen: Dark Loading Screen 1.6.14
- dynamic_fps: Dynamic FPS 3.2.1
- entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
- fabric-api: Fabric API 0.90.0+1.20.1
- fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
- fabricloader: Fabric Loader 0.14.22
- ferritecore: FerriteCore 6.0.0
- fps: FPS Monitor 1.20-1.3.0-Fabric
- java: Java HotSpot(TM) 64-Bit Server VM 17
- jei: Just Enough Items 15.2.0.27
- lambdynlights: LambDynamicLights 2.3.2+1.20.1
- lazydfu: LazyDFU 0.1.3
- lithium: Lithium 0.11.2
- memoryleakfix: Memory Leak Fix 1.1.2
- minecraft: Minecraft 1.20.1
- modmenu: Mod Menu 7.2.2
- nochatreports: No Chat Reports 1.20.1-v2.2.2
- railways: Create: Steam 'n' Rails 1.5.1+fabric-mc1.20.1
- sound_physics_remastered: Sound Physics Remastered 1.20.1-1.2.1
- supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
- supermartijn642corelib: SuperMartijn642's Core Lib 1.1.15
- voicechat: Simple Voice Chat 1.20.1-2.4.27
- wildfire_gender: Wildfire's Female Gender Mod 1.20-3.0.1
- wthit: wthit 8.4.0
- xaerominimap: Xaero's Minimap 23.8.3
- xaeroworldmap: Xaero's World Map 1.35.0

### Additional Context

Modrinth App modpack: https://www.dropbox.com/scl/fi/3oaueulkit4c22upzvvy1/Create-Fabric-1.2.mrpack?rlkey=anw7qwriit88cmpzr2de8kugu&dl=0

**Comment by drwoops** [comment]
downgrade fabric api to 0.88.1.  this may impact other mods, but you will just have to deal with that because the version i gave you is the only one that will reliably work for create.

**Comment by IThundxr** [comment]
sound physics remastered issue

**Comment by TropheusJ** [comment]
This issue has to be fixed by Sound Physics Remastered, but it's not going to happen. https://github.com/henkelmax/sound-physics-remastered/issues/172
