### ISSUE TITLE
Cant even properly load a world without crash

### ISSUE THREAD

**Issue by Zejdow** [Fabricators-of-Create/Create#1245]
### Describe the Bug

I am using the 1.20.1 0.5.1d build of Create for Fabric and whenever I try to launch it, I open a world, which loads, but as soon as I press "e" to open Creative Inventory, game crashes. Only other mod is the Fabric API version 0.88.1 

### Reproduction Steps

Just launch a world, alternatively open the Create Menu in the Main menu, then wait like 5 second for a crash

### Expected Result

Game working properly

### Crash Report or Log

https://pastebin.com/mYmFvLhf

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
Try changing your game language to something else and then change it back

**Comment by Zejdow** [comment]
why did it work???
well but thank you for solving this, it was driving me crazy
