### ISSUE TITLE
Create causes an infinite loading problem, 1.18.2 fabric

### ISSUE THREAD

**Issue by nickdehkordi** [Fabricators-of-Create/Create#1248]
### Describe the Bug

I have a 202 mod modpack and I have narrowed it down to Create causing the issue. When turned off it works fine. The issue in question is that Minecraft will boot up to the red loading screen, the white bar would move to about 95%, and the game would open for a split second but then would reset to the red loading screen and repeats the process indefinitely. No crash.

### Reproduction Steps

1. Use my modpack
2. Open the game
3.
...

### Expected Result

I expect the game to open to the title screen, but it cycles indefinitely between the red loading screen and launching the game for a split second.

### Screenshots and Videos

https://medal.tv/games/minecraft/clips/1LvBsQdrhM8B5c/d1337GkGESYs?invite=cr-MSxkZEIsMzM4NDk4ODAs

### Crash Report or Log

No crash so there is no crash log. 

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.18.2

### Other Mods

[modlist.txt](https://github.com/Fabricators-of-Create/Create/files/13777108/modlist.txt)

**Comment by nickdehkordi** [comment]
Latestlog:https://gist.github.com/glorification12/3d39886fe08a5bb225cabc18d8d82ae2

**Comment by drwoops** [comment]
why are you playing create 0.4.1. its ancient and no longer supported

**Comment by nickdehkordi** [comment]
Attempted to roll back Create version to fix the issue and forgot to roll it to the newest when it didn't work. The bug stays true for the latest build.

**Comment by drwoops** [comment]
i am not looking at this again until you update and provide a new log

**Comment by nickdehkordi** [comment]
Updated create to its latest version. Here is the new latestlog: https://gist.github.com/glorification12/017f198113622ef82531704392add917

**Comment by drwoops** [comment]
downgrade fabric api to 0.76

**Comment by nickdehkordi** [comment]
This solved it. Thank you. 

Just a question, is there any particular line that gave away the solution? or was it more complicated than that?

trying to improve my troubleshooting skills.

**Comment by drwoops** [comment]
no. it's just knowledge of which versions work.
