### ISSUE TITLE
Crash on render

### ISSUE THREAD

**Issue by S1zus** [Fabricators-of-Create/Create#125]
### Describe the Bug

Crash on rendering Create's blocks with animations. Blocks like linear chassis renders fine.

### Reproduction Steps

1. Load into world
2. Place mechanical bearing or encased cogwheel (tested this, probably will crash on other blocks)
3. Get crash

### Expected Result

Expected to actually see this blocks

### Crash Report or Log

https://pastebin.com/kv63vdxU

### Operating System

Windows 10

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

  [✔️] adventurez-1.4.7
  [✔️] appleskin-fabric-mc1.18-2.2.0
  [✔️] appliedenergistics2-10.0.0-beta.5
  [✔️] architectury-3.4.9
  [✔️] bclib-1.2.4
  [✔️] betteranimalsplus-1.18.1-11.0.3-fabric
  [✔️] better-nether-6.0.8
  [✔️] cloth-config-6.1.48-fabric
  [✔️] Controlling-fabric-1.18.1-9.0.11
  [✔️] CraftTweaker-fabric-1.18.1-9.0.0+24
  [✔️] create-mc1.18.1_v0.4c
  [✔️] create-mc1.18.1_v0.4c-sources
  [✔️] dynview.fabric-1.18-1.5
  [✔️] EnchantmentDescriptions-Forge-1.18.1-9.0.9
  [✔️] fabric-api-0.46.1+1.18
  [✔️] fallingleaves-1.9.0+1.18.1
  [✔️] FallingTree-1.18.1-3.1.0
  [✔️] illuminations-1.10.2
  [✔️] immersive-portals-1.2.5-mc1.18.1-fabric
  [✔️] IngredientExtensionAPI-fabric-1.18.1-2.0.1
  [✔️] inmis-2.4.0-1.18
  [✔️] iris-mc1.18.1-1.2.0-pre
  [✔️] lambdynamiclights-2.1.0+1.17
  [✔️] lithium-fabric-mc1.18.1-0.7.7
  [✔️] modmenu-3.0.1
  [✔️] MouseTweaks-fabric-mc1.18-2.22
  [✔️] Quark-3.0-334
  [✔️] RoughlyEnoughItems-7.1.361
  [✔️] sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14
  [✔️] starlight-1.0.0+fabric.d0a3220
  [✔️] TechReborn-5.1.0-beta.5
  [✔️] Terralith_v2.0.11_Fabric+Forge
  [✔️] tetra-1.18.1-4.3.0
  [✔️] torohealth-1.18-fabric-2
  [✔️] worldedit-mod-7.2.8
  [✔️] wraith-waystones-2.4.1
  [✔️] wthit-fabric-4.4.1
  [✔️] Xaeros_Minimap_21.23.0_Fabric_1.18

**Comment by DavidIngalls** [comment]
Do you have iris shader shadows enabled? The mention of Iris' shadow renderer in the crash-log makes me think that this might be related to #97

**Comment by PepperCode1** [comment]
Update Starlight to 1.0.1.
