### ISSUE TITLE
Contraptions visually jitter but function correctly

### ISSUE THREAD

**Issue by EmptyDreams** [Fabricators-of-Create/Create#1250]
### Describe the Bug

As the title suggests, see the video below for the exact effect.

It's worth noting that when the model is twitching: the windmill bearings are rendered correctly; the power output is normal; and the collision box for the windmill is normal, and I get pushed away by the windmill when I stand next to it.

Another detail is that it seems that when the problem occurs, all windmills have the same problem. Since I only have two windmills in my game archive at the moment, I can't guarantee that it must be all of them having problems at the same time.

There's also the small matter of me (or other creatures) being able to jump (or walk) up from anywhere in the structure after I've made it solid using the mine cart.

### Reproduction Steps

I'm not sure how to reproduce the problem, but I've encountered it more than once.

### Expected Result

The model of the windmill should rotate normally.

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/44894906/99460232-d4f5-480a-832d-3745d7c5b27b

### Crash Report or Log

https://paste.ubuntu.com/p/CBZvGJx3Dy/

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

fabric-api-0.88.1
architectury-9.1.12
cloth-config-11.1.106
sodium-0.4.10
indium-1.0.21
lithium-0.11.2
ferritecore-6.0.1
exordium-1.2.1
entityculling-1.6.2
enhancedblockentities-0.9
enchlevel-langpatch-2.1.2
Debugify-2.0
appleskin-2.5.0
journeymap-5.9.12
imblockerfabric-1.0.24
jade-11.6.4
jei-15.2.0.27
lanserverproperties-1.11.1
Patchouli-1.20.1-84
trinkets-3.7.1
Botania-441
create-0.5.1d

**Comment by EmptyDreams** [comment]
Windmill models are not the only ones that can have problems, other models can have problems as well.

https://github.com/Fabricators-of-Create/Create/assets/44894906/21050b0c-d004-4fba-acd1-4983c69ac4a2

I'm guessing it might have something to do with entities "穿模[^1]" with other squares?

[^1]: 穿模：Refers to the whole of a model or part of it mistakenly overlapping another model. Forgive me if I'm not sure how to say this word in English.

**Comment by drwoops** [comment]
does F3+A fix the issue for you?

**Comment by TropheusJ** [comment]
try removing entityculling

**Comment by EmptyDreams** [comment]
> does F3+A fix the issue for you?

I tried this and this solved the problem I was having.

**Comment by EmptyDreams** [comment]
> try removing entityculling

What's "entityculling"?

**Comment by EmptyDreams** [comment]
> try removing entityculling

Oh you mean this mod, I tried it and the problem still exists after removing this mod.

**Comment by EmptyDreams** [comment]
https://github.com/Fabricators-of-Create/Create/assets/44894906/40c0491c-fe15-4bea-bc80-d86290ee9b3d

Today I found out that a similar problem occurs with lifts and that "F3 + A" does not fix the problem.

**Comment by TropheusJ** [comment]
There's been no other reports in nearly a year and still no reproduction or any hints
