### ISSUE TITLE
Recipe for Tea does not match Forge version's

### ISSUE THREAD

**Issue by shimmer-n-shine** [Fabricators-of-Create/Create#1251]
### Describe the Bug

In the forge version of create, half a bucket of tea is created from a quarter bucket of water and milk [(source code)](https://github.com/Creators-of-Create/Create/blob/mc1.20.1/dev/src/generated/resources/data/create/recipes/mixing/tea.json), however, in the fabric version of the mod, 1 bottle of milk and water equates to 2 bottles of tea. [(source code)](https://github.com/Fabricators-of-Create/Create/blob/mc1.20.1/fabric/dev/src/generated/resources/data/create/recipes/mixing/tea.json)

~1 bucket of water and milk would produce 1 and a half buckets of tea in forge, but 2 buckets of tea in fabric.~ EDIT: I did my math wrong so the output for a bucket is the same in both fabric and forge, but still, there's a discrepancy between millibuckets and droplets.

### Reproduction Steps

N/A

### Expected Result

For fabric and forge to have parity.

### Operating System

N/A

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Additional Context

The issue is present in the code for the 1.18 version as well, I did not check the other branches.

**Comment by shimmer-n-shine** [comment]
Also, for the record, the same problem is also present for [chocolate (fabric)](https://github.com/Fabricators-of-Create/Create/blob/mc1.20.1/fabric/dev/src/generated/resources/data/create/recipes/mixing/chocolate.json) [chocolate (forge)](https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/generated/resources/data/create/recipes/mixing/chocolate.json) and [chocolate melting (fabric)](https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/generated/resources/data/create/recipes/mixing/chocolate_melting.json) [chocolate melting (forge)](https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/generated/resources/data/create/recipes/mixing/chocolate_melting.json)

**Comment by drwoops** [comment]
your math is flawed

**Comment by shimmer-n-shine** [comment]
I don't see how 250mb in forge is equal to 27000 droplets in fabric, but okay.

**Comment by drwoops** [comment]
for  the forge recipe. if you multiple by 4 the inputs, you also multiply by 4 the output and that comes out as 2 buckets

**Comment by shimmer-n-shine** [comment]
I don't know how I missed this, that's completely true, still, the actual issue with a mismatch between mbs and droplets remains

**Comment by drwoops** [comment]
1 mb = 81 droplets. so that comes out as 1 bottle = 1/3 bucket for the fabric recipe.  that seems to check out

**Comment by TropheusJ** [comment]
This is intended.
Because millibuckets are nonsense, it's both equivalent and not equivalent.
If you go by millibuckets, then on forge, you get 250 + 250 = 500, and on fabric, 333 + 333 = 666.
If you go by bottles, then on both loaders, it's 1 bottle + 1 bottle = 2 bottles.
The bottle method will be kept as it makes much more sense in a fabric environment.
