### ISSUE TITLE
Contraptions crashing server and duplicating items

### ISSUE THREAD

**Issue by JXSnack** [Fabricators-of-Create/Create#1252]
### Describe the Bug

Some people on my server tried placing a cart assembler ontop of a moving furnace minecart and then the server crashed

### Reproduction Steps

"you know how to make an auto drilling machine right?
and how it needs the furnace minecart and cart assembler
basically mine was moving normally, then I saw something on it was missing (nothing to do with the glitch) and then decided to put the cart assembler on top of the minecart to stop it while it was still moving. The server then crashed/stopped and then when I got back online, everything needed to make and also the materials inside of the storage where all over the floor"

### Expected Result

There shouldn't be any items on the ground and the server should not have crashed.

### Screenshots and Videos

![image1](https://github.com/Fabricators-of-Create/Create/assets/72796341/fa22685d-c7e7-463d-ba26-b281e109bb7f)
![image5](https://github.com/Fabricators-of-Create/Create/assets/72796341/7d8959fb-506f-4c7d-b384-93857b077213)
![image4](https://github.com/Fabricators-of-Create/Create/assets/72796341/97405d1d-2431-49c7-8863-d23d5dbbcc5c)
![image3](https://github.com/Fabricators-of-Create/Create/assets/72796341/337c2915-1386-4a8a-a47a-68d81c4b05fc)
![image2](https://github.com/Fabricators-of-Create/Create/assets/72796341/7ceaca29-0b96-4fcb-af3b-b53b78ba4d26)

### Crash Report or Log

https://gist.github.com/JXSnack/f48022bf74215909294d72ea4faaeb26

### Operating System

Linux Ubuntu

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Ambient Sounds
Another Furniture
Anti XRay
Appleskin
Architectury
Bells and Whistles
Bookshelf
Brewin' and Chewin'
Concurrent Chunk Management Engine (C2ME)
CarryOn
Client Side Noteblocks
Clumps
Comforts
Controlling
CosmeticArmor
Create Enchantment Industry
Create Crafts & Additions
CreativeCore
Discord Integration
Emotecraft
Enchantment Descriptions
Entity Culling
Extended Flywheels
Fabric API (0.91.0+1.20.1)
Fabric Language Kotlin
Farmer's Delight
Ferrite Core
Indium
Iris
Jade
Jade Addons
Just Enough Items
LazyDFU
Ledger
Lithium
Logical Zoom
Mouse Wheelie
Nether's Delight
Observable
Polymorph
Reese's Sodium Options
Searchables
Slice and Dice
Sodium Extra
Sodium
Sound Physics
Spark
Starlight
Steam 'n' Rails
Traveler's Backpack
Trinkets
Vivecraft
Simple Voice Chat
Xaero's Minimap
Xaero's World Map

or download the modpack [here](https://snackbag.net/extras/snacksmp/v15-epic-fix.zip)

### Additional Context

Using create version compatible with sodium - https://modrinth.com/mod/create-fabric-sodium-fix
Version: 0.5.1d-build.5+mc1.20.1

**Comment by TropheusJ** [comment]
duplicate of #1080
