### ISSUE TITLE
Threshold Switch incorrectly selects the sides to send the redstone signal

### ISSUE THREAD

**Issue by Neakita** [Fabricators-of-Create/Create#1253]
### Describe the Bug

The Treshold Switch incorrectly determines the sides to which it should send the redstone signal when looking up and down

### Reproduction Steps

1. Place the Treshold Switch so that it looks up or down
2. Edit it's parameters so it will output redstone signal
3. Put redstone lamps so that you can understand which way the signal is going

### Expected Result

Threshold Switch sends a signal in all directions except the side from which it reads the information, as it happens in the forge version.

### Screenshots and Videos

Forge: https://www.youtube.com/watch?v=WaXLIPvyU84
Fabric: https://www.youtube.com/watch?v=Jb48tSRM8pU

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by Neakita** [comment]
I found that it was fixed in commit https://github.com/Creators-of-Create/Create/commit/2cf7d171df552c145fa7f783ea40c1b487e12ca4 for the forge version

**Comment by TropheusJ** [comment]
that commit has been merged in
