### ISSUE TITLE
no chocolate bucket

### ISSUE THREAD

**Issue by ggtlli** [Fabricators-of-Create/Create#1254]
### Describe the Bug

i went to make a chocolate farm but wif a smart fluid pipe but it needs a chocolate bucket to seperate it from the milk!

### Reproduction Steps

1.smart pipe
2.needs
3.chocolate bucket
...

### Expected Result

no chocolate bucket

### Operating System

windose 12

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by drwoops** [comment]
a bottle works as well

**Comment by TropheusJ** [comment]
![image](https://github.com/Fabricators-of-Create/Create/assets/60247969/afd66610-7f94-4411-9c96-d1ae6bd80068)
