### ISSUE TITLE
Crash: Copycat Steps with Andesite Casing Texture

### ISSUE THREAD

**Issue by Nitwon** [Fabricators-of-Create/Create#1256]
### Describe the Bug

Problematic frame:
J 49543 c2 com.simibubi.create.foundation.model.BakedModelHelper.cropAndMove(Lnet/fabricmc/fabric/api/renderer/v1/mesh/MutableQuadView;Lnet/minecraft/class_1058;Lnet/minecraft/class_238;Lnet/minecraft/class_243;)V (513 bytes) @ 0x00000154a9504e96 [0x00000154a95047a0+0x00000000000006f6]

Is what looks to be the culprit from the crash report. I will post the full report below.

Update: This is caused by copycat steps skinned with andesite casings connecting their textures to neighbouring andesite casings. I had built some windmill bearing harvester contraptions with them and after hours of play time in this world save they have started crashing the game.

### Reproduction Steps

1. Build a construction using an andesite casing block with neighbouring copycat step.
2. Skin the copycat step with andesite casing. The textures should visibly connect.
3. Set the contraption in motion.
4. Maybe start and stop the contraption a few times.

### Expected Result

Use copycat steps with connecting textures without crash.

### Crash Report or Log

https://gist.github.com/Nitwon/56e8d632fdd070aa4e948c6c36f85e7b

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

amethystequipment-fabric-mc1.20.1-v1.0.10.jar
appleskin-fabric-mc1.20.1-2.5.1.jar
architectury-9.1.12-fabric.jar
bellsandwhistles-0.4.5+1.20.1-FABRIC.jar
bobby-5.0.1.jar.disabled
boneequipment-fabric-mc1.20.1-v1.0.8.jar
Bookshelf-Fabric-1.20.1-20.1.8.jar
borderless-mining-1.1.8+1.20.1.jar
carryon-fabric-1.20.1-2.1.2.7.jar
comforts-fabric-6.3.4+1.20.1.jar
Controlling-fabric-1.20.1-12.0.2.jar
create-fabric-0.5.1-d-build.1161+mc1.20.1.jar
creategoggles-1.20.1-0.5.5.e-[FABRIC].jar
createoreexcavation-fabric-1.20-1.4.2.jar
creeperoverhaul-3.0.1-fabric.jar
DistantHorizons-2.0.1-a-1.20.1.jar
dynamiclights-v1.7-mc1.17x-1.20x-mod.jar
emeraldequipment-fabric-1.20.1-v1.1.0.jar
EnchantmentDescriptions-Fabric-1.20.1-17.0.11.jar
endermanoverhaul-fabric-1.20.1-1.0.3.jar
exlinecopperequipment-fabric-mc1.20.1-v2.1.6.jar
extendedgears-2.1.0-1.20.1-0.5.1.c-fabric.jar
fabric-api-0.88.1+1.20.1.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
geckolib-fabric-1.20.1-4.2.3.jar
GoProne-fabric-1.20.1-3.1.3.jar
InventorySorter-1.9.0-1.20.jar
Jade-1.20-fabric-11.7.0.jar
jei-1.20.1-fabric-15.2.0.27.jar
JustEnoughProfessions-fabric-1.20.1-3.0.1.jar
JustEnoughResources-Fabric-1.20.1-1.4.0.238.jar
mcw-bridges-2.1.0-mc1.20.1fabric.jar
mcw-doors-1.1.0fabric-mc1.20.1.jar
mcw-fences-1.0.7-mc1.20.1fabric.jar
mcw-furniture-3.2.1-mc1.20.1fabric.jar
mcw-lights-1.0.6-mc1.20.1fabric.jar
mcw-paintings-1.0.5-1.20.1fabric.jar
mcw-paths-1.0.3fabric-mc1.20.1.jar
mcw-roofs-2.2.4-mc1.20.1fabric.jar
mcw-trapdoors-1.1.2-mc1.20.1fabric.jar
mcw-windows-2.2.1-mc1.20.1fabric.jar
MouseTweaks-fabric-mc1.20-2.25.jar
obsidianequipment-fabric-mc1.20.1-v1.0.8.jar
replaymod-1.20.1-2.6.13.jar
resourcefulconfig-fabric-1.20.1-2.1.0.jar
resourcefullib-fabric-1.20.1-2.1.20.jar
Searchables-fabric-1.20.1-1.0.2.jar
smallships-fabric-1.20.1-2.0.0-a2.3.3.jar
Steam_Rails-1.5.1+fabric-mc1.20.1.jar
Stitched Leather v1.0 - 1.20.1.jar
warhammersmod-fabric-mc1.20.1-v1.0.8.jar
woodarmor-fabric-1.20.1-v1.1.0.jar
wooltostring-fabric-1.20.1-v1.1.0.jar

### Additional Context

I have disabled other mods to narrow it down to a Create-specific thing. I am also using the limited time between crashes to shut down contraptions to see if any of those stop the crash. UPDATE: It's the copycat steps.

**Comment by Nitwon** [comment]
I think I've traced the issue to [this commit](https://github.com/Fabricators-of-Create/Create/commit/a873af3bdf216fafea8e89fd5d00cd621b896124#diff-54f16a4bd57974936ad491d8b357a87ce28e4b76439232397d8fd9b295a619cc) and it's to do with copycat steps, I believe. I will try removing the copycat blocks from my world to see if it fixes this.

**Comment by Nitwon** [comment]
> I think I've traced the issue to [this commit](https://github.com/Fabricators-of-Create/Create/commit/a873af3bdf216fafea8e89fd5d00cd621b896124#diff-54f16a4bd57974936ad491d8b357a87ce28e4b76439232397d8fd9b295a619cc) and it's to do with copycat steps, I believe. I will try removing the copycat blocks from my world to see if it fixes this.

BakedModelHelper.cropAndMove used to return vertexData but now it returns void - why?

**Comment by Nitwon** [comment]
It's copycat steps! I used copycat steps with andesite casings, which have a complex texture connecting to their neighbouring blocks. I started breaking them, but after breaking and dropping, the blocks remained visibly in place and the game crashed.

I will update the report above with this info.

**Comment by Nitwon** [comment]
@PepperCode1 apologies for the tag, but perhaps you can help as the dev on the above commit :)

**Comment by IThundxr** [comment]
Try the following: https://gist.github.com/ChiefArug/edbda5d74bdb6944d2d46911f96d4e20

**Comment by IThundxr** [comment]
No response - closing, most likely fixed by the instructions given above
