### ISSUE TITLE
Create crashing on start

### ISSUE THREAD

**Issue by dwnsdp** [Fabricators-of-Create/Create#1257]
### Describe the Bug

Create loads up before trying again just before the main title screen before trying again three times until it crashe

### Reproduction Steps

1. install create 0.5. I-c-build.1160+mc1.19,2 and fabric api 0,77.0+1.19.2
2. watch
3.
...

### Expected Result

The game loading

### Crash Report or Log

https://pastebin.com/U4563EVY

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.19.2

### Other Mods

Fabric API fabric api 0,77.0+1.19.2

**Comment by drwoops** [comment]
downgrade fabric api to 0.76

**Comment by DarianLStephens** [comment]
Are there currently any plans to fix this?
I can _almost_ work around the issue by disabling the main menu button in the config, but it keeps reloading anyway. Doesn't crash, but unplayable.

**Comment by TropheusJ** [comment]
next update
