### ISSUE TITLE
1.18.2 - [Porting Lib] failed to reload modded shaders leads to game crash

### ISSUE THREAD

**Issue by sp4rkyd4rk** [Fabricators-of-Create/Create#1258]
### Describe the Bug

My friends and I recently updated our fabric server to match currently available version of Create (0.5.1c, build1159) for 1.18.2 from Modrinth. Server is running fabric 0.14.24 and Create is only server-side mod that causes any gameplay changes. Server runs fine however client keeps crashing even though I downgraded FAPI to 0.76.x as per #1207.

### Reproduction Steps

1. Install fabric (any version starting from 0.14.9 and up to current 0.15.3)
2. Install fabulously optimized 
3. Install Create
4. Try to launch the game
5. Game crashes with [Porting Lib] failed to reload modded shaders
...

### Expected Result

Never encountered any issues before upgrading first Create from 0.5.0i to 0.5.1c and then upgrading Fabric to 0.14.24

### Crash Report or Log

https://mclo.gs/O3LEcG8

### Operating System

Win10, MacOS

### Mod Version

0.5.1c

### Minecraft Version

1.18.2

### Other Mods

- Advancement Info
- Animatica
- AntiGhost
- Architectury
- BetterMountHUD
- BetterPingDisplay
- Borderless Mining
- Capes
- CIT Resewn
- Cloth Config v6
- Colormatic
- C2me
- Contiunity
- Create
- Cull Less Leaves
- Custom Entity Models
- DCCH
- Debugify
- Dynamic FPS
- Dynamic Fullbright
- EMI + addons / REI + addons (it may sometimes crash with either of those)
- FAPI 0.76.x
- Fabric Language Kotlin
- Fabrishot
- Farsight
- FerriteCore
- Indium
- Iris
- Item model fix
- Jade+ addons
- Journeymap
- Krypton
- LambdaBetterGrass + DynLights
- Language Reload
- LazyDFU
- Light Overlay
- Lithium
- Memory Leak Fix
- Midnight Controls
- MixinTrace
- Mod menu
- MoreChatHistory
- NoFade
- Proxy Server
- Reese's sodium options + sodium extra
- Smooth Boot
- Sodium + Tempfix
- Starlight
- ToolTip fix
- YOSBR
- Zoomify

### Additional Context

Installing Not Enough Crashes just sends me in a loop of endlessly reloading Mojang screen and keeps spamming my log with [Porting Lib] failure. Just tried to disable every mod except for FAPI and Create: [latest](https://mclo.gs/h9oEF42)

**Comment by drwoops** [comment]
the log shows you have fabric api 0.77

**Comment by sp4rkyd4rk** [comment]
> the log shows you have fabric api 0.77


Nope, it is disabled through Prism. The only running now is 0.76

**Comment by drwoops** [comment]
arguing with the log is useless:
```
- fabric-api 0.77.0 1.18.2
```

**Comment by sp4rkyd4rk** [comment]
> arguing with the log is useless:
> 
> ```
> - fabric-api 0.77.0 1.18.2
> ```

I am very sorry but that's not right. 0.76 is the only other mod besides Create which is enabled.
![image](https://github.com/Fabricators-of-Create/Create/assets/72459001/548934d8-d085-4822-928f-3e162893b142)

**Comment by drwoops** [comment]
then your log is the wrong one

**Comment by sp4rkyd4rk** [comment]
Lemme try to reinstall them. Maybe prev version of my client had FAPI from other source since i got it from my friend

**Comment by sp4rkyd4rk** [comment]
Yeah, seems like FAPI 0.76 I got was mixed up or IDK. Reinstalled it manually via modrinth site and not through launcher, so far so good. Sorry that happened

**Comment by drwoops** [comment]
if your issue is resolved please consider closing this issue
