### ISSUE TITLE
Rendering issues with 'Regions Unexplored' plants.

### ISSUE THREAD

**Issue by HaXrDEV** [Fabricators-of-Create/Create#1259]
### Describe the Bug

With only 'Create Fabric' and 'Regions Unexplored' installed, all the grass and plants from the other mod renders darker than they are supposed to.

Also, setting the Flywheel backend to "off" doesn't solve the issue.

### Reproduction Steps

1. Install both 'Create Fabric' and 'Regions Unexplored'.
2. Notice the modded medium grass texture being darker than vanilla grass.
3. Remove 'Create Fabric'.
4. Notice the medium grass texture now being the same brightness as vanilla grass.

### Expected Result

The two grass variants should be the same brightness.

### Screenshots and Videos

With 'Create Fabric':
![2024-01-03_13 43 33](https://github.com/Fabricators-of-Create/Create/assets/20630404/c5352e91-768d-4261-b3ef-aec14950c6a9)

Without 'Create Fabric':
![2024-01-03_13 52 38](https://github.com/Fabricators-of-Create/Create/assets/20630404/efbbcd1d-ded4-4f26-b5b0-b794e3a2c94c)

### Crash Report or Log

N/A

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Regions Unexplored
TerraBlender

### Additional Context

This issue applies to all plants from the mod like grass, flowers and saplings.

**Comment by drwoops** [comment]
please crash your game by holding F3+C for 10s and attach the crash report

**Comment by HaXrDEV** [comment]
> please crash your game by holding F3+C for 10s and attach the crash report

Here ya go: https://gist.github.com/HaXrBOT/2c1f73533388eb519572157deaa47441

**Comment by drwoops** [comment]
downgrade fabric api to 0.88.1

**Comment by HaXrDEV** [comment]
> downgrade fabric api to 0.88.1

Tried that, same issue. https://gist.github.com/HaXrBOT/21d981b2cfefcce0a665ed041b870d29

**Comment by drwoops** [comment]
could you try adding indium 1.0.21?

**Comment by HaXrDEV** [comment]
> could you try adding indium 1.0.21?

Same issue. https://gist.github.com/HaXrBOT/d3622e899d9ee0c9262b0226d647e507
Note that i am not using Sodium in these tests. So Indium in this case would not be doing anything.

**Comment by drwoops** [comment]
oh you're right.

**Comment by drwoops** [comment]
i wonder if the same issue happens on forge.

**Comment by HaXrDEV** [comment]
> i wonder if the same issue happens on forge.

Just tried it for the heck of it. The issue doesn't seem to occur on forge.

![billede](https://github.com/Fabricators-of-Create/Create/assets/20630404/4b7a5e2b-c3f4-4ab8-ad98-565ce436cf4a)

**Comment by drwoops** [comment]
did you try it with patch d (for exact parity)?

**Comment by HaXrDEV** [comment]
> did you try it with patch d (for exact parity)?

I did not, will try that quickly.

**Comment by HaXrDEV** [comment]
Nope, same thing. Doesn't seem to be happening even with patch d on forge.

![2024-01-03_14 37 42](https://github.com/Fabricators-of-Create/Create/assets/20630404/ae607224-807e-4209-8b35-18912ed69172)

**Comment by drwoops** [comment]
ok. thank you for doing all this testing.  that's about as good as we can narrow it down for now.

**Comment by drwoops** [comment]
you could also try to switch between different flywheel backends (off, instancing, batching)

**Comment by HaXrDEV** [comment]
> you could also try to switch between different flywheel backends (off, instancing, batching)

Did already try that, it made no difference when i tested on Fabric. Regardless of it being set to off, instancing or batching.

**Comment by TropheusJ** [comment]
incredibly strange, genuinely no clue where to even start looking for a fix

**Comment by TropheusJ** [comment]
porting lib was overriding the render material since the models specify a `render_type`. This would be fine, but it was doing it incorrectly. This will be fixed in the next release.
