### ISSUE TITLE
Sodium crash Render overlay

### ISSUE THREAD

**Issue by IamGallito** [Fabricators-of-Create/Create#1260]
### Describe the Bug

game goes into a loading loop then crashes with Create and other mods who use create enabled

### Reproduction Steps

1.enabled integrated stronghold and create mod 
2. start game and then it goes into a boot loop before crashing shortly after
3.
...

### Expected Result

tested with waystones and owo-lib and it launches with no issue it should launch normally 

### Crash Report or Log

https://pastebin.com/WFigKTPh

### Operating System

windows 10

### Mod Version

0.4.0

### Minecraft Version

1.19.2

### Other Mods

Integrated API
Integrated Strongholds
Create Fabric
owo-lib

### Additional Context

I am using an archived version of sodium and sodium extras that i found on mondrith 

![image](https://github.com/Fabricators-of-Create/Create/assets/155607881/31018277-28ce-4c7f-8424-682f2d2bca3d)

**Comment by drwoops** [comment]
downgrade fabric api to 0.76

**Comment by IamGallito** [comment]
> downgrade fabric api to 0.76

issue resolved by doing this and disabling the flywheel compact mod for iris
![image](https://github.com/Fabricators-of-Create/Create/assets/155607881/c0bb032b-073d-4550-9898-161d3747dc14)
