### ISSUE TITLE
Unplayable FPS Drop when rendering rails and assembled trains

### ISSUE THREAD

**Issue by Z3R0TR0N** [Fabricators-of-Create/Create#1263]
### Describe the Bug

Placing down rails that render as entities and/or assembling a train drops my frame rate as low as 6 FPS, which is unplayable. Moving out of the render distance for the rails and train brings back my normal 48-60 FPS. I'm not sure why this is happening and I've tried every possible tweak I could think of. 

### Reproduction Steps

1. Run Minecraft with Create Fabric and related dependencies (sodium, indium, fabric API).
2. Place down either (or both) of the following:
 - multiple rail lines that curve, change height, or otherwise require an entity. (unplayable).
 - assemble any train. (unplayable).
4. Observe severe FPS drop in the F3 debug screen.

### Expected Result

I expected my FPS to remain the same or drop by a marginal (but still playable) amount, like in previous Minecraft Create versions (e.g. 1.18, 1.19).

### Screenshots and Videos

![2024-01-05_23 49 28](https://github.com/Fabricators-of-Create/Create/assets/109635033/e94a41fd-8f69-428d-8923-6aca1ef48ce5)

### Crash Report or Log

https://pastebin.com/u8NhDALx

### Operating System

macOS Ventura 13.6.3

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

No crash occurred, but:
- Modloader: Fabric loader: 0.15.3

Mods: 
- Fabric API 0.88.1
- Sodium 0.4.10+build.27
- Indium 1.0.21
- Reese's Sodium Options 1.6.2
- Mod Menu
- EMI
- Terralith
- Incendium
- Nullscape
- Bewitchment
- Patchouli
- Pehkui
- Trinkets
- Xaero's minimap
- Xaero's worldmap
- Balm
- Waystones
- Better F3

Other mods that I confirmed are not the issue (via disabling and re-launching), but were present in the uploaded log:
- origins
- extra origins
- mob origins
- alt origins GUI
- appleskin
- inventoryHUD+
- inventory profiles next
- cloth config
- cameraUtils
- gecko lib
- gravestones
- lambdynamic lights
- libipn
- litematica
- malilib
- miniHUD
- worldedit
- size shifting potions
- replay mod
- fabric language kotlin
- shulkerbox tooltip

### Additional Context

I suspect it's a problem with my version of the Fabric Modloader, Fabric API, Indium, and/or Sodium. 

It's also possible my GPU is the issue, but I find it hard to believe a 2016 iMac with similar hardware could run Create 1.19 far better than my current 2020 iMac. 

Hardware Specs:
- iMac 2020, 27-inch Retina 5K screen
- CPU: 3.3 GHz 6-core Intel Core i5
- GPU: AMD Radeon Pro 5300 4GB
- RAM: 32 GB, 2667 MHz, DDR4

If you're unable to replicate, please let me know. That way, I know it's likely a problem with my hardware.

Yes, I restarted my computer. Yes, I also lowered my system's resolution (down to the lowest). Yes, I disabled all non-essential mods for the loaded world (see "other mods"). No, nothing changed.

**Comment by drwoops** [comment]
i checked your versions and they are correct. the log does not show an error, but just you losing connection (which admittedly is very strange in single player).  I would suggest to test in a new world, with all mods removed except create and sodium etal.

**Comment by Z3R0TR0N** [comment]
Done. Same problem once enough rails were placed. I have a screenshot of the debug screen but the file is a bit tool large.

My log is below:
https://pastebin.com/UvAXN4U0

**Comment by Z3R0TR0N** [comment]
Uploaded debug screen to drive. Here's the link:

https://drive.google.com/file/d/1OLaTIUc9IZw6Q_PutJpnhVNEfERIJWnm/view?usp=sharing

Quick note: I saw online to try disabling VSYNC, (which is why debug says "ASYNC") but no change occurred. FPS still remains too low.

**Comment by Z3R0TR0N** [comment]
New puzzling discoveries and proof of what I mean:

No rails rendered, my normal gameplay:
![2024-01-06_13 32 00](https://github.com/Fabricators-of-Create/Create/assets/109635033/6265545f-340d-4495-95f6-061ba1b5b6a6)

Rendering rails, approaching:
![2024-01-06_13 32 17](https://github.com/Fabricators-of-Create/Create/assets/109635033/367fa62b-d04a-4a10-b26a-ca45fa86a31e)

Standing still, rails rendered:
![2024-01-06_13 32 43](https://github.com/Fabricators-of-Create/Create/assets/109635033/ce8a66ac-eb79-4ba2-9def-fa8bac448366)

**Comment by Z3R0TR0N** [comment]
FIXED, thanks to the Discord community! Turns out, my computer can't do "Instancing" for Flywheel. It has to be either "Batching" or "Off." Once the config saved, my frames flipped back to their beautiful 60FPS. Closing this issue now.
