### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by KonDeveloper** [Fabricators-of-Create/Create#1266]
### Describe the Bug

I was using optimization mods with create and other mods on Fabric And I placed A Shaft It Crashed!

### Reproduction Steps

1.Launch A World
2.Place a Cogwheel, large cogwheel, shaft or gantry shaft
3.Boom! Crash!

### Expected Result

I wanted it to work perfectly fine!

### Screenshots and Videos

![GameCrash](https://github.com/Fabricators-of-Create/Create/assets/129782736/befc40ed-bb2f-4623-8a77-854846a21950)

### Crash Report or Log

https://mclo.gs/qq1xFZr

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by drwoops** [comment]
downgrade fabric api to 0.88.1
