### ISSUE TITLE
Minecart Contraption Duplication Glitch

### ISSUE THREAD

**Issue by cardboardking1** [Fabricators-of-Create/Create#1267]
### Describe the Bug

Deployers on minecart contraptions still deploy one more of their assigned block even when there is none of said block left accessible to the deployer. This allows for a duplication glitch. For example if I assign a diamond block to a deployer (does not take the diamond block) and run the minecart machine that the deployer is attached to, it will place down said diamond block from nowhere. Will only place once until the machine is refreshed.

### Reproduction Steps

1.Create a minecart contraption with a deployer attached somewhere functional.
2. Assign a unique block to the deployer that will not be accessible to the deployer from any attached chests or whatnot.
3. Run the minecart contraption.

### Expected Result

The deployer will place down 1 of its assigned item, even though it never had an item to place down. 

### Screenshots and Videos

Can't grab a video right now, but if you need assistance recreating the bug, or just need me to make a video of it, please contact cardboardking1 on discord. (I am in the create server.)

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Xareo's World map
Xareo's mini map
Distant Horizons and other small client side mods.

### Additional Context

This bug occurred on a server.

**Comment by IThundxr** [comment]
Cannot reproduce 1.18, patch f

**Comment by IThundxr** [comment]
Cannot reproduce 1.20.1 patch f

**Comment by TropheusJ** [comment]
likely already fixed or some unknown interaction then.
