### ISSUE TITLE
1.20.1 version not supported with sodium 0.5.0+ (and crash on version 0.4.10)

### ISSUE THREAD

**Issue by Kurizek27** [Fabricators-of-Create/Create#1268]
### Describe the Bug

Cannot play with sodium, other fps boost mods like optifine not available (no optifabric)

### Reproduction Steps

1.download fabric installer, create mod, fabric api and any 1.20.1 sodium (0.5.0 incopatible and 0.4.10 crashing after startup)
2. install fabric 1.20.1
3. move mods to mods folder
4. launch game

### Expected Result

Boot minecraft

### Crash Report or Log

https://gist.github.com/FakeSiryakari/0c139685c04fa1f0c8fe3e38dce0d06f

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/105744131/c7c24efc-c158-4fa4-b34c-c88d4a3ac884)

**Comment by drwoops** [comment]
downgrade fabric api to 0.88.1

**Comment by Mac64ps** [comment]
> downgrade fabric api to 0.88.1

This did not work for me. I know the create mod is in beta for 1.20.1 but is there a version of sodium that is compatible with 1.20.1 or do I need to downgrade to an older version of mc? I have tried downgrading to 0.88.1

00:20:27.492
Mod resolution failed
00:20:27.493
Immediate reason: [NEG_HARD_DEP create 0.5.1-d-build.1161+mc1.20.1 {breaks sodium @ [>=0.5.0]}, ROOT_FORCELOAD_SINGLE create 0.5.1-d-build.1161+mc1.20.1, ROOT_FORCELOAD_SINGLE sodium 0.5.3]
00:20:27.493
Reason: [NEG_HARD_DEP create 0.5.1-d-build.1161+mc1.20.1 {breaks sodium @ [>=0.5.0]}]
00:20:27.495
Fix: add [], remove [], replace [[create 0.5.1-d-build.1161+mc1.20.1] -> add:create 1 ([(-∞,∞)])]
00:20:27.514
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with any version that is compatible with:
		 - sodium 0.5.3
More details:
	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
00:20:46.681

00:20:46.682
Process crashed with exit code 1

**Comment by drwoops** [comment]
please attach the new crash report

**Comment by ryouzue** [comment]
```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Remove mod 'Zoomify' (zoomify) 2.11.2 (C:\Users\awe\AppData\Roaming\.minecraft\mods\zoomify-2.11.2.jar).
	 - Replace mod 'Valkyrien Skies 2' (valkyrienskies) 2.1.3-beta.1 with version 2.1.3-beta.1 or later that is compatible with:
		 - sodium 0.5.3
More details:
	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.3!
	 - Mod 'Valkyrien Skies 2' (valkyrienskies) 2.1.3-beta.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

To note, the issues wont be solved by "potential solutions" but by using [this Create fork](https://github.com/Treetrain1/Create) it can be fixed, however there's compatibility errors with some mods such as [Create: Interactive](https://modrinth.com/mod/interactive) bc of version name [based on this issue](https://github.com/Treetrain1/Create/issues/14) on their repo

Minecraft 1.20.1 | Jdk 17 | Fabric (Loader: 0.15.3 / API: 0.91.0)

**Comment by TropheusJ** [comment]
duplicate of #1039
