### ISSUE TITLE
An andesite funnel may play music out of thin air when used with a record player.

### ISSUE THREAD

**Issue by EmptyDreams** [Fabricators-of-Create/Create#1269]
### Describe the Bug

As the title suggests, a record can be made to be played twice by a specific action, and the music will not stop even if the record player and the andesite funnel are destroyed during the second play. However, the volume of the music will decay normally when the player moves away from the record player.

### Reproduction Steps

1. Place a record player, then place an andesite funnel on top of the record player and adjust the andesite funnel to extract items from the record player.
2. Manually place a record into the record player.
3. Wait for the record to finish playing.

### Expected Result

The music should stop playing when the playback ends.

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

architectury-9.1.12
cloth-config-11.1.106
completeconfig-2.5.0
fabric-api-0.88.1
fabric-language-kotlin-1.10.17+kotlin.1.9.22
indium-1.0.21
libIPN-fabric-1.20-4.0.1
modmenu-7.2.2
player-animation-lib-fabric-1.0.2-rc1
yet-another-config-lib-fabric-3.2.1
CreateFabricREIBugFix-0.1.0-create0.5.1
explosive-enhancement-1.2.2
 watut-fabric-1.20.1-1.0.12
journeymap-1.20.1-5.9.12
imblockerfabric-1.0.24
appleskin-fabric-mc1.20.1-2.5.1
bettercombat-fabric-1.8.3
BetterPingDisplay-Fabric-1.20.1-1.1.1
continuity-3.0.0-beta.4
InventoryProfilesNext-fabric-1.20-1.10.9
Jade-1.20-fabric-11.7.0
JadeAddons-1.20.1-fabric-5.2.3
RoughlyEnoughItems-12.0.684-fabric
Zoomify-2.11.2
create-fabric-0.5.1-d-build.1161
lanserverproperties-1.11.1
travelers-backpack-1.20.1-9.1.9
better-clouds-1.3.13
nicer-skies-1.3.0
bsvsb-3.0.3
reeses_sodium_options-1.6.3+mc1.20.1-build.92
sodium-extra-0.4.27+mc1.20.1-build.110
CustomSkinLoader_Fabric-14.19.1
Patchouli-1.20.1-84
trinkets-3.7.1
coroutil-fabric-1.20.1-1.3.5
enchlevel-langpatch-2.1.2
AdaptiveTooltips-1.3.0
Debugify-1.20.1+2.0
NoRealmsButton-1.0.1
enhancedblockentities-0.9
entityculling-fabric-1.6.2
exordium-fabric-1.2.1
letmedespawn-fabric-1.20.x-1.2.0
lithium-1.20.1-0.11.2
lunade-fastanim-1.6
memoryleakfix-fabric-1.17+-1.1.5
modernfix-fabric-5.11.1
nvidium-0.1.15-alpha
sodium-fabric-mc1.20-0.4.10+build.27
Botania-1.20.1-443

**Comment by IThundxr** [comment]
can reproduce, seems like the disc doesnt get ejected quick enough and ends up looping

Side note: disc 11 playing from thin air is very eriee

**Comment by TropheusJ** [comment]
probably the same issue as #1403
