### ISSUE TITLE
Compatibility with modded storage

### ISSUE THREAD

**Issue by RedWideWeb** [Fabricators-of-Create/Create#127]
### Describe the Suggestion

Make contraptions work with modded storages like Expanded storage.

### Screenshots and Videos

![изображение](https://user-images.githubusercontent.com/58992150/152605437-965099e3-8c4a-4943-a954-c1eb69e6b755.png)

[Expanded Storage on Curseforge](https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric)

### Additional Context

It uses it's own container library 

https://www.curseforge.com/minecraft/mc-mods/ninjaphenixs-container-library

**Comment by AlphaMode** [comment]
This is more of a issue with the forge version supporting modded storages you can make a issue about it their or make a addon
