### ISSUE TITLE
insane performance impact with just placing one block

### ISSUE THREAD

**Issue by yuma-dev** [Fabricators-of-Create/Create#1270]
### Describe the Bug

When just placing down for example a watermill block the FPS will more than halve leading to create being unplayable
Attached is a manual Crash report directly done after the video

### Reproduction Steps

1. Place Create Block
2. Watch FPS go down

### Expected Result

1. Place Create Block
2. Watch FPS be stable :D

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/76885566/c45e3854-462e-411d-b653-71ddbcd3c8ad

### Crash Report or Log

https://gist.github.com/yuma-dev/a994a1973f72dc09df216b37c1f335d4

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

https://gist.github.com/yuma-dev/8df9e35b15e8daf17379f275775acba5

### Additional Context

Running with Iris Shaders

**Comment by drwoops** [comment]
are you running a fork of create?

currently create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 and indium 1.0.21 are the precise versions you want, and those are not the versions you have.

**Comment by TropheusJ** [comment]
Enabling shaders disables Flywheel's optimizations. Nothing we can do about it. Check f3 and make sure your 3060 is listed on the right side.

**Comment by drwoops** [comment]
or you can use iris flywheel compat to keep flywheel enabled when shaders are used

**Comment by yuma-dev** [comment]
> are you running a fork of create?
> 
> currently create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 and indium 1.0.21 are the precise versions you want, and those are not the versions you have.

I am not running a fork of create, just the official one from modrinth



> Enabling shaders disables Flywheel's optimizations. Nothing we can do about it. Check f3 and make sure your 3060 is listed on the right side.

My 3060 is listed and the weird thing is that this fps drop is completely new, i never had that problem with shaders and fabric create before

> or you can use iris flywheel compat to keep flywheel enabled when shaders are used

Sadly didn't fix anything :(

**Comment by drwoops** [comment]
you may need to experiment with `/flywheel backend` to see if another setting works better for you case

**Comment by yuma-dev** [comment]
they sadly have zero impact on my performance

**Comment by drwoops** [comment]
my last idea is to use spark to get a profile. maybe this will help pinpoint the pain point

**Comment by TropheusJ** [comment]
https://github.com/Fabricators-of-Create/Create/issues/281
