### ISSUE TITLE
Create breaks fabric mining level api

### ISSUE THREAD

**Issue by dadobug1111** [Fabricators-of-Create/Create#1272]
### Describe the Bug

Fabric uses tags, such as #fabric:needs_tool_level_4 , to require tool levels beyond vanilla defaults, such as #minecraft:needs_diamond_tool . When create is installed, the fabric tags do not apply, but vanilla ones work

### Reproduction Steps

1. Install create on fabric/quilt with any mod that uses the mining level api (Ex: dadobugores/dadobugbedrockores)
2.attempt to mine the blocks that have the tag #fabric:needs_tool_level_4 with an eff5 wood pick
3.observe the gathering of resources with a wood pick which should require a netherite pick

### Expected Result

you should not get resources from the mined block, unless you use a sufficiently advanced tool (netherite pick)

with dadobugores/dadobugbedrockores , the blocks are unminable in the same way as bedrock, unless you have a valid tool.

### Operating System

Win 11

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

Architectury API 6.5.85+fabric
Cloth Config API 8.3.115+fabric
Create Fabric 0.5.0.i-1017+1.19.2 or any higher version (I tested. It started 0.5.0.i Patch 6. Persists to 0.5.1c)
Fabric API 0.76.1+1.19.2
Moonlight Lib 1.19.2-2.3.5
dadobugores-1.0.6-fabric

### Additional Context

Running the above mods, minus create, results in the intended behavior.

**Comment by TropheusJ** [comment]
literally just fixed this (hopefully)
