### ISSUE TITLE
Visual issues with chest block models

### ISSUE THREAD

**Issue by ghost** [Fabricators-of-Create/Create#1275]
### Describe the Bug

![image](https://github.com/Fabricators-of-Create/Create/assets/29960826/e35b661f-a7f3-4bf8-a0fc-ba601ef94172)
If you're using a mod such as Nostalgic Tweaks, or a resource pack like Golden Days, you will notice that create causes these additions to act strangely around chests. In Nostalgic Tweaks and Golden Days, one main feature is making the chests appear as they used to in the alpha days of minecraft. As you can see in the picture, due to Create, this doesn't work as intended, as it appears to render the tile entity chest underneath the full block chest, which causes Z fighting when it's closed, and appears to clip out of the chest when you open and close it.

It should go without saying that it takes away a lot of the immersion intended by these mods, when one of the most used and important items in the game is constantly visually artifacting every time you use it.

### Reproduction Steps

1. Download Create
2. Download Golden Days (resource pack) or Nostagic Tweaks (mod)
3. Observe how vile the chests appear

### Expected Result

Not this.
More specifically, there should be no animation when using mods or resource packs that remove said animation, and the chest model should not appear inside the full-block chest model.

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/29960826/8329f28d-96bb-4f5b-ab5d-a217dfe11c36

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Nostalgic Tweaks
Sodium
Tested with Indium (But crashed when viewing Create's UI)
Lithium
transparent-fabric
entityculling
enhancedblockentities
entity-texture-features

### Additional Context

Golden Days resource pack

**Comment by ghost** [comment]
PS. I have tested this after removing enhanecdblockentities (EBE) and the issue still persists.

**Comment by TropheusJ** [comment]
This is because [Flywheel](https://github.com/Jozufozu/Flywheel) renders some vanilla things through its optimized systems, including chests. You can disable it with `/flywheel backend off` but expect severe performance regression around Create components. You should open an issue on its repo.
