### ISSUE TITLE
[Feature Request] Threshold Switch "respect/ignore data" and "respect/ignore filters" buttons

### ISSUE THREAD

**Issue by steve-the-player** [Fabricators-of-Create/Create#1277]
### Describe the Suggestion

If a threshold switch is reading a chest containing multiple list/attribute filters with different data, and you put a blank filter on the threshold switch, it doesn't register any of them except for the blank ones in its output. It's behaving like the respect data option is stuck on. 

In addition, using a list/attribute filter on the switch wouldn't actually look for things matching the filter, even with respect data enabled, so this would require a button for whether the switch should look for filter items, or items matching the filter. 

This could be done pretty easily with a 3-state toggle, since the combination of ignore data and respect filters wouldn't work well. Ignore Data→Respect Data→Respect filters

### Screenshots and Videos

(Screenshot showing the demo setup to show it's not user error, and also there's plenty of room there on the GUI for a few more buttons)  
![2024-01-18_15 19 07](https://github.com/Fabricators-of-Create/Create/assets/61434698/47da39ac-5043-46ba-80b9-22803dff8b23)

Using a blank filter as the input, it doesn't register the filters with data
![2024-01-18_15 14 16](https://github.com/Fabricators-of-Create/Create/assets/61434698/8b6ccbf2-e3c2-4b8b-a4ae-361a0c7b9097)

Using a filter set to vegetables 
![2024-01-18_15 15 56](https://github.com/Fabricators-of-Create/Create/assets/61434698/49a1a744-b0ef-44d4-a4cc-db3dce580cea)
![2024-01-18_15 21 04](https://github.com/Fabricators-of-Create/Create/assets/61434698/d763ccbb-abb0-4e79-8c32-8a5bc1ca3be0)

Switch is behaving like it is in "respect data mode". If it was in "ignore data mode", the small chest's lamp would be lit. If it was in "respect filter mode" the large chest's lamp would be lit
![2024-01-18_15 16 23](https://github.com/Fabricators-of-Create/Create/assets/61434698/eb812e23-8480-48df-b162-8c8ca34ad59e)

### Additional Context

Bonus content!  
(on the left side) What I currently have to do if I want all 17 items in the c:vegetables tag to link up to a single redstone link vs what it should be (right side, non-functional). 
![2024-01-18_16 11 10](https://github.com/Fabricators-of-Create/Create/assets/61434698/0a300de4-c846-414c-926a-defc34115bbd)
If for any reason something were to be added or removed from that tag, because the modpack changed something slightly (which can happen at any time, especially in singleplayer), I would have to go in and rebuild the entire thing. And c:vegetables is relatively small. The attribute "is furnace fuel", for example, has over a hundred just from vanilla and baseline create. Any mod that adds a new type of wood adds over a dozen items to that attribute on its own, not counting mods that add new burnable wooden items. That is definitely a tag that I use frequently to shut things down if my systems are unable to keep up with the fuel demand, but I do NOT want to build a massive databank vault just to deal with that. 

Dealing with it manually, as I have here (as a temporary quick-fix, but one that still took 20 minutes to set up), doesn't scale up, and is completely untenable. 

_Edit: I forgot about banners. Every single possible banner pattern is technically a unique item due to NBT data. There's 12,696,344,039,844,551,126,101,565,750,244,757,433,489,827,856 (12.7 quattuordecillion) possible banners in vanilla, and all of them would need their own threshold switch and redstone stuff if I wanted to be absolutely certain I was out of fuel for my furnaces. That random chest of messed-up banners, randomly buried somewhere deep within my storage system? It could be enough to restart my entire power plant after a meltdown. Good luck getting to it though, let alone knowing it was there._ 

_I think I've made my point_

**Comment by TropheusJ** [comment]
we don't add features, suggest to the forge repo.

**Comment by steve-the-player** [comment]
whoops, my bad, thought I was there!
