### ISSUE TITLE
water wheels lagging

### ISSUE THREAD

**Issue by ghost** [Fabricators-of-Create/Create#1278]
### Describe the Bug

For some reason when I put a water wheel in my minecraft world the fps drop to 30-40 instead of the usual 150, I use shaders and thats probably the main issue but I dont want to abdicate that, is there any way to solve this?

### Reproduction Steps

1. Create water wheel/ in inventory - 150 fps
2. Put water wheel on the ground - 30 fps
3. Put blocks to cover water wheel - still 30 fps
4. Go a little far from it - 150 fps

### Expected Result

I expected the game to run normally

### Operating System

windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

sodium, starlight, lithium, jei, iris, indium, continuity, fabric api

### Additional Context

Im using complementary shaders

**Comment by drwoops** [comment]
remove starlight and add iris flywheel compat

**Comment by AMDKilla** [comment]
> remove starlight and add iris flywheel compat

Adding Iris Flywheel Compat requires an older version of Iris than currently available. It works with 1.6.9. But setting Flywheel's backend to anything but Off will cause moving Create items (Waterwheels, Crushing Wheels etc) to disappear.

**Comment by drwoops** [comment]
please crash your game by holding F3+C for 10s and attach the crash report

**Comment by AMDKilla** [comment]
> please crash your game by holding F3+C for 10s and attach the crash report

[crash-2024-01-20_16.25.03-client.txt](https://github.com/Fabricators-of-Create/Create/files/13998580/crash-2024-01-20_16.25.03-client.txt)

**Comment by drwoops** [comment]
wait you are using a fork of create. you should report the issue to the authors of the fork

**Comment by AMDKilla** [comment]
> wait you are using a fork of create. you should report the issue to the authors of the fork

Both me and OP are using the Fabric version yes. Annoyingly both the CurseForge and Modrinth "Issues" links both land here. The latest version available for Fabric is 0.5d, so I doubt they will have much of a response to this issue. Thanks for trying anyway

**Comment by TropheusJ** [comment]
https://github.com/Fabricators-of-Create/Create/issues/281
