### ISSUE TITLE
Placing encased chain drive crashes game

### ISSUE THREAD

**Issue by engineer-in-a-box** [Fabricators-of-Create/Create#1280]
### Describe the Bug

Minecraft crashes when I place an encased chain drive

### Reproduction Steps

1. Place encased chain drive

### Expected Result

Game crash

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/157236565/0ad191c5-b06d-488e-8668-892fd5be63d2

### Crash Report or Log

https://mclo.gs/Hp90IKb

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

[ModList.zip](https://github.com/Fabricators-of-Create/Create/files/13998722/ModList.zip)

**Comment by drwoops** [comment]
the precise versions you want are:
- create 0.5.1d
- sodium 0.4.10 
- fabric api 0.88.1 
- iris 1.6.4
- indium 1.0.21
