### ISSUE TITLE
Crashing when putting a handcrank on a piston

### ISSUE THREAD

**Issue by DrgamerGIT** [Fabricators-of-Create/Create#1281]
### Describe the Bug

I put a handcrank on the side of a (Create) Piston and the game crashes.

### Reproduction Steps

1.Place a (Create) Piston
2.Place a handcrank on the side
3.Right click the handcrank

### Expected Result

I expected to see the piston to move upwards when cranking the handcrank

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by drwoops** [comment]
attach the crash report
