### ISSUE TITLE
Eror texture plz help

### ISSUE THREAD

**Issue by DropMuro** [Fabricators-of-Create/Create#1282]
### Describe the Bug

Some items have an erroneous texture, how can I fix this?
![asdasdadasdasv](https://github.com/Fabricators-of-Create/Create/assets/86623982/821544e9-29ab-4635-aa2c-d3c1cd6f7493)

### Reproduction Steps

Just when entering alone or in a net, the textures are buggy

### Expected Result

HOW TO FIX THIS?

### Operating System

windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![imagedasdsadasd](https://github.com/Fabricators-of-Create/Create/assets/86623982/2ce0944e-8f5e-4483-a855-604f0f496a0e)
![imagedasdad](https://github.com/Fabricators-of-Create/Create/assets/86623982/613833ef-17d3-40b8-bad9-8f7abb1c68ae)

**Comment by drwoops** [comment]
i answered you in discord.

**Comment by danielps1818** [comment]
> i answered you in discord.

Please post answer here too.

**Comment by TropheusJ** [comment]
install indium
