### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by xXNightsecretXx** [Fabricators-of-Create/Create#1283]
I had a custom modpack with this issue and I removed the mods one by one until there was only Create Fabric and Fabric API in it, but it's still crashing when I start Minecraft. No one else seems to have this problem and I also tried removing Create and adding it back. Can anyone help me?

**Crash report:** [https://pastebin.com/7MbDbvvJ](https://pastebin.com/7MbDbvvJ)

**Mods:**
- Create Fabric 0.5.1c
- Fabric API 0.77.0

**Minecraft and Modloader version:**
- Minecraft 1.19.2
- Fabric loader 0.15.6

**Comment by drwoops** [comment]
try downgrading to fabric api 0.76

**Comment by xXNightsecretXx** [comment]
That worked! Thanks!
