### ISSUE TITLE
Game crashes when opening inventory while under a status effect.

### ISSUE THREAD

**Issue by dhnash1** [Fabricators-of-Create/Create#1284]
### Describe the Bug

Game saves and crashes when attempting to open inventory while under any status effect

### Reproduction Steps

1. Launch world
2. Inflict any status effect upon self
3. Open inventory
...

### Expected Result

Inventory should be displayed

### Crash Report or Log

https://pastebin.com/SiaEacvD

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

architectury-9.1.12-fabric
bettercombat-fabric-1.8.3+1.20.1
cloth-config-11.1.118-fabric
dimdoors-5.3.2-fabric
fabric-api-0.87.0+1.20.1
jei-1.20.1-fabric-15.2.0.27
modmenu-7.2.2
player-animation-lib-fabric-1.0.2-rc1+1.20
simplyswords-fabric-1.51.5-1.20.1

**Comment by drwoops** [comment]
please upgrade fabric api to 0.88.1

**Comment by dhnash1** [comment]
Tried this, along with the most recent Fabric API for this version of MC As a troubleshooting step, with no success

https://pastebin.com/4mDHy7iA

**Comment by drwoops** [comment]
only fapi 0.88.1 will work.  something else is interfering with the rendering of the status effect in the creative inventory screen. you will have to disable mods to find out the culprit.

**Comment by dhnash1** [comment]
I've narrowed it down to Create and FabricAPI.  Removing Create while leaving FabricAPI causes the bug to no longer occur. https://pastebin.com/5EtxMLxU

**Comment by drwoops** [comment]
for 1.20.1: currently create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 and indium 1.0.21 are the precise versions you want.
enable just create and fabric api. note how the game actually plays fine (like it does for the rest of us). now enable your other mods 1 by 1 until you find the one causing the issue.

**Comment by AshdoII** [comment]
> for 1.20.1: currently create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 and indium 1.0.21 are the precise versions you want. enable just create and fabric api. note how the game actually plays fine (like it does for the rest of us). now enable your other mods 1 by 1 until you find the one causing the issue.

Have similar problem. With both Carpet AMS addition and Create, game will crash when open inventory with any effect. Remove either will fix the problem. Change fabric api version to 0.88.1 does not fix. Game version 1.20.1. Probably casused by this. https://github.com/Fabricators-of-Create/Porting-Lib/issues/75

**Comment by TropheusJ** [comment]
fixed with newer porting lib
