### ISSUE TITLE
Game Crashes at startup due to create trying to render the Create options button

### ISSUE THREAD

**Issue by Cynic1254** [Fabricators-of-Create/Create#1285]
### Describe the Bug

I am trying to create a small modpack for fabric 1.19.2 and noticed that the pack would crash when getting to the main screen, after testing a bit more I made a separate pack which just contained the create mod and fabric api. when starting the game it would still crash and when inspecting the error log it would be clear that create was responsible.

### Reproduction Steps

1. download create fabric [link to the version I used](https://modrinth.com/mod/create-fabric/version/0.5.1-c-build.1160+mc1.19.2)
2. start the game

### Expected Result

the game should not crash

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/69977714/9eade93e-a90d-4e1f-8896-31c3bf356afe)

### Crash Report or Log

https://pastebin.com/kUvrSuj5

### Operating System

Windows 11

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

Fabric api V0.77.0+1.19.2

**Comment by Cynic1254** [comment]
I also tried running the game through the default launcher with the exact same result

**Comment by drwoops** [comment]
please downgrade fabric api to 0.76
