### ISSUE TITLE
Crash when using the Train Station when Caxton is installed

### ISSUE THREAD

**Issue by bluebear94** [Fabricators-of-Create/Create#1286]
### Describe the Bug

When [Caxton](https://modrinth.com/mod/caxton) is installed, using the Train Station results in a crash ([issue on Caxton’s repository](https://gitlab.com/Kyarei/caxton/-/issues/67)).

### Reproduction Steps

1. Create a new world
2. Place a Train Track and a Train Station next to it
3. Right-click on the Train Station

### Expected Result

The train station screen should open.

### Crash Report or Log

https://mclo.gs/7i9WjgN

### Operating System

Linux

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

* Caxton: 0.5.3+1.20.1-FABRIC
* Create IThundxr-Modding/Create-Fabric@3b15a0c was actually used to be usable in a Yarn dev env

### Additional Context

This bug is caused by an interaction between Caxton and the [`NoShadowFontWrapper`](https://github.com/Creators-of-Create/Create/blob/mc1.20.1/dev/src/main/java/com/simibubi/create/content/trains/station/NoShadowFontWrapper.java) class, as Caxton requires access to many of `Font`’s internals.

One of the underlying problems (trying to get a `StringSplitter` from the wrapper before it was fully initialized) has been fixed in [a later commit](https://gitlab.com/Kyarei/caxton/-/commit/e3af53970aa43b78cb12b28451b05dd44a9aa812).

The other problem is that Caxton expects the first parameter of the `Font` constructor to be non-null. I think this is easier to fix from Create’s side than Caxton’s, though it does require an accessor to get the `fonts` field from the wrapped `Font`.

**Comment by lisa-gui** [comment]
Running the same mods on [Forge 47.2.0](https://github.com/MinecraftForge/MinecraftForge/releases/tag/47.2) I got similar results. 
This is probably an upstream issue from [Create](https://github.com/Creators-of-Create/Create) or Caxton and is not in the scope of this project to fix.

**Comment by bluebear94** [comment]
Fair enough; I predicted that this would affect the Forge versions, too, but only tested with Fabric so far.

**Comment by IThundxr** [comment]
Seems like caxtons issue, they should be null checking stuff

**Comment by bluebear94** [comment]
Actually, I realized that I could use `Font#getFontSet` instead of accessing the `Font#fonts` field directly. Definitely easier than mixing into `NoShadowFontWrapper`.

**Comment by bluebear94** [comment]
[Fixed on Caxton’s side.](https://gitlab.com/Kyarei/caxton/-/commit/e8a02d34c5072ed55c3085fa0b2feb4e7919e2b1)
