### ISSUE TITLE
Unexpected behaviour (placed blocks are turning into other blocks)

### ISSUE THREAD

**Issue by wkiuchi** [Fabricators-of-Create/Create#1291]
### Describe the Bug

I go to the server and put a block, but it changes to another block.

### Reproduction Steps

1. Creating a fabric server.
2. Installing fabric-api and create-sodium-fix on client & server.
3. Just placing create blocks.

### Expected Result

Expected result is expected behaviour? I just want to place the blocks normally.

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/147205839/42c766b8-7d07-4708-9174-dcbf363d65d6

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

on client:
instead of fapi - qfapi
indium
iris
sodium

**Comment by IThundxr** [comment]
Registry desync make sure the server & client have the same mods of the same version, also the fork is not supported here so please go to its respective issue tracker
