### ISSUE TITLE
Compat with Extended Drawers Mod

### ISSUE THREAD

**Issue by forcedaresky** [Fabricators-of-Create/Create#1292]
### Describe the Suggestion

since the drawer's added by "extended drawers" did not extend ChestBlock it will not functioning as intended when placed on contraption and will be acted as a "normal not functioning block"

[https://modrinth.com/mod/extended-drawers](url)

### Screenshots and Videos

Before applying into contraption 

![2024-01-30_22 24 17](https://github.com/Fabricators-of-Create/Create/assets/31381698/9426a15d-5344-4c41-acc0-dcfb11c4ef87)
![2024-01-30_22 24 10](https://github.com/Fabricators-of-Create/Create/assets/31381698/08650b7c-89f9-49e5-835d-77596e50abe4)
![2024-01-30_22 24 13](https://github.com/Fabricators-of-Create/Create/assets/31381698/87b161f8-7d6b-424d-be68-e05ed8a9d7ee)

After applying into minecart contraption

![2024-01-30_22 24 39](https://github.com/Fabricators-of-Create/Create/assets/31381698/ed4aa7f0-a303-4999-a705-f7ec06725fe1)
![2024-01-30_22 24 42](https://github.com/Fabricators-of-Create/Create/assets/31381698/7836d560-2f91-4fb3-993f-e3092c93dc72)
![2024-01-30_22 24 47](https://github.com/Fabricators-of-Create/Create/assets/31381698/751212ca-cf80-47d7-b9ed-829bb3d6d7ed)

**Comment by liKe2k1** [comment]
Confirmed :(

**Comment by TropheusJ** [comment]
mod compat has been a long-standing issue on both forge and fabric. #389
