### ISSUE TITLE
big water wheel and other wheels arent rendering and other items

### ISSUE THREAD

**Issue by Alastor8881** [Fabricators-of-Create/Create#1293]
### Describe the Bug

When ever i load up the game it works fine but the water wheel and other types of wheels dont render at all

### Reproduction Steps

1.Load minecraft
2.Enter a world
3.and look at the water wheels or flywheel dosent render at all
...

### Expected Result

.

### Screenshots and Videos

![2024-01-30_11 47 22](https://github.com/Fabricators-of-Create/Create/assets/110850664/1f6d84ba-1262-4fbf-8812-8d46ffb823ed)
![2024-01-30_11 47 24](https://github.com/Fabricators-of-Create/Create/assets/110850664/044cad43-9068-4ca0-9d6d-75f55a989df2)
![2024-01-30_11 47 26](https://github.com/Fabricators-of-Create/Create/assets/110850664/418e28fb-3f05-44ab-8f31-07837157e540)
![2024-01-30_11 47 30](https://github.com/Fabricators-of-Create/Create/assets/110850664/616d205a-0e57-43e6-97c6-03519eca3f94)
![2024-01-30_11 47 35](https://github.com/Fabricators-of-Create/Create/assets/110850664/7bd50830-7308-4686-a95b-44d7f334f8cb)
![2024-01-30_11 47 12](https://github.com/Fabricators-of-Create/Create/assets/110850664/f339c192-c65e-4aef-8b30-b862f4a4e7d9)

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

_rottenflesh-to-leather_1-20-x.jar
additionallanterns-1.1.1-fabric-mc1.20.jar
alloy-forgery-2.1.2+1.20.jar
AmbientEnvironment-fabric-1.20.1-11.0.0.1.jar
AmbientSounds_FABRIC_v5.3.5_mc1.20.1.jar
amecs-1.3.10+mc.1.20.1.jar
amethystequipment-fabric-mc1.20.1-v1.0.10.jar
appleskin-fabric-mc1.20.1-2.5.1.jar
archers-1.0.7+1.20.1.jar
architectury-9.1.12-fabric.jar
areas-1.20.1-5.3.jar
autotag-2.0.2+1.20.jar
azurelibarmor-fabric-1.20.1-2.0.3.jar
azurelib-fabric-1.20.1-2.0.19.jar
balm-fabric-1.20.1-7.2.1.jar
basicweapons-fabric-mc1.20.1+1.2.0.jar
bclib-3.0.14.jar
bedrockify-1.9.1+mc1.20.jar
BetterAdvancements-Fabric-1.20.1-0.3.2.162.jar
bettercommandblockui-0.4.2-1.20.jar
better-end-4.0.11.jar
BetterF3-7.0.2-Fabric-1.20.1.jar
betterfpsdist-fabric-1.20.1-4.0.jar
bettermounthud-1.2.2.jar
better-nether-9.0.10.jar
BetterPingDisplay-Fabric-1.20.1-1.1.1.jar
betterstats-3.7.1+fabric-1.20.1.jar
BetterThirdPerson-Fabric-1.20-1.9.0.jar
BlackwolfLibrary-1.20.1-1.0.4-[FABRIC].jar
boneequipment-fabric-mc1.20.1-v1.0.8.jar
Bookshelf-Fabric-1.20.1-20.1.8.jar
Bountiful-6.0.3+1.20.1-fabric.jar
breakfree-1.2.0.jar
brick_variety_v1.1.2_1.20.1_FABRIC.jar
c2me-fabric-mc1.20.1-0.2.0+alpha.11.0.jar
capes-1.5.2+1.20-fabric.jar
cardinal-components-api-5.2.2.jar
CatEyes-v7_Fabric-1.20.1.jar
cavedweller-1.3.0.jar
chat_heads-0.10.30-fabric-1.20.jar
cherishedworlds-fabric-6.1.5+1.20.1.jar
chesttracker-1.20.1-1.1.23.jar
Chimes-v2.0.1-1.20.1-Fabric.jar
chunksfadein-v1.0.5-1.20.jar
Chunky-1.3.92.jar
ClearDespawn-fabric-1.20.2-1.1.15.jar
clienttweaks-fabric-1.20-11.1.0.jar
cloth-config-11.1.118-fabric.jar
Clumps-fabric-1.20.1-12.0.0.3.jar
collective-1.20.1-7.30.jar
colorfulhearts-fabric-1.20.1-4.0.4.jar
combatroll-fabric-1.3.1+1.20.1.jar
comforts-fabric-6.3.4+1.20.1.jar
continuity-3.0.0-beta.4+1.20.1.jar
Controlling-fabric-1.20.1-12.0.2.jar
CosmeticArmor-1.20-1.6.0.jar
crab-fabric-1.20.2-1.0.2.jar
crafting-manipulator-4.1.0+1.20.jar
craftingtweaks-fabric-1.20-18.2.2.jar
CraftPresence-2.2.6+1.20.1.jar
createbigcannons-fabric-1.20.1-0.5.2.a.jar
create-fabric-0.5.1-d-build.1161+mc1.20.1.jar
CreativeCore_FABRIC_v2.11.16_mc1.20.1.jar
creeperoverhaul-3.0.1-fabric.jar
Croptopia-1.20.1-FABRIC-3.0.4.jar
ctov-3.3.6.jar
daily-shop-1.6.jar
dark-enchanting-1.0.3+1.20.1.jar
dark-loading-screen-1.6.14.jar
darkloot-fabric-1.20.1-1.2.0.jar
darkmining-fabric-1.20.1-1.1.1.jar
darkmobs-fabric-1.20.1-1.0.7.jar
darkquesting-fabric-1.20.1-1.1.8.jar
darkrewards-fabric-1.20.1-1.0.9.jar
darksmelting-fabric-1.20.1-1.0.6.jar
dawn-5.0.0.jar
deeperdarker-fabric-1.20-1.2.5.jar
dehydration-1.3.4.jar
DetailArmorBar-2.6.3+1.20.1-fabric.jar
DiagonalFences-v8.1.3-1.20.1-Fabric.jar
DiagonalWindows-v8.1.3-1.20.1-Fabric.jar
dragonloot-1.1.4.jar
dualwielding-1.1.2.jar
dummmmmmy-1.20-1.8.13-fabric.jar
durabilitytooltip-1.1.5-fabric-mc1.20.jar
dynamiccrosshair-7.4.4+1.20-fabric.jar
dynamic-fps-3.3.3+minecraft-1.20.0.jar
EasyAnvils-v8.0.1-1.20.1-Fabric.jar
EasyMagic-v8.0.1-1.20.1-Fabric.jar
eating-animation-1.20+1.9.5.jar
Eldritch_End-FABRIC-MC1.20.1-0.2.31.jar
eldritch-mobs-1.15.0.jar
elytra_physics-fabric-2.0.jar
elytra_trinket-1.0.3.jar
emeraldequipment-fabric-1.20.1-v1.1.0.jar
emoji-type-2.2.3+1.20.4-fabric.jar
EnchantmentDescriptions-Fabric-1.20.1-17.0.13.jar
enchantment-transfer-0.0.6-fabric-1.20.1.jar
enhancedblockentities-0.9+1.20.jar
entity_model_features_fabric_1.20.1-1.2.3.jar
entity_texture_features_fabric_1.20.1-5.2.1.jar
entityculling-fabric-1.6.2-mc1.20.1.jar
entity-view-distance-1.1.2+1.20.jar
EpheroLib-1.20.1-FABRIC-1.2.0.jar
essential_1-3-0-2_fabric_1-20-1.jar
eureka-1201-1.3.0-beta.4.jar
expanded_ecosphere-3.2.4-fabric.jar
explosive-enhancement-1.2.2-1.20.x.jar
Extra-Enchantments-and-Curses-1.8.1.jar
fabric-api-0.88.1+1.20.1.jar
fabric-end-remastered-5.2.4.jar
fabric-language-kotlin-1.10.17+kotlin.1.9.22.jar
fabric-seasons-2.3+1.20.jar
fallingleaves-1.15.4+1.20.1.jar
fastquit-3.0.0+1.20+.jar
fennecfox-fabric-1.20.1-1.0.0.jar
ferritecore-6.0.1-fabric.jar
firstperson-fabric-2.3.0-mc1.20.1.jar
forcecloseloadingscreen-2.1.1.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
friendsandfoes-fabric-mc1.20.1-2.0.7.jar
From-The-Fog-1.20-v1.9.2-Forge-Fabric.jar
geckolib-fabric-1.20.1-4.2.1.jar
gpumemleakfix-fabric-1.20.1-1.8.jar
handcrafted-fabric-1.20.1-3.0.5.jar
healingcampfire-1.20.1-5.3.jar
holdthatchunk-2.0.1+1.19.jar
icarus-1.16.jar
Iceberg-1.20.1-fabric-1.1.11.jar
immersive_aircraft-0.6.2+1.20.1-fabric.jar
immersive_paintings-0.6.7+1.20.1-fabric.jar
ImmersiveThunder-1.20.1+1.2.2.jar
indium-1.0.21+mc1.20.1.jar
infinitetrading-1.20.1-4.3.jar
infinity-and-mending-1.20.x-1.0.0.jar
interactic-0.2.0+1.20.jar
InventorySorter-1.9.0-1.20.jar
invhud.fabric.1.20-3.4.18.jar
InvMove-1.20-0.8.4-Fabric.jar
invoke-0.2.0.jar
iris-mc1.20-1.6.4.jar
IronChests-2.0.0.jar
ItemBorders-1.20.1-fabric-1.2.0.jar
itemscroller-fabric-1.20.1-0.20.0.jar
Jade-1.20-fabric-11.7.0.jar
Jewelry-1.2.2+1.20.1.jar
journeymap-1.20.1-5.9.18-fabric.jar
jumpoverfences-fabric-1.20.1-1.3.1.jar
Kambrik-6.1.1+1.20.1-fabric.jar
knavesneeds-fabric-2.0.1+1.20.1.jar
krypton-0.2.3.jar
Ksyxis-1.2.2.jar
lambdynamiclights-2.3.2+1.20.1.jar
lazydfu-0.1.3.jar
LegendaryTooltips-1.20.1-fabric-1.4.3.jar
libz-1.0.1.jar
lithium-fabric-mc1.20.1-0.11.2.jar
malilib-fabric-1.20.1-0.16.3.jar
MapFrontiers-1.20.1-2.6.0p1-fabric.jar
mcda-5.0.1.jar
mcdar-3.0.0.jar
mcde-1.5.6-1.20.jar
mcdw-9.0.0.jar
mcw-bridges-2.1.0-mc1.20.1fabric.jar
memoryleakfix-fabric-1.17+-1.1.5.jar
midnightlib-fabric-1.4.1.1.jar
minecraft-comes-alive-7.5.11+1.20.1-universal.jar
mobhealthbar-fabric-1.20.x-2.3.0.jar
modelfix-1.14-fabric.jar
modernfix-fabric-5.12.1+mc1.20.1.jar
modmenu-7.2.2.jar
moonlight-1.20-2.8.84-fabric.jar
more_mobs-v1.5.1-mc1.14x-1.20x-mod.jar
MoreBows-1.0.11+1.20.x.jar
MoreButtons-1.20.1-1.0.3-[FABRIC].jar
MoreCarpets-1.20.1-1.0.3-[FABRIC].jar
morediscs-1.20.1-32-fabric.jar.
MoreDoors-1.20.1-1.0.4-[FABRIC].jar
MoreFences-1.20.1-1.0.3-[FABRIC].jar
moremobvariants-fabric+1.20-1.2.2.jar
MorePressurePlates-1.20.1-1.0.4-[FABRIC].jar
MoreSlabs-1.20.1-1.0.3-[FABRIC].jar
MoreStairs-1.20.1-1.0.3-[FABRIC].jar
MoreTrapdoor-1.20.1-1.0.4-[FABRIC].jar
morevillagers-fabric-1.20.1-5.0.0.jar
MoreWalls-1.20.1-1.0.4-[FABRIC].jar.
MouseTweaks-fabric-mc1.20-2.25.jar
mousewheelie-1.13.0+mc1.20.1.jar
mythic_charms-fabric-1.20.1-0.6.0.jar
mythicmetals-0.19.2+1.20.1.jar
mythic-mounts-1.20.1-7.4.jar
mythicupgrades-2.4.0+mc1.20.1.jar
naturalist-fabric-4.0.3-1.20.1.jar
NaturesCompass-1.20.1-2.2.3-fabric.jar
Necronomicon-Fabric-1.4.1.jar
netherportalfix-fabric-1.20-13.0.1.jar
NETS_0.3.5.5.jar
nicer-skies-1.3.0+1.20.1.jar
niftycarts-3.0.0+1.20.1.jar
NoChatReports-FABRIC-1.20.1-v2.2.2.jar
NoFog-1.3.5+1.16.5-1.20.4.jar
noisium-1.0.2+mc1.20.x.jar
nonarrator-1.0.1.jar
notenoughanimations-fabric-1.7.0-mc1.20.1.jar
Notes-1.20.1-2.1.0-fabric.jar
nounusedchunks-2.0.jar
nyfsquiver-1.20.1-fabric-1.0.4.jar
owo-lib-0.11.2+1.20.jar
paladin-furniture-mod-1.2.0-fabric-mc1.20.1.jar
paladins-1.0.5+1.20.1.jar
Paraglider-fabric-20.1.3.jar
Patchouli-1.20.1-84-FABRIC.jar
Pehkui-3.7.12+1.14.4-1.20.4.jar
player-animation-lib-fabric-1.0.2-rc1+1.20.jar
playlist-1.3.0-1.20.1.jar.
plushies-1.4.0-fabric.jar
polymer-bundled-0.5.19+1.20.1.jar
portabletables-fabric-1.20.1-2.4.jar
potionring-fabric-1.20-1.0.jar
PresenceFootsteps-1.9.1.jar
Prism-1.20.1-fabric-1.0.5.jar
projectile_damage-fabric-3.2.2+1.20.1.jar
promenade-4.1.1.jar
puffish_skills-0.11.2-1.20-fabric.jar
qualitysounds-1.0.0-1.20.1.jar
rare-ice-0.6.0.jar
realisticsleep-1.10.2+mc1.20-1.20.1.jar
recallstaffs-4.1.2+1.20.jar
redpanda-forge-1.20.1-1.0.4.jar yes it is for fabric as well just has name forge
reeses_sodium_options-1.6.2+mc1.20.1-build.85.jar
reinforced-barrels-2.4.1+1.20.jar
reinforced-shulker-boxes-2.5.0+1.20.jar
resourcefulconfig-fabric-1.20.1-2.1.2.jar
resourcefullib-fabric-1.20.1-2.1.20.jar
RingsOfAscension-1.20.1-2.0.2.jar
RoughlyEnoughItems-12.0.684-fabric.jar
runes-fabric-0.9.11+1.20.1.jar
sassot-1.1.3.a-1.20.1+bettercombat.jar
Searchables-fabric-1.20.1-1.0.2.jar
ShoulderSurfing-Fabric-1.20.1-2.8.1.jar
show-me-your-skin-1.6.11+1.20.jar
shulkerboxtooltip-fabric-4.0.4+1.20.1.jar
simplehats-fabric-1.20.1-0.2.0.jar
simplyswords-fabric-1.51.5-1.20.1.jar
skinlayers3d-fabric-1.6.2-mc1.20.1.jar
SkyVillages-1.0.3.2-1.19.2-1.20.1-fabric.jar
slime-1.1.jar
smallernetherportals-1.20.1-3.6.jar
smallships-fabric-1.20.1-2.0.0-a2.3.3.jar
smoothswapping-0.9.3.1-1.20.2-fabric.jar
sodium-extra-0.4.20+mc1.20-build.103.jar
sodium-fabric-mc1.20-0.4.10+build.27.jar
solid_mobs_fabric.1.19.4+1.20-1.7.1.jar
sound-physics-remastered-fabric-1.20.1-1.3.1.jar
spark-1.10.53-fabric.jar
spell_engine-0.12.5+1.20.1.jar
spell_power-fabric-0.9.19+1.20.1.jar
StrawStatues-v8.0.2-1.20.1-Fabric.jar
structure_pool_api-1.0+1.20.1.jar
supermartijn642configlib-1.1.8a-fabric-mc1.20.jar
supermartijn642corelib-1.1.16-fabric-mc1.20.1.jar
symbol-chat-1.20.1-1.1.2.jar
talkbubbles-1.0.8.jar
The_Graveyard_2.9.1_(FABRIC)_1.20+.jar
things-0.3.3+1.20.jar
tia-1.20-1.1-fabric.jar
ToolStats-Fabric-1.20.1-16.0.7.jar
TradingPost-v8.0.1-1.20.1-Fabric.jar
travelers-backpack-1.20.1-9.1.9.jar
TravelersTitles-1.20-Fabric-4.0.1.jar
TreeChop-1.20.1-fabric-0.18.8.jar
trimeffects-1.1.0-fabric.jar
trinkets-3.7.1.jar
universal_ores-1.5.2.jar
valkyrienskies-120-2.1.3-beta.1.jar
variantvanillablocks-1.3.7.jar
villager-hats-1.6.2+1.20.jar
villagernames-1.20.1-7.3.jar
visuality-0.7.1+1.20.jar
voicechat-fabric-1.20.1-2.4.32.jar
voidtotem-fabric-1.20-3.0.1.jar
warhammersmod-fabric-mc1.20.1-v1.0.8.jar
waveycapes-fabric-1.4.0-mc1.20.jar
weaponmaster-client-only-fabric-1.20.1-3.0.5.jar
Weeping-Angels-46.0.1-fabric.jar
winterly-0.9.3+1.20.jar
wizards-1.0.5+1.20.1.jar
WI-Zoom-1.5-MC1.20.1.jar
wooltostring-fabric-1.20.1-v1.1.0.jar
yet-another-config-lib-fabric-3.2.1+1.20.jar
YungsApi-1.20-Fabric-4.0.2.jar
zmedievalmusic-fabric-1.20.1-2.1.jar
PuzzlesLib-v8.1.15-1.20.1-Fabric.jar
cupboard-fabric-1.20.1-2.2.jar
cristellib-1.1.5-fabric.jar
CameraOverhaul-1.4.0-fabric-universal.jar
clockwork-1.20.1-0.1.1-fabric-b82e904a5e.jar
createaddition-fabric+1.20.1-0.9.0.jar
creatediselgenerators-2.1.3.jar
disenchanter-0.1.8+1.20.jar
lootbeams-1.0.3.jar

### Additional Context

If someone could help me i would appreciate it.

**Comment by drwoops** [comment]
remove sound physics remastered; it is known to cause issues having nothing to do with sound

**Comment by Alastor8881** [comment]
> remove sound physics remastered; it is known to cause issues having nothing to do with sound

its not the sound physics remasterd i deleted it and its still not rendering

**Comment by drwoops** [comment]
please crash your game by holding F3+C for 10s and attach the crash report

**Comment by Alastor8881** [comment]
[crash-2024-01-30_19.54.03-client.txt](https://github.com/Fabricators-of-Create/Create/files/14102949/crash-2024-01-30_19.54.03-client.txt)
heres the crash report

> please crash your game by holding F3+C for 10s and attach the crash report

**Comment by Alastor8881** [comment]
found the problem it was playlist mod that was making it not render at all which doesnt make sense cuz it only allowes you to chose music but ok i removed it and now its working
