### ISSUE TITLE
Graphic bug, [0.5.1-d-build.1161+mc1.20.1}

### ISSUE THREAD

**Issue by Unleashed75** [Fabricators-of-Create/Create#1294]
### Describe the Bug

Only seeing this on chest right now but I haven't been playing with all the mods I have so far.

Chest showup with black lids and can become normal based on other chests around them. Sometimes only half of a double chest will have the bug and the other half look normal.

As you can see below, I have only got 2 mods installed. Fabric API and Create for Fabric

### Reproduction Steps

1. Install Fabric api for 1.20.1
2. Install Create Fabric 0.5.1-d-build.1161+mc1.20.1
3. Load any new world and place chests
... 
![image](https://github.com/Fabricators-of-Create/Create/assets/136971457/735bf197-17a6-49a9-a1a6-7f2421044b51)
![image](https://github.com/Fabricators-of-Create/Create/assets/136971457/1063b7e0-5476-45c2-841f-13c775a442a4)

### Expected Result

Expected chest to look like normal chests

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by denys-duchier** [comment]
you need fabric api 0.88.1

**Comment by Unleashed75** [comment]
so the only fix is to roll back 6 versions of Fabric API?
Is this a Create Fabric problem or the Fabric API it's self?

**Comment by Unleashed75** [comment]
I just tried it with all the mods I have installed and that one change breaks the game from loading due to being a outdated version for some of the other mods installed, unless I roll them back just to fix this, which I am not going to test.

The bug does happen on the Forge version too, which I have reported. Another person started a post thinking it's because we have a AMD GPU. I've no idea but if both versions have the problem, sounds like something in it's core to me and not to do with the how the AMD GPU's work.

I have noticed some black parts of the Create toolboxes too, just on the draw parts.
Playing with shaders on, fixes the graphical bugs but tanks my fps when looking at any contraption, from 120+ fps (locked), right down to 10- fps. Rolling back versions or playing with shaders is not really good ways to solve this, in my opinion.

Just sharing all the info I know, not trying to be rude etc

**Comment by IThundxr** [comment]
> I just tried it with all the mods I have installed and that one change breaks the game from loading due to being a outdated version for some of the other mods installed, unless I roll them back just to fix this, which I am not going to test.
> 
> The bug does happen on the Forge version too, which I have reported. Another person started a post thinking it's because we have a AMD GPU. I've no idea but if both versions have the problem, sounds like something in it's core to me and not to do with the how the AMD GPU's work.
> 
> I have noticed some black parts of the Create toolboxes too, just on the draw parts. Playing with shaders on, fixes the graphical bugs but tanks my fps when looking at any contraption, from 120+ fps (locked), right down to 10- fps. Rolling back versions or playing with shaders is not really good ways to solve this, in my opinion.
> 
> Just sharing all the info I know, not trying to be rude etc

Most likely a flywheel issue, pretty sure i replied to you on the forge repo but my memorys bad so try /flywheel backend batching, if that fixes this then it should be reported to flywheel

**Comment by Unleashed75** [comment]
> > I just tried it with all the mods I have installed and that one change breaks the game from loading due to being a outdated version for some of the other mods installed, unless I roll them back just to fix this, which I am not going to test.
> > The bug does happen on the Forge version too, which I have reported. Another person started a post thinking it's because we have a AMD GPU. I've no idea but if both versions have the problem, sounds like something in it's core to me and not to do with the how the AMD GPU's work.
> > I have noticed some black parts of the Create toolboxes too, just on the draw parts. Playing with shaders on, fixes the graphical bugs but tanks my fps when looking at any contraption, from 120+ fps (locked), right down to 10- fps. Rolling back versions or playing with shaders is not really good ways to solve this, in my opinion.
> > Just sharing all the info I know, not trying to be rude etc
> 
> Most likely a flywheel issue, pretty sure i replied to you on the forge repo but my memorys bad so try /flywheel backend batching, if that fixes this then it should be reported to flywheel

Yes that was me, I mentioned about the big frame drops when looking at contraptions

**Comment by TropheusJ** [comment]
opened an issue on flywheel: https://github.com/Jozufozu/Flywheel/issues/226
