### ISSUE TITLE
Fluid tank xray windows

### ISSUE THREAD

**Issue by Piecuuu** [Fabricators-of-Create/Create#1295]
### Describe the Bug

Fluid tank's windows create an "xray-like" effect.

### Reproduction Steps

1. Install the More Culling mod and Create Fabric
2. Place a fluid tank with at least one window covered by a block

### Expected Result

The fluid tank's windows should not have an "xray" effect

### Screenshots and Videos

https://imgur.com/a/5k4hUrn

### Operating System

Linux, specifically Gentoo (! Wayland with Nvidia)

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

More culling, Borderless Mining, Mod Menu, Cloth Config (dependency of More Culling)

### Additional Context

It only happens with the More Culling mod, disabling "Create" in Mod Compatibility of the More Culling config menu solves the issue.

**Comment by IThundxr** [comment]
Moreculling breaks many mods and shouldn't be used, sodium's culling is more then enough and strict enough that it doesnt break in modded play unlike more cullings which dies in a modded environment
