### ISSUE TITLE
Crashes during loading screen: 

### ISSUE THREAD

**Issue by MrStickyPiston** [Fabricators-of-Create/Create#1296]
### Describe the Bug

Minecraft shows the loading screen,
shows the same loading screen again,
fades saving world for a half second
crashes

### Reproduction Steps

1. Install Create fabric
2. Install fabric api (required)
3.
...

### Expected Result

The game doesnt load twice and doesnt crash

### Crash Report or Log

https://mclo.gs/qLb98Ha

### Operating System

Kubuntu 22.04

### Mod Version

0.5.1c

### Minecraft Version

1.18.2

### Other Mods

Fabric Api 0.77.0+1.18.2

### Additional Context

It worked before so idk why it doesnt work now.
I have more mods in another instance, thats where it first crashes. I made this instance to make the debugging more easy.

**Comment by MrStickyPiston** [comment]
Edit: The problem was fabric api 0.77, 0.76 worked fine. Maybe require fabric api up to 0.76?

**Comment by HelloKerem** [comment]
i got the same error too

**Comment by HelloKerem** [comment]
wait IT WORKED REPLACE 0.77 TO 0.76

**Comment by HelloKerem** [comment]
![resim](https://github.com/Fabricators-of-Create/Create/assets/98821815/17763452-0ab3-4e8b-8b5d-5786f98c2525)

**Comment by HelloKerem** [comment]
![resim](https://github.com/Fabricators-of-Create/Create/assets/98821815/9dab8ae2-99f4-479c-b72f-4f8068fcb4c4)

**Comment by HelloKerem** [comment]
wut-
![resim](https://github.com/Fabricators-of-Create/Create/assets/98821815/890f5d93-5909-47a5-8136-246eddf60cae)
