### ISSUE TITLE
Broken schematic files are not handled properly

### ISSUE THREAD

**Issue by goteusz-maszyk** [Fabricators-of-Create/Create#1298]
### Describe the Bug

When a player uploads a schematic, it should be checked if it's a correct ZIP-NBT schematic and not throw the error to console.

### Reproduction Steps

1. Make a broken schematic file, such as one provided below
2. Upload it to create server
3. See that the server logs go crazy with a `java.util.zip.ZipException: Not in GZIP format`

### Expected Result

A player should receive a polite message informing that the schematic file is invalid and they cannot use it.

### Screenshots and Videos

[huh.nbt.zip](https://github.com/Fabricators-of-Create/Create/files/14169970/huh.nbt.zip)

### Operating System

Nobara 39

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by goteusz-maszyk** [comment]
NOTE: it also happens on forge, should I send it to Creators-of-Create/Create or is it ok here?

**Comment by TropheusJ** [comment]
report to the forge repo

**Comment by TropheusJ** [comment]
Issues that occur on Forge as well are no longer being tracked on this repo. Please follow the respective issue on the Forge repo instead: https://github.com/Creators-of-Create/Create/issues/6087
