### ISSUE TITLE
the internal shader crashes (I apologize for the possibly incorrect translation)

### ISSUE THREAD

**Issue by Tapok0** [Fabricators-of-Create/Create#1299]
### Describe the Bug

Once again I apologize for the translation, the internal shader of the mod crashes the game

### Reproduction Steps

1. The game starts
2. The game almost loads and crashes

### Expected Result

The bar should reach the end and the game menu will appear

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.18.2

### Other Mods

<img width="444" alt="Снимок экрана 2024-02-06 114232" src="https://github.com/Fabricators-of-Create/Create/assets/159102740/3315aae3-9757-491d-8dcc-cceeac40a441">
<img width="589" alt="image" src="https://github.com/Fabricators-of-Create/Create/assets/159102740/870e876e-c938-465e-8a9f-88d3b011b637">

**Comment by drwoops** [comment]
downgrade fabric api 0.76

**Comment by IThundxr** [comment]
Non-issue can be closed
