### ISSUE TITLE
compileJava error

### ISSUE THREAD

**Issue by Just-Jasmine** [Fabricators-of-Create/Create#13]
## Describe the bug
Hello! I was wondering if you could help me with an issue I'm having building the project. I'm trying to build on pop os, and when I git clone and run "./gradlew build" in the terminal I get a compileJava error. I also experience this issue when trying to build the fabric version of Botania and some other mods. I understand that this is probably an issue on my end, probably with java version, but I am very unfamiliar with gradle and would appreciate some help.

## To Reproduce
1. git clone the repo
2. "./gradlew build"'
3. experience the compileJava error

## Expected behavior
A built create fabric mod

## Screenshots
No screenshots, but I can give you a paste bin of the output:
https://pastebin.com/dRq9dRj0

If you need any more information I would be happy to help, thank you in advance.

**Comment by YTG1234** [comment]
This project does not compile currently. We have not yet finished porting all of the files.

**Comment by Just-Jasmine** [comment]
Oh, Okay! I was just really exited to see how far the project has come. Thank you so much for all of the hard work you do! I don't know if this is relevant, but if you'd like to teach me how to work on this project I would be happy to contribute.

**Comment by smellypengu** [comment]
For some reason this wasn't closed
