### ISSUE TITLE
Sodium Crashes on World Startup

### ISSUE THREAD

**Issue by ghost** [Fabricators-of-Create/Create#130]
### Describe the Bug

If I have sodium & iris installed, it lets me launch, but as soon as I open a world or server it immediately crashes.

### Reproduction Steps

1. Install create + sodium + iris
2. Run game
3. Open world

### Expected Result

Immediate crash

### Crash Report or Log

https://pastebin.com/KqWKmN48

### Operating System

EndeavorOS Linux

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

Fabric API

**Comment by TropheusJ** [comment]
this will be fixed with the next flywheel update
