### ISSUE TITLE
Hand Crank retains stress capacity after config change

### ISSUE THREAD

**Issue by Epicificator** [Fabricators-of-Create/Create#1300]
### Describe the Bug

If a hand crank is being cranked while the server config value for hand crank stress capacity is changed, then the hand crank will continue to carry the same stress capacity as before the config change, until it has stopped being cranked.

### Reproduction Steps

1.have another player or a deployer crank a hand crank
2. go to config and change stress capacity for hand crank
3. the hand crank will carry the same stress capacity as before the config change, until it has stopped being cranked.
...

### Expected Result

i expected the hand crank to change stress capacity once config was changed, even if it continues to be cranked.

### Screenshots and Videos

https://youtu.be/NjR8AvzBANs

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/143143550/fe767399-dc86-4f1d-90f6-7e5b7f63d9e9)

**Comment by IThundxr** [comment]
Does this affect forge aswell? if yes report to the forge repo

**Comment by Epicificator** [comment]
Yes, just tested, it also affects forge. i will make bug report now

**Comment by TropheusJ** [comment]
Highly doubt it would be fixed, it's so minor and would need significant changes.
