### ISSUE TITLE
Conflicts with Compact Machines

### ISSUE THREAD

**Issue by mohamad4444** [Fabricators-of-Create/Create#1305]
### Describe the Bug

this is the log https://mclo.gs/KBiwyn3

### Reproduction Steps

1. install mods in log
2. hit run

### Expected Result

for minecraft not to crash

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.19.2

**Comment by drwoops** [comment]
start by downgrading fabric api to 0.76

**Comment by mohamad4444** [comment]
> start by downgrading fabric api to 0.76

same issue, i hope u didn't come here only to mention that

**Comment by denys-duchier** [comment]
post the new crash report

**Comment by mohamad4444** [comment]
> post the new crash report

troll pls

**Comment by drwoops** [comment]
my friend, if you do not cooperate when we try to help you, your issue will simply go ignored

**Comment by mohamad4444** [comment]
> my friend, if you do not cooperate when we try to help you, your issue will simply go ignored

i found out what the issue is about it is about porting lib, which i think compact machines uses an old port of it and compact machines need to be updated if i am not mistaken, the troll asked for a new cash report after i already edited it and provided a new one with only 3 mods namely fabric api 0.76 , compact machines and create. also before u mentioned fabric api 0.76 it was already tested with that api and i received same error. because i read other issues before i posted this one and the api was irrelevant here.

**Comment by drwoops** [comment]
hephaestus has the same issue. you need to understand that fabric api 0.76 is the 1 version that is known to work fpr 1.19.2. anything above is known to eventually cause crashes.  there is no point in trying to debug something when in the mix there is a version known to cause issues. hence the request to downgrade fabric api and post the new crash report.

**Comment by drwoops** [comment]
if your pb is resolved, please consider closing this issue.
