### ISSUE TITLE
farmers delight backstabbing bug

### ISSUE THREAD

**Issue by dark-enigma** [Fabricators-of-Create/Create#1309]
### Describe the Bug

backstabbing normally amplifies the damage in your offhand when you hold the knife in your main hand but when the create mod is added it no longer does this

### Reproduction Steps

1.get a backstabbing knife in your main hand
2. get a bow in your offhand
3. fire arrow at the back of a mob
4. with create mod it does around 20-30 hp to iron golem (maxed bow)
5. without create mod it does 50-60 hp to iron golem

### Expected Result

it would do around 1.5 -2x damage

### Operating System

windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

farmers delight 1.4.3
create 0.5.1-d-build.1161+mc1.20.1
fabric api 0.91.1+1.20.1

### Additional Context

https://github.com/newhoryzon/farmers-delight-fabric/issues/240

**Comment by drwoops** [comment]
1. please downgrade fabric api to 0.88.1
2. does this issue also occur on forge?

**Comment by dark-enigma** [comment]
this issue does not occur on forge 
on forge when the create mod is installed it still does the backstabbing with bow thing

**Comment by TropheusJ** [comment]
does this issue still occur with the [new port](https://modrinth.com/mod/farmers-delight-refabricated)?

**Comment by IThundxr** [comment]
If this isn't fixed by the new port open a new issue
