### ISSUE TITLE
[Iris] Miscellaneous Issues

### ISSUE THREAD

**Issue by PepperCode1** [Fabricators-of-Create/Create#131]
### Describe the Bug

- [x] The glowing sections of the wand of symmetry and worldshaper do not cast shadows and do not render when thrown on the ground.
- [x] Placement helpers render completely solid.
- [x] GL errors are spammed in the log if the shader is enabled.

### Reproduction Steps

Self-explanatory

### Expected Result

Self-explanatory

### Operating System

Windows 10

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

Iris 1.2.0 + BSL

**Comment by Specimen-420** [comment]
when ever i use iris the game straight up crashes when i place something from the create mod

**Comment by PepperCode1** [comment]
> when ever i use iris the game straight up crashes when i place something from the create mod

You need to set the backend engine to off either in the config file or in game but while Iris is not installed. This has been fixed by a recent Iris commit but is not present in a release version yet.

**Comment by Specimen-420** [comment]
> 

thank you, becuase im a bit dumb, do you mind giving me a guide as to how to turn the backend engine off?

**Comment by AlphaMode** [comment]
All issues are fixed as far as I am aware now
