### ISSUE TITLE
copycat_step placement error

### ISSUE THREAD

**Issue by henryyuyhy** [Fabricators-of-Create/Create#1310]
### Describe the Bug

![image](https://github.com/Fabricators-of-Create/Create/assets/109945282/3fd731fc-3362-4eba-9ddc-0e20b009279f)
Shown in the image, I tried to place a top-half copycat_step with placement assist but the game places an bottom-half one.

I think it is because the blockstate "half" is not included while placing with placement assist

### Reproduction Steps

1.Enter the game
2.place a top-half copycat_step
3.place another next to it using placement assist

### Expected Result

fix it

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/109945282/7707f6e6-f036-4c82-8e21-645ea4c6df48)

### Operating System

windows 11 (it doesn't matter)

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
Affects forge aswell, report to the forge repo

**Comment by TropheusJ** [comment]
Open an issue on the forge repo
