### ISSUE TITLE
Can not launch minecraft

### ISSUE THREAD

**Issue by baiyu-cs** [Fabricators-of-Create/Create#1313]
### Describe the Bug

I can not launch my minecraft when only installing this mod and fabric api
The crash report shows that there is a java.lang.NullPointerException at com.simibubi.create.infrastructure.gui.OpenCreateMenuButton.method

### Reproduction Steps

1. install minecraft 1.19.2 and fabric 0.15.6
2. install create-fabric-0.5.1-c-build.1160+mc1.19.2 and fabric-api-0.77.0+1.19.2
3. launch minecraft
4. get a crash report

### Expected Result

I expect I can see the minecraft main menu rather than crash report.
Thanks for your fixing.

### Screenshots and Videos

Please see the last line:
![图片](https://github.com/Fabricators-of-Create/Create/assets/52906833/eaab45b5-49de-47c7-8f22-e05a61ec05d1)

### Crash Report or Log

https://gist.github.com/baiyu-cs/4c3ee68e3fa08969238ff8996d147d6d

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

fabric-api-0.77.0+1.19.2
create-fabric-0.5.1-c-build.1160+mc1.19.2

**Comment by denys-duchier** [comment]
for your version, you need fabric api 0.76

**Comment by baiyu-cs** [comment]
thank you very much
