### ISSUE TITLE
Crash from invalid train

### ISSUE THREAD

**Issue by Recheezy** [Fabricators-of-Create/Create#1315]
### Describe the Bug

a specific train in my world crashes my game when it tries to render

### Reproduction Steps

I'm not sure, I just went into render distance of one of my trains I had parked at a station, none of my other trains did this at all even though I've parked them at the same spot before, and I also have other trains twice the size parked in other spots, none of them crash me

### Expected Result

a crash saying "Unable to get Y-rotated facing of down" 

### Crash Report or Log

https://pastebin.com/S6vevR7B

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods
I can add screenshots of the modlist but  I added create into a modpack I had that had 0 issues before I added it so I don't think anything is affecting this glitch since it's only happening when it tries to render the train

**Comment by Recheezy** [comment]
Is there any temprary workaround? (other than avoiding that chunk entirely or restoring a backup of my world)

**Comment by TropheusJ** [comment]
You can delete the train with the `/create killTrain` command. Could you provide a world download first? This shouldn't be able to happen.

**Comment by Recheezy** [comment]
oh I already found a solution and fixed the issue by just replacing the "create_tracks.dat" file in the world files, and unfortunately I deleted that world backup to prevent my computer from running low on space lol, but if it ever happens again I'll let you know and send a world download!

**Comment by Recheezy** [comment]
OH also, I think what happened was that the train somehow tried to park at 2 separate stations at the same time, or something having to do with how my PC isn't that good tbh, I'm not sure if that'll help but I'll do what I can if the issue comes up again!

**Comment by TropheusJ** [comment]
going to close this then
