### ISSUE TITLE
[Patch F] Train Observer Crash 

### ISSUE THREAD

**Issue by JensenJ** [Fabricators-of-Create/Create#1316]
### Describe the Bug

Hi, I'm running the latest commit fb322c86b2f4074b241a0b5079f667ee7368ceec and I imported a singleplayer world from 0.5.1d to see if any crashes or issues occur. Noticed that when train observer saves it's NBT a crash occurs.

### Reproduction Steps

1. Place down train observer linked to track in singleplayer
2. Try to go to main menu to force world save.
3. Crash

### Expected Result

No crash

### Crash Report or Log

https://mclo.gs/qjjG4z9

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

It's the dev environment, so whatever was in that commit.

**Comment by IThundxr** [comment]
Probable cause is that FilterItem#test was replaced by with FilterItemStack#test

**Comment by IThundxr** [comment]
The issue is that it used to pass a ItemStack before and now it passes a FilterItemStack which doesn't extend ItemStack we should be able to use FilterItemStack.item() to which will fix this, will make a pr soon
