### ISSUE TITLE
[Patch F] getVersion() may not be called during transaction causing crash.

### ISSUE THREAD

**Issue by JensenJ** [Fabricators-of-Create/Create#1317]
### Describe the Bug

Hi, I'm running commit https://github.com/Fabricators-of-Create/Create/commit/fb322c86b2f4074b241a0b5079f667ee7368ceec and I imported a singleplayer world from 0.5.1d to see if any crashes or issues occur. It seems that some optimisations made in Patch E on Forge (0510ea3e20f0bfadf5df6100fddf57584d691ffe) when ported to Fabric cause a crash under certain circumstances. 

Note: I built the project and ran it in an instance with just sodium, indium and spark (versions down below) so I could measure the performance to make sure the optimisations work as this was causing issues in my world.

Thanks for the work you put into this great mod.

### Reproduction Steps

1. Place down single item vault block
2. Fill item vault
3. Try to put another stack into item vault via chute or funnel
4. Crash

### Expected Result

No crash and for the optimisations made on Forge to still work on Fabric.

### Crash Report or Log

https://mclo.gs/nvCl8Uw

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.18.2

### Other Mods

Tried to match dev environment as closely as possible.
Fabric API 0.77.0
indium 1.0.7
Sodium 1.18.2-0.4.1
Spark 1.10.39

**Comment by JensenJ** [comment]
Hey there, I saw the PR you did, just tried it out, crash seems to be solved for downwards output from chutes into vaults, but further testing has shown the crash also happens for when you push items upwards from below into an item vault using an encased fan. https://mclo.gs/WPh9rkz

I appreciate the fast response on these. Thanks.

**Comment by IThundxr** [comment]
Fixed both issues, open another issue if it happens elsewhere
