### ISSUE TITLE
Immediate crash when placing a shaft in singleplayer

### ISSUE THREAD

**Issue by Tempest-5ky** [Fabricators-of-Create/Create#132]
### Describe the Bug

Placing a shaft in single player with Iris, indium, and sodium installed causes an immediate crash.

### Reproduction Steps

1. Load minecraft with the latest versions of Iris, Indium, Sodium, and the fabric API for 1.18.1
2. Create a new world.
3. Place a shaft.
...

### Expected Result

No crash occurs, gameplay can progress as normal.

### Crash Report or Log

https://pastebin.com/PN6swYx8

### Operating System

Windows 10

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

Sodium, Iris, Indium

**Comment by PepperCode1** [comment]
This is a Flywheel and Iris incompatibility. It will be fixed with Iris 1.2.1; for now, you can disable the backend manually.

**Comment by Tempest-5ky** [comment]
Thanks! Appreciated.
You're doing amazing work here, very excited to see the finished product.
