### ISSUE TITLE
1.20.1 Sodium Crash

### ISSUE THREAD

**Issue by Tyquelynn** [Fabricators-of-Create/Create#1320]
### Describe the Bug

The game crashed when I launched. It crashed because of a incompatibility with Sodium.

### Reproduction Steps

1. Install Create 1.20.1 v0.5.1.d
2. Install Sodium 0.5.8+mc1.20.1
3. Launch Mincraft

### Expected Result

No crash and improved performance.

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
https://github.com/Fabricators-of-Create/Create/issues/1110
