### ISSUE TITLE
[Crash]incompatible with Fabric API 0.77.0 on MC 1.19.2

### ISSUE THREAD

**Issue by SakuraRK** [Fabricators-of-Create/Create#1323]
### Describe the Bug

When install Fabric API 0.77.0 on MC 1.19.2, Will crash the game on initialization. Sometimes will infinity reload the resources pack make the Mojang logo show again and again.

### Reproduction Steps

1.Install the Fabric API 0.77.0, and Create on MC 1.19.2
2.Run the game.
3.Get the crash.

### Expected Result

Just crash

### Crash Report or Log

https://1drv.ms/t/s!ArjD7tewRXSbvnSWrUzx8VE1tN7M?e=bDFyZA

### Operating System

Windows 11 专业版(Pro version) Insider Preview 22H2

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/95642715/64305426-c126-40c5-b79a-63929556a89d)

**Comment by drwoops** [comment]
downgrade fabric api to 0.76

**Comment by TropheusJ** [comment]
already fixed in dev versions
