### ISSUE TITLE
chocolate bucket is now gone

### ISSUE THREAD

**Issue by magplayzreal** [Fabricators-of-Create/Create#1325]
### Describe the Suggestion

Add the chocolate bucket back since my chocolate factory doesn't work now

**Comment by IThundxr** [comment]
Chocolate hasnt been removed, please next time use the bug report template. Next time do atleast the bare minimum of using the bug report template and adding some more info.

**Comment by magplayzreal** [comment]
I was talking about the bucket of chocolate I know chocolate hasn't been removed its the bucket of liquid chocolate
![download](https://github.com/Fabricators-of-Create/Create/assets/160409276/a0d1d746-a4e5-499f-b7be-f99cee9b8f35)

**Comment by magplayzreal** [comment]
![image](https://github.com/Fabricators-of-Create/Create/assets/160409276/4af0d6e4-4f4d-4f9c-bdf5-4b5a046b4944)

**Comment by IThundxr** [comment]
It hasn't been removed like I've said, try /giving it to yourself

**Comment by magplayzreal** [comment]
do you mind showing a screenshot because i can not find it

**Comment by magplayzreal** [comment]
thanks
