### ISSUE TITLE
Moving Contraptions Delete Items from On-Board Storage

### ISSUE THREAD

**Issue by Stereo528** [Fabricators-of-Create/Create#133]
### Describe the Bug

Moving a contraption with an inventory on it replaces the first instance of the item with the last instance of the item.

I'm also getting confused because it's done 3 different things now. The first time I noticed it, it was copying the last to the first, I wasn't using different tree types at the time yet and I hadn't realized it was deleting items. Later, maybe 5 minutes, before I was aware this was happening still, it deleted the first instance of the item until I went from 3 stacks + 2 of an item to only 2 of an item, I was using a different tree type at this point. After this, I tried to replicate it again, and it did nothing, tried multiple times, I switched tree type and it happened, but it again copied the last to the first.

While trying to figure this out and write this issue, I kept testing to see what I could do to replicate it. If I just place items in without it harvesting it, it seems it will *always* delete the last instance of the item and leave the first one be, no matter the size, it will also move everything to the uppermost left slot it can (this happened while harvesting it too, which is why I didn't realize it at first)

### Reproduction Steps

The below steps are before I wrote the "Describe the Bug" portion, though it will get the original behavior I noticed, I can follow up with what I did for the other behaviors I found later on.

1. Create a contraption like this:
![image](https://user-images.githubusercontent.com/52116771/152896004-1c4448a9-ea1c-4ba0-85e5-d1f4d1c1a931.png)

2. Plant and grow 1 type of tree, for example, Oak
3. Harvest it with the contraption, Example harvest: 
![image](https://user-images.githubusercontent.com/52116771/152896173-84cf8ab4-2216-4c52-833b-fad6d39932b8.png)

4. (Optional) Take everything out except 1 type of item, for example, 3 apples like this:
![image](https://user-images.githubusercontent.com/52116771/152896574-89a32ac0-3377-4825-8de5-c603d826bfa5.png)

4. Plant another tree type like Spruce
5. Harvest it with the contraption
6. Watch as you now have 2 apples instead of 3:
![image](https://user-images.githubusercontent.com/52116771/152896631-272989b1-d277-4293-bb75-75d1dbb86e11.png)

More Extreme example:
![image](https://user-images.githubusercontent.com/52116771/152896666-9ceb9ce7-bbe7-4bed-a63b-420ca8b73369.png)
![image](https://user-images.githubusercontent.com/52116771/152896671-de62e9c3-3188-4477-8d00-9c476d069dd8.png)

Also happens with multiple types of items: (I had forgotten to take a before picture, but 46 sticks were also lost in the process, they were after the 8 sticks, and I believe I had the 2 spruce amounts switched than what they should be in the "before" photo)
![image](https://user-images.githubusercontent.com/52116771/152897272-e8213fba-9077-49e0-bc03-e50563bb9587.png)
![image](https://user-images.githubusercontent.com/52116771/152897161-b726c438-f0a5-4cdb-a7a4-b20597942f60.png)

### Expected Result

Items are not cleared/copied from the last in the list of the same item types, to the first of the same list (happens with multiple items), instead of everything being left as is in the storage.

### Operating System

Linux, Pop!_OS

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

Applied Energistics 2
Consistency+
Bing Bing Wahoo,
Krypton,
Starlight,
Decorative Blocks,
Xaero's Minimap + Worldmap

### Additional Context

This happens in Multiplayer, will update when I test Singleplayer

This also is not my server, I'm unable to test if it happens without krypton, starlight, or without both if it is a multiplayer-only issue.

**Comment by Stereo528** [comment]
Forgot to mention I believe, It will happen if it just moves, even if its half a block before coming back, it doesn't have to harvest anything for this too happen

**Comment by TropheusJ** [comment]
better example
before:
![image](https://user-images.githubusercontent.com/60247969/152908465-01e015f9-5b3f-4b5c-8ef2-499a81258ab4.png)
after:
![image](https://user-images.githubusercontent.com/60247969/152908485-57d56602-336a-4a5c-85c3-a96e7cf69be0.png)
