### ISSUE TITLE
Potato cannon

### ISSUE THREAD

**Issue by Da1Da2** [Fabricators-of-Create/Create#1334]
### Describe the Bug

The problem is that when you shoot potatoes or other food, you can't see potatoes or food flying in the air, because of this it's not convenient to use potato cannon

### Reproduction Steps

I launched only the mod itself and its dependencies (fabric api), launched minecraft without resource packs, created a new world, took a potato cannon and potatoes, fired a shot, but it is not visible how the potato flies out, it is invisible

### Expected Result

It was expected that the potato would be visible when fired from the potato cannon

### Operating System

Windows 7

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

fabric api 0.91.0

**Comment by opee2012** [comment]
I can confirm this issue. Wanted to take down the ender dragon with potato cannon. Can't see the projectiles at all. Using version D.

**Comment by IThundxr** [comment]
can reproduce on dev branches
