### ISSUE TITLE
Crash on 1.19.2 because of incorrect path to shader

### ISSUE THREAD

**Issue by star-host** [Fabricators-of-Create/Create#1336]
### Describe the Bug

`Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: create:create:shaders/core/glowing_shader.vsh`

### Reproduction Steps

1. Downloaded Create 0.5.1c for Minecraft 1.19.2 from Modrinth
2. Launched Minecraft

### Expected Result

game launching without crashing

### Crash Report or Log

https://pastebin.com/K86EG0B8

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

**Comment by drwoops** [comment]
downgrade fabric api to 0.76

**Comment by star-host** [comment]
forgot to reply; can confirm it fixed the issue
