### ISSUE TITLE
[Crash] Place a Train Track on a Nether portal |   java.lang.ClassCastException at AllPortalTracks.getTeleporter()

### ISSUE THREAD

**Issue by fabien-gigante** [Fabricators-of-Create/Create#1337]
### Describe the Bug

Instant game crash when placing a train track on a nether portal.

Exception:
```
java.lang.ClassCastException: class net.minecraft.class_1946 cannot be cast to class
	io.github.fabricators_of_create.porting_lib.entity.ITeleporter (net.minecraft.class_1946 and
	io.github.fabricators_of_create.porting_lib.entity.ITeleporter are in unnamed module of loader 
	net.fabricmc.loader.impl.launch.knot.KnotClassLoader @26be92ad)
```
Stack trace :
```
	at com.simibubi.create.content.trains.track.AllPortalTracks.getTeleporter(AllPortalTracks.java:88)
	at com.simibubi.create.content.trains.track.AllPortalTracks.standardPortalProvider(AllPortalTracks.java:105)
	at com.simibubi.create.content.trains.track.AllPortalTracks.nether(AllPortalTracks.java:69)
	at com.simibubi.create.content.trains.track.AllPortalTracks.getOtherSide(AllPortalTracks.java:57)
	at com.simibubi.create.content.trains.track.TrackBlock.connectToPortal(TrackBlock.java:239)
```

[crash-2024-02-25_16.11.56-server.txt](https://github.com/Fabricators-of-Create/Create/files/14396786/crash-2024-02-25_16.11.56-server.txt)

### Reproduction Steps

1. Create and light up a Nether portal
2. Enter and exit Nether (to make sure that the other side is generated)
3. Place train tracks through the portal
4. Observe crash

### Expected Result

Should not crash, and allow cross-dimensions train travel.

### Screenshots and Videos

![2024-02-25_16 11 29](https://github.com/Fabricators-of-Create/Create/assets/21187022/503d998b-5175-4465-b875-e60227444466)

### Crash Report or Log

https://github.com/Fabricators-of-Create/Create/files/14396786/crash-2024-02-25_16.11.56-server.txt

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

See crash report for complete list. But not likely related to other mods.

### Additional Context

Specific to 0.5.1f, not reproduced using 0.5.1d.
Using specifically _create-fabric-0.5.1-f-build.1287+mc1.20.1.jar_

**Comment by IThundxr** [comment]
fixed in #1338

**Comment by fabien-gigante** [comment]
Crash still happening on build 1291...

**Comment by fabien-gigante** [comment]
Shouldn't this issue be reopened ?

According to @TropheusJ in #1338 :  "Porting lib is missing a mixin"
Do you need a distinct issue to be opened in Porting lib itself to track this problem ?

**Comment by IThundxr** [comment]
> Shouldn't this issue be reopened ?
> 
> According to @TropheusJ in #1338 : "Porting lib is missing a mixin" Do you need a distinct issue to be opened in Porting lib itself to track this problem ?

Nah it's fine, they'll handle it in porting lib soon
