### ISSUE TITLE
Mechanical mixer

### ISSUE THREAD

**Issue by Da1Da2** [Fabricators-of-Create/Create#1341]
### Describe the Bug

I will try to describe the problem correctly, if, for example, put zinc and copper in a basin to produce brass and connect a mixer, and start twisting it, animation will begin, and if you stop and do not twist, then the mixer will stop, but the animation in the basin will that is, resources will continue to rotate in the basin and particles will fly out outside, the sounds will not disappear either, but the mixer does not work, I hope everything is clearly explained.
It also works without extraneous mods and without resource packs.

### Reproduction Steps

1.Create a new world
2.Install a basin and mixer above it
3.Connect a small gear to the mixer and connect the handle to it
4.Put any objects that can be mixed in the basin (for example, zinc and copper)
5.Start turning the handle, and wait the mixer drops into the basin and starts spinning, then stop immediately
6.You will see how objects continue to spin in the basin, releasing particles and making sounds

### Expected Result

It was expected that when the player stops turning the handle, the objects in the basin will stop spinning, releasing particles

### Operating System

Windows 7

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

create
fabric api 0.91.0

**Comment by IThundxr** [comment]
Occurs on forge aswell, report to the forge repo please.
