### ISSUE TITLE
cant find a vers of fabric create  that supports 1.20.1 sodium 0.5.2

### ISSUE THREAD

**Issue by Voidtfz** [Fabricators-of-Create/Create#1343]
### Describe the Bug

Some of your mods are incompatible with the game or each other!

### Reproduction Steps

download mods. setup minecraft - mods. start minecraft. cry...
![image](https://github.com/Fabricators-of-Create/Create/assets/160957638/d11bb321-bc89-4219-9408-b361620de4b0)

### Expected Result

minecraft starts

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/160957638/c372ea1a-9a62-4cbb-82a4-0b233bfbee72)

### Crash Report or Log

[latest.log](https://github.com/Fabricators-of-Create/Create/files/14424184/latest.log)

### Operating System

windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/160957638/2e98a0d0-693b-4695-aeb3-1e44c716abe4)

**Comment by drwoops** [comment]
currently create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 and indium 1.0.21 are the precise versions you want.

an update is in the works

**Comment by Voidtfz** [comment]
> 0.88.

I just want to play with create + addons and sodium - iris, sheiders. on 1.20.1

**Comment by IThundxr** [comment]
Use the versions drwoops mentioned

**Comment by drwoops** [comment]
well these versions will let you do so. don't forget to also install iris flywheel compat. please consider closing this issue.
