### ISSUE TITLE
Crash with BetterClouds

### ISSUE THREAD

**Issue by Maxfoxes** [Fabricators-of-Create/Create#1344]
### Describe the Bug

The game world-generation process was halted and crashed due to **[BetterClouds](https://modrinth.com/mod/better-clouds)**.
**[DashLoader](https://modrinth.com/mod/dashloader)** caused the game to fail to start.

### Reproduction Steps

1.Install DashLoader.jar and BetterClouds.jar into the mods file, then start the game.
2.Game Start Failed. Remove DashLoader.jar, restart the game, then log in.
3.Create a new world, process it, then world will be auto saved and crashed.
4.Remove BetterClouds.jar and log into the world.

### Expected Result

Mod incompatible crashing error.

### Crash Report or Log

Sorry for that, I clean them all, but Dashloader and BetterClouds are the main issue.

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

	- ad_astra 1.15.18
	   \-- javazoom_jlayer 1.0.1
	- adaptive-tooltips 1.3.0
	- advancedcompass 1.2.15
	- appleskin 2.5.1+mc1.20
	- architectury 9.2.14
	- armorskin 0.2
	- athena 3.1.1
	- attributefix 21.0.4
	- badpackets 0.4.3
	- balm-fabric 7.2.2
	- bettercombat 1.8.4+1.20.1
	- betterf3 7.0.2
	- bettermounthud 1.2.2
	- betterpingdisplay 1.1.1
	- betterthanmending 1.3.0
	- betterthirdperson 1.9.0
	- bookshelf 20.1.9
	- botarium 2.3.3
	   \-- team_reborn_energy 3.0.0
	- cardinal-components 5.2.2
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- carryon 2.1.2.7
	- chat_heads 0.10.31
	- chatpatches 201.5.5
	- cherishedworlds 6.1.5+1.20.1
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- clumps 12.0.0.3
	- combatroll 1.3.1+1.20.1
	- controlling 12.0.2
	- create 0.5.1-d-build.1161+mc1.20.1
	   |-- com_electronwill_night-config_core 3.6.3
	   |-- com_electronwill_night-config_toml 3.6.3
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.9-1
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_accessors 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_base 2.1.1127+1.20
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    |-- porting_lib_lazy_registration 2.1.1127+1.20
	   |    \-- porting_lib_utility 2.1.1127+1.20
	   |-- porting_lib_brewing 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_client_events 2.1.1127+1.20
	   |    |-- mm 2.3
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_entity 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_mixin_extensions 2.1.1127+1.20
	   |-- porting_lib_extensions 2.1.1127+1.20
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_fake_players 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_models 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_model_loader 2.1.1127+1.20
	   |-- porting_lib_networking 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_obj_loader 2.1.1127+1.20
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_model_loader 2.1.1127+1.20
	   |-- porting_lib_tags 3.0
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_tool_actions 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_transfer 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        |-- porting_lib_data 2.1.1090+1.20
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- cupboard 1.20.1-2.3
	- disable_custom_worlds_advice 4.1
	- dynamic_fps 3.3.2
	- enchantment-reveal 1.0.0
	- enchdesc 17.0.14
	- entityculling 1.6.2-mc1.20.1
	- equipmentcompare 1.3.8
	- experiencebugfix 2
	- fabric-api 0.88.1+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.2.2+1e61dba177
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.10+23d9108177
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
	   |-- fabric-message-api-v1 5.1.7+3265161977
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.4.3+6bdb2ed077
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.1+195226a777
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabric-language-kotlin 1.10.18+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- fastitems 1.0.0
	- fastpaintings 1.20-1.2.4
	- ferritecore 6.0.1
	- forgeconfigapiport 8.0.0
	- gpumemleakfix 1.20.1-1.8
	- grindenchantments 3.1.2+1.20
	   \-- codec-config-api 1.0.2+1.19.3
	- hardcorerevival 12.0.2
	- highlighter 1.1.9
	- i18nupdatemod 3.5.3
	- iceberg 1.1.18
	- immediatelyfast 1.2.10+1.20.4
	   \-- net_lenni0451_reflect 1.3.2
	- indium 1.0.30+mc1.20.4
	- ingameime 1.0.7-1.20.1
	- inventorymanagement 1.3.1
	- iris 1.6.17
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- irisflw 0.2.4
	- itemframesplus 1.1.0
	- java 17
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- languagereload 1.5.10+1.20.1
	- lazydfu 0.1.3
	- lithium 0.11.2
	- logbegone 1.0.8
	- maxhealthfix 12.0.2
	- memoryleakfix 1.1.5
	- midnightlib 1.4.1
	- minecraft 1.20.1
	- mixin-conflict-helper 1.2.0
	- modmenu 7.2.2
	   \-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	- moonlight 1.20-2.10.8
	- moreculling 1.20.4-0.22.1
	   |-- conditional-mixin 0.3.2
	   \-- mixinsquared 0.1.1
	- mousetweaks 2.25
	- nerb 0.3
	- no-resource-pack-warnings 1.3.0
	- noisium 1.0.2+mc1.20.x
	- notenoughanimations 1.7.1
	- patchouli 1.20.1-84-FABRIC
	   \-- fiber 0.23.0-2
	- player-animator 1.0.2-rc1+1.20
	- puzzleslib 8.1.17
	   \-- puzzlesaccessapi 8.0.7
	- reeses-sodium-options 1.7.2+mc1.20.1-build.101
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.23
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- roughlyenoughitems 12.0.684
	   \-- error_notifier 1.0.9
	- ruined_equipment 2.3.1
	- savemod 1.4.4
	- searchables 1.0.2
	- serverpingerfixer 1.0.4
	- shut_up_gl_error 1.0.0
	- skinlayers3d 1.6.2
	- smoothchunk 1.20.1-3.6
	- smoothparticles 1.2.0-1.21
	- smoothscroll 1.8.1
	- smoothscrollingrefurbished 1.1.2
	- smoothskies 1.1.0
	- smoothswapping 0.9.3.1
	- sodium 0.5.8+mc1.20.1
	- sodium-extra 0.5.4+mc1.20.1-build.115
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- spark 1.10.53
	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
	- spawnanimations 1.9.4+mod
	- status-effect-bars 1.0.3
	- taxfreelevels 1.3.9
	- threadtweak 1.20.2-0.1.1
	- travelersbackpack 1.20.1-9.1.9
	- universalenchants 8.0.0
	   \-- extensibleenums 7.0.1
	- videotape 1.2.1
	   \-- com_github_krlite_pierced v1.2
	- world-days 1.0
	- wthit 8.7.2
	- yet_another_config_lib_v3 3.2.2+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1

**Comment by IThundxr** [comment]
Please reproduce this and attach latest.log and the crash log

**Comment by TropheusJ** [comment]
Dashloader is a known issue caused by Porting Lib. Send the crash report caused by better clouds.

**Comment by IThundxr** [comment]
It's been over 3 weeks without a response, Trying this myself i cannot reproduce this at all https://mclo.gs/8apy2mf. If this still occurs or you can reproduce it please open a new issue with the log attached.
