### ISSUE TITLE
A threshold switch broke my minecraft server

### ISSUE THREAD

**Issue by Ilyushya** [Fabricators-of-Create/Create#1345]
### Describe the Bug

I was making a pipeline to automatically fuel my furnaces, then I wanted to turn the pipeline off the last one is full. I placed a threshold switch by the end of my line of furnaces and then I am continuously receiving crashes. How can I recover my world?

### Reproduction Steps

1. Build a pipeline roll
2. Place a blast furnace
3. Place an item filter accepting items from the roll
4. Place a threshold switch near the furnace

### Expected Result

Obviously, to meter the furnace's capacity

### Crash Report or Log

https://gist.github.com/Intelliractive/4eb430123840a8dd404268e7771856f3

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

- badpackets
- cc tweaked
- create: enchantment industry
- create: new age
- newest fabric api
- botarium
- create cooking
- create: utilities
- fabric lang kotlin
- jei
- lucky blocks
- spawn
- wthit

![изображение](https://github.com/Fabricators-of-Create/Create/assets/98094811/ec9a5e42-e518-4796-98b9-fc8905383673)

**Comment by drwoops** [comment]
currently create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 and indium 1.0.21 are the precise versions you want.

**Comment by IThundxr** [comment]
Update create enchantment industry
