### ISSUE TITLE
Crash Minecraft Fabric 1.19.2

### ISSUE THREAD

**Issue by Arrobinha** [Fabricators-of-Create/Create#1347]
### Describe the Bug

The game left the Launcher and even loaded. But at the end of loading, the game crashes, returning to the launcher with the following message

The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$2" is null

The only mob that is giving this problem is Create Fabric 0.5.1c for version 1.19.2 of Minecraft

### Reproduction Steps

1. Mod installed in the folder
2. Launcher opens normally
3. Game starts to load but crashes

### Expected Result

The game was expected to open normally.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/161619881/6fb9f4a7-949c-41cc-b324-90f625797e79)

![image](https://github.com/Fabricators-of-Create/Create/assets/161619881/11baefe0-36cd-4115-a6c0-cf1a1f18d2fa)

### Crash Report or Log

[_Crash Report](https://pastebin.com/kKv0vp4Z)

### Operating System

Windows 11

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

There are around 220 mods (Libs included), they all work normally, the game only crashes when Fabric is added

**Comment by drwoops** [comment]
please attach the crash report

**Comment by Arrobinha** [comment]
> please attach the crash report

Crash Report Attached

**Comment by drwoops** [comment]
please downgrade fabric api to 0.76
