### ISSUE TITLE
Not sure if its a bug or me being stupid

### ISSUE THREAD

**Issue by HiroWu1** [Fabricators-of-Create/Create#135]
### Describe the Bug

Can't open latest create refabricated in minecraft even though having no other existing mods in the folder except for fabric api

### Reproduction Steps

1.Download Create
2.Put in mods folder
3.CRASH
...

### Expected Result

CRASH

### Crash Report or Log

https://pastebin.com/8hwSsydq

### Operating System

Windows 10

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

None

**Comment by TropheusJ** [comment]
Update fabric loader to 13.1
