### ISSUE TITLE
Issue with deployer's attack mode

### ISSUE THREAD

**Issue by Mynameismichael865** [Fabricators-of-Create/Create#1350]
### Describe the Bug

I'm playing on 1.20.1 with create fabric 0.5.1-d. I tried building an xp farm with skeletons and when the deployer kills the skeletons it just crashes my game. It says something about the inventory of the deployer and I can't figure out a fix.

### Reproduction Steps

1. Build a contraption that moves skeletons into a 1x1 area with a deployer facing the area.
2. Set deployer to attack mode with a chest with iron swords feeding the deployer.
3. Build a conveyer with a brass funnel to take loot out of deployer.
4. When a skeleton is killed the game crashes.
...

### Expected Result

I expected the loot and nuggets of xp from the skeletons to come out onto the belt when the skeletons are killed.

### Crash Report or Log

Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "capturedDrops" is null

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
Known issue, fixed in next version

**Comment by Mynameismichael865** [comment]
Is the next version out right now or is it coming out in a bit?
