### ISSUE TITLE
Game crash on startup (Quilt 1.19.2)

### ISSUE THREAD

**Issue by CabbageBaron** [Fabricators-of-Create/Create#1351]
### Describe the Bug

Game crashes upon loading screen. I'm using Prism Launcher.

### Reproduction Steps

1.Install Quilt and QFAPI
2.Install Create
3.Launch Minecraft

### Expected Result

Minecraft to start normally

### Crash Report or Log

https://gist.github.com/CabbageBaron/2eac4a3e8781aaf429c7dcd3300426e9

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
you need to use the QFAPI version equivalent to FAPI 0.76
