### ISSUE TITLE
sodium 5.0+ incompat

### ISSUE THREAD

**Issue by Embeiii** [Fabricators-of-Create/Create#1353]
### Describe the Bug

I physically cannot boot up my game with sodium 5.0 or higher installed, but if use 4.10 a ton of my other mods don't work, could you please update Create (fabric) so it allows sodium 5.0+?

### Reproduction Steps

1. install create and sodium 5.0 or higher
2. boot up minecraft
3. get en error screen
...

### Expected Result

Game actually boots up.

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 indium 1.0.21 are the exact versions you should use

**Comment by TropheusJ** [comment]
It's already fixed in the upcoming patch F

**Comment by Foul-Tarnished** [comment]
> create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 indium 1.0.21 are the exact versions you should use

why ? it's so old

with latest nightly of Distant Horizons + Sodium + Iris, the game is totally different
(512 chunks LOD, 12 real chunks, heavy shaders, +120fps)

**Comment by IThundxr** [comment]
> > create 0.5.1d sodium 0.4.10 fabric api 0.88.1 iris 1.6.4 indium 1.0.21 are the exact versions you should use
> 
> why ? it's so old
> 
> with latest nightly of Distant Horizons + Sodium + Iris, the game is totally different (512 chunks LOD, 12 real chunks, heavy shaders, +120fps on rtx4080)

As jay has said right above your comment,

> It's already fixed in the upcoming patch F

**Comment by Foul-Tarnished** [comment]
is the code here ? 1.20.1 dev branch ?

**Comment by IThundxr** [comment]
Yes, all current `/dev` branches have patch f changes merged in with the sodium incompatibility solved
