### ISSUE TITLE
Schematic preview visible after removing the schematic from inventory

### ISSUE THREAD

**Issue by Szedann** [Fabricators-of-Create/Create#1355]
### Describe the Bug

after positioning a schematic, it stays visible after removing it from the toolbar

### Reproduction Steps

1. Create a schematic
2. position it in the world
3. remove the schematic from your toolbar

### Expected Result

schematic preview disappearing after removing the schematic from the toolbar

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/65607498/81d05320-660f-4e56-8b70-a11528a46e6d

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

EMI
Mod Menu
Trinkets

**Comment by IThundxr** [comment]
pretty sure this occurs on forge aswell, can you check there aswell?

**Comment by Szedann** [comment]
oup, you're right. I was pretty sure it worked fine on forge but I must've misremembered.
