### ISSUE TITLE
Incompatible with "Show me Your Skin Mod"

### ISSUE THREAD

**Issue by pauliesnug** [Fabricators-of-Create/Create#1356]
### Describe the Bug

When using a Copper/Netherite back tank with the [Show Me Your Skin!](https://modrinth.com/mod/show-me-your-skin) mod, the opacity settings do not affect the visibility of the armor.

This bug was reported on the Show Me Your Skin! GitHub repository here: https://github.com/enjarai/show-me-your-skin/issues/47, but the author said that it was not an issue on their side and that Create armour bypassed traditional Fabric APIs.

### Reproduction Steps

1. Install Create Forge/Fabric on any version since custom Create armour was introduced
2. Install the Show Me Your Skin! mod
3. Try to adjust the opacity of the armour and of vanilla armour, the vanilla armour will work, the Create armour will not

### Expected Result

I expected the opacity of my custom create armour to change with the settings.

### Operating System

MacOS Sonoma 14

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

I was using Create Fabric Sodium Patch rather than normal Create Fabric, but it is still patch D, even on non-Sodium Patch because patch F and E have not been released.

**Comment by IThundxr** [comment]
Can you reproduce this with official create? We don't support unofficial forks here

**Comment by pauliesnug** [comment]
@IThundxr yes, i will test it with patch F ASAP, thank you for your quick response

**Comment by axd1x8a** [comment]
Issue still persists on the latest versions of both mods

**Comment by IThundxr** [comment]
not a issue on our side, Show me your skin has to fix this in their side

**Comment by squimbo** [comment]
"I've looked into Create armor rendering, but its very convoluted and seems to bypass standard Fabric API's. I don't think I'll be fixing this on my side. This issue will be left open to track any potential developments though."
- Show me your skin's creator
I think following the api would be better than having any other mod that affects armor rendering have to jump through hoops to be compatible.
