### ISSUE TITLE
There may be some strange errors during the descent of the rope pulley.

### ISSUE THREAD

**Issue by EmptyDreams** [Fabricators-of-Create/Create#1357]
### Describe the Bug

As shown in the video (The machine is running normally in the video), I designed an automatic mining machine. Normally, when it reaches the bottom, it will automatically return, and then move it through other devices and repeat the process.

https://github.com/Fabricators-of-Create/Create/assets/44894906/9605d330-65c8-4962-b2d6-a80bd16ecdbb

However, in some cases, the machine may continue to descend when there are still some "bedrock" in the next layer, and then materialize. This behavior causes some blocks of the machine to be replaced by "bedrock", thus paralyzing the whole machine.As shown in the figure below:

![91580274E4795D55685F0521FE653A6C](https://github.com/Fabricators-of-Create/Create/assets/44894906/fd2e7438-d2e8-4ed6-9cfb-e3704822d3fb)

I was not present when the error occurred, so I don't know what operation can trigger the bug under what circumstances.

### Reproduction Steps

1. Place several drills under one rope pulley
2. Use super glue to connect them together
3. Use some power sources to drive the rope pulley (I used wind power in the archive)
4. I'm not very clear about the remaining operations

### Expected Result

The rope pulley should stop after excavating to bedrock. (It should be that after excavating the current layer, it was stuck by the remaining bedrock. In the video, I placed a funnel on the side of the machine, so it stopped directly after encountering the bedrock layer.)

### Crash Report or Log

https://paste.ubuntu.com/p/KhXYgXxQVt/

### Operating System

windows10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

architectury-9.1.12
cloth-config-11.1.106
completeconfig-2.5.0
fabric-api-0.88.1
fabric-language-kotlin-1.10.17+kotlin.1.9.22
indium-1.0.21
libIPN-fabric-1.20-4.0.1
modmenu-7.2.2
player-animation-lib-fabric-1.0.2-rc1
yet-another-config-lib-fabric-3.2.1
CreateFabricREIBugFix-0.1.0-create0.5.1
explosive-enhancement-1.2.2
watut-fabric-1.20.1-1.0.12
journeymap-1.20.1-5.9.12
imblockerfabric-1.0.24
appleskin-fabric-mc1.20.1-2.5.1
bettercombat-fabric-1.8.3
BetterPingDisplay-Fabric-1.20.1-1.1.1
continuity-3.0.0-beta.4
InventoryProfilesNext-fabric-1.20-1.10.9
Jade-1.20-fabric-11.7.0
JadeAddons-1.20.1-fabric-5.2.3
RoughlyEnoughItems-12.0.684-fabric
Zoomify-2.11.2
create-fabric-0.5.1-d-build.1161
lanserverproperties-1.11.1
travelers-backpack-1.20.1-9.1.9
better-clouds-1.3.13
nicer-skies-1.3.0
bsvsb-3.0.3
reeses_sodium_options-1.6.3+mc1.20.1-build.92
sodium-extra-0.4.27+mc1.20.1-build.110
CustomSkinLoader_Fabric-14.19.1
Patchouli-1.20.1-84
trinkets-3.7.1
coroutil-fabric-1.20.1-1.3.5
enchlevel-langpatch-2.1.2
AdaptiveTooltips-1.3.0
Debugify-1.20.1+2.0
NoRealmsButton-1.0.1
enhancedblockentities-0.9
entityculling-fabric-1.6.2
exordium-fabric-1.2.1
letmedespawn-fabric-1.20.x-1.2.0
lithium-1.20.1-0.11.2
lunade-fastanim-1.6
memoryleakfix-fabric-1.17+-1.1.5
modernfix-fabric-5.11.1
nvidium-0.1.15-alpha
sodium-fabric-mc1.20-0.4.10+build.27
Botania-1.20.1-443

**Comment by IThundxr** [comment]
Report to the forge repo, this is a issue on forge aswell

**Comment by IThundxr** [comment]
Reported at https://github.com/Creators-of-Create/Create/issues/6215
