### ISSUE TITLE
Game Crashes when Initially Loading

### ISSUE THREAD

**Issue by Doolaidman** [Fabricators-of-Create/Create#1358]
### Describe the Bug

My game crashes when I go to load my game to play. It never gets passed the MOJANG loading screen. I have 125 projects in my instance on Modrinth so I haven't even tried to tackle disabling mods and re-enabling them to make it work. I did that far too many times to get this pack to load but now that I want to add create, I'd much rather get someone elses help. 

I'm also not sure at all how to reproduce this accurately without having the pack I made for myself, I can't figure out how to export it and drop it here. 

**In my mods list, which I hope is formatted correctly? I got rid of all the texture packs that were apart of the list, and kept the shaders. If I accidentally missed a texture pack I'm sorry, however I think I got them all.

### Reproduction Steps

1. Disable Create in my mods
2. Game loads the menu totally fine
3. Enable Create in my mods
4. Load game
...

### Expected Result

Game crashes before the menu screen can open.

### Crash Report or Log

https://mclo.gs/0n55nN7

### Operating System

Windows 11

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

Animal Feeding Trough
by Slexom
1.0.3+1.19.2

Animatica
by FoundationGames
0.5+1.19

AppleSkin
by squeek502
2.5.1+mc1.19.2

Architectury API
by
6.5.90+fabric

AttributeFix
by Darkhax
17.2.7

BCLib
by quiqueck
2.1.8

BSL Shaders
by CaptTatsu
8.2.08

Better Advancements
by way2muchnoise
0.3.0.148

Better Beds
by Motschen
1.2.0

Better Clouds
by qendolin
1.2.10+1.19.2-R

Better Compatibility Checker
by Gaz492
build.16+mc1.19.1

Better Mount HUD
by Lortseam
1.2.0

BetterEnd
by quiqueck
2.1.7

BetterNether
by quiqueck
7.1.5

Bookshelf
by Darkhax
16.3.20

CTM Refabricated
by CodexAdrian
1.0.1+1.19

Carry On
by Tschipp
2.1.1.22

Charm
by svenhjol
4.4.4+1.19.2

Charm of Undying
by TheIllusiveC4
6.2.1+1.19.2

Charmonium
by svenhjol
4.2.1+1.19.2

Chef's Delight
by redstonegamesb
1.0.3-fabric-1.19.2

Chipped
by Terrarium
2.1.5

ChoiceTheorem's Overhauled Village
by ChoiceTheorem
3.2.6

Cloth Config API
by shedaniel
8.3.115+fabric

Clumps
by jaredlll08
9.0.0+14

Clutter
by EmilSG
1.19.2-0.2.1

Comforts
by TheIllusiveC4
6.0.7+1.19.2

Complementary Shaders - Reimagined
by EminGT
r5.1.1

Continuity
by PepperCode1
2.0.2+1.19

CorgiLib
by CorgiTaco

Custom Entity Models
by dorianpb
0.7.3-1.19

Disable Enderman Picking Up Blocks
by Rain156
1.0

Dramatic Doors
by Kitteh6660
1.19.2-3.1.5

Dynamic FPS
by juliand665
3.3.3

Easy Anvils
by Fuzs
v4.0.11-1.19.2-Fabric

Ecologics
by samedifferent
2.1.11

Elytra Slot
by TheIllusiveC4
6.1.1+1.19.2

Enchantment Descriptions
by Darkhax
13.0.14

Entity Culling
by tr7zw
1.6.1-mc1.19.2

Every Compat (Wood Good)
by MehVahdJukaar
1.19.2-2.5.17

Expanded Delight
by ianm1647
0.2.5

Fabric API
by modmuss50
0.77.0+1.19.2

Fabric Language Kotlin
by modmuss50
1.10.17+kotlin.1.9.22

Fabric Waystones
by LordDeatHunter
3.0.8+MC1.19.2

Farmer's Delight [Fabric]
by Zifiv
1.3.10.2

FerriteCore
by malte0811
5.0.3-fabric

Forge Config API Port
by Fuzs
4.2.11

Freecam (Modrinth Edition)
by hashalite
1.2.3+1.19.2

Gamma Utils (Fullbright)
by Sjouwer
1.6.10

Geckolib
by Gecko
3.1.40

Indium
by comp500
1.0.9+mc1.19.2

Inmis
by draylar
2.7.1+1.19

Inventory Profiles Next
by blackd
fabric-1.19.2-1.10.9

Iris Shaders
by coderbot
1.6.11+1.19.2

Jade 🔍
by Snownee
8.7.3

JamLib
by jamalam
0.6.1+1.19-1.19.2

LambDynamicLights
by LambdAurora
2.2.0+1.19.2

LazyDFU
by astei
0.1.3

Litematica
0.12.7

Lithium
by jellysquid3
mc1.19.2-0.11.1

MaLiLib
by masa
0.13.0

Macaw's Bridges
by sketchmacaw
2.1.0

Macaw's Doors
by sketchmacaw
1.1.0

Macaw's Fences and Walls
by sketchmacaw
1.1.0

Macaw's Furniture
by sketchmacaw
3.2.2

Macaw's Trapdoors
by sketchmacaw
1.1.2

Memory Leak Fix
by FX
v1.1.5

MidnightLib
by Motschen
1.0.0-fabric

Mod Menu
by
4.2.0-beta.2

Model Gap Fix
by MehVahdJukaar
1.8

Moonlight Lib
by MehVahdJukaar
1.19.2-2.3.5

More Culling
by FX
v0.17.0-1.19

Nature's Compass
by Chaosyr
1.19.2-2.1.0-fabric

Not Enough Trinket Slots (NETS)
by CookieGD
0.3.5.2

Oh The Biomes You'll Go
by AOCAWOL
1.19.2-2.0.1.6-fabric

Polymorph
by TheIllusiveC4
0.46.5+1.19.2

Puzzles Lib
by Fuzs
v4.4.3-1.19.2-Fabric

Reese's Sodium Options
by FlashyReese
mc1.19.2-1.6.4

Resourceful Lib
by
1.1.24

RightClickHarvest
by jamalam
3.2.3+1.19.x-1.20.1-fabric

Roughly Enough Items (REI)
by shedaniel
9.1.682+fabric

Shearable Vines
by Roundaround
1.0.0+1.19

Shulker Box Tooltip
by MisterPeModder
3.2.2+1.19.2-fabric

Simple Fog Control
by Draradech
v1.3.1

Smarter Farmers (farmers replant)
by MehVahdJukaar
13

Sodium
by jellysquid3
mc1.19.2-0.4.4

Sodium Extra
by FlashyReese
mc1.19.2-0.4.16

Sound Physics Remastered
by henkelmax
fabric-1.19.2-1.3.1

Spawners+
by NathanTheCraziest
3.0-1.19.2

Starlight (Fabric)
by spottedleaf
1.1.1+1.19

Supplementaries
by MehVahdJukaar
1.19.2-2.4.19

TerraBlender
by Adubbz
2.0.1.166

The Bumblezone - Quilt/Fabric
by TelepathicGrunt
6.9.6+1.19.2+fabric

Tom's Simple Storage Mod
by tom5454
1.19-1.5.9-fabric

Tool Stats
by Darkhax
12.1.5

ToolTipFix
by kyrptonaught
1.1.0-1.19

Trinkets
by Emi
3.4.2

Twigs
by Ninni
3.0.0

Vein Mining
by TheIllusiveC4
1.1.3+1.19.2

WorldEdit
7.2.12+6240-87f4ae1

Xaero's Minimap
by thexaero
23.9.7_Fabric_1.19.1

Xaero's World Map
by thexaero
1.37.8_Fabric_1.19.1

YetAnotherConfigLib
by isxander
2.2.0-for-1.19.2

You're in Grave Danger
by b1n-ry
1.4.9

Zoomify
by isxander
2.9.0

libIPN
by blackd
fabric-1.19.2-4.0.1

oωo (owo-lib)
by
0.9.3+1.19

**Comment by TropheusJ** [comment]
use fabric api 0.76 for now
