### ISSUE TITLE
create (beta 0.5.1) fabric 1.20.1 doesn't work with siduim latest version

### ISSUE THREAD

**Issue by Enibeatz** [Fabricators-of-Create/Create#1359]
### Describe the Bug

1.instal create 0.5.1 1.20.1 fabric 
2.drag and drop on mods folder
3.open minecraft 
4.minecraft crash error 
5.Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with any version that is compatible with: sodium 0.5.8+mc1.20.1
6.help

### Reproduction Steps

1.instal create 0.5.1 1.20.1 fabric 
2.drag and drop on mods folder
3.open minecraft 
4.minecraft crash error 
5.Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with any version that is compatible with: sodium 0.5.8+mc1.20.1
6.help

### Expected Result

1.instal create 0.5.1 1.20.1 fabric 
2.drag and drop on mods folder
3.open minecraft 
4.minecraft crash error 
5.Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with any version that is compatible with: sodium 0.5.8+mc1.20.1
6.help

### Operating System

windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
Next time, don't copy and paste the same thing into basically every box.

create 0.5.1d
sodium 0.4.10
fabric api 0.88.1
iris 1.6.4
indium 1.0.21

Are the exact versions you should be using.

**Comment by TropheusJ** [comment]
this is already fixed in the next version

**Comment by Enibeatz** [comment]
thank you . 
When will create fabric no longer be in beta?
