### ISSUE TITLE
Datapack Issue

### ISSUE THREAD

**Issue by StockiesLad** [Fabricators-of-Create/Create#136]
### Describe the Bug

I throw create into my mod pack and it stops loading because of some datapack issue. yeah idk
fabricmodloader 0.13.1

### Reproduction Steps

https://www.technicpack.net/modpack/the-limit-reborn-1181.1905659

add create-mc1.18.1_v0.4d+394.jar
into the mods folder and it happens

### Expected Result

To load into the world and test create on fabric

### Crash Report or Log

https://pastebin.com/BWkk65Qg

### Operating System

windows 10

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

**Comment by StockiesLad** [comment]
its actually not 0.4.0c that was the latest version that I could select

**Comment by TropheusJ** [comment]
does this still happen in the latest build? does it happen without create installed?

**Comment by TropheusJ** [comment]
if it still occurs please reopen.
