### ISSUE TITLE
Crash after loading in world created in Create Forge

### ISSUE THREAD

**Issue by ReMelon** [Fabricators-of-Create/Create#1360]
### Describe the Bug

I tried to port my forge modpack to fabric, worlds from create forge crash after loading in. Looks like a washing machine is the reason for this crash.

### Reproduction Steps

1. Create a world in Create Forge and make a washing setup
2. Change mods to Fabric

### Expected Result

Expected to have world compat between fabric and forge 

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/116052436/18c44592-ffa0-4bef-abcc-cd324fdb36ed)

### Crash Report or Log

https://pastebin.com/Yvfkz5bW

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/116052436/f68f8f56-7fdd-4e25-b237-27754a6b9467)

### Additional Context

The chunks im loading in consist of an andesite farm

**Comment by KonSola5** [comment]
You can use [Neurina](https://www.curseforge.com/minecraft/mc-mods/neruina) to suppress ticking entity/block entity crashes.

Since according to log the fan tries to access an enum constant that doesn't exist.

**Comment by IThundxr** [comment]
Fixed in patch f

**Comment by ReMelon** [comment]
> Fixed in patch f

Is patch f out yet? If yes where can I get it?
