### ISSUE TITLE
The game suddenly crashes while running.

### ISSUE THREAD

**Issue by EmptyDreams** [Fabricators-of-Create/Create#1362]
### Describe the Bug

As I was going through the game, the game suddenly crashed, I'm not quite sure exactly what caused the crash, at the time of the crash I was using the auto refiner (which used cubes like the crush wheel, blower, waterwheel, etc.) and the auto digger (which used cubes like the piston, wireless redstone, drill, windmill, etc.).

I'm looking at the crash log and the class Create appears in it, so I suspect Create is causing the crash, but if it's not Create, forgive my ignorance.

### Reproduction Steps

There is no reproduction method.

This is my crash log:

[crash-2024-03-08_20.37.45-server.txt](https://github.com/Fabricators-of-Create/Create/files/14538261/crash-2024-03-08_20.37.45-server.txt)

### Expected Result

The game should run correctly.

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

A list of modules is listed at the end of the log.

**Comment by IThundxr** [comment]
Already fixed in patch f

**Comment by EmptyDreams** [comment]
> Already fixed in patch f

I've noticed that the patch seems to have been completed two months ago, but the F version has not been pushed to modrinth and curseforge and can only be downloaded in actions, is this because it's still unstable or something else?

**Comment by IThundxr** [comment]
> > Already fixed in patch f
> 
> I've noticed that the patch seems to have been completed two months ago, but the F version has not been pushed to modrinth and curseforge and can only be downloaded in actions, is this because it's still unstable or something else?

It's unreleased at the moment, still in the works

**Comment by EmptyDreams** [comment]
> > > Already fixed in patch f
> > 
> > 
> > I've noticed that the patch seems to have been completed two months ago, but the F version has not been pushed to modrinth and curseforge and can only be downloaded in actions, is this because it's still unstable or something else?
> 
> It's unreleased at the moment, still in the works

Okay, is the version in Actions stable and available? I don't want to have this crash problem again.

Thank you for your patience in replying!
