### ISSUE TITLE
Crash when saving schedule data

### ISSUE THREAD

**Issue by JensenJ** [Fabricators-of-Create/Create#1363]
### Describe the Bug

Loaded up world after updating to latest version of Create Fabric, crashed when saving NBT on train schedules. Looks to be basically the same as https://github.com/Fabricators-of-Create/Create/issues/1316.

### Reproduction Steps

1. Create train schedule with a condition (in this case it was with fluid's but it might also be with items)
2. Press escape to force save
3. Crash

### Expected Result

No crash

### Crash Report or Log

https://mclo.gs/aderf8y

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Lots, based on crash report it's solely a create issue though, no other mods changed in this pack when upgrading to Create  0.5.1f

**Comment by drewcassidy** [comment]
~~FYI this also happens with fluid threshold conditions~~

edit: never mind, fixed in commit 16408e75ff79aedc05043fa1752d3c4ad7de852f
