### ISSUE TITLE
Crash on Fabric version of Create

### ISSUE THREAD

**Issue by skytheraiders** [Fabricators-of-Create/Create#1367]
### Describe the Bug

Game Initialization breaks and crashes to launcher.

### Reproduction Steps

1. Hit Play in launcher
2.
3.
...

### Expected Result

Wait a few seconds and the launcher comes back up with a crash report.
Here's the whole log:
[crash-2024-03-10_11.02.28-client.txt](https://github.com/Fabricators-of-Create/Create/files/14550684/crash-2024-03-10_11.02.28-client.txt)

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
This issue is not related to create and is caused by a addon mod/another mod.

Liquid burner isnt updated yet.

**Comment by skytheraiders** [comment]
Thanks!
