### ISSUE TITLE
Train conductors gets stuck in nether portal

### ISSUE THREAD

**Issue by misigno** [Fabricators-of-Create/Create#1369]
### Describe the Bug

Going in either direction train conductors gets stuck in nether portal upon train arriving in dimension.
This seems to only be visual, train continues to function normally.
If seat is interacted with while conductor is stuck "Driver has gone missing" is displayed in chat and entity gets tp'd to seat location.
When entering dimension following error is displayed in console:
`[Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "com.simibubi.create.content.contraptions.Contraption.setSeatMapping(java.util.Map)" because the return value of "com.simibubi.create.content.contraptions.AbstractContraptionEntity.getContraption()" is null`
	`at com.simibubi.create.content.contraptions.sync.ContraptionSeatMappingPacket.lambda$handle$1(ContraptionSeatMappingPacket.java:71) ~[create-fabric-0.5.1-f-build.1335+mc1.20.1.jar:?]`
	`at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]`
	`at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]`
	`at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]`
	`at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]`
	`at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]`
	`at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]`
	`at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.7.jar:?]`
	`at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]`
	`at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]`
	`at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]`

### Reproduction Steps

1.Make a train with seated entity as conductor
2.Move the train in the nether and back
3.Train driver gets stuck in portal

### Expected Result

Conductor should keep being seated after train moving dimension.

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/5872835/f7501666-00b2-4696-b81f-7f0f6e153b49

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Fabric API 0.92.0

### Additional Context

Cannot reproduce on forge version

**Comment by TropheusJ** [comment]
can't reproduce on the latest commit.

**Comment by TropheusJ** [comment]
considering this a duplicate of #1368
