### ISSUE TITLE
Moving gantry carrige crashes server with Lithium

### ISSUE THREAD

**Issue by CarbonGhost** [Fabricators-of-Create/Create#137]
### Describe the Bug

When running on a dedicated server, a moving gantry carriage will fully crash the server. Suspected incompatibility with Lithium. This crash does not seem to occur on a client with the same mod setup

### Reproduction Steps

1. Install Create and Lithium on a dedicated server.
2. Build a gantry shaft with carriage.
3. Connect motor in order to move carriage.
4. Server will crash.

### Expected Result

Gantry will move and server will not crash.

### Screenshots and Videos

https://gfycat.com/hilariousmajesticaztecant.gif

### Crash Report or Log

https://bin.bloom.host/ponidihuku

### Operating System

Debian (Duckerized)

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

- jankson 1.2.1
- Carpet Mod 1.4.57
- cloth-basic-math 0.6.0
- Cloth Config v6 6.2.57
- core 3.6.4
- toml 3.6.4
- parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
- jsr305 3.0.2
- velocity-native 1.1.0-SNAPSHOT
- Create mc1.18.1_v0.4d+394
- Dripstone Fluid Lib 1.1.1
- Fabric API 0.46.4+1.18
- Fabric API Base 0.4.2+d7c144a865
- Fabric API Lookup API (v1) 1.5.3+d7c144a865
- Fabric Biome API (v1) 6.0.2+d7c144a865
- Fabric Command API (v1) 1.1.7+d7c144a865
- Fabric Commands (v0) 0.2.6+b4f4f6cd65
- Fabric Containers (v0) 0.1.19+d7c144a865
- Fabric Content Registries (v0) 0.4.8+d7c144a865
- Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
- Fabric Data Generation API (v1) 1.0.0+3fec4ad9c8
- Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
- Fabric Entity Events (v1) 1.4.6+d7c144a865
- Fabric Events Interaction (v0) 0.4.17+d7c144a865
- Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
- Fabric Game Rule API (v1) 1.0.11+d7c144a865
- Fabric Item API (v1) 1.3.1+691a79b565
- Fabric Item Groups (v0) 0.3.6+3ac43d9565
- Fabric Language Kotlin 1.7.1+kotlin.1.6.10
- Fabric Lifecycle Events (v1) 1.4.13+713c266865
- Fabric Loot Tables (v1) 1.0.9+d7c144a865
- Fabric Mining Level API (v1) 1.0.6+d7c144a865
- Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
- Fabric Networking API (v1) 1.0.19+d7c144a865
- Fabric Networking (v0) 0.3.6+b4f4f6cd65
- Fabric Object Builder API (v1) 1.11.4+d7c144a865
- Fabric Object Builders (v0) 0.7.12+d7c144a865
- Fabric Particles (v1) 0.2.10+526dc1ac65
- fabric-permissions-api 0.1-SNAPSHOT
- Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
- Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
- Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
- Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
- Fabric Resource Loader (v0) 0.4.14+713c266865
- Fabric Screen Handler API (v1) 1.1.12+d7c144a865
- Fabric Structure API (v1) 2.1.3+d7c144a865
- Fabric Tag Extensions (v0) 1.2.8+d7c144a865
- Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
- Fabric Transfer API (v1) 1.5.9+d7c144a865
- Fabric Loader 0.13.1
- Fake Player API 0.3.0
- FerriteCore 4.1.1
- Forge Tags 1.6
- Forge Config API Port 3.1.0
- Inventory Sorter 1.8.4-1.18
- InvView 1.4.8-1.18+
- ItemFlexer 1.2.3
- OpenJDK 64-Bit Server VM 17
- Krypton 0.1.6
- Kyrpt Config 1.3.4-1.18
- LazyDFU 0.1.2
- Ledger 1.2.1
- Lithium 0.7.7
- LuckPerms 5.3.89
- Microconfig 2.0.4
- Milk Lib 0.1.6
- Minecraft 1.18.1
- commons-compress 1.19
- kotlin-reflect 1.6.10
- kotlin-stdlib 1.6.10
- kotlin-stdlib-jdk7 1.6.10
- kotlin-stdlib-jdk8 1.6.10
- kotlinx-coroutines-core-jvm 1.5.2
- kotlinx-coroutines-jdk8 1.5.2
- kotlinx-serialization-cbor-jvm 1.3.1
- kotlinx-serialization-core-jvm 1.3.1
- kotlinx-serialization-json-jvm 1.3.1
- xz 1.9
- Packet Tweaker 0.2.0+1.18-pre1
- Fabric Placeholder API 0.3.0
- Reach Entity Attributes 2.1.1
- Registrate for Fabric MC1.18.1-1.0.7
- Server Translations API 1.4.8+1.18-pre1
- ServerCore 1.2.7-1.18.1
- Server Properties Reload 1.0.3
- sgui 1.0.0-rc6+1.18-pre5
- spark 1.7.2
- Textile Backup 2.3.0-1.18
- WorldEdit 7.2.9+e20e013

**Comment by TropheusJ** [comment]
[related issue](https://github.com/CaffeineMC/lithium-fabric/issues/200), should be a simple fix
