### ISSUE TITLE
Continuity texuture packs cause log spam

### ISSUE THREAD

**Issue by BreadIsBest** [Fabricators-of-Create/Create#1370]
### Describe the Bug

It keeps spamming this in the logs and I'm not sure why. I can play the game after it just takes up a TON of log space, like thousands of lines. This is on quilt 1.20.1

[23:02:13] [Worker-Main-14/ERROR]: Failed to modify baked model after bake
java.lang.IllegalArgumentException: Cannot create a MultiRenderTypeModel for a wrapped model that isn't CompositeModel.Baked
	at com.simibubi.create.foundation.render.MultiRenderTypeModel$Builder.build(MultiRenderTypeModel.java:125) ~[create-0.5.1-f-build.1335mc1.20.1.i0:0/:?]
	at com.simibubi.create.foundation.render.MultiRenderTypeModel.forNixieTube(MultiRenderTypeModel.java:65) ~[create-0.5.1-f-build.1335mc1.20.1.i0:0/:?]
	at com.simibubi.create.foundation.utility.ModelSwapper.modifyModelAfterBake(ModelSwapper.java:52) ~[create-0.5.1-f-build.1335mc1.20.1.i0:0/:?]
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoaderPluginContextImpl.lambda$new$6(ModelLoaderPluginContextImpl.java:98) ~[quilted-fabric-model-loading-api-v1-7.5.00.91.0-1.20.1.i0:0/:?]
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.modifyModelAfterBake(ModelLoadingEventDispatcher.java:292) ~[quilted-fabric-model-loading-api-v1-7.5.00.91.0-1.20.1.i0:0/:?]
	at net.minecraft.class_1088$class_7778.redirect$hdb000$quilted_fabric_model_loading_api_v1$invokeModifyAfterBake(class_1088.java:561) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_1088.method_45877(class_1088.java:188) ~[minecraft-1.20.1.i0:0/:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
	at net.minecraft.class_1088.method_45876(class_1088.java:185) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_1092.method_45883(class_1092.java:145) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_1092.method_45885(class_1092.java:92) ~[minecraft-1.20.1.i0:0/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

### Reproduction Steps

1. download create + other mods on quilt 
2. run game
3. check logs
...

### Expected Result

Make it not spam my logs please?

### Crash Report or Log

Spam starts at line 1154 https://gist.github.com/BreadIsBest/1b679ad693aa7d79ec306267825461e4 

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

a lot

Mods:
  [✔] ad_astra-fabric-1.20.1-1.15.18
  [✔] alternate-current-mc1.20-1.7.0
  [✔] AmbientSounds_FABRIC_v5.3.9_mc1.20.1
  [✔] animatica-0.6+1.20
  [✔] another_furniture-fabric-1.20.1-3.0.1
  [✔] appleskin-fabric-mc1.20.1-2.5.1
  [✔] arcanus-continuum-0.106.0
  [✔] architectury-9.2.14-fabric
  [✔] artifacts-fabric-9.3.1
  [✔] bclib-3.0.14
  [✔] BeansBackpacks-fabric-1.20.1-0.17-v2
  [✔] beautify-1.0.0+fabric-1.20
  [✔] BetterAdvancements-Fabric-1.20.1-0.3.2.162
  [✔] BetterAnimationsCollection-v8.0.0-1.20.1-Fabric
  [✔] betterarcheology-1.1.6-1.20.1
  [✔] bettercombat-fabric-1.8.4+1.20.1
  [✔] better-end-4.0.11
  [✔] betterendcitiesbetterend-1.20.1
  [✔] BetterF3-7.0.2-Fabric-1.20.1
  [✔] BetterSmithingTable-1.1.0-Fabric-1.20
  [✔] BetterThirdPerson-Fabric-1.20-1.9.0
  [✔] BetterTridents-v8.0.1-1.20.1-Fabric
  [✔] blahaj-fabric-1.20.0-0.3.2
  [✔] blur-3.1.0
  [✔] Boat-Item-View-Fabric-1.20.1-0.0.5
  [✔] botarium-fabric-1.20.1-2.3.3
  [✔] c2me-fabric-mc1.20.1-0.2.0+alpha.11.5
  [✔] cardinal-components-api-5.2.2
  [✔] cave_dust-1.4.1
  [✔] chat_heads-0.10.31-fabric-1.20
  [✔] cherishedworlds-fabric-6.1.6+1.20.1
  [✔] CITResewn-1.1.3+1.20
  [✔] cloth-config-11.1.118-fabric
  [✔] Clumps-fabric-1.20.1-12.0.0.3
  [✔] combatroll-fabric-1.3.1+1.20.1
  [✔] comforts-quilt-6.3.6+1.20.1
  [✔] continuity-3.0.0-beta.4+1.20.1
  [✔] Controlling-fabric-1.20.1-12.0.2
  [✔] convenientdecor-0.3.0
  [✔] CraftPresence-2.3.5+1.20.1
  [✔] create-fabric-0.5.1-f-build.1335+mc1.20.1
  [✔] create-structures-0.1.1-1.20.1-FABRIC
  [✔] CreativeCore_FABRIC_v2.11.24_mc1.20.1
  [✔] ctov-3.4.2
  [✔] ctov-beautify-compat-2.0
  [✔] ctov-chefs-delight-compat-2.0
  [✔] ctov-create-structures-1.0
  [✔] ctov-farmers-delight-compat-2.1
  [✔] ctov-friends-and-foes-compat-2.0
  [✔] CustomPlayerModels-Quilt-1.20-0.6.15a
  [✔] Debugify-1.20.1+2.0
  [✔] deeperdarker-fabric-1.20-1.2.6
  [✔] do_a_barrel_roll-fabric-3.5.2+1.20.1
  [✔] doapi-1.2.8-fabric
  [✔] DripSounds-1.19.4-0.3.2
  [✔] dummmmmmy-1.20-1.8.14-fabric
  [✔] dynamic-fps-3.4.2+minecraft-1.20.4-quilt
  [✔] e4mc-4.0.1+1.19.4-fabric
  [✔] EasyAnvils-v8.0.2-1.20.1-Fabric
  [✔] EasyMagic-v8.0.1-1.20.1-Fabric
  [✔] effective-2.2.0+1.20.1
  [✔] emi_loot-0.6.5+1.20.1
  [✔] emi-1.1.3+1.20.1+fabric
  [✔] emitrades-fabric-1.2.1+mc1.20.1
  [✔] enhancedblockentities-0.9+1.20
  [✔] entity_model_features_fabric_1.20.1-1.3
  [✔] entity_texture_features_fabric_1.20.1-5.2.3
  [✔] exposure-1.20.1-1.4.0-fabric
  [✔] extra-mod-integrations-0.4.2+1.20.1
  [✔] fallingleaves-1.15.4+1.20.1
  [✔] farmers-delight-fabric-1.4.3
  [✔] ferritecore-6.0.1-fabric
  [✘] firstperson-fabric-2.3.4-mc1.20.1.jar (disabled)
  [✔] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
  [✔] friendsandfoes-beekeeperhut-fabric-mc1.20.1-2.0.0
  [✔] friendsandfoes-fabric-mc1.20.1-2.0.9
  [✔] geckolib-fabric-1.20.1-4.4.2
  [✔] guardvillagers-2.0.9-1.20.1
  [✔] handcrafted-fabric-1.20.1-3.0.6
  [✔] Highlighter-1.20.1-fabric-1.1.9
  [✔] Iceberg-1.20.1-fabric-1.1.18
  [✔] ImmediatelyFast-Fabric-1.2.10+1.20.4
  [✔] immersive_weathering-1.20.1-2.0.1-fabric
  [✔] indium-1.0.30+mc1.20.4
  [✔] InvMove-1.20-0.8.4-Quilt
  [✔] iris-mc1.20.1-1.6.17
  [✔] Jade-1.20-fabric-11.8.0
  [✔] krypton-0.2.3
  [✔] lambdynamiclights-2.3.2+1.20.1
  [✔] lazydfu-0.1.3
  [✔] letmedespawn-fabric-1.20.x-1.2.0
  [✔] letsdo-bakery-fabric-1.1.3b
  [✔] letsdo-beachparty-fabric-1.1.3
  [✔] letsdo-vinery-fabric-1.4.11
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] lithostitched-fabric-1.20.1-1.1.5
  [✔] memoryleakfix-fabric-1.17+-1.1.5
  [✔] modmenu-7.2.2
  [✔] moonlight-1.20-2.11.2-fabric
  [✔] moreculling-1.20.4-0.22.1
  [✔] MouseTweaks-fabric-mc1.20-2.25
  [✔] moyai-1.20-2.0.2-fabric
  [✔] naturalist-fabric-4.0.3-1.20.1
  [✔] niftycarts-3.0.1+1.20.1
  [✔] notenoughanimations-fabric-1.7.1-mc1.20.1
  [✔] PacketFixer-fabric-1.20.1-1.2.8
  [✔] Pehkui-3.7.12+1.14.4-1.20.4
  [✔] perfectplushies-fabric-1.20.1-1.9.0
  [✔] player-animation-lib-fabric-1.0.2-rc1+1.20
  [✔] PuzzlesLib-v8.0.15-1.20.1-Fabric
  [✔] qfapi-7.5.0_qsl-6.1.2_fapi-0.91.0_mc-1.20.1
  [✔] quilt-kotlin-libraries-2.1.3+kt.1.9.10+flk.1.10.10
  [✔] reeses_sodium_options-1.7.2+mc1.20.1-build.101
  [✔] resourcefulconfig-fabric-1.20.1-2.1.2
  [✔] resourcefullib-fabric-1.20.1-2.1.23
  [✔] Searchables-fabric-1.20.1-1.0.2
  [✔] SmartBrainLib-fabric-1.20.1-1.13
  [✔] sodium-extra-0.5.4+mc1.20.1-build.115
  [✔] sodium-fabric-0.5.8+mc1.20.1
  [✔] sound-physics-remastered-fabric-1.20.1-1.3.1
  [✔] spark-1.10.53-fabric
  [✔] sparkweave-0.4.1
  [✔] starlight-1.1.2+fabric.dbc156f
  [✔] Steam_Rails-1.5.3+fabric-mc1.20.1
  [✔] supplementaries-1.20-2.8.4-fabric
  [✔] suppsquared-1.20-1.1.14-fabric
  [✔] Terralith_1.20.4_v2.4.11
  [✔] tooltipfix-1.1.1-1.20
  [✔] trinkets-3.7.2
  [✔] villager-transportation-1.2
  [✔] villagesandpillages-fabric-mc1.20.1-1.0.0
  [✔] visuality-0.7.1+1.20
  [✔] wakes-0.2.3
  [✔] yet-another-config-lib-fabric-3.2.2+1.20
  [✔] YungsApi-1.20-Fabric-4.0.4
  [✔] Zoomify-2.11.2

**Comment by TheAyes** [comment]
[Can confirm.](https://mclo.gs/eZaC2Cs)

**Comment by BreadIsBest** [comment]
It seems like Better End and Supplementaries are causing the problem in my modpack. I've tested it with create and those mods on their own and it works normally so I'm not sure what's wrong.

**Comment by KinanLak** [comment]
Same here on Fabric

**Comment by TheAyes** [comment]
> @KinanLak 
> Same here on Fabric

Please consider sharing logs for reference on what the issue could be.

**Comment by KinanLak** [comment]
The Minecraft client and server still run perfectly, but the logs are being spammed.

Here client logs : 
https://mclo.gs/aTEZCB4

edit: wrong link

**Comment by IThundxr** [comment]
Issue is that continuities models are being passed through create's special model stuff, Now this should usually never ever happen but somehow it did.

Cannot reproduce with just continuity + create fabric.
Modernfix dynamic resources changes nothing.
More culling and or entity culling doesnt cause this either.

For now the best option to findout what is doing this is binary searching either AOF7 or some other pack thats smaller.

**Comment by MrRedstoneToGo** [comment]
@BreadIsBest: My trick: Disable the second half of your enabled mods (needed libraries stay active, of course). If the bug still occors, test with the first half of them, otherwise with the first half of the mods you disabled. It'll take at most 10 runs to find out the mod.
Good luck!

**Comment by maoperson** [comment]
I have looked into it.
idk if its just only continuity or if there are other mods present to this issue.
ive tried this with a small list of mods and resource packs that use continuity features etc.
this spam wont happen when i dont load the resourcepacks, and for some reason create disables all my resourcepacks when i load them and this error happens.
(sorry for this cryptic description btw)

gamelog:
https://gist.github.com/NotTheRealRoKur0/80d4ac2bdf8dccfdcd7d8ed2ed6c8884

mods in question:
- mod menu
- forge config api
- create
- cit resewn
- continuity
- sodium extra
- sodium
- nvidium
- entity model features
- sodium
- fabric api
- indium
- reeses sodium options
- entity texture features
- enhanced block entities

version: 1.20.1 latest create release

**Comment by Killercrab432** [comment]
I believe im also getting the same issue https://mclo.gs/I06VOTu

**Comment by IThundxr** [comment]
New updates: AOF7 was able to binary search it down to moonlight lib

**Comment by IThundxr** [comment]
Recording info from the AOF general channel about this bug:

> Embeddedt: when a Continuity resource pack is enabled, it wraps every baked model, so if Create's event handler does not run before Continuity's, it will probably never see the model class it's looking for.
I think Continuity's wrapper implements Fabric's `WrappingBakedModel` interface so you could probably work around the issue by unwrapping the model till you find what you want.
However that means Continuity features likely won't work on any models you override

**Comment by maoperson** [comment]
will this be fixed?
