### ISSUE TITLE
Corrupted models create with addon and origins (Fabric 1.20.1)

### ISSUE THREAD

**Issue by GyroNemesis** [Fabricators-of-Create/Create#1372]
Some of the models (base Create model) and addon models are corrupted when placed.
![2024-03-13_00 59 39](https://github.com/Fabricators-of-Create/Create/assets/163169733/c13bbc17-d2cb-41a7-a8aa-870c6396b9df)
![2024-03-13_00 59 50](https://github.com/Fabricators-of-Create/Create/assets/163169733/140ae3f9-6229-44bd-9399-bb36047af7e3)
![2024-03-13_01 02 39](https://github.com/Fabricators-of-Create/Create/assets/163169733/2c0cc60b-1e58-4424-83c2-1c78c2cb7cff)

This is the list of mods used for the server:

[Fantasy of Creation.zip](https://github.com/Fabricators-of-Create/Create/files/14576129/Fantasy.of.Creation.zip)

**Comment by IThundxr** [comment]
Please follow the bug report template, also your issue is that you are missing indium
