### ISSUE TITLE
World load hangs

### ISSUE THREAD

**Issue by SquareBall789** [Fabricators-of-Create/Create#1374]
### Describe the Bug

When loading into my world it hangs and mine craft is recognized as stopped working, when force closing error suggests ticking entity caused by spout

### Reproduction Steps

I dont know how to recreate this

### Expected Result

not crash :(

### Crash Report or Log

https://pastebin.com/VZknJYRP

### Operating System

windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
exposure mod is crashing
