### ISSUE TITLE
Fabric 1.20.1 Release 0.15.4 status effect crash

### ISSUE THREAD

**Issue by ZeonEsper** [Fabricators-of-Create/Create#1375]
### Describe the Bug

Upon loading up the create-fabric-0.5.1-d-build.1161+mc1.20.1 along with fabric-api-0.91.0+1.20.1 on Fabric - 0.15.4 and loading a world if you receive any status effect and proceed to open your inventory you will crash.

### Reproduction Steps

1.Create a Fabric - 0.15.4 Profile.
2.Download create-fabric-0.5.1-d-build.1161+mc1.20.1 along with fabric-api-0.91.0+1.20.1
3.Load up the game.
4.Create a new creative/survival world.
5.Acquire any status potion effect or otherwise.
6.Open Inventory.
7.Crash.

### Expected Result

The player Inventory opens without any crash due to effects.

### Crash Report or Log

https://gist.github.com/ZeonEsper/7f3c39a995b6c73b2fbb0d9d27933ec3

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
update to patch F
