### ISSUE TITLE
Dispenser bug

### ISSUE THREAD

**Issue by elifian** [Fabricators-of-Create/Create#1377]
### Describe the Bug

Dispenser bug

### Reproduction Steps

1. Set up a "depot"
2. Put a "spout" on top of it.
3. Put any item on the "depot"
4. Done

### Expected Result

Nothing, it shouldn't crash the server

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/69606089/b7f0f49c-71d7-48f5-b465-41ec18b4dc2b

### Crash Report or Log

https://pastebin.com/UniqujNZ

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by elifian** [comment]
Mods:
AdditionalEnchantedMiner-1.20.1-fabric-20.1.1159.jar
AdvancedReborn-1.20.1-1.2.7.jar
ad_astra-fabric-1.20.1-1.15.18.jar
appliedenergistics2-fabric-15.0.23.jar
architectury-9.2.14-fabric.jar
autoconfig1u-3.4.0.jar
balm-fabric-1.20.1-7.2.2.jar
besmirchment-1.20.1-3.jar
bewitchment-1.20-7.jar
Botania-1.20.1-443-FABRIC.jar
botarium-fabric-1.20.1-2.3.3.jar
caracal-1.20-2.3.3.jar
cc-tweaked-1.20.1-fabric-1.109.6.jar
cccbridge-mc1.20.1-fabric-v1.6.2b.jar
Chroma Lights v1.0 - 1.20.1.jar
cloth-config-11.1.118-fabric.jar
clutter-1.20-0.5.7.jar
collective-1.20.1-7.39.jar
configured-fabric-1.20.1-2.2.2.jar
coroutil-fabric-1.20.1-1.3.7.jar
create-fabric-0.5.1-f-build.1335+mc1.20.1.jar
create-new-age-fabric-1.20.1-1.1.2.jar
createaddition-fabric+1.20.1-1.2.3.jar
create_enchantment_industry-1.2.16.jar
create_ultimate_factory-1.5.0-fabric-1.20.1.jar
creeperoverhaul-3.0.2-fabric.jar
cristellib-1.1.5-fabric.jar
CustomSkinLoader_Fabric-14.17.jar
deeperdarker-fabric-1.20-1.2.6.jar
deepmoblearning-refabricated-0.5.16-BETA+1.20.1.jar
disenchanter-0.1.8+1.20.jar
endermanoverhaul-fabric-1.20.1-1.0.4.jar
entangled-1.3.17-fabric-mc1.20.jar
ExplorersCompass-1.20.1-2.2.3-fabric.jar
exposure-1.20.1-1.4.0-fabric.jar
fabric-api-0.92.0+1.20.1.jar
fabric-language-kotlin-1.10.19+kotlin.1.9.23.jar
fakerlib-0.1.3.jar
framework-fabric-1.20.1-0.6.26.jar
ftb-chunks-fabric-2001.2.5.jar
ftb-library-fabric-2001.1.5.jar
ftb-teams-fabric-2001.1.4.jar
ftb-ultimine-fabric-2001.1.4.jar
ftbbackups2-fabric-1.20-1.0.23.jar
geckolib-fabric-1.20.1-4.4.2.jar
graves-3.0.1+1.20.1.jar
improvedsigns-1.3.1.jar
iron-jetpacks-0.4.7.jar
IronChests-2.0.2.jar
linkedstorage-1.5.2-1.20.jar
lootr-1.20-0.7.30.77.jar
mcpitanlib-2.1.9-1.20.1-fabric.jar
megacells-fabric-2.3.3-1.20.1.jar
MobLassos-v8.0.1-1.20.1-Fabric.jar
moonlight-1.20-2.11.1-fabric.jar
mythic_charms-fabric-1.20.1-0.7.0.jar
naturalist-fabric-4.0.3-1.20.1.jar
NaturesCompass-1.20.1-2.2.3-fabric.jar
notenoughcrashes-4.4.7+1.20.1-fabric.jar
ObsidianUI-fabric-0.2.1+mc1.20.1.jar
owo-lib-0.11.2+1.20.jar
Patchouli-1.20.1-84-FABRIC.jar
Pehkui-3.7.12+1.14.4-1.20.4.jar
Philips-Ruins1.20.1-3.3[Fabric].jar
plasmovoice-fabric-1.20.1-2.0.8.jar
polylib-fabric-2000.0.3-build.97.jar
Powah-5.0.5.jar
PuzzlesLib-v8.1.17-1.20.1-Fabric.jar
RebornCore-5.8.7.jar
resourcefulconfig-fabric-1.20.1-2.1.2.jar
resourcefullib-fabric-1.20.1-2.1.23.jar
restart-server-1.2.0+mc1.19.x-1.20.x.jar
revelationary-1.3.7+1.20.1.jar
RoughlyEnoughItems-12.0.684-fabric.jar
RyoamicLights-fabric-0.2.1+mc1.20.1.jar
scalable-cats-force-fabric-2.2.0.jar
spectrum-1.7.7-deeper-down.jar
specutils-1.0.1.jar
supermartijn642configlib-1.1.8a-fabric-mc1.20.jar
supermartijn642corelib-1.1.17-fabric-mc1.20.1.jar
supplementaries-1.20-2.8.6-fabric.jar
TechReborn-5.8.7.jar
theprinter-1.4.3+1.20.jar
Towns-and-Towers-1.12-Fabric+Forge.jar
trinkets-3.7.2.jar
useful_backpacks-fabric-1.20.1-2.0.1.122.jar
u_team_core-fabric-1.20.1-5.1.4.269.jar
VersionCheckerMod-2.2.0.jar
watut-fabric-1.20.1-1.1.0.jar
waystones-fabric-1.20-14.1.3.jar
yet-another-config-lib-fabric-3.2.2+1.20.jar
YungsApi-1.20-Fabric-4.0.4.jar
YungsBetterDesertTemples-1.20-Fabric-3.0.3.jar
YungsBetterDungeons-1.20-Fabric-4.0.3.jar
YungsBetterEndIsland-1.20-Fabric-2.0.5.jar
YungsBetterJungleTemples-1.20-Fabric-2.0.4.jar
YungsBetterMineshafts-1.20-Fabric-4.0.4.jar
YungsBetterNetherFortresses-1.20-Fabric-2.0.5.jar
YungsBetterOceanMonuments-1.20-Fabric-3.0.4.jar
YungsBetterStrongholds-1.20-Fabric-4.0.3.jar
YungsBetterWitchHuts-1.20-Fabric-3.0.3.jar
YungsBridges-1.20-Fabric-4.0.3.jar
zenith-1.1.3-1.20.1.jar
zenith_attributes-0.2.1.jar

**Comment by IThundxr** [comment]
exposure is crashing
