### ISSUE TITLE
Index out of bounds when querying the Create mod specific synthesis method in REI, resulting in MC crash

### ISSUE THREAD

**Issue by nkdns** [Fabricators-of-Create/Create#1378]
### Describe the Bug

在REI中查询Create特有的合成时发生下标越界，导致游戏崩溃
When querying the Create specific composite in REI, the index exceeded the bounds, causing the game to crash

### Reproduction Steps

1.在生存模式查询REI中关于Create的合成表（Query the composite table about Create in the survival mode of REI）
2.查看Create注册的合成方法例如精密构件的制作（View the synthesis method registered in Create, such as the Precision Mechanism components）
3.发送崩溃（Collapse occurred）

### Expected Result

修复bug或给出问题分析以及解决方案
Fix bugs or provide problem analysis and solutions

### Crash Report or Log

https://gist.github.com/nkdns/bf6e7127c05ff262e02f53b706442c07

### Operating System

windows10

### Mod Version

0.5.1f

### Minecraft Version

1.19.2

### Other Mods

simibubi；create；compat；shedaniel；rei；impl

**Comment by Hippopipo** [comment]
just happened to me aswell

**Comment by IThundxr** [comment]
Fixed in dev already

**Comment by nkdns** [comment]
> Fixed in dev already已在开发中修复

Where can I get the fixed version or when will the next version be pushed

**Comment by Hippopipo** [comment]
You could build it yourself but i wouldn't recommend that
