### ISSUE TITLE
This line of code (126) causes an IndexOutOfBounds exception when viewing certain recipes.

### ISSUE THREAD

**Issue by littleconnor1** [Fabricators-of-Create/Create#1379]
https://github.com/Fabricators-of-Create/Create/blame/e471a601b8082c3be1e74ea140e8a5d63f2e87de/src/main/java/com/simibubi/create/compat/jei/category/CreateRecipeCategory.java#L126C8-L126C8

**Comment by IThundxr** [comment]
Can you post the crash log?

**Comment by littleconnor1** [comment]
https://mclo.gs/k9zQFTR

my bad

**Comment by IThundxr** [comment]
Fixed in dev already

**Comment by NolanHewitt** [comment]
Can confirm this. Glad its already fixed, hoping the fix can be released soon.
