### ISSUE TITLE
Incompatibility with Carpet mod

### ISSUE THREAD

**Issue by charmesal** [Fabricators-of-Create/Create#138]
### Describe the Bug

When starting up the game with Carpet and Create installed the game crashes on launch.

Note that I'm using version 0.4d but it was not an option in from the dropdown list below, hence it says version 0.4c.

### Reproduction Steps

1. Install Fabric API, Carpet, and Create
2. Launch the game

### Expected Result

For the game to launch

### Crash Report or Log

https://pastebin.com/T5SX1zvz

### Operating System

Windows 10

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

fabric-api-0.46.4+1.18
fabric-carpet-1.18.1-1.4.57+v220119

**Comment by Oliver-makes-code** [comment]
It seems like a mixin conflict
`carpet.mixins.json:WorldRenderer_pausedShakeMixin`

**Comment by TropheusJ** [comment]
this is an issue with flywheel's [CancelEntityRenderMixin](https://github.com/Jozufozu/Flywheel/blob/1.18/fabric/dev/src/main/java/com/jozufozu/flywheel/mixin/CancelEntityRenderMixin.java) + mixin weirdness. Flywheel's redirect needs to apply after carpet.

**Comment by PepperCode1** [comment]
This should be fixed now. Please test with the very latest versions of Flywheel and Create and report back the findings.

**Comment by charmesal** [comment]
Can confirm that this issue is fixed. Now either the mechanical pistons don't work with Carpet installed or I'm an idiot (it's most likely the latter) but since that's a different issue (if it even is one at all. I'll have to recheck that later) this can be closed.
Thanks for the quick fix devs! Highly appreciated.
