### ISSUE TITLE
Crash occurs when viewing recipes with REI (any version) Create: 1.20.1-0.5.1-f

### ISSUE THREAD

**Issue by nfdm** [Fabricators-of-Create/Create#1380]
### Describe the Bug

Game crashes when viewing certain recipes that require a mixer, press, or basin. The crash occurs when hovering over the ingredient in the second slot of the recipe. Some recipes do not trigger a crash (such as the chocolate or mud recipe) while others do (like andesite/andesite alloy mixing recipe). Issue does not seem to be related to items being from create mod since the andesite mixing recipe has diorite and cobblestone and the crash still occurs. I believe it has to do with the second slot of the recipe in the GUI.

### Reproduction Steps

1. Open game using create 0.5.1-f and any version of REI
2. Search any recipe that requires a basin/press/mixer (such as andesite alloy)
3. Hover over the second ingredient needed for the recipe (for andesite alloy, the nugget)
4. Game crashes unexpectedly
...

### Expected Result

Game should function as normal and not crash. You should be able to hover over the ingredient.

### Screenshots and Videos

https://youtu.be/fuFkbECRp0o

### Crash Report or Log

https://docs.google.com/document/d/1oJljl49J0NzxjARdi91LiBKE2kYpHAK4VuMgEVhdbhs/edit?usp=sharing

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

![mods](https://github.com/Fabricators-of-Create/Create/assets/163314309/1cddac51-374c-4add-9d4f-2e0e428775a5)

### Additional Context

Downgrading to create fabric version 0.5.1-d fixes the crash. Issue is also being tracked on REI issue tracker (https://github.com/shedaniel/RoughlyEnoughItems/issues/1597). Issue does not persist when using JEI.

**Comment by IThundxr** [comment]
known issue fixed in dev

**Comment by AlienXtream** [comment]
gathering this may also affect sandpaper recipe. glad to know its fixed pending update. in the mean time i will be careful what i mouse over in recipe's from create. would appreciate an update here when the fixed version is released :)
