### ISSUE TITLE
Lighting issue with certain blocks

### ISSUE THREAD

**Issue by L4ZYG4M3R** [Fabricators-of-Create/Create#1384]
### Describe the Bug

With the create fabric mod installed in 1.20.1, version 0.5.1-f , it causes certain lighting glitches to chests and rails in which the top part of chests are often black and curved rails are also often black,

### Reproduction Steps

1. I am running the specified version of create through the curse forge mod loader
2. place down a track or chest and the glitch happens

### Expected Result

Not have the visual bug

### Screenshots and Videos

![2024-03-17_04 52 04](https://github.com/Fabricators-of-Create/Create/assets/25245140/153135f7-9320-498e-95c9-7163cbd48d46)

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

 It is in a mod pack however with even disabling all other mods it still occurs

**Comment by drwoops** [comment]
try `/flywheel backend instancing` and `/flywheel backend batching` and use which ever works best for you.

**Comment by CocoManiaDX** [comment]
I'm seeing the same problem and did some more testing.

After trying both flywheel options, they both have their problems.

Batching seems to solve the visual bugs
However, it suffers from severe FPS drops with components like waterwheels.

Testing with just Create, Sodium and Indium installed, it goes from 400+ FPS without any waterwheels placed to 110 FPS when you place 6 of them.

![2024-03-18_16 19 57](https://github.com/Fabricators-of-Create/Create/assets/112061622/211fe1c3-b538-4487-9174-2cff62a975b8)
![2024-03-18_16 19 46](https://github.com/Fabricators-of-Create/Create/assets/112061622/bc0787f4-29a8-4985-a319-6824120963fe)

This isn't a huge problem on its own, however on larger modpacks it becomes a HUGE performance issue.
On my personal pack, the same test goes from 90+ FPS to around 30 FPS with the same 6 waterwheels.

Instancing mode seems to be the opposite.
It completely solves the performance issues, but it creates the black chest tops and train tracks as seen on the OP images.

**Comment by TropheusJ** [comment]
flywheel issue: https://github.com/Jozufozu/Flywheel/issues/226
