### ISSUE TITLE
"Bits and Chisels" bits entering chutes can cause client crashes

### ISSUE THREAD

**Issue by TheAppleFreak** [Fabricators-of-Create/Create#1385]
### Describe the Bug

The mod [Bits and Chisels](https://modrinth.com/mod/bits-and-chisels) lets you create "bits" that can stack in sizes well above 64. A server I play on has found that when these bits interact with certain Create inventories, namely chutes, it'll cause client crashes that recur every time the chute block entity in question is loaded. 

I don't know how many bits it takes to cause a crash (I did a bunch of testing but it was inconsistent, sometimes crashing and sometimes not), but it seems that if it needs to process more than one "batch" of bits at a time it'll cause a crash. 

### Reproduction Steps

1. Load a new world. I set mine to be a Creative world to expedite testing, but this happens in Survival too.
2. Acquire a smart chisel, then find or place any non-entity full block. Equip the chisel, line the selection up with one corner of the block, click, line up the selection with the opposite corner, and click again to confirm. The block should disappear and give you 4096 bits in exchange.
3. Acquire a chute. Place the chute on top of a chest.
4. Throw the bits into the chute.

### Expected Result

The chute should process one stack of bits as often as it can, leaving the rest of the bits on top until it can send them all into the next inventory. 

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/2409324/405f3d0c-1a40-499f-8602-dfe16d978a34

### Crash Report or Log

https://mclo.gs/cUeNzzL

### Operating System

Windows 11 Insiders 24H2 (build 26080.1201)

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

This was tested on a fresh instance of 1.20.1 Fabric, with the following additional mods:

- bitsandchisels-2.7.3
- fabric-api-0.92.0 1.20.1
- indium-1.0.30 mc1.20.4
- lithium-fabric-mc1.20.1-0.11.2
- modmenu-7.2.2
- sodium-fabric-0.5.8 mc1.20.1

**Comment by TropheusJ** [comment]
does it happen with just Create and B&C?

**Comment by TheAppleFreak** [comment]
> does it happen with just Create and B&C?

Yep, same sort of crash (fresh 1.20.1, Fabric API 0.92.0, Create 0.51-f, and B&C 2.7.3 only). [Here's the new crash log](https://mclo.gs/VcNVRrl)

**Comment by TropheusJ** [comment]
B&C returns null for the particle sprite [here](https://github.com/CoolMineman/BitsAndChisels/blob/abf30917671dfd8b826ffbaacb58b4cb2fe24ea3/src/main/java/io/github/coolmineman/bitsandchisels/BitItemModel.java#L123).
This is not valid, there's nothing I can do about this.
Report to them.

**Comment by TheAppleFreak** [comment]
Gotcha, apologies for bringing this up here. Opening a bug report there!
