### ISSUE TITLE
Client Crash when switching deployer from use to attack mode

### ISSUE THREAD

**Issue by Yannik-T** [Fabricators-of-Create/Create#1386]
### Describe the Bug

When clicking on the deployer to change from use to attack mode my game crashes

### Reproduction Steps

1.use wrench on deployer
2.
3.
...

### Expected Result

not crash

### Crash Report or Log

https://pastebin.com/p63258x5

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

See crash report

**Comment by TropheusJ** [comment]
Doesn't seem related to Create at all. Try with it alone.

**Comment by Yannik-T** [comment]
I can't seem to replicate it anymore, not with neither without the mods. Seems to have fixed itself
