### ISSUE TITLE
Crash when placing shaft

### ISSUE THREAD

**Issue by SquareBall789** [Fabricators-of-Create/Create#1388]
### Describe the Bug

Crash when placing shaft

### Reproduction Steps

Placed down a belt, doest visually appear but is there, placed shaft on belt and game crash

### Expected Result

Not crash

### Crash Report or Log

https://pastebin.com/ZqnejMxf

### Operating System

10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
Please try removing Sound Physics Remastered
