### ISSUE TITLE
Rotating components reverses rotational direction of inputs/outputs

### ISSUE THREAD

**Issue by SageofTurtles** [Fabricators-of-Create/Create#1389]
### Describe the Bug

When building a contraption that has a segment which can be related using a mechanical bearing, any components on the segment that has direction-specific inputs will sometimes be reversed. For instance, place a rope pulley on a platform with a windmill to power it to raise/lower a block. When the windmill is on, the rope pulley is retracting the block. However, if the platform is rotated 90 or 180 degrees parallel to the ground (depending on the original direction), the input from the windmill will reverse and cause the pulley to lower the block instead of raising it.

I haven't tested this thoroughly yet, but I would assume this has to do with the positive/negative X and Z axes changing when the contraption is rotated horizontally. So far, this seems to affect all Create components with direction-specific inputs (rotational speed controllers, rope pulleys, mechanical pistons, encased fans, sticky mechanical pistons, and gantry shafts have all had this issue in various designs I've attempted). There is extremely minimal information to be found on this, so I haven't been able to find what's causing the issue or how to prevent it in builds.

### Reproduction Steps

1. Build a platform of any block.
2. Place a power source, such as a windmill or creative motor, on the platform powering a direction-specific component (rope pulley, speed controller, mechanical piston, etc).
3. Glue the platform together with any components on it that need to be attached to move with the platform.
4. Affix a mechanical bearing to the platform with the sticky side facing either up or down, so that it will rotate the platform parallel to the ground.
5. Using a power source + sequenced gearshift, or even just a hand crank, rotate the platform in 90 degree increments.
6. Every 90 or 180 degrees, the direction of rotation powering the components on the platform will be reversed, causing them to change their output result/direction.

### Expected Result

The components should continue to operate consistently in all orientations when rotated, regardless of whether they are facing north, south, east, or west. Instead, they seem to change directions of input/output after being rotated.

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

I've tried this with only Create and have encountered the same issue.

**Comment by TropheusJ** [comment]
this issue has existed for forever and is unlikely to change. It behaves the same on forge.
