### ISSUE TITLE
Chunk Lighting and Overstressed Glitch With Nether Portals

### ISSUE THREAD

**Issue by digitaltrucker** [Fabricators-of-Create/Create#139]
### Describe the Bug

Using a contraption to feed lava buckets through a nether portal.  Occasionally the chunk containing the portal will glitch when the player travels through the portal.  When this happens the chunk is in full dark and the moving contraption will insist it's overstressed although it will continue to function.  If the moving contraption has a clutch on the power source (furnace generator in this case) powering the clutch does not stop the contraption.  Only breaking the wheel stops it.  The contraption I built was using belts.  Breaking the belt clears the overstressed condition but the lighting error remained.  Optimizing the world and clearing the cache will also resolve the problem.  This glitch will also happen even if nothing is currently being thrown through the portal, just the player traveling through can trigger it.

I'm using a fair collection of optimization mods including the known-incompatible Iris (although Create seems to work fairly well with it even so).  Disabling all those mods has had no effect, the error will still happen at random when the player goes through the portal.  It doesn't happen every time though and it doesn't seem to be affected by other entities such as buckets traveling through.  What's bad is I can't get the glitch to happen on command, it's random.  It seems to be connected with moving belts for some reason but I'm not absolutely certain.

Any other info I can provide let me know.

### Reproduction Steps

1.  Build a contraption to throw items such as buckets through a nether portal.
2.  Travel through the portal yourself.
3.  Return through the portal to the overworld, the contraption and chunk lighting may be glitched out.
...

### Expected Result

No glitches or lighting errors.

### Crash Report or Log

https://pastebin.com/bJchD5W9

### Operating System

Windows 10

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

	- advanced_runtime_resource_pack 0.2.9 via carrier
	- animal_feeding_trough 1.0.3+1.18.1
	- architectury 3.6.17
	- autofish 0.9.4
	- balm-fabric 2.4.1+0
	- beenfo 1.18.1-fabric0.45.0-1.3.3
	- blue_endless_jankson 1.2.1 via jankson
	- cardinal-components-base 4.0.1 via polymorph
	- cardinal-components-block 4.0.1 via polymorph
	- cardinal-components-entity 4.0.1 via polymorph
	- cardinal-components-item 4.0.1 via polymorph
	- carrier 1.9.1
	- cherishedworlds 2.0.1-1.18
	- chiselsandbits 1.2.79
	- cleancut 1.18-4.0-fabric
	- clienttweaks 7.0.0
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- collective-fabric 4.4
	- colytra 2.1.0-1.18.1
	- com_electronwill_night-config_core 3.6.3 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.3 via forgeconfigapiport
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- completeconfig 1.3.3
	- continuity 1.0.3+1.18
	- create mc1.18.1_v0.4d+395
	- crowdin-translate 1.4+1.18 via beenfo
	- doubledoors-fabric 3.1
	- dripstone_fluid_lib 1.1.1 via milk
	- enchantinginfuser 3.1.1
	- entityculling 1.5.0
	- fabric 0.46.4+1.18
	- fabric-api-base 0.4.2+d7c144a865 via fabric
	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric
	- fabric-blockrenderlayer-v1 1.1.10+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.19+d7c144a865 via fabric
	- fabric-content-registries-v0 0.4.8+d7c144a865 via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric
	- fabric-data-generation-api-v1 1.0.0+3fec4ad9c8 via registrate-fabric
	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric
	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric
	- fabric-item-api-v1 1.3.1+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.6+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.9+d7c144a865 via fabric
	- fabric-keybindings-v0 0.2.7+b4f4f6cd65 via fabric
	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric
	- fabric-mining-level-api-v1 1.0.6+d7c144a865 via fabric
	- fabric-mining-levels-v0 0.1.11+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.4+d7c144a865 via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.4+d7c144a865 via fabric
	- fabric-object-builders-v0 0.7.12+d7c144a865 via fabric
	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric
	- fabric-renderer-api-v1 0.4.11+b0b66fc365 via fabric
	- fabric-renderer-indigo 0.4.15+6825030165 via fabric
	- fabric-renderer-registries-v1 3.2.10+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.12+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.6+713c266865 via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric
	- fabric-resource-loader-v0 0.4.14+713c266865 via fabric
	- fabric-screen-api-v1 1.0.8+d7c144a865 via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric
	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric
	- fabric-tag-extensions-v0 1.2.8+d7c144a865 via fabric
	- fabric-textures-v0 1.0.10+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.8+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.9+d7c144a865 via fabric
	- fabrication 2.3.0_01
	- fabricloader 0.13.1
	- fake-player-api 0.3.0 via create
	- fastbench 1.18.1-3
	- fastfurnace 1.18-4
	- fiber 0.23.0-2 via collective-fabric
	- flywheel 1.18-0.6.1.22 via create
	- forge_tags 1.6 via create
	- forgeconfigapiport 3.1.1
	- fpsdisplay 1.4.2+1.18
	- gbfabrictools 1.3.4+1.18 via beenfo
	- guardvillagers 1.0.6
	- herdspanic 1.0.4
	- horsestatsvanilla 4.1.10
	- indium 1.0.2-alpha2+mc1.18.1
	- interactic 0.1.8+1.18
	- iris 1.2.0-pre
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- kirin 1.10.0-beta.2 via presencefootsteps
	- kiwi 5.2.5
	- lambdynlights 2.1.0+1.17
	- lapisreserve 1.0.8
	- libcd 3.0.3+1.16.3 via skinnedlanterns
	- libgui 5.0.0-beta.2+1.18-rc1 via horsestatsvanilla
	- libninepatch 1.1.0 via libgui
	- lightoverlay 6.0.4
	- lithium 0.7.7
	- milk 0.1.6 via create
	- minecraft 1.18.1
	- modmenu 3.0.1
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_joml_joml 1.10.2 via sodium
	- org_slf4j_slf4j-api 1.7.12 via iris
	- particlerain 2.0.0
	- phosphor 0.8.1
	- polymorph 0.0.19-1.18.1
	- presencefootsteps 1.4.0
	- pride 1.1.0+1.17 via fabrication
	- puzzleslib 3.1.5
	- raised 1.18.1-1.0.2
	- randomblockplacement 1.18-fabric0.43.1-1.1.2
	- reach-entity-attributes 2.1.1 via create
	- realisticfirespread 1.18-1
	- registrate-fabric MC1.18.1-1.0.7 via create
	- roughlyenoughitems 7.2.425
	- seasons 1.3-BETA+1.18
	- skinnedlanterns 1.2.0+build.12
	- smoothboot 1.18-1.7.0
	- snowrealmagic 3.2.2
	- sodium 0.4.0-alpha6+build.14
	- sound_physics_remastered 1.18.1-1.0.4
	- spruceui 3.3.0+1.17 via lambdynlights
	- xaerominimapfair 22.1.2
	- xaeroworldmap 1.20.1

**Comment by digitaltrucker** [comment]
I did some more experimentation.  Placing the nether portal against a chunk border so that contraptions are in a different chunk resolves the issue.  I wonder if the problem is the same basic issue as Report #141?  The symptoms seem similar, in particular the overstressed condition that crops up
![2022-02-12_11 37 51](https://user-images.githubusercontent.com/77534286/153722091-0cfae15b-2416-44db-9692-00dfe24bdc85.jpg)
.

**Comment by TropheusJ** [comment]
this is likely a duplicate of #141. if it turns out not to be, reopen.
