### ISSUE TITLE
on 0.5.1-d couldn't rotate anything with bearing, and on 0.5.1-f couldn't launch the game 

### ISSUE THREAD

**Issue by Freziyt223** [Fabricators-of-Create/Create#1390]
### Describe the Bug

when i used the 0.5.1-d with my modpack, it did work, but crashed when i tried to rotate anything https://mclo.gs/4GdSias
someone on discord told me to update version of create, i did, and then game wouldn't even launch shttps://mclo.gs/vZiP2nD

### Reproduction Steps

1. Installed create, fabric 0.15.7 for minecraft 1.20.1
2. installed other mods
3. launched the world(on 0.5.1-d) and tried to rotate any object with bearing(crash), can't get back to the world(crashes again)/ launch minecraft(on 0.5.1-f), crash
...

### Expected Result

expect create to do it's whole job and be compatible with other mods

### Operating System

Windows 11 home

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

as you can see in the log, i also use Clockwork and interactive, ad astra, big cannons, thin air, steam and rails, computercraft and it's bridges, and other smaller mods

**Comment by IThundxr** [comment]
Update to 0.5.1-f, if any addons crash with it then report it to the addon dev.
