### ISSUE TITLE
Game Crashes when pausing the game

### ISSUE THREAD

**Issue by Yannik-T** [Fabricators-of-Create/Create#1392]
### Describe the Bug

The game crashes when I pause the game in my already existing world (doesn't happen when I create a new world)

### Reproduction Steps

1. press esc

### Expected Result

not crash

### Crash Report or Log

https://pastebin.com/QdTmccuN

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

see crashlog

**Comment by IThundxr** [comment]
Fixed in dev, don't use item and fluid schedules conditions for now
