### ISSUE TITLE
Ingredients on sequenced assemblies not indexed

### ISSUE THREAD

**Issue by Abalieno** [Fabricators-of-Create/Create#1394]
### Describe the Bug

I tried to use EMI, but it has issues with MI, AE2, FTB, Farmer's Delight and more... There's is obviously no way to have it fixed on those sides, as all those mods on 1.19 fabric are completely abandoned.

I'd use the version of Create that actually works well, but it's a nightly I pulled from github and can't put that in a modpack. And it needed a specific version of porting lib that is not available now because you decided to hide all versions that aren't 1.20.

Everything was working well with this: https://legacy.curseforge.com/minecraft/mc-mods/createfabricreibugfix

Internal versions I've verified working properly:
create-fabric-0.5.1-f-build.1221+mc1.19.2
porting_lib-2.1.1282+1.19.2
CreateFabricREIBugFix-0.1.5-create0.5.1-mc1.19.x

These three combined solve all of the current problems: no crashes on tooltips, all ingredients are indexed, including those on sequenced assemblies. The only minor problem is that it won't show a chance for washing recipes, but at least it doesn't produce wrong numbers and it still shows it is chanced.
That Create version is from end of January, so still quite recent:
https://github.com/Fabricators-of-Create/Create/actions/runs/7705513213

I think it was a commit around February 20-22 that broke compatibility with that add-on, and triggered all the new problems and crashes.

For this issue, as the image shows, the starting ingredient is indexed in REI, circled in green, but all other items that go in deployers or fluid in spouts are not tracked.

I don't understand why the code from that plugin cannot be merged here. REI API hasn't changed in ages, those fixes have worked perfectly for months.

I also don't understand the logic for keeping a public version on CF that has known issues, including crashes, whose fixes are already available. Why cannot be updated more frequently so that at least the known stuff is fixed and the mod can actually be used rather than force people on discord to tell everyone to roll back or stay away from new versions. 

### Reproduction Steps

above

### Expected Result

above

### Screenshots and Videos

![seq](https://github.com/Fabricators-of-Create/Create/assets/4656436/48bf3109-e4c3-4782-9108-fbe6cea92583)

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.19.2

**Comment by IThundxr** [comment]
> I don't understand why the code from that plugin cannot be merged here. REI API hasn't changed in ages, those fixes have worked perfectly for months.

The dev can PR it if they wish and we will merge it.

> I also don't understand the logic for keeping a public version on CF that has known issues, including crashes, whose fixes are already available. Why cannot be updated more frequently so that at least the known stuff is fixed and the mod can actually be used rather than force people on discord to tell everyone to roll back or stay away from new versions.

There are other bugs that we are debugging and fixing, making multiple releases takes a lot of time and effort with testing, hence why we rather bunch up fixes instead of making tons of releases with a few fixes each.
