### ISSUE TITLE
REI crash

### ISSUE THREAD

**Issue by 0xmayro** [Fabricators-of-Create/Create#1395]
### Describe the Bug

When going into one of Create's tabs in REI recipe gui the game crashes.

### Reproduction Steps

1. open the inventory.
2. open the recipe of a block that can be created using Create
3. go into one of Create's tabs in REI.
4. move your cursor over the recipe area in the window and wait a few seconds.

### Expected Result

I expect the game to not crash.

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/136232552/4aa31450-7346-4b9a-8b10-29d07426f822

### Crash Report or Log

https://pastebin.com/pgnAbtMy

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

BetterF3-7.0.2-Fabric-1.20.1.jar
Chipped-fabric-1.20.1-3.0.4.jar
Copycats-fabric.1.20.1-1.2.2.jar
ExtendedDrawers-2.1.1+mc.1.20.1.jar
RoughlyEnoughItems-12.0.684-fabric.jar
Steam_Rails-1.5.3+fabric-mc1.20.1.jar
architectury-9.2.14-fabric.jar
athena-fabric-1.20.1-3.1.2.jar
camerautils-fabric-1.20.1-1.0.9.jar
cardinal-components-api-5.2.2.jar
cloth-config-11.1.118-fabric.jar
continuity-3.0.0-beta.4+1.20.1.jar
create-fabric-0.5.1-f-build.1335+mc1.20.1.jar
create-structures-0.1.1-1.20.1-FABRIC.jar
createdeco-2.0.1-1.20.1-fabric.jar
fabric-carpet-1.20-1.4.112+v230608.jar
farmers-delight-fabric-1.4.3.jar
indium-1.0.30+mc1.20.4.jar
iris-mc1.20.1-1.6.17.jar
krypton-0.2.3.jar
lambdynamiclights-2.3.2+1.20.1.jar
lazydfu-0.1.3.jar
litematica-fabric-1.20.1-0.15.3.jar
lithium-fabric-mc1.20.1-0.11.2.jar
malilib-fabric-1.20.1-0.16.3.jar
memoryleakfix-fabric-1.17+-1.1.5.jar
modmenu-7.2.2.jar
qfapi-7.5.0_qsl-6.1.2_fapi-0.91.0_mc-1.20.1.jar
quilt-kotlin-libraries-2.1.3+kt.1.9.10+flk.1.10.10.jar
reeses_sodium_options-1.7.2+mc1.20.1-build.101.jar
resourcefullib-fabric-1.20.1-2.1.23.jar
sliceanddice-fabric-3.1.0.jar
sodium-extra-0.5.4+mc1.20.1-build.115.jar
sodium-fabric-0.5.8+mc1.20.1.jar
starlight-1.1.2+fabric.dbc156f.jar
worldedit-mod-7.2.15.jar

### Additional Context

I use quilt

**Comment by IThundxr** [comment]
Fixed in dev already, search for if the same issue has already been reported next time
