### ISSUE TITLE
JEI incorrectly shows raw redstone ore as millable

### ISSUE THREAD

**Issue by ST-DDT** [Fabricators-of-Create/Create#1398]
### Describe the Bug

JEI shows the raw redstone ore as millable by the small millstone, but it isn't.

### Reproduction Steps

- Place a small millstone and power it
- Throw a raw redstone ore in it
- Wait a minute
- Right click the millstone and you get the raw redstone ore back

### Expected Result

- Either get redstone dust
- Or not having the JEI recipe show up

### Screenshots and Videos

![grafik](https://github.com/tom5454/Create-Ore-Excavation/assets/1579362/4fb6b91c-5188-441d-b96b-935aa183ab6e)
![grafik](https://github.com/tom5454/Create-Ore-Excavation/assets/1579362/c2431605-c77b-4043-b496-bd5dc20b9273)

### Operating System

Win11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

- createoreexcavation-fabric-1.20-1.4.3 (also reproducible on 1.4.0, didn't test older versions)

### Additional Context

Created by request:

- https://github.com/tom5454/Create-Ore-Excavation/issues/74#issuecomment-2018571836

**Comment by TropheusJ** [comment]
this seems to have been resolved on ore excavation's end.
