### ISSUE TITLE
Inverted Threshold Switches momentarily power on world load

### ISSUE THREAD

**Issue by JordanL2** [Fabricators-of-Create/Create#1399]
### Describe the Bug

When the world is loaded, any threshold switch that is configured to be powered ON when the container is BELOW the threshold will momentarily power on, even if the level is actually above the threshold.

### Reproduction Steps

1. Place a chest, fully load it with items
2. Place a threshold switch pointed into it, invert signal so it'll power on when below threshold
3. Place a redstone lamp next to threshold switch, it should be off
4. Close the world, then reopen it. The redstone lamp will power on for a split second.

### Expected Result

The redstone lamp does not power on.

### Operating System

Linux

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

connectivity-fabric-1.20.1-4.9.jar
create-fabric-0.5.1-f-build.1335+mc1.20.1.jar
cupboard-fabric-1.20.1-2.3.jar
fabric-api-0.92.0+1.20.1.jar
fabric-carpet-1.20-1.4.112+v230608.jar
indium-1.0.30+mc1.20.4.jar
itemscroller-fabric-1.20.1-0.20.0.jar
jei-1.20.1-fabric-15.3.0.4.jar
lithium-fabric-mc1.20.1-0.11.2.jar
malilib-fabric-1.20.1-0.16.3.jar
minihud-fabric-1.20.1-0.27.0.jar
shulkerboxtooltip-fabric-4.0.4+1.20.1.jar
sodium-fabric-0.5.8+mc1.20.1.jar
tweakeroo-fabric-1.20.1-0.17.1.jar

**Comment by TropheusJ** [comment]
same problem as #1213
