### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by AbnormalMatrix** [Fabricators-of-Create/Create#14]
Hello,
Is there a list of things that have already been ported and ones that have not been ported yet?
I think this would be a lot easier to contribute.
Thanks

**Comment by TropheusJ** [comment]
things still left to do, really just anything that errors. As of writing this, there's 1031 errors. We don't really have a list, but there are a few things that cause a significant number of errors:
- item/fluid interactions (we're using [LBA](https://github.com/AlexIIL/LibBlockAttributes) for this)
- misc events found all over the codebase 
- configs (we're planning to use [Conrad](https://github.com/Haven-King/Conrad) for those)
- worldgen (depends on configs)
- JEI compat -> REI compat
- recipes/in-world processing 

There's tons of other errors, but these are all significant sources.

**Comment by TropheusJ** [comment]
There’s now 0 errors left to fix which prevent compiling. Now we need to deal with all the errors and crashes that come post-launch.

**Comment by AbnormalMatrix** [comment]
I'll try to contribute, I really want to see this completed but I do all my programming in Python so I might not be able to do anything.

**Comment by TropheusJ** [comment]
We have made it to the title screen! 🎉

**Comment by vos6434** [comment]
Why not use Github Projects for the todo?

**Comment by TropheusJ** [comment]
closing this, no need for it to stay open. We will (probably) set up some form of a todo list soon.
