### ISSUE TITLE
long term TODOs

### ISSUE THREAD

**Issue by TropheusJ** [Fabricators-of-Create/Create#140]
# Compat
- Alloy Forgery
- Tech Reborn
- More Tags
- Compatibility with common fabric tags
# Refactors
- [maybe] move transfer to use Fabric stuff directly instead of a bridge (it's a pretty invasive change but may be necessary for some potential issues)

**Comment by sylv256** [comment]
i'd like to interject for a moment
what you're referring to as create is, in fact, create + fabric.

**Comment by JieningYu** [comment]
What kind of compat with tech reborn?(like replacing metal sheets or just recipes for crushing?)

**Comment by TropheusJ** [comment]
Compat here really just means recipes for everything

**Comment by michlbro** [comment]
This’ll probably be a stretch (and maybe overpowered) but compat for Mi? (Modern Industrialisation) E.g Mechanical press is able to turn copper rods into copper rings, compressing coal dust into coal.

**Comment by AlphaMode** [comment]
I think it would be better if those mods added compat for create instead

**Comment by JieningYu** [comment]
> I think it would be better if those mods added compat for create instead

But Create for fabric is still testing and we need to add compat with other mods first to work with other mods instead to let modders to add compat themselves with create.

**Comment by AlphaMode** [comment]
I'm talking about recipe compat not mod incompat

**Comment by JieningYu** [comment]
https://github.com/JieningYu/CreatePlus
My datapack for create fabric compat.
