### ISSUE TITLE
Crash when setting fluid cargo condition on train schedule

### ISSUE THREAD

**Issue by pauverblom** [Fabricators-of-Create/Create#1400]
### Describe the Bug

Whenever I set a train schedule with any fluid cargo condition, the game crashes.

### Reproduction Steps

1. Open minecraft with create installed
2. Set any train schedule on a station with any fluid cargo condition
3. Accept the changes to the schedule

Game Crash

### Expected Result

No game crash.

### Crash Report or Log

https://pastebin.com/kKkVVJU1

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Sodium
Sodium Extra

**Comment by IThundxr** [comment]
Known issue & fixed in dev already
