### ISSUE TITLE
Using fluid cargo conditions crashes the game when using train schedules 

### ISSUE THREAD

**Issue by Acea1paca** [Fabricators-of-Create/Create#1401]
### Describe the Bug

Using fluid conditions with a train schedule makes the game crash when confirming 

### Reproduction Steps

1.use a train schedule 
2.select "fluid cargo condition"
3.click the tick
4.click the exit tick

### Expected Result

The game crashes 

### Crash Report or Log

https://pastebin.com/S5X5SBW3

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

[Create Fabric (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[YUNG's API (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric)
[Trinkets (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/trinkets)
[YUNG's Better Ocean Monuments (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments-fabric)
[EMI (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/emi)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Cadmus (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/cadmus)
[YetAnotherConfigLib (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/yacl)
[Snowy Spirit (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/snowy-spirit)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Handcrafted (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
[Create: Steam 'n' Rails (by mattentosh)](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Forge Config API Port (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[End Remastered [Fabric] (by jack_bagel)](https://www.curseforge.com/minecraft/mc-mods/endremastered-fabric)
[YUNG's Extras (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras-fabric)
[MoreMcmeta Emissive Textures (Fabric) (by soir20)](https://www.curseforge.com/minecraft/mc-mods/moremcmeta-emissive-fabric)
[[ETF] Entity Texture Features - [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric)
[MoreMcmeta (Fabric) (by soir20)](https://www.curseforge.com/minecraft/mc-mods/moremcmeta-fabric)
[Hybrid Aquatic (by HybridLabs)](https://www.curseforge.com/minecraft/mc-mods/hybrid-aquatic)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[ewewukek's Musket mod (by ewewukek)](https://www.curseforge.com/minecraft/mc-mods/ewewukeks-musket-mod)
[Useless Reptile (by Nord_Act)](https://www.curseforge.com/minecraft/mc-mods/useless-reptile)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Mutant Monsters [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/mutant-monsters)
[Enchancement (by MoriyaShiine)](https://www.curseforge.com/minecraft/mc-mods/enchancement)
[Sodium (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/sodium)
[ESSENTIAL Mod (by SparkUniverse_)](https://www.curseforge.com/minecraft/mc-mods/essential-mod)
[[EMF] Entity Model Features [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-model-features)
[Aquamirae (Fabric) (by Obscuria)](https://www.curseforge.com/minecraft/mc-mods/aquamirae-fabric)
[YUNG's Better Jungle Temples (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples-fabric)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Cosmetic Armor [FABRIC] (by Apace)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric)
[Continents (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/continents)
[Mighty Mail (Fabric) (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mighty-mail-fabric)
[Moyai (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/moyai)
[Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[Harvest Scythes (by LordDeatHunter)](https://www.curseforge.com/minecraft/mc-mods/harvest-scythes)
[Global Packs (by JTK222)](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack)
[Respawnable Pets (by MoriyaShiine)](https://www.curseforge.com/minecraft/mc-mods/respawnable-pets)
[Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
[Naturalist (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/naturalist)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Obscure API (Fabric) (by Obscuria)](https://www.curseforge.com/minecraft/mc-mods/obscure-api-fabric)
[Small Ships [Fabric & Forge] (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[DarkInventory - Keep Inventory On (Fabric/Forge) (by GamerPotion)](https://www.curseforge.com/minecraft/mc-mods/darkinventory-keep-inventory-on)
[Tectonic (by Apollo)](https://www.curseforge.com/minecraft/mc-mods/tectonic)
[Create Enchantment Industry Fabric (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry-fabric)
[SnowyLeavesPlus (by theRookieCoder)](https://www.curseforge.com/minecraft/mc-mods/snowyleavesplus)
[YUNG's Better Desert Temples (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples-fabric)
[ToolTipFix (by Kyrptonaught)](https://www.curseforge.com/minecraft/mc-mods/tooltipfix)
[Create Slice & Dice (by possible_triangle)](https://www.curseforge.com/minecraft/mc-mods/slice-and-dice)
[Continuity (by Pepper_Bell)](https://www.curseforge.com/minecraft/mc-mods/continuity)
[You've Goat to be Kidding Me! (by plantspookable)](https://www.curseforge.com/minecraft/mc-mods/goated)
[Simple Voice Radio (by CodinGlitch)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-radio)
[Visuality (by PinkGoosik)](https://www.curseforge.com/minecraft/mc-mods/visuality)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Argonauts (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/argonauts)
[Framework (Fabric) (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework-fabric)
[Create: Copycats+ (by Lysine)](https://www.curseforge.com/minecraft/mc-mods/copycats)
[Nullscape (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/nullscape)
[YUNG's Better Strongholds (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds-fabric)
[Voice Chat Interaction (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/voice-chat-interaction)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[End's Phantasm (by Lyof429)](https://www.curseforge.com/minecraft/mc-mods/phantasm)
[Just Enough Farmer's Recipes (by Anxxitty__)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-jei-plugin)

### Additional Context

One other user has had this issue as far as I know so it is not a only me problem

**Comment by IThundxr** [comment]
Known issue & fixed in dev already
