### ISSUE TITLE
Showing bulk washing tooltip crash in RoughlyEnoughltems

### ISSUE THREAD

**Issue by MeltingDiamond** [Fabricators-of-Create/Create#1402]
### Describe the Bug

Showing bulk washing output tooltip crashes the game instead of showing item name as tooltip. I use curseforge modloader.

### Reproduction Steps

1. Go to bulk wasing of any item in RoughlyEnoughltems 
2. Hover over output from washing
3. Game crashes

I get the error:
The game crashed whilst getting tooltips
Error: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2

### Expected Result

I expect it to show the name of the item as a tooltip, but the game crashes instead.

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.19.2

### Other Mods

https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items   RoughlyEnoughltems-9.1.682-fabric.jar
https://www.curseforge.com/minecraft/mc-mods/architectury-api              architectury-6.6.92-fabric.jar
https://www.curseforge.com/minecraft/mc-mods/cloth-config                    cloth-config-8.3.115-fabricjar
fabric-api-O.77.O+1.19.2.jar

**Comment by IThundxr** [comment]
Known issue, fixed in dev

**Comment by rilakuma123** [comment]
Are users expected to wait another 6 months for the next Create Fabric patch release with that fix? I've noticed Create Fabric tends to prefer much bigger releases, despite ironically being called "patches" with your versioning scheme.
