### ISSUE TITLE
Crash when placing create blocks (Hashmap)

### ISSUE THREAD

**Issue by Squ-Cog** [Fabricators-of-Create/Create#1404]
### Describe the Bug

When placing down blocks from create, I will sometimes randomly get a crash to desktop. This is very inconsistent but will happen often when placing down a lot of blocks.

### Reproduction Steps

1. Place someting like a belt or a funnel
2. 1 out of 20 times crash

### Expected Result

I checked the report itself but I could't find a conflict, this also happens without sodium and iris.

### Crash Report or Log

https://gist.github.com/Squ-Cog/f7b4ebf8819f16d54dbbcba8eb01335f
https://gist.github.com/Squ-Cog/7307ffda21dbe12679e8afaa490890f0

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

https://pastebin.com/MDkc312b

**Comment by IThundxr** [comment]
Sound physics remastered is incompatible with create due to calling non thread safe code off thread.
