### ISSUE TITLE
Unable to save schematic to symbolic link directory

### ISSUE THREAD

**Issue by FeedTheChunk** [Fabricators-of-Create/Create#1405]
### Describe the Bug

Create is unable to save a schematic to a folder that is a symbolic link.

[11:53:58] [Render thread/ERROR]: An error occurred while saving schematic [factory_empty.nbt]
java.nio.file.FileAlreadyExistsException: /mnt/NVME2/home/{redacted}/Downloads/prism_launcher/instances/Create Extra/.minecraft/schematics

However that directory is a sym link point to another location.

### Reproduction Steps

1. Create a building / contraption
2. Select the building / contraption with a Schematic and Quill
3. Right click to save 
4.   Failed to save schematic check logs for details
...

### Expected Result

I would have expected that it would save the schematic by following the symbolic link.

### Screenshots and Videos

![2024-03-28_12 07 32](https://github.com/Fabricators-of-Create/Create/assets/35508630/6b66a711-0d9e-4b30-8311-340e0fc0ca2e)

### Operating System

Kubuntu 23.10 x86_64

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Mods:
  [✔] AdaptiveTooltips-1.3.0-fabric-1.20.2
  [✔] Adorn-5.0.1+1.20.1-fabric
  [✔] advancementinfo-1.20-fabric0.83.0-1.4
  [✔] AdvancementPlaques-1.20.1-fabric-1.4.11
  [✔] AmbientSounds_FABRIC_v5.3.5_mc1.20.1
  [✔] antighost-1.20-fabric0.83.0-1.1.5
  [✔] appleskin-fabric-mc1.20.1-2.5.1
  [✔] architectury-9.1.12-fabric
  [✔] assortedlib-fabric-1.20.1-3.0.2
  [✔] azure-paxels-1.20.2-1.0.10
  [✔] badpackets-fabric-0.4.3
  [✔] balm-fabric-1.20.1-7.2.1
  [✔] BetterF3-7.0.2-Fabric-1.20.1
  [✔] betterstats-3.7.1+fabric-1.20.1
  [✘] blur-3.1.0.jar (disabled)
  [✘] bobby-5.0.1.jar (disabled)
  [✔] capes-1.5.2+1.20-fabric
  [✔] cardinal-components-api-5.2.2
  [✔] chat_heads-0.10.31-fabric-1.20
  [✔] CITResewn-1.1.3+1.20
  [✔] clickthrough-1.20-fabric0.83.0-0.4.1
  [✔] cloth-config-11.1.118-fabric
  [✔] continuity-3.0.0-beta.4+1.20.1
  [✔] CraterLib-Fabric-1.20-1.1.1
  [✔] create_enchantment_industry-1.2.12
  [✔] create-0.5.1-d-build.1162+mc1.20.1
  [✔] create-structures-0.1.1-1.20.1-FABRIC
  [✔] createaddition-fabric+1.20.1-0.9.0
  [✔] createbigcannons-fabric-1.20.1-0.5.3.b
  [✔] createdeco-2.0.1-1.20.1-fabric
  [✔] creategoggles-1.20.1-0.5.5.f-[FABRIC]
  [✔] CreativeCore_FABRIC_v2.11.16_mc1.20.1
  [✔] CullLessLeaves-1.3.0
  [✔] dark-loading-screen-1.6.14
  [✔] Debugify-1.20.1+2.0
  [✔] diggusmaximus-1.5.9-1.20
  [✘] dynamic-fps-3.3.3+minecraft-1.20.0.jar (disabled)
  [✘] emotecraft-for-MC1.20.1-2.2.7-b.build.50-fabric.jar (disabled)
  [✔] enhancedblockentities-0.9+1.20
  [✔] entity_model_features_fabric_1.20.1-1.2.3
  [✔] entity_texture_features_fabric_1.20.1-5.2.2
  [✔] entityculling-fabric-1.6.2-mc1.20.1
  [✔] ExtendedDrawers-2.1.1+mc.1.20.1
  [✔] extendeddrawersaddon-1.0.2
  [✔] fabric-api-0.91.0+1.20.1
  [✔] fabric-carpet-1.20-1.4.112+v230608
  [✔] fabric-language-kotlin-1.10.17+kotlin.1.9.22
  [✔] fabrishot-1.10.1
  [✔] fancymenu_fabric_2.14.13_MC_1.20.1
  [✔] fastquit-3.0.0+1.20+
  [✔] feytweaks-1.20-1.2.7
  [✔] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
  [✔] Gamma-Utils-1.7.16-mc1.20.1
  [✔] Iceberg-1.20.1-fabric-1.1.18
  [✔] ImmediatelyFast-Fabric-1.2.10+1.20.4
  [✔] indium-1.0.27+mc1.20.1
  [✔] InventoryProfilesNext-fabric-1.20-1.10.9
  [✔] iris-mc1.20.1-1.6.11
  [✔] jei-1.20.1-fabric-15.2.0.27
  [✔] journeymap-1.20.1-5.9.18-fabric
  [✔] konkrete_fabric_1.8.0_MC_1.20.1
  [✔] krypton-0.2.3
  [✔] lambdynamiclights-2.3.2+1.20.1
  [✔] language-reload-1.5.10+1.20.1
  [✔] libIPN-fabric-1.20-4.0.1
  [✔] litematica-fabric-1.20.1-0.15.3
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] malilib-fabric-1.20.1-0.16.3
  [✔] memoryleakfix-fabric-1.17+-1.1.5
  [✔] midnightlib-fabric-1.4.1.1
  [✔] minihud-fabric-1.20.1-0.27.0
  [✔] mod_sets-intermediary-1.5.0+sha.a17d09c+1.20.1
  [✔] modelfix-1.15-fabric
  [✔] modmenu-7.2.2
  [✔] MouseTweaks-fabric-mc1.20-2.25
  [✔] NoChatReports-FABRIC-1.20.1-v2.2.2
  [✔] notenoughanimations-fabric-1.7.0-mc1.20.1
  [✔] nvidium-0.2.3-beta
  [✔] Patchouli-1.20.1-84-FABRIC
  [✘] PresenceFootsteps-1.9.1.jar (disabled)
  [✔] recursive-resources-2.5.2+1.20
  [✔] reeses_sodium_options-1.6.5+mc1.20.1-build.95
  [✘] replaymod-1.20.1-2.6.14.jar (disabled)
  [✔] Resourcify (1.20-1.20.1-fabric)-1.3.0
  [✔] RPRenames-1.20.2-fabric-0.7.2
  [✔] shulkerboxtooltip-fabric-4.0.4+1.20.1
  [✔] SimpleRPC-fabric-1.20-3.2.4
  [✔] skinlayers3d-fabric-1.6.2-mc1.20.1
  [✔] sliceanddice-fabric-3.0.0
  [✔] sodium-extra-0.5.1+mc1.20.1-build.112
  [✔] sodium-fabric-mc1.20.1-0.5.3
  [✘] sound-physics-remastered-fabric-1.20.1-1.3.1.jar (disabled)
  [✔] spark-1.10.53-fabric
  [✔] Steam_Rails-1.5.1+fabric-mc1.20.1
  [✔] travelers-backpack-1.20.1-9.1.9
  [✔] tweakeroo-fabric-1.20.1-0.17.1
  [✔] visuality-0.7.1+1.20
  [✘] voicechat-fabric-1.20.1-2.5.0.jar (disabled)
  [✔] vt-downloader-2.0.8+1.20.1
  [✔] wthit-fabric-8.5.0
  [✔] yet-another-config-lib-fabric-3.2.1+1.20
  [✔] Zoomify-2.11.2

**Comment by TropheusJ** [comment]
this is a java issue. you need to use a newer version. see #1321

**Comment by FeedTheChunk** [comment]
Thank you.  Updating Java to v21 fixed the issue.
