### ISSUE TITLE
crash when hovering over an item icon

### ISSUE THREAD

**Issue by teacond** [Fabricators-of-Create/Create#1406]
### Describe the Bug

when you hover over the result of processing an item in create, a crash occurs

### Reproduction Steps

1. Open any item processing menu in create
2. Hover over the processing result
3. Сrash

### Expected Result

opening the hover menu

### Screenshots and Videos

[Запись экрана от 2024-03-28 23-51-05.webm](https://github.com/Fabricators-of-Create/Create/assets/100463274/d2e2efe1-d063-4b33-823b-8bad806118e2)

### Crash Report or Log

https://pastebin.com/RCREXzHZ

### Operating System

Fedora 39

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

architectury 9.2.14
cloth config 11.1.118
create enchantment industry 1.2.16
croptopia 3.0.4
Cull Less Leaves 1.3.0
cupboard 2.6
EBE 0.9
EpheroLib 1.2.0
fabric API  0.92.0
ferritCore 6.0.1
immersive aircraft 0.7.5
indium 1.0.30
iris flywheel compat 0.2.4
iris 1.6.17
journey map 5.9.20
lithium 0.11.2
man of many planes 0.0.3
mod menu 7.2.2
noisium 1.0.2
nvidium 0.2.6
reeses sodium options 1.7.2
REI 12.0.684
smooth chunk 3.6
sodium extra 0.5.4
sodium 0.5.8
sound physics 1.1.2
starlight 1.1.2
steam rails 1.5.3
yet another config lib 3.2.2
tl skin cape 1.32

**Comment by IThundxr** [comment]
Known issue, fixed in dev, for now either use jei or emi
