### ISSUE TITLE
Throwing tridents will sometime crash the game

### ISSUE THREAD

**Issue by SpaceNerd95251** [Fabricators-of-Create/Create#1407]
### Describe the Bug

Ever since v0.5.1.f, sometimes throwing a trident will crash the game

### Reproduction Steps

1. Throw trident
2. Keep throwing until it crashes
3. Might help to have loyalty on it, I think it crashes more often when returning to the player
...

### Expected Result

Expected result: not crashing when using a trident

### Crash Report or Log

https://pastebin.com/bY4XvxJC

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Mods can be found in the crash log

**Comment by TropheusJ** [comment]
the relevant code has been rewritten, seems to be working fine
