### ISSUE TITLE
16-stackable Filtering Bug

### ISSUE THREAD

**Issue by cshcrafter** [Fabricators-of-Create/Create#1408]
### Describe the Bug

Setting funnel filters to a 16-stackable item automatically sets it to 64 items instead of the * (allow any) setting.

### Reproduction Steps

1. Place a brass funnel, any orientation
2. Acquire a 16-stackable item such as armour stands or eggs
3. Set the filter on the funnel to said item and observe the error.

### Expected Result

Expected behaviour would be for it to have the * (allow any) setting after one click as is the case for any other 64-stackable item

### Screenshots and Videos

N/A

### Crash Report or Log

N/A

### Operating System

Windows 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

None, just Create.

### Additional Context

Note that singleplayer 0.5.1f seems to work correctly but it is currently untested in multiplayer.

**Comment by TropheusJ** [comment]
can't reproduce on any version
