### ISSUE TITLE
Fluid and redstone stops working in chunks using create

### ISSUE THREAD

**Issue by mrsterner** [Fabricators-of-Create/Create#141]
### Describe the Bug

Some create contraptions induce a chunk-wide bug making fluids and redstone stop updateing rendering them unusable in said chunkm this happens when you leave the chunk and re-enter it. After a while multiple chunks became like this, and only common denominator is those chunks contain create blocks. In attempts to find a specific create block to be the culprit, the only common create blocks in these chunks were Gearboxes, Shafts and Basins. Other than that it varied from chunk to chunk.

The screenshot views button not unpressing, lava and water failing to flow

Notable additions to the server is Lithium which might be involved

Create 0.4d fabric 1.18

### Reproduction Steps

1. Build static iron farm or something which doesnt involve a contraption
2. Wait and unload/load chunks a few times
3. restart server to fix the error temporarly
...

### Expected Result

The expected result would be fluid flowing and buttons unpressed after pressed. The contraptions become overstressed when leaving a chunk also but that might be for another bug report

### Screenshots and Videos

![Untitled](https://user-images.githubusercontent.com/32911664/153718441-1f7ca617-a52e-4be9-a7d6-ee3d6facc316.png)
)

### Crash Report or Log

.

### Operating System

Windows 11

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

- adorn 3.3.1+1.18.1
	- advanced_runtime_resource_pack 0.5.4 via enhancedblockentities
	- alternatecurrent 1.1.0
	- amplified_nether 1.0.1
	- anthropophagy 1.18-2
	- apoli 2.2.2 via origins
	- appleskin 2.3.0+mc1.18.1
	- architectury 3.6.17
	- authme 2.2.0
	- axolotlitemfix 1.1.3
	- bclib 1.3.0
	- besmirchment 1.18-6
	- betteranimalsplus 1.18.1-11.0.4
	- betterdungeons 1.18-0.1.0
	- bettermineshafts 1.18-0.2.0
	- betternether 6.0.10
	- betterstrongholds 1.18-0.1.2
	- bewitchment 1.18-12
	- blue_endless_jankson 1.2.1 via kyrptconfig
	- bosses_of_mass_destruction 1.3.5-1.18
	- botania 1.18.1-427-FABRIC
	- calio 1.4.2 via apoli
	- campanion 3.0.2
	- camsbackpacks 2.9
	- cardinal-components-base 4.0.1 via polymorph
	- cardinal-components-block 4.0.1 via polymorph
	- cardinal-components-entity 4.0.1 via polymorph
	- cardinal-components-item 4.0.1 via polymorph
	- cardinal-components-world 4.0.0 via bosses_of_mass_destruction
	- cavetweaks 1.0
	- cleardespawn 1.1.6
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- cloth-config-lite 2.0.6 via omega-config-gui
	- clumps 8.0.0+5
	- com_electronwill_night-config_core 3.6.5 via globaldataandresourcepacks
	- com_electronwill_night-config_toml 3.6.5 via globaldataandresourcepacks
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- combattweaks 1.8
	- connectiblechains 2.0.1+1.18.1
	- cosmetica 0.3.2 via visuality
	- crawl 0.10.2
	- create mc1.18.1_v0.4d+394
	- damagetilt 1.18-fabric-0.1.2
	- dark-loading-screen 1.6.11
	- darkpaintings 9.0.3
	- disable_custom_worlds_advice 1.4
	- dracomelette 1.18-1
	- dripstone_fluid_lib 1.1.1 via milk
	- dual_riders 1.0.5
	- enhancedblockentities 0.5+1.18
	- experiencebugfix 18
	- extraorigins 1.18-7
	- fabric 0.46.4+1.18
	- fabric-api-base 0.4.2+d7c144a865 via fabric
	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric
	- fabric-blockrenderlayer-v1 1.1.10+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.19+d7c144a865 via fabric
	- fabric-content-registries-v0 0.4.8+d7c144a865 via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric
	- fabric-data-generation-api-v1 1.0.0+3fec4ad9c8 via registrate-fabric
	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric
	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric
	- fabric-item-api-v1 1.3.1+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.6+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.9+d7c144a865 via fabric
	- fabric-keybindings-v0 0.2.7+b4f4f6cd65 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric
	- fabric-mining-level-api-v1 1.0.6+d7c144a865 via fabric
	- fabric-mining-levels-v0 0.1.11+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.4+d7c144a865 via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.4+d7c144a865 via fabric
	- fabric-object-builders-v0 0.7.12+d7c144a865 via fabric
	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via bewitchment
	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric
	- fabric-renderer-api-v1 0.4.11+b0b66fc365 via fabric
	- fabric-renderer-indigo 0.4.15+6825030165 via fabric
	- fabric-renderer-registries-v1 3.2.10+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.12+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.6+713c266865 via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric
	- fabric-resource-loader-v0 0.4.14+713c266865 via fabric
	- fabric-screen-api-v1 1.0.8+d7c144a865 via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric
	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric
	- fabric-tag-extensions-v0 1.2.8+d7c144a865 via fabric
	- fabric-textures-v0 1.0.10+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.8+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.9+d7c144a865 via fabric
	- fabricloader 0.13.1
	- fake-player-api 0.3.0 via create
	- farmersdelight 1.18.1-0.2.0
	- fastfurnace 1.18-4
	- ferritecore 4.1.1
	- fiber 0.23.0-2 via patchouli
	- flywheel 1.18-0.6.1.22 via create
	- forge_tags 1.6 via create
	- forgeconfigapiport 3.1.0 via create
	- fpsreducer 1.25-mc1.18
	- ftbchunks 1801.3.4-build.127
	- ftblibrary 1801.3.5-build.109
	- ftbteams 1801.2.4-build.46
	- geckolib3 3.0.32
	- globaldataandresourcepacks 1.11.3
	- goosik-config 0.2.0 via visuality
	- graveyard 1.5
	- guardvillagers 1.0.6
	- horsestatsvanilla 4.1.10
	- illuminations 1.10.2
	- impaled 1.0.2
	- impersonate 2.4.0 via bewitchment
	- indium 1.0.2-alpha2+mc1.18.1
	- inventorysorter 1.8.4-1.18
	- iris 1.2.0-pre
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- kanos_config 0.1.4+1.14.4-1.17.1 via pehkui
	- kiwi 5.2.5
	- krypton 0.1.6
	- kyrptconfig 1.3.4-1.18 via inventorysorter
	- lazydfu 0.1.2
	- libgui 5.0.0-beta.2+1.18-rc1 via horsestatsvanilla
	- libninepatch 1.1.0 via libgui
	- lithium 0.7.7
	- lumiwool 1.2.2
	- maelstrom_library 1.2.3-1.18-rc3 via bosses_of_mass_destruction
	- mavm 1.0.7a
	- milk 0.1.6 via create
	- minecraft 1.18.1
	- mm 2.3 via crawl
	- modmenu 3.0.1
	- mostructures 1.3.0-pre1+1.18
	- mousetweaks 2.22
	- multipart_entities 1.1.4-1.18-rc3 via bosses_of_mass_destruction
	- nears 1.1.2
	- numismatic-overhaul 0.1.8+1.18
	- omega-config 1.2.2-1.18.1 via graveyard
	- omega-config-gui 1.2.1-1.18.1 via reroll
	- onsoulfire 1.18-1
	- org_anarres_jcpp 1.4.14 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_slf4j_slf4j-api 1.7.12 via iris
	- origins 1.3.1
	- oro_config 2.1.0 via cavetweaks
	- owo 0.5.1+1.18
	- patchouli 1.18.1-65-FABRIC
	- pehkui 3.1.0+1.14.4-1.18.1
	- playerabilitylib 1.5.0 via besmirchment
	- polymorph 0.0.19-1.18.1
	- rad 1.0.1
	- ratsmischief 1.3.4
	- reach-entity-attributes 2.1.1 via create
	- registrate-fabric MC1.18.1-1.0.7 via create
	- reroll 1.4.0-1.18.1
	- respawnablepets 1.18-2
	- roughlyenoughitems 7.2.425
	- roughlyenoughresources 2.4.0
	- seedfix 1.0.0 via amplified_nether
	- snowmercy 2.0.1
	- snowrealmagic 3.2.2
	- sodium 0.4.0-alpha6+build.14
	- sound_physics_remastered 1.18.1-1.0.4
	- stacc 1.3.0 via numismatic-overhaul
	- starlight 1.0.1+fabric.0583973
	- step-height-entity-attribute 1.0.0 via bewitchment
	- stoneholm 1.4.2
	- terraform-wood-api-v1 2.0.2 via besmirchment
	- terralith 2.0.12
	- tooltipfix 1.0.4-1.18
	- trinkets 3.2.0
	- twigs 1.1.2
	- visuality 0.4.0
	- yigd 1.2.16
	- yungsapi 1.18-Fabric-35

### Additional Context

It doesnt crash so there is nothing interesting in the log and its hard to replicate without spening time on a server

**Comment by TropheusJ** [comment]
Crash or not, a log could be useful.

**Comment by michlbro** [comment]
> Crash or not, a log could be useful.

I am getting the same weird bug with digital and mrsterner. No warnings or errors are being displayed in the logs, nor it has to do with starlight or lithium (since they are both gone and bug still persists). It might be an issue with the amount of mods in one server. The easiest way to replicate this issue is to sleep in a bed while the chunk with create contraptions are unloaded then sleep near the chunk while it is loaded in. (Or using the nether portal like digital did)
Edit:
Tested the same world without any mods, just fabric, fabric api and create. The weird fluid bug still persists.
However, I've managed to find this in the log while creating a server using my own pc (Exeraton cuts off the log):
```
[18:17:14] [main/WARN]: Error loading class: net/minecraft/class_5616 (java.lang.ClassNotFoundException: net/minecraft/class_5616)
[18:17:14] [main/WARN]: @Mixin target net.minecraft.class_5616 was not found registrate-fabric.mixins.json:accessor.BlockEntityRenderersAccessor
[18:17:17] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zek000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[18:17:19] [main/WARN]: Configuration file .\config\create-common.toml is not correct. Correcting
```
Full log: 
[latest.log](https://github.com/Fabricators-of-Create/Create/files/8056391/latest.log)

**Comment by mrsterner** [comment]
We have boiled it down to Basins, baisins screw tps and chunks completely
no basin removal: https://spark.lucko.me/V45onkWMS7 
after one basin removal: https://spark.lucko.me/ZfgHaG6eC5
after everyone online removed theirs: https://spark.lucko.me/iu9nL8D3OA

**Comment by TropheusJ** [comment]
related issues:
[upstream](https://github.com/Creators-of-Create/Create/issues/2397), [another](https://github.com/Creators-of-Create/Create/issues/2478)
[forge](https://github.com/MinecraftForge/MinecraftForge/issues/8302)

**Comment by TropheusJ** [comment]
I've added a possible solution [here](https://github.com/Fabricators-of-Create/Create/commit/fc44efdca7cef7efa78273172f720f503cca3a93), please try with this build.

**Comment by armuell** [comment]
Using the build linked in the comment directly above this one on a dedicated server seems to have fixed it. I was able to place a basin in a chunk attached to a windmill as well as flowing water with no issues. I moved away from the chunks so they would be unloaded and slept in a bed (also I entered/left the nether) and returned and the water was flowing just fine. I also logged off and back on with no issues. Also there was nothing in the logs.

**Comment by TropheusJ** [comment]
Perfect. @mrsterner, @KonouChan, and @digitaltrucker please test as well.

**Comment by mrsterner** [comment]
This seems to have fixed the issues indeed 
https://spark.lucko.me/Cb1W57E8sD

**Comment by michlbro** [comment]
Ok perfect, this build has fixed the weird fluid and overstressed issues. 
Did a few tests and nothing shows in the logs. All works fine.👍

**Comment by digitaltrucker** [comment]
> We have boiled it down to Basins, baisins screw tps and chunks completely no basin removal: https://spark.lucko.me/V45onkWMS7 after one basin removal: https://spark.lucko.me/ZfgHaG6eC5 after everyone online removed theirs: https://spark.lucko.me/iu9nL8D3OA

That can't be the source of the problem in my world.  I had no basins when the problem occurred.  Also, mine is a single-player world.

**Comment by TropheusJ** [comment]
some other blocks may have been affected as well, just basins were most apparent. please try anyway.

**Comment by digitaltrucker** [comment]
I hate to admit it, but I have no clue how to build from source.  I've just been playing with the posted builds and demonstrating my usual knack for finding obscure bugs.

**Comment by TropheusJ** [comment]
latest build [here](https://github.com/Fabricators-of-Create/Create/actions/runs/1843632865)

**Comment by digitaltrucker** [comment]
Seems to be working fine so far.

**Comment by TropheusJ** [comment]
perfect. reopen if it reappears.
