### ISSUE TITLE
create:ignoreDeployerAttacks does not function as intended.

### ISSUE THREAD

**Issue by Clark919** [Fabricators-of-Create/Create#1410]
### Describe the Bug

As the title suggests. In Create Fabric 0.5.1-f-build.1335+mc1.20.1 this config does not have any notable effect in-game when set to ANY, CREEPERS, or NONE. I've tried this on both a singleplayer and multiplayer server, and by modifying through the in-game menus and config file directly with no results. Mobs will attempt to attack deployers regardless of the config setting.

Installed:
Minecraft 1.20.1
Create Fabric 0.5.1-f-build.1335+mc1.20.1
Fabric 0.15.7
Fabric API 0.92.0+1.20.1

### Reproduction Steps

1. Place a powered deployer in attack mode.
2. Spawn a mob in-front of the deployer.
3. The mob will attempt to attack the deployer. Very noticeable on mobs such as Skeletons and Creepers.
...

### Expected Result

Expected result is for the mob to ignore the deployer if the relevant config setting is set to ALL, but regardless of the setting all mobs act like it is set to NONE.

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
Related to https://github.com/Creators-of-Create/Create/pull/6072
