### ISSUE TITLE
Incompatible with Dash Loader

### ISSUE THREAD

**Issue by SalmonSnakeD** [Fabricators-of-Create/Create#1412]
### Your game crashes during boot if you have "Dash Loader" installed alongside "Create Fabric"

‎ 
### 📂Modloader
Use latest version of `Quilt 1.20.1 v0.24.0` or latest version of `Fabric 1.20.1 0.15.7`
‎ 
‎ 
### 📂Mods
Install the latest version of **Dash Loader** https://modrinth.com/mod/dashloader v5.0.0-beta.2 for 1.20.1
Install the latest version of **Create Fabric** https://modrinth.com/mod/create-fabric v0.5.1-f-build.1335 for 1.20.1

> Install the latest version of **Fabric API** if on Fabric https://modrinth.com/mod/fabric-api/version/0.92.0+1.20.1
> Install the latest version of **QFAPI** if on Quilt https://modrinth.com/mod/qsl/version/7.5.0+0.91.0-1.20.1

And then just launch the game with these mods and it will crash!

‎ 
### Crash Report or Log

https://gist.github.com/User4716/5c1eabda7d382d97836f56a784e395c8

> Operating System: Windows 11
> Mod Version: 0.5.1f

I added FullStack Watchdog, MixinTrace, Not Enough Crashes and StackDeobfuscator to generate a crash report with more details: https://gist.github.com/User4716/242f90eed3c9ed02568b553291114e5f

**Comment by TropheusJ** [comment]
This is caused by porting lib: https://github.com/Fabricators-of-Create/Porting-Lib/issues/73
This will need explicit compatibility.
Very unlikely to be fixed without someone making a PR.

**Comment by Cuteistfox** [comment]
Dashloader is discountinued so this should be closed

**Comment by TropheusJ** [comment]
is that officially stated anywhere or has it just not updated in a while

**Comment by rinebergc** [comment]
On the Developer's discord, as of 12/14/23.
![image](https://github.com/Fabricators-of-Create/Create/assets/74808260/106bdf80-2608-4dc1-ae7f-e7e5adb5dff6)

**Comment by TropheusJ** [comment]
thanks
