### ISSUE TITLE
Texture on glass fluid pipe has holes on the top and bottom

### ISSUE THREAD

**Issue by 02840** [Fabricators-of-Create/Create#1413]
### Describe the Bug

The texture of the glass fluid pipe isn't complete on the top and bottom of the glass part

### Reproduction Steps

1.Place down a pipe, wrench it so it can be glass
2.Fill it up with lava
...

### Expected Result

The glass texture should be complete

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/136162938/269fcb25-bfd7-4238-af67-1b85c41ec95a)

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

architectury
badpackets
cardinal-components
cloth-config
continuity
create_enchantment_industry
create_high_pressure
createaddition
createdeco
create-structures
create-track-map
entityculling
essential
fabric-api
fabric-language-koltin
indium
iris
jei
megane
createsliceanddice
sodium
steam_rails
traveler's backpack
vivecraft (not in use)
vivecraftcompatfabric
vrapi
wthit
XLpackets

**Comment by TropheusJ** [comment]
the model is the same on forge.
