### ISSUE TITLE
Crash with Sit mod

### ISSUE THREAD

**Issue by intellectmind** [Fabricators-of-Create/Create#1415]
### Describe the Bug

That block position is a robotic arm, it has appeared several times already

### Reproduction Steps

The machine kept running and suddenly crashed

### Expected Result

that the bug doesn't appear again

### Crash Report or Log

https://gist.github.com/intellectmind/c62468862c06344899e2154b9189a2aa

### Operating System

windows11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
This is a problem with the [Sit](https://modrinth.com/mod/sit!) mod.
It assumes that all players have gone through the connection events [here](https://github.com/Oth3r/Sit/blob/86676dd0a19a6bb965e0721c0de1b6cc45cb87f3/src/main/java/one/oth3r/sit/Utl.java#L36C47-L36C61), but fake players (deployers) haven't.
Report to them.

**Comment by IThundxr** [comment]
Reported to Sit
