### ISSUE TITLE
Deployers Crash

### ISSUE THREAD

**Issue by EnderDJ1** [Fabricators-of-Create/Create#1417]
### Describe the Bug

When I tried to make an automatic Xp farm by making deployers holding nuggets of experience kill stuff that spawned, my game crashed the moment any of the deployers killed something. i tested with other items and it turns out that whenever a deployr kills anything at all my game immediatly crashes

### Reproduction Steps

1. Spawn mob(or make farm)
2. make a deployer kill it
3. yay your game crashed
4.
...

### Expected Result

I thought that the deployer would kill the mob and collect the xp in the form of a nugget of expereience

### Crash Report or Log

https://docs.google.com/document/d/1Ka3qNeHeTffYwaGHSptqho35OBKpEVlbyfTazcDqDk8/edit?usp=sharing

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Create Goggles
Create Big cannons
Create Enchantment Industry
Create Steam n Rails
Fabric API
Architecury API

### Additional Context

I don't know if this is important but the exit code was -1

**Comment by IThundxr** [comment]
Attach a log

**Comment by EnderDJ1** [comment]
> Attach a log

where do i find the log

**Comment by IThundxr** [comment]
it will be in the crash-reports/ folder inside your minecraft folder

**Comment by TropheusJ** [comment]
you are using 0.5.1-d. this was fixed in 0.5.1-f
