### ISSUE TITLE
Dying causes contraptions in loaded chunks to visually stop spinning

### ISSUE THREAD

**Issue by Oliver-makes-code** [Fabricators-of-Create/Create#142]
### Describe the Bug

If you die, contraptions in loaded chunks visually stop spinning (Only been tested on dedicated server)

### Reproduction Steps

1. Build a contraption in your spawn area
2. Die

### Expected Result

They keep spinning

### Screenshots and Videos

https://cdn.discordapp.com/attachments/834483421068918785/942441833391325254/Minecraft__1.18.1_-_Multiplayer_3rd-party_Server_2022-02-13_09-26-14.mp4 

### Operating System

Windows 11

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

	- alternatecurrent 1.1.0
	- apoli 2.2.2 via origins
	- architectury 3.6.17
	- aurorasdeco 1.0.0+1.18
	- bedrockify 1.4.0+mc1.18.1
	- caffeineconfig 1.0.0 via sodium-extra
	- calio 1.4.2 via apoli
	- camsbackpacks 2.9
	- cardinal-components-base 4.0.0-alpha.1+21w37a via apoli
	- cardinal-components-entity 4.0.0-alpha.1+21w37a via apoli
	- chunky 1.2.164
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.1.48 via bedrockify
	- com_electronwill_night-config_core 3.6.4 via servercore
	- com_electronwill_night-config_toml 3.6.4 via servercore
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- combattweaks 1.8
	- create mc1.18.1_v0.4d+395
	- dripstone_fluid_lib 1.1.1 via milk
	- dynamic_asset_generator 0.2.0
	- excavated_variants 0.1.0
	- fabric 0.46.4+1.18
	- fabric-api-base 0.4.2+d7c144a865 via fabric
	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric
	- fabric-blockrenderlayer-v1 1.1.10+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.19+d7c144a865 via fabric
	- fabric-content-registries-v0 0.4.8+d7c144a865 via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric
	- fabric-data-generation-api-v1 1.0.0+3fec4ad9c8 via registrate-fabric
	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric
	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric
	- fabric-item-api-v1 1.3.1+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.6+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.9+d7c144a865 via fabric
	- fabric-keybindings-v0 0.2.7+b4f4f6cd65 via fabric
	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric
	- fabric-mining-level-api-v1 1.0.6+d7c144a865 via fabric
	- fabric-mining-levels-v0 0.1.11+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.4+d7c144a865 via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.4+d7c144a865 via fabric
	- fabric-object-builders-v0 0.7.12+d7c144a865 via fabric
	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric
	- fabric-renderer-api-v1 0.4.11+b0b66fc365 via fabric
	- fabric-renderer-indigo 0.4.15+6825030165 via fabric
	- fabric-renderer-registries-v1 3.2.10+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.12+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.6+713c266865 via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric
	- fabric-resource-loader-v0 0.4.14+713c266865 via fabric
	- fabric-screen-api-v1 1.0.8+d7c144a865 via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric
	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric
	- fabric-tag-extensions-v0 1.2.8+d7c144a865 via fabric
	- fabric-textures-v0 1.0.10+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.8+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.9+d7c144a865 via fabric
	- fabricloader 0.13.2
	- fake-player-api 0.3.0 via create
	- ferritecore 4.1.1
	- flywheel 1.18-0.6.1.22 via create
	- forge_tags 1.6 via create
	- forgeconfigapiport 3.1.0 via create
	- indium 1.0.2-alpha2+mc1.18.1
	- inspecio 1.2.1+1.18
	- java 17
	- krypton 0.1.6
	- ksyxis 1.1
	- lazydfu 0.1.2
	- libzoomer 0.3.0+1.17.1 via okzoomer
	- lithium 0.7.7
	- milk 0.1.6 via create
	- minecraft 1.18.1
	- modmenu 3.0.1
	- netherchest 3.1
	- notenoughcrashes 4.1.4+1.18.1
	- okzoomer 5.0.0-beta.3+1.17.1
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_joml_joml 1.10.2 via sodium
	- org_quiltmc_quilt-json5 1.0.0 via okzoomer
	- origins 1.3.1
	- perfectaccuracy 1.2
	- phosphor 0.8.1
	- playerabilitylib 1.3.0 via apoli
	- quilt_base 1.0.0+1.18-SNAPSHOT via aurorasdeco
	- quilt_block_extensions 1.0.0+1.18-SNAPSHOT via aurorasdeco
	- reach-entity-attributes 2.1.1 via combattweaks
	- redstonebits 1.6.2
	- registrate-fabric MC1.18.1-1.0.7 via create
	- roughlyenoughitems 7.2.425
	- servercore 1.2.7-1.18.1
	- sodium 0.4.0-alpha6+build.14
	- sodium-extra 0.3.9
	- spruceui 3.3.0+1.17 via okzoomer
	- terraform-wood-api-v1 2.0.2 via aurorasdeco
	- twm 0.4
	- vmp 0.2.0+beta.3.8
	- wthit 4.5.1

### Additional Context

Only been tested on dedicated server

**Comment by TropheusJ** [comment]
This is a flywheel issue, and can be reproduced in singleplayer.

**Comment by PepperCode1** [comment]
This turned out not to be a Flywheel issue, for those interested. The fix commit's description contains more information.
