### ISSUE TITLE
Trains in the nether somehow crash servers

### ISSUE THREAD

**Issue by JXSnack** [Fabricators-of-Create/Create#1420]
### Describe the Bug

Trains weirdly tick in the nether. I'm too sure why this happens, but it's really bad. If you try to enter the nether the server crashes.

### Reproduction Steps

Enter the Nether

### Expected Result

No crash

### Crash Report or Log

https://gist.github.com/JXSnack/9aaf94c1e4bdb4fd4d5587e17ef8ccad

### Operating System

Linux Ubuntu

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Mods zip: https://www.snackbag.net/extras/snacksmp/v19-epic.zip
Modrinth: https://www.snackbag.net/extras/snacksmp/v19-epic-modrinth-hotfix.mrpack
Curseforge: https://www.snackbag.net/extras/snacksmp/v19-epic-curseforge.zip

**Comment by JXSnack** [comment]
Could not attempt to reproduce on 0.5.1f because of another issue when connecting.
Logs: https://gist.github.com/JXSnack/88084072b16b5702af22409b37a3c998

**Comment by TropheusJ** [comment]
outdated addons

**Comment by TropheusJ** [comment]
duplicate of #1154
