### ISSUE TITLE
1.20 | Game crash when attempting to view mechanism recipes with Roughly Enough Items

### ISSUE THREAD

**Issue by Citrinities** [Fabricators-of-Create/Create#1422]
### Describe the Bug

When attempting to look at create recipes with REI which involve some sort of machine, (i.e: fan, crusher, press, etc), the game crashes after a second of having the GUI open.

### Reproduction Steps

1. Install Create Fabric 0.5.1-f
2. Install REI 12.0.684-Fabric
3. Attempt to view a create recipe which shows the machines on the REI recipe GUI
4. Game Crash

### Expected Result

I expect for the game not to crash when attempting to view recipes which use create machines.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/153131086/29b9ce84-c15b-44da-8170-133ed38050d2)
![image](https://github.com/Fabricators-of-Create/Create/assets/153131086/65144d4d-b68a-4124-8bf6-59ff73dd58f5)

### Crash Report or Log

https://pastebin.com/qf9pPxGu

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/153131086/db746e40-304d-4fda-8e37-4a8d5c0f331a)

**Comment by IThundxr** [comment]
Known issue, fixed in dev, please check the issue tracker before opening duplicate issues

**Comment by Citrinities** [comment]
Ah, alright, thank you.
Sorry about that, was looking through here and didn't spot it, so opted to create a new entry, my bad.
