### ISSUE TITLE
DecoderException for map item on paper server

### ISSUE THREAD

**Issue by Platratio34** [Fabricators-of-Create/Create#1425]
### Describe the Bug

Any time I join a paper server where I have a map in my inventory or in an loaded item frame I immediately get disconnected with a io.netty.handler.codec.DecoderException. This also happens when I move a map item into my inventory while on the server.

### Reproduction Steps

1. Join a Paper server
2. Get a map in your inventory OR load a map in an item frame
3. Get disconnected

### Expected Result

Not get disconnected from server

### Crash Report or Log

https://pastebin.com/157pg2wS

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

fabric-api 0.91.0
fabricloader 0.15.7

### Additional Context

The server I am joining is behind a velocity proxy, but neither the paper server or the proxy have anything in their logs other than the join and disconnect messages.

**Comment by TropheusJ** [comment]
using Create on a server that doesn't have Create installed will not work and is not supported. this goes for every content mod.
