### ISSUE TITLE
Many items either partially or completely invisible 

### ISSUE THREAD

**Issue by myntous** [Fabricators-of-Create/Create#1426]
### Describe the Bug

Many items, like the water wheel and blaze burner, are either partially or completely invisible both in inventory and when placed.
Blocks do not appear after reloading. (F3 + A/T)

### Reproduction Steps

1. Install the same mods as the ones provided in the 'other mods' section
2. Load the game
3. Open inventory and search @create in the REI search bar and/or place a block without a texture in the inventory
4. Suffer

### Expected Result

The items should be visible both in the inventory and when placed.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/166260725/13db9b2c-9449-4366-8470-242f4643ecc5)
![image](https://github.com/Fabricators-of-Create/Create/assets/166260725/36a6a6bf-65c7-4bcf-83fd-76a8472eafa3)

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

This modpack is a modified Better Adventures+

AdvancementPlaques-1.20.1-fabric-1.4.11
adventurez-1.4.18
AmbientSounds_FABRIC_v5.2.20_mc1.20.1
Amplified_Nether_1.20.1_v1.2.2
appleskin-fabric-mc1.20-2.5.0
architectury-9.2.14-fabric
auditory-0.0.6-1.20.1
autotag-2.0.2+1.20
bedspreads-fabric-6.2.0+1.20.1
BetterAdvancements-Fabric-1.20.1-0.3.2.161
BetterThirdPerson-Fabric-1.20-1.9.0
blur-3.1.0
bobby-5.0.1
c2me-fabric-mc1.20.1-0.2.0+alpha.11.5
CameraOverhaul-1.4.0-fabric-universal
camerautils-1.20.1-1.0.4
cave_dust-1.4.1
cherishedworlds-fabric-6.1.0+1.20.1
cloth-config-11.1.118-fabric
comforts-fabric-6.3.4+1.20.1
connectiblechains-2.2.1+1.20.1
continuity-3.0.0-beta.4+1.20.1
create-fabric-0.5.1-f-build.1335+mc1.20.1
CreativeCore_FABRIC_v2.10.24_mc1.20.1
CreativeFly-1.2.0-1.20-fabric
cupboard-fabric-1.20.1-2.1
data-loader-1.1.3+1.19.4-1.20-pre5
DiagonalFences-v8.0.0-1.20.1-Fabric
DisableCustomWorldsAdvice-4.1
DistantHorizons-fabric-2.0.2-a-dev-1.20.1
EasyAnvils-v8.0.0-1.20.1-Fabric
EasyMagic-v8.0.0-1.20.1-Fabric
eating-animation-1.9.4+1.20
EnhancedVisuals_FABRIC_v1.6.7_mc1.20.1
entity_model_features_fabric_1.20.1-1.3
entity_texture_features_fabric_1.20.1-5.2.3
entityculling-fabric-1.6.2-mc1.20
exposure-1.20.1-1.4.0-fabric
extra-sounds-2.3.11.20.1lonefelidae16-build.1
fabric-api-0.92.0+1.20.1
fallingleaves-1.15.1+1.20.1
FallingTree-1.20.1-4.3.4
firstperson-fabric-2.2.3-mc1.20
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
herdspanic-1.0.7
HorseBuff-1.20-2.1.2
Iceberg-1.20.1-fabric-1.1.18
Incendium_1.20.4_v5.3.4
indium-1.0.30+mc1.20.4
inmis-2.7.2-1.20.1
inmisaddon-1.0.4
iris-1.7.0-snapshot+mc1.20.1-7f0ecaa-dirty
ItemBorders-1.20.1-fabric-1.2.1
jamlib-0.6.0+1.20
lazydfu-0.1.3
LegendaryTooltips-1.20.1-fabric-1.4.4
libz-1.0.3
lithium-fabric-mc1.20.1-0.11.2
lootr-1.20-0.7.29.75
modmenu-7.1.0
morebannerfeatures-1.2.0-1.20
moremobvariants-fabric+1.20-1.2.2
mousewheelie-1.11.1+mc1.20-pre2
notenoughanimations-fabric-1.6.4-mc1.20
Nullscape_1.20.4_v1.2.4
PresenceFootsteps-1.9.0
Prism-1.20.1-fabric-1.0.5
PuzzlesLib-v8.0.7-1.20.1-Fabric
replaymod-1.20.1-2.6.13
right-click-harvest-3.2.2+1.19.x-1.20.1-fabric
RoughlyEnoughItems-12.0.684-fabric
shulkerboxtooltip-fabric-4.0.4+1.20.1
smoothswapping-0.9.3.1-1.20.2-fabric
sodium-fabric-0.5.8+mc1.20.1
soulfired-1.20.1-3.2.0.0-fabric
soundphysics-fabric-1.20.1-1.1.1
Structory_1.20.2_v1.3.4
tectonic-mod-1.19.3-v2.2
tiered-1.3.2
TinySkeletons-v8.0.0-1.20.1-Fabric
trade-cycling-fabric-1.20.1-1.0.5
trinkets-3.7.1
UniversalBoneMeal-v8.0.0-1.20.1-Fabric
VanillaTweaks-fabric-1.20.1-1.5.69
visuality-0.7.0+1.20
wakes-0.1.6
weaponmaster-multi-fabric-1.20.1-3.0.5
worldedit-mod-7.2.15
Xaeros_Minimap_24.0.3_Fabric_1.20
XaerosWorldMap_1.38.1_Fabric_1.20
YungsApi-1.20-Fabric-4.0.2
YungsBetterDungeons-1.20-Fabric-4.0.3
YungsBetterMineshafts-1.20-Fabric-4.0.4
YungsBetterStrongholds-1.20-Fabric-4.0.3

Datapacks
New-Desert-Temple
New-End-Cities
New-Ocean-Ruins
New-Ruined-Portals

### Additional Context

I have seen #1039. I have seen #1110. Looks like patch f did not, in fact, fix the problem. Unless this is in some way new.

I have tried reloading textures and chunks.
I have tried disabling shaders and removing them entirely.
I have tried changing the graphics quality from fancy to fabulous to fast.
I have tried disabling all resource packs.
I have tried changing the /flywheel backend settings to every available option.
I have tried removing the following mods and creating new worlds without it fixing the issue:
bobby
Distant Horizons
indium
iris
lithium
sodium

I have tried downgrading mods and creating new worlds, these include:
Create itself to the d patch
indium to every version down to 1.0.21 until it didn't crash on launch due to incompatibilities
sodium to build 27
up- or downgrading flywheel like many posts on the internet suggest is not an option

I reloaded chunks and textures after each launch.
I probably forgot some other things I did.

**Comment by TropheusJ** [comment]
update PuzzlesLib
