### ISSUE TITLE
Threshold Switch cannot detect items from the item vault

### ISSUE THREAD

**Issue by feipangjun** [Fabricators-of-Create/Create#1427]
### Describe the Bug

Threshold Switch cannot detect items from the item vault
I noticed that the Threshold Switch can work properly on build.1376, but when i update to build.1394. The problem floated out. And it still exist on build.1408

### Reproduction Steps

1.install the build.1394 or higher
2.place the item vault and put some item in it
3.place a Threshold Switch and use it to detect items

### Screenshots and Videos

![2024-04-07_21 54 25](https://github.com/Fabricators-of-Create/Create/assets/93204475/2e7a5ae5-2131-4e8b-b747-ca94227656ad)
![2024-04-07_21 57 49](https://github.com/Fabricators-of-Create/Create/assets/93204475/eff892eb-2d77-4423-9f8f-d495a39527a3)

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Fabric loader 0.15.7
Fabric API 0.92

**Comment by vlad-iakovlev** [comment]
Hello @TropheusJ, I think this fix broke compatibility with Extended Drawers mod, MattiDragon/ExtendedDrawers#102. Current behavior is that Threshold Switch thinks that the maximum amount of items in slot is 64, while drawers allow to store multiple stacks and they do it in one slot.

Replacing `long space = Math.min(stackInSlot.getMaxStackSize(), view.getCapacity());` with `long space = view.getCapacity();` may help to solve this. Not sure if it will affect vaults or not.

I'll try to patch this, test with Extended Drawers and let you know the results

**Comment by vlad-iakovlev** [comment]
Just checked, replacing `long space = Math.min(stackInSlot.getMaxStackSize(), view.getCapacity());` with `long space = view.getCapacity();` fixes the issue with Extended Drawers.

**Comment by kiaraly** [comment]
Tested it as well and it doesn't seem to break item vaults. This also is in line with c8685f377db3a6520880ef5f859c1077b043cf95. Would close both this issue and #1459
