### ISSUE TITLE
Game crashes when mousing over Zinc Ingot in REI

### ISSUE THREAD

**Issue by aznshents** [Fabricators-of-Create/Create#1429]
### Describe the Bug

When mousing over the Zinc Ingot in Roughly Enough Items or equivalent mod, the game immediately crashes. 

### Reproduction Steps

1. Log onto a server with Create and REI, 1.20.1
2. Open REI and search for Brass Ingot
3. Hit "r" for Recipe
4. Click on Mixing
5.  Put mouse over the Zinc Ingot picture, game immediately crashes
...

### Expected Result

REI should have shown what the item was named, with no crash.

### Crash Report or Log

https://pastebin.com/LbVpTXuP

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

 advancementinfo 1.20-fabric0.83.0-1.4
	- advancementplaques 1.4.11
	- ambientsounds 5.3.9
	- appleskin 2.5.1+mc1.20
	- architectury 9.2.14
	- authme 7.0.2+1.20
	- auudio 1.0.3
	- balm-fabric 7.2.2
	- betterdeserttemples 1.20-Fabric-3.0.3
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.20-Fabric-4.0.3
	- betterfortresses 1.20-Fabric-2.0.6
	- betterjungletemples 1.20-Fabric-2.0.4
	- bettermineshafts 1.20-Fabric-4.0.4
	- betteroceanmonuments 1.20-Fabric-3.0.4
	- betterpingdisplay 1.1.1
	- betterstrongholds 1.20-Fabric-4.0.3
	- betterthirdperson 1.9.0
	- betterwitchhuts 1.20-Fabric-3.0.3
	- bobby 5.0.1
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- bookshelf 20.1.9
	- borderlessmining 1.1.8+1.20.1
	- bwncr 3.17.0
	- cardinal-components 5.2.2
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- cavedust 1.4.1
	- cherishedworlds 6.1.6+1.20.1
	- cleancut 6.0+mc1.19.1-mc1.20.x
	- cleardespawn 1.1.15
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- clumps 12.0.0.3
	- cobblemon 1.4.1+1.20.1
	- cobblemon_capturexp 1.4-fabric-1.0.2
	- cobblemon_chaining 1.4-fabric-1.0.3
	- cobblemon_counter 1.4-fabric-1.5.0
	- cobblemon_spawn_notification 1.4-fabric-1.3.0
	- cobblemonintegrations 1.0.4
	- cobblemounts 1.2.1
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- cobblepedia 0.5.3
	- cobbreeding 1.5.4
	- collective 7.40
	- continuity 3.0.0-beta.4+1.20.1
	- craftingtweaks 18.2.3
	- create 0.5.1-f-build.1335+mc1.20.1
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.10-2
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_accessors 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_base 2.3.0+1.20.1
	   |    |-- porting_lib_attributes 2.3.0+1.20.1
	   |    |-- porting_lib_common 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    |-- porting_lib_fluids 2.3.0+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.0+1.20.1
	   |    |-- porting_lib_utility 2.3.0+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_brewing 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_client_events 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_entity 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    \-- porting_lib_mixin_extensions 2.3.0+1.20.1
	   |-- porting_lib_extensions 2.3.0+1.20.1
	   |    |-- porting_lib_attributes 2.3.0+1.20.1
	   |    |-- porting_lib_common 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_models 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    |-- porting_lib_fluids 2.3.0+1.20.1
	   |    \-- porting_lib_model_loader 2.3.0+1.20.1
	   |-- porting_lib_networking 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_obj_loader 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    \-- porting_lib_model_loader 2.3.0+1.20.1
	   |-- porting_lib_tags 3.0
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_tool_actions 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_transfer 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    \-- porting_lib_fluids 2.3.0+1.20.1
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        |-- porting_lib_data 2.1.1090+1.20
	        |    \-- porting_lib_gametest 2.1.1090+1.20
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             |-- porting_lib_gametest 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- create_cobblemon 0.3
	- creativecore 2.11.24
	   \-- net_minecraftforge_eventbus 6.0.3
	- ctov 3.4.2
	- cull-less-leaves 1.3.0
	- dismountentity 3.2
	- distanthorizons 2.0.1-a
	- dynamic_fps 3.4.2
	- dynamiccrosshair 7.4.4+1.20
	   \-- yaclx 1.12+1.20.2
	- easiervillagertrading 1.20-fabric0.83.0-1.5.4
	   \-- gbfabrictools 1.3.5+1.20
	- easyanvils 8.0.2
	- easymagic 8.0.1
	- eatinganimationid 1.20+1.9.61
	- emerald_tools 1.6.3
	   \-- pugh_tools 1.6.1
	- enchdesc 17.0.14
	- enhanced_attack_indicator 1.0.4+1.20
	- entityculling 1.6.2-mc1.20.1
	- explorerscompass 1.20.1-2.2.3-fabric
	- fabric-api 0.92.0+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.4+1802ada577
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- fallingleaves 1.15.6
	- farmersdelight 1.20.1-2.0.14+refabricated
	   |-- porting_lib_accessors 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_base 2.3.0+1.20.1
	   |    |-- porting_lib_attributes 2.3.0+1.20.1
	   |    |-- porting_lib_common 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    |-- porting_lib_fluids 2.3.0+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.0+1.20.1
	   |    |-- porting_lib_utility 2.3.0+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_client_events 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_config 2.3.0+1.20.1
	   |    |-- com_electronwill_night-config_core 3.6.6
	   |    |-- com_electronwill_night-config_toml 3.6.6
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_extensions 2.3.0+1.20.1
	   |    |-- porting_lib_attributes 2.3.0+1.20.1
	   |    |-- porting_lib_common 2.3.0+1.20.1
	   |    |-- porting_lib_core 2.3.0+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_lazy_registration 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_loot 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_networking 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_recipe_book_categories 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_registries 2.3.0+1.20.1
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   |-- porting_lib_tags 3.0
	   |    \-- porting_lib_core 2.3.0+1.20.1
	   \-- porting_lib_tool_actions 2.3.0+1.20.1
	        \-- porting_lib_core 2.3.0+1.20.1
	- faster_entity_animations 1.6
	- ferritecore 6.0.1
	- feytweaks 1.20-1.2.7
	   \-- midnightlib 1.4.1
	- fightorflight 0.5.0
	- forgeconfigapiport 8.0.0
	- highlight 2.0.1
	   \-- resourcefullib 2.0.7
	        \-- com_teamresourceful_yabn 1.0.3
	- highlighter 1.1.9
	- iceberg 1.1.18
	- immediatelyfast 1.2.11+1.20.4
	   \-- net_lenni0451_reflect 1.3.2
	- indium 1.0.30+mc1.20.4
	- inventorytotem 3.2
	- iris 1.6.17
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- jade 11.8.0
	- java 17
	- konkrete 1.8.1
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lambdynlights 2.3.2+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- languagereload 1.5.10+1.20.1
	- lazydfu 0.1.3
	- lithium 0.11.2
	- lithostitched 1.1.5
	- livelier-pokemon 1.0.2
	- loadmyresources 1.0.4
	- longerchathistory 1.4
	- lootballs 1.1.1
	- make_bubbles_pop 0.2.0-fabric
	- melody 1.0.3
	- memoryleakfix 1.1.5
	- minecraft 1.20.1
	- modmenu 7.2.2
	- monsters_in_the_closet 1.0.3+1.20
	- moreculling 1.20.4-0.22.1
	   |-- conditional-mixin 0.3.2
	   \-- mixinsquared 0.1.1
	- naturescompass 1.20.1-2.2.3-fabric
	- netherportalfix 13.0.1
	- notenoughanimations 1.7.1
	- owo 0.11.2+1.20
	   \-- blue_endless_jankson 1.2.2
	- patchouli 1.20.1-84-FABRIC
	   \-- fiber 0.23.0-2
	- presencefootsteps 1.9.3
	   \-- kirin 1.15.6+1.20.1
	- puzzleslib 8.1.18
	   \-- puzzlesaccessapi 8.0.7
	- reeses-sodium-options 1.7.2+mc1.20.1-build.101
	- roughlyenoughitems 12.0.684
	   \-- error_notifier 1.0.9
	- roughlyenoughprofessions 2.0.2
	- roughlysearchable 2.6.0+1.20.1
	- showmeyourskin 1.8.0+1.20
	   \-- cicada 0.6.0+1.20.1-minus
	- shulkerboxtooltip 4.0.4+1.20.1
	- sodium 0.5.8+mc1.20.1
	- sodium-extra 0.5.4+mc1.20.1-build.115
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- sspb 3.2.1
	- starterkit 6.5
	- titlefixer 1.0+1.20.1
	- toolstats 16.0.8
	- tooltipfix 1.1.1-1.20
	- travelersbackpack fabric-1.20.1-9.1.11
	   \-- reach-entity-attributes 2.4.0
	- visuality 0.7.1+1.20
	- voicechat 1.20.1-2.5.11
	- waterdripsound 1.19-0.3.2
	- waveycapes 1.4.4
	- wherearemytms 2.1.2-hotfix
	- xaerominimap 24.0.3
	- xaeroworldmap 1.38.1
	- yet_another_config_lib_v3 3.2.2+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- yosbr 0.1.2
	- yungsapi 1.20-Fabric-4.0.4
	   \-- org_javassist_javassist 3.29.2-GA
	- yungsextras 1.20-Fabric-4.0.3
	- zoomify 2.11.2
	   |-- com_akuleshov7_ktoml-core-jvm 0.4.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6

**Comment by TropheusJ** [comment]
this has been fixed in dev
