### ISSUE TITLE
AllArmorMaterials#getName erroneously marked clientside

### ISSUE THREAD

**Issue by TheEpicBlock** [Fabricators-of-Create/Create#143]
[AllArmorMaterials#getName](https://github.com/Fabricators-of-Create/Create/blob/mc1.18/fabric/dev/src/main/java/com/simibubi/create/content/curiosities/armor/AllArmorMaterials.java) is marked clientside despite it not being a clientside method

**Comment by AlphaMode** [comment]
This is a upstream issue

**Comment by AlphaMode** [comment]
To be more clear be make sure to double check that the issues you make aren't something with upstream.
I suggest you make a issue there instead of here
