### ISSUE TITLE
Wrong graphics rendering

### ISSUE THREAD

**Issue by mahiro76** [Fabricators-of-Create/Create#1430]
### Describe the Bug

**There was a graphic rendering error when rendering the "chest", which may be caused by the item"chute" of the mod.**

### Reproduction Steps

1.Place a big chest on the ground.
2.Place a chute on the top of the one of the chest.
3.Open the chest.
4.Then maybe you can see the question.
...

### Expected Result

There will have a effect like this:
![Screenshot_2024-04-08-13-05-33-307_com tungsten fcl](https://github.com/Fabricators-of-Create/Create/assets/154589330/4e37c806-4f2c-425c-a37d-e5af1fc01983)
![Screenshot_2024-04-08-13-05-27-275_com tungsten fcl](https://github.com/Fabricators-of-Create/Create/assets/154589330/2b80ba32-2e7d-4c37-a19d-0e26beac2f46)

### Screenshots and Videos

![Screenshot_2024-04-08-13-05-33-307_com tungsten fcl](https://github.com/Fabricators-of-Create/Create/assets/154589330/ed443bd7-38c3-49e8-8ee1-b04ea307f792)
![Screenshot_2024-04-08-13-05-27-275_com tungsten fcl](https://github.com/Fabricators-of-Create/Create/assets/154589330/1a8f7074-4923-43d2-8c07-bc1dc0370783)

### Operating System

Android(Fold craft launcher)(GPU renderer:freedreno)

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by mahiro76** [comment]
Here is the mod list：
![IMG_20240408_145816](https://github.com/Fabricators-of-Create/Create/assets/154589330/33b3facd-4cd1-4d10-b5b3-7371241a451a)
![IMG_20240408_145747](https://github.com/Fabricators-of-Create/Create/assets/154589330/eea0a1b1-703b-4b90-a333-1fc42d868d24)

**Comment by mahiro76** [comment]
Upon further inspection, it appears that this happens more often when opening a 'chest' when faced with a large number of 'chest'.  But no matter how many and what blocks are near the 'chest', it still will happen.  Maybe it isn't necessarily caused by the 'chutes' alone.  But what is certain is that when this mod and its attachments are removed, the problem will no longer occurs.
@TropheusJ

**Comment by mahiro76** [comment]
I found a similar issue in the issue list:#1441

**Comment by TropheusJ** [comment]
probably a duplicate
