### ISSUE TITLE
Incompatible with Sound Physics Remastered

### ISSUE THREAD

**Issue by PaulRV0709** [Fabricators-of-Create/Create#1431]
### Describe the Bug

Incompatibility with Sound Physics Remastered v1.20.1-1.3.1 on 1.20.1 with latest patch of Create. No crashes, the fabric incompatibility window pops up and says it's incompatible

### Reproduction Steps

1. Install latest patch of Create fabric 1.20.1 and all or any dependencies
2. Install Sound Physics Remastered and all or any dependencies
3. Launch the game
...

### Expected Result

Game doesn't launch and fabric incompatibility window pops up

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/82379138/8e5ab4ac-8545-456b-a6aa-904c0cf4c88d)

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

None should matter. (also my modpack is big)

**Comment by PaulRV0709** [comment]
I did just see the changelog and saw that this was intentional, and that the reason was it was "calling non thread safe code off thread". I don't 100% know what that means, but I know it can be bad, but still at least give us the option to enable compatibility in the config file or something.

**Comment by PaulRV0709** [comment]
I realise now this is an issue with Sound Physics Remastered rather than Create, but still it would be nice if you could toggle this incompatibility flag.

**Comment by IThundxr** [comment]
Due to the mass amounts of concurrency crash reports we've been getting we had to do this, we will remove the breaks when it get's fixed.
