### ISSUE TITLE
Crash caused by manipulator

### ISSUE THREAD

**Issue by intellectmind** [Fabricators-of-Create/Create#1433]
### Describe the Bug

When the manipulator picks up the milk, it will lead to collapse.

### Reproduction Steps

When the manipulator picks up the milk, it will lead to collapse.

### Expected Result

solve problems

### Crash Report or Log

https://gist.github.com/intellectmind/1625b6e25f6ac86b110be8539f41b20d

### Operating System

windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
This is a bug in Enclosure. Has to be fixed on their end.
