### ISSUE TITLE
Server Connection error when loading into singleplayer world

### ISSUE THREAD

**Issue by jahydemon** [Fabricators-of-Create/Create#1434]
### Describe the Bug

Using Create 1.20.1 v1.5.1.f Patch 1 build 1477, when attempting to load into a singleplayer world it gives this screen, followed by sending me to the server list page. I am using a mod pack, so that may be the issue, however everything has run smoothly using Create 1.20.1 v1.5.1.f Patch 1 build 1335.

### Reproduction Steps

1. Put the specified create version into the mods folder
2. Open game
3. Open singleplayer world's list
4.  Select a world
5. Press play
6. Loads to 100% 
7. Gives server error.
...

### Expected Result

The expected result would to be loading into the singleplayer world with no issues.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/166553734/64a808ea-600e-482b-b7ea-caa2709caf51)

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

[modlist.txt](https://github.com/Fabricators-of-Create/Create/files/14923254/modlist.txt)

**Comment by TropheusJ** [comment]
some addons may need to update to the new version.

**Comment by jahydemon** [comment]
I updated all the create addons that were not already the latest version and the problem persists.

**Comment by TropheusJ** [comment]
you need to wait for new updates
