### ISSUE TITLE
Outdated structures cause DFU to process every time they are loaded

### ISSUE THREAD

**Issue by Linguardium** [Fabricators-of-Create/Create#1435]
### Describe the Bug

title. If structure nbt DataVersion doesnt match the game's data version, DFU is forced to process them to update them. Please update your nbt structures as part of datagen to match the mc version you are building for.

### Reproduction Steps

1. open game
2. place structure

### Expected Result

DFU does not need to process structure

### Operating System

N/A

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
Probably affects forge aswell, i'll have a look and update it on forge if that's the case

**Comment by IThundxr** [comment]
Upstream issue, https://github.com/Creators-of-Create/Create/issues/6852
