### ISSUE TITLE
Incompatible with Iris shaders

### ISSUE THREAD

**Issue by dremm-inferniclaw** [Fabricators-of-Create/Create#1436]
### Describe the Bug

Crashes when iris and create fabric run together

### Reproduction Steps

1. make modpack
2. install create and iris
3. start game

...

### Expected Result

Run with shaders on

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
Attach a log

**Comment by BugInYourCode01** [comment]
It worked for me, even with sodium. Then it crashed with Create Iris Oculus Flywheel compat 0.2.1.

**Comment by abidbmt** [comment]
Ive had no issues on the latest version, atleast with Iris Beta

**Comment by Alwis2000** [comment]
> It worked for me, even with sodium. Then it crashed with Create Iris Oculus Flywheel compat 0.2.1.

Try Iris Oculus Flywheel 2.4, its in curseforge I believe

**Comment by BugInYourCode01** [comment]
The Modrinth version is outdated, I know. I just thought that this might be the reason for this problem. Alternatively @dreadstrike-inferniclaw tell us all your mods with the corresponding mod version. For example, Create Fabric 0.5.1-d-build.1161+mc1.20.1 crashed with Iris Shaders, but the next version 0.5.1-f-build.1335+mc1.20.1 worked.

And are Sodium and Indium installed?

**Comment by dremm-inferniclaw** [comment]
Don't use modrinth
Don't have sodium
And I've never heard of indium

**Comment by IThundxr** [comment]
> Don't use modrinth Don't have sodium And I've never heard of indium

please attach a log, also iris depends on sodium

**Comment by TropheusJ** [comment]
closing, still has not provided needed info

**Comment by dremm-inferniclaw** [comment]
I'm sorry. I've been busy in real life. I will get the log today or tomorrow.
