### ISSUE TITLE
Index out of bounds while loading EMI recipes

### ISSUE THREAD

**Issue by drafolin** [Fabricators-of-Create/Create#1439]
### Describe the Bug

The create mod's recipes do not load with EMI. An error log is generated

### Reproduction Steps

1. Load minecraft
2. Join a world
3. Check create's deployment/mixing/mechanical crafting recipes

### Expected Result

The recipes should load correctly

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/66629792/ce8ee6b1-8443-427e-93ff-ea0692e3a3cb)

### Crash Report or Log

https://gist.github.com/drafolin/fd72281ae36ed272419d06e308389253

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

- Dynamic Crosshair Compat
- Presence Footsteps
- Capes
- Concurrent Chunk Management Engine
- EMI
- Staaaaaaaaaaaack
- Autokey
- Autofish
- Flight Assistant
- Very Many Players
- ModernFix
- Model Gap Fix
- Create: Structures
- ItemSwapper
- Entity Texture Features
- Architectury
- Inventory Management
- SleepWarp
- Collective
- Mod Menu
- Elytra Slot
- YetAnotherConfigLib
- Fabric Language Kotlin
- EntityCulling-Fabric
- Prism
- Sounds
- clover
- Forge Config API Port
- Trinkets
- Balm
- Immersive Portals
- Customizable Player Models
- Chat Heads
- Isometric Renders
- YetAnotherConfigLib
- More Culling
- Crafting Tweaks
- Reese's Sodium Options
- Flow
- spark
- Back-burner
- Delightful Creators
- FerriteCore
- EMI Trades
- Create
- CPM SVC Compat
- Mouse Tweaks
- Lootr
- Botania
- Just Enough Breeding
- Jumper's Pizzeria
- Fabric Language Kotlin
- Better Beds
- Simple Hud Enhanced
- Better Mount HUD
- Inventory Profiles Next
- Armor Statues
- Melody
- libIPN
- Spawn Animations
- Create
- Chat Utils Mod
- Stendhal
- Konkrete
- Simple Voice Chat
- EMI Loot
- Create: Steam 'n' Rails
- Load My Resources
- Mineblock's Repeated Utilities
- CICADA
- Beautified Chat Client
- AppleSkin
- LambDynamicLights
- SimplePipeTest
- Client Tweaks
- Cloth Config v11
- FabricSkyBoxes
- Indium
- Continuity
- Noisium
- Sodium Extra
- Sonic Boom
- Jade
- Explosive Enhancement
- Inventory Essentials
- DamageVignette
- Create Utilities
- Clumps
- Dynamic Crosshair
- Fabric API
- Better End
- CC: Tweaked
- Sodium
- Puzzles Lib
- Simple Voice Chat Enhanced Groups
- Journeymap
- Patchouli
- Main Menu Credits
- MapFrontiers
- Carry On
- FancyMenu
- Create: Switzerland
- Mod Loading Screen
- No Chat Reports
- EMI Enchanting
- Just Enough Items
- MiniScaled
- Chest Tracker
- GeckoLib 4
- Damage Numbers
- Lithium
- Entity Model Features
- CC:C Bridge
- Mythic Mounts
- Gravestones
- Searchables
- Portal Gun
- Zoomify
- BadOptimizations
- Forge Config API Port
- CIT Resewn
- Farmer's Delight
- MCPitanLib
- ThreadTweak
- Controlling For Fabric
- Dynamic Fullbright
- Do a Barrel Roll
- FabricSkyBoxes Interop
- Just Enough Professions (JEP)
- Not Enough Crashes
- BetterThanMending
- FastQuit
- Extra Mod Integrations
- BCLib
- EMI Ores
- MixinTrace
- Customizable Player Models
- Inventory HUD +
- Cubes Without Borders
- Freecam (Modrinth Edition)
- Just Enough Effects Descriptions
- Create Ore Excavation
- Spoticraft
- Remove Reloading Screen
- EMIffect
- Debugify
- ImmediatelyFast
- OptiGUI
- Auth Me

### Additional Context
Blasting, haunting, washing and smoking works

**Comment by payphone101** [comment]
affects Create 6.0.1 (NeoForge)

![Image](https://github.com/user-attachments/assets/a5189840-0855-42c3-895e-182736aa9f90)
