### ISSUE TITLE
Option to offset hud elements

### ISSUE THREAD

**Issue by DarianLStephens** [Fabricators-of-Create/Create#144]
### Describe the Suggestion

An option to let you set an X-Y offset for hud elements, notably for the hotbar.
This would let it blend better with mods that might allow you to shift things around.

### Screenshots and Videos

As an example, here's me using Bedrockify's 'screen safe area' feature, which bumps the hotbar off the bottom of the screen a bit:
![2022-02-15_17 57 39](https://user-images.githubusercontent.com/15375876/154010048-0cd3b218-b633-47ae-ac08-74ffac9fa564.png)
It looks a bit strange, and for a while, I thought that's how it was meant to look, until I realized what was happening.

Here's with that Bedrockify option turned off:
![2022-02-15_17 58 59](https://user-images.githubusercontent.com/15375876/154010145-51fdfe12-fb0a-4bad-9562-ada17961d113.png)
Suddenly, everything lines up perfectly. I do still prefer that little bit of space under the hotbar, though.

### Additional Context

This would only really apply when using mods that let you change the position of hud elements, but it would still be nice.

**Comment by AlphaMode** [comment]
Forge has a system for doing this easily with a event that allows for broader capability with other mods. Replicating this on fabric would require some changes to the ui code that would most likely break compatibility with other mods who don't support are system.
The best solution for this would maybe to make a compatibility layer between the two mods.

**Comment by DarianLStephens** [comment]
Couldn't there just be an option in the config to allow you to manually align UI elements?
Botania has a manual offset for the mana bar, couldn't the same sort of thing be applied here?

**Comment by TropheusJ** [comment]
A config option has been added.

**Comment by DarianLStephens** [comment]
Working great, very much appreciated!
![2022-02-18_16 57 56](https://user-images.githubusercontent.com/15375876/154626458-2d789814-4d21-4a6d-8d1a-624962b82343.png)
