### ISSUE TITLE
"count" item ingredient parameter not supported

### ISSUE THREAD

**Issue by BugInYourCode01** [Fabricators-of-Create/Create#1440]
### Describe the Bug

Have I overlooked something or does Create not support the "count" parameter?

`
  "type": "create:compacting",
  "heatRequirement": "heated",
  "ingredients": [
    {
      "count": 4,
      "item": "garnished:cracked_peanut"
    }
  ],
  "results": [
    {
      "amount": 4050,
      "fluid": "garnished:peanut_oil"
    }
  ]
}`

### Reproduction Steps

Create a datapack with this (above) recipe

### Expected Result

4 cracked nuts

### Screenshots and Videos

![2024-04-11_00 20 43](https://github.com/Fabricators-of-Create/Create/assets/163460667/5afb539a-35df-4c77-871e-742f89a8f348)

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
it does not, you need to duplicate the ingredient <count> times

**Comment by BugInYourCode01** [comment]
Why don't you add that?
Is it because packing is based on shaped recipes that have one item per slot?

**Comment by TropheusJ** [comment]
inputs are ingredients, not item stacks. They don't have counts.
