### ISSUE TITLE
Not compatible with Better Trims mod

### ISSUE THREAD

**Issue by gqrshy** [Fabricators-of-Create/Create#1444]
### Describe the Bug

[crash-2024-04-14_16.24.17-client.txt](https://github.com/Fabricators-of-Create/Create/files/14969837/crash-2024-04-14_16.24.17-client.txt)

this is clash log
I get this error only when I add the Better Trims mod and cannot start it.

### Reproduction Steps

I get this error only when I add the Better Trims mod and cannot start it.

### Expected Result

![image](https://github.com/Fabricators-of-Create/Create/assets/88965460/babf2ccf-913b-433c-a54e-55096db3122e)

### Operating System

Win11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
Has nothing to do with create, better trims' iris compat is failing
