### ISSUE TITLE
Singleplayer - Failed to connect to server: unexpected custom data from client. 

### ISSUE THREAD

**Issue by 6adawy** [Fabricators-of-Create/Create#1448]
### Describe the Bug

When using the mod, it fails to create new singleplayer worlds or load existing ones giving me the error "Failed to connect to server: unexpected custom data from client"

### Reproduction Steps

1. Installing mentioned mods
2. Adding Create
3. Load a singleplayer world
...

### Expected Result

Failed to connect to server: unexpected custom data from client

### Screenshots and Videos

<img width="343" alt="1139705134_ScreenShot2020-04-08at8_24_42PM png f13e8d5419412f71429ec00c225e3891" src="https://github.com/Fabricators-of-Create/Create/assets/84728359/99ac5baf-ac18-4d4d-a29e-646e91ff6fbe">

### Crash Report or Log

https://pastebin.com/ARic0jDG

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

- ad_astra 1.15.18
	   \-- javazoom_jlayer 1.0.1
	- ad_astra_giselle_addon 6.6
	- ae2 15.1.0
	   \-- team_reborn_energy 3.0.0
	- ae2mtfix 2.0.0+1.20.1+fabric
	- ae2wtlib 15.2.1-fabric
	- alloy_forgery 2.1.2+1.20
	- ambientsounds 5.3.9
	- amendments 1.20-1.1.19
	   \-- mixinsquared 0.1.1
	- another_furniture 1.20.1-3.0.1
	- apoli 2.9.0
	   |-- additionalentityattributes 1.3.0+1.20.0
	   |-- calio 1.11.0
	   \-- playerabilitylib 1.8.0
	- apugli 2.10.1+1.20.1-fabric
	   \-- midnightlib 1.4.1
	- aqupdgrizzly 1.20-1.6.1
	- architectury 9.2.14
	- automobility 0.4.2+1.20.1-fabric
	   \-- jsonem 0.2.1+1.20
	- bakery 1.1.8
	- basicweapons 1.2.0
	- bclib 3.0.14
	   \-- wunderlib 1.1.5
	- beachparty 1.1.4
	- betterbeds 1.3.0
	- bettercombat 1.8.5+1.20.1
	- betterdeserttemples 1.20-Fabric-3.0.3
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.20-Fabric-4.0.3
	- betterend 4.0.11
	- betterendisland 1.20-Fabric-2.0.6
	- betterfortresses 1.20-Fabric-2.0.6
	- betterfurnacesreforged 1.1.3
	- betterjungletemples 1.20-Fabric-2.0.4
	- bettermineshafts 1.20-Fabric-4.0.4
	- betteroceanmonuments 1.20-Fabric-3.0.4
	- betterstrongholds 1.20-Fabric-4.0.3
	- betterwitchhuts 1.20-Fabric-3.0.3
	- bloomingnature 1.0.6
	   \-- terraform-wood-api-v1 7.0.1
	- bookshelf 20.1.10
	- botanypots 13.0.27
	- botarium 2.3.3
	   \-- team_reborn_energy 3.0.0
	- brewery 1.1.5
	- candlelight 1.2.11
	- cardinal-components 5.2.2
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- cavedust 1.4.1
	- chas 1.20
	- chat_heads 0.10.32
	- chunksfadein 1.0.5-1.20.1
	   |-- com_moandjiezana_toml_toml4j 0.7.2
	   \-- crowdin-translate 1.4+1.19.3
	- cicada 0.6.2+1.20.1-and-below
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- clumps 12.0.0.3
	- clutter 1.20-0.5.7
	- collective 7.40
	- comforts 6.3.5+1.20.1
	   \-- spectrelib 0.13.15+1.20.1
	- connectiblechains 2.2.1+1.20.1
	- connectivity 1.20.1-5.5
	- convenientdecor 0.4.1
	   \-- omega-config 1.4.0+1.20.1
	- creativecore 2.11.24
	   \-- net_minecraftforge_eventbus 6.0.3
	- cristellib 1.1.5
	   \-- blue_endless_jankson 1.2.3
	- croptopia 3.0.3
	- cupboard 1.20.1-2.6
	- customizableelytra 2.1.1+1.20
	- dark-loading-screen 1.6.14
	- darkmodeeverywhere 1.20.1-1.2.2
	- darkutils 17.0.3
	- decorative_blocks 4.1.3
	- display_case 1.0.7
	- do_a_barrel_roll 3.5.4+1.20.1
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- mixinsquared 0.1.1
	- doapi 1.2.9
	   \-- terraform-wood-api-v1 7.0.1
	- doubledoors 5.4
	- dramaticdoors 1.20.1-3.2.1
	- duckling 3.0.0
	- dynamiccrosshair 7.4.4+1.20
	   \-- yaclx 1.12+1.20.2
	- e4mc_minecraft 4.0.1
	- elytraslot 6.3.0+1.20.1
	- epherolib 1.2.0
	- extendedae 1.20-0.2.0-fabric
	   \-- configuration 2.2.0
	- extrakeybinds 0.5.0+1.17-1.19.4
	- fabric-api 0.92.1+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.10
	   \-- mixinextras 0.3.5
	- factory_api 2.1.4
	- fancymenu 3.1.4
	   |-- com_github_keksuccino_japng 0.5.3
	   \-- com_github_rtyley_animated-gif-lib-for-java animated-gif-lib-1.7
	- fastload 3.4.0
	   |-- conditional-mixin 0.3.2
	   |-- fastload-119-0-1-2-compat 3.4.0
	   |-- fastload-1193-compat 3.4.0
	   |-- fastload-1194-compat 3.4.0
	   \-- fastload_fapi_forward 1.0.2
	- firstperson 2.3.4
	- forgeconfigapiport 8.0.0
	- fusion 1.1.1
	- geckolib 4.4.4
	   \-- com_eliotlash_mclib_mclib 20
	- glassential 2.0.1
	- gpumemleakfix 1.20.1-1.8
	- handcrafted 3.0.6
	- herbalbrews 1.0.6
	- heroes 1.1.61
	- immersive_armors 1.6.1+1.20.1
	- indium 1.0.30+mc1.20.4
	- iris 1.6.17
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- jade 11.8.0
	- jadeaddons 5.2.3
	- java 17
	- konkrete 1.8.1
	- kubejs 2001.6.4-build.138
	- leavesbegone 8.0.0
	- letmedespawn 1.2.0
	- livingthings 1.20.1-2.0.2
	- lolmcv 1.5.0
	- lootr 0.7.31.78
	- maxhealthfix 12.0.2
	- mcwbridges 3.0.0
	- mcwdoors 1.1.0
	- mcwfences 1.1.1
	- mcwfurnitures 3.2.2
	- mcwlights 1.0.6
	- mcwpaintings 1.0.5
	- mcwpaths 1.0.4
	- mcwroofs 2.3.0
	- mcwtrpdoors 1.1.2
	- mcwwindows 2.2.1
	- meadow 1.3.8
	- megacells 2.3.4-1.20.1
	- melody 1.0.3
	- mi_sound_addon 1.0.2-1.20.1
	   \-- magna 1.10.1+1.20.1
	- minecraft 1.20.1
	- modern_industrialization 1.8.4
	   |-- magna 1.10.1+1.20.1
	   |-- noindium 1.1.0+1.20
	   |-- playerabilitylib 1.8.0
	   \-- team_reborn_energy 3.0.0
	- modernfix 5.16.0+mc1.20.1
	- modmenu 7.2.2
	- moonlight 1.20-2.11.12
	- more_armor_trims 1.1.3-1.20.1
	- morecosmetics ${version}
	- moremobvariants 1.2.2
	- morevillagers 5.0.0
	- mousetweaks 2.26
	- movingelevators 1.4.6
	- mr_reds_morestructures 1.0.8
	- nethervinery 1.2.9
	- nicer-skies 1.3.0
	- notenoughanimations 1.7.1
	- notenoughcrashes 4.4.7+1.20.1
	- offlineskins 1.20.1-v1a-fabric
	- oregrowth 1.0.11
	- origins 1.10.0
	   \-- reach-entity-attributes 2.4.0
	- overloadedarmorbar 1.20.1-2
	   \-- gbfabrictools 1.2.2+1.16
	- owo 0.11.1+1.20
	- packetfixer 1.2.8
	- palladium 4.0.9
	   |-- palladiumcore 1.0.1
	   \-- team_reborn_energy 3.0.0
	- pantheonsent 1.0.3
	   \-- sherdsapi 4.0.4
	- patchouli 1.20.1-84-FABRIC
	   \-- fiber 0.23.0-2
	- pehkui 3.8.0+1.14.4-1.20.4
	   \-- kanos_config 0.4.1+1.14.4-1.19.4
	- pfm 1.2.1
	- physicsmod 3.0.13
	- pigpen 15.0.2
	- player-animator 1.0.2-rc1+1.20
	- playerplates 3.0.4+mc1.20.1
	- powah 5.0.5
	- presencefootsteps 1.9.2
	   \-- kirin 1.15.4+1.20
	- puzzleslib 8.1.18
	   \-- puzzlesaccessapi 8.0.7
	- quad 1.1.6
	- rechiseled 1.1.5+b
	- regrowth 83.31.1
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.24
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- rhino 2001.2.2-build.18
	- roughlyenoughitems 12.0.697
	   \-- error_notifier 1.0.9
	- runelic 18.0.2
	- searchables 1.0.2
	- searchlight 1.1.11
	- seasons 2.3+1.20
	- seasonscroptopiacompat 1.0-2.2.2
	- seasonsextras 1.2-BETA+1.20
	- simplemagnets 1.1.10
	- simplyswords 1.54.0-1.20.1
	   \-- spruceui 5.0.0+1.20
	- skeletalremains 1.4.2
	- skinlayers3d 1.6.2
	- sodium 0.5.8+mc1.20.1
	- soulfired 3.2.1.0
	- supermartijn642configlib 1.1.8+a
	- supermartijn642corelib 1.1.17
	- swplanets 1.2.7
	- t_and_t 1.12
	- tconstruct 1.20.1-3.6.4.271
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- dripstone_fluid_lib 3.0.1
	   |-- mantle 1.20.1-1.9.265
	   |    |-- com_google_code_findbugs_jsr305 3.0.2
	   |    \-- star 1.5.2+1.20.1
	   |-- milk 1.2.58
	   |-- mixinsquared 0.1.1
	   |-- porting_lib_accessors 2.2.8-beta.5+1.20.1
	   |-- porting_lib_attributes 2.2.8-beta.5+1.20.1
	   |-- porting_lib_base 2.2.8-beta.5+1.20.1
	   |    \-- porting_lib_mixin_extensions 2.2.8-beta.5+1.20.1
	   |-- porting_lib_brewing 2.2.8-beta.5+1.20.1
	   |-- porting_lib_client_events 2.2.8-beta.5+1.20.1
	   |-- porting_lib_common 2.2.8-beta.5+1.20.1
	   |-- porting_lib_config 2.2.8-beta.5+1.20.1
	   |-- porting_lib_core 2.2.8-beta.5+1.20.1
	   |-- porting_lib_data 2.2.8-beta.5+1.20.1
	   |-- porting_lib_entity 2.2.8-beta.5+1.20.1
	   |    \-- porting_lib_mixin_extensions 2.2.8-beta.5+1.20.1
	   |-- porting_lib_extensions 2.2.8-beta.5+1.20.1
	   |-- porting_lib_fluids 2.2.8-beta.5+1.20.1
	   |-- porting_lib_items 2.2.8-beta.5+1.20.1
	   |-- porting_lib_lazy_registration 2.2.8-beta.5+1.20.1
	   |-- porting_lib_loot 2.2.8-beta.5+1.20.1
	   |-- porting_lib_model_loader 2.2.8-beta.5+1.20.1
	   |-- porting_lib_models 2.2.8-beta.5+1.20.1
	   |-- porting_lib_networking 2.2.8-beta.5+1.20.1
	   |-- porting_lib_tags 3.0
	   |-- porting_lib_tool_actions 2.2.8-beta.5+1.20.1
	   |-- porting_lib_transfer 2.2.8-beta.5+1.20.1
	   \-- porting_lib_utility 2.2.8-beta.5+1.20.1
	- terrablender 3.0.1.4
	   |-- com_electronwill_night-config_core 3.6.7
	   \-- com_electronwill_night-config_toml 3.6.7
	- terralith 2.4.11
	- timecontrol 1.5.0
	- toomanyorigins 1.1.1+1.20.1-fabric
	   \-- wwfix 1.0.0+hotfix.1
	- trashcans 1.0.18
	   \-- team_reborn_energy 3.0.0
	- travelersbackpack fabric-1.20.1-9.1.12
	- trinkets 3.7.2
	- twigs 3.1.0
	- vanityslots 1.2.9
	- vinery 1.4.14
	- visualworkbench 8.0.0
	- wakes 0.2.4+1.20.1
	   |-- com_github_jdiemke_delaunay-triangulator_delaunaytriangulator 1.0.0
	   \-- satin 1.14.0
	- wands 2.6.9-release
	- waterdripsound 1.19-0.3.2
	- xaerominimap 24.1.1
	- xaeroworldmap 1.38.4
	- yungsapi 1.20-Fabric-4.0.4
	   \-- org_javassist_javassist 3.29.2-GA
	- yungsbridges 1.20-Fabric-4.0.3
	- yungsextras 1.20-Fabric-4.0.3

### Additional Context

All worlds load perfectly fine with the same mod configuration when Create and all its addons are removed. Tested with just Create and no addons and the same issue persists. Removing Create solves this issue, could be a compatibility issue.

**Comment by mogibesf** [comment]
it's problem with Hephaestus. Waiting for the fix
