### ISSUE TITLE
Crash on REI Recipe Lookup

### ISSUE THREAD

**Issue by cntrik** [Fabricators-of-Create/Create#145]
### Describe the Bug

Crash on REI recipe lookup
[crash-2022-02-15_18.40.31-client.txt](https://github.com/Fabricators-of-Create/Create/files/8075470/crash-2022-02-15_18.40.31-client.txt)

### Reproduction Steps

1.Right Click an item in an the REI entry
2.Click any tab utilizing a Create Recipe
3.Game Crashes
...

### Expected Result

Expected to see the recipe as in JEI for Forge, below is image to the aforementioned Create Recipe categories all of which result in a crash. 

### Screenshots and Videos

![2022-02-15_18 51 42](https://user-images.githubusercontent.com/11052983/154169622-2fc44af3-5945-4130-a62a-083b03175a6a.png)
![2022-02-15_18 51 46](https://user-images.githubusercontent.com/11052983/154169626-d1b93a89-8998-4784-a2be-51e4c31737db.png)
![2022-02-15_18 51 36](https://user-images.githubusercontent.com/11052983/154169627-535495ef-eb37-40dd-9334-01aa15c423f7.png)

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		architectury: Architectury 3.6.17
		balm-fabric: Balm 2.4.1+0
		beaconoverhaul: Beacon Overhaul 1.5.0+1.18
		biomemakeover: Biome Makeover 1.18.1-1.4.6
		blossom: Blossom 1.18.1-1.0.2
		cardinal-components-base: Cardinal Components API (base) 4.0.1
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.0.1
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		catwalksinc: Catwalks Inc. 1.2.0
		chunkbychunk: Chunk By Chunk 1.5.0+1.18.1
		cloth-api: Cloth API 3.1.61
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.1.61
		cloth-common-events-v1: Cloth Common Events v1 3.1.61
		cloth-config: Cloth Config v6 6.2.57
		cloth-datagen-api-v1: Cloth Datagen v1 3.1.61
		cloth-scissors-api-v1: Cloth Scissors API v1 3.1.61
		cloth-utils-v1: Cloth Utils v1 3.1.61
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_google_code_findbugs_jsr305: jsr305 3.0.2
		conjuring: Conjuring 1.0.20+1.18
		create: Create mc1.18.1_v0.4d+401
		creeperspores: Creeper Spores 1.7.2
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portal Api 0.0.1-beta49-1.18
		dashloader: DashLoader 3.0-rc14-1.18
		deathlog: DeathLog 0.2.6+1.18
		defaultoptions: Default Options 14.1.0
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.1
		dev_quantumfusion_hyphen: hyphen 0.1
		dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
		dyed: Dyed 1.18.1-1.0.0
		dynmus: Dynamic Music 1.4.1
		easymagic: Easy Magic 3.2.1
		elytra_aeronautics: Elytra aeronautics 1.0.0
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		endemic: Endemic 1.18.1-1.2.0
		essential-container: essential-container 1.0.0
		essential-loader: essential-loader 1.0.0
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 1.0.0+3fec4ad9c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabricloader: Fabric Loader 0.13.2
		fake-player-api: Fake Player API 0.3.0
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		ferritecore: FerriteCore 4.1.1
		fiber: fiber 0.23.0-2
		flywheel: Flywheel 1.18-0.6.1.23
		forge_tags: Forge Tags 2.0
		forgeconfigapiport: Forge Config API Port 3.1.1
		forgivingvoid: Forgiving Void 6.0.1
		gud_csl: Custom Shader Lib 1.0.0
		gud_recipe_confidence: Recipe Confidence 1.0.2
		hardcore_torches: Hardcore Torches 1.3.3
		immersive_weathering: Immersive Weathering 2.1.1
		incubus_core: Incubus Core 1.6.6+1.18.1
		indexed: Indexed 1.1.0
		inspecio: Inspecio 1.2.1+1.18
		io_airlift_aircompressor: aircompressor 0.21
		isometric-renders: Isometric Renders 0.2.11+1.18
		java: OpenJDK 64-Bit Server VM 17
		kirin: Kirin UI 1.10.0
		kubejs: KubeJS 1801.4.2-build.298
		leather-blocks: Leather Blocks 1.2.0+1.18.x
		lithium: Lithium 0.7.7
		milk: Milk Lib 0.1.6
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 3.0.1
		moretags: More Tags 2.0.3
		netherportalfix: NetherPortalFix 9.0.0
		numismatic-overhaul: Numismatic Overhaul 0.1.8+1.18
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_joml_joml: joml 1.10.2
		owo: oωo 0.5.2+1.18
		palette256: Palette 256 1.0.0
		patchouli: Patchouli 1.18.1-65-FABRIC
		pickupnotifier: Pick Up Notifier 3.1.0
		polymorph: Polymorph 0.0.19-1.18.1
		puzzleslib: Puzzles Lib 3.1.5
		rainbow-shenanigans: Rainbow Shenanigans 1.0.0
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		registrate-fabric: Registrate for Fabric MC1.18.1-1.0.7
		revamped_phantoms: Revamped Phantoms 0.2.1
		rhino: Rhino 1801.1.8-build.99
		roughlyenoughitems: Roughly Enough Items 7.2.425
		sleepwarp: SleepWarp 1.0.0+1.18.1
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.3
		smoothboot: Smooth Boot 1.18-1.7.0
		sodium: Sodium 0.4.0-alpha6+build.14
		stacc: Stacc 1.3.0
		starlight: Starlight 1.0.0+fabric.d0a3220
		stylisheffects: Stylish Effects 3.0.2
		the_aether: Paradise Lost - The Aether Reborn 1.6.5.1+1.18.1
		tinyskeletons: Tiny Skeletons 3.1.0
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.2.0
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.1-1.18.1
		twigs: Twigs 1.1.2
		unvotedandshelved: Unvoted & Shelved 1.0.4
		visualworkbench: Visual Workbench 3.1.0
		voidfog: Void Fog 2.6.1
		worldmesher: Worldmesher 0.2.5+1.18

**Comment by TropheusJ** [comment]
update starlight to 1.0.1.

**Comment by cntrik** [comment]
Thank you that fixed it!
