### ISSUE TITLE
No textures

### ISSUE THREAD

**Issue by Blutaar23** [Fabricators-of-Create/Create#1451]
### Describe the Bug

Flywheel
Crushing wheel
Water wheels
Induction thingies from New Age Addon

They all have no textures in the modpack I play.

How can I fix this.

### Reproduction Steps

1.Better Adventures+ Modpack for 1.20.1
2.
3.
...

### Expected Result

Everyone has those textures but somehow we don't.

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
install indium

**Comment by Blutaar23** [comment]
Does not resolve the issue. I already had Indium installed.

**Comment by JanLukasGithub** [comment]
You need to provide some sort of exact mod list, error log or anything else to help with debugging this. It's impossible to just assume what's happening.

**Comment by drwoops** [comment]
best is to crash your game by holding F3+C for 10s and attach the crash report. it contains a modlist

**Comment by Blutaar23** [comment]
Fabric Mods: 
		advancementplaques: Advancement Plaques 1.4.11
		adventurez: AdventureZ 1.4.18
		alloy_forgery: Alloy Forgery 2.1.2+1.20
		ambientsounds: AmbientSounds 5.2.20
		amplified_nether: Amplified Nether 1.2.2
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.2.14
		auditory: Auditory 0.0.6-1.20.1
		autotag-convention: AutoTag Convention 2.0.2+1.20
			autotag: AutoTag 2.0.2+1.20
		bedspreads: Bedspreads 6.2.0+1.20.1
		bellsandwhistles: Create: Bells & Whistles 0.4.5
		betteradvancements: Better Advancements 0.3.2.161
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
			org_reflections_reflections: reflections 0.10.2
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterthirdperson: Better Third Person 1.9.0
		bewitchment: Bewitchment 1.20-8
			impersonate: Impersonate 2.10.2
				fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			midnightlib: MidnightLib 1.4.1
			playerabilitylib: Pal 1.8.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.3
		blur: Blur (Fabric) 3.1.0
			satin: Satin 1.13.0
		bobby: Bobby 5.0.1
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		botarium: Botarium 2.3.3
			team_reborn_energy: Energy 3.0.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.5
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.5
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.5
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.5
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.5
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.5
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.5
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.5
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.5
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.5
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.5
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.5
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.5
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.5
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.5
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.5
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.5
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		camerautils: Camera Utils 1.20.1-1.0.4
		cavedust: Cave Dust 1.4.1
			kirin: Kirin UI 1.15.0
		chas: Craftable Horse Armour & Saddle 1.20
		cherishedworlds: Cherished Worlds 6.1.0+1.20.1
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		comforts: Comforts 6.3.4+1.20.1
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
			spectrelib: SpectreLib 0.13.14+1.20.1
		connectiblechains: Connectible Chains 2.2.1+1.20.1
		copycats: Create: Copycats+ 1.20.1-1.2.5
		craftable_create_casings: Craftable Create Casings 1.1
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.2+1.20.1
			porting_lib_base: Porting Lib Base 2.3.2+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.2+1.20.1
				porting_lib_common: Porting Lib Common 2.3.2+1.20.1
				porting_lib_config: Porting Lib Config 2.3.2+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.2+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.2+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.2+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.2+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.2+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.2+1.20.1
				porting_lib_core: Porting Lib Core 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.2+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.2+1.20.1
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create_cooking: Create: Cooking 1.0.0
		create_copper_and_zinc: Create: Copper & Zinc Renewables 1.4.0
		create_jetpack: Create Jetpack 4.2.0
			flightlib: Flight Lib 2.1.0
		create_new_age: Create: New Age 1.1.2
		create_ultimate_factory: Create: Ultimate Factory 1.5.0
		create_unbreakable: Create Unbreakable Tools Mod 1.0+fabric-1.20.1
		createaddition: Create Crafts & Additions 1.2.3
		createfastfood: Create FastFood 0.2
		creategoggles: Create Goggles 0.5.5.g
		createmetalwork: Create: Metalwork 1.0.0
		createmoreautomation: Create: More Automation 1.1.2-1.20.1
		createoreexcavation: Create Ore Excavation 1.4.5
			chunk-storage-api-fabric: Chunk Storage Api Fabric 1.0.4
		createutilities: Create Utilities 0.2.1+1.20.1
		creativecore: CreativeCore 2.10.24
			net_minecraftforge_eventbus: eventbus 6.0.3
		cupboard: cupboard 1.20.1-2.1
		darksmelting: DarkSmelting - Smelt Armor and Tools 1.0.6
		dataloader: Data loader 1.1.3+1.19.4-1.20-pre5
		diagonalfences: Diagonal Fences 8.0.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 4.1
		easyanvils: Easy Anvils 8.0.0
		easymagic: Easy Magic 8.0.0
		eatinganimationid: Eating Animation 1.9.4+1.20
		emi: EMI 1.1.4+1.20.1+fabric
		enhancedvisuals: EnhancedVisuals 1.6.7
		entity_model_features: Entity Model Features 0.2.13
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		exposure: Exposure 1.5.1
		extrasounds: ExtraSounds 2.3.1+1.20.1~lonefelidae16-build.1
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			soundcategories: Sound Categories 1.2.4+1.20~lonefelidae16-build.1
		fabric-api: Fabric API 0.92.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.4+1802ada577
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fallingleaves: Falling Leaves 1.15.1+1.20.1
		fallingtree: FallingTree 4.3.4
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		firstperson: FirstpersonModel 2.2.3
		forgeconfigapiport: Forge Config API Port 8.0.0
		garnished: Create: Garnished 1.7.5+1.20.1
			create_dragon_lib: Create Dragon Lib 1.4.2
		herdspanic: Herds Panic 1.0.7
		iceberg: Iceberg 1.1.18
		immersive_aircraft: Immersive Aircraft 0.7.5+1.20.1
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.2.1
		immersive_armors: Immersive Armors 1.6.1+1.20.1
		immersive_paintings: Immersive Paintings 0.6.7+1.20.1
		incendium: Incendium 5.3.4
		indium: Indium 1.0.30+mc1.20.4
		inmis: Inmis 2.7.2-1.20.1
			omega-config: OmegaConfig 1.2.3-1.18.1
		inmisaddon: InmisAddon 1.0.4
		invmove: InvMove 0.8.4
		iris: Iris 1.7-alpha.1-185a9812
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemborders: Item Borders 1.2.1
		jamlib: JamLib 0.6.0+1.20
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.18p1
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.4.4
		libz: LibZ 1.0.3
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.15.2
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.15.2
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.15.2
		lithium: Lithium 0.11.2
		lootr: Lootr 0.7.29.75
		magistuarmory: Epic Knights Mod 9.4
		magistuarmoryaddon: Epic Knights: Addon 1.6
		man_of_many_planes: Man of Many Planes 0.0.3+1.20.1
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.1.0
		morebannerfeatures: More Banner Features 1.2.0
		moremobvariants: More Mob Variants 1.2.2
		mousewheelie: Mouse Wheelie 1.11.1+mc1.20-pre2
			amecsapi: Amecs API 1.4.0+mc1.20-pre1
			coat: Coat 1.0.0-beta.20+mc1.20-pre1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20-pre1
		musketmod: Musket Mod 1.4.6-X
		noincreasingrepaircost: No Increasing Repair Cost 1.0.0
		notenoughanimations: NotEnoughAnimations 1.6.4
		nullscape: Nullscape 1.2.4
		nvidium: Nvidium 0.2.6-beta
		omnihopper: Omni-Hopper 2.2.3+1.20
			cicada: CICADA 0.4.4
			cooldown-coordinator: Cooldown Coordinator 0.6.2
		owo: oωo 0.11.1+1.20
			blue_endless_jankson: jankson 1.2.2
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.8.0+1.14.4-1.20.4
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		portablemobs: Portable Mobs 1.2.0
		presencefootsteps: Presence Footsteps 1.9.0
		prism: Prism 1.0.5
		puzzleslib: Puzzles Lib 8.0.7
		railways: Create: Steam 'n' Rails 1.5.3+fabric-mc1.20.1
			mm: Manningham Mills 2.3
		rightclickharvest: Right Click Harvest 3.2.2+1.19.x-1.20.1-fabric
		seasons: Fabric Seasons 2.3+1.20
		seasonsextras: Fabric Seasons: Extras 1.2-BETA+1.20
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		sliceanddice: Create Slice & Dice 3.1.0
		smallships: Small Ships 2.0.0-b1.1
		smoothswapping: Smooth Swapping 0.9.3.1
		sodium: Sodium 0.5.8+mc1.20.1
		soulfired: Soul fire'd 3.2.0.0
		structory: Structory 1.3.4
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17
		tectonic: Tectonic 2.2
		tiered: Tiered 1.3.0
		tinyskeletons: Tiny Skeletons 8.0.0
		trade_cycling: Trade Cycling 1.20.1-1.0.5
		trinkets: Trinkets 3.7.1
		universalbonemeal: Universal Bone Meal 8.0.0
		vanillatweaks: VanillaTweaks 1.5.69
		visuality: Visuality 0.7.0+1.20
		wakes: Wakes 0.1.6
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
			org_javassist_javassist: javassist 3.29.2-GA
	Loaded Shaderpack: ComplementaryReimagined_r5.1.1.zip
		Profile: HIGH (+9 options changed by user)
	Flywheel Backend: Off

**Comment by IThundxr** [comment]
try updating puzzles lib

**Comment by Blutaar23** [comment]
@IThundxr kiss your eyes :d
Works like a charm!
