### ISSUE TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'main'

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Fabricators-of-Create/Create#1452]
### Describe the Bug

After updating Create to the latest build the pack failed to launch

### Reproduction Steps

See above

### Expected Result

no crash on launch

### Crash Report or Log

https://pastebin.com/rbyfJJEF

### Operating System

Linux Mint 21.3 Cinnamon

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

additionalentityattributes-1.7.3+1.20.0
animatica-0.6+1.20
appleskin-fabric-mc1.20.1-2.5.1
architectury-9.2.14-fabric
ArmorPoser-fabric-1.20.1-2.1.3
ArmorStatues-v8.0.6-1.20.1-Fabric
athena-fabric-1.20.1-3.1.2
backpacked-fabric-1.20.1-2.2.7
balm-fabric-1.20.1-7.2.2
better-end-sky-0.2.1+1.20
better-fabric-console-mc1.20.1-1.1.6
BetterCompatibilityChecker-fabric-4.0.1+mc1.20.1
BetterF3-7.0.2-Fabric-1.20.1
BetterThirdPerson-Fabric-1.20-1.9.0
BHMenu-Fabric-1.20.1-2.4.1
bigger_end_cities-1.20.1-1.0.4
bobby-5.0.1
Botania-1.20.1-443-FABRIC
BuildGuide-1.20-0.4.1
bwncr-fabric-1.20.1-3.17.0
carryon-fabric-1.20.1-2.1.2.7
Chipped-fabric-1.20.1-3.0.6
clienttweaks-fabric-1.20-11.1.0
cloth-config-11.1.118-fabric
Clumps-fabric-1.20.1-12.0.0.3
collective-1.20.1-7.40
completeconfig-2.5.0
connectivity-fabric-1.20.1-5.5
continuity-3.0.0-beta.4+1.20.1
Controlling-fabric-1.20.1-12.0.2
Copycats-fabric.1.20.1-1.2.6
craftingtweaks-fabric-1.20.1-18.2.3
create-fabric-0.5.1-f-build.1417+mc1.20.1
CullLessLeaves-1.3.0
cupboard-fabric-1.20.1-2.6
DisableCustomWorldsAdvice-4.1
DistractingTrims-Fabric-1.20.1-2.0.3
drippyloadingscreen_fabric_3.0.2_MC_1.20.1
easiercrafting-1.20-fabric0.83.0-1.7
easiervillagertrading-1.20-fabric0.83.0-1.5.4
EmeraldTools-Fabric-1.20.1-1.6.3
entitycount-2024.0128
entityculling-fabric-1.6.2-mc1.20.1
entityinformation-1.20.1-3.3
environmentalcreepers-fabric-1.20.1-1.6.0
EssentialGUI-1.9.4+1.20.1
extremesoundmuffler-3.41-fabric-1.20
eyespy-1.3.5+1.20.1
fabric-api-0.92.1+1.20.1
fabric-language-kotlin-1.10.19+kotlin.1.9.23
fancymenu_fabric_3.1.4_MC_1.20.1
farmers-delight-fabric-1.4.3
Fastload+1.18.2-1.20-3.4.0
ferritecore-6.0.1-fabric
fireworks-are-for-flying-1.20.1
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
FpsReducer2-fabric-1.20-2.5
framework-fabric-1.20.1-0.6.16
fullscreeNO-1.0.0
fusion-1.1.1-fabric-mc1.20.1
geckolib-fabric-1.20.1-4.4.4
IBEEditor-1.20-2.2.8-fabric
ImmediatelyFast-Fabric-1.2.11+1.20.4
immersive_paintings-0.6.7+1.20.1-fabric
improvedsigns-1.3.1
indium-1.0.30+mc1.20.4
individualkeepinv-1.0.3
InventorySorter-1.9.0-1.20
iris-mc1.20.1-1.6.17
kibe-1.10.1-BETA+1.20
konkrete_fabric_1.8.1_MC_1.20.1
kubejs-fabric-2001.6.5-build.7
lambdynamiclights-2.3.2+1.20.1
lazydfu-0.1.3
litematica-fabric-1.20.1-0.15.3
lithium-fabric-mc1.20.1-0.11.2
lootr-1.20-0.7.30.77
malilib-fabric-1.20.1-0.16.3
melody_fabric_1.0.4_MC_1.20.1-1.20.4
memoryleakfix-fabric-1.17+-1.1.5
minihud-fabric-1.20.1-0.27.0
modmenu-7.2.2
MouseTweaks-fabric-mc1.20-2.26
neruina-1.3.0-fabric+1.18.2-1.20.1
NoChatReports-FABRIC-1.20.1-v2.2.2
observable-4.4.1
OpenLoader-Fabric-1.20.1-19.0.3
owo-lib-0.11.2+1.20
paladin-furniture-mod-1.2.1-fabric-mc1.20.1
Patchouli-1.20.1-84-FABRIC
Pehkui-3.8.0+1.14.4-1.20.4
polymorph-fabric-0.49.3+1.20.1
PuzzlesLib-v8.1.18-1.20.1-Fabric
quick-menu-1.2.3-1.20.1
reacharound+1.20-1.1.2
reeses_sodium_options-1.7.2+mc1.20.1-build.101
replaymod-1.20.1-2.6.15
resourcefullib-fabric-1.20.1-2.1.24
rhino-fabric-2001.2.2-build.18
RoughlyEnoughItems-12.1.712-fabric
Searchables-fabric-1.20.1-1.0.2
server-essentials-1.2.0
servertick-mc1.20-1.8
shulkerboxtooltip-fabric-4.0.4+1.20.1
sliceanddice-fabric-3.2.1
sodium-extra-0.5.4+mc1.20.1-build.115
sodium-fabric-0.5.8+mc1.20.1
StackDeobfuscatorFabric-1.4.2+bf1fc22
starlight-1.1.2+fabric.dbc156f
status-fabric-1.20.1-1.0.6
swingthrough-1.0.4+1.19
templates-2.1.1+1.20.1
textile_backup-3.1.2-1.20
toms_storage_fabric-1.20-1.6.6
TravelersTitles-1.20-Fabric-4.0.2
trinkets-3.7.2
tweakeroo-fabric-1.20.1-0.17.1
voicechat-fabric-1.20.1-2.5.12
vt-downloader-2.0.8+1.20.1
waystones-fabric-1.20-14.1.3
WI-Zoom-1.5-MC1.20.1
WorldTools-fabric-1.2.4+1.20.1
Xaeros_Minimap_24.1.1_Fabric_1.20
XaerosWorldMap_1.38.4_Fabric_1.20
yet-another-config-lib-fabric-3.2.2+1.20
yosbr-0.1.2
youre-in-grave-danger-2.0.0-beta.11
YungsApi-1.20-Fabric-4.0.4
YungsBetterDesertTemples-1.20-Fabric-3.0.3
YungsBetterDungeons-1.20-Fabric-4.0.4
YungsBetterJungleTemples-1.20-Fabric-2.0.4
YungsBetterMineshafts-1.20-Fabric-4.0.4
YungsBetterNetherFortresses-1.20-Fabric-2.0.6
YungsBetterOceanMonuments-1.20-Fabric-3.0.4
YungsBetterStrongholds-1.20-Fabric-4.0.3
YungsBetterWitchHuts-1.20-Fabric-3.0.3
YungsBridges-1.20-Fabric-4.0.3
YungsExtras-1.20-Fabric-4.0.3
YungsMenuTweaks-1.20.1-Fabric-1.0.2

**Comment by IThundxr** [comment]
sliceanddice is crashing because you are using the old farmers delight port, switch to farmers delight refabricated

**Comment by drwoops** [comment]
the issue is caused by farmer's delight.  farmer's delight fabric says it is deprecated.

**Comment by drwoops** [comment]
lol. typing at teh same time

**Comment by ClaudiusMinimus** [comment]
Thanks, that fixed it
