### ISSUE TITLE
The track in a jukebox continues to play even though there is technically no music disc in it

### ISSUE THREAD

**Issue by BugInYourCode01** [Fabricators-of-Create/Create#1458]
### Describe the Bug

If a music disk is removed from a jukebox by a Create machine while it is still playing (only possible with Mechanical Arm and Chute, Funnels and Smart chutes are blocked by the jukebox's redstone signal), you can still hear the track. However, the jukebox no longer emits a redstone signal and the jukebox is also empty in Jade.

### Reproduction Steps

1. Put a music disc in a jukebox
2. Remove the music disk with a chute or mechanical arm.

### Expected Result

The song stops as if you were pulling out the Muaic disk by hand.

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Additional Context

I took advantage of this and this is what I got. Just put a music disc on the depot and listen to the wonderful music :)

[broken_pigstep.zip](https://github.com/Fabricators-of-Create/Create/files/15053158/broken_pigstep.zip)

There is a schematic in the zip file

**Comment by TropheusJ** [comment]
update FAPI

**Comment by BugInYourCode01** [comment]
Fabric API is already installed (version 0.92.1)

**Comment by IThundxr** [comment]
cant reproduce with fapi `0.92.1+1.20.1`

**Comment by BugInYourCode01** [comment]
I only tested the bug with Create Fabric and Fabric API, Fabric 0.15.10 and it was still there.

![grafik](https://github.com/Fabricators-of-Create/Create/assets/163460667/f9771481-e31b-4d61-9499-a0c0d3909bd0)

Build a tower of chutes and jukeboxes, always alternating. Maybe you can hear several pieces on top of each other.

**Comment by BugInYourCode01** [comment]
I have found out something more precise: When a Chute takes an item from a Jukebox, the Music Disk is removed from the Jukebox inventory, but the song is not stopped. A Mechanical Arm stops the song properly. However, there are problems if a second Mechanical wants to pick up the Music Disc from the jukebox at the same time. Then the song is not stopped.
Maybe this is related to game ticks. If the mechanical arm only searches for a target every second tick, maybe the latter bug is also fixed.

**Comment by TropheusJ** [comment]
This is, again, a fabric API issue. https://github.com/FabricMC/fabric/issues/4220
