### ISSUE TITLE
(Extended Drawers) Threshold switch reading incorrect drawer capacity

### ISSUE THREAD

**Issue by SageofTurtles** [Fabricators-of-Create/Create#1459]
### Describe the Bug

Hello! I'm not sure if this is an issue with Create or Extended Drawers, but the threshold switch seems to not be functioning correctly with the drawers added by that mod. When a threshold switch is attached to a drawer, it will act as if each drawer slot has a max capacity of one stack of items (despite the drawers allowing multiple times that amount by default). As a result, placing one sword in a single drawer slot will cause the threshold switch to register the slot as completely full, even when it can hold thousands more; if the drawer has 4 slots, placing a total of 64 cobblestone in any of that drawer's slots will register as 25% full on the threshold switch; and so on.

### Reproduction Steps

1. Place a drawer (any type).
2. Put one stack of items in the drawer (however many of that item is considered one "stack", e.g. 1 sword, 16 ender pearls, 64 stone, etc.)
3. If a single drawer, it will read as 100% full on the threshold switch with this one stack of items. If a double drawer, it will read as 50% full. If a quad drawer, 25% full.

### Expected Result

Instead of this, it would be expected that the threshold switch shows the actual capacity of the drawer as it is configured so that the additional storage space can be used with the threshold switch.

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Fabric Loader 0.15.7
Fabric API 0.92.0
Extended Drawers (Fabric) 2.1.1

**Comment by MrStickyPiston** [comment]
Same issue, Xubuntu 22.04.04 LTS / Kubuntu 22.04 LTS.
Same version
Same mods

from extended drawers issue (https://github.com/MattiDragon/ExtendedDrawers/issues/105#issuecomment-2073041047):

> [[MattiDragon]:](https://github.com/MattiDragon) Create threshold switches being weird is almost certainly on their end. If they check the max stack size instead of the capacity they're doing it wrong.

> [[MrStickyPiston]:](https://github.com/MrStickyPiston) Seems to work for other storage & in previous versions though

> [[MattiDragon]:](https://github.com/MattiDragon) Do those other storages have capacities beyond the max stack size? I'm pretty sure that's causing the issue.

image i made for that issue:
![image](https://github.com/Fabricators-of-Create/Create/assets/97804691/9f6dd8d8-0b2f-42b7-a3a9-812c6ddb0c09)

**Comment by Plasman888** [comment]
I have this bug aswell

**Comment by MrStickyPiston** [comment]
It is probally usefull to look at the storagedrawers patch: https://github.com/Fabricators-of-Create/Create/blob/mc1.18/fabric/dev/src/main/java/com/simibubi/create/compat/storageDrawers/StorageDrawers.java
