### ISSUE TITLE
Latest build fails to launch

### ISSUE THREAD

**Issue by Nolij** [Fabricators-of-Create/Create#146]
### Describe the Bug

Game doesn't even get to the loading screen

### Reproduction Steps

1. Install Create & dependencies

### Expected Result

Game should launch

### Crash Report or Log

https://paste.ee/p/QHbS2

### Operating System

Arch Linux

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

Fabric API 0.46.4+1.18 (latest non-beta as of posting)

### Additional Context

This build specifically: https://github.com/Fabricators-of-Create/Create/actions/runs/1850595584

**Comment by Nolij** [comment]
Update: the build immediately prior to this one launches fine.

**Comment by TropheusJ** [comment]
please try the latest version. reopen if it persists.
