### ISSUE TITLE
filter respect data has failure

### ISSUE THREAD

**Issue by w23263** [Fabricators-of-Create/Create#1460]
### Describe the Bug

filter respect data has failure

### Reproduction Steps

Select a full durability tool in the filter and  respect data, but a smart chute or brass funnel using this filter won't block tools that aren't full durability

### Expected Result

fix it

### Operating System

windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

only create will happen too

**Comment by VoidLeech** [comment]
Happens on Forge as well, upstream issue: https://github.com/Creators-of-Create/Create/issues/5780
