### ISSUE TITLE
Crash version 0.5.1-f-build.1416

### ISSUE THREAD

**Issue by R2kip** [Fabricators-of-Create/Create#1461]
### Describe the Bug

Version: 0.5.1-f-build.1416

### Reproduction Steps

Join in the world

### Expected Result

Join in world

### Crash Report or Log

https://mclo.gs/LfM5nO8

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.19.2

**Comment by R2kip** [comment]
![image](https://github.com/Fabricators-of-Create/Create/assets/56793105/1e5a53d7-76c3-4479-a955-c1bc4debe01a)

**Comment by IThundxr** [comment]
This issue is not related to create and is caused by a addon mod/another mod.

big cannons is outdated
