### ISSUE TITLE
Create Fabric 0.5.1-f-build.1417+mc1.20.1 is Incompatable with any version of Sound Physics Remastered

### ISSUE THREAD

**Issue by SonofRanman66** [Fabricators-of-Create/Create#1462]
### Describe the Bug

When trying to use Sound Physics Remastered with Create and Fabric, I get a Incompatibility Error stating the 1417 build of create is incompatible with Sound Physics Remastered. No other version of Sound Physics Remastered works. I'm writing reports to both mods because I'm not sure what's at fault here.

I use the AT Launcher for Modded Minecraft.

### Reproduction Steps

1. Install fabric-api-0.92.1+1.20.1
2. Install create-fabric-0.5.1-f-build.1417+mc1.20.1
3. Install any version of Sound Physics Remastered. (I Used: sound-physics-remastered-fabric-1.20.1-1.3.1)
4. Launch Game

### Expected Result

You should get a Incompatibility on Launch

### Screenshots and Videos

<img width="588" alt="CreateandSoundPhysicsError" src="https://github.com/Fabricators-of-Create/Create/assets/67488494/3dba2639-021e-41de-975e-554cb16c2eef">

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Fabric API

Sound Physics Remastered

**Comment by TropheusJ** [comment]
#1432
