### ISSUE TITLE
[1.20.1] Create crashing on launch

### ISSUE THREAD

**Issue by lfpnub** [Fabricators-of-Create/Create#1463]
### Describe the Bug

I've nuked the configs, reinstalled create, and tried it with different versions of farmers delight and supplementaries. Even tried using quilt.

Crash report: https://mclo.gs/JBZeIFa
Full Logs: https://mclo.gs/HjKhnv8

### Reproduction Steps

1. Create a modpack with create
2. Load the modpack
3. Watch in horror as it crashes
...

### Expected Result

I expected the pack to load

### Crash Report or Log

https://mclo.gs/JBZeIFa

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

adorn: Adorn 5.0.1+1.20.1
		ae2: Applied Energistics 2 15.1.0
			team_reborn_energy: Energy 3.0.0
		ae2qolrecipes: AE2 QoL Recipes 1.1.1
		ae2wtlib: AE2WTLib 15.2.1-fabric
		alternate-current: Alternate Current 1.7.0
		another_furniture: Another Furniture 1.20.1-3.0.1
		appleskin: AppleSkin 2.5.1+mc1.20
		aquamirae: Aquamirae 6
		architectury: Architectury 9.2.14
		athena: Athena 3.1.2
		axiom: Axiom 2.7.0
			com_moulberry_axiomclientapi_axiomclientapi_: axiomclientapi 1.0.0
		azurelib: AzureLib 2.0.21
		backported_wolves: Backported Wolves 1.1.0-1.19.3-1.20.4
		badpackets: Bad Packets 0.4.3
		bakingdelight: Baking Delight 0.3.0+1.20.1
		barbequesdelight: Barbeque's Delight 1.0.0
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		bedrockify: BedrockIfy 1.9.1+mc1.20
			panorama_screens: Panorama Screens 1.0+fabric+mc1.20
		bellsandwhistles: Create: Bells & Whistles 0.4.5
		betterarcheology: Better Archeology 1.1.8-1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.4
		betterend: Better End 4.0.11
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.6
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
		betterfurnacesreforged: Better Furnaces Reforged 1.1.3
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.4
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		bitsandchisels: BitsAndChisels 2.7.3
			stacc: Stacc 1.5.2+boneless2ahhhh
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.7.5-1.20.1
			maelstrom_library: Maelstrom Library 1.6.1-1.20
			multipart_entities: MultipartEntities 1.5-1.20
		botarium: Botarium 2.3.3
		brewinandchewin: Brewin And Chewin 3.0.3+1.20.1
			mm: Manningham Mills 2.3
		cakedelight: Cake Delight 1.20.1-v3.0.2
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		casualness_delight: Casualness Delight Fabric 1.20.1-0.4-FDR
		charmofundying: Charm of Undying 6.5.0+1.20.1
			spectrelib: SpectreLib 0.13.15+1.20.1
		chat_heads: Chat Heads 0.10.32
		chefsdelight: Chefs Delight 1.0.3-fabric-1.20.1
		chipped: Chipped 3.0.6
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clutter: Clutter 1.20-0.5.7
		collective: Collective 7.49
		comforts: Comforts 6.3.5+1.20.1
		cratedelight: Crate Delight 1.4.5-1.20.1-fabric
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create-trimmed: create-trimmed 1.0.0
		create_dd: Create: Dreams & Desires 0.1c
			dsbg: Detected setBlock Be Gone 1.0
		create_enchantment_industry: Create Enchantment Industry 1.2.16
			create_dragon_lib: Create Dragon Lib 1.4.2
		create_interactive: Create: Interactive 1.0.2-beta.2
		create_new_age: Create: New Age 1.1.2
		createaddition: Create Crafts & Additions 1.2.3
		createbigcannons: Create Big Cannons 0.5.4-nightly-8b9cea6
			ritchiesprojectilelib: Ritchie's Projectile Library 1.0.0-369e88d+1.20.1-fabric
		createdeco: Create Deco 2.0.1-1.20.1-fabric
		createdieselgenerators: Create Diesel Generators 1.2.3h
		creategoggles: Create Goggles 0.5.5.g
		createoreexcavation: Create Ore Excavation 1.4.5
			chunk-storage-api-fabric: Chunk Storage Api Fabric 1.0.4
		createutilities: Create Utilities 0.3.0+1.20.1
		ctov: ChoiceTheorem's Overhauled Village 3.4.3
		culturaldelights: Cultural Delights Fabric 1.0.0+1.20.1
		debugify: Debugify 1.20.1+2.0
		deeperdarker: Deeper and Darker 1.2.6
			customportalapi: Custom Portal Api 0.0.1-beta64-1.20
		delightfulcreators: Delightful Creators 1.1.8
		design_decor: Create: Design n' Decor 0.2a+1.20.1-12
		diabolicaldelights: Diabolical Delights 1.0.2
		diet: Diet 2.1.1+1.20.1
		dungeons_arise: When Dungeons Arise 2.1.57
		dynamic_fps: Dynamic FPS 3.4.3
		easyanvils: Easy Anvils 8.0.2
		eatinganimationid: Eating Animation 1.20+1.9.61
		elementa: Elementa 629
		elytra-trims: Elytra Trims 2.1.2
			mixinsquared: MixinSquared 0.1.2-beta.4
		emi: EMI 1.1.4+1.20.1+fabric
		emi_enchanting: EMI Enchanting 0.1.0+1.20.1
		emi_loot: EMI Loot 0.6.6+1.20.1
		emiffect: EMIffect 1.1.2+mc1.20.1
		emitrades: EMI Trades 1.2.1+mc1.20.1
			org_quiltmc_parsers_json: json 0.2.1
		enchantmentsplus: Enchantments Plus 1.2.1+1.20.1
		endrem: End Remastered 5.2.4
		ends_delight: End's Delight refabricated-1.20.1-alpha-1.0
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.4+1.20
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		enhancedweather: Enhanced Weather 1.1-Alpha2
			blue_endless_jankson: jankson 1.2.3
		entity_model_features: Entity Model Features 2.0
		entity_texture_features: Entity Texture Features 6.0
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		essential: Essential 1.3.1.3+g88238d7752
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.1
		expandeddelight: Expanded Delight 0.3.1
			omega-config: OmegaConfig 1.4.0+1.20.1
		extendedgears: Extended Cogwheels 2.1.1-1.20.1-0.5.1.f-fabric
		extra-mod-integrations: Extra Mod Integrations 0.4.4+1.20.1
		fabric-api: Fabric API 0.92.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.10
			mixinextras: MixinExtras 0.3.5
		factory_api: Factory API 2.1.4
		farmersdelight: Farmer's Delight 1.20.1-2.0.17+refabricated
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.2+1.20.1
			porting_lib_registries: Porting Lib Registries 2.3.2+1.20.1
		farmersknives: Farmer's Knives 3.2
		farmersrespite: Farmer's Respite 2.3.4
		ferritecore: FerriteCore 6.0.1
		festive_delight: Festive Delight 1.0.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		friendsandfoes: Friends&Foes 2.0.10
		frightsdelight: Frights Delight fabric-1.20.1-1.0.4
		frostiful: Frostiful 1.0.8
		fulleng: Fullblock Energistics 1.6-1.20.1
		fusion: Fusion 1.1.1
		garnished: Create: Garnished 1.7.5+1.20.1
		geckolib: GeckoLib 4 4.4.4
			com_eliotlash_mclib_mclib: mclib 20
		gravestones: Gravestones v1.15
		handcrafted: Handcrafted 3.0.6
		hephaestusexpansion: HephaestusExpansion 1.0.1h+1.20.1
			config_toolkit: ConfigToolkit 1.0.0
				io_determann_shadow-api-17: shadow-api-17 0.1.1
				net_fabricmc_javapoet: javapoet 0.1.0
		hephaestusplus: HephaestusPlus 1.1.1+1.20
		iceberg: Iceberg 1.1.18
		immediatelyfast: ImmediatelyFast 1.2.11+1.20.4
			net_lenni0451_reflect: Reflect 1.3.2
		immersive_aircraft: Immersive Aircraft 0.7.5+1.20.1
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.2.1
		immersive_paintings: Immersive Paintings 0.6.7+1.20.1
		immersive_weathering: Immersive Weathering 1.20.1-2.0.1
		interiors: Create: Interiors 0.5.3+fabric-mc1.20.1
		item_obliterator: Item Obliterator 2.1.0
		itemborders: Item Borders 1.2.2
		java: OpenJDK 64-Bit Server VM 17
		justenoughbreeding: Just Enough Breeding 1.2.1
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		languagereload: Language Reload 1.5.10+1.20.1
		lazydfu: LazyDFU 0.1.3
		liquidburner: Liquid Burner 1.20.1-0.5
		lithium: Lithium 0.11.2
		lithostitched: Lithostitched 1.1.5
		majruszlibrary: Majrusz Library 7.0.5
		majruszsenchantments: Majrusz's Enchantments 1.10.7
		memoryleakfix: Memory Leak Fix 1.1.5
		merequester: ME Requester 1.20.1-1.1.4
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		modelfix: Model Gap Fix 1.15
		modernfix: ModernFix 5.17.0+mc1.20.1
		modmenu: Mod Menu 7.2.2
		monolib: MonoLib 1.0.1
		moonlight: Moonlight 1.20-2.11.12
		more_beautiful_torches: More Beautiful Torches! 3.0.0
		morechathistory: More Chat History 1.3.0
		moreculling: More Culling 1.20.4-0.24.0
			conditional-mixin: conditional mixin 0.3.2
		moredelight: More Delight 1.2.2-1.20.1-fabric
		moremobvariants: More Mob Variants 1.3.0.1
		mr_ketkets_furnicraft: FurniCraft 2.3
		mr_ns_fdrc: Nature's Spirit - Farmer's Delight Recipe Compat 0.0.1
		mr_villager_transportation: Villager Transportation 1.2
		muffins_thaidelight: Muffin's Thai's Delight 1.0.0
		mutantmonsters: Mutant Monsters 8.0.7
			extensibleenums: Extensible Enums 7.0.1
		mythicmounts: Mythic Mounts 1.20.1-7.2
		naturalist: Naturalist 4.0.3
		natures_spirit: Nature's Spirit 1.4.3.1.20.1
		necronomicon: Necronomicon 1.4.2
		nethersdelight: Nether's Delight Refabricated 1.20.1-4.0.3
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		nullscape: Nullscape 1.2.4
		numismatics: Create: Numismatics 1.0.3+fabric-mc1.20.1
		obscure_api: Obscure API 16
		oceansdelight: Ocean's Delight fdrf-fabric-1.0.2-1.20
		org_jetbrains_annotations: annotations 13.0
		owo: oωo 0.11.2+1.20
		oxidized: Oxidized 1.8.2
			saflib: SafLib 1.0.32
		packetfixer: Packet Fixer 1.3.2
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.8.0+1.14.4-1.20.4
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		player-animator: Player Animator 1.0.2-rc1+1.20
		playerplates: Player Plates 3.0.1+mc1.20.1
		powah: Powah! 5.0.5
		prism: Prism 1.0.5
		puzzleslib: Puzzles Lib 8.1.18
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		railways: Create: Steam 'n' Rails 1.6.3+fabric-mc1.20.1
		raknetify: Raknetify (Fabric) 0.1.0+alpha.5.116
		rechiseled: Rechiseled 1.1.6
		rechiseledcreate: Rechiseled: Create 1.0.2+a
		redstonebits: Redstone Bits 1.10.2
		resourcefullib: Resourceful Lib 2.1.24
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		respitecreators: Respite Creators 1.2.0
		rsmm_fabric: Redstone Multimeter Fabric 1.14.1
			amecsapi: Amecs API 1.5.0+mc1.20-pre1
		scorchful: Scorchful 0.6.1
		seasons: Fabric Seasons 2.3+1.20
		seasonsdelightcompat: Fabric Seasons: Delight Compat 1.0-1.3.9
		seasonsextras: Fabric Seasons: Extras 1.2-BETA+1.20
		seasonsterralithcompat: Fabric Seasons: Terralith Compat 1.0-2.3.7
		shakdel: Shakshuka Delight 1.0.0
		sihywtcamc: sihywtcamc 1.4.5+1.20.1
		sihywtcamd: sihywtcamd 1.10.1+1.20.1
		sliceanddice: Create Slice & Dice 3.2.1
		smallships: Small Ships 2.0.0-b1.1
		smarterfarmers: Smarter Farmers 1.20-1.8.2
		snifferplus: Hellion's Sniffer+ 0.3.0
		softerpastels: Softer Pastels 0.4.0-rev.352dd8c
		spell_engine: Spell Engine 0.14.3+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		spell_power: Spell Power Attribute 0.10.2+1.20.1
		spelunkery: Spelunkery 1.20.1-0.3.5
		starlight: Starlight 1.1.2+fabric.dbc156f
		stoneworks: Stoneworks 8.0.0
		storagedelight: Storage Delight 1.0.3-1.20.1-fabric
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17
		supplementaries: Supplementaries 1.20-2.8.10
		suppsquared: Supplementaries Squared 1.20-1.1.14
		tconstruct: Hephaestus 1.20.1-3.6.4.273
			mantle: Mantle 1.20.1-1.9.268
				star: Star 1.5.1+1.20.1
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.4+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.4+1.20.1
			porting_lib_common: Porting Lib Common 2.3.4+1.20.1
			porting_lib_config: Porting Lib Config 2.3.4+1.20.1
			porting_lib_core: Porting Lib Core 2.3.4+1.20.1
			porting_lib_data: Porting Lib Data 2.3.4+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
			porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
			porting_lib_items: Porting Lib Items 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
			porting_lib_model_loader: Porting Lib Model Loader 2.3.4+1.20.1
			porting_lib_models: Porting Lib Models 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
			porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
		terrablender: TerraBlender 3.0.1.4
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		terralith: Terralith 2.4.11
		terrestria: Terrestria 6.0.13
			biolith: Biolith 1.0.0-beta.1
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 7.0.3
			terraform-config-api-v1: Terraform Config API (v1) 7.0.3
			terraform-dirt-api-v1: Terraform Dirt API (v1) 7.0.3
			terraform-shapes-api-v1: Terraform Shapes API (v1) 7.0.3
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 7.0.3
			terraform-tree-api-v1: Terraform Tree API (v1) 7.0.3
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.3
			terrestria-client: Terrestria: Client 6.0.13
			terrestria-common: Terrestria: Common 6.0.13
			terrestria-worldgen: Terrestria: World Generation 6.0.13
		the_bumblezone: The Bumblezone - Fabric 7.3.5+1.20.1-fabric
			noindium: No Indium? 1.1.0+1.20
		thelongstory: The Long Story 0.2.8-1.20.1
		thermoo: Thermoo 2.3.1
		threadtweak: ThreadTweak 1.20.2-0.1.1
		tooltipfix: ToolTip Fix 1.1.1-1.20
		travelerstitles: Traveler's Titles 1.20-Fabric-4.0.2
		trinkets: Trinkets 3.7.2
		tropics: Tropics 1.0.3
		twigs: Twigs 3.1.0
		ubesdelight: Ube's Delight fabric-1.20.1-0.1.5.3
		universalcraft: UniversalCraft 323
		valkyrielib: ValkyrieLib 1.20.1-4.0.4.0
		valkyrienrelogs: ValkyrienRelogs 0.0.2
		valkyrienskies: Valkyrien Skies 2 2.3.0-beta.5
		variantbookshelves: Variant Bookshelves 2.3.8
		variantcraftingtables: Variant Crafting Tables 6.4
		veinmining: Vein Mining 1.4.0+1.20.1
		vietnamsdelight: Vietnam's Delight 1.0.2-1.20.1
		vigilance: Vigilance 295
		villager-hats: Villager Hats 1.6.2+1.20
		villagernames: Villager Names 7.3
		villagersplus: Villagers Plus 3.1
		voicechat: Simple Voice Chat 1.20.1-2.5.12
		vsas: Variant Sticks and Stuff 4.2.6
		wood_you_dye: Wood you Dye 1.1.0+1.20.1
		xaeroworldmap: Xaero's World Map 1.38.4
		yet_another_config_lib_v3: YetAnotherConfigLib 3.4.1+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.4
			org_javassist_javassist: javassist 3.29.2-GA
		zoomify: Zoomify 2.11.2
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6

**Comment by TropheusJ** [comment]
outdated addons, can't tell which

**Comment by lfpnub** [comment]
https://mclo.gs/YIBOewJ

I removed all addons that haven't been updated in the last 3 weeks.

**Comment by TropheusJ** [comment]
Patch F released 1.5 months ago.
Several addons still haven't updated.

**Comment by IThundxr** [comment]
farmersrespite is crashing because it depends on the deprecated farmers delight

liquid burner is outdated
