### ISSUE TITLE
Purple-black (none) texture when destroying a Large Waterwheel

### ISSUE THREAD

**Issue by BugInYourCode01** [Fabricators-of-Create/Create#1464]
### Describe the Bug

If you do not remove the center block of a Large Water Wheel, but one of the side blocks, these purple black particles appear, which indicate that there is no texture.

It would also be nice if the break particles matched the wood color of the Large Water wheel.

### Reproduction Steps

1. Place a Large Water wheel
2. Destroy it

### Expected Result

That only the middle block has particles or that all blocks would produce particles (which I would like best) or that the particles of the destroyed block are brownish.

### Screenshots and Videos

![2024-04-25_16 56 04](https://github.com/Fabricators-of-Create/Create/assets/163460667/1582b0be-5f24-4b26-942c-1e59a159c821)

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
fixed in dev
