### ISSUE TITLE
Large cogwheel can be placed directly next to small cogwheel

### ISSUE THREAD

**Issue by BugInYourCode01** [Fabricators-of-Create/Create#1465]
### Describe the Bug

If you place two small cogwheels next to each other and then hold a large cogwheel in your hand, a hologram appears indicating that you could place the large cogwheel directly next to the small one.

A large cogwheel can also be placed next to a small one as a schematic.

### Reproduction Steps

Rebuild the picture

### Expected Result

No hologram

### Screenshots and Videos

![2024-04-25_20 12 03](https://github.com/Fabricators-of-Create/Create/assets/163460667/2589468c-7511-4ccf-8b62-f9da89098dc6)

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
occurs on create forge aswell, report there
