### ISSUE TITLE
Copycat pannel with light block lost their brightness after chunk was unloaded.

### ISSUE THREAD

**Issue by hakua251** [Fabricators-of-Create/Create#1468]
### Describe the Bug

When a copycat pannel is decorated with a light block like sealantern,they send out brightness like a normal sealantern,but once the chunk where the copycat pannel was placed was unloaded,the copycat pannel lost their brightness,the blcok light become zero.

### Reproduction Steps

1.Place a copycat pannel
2.Decorate the copycat pannel with a ligt block like sealantern
3.Leave away from the chunk you placed the copycat pannel
4.Back to the chunk found the copycat pannel lost brightness

### Expected Result

copycat pannel decorated with light blcok keep their brightness after chunk is unloaded.

### Screenshots and Videos

Before the chunk is unloaded
![2024-04-27_22 58 44](https://github.com/Fabricators-of-Create/Create/assets/109947053/61366071-b675-46f0-b1ba-b5c5cfb6312d)
After the chunk is unloaded
![2024-04-27_22 58 57](https://github.com/Fabricators-of-Create/Create/assets/109947053/f99d23df-c042-4019-939a-d834bfa7b4a3)
F3 show the block light is zero
![image](https://github.com/Fabricators-of-Create/Create/assets/109947053/c8dfcca9-28dc-43b2-93d0-4eaf9c639c3a)

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

modmenu-7.1.0
magiclib-all-0.7.346+e235d92-stable
architectury-9.2.14-fabric
embeddium-fabric-0.3.11+mc1.20.1
fabric-api-0.92.0+1.20.1
fabric-language-kotlin-1.9.6+kotlin.1.8.22

**Comment by Nengyi-Jonathan-Jiang** [comment]
The same thing happens in the Forge version: [https://github.com/Creators-of-Create/Create/issues/4889](url).

**Comment by IThundxr** [comment]
Upstream issue
