### ISSUE TITLE
game crashes due to missing "$$0"

### ISSUE THREAD

**Issue by FiaTheDeermoth** [Fabricators-of-Create/Create#1469]
### Describe the Bug

The bug get's triggered when saving and using fortess mode from "MineFortress" mod. the log mentions a nulled "$$0".

### Reproduction Steps

1. install Create
2. install MineFortress
3. open a world, swap between survival and "Fortress" mode
4. press ESC or wait for the auto save

### Expected Result

Game runs normally

### Crash Report or Log

https://pastebin.com/jMzgEzJh - crash log | https://pastebin.com/ccKbiAk9 - log

### Operating System

Windows 10 Pro

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Minefortress.

**Comment by IThundxr** [comment]
Superseded by https://github.com/Fabricators-of-Create/Create/issues/1531
