### ISSUE TITLE
Incompatible with Starlight

### ISSUE THREAD

**Issue by Nolij** [Fabricators-of-Create/Create#147]
### Describe the Bug

When used with Starlight (mod which hugely boosts lighting performance, must have for a lot of people to get decent performance), the game crashes upon placing any block which has either a complex model or moves (haven't confirmed which).

Blocks known not to crash:
- Anything while it remains in the inventory
- Copper Tiles
- Andesite Casing
- Item Vault
- Basin

Blocks known to crash:
- Shaft
- Furnace Engine
- Flywheel

### Reproduction Steps

1. Install create and dependencies
2. Install latest Starlight
3. Place any of the above listed blocks which are known to crash

### Expected Result

Game should not crash

### Crash Report or Log

https://nextcloud.auvitau.xyz/s/nbce3joJW2dWtDD

### Operating System

Arch Linux

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

Fabric API 0.46.4+1.18
Starlight 1.0.0+fabric.d0a3220

### Additional Context

This build: https://github.com/Fabricators-of-Create/Create/actions/runs/1850424125 (the latest crashes upon launch, detailed in #146)

**Comment by TropheusJ** [comment]
Update starlight to 1.0.1.
