### ISSUE TITLE
Compatability Issue with Sound Physics Remastered

### ISSUE THREAD

**Issue by AoS999** [Fabricators-of-Create/Create#1470]
### Describe the Bug

When running **Create 0.5.1-f-build.1417+mc1.20.1** with **Sound Physics Remastered 1.20.1-1.3.1**, the two are found to be incompatible.

### Reproduction Steps

1) Have Create and Sound Physics Remastered in one instance's mod folder

2) Launch game

3) Game does not launch

### Expected Result

Expected the mods to run together, as prior versions were compatible.

### Crash Report or Log

https://gist.github.com/AoS999/1778d2a18f57fa0af9a8dd991bddc79d

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Fabric API: fabric-api-0.92.1+1.20.1.jar
Sound Physics Remastered: sound-physics-remastered-fabric-1.20.1-1.3.1.jar

### Additional Context

Launcher in use is MultiMC 5 - Version 0.7.0
Currently running 'Create 1.20.1 v0.5.1.f Patch 1'

**Comment by IThundxr** [comment]
https://github.com/Fabricators-of-Create/Create/issues/1432
