### ISSUE TITLE
Bugged textures of steam engines, chest and stressometer

### ISSUE THREAD

**Issue by IHaveNoIdea404** [Fabricators-of-Create/Create#1472]
### Describe the Bug

If you place steam engines theyll be working as normal but textures are black. This also hapens to many other blocks like stressometer etc

### Reproduction Steps

1.Generate new creative world
2.place fluid tanks in 3*3*3
3.Under fluid tanks place blaze burners and activate them by coal
4.Put water into the fluid tank
5.On the fluid tank place a steam engines
6.If you place a shaft on the steam engine, it will produce SU but the textures are black

### Expected Result

fix textures 

### Screenshots and Videos

![2024-05-03_18 03 01_2](https://github.com/Fabricators-of-Create/Create/assets/168850931/1d60279f-972b-4f29-b400-431c801e7f1e)

### Operating System

windows 11 64-bit

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Create Crafts & Additions
Create Enchantment Industry Fabric
Create Fabric
Create: Bells & Whistles
Create: Copycats+
Create: New Age
Create: Steam 'n' Rails
Jade

**Comment by IThundxr** [comment]
Please post your latest.log

**Comment by NolanHewitt** [comment]
Do you have an AMD gpu? There are issues with flywheel and 7000 series AMD gpu's that cause certain things to look like this such as chests. Create has flywheel built in.

**Comment by IHaveNoIdea404** [comment]
> Máš AMD gpu? Existují problémy se setrvačníkem a grafickými procesory AMD řady 7000, které způsobují, že některé věci vypadají takto, například truhly. Create má vestavěný setrvačník.

I do have an AMD graphic card but series 6000 and I've downloaded newest drivers and copletely reinstalled Minecraft and Curseforge and now its working fine.
