### ISSUE TITLE
Schematiccannon dupes schematics if you remove the input before it finishes

### ISSUE THREAD

**Issue by Twisted-Code** [Fabricators-of-Create/Create#1474]
### Describe the Bug

When schematiccann on begins a job, it copies the schematic data so that you can remove the input schematic. However, if you remove the input schematic and don't put it back before the job finishes, it will still output and empty schematic even though it was unable to consume the absent input. This means you can get extra schematics for free, which while generally kind of minor, could be kind of big if for some reason paper and/or cyan dye are more scarce than they are in vanilla.

### Reproduction Steps

1. Upload a schematic
2. Position the schematic
3. Place the schematic in a Schematiccannon
4. Start the job, preferably making sure it's missing at least one item it needs so that the job doesn't finish before the next step
5. Remove the non-blank schematic from the input
6. let the job finish, providing any blocks needed and so forth
7. you'll get an additional blank schematic even though you started with 1
...

### Expected Result

Don't produce a blank schematic if the input is absent. Perhaps the last tick the canon runs should have a method that takes any non-blank schematic OR minecraft:air and branches accordingly? Then the output of the blank is more directly tied to the input's presence.

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Everything in [this version](https://github.com/walksanatora/HexxyTestPack/commit/1cfba66bfdbd62ddac2226596662b0bef321cfb5) of [walksanatora/HexxyTestPack](http://walksanatora/HexxyTestPack)

**Comment by IThundxr** [comment]
Cannot reproduce
