### ISSUE TITLE
Crash when other person use schematics

### ISSUE THREAD

**Issue by NolanHewitt** [Fabricators-of-Create/Create#1476]
### Describe the Bug

Friend playing on my world tried to place a schematic, the confirm prompt showed up for me instead of them though, and then the game crashed a few seconds later. This happens anytime they try to use a schematic.

### Reproduction Steps

1. Have non-world-host place schematic
2. prompt shows for host then game crashes

### Expected Result

Not a crash

### Crash Report or Log

https://gist.github.com/NolanHewitt/72a64d52944a67e248de96f05dae9c00

### Operating System

Windows11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by electricsteve** [comment]
Seems to be lan issue. Someone needs to check if this happens upstream.

**Comment by IThundxr** [comment]
Fixed by upstream, will be released as part of 0.5.1.h
