### ISSUE TITLE
Flywheel renderer not compatibile with Vulkan API.

### ISSUE THREAD

**Issue by Mefisto095** [Fabricators-of-Create/Create#1477]
### Describe the Bug

So Create uses the standard old OpenGL calls in his custom renderer. If u want to play with Vulkan Renderer u cant because create calls OpenGL and Vulkan Rendered mod change the default rendered to Vulkan Api.

### Reproduction Steps

1.Install **Fabric API** and **Create**.
2.Add **Vulkan Renderer** to your mod list.
3.Start a Game.

### Expected Result

Get a **juicy** crash report.

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

**https://modrinth.com/mod/vulkanmod**
https://modrinth.com/mod/fabric-api

### Additional Context

I doubt that anything can be done about it by rewriting the mod from scratch. 
I'd **love** to **help**, but I'm **not** a **programmer**.

**Comment by Oliver-makes-code** [comment]
There is no way this incompatibility can feasibly be fixed. Changing graphics APIs is a hard task to do, and it's hard to take advantage of the new API because the software was designed with another API in mind

**Comment by PepperCode1** [comment]
The default backends in Flywheel 1.0.0 (instancing and indirect), which is in development but almost complete, will automatically disable themselves if they see that a Vulkan mod is installed. In general, this means that all of Flywheel's performance benefits will also be disabled, but at least it will not cause a crash. Flywheel 1.0.0 is designed such that a separate mod can register a backend that will also use Vulkan. Currently, there are no plans to develop a default/official/first-party backend like this.

**Comment by Mefisto095** [comment]
> The default backends in Flywheel 1.0.0 (instancing and indirect), which is in development but almost complete, will automatically disable themselves if they see that a Vulkan mod is installed. In general, this means that all of Flywheel's performance benefits will also be disabled, but at least it will not cause a crash. Flywheel 1.0.0 is designed such that a separate mod can register a backend that will also use Vulkan. Currently, there are no plans to develop a default/official/first-party backend like this.

t's good to hear that there is some hope, thanks for the answer :)

**Comment by IThundxr** [comment]
closing as this is gonna be fixed eventually by flywheel 1.0.0
