### ISSUE TITLE
Not compatible with flux networks

### ISSUE THREAD

**Issue by AshdoII** [Fabricators-of-Create/Create#1478]
### Describe the Bug

when installed with flux networks, will show " Unexpected custom data from client" when create new world/enter exsisting worlds.

### Reproduction Steps

1.install minecraft 1.20.1, fabric 0.15.11
2.install fabric api 0.92.1, create fabric 0.5.1-f-build.1417, flux networks 7.2.8
3.start game, create new world,  get"Unexpected custom data from client"
...

### Expected Result

 Unexpected custom data from client

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/111554896/6ee31ebc-5cf4-4d6a-a799-cb70bfafa86c)

### Crash Report or Log

https://pastebin.com/wCScpYvV

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

fabric api 0.92.1, create fabric 0.5.1-f-build.1417, flux networks 7.2.8

**Comment by IThundxr** [comment]
install https://modrinth.com/mod/porting_lib/version/2.3.4+1.20.1
