### ISSUE TITLE
Create Crafting Recipe for Exposure Mod does not show up in EMI, even with JEI installed

### ISSUE THREAD

**Issue by SabrCat** [Fabricators-of-Create/Create#1479]
### Describe the Bug

How it should look and does look on forge with create, exposure, jei, emi:
![image](https://github.com/Fabricators-of-Create/Create/assets/56313836/a0a6e2fe-290d-432a-abed-968d8da4a6d3)
What I see with the same mod set on fabric:
![image](https://github.com/Fabricators-of-Create/Create/assets/56313836/66fef073-d9ee-4fb8-b0bd-9795a075aa03)
(I have confirmed this to still persist on a minimal modset)

### Reproduction Steps

1. Install JEI, EMI, Create and Exposure in a new fabric instance
2. Launch the game
3. Search for film in the EMI menu and look at the crafting recipe of developed film

### Expected Result

As shown in the first image, the create recipe should show up, but it does not. 
[r1RnLOg.txt](https://github.com/Fabricators-of-Create/Create/files/15264973/r1RnLOg.txt)

### Crash Report or Log

[r1RnLOg.txt](https://github.com/Fabricators-of-Create/Create/files/15264973/r1RnLOg.txt)

### Operating System

Win10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
Exposure hardcodes this, it’s not a real recipe. This compat code is only on forge.
