### ISSUE TITLE
I'm not able to swim

### ISSUE THREAD

**Issue by isushrist** [Fabricators-of-Create/Create#1480]
### Describe the Bug

I go to water and just drop nothing in my inv i just drop like im a rock it ignores water 

### Reproduction Steps

1.i go into the water
2.no swim up
3.die
...

### Expected Result

to swim instead of sinking

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/118482274/640dd497-329c-4956-bdfb-71fa0398da75

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.18.2

### Other Mods

no

**Comment by IThundxr** [comment]
![image](https://github.com/Fabricators-of-Create/Create/assets/74031881/76ec8489-38b4-4373-85c3-9e92af5fbe73)
can't reproduce, the modpack your playing on has likely changed something or you are wearing netherite diving armor

**Comment by TropheusJ** [comment]
Something is breaking the Minecraft:water tag

**Comment by KonSola5** [comment]
Install the LMFT mod (https://www.curseforge.com/minecraft/mc-mods/lmft) - it will:
- load tags despite incorrect entries,
- print into chat what would cause the tag to not load without this mod.
