### ISSUE TITLE
There is a bug where generation model textures are missing.

### ISSUE THREAD

**Issue by sbeom0308** [Fabricators-of-Create/Create#1481]
### Describe the Suggestion

This model is missing textures on some devices

Water Wheel
Large Water Wheel
Crushing Wheel
Blaze Burner (empty included)
Valve Handle (All colors included)
Mechanical Roller
Flywheel

Additionally, the Fluid Pipe is operating normally, but the texture appears to be disjointed

The texture models of the above devices are displayed as shown in the attached photo below

### Screenshots and Videos

![2024-05-11_07 22 02](https://github.com/Fabricators-of-Create/Create/assets/109639261/2e399eb5-88fa-4d6e-91b0-bcfc01dda60a)
![2024-05-11_07 22 32](https://github.com/Fabricators-of-Create/Create/assets/109639261/dc1d8288-e8fc-4541-b3ae-3bae73287de0)
![2024-05-11_07 36 39](https://github.com/Fabricators-of-Create/Create/assets/109639261/905a4762-c4a1-41c7-a288-b6f3ed2a2f0a)

**Comment by IThundxr** [comment]
if you are using sodium you need indium for models to render properly

**Comment by sbeom0308** [comment]
Thank you for quick response!!!
Solved as a result of using indium👍👍👍
