### ISSUE TITLE
Blacklist for the Mechanical Drill and simmilar

### ISSUE THREAD

**Issue by NextRaven10** [Fabricators-of-Create/Create#1482]
### Describe the Suggestion

Make a editable and expandable blacklist for the Mechanical Drill, the mechanical Saw and simmilar. For all things that can destroy something. For e.x. if I would add Obsidian to this list then the Drill just would go trough it without mining it or just stop entirely based on the config.

### Additional Context

I would like this so you can nerf the Mechanical Drills and Simmilar and so Graves can´t be destroyed and loose all their NBT Data :/

**Comment by IThundxr** [comment]
This should be suggested in the create discord server
