### ISSUE TITLE
unknown crash

### ISSUE THREAD

**Issue by FengQ9955** [Fabricators-of-Create/Create#1483]
### Describe the Bug

使用创造马达将转速调到256测试的时候突然崩溃，但重新登录后并未回档，仍然保持崩溃退出时的状态
When using the create motor and set the speed to 256 for testing, it suddenly crashed, but after logging in again, it did not reverse and still remained in the state it was when it crashed and exited

### Reproduction Steps

/

### Expected Result

no crash

### Screenshots and Videos

launcher
![启动器](https://github.com/Fabricators-of-Create/Create/assets/124785203/de9e0a3e-a9f7-4cfa-96d8-82486ae18b57)
崩溃信息  Crash information
![兼容错误](https://github.com/Fabricators-of-Create/Create/assets/124785203/360c3b8e-6760-4812-9042-a4b2c7da36f8)
提到的模组The mod mentioned
quartz
Anvilcraft（Under development）https://github.com/Anvil-Dev/AnvilCraft
QuickBackupMulti  https://github.com/SkyDynamic/QuickBackupM-Fabric

### Crash Report or Log

See above.

### Operating System

windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

![modlist1](https://github.com/Fabricators-of-Create/Create/assets/124785203/ea60c690-0528-438a-8bd9-279c5b514a4f)
![modlist2](https://github.com/Fabricators-of-Create/Create/assets/124785203/b9a45327-aedd-4d3b-8cbe-48fc8f2e6b51)

### Additional Context

其他模组作者的回答  Answers from other mod authors【QuickBackupMulti】
![11111111](https://github.com/Fabricators-of-Create/Create/assets/124785203/eec2c56a-6848-4867-af80-1bedafab2ef2)
该问题触发在Schedule Backup中, 追溯到 make 方法中的 server.saveAll(true, true, true); 行, 可知是发生在保存世界中的问题, 该问题不属于QuickBackupMulti的问题
This issue is triggered in the Schedule Backup and can be traced back to server. saveAll (true, true, true) in the make method; Okay, it can be seen that this is an issue that occurred in the saved world, and it does not belong to QuickBackupMulti

**Comment by FengQ9955** [comment]
上述回答来自于AnvilCraft的github界面，回答者为QuickBackupMulti的作者
The above answer is from the GitHub interface of AnvilCraft, and the respondent is the author of QuickBackupMulti

该作者认为这个问题应该来自于Create而不是AnvilCraft或QuickBackupMulti
The author believes that this issue should come from Create rather than AnvilCraft or QuickBackupMulti

本篇报告均为翻译器翻译
This report is translated by a translator

**Comment by IThundxr** [comment]
attach the crash log

**Comment by FengQ9955** [comment]
.zip
[错误报告-2024-5-11_17.17.40.zip](https://github.com/Fabricators-of-Create/Create/files/15289365/-2024-5-11_17.17.40.zip)

**Comment by electricsteve** [comment]
Hmmmmm, doesn't reallly look like issue with create, I would say try without create, but yea the create things cause it, so idk. I think it's just an incompatibility with the other mod(s).

**Comment by FengQ9955** [comment]
thanks ：）
