### ISSUE TITLE
[Suggestion] Skip 1.20.4 to 1.20.6

### ISSUE THREAD

**Issue by MbtMarco** [Fabricators-of-Create/Create#1485]
It would be better not to update the mod to 1.20.4 but directly to 1.20.6 because now that 1.20.5/6 has been released, players will no longer use 1.20.4, so for the next few months the most used versions will be 1.20. 1 and 1.20.6, it makes no sense to focus on a version that is no longer in use.

**Comment by AnnoyedUser420** [comment]
Are you regarded? 1.20.4 is not going to die.

**Comment by mainrs** [comment]
> Are you regarded? 1.20.4 is not going to die.

It's not worth it to spend time and effort for versions in-between if newer ones have already been released. The majority of people will update to 1.20.6 and 1.21. The more resources are put into versions in-between, the less resources are available to catch up with the newest version.
