### ISSUE TITLE
Crushing wheels controller causing blocks to be unmovable by mechanical piston (sticky & regular)

### ISSUE THREAD

**Issue by SageofTurtles** [Fabricators-of-Create/Create#1486]
### Describe the Bug

I was working out a contraption design, and when testing if it would move correctly, I encountered a strange bug where the sticky/regular mechanical piston would give an "Unable to assemble contraption" message, citing an unmovable block on the contraption.  These blocks should all have been movable, however.  The ones I saw with this design included encased fans, crushing wheels, and shafts.  Which block was considered unmovable seemed to depend on which direction the piston was pushing the contraption.  When I tried breaking the cited block, it allowed me to extend the mechanical sticky piston like normal, but when trying to retract the mechanical sticky piston, it then cited an entirely different unmovable block.  I've attached a .zip file with the schematic I was using (which I tested in multiple singleplayer worlds to confirm the issue was consistent).  I have no clue what would be causing this, any help is appreciated.

[schematic.zip](https://github.com/Fabricators-of-Create/Create/files/15301278/schematic.zip)

### Reproduction Steps

1. Download & unzip the schematic.zip file, then place the NBT file in the schematics folder.
2. Open a world and paste the schematic.
3. Using a mechanical piston or mechanical sticky piston and a handcrank, attempt to push the contraption from any side.
4. For me, it always gives an unmovable block error preventing the contraption from assembling, with a different block being unmovable depending on the direction of the mechanical piston.

### Expected Result

None of the blocks on the contraption should be unmovable, so one would expect it to move when pushed or pulled by a mechanical piston.

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Create Enchantment Industry 1.2.16
Create (Fabric) 0.5.1.d, build 1417
Fabric API 0.92.1

(Contraption was built with blocks from Extended Drawers 2.1.1, but when testing I forgot and removed this mod by accident.  However, the bug still occurred without Extended Drawers installed.)

**Comment by SageofTurtles** [comment]
Okay, so I've done a bit more testing with this, and it seems to be an issue with the crushing wheels controller (I think that's what it was called—it's the phantom block that exists between two crushing wheels). Anytime you try to push/pull a block in a path that goes through this phantom block between two crushing wheels, it registers whichever block would go through the space where the controller is as "unmovable". This only seems to apply when the block is immediately adjacent to the controller.

**Comment by electricsteve** [comment]
hmmmm, dont know if that is supposed to happen. Maybe rename the issue with the discovery to something like "Contraption unmovable when going through crushing wheel controller."

**Comment by TropheusJ** [comment]
Also occurs on forge, an issue needs to be made there
