### ISSUE TITLE
Shaders bug with create

### ISSUE THREAD

**Issue by PolyframeX** [Fabricators-of-Create/Create#1487]
### Describe the Bug

When enabling shaders, most contraptions will have strange blocky like lighting. Causing issues.

### Reproduction Steps

1. Install iris, sodium, and create
2. Use any shader (in this case Complimetary 5.1.1)
3. Make a contraption, and light sources near it
4. Turn on shaders
...

### Expected Result

Lighting should effect contraptions as normal, and look like an entity

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/80133652/0107a037-7428-4162-8056-0e5fa821c92e

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Embeddium 0.3.18
Iris 1.7.0
Also breaks when tested with:
Sodium 0.5.8
Indium 1.0.30

**Comment by NolanHewitt** [comment]
This might be unrelated, but do you have the [flywheel-iris-compat](https://modrinth.com/mod/iris-flw-compat) mod? It’s mostly for performance but might be worth a try.

**Comment by PolyframeX** [comment]
Everytime I use flywheel iris compat, my game crashes, presumably being incompatible with my iris version.

**Comment by drwoops** [comment]
iris flywheel compat has been updated to latest iris.

**Comment by PolyframeX** [comment]
Ah, well despite this, my game still does crash.

**Comment by drwoops** [comment]
then provide the crash report

**Comment by PolyframeX** [comment]
https://pastebin.com/uFLYtCWL

**Comment by drwoops** [comment]
your iris flywheel compat is NOT up to date. you need https://modrinth.com/mod/iris-flw-compat/version/iris-1.20.1-0.2.5

**Comment by PolyframeX** [comment]
Ah, my bad. This issue also seemingly solved itself randomly, even without flywheel compat. So I'm not sure what happened.
