### ISSUE TITLE
Cannot create casings using cherry logs

### ISSUE THREAD

**Issue by YLlywelyn** [Fabricators-of-Create/Create#1488]
### Describe the Bug

I take an andesite ingot, right click on a stripped cherry log and nothing happens.

### Reproduction Steps

1. Right click a stripped cherry log with an andesite alloy
2.
3.
...

### Expected Result

I expect the stripped cherry log to become an andesite casing.

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

N/A - no crash

### Additional Context

Assuming this means cherry logs won't work with the rest of the mod either but haven't been able to test yet.

**Comment by IThundxr** [comment]
cannot reproduce

create-fabric-0.5.1-f-build.1417+mc1.20.1
emi-1.1.6+1.20.1+fabric
fabric-api-0.92.1+1.20.1
