### ISSUE TITLE
Multiple contraptions causes huge lag spikes 1.20.1 FABRIC

### ISSUE THREAD

**Issue by Jerikk07** [Fabricators-of-Create/Create#1489]
### Describe the Bug
It's on Minecraft 1.20.1 FABRIC

I have around 10 train contraptions circling around an area around 32+ chunks.
It's on a hosted server.
The game run at an average of 80 fps. But the fps drops down to 0/20 for 20/30 secs then returns to normal. 
This happens everywhere in this 32 chunks area, around all 5/10 minutes (it's reccurent but random).
It's the same lag I have when I log on the server  and the game is loading the chunks. 
I tried to optimize it with better chunk loading, which works fine, like the log lag have almost disapeard, but this is issue is still there.
I also tried using entity distance. I tried with the minimal and the maximal render distance (up to 512 blocks). The bug was still there in both configurations. So it's not a render issue I'd say.. and the fps were still good overhaul.

As it is now, it looks to me like a chunk loading/unloading issue with the contraption (this bug doesn't happens in area without contraptions).

I have put together all the optimisation mods I could find but yet nothing have yet seems to do a real difference for this issue.
I tried to optimise the cpu render thread, did nothing, the same for the ram, I went from 28gb to 8gb hoping it was a kind of memory issue (too uch ram isn't good) but it did nothing.
Also the server is on OMG-Server, I can't modify the ram nor the Java argument. The server is supposed to dynamically gives enough ram to the game.

I have many mods, but everything else than this area is running just fine.

![2024-05-12_14 33 52](https://github.com/Fabricators-of-Create/Create/assets/168867969/5a1801ae-8773-4933-8181-3511d4f0d944)
![2024-05-12_14 39 07](https://github.com/Fabricators-of-Create/Create/assets/168867969/3acab1ac-642e-4691-89e2-223bba39b034)

### Reproduction Steps

1. have many trains contraptions circling in a 32 chunks area
2. wait for some minutes
3. experience huge lags for up to 30 secs
...

### Expected Result

The game not lagging randomly 

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
shaders disable flywheel it's likely caused by that, try without shaders

**Comment by Jerikk07** [comment]
It still the same without shaders, and I have the flywheel compatibility

**Comment by TropheusJ** [comment]
performance reports are not helpful without running a profiler or providing exact reproduction steps.
