### ISSUE TITLE
Large Water Wheel particles

### ISSUE THREAD

**Issue by NEO245LOL** [Fabricators-of-Create/Create#1492]
### Describe the Bug

particles not showing properly

### Reproduction Steps

1.break water wheel except the center part
2.the particles wont show properly
![image_2024-05-18_094819634](https://github.com/Fabricators-of-Create/Create/assets/77661584/5d5fccec-647f-4db0-9204-00092f27228a)

### Expected Result

particles should be there

### Screenshots and Videos

![image_2024-05-18_094826975](https://github.com/Fabricators-of-Create/Create/assets/77661584/f6666631-9e54-4286-97e9-a7dee3b0e6ca)

### Operating System

windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
fixed in https://github.com/Fabricators-of-Create/Create/commit/fdfb875713d9a63ab992dac4449afc6b1608fe34
