### ISSUE TITLE
Corruption of Item Data when a hopper pushes into a toolbox - Dupe

### ISSUE THREAD

**Issue by SabrCat** [Fabricators-of-Create/Create#1493]
### Describe the Bug

I think a video illustrates this best (below), but in short, if I place a hopper on top of a toolbox and then very quickly throw many different items into the hopper, some items appear to be getting transformed into other items that were in the hopper. My guess would be that this is related to the custom storage slots that can go up to 256, and to zero without loosing the item assigned. 
Do note that whenever an item converts, the type of item that got lost in the conversion to another (e.g. when dirt turned into nether star, the dirt) did not get a permanent slot assigned in the toolbox. When I shift click out all the items, all others keep a zero stack, but that particular one does not. This may be related to the cause of the issue here.

Testing in a modpack:

https://github.com/Fabricators-of-Create/Create/assets/56313836/7ced5cfc-3559-49b6-8f07-ff1962e26cc6

Testing in a minimal modset, only create fabric and mc

https://github.com/Fabricators-of-Create/Create/assets/56313836/03c7c017-277c-460f-a19c-691c37d6370a

https://github.com/Fabricators-of-Create/Create/assets/56313836/9365b4a0-835c-48fb-8fa7-6d5d6ed914c2

And here's a log from the minimal modset:
[7iexZoi.txt](https://github.com/Fabricators-of-Create/Create/files/15365227/7iexZoi.txt)

### Reproduction Steps

see videos

### Expected Result

no items should be converted

### Screenshots and Videos

see above

### Crash Report or Log

[7iexZoi.txt](https://github.com/Fabricators-of-Create/Create/files/15365227/7iexZoi.txt)

### Operating System

Win10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
1.20.1 only ~ doesn't affect forge and doesn't happen on any other version

**Comment by ChickenDestroyer** [comment]
Also, does not only work with hoppers, but any other form of item input. Tested with chutes, and all items were converted to 1 type.
