### ISSUE TITLE
Assembly of a contraption without movement does not cause Portable Storage Interfaces to connect

### ISSUE THREAD

**Issue by SabrCat** [Fabricators-of-Create/Create#1494]
### Describe the Bug

When one assembles a contraption with a PSI on it, and another PSI is already in position to connect to it, they do not connect. This is not a visual glitch, item transfer is also impossible. Most of the time that I've seen this issue, the PSI on contraption side did extend, but the PSI on block side did not extend. A reliable way to circumvent the issue is to power the block side PSI and unpower it again. Sometimes a block update is also sufficient. 

### Reproduction Steps

https://github.com/Fabricators-of-Create/Create/assets/56313836/34106a2c-3fcb-444f-90f5-07195951d347

### Expected Result

The PSIs should connect immediately when the contraption assembles. This is what quite a few of my technical contraptions are based on, and they are broken by this issue. 

### Screenshots and Videos

[Fe9gakb.txt](https://github.com/Fabricators-of-Create/Create/files/15365318/Fe9gakb.txt)

### Crash Report or Log

[Fe9gakb.txt](https://github.com/Fabricators-of-Create/Create/files/15365318/Fe9gakb.txt)

### Operating System

Win10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
occurs on forge aswell, should be reported to the forge repo
