### ISSUE TITLE
Server overload

### ISSUE THREAD

**Issue by Blutaar23** [Fabricators-of-Create/Create#1495]
### Describe the Bug

We use the create mod on our server and one of the group has several chunks packed with different machines, which causes huge overload.

we removed 100 water wheels. This was the first overload.

Later he built 10 Steam Engines. Second overload.

We use New Age where he build tens of generator coils and hundreds of wires. Third overload.

Is this normal in the create mod server branch? Is create not supposed to be used on servers or in larger quantities?

### Reproduction Steps

1.Create Mod on A server
2.Bunch of machines
3.
...

### Expected Result

No server overload caused by create mod in any regular capacity. We don´t do stuff in the range of a TNT world or something. 

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
Allocate more resources to your server, many run public servers with create just fine.

**Comment by Blutaar23** [comment]
I surveyed the overload with the spark mod and our CPU usage is at 2% and RAM is at 4GB of 10 GB.

What are some standard resource allocations? And as far as I understand it this issue is more traffic related, maybe network?
