### ISSUE TITLE
Crash on world start, or creation

### ISSUE THREAD

**Issue by Userbingd** [Fabricators-of-Create/Create#1497]
### Describe the Bug

It crashes when I try to join, or create a world, sometimes without even making a crash report.

### Reproduction Steps

1. Install the mod
2. Create world
3. Crash
...

### Expected Result

It should work

### Crash Report or Log

https://pastebin.com/ztLq2DGX

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

            Architectury
		Chisels-and-bits
		Cloth Config
		Collective
		Comforts
		Create fabric
		Distant Horizons
		When Dungeons Arise
		FTB Chunks
		FTB Library
		fTB Teams
		FTB Ultimine
		handcrafted
		Hide Experimental Warning
		Indium
	        Just Enough Items 
		Kiwi
	        Moonlight
	        Player Animator		
            Resoursful lib
		Serious Player Animations
		Snow! Real Magic! 
		Snowy Spirit
		sodium
		tectonic
		valkyrien skies
            Eureka
            Clockwork

**Comment by IThundxr** [comment]
create_interactive is crashing
