### ISSUE TITLE
Do Honey bottles contain 250 mB of honey or 333 1/3 mB?

### ISSUE THREAD

**Issue by BugInYourCode01** [Fabricators-of-Create/Create#1498]
### Describe the Bug

In https://github.com/MehVahdJukaar/amendments/issues/81 @MehVahdJukaar told me that all bottles contain 333 1/3 mB on Fabric liquid. Does this also apply to honey bottles? Because you can empty them for 250 mB, but you get 333 1/3 mB of honey if you pump it from a bees nest. Is this simply to make Ceate more effective than Vanilla Metoden (like shaft cutting is more effective than shaft crafting) or do you still have the Forge system?
Also, at 333 1/3 mB per bottle, you couldn't make honey blocks liquid anymore, as this consists of 4 * 333 1/3 mB = 1333 1/3 mB. So it would be nice if you could either give bottles 333 1/3 mB when spouting/emptying or if you could put 4 honey bottles in a cauldron, even if this would require either a new cauldron type or a layer 0 in the fluid cauldron exclusively for honey.

### Reproduction Steps

Otherwise there is a dublication glitch:
1. fill a basin with a bucket
2. take out 4 bottles of honey
3. put three bottles of it into a cauldron
4. take the honey out again with a bucket. You have made an extra honey bottle.

### Expected Result

Standardised fluid quantities.

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by MehVahdJukaar** [comment]
To add onto this the unit of a bottle would be, as defined in FluidConstants.BOTTLE_AMOUNT, 27000 fabric fluid units

**Comment by TropheusJ** [comment]
Honey bottles need to use 1/4 instead of 1/3 as vanilla defines 1 block as 4 bottles.

**Comment by drwoops** [comment]
but that's only because of forge limitations, otherwise 1 block of honey could be defined as made of 4/3b... or do i miss something?

**Comment by IThundxr** [comment]
> but that's only because of forge limitations, otherwise 1 block of honey could be defined as made of 4/3b... or do i miss something?

filling water bottles with a cauldron is a 1:3 ratio (1 bucket for 3 bottles of water)

**Comment by TropheusJ** [comment]
4 bottles -> 1 block is a vanilla recipe

**Comment by drwoops** [comment]
i understand both these things. so i must be missing something.  why should a block of honey correspond to a bucket of honey?

**Comment by TropheusJ** [comment]
It’s an established standard and it makes sense in-world.
Either the bottle standard or the block standard has to be broken, I chose to break bottles because mods shouldn’t even need to care about it because of the fluid api. Honey cauldron was not anticipated.

**Comment by drwoops** [comment]
I see; but this is not a vanilla standard. so are we not back pointing the finger at forge?

thank you for humoring me. i appreciate the explanation.

**Comment by MrRedstoneToGo** [comment]
I was only thinking of a honey cauldron because the fluid cauldrons (Admendments) in fabric only have three block states and would need a fourth for honey. @MehVahdJukaar, you could also make it that honey is also allowed in the fluid cauldron and then, unlike the other liquids, fills it completely to the edge.

**Comment by MrRedstoneToGo** [comment]
> so are we not back pointing the finger at forge
No, vanilla minecraft! Sometimes it matches Forge (honey bottles), sometimes Fabric (water bottles)...

**Comment by BugInYourCode01** [comment]
> so are we not back pointing the finger at forge

No, vanilla minecraft! Sometimes it matches Forge (honey bottles), sometimes Fabric (water bottles)...

**Comment by IThundxr** [comment]
> > so are we not back pointing the finger at forge
> 
> No, vanilla minecraft! Sometimes it matches Forge (honey bottles), sometimes Fabric (water bottles)...

forge nor fabric are involved here, cauldrons are in 3 fill levels where the water bottles come from which is 1 bucket = 3 bottles and honey bottles is where you get the block = 4 bottles from

**Comment by MrRedstoneToGo** [comment]
I know, after all I didn't say it depends on the mod loader, but a modloader **matches**/**fits** better.

**Comment by BugInYourCode01** [comment]
I know, after all I didn't say it depends on the mod loader, but it **matches**/**fits** better with one of the mod loaders.

**Comment by MehVahdJukaar** [comment]
> Honey bottles need to use 1/4 instead of 1/3 as vanilla defines 1 block as 4 bottles.

but why would 1 block be equal to 1 bucket? 1 bucket = 3 bottle and 1 block  = 4 bottles. doesnt all that add up?

**Comment by Technici4n** [comment]
The whole thing doesn't make sense. I have always meant for honey bottles to be 250 mb on Fabric too but it felt silly to add a constant just for that. Maybe it would have avoided this discussion at least. 😄
(I wrote `FluidConstants`.)

**Comment by TropheusJ** [comment]
> but why would 1 block be equal to 1 bucket? 1 bucket = 3 bottle and 1 block = 4 bottles. doesnt all that add up?

FluidConstants also defines a block as 81000.
Changing honey bottles to 1/3 will also require increasing the capacity of basins, which has a lot of implications, and is really not something I want to do.
I am going to keep them as 1/4. As long as mods use the transfer API properly, there shouldn't be any issues.

**Comment by MehVahdJukaar** [comment]
Tbh the only constant that seem made up is that one of that block right there. The other 2 are backed up by the cauldron recipe, the block however is not, should be 4 bottles for bottles themselves to be a consistent unit of measure

**Comment by BugInYourCode01** [comment]
No, the variable BLOCK does not actually stand for honey blocks, but for iron/gold blocks. These consist of 9 INGOTs, which consist of 9 NUGGETs. A melted NUGGET is defined as 1000 droplets, an INGOT is 9 times as many and a BLOCK is 81 times as many.
Why else would Fabric have such weird units if not for this?
Both the problem of representing the amount of molten metals or the cauldron problem (which was not actually intended for honey!) were solved, as well as the specification of 1/4 buckets.

**Comment by MehVahdJukaar** [comment]
so where else does the convertion between 1 bucket = 4 bottles instead of 3 comes from?

**Comment by IThundxr** [comment]
> Changing honey bottles to 1/3 will also require increasing the capacity of basins, which has a lot of implications, and is really not something I want to do.

**Comment by BugInYourCode01** [comment]
I just watched a video about some Minecraft facts (https://youtube.com/watch?v=8rB2TQSPLuA) and there was one about honey and water bottles (at 8:36). Honey bottles are actually filled a little HIGHER than water bottles. This does not make the calculations any easier, but I think it is something to mention.
