### ISSUE TITLE
Can not place a Train signal on a large curved Train track

### ISSUE THREAD

**Issue by Tibitt** [Fabricators-of-Create/Create#1499]
### Describe the Bug

it is not always possible to place a Train signal on a large curved Train track

### Reproduction Steps

1. Set Configure -> Gameplay Settings -> Trains -> Max Track Placement Length to 128
2. Place a long curved Train track
3. Try to place Train signal somewhere closer to the middle of it
...

### Expected Result

a Train signal to place

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.19.2

### Other Mods

another_furniture-fabric-1.19.2-2.1.4.jar
architectury-6.5.85-fabric.jar
bellsandwhistles-0.4.41.19.2-12.jar
better-clouds-1.2.10+1.19.2.jar
borderless-mining-1.1.5+1.19.jar
cloth-config-8.3.115-fabric.jar
continuity-2.0.1+1.19.jar
create-fabric-0.5.1-f-build.1416+mc1.19....
do-a-barrel-roll-2.6.2+1.19.2-fabric.jar
ExtendedDrawers-1.4.5+mc.1.19.2.jar
fabric-api-0.77.0+1.19.2 (1).jar
fabric-language-kotlin-1.10.17+kotlin.1.9...
farmers-delight-fabric-1.3.10.2.jar
immersive_aircraft-0.7.9+1.19.2-fabric.jar
indium-1.0.9+mc1.19.2.jar
lambdynamiclights-2.2.0+1.19.2.jar
lithium-fabric-mc1.19.2-0.11.1.jar
man_of_many_planes-0.0.4+1.19.2-fabric...
Mouse Tweaks-fabric-mc1.19-2.22.jar
Roughly Enoughltems-9.1.682-fabric.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
YetAnotherConfigLib-2.2.0-for-1.19.2.jar
Zoomify-2.9.0.jar

**Comment by IThundxr** [comment]
https://github.com/Creators-of-Create/Create/issues/6965
