### ISSUE TITLE
Deployers crash Dedicated Servers when placed

### ISSUE THREAD

**Issue by Alkiasan** [Fabricators-of-Create/Create#150]
### Describe the Bug

Whenever a Deployer is placed, it crashes the dedicated server

### Reproduction Steps

1.Place Deployer
2.Server Crashes

### Expected Result

Server runs normally

### Crash Report or Log

https://www.toptal.com/developers/hastebin/zelohanubo.yaml

### Operating System

Windows 11

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
duplicate of #117
