### ISSUE TITLE
Chutes and funnels don't work when supplied with fan power

### ISSUE THREAD

**Issue by 8a56** [Fabricators-of-Create/Create#1501]
### Describe the Bug

When an item like sand gets pushed by a fan into either a side funnel, a chute underneath it or both with filters for soul sand. Once the sand is right on top of the chute and/or right next to the funnel, and is haunted into soul sand, the funnels and chutes will not collect it until the fan is off.

### Reproduction Steps

1. Have fans move items directly to or from the fan into a chute/funnel with filters of the 
expected item after smelted/haunted/smoked.
2. Have the item either smelted/haunted/smoked in the process before the item goes into the chute/funnel.
3.  The item will not go through the funnel/chute unless the fan pushing it directly into the chute/funnel is turned off.

### Expected Result

The item does not go through the chute/funnel.

### Screenshots and Videos

https://youtu.be/gwem-51bV_g

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Valkyrien Skies
Applied Energistics 2

**Comment by IThundxr** [comment]
This issue is not related to create and is caused by a addon mod/another mod.

valkyrien skies issue
