### ISSUE TITLE
The game keeps crashing when trying to place shaft

### ISSUE THREAD

**Issue by hpndd** [Fabricators-of-Create/Create#1502]
### Describe the Bug

Hi
I'm hpndd.The game keeps crashing when I place the following blocks:Shaft,cogwhell,water whell,Many blocks are related to shafts and cogwheels. It causes my game to constantly crash after placing the above blocks.

### Reproduction Steps

1.I placed the block in relation to the shaft and cogwheel.
2.After that, my game froze and crashed my game.
3. End

...

### Expected Result

I hope my game will never have that error again.

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

-create-fabric-0.5.1-f-build.1417+mc1.20.1
-fabric-api-0.92.1+1.20.1
-farmers-delight-fabric-1.4.3
-jei-1.20.1-fabric-15.3.0.4
-lazydfu-0.1.3
-modmenu-7.2.2
-Steam_Rails-1.6.4+fabric-mc1.20.1

**Comment by drwoops** [comment]
you need to attach the crash report file.  in the absence of that information, my guess is that you need to replace farmers delight fabric (which is deprecated) with farmers delight refabricated.

**Comment by hpndd** [comment]
Oh,okay,thank.But,I'm still worried.

**Comment by IThundxr** [comment]
send the crash log

**Comment by hpndd** [comment]
I deleted the crash log accidentally.

**Comment by hpndd** [comment]
Please help, my game crashes again.

**Comment by drwoops** [comment]
you were asked for a crash report which you still haven't provided

**Comment by hpndd** [comment]
Okay, just kidding

**Comment by drwoops** [comment]
@IThundxr close the issue, ban the troll

**Comment by IThundxr** [comment]
Do not make bug reports with the intention of wasting other people's time ever again.

**Comment by hpndd** [comment]
OK

**Comment by hpndd** [comment]
Never
