### ISSUE TITLE
Incompatible with Sound Physics Remastered

### ISSUE THREAD

**Issue by Jemnand** [Fabricators-of-Create/Create#1503]
### Describe the Bug

I tried launching the game with a small mod pack that contained the create mod and Sound Physics Remastered, the fabric loader gave me the information that I have to remove one of those mods to make the other one work properly. Is that a bug or a wanted occurrence? Thanks for helping me out.

### Reproduction Steps

1. Download the create mod 1.20.1 and Sound Physics Remastered 1.20.1
2. Add both to your mod folder
3. Launch the game and the error should occur
...

### Expected Result

I expected the game to launch normally and that I would have been able to enjoy both mods with my friends. 

### Screenshots and Videos

I will add those when I gathered some.

### Operating System

Windows 10 pro

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

As the error didn’t mention any other mods, a list of all the mods that were contained in the mod pack would just extend your capabilities and take too much time for you to review. Thanks for understanding.

**Comment by drwoops** [comment]
sound physics remastered fixed the issue like... yesterday.  so create has not yet been updated to allow SPR >=1.4.0.

you could do it yourself: https://fabricmc.net/wiki/tutorial:dependency_overrides

**Comment by Jemnand** [comment]
Okay thanks for that quick response and that information. I wasn’t aware of that.

**Comment by AClon314** [comment]
> sound physics remastered fixed the issue like... yesterday. so create has not yet been updated to allow SPR >=1.4.0.
> 
> you could do it yourself: https://fabricmc.net/wiki/tutorial:dependency_overrides

In shorts:
1. Unzip `create-fabric-0.5.1-f-build.1417+mc1.20.1.jar`
2. remove line 71 in `fabric.mod.json`
```json
"breaks": {
    "optifabric": "*",
    "colormatic": "\u003c\u003d3.1.1",
    "iris": "\u003c\u003d1.2.5",
    "sodium": "\u003c\u003d0.4.10",
    "sound_physics_remastered": "*",    // Remove this line
```
3. exec in shell: `jar cvf create-fabric-0.5.1-f-build.1417+mc1.20.1_SPRfix.jar .`

**Comment by Fyoncle** [comment]
> > sound physics remastered fixed the issue like... yesterday. so create has not yet been updated to allow SPR >=1.4.0.
> > you could do it yourself: https://fabricmc.net/wiki/tutorial:dependency_overrides
> 
> In shorts:
> 
> 1. Unzip `create-fabric-0.5.1-f-build.1417+mc1.20.1.jar`
> 2. remove line 71 in `fabric.mod.json`
> 
> ```json
> "breaks": {
>     "optifabric": "*",
>     "colormatic": "\u003c\u003d3.1.1",
>     "iris": "\u003c\u003d1.2.5",
>     "sodium": "\u003c\u003d0.4.10",
>     "sound_physics_remastered": "*",    // Remove this line
> ```
> 
> 3. exec in shell: `jar cvf create-fabric-0.5.1-f-build.1417+mc1.20.1_SPRfix.jar .`

You can just do this in fabric preferences on the config file, you don't need to edit the mod files, this wouldn't be suitable for a modpack.

**Comment by monomere** [comment]
Instead of editing mod files, you can create a file called `fabric_loader_dependencies.json` in the `.minecraft/config/` folder (create it if its not there) with this content:
```json
{
  "version": 1,
  "overrides": {
    "create": {
      "-breaks": {
        "sound_physics_remastered": "*"
      }
    }
  }
}
```

**Comment by jacklollz2** [comment]
I'm using Quilt, how would I create the override? Also, it's annoying the mod hasn't updated yet to push this...

**Comment by drwoops** [comment]
> I'm using Quilt, how would I create the override?

maybe check this: https://github.com/QuiltMC/quilt-loader/wiki/Dependency-Overrides

**Comment by jacklollz2** [comment]
I tried as best I could but everything is obscured and confusing.

**Comment by Yummy-cookie** [comment]
forge how to change

**Comment by nobully-osu** [comment]
> I'm using Quilt, how would I create the override? Also, it's annoying the mod hasn't updated yet to push this...

Using a loader override like fabric but slightly different. Try this: 
```
{
    "schema_version": 1,
    "overrides": [
      {
        "path": "<mods>/create-fabric-0.5.1-f-build.1417+mc1.20.1.jar",
        "breaks": {
          "remove": {
            "id": "sound_physics_remastered",
            "versions": "*"
          }
        }
      }
    ]
  }
```

For easy convenience: 
[quilt-loader-overrides.json](https://github.com/user-attachments/files/17594868/quilt-loader-overrides.json)
