### ISSUE TITLE
Elevator dissapeared

### ISSUE THREAD

**Issue by Dorfyt** [Fabricators-of-Create/Create#1504]
### Describe the Bug

When i arrived after adventure to my base i found that elevator(and everything in it) is just missing.
Though elevator pulley is still there

### Reproduction Steps

No idea

### Expected Result

No idea

### Operating System

Windows 10 22H2

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Modpack All Of Fabric 7

### Additional Context

I know that i gave too little information, but I have no idea how that could've happened

**Comment by cfpwastaken** [comment]
is the pulley going to the bottom of the floor? Try calling some stations (some dont work). The pulley should start moving and the elevator will come into view again.

**Comment by DarianLStephens** [comment]
I've had that exact same issue happen many times on my survival server, and calling it to a different station has worked every time.
Maybe the entity loads before the world, so its target block doesn't exist yet, so it just... goes down to 0?
Does that also happen in the Forge version?

**Comment by Dorfyt** [comment]
![2024-06-25_23 52 48](https://github.com/Fabricators-of-Create/Create/assets/79335749/e6206987-e050-40c8-9965-4518caf9df15)
I found that it gone deep underground

**Comment by cfpwastaken** [comment]
![image](https://github.com/Fabricators-of-Create/Create/assets/44261356/59c3281b-b006-46dd-ba02-d9346a980a75)
adding to this, i am using a mechanical piston contraption to move the elevator contact away to disable that station. Right now, i just enabled the station with my button and the elevator started going down to y=0 right away at full speed. The deepslate down there is the elevator.
