### ISSUE TITLE
Water Wheel Crashing

### ISSUE THREAD

**Issue by thedeadhorsey** [Fabricators-of-Create/Create#1507]
### Describe the Bug

Whenever me or my friend break a water wheel or place it down or do anything with it, it crashes the game and sometimes the launcher

### Reproduction Steps

1. Place It down/Break it/Interact with it in anyways
2. Thats it, dont know what else to say
3.
...

### Expected Result

We can break the water wheel

### Screenshots and Videos

https://www.youtube.com/watch?v=uSilcvXNy04&feature=youtu.be

### Crash Report or Log

https://pastebin.com/ZW1gisH4

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/164976025/4d2082b5-82a7-4737-8d91-4af05dd335bb)
![image](https://github.com/Fabricators-of-Create/Create/assets/164976025/d175962c-6ffe-41a4-82a2-a4211bf362cf)
![image](https://github.com/Fabricators-of-Create/Create/assets/164976025/b0d34f78-1266-4fe8-b4b6-60d472b33659)
![image](https://github.com/Fabricators-of-Create/Create/assets/164976025/5e349fd4-1984-4c7f-bead-cf2b8aa14aac)
![image](https://github.com/Fabricators-of-Create/Create/assets/164976025/e267dbd3-debb-4a27-97d1-94eb6a8f2d72)

**Comment by IThundxr** [comment]
0.4.1 is very old and unsupported, update to newer create
