### ISSUE TITLE
tickting entity from moving contraption (tested on mechanical sticky piston)

### ISSUE THREAD

**Issue by keenan1127** [Fabricators-of-Create/Create#1508]
### Describe the Bug

taking items out of the storage of a contraption while it's depositing those items by a portable storage interface causes it to become a ticking entity upon returning to original position.

### Reproduction Steps

1. make a contraption with a storage container with items and a portable storage interface that at some point transfers items from that interface
2. while it's attached to that interface, open the storage container and take out the items inside
3. wait for the piston to fully retract or stop
4. get annoyed because you caused a ticking entity crash.

### Expected Result

it should just carry on with what it was doing instead of trying to move items that were already removed

### Operating System

Windows 10

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

### Other Mods

too many to count, but none were used to cause this other than create, oh, and expanded storage...

**Comment by keenan1127** [comment]
also, how do I change the labels?
sorry, haven't used github much

**Comment by IThundxr** [comment]
update create
