### ISSUE TITLE
make the liquids for chocolate and honey actually make sense

### ISSUE THREAD

**Issue by keenan1127** [Fabricators-of-Create/Create#1509]
### Describe the Suggestion

just make the placed version of liquids for honey and chocolate be very slow and sticky, like being in lava.
have you *tried* swimming in molten chocolate or a pool of honey? it is NOT as easy as swimming in water.

**Comment by IThundxr** [comment]
suggestions should go to the forge repo

**Comment by keenan1127** [comment]
> suggestions should go to the forge repo

1. ok, I'll move it over
2. why do you have a suggestion part in the issues section if that's the case??
