### ISSUE TITLE
deployer stop working

### ISSUE THREAD

**Issue by wolfien1** [Fabricators-of-Create/Create#1510]
### Describe the Bug

when I place the deployer I set it to attack mode and put a sword on it so after killing the first mob it writes the error message shown in the chat image below.

### Reproduction Steps

1.place deployer
2.click on it with wrench to set it to attack mode
3.put on it diamond sword with some enchants
4.connect it to energy source
5.deployer starts hitting mob
6.when the mob is killled deployer drop error message to chat just like in the picture which should be in the bug description

### Expected Result

the deployer will start hitting and killing mobs

### Screenshots and Videos

![2024-05-30_15 37 07](https://github.com/Fabricators-of-Create/Create/assets/171258347/7ac11efd-c0d4-48d1-8b2d-b5f728ba1772)

### Crash Report or Log

error message: [Neruina]: Caught Ticking Block Entity [Deployer] at position [x=84, y=-21, z=7411. Please resolve

### Operating System

Windows 10

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

no other mods

**Comment by IThundxr** [comment]
update create

**Comment by wolfien1** [comment]
I can´t update create. I am on server
