### ISSUE TITLE
Copycat Panel breaking particles are missing textures when Continuity is installed

### ISSUE THREAD

**Issue by MentoskaPraha** [Fabricators-of-Create/Create#1511]
### Describe the Bug

The Copycat Panel block's breaking particles show missing textures when they are broken. This only occurs when the mod [Continuity](https://modrinth.com/mod/1IjD5062) is installed.

### Reproduction Steps

1) Setup a fresh Fabric install with mods listed in other mods.
1) Apply both resourcepacks provided by Continuity named: Glass Pain Culling Fix and Default Connected Textures, with Glass Pain Culling Fix being above Default Connected Textures in the resourcepack list.
1) Create and join a new world
1) Place down any Copycat block
1) Break the placed copycat block, the break particle textures should now be missing

### Expected Result

The Copycat Panel's breaking particles show the correct texture instead of the black and purple not found texture.

## Observed Result
https://github.com/Fabricators-of-Create/Create/assets/103432169/12d71289-540d-4799-b76c-9282f0a07cc0

## Expected Result
https://github.com/Fabricators-of-Create/Create/assets/103432169/8ee054a9-9072-4f09-82fc-2333ced623be

### Crash Report or Log

https://mclo.gs/lGXWFnm

### Operating System

Arch Linux

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

- Minecraft (`1.20.1`)
- Fabric Loader (`0.15.11`)
- Fabric API ([`0.92.2+1.20.1`](https://modrinth.com/mod/P7dR8mSH/version/P7uGFii0))
- Create Fabric ([`0.5.1-f-build.1417+mc1.20.1`](https://modrinth.com/mod/Xbc0uyRg/version/h2HgGyvA))
- Continuity ([`3.0.0-beta.5+1.20.1`](https://modrinth.com/mod/1IjD5062/version/84Zs6tNo))

### Additional Context

It doesn't seem to occur when the resourcepacks with connected textures are disabled. 
The issue also occurs with all the copycat blocks from [Create: Copycats+](https://modrinth.com/mod/UT2M39wf), however it isn't caused by it.

**Comment by IThundxr** [comment]
search for your issue before creating one, this already has been fixed in dev.

**Comment by MentoskaPraha** [comment]
Whoops. That's on me, sorry about that.
