### ISSUE TITLE
Revert SPR Marked As Broken

### ISSUE THREAD

**Issue by Fyoncle** [Fabricators-of-Create/Create#1512]
### Describe the Bug

The bug has been solved by henkelmax already.
https://github.com/henkelmax/sound-physics-remastered/issues/172

### Reproduction Steps

To solve this;
1. Revert back the changes you made on SPR to avoid using it together.

### Expected Result

If you add a config on fabric dependencies config most likely like;
{
  "version": 1,
  "overrides": {
    "create": {
      "breaks": {
        "sound_physics_remastered": "<1.4.0"
      }
    }
  }
}

Then Create can work perfectly fine with SPR Mod with latest releases.

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
please actually look at what i said, it's fixed in dev already

**Comment by Fyoncle** [comment]
> please actually look at what i said, it's fixed in dev already

Wdym In Dev?? where he said that.

**Comment by IThundxr** [comment]
https://github.com/henkelmax/sound-physics-remastered/issues/172#issuecomment-2146301799
https://github.com/henkelmax/sound-physics-remastered/issues/172#issuecomment-2132007713

> The next version of Create Fabric is expected to remove that declaration of incompatibility. https://github.com/Fabricators-of-Create/Create/commit/b12d4d839d3b5a3bb707e4a5a75c9055f8b5f274

**Comment by Fyoncle** [comment]
> [henkelmax/sound-physics-remastered#172 (comment)](https://github.com/henkelmax/sound-physics-remastered/issues/172#issuecomment-2146301799) [henkelmax/sound-physics-remastered#172 (comment)](https://github.com/henkelmax/sound-physics-remastered/issues/172#issuecomment-2132007713)
> 
> > The next version of Create Fabric is expected to remove that declaration of incompatibility. [b12d4d8](https://github.com/Fabricators-of-Create/Create/commit/b12d4d839d3b5a3bb707e4a5a75c9055f8b5f274)

I thought you mean SPR

**Comment by skellitor301** [comment]
Is there any planned eta for when this will be released to Modrinth/Curseforge? Or are there still other things still being worked on for the next version?
