### ISSUE TITLE
The server is constantly crashing

### ISSUE THREAD

**Issue by M0PAH** [Fabricators-of-Create/Create#1513]
### Describe the Bug

We put together a build of mods on create, a week later the server began to shut down

### Reproduction Steps

We tried to reproduce so that the server turned off, but nothing helped, it turned off itself after 5-20 minutes of operation

### Expected Result

To make the server work stably

### Crash Report or Log

https://pastebin.com/5N5VxxRs

### Operating System

ubuntu - minecraft hosting

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

advancementinfo-1.20-fabric0.83.0-1.4.jar
AdvancementPlaques-1.20.1-fabric-1.4.11.jar
animal_feeding_trough-1.0.3+1.20.1.jar
appleskin-fabric-mc1.20.1-2.5.1.jar
appliedenergistics2-fabric-15.2.0.jar
architectury-9.1.12-fabric.jar
areas-1.20.1-5.0.jar
artifacts-fabric-9.5.5.jar
badpackets-fabric-0.4.3.jar
balm-fabric-1.20.1-7.1.4.jar
bclib-3.0.14.jar
bellsandwhistles-0.4.5+1.20.1-FABRIC.jar
better-end-4.0.11.jar
better-nether-9.0.10.jar
bettercombat-fabric-1.8.2+1.20.1.jar
BetterF3-7.0.1-Fabric-1.20.1.jar
bettermounthud-1.2.2.jar
biomemakeover-FABRIC-1.20.1-1.11.4.jar
blur-3.1.0.jar
Bookshelf-Fabric-1.20.1-20.1.6.jar
Botania-1.20.1-444-FABRIC.jar
botarium-fabric-1.20.1-2.3.3.jar
cardinal-components-api-5.2.2.jar
carryon-fabric-1.20.1-2.1.2.5.jar
chunkloaders-1.2.8a-fabric-mc1.20.1.jar
Chunky-1.3.146.jar
clickthrough-1.20-fabric0.83.0-0.4.1.jar
cloth-config-11.1.106-fabric.jar
Clumps-fabric-1.20.1-12.0.0.3.jar
collective-1.20.1-6.72.jar
Copycats-fabric.1.20.1-1.2.6.jar
create_enchantment_industry-1.2.16.jar
create_jetpack-fabric-4.2.0.jar
create-fabric-0.5.1-f-build.1335+mc1.20.1.jar
create-new-age-fabric-1.20.1-1.1.pre5.jar
deeperdarker-fabric-1.20-1.2.6.jar
DetailArmorBar-2.6.3+1.20.1-fabric.jar
doggo-mod-overhauled-5.3.1.jar
dynamiclights-v1.7-mc1.17x-1.20x-mod.jar
e4mc-4.0.1+1.19.4-fabric.jar
EasyAnvils-v8.0.1-1.20.1-Fabric.jar
easyauth-mc1.20-3.0.19.jar
eating-animation-1.20+1.9.5-CMDfix.jar
eden-ring-20.1.20.jar
edf-remastered-4.3.jar
elytraslot-fabric-6.3.0+1.20.1.jar
entityculling-fabric-1.6.2-mc1.20.1.jar
essential_1-2-3_fabric_1-20-1.jar
ExtendedDrawers-2.0.7+mc.1.20.1.jar
fabric-api-0.92.2+1.20.1.jar
fabric-language-kotlin-1.10.10+kotlin.1.9.10.jar
fabric-seasons-2.3+1.20.jar
fabric-seasons-terralith-2.3.7-compat-1.0.jar
farmers-delight-fabric-1.4.3.jar
fast-portals-1.0.3.jar
ferritecore-6.0.1-fabric.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
graves-3.0.0+1.20.1.jar
healingcampfire-1.20.1-5.1.jar
herdspanic-1.0.7.jar
Highlighter-1.20.1-fabric-1.1.6.jar
Iceberg-1.20.1-fabric-1.1.15.jar
indium-1.0.21+mc1.20.1.jar
InventoryProfilesNext-fabric-1.20-1.10.9.jar
itemswapper-fabric-0.5.3-mc1.20.1.jar
jei-1.20.1-fabric-15.2.0.27.jar
lazydfu-0.1.3.jar
libIPN-fabric-1.20-4.0.0.jar
lithium-fabric-mc1.20.1-0.11.2.jar
lootr-fabric-1.20-0.7.33.81.jar
midnightlib-fabric-1.4.1.1.jar
minecells-1.8.2.jar
modelfix-1.14-fabric.jar
modmenu-7.2.2.jar
modmenu-badges-lib-2023.6.1.jar
monsters-in-the-closet-1.0.3+1.20.jar
notenoughcrashes-4.4.6+1.20.1-fabric.jar
owo-lib-0.11.2+1.20.jar
pal-1.8.0.jar
Patchouli-1.20.1-84-FABRIC.jar
plasmovoice-fabric-1.20.1-2.0.9.jar
player-animation-lib-fabric-1.0.2-rc1+1.20.jar
PlayerHealthIndicators-1.1.0-1.20.1.jar
PresenceFootsteps-1.9.1.jar
PuzzlesLib-v8.1.5-1.20.1-Fabric.jar
Rrls-3.2.0-1.20.1-fabric.jar
serversleep-datapack.jar
shulkerboxtooltip-fabric-4.0.4+1.20.1.jar
skin-restorer-1.2.4.jar
sodium-fabric-mc1.20-0.4.10+build.27.jar
supermartijn642configlib-1.1.8a-fabric-mc1.20.jar
supermartijn642corelib-1.1.15-fabric-mc1.20.1.jar
Terralith_1.20.2_v2.4.8.jar
the_bumblezone-7.3.8+1.20.1-fabric.jar
tia-1.20-1.1-fabric.jar
tool-trims-mod-v2-0-1a-1-20.jar
tooltipfix-1.1.1-1.20.jar
TrampleNoMore-Fabric-1.20.1-13.0.2.jar
trashslot-fabric-1.20-15.1.0.jar
travelers-backpack-1.20.1-9.1.8.jar
travelersbackpack-fabric-1.20.1-9.1.12.jar
trinkets-3.7.1.jar
trinkets-3.7.2.jar
wthit-fabric-8.4.1.jar
Xaeros_Minimap_23.8.4_Fabric_1.20.jar
yet-another-config-lib-fabric-3.2.1+1.20.jar
YungsApi-1.20-Fabric-4.0.2.jar
YungsBetterDesertTemples-1.20-Fabric-3.0.3.jar
YungsBetterDungeons-1.20-Fabric-4.0.3.jar
YungsBetterEndIsland-1.20-Fabric-2.0.4.jar
YungsBetterJungleTemples-1.20-Fabric-2.0.4.jar
YungsBetterMineshafts-1.20-Fabric-4.0.4.jar
YungsBetterNetherFortresses-1.20-Fabric-2.0.5.jar
YungsBetterOceanMonuments-1.20-Fabric-3.0.3.jar
YungsBetterStrongholds-1.20-Fabric-4.0.3.jar
YungsBetterWitchHuts-1.20-Fabric-3.0.3.jar
YungsBridges-1.20-Fabric-4.0.3.jar

**Comment by IThundxr** [comment]
bclib's got a mixin doing something weird with sorting a list, report to them probably

**Comment by M0PAH** [comment]
> bclib's got a mixin doing something weird with sorting a list, report to them probably

How can I solve this problem?
