### ISSUE TITLE
Chute and Smart Chute can't pick up items with an encased fan working

### ISSUE THREAD

**Issue by Fattysand** [Fabricators-of-Create/Create#1515]
### Describe the Bug

Chute and Smart Chute can't pick up items with an encased fan working, such as sand. When 'Bulk Haunting' the sand, if encased fan is working, the Smart Chute cannot pick up soul sand until I shut down the encased fan or use a block to stop airflow. It's not the same as Forge. Is it a bug only happen in fabric 1.19.2? My 'create' mod version is 0.5.1c and 0.5.1f.

### Reproduction Steps

1.use encased fan to 'Bulk Haunting' the sand
2.use smart chute to filter sand and collect soul sand
3.soul sand cannot enter the chute
4.when i shut down encased fan or use block to stop airflow, soul sand can enter the chute
...

### Expected Result

i don't need to shut down encased fan or use block to stop airflow and the smart chute will work well in Forge. but it doesn't work in fabric

### Crash Report or Log

no crash occur

### Operating System

windows 11

### Mod Version

0.5.1c

### Minecraft Version

1.19.2

**Comment by Fattysand** [comment]
water flow sometimes also causes this problem

**Comment by IThundxr** [comment]
do you have create interactive or any valkyrien skies addon?

**Comment by Fattysand** [comment]
> do you have create interactive or any valkyrien skies addon?

yes i have 'valkyrien skies' 2.2.0-beta.3-version

**Comment by IThundxr** [comment]
that's your issue

**Comment by Fattysand** [comment]
> do you have create interactive or any valkyrien skies addon?

i remove 'valkyrien skies' and fix the problem! thank u very much!!!
