### ISSUE TITLE
There are issues with gear maps in Create,and some related items are missing maps 

### ISSUE THREAD

**Issue by ChenXing370** [Fabricators-of-Create/Create#1516]
### Describe the Bug

Map problem

### Reproduction Steps

no

### Expected Result

no

### Screenshots and Videos

![2024-06-09_14 20 32](https://github.com/Fabricators-of-Create/Create/assets/172167968/7e4eb3c6-3f99-47b5-9b19-4799ab8f2add)
![2024-06-09_14 20 48](https://github.com/Fabricators-of-Create/Create/assets/172167968/91c23ecd-af83-41dd-aefe-b9c5108055d9)
![2024-06-09_14 25 19](https://github.com/Fabricators-of-Create/Create/assets/172167968/2e709536-64b9-44b5-ac8a-e6f8d5b76b6a)
![2024-06-09_14 20 10](https://github.com/Fabricators-of-Create/Create/assets/172167968/39ad785b-fc36-4801-9386-22f041eaf09f)
![2024-06-09_14 20 32](https://github.com/Fabricators-of-Create/Create/assets/172167968/3183b9f9-1fac-41d5-ac31-18842f9deb67)
![2024-06-09_14 20 48](https://github.com/Fabricators-of-Create/Create/assets/172167968/dd2ff3fc-bce6-4460-9445-01d81a59493a)
![2024-06-09_14 25 19](https://github.com/Fabricators-of-Create/Create/assets/172167968/f9ee3469-f657-40d1-a830-187f5e85478d)

### Crash Report or Log

no

### Operating System

Windows11

### Mod Version

0.5.1f

### Minecraft Version

1.19.2

### Other Mods

no

### Additional Context

fabric

**Comment by IThundxr** [comment]
Unable to reproduce, if you are able to consistently reproduce this with just create + fabric api feel free to open a new issue
