### ISSUE TITLE
Crash on my server

### ISSUE THREAD

**Issue by TheRaventy** [Fabricators-of-Create/Create#1517]
### Describe the Bug

We are playing on an aternos server, exploring, when we were in a dungeon (When Dungeons Arise mod) and suddently our mc crashed, but not the server.

### Reproduction Steps

Steps ⬆️ 

### Expected Result

⬆️ :arrow_up:

### Screenshots and Videos

I dont have in this situation it isnt possible

### Crash Report or Log

https://paste.gg/p/anonymous/54a41ccbc75f4fb0b2def1cfdda27aa0

### Operating System

Windows 11 / Curseforge app / Majnr + modpack (Edited with more mods)

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

advancednetherite-fabric-2.0.3-1.20.1.jar
appleskin-fabric-mc1.20.1-2.5.1.jar
architectury-9.2.14-fabric.jar
azurelib-fabric-1.20.1-2.0.20.jar
azurelibarmor-fabric-1.20.1-2.0.3.jar
bclib-3.0.14.jar
better-end-4.0.11.jar
better-nether-9.0.10.jar
Bookshelf-Fabric-1.20.1-20.1.9.jar
botarium-fabric-1.20.1-2.3.3.jar
cardinal-components-api-5.2.2.jar
carryon-fabric-1.20.1-2.1.2.7.jar
Chunky-1.3.138.jar
cloth-config-11.1.118-fabric.jar
Clumps-fabric-1.20.1-12.0.0.3.jar
collective-1.20.1-7.40.jar
CreativeCore_FABRIC_v2.11.24_mc1.20.1.jar
creeperoverhaul-3.0.2-fabric.jar
Croptopia-1.20.1-FABRIC-3.0.4.jar
cupboard-fabric-1.20.1-2.6.jar
DungeonsArise-1.20.x-2.1.58-fabric-release.jar
dynamiclights-v1.7.1-mc1.17x-1.20x-mod.jar
EasyAuth
easyauth-mc1.20-3.0.19.jar
Emojiful-Fabric-1.20.1-4.2.0.jar
EnchantmentDescriptions-Fabric-1.20.1-17.0.14.jar
EpheroLib-1.20.1-FABRIC-1.2.0.jar
extraspellattributes-1.1.1.jar
fabric-api-0.92.0+1.20.1.jar
fabric-language-kotlin-1.10.19+kotlin.1.9.23.jar
farmers-delight-fabric-1.4.3.jar
fastpaintings-1.20-1.2.5-fabric.jar
ferritecore-6.0.1-fabric.jar
framework-fabric-1.20.1-0.6.27.jar
ftb-essentials-fabric-2001.2.2.jar
ftb-library-fabric-2001.1.5.jar
ftb-ranks-fabric-2001.1.3.jar
geckolib-fabric-1.20.1-4.4.4.jar
Gobber2-Fabric-1.20.1-2.9.3.jar
goblintraders-fabric-1.20.1-1.9.3.jar
hamsters-fabric-1.0.3-1.20.1.jar
handcrafted-fabric-1.20.1-3.0.6.jar
immersive_armors-1.6.1+1.20.1-fabric.jar
immersive_paintings-0.6.7+1.20.1-fabric.jar
IronChests-2.0.2.jar
itemcollectors-1.1.9-fabric-mc1.20.jar
Jade-1.20-fabric-11.8.0.jar
jei-1.20.1-fabric-15.3.0.4.jar
journeymap-1.20.1-5.9.18p1-fabric.jar
JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar
lazydfu-0.1.3.jar
letmedespawn-fabric-1.20.x-1.2.0.jar
lithium-fabric-mc1.20.1-0.11.2.jar
lootr-1.20-0.7.30.77.jar
malilib-fabric-1.20.1-0.16.3.jar
memoryleakfix-fabric-1.17+-1.1.5.jar
mes-1.3-1.20-fabric.jar
midnightlib-fabric-1.4.1.jar
mighty_mail-fabric-1.20.1-1.0.14.jar
moonlight-1.20-2.11.4-fabric.jar
moremobvariants-fabric+1.20-1.2.2.jar
mythicmobs-1.20.1-fabric-1.4.5.jar
naturalist-fabric-4.0.3-1.20.1.jar
paladins-1.0.5+1.20.1.jar
Patchouli-1.20.1-84-FABRIC.jar
player-animation-lib-fabric-1.0.2-rc1+1.20.jar
plushies-1.4.0-fabric.jar
RegionsUnexploredFabric-0.5.5+1.20.1.jar
repurposed_structures-7.1.13+1.20.1-fabric.jar
resourcefulconfig-fabric-1.20.1-2.1.2.jar
resourcefullib-fabric-1.20.1-2.1.23.jar
runes-fabric-0.9.11+1.20.1.jar
simplyswords-fabric-1.54.0-1.20.1.jar
smoothchunk-fabric-1.20.1-3.6.jar
sound-physics-remastered-fabric-1.20.1-1.3.1.jar
spell_engine-0.12.5+1.20.1.jar
spell_power-fabric-0.9.19+1.20.1.jar
spellbladenext-1.9.0.jar
supermartijn642configlib-1.1.8a-fabric-mc1.20.jar
supermartijn642corelib-1.1.17-fabric-mc1.20.1.jar
supplementaries-1.20-2.8.5-fabric.jar
TerraBlender-fabric-1.20.1-3.0.1.4.jar
Terralith_1.20.4_v2.4.11.jar
tidal-towns-1.2.jar
travelers-backpack-1.20.1-9.1.9.jar
treeharvester-1.20.1-8.7.jar
trinkets-3.7.2.jar
tru.e-ending-v1.1.0c.jar
voicechat-fabric-1.20.1-2.5.9.jar
weathersettings-fabric-1.20.1-2.0.jar
wizards-1.0.5+1.20.1.jar
yet-another-config-lib-fabric-3.2.2+1.20.jar
YungsApi-1.20-Fabric-4.0.4.jar
YungsBetterDesertTemples-1.20-Fabric-3.0.3.jar
YungsBetterDungeons-1.20-Fabric-4.0.3.jar
YungsBetterJungleTemples-1.20-Fabric-2.0.4.jar
YungsBetterNetherFortresses-1.20-Fabric-2.0.6.jar
YungsBetterOceanMonuments-1.20-Fabric-3.0.4.jar
YungsBetterStrongholds-1.20-Fabric-4.0.3.jar

**Comment by drwoops** [comment]
you should always post the entire crash report.  in any case the error seems to happen in starlight

**Comment by TheRaventy** [comment]
Nope, when i removed it, it still crashed

**Comment by TheRaventy** [comment]
only when i removed the entire Create set it stopped

**Comment by drwoops** [comment]
then post the full crash report without it

**Comment by TheRaventy** [comment]
Ok wait a sec

**Comment by TheRaventy** [comment]
i have to find it
somewhere

**Comment by TheRaventy** [comment]
Finally i founded it

**Comment by TheRaventy** [comment]
https://paste.gg/p/anonymous/8391c272ffe147b280f41d0e300e53e9

**Comment by drwoops** [comment]
starlight is still used in this crash

**Comment by IThundxr** [comment]
update create

**Comment by TheRaventy** [comment]
> starlight is still used in this crash

Yes

**Comment by TheRaventy** [comment]
I already fixed it, but i only want creators to fix it

**Comment by IThundxr** [comment]
it's been fixed in 0.5.1-f, like said above update create

**Comment by TheRaventy** [comment]
ok thanks
