### ISSUE TITLE
One of the methods to crash servers or client

### ISSUE THREAD

**Issue by XionioXMaster** [Fabricators-of-Create/Create#152]
### Describe the Bug

https://youtu.be/beEhtqeCqjM

This is the height bypass method that can crash servers and their clients

### Reproduction Steps

1.https://youtu.be/beEhtqeCqjM

### Expected Result

expected crash) 

### Crash Report or Log

https://gist.github.com/XionioXMaster/01bab181c175f2f888324b03652dc3d3

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

nope

**Comment by AlphaMode** [comment]
Have you tested this on the forge version?

**Comment by DavidIngalls** [comment]
I can reproduce this with Forge 0.4d.

**Comment by AlphaMode** [comment]
Please make a issue about this on upstream then

**Comment by XionioXMaster** [comment]
> Please make a issue about this on upstream then

Bot closed issuge which I created in Forge version after 2 weeks
