### ISSUE TITLE
No UI for train station on a server

### ISSUE THREAD

**Issue by BigMommaBee** [Fabricators-of-Create/Create#1520]
### Describe the Bug

While playing on a server, clicking on the train station brings up no UI. Train station works normally in singleplayer

### Reproduction Steps

1. Place train tracks
2. Register train station to track and place it
3. Right click on train station to bring the UI

### Expected Result

Expected: Train station UI to appear to allow building the train in both singleplayer and multiplayer

Result: No UI appears while in multiplayer

### Screenshots and Videos

Multiplayer not working: https://youtu.be/MJJwP94C5TA

Singleplayer working correctly: https://youtu.be/AAgZ4jnvsIg

### Crash Report or Log

Clientside log while trying to access train station UI: https://pastebin.com/d5Lytds2

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Serverside:
- Amendments
- Appleskin
- Architectury
- Automobility
- Badpackets
- Balm
- Blendium
- Better Chunk Loading
- Bookshelf
- Brewin And Chewin
- c2me
- Cardinal Components
- Carryon
- Charm of undying
- Chunky
- Cloth Config
- Coffins
- Collective
- Container Search
- CoroUtil
- Cosmetic Armor
- Create
- Create Structures
- Create Enchantment Industry
- Create Additions
- Create Big Cannons
- Create Deco
- Create Goggles
- CristelLib
- Cultural Delights
- Cupboard
- DistantFriends
- EDF Remastered
- Elytra Trinket
- End Delight Refabricated
- Entity Texture Features
- Entity Culling
- Expanded Delight
- Expanded Storage
- Extended Gears
- Extra Trinkets
- Fabric API
- Farmers Delight
- Farmers Respite
- Forge Config API Port
- Friendly Fire
- Friends And Foes
- Givemehats
- Highlighter
- Iceberg
- Immersive Aircraft
- Immersive Armors
- Immersive Paintings
- Indium
- Interiors - Create
- JEI
- Just Enough Resources
- KubeJS
- Lavender
- LeavesBeGone
- libjf
- Lithium
- Man of many Planes
- MobCaptains
- Moonlight
- NethersDelight
- Noisium
- Not Enough Animations
- OceansDelight
- owo-lib
- Patchouli
- Player Animation Lib
- Polymorph
- PuzzlesLib
- RadiantGear
- Rhino
- Simply Swords
- Create Slice and Dice
- Slyde
- SmoothChunkLoading
- Sodium
- Spelunkery
- Starterkit
- Create Steam & Rails
- Supplementaries
- SwingThrough
- Tectonic
- Things
- Towns And Towers
- Travelers Backpack
- treeharvester
- Trinkets
- WATUT
- Waystones
- Xerca Paint
- Yungs API
- Yungs Better Desert Temples
- Yungs Better Dungeons
- Yungs Better End Island
- Yungs Better Jungle Temples
- Yungs Better Nether Fortresses
- Yungs Better Ocean Monuments
- Yungs Better Strongholds
- Yungs Better Witch Huts
- Yungs Extras

Clientside has all mods above, and additionally:
- 3d Skin Layers
- Bobby
- ChestTracker
- Distant Horizons
- Figura
- Lamb's Dynamic Lights
- Mod Menu
- OK Boomer

### Additional Context

Clientside log while trying to access train station UI: https://pastebin.com/d5Lytds2

Server log: https://pastebin.com/7RQuvSSC

**Comment by IThundxr** [comment]
some mod is messing up packets, binary search to figure out which one

**Comment by BigMommaBee** [comment]
Thank you, it was caused by a corrupted .jar serverside for the Steam & Rails addon. Reuploaded that mod and trains work correctly now.
