### ISSUE TITLE
[Bug Report] With sit and create installed you can't sit on stairs or simmilar in an assembled train

### ISSUE THREAD

**Issue by NextRaven10** [Fabricators-of-Create/Create#1522]
### Describe the Bug

I First reported this issue to the author of sit but he said that it needs to be fixed on the side of create 
https://github.com/bl4ckscor3/Sit/issues/34

Context:
Sit, as the name suggests, makes it so you can sit on stairs and simmilar. 

Bug Description:
As soon as you assemble a train the functionality of sitting on stairs is lost on the assembled train

### Reproduction Steps

1. Install Create Fabric and Sit
2. Build a train with stairs or slabs on it
3. Sit on them (it works)
4. Assemble the train
5. Try to sit on them (it no longer works)

### Expected Result

I had expected to sit on the stairs in the assembled train.

### Operating System

Client: Windows 10 / Server: Linux

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Additional Context

My idea would be to either make it so sit can function on a train, which probably won't work or to make it so that when sit is installed stairs and simmilar or the blocks defined in the config for sit are added as seats. I mean that they are handeled as if they were seats.

PS: Apologies if they are any grammar mistakes, I'm not a native speaker so I would like constructive feedback/criticism

**Comment by IThundxr** [comment]
this would have to be added on their side
