### ISSUE TITLE
I can't craft industrial iron

### ISSUE THREAD

**Issue by DgekSemut** [Fabricators-of-Create/Create#1524]
### Describe the Bug

I can't craft industrial iron, it turns out cast iron. What am I doing wrong?

### Reproduction Steps

1.I made a press heated the bowl but after using it I got cast iron
2.
3.
...

### Expected Result

 industrial iron

### Operating System

windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
you have another mod adding a recipe that overrides industrial iron's, you should report this to whatever mod you are using that does that.

**Comment by gmirmand** [comment]
I encountered the same issue. There was a conflict between the "Create: Dreams & Desires" mod and "Create Deco." This conflict prevents crafting certain items like the Block of Industrial Iron and other recipes in the Stonecutter. Removing "Create: Dreams & Desires" resolved the issue for my modpack. Can be achieved by deleting the "Create Deco" instead
