### ISSUE TITLE
Intereact with block on trains

### ISSUE THREAD

**Issue by EyelessDepth** [Fabricators-of-Create/Create#1525]
### Describe the Suggestion

while riding on a assembled train you can interact with blocks

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/173305256/9821e9bd-56c6-4747-9d69-2caf51b4948e

**Comment by IThundxr** [comment]
suggestions should go into the discord here https://discord.gg/y2uEGsT9
