### ISSUE TITLE
Datapacks register mixing recipes incorrectly

### ISSUE THREAD

**Issue by DanDragonWolf** [Fabricators-of-Create/Create#1526]
### Describe the Bug

Was working on a compatibility datapack, and I realized that the mod wasn't reading fluid amounts correctly. Create registers 250 as 250mB, but Create Fabric registers it as 3mB

### Reproduction Steps

1. Make a datapack for Create that makes a mixer recipe that uses a liquid
2. Use that same datapack with Create Fabric instead

### Expected Result

When I set the amount to 250, it should register as 250mB

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Additional Context

I can provide images of the same recipe in both forge and fabric. Would like for this to be fixed so there doesn't have to be a separate fabric version for the datapack

**Comment by IThundxr** [comment]
fabric uses droplets not mb, multiply mb by 81 to get the fabric amount

**Comment by DanDragonWolf** [comment]
> fabric uses droplets not mb, multiply mb by 81 to get the fabric amount

The problem with that is that there has to be 2 versions of the datapack if I do that, I don't want to have to make a separate fabric version just because yall are too stubborn to make one small change

**Comment by IThundxr** [comment]
> > fabric uses droplets not mb, multiply mb by 81 to get the fabric amount
> 
> The problem with that is that there has to be 2 versions of the datapack if I do that, I don't want to have to make a separate fabric version just because yall are too stubborn to make one small change

this isn't done by us, you'll need to talk to fabric as their fluid system uses droplets

**Comment by DanDragonWolf** [comment]
Thanks for the info, am asking them if they can either add a way to specify measurements to datapacks or come up with a solution that doesn't require making a separate fabric version of the pack
