### ISSUE TITLE
1.20.1 client crashing - java.lang.IllegalStateException: Already building!

### ISSUE THREAD

**Issue by BlueElixir** [Fabricators-of-Create/Create#1528]
### Describe the Bug

There was one time where we managed to figure out what was causing the crash - a short redstone pulse into a clutch connected to a mechanical piston that extended for a short while and popped back when not receiving rotational force. This was only when joining a server. This time however, the game seems to crash almost randomly.

There were also times (like today) where the game crashed with essentially the same error message (at least, the one in the title).

The crash log I have attached is not of the 1st (mechanical piston), but rather the 2nd (seemed random, though might be related to belts, since they're mentioned in the crash report). This also happened on my other PC.

The world we play on is a server hosted on Ubuntu 22.04 LTS,

### Reproduction Steps

1. (the only example we found to actually crash consistently) Place a mechanical piston.
2. On its front face attach a chassis and a harvester.
3. Glue it all together
4. Make a redstone clock (a 4x4-tick repeater clock should do)
5. Attach the piston to a clutch and connect the redstone clock to the clutch
6. Make sure the piston goes forwards a little bit and then pops back into place over and over again.
7. Log off the server and log back in.

### Expected Result

In this case, rather obviously, the game should not have crashed.

### Crash Report or Log

https://pastebin.com/V9T9gkac

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

The mod list is in the crash report. https://pastebin.com/V9T9gkac

**Comment by IThundxr** [comment]
Caused by "Iris Flywheel Compat"
