### ISSUE TITLE
Machines stoping at an angle

### ISSUE THREAD

**Issue by Mauro0roman** [Fabricators-of-Create/Create#1529]
### Describe the Bug

For an unknown reason the machines are stoping at an angle but only in even coordinates. This sometimes creates issues when trying to put mechanical belts.

### Reproduction Steps

1. Unknown
2.
3.
...

### Expected Result

The contraptions stop at an angle 

### Screenshots and Videos

![2024-06-24_04 23 45](https://github.com/Fabricators-of-Create/Create/assets/88685852/0552d90f-d662-4b34-9cf3-943e539efcdb)

### Crash Report or Log

None

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.18.2

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/88685852/a14c7fc9-e036-4f30-a848-6785aeca74ba)
![image](https://github.com/Fabricators-of-Create/Create/assets/88685852/decfca62-f581-4e51-b6a8-9f6fe56908ff)
![image](https://github.com/Fabricators-of-Create/Create/assets/88685852/ae074f9f-5f92-4a12-b053-f248b63c4f31)

### Additional Context

I'm using the Create Astral mod pack and this bug started to happen at around 220hs. I have a considerably big base with a lot of machines running at 256rpm.

**Comment by TropheusJ** [comment]
what do you mean? can you get a video?

**Comment by IThundxr** [comment]
No response - closing
