### ISSUE TITLE
Right clicking a depot with press crashes the game

### ISSUE THREAD

**Issue by Polarite** [Fabricators-of-Create/Create#153]
### Describe the Bug

when you right click a depot with a press game crashes

### Reproduction Steps

1.get a depot and a press in desicated server
2.right click depot with a press
3.profit
...

### Expected Result

not crash

### Crash Report or Log

https://www.toptal.com/developers/hastebin/epajekebaz.yaml

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

can be found in crash log

### Additional Context

none

**Comment by TropheusJ** [comment]
disable flywheel with `/flywheel backend off`
