### ISSUE TITLE
Create Mod items cause massive fps drops

### ISSUE THREAD

**Issue by maulik-sharma** [Fabricators-of-Create/Create#1530]
### Describe the Bug

I play on a fabric server with a few mods installed including create mod. Just looking at a create mod structure causes massive fps drop. With BSL shaders I normally get about 170-200 fps but when looking at the structure or being in the same chunk as the structure drops the fps to around 30-40. Fps normalize when the player is not looking at the structure and is outside the chunk.

### Reproduction Steps

1. Play with create mod installed
2. Build a create mod structure and notice fps drop when looking at it

### Expected Result

The fps drops shouldn't be this noticeable for very simple structures

### Screenshots and Videos

![vlcsnap-2024-06-26-18h51m45s422](https://github.com/Fabricators-of-Create/Create/assets/88702557/399e5787-d462-4b34-b9cb-7d008f6ef85d)
![vlcsnap-2024-06-26-18h52m00s202](https://github.com/Fabricators-of-Create/Create/assets/88702557/501d071f-ee3c-499b-80b9-5be426a24302)

### Crash Report or Log

https://pastebin.com/ut0LAEdr

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

	Fabric Mods: 
		ambientsounds: AmbientSounds 6.0.1
		archers: Archers (RPG Series) 1.2.2+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
			structure_pool_api: Structure Pool API 1.0+1.20.1
		architectury: Architectury 9.2.14
		azurelibarmor: AzureLib Armor 2.0.3
		bettercombat: Better Combat 1.8.5+1.20.1
		bookshelf: Bookshelf 20.2.13
		cameraoverhaul: Camera Overhaul 1.4.1-fabric-universal
		cave_dweller: Cave Dweller 1.4.0
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.2+1.20.1
			porting_lib_base: Porting Lib Base 2.3.2+1.20.1
				porting_lib_config: Porting Lib Config 2.3.2+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.2+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.2+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.2+1.20.1
				porting_lib_core: Porting Lib Core 2.3.2+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.2+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.2+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.2+1.20.1
				porting_lib_common: Porting Lib Common 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.2+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.2+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.2+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		creativecore: CreativeCore 2.11.30
			net_minecraftforge_eventbus: eventbus 6.0.3
		distanthorizons: Distant Horizons 2.1.2-a
		effortless: Effortless Structure 3.0.0
		enchdesc: EnchantmentDescriptions 17.0.16
		entity_model_features: Entity Model Features 2.0.2
		entity_texture_features: Entity Texture Features 6.1.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fallingtrees: Falling Trees 0.12.1
		geckolib: GeckoLib 4 4.4.4
			com_eliotlash_mclib_mclib: mclib 20
		graveyard: The Graveyard 3.0
		indium: Indium 1.0.32+mc1.20.1
		iris: Iris 1.7.1+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.3.0.7
		lithium: Lithium 0.11.2
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.2
		moremcmeta: MoreMcmeta 1.20.1-4.4.7
			moremcmeta_animation_plugin: MoreMcmeta Animation Plugin 1.20.1-1.0.3
			moremcmeta_gui_plugin: MoreMcmeta GUI Plugin 1.20.1-1.0.1
			moremcmeta_json_parser_plugin: MoreMcmeta JSON Parser Plugin 1.20.1-1.1.1
			moremcmeta_properties_parser_plugin: MoreMcmeta Properties Parser Plugin 1.20.1-1.1.5
			moremcmeta_texture_plugin: MoreMcmeta Texture Plugin 1.20.1-1.0.1
		moremcmeta_emissive_plugin: MoreMcmeta Emissive Textures Plugin 1.20.1-2.0.4
		mr_dungeons_andtaverns: Dungeons and Taverns 3.0.3.f
		mr_ships: Ships 3.0.1
		noisium: Noisium 2.0.3+mc1.20-1.20.1
		nyctophobia: Nyctophobia 1.9
			omega-config: OmegaConfig 1.2.2-1.18.1
		pandalib: PandaLib 0.2.1
		player-animator: Player Animator 1.0.2-rc1+1.20
		presencefootsteps: Presence Footsteps 1.9.4+1.20.1
			kirin: Kirin UI 1.15.6+1.20.1
		ranged_weapon_api: RangedWeaponAPI 1.1.2+1.20.1
		runes: Runes 0.9.13+1.20.1
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		sodium: Sodium 0.5.10+mc1.20.1
		spell_engine: Spell Engine 0.15.3+1.20.1
		spell_power: Spell Power Attribute 0.10.3+1.20.1
		terrablender: TerraBlender 3.0.1.6
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		tlskincape: TLSkinCape 1.32
		tooltipfix: ToolTip Fix 1.1.1-1.20
		trinkets: Trinkets 3.7.2
			cardinal-components-base: Cardinal Components API (base) 5.2.0
			cardinal-components-entity: Cardinal Components API (entities) 5.2.0
		voicechat: Simple Voice Chat 1.20.1-2.5.17
		wizards: Wizards (RPG Series) 1.2.1+1.20.1
		xaerobetterpvp: Better PVP 24.2.0
		xaeroworldmap: Xaero's World Map 1.38.8
	Loaded Shaderpack: BSL_v8.2.09.zip

### Additional Context

SPECS:
RTX 3060 12GB
Intel i9-11900K

**Comment by IThundxr** [comment]
shaders disable flywheel which significantly helps your frames when create blocks are being rendered
