### ISSUE TITLE
Create and MineFortress crash the game

### ISSUE THREAD

**Issue by Asdedo** [Fabricators-of-Create/Create#1531]
### Describe the Bug

Playing the most recent fabric version of create with MineFortress leads to the game crashing when opening the Fortress mode and hovering your mouse over the icons on the side of the screen, not allowing to interact with minefortress at all, but only when hovering the icons

### Reproduction Steps

1. Create a new world with Create and Minefortress installed
2. Go into Fortress mode
3. Hover your mouse over the MineFortress Icons at the sides of the screen
Game crashes then

### Expected Result

I should be able to open and operate the tasks of my colonists from minefortress using these icons, clicking on the icons should open a corresponding interface to order something to my colonists.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/82228309/dc43024c-0d51-4c26-bc1c-5efb7771ef30)

https://github.com/Fabricators-of-Create/Create/assets/82228309/c3490337-932c-40d8-8488-4b5d6e4b381a

### Crash Report or Log

https://pastebin.com/rKRmTaPH

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

MineFortress

### Additional Context

ive tried to do this on a modpack with a friend, everything worked right, i could even give manual orders to workers in MineFortress, but the game crashed client side whenever i hovered over any icon on the border of the screen, as i noticed the error was something with create, i removed every mod except for create and minefortress, the error kept happening.

**Comment by IThundxr** [comment]
I don't think we can do much about this, MineFortress is returning null block positions in hit results

https://github.com/remmintan/minefortress/issues/39
