### ISSUE TITLE
Custom modpack crashes on startup: Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition'

### ISSUE THREAD

**Issue by TRRT004** [Fabricators-of-Create/Create#1532]
### Describe the Bug

The game crashes on startup (see crash report for more details

### Reproduction Steps

Install the modpack (curseforge import file attached below)
[Tweak That Create-1.0.0.zip](https://github.com/user-attachments/files/16059178/Tweak.That.Create-1.0.0.zip)
Launch minecraft

### Expected Result

The game boots up

### Crash Report or Log

https://pastebin.com/CKpYMPmb

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.19.2

### Other Mods

[Balm (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm-fabric)
[Chunky (Fabric) (by pop4959)](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator)
[KubeJS Create (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs-create)
[Disable enderman picking up blocks (by 雨过天清)](https://www.curseforge.com/minecraft/mc-mods/disable-enderman-picking-up-blocks)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[Roughly Enough Loot Tables (by GrigLog)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-loot-tables)
[More Mob Variants (by nyuppo)](https://www.curseforge.com/minecraft/mc-mods/more-mob-variants)
[LazyDFU (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/lazydfu)
[Recipe Essentials[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/recipe-essentials-forge-fabric)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Konkrete [Fabric] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete-fabric)
[KubeJS (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Client Crafting (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/client-crafting)
[Better Statistics Screen (by TheCSDev)](https://www.curseforge.com/minecraft/mc-mods/better-stats)
[Consistency+ (by Cart3r1234)](https://www.curseforge.com/minecraft/mc-mods/consistencyplus)
[Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
[Create: Extended Cogwheels Fabric (by Rabbitminers)](https://www.curseforge.com/minecraft/mc-mods/create-extended-cogwheels-fabric)
[CleanCut (by Rongmario)](https://www.curseforge.com/minecraft/mc-mods/cleancut)
[Skin Layers 3D (Fabric/Forge) (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
[Client Tweaks (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/client-tweaks-fabric)
[Continuity (by Pepper_Bell)](https://www.curseforge.com/minecraft/mc-mods/continuity)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[BadOptimizations (by thosea)](https://www.curseforge.com/minecraft/mc-mods/badoptimizations)
[Roughly Enough Items Fabric/Forge/NeoForge (REI) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
[Light Overlay (Rift/Forge/Fabric) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/light-overlay)
[[Deprecated] Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[Better Compatibility Checker (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker)
[MoreJS (by Lytho)](https://www.curseforge.com/minecraft/mc-mods/morejs)
[Distant Horizons: A Level of Detail mod (by James_Seibel)](https://www.curseforge.com/minecraft/mc-mods/distant-horizons)
[BetterEnd (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betterend)
[JourneyMap Integration (by frankV)](https://www.curseforge.com/minecraft/mc-mods/journeymap-integration)
[Sodium (by JellySquid)](https://www.curseforge.com/minecraft/mc-mods/sodium)
[Create Fabric (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
[Boosted Brightness (by aloivmada)](https://www.curseforge.com/minecraft/mc-mods/boosted-brightness)
[Smooth Boot (Fabric) (by UltimateBoomer)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot)
[MaLiLib (by masady)](https://www.curseforge.com/minecraft/mc-mods/malilib)
[Create Decoration Casing (by TheLynkYT)](https://www.curseforge.com/minecraft/mc-mods/create-decoration-casing)
[Connected Glass (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/connected-glass)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Spice of Fabric (Fabric) (by Siphalor)](https://www.curseforge.com/minecraft/mc-mods/spice-of-fabric)
[Language Reload (by Jerozgen)](https://www.curseforge.com/minecraft/mc-mods/language-reload)
[Eldritch Mobs (by CyborgPigeon)](https://www.curseforge.com/minecraft/mc-mods/eldritch-mobs)
[Starlight (Fabric) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight)
[Farmer's Knives [Fabric] (by ianm1647)](https://www.curseforge.com/minecraft/mc-mods/farmers-knives)
[Bad Wither No Cookie - Reloaded (by Kreezxil)](https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded)
[Trash Cans (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/trash-cans)
[Litematica (by masady)](https://www.curseforge.com/minecraft/mc-mods/litematica)
[Extended Drawers (by MattiDragon)](https://www.curseforge.com/minecraft/mc-mods/extended-drawers)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
[Boat Break Fix [Neo/Forge/Fabric/Quilt] (by ElocinDev)](https://www.curseforge.com/minecraft/mc-mods/boat-break-fix)
[Model Gap Fix (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/model-gap-fix)
[Forge Config API Port (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[Jade Addons (Fabric) (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade-addons-fabric)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[ImmediatelyFast (by RaphiMC)](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast)
[Create Deco Fabric (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco-fabric)
[Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Ingredient Extension API (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/ingredient-extension-api)
[BCLib (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/bclib)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Necronomicon API (by ElocinDev)](https://www.curseforge.com/minecraft/mc-mods/necronomicon)
[Sodium Extra (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/sodium-extra)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[BetterNether (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betternether)
[Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Traveler's Backpack [Fabric] (by Tiviacz1337)](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric)
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Create: Steam 'n' Rails (by mattentosh)](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
[LambDynamicLights (by LambdAurora)](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights)
[Visual Workbench [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[OfflineSkins (Fabric) (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/offlineskins-fabric)
[Server Country Flags (by khajiitos)](https://www.curseforge.com/minecraft/mc-mods/server-country-flags)
[Reese's Sodium Options (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)
[Zoomify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/zoomify)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[No Chat Reports (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports)
[Rhino (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/rhino)
[[FABRIC/QUILT] Disable Custom Worlds Advice (by Nara)](https://www.curseforge.com/minecraft/mc-mods/fabric-disable-custom-worlds-advice)
[Faux Custom Entity Data (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/faux-custom-entity-data)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Fast Paintings (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/fast-paintings)
[Naturalist (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/naturalist)
[CreateFabric&REIBugFix (by TexTrue)](https://www.curseforge.com/minecraft/mc-mods/createfabricreibugfix)
[Trade Cycling (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/trade-cycling)
[Suggestion Tweaker (by VelizarP)](https://www.curseforge.com/minecraft/mc-mods/suggestion-tweaker)
[Crafting Tweaks (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks-fabric)
[Roughly Enough Professions (REP) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-professions-rep)
[Get It Together, Drops! (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Server Pinger Fixer (by JustAlittleWolf)](https://www.curseforge.com/minecraft/mc-mods/serverpingerfixer)
[FindMe (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/findme)
[Roughly Enough Resources (by theorbagain)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-resources)
[Roughly Searchable (by InEqualMeasure)](https://www.curseforge.com/minecraft/mc-mods/roughly-searchable)
[Debugify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/debugify)
[Lithium (Fabric) (by JellySquid)](https://www.curseforge.com/minecraft/mc-mods/lithium)
[NetherPortalFix (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/netherportalfix-fabric)
[BetterF3 (by cominixo)](https://www.curseforge.com/minecraft/mc-mods/betterf3)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[CraftTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
[Colorful Hearts (by Terrails)](https://www.curseforge.com/minecraft/mc-mods/colorful-hearts)
[You're in Grave Danger (by b1n_ry)](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Better chunk loading[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-chunk-loading-forge-fabric)
[YetAnotherConfigLib (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/yacl)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Satin API (by PyrofabTheModsmith)](https://www.curseforge.com/minecraft/mc-mods/satin-api)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Roughly Enough Trades (by GrigLog)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-trades)
[Colorful Azaleas (by kekie6)](https://www.curseforge.com/minecraft/mc-mods/colorfulazaleas)
[Fusion (Connected Textures) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
[fix GPU memory leak[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak)
[CIT Resewn (by SHsuperCM)](https://www.curseforge.com/minecraft/mc-mods/cit-resewn)
[Leaf Decay (by Draylar1)](https://www.curseforge.com/minecraft/mc-mods/leaf-decay)
[Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[Creeper Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
[Cardinal Components API (by UpcraftLP)](https://www.curseforge.com/minecraft/mc-mods/cardinal-components-api)

**Comment by IThundxr** [comment]
report to createaddition
