### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by ApexPredatorTV** [Fabricators-of-Create/Create#1533]
### Describe the Bug

My custom modpack is crashing with create installed, however I can't find the problem in the logs. I have checked whether there are incompatibilities, but could not find any.

### Reproduction Steps

1.
2.
3.
...

### Expected Result

game starting

### Crash Report or Log

https://gist.github.com/ApexPredatorTV/1a300f823c3d5c5ea28896aa77d52a26

### Operating System

Win 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

They are in the log provided

**Comment by IThundxr** [comment]
looks like caveore but it's a bit hard to tell without a crash log

**Comment by ApexPredatorTV** [comment]
Hey! thanks for that insanely quick response, though that was not the problem. Caveore even shows that error when loaded on its own XD

**Comment by ApexPredatorTV** [comment]
Here a up to date log and report
https://gist.github.com/ApexPredatorTV/521058aafc1df849b12746168ec5f9fa

**Comment by IThundxr** [comment]
remove dash loader

**Comment by ApexPredatorTV** [comment]
Ok mister wizard. I am schooled in the sense of that i should be able to read why it crashes, yet i cant. can you give me a very short rundown on how you identified the problem?

**Comment by IThundxr** [comment]
porting libs been incompatible with dashloader for quite a while now & dash loader is abandoned, i knew about the issue already so seeing dashloader's mixin failing was enough for me to know that it's caused by dashloader

**Comment by ApexPredatorTV** [comment]
alr alr ty ty <3
