### ISSUE TITLE
fluid error on latest patch Create 1.20.1 v0.5.1.f Patch 1

### ISSUE THREAD

**Issue by PokeLusion** [Fabricators-of-Create/Create#1534]
### Describe the Bug

https://pastebin.com/7EtB6s74

### Reproduction Steps

1. pump fluid
2. once fluid makes contact with liquid, the server crashes

### Expected Result

causes a null response to the fluid being pumped

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
createdieselgenerators is returning null data, report to them
