### ISSUE TITLE
Client lags too much while standing in dense mechanisms area

### ISSUE THREAD

**Issue by ghost** [Fabricators-of-Create/Create#1535]
### Describe the Bug

I have a base on my server with not so much create's mechanisms.

When I enter the center of my base - the framerate is dropping down to 50 FPS or below. So, my normal framerate, when I don't stand in chunks with mechanisms - is above 370 FPS.

Also, it drops down even when I don't look at the mechanisms. So, they must not render, are they?

My Desktop setup is not so bad, even if it looks like so:

- 32 GB DDR3 RAM
- GTX 1070 8GB
- Xeon E5-2650v2

So, why it lags so much? And, will you fix that?

Also, there is a link to the sparkclient profiler's log - https://spark.lucko.me/BGMb8I2Jxi (I started the profiler while standing at the center of my base)

### Reproduction Steps

1. start playing with 3 friends
2. enter the early-mid-game with Create
3. There are too much of lag when standing in area with mechanisms, even if they're out of my sight

### Expected Result

I expected not THAT much lag from Create

### Screenshots and Videos

![2024-07-06_06 22 41](https://github.com/Fabricators-of-Create/Create/assets/98831090/1bf5b858-77fb-43c4-93a6-3427b8a435e5)
![2024-07-06_06 25 47](https://github.com/Fabricators-of-Create/Create/assets/98831090/0c63607c-8c21-4e15-b18e-7f1c7e7ed9ee)
![2024-07-06_06 25 56](https://github.com/Fabricators-of-Create/Create/assets/98831090/d37f6fe1-3009-4e1c-ad20-43b7ced85442)
![2024-07-06_06 26 14](https://github.com/Fabricators-of-Create/Create/assets/98831090/775b8829-f1bc-43e2-bb20-5f03eee3fb63)
![2024-07-06_06 26 23](https://github.com/Fabricators-of-Create/Create/assets/98831090/48fede0f-8ae7-4ca7-9bdc-d97348939206)
![2024-07-06_06 26 34](https://github.com/Fabricators-of-Create/Create/assets/98831090/83240590-e50b-4173-9349-1db2cbedfd52)
![2024-07-06_06 26 42](https://github.com/Fabricators-of-Create/Create/assets/98831090/1787d56a-8ca1-4958-b416-9840374775d6)
![2024-07-06_06 26 48](https://github.com/Fabricators-of-Create/Create/assets/98831090/36dc2e70-e9b9-4e16-ae5e-c38eeabef104)

### Operating System

Windows 10

### Mod Version

0.5.1f (build 1415)

### Minecraft Version

1.18.2

### Other Mods

See at sparkclient's log link - https://spark.lucko.me/BGMb8I2Jxi

**Comment by IThundxr** [comment]
try /flywheel backend instancing and /flywheel backend batching and use whatever gives you better perf

**Comment by ghost** [comment]
Almost no difference, except if I type `/flywhell backend off` - in that case, it's just worse, because it's slideshow (less than 8 FPS)

**Comment by ghost** [comment]
Also, ask yourself:
```
Would an object need to render, if it's not in my sight?
```
Because there are not so much of Create's BlockEntities in that area. We're just newbies to this mod, and we've got only the iron farm, three elevators, one tree farm with automatic charcoal production, that supplies the two-pistoned blaze boiler, one automatic gate, and one big miner (that wagon in the mineshaft that painted in style of ambulance).

And just imagine, what would happen if some group of professional Create gamers will build a really good base? Their framerate will just devastate below zero!

Fix it, please, because I don't want my future players to suffer from client lag.

**Comment by ghost** [comment]
Also, I have allocated 8 gigs of RAM right now (it was 2 gigs before), but nothing changes - framerate is the same

**Comment by IThundxr** [comment]
> Also, ask yourself:
> 
> ```
> Would an object need to render, if it's not in my sight?
> ```
> 
> Because there are not so much of Create's BlockEntities in that area. We're just newbies to this mod, and we've got only the iron farm, three elevators, one tree farm with automatic charcoal production, that supplies the two-pistoned blaze boiler, one automatic gate, and one big miner (that wagon in the mineshaft that painted in style of ambulance).
> 
> And just imagine, what would happen if some group of professional Create gamers will build a really good base? Their framerate will just devastate below zero!
> 
> Fix it, please, because I don't want my future players to suffer from client lag.

i'm not really sure what you want me to say, the first thing your explaining is culling and that already happens.

try updating your graphics drivers and let me know if that makes a difference and also attach latest.log

**Comment by bangetto** [comment]
there's culling? I never noticed it, my frames just always drop whenever I'm near mechanisms (even when looking in the other direction)

**Comment by IThundxr** [comment]
Will be fixed by 0.5.1.h for fabric
