### ISSUE TITLE
 Mixin transformation of net.minecraft.world.level.BlockGetter failed

### ISSUE THREAD

**Issue by jimgreer** [Fabricators-of-Create/Create#1536]
### Describe the Bug

On my initial checkout of the mc1.20.1 branch (84f54d7), I have a failure with the runClient task. Full logs are in the linked pastebin

The mc1.18 branch works fine

`[15:27:16] [main/WARN] (FabricLoader/Mixin) Error loading class: io/vram/frex/base/renderer/context/render/EntityBlockRenderContext (java.lang.ClassNotFoundException: io/vram/frex/base/renderer/context/render/EntityBlockRenderContext)
[15:27:16] [main/WARN] (FabricLoader/Mixin) @Mixin target io.vram.frex.base.renderer.context.render.EntityBlockRenderContext was not found porting_lib_base.mixins.json:client.frex.EntityBlockRenderContextMixin from mod porting_lib_base
[15:27:17] [main/WARN] (FabricLoader/Mixin) Error loading class: mezz/jei/library/load/PluginCaller (java.lang.ClassNotFoundException: mezz/jei/library/load/PluginCaller)
[15:27:18] [main/ERROR] (FabricLoader) Minecraft has crashed!
 net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.world.level.BlockGetter failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.7.jar:?]`

### Reproduction Steps

1. Initial checkout
2. runClient
3.
...

### Expected Result

Expected Minecraft to run

### Crash Report or Log

https://gist.github.com/jimgreer/4cfbfd9bfe16eae9a3d1108c49cd8ba6

### Operating System

macOS Sonoma 14.5

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
Seems like something is pulling a different version of mixin extras, could you check runs/logs/latest.log and send the modlist it outputs at the top of the file, it should show what other mods are JiJing

**Comment by jimgreer** [comment]
Thanks IThundxr - Here's that list

https://gist.github.com/jimgreer/6da03b91fff7aab7ff0713747c4f91f2

**Comment by IThundxr** [comment]
could you try using applying this patch https://hst.sh/koyesuhumi.yaml

**Comment by IThundxr** [comment]
Should be fixed by https://github.com/Fabricators-of-Create/Create/commit/0d6d4ff53b7fc85f888bc104488f0fff5cc62261 could you try pulling in the latest commit and trying to run runClient again? thanks

**Comment by jimgreer** [comment]
Thanks! This one is fixed

But I'm getting a crash on startup now. I'll open a new issue

**Comment by jimgreer** [comment]
Never mind about the other crash. Deleting my build, run and .gradle directories fixed it (though a normal clean build didn't)
