### ISSUE TITLE
Elevator

### ISSUE THREAD

**Issue by Lorenzosuper** [Fabricators-of-Create/Create#1537]
### Describe the Bug

I built the elevator but when I un-assemble it, it remained in my world

### Reproduction Steps

1.I Build the elevator
2.i un-assemble the elevator
3.THE ELEVATOR STILL IN MY WORLD

### Expected Result

O_O

### Operating System

mac OS catalina

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
Unable to reproduce, if you are able to consistently reproduce this with just create + fabric api feel free to open a new issue.
