### ISSUE TITLE
Only for the create mod devs!!!

### ISSUE THREAD

**Issue by leakclient** [Fabricators-of-Create/Create#1539]
### Describe the Bug

the fluids on create fabric are a bit bugged, so thats why you put it on "beta". Well, if you change your recipes on type "filling", then this Issue would be solved.

### Reproduction Steps

1. on the source code, go to "sourcecodefolder\data\create\recipes\filling"
2. click on any type of recipe (like blaze_cake.json)
3. edit the _**"amount":**_ to 25000 (250 mb) = 100000 (1 bucket/1000 mb)

### Expected Result

everything should be the same amount as in the create mod (forge).

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by IThundxr** [comment]
not a bug, fabric (the loader & api itself) uses droplets, the conversion ratio is the following 1mb = 81 droplets, so all recipes must use droplets in them
