### ISSUE TITLE
Remaining issues with REI recipes

### ISSUE THREAD

**Issue by Abalieno** [Fabricators-of-Create/Create#1541]
### Describe the Bug

Works fine with EMI, testing on 1.19.

First problem is wrong quantities for fluids in mixer recipes. An example is create:tea default recipe:
27000 water & milk, the output is 54000 tea

Within REI this is shown an 333mB (x81) for inputs, but then again the same for the output. Despite the icon itself shows a greater amount, the tooltip is still wrong.

The second problem is that fluids used for filling aren't indexed. Example is honeyed apple. If you press "r" on the apple, you see the correct filling recipe. But if you press "u" on the honey, to check its uses, the filling recipes disappear.

### Reproduction Steps

As above

### Expected Result

to work

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
see #1616
