### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by OneZmodrinth** [Fabricators-of-Create/Create#1543]
### Describe the Bug

Missing Textures for many Blocks

### Reproduction Steps

1.Download Create Fabric https://modrinth.com/mod/create-fabric/version/0.5.1-f-build.1417+mc1.20.1 and install it
2./
3./
...

### Expected Result

Missing Textures for Blaze Burner and more

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Automobility
Create Fabric
Fabric API
Geckolib
Immersive Aircraft
Immersive Portals
Iris
Just Enough Items
JustOutdoorStuff
Laserbridges
Macaws Bridges,Doors,furniture,fences,lights,paths,roofs,trapdoors and windows
Modmenu
Immersive Portal Gun
Smallships
Sodium
Worldedit
Xaeros Minimap and Worldmap

**Comment by IThundxr** [comment]
if you use sodium you also need to install indium for mods using the fabric rendering api to work properly
