### ISSUE TITLE
some kind of launch crash with GUI

### ISSUE THREAD

**Issue by netcore10** [Fabricators-of-Create/Create#1547]
### Describe the Bug

launch crash ```java.lang.NullPointerException: Cannot invoke "net.minecraft.client.render.model.BakedModel.getOverrides()" because "$$6" is null
```

### Reproduction Steps

I'm not too sure

### Expected Result

launching

### Screenshots and Videos

_No response_

### Crash Report or Log

https://mclo.gs/7JKXOff

### Operating System

windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

i launched with create only but somethings off.

### Additional Context

_No response_

**Comment by IThundxr** [comment]
You'll need to find which mod is conflicting with create here, do the following

Try a binary search:

The binary search is a way of finding a faulty thing amongst a lot of other things, without having to remove the things one-by-one. This is useful for finding a broken mod among hundreds of mods, without having to spend time testing the mods one-by-one.

The procedure is simple:

1. Remove half of the existing things, and put them aside.
2. Run the program / game.
3. Does the issue still exist?
   If YES: Repeat from step 1 with the current things.
   IF NO: Swap out the current things with the ones set aside, and repeat from step 1.
4. Repeat this process until the problematic thing/s have been found.

**Comment by TropheusJ** [comment]
it's elytra trims, error seems unrelated to create, create just triggers the crash earliest
