### ISSUE TITLE
I cant see a lot of the blocks

### ISSUE THREAD

**Issue by INeedHelp-svg** [Fabricators-of-Create/Create#1548]
### Describe the Bug

I'll place down a block (water wheel, etc.) and i cant see the block?

### Reproduction Steps

1.
2.
3.
...

### Expected Result

I expected to see the blocks

### Screenshots and Videos

![image_2024-07-22_010008311](https://github.com/user-attachments/assets/258cea70-89bb-4348-b5fb-0034f2f0c300)

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Additional Context

It seems to be mainly wheels

**Comment by IThundxr** [comment]
if you are using sodium add indium, if that doesn't work try updating puzzleslib

**Comment by denisJaved** [comment]
Check are you using any flywheel incopatible mods like iris

**Comment by IThundxr** [comment]
iris is not incompatible with flywheel. Flywheel just disables its instancing engine when shaders are being used and defaults to normal rendering.
