### ISSUE TITLE
Sprinting/Swimming Disabled In Build #415

### ISSUE THREAD

**Issue by digitaltrucker** [Fabricators-of-Create/Create#155]
### Describe the Bug

As the title states, the player can no longer swim or sprint in build 415.  Reverting to build 413 restores the abilities.  I have not remapped the sprint key, it's still the default L-CTRL.

### Reproduction Steps

1.  Update to build 415
2.  Try to sprint or swim

### Expected Result

Swim or sprint when using the sprint key.

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
oops! That's why we changed that keybind.

**Comment by digitaltrucker** [comment]
I had a feeling...hehehe.  I would like to take a moment though to congratulate you and the rest of the dev team on this mod.  It's working spectacularly well.
