### ISSUE TITLE
Duplication bug mechanical arm, press and belt

### ISSUE THREAD

**Issue by spazzlad** [Fabricators-of-Create/Create#1550]
### Describe the Bug

Duplication bug using mechanical arm, mechanical press and conveyor belt at full speed (work with obsidian sheet) 
version : 1.18.2
multiplayer : yes
modpack : create Astral (fabric 2.0.5b)

### Reproduction Steps

1. place a track of conveyor belt at full speed (mine is 5 block long)
2. set a mechanical press in the midle of the belt
3. set a mechanical arm taking item from the end to the start of the belt
4. fill the belt with unprocessed obsidian sheet 
5. take the one at the end of the belt 

### Expected Result

not duplicated and sequencial crafting cycling fine 

### Screenshots and Videos

https://imgur.com/a/6oRLO3m

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.18.2

### Other Mods

[Datapack Portals (by Kyrptonaught)](https://www.curseforge.com/minecraft/mc-mods/datapack-portals)
[Idwtialsimmoedm (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/idwtialsimmoedm)
[libIPN (by mirinimi)](https://www.curseforge.com/minecraft/mc-mods/libipn)
[CC:C Bridge (by Sammy_echt)](https://www.curseforge.com/minecraft/mc-mods/cccbridge)
[ToolTipFix (by Kyrptonaught)](https://www.curseforge.com/minecraft/mc-mods/tooltipfix)
[Suggestion Tweaker (by VelizarP)](https://www.curseforge.com/minecraft/mc-mods/suggestion-tweaker)
[Ears (+ Snouts/Muzzles, Tails, Horns, Wings, and More) (by unascribed)](https://www.curseforge.com/minecraft/mc-mods/ears)
[Mystical Oak Tree (by plantspookable)](https://www.curseforge.com/minecraft/mc-mods/mystical-oak-tree)
[Cardinal Components API (by UpcraftLP)](https://www.curseforge.com/minecraft/mc-mods/cardinal-components-api)
[Numeral Ping (by TheKodeToad)](https://www.curseforge.com/minecraft/mc-mods/numeral-ping)
[Cooking for Blockheads (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads-fabric)
[Phonos (by FoundationGames)](https://www.curseforge.com/minecraft/mc-mods/phonos)
[Puzzles Lib [Legacy Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib-fabric)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Global Packs (by JTK222)](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack)
[[ETF] Entity Texture Features - [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric)
[Astral Vinery (by Erdragh)](https://www.curseforge.com/minecraft/mc-mods/astral-vinery)
[Falling Leaves (Fabric) (by RandomMcSomethin)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric)
[Forge Config API Port (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[Iris & Oculus Flywheel Compat (by leon_mout)](https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[CompleteConfig (by Lortseam_)](https://www.curseforge.com/minecraft/mc-mods/completeconfig)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[KubeJS (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
[Projectile Damage Attribute [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/projectile-damage-attribute)
[[FABRIC/QUILT] Disable Custom Worlds Advice (by Nara)](https://www.curseforge.com/minecraft/mc-mods/fabric-disable-custom-worlds-advice)
[Mobvotes Sniffer (by YourDailyModderx)](https://www.curseforge.com/minecraft/mc-mods/mobvotes-sniffer)
[Ambient Environment (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/ambient-environment)
[Auto Config Updated API (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/auto-config-updated-api)
[Audio Extension for FancyMenu v2 [Fabric] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/audio-extension-for-fancymenu-fabric)
[Reinforced Chests (by atonkish)](https://www.curseforge.com/minecraft/mc-mods/reinforced-chests)
[Custom Machinery (by frinn38)](https://www.curseforge.com/minecraft/mc-mods/custom-machinery)
[WI Zoom (by alexander9892)](https://www.curseforge.com/minecraft/mc-mods/wi-zoom)
[Trinkets (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/trinkets)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[Per Aspera (by Erdragh)](https://www.curseforge.com/minecraft/mc-mods/per-aspera)
[Explorer's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/explorers-compass)
[KubeJS Create (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs-create)
[Iris Shaders (by coderbot)](https://www.curseforge.com/minecraft/mc-mods/irisshaders)
[Disable Villager trades (by todd86769)](https://www.curseforge.com/minecraft/mc-mods/disable-villager-trades)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Lootr (Fabric) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr-fabric)
[Mod Menu (by Prospector)](https://www.curseforge.com/minecraft/mc-mods/modmenu)
[Ping Wheel (by LukenSkyne)](https://www.curseforge.com/minecraft/mc-mods/ping-wheel)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[Chassis (by Libra)](https://www.curseforge.com/minecraft/mc-mods/chassis)
[Ad Astra (by AlexNijjar)](https://www.curseforge.com/minecraft/mc-mods/ad-astra)
[You're in Grave Danger (by b1n_ry)](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)
[Inventory Profiles Next (by mirinimi)](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Create Fabric (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[JourneyMap Integration (by frankV)](https://www.curseforge.com/minecraft/mc-mods/journeymap-integration)
[CIT Resewn (by SHsuperCM)](https://www.curseforge.com/minecraft/mc-mods/cit-resewn)
[Chunky (Fabric) (by pop4959)](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Load My Resources [Fabric] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/load-my-resources-fabric)
[Konkrete [Fabric] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete-fabric)
['Dustrial Decor [Fabric] (by slomax907)](https://www.curseforge.com/minecraft/mc-mods/dustrial-decor-fabric)
[Rhino (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/rhino)
[Drink Beer Unofficial: Clockwerk Edition (by ClockwerkKaiser)](https://www.curseforge.com/minecraft/mc-mods/drink-beer-unofficial-clockwerk-edition)
[Subterrestrial (by AlexNijjar)](https://www.curseforge.com/minecraft/mc-mods/subterrestrial)
[FTB Quests (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-quests-fabric)
[Searchlight (& Wall Lights) (Fabric) (by Lizard_OfOz)](https://www.curseforge.com/minecraft/mc-mods/searchlight)
[Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)
[FTB Library (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric)
[Balm (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm-fabric)
[Continuity (by Pepper_Bell)](https://www.curseforge.com/minecraft/mc-mods/continuity)
[Neruina - Ticking Entity Fixer (by bawnorton)](https://www.curseforge.com/minecraft/mc-mods/neruina)
[Puzzle (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/puzzle)
[Another Furniture (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/another-furniture)
[Create: Extended Flywheels Fabric (by Rabbitminers)](https://www.curseforge.com/minecraft/mc-mods/create-extended-flywheels-fabric)
[Extractinator (by AlexNijjar)](https://www.curseforge.com/minecraft/mc-mods/extractinator)
[Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
[Environmental Creepers (by masady)](https://www.curseforge.com/minecraft/mc-mods/environmental-creepers)
[Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
[Debugify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/debugify)
[Observable (by tasgon)](https://www.curseforge.com/minecraft/mc-mods/observable)
[Polaroid Camera (by CyborgPigeon)](https://www.curseforge.com/minecraft/mc-mods/polaroid-camera)
[LazyDFU (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/lazydfu)
[[Let's Do] Vinery (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-vinery)
[Show Me What You Got (by Apace)](https://www.curseforge.com/minecraft/mc-mods/show-me-what-you-got)
[ImmediatelyFast (by RaphiMC)](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast)
[Adopt a Floppa (by ethanicussss)](https://www.curseforge.com/minecraft/mc-mods/adopt-a-floppa)
[FTB Backups 2 (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-backups-2)
[Applied Energistics 2 (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[Packed Inventory (by Kir_Antipov)](https://www.curseforge.com/minecraft/mc-mods/packed-inventory)
[Let Me Despawn (by frikinjay)](https://www.curseforge.com/minecraft/mc-mods/let-me-despawn)
[Reese's Sodium Options (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)
[ServerCore (by Wesley8081)](https://www.curseforge.com/minecraft/mc-mods/servercore)
[Quarry Reborn (by TED_inc)](https://www.curseforge.com/minecraft/mc-mods/quarry-reborn)
[Jade Addons (Fabric) (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade-addons-fabric)
[WorldEdit (by sk89q)](https://www.curseforge.com/minecraft/mc-mods/worldedit)
[Hephaestus Fabric (by thatguynamedalpha)](https://www.curseforge.com/minecraft/mc-mods/hephaestus-fabric)
[Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Dave's Building Extended Fabric (by Rabbitminers)](https://www.curseforge.com/minecraft/mc-mods/daves-building-extended-fabric)
[Create Sifting Refabricated (by Monster__zero)](https://www.curseforge.com/minecraft/mc-mods/create-sifting-refabricated)
[Tech Reborn (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/techreborn)
[Krypton (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/krypton)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[[Deprecated] Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[MC Dungeons Weapons (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcdw)
[Harvest with ease (by CrystalSpider)](https://www.curseforge.com/minecraft/mc-mods/harvest-with-ease)
[Automobility (by FoundationGames)](https://www.curseforge.com/minecraft/mc-mods/automobility)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Quests Additions (Fabric) (by NaturaSpell)](https://www.curseforge.com/minecraft/mc-mods/quests-additions-fabric)
[Drippy Loading Screen [Fabric] [MOVED TO NEW PROJECT] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/drippy-loading-screen-fabric)
[Lithium (Fabric) (by JellySquid)](https://www.curseforge.com/minecraft/mc-mods/lithium)
[Smooth Boot (Fabric) (by UltimateBoomer)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot)
[FTB Chunks (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-fabric)
[Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
[Astral Additions (for Create: Astral) (by ethanicussss)](https://www.curseforge.com/minecraft/mc-mods/astral-additions-for-create-astral)
[Catwalks Inc. (by Reoseah)](https://www.curseforge.com/minecraft/mc-mods/catwalks-inc)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[XL Packets Fabric (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric)
[Limited Chunkloading - Chunk cleanup[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/limited-chunkloading)
[Sodium Extra (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/sodium-extra)
[Gear Reborn (by loleq21)](https://www.curseforge.com/minecraft/mc-mods/gearreborn)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[FTB Teams (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric)
[Polymorph (Fabric 1.16.1 - 1.19.2) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric)
[Auudio [Fabric] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/auudio-fabric)
[Fast Furnace for Fabric (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/fast-furnace-for-fabric)
[Campanion (by wyn_price)](https://www.curseforge.com/minecraft/mc-mods/campanion)
[Naturalist (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/naturalist)
[Carpet (by gnembon)](https://www.curseforge.com/minecraft/mc-mods/carpet)
[Roughly Enough Items Fabric/Forge/NeoForge (REI) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
[CC: Restitched (by merithtk)](https://www.curseforge.com/minecraft/mc-mods/cc-restitched)
[Starlight (Fabric) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight)
[FerriteCore (Fabric) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Packages (by quat)](https://www.curseforge.com/minecraft/mc-mods/packages)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Cammie's Wearable Backpacks (by Cammie)](https://www.curseforge.com/minecraft/mc-mods/cammies-wearable-backpacks)
[MixinTrace (by comp500)](https://www.curseforge.com/minecraft/mc-mods/mixintrace)
[Immersive Aircraft [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[Iceberg [Fabric] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg-fabric)
[Cull Less Leaves (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/cull-less-leaves)
[Passive Piglins (by ethanicussss)](https://www.curseforge.com/minecraft/mc-mods/passive-piglins)
[CTM Refabricated (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/ctm-refabricated)
[CobbleGen [Fabric/Forge] (by ZiRO2264)](https://www.curseforge.com/minecraft/mc-mods/cobblegen)
[Create Deco Fabric (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco-fabric)
[Item Filters (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/item-filters)
[Compressor (by Libra)](https://www.curseforge.com/minecraft/mc-mods/compressor)
[Server Tick (by sammko_)](https://www.curseforge.com/minecraft/mc-mods/servertick)
[FancyMenu [Fabric] [MOVED TO NEW PROJECT] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/fancymenu-fabric)
[Companion 🐕 (Fabric) (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/companion-fabric)

**Comment by spazzlad** [comment]
can provide save if needed

**Comment by IThundxr** [comment]
0.5.0i is a very old version, try reproducing this on 0.5.1f

**Comment by spazzlad** [comment]
![image_2024-07-23_012623728](https://github.com/user-attachments/assets/1794d0e6-369d-4efd-a4f0-2345c40d8b29)
i tried in a world with only create in solo with the latest version and it seem that the bug is not occuring
