### ISSUE TITLE
Game crashes on world generation [playing with multiple other mods, including create addons]

### ISSUE THREAD

**Issue by TheLemon27** [Fabricators-of-Create/Create#1551]
### Describe the Bug

After getting through world settings and pressing the create world button, the game gets to the percentage screen, but crashes before it gets past 0%.

### Reproduction Steps

1. Open Minecraft with the mods.
2. Create a new world. 
3. Game crash.

### Expected Result

The world to generate and not crash.

### Crash Report or Log

https://gist.github.com/TheLemon27/13cba78427449937673b9ae13d15feef (compact error message below)

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

(note: all of these mod names were pulled straight from what they were called in the mod menu. if you need the version of any of these mods, feel free to ask! i didnt put them here because that would be a ton of extra work and it's already past when I should be sleeping anyway.)

2x Better Intelligence
Additional Entity Attributes
Admiral
Aliven't Messenger
Amethyst Gravity: Reattracted
Applied Energistics 2
Architectury
AudioPlayer
Automobility
Bad Packets
Baubly
Better Recipe Book
Blank Discs
Botarium
Chat Heads
Create Dragon Lib
Create Enchantment Industry
Create Utilities
Create: Big Contraptions
Create: Estrogen
Create: Interactive
dark-matter
Debugify
Ears
EldritchMobs
EMI
EMI Enchanting
EMI Loot
EMI Trades
Energy
EnhancedBookWriting
fakerlib
Flywheel
From The Fog
Gravity Changer (qouteall fork)
Happiness is a Warm Gun
Immersive Paintings
Indium
Infinite Dimensions 1.20.1
Infinity Buttons
JsonEM
Jukeboxfix
Just Player Heads
LambDynamicLights
Lithium
Manningham Mills
MazeRunner
Mod Menu
Music Control
Pal
Phillip's Ruins
polymer-bundled
Polymorph
Potion Sauce
Pretty in Pink
Projectile Damage Attribute
Recipe Book Is Pain
Resourceful Lib
Server Translations API
Show Me Your Skin!
Simple Captcha
Simple Voice Chat
SimpleRadio
SmartBrainLib
SmartNameTags
Sodium
Sound Physics Remastered
Stoneworks
Trinkets
Valkyrien Skies 2
Voice Chat Interaction
When Dungeons Arise
wthit
XP Storage
XP Storage - Trinkets
YUNG's API
YUNG's Better Dungeons
YUNG's Better Jungle Temples
YUNG's Better Mineshafts
YUNG's Better Nether Fortresses
YUNG's Better Strongholds
YUNG's Better Witch Huts
YUNG's Bridges
Zenith
Zenith Attributes

### Additional Context

Compact error message here (the one that shows up in the launcher):
```
The game crashed whilst exception in server tick loop
Error: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.simibubi.create.content.trains.entity.Train failed
```

**Comment by TropheusJ** [comment]
caused by interactive
