### ISSUE TITLE
Fluid pipes drop brackets when waterlogged

### ISSUE THREAD

**Issue by AzaSad** [Fabricators-of-Create/Create#1552]
### Describe the Bug

Fluid pipes drop his brackets when waterlogged, but they are still visible in the model

### Reproduction Steps

1.Place a fluid pipe
2.Place a bracket
3.Waterlog the pipe

### Expected Result

The fluid pipe should keep the bracket when waterlogged, or the bracket should stop being visible when dropped

### Screenshots and Videos

https://github.com/user-attachments/assets/5794821f-ba5d-4b69-be03-ac3b600e0b34

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Additional Context

i think the problem is the `onStateReplaced` method on the FluidPipeBlock class

exactly this part
```
		if (state != newState && !isMoving)
			removeBracket(world, pos, true).ifPresent(stack -> Block.dropStack(world, pos, stack));
```

i ask, why would it be needed, since i *think* the only instance in which the fluid pipe state gets replaced is when waterlogged, right?

**Comment by AzaSad** [comment]
![2024-07-27_07 48 26](https://github.com/user-attachments/assets/372c29f3-c762-4af6-a238-7a0ca38423c7)

**Comment by AzaSad** [comment]
![2024-07-27_07 48 26](https://github.com/user-attachments/assets/d31a8c9f-e3c2-491b-b440-b1e597bafc47)

Indeed changing those two lines seem to fix the issue (Sorry for closing and reopening, this is my first time submitting an issue in github)

**Comment by IThundxr** [comment]
PR'd fix upstream
