### ISSUE TITLE
Blueprint right click zone too big

### ISSUE THREAD

**Issue by JupiterSky11** [Fabricators-of-Create/Create#1554]
### Describe the Bug

The crafting blueprint interaction zone extends beyond its hitbox in a 3x3x1 area.  Placing crafting blueprints next to other crafting blueprints becomes nearly impossible.  This has only been tested in a hardcore survival world.

### Reproduction Steps

Place a crafting blueprint, click in the space surrounding it.  It can also be destroyed this way.

### Expected Result

No interaction, as it should only be possible to interact with it when the cursor is touching its hitbox.

### Operating System

Ubuntu 22.04

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

[main/INFO]: Loading 208 mods:
	- ambientsounds 6.0.3
	- appleskin 2.5.1+mc1.20
	- audaki_cart_engine 3.1.1
	- bellsandwhistles 0.4.5
	- betterdeserttemples 1.20-Fabric-3.0.3
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.20-Fabric-4.0.4
	- betterendisland 1.20-Fabric-2.0.6
	- betterfortresses 1.20-Fabric-2.0.6
	- betterjungletemples 1.20-Fabric-2.0.5
	- bettermineshafts 1.20-Fabric-4.0.4
	- bettermounthud 1.2.2
	- betteroceanmonuments 1.20-Fabric-3.0.4
	- betterstrongholds 1.20-Fabric-4.0.3
	- betterwitchhuts 1.20-Fabric-3.0.3
	- bundle_jumble 1.0.2-mc1.20.1
	- bundlescroll 1.1.0
	- c2me 0.2.0+alpha.11.8
	   |-- c2me-base 0.2.0+alpha.11.8
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.8
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.8
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.8
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.8
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.8
	   |-- c2me-notickvd 0.2.0+alpha.11.8
	   |-- c2me-opts-allocs 0.2.0+alpha.11.8
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.8
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.8
	   |-- c2me-opts-math 0.2.0+alpha.11.8
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.8
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.8
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.8
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.8
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.8
	   |-- c2me-server-utils 0.2.0+alpha.11.8
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.8
	   |-- c2me-threading-lighting 0.2.0+alpha.11.8
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.8
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- mixinextras 0.3.6
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- combatify 1.20-1.1.8.3
	   |-- cookeymod 1.7.1+1.20.1
	   \-- reach-entity-attributes 2.4.0
	- create 0.5.1-f-build.1417+mc1.20.1
	   |-- com_electronwill_night-config_core 3.6.6
	   |-- com_electronwill_night-config_toml 3.6.6
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.10-2
	   |-- forgeconfigapiport 8.0.0
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_brewing 2.3.2+1.20.1
	   |-- porting_lib_models 2.3.2+1.20.1
	   |    \-- porting_lib_model_loader 2.3.2+1.20.1
	   |-- porting_lib_obj_loader 2.3.2+1.20.1
	   |    \-- porting_lib_model_loader 2.3.2+1.20.1
	   |-- porting_lib_tags 3.0
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        |-- porting_lib_data 2.1.1090+1.20
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- create_enchantment_industry 1.2.16
	   \-- create_dragon_lib 1.4.2
	- create_structures 1.1.0
	- createbigcannons 0.5.4-nightly-8b9cea6
	   \-- ritchiesprojectilelib 1.0.0-369e88d+1.20.1-fabric
	        \-- porting_lib_utility 2.1.1127+1.20
	             \-- porting_lib_gametest 2.1.1127+1.20
	- createdeco 2.0.2-1.20.1-fabric
	- creativecore 2.11.33
	   \-- net_minecraftforge_eventbus 6.0.3
	- distanthorizons 2.1.2-a
	- eatinganimationid 1.20+1.9.61
	- entityculling 1.6.6
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.11
	- fallingleaves 1.15.6
	- fancymenu 3.2.3
	   |-- com_github_keksuccino_japng 0.5.3
	   \-- com_github_rtyley_animated-gif-lib-for-java animated-gif-lib-1.7
	- farmersdelight 1.20.1-2.1.2+refabricated
	   |-- mm 2.3
	   |-- porting_lib_accessors 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_base 2.3.4+1.20.1
	   |    |-- com_electronwill_night-config_core 3.6.6
	   |    |-- com_electronwill_night-config_toml 3.6.6
	   |    |-- porting_lib_attributes 2.3.4+1.20.1
	   |    |-- porting_lib_common 2.3.4+1.20.1
	   |    |-- porting_lib_core 2.3.4+1.20.1
	   |    |-- porting_lib_entity 2.3.4+1.20.1
	   |    |-- porting_lib_fluids 2.3.4+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.4+1.20.1
	   |    |-- porting_lib_transfer 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_client_events 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_config 2.3.4+1.20.1
	   |    |-- com_electronwill_night-config_core 3.6.6
	   |    |-- com_electronwill_night-config_toml 3.6.6
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_extensions 2.3.4+1.20.1
	   |    |-- porting_lib_attributes 2.3.4+1.20.1
	   |    |-- porting_lib_common 2.3.4+1.20.1
	   |    |-- porting_lib_core 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_lazy_registration 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_loot 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_networking 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_recipe_book_categories 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_registries 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   \-- porting_lib_tool_actions 2.3.4+1.20.1
	        \-- porting_lib_core 2.3.4+1.20.1
	- immediatelyfast 1.2.18+1.20.4
	   \-- net_lenni0451_reflect 1.3.4
	- indium 1.0.34+mc1.20.1
	- java 17
	- konkrete 1.8.1
	- lambdynlights 2.3.2+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- lithium 0.11.2
	- melody 1.0.3
	- memoryleakfix 1.1.5
	- minecraft 1.20.1
	- modelfix 1.15
	- modmenu 7.2.2
	- morechathistory 1.3.0
	- mousetweaks 2.26
	- notenoughanimations 1.7.4
	- owo 0.11.2+1.20
	   \-- blue_endless_jankson 1.2.2
	- railways 1.6.4+fabric-mc1.20.1
	   \-- mm 2.3
	- shulkerboxtooltip 4.0.4+1.20.1
	- sliceanddice 3.2.3
	   \-- forgeconfigapiport 8.0.0
	- sodium 0.5.11+mc1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   \-- fabric-resource-loader-v0 0.11.10+1802ada577
	- sodium-extra 0.5.4+mc1.20.1-build.115
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- visuality 0.7.1+1.20
	- yet_another_config_lib_v3 3.5.0+1.20.1-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- yungsapi 1.20-Fabric-4.0.5
	   \-- org_javassist_javassist 3.29.2-GA
	- yungsbridges 1.20-Fabric-4.0.3
	- yungsextras 1.20-Fabric-4.0.3
	- yungsmenutweaks 1.20.1-Fabric-1.0.2

**Comment by TropheusJ** [comment]
can't reproduce
