### ISSUE TITLE
Bug: Using a Rotation Speed Controller as CC Peripheral allows for setting any speed

### ISSUE THREAD

**Issue by cfpwastaken** [Fabricators-of-Create/Create#1555]
### Describe the Bug

You can set the speed of a rotation speed controller to any speed, even outside of the config's limits and have it work.

### Reproduction Steps

1. Power a rotation speed controller with any power source
2. Place a ComputerCraft Computer next to it
3. Run this lua code:
```lua
rsc = peripheral.wrap("left") -- replace with the side of the peripheral
rsc.setTargetSpeed(29999)
```
4. Go wild

### Expected Result

It should throw a lua error or just automatically cap it to the max of the config.

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/48d7d0d9-40fb-49a7-aff9-f014ea2cf141)
![image](https://github.com/user-attachments/assets/a3ef7735-51ac-4874-b6b3-1908ddfa783a)
Here i connected the speed controller with a wired modem and networking cable but it works the same way.
![image](https://github.com/user-attachments/assets/b3d05257-c8b5-4e27-b2ba-fe1656e4ced6)

### Operating System

Arch Linux

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

CC: Tweaked

**Comment by IThundxr** [comment]
Could you try reproducing this on the forge version of create?

**Comment by cfpwastaken** [comment]
Not reproducible on forge.

**Comment by cfpwastaken** [comment]
I see. I don't seem to have the newest, newest version installed. Tried fixing this myself but it seems patched.

**Comment by cfpwastaken** [comment]
Looking on modrinth the version i was using IS the latest. Perhaps it has been fixed recently but not published yet?

**Comment by IThundxr** [comment]
there were no changes to the cc compat recently

**Comment by IThundxr** [comment]
So, does this occur on the latest fabric patch or no?

**Comment by cfpwastaken** [comment]
It does happen on version 0.5.1-f-build.1417+mc1.20.1 (the latest one on modrinth at the time of writing this).
Compiling the latest commit fb31370 does not have the bug.

**Comment by IThundxr** [comment]
righto, thanks
