### ISSUE TITLE
Crash caused by null stack in BottomlessItemHandler

### ISSUE THREAD

**Issue by cakeGit** [Fabricators-of-Create/Create#1556]
### Describe the Bug

Related to #1036, and I think this is now causing an issue with saving on trains for creative crates, 
![image](https://github.com/user-attachments/assets/13478665-7e6c-485f-8f7c-849903ca20e2)
Since the item is null but the save code iterates over it anyways, and this causes a crash here:
![image](https://github.com/user-attachments/assets/72dfdebc-dbc7-485a-938d-cded23460882)
So it should be fine to just add a check for stack being null and the crash will be avoided

### Reproduction Steps

1.Build a train
2.Put a creative crate on the train
3.Open the pause menu to trigger a save or close the game

### Expected Result

Not to crash

### Screenshots and Videos

Note that this is from a development environment, but the issue still happens outside
[latest.log](https://github.com/user-attachments/files/16462390/latest.log)
[crash-2024-08-01_23.21.16-server.txt](https://github.com/user-attachments/files/16462392/crash-2024-08-01_23.21.16-server.txt)

### Crash Report or Log

https://github.com/user-attachments/files/16462392/crash-2024-08-01_23.21.16-server.txt

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by TropheusJ** [comment]
Can't reproduce.
The stack should never ever be null, something else is wrong.
More debugging would be appreciated.

**Comment by cakeGit** [comment]
Ive gone back onto a backup of the world with the same everything and now i cant reproduce either :/
Ill look out for it in the future but it may have just been a fluke or some other issue at the same time.
My only thought is if its a missing mapping causing the item to become null after the tag has been read, but with testing this doesent work either, thanks for your time though,
