### ISSUE TITLE
Display Links on Threshold Switches cannot be paused.

### ISSUE THREAD

**Issue by MEEPofFaith** [Fabricators-of-Create/Create#1557]
### Describe the Bug

Powering a display link attached to a threshold switch does not pause  writing.

### Reproduction Steps

1. Place a threshold switch on a fluid tank.
2. Power with redstone.

### Expected Result

The display link should stop sending signals as described by the ponder section.

### Screenshots and Videos

https://github.com/user-attachments/assets/9377db1a-cd73-40b2-a2b0-5f4238b34a9a

### Operating System

Windows 11

### Mod Version

0.5.1f (Build 1417)

### Minecraft Version

1.20.1

### Other Mods

No other mods are active in the video (aside from Fabric API, of course).

**Comment by IThundxr** [comment]
Upstream issue: https://github.com/Creators-of-Create/Create/issues/6768
