### ISSUE TITLE
Create Fabric version crashing when launched through Modrinth. Fluidstack error? 

### ISSUE THREAD

**Issue by BedrockBurger** [Fabricators-of-Create/Create#1558]
### Describe the Bug

Setting up a Modrinth instance to easily launch into MC. Got all mod incompatibilities fixed and got the correct versions of Sodium and its add ons working with the correct Create version and add on versions. When i go to launch the instance, Minecraft doesnt even pop up, it just crashes before the launcher appears. Reading the logs, it seems to be a FluidStack error, as thats the last thing in the logs before it crashes. 

### Reproduction Steps

1. Assemble mod pack on Fabric through Modrinth, using specific Create version so it works with Sodium, Enchantment Industry and Steam n Rails add ons
2. Go to launch
3. Crashes after a few seconds
...

### Expected Result

Minecraft to open and allow me to play the instance with Fabric Create

### Crash Report or Log

https://mclo.gs/CMTV1KU

### Operating System

Windows 10 with Fabric Minecraft

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

Appleskin 2.5.1
Athena 3.1.2
Balm 7.3.6
Better third person 1.9.0
cicada 0.8.3
Cardinal Components API 5.2.2
Chipped 3.0.6
chunk loaders 1.2.8a
CorgiLib 4.0.2.0
Create Big cannons 5.5.0
Create Deco 2.0.2
Create enchantment industry 1.2.14
create fabric 0.5.1 build.1161
create copper and zinc renewables 1.4.0
create steam n rails 1.5.1
create trimmed 1.0
create ultimate factory 1.5.0
easy shulker boxes 8.0.2
enhanced block entities 0.9
eureka for ships 1.5.1 beta 3
fabric API 0.92.2
fabric language kotlin 1.11.0
forge config API port 8.0.0
fusion(connected textures) 1.1.1
Geckolib 4.4.7
Indium 1.0.21
IngotCraft 2.4.4
JEI 15.8.2.25
lithium 0.11.2
MaLib 0.16.3
mod menu 7.2.2
more armor trims 1.3.1
mouse tweaks 2.26
oh the biomes weve gone 1.0.4 beta
oh the trees youll grow 1.2.0
puzzles lib 8.1.21
rechiseled 1.1.6
rechiseled: create 1.0.2
replaymod 2.6.13
resourceful lib 2.1.28
show me your skin 1.9.0
sodium 0.4.10
sophisticated backpack fabric 3.19.5
sophisticated core 0.5.109
supermartijn642 config 1.1.8a
supermartijn642 core 1.1.17
Techtonic 2.3.4
Terrablender 3.0.1.7
trinkets 3.7.2
trowel 1.3.0
valkyrien skies 2.3.0 beta.4
waystones 14.1.4
xaeros minimap 24.2.0
xaeros world map 1.38.8
yetanotherconfiglib 3.5.0
zoomify 2.14.0

### Additional Context

Doesnt seem to be a modrinth issue, appears to be Create Fabric based. If theres already a fix for this, please direct me to it. Thank you!

**Comment by IThundxr** [comment]
Update create and all of your other mods

**Comment by BedrockBurger** [comment]
> Update create and all of your other mods

Already did, but Create fabric doesnt work with Sodium, indium and lithium unless its a specific version of each of them. Mod compatability issue. Went back and manually set each to the ones that work together without any incompatibility pop up.

**Comment by IThundxr** [comment]
0.5.1-f works with the latest version of all those mods perfectly fine

**Comment by BedrockBurger** [comment]
> 0.5.1-f works with the latest version of all those mods perfectly fine

Will test again and report back. May have been missing one of them when testing. Thank you for a rapid response :)

**Comment by BedrockBurger** [comment]
> > 0.5.1-f works with the latest version of all those mods perfectly fine
> 
> Will test again and report back. May have been missing one of them when testing. Thank you for a rapid response :)

Update: Missed swapping lithium when manually tweaking each version! My bad! Thank you
