### ISSUE TITLE
Portable storage interface not working

### ISSUE THREAD

**Issue by StarZ563** [Fabricators-of-Create/Create#1560]
### Describe the Bug

When a deployer places a minecart contraption the portable storage interfaces on said contraption stop functioning until they are "reset" (supplying a redstone signal)

### Reproduction Steps

1. Make a minecart contraption with a portable storage interface
2. Pick up with a wrench and place with a deployer in position to have stationary storage interface to connect
3. profit
...

### Expected Result

The interface to work.

### Operating System

Windows 10

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

**Comment by lalaldka** [comment]
exact same issue.

**Comment by IThundxr** [comment]
Fixed by https://github.com/Creators-of-Create/Create/commit/ed875d47acf7c856d6651c42b89039a4b01974cc#diff-f7848a13f4b175872e1f803398db7f9b295b4dc1504db6be09dabc93eacb65b2
