### ISSUE TITLE
Peek Mod and Create don't play nice

### ISSUE THREAD

**Issue by RavenFayrin** [Fabricators-of-Create/Create#1561]
### Describe the Bug

When using the version of Create and Peek below, the 3d modeling does not render on shulkers as Peek is designed to do. I am reaching out to both creators for a fix because I'd love to see both work.

create-fabric-0.5.1-f-build.1417+mc1.20.1
peek-fabric-1.20.1-1.3.4

### Reproduction Steps

1. Load Minecraft 1.20.1 with Fabric 0.15.11 with both **create-fabric-0.5.1-f-build.1417+mc1.20.1** and **peek-fabric-1.20.1-1.3.4**
2. Put stuff in a shulker. See no rendering.
3. Pick up shulker, see rendering in inventory.
4. = Peek only half working.

### Expected Result

Peek should render the name of the shulker if there are many different items in a shulker and a 3d rendering if there is just one when the shulker is placed down.

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

Peek

**Comment by IThundxr** [comment]
can you attach a screenshot of what the issue looks like?

**Comment by RavenFayrin** [comment]
![2024-08-04_16 11 42](https://github.com/user-attachments/assets/dbce2aa0-d293-4901-95f9-6e41e0994afc)
![2024-08-04_16 11 48](https://github.com/user-attachments/assets/86c967cf-369f-40c5-a4fc-51eeeb2c43ef)

**Comment by IThundxr** [comment]
This is because flywheel instances shulker box models, a future version of flywheel will include configs to disable instances for vanilla blocks
