### ISSUE TITLE
Game Crash When Pondering in AOF Orion

### ISSUE THREAD

**Issue by Kira076** [Fabricators-of-Create/Create#1562]
### Describe the Bug

Client crash during pondering a millstone.

This was originally reported in [the Create Forge repo's Issue #4593](https://github.com/Creators-of-Create/Create/issues/4593#issue-1640954537.) It was advised there to open an issue here if this persists (See [IThundxr's comment there](https://github.com/Creators-of-Create/Create/issues/4593#issuecomment-2098404352).)

The error is:
Description: Ticking screen

java.lang.ClassCastException: class com.simibubi.create.foundation.ponder.PonderWorld cannot be cast to class net.minecraft.class_2791 (com.simibubi.create.foundation.ponder.PonderWorld and net.minecraft.class_2791 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @59ec2012)

### Reproduction Steps

1. Running AOF Orion
2. Open inventory and search for Create millstone
3. Hold W to ponder
4. Allow to play for a few seconds
5. Game crashes

### Expected Result

Game does not crash

### Crash Report or Log

https://github.com/user-attachments/files/16488730/crash-2024-08-04_15.42.12-client.txt

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

All of Fabric | Orion

### Additional Context

OS: Windows 10
Minecraft: 1.19.2
Fabric: 0.14.17
Fabric API: 0.75.1+1.19.2
Java: 17.0.12 (OpenJDK)

**Comment by IThundxr** [comment]
0.5.0i isn't supported anymore if you can reproduce this on 0.5.1f open a new issue
