### ISSUE TITLE
Enderman can teleport to and inside of shafts

### ISSUE THREAD

**Issue by MEEPofFaith** [Fabricators-of-Create/Create#1563]
### Describe the Bug

See video.

### Reproduction Steps

1. Place a lot of shafts in the void.
2. Force endermen to teleport.

### Expected Result

Teleporting into blocks doesn't sound intended.

### Screenshots and Videos

https://github.com/user-attachments/assets/c3a68771-da61-42eb-8127-7def8a58e656

### Operating System

Windows 11

### Mod Version

0.5.1f

### Minecraft Version

1.20.1

### Other Mods

None

### Additional Context

Occurs in Forge and Fabric.

**Comment by IThundxr** [comment]
PR'd the fix upstream
