### ISSUE TITLE
Incompatible with Caxton when interacting with Train Station: `java.lang.NullPointerException: Cannot invoke "java.util.function.Function.apply(Object)" because "this.field_1997" is null`

### ISSUE THREAD

**Issue by bluebear94** [Fabricators-of-Create/Create#1568]
### Context

Interacting with Create’s train station crashes when [Caxton](https://modrinth.com/mod/caxton) installed.

This is caused by a missing access widener to `Font#getFontSet`; adding this line to Create’s access widener should solve the problem. Indeed, one workaround is to install [ImmediatelyFast](https://modrinth.com/mod/immediatelyfast), which has an access widener to the same method.

```
extendable method net/minecraft/client/gui/Font getFontSet (Lnet/minecraft/resources/ResourceLocation;)Lnet/minecraft/client/gui/font/FontSet;
```

(The version of Caxton used is [the latest 1.20.1 branch on the repository](https://gitlab.com/Kyarei/caxton/-/tree/1.20.1), which has yet to be released.)

See [issue originally posted on Caxton’s repo](https://gitlab.com/Kyarei/caxton/-/issues/80).

### Crash Report

https://mclo.gs/8oIESvC

**Comment by IThundxr** [comment]
~~is caxton using the fonts (mojmap) field in the Font class by any chance?~~

**Comment by IThundxr** [comment]
fixed the crash with https://github.com/Fabricators-of-Create/Create/commit/4c28059465b51377c3f733cfc9a37a6186e8e26b the text has shadows when caxton is installed, not sure if that's fixable on our side since caxton seems to be doing some stuff with fonts & text drawing

**Comment by bluebear94** [comment]
Yeah, fixing the shadow issue is going to be harder.

**Comment by IThundxr** [comment]
If it's feasible for create to fix it i don't mind fixing it, but if it's easier for you to fix it on your side that would be nice, either way works
