### ISSUE TITLE
Incompatible with Advanced Runtime Resource Pack

### ISSUE THREAD

**Issue by RosaTheRad** [Fabricators-of-Create/Create#1569]
### Context

Modrinth launcher
Minecraft 1.20.1
Fabric Loader 0.15.11
Windows 10
Modpack is Elysium Days 5.2.0 with Sparse Structures 2.2 and Create Fabric 0.5.1-f
Full list of mods copied from the log:
- advanced_runtime_resource_pack 0.8.1
	- advancednetherite 2.1.3-1.20.1
	- advancementinfo 1.20-fabric0.83.0-1.4
	- advancementplaques 1.4.11
	- ambientenvironment **.**.**.**
	- ambientsounds 6.0.3
	- amendments 1.20-1.2.8
	   \-- mixinextras 0.3.6
	- animal_feeding_trough 1.1.0+1.20.1
	- appleskin 2.5.1+mc1.20
	- architectury 9.2.14
	- athena 3.1.2
	- attributefix 21.0.4
	- axesareweapons 1.7.3
	- backported_wolves 1.1.0-1.19.3-1.20.4
	- bakery 1.1.15
	- balm-fabric 7.3.6
	   \-- kuma_api 20.1.8
	- beautify 1.2.0+1.20.1
	- better-trim-tooltips 1.0.1
	- betterarcheology 1.1.9-1.20.1
	- bettercombat 1.8.5+1.20.1
	- betterconduitplacement 3.3
	- betterdeserttemples 1.20-Fabric-3.0.3
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.20-Fabric-4.0.4
	- betterendisland 1.20-Fabric-2.0.6
	- betterfortresses 1.20-Fabric-2.0.6
	- betterjungletemples 1.20-Fabric-2.0.5
	- bettermineshafts 1.20-Fabric-4.0.4
	- bettermounthud 1.2.2
	- betteroceanmonuments 1.20-Fabric-3.0.4
	- betterpingdisplay 1.1.1
	- bettersafebed 1.20-9
	- betterstats 3.12.4+fabric-1.20.1
	- bettertridents 8.0.1
	   |-- cardinal-components-base 5.2.1
	   \-- cardinal-components-entity 5.2.1
	- betterwitchhuts 1.20-Fabric-3.0.3
	- blur 3.1.0
	   \-- satin 1.13.0
	- boatiview 0.0.5
	- bookshelf 20.2.13
	- borderlessmining 1.1.8+1.20.1
	- bountiful 6.0.3+1.20.1
	- breakfree 1.2.0
	- bushierflowers 0.0.3-1.20.1
	- cakechomps 6.2.0+1.20.1
	- calmdowndog 1.1.0
	- candlelight 1.2.13
	- capes 1.5.2+1.20
	- charmofundying 6.5.0+1.20.1
	   \-- spectrelib 0.13.15+1.20.1
	- chas 1.20
	- chat_heads 0.12.9
	- chatanimation 1.0.5
	- cherishedworlds 6.1.6+1.20.1
	- chipped 3.0.6
	- citresewn 1.1.5+1.20.1
	   \-- citresewn-defaults 1.1.5+1.20.1
	- clean-debug 0.4.6
	- clean_tooltips 1.0
	- clickthrough 1.20-fabric0.83.0-0.4.1
	   |-- crowdin-translate 1.4+1.19.3
	   \-- gbfabrictools 1.4+1.20
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- clumps **.**.**.**
	- cobweb 1.0.0
	- collective 7.79
	- comforts 6.4.0+1.20.1
	   |-- cardinal-components-base 5.2.1
	   |-- cardinal-components-entity 5.2.1
	   \-- spectrelib 0.13.15+1.20.1
	- companion 5.2.0
	- continuity 3.0.0-beta.5+1.20.1
	- controlling 12.0.2
	- crawl 0.12.0
	   \-- mm 2.3
	- create 0.5.1-f-build.1417+mc1.20.1
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.10-2
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_accessors 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_base 2.3.2+1.20.1
	   |    |-- porting_lib_attributes 2.3.2+1.20.1
	   |    |-- porting_lib_common 2.3.2+1.20.1
	   |    |-- porting_lib_config 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    |-- porting_lib_fluids 2.3.2+1.20.1
	   |    |-- porting_lib_lazy_registration 2.3.2+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.2+1.20.1
	   |    |-- porting_lib_utility 2.3.2+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_brewing 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_client_events 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_entity 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_mixin_extensions 2.3.2+1.20.1
	   |-- porting_lib_extensions 2.3.2+1.20.1
	   |    |-- porting_lib_attributes 2.3.2+1.20.1
	   |    |-- porting_lib_common 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_models 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    |-- porting_lib_fluids 2.3.2+1.20.1
	   |    \-- porting_lib_model_loader 2.3.2+1.20.1
	   |-- porting_lib_networking 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_obj_loader 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_model_loader 2.3.2+1.20.1
	   |-- porting_lib_tags 3.0
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_tool_actions 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_transfer 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_fluids 2.3.2+1.20.1
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        |-- porting_lib_data 2.1.1090+1.20
	        |    \-- porting_lib_gametest 2.1.1090+1.20
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             |-- porting_lib_gametest 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- creativecore 2.11.33
	   \-- net_minecraftforge_eventbus 6.0.3
	- creeperoverhaul 3.0.2
	- cryingportals 2.8
	- ctov 3.4.6
	- customsplashscreen 2.1.1
	- darkpaintings 17.0.4
	- debugify 1.20.1+2.0
	- deeperdarker 1.2.6
	   \-- customportalapi 0.0.1-beta64-1.20
	- dismountentity 3.5
	- distractingtrims 2.0.4
	- doapi 1.2.15
	   \-- terraform-wood-api-v1 7.0.1
	- doubledoors 5.9
	- e4mc_minecraft 5.1.0
	   \-- folk_sisby_kaleido-config 0.3.1+1.3.1
	- easyanvils 8.0.2
	- easymagic 8.0.1
	- eatinganimationid 1.20+1.9.61
	- elysium-days-tweaks 5.2.0-1.20.1
	- elytraslot 6.4.2+1.20.1
	   \-- mixinsquared 0.1.2-beta.6
	- elytratrims 3.4.3
	   \-- conditional-mixin 0.6.2
	- elytratrims_extensions 2.2.1
	- enchdesc 17.1.18
	- endermanoverhaul 1.0.4
	- endrem 5.2.4
	- enhanced_attack_indicator 1.0.4+1.20
	- enhancedblockentities 0.9+1.20
	   \-- spruceui 5.0.0+1.20
	- entity_model_features 2.1.3
	- entity_texture_features 6.1.3
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.6
	- evs 2.2-backport1.20.1
	- explorify 1.6.1
	- exposure 1.7.5
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.11
	- fabrishot 1.10.1
	- fadeless 1.0.1
	- fallingleaves 1.15.6
	- fastipping 1.0.3
	- ferritecore 6.0.1
	- fishingreal 1.20.1-1.7.2
	- forgeconfigapiport 8.0.0
	- forgivingvoid 10.0.1
	- formations 1.0.2
	- formationsnether 1.0.5
	- friendlyfire 18.0.7
	- gamemenuremovegfarb 2.1.2
	- geckolib 4.4.7
	   \-- com_eliotlash_mclib_mclib 20
	- graveyard 3.0
	- guarding 2.4.0
	   |-- mm 2.3
	   \-- scribe 1.20.1-0.5.0-alpha
	- guardvillagers 2.0.9-1.20.1
	- handcrafted 3.0.6
	- hearth_and_home 1.20.1-2.0.3
	- held-item-info 1.5.0
	- herbalbrews **.**.**.**
	- herdspanic 1.1.0
	- highlight 2.0.1
	- highlighter 1.1.9
	- hopobetterruinedportal 1.3.7
	- hopobetterunderwaterruins 1.1.4
	- horsebuff 2.1.2
	- horseexpert 8.1.1
	- horseinboat 1.1.4
	- iceberg 1.1.18
	- immediatelyfast 1.2.18+1.20.4
	   \-- net_lenni0451_reflect 1.3.4
	- incendium 5.3.5
	- indium 1.0.34+mc1.20.1
	- inmis 2.7.2-1.20.1
	   \-- omega-config 1.2.3-1.18.1
	- inmisaddon 1.0.4
	- inventorysorter 1.9.0-1.20
	   \-- kyrptconfig 1.5.6-1.20
	- invmove 0.8.4
	- invmovecompats 0.3.2
	- iris 1.7.2+mc1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- io_github_douira_glsl-transformer 2.0.1
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.13.1
	- itemborders 1.2.2
	- itemphysiclite 1.6.4
	- jamlib 0.6.1+1.20.x
	- java 17
	- jeed 1.20-2.2.2
	- jei **.**.**.**
	- jumpoverfences 1.3.1
	- justenoughbreeding 1.2.4
	- kaffees_dual_ride 1.1.0
	- kambrik 6.1.1+1.20.1
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lambdynlights 2.3.2+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- languagereload 1.6.1+1.20.1
	- leafmealone 1.0.1
	- leavesbegone 8.0.0
	- lithium 0.11.2
	- lithostitched 1.1.8
	- logbegone 1.0.8
	- make_bubbles_pop 0.3.0-fabric
	- mavapi 1.1.4
	- mavm 1.2.6
	- meadow 1.3.19
	- medievalweapons 1.4.8
	- memoryleakfix 1.1.5
	- mes 1.3.1-1.20-fabric
	- midnightlib 1.4.1
	- minecraft 1.20.1
	- mixintrace 1.1.1+1.17
	- mobfilter 0.4.2+1.20.1
	   \-- org_yaml_snakeyaml 2.1
	- mobs_attempt_parkour 0.5.2-1.20
	   \-- maelstrom_library 1.6.1-1.20
	- modelfix 1.15
	- modernfix 5.19.0+mc1.20.1
	- modmenu 7.2.2
	- monsters_in_the_closet 1.0.3+1.20
	- moonlight 1.20-2.12.10
	- mooshroomtweaks 3.5
	- more_armor_trims 1.3.1-1.20.1
	- moreculling 1.20.4-0.24.0
	- moremcmeta 1.20.1-4.4.7
	   |-- moremcmeta_animation_plugin 1.20.1-1.0.3
	   |-- moremcmeta_gui_plugin 1.20.1-1.0.1
	   |-- moremcmeta_json_parser_plugin 1.20.1-1.1.1
	   |-- moremcmeta_properties_parser_plugin 1.20.1-1.1.5
	   \-- moremcmeta_texture_plugin 1.20.1-1.0.1
	- moremcmeta_emissive_plugin 1.20.1-2.0.4
	- mousetweaks 2.26
	- mr_camps_castles_carriages 2.3.3
	- mr_hero_proof 5.2
	- mr_mastercutter 1.1
	- mr_true_ending 1-v1.1.0c
	- mr_villager_transportation 1.3.1
	- mru 0.4.4+1.20.1
	- naturalist 4.0.3
	- neat 1.20-35-FABRIC
	   \-- fiber 0.23.0-2
	- nerb 0.3
	- netherdepthsupgrade fabric-3.1.6-1.20
	- netherite_horse_armor 1.20.1-1.0.4
	- netherportalfix 13.0.1
	- niftycarts 3.0.2+1.20.1
	- nnvf 0.1.3_1.20
	- no-telemetry 1.8.0
	- noanimaltemptdelay 1.2
	- nochatreports 1.20.1-v2.2.2
	- nonarrator 1.0.1
	- notenoughanimations 1.7.4
	- nullscape 1.2.7
	- nyfsspiders 2.1.1
	- optigui 2.1.7
	   |-- optiglue 2.1.7-mc.1.19.3
	   |-- org_apache_commons_commons-text 1.10.0
	   \-- org_ini4j_ini4j 0.5.4
	- panorama_screens 1.0+fabric+mc1.20
	- passiveshield 3.6
	- pathunderfencegates 1.4.0+mc1.20.x
	- paxi 1.20-Fabric-4.0
	- philipsruins 1.20.1
	- player-animator 1.0.2-rc1+1.20
	- polymorph 0.49.5+1.20.1
	   |-- cardinal-components-base 5.2.1
	   |-- cardinal-components-block 5.2.1
	   |-- cardinal-components-entity 5.2.1
	   |-- cardinal-components-item 5.2.1
	   \-- spectrelib 0.13.15+1.20.1
	- presencefootsteps 1.9.4+1.20.1
	   \-- kirin 1.15.6+1.20.1
	- prism 1.0.5
	- purediscstrickytrials 1.0.1
	- puzzleslib 8.1.21
	   \-- puzzlesaccessapi 8.0.7
	- realisticsleep 1.10.2+mc1.20-1.20.1
	   \-- server_translations_api 2.0.0+1.20
	        \-- packet_tweaker 0.4.0+1.19.4
	- reeses-sodium-options 1.7.2+mc1.20.1-build.101
	- regions_unexplored 0.5.6+1.20.1
	- repurposed_structures 7.1.15+1.20.1-fabric
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.28
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- resourcepackoverrides 8.0.3
	- rightclickharvest 3.2.3+1.19.x-1.20.1-fabric
	- scaffoldingdropsnearby 3.3
	- searchables 1.0.3
	- securecrops 1.0.4+1.20
	- shouldersurfing 4.3.0
	- shulkerboxtooltip 4.0.4+1.20.1
	- shulkerdropstwo 3.4
	- shut_up_gl_error 1.0.0
	- simple-armor-hud 1.20.2-1.3.2
	- simplehudenhanced 4.7.1
	- simplemod 1.20.1
	- sit 1.20.1-27
	- skeletonhorsespawn 4.0
	- skinlayers3d 1.6.6
	- smarterfarmers 1.20-1.8.2
	- snowpig 3.0.1
	- snowundertrees 2.4.0+1.20.1
	- sodium 0.5.11+mc1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   \-- fabric-resource-loader-v0 0.11.10+1802ada577
	- sodium-extra 0.5.4+mc1.20.1-build.115
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- soul_fire_d 4.0.2
	- sound_physics_remastered 1.20.1-1.4.5
	- soundcontroller 1.0.0
	- sounds 0.9.0+1.20.1
	   \-- org_chenliang_oggus_oggus 1.2.0
	- sparsestructures 2.2.0
	- spawnanimations 1.9.4+mod
	- sspb 3.3.1
	- starlight 1.1.2+fabric.dbc156f
	- supplementaries 1.20-2.8.17
	   \-- mixinextras 0.3.6
	- surfacemushrooms 3.5
	- tcdcommons 3.12.2+fabric-1.20.1
	- terrablender **.**.**.**
	   |-- com_electronwill_night-config_core 3.6.7
	   \-- com_electronwill_night-config_toml 3.6.7
	- tipsmod 12.1.8
	- tlc 1.0.1
	- torch_hit 7.0.0
	- treeharvester 9.0
	- trinkets 3.7.2
	- universalbonemeal 8.0.1
	- unsafe-world-random-access-detector 1.1.0
	- veinmining 1.5.0+1.20.1
	   \-- spectrelib 0.13.15+1.20.1
	- villagernames 8.1
	- villagesandpillages 1.0.0
	- visuality 0.7.1+1.20
	- waterdripsound 1.19-0.3.2
	- waveycapes 1.4.8
	- weakerspiderwebs 3.7
	- weaponmaster_ydm 4.2.3
	- whatthebucket 11.0.3
	- xaerominimap 24.2.0
	- xaeroworldmap 1.38.8
	- yeetusexperimentus 2.3.0-build.4+mc1.20.1
	- yet_another_config_lib_v3 3.5.0+1.20.1-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- yigd 2.0.0-beta.13
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- libgui 8.1.1+1.20.1
	        |-- jankson 6.0.0+j1.2.3
	        |    \-- blue_endless_jankson 1.2.3
	        \-- libninepatch 1.2.0
	- yosbr 0.1.2
	- yungsapi 1.20-Fabric-4.0.5
	   \-- org_javassist_javassist 3.29.2-GA
	- yungsbridges 1.20-Fabric-4.0.3
	- yungsextras 1.20-Fabric-4.0.3
	- zombiehorsespawn 5.1
	- zoomify 2.14.0+1.20.1
	   \-- com_akuleshov7_ktoml-core-jvm 0.5.1

Game crash on launch. See crash report. (fabric_loader_dependencies.json was edited to remove the incompatibility between Create and Sound Physics Remastered. SPR is not the cause of this crash, which occurs with or without it.)

### Crash Report

https://mclo.gs/ZS4Gvfg

**Comment by TropheusJ** [comment]
Some mod is loading the registry way too early. ARRP is unrelated. You will have to figure out which mod is causing it.

**Comment by Fyoncle** [comment]
> Some mod is loading the registry way too early. ARRP is unrelated. You will have to figure out which mod is causing it.

Sorry for the misuderstanding, it was happening because of Serilum's mods, issue opened to the related places.
https://github.com/Serilum/.issue-tracker/issues/2578

This issue can be closed.
