### ISSUE TITLE
Rope Pulley Doesn't Pull Upwards

### ISSUE THREAD

**Issue by Ashton3D** [Fabricators-of-Create/Create#157]
### Describe the Bug

The rope pulley tries to pull upwards, then it turns into an entity and then just freezes and locks back in place again.
Vertical gantry carriage has a similar issue, where it just stops working even if it worked before. Unsure if horizontal does the same thing.

Both pulley and gantry carriage have worked before.

### Reproduction Steps

1. Make a rope pulley/gantry carriage setup (may have to only be on low power source link a windmill with a rotational speed controller)
2. Attach a semi-large structure to it
3. Use the rope pulley or gantry over and over until it breaks (may depend on how much the server is lagging)

### Expected Result

The Gantry carriage will just stop working, and the rope pulley will start moving for a second, then stop after moving nowhere.

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

[Mouse Tweaks](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Clumps](https://www.curseforge.com/minecraft/mc-mods/clumps)
[FPS Reducer](https://www.curseforge.com/minecraft/mc-mods/fps-reducer)
[Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu)
[Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium)
[Dark Paintings](https://www.curseforge.com/minecraft/mc-mods/dark-paintings)
[Lithium (Fabric)](https://www.curseforge.com/minecraft/mc-mods/lithium)
[LazyDFU](https://www.curseforge.com/minecraft/mc-mods/lazydfu)
[Illuminations 🔥](https://www.curseforge.com/minecraft/mc-mods/illuminations)
[Fabric Language Kotlin](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Origins (Fabric)](https://www.curseforge.com/minecraft/mc-mods/origins)
[More Axolotl Variants Mod](https://www.curseforge.com/minecraft/mc-mods/mavm)
[ToolTipFix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix)
[Indium](https://www.curseforge.com/minecraft/mc-mods/indium)
[Mo' Structures (Fabric)](https://www.curseforge.com/minecraft/mc-mods/mo-structures)
[On Soul Fire](https://www.curseforge.com/minecraft/mc-mods/on-soul-fire)
[Krypton](https://www.curseforge.com/minecraft/mc-mods/krypton)
[Amplified Nether](https://www.curseforge.com/minecraft/mc-mods/amplified-nether)
[Inventory Sorting](https://www.curseforge.com/minecraft/mc-mods/inventory-sorting)
[Nears [Fabric]](https://www.curseforge.com/minecraft/mc-mods/nears)
[Axolotl Bucket Fix](https://www.curseforge.com/minecraft/mc-mods/axolotl-bucket-fix)
[Horse Stats Vanilla (Fabric)](https://www.curseforge.com/minecraft/mc-mods/horsestatsvanilla)
[Crawl (Fabric)](https://www.curseforge.com/minecraft/mc-mods/crawl)
[Pehkui](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[Starlight (Fabric)](https://www.curseforge.com/minecraft/mc-mods/starlight)
[Rat's Mischief 🐀](https://www.curseforge.com/minecraft/mc-mods/rats-mischief)
[Auth Me](https://www.curseforge.com/minecraft/mc-mods/auth-me)
[Reroll](https://www.curseforge.com/minecraft/mc-mods/reroll)
[Fix Experience Bug (now with FABRIC and FORGE versions)](https://www.curseforge.com/minecraft/mc-mods/fix-experience-bug)
[Reload Audio Driver (RAD) [Fabric]](https://www.curseforge.com/minecraft/mc-mods/reload-audio-driver-fabric)
[Clear Despawn [Fabric]](https://www.curseforge.com/minecraft/mc-mods/clear-despawn-fabric)
[Farmer's Delight [Fabric]](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[Dark Loading Screen](https://www.curseforge.com/minecraft/mc-mods/dark-loading-screen)
[Luminous Wool](https://www.curseforge.com/minecraft/mc-mods/luminous-wool)
[Kiwi 🥝 (Fabric)](https://www.curseforge.com/minecraft/mc-mods/kiwi-fabric)
[Damage Tilt](https://www.curseforge.com/minecraft/mc-mods/damage-tilt)
[Fast Furnace for Fabric](https://www.curseforge.com/minecraft/mc-mods/fast-furnace-for-fabric)
[Cave Tweaks](https://www.curseforge.com/minecraft/mc-mods/cave-tweaks)
[Enhanced Block Entities](https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities)
[Sound Physics Remastered](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[Botania (Fabric)](https://www.curseforge.com/minecraft/mc-mods/botania-fabric)
[Campanion](https://www.curseforge.com/minecraft/mc-mods/campanion)
[Dracomelette](https://www.curseforge.com/minecraft/mc-mods/dracomelette)
[Impaled 🔱](https://www.curseforge.com/minecraft/mc-mods/impaled)
[Terralith 2.0 ~ Overworld Evolved](https://www.curseforge.com/minecraft/mc-mods/terralith)
[Global Data- & Resourcepacks](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack)
[[FABRIC] Disable Custom Worlds Advice](https://www.curseforge.com/minecraft/mc-mods/fabric-disable-custom-worlds-advice)
[Alternate Current](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
[Connectible Chains [Fabric]](https://www.curseforge.com/minecraft/mc-mods/connectible-chains)
[Dual Riders](https://www.curseforge.com/minecraft/mc-mods/dual-riders)
[Twigs](https://www.curseforge.com/minecraft/mc-mods/twigs)
[Visuality](https://www.curseforge.com/minecraft/mc-mods/visuality)
[Cammie's Combat Tweaks](https://www.curseforge.com/minecraft/mc-mods/cammies-combat-tweaks)
[Polymorph (Fabric)](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric)
[Snow Mercy ⛄](https://www.curseforge.com/minecraft/mc-mods/snow-mercy)
[AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[FTB Library (Fabric)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric)
[FTB Teams (Fabric)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric)
[FTB Chunks (Fabric)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-fabric)
[GeckoLib](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Patchouli (Fabric)](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
[Stoneholm, Underground Villages (Fabric)](https://www.curseforge.com/minecraft/mc-mods/stoneholm)
[The Graveyard (FABRIC)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-fabric)
[Anthropophagy](https://www.curseforge.com/minecraft/mc-mods/anthropophagy)
[Better Animals Plus](https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus)
[BetterNether](https://www.curseforge.com/minecraft/mc-mods/betternether)
[Bosses of Mass Destruction](https://www.curseforge.com/minecraft/mc-mods/bosses-of-mass-destruction)
[Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Respawnable Pets](https://www.curseforge.com/minecraft/mc-mods/respawnable-pets)
[Snow! Real Magic! ⛄ (Fabric)](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic-fabric)
[Trinkets (Fabric)](https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric)
[Adorn](https://www.curseforge.com/minecraft/mc-mods/adorn)
[Architectury API (Fabric)](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric)
[FerriteCore (Fabric)](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric)
[Roughly Enough Items Fabric/Forge (REI)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
[Numismatic Overhaul](https://www.curseforge.com/minecraft/mc-mods/numismatic-overhaul)
[Roughly Enough Resources](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-resources)
[Cloth Config API (Fabric)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Guard Villagers (Fabric)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers-fabric)
[Cammie's Wearable Backpacks](https://www.curseforge.com/minecraft/mc-mods/cammies-wearable-backpacks)
[Extra Origins](https://www.curseforge.com/minecraft/mc-mods/extra-origins)
[You're in Grave Danger](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)
[oωo (owo-lib)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
[Besmirchment 2](https://www.curseforge.com/minecraft/mc-mods/besmirchment-2)
[Bewitchment](https://www.curseforge.com/minecraft/mc-mods/bewitchment)
[BCLib](https://www.curseforge.com/minecraft/mc-mods/bclib)

### Additional Context

Likely has to be on a server.

**Comment by PepperCode1** [comment]
This may be fixed with the latest build. Please test it and let us know.

**Comment by TropheusJ** [comment]
Reopen if it still happens.
