### ISSUE TITLE
New custom modpack (Curseforge) crashes on launch

### ISSUE THREAD

**Issue by wonkers27** [Fabricators-of-Create/Create#1572]
### Context

So I recently created a new custom create-focused modpack on Minecraft 1,20.1, I switched to fabric for performance and mod availability reasons, and the game fully crashes on launch.
![Minecraft Launcher 2024-08-11 9_28_50 PM](https://github.com/user-attachments/assets/f53e664b-f902-4706-8f73-9de9c07abdfd)
Crash report is included below, I'm not sure what to do here so feedback is appreciated.

### Crash Report

https://mclo.gs/kHb2R40

**Comment by IThundxr** [comment]
createlagless is crashing
