### ISSUE TITLE
Create 1.19.2 v.0.5.1.f Patch 1 crashes on startup.

### ISSUE THREAD

**Issue by Skullians** [Fabricators-of-Create/Create#1573]
### Description

Create crashes on startup with the error java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1087.method_4710()" because "$$6" is null.

### Game Log

https://mclo.gs/iEpB0Oj / https://mclo.gs/MrDfJqW

### Debug Information

N/A.

**Comment by IThundxr** [comment]
report to the tinkers fabric port you are using

**Comment by Skullians** [comment]
Do you know how it happens though?
The dev of the port is inactive

**Comment by Skullians** [comment]
@IThundxr The error is to do with this in the OpenCreateMenuButton.

```java
        @Override
	public void renderBg(PoseStack mstack, Minecraft mc, int mouseX, int mouseY) {
		Minecraft.getInstance().getItemRenderer().renderGuiItem(ICON, x + 2, y + 2);
	}
```

and the ICON variable is AllItems.GOGGLES.asStack();
I do know Tinkers Construct adds Traveler's Goggles but I don't see it overriding any create API whatsoever?

**Comment by Skullians** [comment]
From the looks of it, it's failing to render the goggles item but I fail to see any involvement with the tinkers construct port I am using

**Comment by IThundxr** [comment]
It is not, the actual exception is thrown before: https://mclo.gs/MrDfJqW#L1805

**Comment by Skullians** [comment]
oh :/ I'm blind
