### ISSUE TITLE
When detecting whether a fluid being drained is infinite or not, game will only detect the fluid blocks upon the bottom of the hose(or at least not all the way to the bottom of it)

### ISSUE THREAD

**Issue by henryyuyhy** [Fabricators-of-Create/Create#1577]
### Description

see pic
![image](https://github.com/user-attachments/assets/45110c42-abb2-4ec1-b56d-ef1b147aa65e)
so i have to crank the hose all the way to the bottom of my lava pit

### Game Log

/

### Debug Information

/

**Comment by IThundxr** [comment]
This is intended and this is how it's always worked
