### ISSUE TITLE
Saw timestopper

### ISSUE THREAD

**Issue by LMattewl** [Fabricators-of-Create/Create#1581]
### Description

I don't know how to explain, I don't even speak english, but I will try my best.

When I'm doing any farm with the saws stuck with slime glue they bug as if they were "shaking", I don't know if you understood but it is shaking, together with another "version" of the same farm with mechanical bearing, it's even funny  

### Game Log

There's no log

**Comment by denisJaved** [comment]
Try to use other languages you know, this can be helpful for understanding issue

**Comment by IThundxr** [comment]
Upstream issue
