### ISSUE TITLE
Can't access the train station to build a train

### ISSUE THREAD

**Issue by Abitconfused** [Fabricators-of-Create/Create#1583]
### Description

Playing on 1.20.1, on fabric and can't use the train station in any way, to be exact it doesn't show the screen to to name the station or to start building the train, there is simply no reaction when i interact with it.

### Game Log

https://mclo.gs/fIFShTs

**Comment by IThundxr** [comment]
Does this also occur with just create + fabric api?

**Comment by Abitconfused** [comment]
No, it doesn't. I'm guessing then there must have been something else causing that issue.

**Comment by IThundxr** [comment]
Try the following:

The binary search is a way of finding a faulty thing amongst a lot of other things, without having to remove the things one-by-one. This is useful for finding a broken mod among hundreds of mods, without having to spend time testing the mods one-by-one.

The procedure is simple:

1. Remove half of the existing things, and put them aside.
2. Run the program / game.
3. Does the issue still exist?
   If YES: Repeat from step 1 with the current things.
   IF NO: Swap out the current things with the ones set aside, and repeat from step 1.
4. Repeat this process until the problematic thing/s have been found.
