### ISSUE TITLE
When I open REI I get massive fps drops and bad performance inside of any GUI.

### ISSUE THREAD

**Issue by redpanas** [Fabricators-of-Create/Create#159]
### Describe the Bug

Very bad FPS in any GUI, including chests, the inventory etc. Basically everything that REI pops into. I don't know if this is a problem of REI or Create. I'm happy to share any more info.

### Reproduction Steps

1. Open any GUI that REI is in.

### Expected Result

No freezing and no fps drops.

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

1.18-StorageCabinet-1.4.2-fabric.jar
Adorn-3.3.1+1.18.1-fabric.jar
advancementinfo-1.18-fabric0.43.1-1.3.jar
advancements-enlarger-0.2.4.jar
Amplifier+Nether+1.0.1+_+Fabric.jar
animatica-0.3+1.18.jar
antighost-1.18-fabric0.43.1-1.1.4.jar
appleskin-fabric-mc1.18.1-2.3.0.jar
appliedenergistics2-10.1.0-beta.2.jar
architectury-3.6.17.jar
architectury-3.7.22.jar
arrp-0.5.4.jar
autoconfig1u-3.3.1.jar
backslot-1.2.5.jar
backslotaddon-1.0.8.jar
balm-fabric-2.4.1+0.jar
bclib-1.3.4.jar
beenfo-1.18.1-fabric0.45.0-1.3.3.jar
better-nether-6.0.10.jar
bettermounthud-1.1.4.jar
BetterPingDisplay-Fabric-1.18.1-1.1.1.jar
bettersleeping-0.4.0.jar
BetterStrongholds-Fabric-1.18.1-1.0.1.jar
betterthanmending-1.3.0.jar
bewitchment-1.18-13.jar
blabber-0.1.2.jar
blast-1.8.2.jar
borderless-mining-1.1.1+1.18.jar
Capes-1.2.2+1.18.jar
cem-0.7.0.jar
CITResewn-0.9.1+1.18.1.jar
cloth-api-3.1.61.jar
cloth-config-6.2.57-fabric.jar
Clumps-fabric-1.18.1-8.0.4.jar
CompactStatusEffects-2.1.1.jar
completeconfig-lib-1.3.3.jar
conjuring-1.0.20+1.18.jar
continuity-1.0.3+1.18.jar
CraftPresence-Fabric-1.18.1-Release-1.8.8.jar
create-mc1.18.1_v0.4d+413.jar
crimson-moon-2.1.1-1.18.1.jar
crookedcrooks-2.0.1+1.18.1.jar
Croptopia-1.18-FABRIC-1.8.0.jar
dark-enchanting-0.6.3+1.18.jar
dawn-3.2.0.jar
diggusmaximus-1.5.2-1.18.jar
dynamic-fps-2.1.0.jar
enhancedblockentities-0.5+1.18.jar
entityculling-fabric-mc1.18-1.5.0.jar
fabric-api-0.46.4+1.18.jar
fabric-language-kotlin-1.7.1+kotlin.1.6.10.jar
FabricShieldLib-1.5.0-1.18.jar
fabrishot-1.6.2.jar
fastopenlinksandfolders-1.1.0.jar
feature_nbt_deadlock_be_gone_fabric-1.0.1+1.18.1.jar
ferritecore-4.1.1-fabric.jar
geckolib-fabric-1.18-3.0.32.jar
illuminations-1.10.2.jar
illuminations-uninstaller.jar
indium-1.0.2-alpha2+mc1.18.1.jar
indrev-1.13.6-BETA.jar
inmis-2.5.1-1.18.1.jar
InventorySorter-1.8.4-1.18.jar
invisframes-2.1.1.jar
iron-jetpacks-0.4.3.jar
item-model-fix-1.0.3+1.18.jar
itemscroller-fabric-1.18.1-0.15.0.jar
kibe-1.9.4-BETA+1.18.jar
lambdabettergrass-1.2.2+1.17.jar
lambdynamiclights-2.1.0+1.17.jar
language-reload-1.2.1.jar
lapisreserve-1.0.8.jar
lazydfu-0.1.2.jar
lifts-1.4-BETA+1.18.jar
light-overlay-6.0.4.jar
lithium-fabric-mc1.18.1-0.7.7.jar
logical_zoom-0.0.13.jar
lootbeams-2.0.4.jar
malilib-fabric-1.18.1-0.11.7.jar
mcda-2.0.1.jar
mcdar-1.4.3-1.18.jar
mcdw-4.0.4.jar
midnightlib-0.3.1.jar
MinecraftCapes+Fabric+1.18.1-12.0.2.jar
mini-extras-fabric-1.4.0+1.18.1.jar
Mo-Glass-1.6.1-MC1.18.1.jar
mobz-3.3.1-fabric.jar
Modern-Industrialization-1.0.5.jar
modmenu-3.0.1.jar
morechathistory-1.18-1.1.0.jar
morevillagers-FABRIC-1.18.1-3.1.1.jar
mostructures-1.3.0-pre1-1.18.jar
mousewheelie-1.8.0+mc1.18-pre5.jar
musicdr-1.4.0.jar
namepain-1.4.1+forge-1.18.x.jar
ninjaphenix-container-library-1.3.0+1.18-fabric.jar
nofade-1.18-2.0.1.jar
nomoreglowingpots-1.0.2.jar
notenoughanimations-fabric-1.4.0-mc1.18-pre1.jar
notenoughcrashes-4.1.4+1.18.1-fabric.jar
notes-1.18-1.0.10.jar
now-playing-1.3.0-fat.jar
no_angled_brackets-universal-1.1.0.jar
no_null_processors_fabric-2.0.0+1.18.jar
npc-variety-1.18-2.2.2.jar
owo-lib-0.5.2+1.18.jar
packages-1.18.1-1.3.jar
Patchouli-1.18.1-65-FABRIC.jar
Pehkui-3.1.0+1.14.4-1.18.1.jar
PerspectiveModRedux-1.17-0.0.5_01.jar
PetOwner-1.8.2-1.18-pre4+.jar
phonos-0.2+1.18.jar
pling-1.5.0.jar
polymorph-fabric-0.0.19-1.18.1.jar
promenade-2.5.1.jar
puzzle-1.1.0.jar
quartz-elevator-2.1.0+1.18.jar
quickshulker-1.3.6-1.18.jar
ratsmischief-1.3.4.jar
red-bits-1.12.0.jar
redstone-bits-1.6.2+fabric-mc1.18.jar
reeses_sodium_options-mc1.18.1-1.4.0.jar
replanter-fabric-1.18-1.3.jar
repurposed_structures_fabric-3.3.12+1.18.1.jar
rer-2.4.1.jar
reroll-1.4.0-1.18.1.jar
respawnablepets-1.18-2.jar
right-click-clear-2.0.4.jar
RingsOfAscension-1.18-1.0.jar
rocks-1.5.2.jar
RoughlyEnoughItems-7.3.432.jar
rpgstats-4.3.4+1.18.1.jar
ruined-equipment-1.4.0.jar
sandwichable-1.2-rc4+1.18.jar
secretrooms-1.3.0+1.18.1.jar
servertick-mc1.18-1.6.jar
servux-fabric-1.18.0-0.1.0.jar
shuffle-4.0.0-fabric.jar
shulkerboxtooltip-3.0.5+1.18.jar
SimpleBackpack_Fabric-1.18.1-1.2.30.jar
sit-1.18.1-16.jar
skin-swapper-fabric-3.1.0.jar
slight-gui-modifications-2.0.3.jar
slotlock-1.0.4-BETA+1.18.jar
smoothboot-fabric-1.18-1.7.0.jar
sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar
soundphysics-fabric-1.18.1-1.0.4.jar
spawnlanterns-1.0.3.jar
staffofbuilding-1.4.1-1.18.1.jar
strawdummy-1.6.0.jar
TacoCraft-1.7.2+1.18.1.jar
TechReborn-5.1.0-beta.9.jar
the_bumblezone_fabric-4.3.5+1.18.1.jar
TieFix-1.9.0.jar
toms_storage-1.18-1.1.19.jar
tooltipfix-1.0.4-1.18.jar
trapexpansion-1.3.3+fabric-mc1.18.jar
trinkets-3.2.0.jar
tweakeroo-fabric-1.18.1-0.12.3.jar
upgradedechests-1.0.3-1.18.jar
upgradedshulkers-1.1.1.-1.18.jar
vanilla-hammers-3.2.0-1.18.1.jar
vanillaexcavators-2.2.0-1.18.1.jar
voicechat-fabric-1.18.1-2.2.16.jar
WardBlocks-Fabric-1.18.1-1.2.24.jar
waystones-fabric-1.18.1-9.0.3.jar
wirelessnetworks-1.4.1.jar
Wither-Totems-Mod-0.3.4-1.18-rc2.jar
wolves-with-armor-1.7.0-1.18.jar
WorldEditCUI-1.18.1+01.jar
wraith-harvestscythes-2.4.1.jar
wthit-fabric-4.5.1.jar
XaerosWorldMap_1.20.3.1_Fabric_1.18.jar
Xaeros_Minimap_22.2.0.1_Fabric_1.18.jar
xp_storage-1.4.3+1.18.jar
yosbr-0.1.1.jar
YungsApi-1.18-Fabric-36.jar

### Additional Context

FYI. I have a Ryzen 5 5600x and a GTX 1650.

**Comment by TropheusJ** [comment]
Please test without Create and see if the problem persists.

**Comment by redpanas** [comment]
> Please test without Create and see if the problem persists.

Yeah sorry it was dumb of me to not test. The problem persisted.
