### ISSUE TITLE
Chutes incorrectly remove music discs from jukeboxes

### ISSUE THREAD

**Issue by techno-sam** [Fabricators-of-Create/Create#1590]
### Description

If a Chute is placed under a Jukebox, and a Music Disc is placed in the Jukebox (manually) then the Chute will remove the Music Disk, but it bypasses `Lnet/minecraft/block/entity/JukeboxBlockEntity;removeStack(II)Lnet/minecraft/item/ItemStack;` which results in the Jukebox continuing to play and continuing to have the `has_record` property be set to `true`.

### Game Log

N/A

**Comment by TropheusJ** [comment]
fabric API implements transfer support for the jukebox, report there

**Comment by TropheusJ** [comment]
are you on the latest version though? support should've been fixed ages ago

**Comment by IThundxr** [comment]
> Fabric api: 0.92.2
> Create Fabric: 0.5.1-f-build.1417

**Comment by IThundxr** [comment]
Was supposedly fixed in FAPI 0.92.1
