### ISSUE TITLE
incompatible with shader

### ISSUE THREAD

**Issue by IjiyaKokujo** [Fabricators-of-Create/Create#1591]
### Description

In this case, the problem only occurs with moving blocks such as sliding doors or elevators. Trains
![image](https://github.com/user-attachments/assets/69f673e5-b65b-4281-a63d-1b80d34af13a)

### Game Log

https://mclo.gs/uejO2SS

**Comment by denisJaved** [comment]
Remember so flywheel is not compatible with iris how said in #1548

**Comment by denisJaved** [comment]
> iris is not incompatible with flywheel. Flywheel just disables its instancing engine when shaders are being used and defaults to normal rendering.

I think so irisflw causes bug by forcing iris engine not in all places it needs to.

**Comment by IjiyaKokujo** [comment]
> > iris is not incompatible with flywheel. Flywheel just disables its instancing engine when shaders are being used and defaults to normal rendering.
> 
> I think so irisflw causes bug by forcing iris engine not in all places it needs to.

ahaa i see thank you
