### ISSUE TITLE
Unbreakable doesn't stay.

### ISSUE THREAD

**Issue by Schoktra** [Fabricators-of-Create/Create#1592]
### Description

I have a mod which allows me to add the unbreakable flag to tools and armor. Problem lies in that when you add it to a netherite back tank (and I assume copper sill suffer this as well), place it in a contraption to refill the air, then pick it back up it removes the unbreakable flag.

### Game Log

https://mclo.gs/hsgrHvy

**Comment by IThundxr** [comment]
This should be fixed by the next patch already, can you give https://mvn.devos.one/snapshots/com/simibubi/create/create-fabric-1.20.1/0.5.1-g-build.1506+mc1.20.1/create-fabric-1.20.1-0.5.1-g-build.1506+mc1.20.1.jar a try?

**Comment by IThundxr** [comment]
I'm gonna assume this is fixed by the linked jar, if it isn't feel free to open a new issue.
