### ISSUE TITLE
Datapacks using create recipes don't function on Fabric Create

### ISSUE THREAD

**Issue by UmbraResistis** [Fabricators-of-Create/Create#1597]
### Description

I had made a datapack with both fabric Create and forge Create, on forge create the recipes work fine in datapack form, but on fabric I had to specifically make it into mod form for the recipes to function. The same datapack that worked on forge Create did not on fabric Create.
Currently using Create 1.20.1 v0.5.1.f Patch 1

### Game Log

https://mclo.gs/gj95Ict

**Comment by TropheusJ** [comment]
upload the datapack
