### ISSUE TITLE
REI fluid quantity display error

### ISSUE THREAD

**Issue by Htao-uu** [Fabricators-of-Create/Create#1598]
### Description

Always I use Crafttweeker or other ways to add mixing recipe, if I add a recipe with two or more kinds of fluid inputted and one kind of fluid outted,the REI gui will show the wrong fluid quantity but right aspect ratio of the icon. For example if I add a recipe that let 111mb water and 222mb lava translate into 333mb milk, it will only show 111mb on each fluid icon(maybe222 or 333,i dont know the rule)
create version: fabric-0.5.1-f-build.1417+mc1.20.1
REI version: 12.1.758-fabric   1.20.1

### Game Log

no need

**Comment by TropheusJ** [comment]
Can you get screenshots? Is the tooltip wrong or the displayed fluid?

**Comment by TropheusJ** [comment]
see #1616
