### ISSUE TITLE
Crushing Wheel cannot export to Chute below

### ISSUE THREAD

**Issue by Dr-WeiAL** [Fabricators-of-Create/Create#160]
### Describe the Bug

I have tried it, and the forge version of create does not have this problem

### Reproduction Steps

1.Put Chute under Crushing Wheel
2.Crushing Wheel cannot import items into Chute

### Expected Result

make it work

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/47446553/155561224-164978ba-9392-4f0f-9d39-37ed299485c7.png)
![image](https://user-images.githubusercontent.com/47446553/155561286-e633aaf9-986a-4891-8964-ef7fb1c8ebec.png)
![image](https://user-images.githubusercontent.com/47446553/155561337-367728b0-dc43-4699-b1fe-3bafab5e6611.png)
![image](https://user-images.githubusercontent.com/47446553/155561370-9fffa6bf-451f-4fcd-8417-b741c47048cf.png)

### Operating System

windows10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by JieningYu** [comment]
未发现这样的问题，在最新的commit中正常。

**Comment by Dr-WeiAL** [comment]
> 未发现这样的问题，在最新的commit中正常。

我就是用的最新构建，还是有这个问题

**Comment by JieningYu** [comment]
上面箱子里凝灰岩消耗了吗？

**Comment by JieningYu** [comment]
> 上面箱子里凝灰岩消耗了吗？

如果消耗了说明粉碎凝灰岩时没掉矿粒（有概率的），粉碎圆石试试

**Comment by Dr-WeiAL** [comment]
> > 上面箱子里凝灰岩消耗了吗？
> 
> 如果消耗了说明粉碎凝灰岩时没掉矿粒（有概率的），粉碎圆石试试

情况是这样的：粉碎轮已经把输入的物品粉碎了，但是下面似乎没有识别出溜槽，就直接堵住了出口，只要打掉溜槽东西就掉出来了

**Comment by JieningYu** [comment]
> > > 上面箱子里凝灰岩消耗了吗？
> > 
> > 
> > 如果消耗了说明粉碎凝灰岩时没掉矿粒（有概率的），粉碎圆石试试
> 
> 情况是这样的：粉碎轮已经把输入的物品粉碎了，但是下面似乎没有识别出溜槽，就直接堵住了出口，只要打掉溜槽东西就掉出来了

离谱

**Comment by michlbro** [comment]
Hoppers seem to fix this issue when used to collect the items, however there is also an issue with hoppers. Usually hoppers have 4 slots (I think), which acts as a buffer so when you put more than one item it should fill up this slot. But when used to collect items in the crushing wheel, only the first slot is used so the items basically pile up on top of the hopper.
