### ISSUE TITLE
Using Deployer to apply List Filter to an object's filter slot causes immediate crash

### ISSUE THREAD

**Issue by Trey3Stone** [Fabricators-of-Create/Create#1602]
### Context

Deployers are capable of setting a filterable object's filter slot. However, trying to set that filter to an actual List Filter causes an immediate crash. Confirmed reproducible on a fresh 1.20.1 instance with no other mods. This crash does not occur in the Forge version.
![2024-09-15_14 05 11](https://github.com/user-attachments/assets/e2c93c56-b031-4f68-9c78-ce2c7eb9f3df)

### Crash Report

https://mclo.gs/DPTGcre

**Comment by IThundxr** [comment]
Fixed in https://github.com/Fabricators-of-Create/Create/commit/86ce69d5e31089a5bfb3d4dc6b31a979814970c0
