### ISSUE TITLE
schematic of death

### ISSUE THREAD

**Issue by TheRedPanda7211** [Fabricators-of-Create/Create#1606]
### Context

Randomly at any time (I have no idea what the cause is) in creative mode after having used a schematic and quill at least once the menu that allows you to change the dimensions pops up and kicks you out of any UI that you where in and when you click the Ok button the game crashed  
![image](https://github.com/user-attachments/assets/858c450e-b6ae-4d16-9a28-b01e78380387)

### Crash Report

https://mclo.gs/rC11hXd

**Comment by IThundxr** [comment]
Fixed by https://github.com/Creators-of-Create/Create/commit/2e91e169324e4b5b19193d3909c24b847da6ccab
