### ISSUE TITLE
Create can't extract fluid from cauldrons using Fabric Transfer API's CauldronStorage

### ISSUE THREAD

**Issue by Auroali** [Fabricators-of-Create/Create#1618]
### Description

The issue seems the be in [FlowSource.java](https://github.com/Fabricators-of-Create/Create/blob/76489aa1100cd19470a00e60e2e2a068811832bc/src/main/java/com/simibubi/create/content/fluids/FlowSource.java#L32), where it tries extracting an amount of 1, and [CauldronStorage.java](https://github.com/FabricMC/fabric/blob/3b9245a97679f6c58089dd803021f93d91402b29/fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/impl/transfer/fluid/CauldronStorage.java#L151) on fabric's end, where it returns an amount of 0 if the amount to be extracted is less than the amount of a single layer

### Game Log

https://mclo.gs/bjp21sC

**Comment by IThundxr** [comment]
I cannot reproduce this at all, the pumps work with cauldrons just fine

**Comment by Auroali** [comment]
it seems to work fine with vanilla cauldrons, but not ones registered exclusively using the transfer api's CauldronFluidContent#registerCauldron (like in [here](https://github.com/Auroali/sanguinis-luxuria/blob/3f696b0d9dd1c5393bd380edfd1905c07480e9f3/src/main/java/com/auroali/sanguinisluxuria/Bloodlust.java#L121))
