### ISSUE TITLE
Use convention tags

### ISSUE THREAD

**Issue by JieningYu** [Fabricators-of-Create/Create#162]
### Describe the Suggestion

No fabric mod except Create fabric use Forge tags so there’s a big compat issue between create and other fabric mods.
For example, if player use create’s mechanical press to press a brass ingot into a brass sheet, in receives c:ingots/brass but not c:brass_ingots which most fabric mods are using. So only create’s brass ingot can be pressed into brass sheet using mechanical press.
For another example, a player use a techreborn’s industrial grinder to grind a brass ingot into brass dust, but it only receives c:brass_ingots but not c:ingots/brass so only create’s brass ingot can’t grind.
To fix this problem is easy, just change items/blocks’ tags into which most fabric mods use and change recipes’ required tags into which most fabric mods use but not forge tags.
When this issue is fixed, the mod’s compatibility will be enhanced a lot.

### Additional Context

Just revert the changes from updating forge tags2.0.

**Comment by AlphaMode** [comment]
Imo we prefer forge tags layout and convention for now we are probably going to be keeping forgetags and a legacy system might be put in place later

**Comment by JieningYu** [comment]
Or a more convenient way is add all c:brass_ingots into c:ingots/brass and add all c:ingots/brass into c:brass_ingots so we can still keep forge tags system and have compatibility with other mods.

**Comment by AlphaMode** [comment]
> Or a more convenient way is add all c:brass_ingots into c:ingots/brass and add all c:ingots/brass into c:brass_ingots so we can still keep forge tags system and have compatibility with other mods.

That's what I talk about when I say legacy system

**Comment by TropheusJ** [comment]
I've merged this into #140.

**Comment by TropheusJ** [comment]
un-merged since it's the only real thing left there. Will be handled in the 1.19 update.

**Comment by JieningYu** [comment]
um.. when will Create Fabric update to 1.19? (Create Forge has already been updated to 1.19)

**Comment by maximumpower55** [comment]
Instead of commenting on a random issue, maybe ask on the discord instead next time :>

**Comment by JieningYu** [comment]
> Instead of commenting on a random issue, maybe ask on the discord instead next time :>

This issue will be handled in the 1.19 update (by TropheusJ)

**Comment by rlnt** [comment]
The issue was not handled. Create Fabric still uses the wrong tag format...

**Comment by JieningYu** [comment]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/61787533/202851159-41c3fe2c-6510-4d98-94e8-522f2882d880.png">
...yes

**Comment by rlnt** [comment]
It seems like Fabric adds the same tag style to vanilla items tho
![](https://i.imgur.com/EXisUqv.png)
So maybe that should be the convention instead and Create Fabric did the right thing here.

**Comment by JieningYu** [comment]
> It seems like Fabric adds the same tag style to vanilla items tho ![](https://camo.githubusercontent.com/4beba8d69d56588f0921809dc9a87f2cfe89d7546854828a0b5ca2f8ab8867be/68747470733a2f2f692e696d6775722e636f6d2f455869735571762e706e67) So maybe that should be the convention instead and Create Fabric did the right thing here.

No, it's Forge Tags mod by Alphamode.

**Comment by JieningYu** [comment]
In convention tags it should be `c:nether_bricks` (or `c:nether_brick_ingots`)

**Comment by TropheusJ** [comment]
Forgot about this... Soon™️
