### ISSUE TITLE
erratic chute-belt movement can cause item dupes or wipes.

### ISSUE THREAD

**Issue by freddy46** [Fabricators-of-Create/Create#1623]
### Description

![duping machine 1](https://github.com/user-attachments/assets/80c2af07-5e76-4cca-bbb6-ea05f721d2f4)
1.20.1, create 0.5.1f , no other mods present.

Requirements to cause dupe bug:
1. belts move at 128 rpm, chutes pull items upward at 32 rpm;
2. the kinetic stress source and the item moving blocks need to be separate contraptions and moved separately (though the movement in my example is identical for both contraptions);
3. move both contraptions back and forth in 8 tick intervals, at 128 rpm (at least that's what consistently caused the bug for me, it probably has more to do with the contraptions being disassembled and reassembled in a specific amount of ticks).

I haven't figured out the timing to consistently wipe items, but the steps are the same with just different timings.
in 1.18 the dupe is even easier to do, so much so that I stumbled into it.

### Game Log

https://mclo.gs/I9IXw6W

**Comment by TropheusJ** [comment]
please provide a schematic for this setup

**Comment by freddy46** [comment]
[duping_machine_1_1.zip](https://github.com/user-attachments/files/17522541/duping_machine_1_1.zip)
the pulse repeater delays that cause the bug are different depending on the version, iirc this one should work for 1.20,

**Comment by TropheusJ** [comment]
Also occurs on forge, please open an issue there.
