### ISSUE TITLE
Storage is "null" when using cobblestone generator

### ISSUE THREAD

**Issue by zevaryx** [Fabricators-of-Create/Create#1624]
### Context

I'm working on creating the Iron farm from this schematic:

https://createmod.com/schematics/ultimate-iron-farm-1300-ingot-hr

Starting this farm causes an instant crash. I'm playing the Create Extra modpack w/ a few mods added:

Sophisticated Backpacks
Sophisticated Storage
Tom's Simple Storage Mod
Trinkets
Distant Horizons

### Crash Report

https://mclo.gs/je5jOei

**Comment by IThundxr** [comment]
Try removing valkyrienskies

**Comment by zevaryx** [comment]
Yep, that fixed it! Interesting that that mod in particular causes it, since Create: Interactive depends on it
