### ISSUE TITLE
Incompatibility with Starlight

### ISSUE THREAD

**Issue by MikiP98** [Fabricators-of-Create/Create#1629]
### Context

I've enebled mechanical bearing, or I've joined a world with a enabled mechanical bearing or I've generated or world with Create Structures.

Tested versions:
- MC 1.20.1
- Starlight 1.1.2+1.20
- Create 0.5.1-f-build.1417+mc1.20.1

Error:
```
java.lang.ClassCastException: class com.simibubi.create.content.contraptions.render.ContraptionRenderDispatcher$1 cannot be cast to class net.minecraft.class_638 (com.simibubi.create.content.contraptions.render.ContraptionRenderDispatcher$1 and net.minecraft.class_638 are in unnamed module of loader 'knot' @2a2d45ba)
```
Crash Report:
[crash-2024-10-18_22.47.27-client.txt](https://github.com/user-attachments/files/17440643/crash-2024-10-18_22.47.27-client.txt)
*I know there is a lot of mods here, I don't mahe time right now to test only Starlight with Create, the possibility of this crash can at least be mentioned on the project page.*

### Crash Report

https://mclo.gs/WPVmaFD

**Comment by IThundxr** [comment]
Starlight is both abandoned and no longer needed on 1.20.1, this is already mentioned on the starlight modrinth and curseforge pages

https://gist.github.com/Spottedleaf/6cc1acdd03a9b7ac34699bf5e8f1b85c

**Comment by MikiP98** [comment]
Well, there are people that disagree: https://github.com/RelativityMC/ScalableLux  
I just want Starlight to be added as `Incompatible` on Modrinth version pages or as `breaks` inside `fabric.mod.json`

**Comment by IThundxr** [comment]
> Well, there are people that disagree: https://github.com/RelativityMC/ScalableLux I just want Starlight to be added as `Incompatible` on Modrinth version pages or as `breaks` inside `fabric.mod.json`

Report this to them so they can fix it or remove the mod.

**Comment by MikiP98** [comment]
I already removed `Starlight`, `Create` is a bigger priority, but...
...you've marked a __**Compatible**__ mod `Sound Physics Remastered` as incompatible, but you don't want to mark an actual incompatible mod as such?
Well you do you I guess...
Have a nice day!

**Comment by IThundxr** [comment]
> I already removed `Starlight`, `Create` is a bigger priority, but... ...you've marked a **Compatible** mod `Sound Physics Remastered` as incompatible, but you don't want to mark an actual incompatible mod as such? Well you do you I guess... Have a nice day!

https://github.com/henkelmax/sound-physics-remastered/issues/172 The reason SPR was marked as broken was after notifying the author of a pretty big issue that had caused many invalid bug reports to be submitted to create and create fabric.

As you can see it was later [removed](https://github.com/Fabricators-of-Create/Create/commit/b12d4d839d3b5a3bb707e4a5a75c9055f8b5f274) and then replaced with a breaks for older broken versions.

If people are willingly using a mod that even the author has said isn't really needed then that is on them.
