### ISSUE TITLE
Mechanical Bearings performance issues on dedicated server

### ISSUE THREAD

**Issue by pbone64** [Fabricators-of-Create/Create#163]
### Describe the Bug

Mechanical Bearings (possibly only in unloaded chunks? I tried to test but it wasn't conclusive) cause heavy server lag (ie TPS slowdowns) when the chunk they're in tries to unload. If one player keeps the mechanical bearing tile entities loaded this issue doesn't show up, but as soon as they're unloaded it starts to lag. Windmill bearings (possibly other create tile entities as well) may cause this issue, I haven't tested everything. I am unsure whether this to single player worlds, I noticed this on a dedicated server.

### Reproduction Steps

1. Have a Mechanical Bearing in a chunk, preferably connected to a stress network.
2. Unload the chunk. I find this shows up the most when I change dimensions
3. TPS should slow down a ton

### Expected Result

The server shouldn't die.

### Crash Report or Log

Spark Profiler: https://spark.lucko.me/v0YxhXkZPN

### Operating System

Fedora Linux (amd64)

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

https://pastebin.com/DwxdDZZc

**Comment by TropheusJ** [comment]
you have a very outdated build installed, this should have already been fixed. reopen if it persists.

**Comment by pbone64** [comment]
Issue persists on build 444 (I can't test on the latest build [448] as the refmap changes prevent the game from loading). I'd reopen the issue, but I can't if a collaborator closed it.

**Comment by TropheusJ** [comment]
please test with the latest build and provide a log.

**Comment by TropheusJ** [comment]
I can't reproduce this, reopen if it still happens.
