### ISSUE TITLE
Looking at Bulk Washing recipes crashes the game when using Create with Moderner Beta

### ISSUE THREAD

**Issue by Dogo20** [Fabricators-of-Create/Create#1632]
### Context

For some reason looking at Bulk Washing recipes through JEI can just crash the game for some reason, looked at the logs and it seems to do something with how Moderner Beta does biome tinting or something (i honestly dont know whats going on)

(I used Not Enough Crashes for the crash report, not sure if that can effect it but just wanted to mention that)

Video:

https://github.com/user-attachments/assets/c5f67aa6-d3f3-4187-bd2a-3173f291fa73

### Crash Report

https://mclo.gs/es2qF6d

**Comment by VoidLeech** [comment]
Fixed by https://github.com/BlueStaggo/moderner-beta/commit/11e2a44fb646e6e563348976f59614939f50da7e (unreleased atm)
