### ISSUE TITLE
Stockpile switcher and Sophisticated Storage bug

### ISSUE THREAD

**Issue by KrokusAstra** [Fabricators-of-Create/Create#1633]
### Description

Hi! I have a bug with Sophisticated Storage, where Stockpile Switcher doesn't recognize single-item barrel's stacksize. Even if maximum limit of the barrel is 32k resources, SS says it's full on 64 items.

Also there is a bunch of other create errors in log file which i don't know how to fix, and idk if they even need a fix

![изображение_2024-10-27_181439635](https://github.com/user-attachments/assets/dcfd4cc2-3ee9-4e16-bad5-caefb341d592)
![изображение_2024-10-27_181448810](https://github.com/user-attachments/assets/7fa42c9f-bf69-486a-8580-5189d0f04f02)

### Game Log

https://mclo.gs/NlJxU1U

**Comment by TropheusJ** [comment]
needs to be re-tested once the next patch is out, there were significant changes to the relevant code

**Comment by IThundxr** [comment]
This was tested with 0.5.1-j by me

**Comment by IThundxr** [comment]
Still broken, stack upgrades aren't accounted for correctly
