### ISSUE TITLE
Crash when display some recipes in REI

### ISSUE THREAD

**Issue by ffSupver** [Fabricators-of-Create/Create#1636]
### Context

# phenomenon :
When display some recipes in REI the game will crach .
The id of those recipes include : compacting\andesite_from_flint    compacting\diorite_from_flint   compacting\granite_from_flint
  and splashing recipes which have two output with chance .

### Crash Report

https://mclo.gs/bHkTgpe

**Comment by IThundxr** [comment]
Update create
