### ISSUE TITLE
Could not excecute entrypoint stage 'main' due to errors provided by 'create'

### ISSUE THREAD

**Issue by Ovi-dor** [Fabricators-of-Create/Create#1648]
### Context

I'm trying to make a modpack on Curseforge and I keep getting the same issue no matter what I try. I'm sure I have some redundant mods but nothing should be causing create to break

### Crash Report

https://mclo.gs/B3LZ4xR

**Comment by IThundxr** [comment]
Can you also post latest.log from your logs folder

**Comment by Ovi-dor** [comment]
https://mclo.gs/x4HB79A

**Comment by IThundxr** [comment]
Try disabling `impaled`

**Comment by Ovi-dor** [comment]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'kiwi' at 'snownee.kiwi.Kiwi'!

**Comment by Ovi-dor** [comment]
https://mclo.gs/zhr6m0T

**Comment by IThundxr** [comment]
Disable kiwi aswell then

**Comment by Ovi-dor** [comment]
That worked thank you, it was an issue that Kiwi was causing
