### ISSUE TITLE
How can I add the ability to wrench-break an item?

### ISSUE THREAD

**Issue by dzervas** [Fabricators-of-Create/Create#1649]
I want to be able to shift-wrench to break some specific blocks (storagedrawers drawer controllers and more).

I imagined it's just a tag that I can apply through a datapack but I can't find it through the code. Am I missing something?

**Comment by IThundxr** [comment]
https://github.com/Creators-of-Create/Create/wiki/Useful-Tags#block-tags `#create:wrench_pickup`
