### ISSUE TITLE
Game is crashing for some reason

### ISSUE THREAD

**Issue by Polarite** [Fabricators-of-Create/Create#165]
### Describe the Bug

I have no idea why, I just came back to my base and somehow create started crashing my game. Cant join or test anything 

### Reproduction Steps

1.
2.
3.
...

### Expected Result

Not crash

### Crash Report or Log

https://paste.ee/p/Cs13x

### Operating System

windows 11

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
Can you try redownloading the latest build? A corrupted download or broken jar is all I can think of, this error should not be possible.

**Comment by JieningYu** [comment]
Carpet mod?

**Comment by Polarite** [comment]
> Can you try redownloading the latest build? A corrupted download or broken jar is all I can think of, this error should not be possible.

I suspect its about corrupt files, I tried and didnt work, ended up using older version of my mods, no idea whats causing it

**Comment by TropheusJ** [comment]
please test with the latest build.

**Comment by TropheusJ** [comment]
Closing in favor of #187
