### ISSUE TITLE
Crash on Startup (1.20.1)

### ISSUE THREAD

**Issue by NolanHewitt** [Fabricators-of-Create/Create#1651]
### Context

Using only Create Version J Patch1 and QFAPI.
[latest.log](https://github.com/user-attachments/files/17971574/latest.log)

### Crash Report

https://mclo.gs/STHCN7p

**Comment by IThundxr** [comment]
This should be reported to QSL, Their LivingEntityMixin is absolutely horrible for compat and should entirely be redone

**Comment by OroArmor** [comment]
Yeah its a horrible mixin. https://github.com/QuiltMC/quilt-standard-libraries/pull/383 Should improve this

**Comment by NolanHewitt** [comment]
This is now fixed with the new version of QSL!
