### ISSUE TITLE
Some recipes using copper plates are crashed.

### ISSUE THREAD

**Issue by gmhan99** [Fabricators-of-Create/Create#1653]
### Description

The recipes that include copper sheets seems to be crashed.

![create mod bug report 1](https://github.com/user-attachments/assets/b315c5b0-03f9-40e6-bcce-af6046f7f947)

The code where crafting/kinetics/fluid_pipe says plates/copper and needs to be changed to copper_plates

### Game Log

https://mclo.gs/xp7ohwt

**Comment by TropheusJ** [comment]
closing in favor of #1654
