### ISSUE TITLE
funnel compatibility

### ISSUE THREAD

**Issue by Dr-WeiAL** [Fabricators-of-Create/Create#166]
### Describe the Bug

andesite funnel and brass funnel cannot import items into Cabinet Manager of Storage Cabinet
But minecraft's hopper can import 

### Reproduction Steps

There are screenshots

### Expected Result

Can it be imported?

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/47446553/156217673-0b182203-4e47-4317-ba76-6d0cfb277b7a.png)

### Operating System

windows10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

Storage Cabinet

### Additional Context

https://github.com/AshIndigo/Storage_Cabinet

**Comment by TropheusJ** [comment]
Storage Cabinet does not implement the Fabric Transfer API, this is not our issue. Report it to them.

**Comment by Dr-WeiAL** [comment]
Well, although the author doesn't seem to be around lately
