### ISSUE TITLE
Game crashes on entering Singleplayer world

### ISSUE THREAD

**Issue by avilonlegends** [Fabricators-of-Create/Create#1661]
### Context

Hi there!

I've updated to the newest version of Create on my private modpack, and the game starts as normal, but when I try to enter a singleplayer world, the game shuts down after loading for a few moments. I saw a lot of errors in the console, so I assume it's an issue with mod compatibility, but I'm not sure.

Also, the log mentions something about a parsing error for the recipe "create:pressing/compat/betterend/end_myclium_path".

Here is the latest.log (_**crash report is provided below**_):
https://mclo.gs/1oMTc3l

I'm playing on 1.20.1 Fabric.

Any idea what this could be about?
In any case, thank you!

### Crash Report

https://mclo.gs/fyLfKpa

**Comment by IThundxr** [comment]
jadeaddons has a broken mixin
