### ISSUE TITLE
Wondering if its possible to port the current 0.5.1 into 1.21

### ISSUE THREAD

**Issue by ajaxnotmeta** [Fabricators-of-Create/Create#1667]
just as title said i wonder if its possible, while we waiting the proper updates that possibly made by Create (neo)forge team on 1.21+ that possibly also brings 0.5.2 or even 0.6 where we can just skip ahead

**Comment by IThundxr** [comment]
It's possible yes, but 0.5.1 will not be getting a port to 1.21.1 as the first version available for 1.21.1 will be 0.5.2, and create fabric will not diverge from create forge as it'll cause merge conflicts later down the line

**Comment by ajaxnotmeta** [comment]
i see understandable, i guess we may get 1.22 before create(hopefully dont 🙏)
