### ISSUE TITLE
The Crushing Wheel be ruined by the water flow.

### ISSUE THREAD

**Issue by Next-Page-Vi** [Fabricators-of-Create/Create#167]
### Describe the Bug

The Crushing Wheel controller block be ruined by the water flow.

### Reproduction Steps

1.2 Crushing Wheel
2.1 Water

### Expected Result

It blocked the water flow.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/52558763/156403907-e855c8f9-976e-4280-8794-44b3aefec4bd.png)
![Uploading image.png…]()

### Operating System

Windows 11

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

		flywheel: Flywheel 1.18-0.6.1.custom
		indium: Indium 1.0.2-alpha2+mc1.18.1
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.2.4
		itemscroller: Item Scroller 0.15.0
		litematica: Litematica 0.10.1
		malilib: MaLiLib 0.11.6
		masa_gadget_mod: Masa Gadget 2.0.7-beta+343e49a
		minihud: MiniHUD 0.21.3
		modmenu: Mod Menu 3.0.1
		multiconnect-api: MultiConnect API 1.5
		ommc: Oh My Minecraft Client 0.4.1
		pca: Plusls carpet addition mod 0.2.3-alpha+20211227.002334.dirty.8044a12
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		roughlyenoughitems: Roughly Enough Items 7.2.416
		sodium: Sodium 0.4.0-alpha6+build.14
		tweakeroo: Tweakeroo 0.12.2
		xaero_map_addition: Xaero Map Addition 0.1.4
		xaerominimap: Xaero's Minimap 22.1.2
		xaeroworldmap: Xaero's World Map 1.20.1

**Comment by TropheusJ** [comment]
this is the same in forge create, so we will not be fixing it on our side.

**Comment by JieningYu** [comment]
Fixed in Forge version now.
