### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by om3ga6400** [Fabricators-of-Create/Create#1678]
### Context

when booting up the game

mods: Aquamirae
Aquamirae Mod EXTRA Music
Architectury
BCLib
BadOptimizations
Better End
Better Nether
BiomeParticleWeather
BlinkLoad
Cloth Config v11
Concurrent Chunk Management Engine
Create
Debugify
Default Skill Trees
Dungeons and Taverns
Dungeons and Taverns Ancient City Overhaul
Dungeons and Taverns Pillager Outpost Rework
Dungeons and Taverns Stronghold Rework
Dungeons and Taverns Swamp Hut Rework
Enhanced Block Entities
EntityCulling
Epic Knights Mod
Fabric API
Farmer's Delight
FerriteCore
GeckoLib 4
Geophilic
ImmediatelyFast
Immersive Aircraft
Immersive Weathering
Incendium
Krypton
Lithium
Man of Many Planes
Memory Leak Fix
ModernFix
Moog's End Structures
Moog's Nether Structures
Moog's Soaring Structures
Moog's Voyager Structures
Moonlight
More Culling
Noisium
Noxesium
Nullscape
Obscure API
Pufferfish's Attributes
Pufferfish's Skills
Reese's Sodium Options
ServerCore
Sodium
Sodium Extra
Sophisticated Backpacks
Sophisticated Core
Starlight
Tectonic
Terralith
The Graveyard
Trinkets
YUNG's API
YUNG's Better Desert Temples
YUNG's Better Dungeons
YUNG's Better End Island
YUNG's Better Jungle Temples
YUNG's Better Mineshafts
YUNG's Better Nether Fortresses
YUNG's Better Ocean Monuments
YUNG's Extras
YetAnotherConfigLib
essential-container

### Crash Report

https://mclo.gs/wycA4F7

**Comment by IThundxr** [comment]
noxesium has a bad mixin, report this to its developer(s)

**Comment by om3ga6400** [comment]
> noxesium has a bad mixin, report this to its developer(s)

just to make sure, when I remove create mod I don't crash but its actually noxesiums fault, correct?
