### ISSUE TITLE
dispensor does not shoot projectiles when moving

### ISSUE THREAD

**Issue by jihn47** [Fabricators-of-Create/Create#168]
### Describe the Bug

dispensor does not shoot projectiles(arrows,fire charges,snowballs) when moved by create related things

### Reproduction Steps

1.attatch dispensor to whatever create related mechanism that moves
2.put projectiles in dispensor
3.move(rotate) it with mechanical bearing,gantry carriage,or using cart assembler
...

### Expected Result

dispensor should shoot projectiles(arrows,snowballs etc...)

### Operating System

windows 11

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

appleskin
cloth-api
cloth-config
continuity
fabric-api
ferritecore
gamma-utils
indium
iris
item-model-fix
lazydfu
lithium
modmenu
nofog
shulkerboxtooltip
smoothboot
sodium-extra
sodium
spark
WI-Zoom
wthit
xaeros minimap and worldmap

**Comment by TropheusJ** [comment]
please test on the latest build and reopen this issue if it still happens.
