### ISSUE TITLE
Bad performance with shaders only when looking at Create machines

### ISSUE THREAD

**Issue by NVGAT** [Fabricators-of-Create/Create#1680]
### Description

I'd first like to preface this by saying that IT'S NOT A HARDWARE ISSUE - I have an Intel i9 13900 with an RTX 4080 SUPER. My frames can drop from 300 to under 20 just by looking at a Create machine.

### Game Log

https://mclo.gs/LwPkvGx

**Comment by IThundxr** [comment]
When you enable shaders create fallbacks to vanilla rendering which is inefficient compared to using flywheels instancing backend
