### ISSUE TITLE
Exit code: -1 when trying to start up a world.

### ISSUE THREAD

**Issue by JaxOfSpades21** [Fabricators-of-Create/Create#1682]
### Context

game booted up fine and i downloaded 1.20.1. I'd go onto the world, it would generate it, and right before i would load in it would crash with exit code -1. tried searching it up but couldn't find a fix.

### Crash Report

https://mclo.gs/B90g9s7

**Comment by TropheusJ** [comment]
your current versions of Create and jadeaddons are incompatible

**Comment by JaxOfSpades21** [comment]
you are a chad
