### ISSUE TITLE
1.20.1 Minecraft fails to launch when Prism Launcher is not in English

### ISSUE THREAD

**Issue by slmnemo** [Fabricators-of-Create/Create#1683]
### Context

I was attempting to open a modpack with just create, fabric, and fabric API in a german instance of multiMC. The game launches fine in english, but fails to launch in german. I'm on OpenSUSE 15.6 Leap, if that matters.

Please see crash report for more info.

### Crash Report

https://mclo.gs/YNXTaN1

**Comment by slmnemo** [comment]
Update: I have no idea what the issue is.

**Comment by TropheusJ** [comment]
it seems to be a problem with your system configuration, unrelated to Create, Minecraft, and even Java: https://stackoverflow.com/questions/32281277/too-many-open-files-failed-to-initialize-inotify-the-user-limit-on-the-total
