### ISSUE TITLE
Intermittent Server Crash

### ISSUE THREAD

**Issue by SAILQAQ** [Fabricators-of-Create/Create#1684]
### Context

The server starts normally but crashes after running for 4-5 hours, with memory usage increasing continuously.
![{94519D65-E155-409D-8D07-11B7DD9C9004}](https://github.com/user-attachments/assets/42598ed4-585c-40c1-991c-bb96a44ac3d9)
![1](https://github.com/user-attachments/assets/616d57ba-c8a6-4c85-94d4-a026baa287e5)

### Crash Report

https://mclo.gs/PiRy4bw

**Comment by IThundxr** [comment]
This is a fabric api issue, that's been fixed in 1.21 but hasn't been backported to 1.20.1 https://github.com/FabricMC/fabric/issues/3974

I'll try making a backport PR soon
