### ISSUE TITLE
Server Crashes when using book in schematicannon to get materials list

### ISSUE THREAD

**Issue by diamondstars** [Fabricators-of-Create/Create#169]
### Describe the Bug

I installed the Fabric port of Create onto my modded Minecraft server and we've been experiencing some issues, this is one of them. Judging from the crash log, this was caused by a conflict with Create and Iron Chests, may or may not affect other mods.

### Reproduction Steps

1. Get a schematic, include iron chest blocks in it, place down the schematic, put it into a cannon.
2. Get a book and place it in the cannon in an attempt to get a materials list.
3. Server crash.
...

### Expected Result

Server crashes instantly as soon as the book is placed in the cannon, it will also crash every time you load the cannon that has a book in it.

### Crash Report or Log

https://pastebin.com/YejQYMzW

### Operating System

Client: Windows 10, Server: Probably Linux

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

A list of all the fabric mods should already be in the crash log.

**Comment by AlphaMode** [comment]
This is a issue with iron chest's trying to cast are SchematicWorld to a ServerWorld when its not
please report the issue to them

**Comment by AlphaMode** [comment]
Line in question https://github.com/4nner/IronChests/blob/e1b470a1cad5fdbdb0f9d6a8d3afb7ae0f2f65ce/src/main/java/io/github/cyberanner/ironchests/blocks/blockentities/GenericChestEntity.java#L95

**Comment by diamondstars** [comment]
Thank you, I will do that.
