### ISSUE TITLE
[BUG] Cant use clicking block in ftb claims

### ISSUE THREAD

**Issue by Polarite** [Fabricators-of-Create/Create#170]
### Describe the Bug

Because how FTB chunks claims work, I cant use clicker block from create(I cant remember the name of it) and crashes the game upon placing something on a stationary contraction. Which was in my case placing saplings for automating tree farm.

### Reproduction Steps

1. Claim an area with ftb chunks
2. Try to set up an autofarm contraption which automatically plants saplings
3. Game crashes
...

### Expected Result

Not to crash

### Operating System

Windows 11

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by Polarite** [comment]
Sorry about not giving enough information, server files got removed while I was trying to report... whoops.

**Comment by JieningYu** [comment]
Give permission to Deployer?

**Comment by Polarite** [comment]
FTB chunks crashes the game when tried instantly, not like it cant place or anything

**Comment by Polarite** [comment]
if its possible to just not crash, then I can give perms

**Comment by TropheusJ** [comment]
If it crashes send a log.

**Comment by Polarite** [comment]
I will if it happens again

**Comment by TropheusJ** [comment]
please test the latest build. reopen if it happens again.
