### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by belkinark** [Fabricators-of-Create/Create#172]
### Describe the Bug

I went into my world, took a block from the create mod, put it in and got an error.

### Reproduction Steps

1. Entered the world.
2. Took the block from the create in hand.
3. Put it.
4. Crash

### Expected Result

The block had to be placed without crash.

### Screenshots and Videos

![screen 2022-03-05 122321](https://user-images.githubusercontent.com/67878832/156873370-ab4fc85c-5a8b-46f8-a9c2-1a1c603467ae.png)

### Crash Report or Log

https://bytebin.lucko.me/x3lXXiXHqE

### Operating System

Windows 11

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

additionaladditions: Additional Additions 3.0.1
additionalbars: Additional Bars 2.2.1
advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
advancementplaques: Advancement Plaques 1.4.4
advancements-enlarger: Advancements Enlarger 0.2.4
adventurez: AdventureZ 1.4.8
alloy_forgery: Alloy Forgery 2.0.9+1.18
ambientenvironment: Ambient Environment 7.0+17
amecsapi: Amecs API 1.3.3+mc1.18-pre1
antighost: AntiGhost 1.18-fabric0.43.1-1.1.4
appleskin: AppleSkin 2.3.0+mc1.18.1
architects_palette: Architect's Palette Fabric 1.6
architectury: Architectury 3.7.31
autoconfig1u: Auto Config v1 Updated 3.2.2
axolotlitemfix: Axolotl Item Fix 1.1.3
backslot: BackSlot 1.2.5
backslotaddon: BackSlot Addon 1.0.8
bclib: BCLib 1.3.4
beaconoverhaul: Beacon Overhaul 1.5.0+1.18
betterdungeons: YUNG's Better Dungeons 1.18-1.0
betterend: Better End 1.0.2
betterf3: BetterF3 1.2.2
betterfpsdist: Better FPS distance Mod 1.18-1.6
bettermounthud: Better Mount HUD 1.1.4
betternether: Better Nether 6.0.10
betterstrongholds: YUNG's Better Strongholds 1.18.1-1.0.1
betterthirdperson: Better Third Person 1.6.0
blockus: Blockus 2.3.6+1.18.1
blue_endless_jankson: jankson 1.2.1
blur: Blur (Fabric) 2.4.1
bobby: Bobby 3.1.0
borderlessmining: Borderless Mining 1.1.1+1.18
caffeineconfig: CaffeineConfig 1.0.0
capes: Capes 1.2.2+1.18
cardinal-components-base: Cardinal Components API (base) 4.1.0
cardinal-components-entity: Cardinal Components API (entities) 4.1.0
cem: Custom Entity Models 0.7.0
chat_heads: Chat Heads 0.6.0
chipped: Chipped 1.2
chisel: Chisel Refabricated 1.4.4
citresewn: CITResewn 0.9.1+1.18.1
cloth-basic-math: cloth-basic-math 0.6.0
cloth-config: Cloth Config v6 6.2.57
com_electronwill_night-config_core: core 3.6.5
com_electronwill_night-config_toml: toml 3.6.5
com_eliotlash_mclib_mclib: mclib 18
com_eliotlash_molang_molang: molang 18
com_google_code_findbugs_jsr305: jsr305 3.0.2
com_moandjiezana_toml_toml4j: toml4j 0.7.2
com_typesafe_config: config 1.4.1
com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
comforts: Comforts 1.0.2-1.18.1
completeconfig: CompleteConfig 1.3.3
confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
consistency_plus: Consistency Plus 0.5.0-RC1+1.18.1
continuity: Continuity 1.1.0+1.18
cosmetic-armor: Cosmetic Armor 1.2.1
crawl: Crawl 0.10.2
create: Create mc1.18.1_v0.4d+445
creeperoverhaul: Creeper Overhaul 0.3.0
croptopia: Croptopia 1.8.2
crowdin-translate: CrowdinTranslate 1.4+1.18
customizableelytra: Customizable Elytra 1.5.3-1.18
dawn: Dawn API 3.2.0
dragonloot: DragonLoot 1.0.10
drippyloadingscreen: Drippy Loading Screen 1.5.1
dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
dynamicfps: Dynamic FPS 2.1.0
dynview: Dynamic View Mod 1.18-1.5
earthtojavamobs: Earth2Java 1.7.4+1.18
effective: Effective 1.1
enchant_giver: Enchant Giver 1.1.0
enhancedblockentities: Enhanced Block Entities 0.5+1.18
entityculling: EntityCulling-Fabric 1.5.0
extrasounds: Extra Sounds 2.2.1+1.18.2
fabric: Fabric API 0.46.6+1.18
fabric-api-base: Fabric API Base 0.4.3+d7c144a8d2
fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
fabric-data-generation-api-v1: Fabric Data Generation API (v1) 1.0.0+3fec4ad9c8
fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.15+8906aafd65
fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.9+fb3b57b465
fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
fabricloader: Fabric Loader 0.13.3
fabrishot: Fabrishot 1.6.2
fake-player-api: Fake Player API 0.3.0
fallingleaves: Falling Leaves 1.9.0+1.18.1
fancymenu: FancyMenu 2.6.4
farmersdelight: Farmer's Delight 1.18.1-0.2.0
fastopenlinksandfolders: FastOpenResourcePacks 1.1.0
ferritecore: FerriteCore 4.1.2
fiber: fiber 0.23.0-2
firstperson: FirstpersonModel 2.1.0
flonters: Flonters 1.3.0+1.18.1
flywheel: Flywheel 1.18-0.6.1.24
forge_tags: Forge Tags 2.0
forgeconfigapiport: Forge Config API Port 3.1.1
geckolib3: Geckolib 3.0.33
go-fish: Go Fish 1.4.1-1.18.1
gobber2: Gobber2 2.5.63
harvest_scythes: Harvest Scythes 2.4.1
hologram-api: Hologram API 0.2.1+1.18-pre5
hookshot: Hookshot 24.0
iceberg: Iceberg 1.0.38
impactfulweather: Biome Particle Weather 1.3.2
indium: Indium 1.0.2-alpha3+mc1.18.1
interactic: Interactic 0.1.8+1.18
inventorysorter: Inventory Sorter 1.8.5-1.18
io_leangen_geantyref_geantyref: geantyref 1.3.11
iris: Iris 1.2.0-pre
jankson: Jankson 4.0.0+j1.2.0
java: OpenJDK 64-Bit Server VM 17
konkrete: Konkrete 1.3.3
krypton: Krypton 0.1.7
kyrptconfig: Kyrpt Config 1.3.9-1.18
lambdabettergrass: LambdaBetterGrass 1.2.2+1.17
lambdynlights: LambDynamicLights 2.1.0+1.17
languagereload: Language Reload 1.2.1
lazy-language-loader: lazy-language-loader 0.2.6
lazydfu: LazyDFU 0.1.2
legendarytooltips: Legendary Tooltips 1.2.4
libcd: LibCapableData 3.0.3+1.16.3
libgui: LibGui 5.1.0+1.18
libninepatch: LibNinePatch 1.1.0
libzoomer: LibZoomer 0.3.0+1.17.1
magna: Magna 1.7.0-1.18-pre1
mavm: More Axolotl Variants Mod 1.0.7a
mcda: MC Dungeons Armors 2.0.3
mcdw: MC Dungeons Weapons 4.2.2
mcwpaintings: Macaw's Paintings 1.0.2
mcwtrpdoors: Macaw's Trapdoors 1.0.4
medievalmusic: Medieval Music Mod 1.18-1.3
midnightlib: MidnightLib 0.3.1
milk: Milk Lib 0.1.6
minecraft: Minecraft 1.18.1
mm: Manningham Mills 2.3
mo_glass: Mo Glass 1.6.1-MC1.18.1
mobscarecrow: Mob Scarecrow 1.2.0
modmenu: Mod Menu 3.0.1
more-axolotls: More Axolotls 1.0.2
morebannerfeatures: More Banner Features 1.1.3
morechathistory: MoreChatHistory 1.1.0
mousetweaks: Mouse Tweaks 2.22
musica: Musica 1.5.0
mythicmetals: Mythic Metals 0.12.0
no-telemetry: No Telemetry 1.3.0
nofade: No Fade 1.18-2.0.1
notenoughanimations: NotEnoughAnimations 1.4.0
notenoughcrashes: Not Enough Crashes 4.1.4+1.18.1
okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
omega-config: OmegaConfig 1.0.8
org_anarres_jcpp: jcpp 1.4.14
org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
org_joml_joml: joml 1.10.2
org_quiltmc_quilt-json5: quilt-json5 1.0.0
org_slf4j_slf4j-api: slf4j-api 1.7.12
org_spongepowered_configurate-core: configurate-core 4.1.1
org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
org_spongepowered_configurate-gson: configurate-gson 4.1.1
org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
owo: oωo 0.5.2+1.18
packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
patchouli: Patchouli 1.18.1-65-FABRIC
placeholder-api: Placeholder API 1.1.3+1.17.1
polymer: Polymer (Core) 0.2.0-beta.27+1.18.1
polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-beta.27+1.18.1
pride: Pride Lib 1.1.0+1.17
pugh_lib: Pugh Lib 1.2.15
pugh_tools: Pugh Tools 1.1.17
reach-entity-attributes: Reach Entity Attributes 2.1.1
reeses-sodium-options: Reese's Sodium Options 1.4.0
registrate-fabric: Registrate for Fabric MC1.18.1-1.0.7
roughlyenoughitems: Roughly Enough Items 7.3.443
satin: Satin 1.7.0
seedfix: Seed Fix 1.0.0
server_translations_api: Server Translations API 1.4.8+1.18-pre1
sgui: sgui 1.0.0+1.18.1
shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
sit: Sit 1.18.1-16
skinlayers: 3d Skin Layers 1.4.2-mc1.18.2
smoothboot: Smooth Boot 1.18-1.7.0
sodium: Sodium 0.4.0-alpha6+build.14
sodium-extra: Sodium Extra 0.4.0
sound_physics_remastered: Sound Physics Remastered 1.18.1-1.0.4
soundcategories: Sound Categories 1.2.1+1.18
spark: spark 1.8.6
spruceui: SpruceUI 3.3.2+1.17
starlight: Starlight 1.0.0+fabric.d0a3220
stonecutter_recipe_tags: Stonecutter Recipe Tags 2.0.0
terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
terralith: Terralith for Fabric 2.0.12
tooltipfix: ToolTip Fix 1.0.4-1.18
trinkets: Trinkets 3.2.0
twigs: Twigs 1.1.2
universal-graves: Universal Graves 2.0.0-rc.5+1.18.1
universal_ores: Universal Ores 1.2.1
valley: ValleyCraft 2.2.2-1.18.1
voicechat: Simple Voice Chat 1.18.1-2.2.26
xaeroworldmap: Xaero's World Map 1.20.3.1
yosbr: YOSBR 0.1.1
yungsapi: YUNG's API 1.18-Fabric-36

**Comment by TropheusJ** [comment]
update starlight to 1.0.1.
