### ISSUE TITLE
Build 448 crash

### ISSUE THREAD

**Issue by digitaltrucker** [Fabricators-of-Create/Create#173]
### Describe the Bug

Game fails to launch with build 448.

### Reproduction Steps

1.  Update Create to build 448

### Expected Result

Successful launch

### Crash Report or Log

https://pastebin.com/x9AheeC8

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by JieningYu** [comment]
I also crashed with only fabric api.

**Comment by TropheusJ** [comment]
seems the refmap isn't being remapped properly and I have *no* idea why.

**Comment by TropheusJ** [comment]
This has been narrowed down to a loom bug involving interface injection.

**Comment by TropheusJ** [comment]
issue opened: FabricMC/fabric-mixin-compile-extensions#18
