### ISSUE TITLE
Sequenced Assembly not working

### ISSUE THREAD

**Issue by redstonerti** [Fabricators-of-Create/Create#174]
### Describe the Bug

The deployer doesn't do anything when I place it over a depot with a golden sheet while holding a small cogwheel
I am trying to make a mechanical arm but I can't without the precision mechanism

### Reproduction Steps

1. Place a depot
2. place a block on it
3. Shift place a deployer while looking down on the block
4. break the block
5. put a small cog in the deployer's hand
6. put a golden sheet in the depot
7. put a hand crank on the deployer
8. Nothing happens when you turn it
...

### Expected Result

I expected the deployer to move (I have never used sequenced assemblies before) but nothing happened. I asked in the discord if this is the correct way to do it and they said it is

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/48157961/156903020-5e816edc-a237-4a86-9917-5debaee73578.png)
![image](https://user-images.githubusercontent.com/48157961/156903027-f006e608-89b3-483d-bcef-1e6e0fd0a260.png)

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by AlphaMode** [comment]
Did you try spinning it the other way?

**Comment by redstonerti** [comment]
> Did you try spinning it the other way?

Yeah

**Comment by TropheusJ** [comment]
it was the wrong item. spot the difference. thanks indrev
![image](https://user-images.githubusercontent.com/60247969/156903345-11600e81-7c93-42e6-8c10-45f84051c3ca.png)

**Comment by redstonerti** [comment]
![image](https://user-images.githubusercontent.com/48157961/156903332-81662dda-a5b1-4120-b1f4-8f00ca26a4a5.png)
Sorry about that, it was a golen plate, not a golden sheet from industrial revolution.
They just look almost identical
Edit: didn't see the comment above

**Comment by JieningYu** [comment]
So that's why fabric create needs to enhance compatibility with other mods by editing tags
