### ISSUE TITLE
Gantry Carriages and Connected Blocks Disappear When Moving.

### ISSUE THREAD

**Issue by digitaltrucker** [Fabricators-of-Create/Create#175]
### Describe the Bug

As stated, gantry carriages and anything connected to them disappear while moving.  It's not merely visual either, I tried to ride one down and fell to my death :/

### Reproduction Steps

1.  Set up a gantry shaft and carriage assembly (vertical in my case).
2.  Power it up and move it.

### Expected Result

Assemblies shouldn't disappear.

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

	- architectury 3.7.31
	- armorposer 1.0.2
	- balm-fabric 2.4.3+0
	- beenfo 1.18.1-fabric0.45.0-1.3.3
	- blue_endless_jankson 1.2.1 via jankson
	- cardinal-components-base 4.1.3 via puzzleslib
	- cardinal-components-block 4.0.1 via polymorph
	- cardinal-components-entity 4.1.3 via puzzleslib
	- cardinal-components-item 4.0.1 via polymorph
	- cherishedworlds 2.0.1-1.18
	- chiselsandbits 1.2.82
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- collective-fabric 4.9
	- com_electronwill_night-config_core 3.6.3 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.3 via forgeconfigapiport
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- companion 1.2.1
	- completeconfig 1.3.3
	- continuity 1.1.0+1.18
	- create mc1.18.1_v0.4d+445
	- crowdin-translate 1.4+1.18 via beenfo
	- doubledoors-fabric 3.1
	- dripstone_fluid_lib 1.1.1 via milk
	- entityculling 1.5.0
	- entityoutliner 1.2.0
	- fabric 0.46.6+1.18
	- fabric-api-base 0.4.2+d7c144a865 via fabric
	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric
	- fabric-blockrenderlayer-v1 1.1.10+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.19+d7c144a865 via fabric
	- fabric-content-registries-v0 0.4.9+d7c144a865 via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric
	- fabric-data-generation-api-v1 1.0.0+3fec4ad9c8 via registrate-fabric
	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric
	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric
	- fabric-item-api-v1 1.3.1+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.7+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.9+d7c144a865 via fabric
	- fabric-keybindings-v0 0.2.7+b4f4f6cd65 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric
	- fabric-mining-level-api-v1 1.0.7+d7c144a865 via fabric
	- fabric-mining-levels-v0 0.1.12+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.4+d7c144a865 via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.5+737332ce65 via fabric
	- fabric-object-builders-v0 0.7.13+d7c144a865 via fabric
	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric
	- fabric-renderer-api-v1 0.4.11+b0b66fc365 via fabric
	- fabric-renderer-indigo 0.4.15+6825030165 via fabric
	- fabric-renderer-registries-v1 3.2.10+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.12+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.6+713c266865 via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric
	- fabric-resource-loader-v0 0.4.15+8906aafd65 via fabric
	- fabric-screen-api-v1 1.0.8+d7c144a865 via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric
	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric
	- fabric-tag-extensions-v0 1.2.9+d7c144a865 via fabric
	- fabric-textures-v0 1.0.10+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.9+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.10+c329913d65 via fabric
	- fabrication 2.3.0_01
	- fabricloader 0.13.3
	- fake-player-api 0.3.0 via create
	- fiber 0.23.0-2 via collective-fabric
	- flywheel 1.18-0.6.1.24 via create
	- forge_tags 2.0 via create
	- forgeconfigapiport 3.1.1
	- fpsdisplay 1.4.2+1.18
	- gbfabrictools 1.3.4+1.18 via beenfo
	- guardvillagers 1.0.7
	- hctm-base 3.7.0 via rswires
	- herdspanic 1.0.4
	- horsestatsvanilla 4.1.10
	- indium 1.0.2-alpha3+mc1.18.1
	- interactic 0.1.8+1.18
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- kirin 1.10.0-beta.2 via presencefootsteps
	- kiwi 5.2.5
	- lambdynlights 2.1.0+1.17
	- libaddict 0.3.0 via hctm-base
	- libcd 3.0.3+1.16.3 via skinnedlanterns
	- libgui 5.0.0-beta.2+1.18-rc1 via horsestatsvanilla
	- libninepatch 1.1.0 via libgui
	- lightoverlay 6.0.4
	- litematica 0.10.4
	- litematicatool 1.3.2
	- lithium 0.7.8
	- malilib 0.11.8
	- milk 0.1.6 via create
	- minecraft 1.18.1
	- modmenu 3.0.1
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- particlerain 2.0.0
	- phosphor 0.8.1
	- polymorph 0.0.19-1.18.1
	- presencefootsteps 1.4.0
	- pride 1.1.0+1.17 via fabrication
	- puzzleslib 3.2.1
	- qcommon-cfg-core 3.3.0 via hctm-base
	- qcommon-croco 2.1.1 via hctm-base
	- raised 1.18.1-1.0.2
	- randomblockplacement 1.18-fabric0.43.1-1.1.2
	- reach-entity-attributes 2.1.1 via create
	- registrate-fabric MC1.18.1-1.0.7 via create
	- replaymod 1.18.1-2.6.3
	- roughlyenoughitems 7.3.443
	- rswires 4.12.0
	- seasons 1.3-BETA+1.18
	- skinnedlanterns 1.2.0+build.12
	- sleepwarp 1.1.0+1.18.1
	- smoothboot 1.18-1.7.0
	- snowrealmagic 3.2.2
	- sodium 0.4.0-alpha6+build.14
	- sound_physics_remastered 1.18.1-1.0.4
	- spruceui 3.3.0+1.17 via lambdynlights
	- xaerominimapfair 22.2.0.1

### Additional Context

Using build 445.  I do use Iris, but that's not the issue since the problem persists even with Iris removed.

**Comment by TropheusJ** [comment]
please test with builds [443](https://github.com/Fabricators-of-Create/Create/actions/runs/1925918668) and [440](https://github.com/Fabricators-of-Create/Create/actions/runs/1900761838) and report back.

**Comment by digitaltrucker** [comment]
Same result with both 440 and 443.  I also tried it with build 420, but got a different result.  With build 420 the gantry carriage worked properly as long as I was looking at it while it was moving.  As soon as I looked away it disappeared, then it would reappear when I looked back.  Based on that I disabled the Entity Culling mod and continued testing various builds with the following results:

Build 424 and older - gantry carriage works perfectly without Entity Culling mod

Build 425 and newer - gantry carriage disappears completely while moving

**Comment by TropheusJ** [comment]
does this only apply to gantries?

**Comment by TropheusJ** [comment]
I can't reproduce this in latest build, can you test with create alone? if it doesn't happen, can you try to narrow down what causes it?

**Comment by digitaltrucker** [comment]
I did more testing using Build 445.  With Create alone there are no problems.  It turns out there are three mods in my load order that cause issues.  They are:

Entity Culling
Iris
Replay Mod.

Entity Culling causes the gantry to unload when I'm not actually looking at it.  This mod isn't supposed to affect Create contraptions in the Forge version although I haven't done any testing with that.

Both Iris and Replay Mod cause the gantry to disappear completely when moving.  Iris of course already has known compatibility issues, particularly with sails.  Replay Mod was surprising though.

In addition to gantires, both chassis and sails are affected.  I haven't found anything else yet.

**Comment by TropheusJ** [comment]
please test with latest build.

**Comment by digitaltrucker** [comment]
Still broken, but with one change.

With Entity Culling it no longer instantly drops the player to death, but the player's vertical position doesn't update when not looking at the gantry.  When I look at the gantry then the vertical position updates and I drop to the gantry's location..

With Replay Mod (and Iris) the issue appears to be unchanged.

**Comment by AlphaMode** [comment]
This is a issue on forge please report this to the main repo
