### ISSUE TITLE
Crash when resource pack is reloaded / Entity is reloaded

### ISSUE THREAD

**Issue by aria1th** [Fabricators-of-Create/Create#176]
### Describe the Bug

Build any simple contraption.
Reload resource pack with F3+T or change render distance.
Then it crashes.

### Reproduction Steps

1.Build any simple contraption.
2. F3+T (or change Render Distance)

### Expected Result

It should reload entity and render.

### Crash Report or Log

https://bytebin.lucko.me/KXnZWlX9oG

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

FlyWheel
Sodium + Indium + IRIS + Continuity (seems not related)

### Additional Context

https://github.com/Jozufozu/Flywheel/issues/116
I think its flywheel's bug, but not sure.

**Comment by TropheusJ** [comment]
Iris issue, please test with 1.2.1.

**Comment by TropheusJ** [comment]
1.2.1 is 1.18.2 only, so nevermind. This issue is known and a fix will be available eventually.
