### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by SkyTheNerd** [Fabricators-of-Create/Create#180]
### Describe the Bug

When I launch the game, it instantly crashes with exit code 1.

### Reproduction Steps

1. Launch the game
2. Watch it crash.

### Expected Result

The game starts up normally.

### Crash Report or Log

https://pastebin.com/zcry6sha

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18

### Other Mods

Fabric API

### Additional Context

I was using 1.18.2.

**Comment by AlphaMode** [comment]
Please use 1.18.1
