### ISSUE TITLE
Dedicated server not connecting at all

### ISSUE THREAD

**Issue by Syncinus** [Fabricators-of-Create/Create#182]
### Describe the Bug

I have made a dedicated server and a client with just the Create mod, it seems that with it I am unable to connect to the server, however if I remove the Create mod from both I am able to connect to the server (and with any of the other mods I use). I am on the latest build 0.4.0d+254

I see no errors on either side and I do in fact connect, however as soon as I connect I am immediately disconnected. 

### Reproduction Steps

1. Set up a dedicated server with Fabric API and Create
2. Make a client instance with Fabric API and Create
3. Join the server (an easy way to do this without port forwarding is to use ngrok https://ngrok.com/)
4. The client should go through all steps up to "Joining world.." until it abruptluy goes to a screen saying "Connection Lost"

### Expected Result

I am able to properly connect to the server and play.

### Screenshots and Videos

https://user-images.githubusercontent.com/34169172/157367912-c1da0227-da0c-4a33-99d6-faaa5ba93487.mp4

### Crash Report or Log

Server: https://pastebin.com/0g72W6NH Client: https://pastebin.com/B3matCTZ

### Operating System

Linux (NixOS)

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

Fabric API 0.46.4+1.18 (server & client)

**Comment by TropheusJ** [comment]
Please install [WDMNF](https://github.com/Tom-The-Geek/WDMNF/releases/tag/v1.1.0%2Bsnapshots) on both server and client, try again, and send both new logs.

**Comment by Syncinus** [comment]
https://pastebin.com/ygCWdM8K

WDMNF doesn't seem to work on it. I think because 22w07a is for 1.18.2 which (from what I know) is incompatible with 1.18.1 which is what Create is using.

**Comment by Syncinus** [comment]
Okay it appears the 1.17 version worked (probably because 1.18.1 still uses Log4J but 1.18.2 uses SLF4J) so here are the server and client logs:

Updated server log: https://pastebin.com/4dTzMY2q
Update client log: https://controlc.com/3ab1eaa8 (pastebin kept deleting my log for some reason)

**Comment by Polarite** [comment]
still happening with latest build

**Comment by Syncinus** [comment]
OK I have manually built from source (I am trying to make a PR to fix this)

Here is a better quality (non-obfuscated) log of the error: https://pastebin.com/h5HgBHV2

**Comment by TropheusJ** [comment]
[potential_fix.zip](https://github.com/Fabricators-of-Create/Create/files/8240445/potential_fix.zip)
This jar has a modified port lib jar. Add this to your mods on client and server and test. This will be broken in many other ways, I removed some possibly problematic code, so don't use it on anything important. Provide logs after.

**Comment by Syncinus** [comment]
Okay I think I got it to be the used porting_lib (I am using ``modImplementation files("../porting_lib-0.2.0-interfacent+1.18-interfacent.cfd1087.jar")`` to import it and I am doing a custom build off of the source). I still can not connect, here is the log it is giving me: https://pastebin.com/PjVXs9GW

**Comment by TropheusJ** [comment]
can you provide a full log?

**Comment by Syncinus** [comment]
Client: https://pastebin.com/NrhSL5w4
Server: https://pastebin.com/nmTXxH0u
(Server has `online-mode` turned off so I can connect to it to the local project)

**Comment by DirtyNative** [comment]
This exact same thing happens to me as well. Any news here?

**Comment by TropheusJ** [comment]
this might be related to #194, but I have zero ideas for either issue.

**Comment by DirtyNative** [comment]
Well I can tell this happens on a new fabric server, only the Fabric Api and create mod installed.
When I create a singleplayer world, it works as expected.

**Comment by DirtyNative** [comment]
A little addition: The same error occurs, when only the client has the mod installed and it's trying to connect to the server. I would expect a mod mismatch error, but instead the client disconnects immediately. Maybe this helps finding a solution

**Comment by TropheusJ** [comment]
This appears to be a local server issue only: #213

**Comment by StockiesLad** [comment]
Add Priority to this thread because this is a fairly serious issue

**Comment by Kevinello** [comment]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/56342249/159120078-dc8ea637-6908-4689-85f6-bcbfba8482ac.png">
have the same issue on my create-mod-only server as well

**Comment by drakes00** [comment]
> This appears to be a local server issue only: #213

I don't think it is only localhost server issue.
I have the same problem with my client being on my laptop and the create server being on a dedicated station.

**Comment by TropheusJ** [comment]
Is it on the same network as the client?

**Comment by Kevinello** [comment]
> Is it on the same network as the client?

nope
my mc server is deployed on my cloud server with a public IP

**Comment by TropheusJ** [comment]
> Client: https://pastebin.com/NrhSL5w4
> Server: https://pastebin.com/nmTXxH0u
> (Server has `online-mode` turned off so I can connect to it to the local project)

This client log has been removed, can someone provide a new one?

**Comment by drakes00** [comment]
> > Is it on the same network as the client?
> 
> nope my mc server is deployed on my cloud server with a public IP

Same here


> [potential_fix.zip](https://github.com/Fabricators-of-Create/Create/files/8240445/potential_fix.zip) This jar has a modified port lib jar. Add this to your mods on client and server and test. This will be broken in many other ways, I removed some possibly problematic code, so don't use it on anything important. Provide logs after.

Currently not tested with this fix BTW, should it be used?

**Comment by TropheusJ** [comment]
It probably won’t matter but there’s no harm in it

**Comment by drakes00** [comment]
I'm having issues launching with WDMNF, is it a mod you drop in the 'mods' folder?

> Yes. Make sure you use the 1.17 version.

My bad, going to

**Comment by TropheusJ** [comment]
Yes. Make sure you use the 1.17 version.

**Comment by drakes00** [comment]
> > Client: https://pastebin.com/NrhSL5w4
> > Server: https://pastebin.com/nmTXxH0u
> > (Server has `online-mode` turned off so I can connect to it to the local project)
> 
> This client log has been removed, can someone provide a new one?

Okay, personally I barely got any special logs, hope it helps :(
Server: https://gist.github.com/drakes00/8921120361ab86e0ab0d775356d2c0b3
Client: https://gist.github.com/drakes00/5814767c03531fa992311ba64ec9e44a

I'm surprised I didn't got the special character related error someone had up there

**Comment by Blightbuster** [comment]
Is there anything needed to assist with solving this issue?

**Comment by drakes00** [comment]
> Is there anything needed to assist with solving this issue?

I personally have no idea on how to solve this but I can help providing feedback if it helps :(

**Comment by StockiesLad** [comment]
I'm inclined to believe that create (when on the server) possibly doesn't register probably like 1 line of code correctly and doesn't sync correctly or another way around. Or perhaps a remnant piece of code was leftover from an old syncing system and interferes with server-client compatibility. My idea is that there is no syncing because maybe 1 block doesn't register in either the client or the server and due to undeveloped logging, it is impossible to find what block/entity is causing the issue.
Idk I'm just throwing out random ideas to see if it might help to solve this issue.

**Comment by DirtyNative** [comment]
I am using the Build 441 now, because I have read that this is the most stable one. It works for me, also with connecting to the server. Maybe this helps finding the problem

**Comment by XionioXMaster** [comment]
Same

**Comment by Blightbuster** [comment]
I narrowed the issue down to a commit after `e4c7c73` up to `b5fc151` in Porting-Lib.
