### ISSUE TITLE
Nerf cart based contraptions

### ISSUE THREAD

**Issue by aria1th** [Fabricators-of-Create/Create#183]
### Describe the Suggestion

Now Cart can attach 100,000 blocks and assemble, then do anything same as contraptions. But its based on furnace minecart, and does not require fuel to 'work'. It only consumes fuel when it need to move forward, which can be just solved by pushing with other cart / or powered rail / boat cart....etc.

Its basically just infinite non-stress based overpowered contraption, which does not calculate stress, or fuel consumption, anything. You can easily build giant drill-attached cart instead of stationary drills that breaks cobblestone.

Automating process is good, but these tweaks are too powerful to exist. There's no config to limit cart attached blocks, nor ways to count stress-related objects in cart.

**Comment by AlphaMode** [comment]
Please make a issue upstream about this as we will not make any major changes to the code that upstream doesn't make
