### ISSUE TITLE
Vault and hopper losing items

### ISSUE THREAD

**Issue by WhyDontULuvCats** [Fabricators-of-Create/Create#185]
### Describe the Bug

Hopper placed under a vault receives only a part of items (Usually half*) Nothing is left in the vault. 

### Reproduction Steps

1. Place a hopper
2. Place a vault on top of the hopper
3. Place a funnel (andesite or brass) facing the vault
4. Right click the funnel holding 9 items of any type
5. Open the hopper. Just 5 items
6. Break the vault to make sure there is no items stuck in it

OR

1. Place a hopper
2. Place a vault on top of the hopper
3 Place a brass funnel facing the vault
4. Place a belt heading in the funnel and power it
5. Place a chest before the belt diagonally up 1 block
6. Add a brass funnel between the chest and the belt
7. Drag 9 items of any type in the chest.
8. Open the hopper. Just 5 items
9. Break the vault to make sure there is no items stuck in it
...

### Expected Result

To see 9 items in the hopper

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/101272527/157593070-ce94a8cc-53b2-4456-aed4-369d59d97660.png)

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Additional Context

*When items are inserted one by one, the amount of lost items depends on insertion speed. Insert fast, lose at most half the items. Insert slower to lose less. Insert really slow to not lose any items at all

**Comment by TropheusJ** [comment]
Can you test with [this build](https://github.com/Fabricators-of-Create/Create/actions/runs/1955061165)?

**Comment by WhyDontULuvCats** [comment]
> Can you test with [this build](https://github.com/Fabricators-of-Create/Create/actions/runs/1955061165)?

Same issue

**Comment by TropheusJ** [comment]
fixed in [af66eba](https://github.com/Fabricators-of-Create/Create/commit/af66eba28d168593e6c92d06e57815ad753a4f10)
