### ISSUE TITLE
Crashes when entering the world

### ISSUE THREAD

**Issue by eoNaho** [Fabricators-of-Create/Create#186]
### Describe the Bug

Upon entering the world, the game simply crashes and closes 

### Reproduction Steps

Just enter a world 

### Expected Result

Enter the world without Crashes

### Crash Report or Log

https://gist.github.com/Naho-sama/00f05318ea271f748e75a411f5a05d49

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

                additionaladditions: Additional Additions 3.0.1
		adorn: Adorn 3.3.1+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.7
		advancednetherite: Advanced Netherite 1.4.0-1.18.1
		advancementplaques: Advancement Plaques 1.4.4
		adventurez: AdventureZ 1.4.7
		alloy_forgery: Alloy Forgery 2.0.9+1.18
		amplified_nether: Amplified Nether for Fabric 1.0.1
		architectury: Architectury 3.7.26
		armoredelytra: Armored Elytra 3.0.2
		artifacts: Artifacts 6.0.0+fabric
		artifality: Artifality 0.5.5
		attributefix: AttributeFix 13.0.5
		awesomedungeon: Awesome Dungeon 2.0.4
		bclib: BCLib 1.3.4
		betterend: Better End 1.0.2
		betterfpsdist: Better FPS distance Mod 1.18-1.7
		betternether: Better Nether 6.0.10
		bitsandchisels: BitsAndChisels 2.6.4
		blockus: Blockus 2.3.4+1.18.1
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.1
		botania: Botania 1.18.1-429-FABRIC
		breakprogress: Break Progress 1.0.1
		caffeineconfig: CaffeineConfig 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		charm: Charm 4.0.0
		chipped: Chipped 1.2
		chisel: Chisel Refabricated 1.4.4
		citresewn: CITResewn 0.9.1+1.18.1
		cleancut: CleanCut 1.18-4.0-fabric
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		cloth-config-lite: cloth-config-lite 2.0.6
		clumps: Clumps 8.0.0+5
		collective-fabric: Collective (Fabric) 4.9
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_llamalad7_mixinextras: MixinExtras 0.0.6
		com_google_code_findbugs_jsr305: jsr305 3.0.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		conjuring: Conjuring 1.0.20+1.18
		continuity: Continuity 1.1.0+1.18
		controlling: Controlling For Fabric 9.0+15
		crawl: Crawl 0.10.2
		create: Create mc1.18.1_v0.4d
		creeperoverhaul: Creeper Overhaul 0.3.0
		cullleaves: Cull Leaves 2.3.2
		customportalapi: Custom Portal Api 0.0.1-beta47-1.18
		dashloader: DashLoader 3.0-rc14-1.18
		dataattributes: Data Attributes 1.1.5
		decorative_blocks: Decorative Blocks 2.0.4
		deepslatecutting: Deepslate Cutting 1.3.1
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.1
		dev_quantumfusion_hyphen: hyphen 0.1
		diggusmaximus: Diggus Maximus 1.5.2-1.18
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		doubledoors-fabric: Double Doors (Fabric) 3.1
		dragonloot: DragonLoot 1.0.10
		dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dynamicfps: Dynamic FPS 2.1.0
		dynview: Dynamic View Mod 1.18-1.5
		earthbounds: Earthbounds 1.0.5b
		easiervillagertrading: EasierVillagerTrading 1.18-fabric0.43.1-1.5.4
		eatinganimationid: Eating Animation 1.5
		effective: Effective 1.1
		elevator233: squid233's Elevator 0.2.0-no-blocks
		enchant_giver: Enchant Giver 1.1.0
		endrem: End Remastered 5.0.0
		entityculling: EntityCulling-Fabric 1.5.0
		equipmentcompare: Equipment Compare 1.2.11
		expandability: ExpandAbility 5.0.0
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.2
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.0.2
		fabric: Fabric API 0.46.6+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 1.0.0+3fec4ad9c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-furnaces: Fabric Furnaces 2.1.0-1.18.1
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.15+8906aafd65
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.9+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
		fabricloader: Fabric Loader 0.13.3
		fake-player-api: Fake Player API 0.3.0
		fallingleaves: Falling Leaves 1.9.0+1.18.1
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 1.0.1+1.18.1
		ferritecore: FerriteCore 4.1.2
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 1.7.1
		flywheel: Flywheel 1.18-0.6.1.24
		forge_tags: Forge Tags 2.0
		forgeconfigapiport: Forge Config API Port 3.1.1
		fuelinfo: FuelInfo 1.0-SNAPSHOT
		gbfabrictools: GBfabrictools 1.3.4+1.18
		geckolib3: Geckolib 3.0.33
		goosik-config: goosik-config 0.2.0
		graveyard: The Graveyard 1.5
		guild: Guild 0.3.8
		horseinfo: Horse Info 0.4.1-1.18
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		iceberg: Iceberg 1.0.38
		indium: Indium 1.0.2-alpha3+mc1.18.1
		indrev: Industrial Revolution 1.13.6-BETA
		io_airlift_aircompressor: aircompressor 0.21
		iris: Iris 1.2.0-pre
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kirin: Kirin UI 1.10.0-beta.2
		kyrptconfig: Kyrpt Config 1.2.4-1.18
		lambdabettergrass: LambdaBetterGrass 1.2.2+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazy-language-loader: lazy-language-loader 0.2.6
		legendarytooltips: Legendary Tooltips 1.2.4
		libblockattributes_core: LibBlockAttributes (Core) 0.10.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
		libblockattributes_items: LibBlockAttributes (Items) 0.10.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		libraryferret: Library Ferret 1.0.3
		libzoomer: LibZoomer 0.3.0+1.17.1
		lightoverlay: Light Overlay 6.0.4
		litematica: Litematica 0.10.2
		lithium: Lithium 0.7.8
		lootcrates: Modular Loot Crates 2.7.0-1.18.1
		magna: Magna 1.7.0-1.18-pre1
		malilib: MaLiLib 0.11.7
		mannequins: Mannequins 2.0.0
		maybe-data: Maybe data 1.0.1-1.17
		maybe-more-data: Maybe More Data 1.0.0-1.18.1
		mcwfences: Macaw's Fences and Walls 1.0.4
		mcwlights: Macaw's Lights and Lamps 1.0.2
		mcwpaintings: Macaw's Paintings 1.0.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.4
		megane: megane 7.1.3
		megane-api: megane-api 7.0.0
		megane-fabric-transfer: megane-fabric-transfer 7.0.0
		megane-industrial-revolution: megane-industrial-revolution 7.0.0
		megane-lib-block-attributes: megane-lib-block-attributes 7.0.0
		megane-reborn-core: megane-reborn-core 7.0.0
		megane-reborn-energy: megane-reborn-energy 7.0.0
		megane-runtime: megane-runtime 7.1.3
		megane-tech-reborn: megane-tech-reborn 7.0.0
		megane-vanilla: megane-vanilla 7.0.0
		midnightlib: MidnightLib 0.3.1
		milk: Milk Lib 0.1.6
		minecraft: Minecraft 1.18.1
		mining_dims: Mining Dimensions 1.3.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		mousetweaks: Mouse Tweaks 2.22
		mythic-mounts: Mythic Mounts 1.18-4.0
		mythicmetals: Mythic Metals 0.11.4
		naturescompass: Nature's Compass 1.18.1-2.0.2-fabric
		net_objecthunter_exp4j: exp4j 0.4.8
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.1
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		omega-config: OmegaConfig 1.2.3-1.18.1
		omega-config-gui: Omega Config GUI 1.2.1-1.18.1
		opc: Offline Player Cache 0.0.1
		org_anarres_jcpp: jcpp 1.4.14
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		owo: oωo 0.5.2+1.18
		patchouli: Patchouli 1.18.1-65-FABRIC
		phosphor: Phosphor 0.8.1
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.5.0
		playerex: PlayerEx 3.1.4
		pollen: Pollen 1.1.1
		polymorph: Polymorph 0.0.19-1.18.1
		porting_lib: Porting Lib 0.1.0-interfacent+1.18-interfacent.437f82b
		presencefootsteps: Presence Footsteps 1.4.0
		pride: Pride Lib 1.1.0+1.17
		pugh_lib: Pugh Lib 1.2.15
		puzzleslib: Puzzles Lib 3.2.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.1.0
		reeses-sodium-options: Reese's Sodium Options 1.4.0
		registrate-fabric: Registrate for Fabric MC1.18.1-1.0.7
		repurposed_structures: Repurposed Structures 3.3.12+1.18.1
		reroll: Reroll 1.4.0-1.18.1
		ringsofascension: Rings of Ascension 1.0
		roughlyenoughitems: Roughly Enough Items 7.3.435
		roughlyenoughresources: Roughly Enough Resources 2.4.1
		satin: Satin 1.7.0
		seedfix: Seed Fix 1.0.0
		simple_cobblestone_generator: Simple cobblestone generator 1.1.7
		slime_sling: SlimeSling 1.0.0
		smoothboot: Smooth Boot 1.18-1.7.0
		soaringstructures2: Soaring Structures 2 1.18 - 2.2
		sodium: Sodium 0.4.0-alpha6+build.14
		sodium-extra: Sodium Extra 0.4.0
		spruceui: SpruceUI 3.3.2+1.17
		stacc: Stacc 1.2.3
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.4.2
		team_reborn_energy: Energy 2.2.0
		techreborn: Tech Reborn 5.1.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		things: Things 0.2.14+1.18
		toms_storage: Tom's Simple Storage Mod 1.1.19
		toolstats: ToolStats 8.0.3
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		travelersbackpack: Traveler's Backpack 1.18.1-7.0.0
		trinkets: Trinkets 3.2.0
		urns: Urns 1.0.1
		vanilla-hammers: Vanilla Hammers 3.2.0-1.18.1
		vanillaexcavators: Vanilla Excavators 1.1.0
		visuality: Visuality 0.4.1
		visualworkbench: Visual Workbench 3.1.0
		waystones: Waystones 2.4.1
		wthit: wthit 4.5.4
		xaerominimap: Xaero's Minimap 22.2.0.1
		xaeroworldmap: Xaero's World Map 1.20.3.1

**Comment by TropheusJ** [comment]
Remove iris or disable flywheel.

**Comment by poisson-fish** [comment]
this issue is caused likely by an incompatibility between data attributes and create, issue [here](https://github.com/CleverNucleus/Data-Attributes/issues/15)

**Comment by TropheusJ** [comment]
This issue has been resolved for 4 months, and was a problem with flywheel and iris. Make a new issue for data attributes.
