### ISSUE TITLE
Game crashing when trying to render create blocks with sodium

### ISSUE THREAD

**Issue by Exotik850** [Fabricators-of-Create/Create#187]
### Describe the Bug

On game loading into a world, runs fine until placing a block from create, crashing the game

### Reproduction Steps

1. Install both sodium and create 
2. Load into a world
3. Place a block from create

### Expected Result

Placing the block without crash 

### Crash Report or Log

https://pastebin.com/RHBBk6Zc

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

Sodium

**Comment by TropheusJ** [comment]
this seems to have been fixed at some point.

**Comment by AlphaMode** [comment]
This is not fixed

**Comment by AlphaMode** [comment]
Issue seems to be a issue with Indium not sodium

**Comment by TropheusJ** [comment]
using sodium and indium, it works perfect for me in both dev and prod.

**Comment by AlphaMode** [comment]
This is a problem with indium remapping in dev false alarm
