### ISSUE TITLE
Eta on 1.18.2 build?

### ISSUE THREAD

**Issue by redstonerti** [Fabricators-of-Create/Create#188]
Sorry for asking, but we use terallith in our server and structures don't work in 1.18.1. Out of the 181 mods, we are waiting on create.
I know it is not even supposed to be playable yet.

**Comment by TropheusJ** [comment]
We are waiting on upstream which is waiting on flywheel and registrate. No ETAs.

**Comment by redstonerti** [comment]
Fair enough 👍

**Comment by JieningYu** [comment]
have one now

**Comment by StockiesLad** [comment]
Close this thread lol
