### ISSUE TITLE
Shafts render incorrectly with Sodium 

### ISSUE THREAD

**Issue by Blightbuster** [Fabricators-of-Create/Create#189]
### Describe the Bug

When using sodium shafts base model is rendered on top of the animated model which results in z fighting.
Possibly related to #187 

### Reproduction Steps

1. Go into a world
2. Place a shaft

### Expected Result

Shaft looks normal as when not using sodium

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/24388294/157763691-df45fafa-b38a-42d8-9660-73fd2c81ead5.png)

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar

**Comment by TropheusJ** [comment]
install indium.
