### ISSUE TITLE
I cant compile it

### ISSUE THREAD

**Issue by BeanBeingABean** [Fabricators-of-Create/Create#19]
I just cant compile it

1. Be me 
2. Try to compile
3. No work
4. h o w

i expected it to compile

**_im a idiot_**

**Comment by TropheusJ** [comment]
The mod currently is not compileable outside of the dev env, and this will probably stay this way until we get rid of our unholy mappings system, which should happen once upstream switches to mojmap.

**Comment by IMS212** [comment]
troll

**Comment by BeanBeingABean** [comment]
> The mod currently is not compileable outside of the dev env, and this will probably stay this way until we get rid of our unholy mappings system, which should happen once upstream switches to mojmap.

i understood 10% of that

**Comment by BeanBeingABean** [comment]
thanks for the answer tho

**Comment by IMS212** [comment]
weirdcamp
