### ISSUE TITLE
cannot transfer to non-Create storages

### ISSUE THREAD

**Issue by TropheusJ** [Fabricators-of-Create/Create#191]

**Comment by digitaltrucker** [comment]
I can confirm.  Updating to build 459 broke my fan+chute ore loader system on a furnace engine.  The ore no longer drops back into the furnace when the power runs out.  Works fine in build 455.

**Comment by TropheusJ** [comment]
should be fixed in [build 482](https://github.com/Fabricators-of-Create/Create/actions/runs/2084568820) or newer.
