### ISSUE TITLE
Minecart couplings don't really exist anymore

### ISSUE THREAD

**Issue by TropheusJ** [Fabricators-of-Create/Create#192]

**Comment by digitaltrucker** [comment]
What do you mean?  They're still present in build 455, they just don't appear to have hitboxes.

**Comment by TropheusJ** [comment]
On 459 at least, they aren’t visible on my client anymore. Will look into it more tomorrow.

**Comment by digitaltrucker** [comment]
I just updated to build 459, and existing couplings disappeared.  Replacing them with new ones works as expected.
