### ISSUE TITLE
Game not starting on latest build

### ISSUE THREAD

**Issue by Syncinus** [Fabricators-of-Create/Create#196]
### Describe the Bug

The game crashes immediately on startup on build v0.4d+449

### Reproduction Steps

1. Start the game
2. Game crashes

### Expected Result

The game opens and runs properly

### Screenshots and Videos

https://user-images.githubusercontent.com/34169172/158001552-f894e010-156c-4c01-b848-16061ff6efcf.mp4

### Crash Report or Log

https://pastebin.com/f3jWg7DC

### Operating System

Linux (NixOS)

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

Fabric API 0.46.6+1.18
Why Did My Netty Fail 1.0.0+mc1.17 (MC 1.18 uses Log4J so the 1.17 version works fine)

**Comment by TropheusJ** [comment]
449 is not the latest build. Update.

**Comment by Syncinus** [comment]
Yeah sorry I just realized I was on 449 instead of 459 (currently 460), sorry about that.
