### ISSUE TITLE
Some Recipes Don't Show With REI

### ISSUE THREAD

**Issue by digitaltrucker** [Fabricators-of-Create/Create#197]
### Describe the Bug

Flywheel and Furnace Engine recipes don't show with REI.  I don't know how many recipes are broken but it's not all of them.  Instead of the recipes, REI shows the message "Failed to initiate setupDisplay - Check console for error"

### Reproduction Steps

1.  Open a crafting menu
2.  Try to see the recipe for a flywheel

### Expected Result

See the recipes.

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

REI

### Additional Context

Build 360.  I don't know when they broke, they used to work.  I don't even know if it's on REI or Create's end.

**Comment by JieningYu** [comment]
Dupe of https://github.com/Fabricators-of-Create/Create/issues/190

**Comment by digitaltrucker** [comment]
Oops, sorry.
