### ISSUE TITLE
Drain fails to interact with other containers using Fabric Transfer API, crashing the world

### ISSUE THREAD

**Issue by Neubulae** [Fabricators-of-Create/Create#198]
### Describe the Bug

Trying to transfer multiple items to a drain crashes the game

### Reproduction Steps

1. Place a drain in the world
2.	Connect it to an item pipe from other mods, for instance an IndRev item pipe
3. Insert multiple things
4. the game perishes in silence oh no

### Expected Result

Things don't go wrong and if multiple buckets are inserted, bucket should pop off

### Crash Report or Log

https://paste.gg/p/anonymous/682b158290484ee3ba5367f20931d560

### Operating System

Arch Linux

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

indrev, ae2, modern industrialization are the best candidates to test the aformentioned behavior

**Comment by TropheusJ** [comment]
Please test this on [build 482](https://github.com/Fabricators-of-Create/Create/actions/runs/2084568820) or newer. If this issue still occurs, please re-open it.
