### ISSUE TITLE
Placing a hose pulley on the side of another hose pulley crashes the game

### ISSUE THREAD

**Issue by Syncinus** [Fabricators-of-Create/Create#204]
### Describe the Bug

Placing a hose pulley on the side of another hose pulley, specifically the side with the tubing on it, will crash the game

### Reproduction Steps

1. Place a hose pulley on the side of another hose pulley

### Expected Result

The game does not crash

### Screenshots and Videos

https://user-images.githubusercontent.com/34169172/158088139-7aa5e6b5-972e-4015-a1df-a48a88be4ff8.mp4

### Crash Report or Log

https://pastebin.com/5TyESr1V

### Operating System

Linux (NixOS)

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

Fabric API 0.46.6
Chipped 1.2

### Additional Context

Build is the latest code built from source (no errors on build)

**Comment by TropheusJ** [comment]
Please test this on [build 482](https://github.com/Fabricators-of-Create/Create/actions/runs/2084568820) or newer. If this issue still occurs, please re-open it.

**Comment by Syncinus** [comment]
Happy to say it no longer happens when on build 482
