### ISSUE TITLE
Transfer is in a very sorry state right now

### ISSUE THREAD

**Issue by TropheusJ** [Fabricators-of-Create/Create#205]
Everything transfer is kinda busted - see #204, #191, #178.
Stuff used to work somewhat, but was very unstable and performance heavy.
I tried adding some caching, but that broke everything because FAPI's `getVersion` isn't actually implimented.
I plan to redo all of transfer in the near future, directly interfacing with FAPI. That will be a lot of work though and will take a bit.

**Comment by Neubulae** [comment]
:waaaaagh_perish:

**Comment by Polarite** [comment]
Use 441th build for now, its the most stable build so far.

**Comment by TropheusJ** [comment]
[branch has been created.](https://github.com/Fabricators-of-Create/Create/tree/mc1.18/fabric/transfer-redo)
300 errors that need to be rewritten, this will take a bit. Afterwards a lot of testing will be needed. In the meantime, 441 works.

**Comment by TropheusJ** [comment]
see #226
