### ISSUE TITLE
[Bits and Chisels] rope pulley with default empty collision box can destroy any blocks below when extending

### ISSUE THREAD

**Issue by aria1th** [Fabricators-of-Create/Create#206]
### Describe the Bug

Bit collection block has no default collision from its state, but its last block of the pulley, which makes collision check empty and extend even if block was there.

### Reproduction Steps

put "bit collection block" below rope pulley and extend it .
It breaks everything below and extends.

### Expected Result

It should stop extending. Can be solved by adding this line:
				`if (info.state.hasBlockEntity()){
					cachedColliders.add(info.pos);
					continue;
				}`

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

https://github.com/CoolMineman/BitsAndChisels

### Additional Context

This is occured from TranslatingContraption.getColliders, it does not return anything because **bit block's default collision shape is Empty.**
` info.state.getCollisionShape(world, offsetPos)`

**Comment by TropheusJ** [comment]
This is likely an issue on forge as well, could you test there with chisel and bits?

**Comment by aria1th** [comment]
It says "Unmovable block (Chiseled Rock) in [X Y Z]", so likely its only in fabric

**Comment by TropheusJ** [comment]
so chisel and bits blocks can't be moved with contraptions on forge?

**Comment by TropheusJ** [comment]
after some testing, this is because on forge, bit blocks have an unmovable piston push reaction. I will add them to the immovable tag on fabric.
