### ISSUE TITLE
Incompatibility with anti xray

### ISSUE THREAD

**Issue by redstonerti** [Fabricators-of-Create/Create#207]
### Describe the Bug

Schematics that have blocks that aren't visible from any side are turned into ores with the anti xray mod if it is installed on your server. The ores are saved into the schematic too. I don't know how easily or if this is fixable, but it would be really nice to see a collaboration with https://github.com/DrexHD/AntiXray in order to get this fixed.

### Reproduction Steps

Download create and anti xray on a server and try to make a schematic with blocks that aren't visible on any side
Does not work in singleplayer

### Expected Result

I expect the schematics to save the real blocks, not whatever fake blocks anti xray sends

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/48157961/158188585-c1fdf584-6cb2-40cf-bf17-7e1b54e11be2.png)

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
While this isn’t intended we probably won’t fix it. schematics could be used to extract parts of the world and look through to them, effectively X-ray. If you’re worried about your users cheating, this is probably for the best.
