### ISSUE TITLE
Some weirdness with LamdDynamicLights

### ISSUE THREAD

**Issue by redstonerti** [Fabricators-of-Create/Create#208]
### Describe the Bug

The drill bit of drills and the hand of deployers remain unlit while the rest of the block is lit. I don't know who's fault this is so i'm posting it on both githubs

### Reproduction Steps

get in a dark room
hold a torch
look at a drill

### Expected Result

I expected the whole block to be lit

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/48157961/158185346-0dee8248-8775-4c39-a5bc-629ba87aacea.png)

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
Test with flywheel disabled. /flywheel backend off.

**Comment by TropheusJ** [comment]
Also, could you test on forge with OptiFine dynamic lighting?

**Comment by redstonerti** [comment]
Both flywheel batching and instancing introduce this issue. When flywheel is disabled it does not manifest.

**Comment by redstonerti** [comment]
Should I post an issue on flywheel's github instead?

**Comment by TropheusJ** [comment]
Does this happen with chests and bells while they animate? If so, yes. Otherwise no.

**Comment by redstonerti** [comment]
https://redstoner.me/downloads/videos/lighting%20bug.mp4
Yes it does, sorry for being so late. I will be closing this issue then

Edit: Could you please inform flywheel's team because I don't know the information needed to fill out the bug report. It asks for forge and flywheel versions and I don't think it would be much help to not specify. (I am using create version 0.4d)

**Comment by TropheusJ** [comment]
issue made.
