### ISSUE TITLE
Smart chute doesn't detect item change when not moving

### ISSUE THREAD

**Issue by redstonerti** [Fabricators-of-Create/Create#209]
### Describe the Bug

The smart chute doesn't detect fluix or certus quartz seeds from applied energistics 2 turning into crystals when in water. I have set the item filter to fluix crystals and have put the seeds in the water above it. If you use an encased fan to pull them up a bit every so often with a timer, it does detect them and puts them into the chest below-

### Reproduction Steps

Place a chest down
Place a smart chute above it
Set the item filter to fluix crystals
![image](https://user-images.githubusercontent.com/48157961/158383144-6355339c-540a-4a68-adc3-8fba406d4f5f.png)

Get a working me controller (with power)
![image](https://user-images.githubusercontent.com/48157961/158383279-8420314a-52d8-4014-a395-0225498781a9.png)

Set up the cables
![image](https://user-images.githubusercontent.com/48157961/158383507-0b09be10-387b-4ccb-9d56-bf1f5bac9898.png)

Stand on the smart chute and place growth crystal
![image](https://user-images.githubusercontent.com/48157961/158383644-20f9fec3-5b3c-417a-a29b-249ff38d1cfb.png)

Place water on the chute and throw in more than one stack of fluix seeds
![image](https://user-images.githubusercontent.com/48157961/158383795-2b9ecc9b-c726-456c-93a0-7b5c08480e38.png)

Wait for them to turn into fluix crystals and observer that they don't get sucked into the chute
![image](https://user-images.githubusercontent.com/48157961/158384492-47d7bdbd-4131-4a3c-82a7-54d8257a8bd5.png)

Note: This may not bug the first or second or third time, keep throwing more and more stacks in until it does

### Expected Result

I expected the smart chute to suck the items into the chest

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

Applied energistics 2

**Comment by TropheusJ** [comment]
Can you test this on forge? I don’t see why it would be different.

**Comment by redstonerti** [comment]
Turns out it is also broken on forge

**Comment by TropheusJ** [comment]
please make an issue on forge instead then.

**Comment by redstonerti** [comment]
Will do

**Comment by TropheusJ** [comment]
does this still occur?
