### ISSUE TITLE
Lighting error in chunk

### ISSUE THREAD

**Issue by Foxificer** [Fabricators-of-Create/Create#211]
### Describe the Bug

A chunk with a create contraption would soon have a bug where the entire chunk lighting is set to absolute 0 except for small patches around torches.

### Reproduction Steps

1. Find a nice piece of land
2. Make some create contraptions
3. Leave for a bit
4. Come back
...

### Expected Result

Entire chunk lighting will be set to 0

### Screenshots and Videos

Below are some screenshots of the error happening to various user builds on the server.
![2022-03-18_03 21 07](https://user-images.githubusercontent.com/95505194/158963259-c07b3223-88f3-40f5-bdf4-6e1d659ebdd5.png)
![2022-03-18_03 21 12](https://user-images.githubusercontent.com/95505194/158963263-300ec8a8-2f2f-4b86-8f30-5d116d671628.png)
![2022-03-18_03 21 17](https://user-images.githubusercontent.com/95505194/158963265-70a05d92-0ced-4cd6-b4e3-2f1f48c21ab9.png)
![2022-03-18_03 21 26](https://user-images.githubusercontent.com/95505194/158963270-de3f1e84-fedf-45f9-877d-ae65c35b0c1c.png)
![2022-03-18_02 38 38](https://user-images.githubusercontent.com/95505194/158963283-6ba07c6e-a8ac-470b-988d-85b62cab8076.png)

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

Too many to remember/list so here the modpack

https://www.dropbox.com/s/2wp1nrum5idqy1b/NowhereSMP_Modpack_V2.4.zip?dl=0

**Comment by TropheusJ** [comment]
according to simi, this can be caused by checking chunk contents during load.
If you can, please try to narrow down which block(s) cause this to happen.

**Comment by michlbro** [comment]
What build is the create mod in your modpack? The one in your modpack doesn’t have a build number on it meaning it could be old or you renamed it.

**Comment by TropheusJ** [comment]
Good catch. Forge Create suffered from this during 0.4 dev, so this is hopefully the same issue.

**Comment by Blightbuster** [comment]
Tested on 482 and I am unable to reproduce the issue. I tried building a similar contraption to the one provided and left it running for 10min once in loaded once in unloaded chunks but with no lighting glitches. Perhaps im just unlucky though?

**Comment by TropheusJ** [comment]
I am going to assume this is fixed, reopen if this is not the case.
