### ISSUE TITLE
Starlight and Create Crash (FIXED)

### ISSUE THREAD

**Issue by StockiesLad** [Fabricators-of-Create/Create#212]
### Describe the Bug

Crashing upon pressing the button for create configuration.

### Reproduction Steps

1. Install Create and Starlight on Fabric 0.13.3
2. Press the engineer's googles button on create
3. Crash

### Expected Result

To just open the GUI like every other GUI

### Crash Report or Log

[latest.log](https://github.com/Fabricators-of-Create/Create/files/8308601/latest.log)

### Operating System

Windows 10 Home

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

starlight-1.0.0+fabric.d0a3220

**Comment by TropheusJ** [comment]
update starlight to 1.0.1.

**Comment by StockiesLad** [comment]
There is no Starlight 1.0.1 on CF

**Comment by TropheusJ** [comment]
1.0.2 then

**Comment by TropheusJ** [comment]
wait nope, that's for 1.18.2 only

**Comment by TropheusJ** [comment]
Will be fixed with starlight 1.0.2+ once we update to 1.18.2.

**Comment by StockiesLad** [comment]
im trying to build 1.0.1 but the build is failing

**Comment by StockiesLad** [comment]
https://github.com/PaperMC/Starlight/commit/05839734b3b6f2fbc9295fbc1b3a1cef41eb6dc3
COMPILE THIS FOR 1.0.1 WHOEVER HAS THIS ISSUE.

YOU ARE WELCOME!
THE BUILD WORKS IF IT FAILS GET SOMEONE TO HELP YOU OUT!

**Comment by StockiesLad** [comment]
https://pastebin.com/kQut2g6Y

Open up your build.gradle and replace the text with the text in paste bin, and the build shouldn't fail anymore. If it doesn't fail in the first place!
