### ISSUE TITLE
Server Incompatibility

### ISSUE THREAD

**Issue by StockiesLad** [Fabricators-of-Create/Create#213]
### Describe the Bug

Can't join a localhost server

### Reproduction Steps

1.Download My modpack https://www.technicpack.net/modpack/the-limit-reborn-1181.1905659
2.Download the Server Pack 
3.Run them both
4. Try to join server

### Expected Result

To join the server

### Crash Report or Log

https://pastebin.com/ivZSTkLS

### Operating System

windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

Its on the modpack page

**Comment by StockiesLad** [comment]
It even happens with create by itself

**Comment by TropheusJ** [comment]
appears to be duplicate of #182
