### ISSUE TITLE
Iris issues

### ISSUE THREAD

**Issue by StockiesLad** [Fabricators-of-Create/Create#214]
### Describe the Bug

There are 2:
First is demonstrations do not render 
![image](https://user-images.githubusercontent.com/60066663/159150446-e73db2c3-c89c-4643-81ea-d63e4d661cf7.png)

The second is a crash when turning off shader packs.

[crash-2022-03-20_17.00.04-client.txt](https://github.com/Fabricators-of-Create/Create/files/8310686/crash-2022-03-20_17.00.04-client.txt)
[latest.log](https://github.com/Fabricators-of-Create/Create/files/8310687/latest.log)

### Reproduction Steps

1.Play with provide mods
2. Switch shaders and crash
3.Second: Play with shaders
4. Try to render demonstration and it won't show!
...

### Expected Result

To just switch shaders normally
To see the demonstration just like when shaders are switched off

### Crash Report or Log

Already provided

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

Look in LOG

### Additional Context

I really like the create mod but this as well as issue with servers forces me to take it out of the mod pack for now.
With all that said there has been SO MUCH progress so great job on that. It's just these issues that need to be fixed so my mod pack players can enjoy this mod masterpiece.

**Comment by weegeeluigi** [comment]
I believe Iris created a branch entirely for Create and pushed the fixes for a lot of rendering problems, but from what I can tell, those fixes were only pushed in time for the latest version which is for 1.18.2.  With a lot of reworking going into transfers based on what's been stated, and with upstream still not 1.18.2 ready, I don't suspect this will be able to be tested properly for a while.  Patience is going to be needed for a bit.

**Comment by michlbro** [comment]
For the crashing issue, have you tried turning off flywheel?
`/flywheel backend off`

**Comment by StockiesLad** [comment]
no I haven't
Even if I fixed the crash, the rendering issues are still an annoying problem

**Comment by aria1th** [comment]
[link removed]
you'll have to build from patch Iris-68e252c147ba8d872d65d579049efc9c411ac755

change buildscript then it will work with create, F3+T / render distance change
...or just download from upward release

**Comment by IMS212** [comment]
Please don't redistribute *half-done* development builds of Iris as downloads. You just gave users a download with a known entity issue causing terrible performance.

There's a reason we aren't backporting to 1.18.1; to encourage updates to 1.18.2 and avoid duplicate versioning.

**Comment by AlphaMode** [comment]
This is a duplicate of #97 please check previous issues before making a new one

**Comment by StockiesLad** [comment]
> Please don't redistribute _half-done_ development builds of Iris as downloads. You just gave users a download with a known entity issue causing terrible performance.
> 
> There's a reason we aren't backporting to 1.18.1; to encourage updates to 1.18.2 and avoid duplicate versioning.

It's nice and all to get people to update to 1.18.2 but create isn't updated yet. Removing that link just annoys me, it's not like we can even update to 1.18.2 Rn. It's ok that you support 1.18.2 but why are you removing patches that were already done anyways.

EDIT: I know there is an entity issue but still...

**Comment by weegeeluigi** [comment]
The entity issue is pretty big if you actually tried running the code base with the regression, I tried it on my own and the hit was substantial with shaders on in many parts of my world, which is why I didn't recommend to try to manually build it as a solution but instead to wait.  Someone with a lot more time can try to cherry pick a fork with all the fixes in to run on 1.18.1, but with the fact there's a major rewrite in progress to fix a ton of issues and Create upstream doesn't even officially support 1.18.2 yet, I don't see the rush when the issue has been fixed, just on a different minor version of the game.
