### ISSUE TITLE
Some resource packs cause the glowing shader to fail to load

### ISSUE THREAD

**Issue by redstonerti** [Fabricators-of-Create/Create#217]
### Describe the Bug

Create stops all resource packs from being loaded
Here's a relevant line in the logs: Caused by: java.io.IOException: Couldn't compile vertex program (Fabric Mods, create:glowing_shader) : 0(29) : error C1503: undefined variable "cylindrical_distance"

### Reproduction Steps

Download create
Try to load any resource pack

### Expected Result

The resource pack should load

### Crash Report or Log

https://mclo.gs/LrCXObo   

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by digitaltrucker** [comment]
That's a really old build, try build 445 (that's the one I use).

**Comment by redstonerti** [comment]
https://mclo.gs/ANdzHeI
I tried build 463 and it crashes on startup. I'll keep running down the builds until it works

**Comment by redstonerti** [comment]
![image](https://user-images.githubusercontent.com/48157961/160253124-f32fe043-d4db-4b8d-bd03-4ad5b4dabf23.png)
https://mclo.gs/Ahh1SF8
I tried it with the latest build. The bug is still present

**Comment by TropheusJ** [comment]
latest builds are unusable, test 441 or 445

**Comment by redstonerti** [comment]
![image](https://user-images.githubusercontent.com/48157961/160253490-5f2654cb-3d08-4b9d-be37-20a4f3eaab22.png)
This was the one I used, and everything else worked fine. It was usable. I will try it with 445 though just to be sure.

**Comment by redstonerti** [comment]
Just tested build 445, no difference

**Comment by Blightbuster** [comment]
Tested on 448 with this resource pack: https://resourcepack.net/wayukian-resource-pack/

Everything loads fine and I don't get any error.

@redstonerti could you please link the pack you used?

![image](https://user-images.githubusercontent.com/24388294/162105757-41454cf1-6efa-4bc4-a72b-3b89af4aed90.png)

**Comment by TropheusJ** [comment]
![image](https://user-images.githubusercontent.com/60247969/162346431-e1c1bc41-52ba-48ea-9ed4-d469c1545c81.png)
can't reproduce

**Comment by Cart3r1234** [comment]
_Featuring the almighty H Pack_

**Comment by redstonerti** [comment]
I just tested it in build 445 with your resource pack, and it works. What doesn't work however, is this resource pack.
[fourniv6.zip](https://github.com/Fabricators-of-Create/Create/files/8451483/fourniv6.zip)
Which is very weird to be honest. All I did was upscale some textures. Everything is a multiple of two and some small details have been added. I'm going to try and test it later with more resource packs and see what happens but this is all I have for now.

**Comment by redstonerti** [comment]
![image](https://user-images.githubusercontent.com/48157961/162429669-c668bf89-6610-4eea-9daf-338facab8647.png)
Also yeah the same error happened as before. You could say that this is my fault, that I made a bad texture pack, but this error might cause problems with other packs as well.
Mods: https://drive.google.com/file/d/1Db-0a-QTF8m-0kZaGzkijoKpNsjJ8S1T/view?usp=sharing
Fabric version: 0.13.3-1.18.1

**Comment by redstonerti** [comment]
Yeah sorry, I should have changed the title myself. Were you able to reproduce this?

**Comment by AlphaMode** [comment]
Can you test this on forge too

**Comment by redstonerti** [comment]
> Can you test this on forge too

We were playing on forge with this resource pack before switching to fabric. I guess I could test it again on the latest version but I am 99.99% sure that it works on forge.

**Comment by TropheusJ** [comment]
I've figured out that if a resource pack defines core shaders, flywheel shaders will fail to load. This example pack seems to be made exceptionally terribly, and seems to bundle duplicates of vanilla resources, including shaders.

**Comment by TropheusJ** [comment]
further investigation: the pack has a messed up `include/fog.glsl` shader. The `fog_distance` function is just missing.

**Comment by TropheusJ** [comment]
to my understanding this is just a flaw in the pack.
