### ISSUE TITLE
Incredibly low fps when looking at waterwheels

### ISSUE THREAD

**Issue by redstonerti** [Fabricators-of-Create/Create#218]
### Describe the Bug

When looking at 144 waterwheels that are all connected with encased chain drives, my frames per second get reduced by about 60%
Here's a video demonstrating that
https://redstoner.me/downloads/videos/low%20create%20fps.mp4
Here's the same build in a superflat world
![image](https://user-images.githubusercontent.com/48157961/160257878-60b54c68-27dc-4d88-a800-6731e1f9545f.png)
![Uploading image.png…]()

### Reproduction Steps

Here's a schematic of the superflat build
https://redstoner.me/downloads/schematics/waterwheels2.nbt

### Expected Result

I expected maybe a bit lower fps but this is insane. About one third the fps is more than I could tolerate

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Additional Context

This is on build 413. I tried build 445 and it was the same. That build had other issues though which I will be posting after this

**Comment by TropheusJ** [comment]
flywheel is not enabled, this is likely identical on forge. use `/flywheel backend instancing` to enable.

**Comment by TropheusJ** [comment]
fixed through discord by enabling instancing.
