### ISSUE TITLE
Gantry shaft has no cogwheel animation

### ISSUE THREAD

**Issue by redstonerti** [Fabricators-of-Create/Create#219]
### Describe the Bug

Gantry shaft has no cogwheel animation
tested with build 443 and 445
https://redstoner.me/downloads/videos/cog%20no%20turn.mp4

### Reproduction Steps

Already showed a video

### Expected Result

I expected the cog to turn as it does on forge

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by AlphaMode** [comment]
Please check if the issue occurs on forge please before opening a issue

**Comment by AlphaMode** [comment]
Please report this to upstream if you believe it is a issue. I am pretty sure this is intended though

**Comment by redstonerti** [comment]
Sorry about that. The cog might have turned in previous versions of create and confused me. Or I could I have made the whole thing up because it looked weird. I made a mistake
