### ISSUE TITLE
Black texture on rotating blocks

### ISSUE THREAD

**Issue by BratishkaErik** [Fabricators-of-Create/Create#22]
![2021-11-21_19 28 48](https://user-images.githubusercontent.com/25210740/142763859-ec015610-4686-4eab-8a02-5550ccfe3095.png)
![2021-11-21_19 28 53](https://user-images.githubusercontent.com/25210740/142763861-af02436b-5d72-44ed-bef7-bda2e9dae223.png)

**Comment by AlphaMode** [comment]
Turning off flywheel should fix this for now

**Comment by AlphaMode** [comment]
Fixed
