### ISSUE TITLE
Duping of items

### ISSUE THREAD

**Issue by Papaturts** [Fabricators-of-Create/Create#221]
### Describe the Bug

built a radial tree farm with saws an deployers
seems items either dont completely deposit into the chest or possible duping of the items via the portable storage interface connected to a chute and a chest
also deployers dont replant sapplings 

### Reproduction Steps

1. build radial tree farm
2. run radial tree far
3. check chest after trees have been cut
...

### Expected Result

all items should be the proper amount deposited into chest

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

fabric api

### Additional Context

be willing to do a series on youtube with this an possibly help out on finding other issues that may arise

**Comment by TropheusJ** [comment]
Please test this on [build 482](https://github.com/Fabricators-of-Create/Create/actions/runs/2084568820) or newer. If this issue still occurs, please re-open it.
