### ISSUE TITLE
Minecart contraptions with inventories crash upon formation.

### ISSUE THREAD

**Issue by theishiopian** [Fabricators-of-Create/Create#223]
### Describe the Bug

Minecart contraptions with inventories like barrels crash the game.

### Reproduction Steps

Create a minecart contraption with an inventory on it, with one stack of items inside.

### Expected Result

The game should not crash.

### Crash Report or Log

https://pastebin.com/TnPJtET5

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

Better Nether
Better End
BCLib
Amplified Nether

### Additional Context

Build 478

**Comment by TropheusJ** [comment]
Please test this on[ build 482](https://github.com/Fabricators-of-Create/Create/actions/runs/2084568820) or newer. If this issue still occurs, please re-open it.

**Comment by theishiopian** [comment]
Will do

**Comment by theishiopian** [comment]
Still crashes with 482

Log: https://pastebin.com/6PeKzmiZ

**Comment by TropheusJ** [comment]
This should now be fixed.
