### ISSUE TITLE
When entering the server, the player disconnects

### ISSUE THREAD

**Issue by XionioXMaster** [Fabricators-of-Create/Create#225]
### Describe the Bug

When entering the server, the player disconnects, i used last Action Build 1.18.1

### Reproduction Steps

1. Put mod for server (not localhost)
2. Put mod client
3. Join to the server
...

### Expected Result

?

### Operating System

unbuntu 20

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
Duplicate of #182
