### ISSUE TITLE
Deployers not planting sapplings after cutting trees

### ISSUE THREAD

**Issue by Papaturts** [Fabricators-of-Create/Create#228]
### Describe the Bug

The deployers plant sapplings fine until the contraption cuts the first tree down.
No longer plants sapplings afterwards

### Reproduction Steps

1.Build radial tree farm
2.use deployers to plant sapplings
3.let farm run with saws cutting trees as they grow
...

### Expected Result

Deployers replant sapplings after cutting trees

### Screenshots and Videos

![2022-04-03_16 42 39](https://user-images.githubusercontent.com/97408568/161450231-b08f49d4-d303-40ea-b92e-3924d0cbee7b.png)

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Additional Context

using the build linked in email
the picture is after a few of the trees have grown/cut down

**Comment by michlbro** [comment]
Have you put filters on the deployers?
They seem to work fine in most stable build of create (build ~445)

**Comment by TropheusJ** [comment]
builds 482+ should now be used in place of older builds.

**Comment by Papaturts** [comment]
Im using build 482 i think it was at the time that was linked in a previous issue
Yes I did add oak saplings to the filters-good question tho, as ive seen that as an issue a fair amount in other servers

**Comment by Blightbuster** [comment]
Just tested on 482 and indeed using any filter on a Deployer doesnt work. It will just block any item from coming through.
