### ISSUE TITLE
items dissappear when thrown into basin

### ISSUE THREAD

**Issue by Papaturts** [Fabricators-of-Create/Create#229]
### Describe the Bug

items dissapear when tossed into a basin
tried with both copper/zinc to make brass
also tried iron nuggets and andesite to make andesite alloy

### Reproduction Steps

1. setup mixer with basin
2. add iron nuggets in one chest then andesite in another or copper and zinc 
3. have them mix together in the basin
...

### Expected Result

create andesite allow
or
brass from copper an zinc while heated with a blaze burner

### Screenshots and Videos

![2022-04-03_20 58 06](https://user-images.githubusercontent.com/97408568/161463296-42c23740-837b-4049-a899-2d9b5485ffa0.png)

### Operating System

windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
this has been fixed.
