### ISSUE TITLE
Once the flaming man stove is placed, the game will collapse

### ISSUE THREAD

**Issue by Achiyun** [Fabricators-of-Create/Create#230]
### Describe the Bug

Such as title

### Reproduction Steps

1.
2.
3.
...

### Expected Result

,

### Screenshots and Videos

,

### Crash Report or Log

,

### Operating System

ubuntu21.10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

### Other Mods

,

### Additional Context

,

**Comment by DarianLStephens** [comment]
Sometimes, I love mistranslations.
