### ISSUE TITLE
1.18.2 Ready Version (Build 485) Crash

### ISSUE THREAD

**Issue by digitaltrucker** [Fabricators-of-Create/Create#231]
### Describe the Bug

Game crashes on launch.

### Reproduction Steps

1.  Attempt to launch game
2. ???

### Expected Result

Game launches.

### Crash Report or Log

https://pastebin.com/YFX2sU82

### Operating System

Windows 10

### Mod Version

0.4.0f

### Minecraft Version

1.18.1

### Additional Context

Actually Minecraft 1.18.2, that option just isn't selectable in the dropdown box.

**Comment by MattiDragon** [comment]
Related to nightconfig

**Comment by digitaltrucker** [comment]
What's that?

Edit:  Never mind, not on my end anyway.

**Comment by Kneelawk** [comment]
From the error log, we can see that `com_electronwill_night-config_core` and `com_electronwill_night-config_toml` aren't getting loaded, despite being JIJ'd in the create jar, while `com_google_code_findbugs_jsr305` (also JIJ'd in create) is getting loaded.

No clue as to what could be causing this though.

**Comment by Kneelawk** [comment]
Extracting the `META-INF/jars/core-3.6.3.jar` and `META-INF/jars/toml-3.6.3.jar` files from the create jar and copying them into the `mods` folder, then changing their mod-ids to replace all instances of `-` with `_` appears to have fixed the issue and these libraries are now being loaded by fabric-loader.

My guess is that this is a bug in fabric-loader.

**Comment by TropheusJ** [comment]
Please test this with build 487+.

**Comment by StockiesLad** [comment]
Same issue on 488

**Comment by digitaltrucker** [comment]
Build 490 is still crashing the game, but it seems to be different as it no longer creates a log in the crash-reports folder.  Instead it generates a regular log.

https://pastebin.com/BZNX3nWK

**Comment by ThinkWithPbody** [comment]
Using build 490 and the game crashes on launch for me too. I don't see a crash report though, only the "Minecraft has crashed!" error report from fabric loader.  

https://pastebin.com/9mwZZkGV
Edit: Full log https://pastebin.com/L7EtEcxh

**Comment by sybershot** [comment]
Same goes for me. Using build 490 crashes the game.
Mods that i have:
- Create
- Iris shaders 1.2.2.build 32
- Sodium 0.41 build 15
- Sodium Extra 0.4.3
- Reese's Sodium Options 1.4.2
- Fabric API 0.48.0
I have a different crash log than recently reported. It is referring to `com.electronwill.nightconfig.core` again.
Upd: I tried to move core and toml jars from META-INF to my mods folder and got the same result.
Full Log: https://paste.ee/p/jzItK
Crash Log: https://paste.ee/p/NLH9t

**Comment by OverloadedWithMods** [comment]
It's almost like create is becoming progressively more unstable...

**Comment by TropheusJ** [comment]
It’s almost like rewriting entire systems and updating to a new Minecraft version are likely to break things. 
I’ve already fixed this issue locally, I just need to finish up some other things with transfer.

**Comment by StockiesLad** [comment]
> It’s almost like rewriting entire systems and updating to a new Minecraft version are likely to break things. I’ve already fixed this issue locally, I just need to finish up some other things with transfer.

It was just a joke! I appreciate ur hardwork just wanted to make some people laugh. I know its difficult and I didnt mean to offend u.

**Comment by Polarite** [comment]
we are happy with the improvements create fabric having to be honest. It is amazing that great mod is being ported to fabric!

**Comment by redstonerti** [comment]
> we are happy with the improvements create fabric having to be honest. It is amazing that great mod is being ported to fabric!

This. Thank you tropheus for your hard work and for saving our fps.

**Comment by StockiesLad** [comment]
I deleted the comment! It was an ass move. My bad!

**Comment by vince25297** [comment]
Thanks for your work!

**Comment by ThinkWithPbody** [comment]
Build 491 causes the game to crash on launch for me too. Thanks for your hard work! 
Log: https://pastebin.com/V0f3BY6C

Build 492 seems to work! Please ignore :)

**Comment by TropheusJ** [comment]
this is the lithium crash that I just fixed.
