### ISSUE TITLE
Curseforge/modrinth build posts

### ISSUE THREAD

**Issue by StockiesLad** [Fabricators-of-Create/Create#232]
### Describe the Suggestion

Would be cool if builds you... u know... were posted on CF/Modrinth.

**Comment by AlphaMode** [comment]
Builds will be posted when we are ready to release the mod

**Comment by MSandro** [comment]
I really don't want to be rude, but can you give a rough estimate of how long this is going to take?
about a month, two months, early summer...
I would love to use the mod in one of my planned modpacks and can't wait for it to be released.

Thanks for the great work.
