### ISSUE TITLE
This isn't anything but congratulations!

### ISSUE THREAD

**Issue by StockiesLad** [Fabricators-of-Create/Create#235]
### Describe the Suggestion

Dude you guys  are killing it man! Thank you for porting the best tech mod to fabric. Absolute legends!

PS: TropheusJ Soz for that comment earlier about create becoming unstable! I just saw how the issues section just got halved. Clearly proved that comment wrong!

**Comment by TropheusJ** [comment]
Thank you, but please don't use the issue tracker for this :)

**Comment by StockiesLad** [comment]
Is there a discord server for this mod

**Comment by TropheusJ** [comment]
The main Create discord
