### ISSUE TITLE
Animation & Static model

### ISSUE THREAD

**Issue by kolaSentrys** [Fabricators-of-Create/Create#239]
### Describe the Bug

Cogs and shafts display both the static model and the animated model at the same time. 

### Reproduction Steps

1. Get a cog/shaft
2. Produce rotational energy.
3. Connect cog/shaft to the power source.
...

### Expected Result

For the cog and shaft to animate properly without a static model.

### Screenshots and Videos

![2022-04-07_20 07 53_7](https://user-images.githubusercontent.com/102298551/162438779-74e84636-09e4-44ec-8f7a-ac513c6b52c0.png)

### Crash Report or Log

No log/crash

### Operating System

Windows 10

### Mod Version

0.4.0d

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
Install indium.
