### ISSUE TITLE
Items harvested by a contraption do not appear in chest

### ISSUE THREAD

**Issue by ghost** [Fabricators-of-Create/Create#240]
### Describe the Bug

I haven't tested further, but if you connect a harvester and chest via a linear chassis on a mine cart, the items collected by the harvester don't show up in the chest. The same machine works perfectly on Forge.

### Reproduction Steps

1. Build a contraption that harvests something and puts it in a chest
2. Stop the contraption and look into the chest, see nothing

### Expected Result

the items that the harvester picks up should go into the chest.

### Screenshots and Videos

This is the contraption I built: https://www.youtube.com/watch?v=Ff5b7Cl9_10

### Operating System

arch btw

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Iris + BSL

**Comment by Papaturts** [comment]
Have you tried a barrel by chance? seen on other servers with other versions of create where chests dont seem to work for some reason
nvm
Barrels dont work either
can confirm this as well
