### ISSUE TITLE
When downloading from Action, the archive has 17 MB, but inside the .jar it weighs 0

### ISSUE THREAD

**Issue by XionioXMaster** [Fabricators-of-Create/Create#242]
### Describe the Bug

When downloading from Action, the archive has 17 MB, but inside the .jar it weighs 0

### Reproduction Steps

When downloading from Action, the archive has 17 MB, but inside the .jar it weighs 0

### Expected Result

When downloading from Action, the archive has 17 MB, but inside the .jar it weighs 0

### Operating System

When downloading from Action, the archive has 17 MB, but inside the .jar it weighs 0

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by JieningYu** [comment]
You can simply build yourself

**Comment by JieningYu** [comment]
Your problem. The jar is fine on my side

**Comment by RedWideWeb** [comment]
The jar is okay so you can close the issue

![image](https://user-images.githubusercontent.com/58992150/162613406-47c74e3c-880c-478f-8702-2648cc0c7045.png)

![image](https://user-images.githubusercontent.com/58992150/162613361-f1368862-c311-4ee7-b5fa-c60aaa6ff31e.png)
