### ISSUE TITLE
Server crashes if NbtCrafting recipes are loaded

### ISSUE THREAD

**Issue by NyannRR** [Fabricators-of-Create/Create#250]
### Describe the Bug

title

### Reproduction Steps

1. Download Alloygery and Create
2. Load or create a world
3. The game crashes

### Expected Result

The world loads with no issue

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/70542437/163695788-a3047c2b-a6c3-421c-a2d3-1e41e36494c5.png)

### Crash Report or Log

https://pastebin.com/162Bi2p0 (entire log)
https://pastebin.com/kRHygAx1 (crash)

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by JieningYu** [comment]
what is "Alloygery"
Alloy Forgery?

**Comment by NyannRR** [comment]
> what is "Alloygery" Alloy Forgery?

No, it's [this mod](https://www.curseforge.com/minecraft/mc-mods/alloygery)

**Comment by ProjectET** [comment]
Nbtcrafting is the culprit

**Comment by NyannRR** [comment]
> Nbtcrafting is the culprit

Yup, I tried adding NbtCrafting recipes with datapacks and the server crashed too ~~(I should have probably tested this before, sry)~~
