### ISSUE TITLE
deployer crash

### ISSUE THREAD

**Issue by Skidamek** [Fabricators-of-Create/Create#252]
### Describe the Bug

Server crashed while building auto tree farm more precisely when I put the deployer on super glue to my farm, server crashed and when I started it back when chunk loaded where the contraption is, server immediately crashed.
(latest build 504)

### Reproduction Steps

I'd tried to reproduce this but when I tried it works well...
When I find out how to I will send.

### Expected Result

Work well without crash.

### Screenshots and Videos

I wanted to, but I forgot to record by surprise...

### Crash Report or Log

https://pastebin.com/1K5cgYqf - crash log

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Server mods:

1.18-up-we-go-3.0.0.jar
AirHop-v3.2.0-1.18.2-Fabric.jar
Alternate Current-LATEST-[1.181.2.0.].jar
AttributeFix-1.16.5-10.1.4.jar
AwesomeDungeonFabric-1.18.1-2.0.8.jar
balm-fabric-3.0.0+0.jar
c2me-fabric-mc1.18.2-0.2.0+alpha.7.18.jar
carpet-fixes-1.18.x-1.7.5+v220411.jar
cloth-config-5.3.58-fabric.jar
create-mc1.18.2_v0.4.1+504.jar
debugify-fabric-1.7.2.jar
EasyShulkerBoxes-v3.1.1-1.18.2-Fabric.jar
EditSign-1.18.2-2.3.1.jar
enchanted-vertical-slabs-1.4.1.jar
EnchantingInfuser-v3.2.0-1.18.2-Fabric.jar
Fabric API-LATEST-[0.51.01.18.2.].jar
fabric-carpet-1.18.2-1.4.69+v220331.jar
fabric-diagonal-panes-0.6.1.jar
FastLeafDecay-28.jar
ferritecore-4.2.0-fabric.jar
ForgeConfigAPIPort-v3.2.0-1.18.2-Fabric.jar
krypton-0.1.9.jar
Ksyxis-1.1.jar
lazydfu-0.1.2.jar
LibraryFerret-Fabric-1.18.2-1.0.3.jar
lithium-fabric-mc1.18.2-0.7.9.jar
MmmMmmMmmMmm-1.18-1.5.1.jar
mods-command-mc1.18.2-1.0.6.jar
netherportalfix-fabric-1.18-9.0.0.jar
plasmovoice-fabric-1.18.2-1.2.11-hotfix1.jar
PuzzlesLib-v3.3.1-1.18.2-Fabric.jar
sit-1.18.2-18.jar
spark-1.8.14-fabric.jar
starlight-1.0.2+fabric.89b8d9f.jar
TinySkeletons-v3.2.1-1.18.2-Fabric.jar
trinkets-3.3.0.jar
villager-hats-mod-1.3.1.jar
VisualWorkbench-v3.2.0-1.18.2-Fabric.jar

**Comment by Skidamek** [comment]
I discovered that this bug doesn't exist on singleplayer that's why I was unable to reproduce it
So with this knowledge I reproduce it to server and recorded, the video is to big for github so I uploaded it on youtube https://youtu.be/HKBuYnOOpsQ

**Comment by Skidamek** [comment]
I come to a fundamental conclusion deployer not work on servers I guess or some from my mods not work well with create its more possible but which?

**Comment by Skidamek** [comment]
LOL the most unexpected mod is incompatible with create 
mods-command-mc1.18.2-1.0.6.jar
so I can close it but you can add this to incompatible list or something 
Have a nice day!

**Comment by TropheusJ** [comment]
Duplicate of #117
