### ISSUE TITLE
Colormatic causes crash with Create fluids

### ISSUE THREAD

**Issue by Bipbip2109** [Fabricators-of-Create/Create#255]
### Describe the Bug

When you put tea in a fluid tank and the game tries to render it, the "saving" dirt screen appears and it instantly crashes.

### Reproduction Steps

1. Install every fucking single fabric 1.18.2 mod
2. Put tea in a fluid tank
3. Enjoy your crash

### Expected Result

Crash

### Crash Report or Log

https://pastebin.com/9WNVZppP

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Sodium, iris (no shaders activated), starlight, and many more.

### Additional Context

I think that sodium causes the issue.
Also the version of the mod is the latest build (506)

**Comment by TropheusJ** [comment]
I can't reproduce this. Can you test on the latest build? Related code has been changed.

**Comment by Bipbip2109** [comment]
It still happens with the latest build

**Comment by JieningYu** [comment]
Try remove mods about entity/block entity rendering(ex. cem)

**Comment by TropheusJ** [comment]
please test build 532

**Comment by Bipbip2109** [comment]
Yep build532 fixes the issue

**Comment by acanthii** [comment]
Don't know if this is relevant enough to not warrant opening another issue, but running **colormatic**  + sodium iris + the latest create build makes custom liquid render invisible in tanks, and crashes the game when custom liquids move through a pipe or when you ponder on the liquid tank item.

**Comment by Bipbip2109** [comment]
@azridere same issue in my game

**Comment by TropheusJ** [comment]
This has been tracked down to an issue with colormatic, which has been reported.
