### ISSUE TITLE
Crashing on Launch with Latest Build (#511)

### ISSUE THREAD

**Issue by Tenuuu** [Fabricators-of-Create/Create#256]
### Describe the Bug

Started a fresh profile to give this mod a go and can't seem to launch up the profile at all. First time trying this mod out so not sure if I need additional mods to help out.

### Reproduction Steps

1. Install latest build (Bulid 511)
2. Crash

### Expected Result

Expected to launch up perfectly normal

### Crash Report or Log

https://gist.github.com/Tenuuu/abd9683c63e0e9b5ac77f2b482c48000

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by JieningYu** [comment]
same issue on Quilt Loader with qsl beta 6.

**Comment by TropheusJ** [comment]
Can you test fabric loader 0.13.3?

**Comment by Skidamek** [comment]
> Can you test fabric loader 0.13.3?

Same issue nothing changed on fabric 0.13.3 - no other mods only fabric api 0.51.1+1.18.
https://pastebin.com/v6CC22J7

**Comment by StockiesLad** [comment]
same issue

**Comment by StockiesLad** [comment]
it worked in a modpack somehow??????? but when eden ring installed, it failed again. idek

**Comment by StockiesLad** [comment]
and now its not working??

**Comment by Tenuuu** [comment]
> > Can you test fabric loader 0.13.3?
> 
> Same issue nothing changed on fabric 0.13.3 - no other mods only fabric api 0.51.1+1.18. https://pastebin.com/v6CC22J7

I noticed that my crash log has this little bit at the top when compared to your log which doesn't have it. Does that mean anything or?

https://gist.github.com/Tenuuu/bd69dd85982befbb04e867425cb0c38a

**Comment by Tenuuu** [comment]
Thought I would note as well that this same crash did happen for me on other builds. Tested all this last night and cannot remember which builds I tried, but I can figure that out soon.

**Comment by Skidamek** [comment]
> > > Can you test fabric loader 0.13.3?
> > 
> > 
> > Same issue nothing changed on fabric 0.13.3 - no other mods only fabric api 0.51.1+1.18. https://pastebin.com/v6CC22J7
> 
> I noticed that my crash log has this little bit at the top when compared to your log which doesn't have it. Does that mean anything or?
> 
> https://gist.github.com/Tenuuu/bd69dd85982befbb04e867425cb0c38a

yes because I used build 513 (latest build) but also crash so..

**Comment by Tenuuu** [comment]
> 

Interesting. I can try build 513 when I get back to my PC in a bit.

**Comment by Tenuuu** [comment]
> > > > Can you test fabric loader 0.13.3?
> > > 
> > > 
> > > Same issue nothing changed on fabric 0.13.3 - no other mods only fabric api 0.51.1+1.18. https://pastebin.com/v6CC22J7
> > 
> > 
> > I noticed that my crash log has this little bit at the top when compared to your log which doesn't have it. Does that mean anything or?
> > https://gist.github.com/Tenuuu/bd69dd85982befbb04e867425cb0c38a
> 
> yes because I used build 513 (latest build) but also crash so..

Interesting. I can try build 513 when I get back to my PC in a bit.

**Comment by Tenuuu** [comment]
https://gist.github.com/Tenuuu/aa95e40365fcfd6a3ad1c8d94f743ce3

Crashing with build 513 on fabric version 0.13.3

**Comment by TropheusJ** [comment]
please test build 514 once it finishes.

**Comment by Tenuuu** [comment]
> please test build 514 once it finishes.

Tested build 514 and it launched up perfectly!

**Comment by TropheusJ** [comment]
Perfect.
