### ISSUE TITLE
Incompatible with Eden Ring, Better Nether/End, Bclib

### ISSUE THREAD

**Issue by StockiesLad** [Fabricators-of-Create/Create#257]
### Describe the Bug

It has some weird error with the porting lib. I have tried this with just them strictly AND in a heavily modded environment. 
I have used fabric api 0.14.2,0.13.3, same error again.
I have tried all builds from create .506 and above

### Reproduction Steps

1.Install all of the above
2.Run
3.
...

### Expected Result

To load into the game atleast

### Screenshots and Videos

[latest.log](https://github.com/Fabricators-of-Create/Create/files/8554110/latest.log)
Log is here bc it couldnt upload in the main tab for it!

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

BcLib, Better End/Nether, Eden Ring

### Additional Context

It somehow worked in a modded environment (too many to show here) without eden ring, I got no idea how but yeah..

**Comment by StockiesLad** [comment]
After more testing, it is a direct conflict between eden ring and create refabricated.
FOR build 506

**Comment by JieningYu** [comment]
Betternether is compatible.

**Comment by AlphaMode** [comment]
Build 506 is a testing build testing compatibility 
with canvas and is not meant to be used at all. Please use a build from the main branch
