### ISSUE TITLE
 Compilation failed; see the compiler error output for details.

### ISSUE THREAD

**Issue by Potochnyy** [Fabricators-of-Create/Create#26]
warning: unknown enum constant Dist.CLIENT
  reason: class file for net.minecraftforge.api.distmarker.Dist not found
warning: unknown enum constant Dist.CLIENT
warning: unknown enum constant Dist.CLIENT
68 errors
9 warnings

> Task :compileJava FAILED
Deprecated Loom APIs were used in this build, making it incompatible with future versions of Loom. Use Gradle warning modes to control the verbosity of the warnings.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
1 actionable task: 1 executed

**Comment by imreallybadatnames** [comment]
project not ready for compilation yet

**Comment by AlphaMode** [comment]
What branch are you using?

**Comment by AlphaMode** [comment]
If you want to compile the project use the 1.17 fabric branch. If you want to use 1.18 you need to wait until we get flywheel working.

**Comment by AlphaMode** [comment]
> project not ready for compilation yet

This is not entirely true its just missing the needed dependencies that are not on a maven yet

**Comment by Potochnyy** [comment]
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install registrate, any version.
Unmet dependency listing:
	 - Mod 'Create: Refabricated' (create) 0.4 requires any version of registrate, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install registrate, any version.
Unmet dependency listing:
	 - Mod 'Create: Refabricated' (create) 0.4 requires any version of registrate, which is missing!
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

Game crash when i start it with Create in 1.17.1, it say need registrate any versions, but its already in mods folder, how to fix?

**Comment by Potochnyy** [comment]
> > project not ready for compilation yet
> 
> This is not entirely true its just missing the needed dependencies that are not on a maven yet

Game crash when i start it with Create in 1.17.1, it say need registrate any versions, but its already in mods folder, how to fix?
