### ISSUE TITLE
Contraptions don't spawn in latest commit

### ISSUE THREAD

**Issue by maximumpower55** [Fabricators-of-Create/Create#264]
### Describe the Bug

Contraptions don't spawn in latest commit

### Reproduction Steps

1: Make a simple contraption like this ( Remember to use superglue :> )
![2022-04-28_13 58 01](https://user-images.githubusercontent.com/62370320/165844692-25a41f4b-46b4-408c-a8f4-91523c516e79.png)
2: Activate the bearing
3: The contraption should not spawn
![2022-04-28_13 58 08](https://user-images.githubusercontent.com/62370320/165844895-74e7d042-3513-489e-a204-119d7d9d54b6.png)

### Expected Result

The contraption should spawn (pretty self explanatory)

### Screenshots and Videos

Screenshots listed in reproduction steps

### Crash Report or Log

[13:58:03] [Render thread/ERROR]: Error executing task on Client
java.lang.IndexOutOfBoundsException: readerIndex(708) + length(1) exceeds writerIndex(708): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 708, widx: 708, cap: 1024)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-all-4.1.68.Final.jar:?]
	at net.minecraft.class_2540.readByte(class_2540.java:1013) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_30616(class_2540.java:443) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10798(class_2540.java:432) ~[client-intermediary.jar:?]
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.readSpawnData(AbstractContraptionEntity.java:428) ~[create-mc1.18.2_v0.4.1+521.jar:?]
	at net.minecraft.class_634.handler$zzk000$port_lib$afterRecreateEntity(class_634.java:2935) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11112(class_634.java:403) ~[client-intermediary.jar:?]
	at net.minecraft.class_2604.method_11178(class_2604.java:93) ~[client-intermediary.jar:?]
	at net.minecraft.class_2604.method_11054(class_2604.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.3.jar:?]

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

	- advanced_runtime_resource_pack 0.5.5 via enhancedblockentities
	- animatica 0.4+1.18
	- borderlessmining 1.1.2+1.18.2
	- caffeineconfig 1.1.0 via sodium-extra
	- cem 0.7.1
	- citresewn 1.0.1+1.18.2
	- citresewn-defaults 1.0.1+1.18.2 via citresewn
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- colormatic 3.2.0-snapshot+mc.1.18.2
	- com_electronwill_night-config_core 3.6.3 via create
	- com_electronwill_night-config_toml 3.6.3 via create
	- com_github_llamalad7_mixinextras 0.0.8 via debugify
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- completeconfig 1.0.0 via cem
	- continuity 2.0.0-alpha.2+1.18.2
	- create mc1.18.2_v0.4.1+521
	- dcch 1.0
	- debugify 1.9.0
	- dev_isxander_settxi 2.1.1 via zoomify
	- dripstone_fluid_lib 1.2.0 via milk
	- dynamicfps 2.1.0
	- enhancedblockentities 0.6+1.18.2
	- entity_texture_features 2.6.1
	- entityculling 1.5.1
	- fabric 0.51.1+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-data-generation-api-v1 2.0.7+6d3e563660 via registrate-fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.7.4+kotlin.1.6.21
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via borderlessmining
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.14.3
	- fabrishot ${version}
	- fake-player-api 0.3.0 via create
	- ferritecore 4.2.1
	- flywheel 1.18-0.6.2.25 via create
	- forge_tags 2.1 via porting_lib
	- forgeconfigapiport 3.2.0 via create
	- indium 1.0.3+mc1.18.2
	- iris 1.2.3-85cb7bd9
	- itemmodelfix 1.0.3+1.18
	- java 17
	- kappa 3.0.2
	- krypton 0.1.9
	- lazy-language-loader 0.3.0
	- lazydfu 0.1.2
	- lithium 0.7.9
	- midnightlib 0.4.0 via puzzle
	- milk 0.3.0 via create
	- minecraft 1.18.2
	- mm 2.3 via porting_lib
	- modmenu 3.2.1
	- morechathistory 1.1.0
	- nofade 1.18-2.0.1
	- noindium 1.0.1+1.18.2 via create
	- not-that-cc 1.0
	- omega-config 1.2.3-1.18.1 via noindium
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_bundleproject_libversion 0.0.3 via zoomify
	- org_jetbrains_kotlin_kotlin-reflect 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.21 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- packet_tweaker 0.2.0+1.18-pre1 via polymer
	- placeholder-api 1.1.3+1.17.1 via styledchat
	- player-data-api 0.1.0+1.18 via styled-nicknames
	- polymer 0.2.0-beta.29+1.18.2 via polymer-all
	- polymer-all 0.2.0-beta.29+1.18.2
	- polymer-blocks-ext 0.1.0-alpha.5+1.18.2 via polymer-all
	- polymer-legacy 0.1.9+0.2.0-beta.29+1.18.2 via polymer
	- porting_lib 0.2.0+1.18.2.3c06af9 via create
	- puzzle 1.2.1
	- puzzle-base 1.2.1 via puzzle
	- puzzle-gui 1.2.1 via puzzle
	- puzzle-models 1.2.1 via puzzle
	- puzzle-splashscreen 1.2.1 via puzzle
	- raised 1.0.6
	- reach-entity-attributes 2.1.1 via create
	- reeses-sodium-options 1.4.2
	- registrate-fabric MC1.18.2-1.0.x via create
	- replaymod 1.18.2-2.6.4
	- screenshotclipboard 1.0.9
	- seedfix 1.0.2
	- servertick 1.6
	- settxicloth 1.0.1 via zoomify
	- skinlayers 1.4.3-mc1.18.2
	- sodium 0.4.1+replaymod-rev.9fa8b28
	- sodium-extra 0.4.3
	- spark 1.8.14
	- spectater 2.0.1
	- spruceui 3.3.0+1.17 via enhancedblockentities
	- starlight 1.0.2+fabric.89b8d9f
	- styled-nicknames 1.0.4+1.18
	- styledchat 1.2.3+1.18
	- tooltipfix 1.0.4-1.18
	- worldedit 7.2.10+1742f98
	- zoomify 1.5.0

### Additional Context

It seems like the contraption does spawn on the server but not on the client because the packet is too big

(Yes.. I have tested with xl packets **FABRIC**, the same error happens)

**Comment by TropheusJ** [comment]
fixed by build 522
