### ISSUE TITLE
Sodium causes fluids to render with a white side overlay through transparent blocks

### ISSUE THREAD

**Issue by JieningYu** [Fabricators-of-Create/Create#265]
### Describe the Bug

The chocolate fluid is white-sided.

### Reproduction Steps

1. place a bucket of chocolate
2. Use a glass/sign or other block to block the side of still chocolate fluid block.

### Expected Result

The texture of side of the chocolate should be normal texture but not white.

### Screenshots and Videos

<img width="457" alt="Screenshot@20220429102435" src="https://user-images.githubusercontent.com/61787533/165876686-436b2f48-99dd-476b-b3b5-c6213029c1c4.png">

### Operating System

macOS 12.2 Beta (21D5039d)

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

- sodium
- indium
- fabric api

**Comment by JieningYu** [comment]
The bug still present with build 524.

**Comment by TropheusJ** [comment]
Sodium reimplements the fluid renderer, and it seems indium does not account for overlay sprites.

**Comment by TropheusJ** [comment]
This has been tracked down to an issue with colormatic, which has been reported.

**Comment by TropheusJ** [comment]
...I closed the wrong issue, I meant #255. This is not colormatic related, that is.

**Comment by AlphaMode** [comment]
![image](https://user-images.githubusercontent.com/26313415/201446701-d7f609c9-41b6-442c-9429-8896ec4fe2f7.png)
This seems to been fixed
