### ISSUE TITLE
Fluid Tanks Quit Transferring After Save/Load In Single Player

### ISSUE THREAD

**Issue by digitaltrucker** [Fabricators-of-Create/Create#268]
### Describe the Bug

As the title states, saving a reloading a world cause fluid tanks to stop filling or emptying even though the pump is working.  This is confirmed by using the windowed variant of fluid pipes to see fluid flow.  The only fix is to break and replace the fluid tanks, then they start working again.

This was pumping lava, btw.

### Reproduction Steps

1.  Build a quick pumping system to pump lava into a fluid tank.
2.  Save and exit the world.
3.  Reload the world.
4.  Fluid tank stops filling/emptying.
5.  Break and replace the fluid tank(s), the system starts working again.
...

### Expected Result

Fluid tank systems continue to work after save/exit/reload.

### Crash Report or Log

https://pastebin.com/anQQ1kWQ

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

See linked log.

### Additional Context

Using Fabric Loader 0.14.3

**Comment by TropheusJ** [comment]
can you provide a screenshot of your setup?

**Comment by digitaltrucker** [comment]
It's about as basic as it gets, I just set it up for testing.
![2022-04-30_19 03 42](https://user-images.githubusercontent.com/77534286/166126657-e616161f-03ab-4361-b4ef-1b75073989d4.png)
