### ISSUE TITLE
Small issue with redstone link

### ISSUE THREAD

**Issue by CJendantix** [Fabricators-of-Create/Create#271]
### Describe the Bug

If I put a redstone link in any frequency of a redstone link, you can barely see it.

### Reproduction Steps

1. Place a redstone link
2. Put a redstone link in any frequency of the redstone link

### Expected Result

I expected the redstone link to be completely visible in the frequency area

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/75325223/166152077-47b690f7-b722-4bc8-9f06-d8636979436a.png)

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
Identical to on forge
