### ISSUE TITLE
Item dissapears when block is blocking an upwards chute 

### ISSUE THREAD

**Issue by CJendantix** [Fabricators-of-Create/Create#272]
### Describe the Bug

Item dissapears when block is blocking an upwards chute

### Reproduction Steps

1. place a creative motor (get any rotational force)
2. get rotational force to an upwards pushing encased fan
3. attach some chutes to the encased fan going diagonally
4. put a chest or other block on the top of the chute
5. input an item at the bottom of the chute

### Expected Result

I expected the item to enter something like a chest, or if it was a normal block I expected the item to appear after I break the block.

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
can I see a screenshot of a setup that causes this?

**Comment by anim4trix** [comment]
![2022-05-03_12 47 48](https://user-images.githubusercontent.com/96380963/166433988-90662078-c340-4ebd-8bc5-d744d14089cf.png)
