### ISSUE TITLE
Create Crashes when loaded with Paradise Lost (Aether fabric port)

### ISSUE THREAD

**Issue by EmpressAutumn** [Fabricators-of-Create/Create#273]
### Describe the Bug

When I try to launch the game with both Create and Paradise Lost, the game fails to load and crashes before reaching the loading screen.

### Reproduction Steps

1. install Fabric API 0.51.1 (latest)
2. install Create 0.4.1+534 (latest)
3. install Paradise Lost 1.6.8 (latest)
4. launch game with Fabric Loader 0.13.3

### Expected Result

The game should load to the title screen rather than crashing.

### Crash Report or Log

https://pastebin.com/ut7Vy5dC

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Fabric API, Paradise Lost

**Comment by EmpressAutumn** [comment]
I'm not sure if this is a Create issue or an issue with Paradise Lost, so I'm going to put the issue on both repositories.

**Comment by TropheusJ** [comment]
the error does not mention Create at all, test without it.

**Comment by SollyW** [comment]
This is likely caused by the aether's boreal wisteria leaf shader

**Comment by StockiesLad** [comment]
Close this thead, I put it in a modpack with paradise and nobody reports issues

**Comment by TropheusJ** [comment]
will close tomorrow if no response from author
