### ISSUE TITLE
KubeJS compat and better tags

### ISSUE THREAD

**Issue by StockiesLad** [Fabricators-of-Create/Create#275]
### Describe the Suggestion

I was trying to get create to work with other mods' ores, ingots etc. Things like getting the crushing wheel to properly process other ores. All the trial and error to no avail. My concern is that since create (fabric) uses forge tags, it doesn't work at all with anything else besides vanilla. I already assume you guys are aware of this and I'm curious about the plans of mitigation.

**Comment by Arathain** [comment]
if you want it to work with other mods, I'd think that editing the base tags yourself would be viable, seeing as none of this is hardcoded

**Comment by JieningYu** [comment]
try CreatePlus.
https://modrinth.com/mod/createplus
it can fix issue about tags.

**Comment by JieningYu** [comment]
> try CreatePlus. https://modrinth.com/mod/createplus it can fix issue about tags.

https://github.com/Fabricators-of-Create/Create/pull/245
Pull Request about this

**Comment by StockiesLad** [comment]
> try CreatePlus. https://modrinth.com/mod/createplus it can fix issue about tags.

trying it now.

**Comment by StockiesLad** [comment]
Oh wait, its for quilt exclusively...
Does it really have to be exclusive for quilt?

**Comment by JieningYu** [comment]
It has a datapack format.
https://cdn.modrinth.com/data/svgZx0UN/versions/1.0-beta2/CreatePlus%20Datapack.zip

**Comment by StockiesLad** [comment]
oh ok thanks!

**Comment by StockiesLad** [comment]
> 

Any plans to have fabric support in your mod addon.

**Comment by JieningYu** [comment]
> > 
> 
> Any plans to have fabric support in your mod addon.

It's easy to port(you can port yourself or use Quilt. Most of Fabric mods can play on Quilt.

**Comment by StockiesLad** [comment]
> > > 
> > 
> > 
> > Any plans to have fabric support in your mod addon.
> 
> It's easy to port(you can port yourself or use Quilt. Most of Fabric mods can play on Quilt.

quilt is very buggy. I'm building from source anyways so it's all good.

**Comment by JieningYu** [comment]
> > > > 
> > > 
> > > 
> > > Any plans to have fabric support in your mod addon.
> > 
> > 
> > It's easy to port(you can port yourself or use Quilt. Most of Fabric mods can play on Quilt.
> 
> quilt is very buggy. I'm building from source anyways so it's all good.

note that the source doesn't include createplus-core(datapack) by default.

**Comment by StockiesLad** [comment]
[B#744]  Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on port_lib$clientStartTickEvent could not find any targets matching 'Lnet/minecraft/class_1657;tick()V' in net.minecraft.class_1657. Using refmap porting_lib-refmap.json [PREINJECT Applicator Phase -> porting_lib.mixins.common.json:PlayerMixin from mod porting_lib -> Prepare Injections ->  -> handler$zeg000$port_lib$clientStartTickEvent(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]


It spits out this error when I use the compiled version.

**Comment by JieningYu** [comment]
> 



> [B#744] Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on port_lib$clientStartTickEvent could not find any targets matching 'Lnet/minecraft/class_1657;tick()V' in net.minecraft.class_1657. Using refmap porting_lib-refmap.json [PREINJECT Applicator Phase -> porting_lib.mixins.common.json:PlayerMixin from mod porting_lib -> Prepare Injections -> -> handler$zeg000$port_lib$clientStartTickEvent(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
> 
> It spits out this error when I use the compiled version.

how you compile?

**Comment by StockiesLad** [comment]
I changed the port lib hash to the new one.

**Comment by JieningYu** [comment]
createplus don't need port lib and you can use the latest version of create fabric directly.

**Comment by StockiesLad** [comment]
I was talking about ur PR of create

**Comment by JieningYu** [comment]
fetched upstream

**Comment by StockiesLad** [comment]
> fetched upstream

Is it getting merged now? Or is it already merged.

**Comment by StockiesLad** [comment]
oh i saw...

**Comment by StockiesLad** [comment]
[latest.log](https://github.com/Fabricators-of-Create/Create/files/8629711/latest.log)
It causes a porting lib issue tho...

**Comment by StockiesLad** [comment]
Player Mixin is failing

**Comment by JieningYu** [comment]
?

**Comment by JieningYu** [comment]
if it's a mixin issue, report it to [TropheusJ](https://github.com/Fabricators-of-Create/Create/commits?author=TropheusJ)

**Comment by StockiesLad** [comment]
> if it's a mixin issue, report it to [TropheusJ](https://github.com/Fabricators-of-Create/Create/commits?author=TropheusJ)

ok

**Comment by TropheusJ** [comment]
KubeJS support: https://www.curseforge.com/minecraft/mc-mods/kubejs-create
we will be handling tags with the 1.19 update.

**Comment by JieningYu** [comment]
pog

**Comment by TropheusJ** [comment]
tag change happened
