### ISSUE TITLE
Crash - Flywheel - handle is not valid. 

### ISSUE THREAD

**Issue by TheCherry** [Fabricators-of-Create/Create#286]
### Describe the Bug

Seems a problem with immersive portals, I removed the mod and then its works.
The strange thing is, its worked for a long time and after I loaded today my save, the game crashes.
And in the loaded area is no portal at all.

Crashoverview: https://crashy.net/6zezNy24hbuQZDlqz3l7
Crashreport: https://bytebin.lucko.me/brpg8nQhKb

Multi-MC Instance (Includes mods and the savefile):  https://risegaming.de/test_for_create_crash.zip

### Reproduction Steps

Just load the included savefile with the mods and the game crashs after some seconds.

### Expected Result

not to crash.

### Operating System

Windows 10

### Mod Version

555

### Minecraft Version

1.18.2

### Other Mods

advancementinfo-1.18.2-fabric0.47.10-1.3.1.jar
architectury-4.2.50.jar
autoconfig1u-3.4.0.jar
badpackets-fabric-0.1.2.jar
balm-fabric-3.0.0+0.jar
bclib-1.4.5.jar
better-end-1.1.0.jar
BetterF3-1.2.4-Fabric-1.18.2.jar
betterfpsdist-fabric-1.18-1.7.jar
better-nether-6.1.1.jar
charmonium-fabric-1.18-4.0.0.jar
cloth-config-6.2.57-fabric.jar
create-mc1.18.2_v0.4.1+555.jar
dashloader-def-3.1.1+1.18.jar
EssentialGUI-1.7.3+1.18.2.jar
fabric-api-0.51.1+1.18.2.jar
fabric-language-kotlin-1.7.4+kotlin.1.6.21.jar
feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1.jar
immersive-portals-1.3.6-mc1.18.2-fabric.jar
indium-1.0.3+mc1.18.2(1).jar
inventorio-1.18-fabric-1.7.0.jar
iris-mc1.18.2-1.2.4-build.38.jar
iron-jetpacks-0.4.3.jar
item-filters-fabric-1802.2.7-build.25.jar
kubejs-fabric-1802.5.1-build.372.jar
lambdynamiclights-2.1.0+1.17.jar
light-overlay-6.0.5.jar
malilib-fabric-1.18.2-0.12.1.jar
megane-7.5.1.jar
Modern-Industrialization-1.1.1.jar
modget-minecraft-0.4.3+1.17.jar
modmenu-3.2.1.jar
mostructures-1.4.2+1.18.2.jar
mousewheelie-1.8.8+mc1.18.2.jar
no-mob-farm-1.6.2.jar
notenoughcrashes-4.1.6+1.18.2-fabric.jar
pal-1.5.1.jar
Patchouli-1.18.2-67-FABRIC.jar
phosphor-fabric-mc1.18.x-0.8.1.jar
probejs-2.8.0-fabric.jar
quilt-loading-screen-2.2.1+1.17.jar
repurposed_structures_fabric-4.1.6+1.18.2.jar
rhino-fabric-1801.1.9-build.135.jar
RoughlyEnoughItems-8.1.457.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
TechReborn-5.2.0-beta.3.jar
Terralith_v2.2.1a.jar
toms_storage_fabric-1.18.2-1.3.0.jar
world-of-imagination-1.0.1.jar
wraith-waystones-2.5.0.jar
wthit-fabric-4.10.1.jar
Xaeros_Minimap_22.7.0_Fabric_1.18.2.jar
XaerosWorldMap_1.21.2_Fabric_1.18.2.jar
YungsApi-1.18.2-Fabric-2.0.8.jar
YungsBetterDungeons-1.18.2-Fabric-2.1.0.jar
YungsBetterMineshafts-1.18.2-Fabric-2.1.1.jar
YungsBetterStrongholds-1.18.2-Fabric-2.1.1.jar
YungsBridges-1.18.2-Fabric-2.1.0.jar
YungsExtras-1.18.2-Fabric-2.1.0.jar

**Comment by Skidamek** [comment]
Try the new version of immersive portals
https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v1.3.7-1.18

**Comment by TheCherry** [comment]
Released 3 hours ago - lol
And yes that worked. Thanks!
