### ISSUE TITLE
Gradle Import Failed, Fresh Clone.

### ISSUE THREAD

**Issue by Stereo528** [Fabricators-of-Create/Create#29]
### Describe the Bug

Gradle fails to "resolve all files for configuration `:classpath`" with `Could not resolve io.github.juuxel:loom-quiltflower-mini`

Java 17 is set as my Project SDK in IntelliJ IDEA Ultimate, IntelliJ Downloaded Gradle 7.3.1 upon opening the project

If I understand the log (linked below) correctly it is complaining about not having Gradle 7.3.1 and something about Needing Java 8 despite being a project and mod in Java 17

### Reproduction Steps

I have literally no clue how to reproduce this...

### Expected Result

Gradle should import everything fine and work. Not sure how else to explain it.

### Crash Report or Log

https://pastebin.com/c2Pn0xdb (Full IntelliJ Log)

### Operating System

Windows 10

### Mod Version

0.4.0a

### Minecraft Version

1.18.1

### Forge Version

Fabric Loader Version 12.11

### Additional Context

Fresh clone, was going to possibly do some bug hunting and fix a few things, been bored and wanted to code...

**Comment by Stereo528** [comment]
Upon deleting `gradle` folder to see if that would fix anything, it seems Intellij might be downloading Gradle 7.1? 
![image](https://user-images.githubusercontent.com/52116771/146107793-64fa6557-5f00-4d8b-89ef-f53259621bd3.png)
Not sure if this could be the issue.

Edit: It seems now that all of the `(required '7.3.1')` bits now say `(required '7.1')` also

**Comment by Stereo528** [comment]
fun fact: IntelliJ had set my Gradle JVM in Build Tools > Gradle to Java despite having never using Java 8, thanks to JAVA_HOME and IntelliJ for ruining my fun :trollface:. Worst part is that I'm pretty sure my Java Home was set to Java 17 before ever opening IntelliJ for the first time, which I just recently installed OS sooooo.

consider this being a "me being dumb" and "IntelliJ being dumb" moment

**Comment by AlphaMode** [comment]
Sigh* please don't make issues regarding getting the mod running we are not here to tell you how to use gradle we are here to fix bugs

**Comment by Stereo528** [comment]
I am aware. I've seen the other issues, my bad. I was also conversing with jay (who, tbf, did not give input on making an issue on github, that was all me) but did help me resolve it. Again "consider this being a 'me being dumb' moment".
