### ISSUE TITLE
Incompatibility with REI Dark Mode

### ISSUE THREAD

**Issue by surprisedpika** [Fabricators-of-Create/Create#290]
### Describe the Bug

When viewing recipes through REI with Dark Mode enabled, certain item boxes are not correctly rendered as dark.

### Reproduction Steps

1. Make sure REI and Create are downloaded
2. On the REI settings (right of search bar) select "Dark Theme"
3. View any recipe type added by Create using REI

### Expected Result

The graphics should all update to a dark theme.

### Screenshots and Videos

https://user-images.githubusercontent.com/82579156/168845477-e4786892-6f1b-49ed-98cf-760bca945e0c.mp4

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

REI

**Comment by JieningYu** [comment]
need to redo the textures used for rei because the og texture is white-gray based.

**Comment by labaredaf** [comment]
I made a resourcepack that """fixes""" it (only use it if REI's dark theme is enabled, as it overrides the textures and would make light theme look weird)
[Create REI Dark Theme.zip](https://github.com/Fabricators-of-Create/Create/files/8711265/Create.REI.Dark.Theme.zip)

**Comment by maximumpower55** [comment]
> I made a resourcepack that fixes it [Create REI Dark Theme.zip](https://github.com/Fabricators-of-Create/Create/files/8711265/Create.REI.Dark.Theme.zip)

Could i pr this?

**Comment by JieningYu** [comment]
> > I made a resourcepack that fixes it [Create REI Dark Theme.zip](https://github.com/Fabricators-of-Create/Create/files/8711265/Create.REI.Dark.Theme.zip)
> 
> Could i pr this?

but this pack override the original texture which is hacky.

**Comment by labaredaf** [comment]
> > > I made a resourcepack that fixes it [Create REI Dark Theme.zip](https://github.com/Fabricators-of-Create/Create/files/8711265/Create.REI.Dark.Theme.zip)
> > 
> > 
> > Could i pr this?
> 
> but this pack override the original texture which is hacky.

Yeah, it's only supposed to be used if REI's dark theme is going to be enabled all the time, in case a full fix is done feel free to use my textures though

**Comment by JieningYu** [comment]
Need to add a condition to detect if dark mode is enabled.

**Comment by maximumpower55** [comment]
Okay, And a fix to allow for both light and dark mode textures would just be a simple if statement

**Comment by maximumpower55** [comment]
The more i think about this, this is a issue with upstream (forge) create too, so i don't think we should fix it

**Comment by maximumpower55** [comment]
Nevermind im dumb, JEI doesn't have dark mode

**Comment by Skidamek** [comment]
> Nevermind im dumb, JEI doesn't have dark mode




But rei is available for forge too

**Comment by maximumpower55** [comment]
> > Nevermind im dumb, JEI doesn't have dark mode
> 
> But rei is available for forge too

Yes but literally no one uses that

**Comment by electricsteve** [comment]
> > > Nevermind im dumb, JEI doesn't have dark mode
> > 
> > 
> > But rei is available for forge too
> 
> Yes but literally no one uses that

that isn't true, it is used in modpacks like FTB SB3. Mainly for grouping of items.

**Comment by electricsteve** [comment]
> I made a resourcepack that """fixes""" it (only use it if REI's dark theme is enabled, as it overrides the textures and would make light theme look weird) [Create REI Dark Theme.zip](https://github.com/Fabricators-of-Create/Create/files/8711265/Create.REI.Dark.Theme.zip)

I am currently fixing this issue, so can i use your textures? edit: @labaredaf

**Comment by TropheusJ** [comment]
see #1616
