### ISSUE TITLE
crash when using rei on some recipes

### ISSUE THREAD

**Issue by redstonek** [Fabricators-of-Create/Create#293]
### Describe the Bug

It crashed after i looked at a recipe of some item. After trial and error i figured out that it crashes when I check the usage of redstone and switch the tab to automated brewery (?).

### Reproduction Steps

1. Use create fabric with REI.
2. Check the usage of redstone.
3. Change the tab to automated potion brewing.
4.  Crash
...

### Expected Result

no crash

### Crash Report or Log

https://pastebin.com/fLaMFjD7

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by redstonek** [comment]
Actually the crash seems to happen also with other items and the stout filling tab. I think it's something with the liquid rendering.

**Comment by DarianLStephens** [comment]
I personally didn't have any crashes when scrolling through all Redstone uses in Potion Brewing.
I'm using the version currently on Curseforge.
Maybe a mod conflict?

**Comment by redstonek** [comment]
That's possible, because I just plugged create and some other mods into a light optimization modpack (fabulously optimized) and maybe it doesn't like sodium or something.

**Comment by SplendidAlakey** [comment]
Try removing Colormatic. I had a similar crash with coloured water from other mods with it installed. Should be fixed in the next update: https://github.com/kvverti/colormatic/issues/94

**Comment by TropheusJ** [comment]
yep, colormatic. duplicate of #255
