### ISSUE TITLE
Fabric mod doesnt work

### ISSUE THREAD

**Issue by GameSterDamian** [Fabricators-of-Create/Create#294]
### Describe the Bug

When I install the mod on feather client with the fabric version, it doesn't work...

### Reproduction Steps

1. Install on Feather Client (Not sure about other clients)
2. Open MC

### Expected Result

Game crash

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by AlphaMode** [comment]
Fabric and quilt are the only supported loaders

**Comment by IMS212** [comment]
And Optifine is not supported.
