### ISSUE TITLE
REI Oversights

### ISSUE THREAD

**Issue by Notenoughmail** [Fabricators-of-Create/Create#297]
### Describe the Bug

For splashing (and possibly other fan processing types as well) the output percentage does not display in the tooltip, but the background is still checkerboard to indicate it is a percentage.

In addition, for splashing recipes, REI does not correctly support up to six recipes, like JEI does on Forge

### Reproduction Steps

1. Create a splashing recipe via datapacks/kubejs/etc. with more than three outputs and a chance output
2. Observe the recipe via REI

### Expected Result

The hover tooltip for outputs should have their percent chance of output shown and recipes with more than three outputs should rearrange them to be two columns next to each other

### Screenshots and Videos

As seen in my testing:
![bug](https://user-images.githubusercontent.com/78008321/168970966-d2b3858c-7071-4f49-a03c-86d32f33b0f7.png)
Sequenced assembly correctly displaying percent chance output on hover:
![no_bug](https://user-images.githubusercontent.com/78008321/168973410-d3155c1a-4011-44fc-a2cf-78555bc6ae18.png)
Simi's statement and demonstration of expected behavior:
![dev](https://user-images.githubusercontent.com/78008321/168973875-9c7e1f53-b479-41d4-8ff6-e6afd299f8b1.png)

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Additional Context

Great job on getting the port done! Been enjoying it with some Fabric mods I haven't used before and am having a blast!

**Comment by michlbro** [comment]
For the output percentage issue, I believe it has something to do with REI (Someone has made this issue [here](https://github.com/shedaniel/RoughlyEnoughItems/issues/850))

**Comment by Notenoughmail** [comment]
Update: after installing (and then removing b/c crashes) some mods, the percentages show up again for some reason

**Comment by Notenoughmail** [comment]
Update 2: The percentages are only shown for some recipes
https://youtu.be/0xUQ5rlIjIA

**Comment by michlbro** [comment]
Yep, if you click on the hyper link someone has said its not just Create that has this problem but also tinkers construct.

Edit: On REI’s github page, it says that this will be fixed in the next release.

**Comment by TropheusJ** [comment]
see #1616
