### ISSUE TITLE
the games crash in the middle of exploration

### ISSUE THREAD

**Issue by bubble13699** [Fabricators-of-Create/Create#298]
[crash-2022-05-19_02.24.43-server.txt](https://github.com/Fabricators-of-Create/Create/files/8719114/crash-2022-05-19_02.24.43-server.txt)

i never had any crash before in my modded minercaft world. but when i installed the create mod(fabric) the games just crash me out when i was exploring in the overworld.
i have a lot of mods installed in here, so can you tell me what mods cause the error?

**Comment by Papaturts** [comment]
A crash report would help out, if your able to post one
also a list of mods could help to narrow it down

**Comment by puldzian** [comment]
i have the same exact fragment in my crash log: 
`java.lang.ClassCastException: class party.lemons.biomemakeover.entity.mutipart.EntityPart cannot be cast to class io.github.fabricators_of_create.porting_lib.entity.PartEntity (party.lemons.biomemakeover.entity.mutipart.EntityPart and io.github.fabricators_of_create.porting_lib.entity.PartEntity are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1477089c)`
in my case the crash happens in the specific place in the jungle biome (near water?) ant it doesnt happen when i remove create from the mod folder. seems i can safely explore other biomes. 

looks like an incompatibility between create-mc1.18.2_v0.4.1+565 and biomemakeover-FABRIC-1.18.2-1.4.20?

**Comment by bubble13699** [comment]
> A crash report would help out, if your able to post one also a list of mods could help to narrow it down
![mods 5](https://user-images.githubusercontent.com/101046132/169122795-856cf8ec-3fb2-4e83-82e7-b81399a53318.png)
![mods 4](https://user-images.githubusercontent.com/101046132/169122810-7d2abdbf-2a5f-46fc-8b4e-b50e8befe29a.png)
![mods 3](https://user-images.githubusercontent.com/101046132/169122819-47c3fd75-68ed-4b9d-9d3d-9a11269d5b32.png)
![mods 2](https://user-images.githubusercontent.com/101046132/169122825-4248cd35-f613-4c43-8ccf-af52b7d16202.png)
![mods 1](https://user-images.githubusercontent.com/101046132/169122835-429da264-d40a-4060-be1b-f00205a1f068.png)
![mods 6](https://user-images.githubusercontent.com/101046132/169122846-2012e25e-7193-45bc-8ea4-51c071132ae3.png)
 
that's all of the mods, and it's a lot.

**Comment by bubble13699** [comment]
> i have the same exact fragment in my crash log: `java.lang.ClassCastException: class party.lemons.biomemakeover.entity.mutipart.EntityPart cannot be cast to class io.github.fabricators_of_create.porting_lib.entity.PartEntity (party.lemons.biomemakeover.entity.mutipart.EntityPart and io.github.fabricators_of_create.porting_lib.entity.PartEntity are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1477089c)` in my case the crash happens in the specific place in the jungle biome (near water?) ant it doesnt happen when i remove create from the mod folder. seems i can safely explore other biomes.
> 
> looks like an incompatibility between create-mc1.18.2_v0.4.1+565 and biomemakeover-FABRIC-1.18.2-1.4.20?

ahhh, so it's maybe the incompatibility between create-mc1.18.2_v0.4.1+565 and biomemakeover-FABRIC-1.18.2-1.4.20. i guess i can try to play the mod(create) without biomemakeover mod. let's see if the game still crash or not.

**Comment by SplendidAlakey** [comment]
For what it's worth I can't reproduce this issue with Create + Biome Makeover, as well as many other mods you have. I also spawned all the possible entities from Biome Makeover and none caused the crash either.

On an unrelated note, you have 2 mods that don't work together - CIT Resewn and Eating Animation, the latter breaks CITs in both CIT Resewn and Optifine.

**Comment by bubble13699** [comment]
> For what it's worth I can't reproduce this issue with Create + Biome Makeover, as well as many other mods you have. I also spawned all the possible entities from Biome Makeover and none caused the crash either.
> 
> On an unrelated note, you have 2 mods that don't work together - CIT Resewn and Eating Animation, the latter breaks CITs in both CIT Resewn and Optifine.

i got the crash when i was near a structure. kinda like a swamp hut but in a birch version. i was able to enter the world again and spawned in near the structure where my game crashed. but when i try to walk around the game crashed again, and when i tried to enter the world again, the screen is just go black and then crashed me out. dunno wht happened there.

**Comment by SplendidAlakey** [comment]
> i get the crash when i was near a structure. kinda like a swamp hut but in a birch version. i was able to enter the world again and spawned in near the structure where my game crashed. but when i try to walk around the game crashed again, and when i tried to enter the world again, the screen is just go black and then crashed me out. dunno wht happened there.

Biome Makeover adds only 3 structures, sunken ruins, overhauled mansion and ghost town. I teleported to all of them, none caused the crash. Try loading just Create and Biome Makeover, then do /locate biomemakeover:X, where X is the structure's name, teleport to it and walk around. That way you can test whether or not Create conflicts with BM structures.

Edit: I also went ahead and tested a birch witch hut from Repurposed structures, still no crash.

**Comment by JieningYu** [comment]
Try summon all entities from Biome Makeover.

**Comment by bubble13699** [comment]
> > i get the crash when i was near a structure. kinda like a swamp hut but in a birch version. i was able to enter the world again and spawned in near the structure where my game crashed. but when i try to walk around the game crashed again, and when i tried to enter the world again, the screen is just go black and then crashed me out. dunno wht happened there.
> 
> Biome Makeover adds only 3 structures, sunken ruins, overhauled mansion and ghost town. I teleported to all of them, none caused the crash. Try loading just Create and Biome Makeover, then do /locate biomemakeover:X, where X is the structure's name, teleport to it and walk around. That way you can test whether or not Create conflicts with BM structures.
> 
> Edit: I also went ahead and tested a birch witch hut from Repurposed structures, still no crash.

test it out with create, biomemakeover, terralith and no error or crash on that exact place (it was the sunken ruins).

i tried to restore all the mods back n try to re-create the world again and see if the crash occur and yep it does on the sunken ruins...dunno why.

**Comment by SplendidAlakey** [comment]
> test it out with create, biomemakeover, terralith and no error or crash on that exact place (it was the sunken ruins).
> 
> i tried to restore all the mods back n try to re-create the world again and see if the crash occur and yep it does on the sunken ruins...dunno why.

~~You can try figuring out the exact combination of mods that cause the crash by adding mods in groups instead of all at once. To make things easier you can exclude all the mods from this list: https://gist.github.com/Footage2-Amply-Pounce/b56b0424ac98deeb574091adb8e9d4fa (these are the mods I tried to replicate the issue with and everything was fine). Or you can load all your mods, minus any that are on my list, and go down from there. Also see if your game still crashes with your mods, but without those that are on the list. Edit: but leave Create and Biome Makeover in ofc.~~

Ignore that, see comment below.

**Comment by AlphaMode** [comment]
I already know the issue it's the stone golem from biome makeover
