### ISSUE TITLE
Crashing on world creation

### ISSUE THREAD

**Issue by SalmaelNox** [Fabricators-of-Create/Create#301]
### Describe the Bug

After adding Create to my modlist, my game crashes whenever I try to load or create a world.

### Reproduction Steps

1.Launch Minercraft
2.Try loading or creating a world

### Expected Result

The world is created/loads normally

### Crash Report or Log

https://paste.ee/p/IVp30

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

  [✔️] appleskin-fabric-mc1.18.2-2.4.0
  [✔️] architectury-4.4.54
  [✔️] balm-fabric-3.0.0+0
  [✔️] bclib-1.4.5
  [✔️] bedspreads-fabric-1.5.0-1.18
  [✔️] betteranimalsplus-1.18.2-11.0.5-fabric
  [✔️] better-end-1.1.0
  [✔️] BetterF3-1.2.4-Fabric-1.18.2
  [✔️] better-nether-6.1.1
  [✔️] Bookshelf-Fabric-1.18.2-13.0.13
  [✔️] Clumps-fabric-1.18.2-8.0.0+8
  [✔️] cookingforblockheads-forge-1.18.2-12.0.1
  [✔️] create-mc1.18.2_v0.4.1+565
  [✔️] Croptopia-1.18.2-FABRIC-1.8.3
  [✔️] Decorative+Blocks-forge-1.18.2-2.1.0
  [✔️] effective-1.2.1
  [✔️] elementalcreepers-1.4.2+1.18.2
  [✔️] EnchantingInfuser-v3.2.0-1.18.2-Fabric
  [✔️] EnchantmentDescriptions-Fabric-1.18.2-10.0.3
  [✔️] ExplorersCompass-1.18.2-2.1.0-fabric
  [✔️] extrakeybinds-1.18-0.1.0
  [✔️] extraorigins-1.18-10
  [✔️] fabric-api-0.51.1+1.18.2
  [✔️] flan-1.18.2-1.7.6-fabric
  [✔️] ForgeConfigAPIPort-v3.2.0-1.18.2-Fabric
  [✔️] genesis-1.18.2-1.0.1
  [✔️] golemsgalore-1.2.1+1.18.2
  [✔️] gravestone-1.18.2-1.0.1
  [✔️] illuminations-1.10.4
  [✔️] immersive-portals-1.3.6-mc1.18.2-fabric
  [✔️] impaled-1.1.1
  [✔️] journeymap-1.18.2-5.8.2-fabric
  [✔️] just-end-anchor-1.0.2-1.18
  [✔️] lank
  [✔️] medieval-origins-1.18.x-4.0.2
  [✔️] moborigins-1.8.1
  [✔️] mythicmetals-0.13.1
  [✔️] NaturesCompass-1.18.2-2.0.3-fabric
  [✔️] Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-11
  [✔️] Origins-1.18.2-1.4.1
  [✔️] Origins-Classes-1.18.2-1.3.0
  [✔️] Patchouli-1.18.2-67-FABRIC
  [✔️] Pehkui-3.2.2+1.14.4-1.19
  [✔️] phosphor-fabric-mc1.18.x-0.8.1
  [✔️] PuzzlesLib-v3.3.1-1.18.2-Fabric
  [✔️] RoughlyEnoughItems-8.1.449
  [✔️] sophisticatedbackpacks-1.18.2-3.15.17.559
  [✔️] spyglass-improvements-1.2+mc1.18.2+fabric
  [✔️] TerraBlender-fabric-1.18.2-1.1.0.99
  [✔️] Terralith_v2.2.1a
  [✔️] victus-0.1.10+1.18
  [✔️] waystones-fabric-1.18.2-10.0.0
  [✔️] worldedit-mod-7.2.10
  [✔️] wraith-alloy-forgery-2.0.13+1.18
  [✔️] xp_obelisk-0.3.8.r_for_1.18.x_Fabric

**Comment by Skidamek** [comment]
try update immersive portals https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v1.3.7-1.18

**Comment by SalmaelNox** [comment]
Thank you, it works perfectly now !
