### ISSUE TITLE
Native QSL support

### ISSUE THREAD

**Issue by JieningYu** [Fabricators-of-Create/Create#302]
### Describe the Suggestion

this could be hard but it will be meaningful

**Comment by PepperCode1** [comment]
Why?

**Comment by JieningYu** [comment]
Will Quilted Fabric Api stop developing?

**Comment by AlphaMode** [comment]
We dont need to support quilt natively like this it would just be a waste of time. Quilt still supports loading fabric mods there is no reason for us to put in the extra time and effort for this
