### ISSUE TITLE
Crash with Table Top Craft

### ISSUE THREAD

**Issue by SplendidAlakey** [Fabricators-of-Create/Create#304]
### Describe the Bug

When Create is installed together with [Table Top Craft](https://www.curseforge.com/minecraft/mc-mods/table-top-craft/files/3798199), the game will crash on startup.

### Reproduction Steps

1. Install both mods and launch the game
2. Crash after the Mojang logo

### Expected Result

No crash

### Crash Report or Log

https://gist.github.com/Footage2-Amply-Pounce/49cb302990ff54cc940dd0f06c7b51c5

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
[likely culprit](https://github.com/andrew0030/Table-Top-Craft/blob/1.18.2-Fabric/src/main/java/andrews/table_top_craft/mixins/ShaderInstanceMixin.java)

**Comment by SplendidAlakey** [comment]
It might actually be problematic with other mods as well, not just Create. Someone else reported a crash on the Table Top Craft github here: https://github.com/andrew0030/Table-Top-Craft/issues/8. Their log looks slightly different, but still references shaders. They do have Create installed, but I suspect it's going to crash with other mods as well. I should've tested TTC with other mods before reporting here. I just assumed it was a Create + TTC incompatibility because I saw PortingLib mentioned the most in my logs.

**Comment by GiantLuigi4** [comment]
> likely culprit

That’s actually my code
Is there a better way to do that?

Edit4: I mean yeah, I know I can use ModifyVar and whatnot, but back when I wrote that, I didn’t know that that existed, so I went with what I wrote there

Edit: for reference, that mixin was designed to fall back upon other mods that might do the same or similar things if other mods that do similar things are present

Edit2: and yes, it does succeed at falling back to other mods that do similar things, considering I believe architectury is doing the same thing as PortingLib, and it works fine with architectury

Edit3: just checked architectury, yeah it’s more or less the same thing

Edit5: this is infact unrelated to my mixin, it’s something else
Problem is, I don’t know what

[TTC#8](https://github.com/andrew0030/Table-Top-Craft/issues/8) however, is related to my mixin

Edit6: or hm… I fail to see how it’d throw a null pointer?

Edit7: that `likely culprit` Is meant to not require succeeding, but I should just rewrite it

**Comment by TropheusJ** [comment]
It replaces the ID indiscriminately, and I'm pretty sure that's causing this malformed shader location, causing the crash: `minecraft:shaders/core/s/core/glowing_shader.vsh` (note the `/s/`)
Porting lib accomplishes the same thing like [this](https://github.com/Fabricators-of-Create/Porting-Lib/blob/1.18.2/src/main/java/io/github/fabricators_of_create/porting_lib/mixin/client/ShaderInstanceMixin.java) and they likely conflict.

**Comment by GiantLuigi4** [comment]
yeah, I rewrote it a bit ago and it works now

it was just weird to me considering it worked fine with architectury despite architectury doing something very similar to what porting lib is doing

**Comment by SplendidAlakey** [comment]
Yep, it works now. Tested with Create and a whole lot of other mods. Thank you!
