### ISSUE TITLE
Schematic made external editor not working

### ISSUE THREAD

**Issue by MimiVRC** [Fabricators-of-Create/Create#308]
### Describe the Bug

I made a schematic in minecraft using create, this one works fine in the table, but if I make one with https://cubical.xyz/ and export it doesn't load in the schematic table. the empty schematic is just lost when pressing the checkmark

### Reproduction Steps

1. go to https://cubical.xyz/ and make something
2. export as nbt
3. put in schematic folder
4. try to load using an empty schematic in game
5. empty schematic is lost

### Expected Result

you get the schematic on the paper

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
do these schematics work on forge? can you provide a log?

**Comment by MimiVRC** [comment]
someone on forge tested it and it did work. I will need to get a log later but I thought I would let you know that it did seem to work on forge. that's when I came to post about it here

**Comment by IThundxr** [comment]
Works fine apart from grass blocks being grass, but thats probably a oversight on their side
