### ISSUE TITLE
Client is being sent null blockstates, causing crash

### ISSUE THREAD

**Issue by Oliver-makes-code** [Fabricators-of-Create/Create#310]
### Describe the Bug

When entering certain chunks, it causes my client to crash when playing on a dedicated server

### Reproduction Steps

1. join server
2. fly around for a bit

### Expected Result

It doesn't crash and plays noramlly

### Crash Report or Log

https://pastebin.com/DcrmrcZ3

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

https://olivermakesco.de/assets/mods.zip + create 

### Additional Context

I narrowed the crash down to create
I'm using Quilt Loader

**Comment by TropheusJ** [comment]
I don't understand how but the client is somehow being sent null blockstates from the server.

**Comment by Oliver-makes-code** [comment]
Huh, it looks like I'm just having an issue with registry sync in general, even without any mods, so it's not a create issue
