### ISSUE TITLE
Hose pully and mechanical pump crash with "infinite" liquid.

### ISSUE THREAD

**Issue by WaffleDevsAlt** [Fabricators-of-Create/Create#313]
### Describe the Bug

When using a hose pully and mechanical pump on an infinite lava pool (in my case) crashs the game if the liquid is considered infinite.

### Reproduction Steps

1.place hose pully
2.lower down
3.pump with mechanical pump
4. Crash

### Expected Result

Infinite liquid without crashes

### Operating System

Mac os 10.15 and win 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
Works fine on my side,
Can’t help without a log.

**Comment by WaffleDevsAlt** [comment]
Fixed in new updates
