### ISSUE TITLE
Both Flywheel and Enhanced Block Entities render, causing visual issues

### ISSUE THREAD

**Issue by SplendidAlakey** [Fabricators-of-Create/Create#316]
### Describe the Bug

When [EBE](https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities) and Create are installed together, chests and bells have broken lighting, which is very noticeable when you move around.

### Reproduction Steps

1. Install EBE and Create, leave Create settings on default, make sure "Enhanced chests" and "Enhanced bells" are on in EBE settings (should be on by default)
2. Place down a chest and a bell, move your cam or your character around
3. Observe broken shadows flickering all over the chest and the bell

### Expected Result

Smooth lighting on chests and bells.

### Screenshots and Videos

![2022-05-24_10 48 18](https://user-images.githubusercontent.com/86702831/169993436-1ca93f20-6fc5-4f31-a714-fefebac453a9.png)
![2022-05-24_10 48 21](https://user-images.githubusercontent.com/86702831/169993447-4713be5c-73ee-4197-9b55-476e9d6cf5ca.png)
![2022-05-24_10 48 46](https://user-images.githubusercontent.com/86702831/169993451-f4cfc40b-d8b7-460a-97c6-a5c80a310b7d.png)
![2022-05-24_10 48 51](https://user-images.githubusercontent.com/86702831/169993454-28e44307-1c35-4fce-822e-1a8471bc5044.png)

### Crash Report or Log

https://gist.github.com/SplendidAlakey/6e2481b63e0fa11783b8ba7d1a373ec1

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Additional Context

Setting /flywheel backend off solves the issue. Batching and instancing both produce the same broken lighting.

Setting "Enhanced chests" and "Enhanced bells" to off solves the issue, as it basically disables EBE.

Setting "Smooth lighting" to off doesn't solve the issue, but it becomes a lot less visible (not possible to capture with a screenshot, but can still see it when moving your cam/character in game).

Other block entities affected by EBE (shulker boxes, beds) don't have this issue.

**Comment by TropheusJ** [comment]
Both flywheel and EBE are rendering, making it happen twice, causing the effect

**Comment by SplendidAlakey** [comment]
Does Flywheel render it as baked block models as well, meaning EBE is redundant with Flywheel? And in any case is that something that needs to be fixed or is just a thing to keep in mind when using the 2 mods together?

**Comment by TropheusJ** [comment]
I’m not sure which would be better for performance, needs to be tested. Not sure how this could be fixed on the mod side, but for now I’d say that if you want performance, disable EBE. If you want resource packs features, disable flywheel.

**Comment by IThundxr** [comment]
This'll be fixed on flywheel's side eventually
