### ISSUE TITLE
Game crashes when using Schematics or Schematicannon 

### ISSUE THREAD

**Issue by KevinKharma1** [Fabricators-of-Create/Create#317]
### Describe the Bug

When I use either Schematic or Schematicannon, my game crashes.

### Reproduction Steps

Schematics:
1. After selecting both positions and naming the schematic, upon leaving the menu, the game crashes.
Schematicannon: After leaving the menu (Not even clicking anything), the game crashes.

### Expected Result

I expect both items to work as intended.

### Operating System

macOS Monterey Version 12.3.1

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

3dskinlayers-fabric-1.4.4-mc1.18.2.jar
accurate-block-placement-1.0.12.jar
advanced-xray-fabric-1.18.2-1.0.0-build.11.jar
AmbientEnvironment-fabric-1.18.2-7.0+19.jar
AmbientSounds_FABRIC_v5.0.16_mc1.18.2.jar
These are all the mods I had Installed when the crash happen:
appleskin-fabric-mc1.18.2-2.4.0.jar
architectury-4.2.50.jar
artifacts-7.0.3+fabric.jar
Autofish-0.9.4-fabric-mc1.18.jar
AutoRegLib-1.7-53.jar
autorun-1.18.X-0.4.0.jar
AxesAreWeapons-1.5.1-fabric-1.17.1.jar
balm-fabric-3.0.0+0.jar
bclib-1.4.5.jar
BetterF3-1.2.5-Fabric-1.18.2.jar
betterfoliage-3.0.3.jar
bettermounthud-1.1.4.jar
cloth-api-3.2.64.jar
cloth-config-6.2.57-fabric.jar
collective-fabric-1.18.x-4.26.jar
Controlling-fabric-1.18.2-9.0+19.jar
create-mc1.18.2_v0.4.1+586.jar
CreativeCore_FABRIC_v2.6.10_mc1.18.2.jar
customfov-fabric-1.4.1-1.18.1.jar
DisableCustomWorldsAdvice-2.0.jar
dynamic-fps-2.1.0.jar
easiervillagertrading-1.18.2-fabric0.47.10-1.5.4.jar
eating-animation-1.6.jar
enhanced_attack_indicator-1.0.3+1.18.jar
entityculling-fabric-mc1.18-1.5.1.jar
fabric-api-0.51.1+1.18.2.jar
fabric-language-kotlin-1.7.4+kotlin.1.6.21.jar
fabric-tree-chopper-0.8.5.jar
farmers-delight-fabric-0.2.1.jar
ForgeConfigAPIPort-v3.2.0-1.18.2-Fabric.jar
FPS-Monitor-1.18-1.2.1-Fabric.jar
freecam-1.0.6+1.18.jar
grind-enchantments-1.6.1+1.18.2.jar
grindstonesharpertools-fabric_1.18.x-1.6.jar
guiclock-fabric_1.18.x-3.0.jar
Iceberg-1.18.2-fabric-1.0.38.jar
indium-1.0.3+mc1.18.2.jar
interactic-0.1.10+1.18.jar
InventoryHUD-fabric-[1.18]+-3.4.2.jar
iris-mc1.18.2-1.2.4-build.38.jar
item-model-fix-1.0.3+1.18.jar
ItemBorders-1.18-fabric-1.1.5.jar
itemsortermod-fabric-1.18.2-1.10.0.jar
lanterns-belong-on-walls-1.2.0.jar
lapisreserve-1.0.8.jar
lazydfu-0.1.2.jar
LegendaryTooltips-1.18.2-fabric-1.2.4.jar
LibraryFerret-Fabric-1.18.2-1.0.3.jar
lithium-fabric-mc1.18.2-0.7.9.jar
malilib-fabric-1.18.2-0.12.1.jar
modmanager-1.2.3+1.18.jar
modmenu-3.2.2.jar
monsters-in-the-closet-1.0.3+1.18.jar
mostructures-1.4.2+1.18.2.jar
notenoughanimations-fabric-1.6.0-mc1.18.2.jar
notenoughcrashes-4.1.6+1.18.2-fabric.jar
numismatic-overhaul-0.2.1+1.18.jar
owo-lib-0.7.2+1.18.jar
reeses_sodium_options-mc1.18.2-1.4.2.jar
RoughlyEnoughItems-8.0.442.jar
shulkerboxtooltip-3.0.7+1.18.2.jar
signtools-fabric.1.18-1.0.0.jar
sleepwarp-1.1.1+1.18.2.jar
sodium-extra-0.4.4+mc1.18.2-build.39.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
starlight-1.0.2+fabric.89b8d9f.jar
TaxFreeLevels-1.3.jar
trinkets-3.3.1.jar
visuality-0.4.2.jar
WaveyCapes-fabric-1.2.0-mc1.18.jar

**Comment by TropheusJ** [comment]
log?

**Comment by TropheusJ** [comment]
cannot get either of these to happen, a log is needed.

**Comment by TropheusJ** [comment]
closing until a log is provided.
