### ISSUE TITLE
Compatibilty with Gravity Changer

### ISSUE THREAD

**Issue by viciscat** [Fabricators-of-Create/Create#319]
### Describe the Suggestion

I would like to see compatibility with the Gravity Changer mod to be able to some sick parkour tricks, the main issue right now is that the "physics" aren't working quite right... [link](https://github.com/qouteall/GravityChanger)

### Screenshots and Videos

https://user-images.githubusercontent.com/51047087/170510034-526fb16b-fcab-4f67-be58-83536368a81e.mp4

Here's what it does right now, I just go through it most of the time

### Additional Context

I used portals from immersive portals to rotate gravity but it's not needed, there's a /gravity command

**Comment by viciscat** [comment]
Also bonus issue rendering of moving stuff from create is scuffed when looking from a portal. You can kinda see it in the video. Seems to be rendered based on camera/player position.

**Comment by Fusion-Flux** [comment]
i can confirm this happens on my rewrite of gravity changer aswell
although i dont exactly know the cause

**Comment by Fusion-Flux** [comment]
i may need to be taught how create does collision to get an idea on how to fix this

**Comment by KevlarBandit** [comment]
There is also the added incompatibility that on pressing ponder, the game crashes. It appears this is a gravity changer issue however.

**Comment by Fusion-Flux** [comment]
fixed on my version of this

**Comment by IThundxr** [comment]
Fixed by fusions version of gravity api
