### ISSUE TITLE
1.17/dev | Could not resolve all dependencies for configuration ':modImplementation'.

### ISSUE THREAD

**Issue by SolidStateNetwork** [Fabricators-of-Create/Create#320]
### Describe the Bug

> Configure project :
Fabric Loom: 0.10.66
Loom is applying dependency data manually to publications instead of using a software component (from(components["java"])). This is deprecated and will be removed in Loom 0.12.
Deprecated Loom APIs were used in this build, making it incompatible with future versions of Loom. Use Gradle warning modes to control the verbosity of the warnings.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Create-mc1.17-fabric-dev'.
> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not resolve com.tterrag:registrate-fabric:0.1.10.
     Required by:
         project :
      > Could not resolve com.tterrag:registrate-fabric:0.1.10.
         > Could not get resource 'https://maven.devos.community/releases/com/tterrag/registrate-fabric/0.1.10/registrate-fabric-0.1.10.pom'.
            > Could not GET 'https://maven.devos.community/releases/com/tterrag/registrate-fabric/0.1.10/registrate-fabric-0.1.10.pom'.
               > maven.devos.community

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

### Reproduction Steps

1. Update link.

### Expected Result

It can download the file again.

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.17.1

**Comment by AlphaMode** [comment]
1.17 is not supported
