### ISSUE TITLE
Crash in location due to create error

### ISSUE THREAD

**Issue by RatDonkeyGoat** [Fabricators-of-Create/Create#321]
### Describe the Bug

i crash

### Reproduction Steps

join server at location 

crash

### Expected Result

not crash

### Crash Report or Log

https://pastebin.com/3VdW9C7i

### Operating System

windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
Remove better-fabric-console for now
