### ISSUE TITLE
Server crash when placing a block on my modpack server

### ISSUE THREAD

**Issue by netcore10** [Fabricators-of-Create/Create#323]
### Describe the Bug

ticking block crash

### Reproduction Steps

no idea

### Expected Result

to not crash

### Crash Report or Log

https://mclo.gs/GFZJ0J4

### Operating System

windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

https://www.curseforge.com/minecraft/modpacks/haywen-unity-fe/files/3806881

**Comment by Tempest-5ky** [comment]
Threw it into Crashy, seems to have been caused by a piston? Hope this helps anyone trying to troubleshoot! https://crashy.net/PKFXTWXg6jE38fjosCsx

**Comment by TropheusJ** [comment]
This doesn't seem to be related to Create at all, please test without it.

**Comment by netcore10** [comment]
Apologies, it's just a weird issue.
