### ISSUE TITLE
Mechanical Crafter does not craft.

### ISSUE THREAD

**Issue by NachoIannizzotto** [Fabricators-of-Create/Create#324]
### Describe the Bug

Mechanical Crafter is not working properly. When trying to make the crusher, the Mechanical Crafter assemble everything but drop everything on the last assemble.

### Reproduction Steps

1. Make the Mechanical Crafter.
2. Add the crafting recipe.
3. The recipe suddenly drop on the floor.

### Expected Result

It should craft the crusher or another items.

### Screenshots and Videos

https://user-images.githubusercontent.com/60115738/170822032-cf0ee75e-96fc-4ace-bf8f-e3eeb411c045.mp4

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Additional Context

The problem is only present with the crusher recipe.

**Comment by michlbro** [comment]
I think it's the way you have set up the mechanical crafter, I'm able to reproduce this on forge version of create.

Edit: I don't think you can use cobblestone as an ingredient.

**Comment by lecuek** [comment]
You can't use cobblestone as an ingredient for the crusher afaik :x

**Comment by NachoIannizzotto** [comment]
Uoh, my bad. Sorry for bothering

**Comment by Tempest-5ky** [comment]
No worries! Don't forget to close the issue!
