### ISSUE TITLE
Stockpile Switch causing crash

### ISSUE THREAD

**Issue by Globears** [Fabricators-of-Create/Create#330]
### Describe the Bug

When a Stockpile Switch connect to a chest(with items in it) that attached to a funnel/chute, it will lead to a crash.

### Reproduction Steps

1.Place a chest
2.Place a Stockpile Switch face to the chest
3.Place a chute/funnel under the chest
4.put at least one item into the chest
5.crash
...

### Expected Result

It shouldn't crash, I think

### Screenshots and Videos

![2022-05-30_19 10 12](https://user-images.githubusercontent.com/106528728/170982311-2d4cba87-3bc0-477d-931e-b5a937ea1bbe.png)

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

fabric-api-0.53.3+1.18.2.jar

**Comment by TropheusJ** [comment]
Already fixed, just needs to be released
