### ISSUE TITLE
Encased fans still process items through tunnels

### ISSUE THREAD

**Issue by JensenJ** [Fabricators-of-Create/Create#331]
### Describe the Bug

When an item is travelling through a tunnel an encased fan can still process the item with fire/lava/water. 

### Reproduction Steps

1. Place a belt with an encased fan with water/fire/lava facing into it
2. Put tunnel over belt
3. Watch items still be processed

### Expected Result

Items shouldn't be processed inside tunnel as the particles are blocked by the tunnel wall.

### Screenshots and Videos

Screenshots show kelp still being processed into dried kelp inside tunnel.

![2022-05-30_22 33 17](https://user-images.githubusercontent.com/13812018/171061205-9a1ee070-4be5-42f1-80a8-a97a3baa4d8a.png)
![2022-05-30_22 34 32](https://user-images.githubusercontent.com/13812018/171061209-7f1f3db9-4144-492f-90ca-7c822afd5ded.png)

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Modified version of Better Minecraft 1.18.2 Version 11.5 Fabric Modpack 

Added:
Create mc1.18.2_v0.4.1+586 (Patch 2)
Create Chunkloading
Charm

Removed:
Fabric Seasons

### Additional Context

Both Singleplayer and Multiplayer

**Comment by DarianLStephens** [comment]
Is this a thing in the Forge version of Create?

**Comment by JensenJ** [comment]
Just confirmed, this is a thing in the Forge version of Create as well, with only Create 0.4.1 and flywheel 0.6.2 installed on top of 1.18.2 vanilla and forge 40.1.0.

**Comment by DarianLStephens** [comment]
It would need to be reported there, then, since it's not a problem introduced with the port.

**Comment by TropheusJ** [comment]
Issues that occur on Forge as well are no longer being tracked on this repo. Please follow the respective issue on the Forge repo instead: https://github.com/Creators-of-Create/Create/issues/3083
