### ISSUE TITLE
Brass Funnel: IllegalStateException: May not call getCurrentUnsafe() from a close callback.

### ISSUE THREAD

**Issue by Mg138** [Fabricators-of-Create/Create#332]
### Describe the Bug

Server crashes immediately when loading in a (bugged) brass funnel. 

### Reproduction Steps

Unfortunately, currently unknown. Might update later when we figure it out, but for now, the issue was caused on a server and not by me myself.

### Expected Result

No crash.

### Crash Report or Log

https://pastebin.com/48Qv2B8P

### Operating System

Windows Server 2019

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
Has already been fixed, just needs to be released
