### ISSUE TITLE
Server and client crash by bypassing height

### ISSUE THREAD

**Issue by DonorKrovi** [Fabricators-of-Create/Create#333]
### Describe the Bug

Build any mechanism that can use its mechanism bypassing the height of the world, you will destroy your server and client in this way

Works in any world

### Reproduction Steps

Build any mechanism that can use its mechanism bypassing the height of the world, you will destroy your server and client in this way

### Expected Result

not crash

### Operating System

windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

No

**Comment by DonorKrovi** [comment]
It also works in the forge.

**Comment by XionioXMaster** [comment]
Yes, crash!

**Comment by XionioXMaster** [comment]
Fixed?

**Comment by sall0-0p** [comment]
Is it possible to launch world after this?

**Comment by IThundxr** [comment]
Can't reproduce, gonna assume it was fixed sometime between 0.4.1 and 0.5.1.f
