### ISSUE TITLE
[Fabric] - Server crashes possibly from a Redstone link, stockpile switch or a clutch

### ISSUE THREAD

**Issue by messAround48** [Fabricators-of-Create/Create#336]
### Describe the Bug

So i had a basic wood farm: wind turbine -> clutch -> rotor with sawblades + conveyors to chest and all that
stockpile switch connected to output chest, redstone link connected to it, and another link connected to clutch, basic setup. it worked perfeclty without the whole switch+link+clutch shenanigans, but when this automated-turn-off mechanism was completed and as soon as the first wood block went from conveyor to output chest - instant crash, and the server won't start anymore with the same crash message.

### Reproduction Steps

1.item goes to chest
2.stockpile switch reads chest inventory and decides will it change state
3.hoorah redstone automation

### Expected Result

crash when item went into chest. client literally froze right at the brass funnel to chest when server crashed

### Crash Report or Log

https://pastebin.com/0Syu9ziX

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Ambient Sounds 5.0.16
Appleskin 2.4.0
AE2 11.0.0
Architectury 4.4.67
Charm 4.1.0
Craft horse armor dont remember name (CHAS-1.18-1.8-Fabric)
Cloth config 6.2.62
Create Crafts&Additions 20220525a
CreativeCore 2.6.11
Croptopia 2.0.3
Fabric API 0.53.4
FTB Chunks 1802.3.6 Build 145
FTB Library 1802.3.6 Build 119
FTB Teams 1802.3.6 Build 51
Indium 1.0.3
Jade 5.99.2
Lithium 0.7.10
MouseTweaks 2.22
Phosphor 0.8.1
REI 8.2.470
Sodium 0.4.1 Build 15
Wraith waystones 2.5.3
You're in grave danger 1.3.6

**Comment by TropheusJ** [comment]
Has already been fixed, will be in next release
