### ISSUE TITLE
Better Biome blend causes create config button to not show

### ISSUE THREAD

**Issue by StockiesLad** [Fabricators-of-Create/Create#338]
### Describe the Bug

Self-Explanatory

### Reproduction Steps

Self-explanatory

### Expected Result

Self-explanatory

### Crash Report or Log

https://gist.github.com/FluffyBumblebees/bdd948b647907364d3145d66d06650ae

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Better biome blend

**Comment by StockiesLad** [comment]
https://github.com/FionaTheMortal/better-biome-blend/issues/55

**Comment by StockiesLad** [comment]
In the mentioned thread, the dev of BBB disabled most of the mod and create still failed to show its config button. This is an issue on creates end.

**Comment by TropheusJ** [comment]
I've fixed this locally. Somehow installing BBB causes I18n to not translate correctly. I've swapped button searching to use keys.

**Comment by StockiesLad** [comment]
Nice
