### ISSUE TITLE
Hose pulley visually disappears when the chunk is unloaded

### ISSUE THREAD

**Issue by Seon82** [Fabricators-of-Create/Create#339]
### Describe the Bug

The hose part of the hose pulley visually disappears when then chunk is unloaded, but keeps pumping liquids normally. Updating its height makes it reappear.

### Reproduction Steps

Place a hose pulley and unroll it. Unload the chunks. Return and observe that the hose pulley has disappeared.

### Expected Result

No Schrödinger pulleys.

### Screenshots and Videos

https://user-images.githubusercontent.com/46298009/171750405-2438b6d0-b399-46c2-9ef1-118e7a1a4a8b.mp4

### Operating System

Linux (Fedora 36)

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Could reproduce with create alone, and with create + sodium + indium.

**Comment by TropheusJ** [comment]
upstream issue, won't be fixed on our side

**Comment by Seon82** [comment]
Couldn't find it in the forge tracker, does it need reporting there?

**Comment by TropheusJ** [comment]
I remember seeing it there, maybe I misremembered though. If you can get it to happen on forge for sure, then yes.

**Comment by IThundxr** [comment]
Doesnt happen in forge or fabric anymore
