### ISSUE TITLE
Create v0.4.1+594 crash

### ISSUE THREAD

**Issue by Trnrr** [Fabricators-of-Create/Create#340]
### Describe the Bug

Downloaded version 0.4.1+594 off Modrinth and when I try and start the game it crashes.

### Reproduction Steps

1. Download fabric 0.14.6
2. Download fabric api 0.54.0
3. Download create fabric 0.4.1+594 
4. Start the client and it crashes and closes the window.

### Expected Result

It to not crash

### Crash Report or Log

Crash Log: https://gist.github.com/Trnrr/b63d07ab7d28658ad2911f715c59bfe6

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

fabric api 0.54.0

**Comment by TropheusJ** [comment]
oops, fixed
