### ISSUE TITLE
create fabric +595 crashing with exit code 1

### ISSUE THREAD

**Issue by dauthiatull** [Fabricators-of-Create/Create#342]
### Describe the Bug

fabric 0.14.6

game crashes with exit code 1
even with a new profile with no other mods

### Reproduction Steps

1. use curseforge to install fabric and fabric api 
2. install crate fabric
3. start launcher
4. click play
5. crash with exit code 1

### Expected Result

not crash

### Crash Report or Log

https://pastebin.com/xvt0dj2h

### Operating System

windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
#343
