### ISSUE TITLE
[Bug] [1.18.2 Fabric] [v0.4.1 Patch 4] Crash on startup

### ISSUE THREAD

**Issue by ThePixelist** [Fabricators-of-Create/Create#343]
I've been using the **[v0.4.1 Patch 4](https://www.curseforge.com/minecraft/mc-mods/create-fabric/files/3815503)** version of Create **Fabric** 1.18.2, and have been crashing.

It happens when Create is added.

Fabric, No mods: **Opens**
Fabric, just **Fabric API**: **Opens**
Fabric, **Fabric API** + **Create v0.4.1 Patch 4**: **Crashes**

I've attached [2022-06-03-4.log](https://github.com/Fabricators-of-Create/Create/files/8830417/2022-06-03-4.log) and [latest.log](https://github.com/Fabricators-of-Create/Create/files/8830418/latest.log).

//I hope my bug report was concise and informative, please tell me if I need to provide more info.

**Comment by TropheusJ** [comment]
I tried to update and the universe really just said no 
Patch 5 is out.
