### ISSUE TITLE
Errors in currently selected datapack

### ISSUE THREAD

**Issue by Azzmikaelson** [Fabricators-of-Create/Create#344]
### Describe the Bug

Minecraft thinks there's an error in my datapacks I have selected depsite the fact I have none yet. [Expect for the default one for fabric mods] it's preventing me from creating or entering a world.

This happened when I installed the new patch of Create Fabric.

### Reproduction Steps

1. Install Create Fabric Patch 5
2. Load a world or Create a new world
3. You'll see the error screen shortly after that.
...

### Expected Result

I expected my world would have just loaded perfectly without any issues.

### Screenshots and Videos

![IMG_20220603_173039](https://user-images.githubusercontent.com/104194329/171829423-a4a5f899-0fdd-4598-b39b-e24eee99537a.jpg)

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by JieningYu** [comment]
provide a log for more info.
this issue usually take place when you delete some mod.

**Comment by ghost** [comment]
Here's a log, same issue on my end, creating a new world with no datapacks:

https://pastebin.com/GmhdcUXd

**Comment by JieningYu** [comment]
Try to remove Farmer's Delight and Debugify.

**Comment by Sheep7798** [comment]
It worked when I removed Farmers Delight

**Comment by FreeFull** [comment]
I can confirm, patch 2 works with Farmer's Delight and patch 5 doesn't

**Comment by ghost** [comment]
In addition to Farmer's Delight and Debugify, I had to disable Pollen, a dependency of Enhanced Mushrooms.
