### ISSUE TITLE
Incompatibility with Very Many Players

### ISSUE THREAD

**Issue by ghost** [Fabricators-of-Create/Create#345]
### Describe the Bug

Launching a modpack with both Create and [VMP](https://github.com/RelativityMC/VMP-fabric) enabled causes a crash on startup.

I'm also submitting this issue to the VMP team since I don't know which is more likely to be able to fix the 'problem'.

### Reproduction Steps

1. Launch a modpack with both Create and VMP enabled

### Expected Result

Game to run

### Crash Report or Log

https://pastebin.com/XXkhzqrH

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

VMP 0.2.0+beta.3.17

(others listed in log)

**Comment by SplendidAlakey** [comment]
Just to add to this: this only became an issue with Patch 5, used to work perfectly fine before.

**Comment by ghost** [comment]
VMP's author responded with [a possible fix](https://github.com/RelativityMC/VMP-fabric/issues/14#issuecomment-1145872845) on Create's end.
