### ISSUE TITLE
[1.18.2 Crash] crash with twilight forest during startup (0.4.1-596)

### ISSUE THREAD

**Issue by itsdinkd** [Fabricators-of-Create/Create#347]
### Describe the Bug

After updating to latest create, I can no longer launch my modpack. It seems that there might be a conflict with Twilight Forest's latest version as well. (The previous build of TF and Create 0.4.1-586 worked fine)

### Reproduction Steps

1. Download AQM2
2. Update Create, add Twilight forest
3. crash

### Expected Result

not to crash

### Operating System

11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Additional Context

https://pastebin.com/CJxznm0U

**Comment by itsdinkd** [comment]
Can confirm downgrading to Create's 586 build does not crash game with twilight forest. Removing twilight forest and using create 596 does not crash game.

**Comment by JieningYu** [comment]
rename it to "crash with twilight forest" would be better.

**Comment by itsdinkd** [comment]
sucks they still have yet to release an hotfix for this. killing my modpack =/ esp being 6 versions behind on create

**Comment by AlphaMode** [comment]
Fixed in latest tf commit
