### ISSUE TITLE
The Corners causes invisible items

### ISSUE THREAD

**Issue by Gamerbolts** [Fabricators-of-Create/Create#349]
### Describe the Bug

Create has invisible items such as the Wrench, Sand Paper, etc.

### Reproduction Steps

I am creating a modpack called Bolt's Craazzy Adventure. Not sure how you are able to replicate it.

### Expected Result

The items to be seen

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/20451601/172018752-e7c09f55-f8f4-476f-86a9-047b5c9d054e.png)

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

https://docs.google.com/spreadsheets/d/1S--Gsjqe4B8BPipKmOJVyV7nim12h63TUyKee_alI60/edit?usp=sharing

**Comment by Tempest-5ky** [comment]
This probably isn't it but if you're using Sodium, it could be a rendering issue. Try installing indium and seeing if that fixes the issue? https://www.curseforge.com/minecraft/mc-mods/indium
I had a similar problem with Kibe once and indium fixed it!

**Comment by JieningYu** [comment]
> This probably isn't it but if you're using Sodium, it could be a rendering issue. Try installing indium and seeing if that fixes the issue? https://www.curseforge.com/minecraft/mc-mods/indium I had a similar problem with Kibe once and indium fixed it!

Indium installed because if you don't install indium, create will display a warning at startup(No Indium?)

**Comment by Gamerbolts** [comment]
> This probably isn't it but if you're using Sodium, it could be a rendering issue. Try installing indium and seeing if that fixes the issue? https://www.curseforge.com/minecraft/mc-mods/indium I had a similar problem with Kibe once and indium fixed it!

Thanks for the reply and yes Indium is installed with Sodium :)

**Comment by Gamerbolts** [comment]
I put create with just sodium and indium and it worked that means it is another of my mods... I will do some testing and see

**Comment by Gamerbolts** [comment]
After lots of testing it is a mod called The Corners that is causing the issues.

**Comment by TropheusJ** [comment]
The Corners has custom shaders, which seems to break other mods as well. We can’t fix it, and the issue is labeled as won’t fix on their side, so only option is to remove it.

**Comment by Gamerbolts** [comment]
I removed The Corners :) Ty!
