### ISSUE TITLE
Spout in my honey farm randomly stopped working. 

### ISSUE THREAD

**Issue by KraftMinecraft** [Fabricators-of-Create/Create#350]
I was trying to make a simple honeyed apple farm, and it worked for a short time, until I relogged. when I came back the spout stopped working, despite being filled with honey. No matter what I did it wouldn't fix, I tried breaking the depot and replacing it, only using one apple, breaking and replacing the spout, but nothing worked.

**Comment by KraftMinecraft** [comment]
update: I have figured out that the direct problem is with taking items out of the depot. I had a filter which would put the honeyed apples onto a belt, however the spout wouldn't work when I did it.

**Comment by Seon82** [comment]
Ran into a similar issue with a spout feeding lava into a bucket, with a funnel from the depot to the belt filtering lava buckets. A workaround that solved the issue in my case was to  set the quantity on the funnel filter to 1.

**Comment by TropheusJ** [comment]
Can't reproduce, might've been fixed. Can you test with [a dev build](https://github.com/Fabricators-of-Create/Create/actions/runs/2501858933)?

**Comment by TropheusJ** [comment]
[Patch 9](https://modrinth.com/mod/create-fabric/version/mc1.18.2_v0.4.1+628) also works.

**Comment by Seon82** [comment]
Seems fixed for me with lava buckets. Thanks!
