### ISSUE TITLE
Robotic hand holding sandpaper interacts with air crash

### ISSUE THREAD

**Issue by Alvin-YS** [Fabricators-of-Create/Create#351]
### Describe the Bug

When the manipulator is holding the sandpaper against the air, an irreversible archive crash will occur (urgent fix)

### Reproduction Steps

1.Place the robot
2.Power the manipulator
3.Give the sandpaper to the manipulator
4.Make sure the robot interacts with air
5.crash happened

### Expected Result

Fix it please! you can do it!

### Screenshots and Videos

![Bug](https://user-images.githubusercontent.com/84568539/172048048-5adecd94-3be0-41d9-b8bc-e3abe42d6633.png)

### Crash Report or Log

https://gist.github.com/YunSheng-Studio/1f99cea5e9de72c68cbb156ab06d8df9

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

createaddition-1.18.2-20220525a
and its pre-module

**Comment by TropheusJ** [comment]
oops, should've been closed
