### ISSUE TITLE
Shears don't seem to be working

### ISSUE THREAD

**Issue by Viotomix** [Fabricators-of-Create/Create#352]
### Describe the Bug

Breaking vines, leaves, grass, fern or seagrass with shears yields no drop. This happens to normal vines and twisting vines (but not weeping vines, or any modded vines that I tested) as well as all type of vanilla leaves and some modded leaves but not all. (That could of course be an issue on another mods end tho, such as Bewitched) There may be other blocks that this applies to but I haven't tested more than the ones listed above.

Versions that I tested this on:
mc1.18.2_v0.4.1+599
mc1.18.2_v0.4.1+600

Both versions were tested on their own and with other mods

### Reproduction Steps

1. Try to break any of the mentioned blocks with shears

### Expected Result

The given block to be dropped.

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Should not be relevant as this was tested with and without other mods. If the mods are still needed please let me know

**Comment by digitaltrucker** [comment]
Can confirm.
