### ISSUE TITLE
Deployer doesn't milk cow

### ISSUE THREAD

**Issue by rkrgr** [Fabricators-of-Create/Create#356]
### Describe the Bug

Hey, I tried to milk a cow with a deployer, but nothing happens.

Thanks for the great mod btw.

### Reproduction Steps

1. Place down deployer and give it buckets
2. Place a cow two blocks away
3. Power the deployer
4. Hand with bucket moves to cow, but cow is not milked

### Expected Result

Deployer should milk the cow

### Screenshots and Videos

![2022-06-08_11 49 20](https://user-images.githubusercontent.com/9026012/172587962-1f337aea-d132-4302-8169-eeea826e1075.png)

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Additional Context

In the Valhelsia Discord I read that others have the same problem. Shears don't seem to work either.

**Comment by Globears** [comment]
I don't know why but when a deployer use a milk bucket, it will turn it into a empty bucket(maybe it means the deployer pour out the milk), So you probably didn't see the milk bucket. Btw, through my tests, the chute and funnel can't garb items from a deployer, maybe you need to adjust your design(eg. item drain).

**Comment by JieningYu** [comment]
<img width="163" alt="image" src="https://user-images.githubusercontent.com/61787533/172614697-db349715-e16c-4a0b-be27-986d917d5799.png">

**Comment by Globears** [comment]
> <img alt="image" width="163" src="https://user-images.githubusercontent.com/61787533/172614697-db349715-e16c-4a0b-be27-986d917d5799.png">

from bilibili ;)

**Comment by rkrgr** [comment]
Okay I know the problem. The setup was working but I'm using the LevelZ mod, where you need to level a farming skill to be able to milk cows. The deployer simply doesn't have the skill. Thanks for helping.

**Comment by JieningYu** [comment]
But..how to level up Deployers?

**Comment by rkrgr** [comment]
Yeah that's the problem. :D
I created an issue for LevelZ. The level requirements should not apply for fake players I think.

**Comment by rkrgr** [comment]
For anyone interested: this will be fixed in the next LevelZ release. https://github.com/Globox1997/LevelZ/commit/edbe8a2ed6a7d0d3a9f492328f61455468b772d8
