### ISSUE TITLE
Allow customisation of Ponder UI

### ISSUE THREAD

**Issue by twome** [Fabricators-of-Create/Create#357]
### Describe the Suggestion

Hi, with the "InvMove" mod (which allows movement during inventory screens) installed, any keybinds which operate on movement keys become incredibly frustrating. I like the spatial WASD/QE consistency of Ponder's default binds but customisation would be great. If this already exists, please make those properties exposed/discoverable by default in the config JSON.

Thanks for making the best ingame tutorial/documentation for any mod of any game I've ever seen!

**Comment by JieningYu** [comment]
You can report this suggestion to Forge upstream.

**Comment by twome** [comment]
Thanks, sorry I didn't realise they were still git-connected :)

**Comment by DarianLStephens** [comment]
You can also disable movement in the Ponder UI using InvMove's own config.

**Comment by TropheusJ** [comment]
We won't be changing this in the port, should be reported to upstream
