### ISSUE TITLE
Make use of the "Mod Menu" mod's API / standard to reach the Create menu & Ponder

### ISSUE THREAD

**Issue by twome** [Fabricators-of-Create/Create#358]
### Describe the Suggestion

Some other mod I have installed is hiding Create's button from appearing on the main menu. This would be no problem if I could access Create's menu/config/tutorials from [Mod Menu](https://modrinth.com/mod/modmenu), as I can do for ~80% of my other mods, but the "open config" button is disabled. I'd really appreciate if Create could have good "mod etiquette" and only take over common UI space (e.g. the main menu) or break compatability with other mods when necessary. I wouldn't mind if it was *just* Create spreading its legs (all your menu UI components are so high-quality!), but unfortunately it's not the only one, haha

**Comment by TropheusJ** [comment]
Configs are available to offset the button to prevent overlap. I've added mod menu config button integration in the latest commit.

**Comment by twome** [comment]
Bless you! In my case the button seems not to be getting rendered at all, rather than shunted off-screen or obscured, but that's a separate issue and I haven't found out the guilty mod causing that yet. Thanks for your work on this absolutely superlative mod!
