### ISSUE TITLE
EMI (REI alternative) Support

### ISSUE THREAD

**Issue by ZekeZDev** [Fabricators-of-Create/Create#363]
### Describe the Suggestion

EMI Is an alternative to the REI recipe browser it has a more modern UI is available on modrinth, features a recipe tree and other qol changes. 

https://modrinth.com/mod/emi

Currently the recipes for basic items are viewable however mechanical crafting is not shown. I don't know if this is possible to implement with EMI however if possible it would be very useful, especially for Modrinth modpack developers.

### Screenshots and Videos

_Standard recipe working_
![Standard recipe working](https://user-images.githubusercontent.com/81902668/173015429-9606706d-8dd4-4e6e-889e-9d93d4a07b61.png)
_Mechanical Recipe not working_
![Mechanical Recipe not working](https://user-images.githubusercontent.com/81902668/173015597-694c5b7e-69a6-40c1-b6bb-f3cc6da25abc.png)

**Comment by JieningYu** [comment]
potato cannon is working
<img width="517" alt="image" src="https://user-images.githubusercontent.com/61787533/173020289-aa1c9747-e1ff-4b95-a663-2b3e032a1b4b.png">
<img width="854" alt="image" src="https://user-images.githubusercontent.com/61787533/173020344-76c1895c-d648-47a6-a5fd-369f6db9f26a.png">

**Comment by JieningYu** [comment]
update your Create to dev version

**Comment by TropheusJ** [comment]
We already have EMI support, just needs to be released.

**Comment by ZekeZDev** [comment]
Ohh epic, great to hear!
