### ISSUE TITLE
It doesn't work with Questcraft

### ISSUE THREAD

**Issue by EpicProSteve** [Fabricators-of-Create/Create#366]
### Describe the Bug

The bug crashes the game while loading

### Reproduction Steps

1.Have Questcraft 
2.put create fabric in the mods folder
3.try to run Questcraft
...

### Expected Result

I expected the game to load and for me to be able to play Questcraft with the create fabric mod.

### Crash Report or Log

https://docs.google.com/document/d/1kbfJfygo_3ykiT4pjuhguKGasB2eBpsv_F-nkCqGRTo/edit?usp=sharing

### Operating System

Oculus Quest 2

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

It wouldn't let me put an image of the other mods I used so I had to make another document [https://docs.google.com/document/d/1N4iKIh-0HQm2Rl7UQIgzYvm22mILBMSx2RN790K8_YQ/edit?usp=sharing](url)
(Both of the mcxr mods are for Questcraft)

**Comment by TropheusJ** [comment]
I need a crash log, this is a regular log, and use a paste site like gist.
