### ISSUE TITLE
Crash when placing a stockpile switch next to a fluid tank

### ISSUE THREAD

**Issue by JensStorm** [Fabricators-of-Create/Create#368]
### Describe the Bug

I was making a stockpile switch to make a contraption turn off once the fluid tank gets filled, and when i placed it just beside the fluid tank (no gap between) the server crashes, the server will crash indefiently as its a block entity crash.

Note, i got Create Crafts and addition added, the fluid inside the tank is seed oil
Update note, I tried with normal minecraft fluids and create fluids and those fluids crashes the game too so i dont think it has anything to do with Create Crafts and Additions

### Reproduction Steps

1. Make a fluid tank
2. Make it so theres fluid in the fluid tank
3. Place a stockpile switch next to the fluid tank with no space in between

### Expected Result

Only thing i can think of is that certain fluids arent compatible with the stockpile switch

### Crash Report or Log

https://pastebin.com/pRxbkVR6

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Its included in the pastebin crash report under System Details

**Comment by TropheusJ** [comment]
update Create.
