### ISSUE TITLE
brass tunnel can get unlimited items

### ISSUE THREAD

**Issue by CvRain** [Fabricators-of-Create/Create#369]
### Describe the Bug

The first item put into the brass tunnel can be obtained infinitely

### Reproduction Steps

1. Set up any brass tunnel group
2. Use hopper or brass funnel to fill a item
3. Put items at will

### Expected Result

The first time you put an item into the brass tunnel, you will get this item if you put subsequent items into it
This also causes the chute to not be able to put objects inside

### Screenshots and Videos

https://www.bilibili.com/video/BV1uS4y1q7GN/?vd_source=305b708bb56696a8ae510ab0fbce9e13

### Operating System

Windows 10 & OpenSuse Linux Server

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by CvRain** [comment]
The link is missing. Try this one
https://www.bilibili.com/video/BV1GY4y1479Z/

**Comment by ZYFDroid** [comment]
Images of how-to-reproduce: 
![幻灯片1](https://user-images.githubusercontent.com/39429452/173224625-16fe83b6-c652-455d-85e7-c6cb17aa0759.PNG)
![幻灯片2](https://user-images.githubusercontent.com/39429452/173224628-31b031a6-3bba-4191-baed-917400570fa7.PNG)
![幻灯片3](https://user-images.githubusercontent.com/39429452/173224632-8acf1568-9a51-41e4-bc57-1ade7e3c0fc3.PNG)

only combined brass tunnel have this bug.
