### ISSUE TITLE
Funnels extracting from item drains crash the game and mess up worlds

### ISSUE THREAD

**Issue by OnajStoJesam** [Fabricators-of-Create/Create#370]
### Describe the Bug

The moment I place a funnel extracting items from the side of a drain, the game crashes. I cannot enter the worlds in which it happened without the game crashing again upon loading the world.

### Reproduction Steps

1. Place down an item drain
2. Place a funnel on its side
3. Make it extract if it's already not set to that

### Expected Result

It should have no crashed the game and allowed me to switch it to insert mode. 

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by Infinidoge** [comment]
Can reproduce, in this case with a chest, and a brass funnel outputting to a depot.
Log: https://mclo.gs/nXzAtPB#L1095

**Comment by OnajStoJesam** [comment]
> Can reproduce, in this case with a chest, and a brass funnel outputting to a depot. Log: https://mclo.gs/nXzAtPB#L1095

I am desperate to fix this. I'm begging you to tell me how? I've tried multiple versions of Create fabric and fabric API.
