### ISSUE TITLE
Disconnects when trying to connect to server

### ISSUE THREAD

**Issue by TheButterbrotMan** [Fabricators-of-Create/Create#371]
### Describe the Bug

Hello, im developing the next version of my modpack, and singleplayer works. But when i make the server pack and try to join, i get disconnected instantly. I could identify Create Addition as the cause, by removing mods one by one.

### Reproduction Steps

Cant really give a reproduce way here.

### Expected Result

To not disconnect.

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TheButterbrotMan** [comment]
Serverlog: https://bytebin.lucko.me/ops4nWGBtj

**Comment by TheButterbrotMan** [comment]
Clientlog: https://bytebin.lucko.me/CWkVFkgn5D

**Comment by TropheusJ** [comment]
if Create addition is the cause, please report it to them.
