### ISSUE TITLE
Arms bypass smart chute stack limit

### ISSUE THREAD

**Issue by OnajStoJesam** [Fabricators-of-Create/Create#372]
### Describe the Bug

By the looks of things, the stack limit on smart chutes affects how many items they can input, not how many they can output. The arm, however, will put more items in a smart chute than the stack size allows for.

### Reproduction Steps

1. Place a smart chute with and stack limit and a chest on top of it
2. Place a robotic arm and make it take put items from a depot or something into the chute

### Expected Result

The arm should not insert more than the stack limit, but it does.

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
Identical to Forge behavior
