### ISSUE TITLE
Wrench issues with other mods

### ISSUE THREAD

**Issue by andylmfao** [Fabricators-of-Create/Create#373]
### Describe the Bug

Incompatibility issue found with other mods - other wrenches stop working when create is installed
Discovered with Applied energistics 2, where the Certus Quartz Wrench doesn't rotate the Mod's blocks. It however DOES rotate cogwheels and chests, and similar blocks.

### Reproduction Steps

1. Have both create and Applied energistics 2 installed
2. Get a certus quartz wrench
3. Place an AE2 block (I used the inscriber)
4. You should now normally be able to rotate it by right-clicking on the block, but it doesn't work. 

### Expected Result

Fix in what i assume might be item tags in fabric, so that It's compatible and doesn't interfere with other mods. 

### Screenshots and Videos

https://imgur.com/a/qCvlnbX

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

The entire valhelsia enhanced vanilla pack.

**Comment by AlphaMode** [comment]
I'm pretty sure that it's been decided that the only wrench that you should be using is the create one

**Comment by TropheusJ** [comment]
Could you test this with [a dev build](https://github.com/Fabricators-of-Create/Create/actions/runs/2505616400)? The Create wrench should work for other machines, but not the other way around.

**Comment by TropheusJ** [comment]
[Patch 9](https://modrinth.com/mod/create-fabric/version/mc1.18.2_v0.4.1+628) also works.

**Comment by andylmfao** [comment]
![image](https://user-images.githubusercontent.com/63781863/174053049-a7d17200-fb2a-49de-93f1-2013176051db.png)
Get this, where do i download the lib?

**Comment by Skidamek** [comment]
> ![image](https://user-images.githubusercontent.com/63781863/174053049-a7d17200-fb2a-49de-93f1-2013176051db.png) Get this, where do i download the lib?

just update fabric api (porting lib is build in create)

**Comment by TropheusJ** [comment]
should have been fixed, going to assume it was
