### ISSUE TITLE
Game Crashes when Smart Chute Disposes of items in lava

### ISSUE THREAD

**Issue by FarmerOfBricks** [Fabricators-of-Create/Create#374]
### Describe the Bug

On My Server i set up a iron generator and it makes flint too so i wanted a disposal system and once i hooked up the smart chute and stockpile switch every time i join and load the chunks the server restarts

### Reproduction Steps

1.have a chest
2.have a smart chute 
3.have a stockpile switch hooked up to the smart chute so when the chest fills up items come out of the chute
4.fill the chest
5.server should crash 
(on fabric 1.18.2)
...

### Expected Result

Server Restarting

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Bclib
better end
better nether
bookshelf fabric
chipped
craftable chainmail
decorative blocks
ecologics
emerald tools
enhancements
enchantment descriptions
extra origins
fabric api
geckolib
impaled
mob origins
origins
origins umbrellas
pehuki
pick your poison
rats mischief
simple backpack
terralith 2.0 Overworld Evolved
tooltip fix
trinkets
witherborn origin
wraith waystones (aka Fabric waystones)
yungs api
yungs better strongholds

**Comment by FarmerOfBricks** [comment]
i just tested it in single player it crashes the Mc window

**Comment by FarmerOfBricks** [comment]
it gave me this error code when the launcher opened

"The game crashed whilst ticking block entity
Error: java.lang.RuntimeException: Encountered an exception while invoking a transaction outer close callback.
Exit Code: -1"

**Comment by Globears** [comment]
Try update create

**Comment by TropheusJ** [comment]
This should be fixed in a newer Create update.
