### ISSUE TITLE
[1.18.2]Mechanic Arm& Belt Bug

### ISSUE THREAD

**Issue by Globears** [Fabricators-of-Create/Create#378]
### Describe the Bug

It seems that after you fixes the Mechanic Arm has a new bug, when mechanic arms try to grab item from a belt, it was frozen.

### Reproduction Steps

1.have a mechanic arm linked to a motor
2.let it grab items from a belt
3.
...

### Expected Result

it should grab the item normally. ( I'm not sure, did I do anything wrong?)

### Screenshots and Videos

![Uploading 2022-06-16_16.22.32.png…]()

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

create-mc1.18.2_v0.4.1+628.jar (also+627)
fabric-api-0.56.0+1.18.2.jar

**Comment by TropheusJ** [comment]
fixed

**Comment by TropheusJ** [comment]
...oops, wrong issue

**Comment by TropheusJ** [comment]
likely fixed, mechanical arms are working well right now
