### ISSUE TITLE
belt bug that copies items

### ISSUE THREAD

**Issue by YoungHuang233** [Fabricators-of-Create/Create#379]
### Describe the Bug

When I drop two or more items onto the belt, the items remains there meanwhile they are transported, so actually the items are copied.(forgive my poor English)

### Reproduction Steps

1.a driving belt
2.just throw items on it

### Expected Result

the items should be transported

### Screenshots and Videos

https://user-images.githubusercontent.com/106714014/174073454-b2801dfb-ce74-412c-8b43-a70fe44a9530.mp4

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
fixed
