### ISSUE TITLE
Latest build just crashes at startup

### ISSUE THREAD

**Issue by TheBeautyLlama** [Fabricators-of-Create/Create#38]
### Describe the Bug

Latest build just crashes at startup

### Reproduction Steps

launch minecraft
mods: create, fabric 0.12.12, fabric api 0.44.0

### Expected Result

what mods i need or how can i lauch it?

### Operating System

Windows 11

### Mod Version

0.4.0a

### Minecraft Version

1.18.1

### Forge Version

no forge?

### Other Mods

create, fabric 0.12.12, fabric api 0.44.0

**Comment by TheBeautyLlama** [comment]
https://paste.ee/p/5zbG2

**Comment by TropheusJ** [comment]
should be fixed.
