### ISSUE TITLE
Deployer disables seats

### ISSUE THREAD

**Issue by SandWoodJones** [Fabricators-of-Create/Create#381]
### Describe the Bug

If a seat has been interacted with by a deployer, say as to remove a mob from it, that seat will become unusable for both players and mobs.

### Reproduction Steps

1. Place a seat and have a deployer click it
2. You can not use that seat anymore nor can any mob falling on.
3. Breaking it and placing it again fixes this

### Expected Result

Any players or mobs can sit on an empty seat that has previously been interacted with by a deployer.

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Additional Context

I'm trying to build a farm where I remove chickens from a place one by one using seats and after the first chicken is sat down and then removed from the seat no other chicken will be able to sit on it again.

**Comment by CzechHek** [comment]
(This still happens in latest dev versions btw).

Deployer sits on the seat basically. Wouldn't it be easy to blacklist deployer seat interactions?

Nevertheless, this is an upstream issue. I'm sure there is an issue for this on forge repo.
