### ISSUE TITLE
Mech. Arms infinite item glitch?

### ISSUE THREAD

**Issue by N0Ninja** [Fabricators-of-Create/Create#383]
### Describe the Bug

I have a blasting setup with fans and lava, which uses arms to move items from the input barrel's depot to the blasting floor to the output barrel's brass funnel. When the input arm takes an item/stack from the input depot, it places it onto the blasting depot floor, but while putting the stack on the depot, it still has the same stack in the hand, which proceeds to continuously place the "same stack" in different spots, leading to presumably infinite blasted items (tested to over 200 stacks worth from one input stack).

### Reproduction Steps

1.setup depot and mech. arm along with fans/lava/blasting depots to take from input depot and place on blasting depot
2.test if items still infinitely stack
3.
...

### Expected Result

Hopefully the items simply get blasted one time per input stack (infinite items are fun until you have no room to store them lol)

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/107666967/174230377-ef7c8725-fbdd-47cc-95a5-5732609357e8.png)
![image](https://user-images.githubusercontent.com/107666967/174230479-480cfbbd-a9f5-4ec1-a961-ff28baf45a91.png)

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

I was running the valhelsia enhanced vanilla modpack plus a few non create mods (ftb maps i think, couple more like that)

### Additional Context

In order to stop it, I have to take the item directly from the mech. arm, and it gives me the full stack of the item it was moving.

**Comment by TropheusJ** [comment]
should be fixed
