### ISSUE TITLE
depot bug that copies items

### ISSUE THREAD

**Issue by YoungHuang233** [Fabricators-of-Create/Create#384]
### Describe the Bug

When using vanilla hopper to transport items to the depot, the items are copied

### Reproduction Steps

1.place a depot
2.put a hopper to it
3.put items on the depot out

### Expected Result

items should be transported to the depot, not copies

### Screenshots and Videos

https://user-images.githubusercontent.com/106714014/174235564-1bd16e4b-062b-412f-bb75-0f225dccf5a4.mp4

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
Make sure you're using patch 11.

**Comment by YoungHuang233** [comment]
Now I know it is conflicted with other mods. But the problem that items do not display on the depot when using vanilla hopper to transport items to the depot.

**Comment by TropheusJ** [comment]
should be fixed
