### ISSUE TITLE
Funnels won't extract / insert items from / to contraption inventory if being *steady*

### ISSUE THREAD

**Issue by para-dichloro-benzene** [Fabricators-of-Create/Create#386]
### Describe the Bug

Seems the funnel won't work if being steady when the contraption moves.

### Reproduction Steps

1. Place a mechanical bearing facing any direction.
2. Attach a chest to it.
3. Insert something into the chest.
4. Attach a funnel at the contraption's rotating axis facing the same axis.
5. Rotate the contraption.

### Expected Result

The funnel should extract the items from the chest.

### Screenshots and Videos

https://user-images.githubusercontent.com/50518519/174303534-6f4b79d1-b368-4381-8b1e-205d87831517.mp4

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by para-dichloro-benzene** [comment]
Alright, I found this bug being also present in the forge version, opened an issue there.
https://github.com/Creators-of-Create/Create/issues/3125

**Comment by para-dichloro-benzene** [comment]
Alright, I found this bug being also present in the forge version, opened an issue there. (And accidently closed this issue, reopened now)
https://github.com/Creators-of-Create/Create/issues/3125

**Comment by TropheusJ** [comment]
Issues that occur on Forge as well are no longer being tracked on this repo. Please follow the respective issue on the Forge repo instead: https://github.com/Creators-of-Create/Create/issues/3125
