### ISSUE TITLE
Colormatic Incompatibility

### ISSUE THREAD

**Issue by ardissaps** [Fabricators-of-Create/Create#387]
### Describe the Bug

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Create' (create) mc1.18.2_v0.4.1+631 with any version that is compatible with:
		 - colormatic 3.1.1+mc.1.18.2
Unmet dependency listing:
	 - Mod 'Create' (create) mc1.18.2_v0.4.1+631 is incompatible with version 3.1.1 or earlier of mod 'Colormatic' (colormatic), but a matching version is present: 3.1.1+mc.1.18.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Reproduction Steps

Install Colormatic
Install Create
Launch game

### Expected Result

Launched

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

https://modrinth.com/mod/colormatic
Version 3.1.1

**Comment by TropheusJ** [comment]
yes, colormatic is broken. We can't fix it. I believe the issue was fixed in the 1.19 update.

**Comment by ardissaps** [comment]
> yes, colormatic is broken. We can't fix it. I believe the issue was fixed in the 1.19 update.

I removed colormatic, and not a big deal I guess, world still same.

**Comment by sleepingdragoninn** [comment]
Colormatic commit with the fix occurred before the 1.19 port, here's an artifact for any grumpy 1.18.2 modpack devs

[colormatic-3.1.2-snapshot+mc.1.18.2.jar.zip](https://github.com/Fabricators-of-Create/Create/files/9185741/colormatic-3.1.2-snapshot%2Bmc.1.18.2.jar.zip)
