### ISSUE TITLE
[1.18.2] Spongepowered warnings

### ISSUE THREAD

**Issue by itsdinkd** [Fabricators-of-Create/Create#388]
### Describe the Bug

This is popping up when starting a dedicated server and using create

### Reproduction Steps

1. Add Create
...

### Expected Result

not to have 2 warnings

### Crash Report or Log

https://pastebin.com/riWXpiHj

### Operating System

W11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
This does not mention Create at all, and it can be ignored if the game works properly.

**Comment by itsdinkd** [comment]
> 

It doesnt mention create however with binary searching, it was create that caused it.

**Comment by itsdinkd** [comment]
@TropheusJ  Did you see the above comment?

**Comment by TropheusJ** [comment]
not sure why it happens, but if nothing is wrong then it can be ignored.

**Comment by itsdinkd** [comment]
Sounds good
