### ISSUE TITLE
Smooth Lightning does not work on fluid tanks

### ISSUE THREAD

**Issue by ardissaps** [Fabricators-of-Create/Create#390]
### Describe the Bug

smooth lightning glitch

### Reproduction Steps

1. turn on smooth lightning
2. build fluid tank 2 tall
3. fill with lava
4. well

### Expected Result

smooth light

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/82106625/175455627-13a0129f-4eea-4706-8f81-efaa93ffdcfb.png)

### Operating System

windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

iris, complementary

**Comment by JieningYu** [comment]
toxic
<img width="224" alt="image" src="https://user-images.githubusercontent.com/61787533/174474431-425b2f44-249c-4f3f-8bef-c34511eace71.png">

**Comment by TropheusJ** [comment]
no idea what this is talking about, image did not upload

**Comment by ardissaps** [comment]
> no idea what this is talking about, image did not upload

I am so sorry didnt realized. edited the post.

**Comment by IThundxr** [comment]
Moved to upstream, https://github.com/Creators-of-Create/Create/issues/6851
