### ISSUE TITLE
Upwards transporting chutes do not insert items onto depots properly

### ISSUE THREAD

**Issue by TrombiKinkku** [Fabricators-of-Create/Create#391]
### Describe the Bug

When trying to insert items on to a depot with an upward transporting chute the depot stays visually empty and the transported item can be seen stuck at the top of the chute. Interacting with the depot via hand or funnels produces infinite items.

### Reproduction Steps

1. Create a chute with a mechanical fan below it blowing upwards.
2. Place a depot on top of the chute.
3. Insert an item in to the chute with a hopper or a funnel.

### Expected Result

The chute inserts the item onto the depot.

### Operating System

Linux

### Mod Version

0.4.1 patch 11

### Minecraft Version

1.18.2

### Other Mods

Fabric API 0.56.0+1.18.2

### Additional Context

Relogging to the world fixes the issue unless a funnel is taking items from the depot.

**Comment by TropheusJ** [comment]
should be fixed
