### ISSUE TITLE
A Chunk Contain Create Block Becoma Permanent Dark

### ISSUE THREAD

**Issue by ardissaps** [Fabricators-of-Create/Create#392]
### Describe the Bug

Whenever I build anyhing from create then teleport to any place (creative mode) then teleport back there a chunk that contain create block become permanent dark (screenshot included)

### Reproduction Steps

1. Build Create Object
2. Teleport
3. Teleport back to created object
...

### Expected Result

No problem

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/82106625/174528079-5eb11ce7-683a-472b-83ea-761f32728515.png)

### Operating System

Win 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
#318 or #355

**Comment by ardissaps** [comment]
> #318 or #355

Already fixed by using [Starlight](https://modrinth.com/mod/starlight) instead of Phospor.
