### ISSUE TITLE
Some sounds do not work with Presence Footsteps

### ISSUE THREAD

**Issue by ardissaps** [Fabricators-of-Create/Create#394]
### Describe the Bug

Maybe material tag or something hitbox? Only found Water Tank for now, other than that play proper sound with Presence of the Footstep sound. I'll post again if I found another block that does not sound.

The one that does not have sound (I'll add more if find again) :
- Fluid Tank
- Moving Object (Step sound missing when we jump on the moving example lift with rope pulley)

### Reproduction Steps

(with Presence of the Footstep mod)
1. Built Liquid Tank 
2. Jump on top of it

### Expected Result

Step sound

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/82106625/174709112-a648f8e6-2a0c-4e79-b9dc-8cc21f15d886.png)

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

https://modrinth.com/mod/presence-footsteps

### Additional Context

Other than that play sound,

**Comment by StockiesLad** [comment]
This isn't a create issue... this is clearly a presence footsteps compat issue

**Comment by ardissaps** [comment]
It can be fixed with few line of code, many mod added item have material item sound, no need to be exclusively unique just at least sound like wood or metal or stone or glass is ok. (but metal make sense for his tank rather than completely silent)

**Comment by StockiesLad** [comment]
That is fair

**Comment by TropheusJ** [comment]
the tank is fine, but contraptions are silent.

**Comment by TropheusJ** [comment]
Seems to be cancelling step sounds [here](https://github.com/Sollace/Presence-Footsteps/blob/cef692eee2ed9c2a32d8dd741c5d84bd43f80d46/src/main/java/eu/ha3/presencefootsteps/sound/SoundEngine.java#L158).

**Comment by Sollace** [comment]
I have looked at how to fix this and have made chances so PF no longer increments the next step counter to prevent steps from being played on the client, however that appears to be still not working.

Just a note: Create should be producing their steps on the client side. If you do that, it will work correctly.

**Comment by Sollace** [comment]
Update: Footsteps even do not play when the mod's functions are entirely disabled, so this seems like a problem only the Create devs can fix at this point.

**Comment by IThundxr** [comment]
Will be fixed by the next patch
