### ISSUE TITLE
Redstone Contact Still Emith Signal beside Not Connected

### ISSUE THREAD

**Issue by ardissaps** [Fabricators-of-Create/Create#396]
### Describe the Bug

Redstone Contact Still Emith Signal beside Not Connected causing the attached redstone device not turned off while moving.

### Reproduction Steps

1. Build 2 "Redstone Contact" block facing eachother 
2. Attack Iron Door to one of the Contact
3. Make one of Contact to Move (detail screenshot)

### Expected Result

While moving the Redstone Contact block should turned off and make the Iron Door close.

### Screenshots and Videos

![redstone contact iron door](https://user-images.githubusercontent.com/82106625/174963417-50f6b72d-1e40-4afd-9cf9-3c26f5413926.jpg)

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by ardissaps** [comment]
The picture taken while moving upward with Stationary Contraption

**Comment by TropheusJ** [comment]
blocks do not update on contraptions except for a few exceptions. A redstone contact in motion is always powered and will power stationary ones as they make contact.

**Comment by ardissaps** [comment]
> blocks do not update on contraptions except for a few exceptions. A redstone contact in motion is always powered and will power stationary ones as they make contact.

Is it possible to bring air in enclosed contraption when it moved to underwater, currently when submerged the air replaced with water.

**Comment by TropheusJ** [comment]
no
