### ISSUE TITLE
Deny list filter on single tunnel with multiple outputs breaks the routing of the tunnel

### ISSUE THREAD

**Issue by weegeeluigi** [Fabricators-of-Create/Create#397]
### Describe the Bug

A deny filter on a single tunnel with multiple outputs stops the tunnel from applying whatever filtering config is applied to it.  It appears in single tunnel setups, the deny filter will double as an implicit allow for every other item.  In other words, the deny filter will work correctly, but it will also behind the scenes appear to act as an allow for every other item(s) not in the deny filter, rendering the other tunnel outputs broken.

Attached screenshot shows the setup.  The tunnel is set to forced round robin.  The side with the filter is a deny filter with only coal.  Coal won't go on that belt.  It will go straight, as it should.  Place any other item on the belt though, and the tunnel will always output on the filter side where coal is denied.  It doesn't not alternate between that side and going straight, like it should.  It will only do so if you place an allow filter on the other side.

### Reproduction Steps

1.Setup a belt system where you can place a tunnel for more than 1 output.
2. Place a tunnel where you want to split the output.
3. Add a deny filter to one side (let's say, coal)
4. Set the filter to forced round robin
5. Coal never goes out the deny filter side (correct) and only the other output
6. Every other item not in the deny filter (so, not coal) will only go out the deny filter side only.  Round robin doesn't work, even if the output is valid.  The round robin fails.  The only way to get the round robin to work is to add an allow filter to the other output explicitly

### Expected Result

Coal or whatever denied item(s) don't go down that route, but other valid outputs function and output according to their filters or lack of filters.

### Screenshots and Videos

![2022-06-22_17 04 45](https://user-images.githubusercontent.com/7762155/175064952-d02e15f7-5a35-44b4-be63-8b07e6664d2a.png)

### Crash Report or Log

No crash so N/A

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Additional Context

Using latest patch 11

**Comment by TropheusJ** [comment]
identical to forge behavior

**Comment by weegeeluigi** [comment]
So is this a known bug or do I need to report it upstream?

**Comment by TropheusJ** [comment]
Not sure, check the issue tracker

**Comment by weegeeluigi** [comment]
Posted upstream last week and still no response, so I don't know if it's intended or not.  All I know is it's breaking my base since I hit an edge case where clay blocks the tunnel completely and won't go out any side.  Tunnels in general with filters just don't feel like they are working right.  A side with an allow list should only allow those items in the list out ONLY that side right or does it still allow on both sides?  Because it's doing just that and I don't believe it should since the allow list should block those items to that side.

I feel 100% this is bugged because if you remember me from the Iris perf post, I had this base built then and that was during beta and all these tunnels processed properly in testing the flows when I was building the project out.  Now that I turned the whole base on they don't after going full release.

**Comment by TropheusJ** [comment]
Issues that occur on Forge as well are no longer being tracked on this repo. Please follow the respective issue on the Forge repo instead: https://github.com/Creators-of-Create/Create/issues/3139
