### ISSUE TITLE
Weird wrench issues

### ISSUE THREAD

**Issue by andylmfao** [Fabricators-of-Create/Create#401]
### Describe the Bug

When right-clicking with a wrench, it only rotates blocks, and destroys belts in an odd way.

### Reproduction Steps

1. Get wrench
2. Right click on funnel, or belt (as shown)

### Expected Result

A fix for this in the next patch.

### Screenshots and Videos

https://gfycat.com/clumsycloudyasp

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Valhelsia: Enhanced vanilla modpack

### Additional Context

This for some reason only happened after updating from Patch 2 to the newest patch. Very very strange.

**Comment by TropheusJ** [comment]
Log please

**Comment by andylmfao** [comment]
https://pastebin.com/AT2v4Xpv Here you go!

**Comment by TropheusJ** [comment]
Could you try without refined storage and kubejs? they're erroring, and it looks like the server crashed in the video.

**Comment by andylmfao** [comment]
I'll give it a shot.

**Comment by andylmfao** [comment]
It was RS2,  I'll report it to the RS2 dev. Thanks!
