### ISSUE TITLE
Changing resource packs messes with textures

### ISSUE THREAD

**Issue by Tempest-5ky** [Fabricators-of-Create/Create#402]
### Describe the Bug

Recently updated to the newest release of Create Fabric, on the first server restart everything seemed fine but after a second, All my weighted ejectors had gained this texture on the top?
Quite strange, not sure what may have caused it.

### Reproduction Steps

Hard to say, honestly, because these would be unusual circumstances.

### Expected Result

Normal top texture, as they were before the update.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/99220350/175830488-730971b8-957d-45b3-8679-ff1126020e83.png)

### Crash Report or Log

n/a

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Pasted from the logs as there is a truly ungodly amount haha:

        - adabraniummod 2.2.1+1.18.2
	- additionalbanners 7.0.4
	- additionalbars 3.0.0
	- additionalentityattributes 1.0.0+1.18.2 via apoli
	- adorn 3.5.0+1.18.2
	- advanced_runtime_resource_pack 0.5.7 via missingwilds
	- advancednetherite 1.5.1-1.18.2
	- advdebug 2.3.0
	- adventure-platform-fabric 5.2.1 via minimotd-fabric
	- adventurez 1.4.10
	- ae2 11.1.2
	- alloy_forgery 2.0.13+1.18
	- alternate-current 1.3.0
	- amphitritecoffer 1.2.0
	- amplified-nether 1.1
	- animal_feeding_trough 1.0.3+1.18.2
	- annotateddi 2.1.0+1.18.2 via fireplacelib
	- antishulkerdupe 1.0.0
	- anvilrestoration-fabric 1.1
	- aopalliance_aopalliance 1.0 via annotateddi
	- apoli 2.3.3 via epoli
	- appbot 1.2.1
	- aqupdgrizzly 1.18-1.3
	- architects_palette 2.1
	- architectury 4.4.70
	- artifacts 7.0.3+fabric
	- artisanat 2.2.1
	- attributefix 1.0.3
	- audaki_cart_engine 1.0.2
	- autoconfig1u 3.4.0
	- autowhitelist 1.0.1
	- axesareweapons 1.5.1
	- backslot 1.2.6
	- backslotaddon 1.0.8
	- badpackets 0.1.2
	- badstdout 1.1.1-1.18
	- balm-fabric 3.0.0+0
	- banhammer 0.5.1+1.18.2
	- basicshields 1.3.1-1.18.2
	- bcc fabric-1.0.5
	- beaconoverhaul 1.6.0+1.18.2
	- beeinajar 1.0.0
	- beenfo 1.18.2-fabric0.47.10-1.3.3
	- besmirchment 1.18.2-11
	- better-snowball-fight 0.1
	- better_bad_omen 1.3.0
	- betteranimalsplus 1.18.2-11.0.5
	- betterconduitplacement-fabric 1.3
	- betterdeserttemples 1.18.2-Fabric-1.1.0
	- betterdungeons 1.18.2-Fabric-2.1.0
	- betterleads 1.0.1+1.18.1
	- bettermineshafts 1.18.2-Fabric-2.1.3
	- bettersafebed 1.18-fabric-a
	- betterstrongholds 1.18.2-Fabric-2.1.1
	- betterthanmending 1.3.0
	- bettervillage 1.0.1
	- betterwitchhuts 1.18.2-Fabric-1.0
	- bewitchment 1.18-21
	- bigbeacons 1.2.5
	- biomemakeover 1.18.2-1.4.24
	- blast 1.9.1
	- blastingsand 1.18.2-2
	- blockswap 1.0.1
	- blockus 2.4.7+1.18.2
	- blue_endless_jankson 1.2.1 via kyrptconfig
	- bookshelf 13.2.20
	- botania 1.18.2-433-FABRIC
	- box-of-placeholders 1.3.4+1.18
	- brokennametags 1.0.2
	- bwplus 1.18.2-16
	- byg 1.4
	- c2me 0.2.0+alpha.7.0
	- cacao 1.1
	- calio 1.5.1 via apoli
	- camp_fires_cook_mobs 1.2.6
	- campanion 3.0.4
	- campingsticks 1.18.2-1
	- capybara 1.0.4
	- cardinal-components ${version}
	- cardinal-components-base 4.1.4 via epoli
	- cardinal-components-block 4.1.4 via polymorph
	- cardinal-components-entity 4.1.4 via epoli
	- cardinal-components-item 4.1.4 via polymorph
	- cardinal-components-world 4.1.4 via charter
	- carpet 1.4.69
	- carpet-extra 1.4.72
	- carpet-fixes 1.18.x-1.7.9
	- carrynametag 1.0.1-1.18
	- catwalksinc 1.3.0
	- cauldronlib 1.2.2 via quicksand
	- ce 1.1.5
	- chainsuspension 1.1.0
	- chalk 2.0.1+1.18.2
	- charter 0.2.2
	- chat_plus 2.1.6
	- chestcavity 2.16.2
	- chimes 1.1.1
	- chipped 1.2
	- chunky 1.2.164
	- clean-logs 1.1.0
	- cloth-api 3.2.64
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-client-events-v0 3.2.64 via cloth-api
	- cloth-common-events-v1 3.2.64 via cloth-api
	- cloth-config 6.2.62
	- cloth-config-lite 2.0.6 via omega-config-gui
	- cloth-datagen-api-v1 3.2.64 via cloth-api
	- cloth-utils-v1 3.2.64 via cloth-api
	- cloud 1.7.0-SNAPSHOT via tabtps-fabric
	- cloud_commandframework_cloud-brigadier_ 1.7.0-SNAPSHOT via cloud
	- cloud_commandframework_cloud-core_ 1.7.0-SNAPSHOT via cloud
	- cloud_commandframework_cloud-minecraft-extras 1.7.0-SNAPSHOT via tabtps-fabric
	- cloud_commandframework_cloud-services_ 1.7.0-SNAPSHOT via cloud
	- clumps 8.0.0+8
	- cmdspy 1.2.4
	- cobbled_paths 0.1.7
	- collective-fabric 4.27
	- coloredglowlib 1.3.3
	- columns 1.4.0
	- com_electronwill_night-config_core 3.6.5 via couplings
	- com_electronwill_night-config_toml 3.6.5 via couplings
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_fasterxml_jackson_core_jackson-annotations 2.13.1 via disfabric
	- com_fasterxml_jackson_core_jackson-core 2.13.1 via disfabric
	- com_fasterxml_jackson_core_jackson-databind 2.13.1 via disfabric
	- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.13.0 via essential_commands
	- com_github_llamalad7_mixinextras 0.0.10 via debugify
	- com_google_code_findbugs_jsr305 3.0.2 via autowhitelist
	- com_google_inject_guice 5.1.0 via annotateddi
	- com_h2database_h2 1.4.200 via factions
	- com_ishland_c2me_libs_ 0.2.0+alpha.7.0 via c2me
	- com_konghq_unirest-java_standalone 3.13.4 via disfabric
	- com_moandjiezana_toml_toml4j 0.7.2 via deepslatecutting
	- com_neovisionaries_nv-websocket-client 2.14 via autowhitelist
	- com_squareup_okhttp3_okhttp 3.13.0 via autowhitelist
	- com_squareup_okio_okio 1.17.2 via autowhitelist
	- com_typesafe_config 1.4.2 via tabtps-fabric
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- compacthelpcommand-fabric 1.1
	- companion 2.0.1
	- completeconfig 1.4.1
	- compostable-rottenflesh 1.0.0
	- conditional-mixin 0.1.5 via carpet-fixes
	- conduitspreventdrowned-fabric 1.5
	- config2brigadier 1.1.1 via fabrictailor
	- conjuring 1.0.22+1.18
	- connectiblechains 2.1.1+1.18.2
	- connectivity 1.18.2-2.9
	- consistency_plus 0.5.0+1.18.2
	- convenient-mobgriefing 2.0.2
	- conveyor-belts 1.8
	- copper_pipe r1.9
	- couplings 1.8.0+1.18.2
	- cpm 0.4.3a
	- crafted 1.3.1
	- crafttweaker 9.1.153
	- crawl 0.10.6
	- create mc1.18.2_v0.4.1+637
	- createaddition ${version}
	- creeperoverhaul 1.3.1
	- crimsonmoon 2.3.0-1.18.2
	- crops_love_rain 1.2.2
	- croptopia 2.0.5
	- crowdin-translate 1.4+1.18.2 via beenfo
	- cyanide 2.1.1
	- damagetilt 1.18-fabric-0.1.2
	- dankstorage 1.18.2-3.7
	- darkpaintings 10.0.3
	- dawn 3.3.1
	- de_poiu_apron_apron 2.1.1 via mconfig
	- deathbackup-fabric 1.5
	- debugify 1.11.0
	- decorative_blocks 2.1.0
	- deepslatecutting 1.3.4
	- deepslateinstamine 1.5
	- dimheight 1.1.1
	- discerning_furnace 1.0.6
	- disfabric 1.3.7
	- dramaticdoors 1.18.2-1.1.1
	- drinkbeer 3.0.2
	- dripstone_fluid_lib 1.2.0 via milk_plus
	- drogtor 1.1.2
	- dual_riders 1.1.1
	- dusk 1.18.2-1.9
	- dustrial_decor 0.5
	- dynmap 3.4-beta-3
	- dynview 1.18.2-2.2
	- early_buckets 2.0.0+1.18.2
	- earthbounds 1.18.2-1.1.2a
	- easierpowderedsnow 1.0.1
	- easymagic 3.3.0
	- ec-core 1.0.1-mc1.18.2 via essential_commands
	- ecologics 1.5.4
	- eer 1.0.2+1.18
	- egg-of-capitalism 3.1
	- elytratrinket 3.0.0-1.18.1
	- enchant_the_rainbow 1.0.1
	- enchantinginfuser 3.2.0
	- enderchests 1.0.9
	- enderitemod 1.3.5
	- endermenarefriends 1.1-mc1.17-fabric
	- epoli 1.0.1
	- essential_commands 0.23.0-mc1.18.2
	- exoriadvzbylily 1.0
	- exoricropbylily 1.0
	- expandability 6.0.0 via artifacts
	- expanded_armor_enchanting 1.0.2
	- expanded_axe_enchanting 1.0.3
	- expanded_weapon_enchanting 1.0.2
	- expandeddelight 0.1.8.1
	- experiencebugfix 18
	- extended_drawers 1.2.1+mc.1.18.2
	- extra_classes_origins 1.0.0
	- extrakeybinds 0.2.0
	- extraorigins 1.18-11
	- fabric 0.56.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.22+d7c144a860 via fabric
	- fabric-content-registries-v0 3.1.0+6f01bfd860 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric
	- fabric-data-generation-api-v1 3.0.0+9fcb91d260 via fabric
	- fabric-diagonal-panes 0.6.1
	- fabric-dimensions-v1 2.1.19+ffb2c71e60 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.18+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.5.1+6c4e5d0960 via fabric
	- fabric-item-groups-v0 0.3.13+91896a4960 via fabric
	- fabric-language-kotlin 1.7.3+kotlin.1.6.20
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric
	- fabric-loot-api-v2 1.0.0+e747827960 via fabric
	- fabric-loot-tables-v1 1.1.0+e747827960 via fabric
	- fabric-mining-level-api-v1 2.1.3+cc71601c60 via fabric
	- fabric-networking-api-v1 1.0.22+e6b169eb60 via fabric
	- fabric-networking-v0 0.3.9+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.2+032c981d60 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via invview
	- fabric-registry-sync-v0 0.9.9+0d9ab37260 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.5.1+e747827960 via fabric
	- fabric-screen-handler-api-v1 1.2.1+1f6558e860 via fabric
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric
	- fabricloader 0.14.7
	- fabricshieldlib 1.5.3-1.18
	- fabrictailor 1.8.2
	- factions 1.5.0
	- fake-player-api 0.3.0 via create
	- fallingtree 3.5.1
	- fallthroughslime-fabric 1.4
	- fancysporeblossom 1.0.0
	- farmersdelight 1.18.2-0.2.1
	- farsighted-mobs 1.1-1.18
	- fastbench 1.18.1-3
	- fastload 1.0.0
	- feature_nbt_deadlock_be_gone 2.0.0+1.18.2-rc1
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via patchouli
	- fireplacelib 6.3.1+1.18.2
	- fishofthieves 1.0.6
	- floral_flair 1.3.0
	- flytre_lib 1.8.1
	- foodplusid 1.4.0
	- forge_tags 2.1 via create
	- forgeconfigapiport 3.2.0
	- forgero 1.18.2-BETA-0.8.5
	- forgivenessmod 1.2.0
	- foxglow 1.2.8
	- freedomofinsomnia 1.1.1
	- ftbchunks 1802.3.6-build.147
	- ftblibrary 1802.3.6-build.123
	- ftbquests 1802.3.8-build.101
	- ftbranks 1801.1.6-build.22
	- ftbteams 1802.2.6-build.51
	- ftbultimine 1802.3.3-build.55
	- furnacerecycle-fabric 1.2
	- gargantuan 1.2.4
	- geckolib3 3.0.47
	- geodes 1.4.2
	- glassential 1.3.0
	- go-fish 1.5.0-1.18.2
	- gobber2 2.5.74
	- gottagofast 1.0.2
	- grindenchantments 1.6.4+1.18.2
	- guardiansgalore 1.18.2-3.0
	- guarding 1.1.1
	- halfdoors 1.18.2-fabric-1.3.6
	- harvest_scythes 2.5.1
	- herdspanic 1.0.5
	- hologram-api 0.2.1+1.18-pre5 via holograms
	- holograms 1.3.1+1.18.2
	- hookshot 25.0
	- horizontalpanes 1.1.7+1.18.2
	- horsebuff 2.0.0
	- horseinboat 1.1.2
	- horsestonks 1.0.1
	- hoverpets 0.3.3
	- ia 1.1
	- icarus 1.11
	- immersive_weathering 2.5.5
	- impaled 1.1.3
	- impersonate 2.5.0
	- infinitevillagertrading 1.18.2-fabric0.47.10-1.1
	- infusion_table 1.1.0
	- ingredient-extension-api 2.0.5
	- inmis 2.6.0-1.18.2
	- interference 1.4.1 via redbits
	- invview 1.4.8-1.18+
	- io_leangen_geantyref_geantyref 1.3.13 via cloud
	- ironfurnaces 3.0.0
	- itemfilters 1802.2.7-build.27
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- javax_inject_javax_inject 1 via annotateddi
	- justplayerheads-fabric 1.8
	- kambrik 3.0.1-1.18
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- keepheadnames 1.5.1
	- kfa 1.0.0
	- kibe 1.9.7-BETA+1.18
	- kiln 1.0.0
	- kiwi 6.0.2
	- kleeslabs 11.0.0
	- krypton 0.1.9
	- kyrptconfig 1.3.4-1.18 via quickshulker
	- lava_walker Fabric-1.18.2-0.1.1
	- ledger 1.2.4
	- lengthyladders 1.0.5
	- libgui 5.3.2+1.18.2 via probablychests
	- libninepatch 1.1.0 via libgui
	- libraryferret 1.0.3
	- lifts 1.4.1-BETA+1.18
	- limitedchunks 1.18.2-2.5
	- lithium 0.7.10
	- logbegone 1.0.1
	- lootr 0.3.20.57
	- lovely_snails 1.0.4+1.18
	- luckperms 5.4.25
	- lucys_sloths 1.0-SNAPSHOT
	- macawsbridgesbyg 1.18.2-1.2
	- macawsroofsbyg 1.18.2-1.0
	- maelstrom_library 1.2.4-1.18.2 via mobs_attempt_parkour
	- mantori 1.0.0-1.18.2
	- mavm 1.0.7a
	- maybe-data 1.3.1-1.18.2 via deepslatecutting
	- mconfig 1.2.0 via extended_drawers
	- mcwbridges 2.0.3
	- mcwdoors 1.0.6
	- mcwfences 1.0.5
	- mcwlights 1.0.3
	- mcwpaintings 1.0.3
	- mcwroofs 2.1.2
	- mcwtrpdoors 1.0.5
	- mcwwindows 2.0.3
	- megane 7.5.1
	- megane-api 7.1.0 via megane
	- megane-applied-energistics-2 7.1.0 via megane
	- megane-fabric-transfer 7.1.0 via megane
	- megane-kibe 7.1.0 via megane
	- megane-reborn-core 7.1.0 via megane
	- megane-reborn-energy 7.0.0 via megane
	- megane-runtime 7.2.0 via megane
	- megane-tech-reborn 7.1.0 via megane
	- megane-vanilla 7.1.1 via megane
	- megaparrot 1.0.5
	- midashunger 2.1.0+1.18.2
	- midnightlib 0.4.0 via puddles
	- mighty_mangoes 1.0.6
	- milk 0.3.2 via create
	- milk_plus 3.0.1
	- minecraft 1.18.2
	- minimotd-fabric 2.0.7
	- missingwilds 1.0.1
	- mm 2.3 via fabricshieldlib
	- mo_glass 1.6.1-MC1.18.2
	- mobs_attempt_parkour 0.2.5-1.18.2
	- modid 1.0.0
	- modify-drops-api 0.4.0.2 via chestcavity
	- monsters_in_the_closet 1.0.3+1.18
	- more-axolotls 1.0.2
	- morevillagers-fabric 3.2.0-SNAPSHOT
	- mostructures 1.4.2+1.18.2
	- multi_item_lib 1.5.2
	- multiworldborders 1.4-fabric-1.18.2
	- myron 1.6.3+1.18.1 via shetiphiancore
	- mysql_mysql-connector-java 8.0.29 via banhammer
	- mythicmounts 1.18.2-7.0
	- naturescompass 1.18.2-2.0.3-fabric
	- ncake 1.2.0
	- net_dv8tion_jda 5.0.0-alpha.1 via disfabric
	- net_kyori_adventure-api 4.10.1 via adventure-platform-fabric
	- net_kyori_adventure-key 4.10.1 via adventure-platform-fabric
	- net_kyori_adventure-platform-api 4.1.0 via adventure-platform-fabric
	- net_kyori_adventure-serializer-configurate4 4.10.1 via tabtps-fabric
	- net_kyori_adventure-text-feature-pagination 4.0.0-SNAPSHOT via tabtps-fabric
	- net_kyori_adventure-text-minimessage 4.10.1 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-gson 4.10.1 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-legacy 4.10.1 via tabtps-fabric
	- net_kyori_adventure-text-serializer-plain 4.10.1 via adventure-platform-fabric
	- net_kyori_examination-api 1.3.0 via adventure-platform-fabric
	- net_kyori_examination-string 1.3.0 via adventure-platform-fabric
	- net_sf_trove4j_trove4j 3.0.3 via autowhitelist
	- netherchest 4.0
	- netherite_nugget 1.4.1
	- neutrino 0.7.1
	- nicemod 0.2
	- notenoughcrashes 4.1.6+1.18.2
	- numismatic-overhaul 0.2.2+1.18
	- nyfsquiver Fabric-0.5.0-1.18.2
	- observable 2.2.3
	- observed 1.3.1
	- omega-config 1.2.3-1.18.1 via mostructures
	- omega-config-gui 1.2.1-1.18.1 via reroll
	- online_detector 1.18.2-2.0.2
	- onsoulfire 1.18-3
	- org_apache_commons_commons-collections4 4.1 via autowhitelist
	- org_javassist_javassist 3.29.0-GA via crafttweaker
	- org_jetbrains_annotations 16.0.1 via autowhitelist
	- org_jetbrains_kotlin_kotlin-reflect 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_json_json 20211205 via pickyourpoison
	- org_reflections_reflections 0.10.2 via crafttweaker
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- org_xerial_sqlite-jdbc 3.36.0.3 via banhammer
	- oricropbylily 1.0
	- oridralobylily 1.0
	- origins 1.4.1
	- origins-classes 1.3.0
	- overweight_farming 1.18.2-1.4.2-fabric
	- owo 0.7.2+1.18
	- oxidized 1.6.4
	- packages 1.4
	- packet_tweaker 0.2.0+1.18-pre1 via server_translations_api
	- paperbooks-fabric 1.4
	- parry 1.3+1.18
	- patchouli 1.18.2-69-FABRIC
	- paxi 1.18.2-Fabric-2.0
	- pehkui 3.3.2+1.14.4-1.19
	- pettablebees 1.1.0
	- pickyourpoison 1.0.8
	- piglessportals 1.1.0
	- pisces 1.0.0+1.16.4
	- placeholder-api 1.1.3+1.17.1 via box-of-placeholders
	- placementpog 1.0.0
	- pladder 0.3.0
	- platforms 1.2.4
	- player-data-api 0.1.0+1.18 via styledplayerlist
	- player_events 2.3.0
	- player_events_api 2.3.0 via player_events
	- playerabilitylib 1.5.0 via besmirchment
	- plushies 1.2
	- polaroidcamera 1.2.9
	- polymorph 0.0.21-1.18.2
	- porting_lib 1.1.317-beta+1.18.2-dev.7ad1f24 via create
	- probablychests 0.4.3
	- promenade 2.6.3
	- puddles 1.2.1
	- pugh_lib 1.3.0 via gobber2
	- pugh_tools 1.2.5 via gobber2
	- puzzleslib 3.3.5
	- questsadditions 1.3.1
	- quicksand 1.1.0
	- quickshulker 1.3.6-1.18
	- rangers_haven 2.3.1
	- ratsmischief 1.3.7
	- reach-entity-attributes 2.1.1 via epoli
	- reborncore 5.2.0 via techreborn
	- redbits 1.13.3
	- registrate-fabric MC1.18.2-1.0.3 via create
	- regrowth 0.30d.release
	- reinforced_bows 1.18.2 - 1.1
	- repurposed_structures 4.1.14+1.18.2
	- reroll 1.5.0-1.18.2
	- respawningshulkers-fabric 1.6
	- revamped_phantoms 0.2.3
	- ringsofascension 1.0.1
	- rocks 1.6.0
	- scaffoldforever 1.1+1.17.1
	- secretrooms 1.3.1+1.18.2
	- serialization_hooks 0.2.0+1.18.f5d4aa6 via porting_lib
	- server-hats 0.9
	- server_translations_api 1.4.9+1.18.2-rc1 via holograms
	- sgui 1.0.2+1.18.2 via banhammer
	- sheepconsistency 1.0.4
	- shetiphiancore 1.2.10
	- shroomlight_slab 1.2
	- shulkerutils 1.0.4-1.18 via quickshulker
	- shwfox 1.3+fabric
	- sign_editor 0.8.3
	- silky-hands 1.0.2
	- simplycotton 1.1.0
	- slabby 0.2.3
	- slapmap 1.1.0+1.18
	- sleepwarp 1.1.1+1.18.2
	- slime 1.1
	- slimyfloor 1.18.2-1.2.3
	- slipperywalls 1.0.0+1.17
	- smoothboot 1.18.2-1.7.0
	- smootherbedrock 1.0.4
	- smwyg 1.0.1
	- snailmail 1.18.2-1.1.0
	- snowballkb 1.1-1.18.1
	- snowrealmagic 4.0.0
	- snowytrees 1.1.0
	- someforgepatchesported 1.0.3
	- spark 1.9.11
	- sprout 1.3.1
	- stacc 1.3.0 via numismatic-overhaul
	- stackablepotions 1.0.0
	- starlight 1.0.2+fabric.89b8d9f
	- static-content 1.0.1-1.16.2 via wolveswitharmor
	- staticdata 1.1.2 via static-content
	- step-height-entity-attribute 1.0.0 via botania
	- stonecutter_recipe_tags 3.0.1+1.18.bc850d5.fabric via consistency_plus
	- stoneholm 1.4.3
	- styledplayerlist 2.1.3+1.18
	- syncmatica 1.18.2-0.3.2
	- tabtps-fabric 1.3.13
	- taxfreelevels 1.2.1
	- team_reborn_energy 2.2.0 via createaddition
	- techreborn 5.2.0
	- terrablender 1.1.0.99
	- terraform-shapes-api-v1 2.1.0 via promenade
	- terraform-wood-api-v1 3.0.0 via besmirchment
	- the_bumblezone 5.1.2+1.18.2
	- things 0.2.18+1.18
	- thorium 1.2.1
	- tinyskeletons 3.2.1
	- tolaserblade 1.18.2-0.6.0.0
	- toolleveling 1.18.1 - 1.3.0
	- trade_cycling 1.18.2-1.0.2
	- tradingpost 3.2.0
	- tramplenomore 6.0.1
	- transferpet 0.0.5
	- transportables 1.2
	- travelersbackpack 1.18.2-7.1.0
	- trinketofundying 2.0.1-1.18
	- trinkets 3.3.1
	- trmanual 1.0.0
	- tweed4_annotated 1.3.0 via wandering_collector
	- tweed4_base 1.5.0+mc1.18.2 via wandering_collector
	- tweed4_data 1.2.1+mc1.18.2 via wandering_collector
	- tweed4_data_hjson 1.1.0 via wandering_collector
	- universal_ores 1.2.1
	- universalbonemeal 3.0.5
	- usefulutilities 1.0.1
	- variablespawnerhardness 1.18.2-1.2.2
	- villagers-follow-emeralds 1.2.0
	- visualworkbench 3.3.0
	- vmp 0.2.0+beta.3.17
	- voicechat 1.18.2-2.2.45
	- vulnerableflight 1.0.0
	- walljump 1.4.2+1.18.2
	- wandering_collector 1.1.2+mc1.18.2
	- wandering_trapper 1.2.0
	- waystones 10.0.0
	- weakerspiderwebs-fabric 2.0
	- welcomemessage-fabric 1.0
	- whereisit 1.14.10
	- whisperwoods 1.18.2-2.1.0
	- whyamionfire 1.1.2
	- wie 1.1.0
	- wildlife 1.18.2-2.0
	- windchimes 1.2.0
	- wireless_redstone 2.0.5
	- wither_cage_fix 1.0.12
	- wolveswitharmor 1.7.1-1.18.2
	- wooltweaks-fabric 1.5
	- world-data 1.0.3-1.18.2 via crimsonmoon
	- worldedit 7.2.10+1742f98
	- worldspecificviewdistance 0.1.0-1.18
	- wthit 4.10.3
	- wthit-plugins 1.0.6+1.18.2
	- xp_storage 1.4.3+1.18
	- xp_storage_trinkets 0.1+1.18
	- yigd 1.3.6
	- yungsapi 1.18.2-Fabric-2.0.8
	- yungsbridges 1.18.2-Fabric-2.1.0
	- yungsextras 1.18.2-Fabric-2.1.0
	- zombiehorsespawn-fabric 3.0

**Comment by TropheusJ** [comment]
restart your game

**Comment by TropheusJ** [comment]
I believe this has been fixed
