### ISSUE TITLE
Portable storage interface does not extract everything from moving contraption.

### ISSUE THREAD

**Issue by BorkonStuff** [Fabricators-of-Create/Create#404]
### Describe the Bug

I built a quick and dirty quarry just to test that things work on Fabric. Similar design worked on Forge Create mod version 0.3.2g. 4 funnels connected to the portable storage interface. After eating one layer of world the portable storage interface connects correctly, spits out a handful of stacks and gives up after a few seconds (normally unloading is the slowest part of quarrying). After a few more layers of the world the storage barrels on the quarry get full and hilarity ensues with thousands of entities filling the world until it grinds to a halt.

Tested and reproduced on Create Fabric v0.4.1+637 (from a few hours ago), may or may not be related to #395 which was closed in an earlier release. Either that fix wasn't sufficient or this is a different bug or somehow the fix got undone.

### Reproduction Steps

1. Make moving contraption that gathers stuff.
2. Unload with portable storage interface.

### Expected Result

I expect the portable storage interface to fully unload everything.

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Additional Context

The quarry is functionally the same as the one I did here: https://youtu.be/xpb_YH8XkoE but in a new quick and dirty test world and rather than doing the song and dance with barrels the funnels just drop items 5 blocks down into a water stream for a different loot management system. The result was the same when it was just one smart chute sucking items out of the storage interface and even just one chute should be able to unload everything (although slower).

**Comment by Icewater661** [comment]
It works same as #395.
