### ISSUE TITLE
Broke the entire game

### ISSUE THREAD

**Issue by SirBlueAxolotl** [Fabricators-of-Create/Create#406]
### Describe the Bug

Breaking the entire game when creating a new world

### Reproduction Steps

I don't understand what this means

### Expected Result

Fixed the crash when creating a new world

### Crash Report or Log

---- Minecraft Crash Report ---- // Shall we play a game?  Time: 2022-06-29, 4:05 p.m. Description: Exception in server tick loop  java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3898 failed 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 	at net.minecraft.class_3215.<init>(class_3215.java:85) 	at net.minecraft.class_3218.<init>(class_3218.java:223) 	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:374) 	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:330) 	at net.minecraft.class_1132.method_3823(class_1132.java:70) 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) 	at java.base/java.lang.Thread.run(Thread.java:833) Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) 	... 11 more Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [porting_lib.mixins.common.json:ChunkMapMixin] from phase [DEFAULT] in config [porting_lib.mixins.common.json] from mod [porting_lib] FAILED during APPLY 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) 	... 14 more Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("JUMP") on net/minecraft/class_3898::port_lib$startTrackingChunk with priority 1000 cannot inject into net/minecraft/class_3898::method_17241(Lnet/minecraft/class_3222;Lnet/minecraft/class_1923;Lorg/apache/commons/lang3/mutable/MutableObject;ZZ)V merged by qouteall.imm_ptl.core.mixin.common.chunk_sync.MixinChunkMap_C with priority 1100 [PREINJECT Applicator Phase -> porting_lib.mixins.common.json:ChunkMapMixin -> Prepare Injections ->  -> handler$zcp000$port_lib$startTrackingChunk(Lnet/minecraft/class_3222;Lnet/minecraft/class_1923;Lorg/apache/commons/lang3/mutable/MutableObject;ZZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare] 	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) 	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) 	... 14 more   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- System Details -- Details: 	Minecraft Version: 1.18.2 	Minecraft Version ID: 1.18.2 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.1, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 1190228984 bytes (1135 MiB) / 1845493760 bytes (1760 MiB) up to 2147483648 bytes (2048 MiB) 	CPUs: 4 	Processor Vendor: GenuineIntel 	Processor Name: Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz 	Identifier: Intel64 Family 6 Model 60 Stepping 3 	Microarchitecture: Haswell (Client) 	Frequency (GHz): 3.70 	Number of physical packages: 1 	Number of physical CPUs: 2 	Number of logical CPUs: 4 	Graphics card #0 name: NVIDIA GeForce GTX 1650 	Graphics card #0 vendor: NVIDIA (0x10de) 	Graphics card #0 VRAM (MB): 4095.00 	Graphics card #0 deviceId: 0x1f82 	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 1.33 	Memory slot #0 type: DDR3 	Memory slot #1 capacity (MB): 8192.00 	Memory slot #1 clockSpeed (GHz): 1.33 	Memory slot #1 type: DDR3 	Virtual memory max (MB): 31845.43 	Virtual memory used (MB): 20492.82 	Swap memory total (MB): 15527.64 	Swap memory used (MB): 2219.09 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	Fabric Mods:  		chiselsandbits: Chisels & Bits 1.2.84 		create: Create mc1.18.2_v0.4.1+637 			com_electronwill_night-config_core: core 3.6.3 			com_electronwill_night-config_toml: toml 3.6.3 			com_google_code_findbugs_jsr305: jsr305 3.0.2 			fake-player-api: Fake Player API 0.3.0 			flywheel: Flywheel 1.18-0.7.0.26 			forge_tags: Forge Tags 2.1 			forgeconfigapiport: Forge Config API Port 3.2.0 			milk: Milk Lib 0.3.2 				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0 			noindium: No Indium? 1.0.1+1.18.2 				omega-config: OmegaConfig 1.2.3-1.18.1 			porting_lib: Porting Lib 1.1.317-beta+1.18.2-dev.7ad1f24 				com_github_llamalad7_mixinextras: MixinExtras 0.0.10 				mm: Manningham Mills 2.3 				serialization_hooks: Serialization Hooks 0.2.0+1.18.f5d4aa6 			reach-entity-attributes: Reach Entity Attributes 2.1.1 			registrate-fabric: Registrate for Fabric MC1.18.2-1.0.3 		fabric: Fabric API 0.57.0+1.18.2 			fabric-api-base: Fabric API Base 0.4.4+d7c144a860 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560 			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560 			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860 			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60 			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860 			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860 			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860 			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960 			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60 			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260 			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60 			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860 			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60 			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60 			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260 			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560 			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.2+d005b03a60 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60 			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560 			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860 			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560 			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960 		fabricloader: Fabric Loader 0.13.3 		immersive_portals: Immersive Portals 1.3.6 			cloth-config: Cloth Config v6 6.0.42 				cloth-basic-math: cloth-basic-math 0.6.0 			imm_ptl_core: Immersive Portals Core 1.3.6 			q_misc_util: QMiscUtil 1.3.6 		java: OpenJDK 64-Bit Server VM 17 		minecraft: Minecraft 1.18.2 		pehkui: Pehkui 3.2.2+1.14.4-1.19 			kanos_config: Kanos Config 0.2.0+1.14.4-1.19 		worldedit: WorldEdit 7.2.10+1742f98 	Flywheel Backend: GL33 Instanced Arrays 	Server Running: true 	Player Count: 0 / 8; [] 	Data Packs: vanilla, Fabric Mods 	World Generation: Stable 	Type: Integrated Server (map_client.txt) 	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

![Screenshot (1357)](https://user-images.githubusercontent.com/105134703/176533570-516bed41-56bb-4c7b-9f41-f284f2ba159e.png)

**Comment by TropheusJ** [comment]
try without immersive portals

**Comment by SirBlueAxolotl** [comment]
ok

**Comment by SirBlueAxolotl** [comment]
It's fixed
