### ISSUE TITLE
Redstone Link can only Face North

### ISSUE THREAD

**Issue by ardissaps** [Fabricators-of-Create/Create#407]
### Describe the Bug

Can not rotate the Redstone Link

### Reproduction Steps

1. Put Redstone Link to all directio from where you are standing.
2. Redstone Link only facing North.

### Expected Result

Redstone Link face you. (Visually)

### Screenshots and Videos

![Uploading image.png…]()

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
working as intended

**Comment by ardissaps** [comment]
> working as intended

yes it works, but model could face every direction depending on place we are facing (for aesthetic)

**Comment by JieningYu** [comment]
You should report it to upstream as suggestion.

**Comment by ardissaps** [comment]
> You should report it to upstream as suggestion.

I'll try, thanks
