### ISSUE TITLE
Brass-encased things do not have any recipes or ponders

### ISSUE THREAD

**Issue by StockiesLad** [Fabricators-of-Create/Create#409]
### Describe the Bug

Things like brass encased cogwheel, etc, have 0 REI data on it

### Reproduction Steps

It takes 1 synapse to know how to reproduce this

### Expected Result

For ponders and recipes

### Crash Report or Log

NaN

### Operating System

Win 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Happens regardless

### Additional Context

Is this already known?

**Comment by JieningYu** [comment]
work as intended

**Comment by DarianLStephens** [comment]
I guess maybe it should have the same ponder thing as the casings?

**Comment by TropheusJ** [comment]
are these present on Forge?

**Comment by JieningYu** [comment]
As long as I know, no.

**Comment by TropheusJ** [comment]
closing, still don't know what exactly this is talking about. The one example, brass encased cogwheel, has no ponder on forge either.
