### ISSUE TITLE
Commented out player entity check causes crash if blocks are placed by non-player entity 

### ISSUE THREAD

**Issue by skylorbeck** [Fabricators-of-Create/Create#410]
https://github.com/Fabricators-of-Create/Create/blob/d9851d3035dfd9b1a182be1ca52385179324c5ab/src/main/java/com/simibubi/create/content/curiosities/symmetry/SymmetryHandler.java#L49

This commented out check causes a crash if a modded entity places blocks see: https://github.com/skylorbeck/MageHand/issues/8

**Comment by skylorbeck** [comment]
This is the Forge version for reference https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/main/java/com/simibubi/create/content/curiosities/symmetry/SymmetryHandler.java#L52

**Comment by skylorbeck** [comment]
Heads up, this bug is back and the code is commented out again. https://github.com/Fabricators-of-Create/Create/blob/8e42841e2577ee4c5535ff1563e04dd7ef9dbf4b/src/main/java/com/simibubi/create/content/curiosities/symmetry/SymmetryHandler.java#L49

**Comment by TropheusJ** [comment]
How…

**Comment by skylorbeck** [comment]
Also this code is commented out in every branch I could find.

**Comment by TropheusJ** [comment]
looking at this again, this is not an issue. The comment could be removed, but my fix was a null check a few lines down, which is still present. If something is crashing, it's a separate issue.

**Comment by skylorbeck** [comment]
Okay well I guess having support for nonplayer entities placing blocks isn't important then. I'll be sure to pass that onto all my users who crash because of it.

**Comment by TropheusJ** [comment]
This event only listens for players placing blocks. If non-players placing is crashing, it's a separate issue and I'd still like to see the log and maybe fix it.

**Comment by skylorbeck** [comment]
> This event only listens for players placing blocks. If non-players placing is crashing, it's a separate issue and I'd still like to see the log and maybe fix it.

You should read the whole thread. You guys already fixed this bug once and I've linked a user's crash log in the opening post. You aren't listening for players, you're listening for onblockplaced and you explicitly commented out the filter for players. I don't really care if it's fixed or not but at least understand what you're saying.

**Comment by skylorbeck** [comment]
This check will fail when a nonplayer entity places a block. https://github.com/Fabricators-of-Create/Create/blob/8e42841e2577ee4c5535ff1563e04dd7ef9dbf4b/src/main/java/com/simibubi/create/content/curiosities/symmetry/SymmetryHandler.java#L56
You are in OnBlockPlaced which is called when blocks are placed. You cannot guarantee players will be the only code that reaches here. I don't even know why this is an issue.
