### ISSUE TITLE
Allow redstone links to read adjacent analog signals on moving objects. 

### ISSUE THREAD

**Issue by RaMcHiPTech** [Fabricators-of-Create/Create#411]
### Describe the Suggestion

Not sure if bug or suggestion so will post as suggestion.  I am building an elevator that has a strip of analog switches going up the entire elevator shaft that is read by a redstone link and fed back to redstone links which power nixie tubes.  Whenever the elevator is in motion, the nixie tubes all go to 0 and then just pop to the floor once its reached that floor.  Is it possible to get the redstone links and nixie tubes to communicate and light up while the elevator is in motion?

**Comment by TropheusJ** [comment]
not possible, and we won't be changing it. We don't make gameplay changes, you'd want the forge repo for this suggestion.

**Comment by RaMcHiPTech** [comment]
Thanks man!  Bad news but truly appreciate the insanely fast response!!!
