### ISSUE TITLE
create mod performance improvement

### ISSUE THREAD

**Issue by posral** [Fabricators-of-Create/Create#412]
### Describe the Suggestion

hi! i am currently doing a create playthrough and i noticed huge framerate drop when i staying close enough to big mechanisms (from ~500 to ~30 fps), so could you please optimize it? yesterday, i found an enthusiast who did an experimental render which made their framerate a lot better, but it is for forge 1.15, i will leave a link to this project below. hope it helps.

### Additional Context

https://github.com/Jozufozu/Create/releases/tag/v0.3e-experimental-rendering

**Comment by JieningYu** [comment]
It seems that the experimental rendering use Flywheel which is now used by Create Fabric.

**Comment by TropheusJ** [comment]
flywheel is used on fabric too. use `/flywheel backend` and try all 3 options, see which one performs best on your computer.
