### ISSUE TITLE
Wand of Symmetry not breaking blocks in survival

### ISSUE THREAD

**Issue by AlexandruGabi47** [Fabricators-of-Create/Create#413]
### Describe the Bug

When using the Wand of Symmetry in survival, placing blocks works as intended, but breaking them isn't, if you switch to creative you will notice it works as intended.

### Reproduction Steps

1. Right click wand of symmetry using any mode and make sure you're in survival
2. Place any block(this step could be skipped if you already have an area made out of the same blocks)
3. Break said block in survival and notice how the mirrored blocks aren't being broken

### Expected Result

Wand of Symmetry should mirror when you break the same block not just when you place one

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Additional Context

It works as intended in creative

**Comment by 2000Slash** [comment]
Hey since I also encountered this issue, I looked at the code and saw that it is actually disabled when you are in survival. This is a simple fix, although I don't really know if it affects anything else since I'm not familiar with the codebase.
