### ISSUE TITLE
Goggle Double Overlapping Overlay Glitch (on survival only)

### ISSUE THREAD

**Issue by ardissaps** [Fabricators-of-Create/Create#414]
### Describe the Bug

Overlapping double overlay for goggle when switch to Survival Mode (no problem in Creative Mode).

### Reproduction Steps

1. Wear Goggle
2. Look at any Goggleable block
3. Double overlapping glitch

### Expected Result

Should not double overlay, just like on Creative.

### Screenshots and Videos

Survival Mode :
![image](https://user-images.githubusercontent.com/82106625/177463792-66e3b62b-291d-46b0-b039-8fe0a4bb7124.png)
![image](https://user-images.githubusercontent.com/82106625/177464057-8e4ae847-6d71-4009-a5d3-8d1f6ff42551.png)

### Crash Report or Log

No Crash, overlay Glitch only (On Survival)

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Additional Context

Only happen on Survival Mode

**Comment by TropheusJ** [comment]
this is a mod conflict, we need your mod list

**Comment by ardissaps** [comment]
![image](https://user-images.githubusercontent.com/82106625/177474576-6bd18386-8404-4cef-9d69-15af41e989df.png)

**Comment by TropheusJ** [comment]
If this still happens, try to narrow down the cause. Closing for now, stale and not reproducible

**Comment by TropheusJ** [comment]
followup: #790
