### ISSUE TITLE
Horizontal and Vertical Framed Glass look like Regular Framed Glass

### ISSUE THREAD

**Issue by ardissaps** [Fabricators-of-Create/Create#415]
### Describe the Bug

All of 3 model look the seame beside the type (also the pane version).

### Reproduction Steps

1. Put Framed Glass
2. Put Horizontal Framed Glass
3. Put Vertical Framed Glass
4. All look the same

### Expected Result

They coul look different.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/82106625/177549769-d7a827f5-ef99-4719-a48b-3685f573b949.png)

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

My resourcepack order
![image](https://user-images.githubusercontent.com/82106625/177550013-1399a302-ed76-491f-971e-34e065f55619.png)

VanillaTweak List :
- DarthXisumaPiglins
- SpruceWoodPlanks
- AlternateEnchantGlint
- QuieterZombies
- VisualInfestedStoneItems
- VisualWaxedCopperItems
- ClearBannerPatterns
- DirectionalDispensersDroppers
- BetterObservers
- GroovyLevers
- NoteblockBanners
- VisualSaplingGrowth
- VisualHoney
- DoubleSlabFix
- EnderDragonElytra
- HDShieldBanners
- BetterParticles
- UniqueDyes
- IronBarsFix

### Additional Context

My Top most Edit is mostly custom dark mode UI and language files.

**Comment by TropheusJ** [comment]
framed glass only connects to itself.
![image](https://user-images.githubusercontent.com/60247969/209537233-7304b671-0e71-40bd-a8ba-1390cac785f8.png)
