### ISSUE TITLE
Adjacent blocks are powered by redstone

### ISSUE THREAD

**Issue by luigistyle** [Fabricators-of-Create/Create#416]
### Describe the Bug

When playing on the Forge (original) version of Create, placing two redstone-conductive blocks next to each other and powering one of them causes only that one block to be powered (shown in screenshots below). However, when attempting to do the same on the Fabric version, both blocks now become powered from powering only one of them, causing issues with certain contraptions in which components get powered by redstone when they shouldn't be.

### Reproduction Steps

1. Place two redstone-conductive blocks next to each other (for example, a Gearshift and a Clutch).
2. Power only one of the blocks using any source (lever, button, etc.)
3. Observe as both blocks become powered when only one of them should be

### Expected Result

Only the block that was originally powered by whatever means should be turned on rather than the power conducting to the attached block.

### Screenshots and Videos

![2022-07-07_00 47 45](https://user-images.githubusercontent.com/72584179/177640797-13febc1a-9996-40be-a3da-f2ebf2fbc1ce.png) Forge Version

![2022-07-07_00 53 43](https://user-images.githubusercontent.com/72584179/177641293-eeaac10b-2de1-4a80-9c80-0467f66a1186.png) Fabric Version

### Crash Report or Log

N/A

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Other than Create Fabric and the Fabric API, no other mods were running.

### Additional Context

This bug is preventing me from making a cool elevator. I'll give y'all big mcthankies from mcspankies if it gets fixed

**Comment by Merith-TK** [comment]
![image](https://user-images.githubusercontent.com/10422110/180627322-ab98aaee-f814-4b30-98fd-3279b8194471.png)
having this as well, this is an pretty big issue as it means condensed schematics wont work between Forge and Fabric versions

![image](https://user-images.githubusercontent.com/10422110/180633144-7848329e-563d-4ae1-9f5d-6578624c0b92.png)
