### ISSUE TITLE
Brass Funnels/Chute only checks first slot for amount-specific extracts

### ISSUE THREAD

**Issue by kitoaken** [Fabricators-of-Create/Create#417]
### Describe the Bug

If a Brass Funnel or Brass Chute is set to extract a specific amount of items, it will only check the first slot. Other inventory slots are ignored even if they have enough items

### Reproduction Steps

1. Put a Brass Funnel or Chute on a Chest, set to extract X items
2. Put a small amount of in the top left slot of the Chest
3. Fill the Chest with any other items

### Expected Result

Should work the same as Forge. Slots without enough items should be ignored, instead of blocking up the device

### Screenshots and Videos

Both are set to 64, nothing will be extracted from these barrels because of the 3 fish in the top left. Fabric-exclusive bug, as this works as intended on Forge

![Capture](https://user-images.githubusercontent.com/102918484/177651153-24e4f0d6-230a-4e59-9f65-0859ba2f0827.JPG)
![Capture](https://user-images.githubusercontent.com/102918484/177651223-e8f6fbe8-ce51-4e24-9235-d4f8c6f889b8.JPG)

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
This should have been fixed, make sure you're on patch 13

**Comment by kitoaken** [comment]
I'm on Patch 13, create-mc1.18.2_v0.4.1+637

Tested on a fresh install with no mods, here's a log to confirm https://pastebin.com/BsZUSL8x
