### ISSUE TITLE
Cannot compile shader because 'flywheel:model' is not recognized.

### ISSUE THREAD

**Issue by BEMZ01** [Fabricators-of-Create/Create#420]
### Describe the Bug

Crash to Desktop when iris is installed and activated. Sometimes works when Iris' shaders have been disabled, but will still Randomly crash to desktop. Using curse forge launcher as a mod manager, so maybe outdated version has been grabbed from curseforge.com?

### Reproduction Steps

1. Open a new world in minecraft with iris and create installed. 
2.Wait for world to generate
3. Generate goes to 100%, then saving world. Followed by a crash to desktop

### Expected Result

Open single player world and wait for world to generate, instant crash to desktop

### Screenshots and Videos

N/A

### Crash Report or Log

Client - https://crashy.net/5gpqnCvlDXpHDLGqXlDr ~ Latest.log - https://paste.shockbyte.com/ivojitagotobinusoqab.md

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

		additionalstructures: Additional Structures 3.0.3
		advdebug: Advancements Debug 2.3.0
		ambientenvironment: Ambient Environment 7.0+19
		ambientsounds: Ambiend Sounds (Fabric) 5.0.16
		animatica: Animatica 0.5+1.18.2
		antighost: AntiGhost 1.18.2-fabric0.47.10-1.1.4
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
		anvil_fix: AnvilFix 1.3.0
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.5.76
		armorsoundtweak: Armor Sound Tweak 5.1.1
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
		attributefix: AttributeFix 14.0.2
		awesomedungeon: Awesome Dungeon 2.0.11
		awesomedungeonend: Awesome Dungeon Edition end 1.0.3
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.3
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.8
		badpackets: Bad Packets 0.1.2
		bcc: BetterCompatibilityChecker fabric-1.0.5
		bclib: BCLib 1.4.7
		better_loading_screen: Better Loading Screen 1.4.0
		betteranimalsplus: Better Animals Plus 1.18.2-11.0.5
		betterbiomeblend: Better Biome Blend 1.18.2-1.3.5-fabric
		betterdeserttemples: YUNG's Better Desert Temples 1.18.2-Fabric-1.2
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		betterend: Better End 1.1.1
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.2
		bettermounthud: Better Mount HUD 1.1.4
		betternether: Better Nether 6.1.2
		betterpingdisplay: Better Ping Display 1.1.1
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		betterthirdperson: Better Third Person 1.8.1
		betterwitchhuts: YUNG's Better Witch Huts 1.18.2-Fabric-1.0.1
		bookshelf: Bookshelf 13.2.21
		borderlessmining: Borderless Mining 1.1.2+1.18.2
		byg: Oh The Biomes You'll Go 1.4
		capes: Capes 1.3.1+1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		carrier: Carrier 1.10.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		cem: Custom Entity Models 0.7.1
			completeconfig: CompleteConfig 1.0.0
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chunky: Chunky 1.2.164
		citresewn: CIT Resewn 1.1.1+1.18.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.18.2
		cleancut: CleanCut 1.18.2-5.0-fabric
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 8.0.0+10
		colouredtooltips: ColouredTooltips 15.0.1
		continuity: Continuity 2.0.0+1.18.2
		create: Create mc1.18.2_v0.4.1+637
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			flywheel: Flywheel 1.18-0.7.0.26
			forge_tags: Forge Tags 2.1
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			noindium: No Indium? 1.0.1+1.18.2
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			registrate-fabric: Registrate for Fabric MC1.18.2-1.0.3
		creativecore: CreativeCore (Fabric) 2.6.12
		creeperoverhaul: Creeper Overhaul 1.3.1
		croptopia: Croptopia 2.0.5
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		cull-less-leaves: Cull Less Leaves 1.0.1
		dashloader: DashLoader 4.0.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		dcch: DCCH 1.0
		debugify: Debugify 1.11.0
			com_github_llamalad7_mixinextras: mixinextras 0.0.10
		decorative_blocks: Decorative Blocks 2.1.0
		dimdoors: DimensionalDoors 4.0.4
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-chunk: Cardinal Components API (chunks) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
			cardinal-components-item: Cardinal Components API (items) 4.1.4
			cardinal-components-level: Cardinal Components API (world saves) 4.1.4
			cardinal-components-world: Cardinal Components API (worlds) 4.1.4
			com_flowpowered_flow-math: flow-math 1.0.3
			com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
			curse_maven_wthit-3707010: wthit-3707010 440979
			matrix: Matrix 1.0.0
			org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		dual_riders: Dual Riders 1.1.1
		dynamicfps: Dynamic FPS 2.1.0
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.18.2
		edenring: EdenRing 0.5.2
		enchdesc: EnchantmentDescriptions 10.0.4
		endrem: End Remastered 5.1.0
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.18.2
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.5
		entity_texture_features: Entity Texture Features 3.1.4-mc1.18.x
		entityculling: EntityCulling-Fabric 1.5.1
		extra_classes_origins: Extra Classes - Origins 1.0.0
		extraorigins: Extra Origins 1.18-11
		fabric: Fabric API 0.57.0+1.18.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.2+d005b03a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fabrishot: Fabrishot ${version}
		fallingtree: FallingTree 3.5.3
		farsight: Farsight Mod 1.18-1.9
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.1
		findme: FindMe 3.0.6
		flowery: Flowery Structures 10
		flowerycore: Flowery Core 5
		flowerycrop: Flowery Crop 3
		flytre_lib: FlytreLib 1.8.1
		forgeconfigapiport: Forge Config API Port 3.2.0
		fpsreducer: FPS Reducer 1.18.2-2.0
		geckolib3: Geckolib 3.0.50
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		graveyard: The Graveyard 1.9
		graveyard_biomes: The Graveyard Biomes 1.1
		highlighter: Highlighter 1.1.2
		iceberg: Iceberg 1.0.38
		incendium: Incendium + Seed Fix 5.0.4
		indium: Indium 1.0.6+mc1.18.2
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		isxander-main-menu-credits: Main Menu Credits 1.1.1
		itemborders: Item Borders 1.1.5
		itemmodelfix: Item Model Fix 1.0.3+1.18
		java: OpenJDK 64-Bit Server VM 17
		journeymap-fabric: Journeymap 5.8.5
			journeymap-api-fabric: JourneyMap API 1.18.2-1.8-fabric-SNAPSHOT
		krypton: Krypton 0.1.9
			com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		kubejs: KubeJS 1802.5.4-build.510
		kubejs_create: KubeJS Create 1802.2.2-build.26
		lambdabettergrass: LambdaBetterGrass 1.2.4+1.18
			spruceui: SpruceUI 3.3.3+1.18
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
		languagereload: Language Reload 1.2.1
		lanserverproperties: Lan Server Properties 1.8
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.2.5
		libraryferret: Library Ferret 2.0.0
		lightoverlay: Light Overlay 6.1.0
			org_javassist_javassist: javassist 3.26.0-GA
			org_reflections_reflections: reflections 0.9.12
		lithium: Lithium 0.7.10
		logprot: Logprot Mod 1.18-1.6
		lushforest: Lush Forests 1.3.0
		macawsbridgesbyg: Macaw's Bridges - BYG 1.18.2-1.2
		macawsroofsbyg: Macaw's Roofs - BYG 1.18.2-1.0
		maptooltip: Map Tooltip 1.3.2
		mcwbridges: Macaw's Bridges 2.0.3
		mcwdoors: Macaw's Doors 1.0.6
		mcwfences: Macaw's Fences and Walls 1.0.5
		mcwlights: Macaw's Lights and Lamps 1.0.3
		mcwroofs: Macaw's Roofs 2.1.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.6
		mcwwindows: Macaw's Windows 2.0.3
		medievalorigins: Medieval Origins 1.18.x-4.0.2
		memoryleakfix: memory Leak Fix 1.18.2-0.3.5
		midnightlib: MidnightLib 0.4.4
		minecraft: Minecraft 1.18.2
		moborigins: Mob Origins 1.8.1
		modmenu: Mod Menu 3.2.3
		morechathistory: MoreChatHistory 1.1.0
		mostructures: Mo' Structures 1.4.2+1.18.2
		nofade: No Fade 1.18-2.0.1
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		optigui: OptiGUI 1.1.0
			org_apache_commons_commons-text: commons-text 1.9
		origins: Origins 1.4.1
			apoli: Apoli 2.3.3
				additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
				calio: Calio 1.5.1
				playerabilitylib: Pal 1.5.0
		origins-classes: Origins: Classes 1.3.0
		pehkui: Pehkui 3.3.3+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		pling: Pling 1.5.0
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.18.2-build.42
		repurposed_structures: Repurposed Structures 4.1.14+1.18.2
		rhino: Rhino 1802.1.14-build.190
		roughlyenoughitems: Roughly Enough Items 8.3.502
		seedfix: Seed Fix 1.0.1
		skinlayers: 3d Skin Layers 1.4.6-mc1.18.2
		sleepwarp: SleepWarp 1.1.1+1.18.2
		smoothboot: Smooth Boot 1.18.2-1.7.0
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.5+mc1.18.2-build.42
			caffeineconfig: CaffeineConfig 1.1.0
		sound_physics_remastered: Sound Physics Remastered 1.18.2-1.0.6
		spark: spark 1.9.11
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		structory: Structory 1.0.0
		structurepalettes: Structure Palettes 1.0.0
		structures_compass: Structures Compass 1.18.2-1.4.2
		t_and_t: Towns and Towers - Structure Add-on 1.6
		techno_backrooms: Techno's Backrooms Mod 1.1.4-1.18.2
			limlib: Liminal Library 5.1.2
			satin: Satin 1.7.2
		terrablender: TerraBlender 1.1.0.102
		tipsmod: Tips 5.0.3
		tooltipfix: ToolTip Fix 1.0.4-1.18
		totw_additions: Towers of the Wild: Additions 1.2.1
		twilightforest: The Twilight Forest 4.1.251
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
			porting_lib: Porting Lib 1.1.342-beta+1.18.2-dev.dd61cdc
				serialization_hooks: Serialization Hooks 0.2.0+1.18.f5d4aa6
		unstructured: Unstructured 0.4+1.18.2
		walllanterns: Lanterns Belong on Walls 1.2.0
		waterdripsound: Drip Sounds 1.18-0.3.0
		waystones: Waystones 2.5.5+mc1.18.2
		wthit: wthit 4.11.0
		xaeroworldmap: Xaero's World Map 1.24.0
		yigd: You're in Grave Danger 1.3.7
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.1.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0
		zoomify: Zoomify 1.6.0
			dev_isxander_settxi: settxi 2.1.1
			settxicloth: Settxi Cloth Impl 1.0.2

**Comment by nebulazorua** [comment]
any updates on this?

**Comment by TropheusJ** [comment]
not reproducible, it has to be some other incompatibility

**Comment by TropheusJ** [comment]
closing, stale and not reproducible
