### ISSUE TITLE
Tracks do not cooperate with Iris, even without shaders enabled

### ISSUE THREAD

**Issue by digitaltrucker** [Fabricators-of-Create/Create#424]
### Describe the Bug

Game crashes when placing a train track, world then crashes on load.  I checked the Forge version to see if it's an upstream problem.  The only thing close I saw was a crash when using shaders.  I disabled my shader and it still crashed.

### Reproduction Steps

1.  Try to place track.
2.  Watch crash.
3.  Try to reload save.
4.  Watch crash.

### Expected Result

No crash.

### Crash Report or Log

https://pastebin.com/a0Qy48ky

### Operating System

Windows 10

### Mod Version

0.5.0

### Minecraft Version

1.18.2

### Other Mods

See the linked latest.log.

### Additional Context

In addition to the crash log, here is the latest.log.  https://pastebin.com/h14QKRC6

**Comment by TropheusJ** [comment]
try without iris

**Comment by digitaltrucker** [comment]
Yep, it worked.  The world that previously refused to load loads just fine now.

**Comment by maximumpower55** [comment]
This is specifically a issue with iris's batched entity rendering

**Comment by RedWideWeb** [comment]
Iris 1.2.4 and older works fine

**Comment by JieningYu** [comment]
Also crash with Flywheel's batching engine.

**Comment by maximumpower55** [comment]
> Iris 1.2.4 and older works fine

Again, please don't use that as a actual fix

**Comment by RedWideWeb** [comment]
> > Iris 1.2.4 and older works fine
> 
> Again, please don't use that as a actual fix

Doesn’t that mean it’s Iris Issue?

**Comment by JieningYu** [comment]
Create's issue.

**Comment by TropheusJ** [comment]
This might be a 3-way issue with Create, Immersive Portals, and Iris. See if removing immptl fixes it too.

**Comment by Dr-WeiAL** [comment]
I don't have Immersive Portals installed and still have this problem

**Comment by maximumpower55** [comment]
> Create's issue.

No, its on us aka its a iris issue, it may also be on create, we are still currently investigating it

**Comment by maximumpower55** [comment]
This has been fixed in iris and will be coming in the next update

**Comment by TropheusJ** [comment]
since this will be fixed with the update I'm closing it
