### ISSUE TITLE
Crash when starting the game

### ISSUE THREAD

**Issue by Dr-WeiAL** [Fabricators-of-Create/Create#425]
### Describe the Bug

[latest.log](https://github.com/Fabricators-of-Create/Create/files/9088273/latest.log)
[crash-2022-07-12_07.58.21-client.txt](https://github.com/Fabricators-of-Create/Create/files/9088276/crash-2022-07-12_07.58.21-client.txt)

### Reproduction Steps

1.start the game

### Expected Result

Started successfully

### Operating System

windows10

### Mod Version

0.5.0

### Minecraft Version

1.18.2

### Other Mods

There should be a display in the log and crash, but there are a lot of mods

**Comment by TropheusJ** [comment]
Could you try with no resource packs and without Continuity?

**Comment by Dr-WeiAL** [comment]
I found out the problem, the conflict caused by shetiphiancore

**Comment by RedWideWeb** [comment]
@TropheusJ thanks for commenting on my video. This mean a lot ❤️

**Comment by TropheusJ** [comment]
Very weird issue. shetiphiancore is closed source so I really can't look into this. Report to them I guess.

**Comment by Dr-WeiAL** [comment]
> Very weird issue. shetiphiancore is closed source so I really can't look into this. Report to them I guess.

@TropheusJ 
After investigation there, it was found that it was actually a conflict with Myron
https://github.com/Haven-King/myron
