### ISSUE TITLE
Contraption crash

### ISSUE THREAD

**Issue by Dr-WeiAL** [Fabricators-of-Create/Create#426]
### Describe the Bug

Testing found that using Contraption when installing Modern-Elevators-Escalators caused a crash
[latest.log](https://github.com/Fabricators-of-Create/Create/files/9088465/latest.log)
[crash-2022-07-12_08.46.53-client.txt](https://github.com/Fabricators-of-Create/Create/files/9088466/crash-2022-07-12_08.46.53-client.txt)

### Reproduction Steps

1.Install Modern-Elevators-Escalators
2.Use Contraption

### Expected Result

not crash

### Operating System

windows10

### Mod Version

0.5.0

### Minecraft Version

1.18.2

### Other Mods

https://www.curseforge.com/minecraft/mc-mods/modern-elevators-and-escalators

### Additional Context

It does not crash in version 0.4.1, but causes the Contraption to disappear

**Comment by TropheusJ** [comment]
This seems to be an issue with Modern-Elevators-Escalators. It seems their entity types are not being registered at the right time. Should be reported to them.
