### ISSUE TITLE
It always crashes with error code 1 and If i remove the mod it works fine

### ISSUE THREAD

**Issue by Tashy1** [Fabricators-of-Create/Create#428]
### Describe the Bug

Any time when i try to play with this mod it crashes with error code 1 and no crash log i am on pojavlauncher 

### Reproduction Steps

1. Crashes with error code 1

### Expected Result

Just to run it and play 

### Screenshots and Videos

No screenshots

### Crash Report or Log

Error code 1 no log

### Operating System

Android 

### Mod Version

0.5.0a

### Minecraft Version

1.18.2

### Other Mods

Optifine, notenoughcrashes

**Comment by Tempest-5ky** [comment]
find your latest.log and paste it into here, then send it
https://mclo.gs/

**Comment by JieningYu** [comment]
Remove Optifine

**Comment by natejw** [comment]
it could be antivirus not allowing minecraft or create to go through

**Comment by JieningYu** [comment]
Optifine conflict with Create Fabric.

**Comment by TropheusJ** [comment]
Optifine is incompatible.

**Comment by Tempest-5ky** [comment]
I imagine that optifine is probably the issue, considering that this mod is
for fabric and optifine is not.
