### ISSUE TITLE
Display Link not working

### ISSUE THREAD

**Issue by RedWideWeb** [Fabricators-of-Create/Create#430]
### Describe the Bug

(or maybe am I stupid?)

I cannot right click the Display Board with Display Link

### Reproduction Steps

1. Place Display Board
2. Power it up 32 RPM or more
3. Right click with Display Link

### Expected Result

Connection tooltip to show

### Operating System

Windows 10 1809

### Mod Version

0.5.0

### Minecraft Version

1.18.2

### Other Mods

fabric api 0.57.0

**Comment by X2IX** [comment]
i think you are not stupid 
display link not work

https://user-images.githubusercontent.com/51007061/178615933-f69494c5-48b0-442a-a1f1-c63088804e47.mp4

**Comment by RedWideWeb** [comment]
It was fixed in upstream 0.5b so we should wait for PR
