### ISSUE TITLE
Game Crashes On load

### ISSUE THREAD

**Issue by SnowedInOwl** [Fabricators-of-Create/Create#431]
### Describe the Bug

The game tries to start but doesn't get past the first few seconds of load and then crashes. I'm unsure why though.

### Reproduction Steps

1. Start the game with listed mods
2.
3.
...

### Expected Result

For The Game to startup

### Crash Report or Log

https://pastebin.com/1Lq6BqTd

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

	- accurateblockplacement 1.0.12
	- achievement_plates 1.6.1
	- additionalbanners 7.0.6
	- additionalbars 3.3.1+1.18.2
	- adorn 3.5.0+1.18.2
	- advanced_runtime_resource_pack 0.5.7 via dynamic_asset_generator
	- advancednetherite 1.5.1-1.18.2
	- adventurez 1.4.11
	- ae2 11.1.4
	- ae2additions 3.1.1-fabric
	- ae2things 1.1.0-beta.7
	- ae2wtlib 11.1.4
	- allarrowsinfinityfix 1.0.0
	- ambientsounds 5.0.16
	- amecsapi 1.3.5+mc22w06a via backslot
	- amplified-nether 1.1
	- animal_feeding_trough 1.0.3+1.18.2
	- anvilrestoration-fabric 1.1
	- appleskin 2.4.0+mc1.18.2
	- aquatictorches 1.0.0
	- aqupdcaracal 1.18.2-1.3.8
	- architects_palette 2.2
	- architectury 4.5.76
	- armor-stand-swap 1.0.2
	- armorpointspp 3.0.1
	- artifacts 7.0.3+fabric
	- attributefix 14.0.2
	- audioplayer 1.18.2-1.0.3
	- autoconfig1u 3.4.0
	- backslot 1.2.6
	- backslotaddon 1.0.8
	- balm-fabric 3.1.0+0
	- basicshields 1.3.1-1.18.2
	- bclib 1.4.7
	- beaconoverhaul 1.6.0+1.18.2
	- beehivetooltips 1.4.2
	- beo 1.18.2-2.1.0-Fabric
	- better_loading_screen 1.4.0
	- betteradvancements 0.2.1.132
	- betteranimalsplus 1.18.2-11.0.5
	- betterbiomeblend 1.18.2-1.3.5-fabric
	- betterend 1.1.1
	- betterf3 1.2.5
	- betterfpsdist 1.18-1.8
	- betternether 6.1.2
	- betterpingdisplay 1.1.1
	- betterthanmending 1.3.0
	- bigbeacons 1.2.5
	- bigbenchtheory 1.2.1
	- biomemakeover 1.18.2-1.4.28
	- blast 1.9.1
	- blockus 2.4.7+1.18.2
	- blossom 1.18.2-1.0.4
	- blur 2.4.1
	- bno 1.18.2-7.2.0-Fabric
	- bookshelf 13.2.21
	- borderlessmining 1.1.2+1.18.2
	- bosses_of_mass_destruction 1.3.8-1.18.2
	- bottledair-fabric 1.0
	- buildguide 0.3.3
	- camera r1.0
	- campanion 3.0.3
	- capybara 1.0.6
	- cardboard 55
	- cardinal-components 4.2.0
	- cardinal-components-base 4.2.0 via cardinal-components
	- cardinal-components-block 4.2.0 via cardinal-components
	- cardinal-components-chunk 4.2.0 via cardinal-components
	- cardinal-components-entity 4.2.0 via cardinal-components
	- cardinal-components-item 4.2.0 via cardinal-components
	- cardinal-components-level 4.2.0 via cardinal-components
	- cardinal-components-scoreboard 4.2.0 via cardinal-components
	- cardinal-components-world 4.2.0 via cardinal-components
	- catwalksinc 1.3.0
	- ce 1.1.5
	- charginggadgets 1.0.2
	- charm 4.1.2
	- chat_heads 0.6.0
	- chipped 1.2
	- chromatic_currents 1.0.2
	- clickadv 2.6
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 6.2.62
	- clumps 8.0.0+10
	- coinsje 7.0.1
	- collective-fabric 4.27
	- colorfulanvils 1.0.0
	- colouredtooltips 15.0.1
	- com_electronwill_night-config_core 3.6.5 via couplings
	- com_electronwill_night-config_toml 3.6.5 via couplings
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_github_isaiahpatton_specialsource master-SNAPSHOT via cardboard
	- com_github_llamalad7_mixinextras 0.0.10 via porting_lib
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_moandjiezana_toml_toml4j 0.7.2 via charm
	- compacthelpcommand-fabric 1.1
	- companion 2.0.1
	- connectiblechains 2.1.1+1.18.2
	- connectivity 1.18.2-3.3
	- consistency_plus 0.5.0+1.18.2
	- continuity 2.0.0+1.18.2
	- controlling 9.0+21
	- couplings 1.8.0+1.18.2
	- cozycabincore 1.1
	- craftingtweaks 14.0.3
	- crafttweaker 9.1.164
	- crawl 0.10.6
	- create mc1.18.2_v0.4.1+637
	- creativecore 2.6.12
	- crowdin-translate 1.4+1.18.2 via basicshields
	- ctm 1.0.0+1.18
	- ctov 2.9
	- cyti 1.0.5
	- dawn 3.3.2
	- disable_custom_worlds_advice 2.0
	- dripstone_fluid_lib 1.2.0 via milk
	- dynamic_asset_generator 0.6.2
	- expandability 6.0.0 via artifacts
	- fabric 0.57.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.22+d7c144a860 via fabric
	- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric
	- fabric-data-generation-api-v1 3.0.0+9fcb91d260 via fabric
	- fabric-dimensions-v1 2.1.20+489d6f8260 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.18+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.5.1+6c4e5d0960 via fabric
	- fabric-item-groups-v0 0.3.14+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.8.1+kotlin.1.7.0
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric
	- fabric-loot-api-v2 1.1.0+1997ad1260 via fabric
	- fabric-loot-tables-v1 1.1.2+e747827960 via fabric
	- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.22+e6b169eb60 via fabric
	- fabric-networking-v0 0.3.9+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.9+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.2+d005b03a60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.1+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric
	- fabricloader 0.14.8
	- fabricshieldlib 1.5.3-1.18
	- fake-player-api 0.3.0 via create
	- fiber 0.23.0-2 via armorpointspp
	- flytre_lib 1.8.1
	- flywheel 1.18-0.7.0.26 via create
	- forge_tags 2.1 via create
	- forgeconfigapiport 3.2.0
	- geckolib3 3.0.50
	- iceberg 1.0.38
	- icommon 1.18
	- iknowwhatimdoing 4.1.0
	- ingredient-extension-api 2.0.6
	- java 17
	- kiwi 6.0.2
	- libblockattributes_core 0.10.2 via libmultipart_deps_container
	- libmultipart 0.7.2 via libmultipart_deps_container
	- libmultipart_deps_container 0.7.2
	- libnetworkstack 0.6.3
	- libraryferret 2.0.0
	- limlib 5.1.2 via techno_backrooms
	- maelstrom_library 1.2.4-1.18.2 via bosses_of_mass_destruction
	- mantori 1.1.1-1.18.2
	- midnightlib 0.4.4
	- milk 0.3.2 via create
	- minecarttweaks 1.5
	- minecraft 1.18.2
	- mm 2.3 via crawl
	- modmenu 3.2.3
	- multipart_entities 1.1.5-1.18.2 via bosses_of_mass_destruction
	- myron 1.6.3+1.18.1 via shetiphiancore
	- no-telemetry 1.4.0
	- noindium 1.0.2+1.18.2 via ae2
	- omega-config 1.2.3-1.18.1 via noindium
	- org_javassist_javassist 3.29.0-GA via crafttweaker
	- org_jetbrains_kotlin_kotlin-reflect 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_reflections_reflections 0.10.2 via crafttweaker
	- owo 0.7.2-no-cme+1.18
	- placeholder-api 1.1.3+1.17.1 via colorfulanvils
	- porting_lib 1.1.317-beta+1.18.2-dev.7ad1f24 via create
	- puzzleslib 3.3.5
	- reach-entity-attributes 2.1.1 via beaconoverhaul
	- reborncore 5.2.0-beta.3 via charginggadgets
	- registrate-fabric MC1.18.2-1.0.3 via create
	- satin 1.7.2 via techno_backrooms
	- serialization_hooks 0.2.0+1.18.f5d4aa6 via porting_lib
	- shetiphiancore 1.2.11
	- skinlayers 1.4.6-mc1.18.2
	- step-height-entity-attribute 1.0.0 via artifacts
	- stonecutter_recipe_tags 3.0.1+1.18.bc850d5.fabric via consistency_plus
	- team_reborn_energy 2.2.0 via charginggadgets
	- techno_backrooms 1.1.4-1.18.2
	- tenshilib 1.18.2-1.6.7
	- terrablender 1.1.0.102
	- terraform-wood-api-v1 3.0.0 via blockus
	- thonkutil 2.14.1+1.18
	- thonkutil-base 1.12.2+23c1dc2c60 via thonkutil
	- thonkutil-capes-v1 1.3.2+9e23427060 via thonkutil
	- thonkutil-coords-v1 1.0.19+9b80223760 via thonkutil
	- thonkutil-customization-v1 1.0.14+9b80223760 via thonkutil
	- thonkutil-legacy 1.0.20+9b80223760 via thonkutil
	- thonkutil-modchecker-v1 1.0.12+9b80223760 via thonkutil
	- thonkutil-potions-v0 1.4.1+9b80223760 via thonkutil
	- thonkutil-titlescreen-v1 1.1.9+9b80223760 via thonkutil
	- thonkutil-trades-v1 1.1.20+9b80223760 via thonkutil
	- trinkets 3.3.1
	- voicechat 1.18.2-2.2.45
	- wands 2.5_mc1.18.2
	- yungsapi 1.18.2-Fabric-2.0.8

**Comment by StockiesLad** [comment]
Porting Lib and flywheel having overlapping mixins, but portinglib is the one really stuffing up

**Comment by TropheusJ** [comment]
no, cardboard is doing something incredibly weird:
```
Expected: [Lnet/minecraft/class_1799;, D, D, D, I, D, D, D]
Found: [Lnet/minecraft/class_1799;, I, D, D, D, Lorg/bukkit/entity/Player;, Lorg/bukkit/event/player/PlayerTeleportEvent;]
```
[Never use cardboard](https://gist.github.com/Patbox/e44844294c358b614d347d369b0fc3bf), it's unsupported and we're not fixing it.
