### ISSUE TITLE
Blaze Cakes Not Working in Create 0.5.0

### ISSUE THREAD

**Issue by SlimeBoi2006** [Fabricators-of-Create/Create#433]
### Describe the Bug

Whenever I right click the burner with a blaze cake it does not get super heated

### Reproduction Steps

1.Download Create 0.5.0
2.Place Burner
3.Use Blaze Cake On Burner
...

### Expected Result

Burner Should Get Superheated

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/84562128/179140108-14cfb552-ae1f-4579-97ef-3b3a68d97e68.png)

### Operating System

Windows 10

### Mod Version

0.5.0

### Minecraft Version

1.18.2

**Comment by JieningYu** [comment]
what about using Mechanical Arm?

**Comment by SlimeBoi2006** [comment]
nope still does not work

**Comment by Itplayz** [comment]
How were you able to download 0.5.0a?

**Comment by SlimeBoi2006** [comment]
Sorry I realized I put the wrong version it was supposed to be 0.5.0

**Comment by Itplayz** [comment]
But how were you able to get 0.5.0 Version?
I cant seem to find it

**Comment by CzechHek** [comment]
> But how were you able to get 0.5.0 Version? I cant seem to find it

https://www.curseforge.com/minecraft/mc-mods/create/files/all

😳😳😳😳😳

edit: I'm stupid

**Comment by piperswe** [comment]
> https://www.curseforge.com/minecraft/mc-mods/create/files/all

That's for Forge, this repo is the Fabric port

**Comment by SlimeBoi2006** [comment]
I compiled the mod myself

**Comment by JieningYu** [comment]
https://github.com/Fabricators-of-Create/Create/commit/d3cea4430a05756646497b2cd1be518d34390071

> But how were you able to get 0.5.0 Version? I cant seem to find it

**Comment by SlimeBoi2006** [comment]
oh oops i think i answered the question wrong mb

**Comment by Itplayz** [comment]
> [d3cea44](https://github.com/Fabricators-of-Create/Create/commit/d3cea4430a05756646497b2cd1be518d34390071)
> 
> > But how were you able to get 0.5.0 Version? I cant seem to find it

Thanks!

**Comment by JieningYu** [comment]
So..how this will be fixed?

**Comment by JieningYu** [comment]
So..how this will be fixed?

**Comment by jiangyh91** [comment]
I have same problem, and I found a funny thing. If you are using deployer to feed, and stay away (this is important), it will work sometime.
![image](https://user-images.githubusercontent.com/18522738/179508544-849e0fee-0fe3-4134-be81-f80be83e17ee.png)

**Comment by JieningYu** [comment]
So it depends the distance from player?

**Comment by jiangyh91** [comment]
seems not ture, I tried to reproduce it. And it's more like when the depolyer feed the cake, there is a chance that it will work.

**Comment by SlimeBoi2006** [comment]
for me the deployer does not work either but the creative blaze cake works for me

**Comment by jiangyh91** [comment]
creative blaze cake works for me as well
