### ISSUE TITLE
Deployer Crashes Server

### ISSUE THREAD

**Issue by MarquisXDeXSade** [Fabricators-of-Create/Create#434]
### Describe the Bug

Placing a Deployer crashes my server - anyone who enters the chunk after the server comes back up will cause the server to crash as well. Have to load Alchemy and delete the block and save the world before restoring the servers.

### Reproduction Steps

1.Place Deployer
2.Server Crashes

### Expected Result

Place Deployer and not crash the server. Was using it as intended off a cog wheel, and it crashes every time it's placed.

### Crash Report or Log

https://pastebin.com/9J29PuaB

### Operating System

Windows Server 2019

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Mod Pack [Valhelsia Enhance Vanilla](https://www.curseforge.com/minecraft/modpacks/valhelsia-enhanced-vanilla/files/3863972)

**Comment by SplendidAlakey** [comment]
Duplicate https://github.com/Fabricators-of-Create/Create/issues/117

Remove TabTPS-

**Comment by MarquisXDeXSade** [comment]
Fixed. Thank you - didn't see it listed, very tired so I apologize.
