### ISSUE TITLE
Build #653 fails to work with Quilt loader.

### ISSUE THREAD

**Issue by qwerty121123** [Fabricators-of-Create/Create#435]
### Describe the Bug

The latest working 0.5 build for create refabricated seems to be unable to work with quilt.
Every time I attempt to run quilt 1.18.2 with the mod installed, (I am using the latest version of the loader, and the latest 1.18.2 version of the quilt api.) it brings up this error:
![Quilt Loader 0 17 1-beta 6 7_16_2022 11_01_03 AM](https://user-images.githubusercontent.com/109119492/179366844-f6911dbb-6c2b-4947-bd2d-e04e0b563cff.png)
I have tried a couple things, like removing all other mods installed. (Same error)
Tried an older version of the loader (More errors)
And even tried using the latest release of the api (This error)
![Quilt Loader 0 17 1-beta 6 7_16_2022 11_06_53 AM](https://user-images.githubusercontent.com/109119492/179367078-dad51372-987f-4a2b-a671-592e571dd5da.png)

To me, it seems just like quilt has not updated the 1.18.2 api to the latest version. I cannot find a fix for this.

### Reproduction Steps

1. Download Quilt, latest version 1.18.2.
2. Download any Quilt API build for 1.18.2
3. Download Create Refabricated build #653
4. Attempt to launch Quilt 1.18.2.

### Expected Result

I expected 1.18.2 to work on quilt, as it states on the modrinth page, quilt is supported.

### Operating System

Windows 10

### Mod Version

0.5.0

### Minecraft Version

1.18.2

### Other Mods

qfapi-3.0.0-alpha.3_qsl-2.0.0-beta.14_fapi-0.57.2_mc-1.19.1-pre4.jar (Quilt standard lib)

**Comment by Sheep7798** [comment]
Looks like you are using an api for 1.19.1 pre release 4 when trying to launch a 1.18.2 mod

**Comment by Stereo528** [comment]
My guess is that Create needs FAPI 57, latest QSL is FAPI 56 still and has probably moved to 1.19/1.19.1 focus meaning updating  1.18.2 is on the back burner (which I think one can assume is slightly obvious due to the fact the latest 1.18.2 QSL update was a month ago)

do however take this with a grain of salt because I don't work on QSL nor do I know their plans for updating "old" versions like 1.18.2

**Comment by JieningYu** [comment]
Can build 653 work with fabric api 56 by editing fabric.mod.json?

**Comment by Sheep7798** [comment]
If you know how to do it maybe

**Comment by qwerty121123** [comment]
> Looks like you are using an api for 1.19.1 pre release 4 when trying to launch a 1.18.2 mod

I put the wrong mod name down, sorry. The 1.19.1 gave the second error. The latest 1.18.2 api gave the first error.
I tried using the latest experimental build of 1.18.2 but that gave the same error as the release. When I used both apis (1.19 + 1.18.2) it seemed to almost work but it had 1 duplicate file I don't know how to remove

**Comment by qwerty121123** [comment]
Also, thank you all for your helpful responses, but I ended up talking to one of the devs behind the quilt api, and they said they were working on the 1.18.2 API update.

**Comment by JieningYu** [comment]
Ok fine.
