### ISSUE TITLE
Debilitating incompatability issues with Sodium Fabric

### ISSUE THREAD

**Issue by ghost** [Fabricators-of-Create/Create#436]
### Describe the Bug

I had a few issues with the mod, using it on my client, and isolated the issue as an incompatability with the Sodium Fabric mod. 

When it is installed, cogwheels will spawn with duplicates of themselves intersecting their own models. Additionally, fluid pipes and pipe blocks will spawn without their "cuffs" at either end, and t and x sections will also be glitched. They will fail to connect and interact with other blocks. Fluid tanks of larger sizes will merge correctly on the outside, but will fail to merge their textures inside the tank.

Another strange bug: Chunks containing the Rope Pulley block will sometimes become light level 0 all the way through after loading the game. This can be fixed by "optimising chunks" under Edit in the world menu, but will always reappear after relogging.

### Reproduction Steps

1. Install the latest builds of Fabric for 1.18.2, Create, and Sodium Fabric
2. Launch the game and start a game
3. Observe issues such as cogwheels intersecting themselves and Create fluid mechanics being completely broken

### Expected Result

When Sodium is disabled, as in the picture, none of these bugs will occur and Create functions nominally
![2022-07-16_21 12 29](https://user-images.githubusercontent.com/109435875/179369316-a2f3712a-929f-4886-a2ab-2dd82cd3a28c.png)

### Screenshots and Videos

![2022-07-16_21 12 29](https://user-images.githubusercontent.com/109435875/179369325-9dcc735b-be7c-4827-a0c4-4eee0de3518d.png)
![2022-07-16_21 16 29](https://user-images.githubusercontent.com/109435875/179369327-44c11222-62cc-498b-b9ca-f07e5fd87106.png)
![2022-07-16_21 17 39](https://user-images.githubusercontent.com/109435875/179369329-c28623cd-db53-40de-9030-310c1864c993.png)
![2022-07-16_21 19 53](https://user-images.githubusercontent.com/109435875/179369332-4877566d-c71b-4ebc-8d46-dae101c7fbcf.png)

### Operating System

Windows 10 Home

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

appleskin-fabric-mc1.18.2-2.4.0
cloth-config-6.2.62-fabric
double_hotbar-1.18.2-v1.1.0
fabric-api-0.57.0+1.18.2
InventoryHUD-fabric-[1.18] -3.4.2
iris-mc1.18.2-1.2.5.jar
itemscroller-fabric-1.18.2-0.16.0
jei-1.18.2-fabric-10.1.0.216
litematica-fabric-1.18.2-0.11.3
lithium-fabric-mc1.18.2-0.7.10
malilib-fabric-1.18.2-0.12.1
minihud-fabric-1.18.2-0.22.0
modmenu-3.2.3
phosphor-fabric-mc1.18.x-0.8.1
sodium-extra-0.4.5+mc1.18.2-build.42.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
tweakeroo-fabric-1.18.2-0.13.3
WorldEditCUI-1.18.2+01
worldedit-mod-7.2.10
Xaeros_Minimap_22.10.0_Fabric_1.18.2
XaerosWorldMap_1.24.0_Fabric_1.18.2

**Comment by AlphaMode** [comment]
Install indium and I recommend installing rei too as jei is not supported
