### ISSUE TITLE
Any ETA on Patch B?

### ISSUE THREAD

**Issue by RedWideWeb** [Fabricators-of-Create/Create#437]
### Describe the Suggestion

At least something to fix display links 🥺

Thanks you developers! You are the best❤️

**Comment by Sheep7798** [comment]
They are waiting for flywheel right now

**Comment by maximumpower55** [comment]
Flywheel fabric has been updated

**Comment by maximumpower55** [comment]
Also there isn't any ETA, please don't ask for ETAs it's kinda annoying for like every mod dev

**Comment by RedWideWeb** [comment]
> Also there isn't any ETA, please don't ask for ETAs it's kinda annoying for like every mod dev

Alright, sorry. Create devs are the best❤️
