### ISSUE TITLE
Crash with Canvas when rendering Ponder GUI and Schematics

### ISSUE THREAD

**Issue by spiralhalo** [Fabricators-of-Create/Create#440]
### Describe the Bug

Game crashes when opening Ponder UI with Canvas installed.

See also additional context below.

### Reproduction Steps

1. Run Create with Canvas.
2. In game, navigate to a Create block such as Mechanical Press
3. Hold W to ponder
4. Game crashes

### Expected Result

No crash.

### Crash Report or Log

https://gist.github.com/spiralhalo/33ed8c8dcedbd5af76660459ebc6e0e8

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

[Fabric]+Wildfire+Female+Gender+Mod-2.9
adventurez-1.4.11
appleskin-fabric-mc1.18.2-2.4.0
architectury-4.5.76-fabric
bclib-1.4.7
blast-1.9.1
bobby-3.1.1
bucket-warning-1.1.0
canvas-fabric-mc118-1.0.2374.jar
cloth-config-fabric-6.2.62
create-mc1.18.2_v0.4.1+637
darkness-fabric-mc118-2.0.91
dawn-3.3.2
earthbounds-1.18.2-1.1.4
eden-ring-0.5.2
enderscape-0.3.4-1.18.2
enhancedblockentities-0.6+1.18.2
extrasounds-2.2.1+1.18.2
extrasounds-2.3.1+1.18.2
fabric-api-0.57.0+1.18.2
friendsandfoes-fabric-mc1.18.2-1.4.5
geckolib-fabric-1.18-3.0.50
jpgscreenshot-1.0.1
lazydfu-0.1.2
malilib-fabric-1.18.2-0.12.1
minecraft-comes-alive-7.3.8-fabric
minihud-fabric-1.18.2-0.22.0
minimepets-fabric-1.0.0-mc1.18
mixintrace-1.1.1+1.17
modmenu-3.1.0
notenoughcrashes-4.1.6+1.18.2-fabric
paperdoll-fabric-1.1.0-mc1.18
pettablebees-fabric-1.1.0
PresenceFootsteps-1.5.0
promenade-2.6.3
RoughlyEnoughItems-8.3.510
starlight-1.0.2+fabric.89b8d9f
villagerconverting-1.0.1+1.18.2
WaveyCapes-fabric-1.2.0-mc1.18
wraith-waystones-2.5.5+mc1.18.2

### Additional Context

**Technical investigation**

Based on [Flywheel fabric branch's design of `com.jozufozu.flywheel.core.model.ShadeSeparatingVertexConsumer`](https://github.com/Jozufozu/Flywheel/blob/473b1af5c6b15729c36e4b983799ca19c74fe995/src/main/java/com/jozufozu/flywheel/core/model/ShadeSeparatingVertexConsumer.java#L107), models rendered with it is meant to be wrapped to work properly with FRAPI custom renderer. Create [does an optimization for vanilla models](https://github.com/Fabricators-of-Create/Create/blob/cc4ee7c30d3236bbccf3cbdc05d13a4f7ac993ad/src/main/java/com/simibubi/create/foundation/ponder/element/WorldSectionElement.java#L445-L453) which works for Indigo (?) but definitely break Canvas.

**Comment by JieningYu** [comment]
https://github.com/Fabricators-of-Create/Create/issues/94
another issue caused by canvas

**Comment by spiralhalo** [comment]
> #94 another issue caused by canvas

I just saw it.

**Comment by spiralhalo** [comment]
Identical crash when rendering schematics as well.

Crash report: https://gist.github.com/spiralhalo/a46da33c094a6808cd2c81d9c33525f4
