### ISSUE TITLE
Pump Stops Working After Relogging

### ISSUE THREAD

**Issue by SlimeBoi2006** [Fabricators-of-Create/Create#442]
### Describe the Bug

Whenever I relog onto my world or server the mechanical pump stops working and the only way to fix it is to break the tank and place it again

### Reproduction Steps

1.Place Tank
2.Attach and Power mechanical pump
3.Log out and Relog back in
...

### Expected Result

Pump works when relogging

### Operating System

Windows 10

### Mod Version

0.5.0

### Minecraft Version

1.18.2

**Comment by Papaturts** [comment]
Having the same issue
relog  tank stops getting water till i break the tank thats connected to the pipe/pump  then starts filling right back up
