### ISSUE TITLE
Can't pump in-world fluid using pipes

### ISSUE THREAD

**Issue by JieningYu** [Fabricators-of-Create/Create#443]
### Describe the Bug

ex. using a mechanical pump to pump water block into basin and nothing happened.

### Reproduction Steps

- plate a water block
- place a pump and give it power to pump the water
- the water should be pumped to another side but nothing happened.

### Expected Result

The water should be pumped to the another side of pump.

### Screenshots and Videos

<img width="480" alt="image" src="https://user-images.githubusercontent.com/61787533/179653997-8506f848-41c8-4618-b74c-e2a542e6c952.png">

### Operating System

macOS 12.5 Beta (21G5027d)

### Mod Version

0.5.0

### Minecraft Version

1.18.2

### Other Mods

Lithium
Starlight

**Comment by JieningYu** [comment]
pump-out function is fine, but pump-in is broken.

**Comment by jiangyh91** [comment]
hose pulley seems working for me

**Comment by JieningYu** [comment]
For me pipes doesn't work.

**Comment by Papaturts** [comment]
Not working on fix #423 build #665 as of yet
using a hose pulley seems to be on the slowish side, even with a creative motor going the full 256 rpm

**Comment by TropheusJ** [comment]
seems [this](https://github.com/Fabricators-of-Create/Create/commit/77989a664480d7f6eabfcbb0f5901f1af241b3ab) did indeed fix it.

**Comment by JieningYu** [comment]
yep it fixed this issue
