### ISSUE TITLE
Mechanical Crafter Invisible

### ISSUE THREAD

**Issue by gavincassel** [Fabricators-of-Create/Create#444]
### Describe the Bug

When placed down, the mechanical crafter only appears as a cog. Attempting to interact with it crashes the game. It has also made some of the surrounding blocks invisible. 

This crash also occurs when you click mechanical crafting options in JEI.

### Reproduction Steps

1. Place down Mechanical Crafter
2. Attempt to destroy it

### Expected Result

Game crashes the instant before the block breaks. 

### Screenshots and Videos

![2022-07-19_22 25 34](https://user-images.githubusercontent.com/77476289/179884167-c7524fe0-673b-40ea-9cdb-163ed5a3118e.png)
![2022-07-19_22 25 42](https://user-images.githubusercontent.com/77476289/179884172-b3d5d4b3-7c07-4334-90b4-caf4a36f24c9.png)

### Crash Report or Log

https://gist.github.com/gavincassel/61f29ba3a357a5f76b6a8f7cf0e5f6e3

### Operating System

Windows 10

### Mod Version

0.5.0

### Minecraft Version

1.18.2

### Other Mods

![image](https://user-images.githubusercontent.com/77476289/179884750-f90ff167-e0f6-4c04-b551-8ad0ea990b0d.png)

### Additional Context

Not sure if anyone here would be of help but thought I would put it out there in case anyone else has ran into this problem!

**Comment by JieningYu** [comment]
This shouldn't be a Create issue.
Also don't use Flywheel forge under Fabric.

**Comment by TropheusJ** [comment]
closing in favor of #461
