### ISSUE TITLE
Creating a train causes a crash (on the latest build)

### ISSUE THREAD

**Issue by Sheep7798** [Fabricators-of-Create/Create#445]
### Describe the Bug

When you try to create a train (when you place a train casing on the tracks for a bogey to appear), the game crashes. And when I try to relog into my world, the game crashes again.
This crash happens on the latest build (0.5.0+659) but it doesn't with the old build. So, I was able to reconnect on my world on the build 0.5.0+653.

### Reproduction Steps

1. Place tracks down
2. Place a train station to start creating a train
3. Place a train casing on the tracks to create a bogey
4. Game crashes

### Expected Result

I expected the game not to crash after starting to create a train

### Screenshots and Videos

https://user-images.githubusercontent.com/106376800/179932419-ecd53277-287f-4189-9090-21a8792ff5c4.mp4

### Crash Report or Log

https://pastebin.com/6P7Y7QcA

### Operating System

Mac OS 12.4

### Mod Version

0.5.0a

### Minecraft Version

1.18.2

### Other Mods

Fabric API 0.57.0+1.18.2

**Comment by Tempest-5ky** [comment]
Threw it into crashy in case that's helpful for anyone https://crashy.net/YjPmIOQvdrQcYgYACVaM

**Comment by TropheusJ** [comment]
659 was explicitly stated to be unusable, this should be fixed. If not, let me know.
