### ISSUE TITLE
Crash while placing down cogwheels and then trying to break them again (Fabric 1.18.2)

### ISSUE THREAD

**Issue by CookieGD** [Fabricators-of-Create/Create#446]
### Describe the Bug

I wanted to place down some cogwheels at my windmill to get some energy to my press. After trying to break one of the wheels the game crashed instantly.
Here are the latest.log and the crash reports when the first crash occured and when I tried to join the world again.
[latest.log](https://github.com/Fabricators-of-Create/Create/files/9149629/latest.log)
[hs_err_pid10440.log](https://github.com/Fabricators-of-Create/Create/files/9149633/hs_err_pid10440.log)
[hs_err_pid6940.log](https://github.com/Fabricators-of-Create/Create/files/9149634/hs_err_pid6940.log)

### Reproduction Steps

1. Build a Windmill by the size of 5x5x3 with wool and radial chassis and remove the corners so that it looks like a roll of toilet paper (yes I'm serious about that).
2. Place down the wind mill thing that gets it to rotate (sry, forgot the name).
3. Place a big cogwheel behind the block, then a small one diagonally down left and another big one so that it forms a diagonal line with the big cogwheels being at both ends.
4. Start breaking the lowest wheel.

### Expected Result

I expected the wheels to drop so that I could rearrange them in another place as I wasn't happy with the positions I had placed them in.

### Crash Report or Log

The crash logs are in the description because pastebin triggered their spam protection for some reason.

### Operating System

Windows 10

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Too many mods to list here, but the modpack was https://www.curseforge.com/minecraft/modpacks/sky-fabrication-3

### Additional Context

Sry but I had to put the log files in the description (I hope they were uploaded as files and not as text) because the logs are so weird that neither crashy.net nor pastebin were letting me through for some reason. MSandro (the modpack creator) adviced me to ask you guys here for help as it might have smth to do with the Fabric version of Flywheel.

**Comment by Tempest-5ky** [comment]
Managed to get them to work with mclo.gs if that's easier for anyone! These are the weirdest logs i have ever seen though
https://mclo.gs/Xbna9RS
https://mclo.gs/mCB3t4d
https://mclo.gs/biRqLYv

One thing i will say is that i'd recommend using FastLoad instead of Ksyxis, as Ksyxis can often cause issues. Fastload works almost as well but has none of the issues that Ksyxis can cause!

**Comment by TropheusJ** [comment]
The entire JVM crashed, quite an accomplishment. It's definitely flywheel, I think it has a couple issues open for these crashes. Try disabling it through the config in the main menu.

**Comment by JieningYu** [comment]
So that means players can't enable Flywheel without crashes?

**Comment by MSandro** [comment]
> The entire JVM crashed, quite an accomplishment. It's definitely flywheel, I think it has a couple issues open for these crashes. Try disabling it through the config in the main menu.

what do you mean?
![image](https://user-images.githubusercontent.com/10937159/180180757-5f19f284-401c-47c1-8e68-8c40c221c3c1.png)

**Comment by JieningYu** [comment]
backend switch to off

**Comment by MSandro** [comment]
thanks, but whats the impact of this option?
I am not exactly sure what Flywheel does.

**Comment by JieningYu** [comment]
down of rendering performance
