### ISSUE TITLE
The latest build won't start the game

### ISSUE THREAD

**Issue by Dr-WeiAL** [Fabricators-of-Create/Create#451]
### Describe the Bug

The build used is 679

### Reproduction Steps

1. start the game

### Expected Result

Started successfully

### Crash Report or Log

[latest.log](https://github.com/Fabricators-of-Create/Create/files/9173788/latest.log)

### Operating System

windows10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

**Comment by JieningYu** [comment]
0.5c is still under heavy development.

**Comment by Dr-WeiAL** [comment]
Yes, but when I saw a project that was built successfully, I downloaded it and tried it, and found that it couldn't run

**Comment by TropheusJ** [comment]
`Reference map 'create-refmap.json' for create.mixins.json could not be read.` oh no

**Comment by Dr-WeiAL** [comment]
Well, it seems like a small problem?
Just change `create-1.18.2-refmap.json` to `create-refmap.json` to run the game
