### ISSUE TITLE
Not compatible with Myron

### ISSUE THREAD

**Issue by Dr-WeiAL** [Fabricators-of-Create/Create#452]
### Describe the Bug

https://github.com/Fabricators-of-Create/Create/issues/425
copy of this issue
After the final determination, the incompatibility caused by myron in shetiphiancore

### Reproduction Steps

1.start the game

### Expected Result

Started successfully

### Crash Report or Log

[latest.log](https://github.com/Fabricators-of-Create/Create/files/9173828/latest.log)

### Operating System

windows10

### Mod Version

0.5.0

### Minecraft Version

1.18.2

### Other Mods

[myron](https://github.com/Haven-King/myron)

### Additional Context

After testing, the 679 build also has this problem

**Comment by ardissaps** [comment]
up

**Comment by ghost** [comment]
I tried updating mod shetiphiancore-fabric-1.18-1.2.14.jar and he is removing Myron there and now I can finally play the game with your amazing Create mod :)

**Comment by Tempest-5ky** [comment]
Shetiphiancore has been updated with a fix for this! https://www.curseforge.com/minecraft/mc-mods/shetiphiancore-fabric/files/3934933

**Comment by ardissaps** [comment]
yes, look like they will drop myron but currently converting model to non myron is in process.
