### ISSUE TITLE
Crash While Inserting Items to Chutes

### ISSUE THREAD

**Issue by kompl3xpr** [Fabricators-of-Create/Create#455]
### Describe the Bug

Inserting items from belts to chutes causes crash in some case.

### Reproduction Steps

see the screenshot

### Expected Result

no crash

### Screenshots and Videos

![2022-07-25_14 49 42-](https://user-images.githubusercontent.com/109941110/180721321-8c699f5d-909e-41bd-a7c7-3eed6e926d04.png)

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

**Comment by RedWideWeb** [comment]
@Kompl3xpr what mod do you use for this gui overlay of commands?

**Comment by kompl3xpr** [comment]
> @Kompl3xpr what mod do you use for this gui overlay of commands?

not any mod, just photoshop

**Comment by RedWideWeb** [comment]
> > @Kompl3xpr what mod do you use for this gui overlay of commands?
> 
> not any mod, just photoshop

Lol. Thanks 😂

**Comment by yury-kakareko-fortune** [comment]
@Kompl3xpr Isn't it duplication of [#403](https://github.com/Fabricators-of-Create/Create/issues/403)?
It was fixed at totays morning [commit](https://github.com/Fabricators-of-Create/Create/commit/1e9392b62eec74d078d995e9ff199bdfafb4e389)

**Comment by Bugord** [comment]
@Kompl3xpr Isn't it duplication of [#403](https://github.com/Fabricators-of-Create/Create/issues/403)?
It was fixed at totays morning [commit](https://github.com/Fabricators-of-Create/Create/commit/1e9392b62eec74d078d995e9ff199bdfafb4e389)

**Comment by kompl3xpr** [comment]
> @Kompl3xpr Isn't it duplication of [#403](https://github.com/Fabricators-of-Create/Create/issues/403)? It was fixed at totays morning [commit](https://github.com/Fabricators-of-Create/Create/commit/1e9392b62eec74d078d995e9ff199bdfafb4e389)

I'm sure it isn't, or the commit doesn't fully fix it.
