### ISSUE TITLE
Loading mod with ViaFabric doesn't work

### ISSUE THREAD

**Issue by zap8600** [Fabricators-of-Create/Create#456]
### Describe the Bug

Viafabric gives an error saying '1.19 block missing` when joining with mod loaded. I was going to test a 1.19 build but the Artifacts have expired. 

### Reproduction Steps

1. Install a 1.18.2 server
2. Install fabric API 
3. Install create mod
4. Install ViaFabric
5. Start server
6. Join from 1.19 Java Client

### Expected Result

The client should join the server

### Crash Report or Log

https://paste.gg/d1fd9171d99e4b2788b6ff9bcfe36c1c

### Operating System

Raspberry Pi OS aarch64

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
content mods will not work across game versions, and the old Create 1.19 versions never made it past the experimental snapshots. An actual 1.19 port has not been started. If you have a 1.18 server, just use Create 1.18?
