### ISSUE TITLE
Giving a wolf a train schedule will cause the game to crash

### ISSUE THREAD

**Issue by JLo100** [Fabricators-of-Create/Create#457]
### Describe the Bug

Whenever a train schedule is given to a wolf on the train the game crashes

### Reproduction Steps

1.Make a train 
2.Drop wolf onto a seat on the train
3.Right click the wolf with the schedule
...

### Expected Result

The train should automatically complete the schedule.

### Crash Report or Log

https://gist.github.com/JLo100/e17b141a016c32eaf5dd6616afa5ca94

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

**Comment by Paraxdq** [comment]
Wrong repository, they are no trains in create fabric.

**Comment by AlphaMode** [comment]
> Wrong repository, they are no trains in create fabric.

They are on the right repository they are using a build from actions

**Comment by Paraxdq** [comment]
> > Wrong repository, they are no trains in create fabric.
> 
> They are on the right repository they are using a build from actions

My bad :)
