### ISSUE TITLE
[1.18.2] REI + Create Crash

### ISSUE THREAD

**Issue by itsdinkd** [Fabricators-of-Create/Create#459]
### Describe the Bug

Crashing when viewing all categories and clicking on one of Create's machines (I didn't have time to see which one I clicked as it crashed pretty fast, I was going through all my packs mods recipe types). 

### Reproduction Steps

1. Open REI
2. Open All Categories by clicking on the Crafting Type (Crafting Table text)
3. Click through all Create's recipe types
4. Crash

### Expected Result

not to crash and to show that machine's available recipes

### Crash Report or Log

https://pastebin.com/KCZmWnmH

### Operating System

W11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
this seems to be fixed
