### ISSUE TITLE
Unbreakable glue cannot be used

### ISSUE THREAD

**Issue by FarmerOfBricks** [Fabricators-of-Create/Create#460]
### Describe the Bug

basically i wanted to make a cool windmill with some  glue in it so i craft it up and then when i try to use it it says not enough glue
this might be a feature and if so how do i use the glue and sorry for reporting it unnecarily

### Reproduction Steps

1.have glue in survival
2.attempt to glue 2 blocks with the box selecting thing
3.
...

### Expected Result

an error message above your hotbar saying "not enough glue in inventory" the selection box 
 however placing the glue in the offhand and placing 1 by 1 does work
only the mass selection doesent
 

### Screenshots and Videos

![2022-07-25_17 44 22](https://user-images.githubusercontent.com/107431499/181091151-dc172d1a-1431-4ada-892c-85a3fa45102c.png)

### Operating System

windows 11

### Mod Version

0.5.0

### Minecraft Version

1.18.2

### Additional Context

the server hosting service was  dedicated mc if that matters

**Comment by Sheep7798** [comment]
It works for me, maybe that's something with other mods

**Comment by digitaltrucker** [comment]
I find holding the glue in my offhand while placing blocks works best, it gets glued automatically.

**Comment by TropheusJ** [comment]
I can't get this to happen.
- does it work with a larger area selected?
- is the glue unbreakable? I've had issues with some ways of doing that
- it might be a mod incompatibility. See if you can find which mods together cause it.

**Comment by JieningYu** [comment]
I has this issue too.
Seems that the glue only works if the "use" button is set to "right click".
If I set it to button "R" then it can't work.

**Comment by TropheusJ** [comment]
works perfectly fine for me with left click. R not working is because it only checks for mouse input, which should probably be changed.

**Comment by JieningYu** [comment]
But if the use input is set to R, the right button can't be used to set up glue. So there's no way to set up glue unless use right button as 'use' or put the glue at the left hand and the block at the main hand.

**Comment by FarmerOfBricks** [comment]
im using right click
the glue is unbreakable because we have a mod on the server that remakes the enchantment system its called enhancements (https://www.curseforge.com/minecraft/mc-mods/enchancement)
it removes durability from everything

**Comment by FarmerOfBricks** [comment]
im using right click but the glue is unbreakable  because of this mod
https://www.curseforge.com/minecraft/mc-mods/enchancement

**Comment by FarmerOfBricks** [comment]
also @digitaltrucker i discovered it does work with offhand so thats what ive been doing
still would be nice to bulk glue stuff
