### ISSUE TITLE
Fatal NPE on SymmetryHandler events when NPCs from another mod interact with vanilla chests

### ISSUE THREAD

**Issue by tylerscallan** [Fabricators-of-Create/Create#462]
### Describe the Bug

This series of calls can throw an NPE if non player entities trigger the event or something like that -- I figure you all will see it immediately. 

Specifically here Mage Hands causes a fatal NPE.

Would recommend more null safety / graceful degradation / non fatal alerts (not sure if that's a mc thing etc, obvs you all know what to do) on all potentially global events.

Ty all -- Create is brilliantly clever and absolutely awesome.

https://github.com/Creators-of-Create/Create/blob/82be76d8934af03b4e52cad6a9f74a4175ba7b05/src/main/java/com/simibubi/create/content/curiosities/symmetry/SymmetryHandler.java#L56

### Reproduction Steps

1. use mage hands on a chest
2. crash

Does not occur when mage hands are not used on a chest.

### Expected Result

No NPE

### Crash Report or Log

https://pastebin.com/WT3LXBmA

### Operating System

Windows 11

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

Mage Hands

**Comment by TropheusJ** [comment]
This has already been fixed in dev
