### ISSUE TITLE
some form of vertical item transportation using belts

### ISSUE THREAD

**Issue by FarmerOfBricks** [Fabricators-of-Create/Create#464]
### Describe the Suggestion

so if you have a vertical belt and then you right click it with some thing like a depot or new item idk it would start going up the belt and items could be placed on it using stuff esseentially a belt but vertical

**Comment by TropheusJ** [comment]
please make gameplay suggestions to the Forge page.

**Comment by FarmerOfBricks** [comment]
ok i didnt know that sorry

**Comment by FarmerOfBricks** [comment]
may i ask what kind of suggestion i can make on this page?

**Comment by TropheusJ** [comment]
Anything that would be specific to the fabric version

**Comment by FarmerOfBricks** [comment]
oh so like mod compatability and stuff?

**Comment by TropheusJ** [comment]
Yeah

**Comment by FarmerOfBricks** [comment]
ok thanks

**Comment by DarianLStephens** [comment]
Can't you just use chutes with fans for that? Or those throwing pads, or fans in general, or vanilla bubble columns?
