### ISSUE TITLE
0.5 for Fabric

### ISSUE THREAD

**Issue by MezoPeeta** [Fabricators-of-Create/Create#465]
### Describe the Suggestion

Hello , i wanna add trains in my world , I'm using Fabric 1.18.2 , I appreciate your amazing work and how u made Minecraft more enjoyable but please I'm waiting for this .

**Comment by JieningYu** [comment]
0.5 fabric is still wip and you can test the dev builds from the latest commits.

**Comment by Skidamek** [comment]
You can already download it there https://github.com/Fabricators-of-Create/Create/actions/workflows/build.yml
Just select latest and download the artifacts

**Comment by TropheusJ** [comment]
Soon™️
