### ISSUE TITLE
Test build crash -suspected mod sodium

### ISSUE THREAD

**Issue by anim4trix** [Fabricators-of-Create/Create#467]
### Describe the Bug

is this expected?

### Reproduction Steps

Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Sodium (sodium)

latest fabric loader and api.

### Expected Result

.

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Additional Context

[crash-2022-07-29_13.58.30-client.txt](https://github.com/Fabricators-of-Create/Create/files/9223668/crash-2022-07-29_13.58.30-client.txt)

**Comment by Tempest-5ky** [comment]
mclo.gs and crashy logs for anyone who doesn't want to download the .txt:
https://mclo.gs/IWvslSe
https://crashy.net/3zOL1hzGnwWk1nm69QCB

Seems to be a config issue? I'd say it's an issue with Sodium, not Create, try deleting your Sodium configs

**Comment by anim4trix** [comment]
it said sodium but the culprit is create additions , i didnt know they were incompatible yet ,thanks
