### ISSUE TITLE
Flywheel occasionally causes broken contraption lighting

### ISSUE THREAD

**Issue by fizziy** [Fabricators-of-Create/Create#468]
### Describe the Bug

(Newest fabric beta, so sorry if this is known already) When train is in movement the train seems to get dark visually, and even sometimes when stopped. acts similar to if there was a platform above the train, casting a shadow. flipping a trapdoor updates lighting, but if it starts moving again it continues it.
![image](https://user-images.githubusercontent.com/86824139/181866934-56661ccc-a996-4edc-8e69-f7d90644d9be.png)

### Reproduction Steps

1. build a train

2. try to ride it

### Expected Result

I expected it not to have shadows

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/86824139/181866943-809fe6e6-f155-4111-8249-37020a8b6999.png)

### Operating System

Windows 11 

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

AppleSkin

Architectury

Badpackets

BeyondEarth

ClothConfig

Fabric API

FarmersDelight

LambDynamicLights (possible cause of issue?)

Patchouli

Replaymod

REI

SmoothBoot

VoiceChat

WTHIT

**Comment by fizziy** [comment]
Id like to update, the dynamic lighting mod was not causing the problem

**Comment by Sheep7798** [comment]
Try starlight mod

**Comment by fizziy** [comment]
> 

ive heard that mod is good, but will it be fixed or is it a mc problem?

**Comment by JieningYu** [comment]
Probably a mc bug

**Comment by RedWideWeb** [comment]
> ive heard that mod is good, but will it be fixed or is it a mc problem?

You just have no idea HOW BAD Minecraft lighting engine is. It’s totally Minecraft issue

**Comment by fizziy** [comment]
> > ive heard that mod is good, but will it be fixed or is it a mc problem?
> 
> You just have no idea HOW BAD Minecraft lighting engine is. It’s totally Minecraft issue

makes sense, i tried the mod and it still didnt fix it tho

**Comment by TropheusJ** [comment]
what if the train is moved somewhere else? what if flywheel is disabled with `/flywheel engine off`?

**Comment by ghost** [comment]
I have the same problem... have yall been able to fix it?

**Comment by ghost** [comment]
The problem was the flywheel engine... however disabling it causes a massive drop in fps when close to the train

**Comment by pastellexists** [comment]
I've had a similar problem, it seems inconsistent and may have something to do with the actual composition of the train. Some trains seem to have the problem, some don't. I haven't been able to work out what the common factor is, if there is one.

**Comment by pastellexists** [comment]
Update: this problem is definitely present on v0.5.0.i-1003+1.19.2. As with ghost above, disabling the Flywheel renderer fixes it, but of course, rendering trains and other contraptions without it is pretty untenable.

**Comment by James103** [comment]
Have you tried increasing the value of `maxContraptionLightVolume` to a high value, such as `9999999`?

From checking the code, it appears if the volume of the _bounding box_ of a Create contraption exceeds the value of `maxContraptionLightVolume`, the contraption's lighting is not updated, causing artifacts as shown in previous posts.

The default value of 16384 works for small contraptions, but even contraptions containing less than 100 blocks can exceed this limit if the blocks extend in a line out from the anchor (minecart, gantry shaft, etc). The value `9999999` should be sufficient for any contraption with a size less than 80 blocks on its longest axis.

**Comment by IThundxr** [comment]
You should change maxContraptionLightVolume if you have big contraptions
