### ISSUE TITLE
Crash on startup REI+Create

### ISSUE THREAD

**Issue by UberMorgott** [Fabricators-of-Create/Create#470]
### Describe the Bug

I create my own builds to play with friends. But the build stops after 2 core mods (create and fabric)
REI+create-1.18.2-0.5.0c-702

### Reproduction Steps

1.Launch and wait
2.The game will crash
3.
...

### Expected Result

The game should launch with no issues

### Crash Report or Log

https://pastebin.com/rGuQMJ5K

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

fabric-api-0.58.0+1.18.2
RoughlyEnoughItems-8.3.519

**Comment by Graphicscore** [comment]
Are you sure you're having the dependencies for REI installed? As far as I am aware it needs architectury

**Comment by UberMorgott** [comment]
> Are you sure you're having the dependencies for REI installed? As far as I am aware it needs architectury

Yes, my fault.
Initially, the pack of mods was from 180pcs. Removed 1 piece to calculate the cause of the crash. Looks like I checked everything 10 times. turns out not all.
You can close this issue. -_- Sorry.
