### ISSUE TITLE
When you have 2+ same named stations, train goes to nearest available.

### ISSUE THREAD

**Issue by sall0-0p** [Fabricators-of-Create/Create#471]
### Describe the Suggestion

Now if you have few same named stations, train will go to random of them. That will be great to have it going to nearest instead. It will give us ability to run stations with different platforms and one-way stations much easier.

### Screenshots and Videos

<img width="850" alt="Screenshot 2022-07-30 at 21 19 18" src="https://user-images.githubusercontent.com/79805623/181940822-507599a0-1299-4ee7-9451-0c8fbd2081d2.png">
Yellow - how it could go.
Blue - how it goes.

### Additional Context

When you have lots of stations, it will be better to set ONE station name, and it will take best platform automatically.

**Comment by TropheusJ** [comment]
suggestions changing behavior should be submitted to the forge repo.
