### ISSUE TITLE
New glue cannot be used with alternative use bindings.

### ISSUE THREAD

**Issue by Aquaeyes** [Fabricators-of-Create/Create#473]
### Describe the Bug

Rebinding use item from right click to E does not allow for the new glue to function.

### Reproduction Steps

1. Rebind Right Click to E
2. Attempt to Right Click anything with Glue

### Expected Result

The Glue would glue an area, which did not even show the highlight.

### Operating System

MacOS 12.3

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
this should be resolved on 1.19 with a refactor to interaction listening
