### ISSUE TITLE
No recipe for brass in REI

### ISSUE THREAD

**Issue by triffman33** [Fabricators-of-Create/Create#474]
### Describe the Bug

Pressing R on a brass ingot does not come up with the mixing recipe for brass, however pressing U on a zinc or copper ingot will show the mixing recipe in REI.

### Reproduction Steps

1. Press R on brass ingot to find the mixing recipe
2. Open eyes

### Expected Result

Show the recipe for brass in the mixer

### Screenshots and Videos

![2022-07-31_18 26 39](https://user-images.githubusercontent.com/31788797/182038352-4feccb6b-3dca-48b1-bfad-125e795007fb.png)
![2022-07-31_18 26 51](https://user-images.githubusercontent.com/31788797/182038354-8d410d58-f423-40dd-87f5-15ca2db6e425.png)

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

REI mods

**Comment by CzechHek** [comment]
Only EMI is fully supported as of now. REI and JEI are being worked on.

**Comment by triffman33** [comment]
Ahh i see, thank you, didn't realise there was a different mod.

**Comment by AlphaMode** [comment]
Fixed in latest commit
