### ISSUE TITLE
Water Rendering Is Weird With Framed Glass [Fabric]

### ISSUE THREAD

**Issue by DakotaPride** [Fabricators-of-Create/Create#476]
### Describe the Bug

There are these weird lines that appear on the bottom of the water texture (or maybe on top of the framed glass texture?)

### Reproduction Steps

1. Make a little area of water
2. Put Framed Glass Underneath
3. Go Beneath The Glass And Look Through It
...

### Expected Result

Just the normal water texture or no texture above it (I think there's an issue with Minecraft's normal glass, where the water texture doesn't show up from underneath, so I'm not sure which it's exactly meant to be)

### Screenshots and Videos

![2022-07-31_20 03 46](https://user-images.githubusercontent.com/82760983/182054609-ce928f38-62ad-449d-a81c-63dcafae391c.png)

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

YOSBR (Your Options Shall Be Respected)
World Edit
WMITAF (What Mod Is This Actually From?)
VoidZ
Visuality
Villager Quests
Villager Hats
Vein Mining
Universal Ores
Universal Bonemeal
Twigs
Tweakeroo
Toro Health Damage Indicators
Snow Pig
Sodium
Smooth Boot
Sit
Simple Voice Chat
Shulker Box Tooltip
Satin
Runelic
Roughly Searchable
Roughly Enough Resources
Roughly Enough Professions
Roughly Enough Items
Rat's Mischief
Quick Shulker
Puzzle
Probably Chests
Pollen
Pickable Villagers
Pick Your Poison
Phospher
PAUCAL
Patchouli
Not Enough Crashes
No Indium?
Indium
Nears
Name Pain
Mouse Tweaks
More Geodes
More Axolotl Variants Mod
Mod Menu
MaliLib
Logical Zoom
Lithium
Legendary Tooltips
LazyDFU
Language Reload
LambDynamicLights
Krypton
Jankson
Jade
Iris Shaders
Inventory Sorts
Inmis
Incantation
Impaled
Illuminations
Iceberg
Health Overlay
Harvest Scythes
Geckolib
Full Brightness Toggle
FPS Reducer
Ferrite Core
Farsight Mod
Falling Leaves
Fabric Language Kotlin
Etched
Equipment Compare
Entity Texture Features
Enderscape
Eden Ring
Ecologics
Dynamic FPS
Disable Custom Worlds Advice
Detail Armour Bar
Delete Worlds To Trash
Deepslate Cutting
Decorative Blocks
Dash Loader
Custom Entity Models
Creeper Overhaul
Controlling
Continuity
Comforts
Collective
Clumps
Clean Cut
CIT Resewn
Chimes
Cherished Worlds
Charmonium
Bosses Of Mass Destruction
Blur
Better Biome Blend
Bed Spreads
BCLib
Basic Shields
Bad Packets
Axolotl Item Fix
Architectury
Architect's Palette
Applied Energistics 2
Animatica
Appleskin
AdventureZ

**Comment by TropheusJ** [comment]
does it happen without Sodium?

**Comment by DakotaPride** [comment]
Yes. And After I disabled Sodium, I wanted to make sure, so I reenabled it as well as Indium, and the issue didn't happen. It's either Phospher, Lithium, Or Iris Shaders

**Comment by TropheusJ** [comment]
iris is a likely culprit, could you try just toggling that?

**Comment by DakotaPride** [comment]
I disabled All Sodium-related mods and then reenabled them one by one and for some reason, it just doesn't happen, even though it's the same modlist, just after a ton of removing/adding back mods. Also, sorry that it took a little bit to respond back, as there were like 6-7 mods that depended on Sodium, meaning I had to load Minecraft with some of those disabled and then had to reopen it and continue it until it happened again (but it didn't happen again, not sure why)
