### ISSUE TITLE
Funnel on Item Vault with comparator output crashes server

### ISSUE THREAD

**Issue by kevalpithadiya** [Fabricators-of-Create/Create#477]
### Describe the Bug

When an Item Vault has a Comparator output and a Brass Funnel (have not tested Andesite Funnel) output, the server crashes on attempting to output new stack after current stack is retrieved by a player.

### Reproduction Steps

1. Setup an item Vault and store some items in it.
2. Attach an output Brass Funnel on the Item Vault
3. Add a comparator output to the Item Vault
4. Pick up the item stack dropped by the funnel.

### Expected Result

The funnel should drop another stack from the stored items in the Item Vault without crashing the server / game.

### Screenshots and Videos

![Screenshot of Setup](https://i.imgur.com/aLGObdX.png)

### Crash Report or Log

https://pastebin.com/XBGAfgZv

### Operating System

Linux (Endeavour OS)

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Other Mods

appleskin-fabric-mc1.18.1-2.3.0.jar
architectury-4.6.77-fabric.jar
BetterF3-1.2.4-Fabric-1.18.2.jar
cammies-minecart-tweaks-1.4.jar
cloth-config-6.2.57-fabric.jar
continuity-1.1.0+1.18.2.jar
create-mc1.18.2_v0.4.1+637.jar
fabric-api-0.58.0+1.18.2.jar
fabric-language-kotlin-1.8.2+kotlin.1.7.10.jar
indium-1.0.2+mc1.18.2.jar
iris-mc1.18.2-1.2.2-build.32.jar
malilib-fabric-1.18.2-0.12.1.jar
mcw-lights-1.0.3fabric-mc1.18.2.jar
modmenu-3.1.0.jar
mousewheelie-1.10.2+mc1.18.2.jar
RoughlyEnoughItems-8.3.510.jar
sodium-extra-0.4.6+mc1.18.2-build.46.jar
sodium-fabric-mc1.18.2-0.4.1+replaymod.rev.23e83a1.jar
starlight-1.0.2+fabric.89b8d9f.jar
tweakeroo-fabric-1.18.2-0.13.1.jar
Xaeros_Minimap_22.12.0_Fabric_1.18.2.jar
Zoomify-1.6.0.jar

### Additional Context

This behavior was tested on an Aternos server as well as a local world.

**Comment by anim4trix** [comment]
looks smiliar #269

**Comment by kevalpithadiya** [comment]
> looks smiliar #269

Does the fix address this specific bug as well?

**Comment by TropheusJ** [comment]
fixed in dev
