### ISSUE TITLE
Add key binds to control scroll behavior

### ISSUE THREAD

**Issue by Sammcb** [Fabricators-of-Create/Create#483]
### Describe the Suggestion

Some features, such as selecting parameters on the sequenced gearshift or adjusting the block attachment distance using a wrench on the linear chassis, require the use of scrolling. I run Minecraft on my Mac laptop and only have the trackpad, which has a very high sensitivity scroll (there are options to adjust it in the Minecraft Options panel, but I don't thing Create respects these from my testing). This makes using the sequenced gearshift and other scrolling-based mechanisms nearly unusable. Would love to see some other options for controlling these items!

Thanks!

**Comment by TropheusJ** [comment]
Suggestions that aren't specific to the Fabric version should be submitted to the Forge repo.

**Comment by VityaSchel** [comment]
I made a small mixin-based patch mod that allows you to change sensitivity of Create scroll inputs for Fabric (1.20.1) and NeoForge (1.21.1)

![Screenshot](https://cdn.modrinth.com/data/cached_images/b393c56079692b61443321dac13e10bda0ad343e.png)

https://git.hloth.dev/demovio/minecraft-create-touchpad-scrolling-fix
https://modrinth.com/mod/create-touchpad-scrolling-fix (currently under review)
