### ISSUE TITLE
Latest Version Crash 0.5c

### ISSUE THREAD

**Issue by ardissaps** [Fabricators-of-Create/Create#484]
### Describe the Bug

Crash

### Reproduction Steps

Update Create Fabric to 0.5c

### Expected Result

Not Crash

### Crash Report or Log

https://paste.atlauncher.com/view/f258b2a0-6f0d-4c2c-9fcc-ab350cd35b40

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

(In the log)

**Comment by TropheusJ** [comment]
Create deco is not updated.

**Comment by ardissaps** [comment]
> Create deco is not updated.

Ah yes! I just forgot that I have some addons that need to be updated too! I am so sorry!
