### ISSUE TITLE
crash with NPC Variety

### ISSUE THREAD

**Issue by 800020h** [Fabricators-of-Create/Create#486]
### Describe the Bug

when joining a world with Create and NPC Variety
I get a "Exception ticking world" crash

### Reproduction Steps

1.have Create and NPC Variety
2.try to join/create a world
3.
...

### Expected Result

it would work and not crash

### Crash Report or Log

https://gist.github.com/800020h/5395fb9bf09687c7ec6a89ebd5b1082a

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

NPC Variety 2.2.1
https://www.curseforge.com/minecraft/mc-mods/npc-variety-port

Fabric API 0.58.0+1.18.2

### Additional Context

note:
it didn't happen with create 0.4.1 and NPC Variety 2.2.1

**Comment by TropheusJ** [comment]
Install this and get a new crash log https://modrinth.com/mod/mixintrace

**Comment by 800020h** [comment]
new log after installing that ^
https://gist.github.com/800020h/3c62ab550e911386e3b238b14cb015e4

**Comment by TropheusJ** [comment]
I don't see how this can be Create's fault, are you sure it's fine without it?

**Comment by TropheusJ** [comment]
nevermind, found possible culprit. new build coming soon.

**Comment by 800020h** [comment]
NPC Variety is working as expected in the same instance after disabling Create
and was working in another instance with Create 0.4.1

I started typing this before the previous comment was sent

**Comment by TropheusJ** [comment]
okay this is not a simple fix, build coming tomorrow maybe.

**Comment by 800020h** [comment]
still an issue with Create 0.5.0d and NPC Variety 2.2.1
crashlog
https://gist.github.com/800020h/9da03f429ce8835ed96d3dab0c539807

**Comment by 800020h** [comment]
fixed by NPC Variety 2.2.2
https://github.com/OverlordsIII/NPCVarietyPort/pull/20
