### ISSUE TITLE
[0.5c] crash on startup: com.simibubi.create.foundation.config.ui.OpenCreateMenuButton.renderBackground(OpenCreateMenuButton.java:35)

### ISSUE THREAD

**Issue by MSandro** [Fabricators-of-Create/Create#488]
### Describe the Bug

crash on starting my modpack. It seems to be a Mod combat issue. I am trying to figure out which one it is and will post this info here.

### Reproduction Steps

1. Download my Modpack Sky FABRICation 3
2. Update Create to 0.5c
3. remove addons (CreatePlus, CreateAdditions and KubeJS Create)
4. start the modpack
5. crash

### Expected Result

not crashing

### Crash Report or Log

https://gist.github.com/MSandro/29c4fa7494b67e78154101df2a8de597

### Operating System

Manjaro Linux

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

https://www.curseforge.com/minecraft/modpacks/sky-fabrication-3

**Comment by StockiesLad** [comment]
It's just a blockstate file issue so it would be fixed considerably quickly.

**Comment by MSandro** [comment]
currently its incompatible with shetiphiancore-fabric-1.18-1.2.13!
![image](https://user-images.githubusercontent.com/10937159/182645650-0a073945-9cec-4d82-a6a7-b0312205d3f3.png)

**Comment by TropheusJ** [comment]
Duplicate of #452

**Comment by StockiesLad** [comment]
What the hell is myron doing to interrupt blockstates ??????????
