### ISSUE TITLE
Game crashes when placing down train track

### ISSUE THREAD

**Issue by RichterFowl** [Fabricators-of-Create/Create#489]
### Describe the Bug

After updating to 0.5c, placing a train track causes the game to crash for the user who places the track. 

Other players on the server are not affected unless they get within a certain distance of the placed track.

Other new items from update like the steam whistle don't seem to trigger a crash.

### Reproduction Steps

1. Launch 1.18.2 Fabric with 0.5c Create
2. Place train track on ground
3. Game will go into a "Saving World" screen briefly before it crashes and prompts error message: java.lang.IllegalStateException: Wrapping function stack not empty!
...

### Expected Result

Track to be placed on ground.

### Crash Report or Log

https://pastebin.com/v2Wxtpyv

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

additionaladditions: Additional Additions 4.0.5
adorn: Adorn 3.5.0+1.18.2
advancementplaques: Advancement Plaques 1.4.5
advdebug: Advancements Debug 2.3.0
appleskin: AppleSkin 2.4.0+mc1.18.2
architectury: Architectury 4.5.76
badpackets: Bad Packets 0.1.2
balm-fabric: Balm 3.1.0+0
betteranimalsplus: Better Animals Plus 1.18.2-11.0.5
bewitchment: Bewitchment 1.18-22
bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.7-1.18.2
byg: Oh The Biomes You'll Go 1.4
cardinal-components: Cardinal Components API 4.2.0
citresewn: CIT Resewn 1.1.1+1.18.2
comforts: Comforts 1.1.2-1.18.2
continuity: Continuity 2.0.0+1.18.2
create: Create 0.5.0c-708
croptopia: Croptopia 2.0.5
ecologics: Ecologics 1.7.2
explorerscompass: Explorer's Compass 1.18.2-2.1.0-fabric
fabric: Fabric API 0.57.0+1.18.2
fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
fabricloader: Fabric Loader 0.14.8
forgottengraves: Forgotten Graves 1.18.2-2.6.0
friendsandfoes: Friends&Foes 1.4.5
geckolib3: Geckolib 3.0.35
iceberg: Iceberg 1.0.38
indium: Indium 1.0.6+mc1.18.2
infusion_table: Infusion Table 1.1.0
inmis: Inmis 2.6.0-1.18.2
iris: Iris 1.2.5
journeymap-fabric: Journeymap 5.8.2
lazydfu: LazyDFU 0.1.2
lithium: Lithium 0.7.10
mavm: More Axolotl Variants Mod 1.0.7a
mcda: MC Dungeons Armors 2.0.6
mcdar: MC Dungeons Artifacts 1.4.8
mcdw: MC Dungeons Weapons 4.4.0
medievalorigins: Medieval Origins 1.18.x-4.0.3
memoryleakfix: Memory Leak Fix 1.18.2-0.7.0
minecraft: Minecraft 1.18.2
modmenu: Mod Menu 3.2.3
morevillagers: More Villagers 3.3.2
mostructures: Mo' Structures 1.4.2+1.18.2
naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
origins: Origins 1.4.1
patchouli: Patchouli 1.18.2-71.1-FABRIC
pehkui: Pehkui 3.3.3+1.14.4-1.19.1
playerabilitylib: Pal 1.5.1
reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.18.2-build.42
roughlyenoughitems: Roughly Enough Items 8.3.501
seethroughlava: SeeThroughLava 2.3
skylorlib: SkyLib 1.3.35
sodium: Sodium 0.4.1+build.15
sodium-extra: Sodium Extra 0.4.5+mc1.18.2-build.42
starlight: Starlight 1.0.2+fabric.89b8d9f
terrablender: TerraBlender 1.1.0.102
trinkets: Trinkets 3.3.1
twilightforest: The Twilight Forest 4.1.251
untitledduckmod: Untitled Duck Mod 0.5.0
vanilla-hammers: Vanilla Hammers 3.4.0-1.18.2
waystones: Waystones 2.5.4
wthit: wthit 4.11.0

**Comment by DazDaz11** [comment]
I have noticed that Iris 1.2.5 was causing the crashing with the track and when I updated Iris to 1.2.6 it started working as intended.
Likely something rendering related.

**Comment by Sheep7798** [comment]
Your iris version is too old

**Comment by RichterFowl** [comment]
Thanks! Updating Iris did the trick.
