### ISSUE TITLE
OpenGL shader compilation error on Mesa (Linux Intel/AMD)

### ISSUE THREAD

**Issue by ryndinol** [Fabricators-of-Create/Create#49]
### Describe the Bug

Regression  in recent commit 5cfe04cff770174c686f1f75b5c8cfae7d1d5eaf for shader crash that was fixed in upstream Create.

```
[21:01:53] [Render thread/INFO] (com.mojang.blaze3d.platform.GlDebug) OpenGL debug message: id=3, source= SHADER COMPILER, type=ERROR, severity=HIGH, message='0:69(1): error: #extension directive is not allowed in the middle of a shader'
[21:01:53] [Render thread/ERROR] (com.jozufozu.flywheel.backend.Backend) Shader compilation log for create:rotating: 0:69(1): error: #extension directive is not allowed in the middle of a shader
```

Only fails on Intel/AMD graphics on Linux.
Upstream commit of fix:
https://github.com/Creators-of-Create/Create/commit/67bcbc874bc48b5f8f332335628cf2f2b1abd932

Regression in this commit:
https://github.com/Create-Fabric/Create-Refabricated/commit/5cfe04cff770174c686f1f75b5c8cfae7d1d5eaf#:~:text=if%20defined(GL_ARB_conservative_depth)-,%23,-extension%20GL_ARB_conservative_depth%20%3A%20enable

### Reproduction Steps

1. Checkout 5cfe04cff770174c686f1f75b5c8cfae7d1d5eaf or later on Linux running Intel/AMD graphics.
2. ./gradlew clean runClient --no-daemon
3. See shader compilation error in log
4. delete `#extension GL_ARB_conservative_depth : enable` in `src/main/resources/assets/create/flywheel/shaders/context/contraption.glsl` (it's already included in `#use "flywheel:context/fog.glsl"` I think)
5. recompile, runs in-game as expected.

### Expected Result

...

### Operating System

Void Linux (mesa-21.2.6_1)

### Mod Version

0.4.0a

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
speedrun
