### ISSUE TITLE
Schematicannon crashes and causes bugged lighting with Botania, LazyDFU, and Lithium installed

### ISSUE THREAD

**Issue by object-Object** [Fabricators-of-Create/Create#490]
### Describe the Bug

When building schematics in singleplayer with the Schematicannon with Botania, LazyDFU, and Lithium installed, the game crashes after a few blocks have been placed.

In multiplayer, it doesn't seem to crash (I haven't tested extensively), but when you leave the area and come back, the chunk's lighting is messed up (see screenshot). I've also had the lighting bug happen a couple of times while testing in singleplayer, but I can't seem to make it happen reliably.

### Reproduction Steps

1. Have Create, Botania, LazyDFU, Lithium, and deps installed.
2. Place a Schematicannon with a Creative Crate (I'm fairly sure it also happens pulling from a normal chest, but I haven't extensively tested it).
3. Load a schematic and build it. The crash should happen within the first 30 seconds or so. Sometimes it doesn't happen — try generating a new world and trying again.

### Expected Result

I expected the Schematicannon to build my schematic without crashing the game.

### Screenshots and Videos

The bugged lighting that sometimes shows up.
![2022-08-03_11 43 42](https://user-images.githubusercontent.com/37044997/182651443-fc18007b-efcd-4660-8392-577a403cec2c.png)

### Crash Report or Log

https://crashy.net/0MirtTFifSWuYG9Da0KA or https://bytebin.lucko.me/2yr0thuCkO

### Operating System

Windows 11 Home 10.0.22000

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

Patchouli-1.18.2-71.1-FABRIC.jar
trinkets-3.3.1.jar
lazydfu-0.1.2.jar
Botania-1.18.2-434-FABRIC.jar
lithium-fabric-mc1.18.2-0.7.10.jar
fabric-api-0.58.0+1.18.2.jar
notenoughcrashes-4.1.6+1.18.2-fabric.jar

### Additional Context

This bug also happens with Create v0.4.1+637.

[Here's the schematic I've been testing with](https://drive.google.com/file/d/16UJ9WCp6UQg1lH5mwBR8NVEyH-ETHeFw/view?usp=sharing). I don't think there's anything special about it, it's just using vanilla and Create redstone. The crash happens very early, when it's still placing the stone bricks.

**Comment by TropheusJ** [comment]
Is this your entire mod list? I think this is two separate issues.
The actual crash seems to be caused by Botania, and I don't see how Create could make it happen.
There's several known issues with lighting, but they're caused by having Phosphor.

**Comment by object-Object** [comment]
Yes, this is the entire smallest modlist where I got the crash to happen.

**Comment by TropheusJ** [comment]
My guess is botania caused the crash and the crash messed up lighting. Don't think it's create's fault, and even if it is, this isn't reproducible.
