### ISSUE TITLE
Memory leak in WorldAttached class

### ISSUE THREAD

**Issue by Rasmion** [Fabricators-of-Create/Create#491]
### Describe the Bug

WorldAttached seems to have problems with removing unloaded worlds. Flywheel also has a WorldAttached class in which this bug is probably fixed, at least there are comments that suggest this.

### Reproduction Steps

1. Build some constraptions in your world
2. Switch the world a few times
3. Notice the memory increase

### Expected Result

There should be no memory leak, which eventually leads to lag spikes and crashes.

### Screenshots and Videos

net.minecraft.class_638 -> ServerLevel
![grafik](https://user-images.githubusercontent.com/42215949/182696409-7aa35e67-d4e2-4860-981a-717f8da8b309.png)
![grafik](https://user-images.githubusercontent.com/42215949/182696488-c5fa7342-4809-4529-b9fc-1ab8b3ced77f.png)

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
An issue should be made to the forge repo.
