### ISSUE TITLE
Glue from schemetics from v0.4 dosnt work with v0.5

### ISSUE THREAD

**Issue by StoneMcYT** [Fabricators-of-Create/Create#493]
### Describe the Bug

When pasting a schematic from v0.4 into a v0.5 world the glue doesn't actually stick 

### Reproduction Steps

1. Make a schem in v0.4 glue a bunch of blocks together eg Redstone to liner chasis 
2. Paste the schem in v0.5 ontop of a contraception assembler/bellow a rope pully
3. Activate the rope pully/contraption assembler 
4. See the redstone dust fall off
...

### Expected Result

The glue should have been glued 

### Screenshots and Videos

https://youtu.be/TpZlmH_qY98
There's no audio  but what is happening 
- Loading up a schematic (Not mine) via the table 
- Pasting it
- Removing the drill portion of it as I can't show the bug with it as it blocks the rope portion
- Shows the Redstone contact + Redstone dust being there 
- Activities the rope pully 
- Sees the Redstone dust and the Redstone contact no stick
Yes, i have tested this schem in v0.4 and i am sure it works 

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

![image](https://user-images.githubusercontent.com/67421882/182769071-e1d53392-361a-43ed-b16f-325a7e86a7ef.png)

**Comment by JieningYu** [comment]
Is this an upstream issue?

**Comment by StoneMcYT** [comment]
> Is this an upstream issue?

uh sorry im not that good with my code terminology but you mean upstream as as in upgrading versions right?

**Comment by JieningYu** [comment]
upstream means Create Forge

**Comment by StoneMcYT** [comment]
> upstream means Create Forge

ah you meant fork upstream nope this is a create mod fabric issue

**Comment by Sheep7798** [comment]
Are you sure ? I heard that was a forge issue too since they changed the way glue works

**Comment by StoneMcYT** [comment]
> Are you sure ? I heard that was a forge issue too since they changed the way glue works

I am 100% sure i am on fabric my mods list cleary states that and the 'changed the way glue works' was a new mechanic implemented in v0.5 which was newly released to fabric users 
![image](https://user-images.githubusercontent.com/67421882/182806536-41f8ce14-0fd1-4756-9fb5-4237b665ced0.png)

**Comment by SplendidAlakey** [comment]
"Upstream issue" means that it's something that Forge version devs have to fix and then Fabric devs merge it into the Fabric version.

And it is indeed an upstream issue: https://github.com/Creators-of-Create/Create/issues/3410

**Comment by StoneMcYT** [comment]
oh great im dumb i didint check the forge devs issue tracker

**Comment by StoneMcYT** [comment]
Sorry bout that yall

**Comment by TropheusJ** [comment]
Issues that occur on Forge as well are no longer being tracked on this repo. Please follow the respective issue on the Forge repo instead: https://github.com/Creators-of-Create/Create/issues/3410
