### ISSUE TITLE
create-1.18.2-0.5.0c-708.jar crashes on start up

### ISSUE THREAD

**Issue by Fade-Alchemist** [Fabricators-of-Create/Create#495]
### Describe the Bug

Game crashes on startup with the new version create-1.18.2-0.5.0c-708.jar .  
returns error"

The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1087.method_4710()" because "$$6" is null
Exit Code: **-1**

crash log attached
[crash-2022-08-06_01.09.39-client.txt](https://github.com/Fabricators-of-Create/Create/files/9274478/crash-2022-08-06_01.09.39-client.txt)

### Reproduction Steps

1. Load the game with mods present in the attached crash log
2. The game then crashes.
3.
...

### Expected Result

The game launches without crashing. 

[crash-2022-08-06_01.09.39-client.txt](https://github.com/Fabricators-of-Create/Create/files/9274484/crash-2022-08-06_01.09.39-client.txt)

### Screenshots and Videos

n/a

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

Included in the crash report..... from that report

additionalbars: Additional Bars 3.3.1+1.18.2
		adorn: Adorn 3.5.0+1.18.2
		advancementplaques: Advancement Plaques 1.4.5
		adventurez: AdventureZ 1.4.11
		annotateddi: Annotated DI 4.0.1+1.18.2
			aopalliance_aopalliance: aopalliance 1.0
			com_google_inject_guice: guice 5.1.0
			javax_inject_javax_inject: javax.inject 1
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.7.78
		armor-stand-swap: Armor Stand Swap 1.0.2
		attributefix: AttributeFix 14.0.2
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 3.2.0+0
		bclib: BCLib 1.4.7
		bedspreads: Bedspreads 1.6.0-1.18
		beehivetooltips: Beehive Tooltips 1.4.2
		besmirchment: Besmirchment 1.18.2-12
			playerabilitylib: Pal 1.5.0
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		betterend: Better End 1.1.1
		betternether: Better Nether 6.1.2
		bettersleeping: BetterSleeping 0.6.1+1.17
			bettersleeping-core: BetterSleeping Core 0.6.1
			org_apache_commons_commons-text: commons-text 1.9
		bewitchment: Bewitchment 1.18-23
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		blastingsand: BlastingSand 1.18.2-2
		boatcontainer: BoatContainer 1.2.2
		bookshelf: Bookshelf 13.2.47
		botania: Botania 1.18.2-434-FABRIC
			fiber: fiber 0.23.0-2
		camsbackpacks: Cammie's Wearable Backpacks 2.11
		chipped: Chipped 1.2
		chisel: Chisel Refabricated 1.4.5
		chiselsandbits: Chisels & Bits 1.2.113
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 8.0.0+15
		comforts: Comforts 1.1.2-1.18.2
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		connectiblechains: Connectible Chains 2.1.1+1.18.2
		continuity: Continuity 2.0.0+1.18.2
		controlling: Controlling For Fabric 9.0+21
		create: Create 0.5.0c-708
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			flywheel: Flywheel 0.6.4-30
			forge_tags: Forge Tags 2.1
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			noindium: No Indium? 1.0.1+1.18.2
			porting_lib: Porting Lib 1.2.421-beta+1.18.2-dev.b8d195a
				mm: Manningham Mills 2.3
				serialization_hooks: Serialization Hooks 0.3.21
			registrate-fabric: Registrate for Fabric MC1.18.2-1.1.3
				com_github_llamalad7_mixinextras: MixinExtras 0.0.11
		createplus: CreatePlus 1.0
		culinaire: Culinaire 2.4.0
		dankstorage: Dank Storage 1.18.2-3.7.1
		dark-loading-screen: Dark Loading Screen 1.6.11
		darkrites: Dark Rites 1.18.2-1
		dawn: Dawn API 3.3.2
		decorative_blocks: Decorative Blocks 2.1.0
		deepslatecutting: Deepslate Cutting 1.3.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			maybe-data: Maybe data 1.3.1-1.18.2
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		enchdesc: EnchantmentDescriptions 10.0.4
		enhancedcelestials: Enhanced Celestials 2.0.7
		experiencebugfix: Experience Bug Fix 18
		extraalchemy: Extra Alchemy 1.8.1
		extraorigins: Extra Origins 1.18-12
		fabric: Fabric API 0.58.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.1+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.10+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.3+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		farmersdelight: Farmer's Delight 1.18.2-0.2.1
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		fireplacelib: Fireplace Lib 7.0.2+1.18.2
		forgeconfigapiport: Forge Config API Port 3.2.3
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		genesis: Genesis 1.18.2-1.0.1
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.14
		iceberg: Iceberg 1.0.38
		indium: Indium 1.0.7+mc1.18.2
		inventorysorter: Inventory Sorter 1.8.8-1.18
			kyrptconfig: Kyrpt Config 1.4.6-1.18
				blue_endless_jankson: jankson 1.2.1
		ironchests: Iron Chests 1.7.4
			libgui: LibGui 5.4.2+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
				libninepatch: LibNinePatch 1.1.0
		java: OpenJDK 64-Bit Server VM 17
		kubejs: KubeJS 1802.5.4-build.533
		kubejs_create: KubeJS Create 1802.2.2-build.26
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		lightoverlay: Light Overlay 6.0.5
		litematica: Litematica 0.11.3
		lithium: Lithium 0.7.10
		ljcia: Literally Just Cheap Invisible Armor 1.0.0
		malilib: MaLiLib 0.12.1
		marketcrates: Marketcrates 1.4.1
		mcda: MC Dungeons Armors 2.0.7
		mcdar: MC Dungeons Artifacts 1.4.8
		mcdw: MC Dungeons Weapons 4.4.1
			enchant_giver: Enchant Giver 1.2.1
		mcwbridges: Macaw's Bridges 2.0.3
		mcwdoors: Macaw's Doors 1.0.6
		mcwfences: Macaw's Fences and Walls 1.0.6
		mcwlights: Macaw's Lights and Lamps 1.0.4
		mcwpaintings: Macaw's Paintings 1.0.3
		mcwpaths: Macaw's Paths and Pavings 1.0.0
		mcwroofs: Macaw's Roofs 2.1.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.7
		mcwwindows: Macaw's Windows 2.0.3
		medievalorigins: Medieval Origins 1.18.x-4.0.2
		minecarttweaks: Cammie's Minecart Tweaks 1.5
		minecraft: Minecraft 1.18.2
		mo_glass: Mo Glass 1.6.1-MC1.18.2
		moborigins: Mob Origins 1.8.1
		modmenu: Mod Menu 3.2.3
		morebannerfeatures: More Banner Features 1.1.3
		morevillagers: More Villagers 3.3.2
		mostructures: Mo' Structures 1.4.2+1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		mousetweaks: Mouse Tweaks 2.22
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		nbttooltip: NBT Tooltip 1.6.0
		notenoughanimations: NotEnoughAnimations 1.6.0
		onsoulfire: On Soul Fire 1.18-3
		origins: Origins 1.4.1
			apoli: Apoli 2.3.3
				additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
				calio: Calio 1.5.1
		origins-classes: Origins: Classes 1.3.0
		originsenhanced: Origins Enhanced 1.7.0
			com_jagrosh_discordipc: DiscordIPC 0.5
			com_originrealms_enhanced_networking: networking 2.2.0
		pandemonium: Requiem: Pandemonium 2.0.0-beta.8
			pandemoniumapi: Requiem: Pandemonium-API 2.0.0-beta.8
		patchouli: Patchouli 1.18.2-71.1-FABRIC
		pehkui: Pehkui 3.3.3+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		platforms: Platforms 1.2.5
		polymorph: Polymorph 0.0.21-1.18.2
			cardinal-components-block: Cardinal Components API (blocks) 4.1.4
			cardinal-components-item: Cardinal Components API (items) 4.1.4
		puzzleslib: Puzzles Lib 3.3.5
		redbits: Red Bits 1.13.3
			interference: Interference API 1.4.1
		reinfbarrel: Reinforced Barrels 2.0.1+1.18.2
			reinfcore: Reinforced Core 2.0.1+1.18.2
		replaymod: Replay Mod 1.18.2-2.6.5
		repurposed_structures: Repurposed Structures 4.1.14+1.18.2
		requiem: Requiem 2.0.0-beta.9
			automatone: Automatone 0.7.0
			blabber: Blabber 0.2.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.1.3
			cardinal-components-world: Cardinal Components API (worlds) 4.1.3
			chime: Chime 1.2.1
			fiber2cloth: Fiber To Cloth 3.1.1
			impersonate: Impersonate 2.5.0
			locki: Locki 0.7.0
			requiem-core: Requiem-Core 2.0.0-beta.9
			requiemapi: Requiem-API 2.0.0-beta.9
			satin: Satin 1.7.2
		rhino: Rhino 1802.1.14-build.209
		right-click-harvest: Right-Click-Harvest 1.2.0
		roughlyenoughitems: Roughly Enough Items 8.3.519
		roughlyenoughresources: Roughly Enough Resources 2.5.0
		shetiphiancore: ShetiPhianCore 1.2.13
			myron: Myron 1.6.3+1.18.1
		signtools: Sign Tools 1.0.0
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sspb: Sodium Shadowy Path Blocks 2.0.1
		storagecabinet: Storage Cabinet 1.4.3
		the_bumblezone: The Bumblezone - Fabric 5.1.2+1.18.2
		trashslot: TrashSlot 11.0.2
		trinkets: Trinkets 3.3.1
		twigs: Twigs 1.1.3-patch2+1.18.2
		unforgivingvoid: Unforgiving Void 3.1.5+1.18.2
		valley: ValleyCraft 2.3.1-1.18.2
		visuality: Visuality 0.4.2
			goosik-config: goosik-config 0.2.0
			tlcosmetica: Cosmetica 0.4.0
		visualoverhaul: VisualOverhaul 4.1.0
			midnightlib: MidnightLib 0.4.0
		visualworkbench: Visual Workbench 3.3.0
		voidz: VoidZ 1.0.7
		wands: Building Wands 2.5_mc1.18.2
		wildfire_gender: Wildfire's Female Gender Mod 2.9
		wthit: wthit 4.11.0
		yigd: You're in Grave Danger 1.3.7

**Comment by JieningYu** [comment]
myron

**Comment by JieningYu** [comment]
https://github.com/Fabricators-of-Create/Create/issues/452
