### ISSUE TITLE
Create doesn't support storages from blocks without block entities

### ISSUE THREAD

**Issue by MattiDragon** [Fabricators-of-Create/Create#496]
### Describe the Bug

When create is searching for storages to insert to with `CapManipulationBehaviourBase` it requires that a block entity is present. This is not necessarily the case for all transfer api implementations. 

For example in my mod, extended drawers, I have a access point block that allows access to the drawer network, but it isn't a block entity as it doesn't have top store anything, it merely looks up the cached storage instance of the network. This causes create to ignore my access point as a target for eg. funnels. 

### Reproduction Steps

1. Install extended drawers alongside create 
2. Place an access point and a drawer next to it
3. Connect a funnel to the access point
4. Notice how it doesn't insert anything

### Expected Result

That create would detect storages without a block entity, thus making funnels work on access points 

### Screenshots and Videos

https://user-images.githubusercontent.com/61198884/183242112-89434d35-737a-4d2c-a723-ae232b250709.mp4

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

Extended Drawers v1.3.2

### Additional Context

It looks like porting lib already supports this and it's just a matter of removing the check and using world and pos instead. 

Originally reported here: MattiDragon/extendeddrawers#19

**Comment by TropheusJ** [comment]
I believe this has been fully resolved, let me know if I missed anything. Access points work now.
