### ISSUE TITLE
Crash with RefinedCreativeInventory

### ISSUE THREAD

**Issue by leohu1** [Fabricators-of-Create/Create#497]
### Describe the Bug

Can't launch when using with [RefinedCreativeInventory](https://github.com/DarkKronicle/RefinedCreativeInventory) and this mod.

### Reproduction Steps

1.Add Create-1.18.2-0.5.0c-708 and RefinedCreativeInventory-0.1.0 to mods folder
2.Try to launch

### Expected Result

To launch normally

### Crash Report or Log

https://pastebin.com/YtpPVWEe

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

In Crash Log

**Comment by TropheusJ** [comment]
This isn't going to be fixable on our side. Create checks item models to determine their position in the creative menu, and RCI initializes groups too early for that. Should make an issue on the RCI repo.
