### ISSUE TITLE
Mods using KyoriPowered adventure-platform-fabric cause a NullPointerException

### ISSUE THREAD

**Issue by SajmonOriginal** [Fabricators-of-Create/Create#503]
### Describe the Bug

Create creates a Ticking Entity when Deployer is laid down, when the server is with another server utility modification what uses adventure-platform-fabric.

### Reproduction Steps

1. Create a Fabric server
2. Add a Create Mod along with some mod that uses adventure-platform-fabric, what I have observed so far are: (MiniMOTD, BetterFabricConsole, TabTPS)
3. Place a Deployer block on the server
...

### Expected Result

That the mods will coexist, this is Create's fault because of Create mod's Fake Player implementation

### Crash Report or Log

https://mclo.gs/wMH2ODd

### Operating System

Windows 11 - Client, Ubuntu - Server

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

MiniMOTD
TabTPS
BetterFabricConsole

### Additional Context

Hello, I would like to ask if there are any plans to fix compatibility with other mods that use `fake-player-api`. Server utility mods are made using the `adventure-library`

Since I've been reading through the various issues with `Create`, `MiniMOTD`, `TabTPS`, `adventure-library`.. I've read that the developers can't do anything about this because the problem is on the Create side and all issues are closed

Create creates a Ticking Entity when Deployer is laid down, when the server is with another server utility modification what uses adventure-platform-fabric.

I would really like to use server side mods like MiniMOTD etc.. together with Create.

https://github.com/jpenilla/better-fabric-console/issues/11
https://github.com/gnembon/fabric-carpet/pull/1235

#314 
#117 
#434

**Comment by TropheusJ** [comment]
there's nothing that can be done on Create's side. It needs to be fixed in the fake player API. I've brought it up to the developer again.

**Comment by ryleu** [comment]
Would you mind editing the title to include "NullPointerException" or "NPE" so that people searching for the error can find this more easily?
