### ISSUE TITLE
Default range of chassis should be 1

### ISSUE THREAD

**Issue by Zetabite** [Fabricators-of-Create/Create#506]
### Describe the Suggestion

The default range upon placing of a chassis should be 1. Why? For example, I build a draw gate with them. Issue is, if you forget to set it to the correct value, it drags many blocks with them, destroys some and makes it hard to put all of them back in place. Its also very frustrating to do so. reducing the damage it can do by default to 1, should make for a good experience for everyone, without reducing the functionality of the contraption.

**Comment by TropheusJ** [comment]
Suggestions changing behavior should be submitted to the forge repo
