### ISSUE TITLE
Smart Chute with filter set to a specific amount doesn't correctly extract items out of inventory

### ISSUE THREAD

**Issue by Zetabite** [Fabricators-of-Create/Create#507]
### Describe the Bug

When using a smart chute with a filter set to several items, like nuggets, and set to a specific amount (9) to take out of the connected inventory (double chest for example), i draws 9 nuggets of the same type out of the inventory, till it reaches a stack of a valid nugget that the inventory has less than 9 of it. If there are remaining stacks behind that less than 9 nuggets stack, that have enough nuggets to take out, the chute will stop extracting, even though valid stacks for extraction remain.

### Reproduction Steps

1.Place double chest over a smart chute
2.Set filter for smart chute for at least two items
3.Set the smart chute to extract 2 or more items of the same time out of the chest
4.Fill chest with the set items, making sure that the sum of items of the item stacks of one type of the first few filled slots are not dividable by the number set previously.
5. Observe that valid item stacks behind those undividiable item stacks cant be extracted

### Expected Result

Smart chute should skip to the next valid item stack if there is one and not stop at the undividable stack.

### Screenshots and Videos

Will send tomorrow, just needed to get this off of my chest for now.

### Operating System

Arch Linux

### Mod Version

0.4.1

### Minecraft Version

1.18.2

### Additional Context

I am sorry if this is intended behavior. I just expected it would work differently.

**Comment by Zetabite** [comment]
Will test on new release in short, and will attach screenshots if the issue remains.

**Comment by Zetabite** [comment]
![2022-08-09_03 34 47](https://user-images.githubusercontent.com/25250463/183543941-91422ef9-0255-4814-b699-a21d9df52090.png)
![2022-08-09_03 34 57](https://user-images.githubusercontent.com/25250463/183543944-5654528f-bf95-4d47-a14f-b8d2c4c0cfde.png)
![2022-08-09_03 35 20](https://user-images.githubusercontent.com/25250463/183543945-ada4e1ae-e58b-4a33-8438-666b4f087ce6.png)

**Comment by JieningYu** [comment]
Is this a Forge Create bug?

**Comment by JieningYu** [comment]
also, use 0.5.0c if possible.

**Comment by Zetabite** [comment]
Its Fabric, I have never used the forge version. Currently trying to get 0.5.0 working, but its crashing

**Comment by Zetabite** [comment]
Ok, cant seem to reproduce on 0.5.0, so seems to be fixed. I will reopen in case i have that issue again
