### ISSUE TITLE
[0.5c] Balm + Create 0.5c breaks resources

### ISSUE THREAD

**Issue by itsdinkd** [Fabricators-of-Create/Create#508]
### Describe the Bug

First I had the issue with Myron, after removing ShetiphanCore, Platforms, and Multibeds, this issue appeared which breaks resources between Balm and Create. 

https://github.com/ModdingForBlockheads/Balm/issues/33

### Reproduction Steps

1. Add Balm, Cooking for Blockheads, Farming for Blockheads, Create
2. Add Create 0.5c
3. Launch
...

### Expected Result

To load and not go into a infinite load loop

### Crash Report or Log

https://gist.github.com/itsdinkd/17d6d03de0e01e697413d0d93c80992a

### Operating System

W11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

**Comment by AlphaMode** [comment]
This has already been fixed. but a fixed hasn't been published yet

**Comment by itsdinkd** [comment]
> This has already been fixed. but a fixed hasn't been published yet

Glad to hear it! By chance, is there anything I can do on my end possibly so I can at least get the create 0.5c update out in my pack while waiting for the official fix? aside from removing the mods ofc. maybe removing any mixins?

**Comment by AlphaMode** [comment]
> > This has already been fixed. but a fixed hasn't been published yet
> 
> Glad to hear it! By chance, is there anything I can do on my end possibly so I can at least get the create 0.5c update out in my pack while waiting for the official fix? aside from removing the mods ofc. maybe removing any mixins?

https://github.com/Fabricators-of-Create/Porting-Lib/actions/runs/2821716072 you can try using this build of porting lib for now

**Comment by itsdinkd** [comment]
Will do, thanks Alpha!

**Comment by itsdinkd** [comment]
oooh.. so apparently removing Cooking for Blockheads and downgrading balm to 3.1.0 also worked.  either way, thanks! ill try the porting lib build and hope CF accepts the upload
