### ISSUE TITLE
crash when updating to Create 0.5

### ISSUE THREAD

**Issue by warior456** [Fabricators-of-Create/Create#509]
### Describe the Bug

When updating create to 0.5 the game won't load with my mods, it did load before updating.

### Reproduction Steps

1. use version 0.1.3 of this modpack: https://www.curseforge.com/minecraft/modpacks/tsm18/files
2. update Create to 0.5
3. Start the game

### Expected Result

Game starts normally with Create 0.5

### Crash Report or Log

https://pastebin.com/7jsd6XYy

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

https://pastebin.com/Ljtug1dg

**Comment by warior456** [comment]
after removing a lot of mods the only usefull error i'm left with is: "Configuration conflict: there is more than one oshi.architecture.properties file on the classpath"

**Comment by Tempest-5ky** [comment]
Seems to be some kind of conflict with Midnight Controls

**Comment by warior456** [comment]
it isnt because after removing midnight its sodium and after romoving extra mods i end up with another error wich i stated in my comment

**Comment by warior456** [comment]
this has been resolved probably because create additions updated
