### ISSUE TITLE
Create version 0.5 crash when launching minecraft

### ISSUE THREAD

**Issue by CasianStreza** [Fabricators-of-Create/Create#510]
### Describe the Bug

Previous version of create had no problems but the new one keeps crashing

### Reproduction Steps

1.Launch Minecraft 
2.Ensue create crash
3.
...

### Expected Result

Game to start without crashing with Create 0.5

### Crash Report or Log

https://pastebin.com/Ux9b7prE

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

https://pastebin.com/W87t3mn7

**Comment by Tempest-5ky** [comment]
Issue with sodium, not Create. Try deleting your sodium configs or updating sodium

**Comment by warior456** [comment]
if removing sodium doesnt work this issue is the same as mine

**Comment by TropheusJ** [comment]
I've seen this issue before but no idea what causes it. Something is initializing when it shouldn't be. Can almost guarantee it's not Create's fault, though.
