### ISSUE TITLE
If a weighted ejector has a stack size set and an item on it, it won't split a full stack of items

### ISSUE THREAD

**Issue by object-Object** [Fabricators-of-Create/Create#511]
### Describe the Bug

If a weighted ejector has a stack size set and `n` items on it, it won't take part of a stack of `64 - n + 1` items that is thrown, belted, or tunneled onto it. For example, if there are two items on an ejector and you throw a stack of 63 items at it, the ejector won't take any of the items, but it works fine if you throw 62 items.

### Reproduction Steps

1. Set the stack size on a weighted ejector to 2.
2. Throw one item onto the ejector.
3. Throw a full stack of items onto the ejector.

### Expected Result

The ejector should take enough items to meet its stack size, as it does when you throw less than a full stack of items onto it.

### Screenshots and Videos

Once the item on the ejector was removed, it started launching 2 items at a time as expected.
![2022-08-11_12 11 37](https://user-images.githubusercontent.com/37044997/184180333-c3f32cc7-bd06-4af8-9378-fcd59d796f5a.png)

### Operating System

Windows 11 Home 10.0.22000

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
Since the ejector is holding an item already, it will ignore items that land on it.
This is the exact same behavior as on Forge.
Going to say this is not a bug. Maybe a bit of an oversight, but not on us to change.

**Comment by object-Object** [comment]
Oops, my bad, should have tested it on Forge first before opening an issue here.
