### ISSUE TITLE
Contraptions sometimes disappear when the game crashes

### ISSUE THREAD

**Issue by StoneMcYT** [Fabricators-of-Create/Create#512]
Technically not a bug report / suggestion i posted this in #questions and i feel like it would be better if i posted it here for the devs as well

Drill 1:
![image](https://user-images.githubusercontent.com/67421882/184373099-7463617c-c43e-4b65-85e9-b8c4c2a2bae2.png)
Drill 2:
![image](https://user-images.githubusercontent.com/67421882/184373125-84af3fdc-42bb-4ca0-820e-2cdd2d05bbfe.png)
Drill 3:
![image](https://user-images.githubusercontent.com/67421882/184373161-df873c0f-5e1a-4547-82ba-96a3197fe365.png)

For drills 1 and 2 post server crash the glue detaches from my item vaults +  mechanical drills 
For drill 3 the drill just plain vanishes 

When i was running my server it crashed once and all players was time-ed out (no crash reported created though) and when logging on my drills had issues ( Drill 1, 2,3) and when inspecting the issue server crashed again and generated a crash report (see bellow). Does any dev/fellow person know whats happening?

Server mod list:
![image](https://user-images.githubusercontent.com/67421882/184373359-b2bee099-6af9-4c9f-948c-1941f52b4c1d.png)

My drills:
![image](https://user-images.githubusercontent.com/67421882/184373392-c74c8c4a-4b1b-4165-bda7-cadabf6fa33c.png)
4 wasnt running at the time

Crash  report:
[message.txt](https://github.com/Fabricators-of-Create/Create/files/9316991/message.txt)

**Comment by TropheusJ** [comment]
Contraptions have randomly disappeared on crashes for a while, but it's not really a priority since the crash usually is.

**Comment by TropheusJ** [comment]
Is this still an issue? Haven't encountered this in quite a while. Closing for now.
