### ISSUE TITLE
A bug occurred while extracting fluid from the Basin.

### ISSUE THREAD

**Issue by Next-Page-Vi** [Fabricators-of-Create/Create#515]
### Describe the Bug

When the fluid is extracted from the working basin, the amount of fluid consumed is inconsistent with the amount of fluid blocks generated, resulting in an increase in fluid anomalies.
![image](https://user-images.githubusercontent.com/52558763/184525736-d3904d27-ee3e-4141-b9af-9c9065831bd1.png)
![image](https://user-images.githubusercontent.com/52558763/184525743-d83c682b-6e80-4aba-b796-a67fc2453f09.png)

### Reproduction Steps

Extracting fluid from the Basin

### Expected Result

1 ml of the fluid in the working basin is consumed when a block of fluid is generated.

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

Minecraft Version: 1.18.2
create: Create 0.5.0c-708
carpet: Carpet Mod 1.4.69
lithium: Lithium 0.8.1

**Comment by adaqa** [comment]
Similar bug occured when I extract fluid pulled out on block.

**Comment by JieningYu** [comment]
Not only Basins but all the fluid containers (ex. smeltery from tconstruct mod)
