### ISSUE TITLE
unknown position and rotation NaN corruption

### ISSUE THREAD

**Issue by imreallybadatnames** [Fabricators-of-Create/Create#516]
### Describe the Bug

could not reproduce the bug ever again so the cause is unknown
1 bogey simple train, construction is simple and can be seen through contraption nbt

### Reproduction Steps

not exactly sure, but i remember just approaching a train station(pressing space) in the nether while i was in the overworld

### Expected Result

teleport to nether; no crash

### Crash Report or Log

isolated crash error: https://gist.github.com/imreallybadatnames/f91a9dca12c84ae9448f140aff3ebd32

### Operating System

ubuntu(vps host in which crash happened)

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

all mods in used modpack(custom made enormous abomination): https://gist.github.com/imreallybadatnames/b0699a5b5103e6a3dab9700640801006

### Additional Context

(badly) formatted extracted carriage contraption entity nbt(located in the nether): [snbt.txt](https://github.com/Fabricators-of-Create/Create/files/9333193/snbt.txt)

**Comment by imreallybadatnames** [comment]
even though the dimension the entity loads from is the nether, it might be in an overworld region file

**Comment by imreallybadatnames** [comment]
as i previously suspected, the contraption entity might not be stored in an entities folder region file at all

**Comment by imreallybadatnames** [comment]
its either in other region files or a separate file(very unlikely)

**Comment by imreallybadatnames** [comment]
the latter indeed was, at least the crash is present when `create_tracks.dat` is in its data folder of the world

**Comment by imreallybadatnames** [comment]
stored in [root tag]/data/Trains[0]/Carriages[0]/Entity(in the `create_tracks.dat` file)

**Comment by imreallybadatnames** [comment]
manually edited in valid values based on valid train data as temp fix

**Comment by imreallybadatnames** [comment]
temp fix worked

**Comment by imreallybadatnames** [comment]
time to attempt reproducing on the original server

**Comment by imreallybadatnames** [comment]
so far no luck; will reopen when this issue occurs again

**Comment by imreallybadatnames** [comment]
note: the carriage itself did arrive into the nether properly respecting position of track(halfway to the station) but something corrupted the main entity coords upon loading.
position is equal to position anchor coords in `EntityPositioning` tag which is stored on the same level as the `Entity` tag, figured out relative AABB values by building a carriage of same size dimensions in another world, rotation values fixed themselves.

**Comment by BillBodkin** [comment]
I have also just had this issue, station was before portal into the nether. Don't recall if i was accentually pressing the 'goto station' button causing the crash. Position of train became NaN and I wasn't able to join until I removed the corrupted train from create_tracks.nbt using NBTExplorer.

https://crashy.net/HAN4FDbAfSjvKOZS6Wh6

Create version 0.5.0e-733
