### ISSUE TITLE
Cogwheels and texures that are supposed to be connected dont look right

### ISSUE THREAD

**Issue by BentleyInu** [Fabricators-of-Create/Create#517]
### Describe the Bug

For some reason, the cogwheels and shafts dont move properly and usually moving with the idle stage stuck inside.
![2022-08-16_17 11 01](https://user-images.githubusercontent.com/111286363/184843463-093085e9-5ef0-4767-8c56-d66480fee9b2.png)

Secondly, the textures dont connect.
![2022-08-16_17 12 17](https://user-images.githubusercontent.com/111286363/184844301-7f439b3c-117d-4ecc-9c52-20f9351c793b.png)

### Reproduction Steps

1.
2.
3.
...

### Expected Result

I was expecting the large and regular cogwheels to work like normal and the textures to connect.

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

![Screenshot 2022-08-16 171456](https://user-images.githubusercontent.com/111286363/184844076-46da17b6-cdfd-4d6f-8b1b-fe2f8ea23707.png)

**Comment by JieningYu** [comment]
install [indium](https://modrinth.com/mod/indium)
