### ISSUE TITLE
The textures of fluid pipes seems wrong at a certain angle

### ISSUE THREAD

**Issue by jjjbaku** [Fabricators-of-Create/Create#519]
### Describe the Bug

Some parts of the fluid pipes disappear at a certain angle.

### Reproduction Steps

1. Open a new world in creative mode
2. Put some fluid pipes on the ground
3. Just move around then will see the result in the picture
...

### Expected Result

Some parts of the fluid pipes will disappear at certain angle.
And it will change back to normal if you move to some other position.

### Screenshots and Videos

![CNWE`E)$8OQOS 6_6M(LX9G](https://user-images.githubusercontent.com/10635514/185422686-81628829-c220-4b75-a0d7-c6d4ae60ff28.png)

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

Mod list:
 [✔️] 3dskinlayers-fabric-1.4.6-mc1.18.2
  [✔️] animal_feeding_trough-1.0.3+1.18.2
  [✔️] appleskin-fabric-mc1.18.2-2.4.0
  [✔️] architectury-4.9.83-fabric
  [✔️] artifacts-7.0.3+fabric
  [✔️] badpackets-fabric-0.1.2
  [✔️] balm-fabric-3.2.0+0
  [✔️] bclib-1.4.7
  [✔️] betterbiomeblend-1.18.2-1.3.5-fabric
  [✔️] better-end-1.1.1
  [✔️] BetterF3-1.2.5-Fabric-1.18.2
  [✔️] bettermounthud-1.1.4
  [✔️] BetterPingDisplay-Fabric-1.18.2-1.1.1
  [✔️] BetterThirdPerson-Fabric-1.18.2-1.8.1
  [✔️] blur-2.4.1
  [✔️] boatcontainer-1.2.2-1.18
  [✔️] Bookshelf-Fabric-1.18.2-13.2.21
  [✔️] can-i-mine-this-block-1.2.0
  [✔️] carrier-1.10.0 (1)
  [✔️] cem-0.7.1
  [✔️] chalk-2.0.1+1.18.2 (1)
  [✔️] chat_heads-0.6.0-fabric-1.18.1
  [✔️] CITResewn-1.1.1+1.18.2
  [✔️] cloth-api-3.2.64
  [✔️] cloth-config-6.2.62-fabric
  [✔️] comforts-fabric-1.1.2-1.18.2
  [✔️] completeconfig-lib-1.4.1
  [✔️] connectivity-fabric-1.18.2-3.3
  [✔️] continuity-2.0.0+1.18.2
  [✔️] craftingtweaks-fabric-1.18.2-14.0.3
  [✔️] create-1.18.2-0.5.0c-708
  [✔️] createaddition+1.18.2-1.1
  [✔️] createplus-1.0.0-beta4
  [✔️] CreativeCore_FABRIC_v2.6.12_mc1.18.2
  [✔️] creeperoverhaul-1.18.2-1.3.1-fabric
  [✔️] cullleaves-2.3.2
  [✔️] customizableelytra-fabric-1.5.3-1.18
  [✔️] CustomPlayerModels-Fabric-1.18-0.4.7a
  [✔️] DamageTilt-1.18-fabric-0.1.2
  [✔️] DetailArmorBar-2.6.2+1.18-fabric
  [✔️] DisableCustomWorldsAdvice-2.0
  [✔️] DraggableResourcePacks-2.0.0
  [✔️] ears-fabric-1.17-1.4.5_01
  [✔️] ecologics-fabric-1.18.2-1.7.8
  [✔️] effective-1.2.1
  [✔️] ellemes-container-library-1.4.0-beta.2+1.18.2-fabric
  [✔️] elytratrinket-fabric-3.0.0-1.18.1
  [✔️] emotecraft-for-MC1.18.2-2.1.2-fabric
  [✔️] EnchantingInfuser-v3.2.0-1.18.2-Fabric
  [✔️] EnchantmentDescriptions-Fabric-1.18.2-10.0.4
  [✔️] entity-texture-features-3.1.4-mc1.18.x
  [✔️] EquipmentCompare-1.18.2-fabric-1.2.12
  [✔️] expandedstorage-7.4.0-beta.4+1.18.2-fabric
  [✔️] fabric-api-0.58.0+1.18.2
  [✔️] fabric-language-kotlin-1.8.2+kotlin.1.7.10
  [✔️] fallingleaves-1.11.1+1.18.2
  [✔️] FallingTree-1.18.2-3.5.3
  [✔️] farmers-delight-fabric-1.18.2-1.2.0
  [✔️] feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1
  [✔️] firstperson-fabric-2.1.2-mc1.18.2
  [✔️] ForgeConfigAPIPort-v3.2.3-1.18.2-Fabric
  [✔️] geckolib-fabric-1.18-3.0.56
  [✔️] guard-villagers-fabric-1.18.2-1.0.14
  [✔️] HealthOverlay-1.18.2-6.2.4
  [✔️] i18nupdatemod-1.18-3.0.2
  [✔️] Iceberg-1.18.2-fabric-1.0.38
  [✔️] immersive_armors-1.3.5
  [✔️] indium-1.0.7+mc1.18.2
  [✔️] IngameIME-fabric-1.18.2-1.6.5
  [✔️] interactic-0.1.10+1.18
  [✔️] InventoryProfilesNext-fabric-1.18.2-1.6.3
  [✔️] iris-flywheel-compat-1.18.2-0.1.5-ALPHA
  [✔️] iris-mc1.18.2-1.2.6
  [✔️] keymap-0.6.0-beta.0+1.18.2-fabric
  [✔️] krypton-0.1.9
  [✔️] leaves-us-in-peace-1.0.5+MC1.18-1.18.2
  [✔️] lithium-fabric-mc1.18.2-0.7.10
  [✔️] map-atlases-2.0.1+1.18
  [✔️] Modern-Industrialization-1.2.2
  [✔️] modmenu-3.2.3
  [✔️] MouseTweaks-fabric-mc1.18-2.22
  [✔️] mousewheelie-1.10.2+mc1.18.2
  [✔️] naturalist-fabric-1.1.1-1.18.2
  [✔️] notenoughanimations-fabric-1.6.0-mc1.18.2
  [✔️] overweightfarming-1.18.2-1.5.3-fabric
  [✔️] phosphor-fabric-mc1.18.x-0.8.1
  [✔️] polymorph-fabric-0.0.21-1.18.2
  [✔️] PresenceFootsteps-1.5.1
  [✔️] puzzle-1.4.0-1.18
  [✔️] PuzzlesLib-v3.3.5-1.18.2-Fabric
  [✔️] raised-fabric-1.18.2-1.1.2
  [✔️] reeses_sodium_options-1.4.4+mc1.18.2-build.46
  [✔️] repurposed_structures_fabric-4.1.14+1.18.2
  [✔️] RoughlyEnoughItems-8.3.527
  [✔️] shulkerboxtooltip-3.0.10+1.18.2
  [✔️] sit-1.18.2-19
  [✔️] slight-gui-modifications-2.1.0
  [✔️] sodium-extra-0.4.6+mc1.18.2-build.46
  [✔️] sodium-fabric-mc1.18.2-0.4.1+build.15
  [✔️] soundphysics-fabric-1.18.2-1.0.6
  [✔️] stoneholm-1.4.3
  [✔️] StylishEffects-v3.1.0-1.18.2-Fabric
  [✔️] trinketofundying-fabric-2.0.2-1.18.2
  [✔️] trinkets-3.3.1
  [✔️] visuality-0.4.2
  [✔️] wthit-fabric-4.11.0
  [✔️] youre-in-grave-danger-1.3.8

**Comment by TropheusJ** [comment]
Sodium issue, fixed in dev
