### ISSUE TITLE
Trains INSANELY glitching

### ISSUE THREAD

**Issue by jona23E** [Fabricators-of-Create/Create#520]
### Describe the Bug

We hosted an origins smp on **falixnodes**, and we wanted to create a 5000 blocks long metro system. We are almost done laying the tracks but the trains are getting extremely glitchy now. When i recorded the video the server was on 6 TPS, but it happens on even 20 TPS

### Reproduction Steps

1. Create a server
2. Install create-1.18.2-0.5.0c-708, create-mc1.18.2_v0.5.0c and createplus-1.0.0-beta4
3. Make a long train track
4. Create a train 
5. Get in the train, click on the train controls and hold down w

### Expected Result

The train glitching back and forth, sometimes kicking you out of the seat or even running over you

### Screenshots and Videos

https://www.youtube.com/watch?v=cPpaxjSq8h8

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

ACOrigins-1.18-0.4.0.jar

advdebug-2.3.0.jar

AE2Things-1.1.0-beta.8.jar

AEAdditions-1.18.2-3.1.2-fabric.jar

appliedenergistics2-11.1.5.jar

architectury-4.8.81-fabric.jar

autoconfig1u-3.4.0.jar

balm-fabric-3.2.0+0.jar

BasicNetherOres-1.18.2-7.2.0-Fabric.jar

bclib-1.4.7.jar

BeaconOverhaul-1.6.0+1.18.2.jar

betteranimalsplus-1.18.2-11.0.5-fabric.jar

betterCompatibilityChecker-fabric-1.0.5.jar

beyond_earth-1.0.2.jar

BOMD-1.3.8-1.18.2.jar

Bookshelf-Fabric-1.18.2-13.2.47.jar

Botania-1.18.2-434-FABRIC.jar

cardinal-components-api-4.2.0.jar

cc-restitched-1.100.8.jar

cccbridge-1.0.0.jar

charginggadgets-fabric-1.0.2.jar

chisel-1.4.5+1.18.x.jar

cloth-api-3.2.64.jar

cloth-config-6.2.57-fabric.jar

cloth-config-6.2.62-fabric.jar

collective-fabric-1.18.2-4.36.jar

Controlling-fabric-1.18.2-9.0+21.jar

creeperoverhaul-1.18.2-1.3.1-fabric.jar

DarkPaintings-Fabric-1.18.2-10.0.3.jar

DarkUtilities-Fabric-1.18.2-10.0.5.jar

dawn-3.3.2.jar

Decorative Blocks-fabric-1.18.2-2.1.0.jar

deepmoblearning-refabricated-1.18.2.jar

elytratrinket-fabric-3.0.0-1.18.1.jar

Enhanced_Celestials-fabric-1.18.2-2.0.7.jar

EnhancedQuarries-1.18.2-1.2.1.jar

expandedstorage-7.3.12+1.18.2.jar

extra-generators-1.2.1-BETA+1.18.jar

extraalchemy-fabric-1.18.2-1.8.1.jar

extraorigins-1.18-12.jar

fabric-api-0.58.0+1.18.2.jar

fabric-experiencebugfix-1.18-18.jar

fabric-furnaces-2.1.1-1.18.2.jar

fabric-language-kotlin-1.8.2+kotlin.1.7.10.jar

fabric-language-scala-1.1.0+scala.2.13.6-fat.jar

fabrictailor-1.9.0+1.18.2.jar

farmers-delight-fabric-0.2.1.jar

flywheel-forge-1.18-0.6.4.jar

ForgeConfigAPIPort-v3.2.3-1.18.2-Fabric.jar

friendsandfoes-fabric-mc1.18.2-1.4.5.jar

GearReborn-1.18.2-0.1.14.jar

geckolib-fabric-1.18-3.0.55.jar

guard-villagers-fabric-1.18.2-1.0.14.jar

heartytrinkets-1.18.2-1.0.0.jar

Iceberg-1.18.2-fabric-1.0.38.jar

immersive_weathering-2.5.6.jar

indrev-1.14.0-BETA.jar

inmis-2.6.0-1.18.2.jar

krypton-0.1.9.jar

lazydfu-0.1.2.jar

libblockattributes-all-0.10.2.jar

LibraryFerret-Fabric-1.18.2-2.5.1.jar

lithium-fabric-mc1.18.2-0.7.10.jar

Mantle-1.18.2-1.9.DEV.927efc4.jar

MaxHealthFix-Fabric-1.18.2-5.0.1.jar

mcw-bridges-2.0.3fabric-mc1.18.2.jar

mcw-doors-1.0.6fabric-mc1.18.2.jar

mcw-fences-1.0.6fabric-mc1.18.2.jar

mcw-lights-1.0.4fabric-mc1.18.2.jar

mcw-paths-1.0.1fabric-mc1.18.2.jar

mcw-roofs-2.1.2fabric-mc1.18.2.jar

mcw-trapdoors-1.0.7fabric-mc1.18.2.jar

mcw-windows-2.0.3bfabric-mc1.18.2.jar

medieval-origins-1.18.x-4.0.2.jar

moborigins-1.8.1.jar

Modern-Dynamics-0.2.4-beta.jar

Modern-Industrialization-1.2.2.jar

more-geodes-1.4.2.jar

mythic-mounts-1.18.2-7.0.jar

netherrackmod-0.0.10-1.18.2.jar

ninjaphenix-container-library-1.3.0+1.18-fabric.jar

Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4.2.jar

Origins-1.18.2-1.4.1.jar

Origins-Classes-1.18.2-1.3.0.jar

owo-lib-0.7.2-no-cme+1.18.jar

Patchouli-1.18.2-71.1-FABRIC.jar

Pehkui-3.4.0+1.14.4-1.19.2.jar

phosphor-fabric-mc1.18.x-0.8.1.jar

PigPen-Fabric-1.18.2-8.0.1.jar

polymorph-fabric-0.0.21-1.18.2.jar

RebornCore-5.2.0.jar

reinforced-barrels-2.0.1+1.18.2.jar

rer-2.5.0.jar

right-click-harvest-1.2.0+1.18.2-fabric.jar

RoughlyEnoughItems-8.3.519.jar

Runelic-Fabric-1.18.2-11.0.1.jar

SimpleRPC-fabric-1.18.2-3.1.1.jar

simulacrum-0.5.4-beta.jar

spark-1.9.11-fabric.jar

stoneholm-1.4.3.jar

TechReborn-5.2.0.jar

TerraBlender-fabric-1.18.2-1.1.0.102.jar

theoneprobe-fabric-1.18-5.1.3 (1).jar

thonkutil-2.14.1+1.18.jar

Tinkers Construct Fabric 5.4.3.jar

torohealth-1.18-fabric-2.jar

trinkets-3.3.1.jar

twilightforest-fabric-1.18.2-4.1.268.jar

vmp-fabric-mc1.18.2-0.2.0+beta.3.85-all.jar

youre-in-grave-danger-1.3.7.jar

YungsApi-1.18.2-Fabric-2.0.8.jar

YungsBetterDungeons-1.18.2-Fabric-2.1.0.jar

YungsBetterMineshafts-1.18.2-Fabric-2.2.jar

YungsBetterStrongholds-1.18.2-Fabric-2.1.1.jar

YungsExtras-1.18.2-Fabric-2.1.0.jar

**Comment by Tempest-5ky** [comment]
Trains are ridiculously buggy for me too! Same issues you were having, as well as graphical glitches like the train appearing to be derailed when it's not, cars having 10-20 block gaps visible between them, and straight-up not detecting that they're approaching a station which means that they can't be disassembled when they're bugging out.

**Comment by SplendidAlakey** [comment]
This is probably the same issue as on Forge https://github.com/Creators-of-Create/Create/issues/3428

**Comment by AdUwUisor7623** [comment]
> This is probably the same issue as on Forge [Creators-of-Create#3428](https://github.com/Creators-of-Create/Create/issues/3428)

yep its the same thing

**Comment by XelfXendr** [comment]
I am experiencing the same bug on a modded fabric server.

The issue does seem to be linked to TPS for me.

- ~20 TPS - moving train contraptions are stable, sometimes glitching back and forth a bit but stabilizing
- ~15 TPS - moving trains stable for a bit before starting rubberbanding, which increases in intensity until calming down suddenly
- ~12-10 TPS - violent rubberbanding of moving trains

Key info:
- The issue arises regardless of track size
- Rubberbanding happens for both player-controlled and AI-controlled trains
- When rubberbanding happens, all players on the server see it, so the issue appears to be server-side
- Despite that, the train seems to settle down at the correct location, for example AI-trains settle down when they arrive to their station

Also the same issue  as Creators-of-Create#3576

**Comment by Tempest-5ky** [comment]
Can vouch that this is a server-only problem! Singleplayer trains work great :D

**Comment by AdUwUisor7623** [comment]
> Can vouch that this is a server-only problem! Singleplayer trains work great :D

it only happened to me when i turned lan on thanks

**Comment by TropheusJ** [comment]
Issues that occur on Forge as well are no longer being tracked on this repo. Please follow the respective issue on the Forge repo instead: https://github.com/Creators-of-Create/Create/issues/3428
