### ISSUE TITLE
Fluid pipes have transparent connecters when views at certain angles.

### ISSUE THREAD

**Issue by Fade-Alchemist** [Fabricators-of-Create/Create#524]
### Describe the Bug

![2022-08-21_16 42 25](https://user-images.githubusercontent.com/29619427/185812236-88b6eb4d-949f-46d7-b04b-9c59f0cf598c.png)

### Reproduction Steps

load up the pack and look at a length of fluid pipe at different angles. 

list of mods below:

[Fabric] Wildfire Female Gender Mod-2.9.jar
237.68 kB
Jun 17th, 2022 8:12PM
1.18.2-StorageCabinet-1.4.3.jar
130.41 kB
Jun 17th, 2022 8:11PM
additionalbars-3.3.1+1.18.2.jar
397.84 kB
Jun 30th, 2022 11:04PM
Adorn-3.5.0+1.18.2-fabric.jar
4.01 MB
Jun 17th, 2022 8:11PM
AdvancementPlaques-1.18.2-fabric-1.4.5.jar
183.7 kB
Jul 1st, 2022 9:45PM
adventurez-1.4.11.jar
4.76 MB
Jun 17th, 2022 8:11PM
Annotated-DI-Fabric-4.0.1+1.18.2.jar
808.9 kB
Jul 26th, 2022 4:51AM
appleskin-fabric-mc1.18.2-2.4.1.jar
892.19 kB
Aug 14th, 2022 6:36PM
architectury-4.9.83-fabric.jar
559.13 kB
Aug 14th, 2022 6:36PM
armor-stand-swap-1.0.2.jar
107.79 kB
Jun 17th, 2022 8:11PM
AttributeFix-Fabric-1.18.2-14.0.2.jar
18.46 kB
Jun 17th, 2022 8:11PM
badpackets-fabric-0.1.2.jar
24.87 kB
Jun 17th, 2022 8:11PM
balm-fabric-3.2.0+0.jar
627.22 kB
Aug 14th, 2022 6:36PM
bclib-1.4.7.jar
928.6 kB
Jun 17th, 2022 8:11PM
bedspreads-fabric-1.6.0-1.18.jar
81.83 kB
Jul 4th, 2022 4:13PM
beehive-tooltips-fabric-1.4.2.jar
28.04 kB
Jun 17th, 2022 8:11PM
besmirchment-1.18.2-12.jar
410.99 kB
Jul 27th, 2022 1:39PM
better-end-1.1.1.jar
87.03 MB
Jun 17th, 2022 8:11PM
better-nether-6.1.2.jar
20.85 MB
Jun 17th, 2022 8:11PM
bettersleeping-0.6.1+1.17.jar
475.51 kB
Aug 14th, 2022 6:17PM
bewitchment-1.18-23.jar
5.2 MB
Jul 10th, 2022 9:41PM
blasting.sand-1.18.2-2.jar
1.43 MB
Jun 17th, 2022 8:11PM
boatcontainer-1.2.2-1.18.jar
68.14 kB
Jul 21st, 2022 12:56PM
Bookshelf-Fabric-1.18.2-13.2.47.jar
278.66 kB
Aug 14th, 2022 6:36PM
Botania-1.18.2-435-FABRIC.jar
11.33 MB
about 3 hours ago
BuildingWands_mc1.18.2-2.6.3_release-fabric.jar
275.19 kB
Aug 14th, 2022 5:59PM
cammies-minecart-tweaks-1.5.jar
1023.93 kB
Jun 17th, 2022 8:11PM
camsbackpacks-2.11.jar
186.12 kB
Jun 17th, 2022 8:11PM
chipped-1.2.jar
6.46 MB
Jun 17th, 2022 8:11PM
chisel-1.4.5+1.18.x.jar
5.57 MB
Jun 17th, 2022 8:11PM
ChiselsBits-fabric-1.18.2-1.2.113.jar
1.92 MB
Jul 14th, 2022 5:40PM
cloth-config-6.2.57-fabric.jar
1.07 MB
Jul 22nd, 2022 1:38AM
Clumps-fabric-1.18.2-8.0.0+15.jar
17.99 kB
Aug 14th, 2022 5:59PM
comforts-fabric-1.1.2-1.18.2.jar
327.17 kB
Jun 17th, 2022 8:11PM
connectiblechains-2.1.1+1.18.2.jar
4.7 MB
Jun 17th, 2022 8:11PM
continuity-2.0.1+1.18.2.jar
1.08 MB
Aug 14th, 2022 6:17PM
Controlling-fabric-1.18.2-9.0+21.jar
116.15 kB
Jul 10th, 2022 9:41PM
create-1.18.2-0.5.0c-708.jar
14.89 MB
Aug 14th, 2022 3:17PM
createplus-1.0.0-beta4.jar
888.98 kB
Jun 18th, 2022 12:03AM
culinaire-2.4.0.jar
264.11 kB
Jun 17th, 2022 8:11PM
dankstorage-1.18.2-3.7.1.jar
193.12 kB
Jul 27th, 2022 1:39PM
darkrites-1.18.2-1.jar
120.04 kB
Jun 19th, 2022 8:56PM
dawn-3.3.2.jar
1.1 MB
Jun 30th, 2022 11:04PM
Decorative Blocks-fabric-1.18.2-2.1.1.jar
450.95 kB
Aug 14th, 2022 6:17PM
deepslatecutting-1.18.2-1.3.4.jar
155.21 kB
Jun 17th, 2022 8:11PM
dummmmmmy-1.18-1.5.2.jar
95.86 kB
Jun 17th, 2022 8:11PM
EnchantmentDescriptions-Fabric-1.18.2-10.0.8.jar
48.67 kB
about 3 hours ago
Enhanced_Celestials-fabric-1.18.2-2.0.7.jar
1.42 MB
Jun 17th, 2022 8:11PM
extraalchemy-fabric-1.18.2-1.8.1.jar
1.12 MB
Jun 17th, 2022 8:11PM
extraorigins-1.18-12.jar
113.43 kB
Jul 16th, 2022 8:27PM
fabric-api-0.58.0+1.18.2.jar
1.38 MB
Jul 27th, 2022 1:39PM
fabric-experiencebugfix-1.18-18.jar
78.13 kB
Jun 17th, 2022 8:11PM
fabric-language-kotlin-1.8.2+kotlin.1.7.10.jar
6.03 MB
Jul 21st, 2022 12:56PM
farmers-delight-fabric-1.18.2-1.2.1.jar
2.44 MB
about 2 hours ago
feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1.jar
15.69 kB
Jun 17th, 2022 8:11PM
Fireplace-Lib-Fabric-7.0.2+1.18.2.jar
1.1 MB
Jul 26th, 2022 4:46AM
ForgeConfigAPIPort-v3.2.4-1.18.2-Fabric.jar
323.6 kB
about 2 hours ago
genesis-1.18.2-1.0.1.jar
64.42 kB
Jun 17th, 2022 8:11PM
guard-villagers-fabric-1.18.2-1.0.14.jar
239.51 kB
Jun 17th, 2022 8:11PM
Iceberg-1.18.2-fabric-1.0.38.jar
76.34 kB
Jun 17th, 2022 8:11PM
indium-1.0.7+mc1.18.2.jar
115.96 kB
Aug 14th, 2022 6:36PM
InventorySorter-1.8.8-1.18.jar
203.83 kB
Jun 17th, 2022 8:11PM
IronChests-1.7.4.jar
462.72 kB
Jul 21st, 2022 12:56PM
kubejs-create-fabric-1802.2.2-build.28.jar
23.77 kB
Aug 14th, 2022 6:36PM
kubejs-fabric-1802.5.4-build.533.jar
982.94 kB
Aug 14th, 2022 6:36PM
light-overlay-6.0.5.jar
60.74 kB
Jun 17th, 2022 8:11PM
litematica-fabric-1.18.2-0.11.3.jar
875.7 kB
Jun 17th, 2022 8:11PM
lithium-fabric-mc1.18.2-0.7.10.jar
455.27 kB
Jun 17th, 2022 8:11PM
ljcia-1.0.0.jar
16.16 kB
Jun 17th, 2022 8:11PM
malilib-fabric-1.18.2-0.12.1.jar
483.91 kB
Jun 17th, 2022 8:11PM
marketcrates-fabric-1.4.1.jar
573.13 kB
Jun 17th, 2022 8:11PM
mcda-2.0.7.jar
814.43 kB
Jul 10th, 2022 9:41PM
mcdar-1.4.8.jar
260.02 kB
Jun 17th, 2022 8:11PM
mcdw-4.4.1.jar
1.11 MB
Aug 14th, 2022 5:59PM
mcw-bridges-2.0.3fabric-mc1.18.2.jar
746.39 kB
Jun 18th, 2022 12:03AM
mcw-doors-1.0.7fabric-mc1.18.2.jar
881.35 kB
Aug 14th, 2022 5:42PM
mcw-fences-1.0.6fabric-mc1.18.2.jar
294.23 kB
Aug 14th, 2022 5:42PM
mcw-lights-1.0.4fabric-mc1.18.2.jar
259.36 kB
Aug 14th, 2022 5:42PM
mcw-paintings-1.0.4fabric-mc1.18.2.jar
46.85 kB
Aug 9th, 2022 1:19AM
mcw-paths-1.0.1fabric-mc1.18.2.jar
193.98 kB
Aug 9th, 2022 1:19AM
mcw-roofs-2.1.2fabric-mc1.18.2.jar
1.81 MB
Jun 18th, 2022 12:03AM
mcw-trapdoors-1.0.7fabric-mc1.18.2.jar
452.58 kB
Aug 14th, 2022 5:42PM
mcw-windows-2.0.3bfabric-mc1.18.2.jar
848.4 kB
Jun 18th, 2022 12:03AM
medieval-origins-1.18.x-4.0.2.jar
410.96 kB
Jun 17th, 2022 8:11PM
Mo-Glass-1.6.1-MC1.18.2.jar
570.45 kB
Jun 17th, 2022 8:11PM
moborigins-1.8.1.jar
169.98 kB
Jun 17th, 2022 8:11PM
modmenu-3.2.2.jar
292.9 kB
Jun 17th, 2022 8:11PM
morebannerfeatures-1.1.3-1.18.jar
221.74 kB
Jun 17th, 2022 8:11PM
morevillagers-fabric-1.18.2-3.3.2.jar
1.19 MB
Jun 22nd, 2022 2:38PM
mostructures-1.4.2+1.18.2.jar
683.72 kB
Jun 17th, 2022 8:11PM
MouseTweaks-fabric-mc1.18-2.22.jar
75.83 kB
Jun 17th, 2022 8:12PM
NaturesCompass-1.18.2-2.0.3-fabric.jar
207.77 kB
Jun 17th, 2022 8:12PM
nbttooltip-1.6.0.jar
986.38 kB
Jun 17th, 2022 8:12PM
notenoughanimations-fabric-1.6.0-mc1.18.2.jar
386.77 kB
Jun 17th, 2022 8:12PM
onsoulfire-1.18-3.jar
105.91 kB
Jun 17th, 2022 8:12PM
Origins-1.18.2-1.4.1.jar
2.02 MB
Jun 17th, 2022 8:12PM
Origins-Classes-1.18.2-1.3.0.jar
162.58 kB
Jun 17th, 2022 8:12PM
origins-enhanced-fabric-1.7.0.jar
699.03 kB
Jun 17th, 2022 8:12PM
Patchouli-1.18.2-71.1-FABRIC.jar
826.15 kB
Jun 28th, 2022 1:12AM
Pehkui-3.4.0+1.14.4-1.19.2.jar
380.31 kB
Aug 14th, 2022 6:36PM
platforms-fabric-1.18-1.2.5.jar
533.47 kB
Jul 22nd, 2022 1:38AM
polymorph-fabric-0.0.21-1.18.2.jar
322.58 kB
Jun 17th, 2022 8:12PM
PuzzlesLib-v3.3.5-1.18.2-Fabric.jar
394.4 kB
Jun 17th, 2022 8:12PM
red-bits-1.13.3.jar
1.15 MB
Jun 17th, 2022 8:12PM
reinforced-barrels-2.0.1+1.18.2.jar
80.99 kB
Jun 17th, 2022 8:12PM
repurposed_structures_fabric-4.1.14+1.18.2.jar
6.17 MB
Jun 17th, 2022 8:12PM
requiem-2.0.0-beta.9.jar
2.73 MB
Jun 30th, 2022 8:49PM
rer-2.5.0.jar
79.65 kB
Jun 17th, 2022 8:12PM
rhino-fabric-1802.1.14-build.225.jar
1.03 MB
about 3 hours ago
right-click-harvest-1.2.0+1.18.2-fabric.jar
25.37 kB
Jun 17th, 2022 8:12PM
RoughlyEnoughItems-8.3.529.jar
1.98 MB
about 3 hours ago
shetiphiancore-fabric-1.18-1.2.13.jar
434.79 kB
Aug 14th, 2022 3:17PM
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
1.26 MB
Jun 17th, 2022 8:12PM
sodium-shadowy-path-blocks-2.0.1.jar
50.38 kB
Jun 17th, 2022 8:12PM
the_bumblezone_fabric-5.1.2+1.18.2.jar
4.88 MB
Jun 30th, 2022 8:47PM
trashslot-fabric-1.18.1-11.0.2.jar
115.19 kB
Jun 17th, 2022 8:12PM
trinkets-3.3.1.jar
225.15 kB
Jun 17th, 2022 8:12PM
twigs-fabric-1.1.3-patch2+1.18.2.jar
701.66 kB
Jun 28th, 2022 1:12AM
Unforgiving-Void-Fabric-3.1.5+1.18.2.jar
109.25 kB
Jul 26th, 2022 4:51AM
valley-craft-2.3.1-1.18.2.jar
4.51 MB
Jun 17th, 2022 8:12PM
visuality-0.4.2.jar
169.28 kB
Jun 17th, 2022 8:12PM
visualoverhaul-4.1.0.jar
187.8 kB
Jun 17th, 2022 8:12PM
VisualWorkbench-v3.3.0-1.18.2-Fabric.jar
64.22 kB
Jun 17th, 2022 8:12PM
voidz-1.0.7.jar
65.87 kB
Jun 17th, 2022 8:12PM
wthit-fabric-4.13.1.jar
392.37 kB
about 3 hours ago
youre-in-grave-danger-1.3.8.jar

### Expected Result

connected textures with no transparent segments 

### Screenshots and Videos

![2022-08-21_16 42 25](https://user-images.githubusercontent.com/29619427/185812259-7abd0cb9-2440-4529-9d0e-0be039d085da.png)
![2022-08-21_16 48 41](https://user-images.githubusercontent.com/29619427/185812309-bfade636-ca09-4a90-841e-28cd9552ab2d.png)
![2022-08-21_16 49 31](https://user-images.githubusercontent.com/29619427/185812310-319ae4c5-a114-4f48-9c6f-0e8efc6ed9ed.png)

### Crash Report or Log

no crash

### Operating System

windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

No crash

### Additional Context

n.a

**Comment by TropheusJ** [comment]
sodium issue, fixed in dev
