### ISSUE TITLE
Not compatible with Vulkan 

### ISSUE THREAD

**Issue by DanMoney** [Fabricators-of-Create/Create#526]
### Describe the Bug

Vulkan is optimization mod, better then sodium, and it's incompatible with create 
mod: https://github.com/xCollateral/VulkanMod

### Reproduction Steps

1. lunch the game
2. crush with exit code 1

### Expected Result

Game started successfully 

### Crash Report or Log

https://gist.github.com/DanMoney/b8e12b15180ab02356ce37439de9dd18#file-latest-log

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

VulkanMod_1.18.2-0.1.6     Fabric-Api-0.58.0+1.18.2     Create-1.18.2-0.5.0c-708

**Comment by JieningYu** [comment]
Flywheel is using openGL

**Comment by AlphaMode** [comment]
This issue should be moved to flywheel
