### ISSUE TITLE
Textures of vertical/horizontal framed glasses

### ISSUE THREAD

**Issue by RedCons** [Fabricators-of-Create/Create#527]
### Describe the Bug

Hello, something is not right with textures of the framed glasses
in hand and inventory the looking like they supposed to be
but when i putting it the block have other texture

### Reproduction Steps

1.
2.
3.
...

### Expected Result

![2022-08-23_22 51 06](https://user-images.githubusercontent.com/109233710/186253106-11e570f3-e8c4-4bfe-9ac4-756f4894ae3a.png)

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
intended, the item is different so you can tell the difference
![image](https://user-images.githubusercontent.com/60247969/186982929-8a17f676-4112-482e-be65-b76964172167.png)
