### ISSUE TITLE
Full item vaults cause lag when trying to input items

### ISSUE THREAD

**Issue by JensenJ** [Fabricators-of-Create/Create#528]
### Describe the Bug

Hi,
Built an automatic farm using create and was putting the items into item vaults. Everything was working well until the item vault filled up at which point the TPS of the server dropped significantly. As soon as I disconnected the belt from power, the performance increased. I imagine the funnel attached to the belt is searching the vault for a space to put the items every server tick or something. This issue seems to get worse the bigger the item vault (more slots to search I guess). 

For anyone else having this issue, a workaround until this is resolved is to disable the input belt when the item vault is full using a stockpile switch and clutch.

### Reproduction Steps

1. Place down item vault and fill it up with items
2. Try to fill put items into vault using funnels and belts
3. Do a spark profile or observable profile to see performance drop. 

### Expected Result

The item vault should not cause significant lag if it is full and items are being input.

### Screenshots and Videos

An Observable profile showing a full item vault with items attempting to be put into it. Each item vault block uses around 100 microseconds a tick, which is significant compared to other blocks.

![2022-08-25_00 50 04](https://user-images.githubusercontent.com/13812018/186544599-20514d55-abc2-4899-9093-d23878c45019.png)

### Crash Report or Log

Spark profile: https://spark.lucko.me/8HZIhJmglT

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

3dskinlayers-fabric-1.4.6-mc1.18.2.jar
AdditionalAdditions-4.0.5.jar
AdditionalBanners-Fabric-1.18.2-7.0.6.jar
additionalbars-3.3.1+1.18.2.jar
AdditionalStructures-1.18.2-(v.3.0.3).jar
Adorn-3.5.0+1.18.2-fabric.jar
advancements-enlarger-0.2.4.jar
advdebug-2.3.0.jar
adventurez-1.4.11.jar
another_furniture-fabric-1.1.3-1.18.2.jar
antighost-1.18.2-fabric0.47.10-1.1.4.jar
appleskin-fabric-mc1.18.2-2.4.0.jar
appliedenergistics2-11.1.5.jar
architects-palette-fabric-2.2.jar
architectury-4.4.56.jar
architectury-4.7.78-fabric.jar
AttributeFix-Fabric-1.18.2-14.0.2.jar
autoconfig1u-3.4.0.jar
auudio_fabric_1.0.3_MC_1.18-1.18.2.jar
axolotl-item-fix-1.1.3.jar
badpackets-fabric-0.1.2.jar
balm-fabric-3.1.0+0.jar
BasicShields-1.3.1-1.18.2.jar
bclib-1.4.7.jar
BeaconOverhaul-1.6.0+1.18.2.jar
betteranimalsplus-1.18.2-11.0.5-fabric.jar
betterbiomeblend-1.18.2-1.3.5-fabric.jar
BetterF3-1.2.5-Fabric-1.18.2.jar
BetterThirdPerson-Fabric-1.18.2-1.8.1.jar
bewitchment-1.18-23.jar
biomeinfo-1.18.2-10.jar
biomemakeover-FABRIC-1.18.2-1.4.29.jar
blockus-2.4.7+1.18.2.jar
blur-2.4.1.jar
BOMD-1.3.8-1.18.2.jar
Bookshelf-Fabric-1.18.2-13.2.47.jar
capybara-1.18.2-1.0.6.jar
cardinal-components-api-4.2.0.jar
charm-fabric-1.18.2-4.1.2.jar
charmonium-fabric-1.18.2-4.1.0.jar
chipped-1.2.jar
cleancut-1.18.2-5.0-fabric.jar
clienttweaks-fabric-1.18.1-7.1.0.jar
cloth-config-6.2.57-fabric.jar
cloth-config-6.2.62-fabric.jar
Clumps-fabric-1.18.2-8.0.0+15.jar
comforts-fabric-1.1.2-1.18.2.jar
connectiblechains-2.1.1+1.18.2.jar
continuity-2.0.0+1.18.2.jar
Controlling-fabric-1.18.2-9.0+21.jar
CosmeticArmor-1.18.2-1.3.1.jar
CraftTweaker-fabric-1.18.2-9.1.177.jar
crawl-0.10.6.jar
create-1.18.2-0.5.0c-708.jar
createaddition+1.18.2-1.18.2-20220813a.jar
creeperoverhaul-1.18.2-1.3.1-fabric.jar
cullleaves-2.3.2.jar
DarkPaintings-Fabric-1.18.2-10.0.3.jar
dashloader-4.0.0.jar
dawn-3.3.2.jar
Decorative Blocks-fabric-1.18.2-2.1.0.jar
deepslatecutting-1.18.2-1.3.4.jar
dragonfight-fabric-1.18.2-2.5.jar
dragonloot-1.1.0.jar
dual_riders-1.18.2-1.1.1-fabric.jar
duckling-1.0.5-fabric.jar
dustrial-decor-fabric-0.5.jar
dynamic-fps-2.1.0.jar
EasyMagic-v3.3.0-1.18.2-Fabric.jar
EasyShulkerBoxes-v3.1.1-1.18.2-Fabric.jar
eating-animation-1.8.jar
ecologics-fabric-1.18.2-1.7.6.jar
elytratrinket-fabric-3.0.0-1.18.1.jar
enchantment-lore-1.2.6-1+MC1.18-1.18.2.jar
EnchantmentDescriptions-Fabric-1.18.2-10.0.4.jar
entityculling-fabric-mc1.18-1.5.1.jar
expandeddelight-0.1.9.jar
extended-armor-bars-1.2.1.jar
extendedclouds-1.1.1-fabric.jar
extraalchemy-fabric-1.18.2-1.8.1.jar
fabric-api-0.58.0+1.18.2.jar
fabric-experiencebugfix-1.18-18.jar
fabric-language-kotlin-1.8.2+kotlin.1.7.10.jar
FabricShieldLib-1.5.3-1.18.jar
FallingTree-1.18.2-3.5.3.jar
farmers-delight-fabric-0.2.1.jar
farmersknives-1.3.1.jar
farsight.fabric-1.18-1.9.jar
FauxCustomEntityData-fabric-1.18.2-1.0.4.jar
feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1.jar
ferritecore-4.2.1-fabric.jar
flytre_lib-1.18.2-1.8.1-fabric.jar
ForgeConfigAPIPort-v3.2.3-1.18.2-Fabric.jar
forgottenrecipes-fabric-1.18.1-1.0.0.jar
FriendlyFire-Fabric-1.18.2-11.0.2.jar
friendsandfoes-fabric-mc1.18.2-1.4.5.jar
gate-of-babylon-1.7.0-1.18.2.jar
geckolib-fabric-1.18-3.0.52.jar
go-fish-1.5.0-1.18.2.jar
goblin-traders-1.5.1.jar
Highlighter-1.18-fabric-1.1.2.jar
Iceberg-1.18.2-fabric-1.0.38.jar
impaled-1.1.3.jar
indium-1.0.7+mc1.18.2.jar
infusion-table-mod-1.1.0.jar
IngredientExtensionAPI-fabric-1.18.2-2.0.6.jar
inmis-2.6.0-1.18.2.jar
InventoryHUD-fabric-[1.18] -3.4.2.jar
iris-mc1.18.2-1.2.6.jar
kleeslabs-fabric-1.18.2-11.1.1.jar
konkrete_fabric_1.5.0_MC_1.18-1.18.2.jar
kubejs-create-fabric-1802.2.2-build.28.jar
kubejs-fabric-1802.5.4-build.533.jar
lambdynamiclights-2.1.0+1.17.jar
lazydfu-0.1.2.jar
lilwings-fabric-1.2.0.jar
lithium-fabric-mc1.18.2-0.7.10.jar
lovely_snails-1.0.4+1.18.jar
macawsbridgesbyg-fabric-1.18.2-1.2.jar
macawsroofsbyg-fabric-1.18.2-1.0.jar
MagnumTorch-v3.1.2-1.18.2-Fabric.jar
mcw-bridges-2.0.3fabric-mc1.18.2.jar
mcw-doors-1.0.6fabric-mc1.18.2.jar
mcw-fences-1.0.6fabric-mc1.18.2.jar
mcw-lights-1.0.4fabric-mc1.18.2.jar
mcw-paintings-1.0.3fabric-mc1.18.2.jar
mcw-paths-1.0.0fabric-mc1.18.2.jar
mcw-roofs-2.1.2fabric-mc1.18.2.jar
mcw-trapdoors-1.0.7fabric-mc1.18.2.jar
mcw-windows-2.0.3bfabric-mc1.18.2.jar
midnightlib-0.4.4.jar
Mo-Glass-1.6.1-MC1.18.2.jar
modmenu-3.2.3.jar
more-axolotls-1.0.2-1.18.jar
more-totems-mod-2.10.0.jar
MoreAchievements-1.18.1-1.0.8.jar
morevillagers-fabric-1.18.2-3.3.2.jar
mostructures-1.4.2+1.18.2.jar
MouseTweaks-fabric-mc1.18-2.22.jar
NaturesCompass-1.18.2-2.0.3-fabric.jar
nears-fabric-1.18-1.1.8.jar
notenoughanimations-fabric-1.6.0-mc1.18.2.jar
observable-2.2.3-fabric.jar
Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4.2.jar
onsoulfire-1.18-3.jar
oxidized-1.6.4.jar
Paintings-fabric-1.18.2-9.1.2.1.jar
Patchouli-1.18.2-71.1-FABRIC.jar
Pehkui-3.3.3+1.14.4-1.19.1.jar
PickUpNotifier-v3.2.0-1.18.2-Fabric.jar
pigsteel-fabric-1.18.2-1.7.1.jar
plushie-mod-1.2-1.18.2.jar
polymorph-fabric-0.0.21-1.18.2.jar
post-materia-1.0.0-1.18.2.jar
probablychests-0.5.3-1.18.2.jar
puzzle-1.4.0-1.18.jar
PuzzlesLib-v3.3.5-1.18.2-Fabric.jar
quartz-elevator-2.1.2+1.18.2.jar
reeses_sodium_options-1.4.4+mc1.18.2-build.46.jar
repurposed_structures_fabric-4.1.14+1.18.2.jar
rhino-fabric-1802.1.14-build.225.jar
right-click-harvest-1.2.0+1.18.2-fabric.jar
RoughlyEnoughItems-8.3.519.jar
simplechunkloader-1.0.1-1.18.2.jar
sit-1.18.2-19.jar
skin-swapper-fabric-3.1.1.jar
smoothboot-fabric-1.18.2-1.7.0.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
spark-1.9.11-fabric.jar
spirit-fabric-1.18.2-2.1.5.jar
sprout-1.3.1-fabric.jar
starlight-1.0.2+fabric.89b8d9f.jar.disabled
stoneholm-1.4.3.jar
styledplayerlist-2.1.3+1.18.jar
TerraBlender-fabric-1.18.2-1.1.0.102.jar
The_Graveyard_1.9_(FABRIC)_for_1.18.2.jar
thonkutil-2.14.1+1.18.jar
TipTheScales-fabric-1.18.2-5.0.6.jar
tooltipfix-1.0.4-1.18.jar
Towns-and-Towers-1.18.2-1.6.0.jar
TradingPost-v3.2.0-1.18.2-Fabric.jar
transparent-4.1.0+1.18.2-fabric.jar
TransparentCosmetics-1.4.0.jar
trinketofundying-fabric-2.0.2-1.18.2.jar
trinkets-3.3.1.jar
twigs-fabric-1.1.3-patch2+1.18.2.jar
UniversalBoneMeal-v3.0.5-1.18.2-Fabric.jar
universal_ores-1.3.1.jar
vanilla_degus-1.18.2-v1.3.0-fabric.jar
villager-hats-1.4.0.jar
villagernames-1.18.2-4.0.4.jar
VisualWorkbench-v3.3.0-1.18.2-Fabric.jar
voidtotem-fabric-1.18.2-1.3.1.jar
voidz-1.0.7.jar
wanderingcollector-1.1.2+mc1.18.2.jar
windchimes-1.2.0.jar
wolves-with-armor-1.7.1-1.18.2.jar
worldedit-mod-7.2.10.jar
wraith-waystones-2.5.5+mc1.18.2.jar
wthit-fabric-4.11.0.jar
XaerosWorldMap_1.26.1_Fabric_1.18.2.jar
Xaeros_Minimap_FP22.12.0_Fabric_1.18.2.jar
xlpackets-2.1-1.17.1.jar
youre-in-grave-danger-1.3.7.jar
YungsApi-1.18.2-Fabric-2.0.8.jar
YungsBetterDesertTemples-1.18.2-Fabric-1.3.jar
YungsBetterDungeons-1.18.2-Fabric-2.1.0.jar
YungsBetterMineshafts-1.18.2-Fabric-2.2.jar
YungsBetterStrongholds-1.18.2-Fabric-2.1.1.jar
YungsBetterWitchHuts-1.18.2-Fabric-1.0.1.jar
YungsBridges-1.18.2-Fabric-2.1.0.jar
YungsExtras-1.18.2-Fabric-2.1.0.jar
Zoomify-1.6.0.jar

**Comment by TropheusJ** [comment]
could you test [this build](https://github.com/Fabricators-of-Create/Create/actions/runs/2950338012)?

**Comment by JensenJ** [comment]
Yes, this seems to have fixed the issue, thank you very much.
