### ISSUE TITLE
Game stuck at "Loading Terrain"

### ISSUE THREAD

**Issue by folke13** [Fabricators-of-Create/Create#530]
### Describe the Bug

Game stuck at "Loading Terrain"

### Reproduction Steps

1. Install create-1.18.2-0.5.0c-708 and fabric-api-0.58.0
2. Run it with fabric-loader-0.14.9
3. Try to join a world or create a new one
...

### Expected Result

Game get's stuck on "Loading Terrain"

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/8281830/186931232-068da622-2f58-4ad9-97b7-03da99def44b.png)

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

**Comment by folke13** [comment]
Note: No crash report was created from what I could find.

**Comment by TropheusJ** [comment]
send your latest.log

**Comment by folke13** [comment]
[latest.zip](https://github.com/Fabricators-of-Create/Create/files/9436268/latest.zip)

**Comment by TropheusJ** [comment]
log is completely full of GL errors
```
[16:51:58] [Render thread/ERROR]: ########## GL ERROR ##########
[16:51:58] [Render thread/ERROR]: @ Render
[16:51:58] [Render thread/ERROR]: 65540: Invalid time inf
```
Remove Create and get into the game and send an F3 screenshot.

**Comment by folke13** [comment]
Managed to find a solution. Deleting options.txt made it work!
