### ISSUE TITLE
Server wont start on latest build

### ISSUE THREAD

**Issue by BluePineappleCake** [Fabricators-of-Create/Create#535]
### Describe the Bug

I wanted to try the newest build(0.5d) on our server but sadly it wont get past
launching the server.
It works fine on the last stable Create 0.5c build.

### Reproduction Steps

1. Replace old Create 0.5c with 0.5d dev
2. Start server

### Expected Result

Server starts and is usable

### Crash Report or Log

https://pastebin.com/RXTfhcVA

### Operating System

Ubuntu 22.04

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

### Other Mods

	- ad_astra 1.0.0
	- additionaladditions 4.0.5
	- additionalentityattributes 1.0.0+1.18.2 via spectrum
	- adorn 3.5.0+1.18.2
	- advanced_runtime_resource_pack 0.5.7
	- advancednetherite 1.5.1-1.18.2
	- advdebug 2.3.0
	- adventurez 1.4.11
	- ae2 11.1.5
	- ae2additions 3.1.2-fabric
	- ae2things 1.1.0-beta.8
	- ae2wtlib 11.1.4
	- animal_feeding_trough 1.0.3+1.18.2
	- appbot 1.3.1
	- appleskin 2.4.1+mc1.18.2
	- aqupdcaracal 1.18.2-1.3.8
	- aqupdgrizzly 1.18-1.3
	- arcanus 1.29
	- architects_palette 2.2
	- architectury 4.9.83
	- artifacts 7.0.3+fabric
	- attributefix 14.0.2
	- auto-workstations 1.0-SNAPSHOT-14
	- autoconfig1u 3.4.0
	- automobility 0.2.1+1.18.2
	- badpackets 0.1.2
	- balm-fabric 3.2.0+0
	- bannerpp 2.0.6-teb.1+mc.1.18.2 via spectrum
	- bcc fabric-1.0.5
	- bclib 1.4.7
	- beaconoverhaul 1.6.0+1.18.2
	- bedbenefits 6.0.2
	- better_bad_omen 1.3.0
	- betterdeserttemples 1.18.2-Fabric-1.3
	- betterdungeons 1.18.2-Fabric-2.1.0
	- betterend 1.1.1
	- bettermineshafts 1.18.2-Fabric-2.2
	- betternether 6.1.2
	- betterstrongholds 1.18.2-Fabric-2.1.1
	- betterwitchhuts 1.18.2-Fabric-1.0.1
	- bewitchment 1.18-23
	- bhmenu 1.17.1-1.18.2-1.3
	- biomemakeover 1.18.2-1.4.29
	- blast 1.9.1
	- blockus 2.4.8+1.18.2
	- blue_endless_jankson 1.2.1 via kyrptconfig
	- bookshelf 13.2.47
	- bosses_of_mass_destruction 1.3.8-1.18.2
	- botania 1.18.2-435-FABRIC
	- bowinfinityfix rv11
	- buildinggadgets 1.0.22
	- byg 1.4
	- cacao 1.2
	- campanion 3.0.3
	- capybara 1.0.6
	- cardinal-components 4.2.0
	- cardinal-components-base 4.2.0 via cardinal-components
	- cardinal-components-block 4.2.0 via cardinal-components
	- cardinal-components-chunk 4.2.0 via cardinal-components
	- cardinal-components-entity 4.2.0 via cardinal-components
	- cardinal-components-item 4.2.0 via cardinal-components
	- cardinal-components-level 4.2.0 via cardinal-components
	- cardinal-components-scoreboard 4.2.0 via cardinal-components
	- cardinal-components-world 4.2.0 via cardinal-components
	- carrier 1.10.0
	- catwalksinc 1.3.0
	- chalk 2.0.1+1.18.2
	- chassis 1.1.0
	- chipped 1.2
	- chisel 1.4.5
	- chiselsandbits 1.2.113
	- chord 1.8.0+1.18.2-fabric via wilderworld
	- chunky 1.2.164
	- clienttweaks 7.1.0
	- cloth-api 3.2.64
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-client-events-v0 3.2.64 via cloth-api
	- cloth-common-events-v1 3.2.64 via cloth-api
	- cloth-config 6.2.62
	- cloth-config-lite 2.0.6 via omega-config-gui
	- cloth-datagen-api-v1 3.2.64 via cloth-api
	- cloth-utils-v1 3.2.64 via cloth-api
	- clumps 8.0.0+15
	- com_electronwill_night-config_core 3.6.5 via couplings
	- com_electronwill_night-config_toml 3.6.5 via couplings
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_github_llamalad7_mixinextras 0.0.11 via porting_lib
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_moandjiezana_toml_toml4j 0.7.2 via deepslatecutting
	- com_typesafe_config 1.4.1 via croptopia
	- compactmachines ${version}
	- companion 2.0.1
	- compressor 0.2.0
	- computercraft 1.100.8
	- conjuring 1.0.22+1.18
	- cookingforblockheads 12.1.0
	- couplings 1.8.0+1.18.2
	- coxinhautilities 1.4.2+1.18.2
	- craftingtweaks 14.0.3
	- crawl 0.10.6
	- create 0.5.0c-725
	- createaddition ${version}
	- createplus 1.0
	- creeperoverhaul 1.3.1
	- croptopia 2.0.5
	- croptosis 1.5.0
	- crowdin-translate 1.4+1.18.2 via compressor
	- cyti 1.0.5
	- dankstorage 1.18.2-3.7.1
	- dark-enchanting 1.0.0+1.18.2
	- darkpaintings 10.0.3
	- darkutils 10.0.5
	- dawn 3.3.2
	- deathlog 0.2.9+1.18
	- decorative_blocks 2.1.1
	- deepslatecutting 1.3.4
	- defaultoptions 14.1.1
	- display_case 1.0.0
	- dml-refabricated 1.18.2
	- dml-refabricated-base 1.18.2 via dml-refabricated
	- dml-refabricated-events 1.18.2 via dml-refabricated
	- dml-refabricated-modular-armor 1.18.2 via dml-refabricated
	- dml-refabricated-rei 1.18.2 via dml-refabricated
	- dmlsimulacrum 0.5.4-beta
	- doodads 0.1.2-1.18.2
	- dragonloot 1.1.0
	- dripstone_fluid_lib 1.2.0 via milk
	- dual_riders 1.1.1
	- duckling 1.0.6
	- dusk 1.18.2-2.1
	- dustrial_decor 0.5
	- dwarfcoal 1.18.1-1.0.1
	- ecologics 1.7.9
	- ellemes_container_lib 1.4.0-beta.2
	- elytratrinket 3.0.0-1.18.1
	- enchancement 1.18-18
	- entitybanners 1.0.2-BETA+1.18
	- error_notifier 1.0.9 via roughlyenoughitems
	- expandability 6.0.0 via artifacts
	- expandedstorage 7.4.0-beta.4
	- experiencebugfix 18
	- extraalchemy 1.8.1
	- extragenerators 1.2.1-BETA+1.18
	- fabric 0.58.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.23+d7c144a860 via fabric
	- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric
	- fabric-data-generation-api-v1 3.0.1+9fcb91d260 via fabric
	- fabric-dimensions-v1 2.1.20+489d6f8260 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.19+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.5.2+17cbbd4360 via fabric
	- fabric-item-groups-v0 0.3.14+91896a4960 via fabric
	- fabric-language-kotlin 1.8.2+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric
	- fabric-loot-api-v2 1.1.0+1997ad1260 via fabric
	- fabric-loot-tables-v1 1.1.2+e747827960 via fabric
	- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric
	- fabric-networking-api-v1 1.0.23+2d30af4b60 via fabric
	- fabric-networking-v0 0.3.10+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
	- fabric-registry-sync-v0 0.9.10+0d9ab37260 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric
	- fabric-screen-handler-api-v1 1.2.2+1f6558e860 via fabric
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric
	- fabricloader 0.14.9
	- fake-player-api 0.3.0 via create
	- farmersdelight 1.18.2-1.2.0
	- farmingforblockheads 10.0.2
	- feature_nbt_deadlock_be_gone 2.0.0+1.18.2-rc1
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via botania
	- findme 3.0.6
	- floral_flair 1.3.0
	- flytre_lib 1.8.1
	- forge_tags 2.2 via compactmachines
	- forgeconfigapiport 3.2.3
	- ftbchunks 1802.3.6-build.147
	- ftblibrary 1802.3.6-build.140
	- ftbquests 1802.3.8-build.101
	- ftbteams 1802.2.6-build.51
	- ftbultimine 1802.3.3-build.55
	- gateofbabylon 1.7.0-1.18.2
	- geckolib3 3.0.56
	- geodes 1.4.2
	- glassential 1.3.0
	- go-fish 1.5.0-1.18.2
	- goblintraders 1.5.1
	- goldenhoppers 1.3.3
	- goodall 1.0.2
	- graveyard 1.9
	- graveyard_biomes 1.1
	- guardvillagers 1.18.2-1.0.14
	- guild 0.4.0
	- harvest_scythes 2.5.1
	- horseinfo 0.4.1-1.18
	- iceberg 1.0.38
	- icy-incitement 1.18.2-fabric-1.1.3
	- impaled 1.1.3
	- impersonate 2.4.1 via bewitchment
	- improved-stations 2.1.0
	- incantationem 1.1.3+1.18.2
	- incubus_core 1.7.1 via spectrum
	- indrev 1.14.0-BETA
	- infusion_table 1.1.0
	- inmis 2.6.0-1.18.2
	- inventorysorter 1.8.8-1.18
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- iron-jetpacks 0.4.3
	- itemfilters 1802.2.7-build.21
	- jamlib 0.0.5
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- javax_annotation_javax_annotation-api 1.3.2 via twilightforest
	- jsonem 0.1.2 via automobility
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- kibe 1.9.9-BETA+1.18
	- kjsextras 3.0.0
	- kleeslabs 11.1.1
	- ktdatataglib 1.6.5+1.18.2 via dmlsimulacrum
	- kubejs 1802.5.4-build.533
	- kubejs_create 1802.2.2-build.28
	- kyrptconfig 1.4.6-1.18 via inventorysorter
	- lazydfu 0.1.2
	- libblockattributes_core 0.10.0 via indrev
	- libblockattributes_fluids 0.10.0 via indrev
	- libblockattributes_items 0.10.0 via indrev
	- libgui 5.4.0+1.18.2 via dark-enchanting
	- libninepatch 1.1.0 via libgui
	- lifts 1.4.1-BETA+1.18
	- lithium 0.7.10
	- logbegone 1.0.1
	- logprot 1.18-1.6
	- lootr 0.3.23.60
	- lovely_snails 1.0.4+1.18
	- luggage 1.3.2
	- maelstrom_library 1.2.4-1.18.2 via bosses_of_mass_destruction
	- magicalforest 2.0.3
	- magna 1.7.0-1.18-pre1 via vanilla-hammers
	- maybe-data 1.3.1-1.18.2 via deepslatecutting
	- mcwbridges 2.0.3
	- mcwdoors 1.0.7
	- mcwfences 1.0.6
	- mcwlights 1.0.4
	- mcwpaintings 1.0.4
	- mcwpaths 1.0.1
	- mcwroofs 2.1.2
	- mcwtrpdoors 1.0.7
	- mcwwindows 2.0.3
	- megane 7.8.0
	- megane-api 7.8.0 via megane
	- megane-applied-energistics-2 7.8.0 via megane
	- megane-create 7.8.0 via megane
	- megane-deep-mob-learning-simulacrum 7.8.0 via megane
	- megane-extra-generators 7.8.0 via megane
	- megane-fabric-transfer 7.8.0 via megane
	- megane-industrial-revolution 7.8.0 via megane
	- megane-kibe 7.8.0 via megane
	- megane-lib-block-attributes 7.8.0 via megane
	- megane-luggage 7.8.0 via megane
	- megane-modern-dynamics 7.8.0 via megane
	- megane-reborn-core 7.8.0 via megane
	- megane-reborn-energy 7.8.0 via megane
	- megane-runtime 7.8.0 via megane
	- megane-tech-reborn 7.8.0 via megane
	- megane-vanilla 7.8.0 via megane
	- megane-wireless-networks 7.8.0 via megane
	- milk 0.3.2 via create
	- minecarttweaks 1.5
	- minecraft 1.18.2
	- mm 2.3 via buildinggadgets
	- mobscarecrow 2.1.1
	- mocolors 1.4.0
	- modern_industrialization 1.2.2
	- moderndynamics 0.2.4-beta
	- morevillagers 3.3.2
	- mostructures 1.4.2+1.18.2
	- mtmechs 1.0.12
	- multipart_entities 1.1.5-1.18.2 via bosses_of_mass_destruction
	- myron 1.6.3+1.18.1 via automobility
	- mythicmounts 1.18.2-7.0
	- naturalist 1.1.1
	- naturescompass 1.18.2-2.0.3-fabric
	- nears 1.1.8
	- netherportalfix 9.0.0
	- no_angled_brackets 1.0.0
	- no_null_processors 2.0.1+1.18.1
	- omega-config 1.2.3-1.18.1 via mostructures
	- omega-config-gui 1.2.3-1.18.1 via coxinhautilities
	- onastick 2.0.0
	- openloader 12.0.1
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- overloadedarmorbar 1.18.1-6
	- owo 0.7.2-no-cme+1.18
	- patchouli 1.18.2-71.1-FABRIC
	- pehkui 3.4.0+1.14.4-1.19.2
	- peripheralium 0.1.1
	- peripheralworks 0.1.2
	- phosphor 0.8.1
	- piercingpaxels 1.0.1+1.18.2
	- pigpen 8.0.1
	- playerabilitylib 1.5.0 via kibe
	- plushies 1.2
	- polylib 1801.0.2-build.13
	- porting_lib 1.2.466-beta+1.18.2-dev.0251f31 via compactmachines
	- probablychests 0.5.3-1.18.2
	- programmerartinjector 1.2.1 via spectrum
	- promenade 2.6.3
	- pyrotastic 1.18.2+0.0.2
	- questsadditions 1.3.1
	- quickshulker 1.3.6-1.18
	- rare-ice 0.4.1
	- reach-entity-attributes 2.1.1 via twilightforest
	- reborncore 5.2.0
	- redstonebits 1.8.2
	- registrate-fabric MC1.18.2-1.1.3 via create
	- repurposed_structures 4.1.14+1.18.2
	- respawnablepets 1.18-4
	- revelationary 1.0.0
	- rhino 1802.1.14-build.209
	- rightclickharvest 3.0.0+1.18
	- roughlyenoughitems 8.3.529
	- roughlyenoughprofessions 1.0.1
	- roughlyenoughresources 2.5.0
	- runelic 11.0.1
	- secretrooms 1.3.1+1.18.2
	- seedfix 1.0.1
	- serialization_hooks 0.3.23 via porting_lib
	- shulkerboxtooltip 3.1.1+1.18.2
	- shulkerutils 1.0.4-1.18 via quickshulker
	- simpleteleporters 2.3.0
	- simplevoidworld 4.0.0
	- slimyfloor 1.18-1.2.2
	- smootherbedrock 1.0.4
	- smwyg 1.0.1
	- someforgepatchesported 1.0.3
	- spark 1.9.11
	- spectrum 1.5.0-1.18.2-magic
	- speedometer 1.1.0
	- spirit 2.1.8
	- staffofbuilding 1.4.1-1.18.1
	- static-content 1.0.2-1.16.2 via vanilla-hammers
	- staticdata 1.1.2 via static-content
	- step-height-entity-attribute 1.0.0 via artifacts
	- stoneholm 1.4.3
	- strawdummy 1.7.0
	- structory 1.0.0
	- team_reborn_energy 2.2.0 via buildinggadgets
	- techreborn 5.2.0
	- terrablender 1.1.0.102
	- terraform-shapes-api-v1 2.1.0 via promenade
	- terraform-wood-api-v1 3.0.0 via blockus
	- terrarianslimes 1.2.1-BETA+1.18
	- thatched 1.1.0
	- thonkutil 2.14.1+1.18
	- thonkutil-base 1.12.2+23c1dc2c60 via thonkutil
	- thonkutil-capes-v1 1.3.2+9e23427060 via thonkutil
	- thonkutil-customization-v1 1.0.14+9b80223760 via thonkutil
	- thonkutil-legacy 1.0.20+9b80223760 via thonkutil
	- thonkutil-modchecker-v1 1.0.12+9b80223760 via thonkutil
	- thonkutil-potions-v0 1.4.1+9b80223760 via thonkutil
	- thonkutil-trades-v1 1.1.20+9b80223760 via thonkutil
	- timeoutout 1.0.1+1.18
	- toolstats 9.0.3
	- totemmod 0.3.5-1.18.2-pre2
	- totw_additions 1.2.1
	- transportables 1.2
	- trapexpansion 1.3.3
	- trashslot 11.0.2
	- travelersbackpack 1.18.2-7.1.5
	- trinketofundying 2.0.2-1.18.2
	- trinkets 3.3.1
	- twigs 1.1.3-patch2+1.18.2
	- twilightforest 4.1.268
	- vanilla-hammers 3.4.0-1.18.2
	- vanillaexcavators 1.1.0
	- villager-hats 1.4.0
	- voidtotem 1.18.2-1.3.1
	- waystones 2.5.5+mc1.18.2
	- wildbackport 1.2.1
	- wilderworld 2.2.2
	- wirelessnetworks 1.5.1
	- wolveswitharmor 1.7.1-1.18.2
	- wthit 4.13.1
	- xaerominimap 22.13.2
	- xaeroworldmap 1.26.5
	- xlpackets 2.1-1.17.1
	- xps 0.4.4.r_for_1.18.x_Fabric
	- yigd 1.3.8
	- yungsapi 1.18.2-Fabric-2.0.8
	- yungsbridges 1.18.2-Fabric-2.1.0
	- yungsextras 1.18.2-Fabric-2.1.0

**Comment by TropheusJ** [comment]
CreateAddition needs to be updated
