### ISSUE TITLE
Latest dev build makes players unable to join servers - cannot synchronize recipes.

### ISSUE THREAD

**Issue by CzechHek** [Fabricators-of-Create/Create#537]
### Describe the Bug

When you download build from https://github.com/Fabricators-of-Create/Create/actions/runs/2950338012, players will be unable to join Open to LAN servers (normal servers as well? haven't tried). They will get kicked for not being able to receive packet SynchronizeRecipesS2CPacket.

### Reproduction Steps

1. Download latest build from https://github.com/Fabricators-of-Create/Create/actions/runs/2950338012
2. Open to LAN
3. Try to join with same mods.

### Expected Result

Players should be able to join servers.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/42714212/187659540-1b8ecf6b-e60c-4018-b142-e641de055c82.png)

### Crash Report or Log

https://mclo.gs/6YRTJHz

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

none

### Additional Context

This was discovered when other person tried to join my Open to LAN with Create in modpack. Later on I ran purely Create and was able to replicate it by joining localhost.

**Comment by TropheusJ** [comment]
can you try the newest build?

**Comment by CzechHek** [comment]
> can you try the newest build?

Fixed, tested https://github.com/Fabricators-of-Create/Create/suites/8081999073/artifacts/348603511.
