### ISSUE TITLE
fluid tank level as read from content observer is multiplied x81

### ISSUE THREAD

**Issue by CatgirlChilis** [Fabricators-of-Create/Create#538]
### Describe the Bug

When reading the fluid level in a fluid tank with a display link attached to a content observer, the amount displayed in mB is multiplied by 81 (so 1,000 mB displays 81000, 2,000 to 162000, 64,000 to 5184000, etc.)

### Reproduction Steps

1. set up a fluid tank with a content observer attached, and a display link outputting one of the fluid data sets to a display board
2. add any fluid to the tank
3. read the fluid level with engineer's goggles and compare to the display board

### Expected Result

Amount displayed should match what is read with engineer's goggles, being equal to 1,000 mB for each bucket added to the tank.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/17153074/187820312-1ecfd96d-a519-4760-b7d5-e24e063d1f09.png)
![image](https://user-images.githubusercontent.com/17153074/187820324-991bf708-3526-4dc7-8cfc-822469d32170.png)

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

none

**Comment by TropheusJ** [comment]
Since the text can't be based on the config, I've added additional configuration to select the unit.
