### ISSUE TITLE
Partial incompatibility with Sodium (Flywheel backend)

### ISSUE THREAD

**Issue by AeiouEnigma** [Fabricators-of-Create/Create#54]
Create's shafts, belts, crushing wheels, and probably more do not render at all while the Flywheel backend is enabled.

![2021-12-24_20 57 54](https://user-images.githubusercontent.com/3160746/147375753-47888f6a-a8c7-4a32-b007-62141f35c98a.png)
![2021-12-24_20 58 07](https://user-images.githubusercontent.com/3160746/147375754-fb5b2c7a-4668-4490-9690-472dbcc95de6.png)

**Comment by AeiouEnigma** [comment]
Haven't found any issues at all with Sodium when Flywheel backend is disabled

**Comment by Jozufozu** [comment]
https://github.com/Jozufozu/sodium-forge/commit/9bcfbc28118fc35ee831a01eea7c59b55b94fd26
No doubt sodium's internals have changed, but this needs to be fixed on their end

**Comment by AeiouEnigma** [comment]
> [Jozufozu/sodium-forge@9bcfbc2](https://github.com/Jozufozu/sodium-forge/commit/9bcfbc28118fc35ee831a01eea7c59b55b94fd26) No doubt sodium's internals have changed, but this needs to be fixed on their end

[@Jozufozu would I have your blessing in potentially adapting your linked code into a PR to sodium-fabric, in the event I get such a thing working right?](https://github.com/Creators-of-Create/Create/pull/2485)

**Comment by Jozufozu** [comment]
Absolutely, ping me if you get it working and I'll help verify

**Comment by TheBeautyLlama** [comment]
> Haven't found any issues at all with Sodium when Flywheel backend is disabled
how to off it?

**Comment by AeiouEnigma** [comment]
Okay it's not quite as plug-and-play as I was hoping. No improvement when flywheel backend is enabled, and making that change to sodium as-written also newly breaks things when flywheel backend is disabled

This task is officially beyond me lol

![image](https://user-images.githubusercontent.com/3160746/147421451-4d7ab0c0-fe2f-47ad-b190-7e6336d3e510.png)

**Comment by Oliver-makes-code** [comment]
It seems to work fine with [Indium](https://modrinth.com/mod/indium)
![2021-12-30_22 25 31](https://user-images.githubusercontent.com/59418903/147803269-7509f167-5025-4673-b9c3-0a469b40381b.png)

**Comment by AeiouEnigma** [comment]
how

![2021-12-30_23 29 45](https://user-images.githubusercontent.com/3160746/147803381-290ce2a7-0d4d-4614-a8ea-7bbb22c04d61.png)

**Comment by AeiouEnigma** [comment]
Could this be an nvidia issue?

**Comment by Oliver-makes-code** [comment]
Possibly, Sodium has had problems with driver-specific things in the past

**Comment by Oliver-makes-code** [comment]
Here's a small update: It fixes it, but only for a period of time, and then it spams the following error in the console:
```
[22:42:44] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'
```

**Comment by Oliver-makes-code** [comment]
It occurs when chunks are reloaded after the blocks are placed

**Comment by Oliver-makes-code** [comment]
Gonna look into this to see what the cause is

**Comment by Oliver-makes-code** [comment]
I think I found something, it occurs during startup
https://pastebin.com/4mVFbqkG

**Comment by Oliver-makes-code** [comment]
It looks like that when a chunk reload is triggered via world reload, f3+a, or unloading a chunk, FlyWheel removes the models it needs to render, and Sodium's renderer doesn't call the methods that FlyWheel uses to put them back

**Comment by Oliver-makes-code** [comment]
`ChunkRenderDispatcher$RenderChunk$RebuildTask$handleBlockEntity` (`ChunkBuilder$BuiltChunk$RebuildTask$addBlockEntity` on yarn) isn't called on sodium's side, and that's what FlyWheel uses to re-add the BlockEntities.

**Comment by plapl1** [comment]
Same issue exists on Canvas Renderer, unsure if I should create a new issue since it might be the same error causing it on both renderers.

**Comment by Oliver-makes-code** [comment]
As of the latest version, It straight up crashes during startup due to a mixin conflict with LevelRendererMixin and MixinWorldRenderer on Flywheel and Sodium respectively

**Comment by AeiouEnigma** [comment]
> As of the latest version, It straight up crashes during startup due to a mixin conflict with LevelRendererMixin and MixinWorldRenderer on Flywheel and Sodium respectively

The crash will be fixed in the next Flywheel update.

**Comment by RedWideWeb** [comment]
Partially fixed in builds 343 and 344. Still crashes occasionally but it works now. World launches, belts and entities are rendered properly. Even Shaders are partially working. Great job, @AeiouEnigma

**Comment by AeiouEnigma** [comment]
Appreciate it, but truly the credit needs to go to Jozufozu and Pepper :)

I only took 2 minutes to merge the existing code from the forge version.

To avoid crashes, just make sure to set `/flywheel backend off`. Shaders seem to work fine with contraptions if you use Iris's new configuration menu to disable shader-based shadows, if the option exists for your particular shaderpack.

**Comment by RedWideWeb** [comment]
> To avoid crashes, just make sure to set `/flywheel backend off`. Shaders seem to work fine with contraptions if you use Iris's new configuration menu to disable shader-based shadows, if the option exists for your particular shaderpack.

Will try that. Thanks!

**Comment by RedWideWeb** [comment]
Why is this issue still open?

**Comment by AeiouEnigma** [comment]
> Why is this issue still open?

Because using Sodium, even with Indium installed, still results in severe rendering issues when the Flywheel backend is enabled.

**Comment by DarianLStephens** [comment]
I was trying it a few minutes ago, and everything looked how I'd expect coming from the Forge version.

**Comment by RedWideWeb** [comment]
> > Why is this issue still open?
> 
> Because using Sodium, even with Indium installed, still results in severe rendering issues when the Flywheel backend is enabled.

Yeah, I see. Okay

**Comment by RedWideWeb** [comment]
> I was trying it a few minutes ago, and everything looked how I'd expect coming from the Forge version.

Have you disabled flywheel backend?

**Comment by DarianLStephens** [comment]
I haven't.
Just installed the latest artifact and everything's peachy.

**Comment by DarianLStephens** [comment]
Screenshot for reference:
![2022-01-21_10 27 14](https://user-images.githubusercontent.com/15375876/150438325-aa07fdfb-ad6c-4e02-99d4-fd7b3d46842e.png)

**Comment by RedWideWeb** [comment]
> Screenshot for reference:
> ![2022-01-21_10 27 14](https://user-images.githubusercontent.com/15375876/150438325-aa07fdfb-ad6c-4e02-99d4-fd7b3d46842e.png)

Flywheel: Off

**Comment by DarianLStephens** [comment]
Wait, is it off by default? I just noticed that text on the right, but I haven't run that /flywheel backend off command.

**Comment by RedWideWeb** [comment]
> Wait, is it off by default? I just noticed that text on the right, but I haven't run that /flywheel backend off command.

Not sure. Maybe it should be Off

**Comment by RedWideWeb** [comment]
@AeiouEnigma should Flywheel be marked as Off in F3 menu

**Comment by DarianLStephens** [comment]
Running /flywheel backend batching crashed the game instantly.
Running /flywheel backend instancing does the same.

I guess that means it was off the entire time and I just never noticed.

**Comment by AeiouEnigma** [comment]
> Running /flywheel backend batching crashed the game instantly. Running /flywheel backend instancing does the same.

Known issue with Iris, though we haven't actually opened an Issue about that

**Comment by RedWideWeb** [comment]
> Running /flywheel backend batching crashed the game instantly. Running /flywheel backend instancing does the same.
> 
> I guess that means it was off the entire time and I just never noticed.

For me it was instancing by default. So before I disabled it i ran just `/flywheel backend` and it printed default value which was instancing for me.

**Comment by AeiouEnigma** [comment]
Running the `/flywheel backend instancing` or `/flywheel backend batching` commands with sodium installed results in various blocks having messed up or non-existent rendering

**Comment by DarianLStephens** [comment]
Yeah, Iris does _not_ like this.
Turning shaders on made contraptions (the windmill) disappear, and turning them back off just crashed the game.

With Iris off, it's defaulting to Instancing, and I'm seeing the same issues as here.
![2022-01-21_10 33 35](https://user-images.githubusercontent.com/15375876/150438849-4bf80762-4f84-462c-9a50-ed030cdbc097.png)

Batching just makes it all disappear:
![2022-01-21_10 34 34](https://user-images.githubusercontent.com/15375876/150438951-9b32ac97-902b-4a7a-9b22-f94bbdce3496.png)

**Comment by RedWideWeb** [comment]
> Yeah, Iris does _not_ like this. Turning shaders on made contraptions (the windmill) disappear, and turning them back off just crashed the game.
> 
> With Iris off, it's defaulting to Instancing, and I'm seeing the same issues as here. ![2022-01-21_10 33 35](https://user-images.githubusercontent.com/15375876/150438849-4bf80762-4f84-462c-9a50-ed030cdbc097.png)

For shaders disable Realtime shadows. This fixes the Windmills

**Comment by AeiouEnigma** [comment]
If the world *loads* while the flywheel backend is enabled, things will probably look just fine until the renderer reloads.

Contraptions not rendering with certain shaders enabled is another known issue. If the shaderpack has an option to disable shadows, that may 'fix' the problem.

**Comment by DarianLStephens** [comment]
Interestingly, newly-placed blocks seem to render just fine, but toggling Flywheel or using F3+A makes things disappear.
![2022-01-21_10 37 10](https://user-images.githubusercontent.com/15375876/150439210-95e1f460-08a3-4393-bf1f-f9a6b42e7963.png)
![2022-01-21_10 37 40](https://user-images.githubusercontent.com/15375876/150439245-9f27b0ed-a3cc-42c4-875e-406d98237f5c.png)

The cogwheel was even spinning.

**Comment by DarianLStephens** [comment]
More of things working after replacing the blocks manually.
![2022-01-21_10 40 44](https://user-images.githubusercontent.com/15375876/150439496-c3942e71-323b-4bdd-a7e3-410c86b303ea.png)

**Comment by RedWideWeb** [comment]
There are no shafts on the gearboxes

**Comment by AeiouEnigma** [comment]
Alright I appreciate it but you can both stop updating on every minor detail lol, the issue is known

**Comment by RedWideWeb** [comment]
> Alright I appreciate it but you can both stop updating on every minor detail lol, the issue is known

Okay, sorry.

**Comment by AeiouEnigma** [comment]
No harm done 😄

**Comment by PepperCode1** [comment]
This was fixed completely in Flywheel as of yesterday, and I am not aware of any issues with Create specifically, so I am closing this issue. If there are other problems please open a new one.
