### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by ardissaps** [Fabricators-of-Create/Create#542]
### Describe the Bug

Crash when opening ponder for a while.

### Reproduction Steps

1. Open any ponder

### Expected Result

No problem

### Screenshots and Videos

Latest Log : https://aofpaste.com/ujavavoruw.yaml

### Crash Report or Log

https://aofpaste.com/ozenidagav.yaml

### Operating System

Windows 11

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

**Comment by GoodGuyJimmy** [comment]
This is also happening to me on the latest version, the game crashes after pondering
