### ISSUE TITLE
Ores not generating

### ISSUE THREAD

**Issue by ikhlaz** [Fabricators-of-Create/Create#545]
### Describe the Bug

I'm playing version 0.5d with no other mods.
Zinc ores and other Create mod blocks such as scoria, crimsite, etc do not spawn in world, even when starting new games. 

### Reproduction Steps

1. Start new game in spectator mode
2. Go around the world looking for create mod ores

### Expected Result

Can't find any custom ores

### Operating System

Windows 10

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

**Comment by ikhlaz** [comment]
Tried with 0.5.0c and the ores spawn normally. 
I believe it has something to do with the create-common.toml settings which cannot be manually changed by end users. 
In 0.50d, there's an additional setting which is marked as > -2XXXXXXXXXXX for the range of values. 
This is absent in 0.50c, and the ore generation here works fine.

**Comment by TropheusJ** [comment]
what's the setting?

**Comment by ikhlaz** [comment]
Setting? I didn't tamper with any settings. Just using the default one.

**Comment by TropheusJ** [comment]
you said there was an additional setting. Nevermind though, this is fixed in patch 2.

And configs are designed to be changed by users, that's their entire point.

**Comment by ikhlaz** [comment]
Oh, ok. The setting that I was talking about can't be changed through the in-game Create options or editing the toml file. 
Since it's fixed nvm. Thanks for the quick response!
