### ISSUE TITLE
Crash with Pojav Launcher

### ISSUE THREAD

**Issue by Ruijin1722** [Fabricators-of-Create/Create#546]
### Describe the Bug

Works not with forge or Fabric in pojav Launcher Android pls make an Update and Playable maybe Open gl downgrade 

### Reproduction Steps

1.
2.
3.
...

### Expected Result

Works not with forge or Fabric in pojav Launcher Android pls make an Update and Playable maybe Open gl downgrade 

### Operating System

Android

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

### Other Mods

Only create Mod.

**Comment by ghost** [comment]
fabric api? Logs?

**Comment by JieningYu** [comment]
OpenGL downgrade requires Flywheel to be compatibilited.

**Comment by Vannz837** [comment]
I want to install forge but it always crashes, what causes it all

**Comment by AkashiiKun** [comment]
> I want to install forge but it always crashes, what causes it all

This fork is for Fabric. 
Forge version: https://github.com/Creators-of-Create/Create

**Comment by TropheusJ** [comment]
can't do anything without logs, and I can't test pojav.

**Comment by IThundxr** [comment]
Pojav is unsupported
