### ISSUE TITLE
incompatible with colormatic?

### ISSUE THREAD

**Issue by RichPrune** [Fabricators-of-Create/Create#547]
### Describe the Bug

crashes on startup

### Reproduction Steps

1.i open with both mods installed and it gives a white fabric icon error screen says " this version isnt compatible with this version. change to a version that is"

2.
3.
...

### Expected Result

not to crash

### Operating System

windows 10

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

### Additional Context

happens for both .5.0d and c for fabric 1.18.2

**Comment by TropheusJ** [comment]
yes, they are incompatible. It can't be fixed by us.
