### ISSUE TITLE
Bug, some survival recipes are not displayed. 

### ISSUE THREAD

**Issue by smertVkedax** [Fabricators-of-Create/Create#549]
### Describe the Bug

Bug, some survival recipes are not displayed. 
REI ,JEI  I tried and nothing has changed.

### Reproduction Steps

1.in REI or JEI Not displayed 
2.crafting recipe not showing
3.
...

### Expected Result

removing other mods didn't fix the crafting display issue Create.Other version create did not solve the crafting problem. Sorry for my bad english 

### Operating System

Linux

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
What recipes?

**Comment by smertVkedax** [comment]
> Какие рецепты?

Andesite Casing,Brass Casing,Copper Casing,Train Casing and a couple more.

**Comment by TropheusJ** [comment]
Those recipes were changed to in-world interaction.

**Comment by smertVkedax** [comment]
And how can I craft these mechanisms if I do not know the recipe.

**Comment by TropheusJ** [comment]
they're in the manual item application category
![image](https://user-images.githubusercontent.com/60247969/189235438-cdcb8f00-666e-4171-97f2-8b430a2d7624.png)

**Comment by smertVkedax** [comment]
I understand! But to create manually you need plates that are crafted through a press and the press requires Andesite Casing. Because it's not well thought out :/

**Comment by JieningYu** [comment]
you don't need plates to make andesite casings.

**Comment by smertVkedax** [comment]
![Screenshot_20220909_184002](https://user-images.githubusercontent.com/112849953/189389164-9a7aa526-3b8a-427b-b321-fd36eda9557d.png)
![Screenshot_20220909_184113](https://user-images.githubusercontent.com/112849953/189389186-f8b4cb6f-ebed-49de-9a86-a891588a0b45.png)
![Screenshot_20220909_184142](https://user-images.githubusercontent.com/112849953/189389197-a2f7010d-31f9-4b7c-8d38-c0de117f0e89.png)
To create an andesite case, you need a manual one! But to create a manual one, you need plates like on the screen! And the plates are made with a press. So please explain to me how I can create andesite case ! I do not understand!! Enter minecraft 1.18.2 in survival and show a screen how you create this damn andesite hull! If no other recipes are displayed for it! Through the workbench, too, it’s impossible to create!

**Comment by TropheusJ** [comment]
just place a stripped log and click it with an andesite alloy.

**Comment by smertVkedax** [comment]
Why couldn't this be added to crafting? like a fool, I surfed the whole Internet to understand how to craft, and it's so easy to click .... how can I live with this. Thanks a lot for your help!!!!!
