### ISSUE TITLE
Create Mod rendering screen error

### ISSUE THREAD

**Issue by Coosanta17** [Fabricators-of-Create/Create#550]
### Describe the Bug

Create Mod crashes as soon as I load/create a world. Config menus for other mods are all fine and working but when I click the create mod icon it freezes on `Saving World` before crashing, the same thing happens with loading a world. I am not sure whether this is a compatibility issue or not but I will report it here anyway.

### Reproduction Steps

1. Load Minecraft with mods listed above.
2. Create a world or click the create mod options icon.
3. Game crashes

### Expected Result

The world will load with everything functioning normally

### Crash Report or Log

https://pastebin.com/AcTJ1Ea6

### Operating System

Windows 10

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

Here are all the mods I have installed: 
![image](https://user-images.githubusercontent.com/85379921/189057619-a65c700f-8ede-48fe-b325-fe8aa508ace3.png)

**Comment by TropheusJ** [comment]
problem with iris, update it
