### ISSUE TITLE
Bugs with cogwheel

### ISSUE THREAD

**Issue by RainStar7981** [Fabricators-of-Create/Create#552]
### Describe the Bug

(my english is not very good)
1.When the received steering of the cogwheels is uneven, the cogwheels will not drop
2.as in the video, then the game will crash
video link: https://www.bilibili.com/video/BV17e411u74r/

### Reproduction Steps

as in the video

### Expected Result

This bug is annoying, hope it gets fixed soon
thanks to the author :)

### Screenshots and Videos

launcher promet
![图片](https://user-images.githubusercontent.com/94267417/189485037-287b89d8-f8b5-402a-aa3c-3c289cb4d046.png)
(This is not the launcher prompt for the client in the video, but the problem is the same)

### Crash Report or Log

https://gist.github.com/RainStar7981/d600423e39cb5edb34392540f149b179

### Operating System

windows 10

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

### Other Mods

sodium, indium , modmenu and imblocker(fabric)

**Comment by RainStar7981** [comment]
After removing sodium, bug1 no longer reproduces, but bug2 still exists.
new crash report: https://gist.github.com/RainStar7981/1708c47d94f9b0dc1cd1c461f0e15be9

**Comment by TropheusJ** [comment]
Can’t reproduce, please test patch G.

**Comment by RainStar7981** [comment]
yeah, can't reproduce in patch G.
