### ISSUE TITLE
Soft-lock from invalid contraption

### ISSUE THREAD

**Issue by poly2it** [Fabricators-of-Create/Create#553]
### Describe the Bug

Assembling a train under certain circumstances can result in an invalid contraption, resulting in a permanent soft-lock, instantly kicking every player in the region with no way of returning.

This behavior is present both in 0.5c and 0.5d Patch 2.

Schematic:
[arbetart_g.nbt.zip](https://github.com/Fabricators-of-Create/Create/files/9542297/arbetart_g.nbt.zip)

### Reproduction Steps

1. Build the train schematic on rails using a schematicannon.
2. Use a station to begin construction of a train.
3. The server will create an invalid train when you attempt to assemble, irreversibly soft-locking every player in the area out of the server.

### Expected Result

A train should be assembled.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/84731064/189523017-22759a45-aa64-40e9-8ece-7a4f7f8236b7.png)

### Crash Report or Log

https://gist.github.com/Poly2it/7db2b82d450577117cc6613d638f780b

### Operating System

Ubuntu 22.04

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

### Other Mods

Blockus

**Comment by TropheusJ** [comment]
Can’t reproduce, please test patch G.

**Comment by TropheusJ** [comment]
I can load the schematic fine, I have heard no other reports of this issue, and many things have changed since patch C. considered fixed until proven otherwise.
