### ISSUE TITLE
Better Contributing.md

### ISSUE THREAD

**Issue by JaaiDead** [Fabricators-of-Create/Create#555]
### Describe the Suggestion

Hello , 
I Suggest to add a  CONTRIBUTING.md, for contributions and steps to follow.

**Comment by JieningYu** [comment]
https://github.com/Fabricators-of-Create/Create/blob/mc1.18/fabric/dev/README/CONTRIBUTING.md

**Comment by TropheusJ** [comment]
That needs to be updated

**Comment by JaaiDead** [comment]
hello, just checking anyone here?
