### ISSUE TITLE
Item Duplication with Weighted Ejectors

### ISSUE THREAD

**Issue by rainbowcraft2** [Fabricators-of-Create/Create#558]
### Describe the Bug

Filling multiple buckets or bottles on a Weighted Ejector will cause it to dupe the filled buckets/bottles infinitely

### Reproduction Steps

1. Set up a Weighted Ejector with a destination that has a filter. This filter will be set to the filled version of the chosen item (ie: water bucket)
2. Set up a spout above the Ejector to fill bottles/buckets. Make sure it has a tank with enough fluid to fill at least 2 buckets/bottles
3. Place a stack of 2 or more empty buckets on the Ejector. They will get filled up by your fluid of choice
4. The Ejector will successfully launch the first one just fine. All remaining items on the Ejector will get duped.
5. This works with buckets, builder's tea, potions, etc.

### Expected Result

I expect the ejector to eject the items it is holding one at a time, clearing them out completely after it's done. Instead it clears the first one and fails to clear the remaining items.

### Screenshots and Videos

I recorded a video of many different items. More explanation/description of the bug is included in the video's description
[https://youtu.be/KBq3s3hWBBs](https://youtu.be/KBq3s3hWBBs)

### Operating System

Windows 10 Home

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

- fabric-api-0.58.0+1.18.2.jar
- jei-1.18.2-fabric-10.1.3.240.jar
- lithium-fabric-mc1.18.2-0.7.10.jar
- phosphor-fabric-mc1.18.x-0.8.1.jar

### Additional Context

I was trying to design a new machine in creative mode to reference when building in survival on a server I for myself and my siblings when I accidentally found this dupe (the machine was supposed to collect lava from the nether and send it to the overworld for draining into a tank). This lava would then be used for making Blaze Cakes and Sturdy Sheets.

**Comment by JieningYu** [comment]
have you tested with the latest version?

**Comment by Orisland** [comment]
Same question!
[Video](https://www.bilibili.com/video/BV1fe411L7ip/)
Version: [create-1.18.2-0.5.0c-708](https://www.curseforge.com/minecraft/mc-mods/create-fabric/files/3913786)
From [AOF5 1.5.1](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5/files/3941192) modpacks.

**Comment by rainbowcraft2** [comment]
> 
Hi, sorry for taking nearly a month to get back to you - I was busy and on top of that I wasn't ready to update yet. As of today, the bug is still happening in patch 0.5.0e (latest available download). I checked with both lava and water buckets.

**Comment by Derpford** [comment]
I've also encountered this bug when using a spout in a Sequenced Assembly recipe (tested with the first step of Create's sturdy plate recipe, and with the AE2 quartz growth recipe from CreatePlus). Again, version 0.5.0e.
