### ISSUE TITLE
Milk bucket gets stuck on drain

### ISSUE THREAD

**Issue by LordGrimmauld** [Fabricators-of-Create/Create#56]
### Describe the Bug

trying to drain a milk bucket by rolling it over a drain will make the bucket stuck infinitely on the drain

### Reproduction Steps

1. Make a belt/hopper pointing into a drain
2. put in a milk bucket
3. watch it get stuck on the drain
...

### Expected Result

Milk bucket gets emptied into the drain fluid buffer

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/49513131/147421647-5c9b1743-7c2c-4c4d-8e0a-093b0a20ace9.png)
![image](https://user-images.githubusercontent.com/49513131/147421650-0bb69e36-3c9c-4f1c-b728-cb436dc881c2.png)

### Operating System

Win 10

### Mod Version

0.4.0a

### Minecraft Version

1.18.1

### Other Mods

Flywheel and other dependencies

### Additional Context

Milk exists, as evidenced by the second screenshot. It just doesn't like the emptying into buckets,

Found by @Indi, second screenshot evidencing the existance of milk by @SpottyTheTurtle

**Comment by TropheusJ** [comment]
this was fixed [here](https://github.com/Create-Fabric/Create-Refabricated/commit/ea6a97a57481c088341b69998a6d7169750aff7e)
