### ISSUE TITLE
Cogwheels and Pipes are Glitched

### ISSUE THREAD

**Issue by MeryBence** [Fabricators-of-Create/Create#563]
### Describe the Bug

I play on a server with my friends on Fabric, and when I place down a cogwheel it has a stable cogwheel that doesn't move, and the one that moves when it has some RPM. The pipes are not connecting visually.

### Reproduction Steps

1. I place down a cogwheel/pipe
2. Then the cogwheel starts to move, but there are two cogwheels overlapping. 1 stable, 1 moving. The Pipes don't connect visually.

### Expected Result

The pipes and the cogwheels look bad, and at the cogwheels it is not that a big bug, but at the pipes. I can't play whit how the pipes look.

### Operating System

WIndows 10

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

### Other Mods

- Sodium
- Xaeros Minimap
- Jei
- Origins

**Comment by ghost** [comment]
its good to mention that sodium doesn't play nice with many fabric mods, try adding [this mod](https://modrinth.com/mod/indium) and try again.

**Comment by TropheusJ** [comment]
indium is needed when sodium is used
