### ISSUE TITLE
Bat Mount Ice Game Crash

### ISSUE THREAD

**Issue by Kuuhaku1992** [Fabricators-of-Create/Create#565]
### Describe the Bug

Game Crashes after you try to kill a Bat Mount with a frost enchanted Sword.
Minecraft Bug report says: Loading failed due to Frosted Bat Entity.

### Reproduction Steps

1. Encounter Bat Mount in the Nether
2. Hit it with Frosteffect Weapon
3. Game Crash
...

### Expected Result

My World will not crash as soon as i join it

### Operating System

Windows 11

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Other Mods

All of Fabric 5 Mod Pack

**Comment by TropheusJ** [comment]
can't do anything without a log, and I doubt this is a Create issue.
