### ISSUE TITLE
Create causes a "bootloop"

### ISSUE THREAD

**Issue by TheButterbrotMan** [Fabricators-of-Create/Create#566]
### Describe the Bug

When i try to start my game it loads into a bootloop. Minecraft restart loading again and again.

### Reproduction Steps

1. Download the modpack
2. Update Create
3. Start the modpack
4. ???
5. Minecraft Bootloop

### Expected Result

I can start the game sucessfully.

### Crash Report or Log

https://bytebin.lucko.me/kSQZiQblz3

### Operating System

Windows 10

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

### Other Mods

https://www.curseforge.com/minecraft/modpacks/deathdusk (2.1.6)

**Comment by TheButterbrotMan** [comment]
Any news on this? Still happening with newest release.

**Comment by TropheusJ** [comment]
There’s no way I can debug a pack of 600+ mods. You’ll need to binary split it.

split mods in half. Fixed? Check the other half. Not fixed? Repeat until minimum mod combo is found.

**Comment by TropheusJ** [comment]
The primary error in here is with fluid attributes. These have been changed since the issue was made, and are entirely removed on 1.19, so I'm going to consider this fixed
