### ISSUE TITLE
Potato cannon doesn't autofire

### ISSUE THREAD

**Issue by twu425** [Fabricators-of-Create/Create#574]
### Describe the Bug

1. The potato cannon doesn't autofire like it does in the forge version when holding down right click. It simply slows you down. 

2. The potato cannon can't be enchanted with anything outside of unbreaking

### Reproduction Steps

1. Hold down right click with the potato cannon.

2. Attempt to enchant a potato cannon

### Expected Result

1. Given that the forge version has support for autofiring, I expected the same behavior on the fabric version. 

2. I'm unsure if this is the same for the forge version but I believe you were able to at least enchant the cannon with the potato recovery as well as power and flame.

### Operating System

Windows 11

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
2. has been fixed.
