### ISSUE TITLE
REI Sequenced Assembly filling oversight

### ISSUE THREAD

**Issue by mangiti** [Fabricators-of-Create/Create#575]
### Describe the Bug

Sequenced assembly recipes with multiple fluid ingredients causes REI to fail.

### Reproduction Steps

1. Create any sequenced assembly with two or more spouting steps of different fluids, (Lava and water, two different potions, etc)
2. Attempt to view the recipe in REI

### Expected Result

Recipe is shown properly

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/18366242/197359728-54978bcc-e794-4199-8a85-03505629b8cd.png)

### Crash Report or Log

`[16:00:27] [Render thread/INFO]: [STDERR]: java.lang.IndexOutOfBoundsException: index (1) must be less than size (1) [16:00:27] [Render thread/INFO]: [STDERR]: 	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1355) [16:00:27] [Render thread/INFO]: [STDERR]: 	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1337) [16:00:27] [Render thread/INFO]: [STDERR]: 	at com.google.common.collect.SingletonImmutableList.get(SingletonImmutableList.java:44) [16:00:27] [Render thread/INFO]: [STDERR]: 	at com.simibubi.create.compat.rei.category.sequencedAssembly.ReiSequencedAssemblySubCategory$AssemblySpouting.addFluidIngredients(ReiSequencedAssemblySubCategory.java:86) [16:00:27] [Render thread/INFO]: [STDERR]: 	at com.simibubi.create.compat.rei.category.SequencedAssemblyCategory.addWidgets(SequencedAssemblyCategory.java:84) [16:00:27] [Render thread/INFO]: [STDERR]: 	at com.simibubi.create.compat.rei.category.CreateRecipeCategory.setupDisplay(CreateRecipeCategory.java:294) [16:00:27] [Render thread/INFO]: [STDERR]: 	at com.simibubi.create.compat.rei.category.CreateRecipeCategory.setupDisplay(CreateRecipeCategory.java:44) [16:00:27] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.initDisplays(DefaultDisplayViewingScreen.java:295) [16:00:27] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25426(DefaultDisplayViewingScreen.java:272) [16:00:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25423(class_437.java:389) [16:00:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1507(class_310.java:993) [16:00:27] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.ClientHelperImpl.openView(ClientHelperImpl.java:348) [16:00:27] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.api.client.view.ViewSearchBuilder.open(ViewSearchBuilder.java:228) [16:00:27] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25404(ScreenOverlayImpl.java:382) [16:00:27] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$22(RoughlyEnoughItemsCoreClient.java:428) [16:00:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.handler$bbf000$onKey(class_309.java:1141) [16:00:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:380) [16:00:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:472) [16:00:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:103) [16:00:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:472) [16:00:27] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) [16:00:27] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method) [16:00:27] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [16:00:27] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197) [16:00:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310) [16:00:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1147) [16:00:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737) [16:00:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236) [16:00:27] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [16:00:27] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [16:00:27] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [16:00:27] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) [16:00:27] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:577) [16:00:27] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [16:00:27] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [16:00:27] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [16:00:27] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) [16:00:27] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)`

### Operating System

Linux

### Mod Version

0.5.0f

### Minecraft Version

1.18.2

### Other Mods

REI

**Comment by TropheusJ** [comment]
can you provide an example recipe that fails?

**Comment by JieningYu** [comment]
for example
<img width="505" alt="image" src="https://user-images.githubusercontent.com/61787533/202897605-f8fa9992-33b8-46e5-b989-ef42ca7c4f89.png">

**Comment by cold233** [comment]
This issue is also seen in my case, mod version:0.5.0.i-1016+1.18.2

**Comment by JieningYu** [comment]
solution: https://github.com/HO-Artisan/CreateFabric-REIBugFix

**Comment by TropheusJ** [comment]
see #1616
