### ISSUE TITLE
*item vault. fixed.

### ISSUE THREAD

**Issue by Gismov2** [Fabricators-of-Create/Create#577]
### Describe the Bug

*so the item vault for some reason wont connect into one in the texture but it is still one but i cant see it and idk why but one of my friends tryed it and it worked nomely so idk if its my textures idk to i just stoped working
![bugg](https://user-images.githubusercontent.com/116737473/198053059-af011361-ee23-424f-a573-a51736ecf375.png)

### Reproduction Steps

*1.take item vaults
*2. place in 3x3x3

### Expected Result

*i did not expact this to happend at first cuz i worked yesterday so idk why but it keep hapending to me meybe its my textures

### Screenshots and Videos

*![Uploading bugg.png…]()

### Crash Report or Log

*

### Operating System

*windows 11

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

### Other Mods

*

### Additional Context

* i do have some shaders installed

**Comment by TropheusJ** [comment]
Does the title change mean this is no longer an issue? If you still have problems re-open and provide your latest.log.
