### ISSUE TITLE
Create fabric server 1.18 create placed block changes

### ISSUE THREAD

**Issue by creativecaleb** [Fabricators-of-Create/Create#578]
### Describe the Bug

Basically, I am running a create mod server for me and my friends, but I just started to get into the start of create by placing a depot but it turned into a chute and when broken, it changes back.

There are also issues regarding generation of certain blocks, for example I found a 'vein' of waterlogged walls

### Reproduction Steps

1.create a 1.18 fabric create mod server with the mods listed below
2.place a depot(probably the same for other create mod blocks)

### Expected Result

I expected a depot would be placed when I right clicked with it in my hand

### Operating System

Windows 10

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

### Other Mods

![image_2022-10-29_133856568](https://user-images.githubusercontent.com/94647976/198753804-c416cdde-1fe7-4ba7-8183-77e5062ac395.png)

**Comment by TropheusJ** [comment]
This is a registry desync. make sure the versions of mods on the server and all clients are *exactly* the same and fully up to date.

**Comment by creativecaleb** [comment]
ok, I'll try that later

**Comment by creativecaleb** [comment]
![image](https://user-images.githubusercontent.com/94647976/198792666-0b9fc36c-b0a4-4e41-b82b-70096bd31e90.png)
could this be the problem?

**Comment by TropheusJ** [comment]
no

**Comment by creativecaleb** [comment]
ok, i fixed the mods and my game crashed every time I tried to join. Ill try it tomorrow on a pc with hopefully better specs

**Comment by creativecaleb** [comment]
It works, but it keeps kicking me and being laggy. Is that mods or just hardware?

**Comment by JieningYu** [comment]
mods and hardware

**Comment by creativecaleb** [comment]
ok, thanks. I can put up with the lag, but the issue is solved thanks
