### ISSUE TITLE
Crash when punching any mob 

### ISSUE THREAD

**Issue by Xertyp1** [Fabricators-of-Create/Create#579]
### Describe the Bug

Minecraft crashes when punching any a mob

### Reproduction Steps

1.Open intellij
2.start fabric project on 1.18.2 and set it up to be ready to run client
3.put create mod in mods folder
4.press run client in intellij
5.load up world
6.punch mob
7. minecraft crashes

### Expected Result

-minecraft NOT crashing

### Operating System

macOS

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

### Other Mods

-not enough crashes(fabric)
-Fabric API

### Additional Context

Im not using the minecraft launcher, instead i am only using intellij
-i can still kill mobs with a bow
-mobs such as boats are affected aswell
-mobs can take any other damage then my punch without minecraft crashing

**Comment by JieningYu** [comment]
why use gradle to runClient? just grab the artifact from Actions and run it in a typical launcher.

**Comment by Sheep7798** [comment]
That’s related to porting lib, not create

**Comment by Xertyp1** [comment]
> why use gradle to runClient? just grab the artifact from Actions and run it in a typical launcher.

i guess ill do that

**Comment by TropheusJ** [comment]
can't do anything without logs, but it seems you got a solution
