### ISSUE TITLE
Filling a tank with a bucket also places the fluid as a block

### ISSUE THREAD

**Issue by PepperCode1** [Fabricators-of-Create/Create#58]
### Describe the Bug

Filling a tank with a bucket also places the fluid as a block.

### Reproduction Steps

1. Right click on a tank with a filled bucket in creative mode

### Expected Result

The fluid should not be placed in-world.

### Operating System

Windows 10

### Mod Version

0.4.0a

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
only happens on non-controllers
