### ISSUE TITLE
Documentation / instructions for the compilation of the mod 

### ISSUE THREAD

**Issue by SirMishaa** [Fabricators-of-Create/Create#581]
Hello, first of all I wanted to say that I love your work, it's incredible this portage.  Thank you, really. ❤️

I started a new world on the [Better Minecraft - Fabric modpack](https://www.curseforge.com/minecraft/modpacks/better-mc-fabric) and I would love to add Create to spice up my adventure.

I saw that there is a branch https://github.com/Fabricators-of-Create/Create/tree/mc1.19/fabric/dev for 1.19.
I don't know the state of work of this branch, but I've seen a lot of commits, I guess I can try to compile myself to be able to test? 

Can you provide me with instructions on how to compile with this branch? (I am a developer by profession, but unfortunately, I do not know Java). If the compilation tools are standard, I can document myself.

Also, I saw that you don't have the Github Sponsors donations enabled. I imagine people (including me) would be interested in donating for the work done. 

Thank you very much.

**Comment by JieningYu** [comment]
That branch isn't in 1.19 yet.

**Comment by TropheusJ** [comment]
that branch is identical to the 1.18 one currently. The update is in the works, there's a PR being worked on.
I really recommend just waiting for the release, but if you must, the PR can be compiled, but it's quite a process.

You'll need to checkout Alula's [Registrate](https://github.com/alula/Registrate-Refabricated) and [Flywheel](https://github.com/alula/Flywheel) forks and run `gradlew publishToMavenLocal` on both.
Then you can checkout their [Create fork](https://github.com/alula/Create-1.19.2) and run `gradlew build`. You'll find the jar in `build/libs`.
