### ISSUE TITLE
update of create mod

### ISSUE THREAD

**Issue by PJS69420** [Fabricators-of-Create/Create#582]
### Describe the Suggestion

i have been waiting to create a new minecraft server to play with my friends... they wanted me to use the create mod but i said it needs an update. so please update it so i can play minecraft with my friends.. p.s im running out of time so please update it fast

**Comment by EmpressAutumn** [comment]
I agree strongly with this high quality and very detailed suggestion. This is quite the linguistic masterpiece and would simply put English majors and Comp Sci majors to shame at the same time. Thank you for your input and improvement to this project.

**Comment by JieningYu** [comment]
I agree strongly with this high quality and very detailed suggestion. This is quite the linguistic masterpiece and would simply put English majors and Comp Sci majors to shame at the same time. Thank you for your input and improvement to this project.

**Comment by TropheusJ** [comment]
it's being worked on
