### ISSUE TITLE
more halp

### ISSUE THREAD

**Issue by PJS69420** [Fabricators-of-Create/Create#583]
### Describe the Suggestion

sooo with the previous commnet , i forgot to add one more thing
please put it on curseforge as well cuz my friends' computer cannot run fabric

**Comment by JieningYu** [comment]
1. "help" is not "halp".
2. this mod (Create Fabric) is already available on Curseforge.
3. If your friend's computer can't run Fabric you can use Create, which is a Forge mod (yes Create Fabric just port it to Fabric).
4. Curseforge is not Minecraft Forge.
5. you can edit your original issue.
