### ISSUE TITLE
1.19dev not compatible with twilightforest

### ISSUE THREAD

**Issue by ViceEye** [Fabricators-of-Create/Create#584]
### Describe the Bug

I self-build the 1.19dev branch cuz I wanna play 1.19.2 with Create.

But I discover Create is incompatible with twilight forest.

Here is the error log, I filtered out that twilight forest is not compatible not just guess.

https://github.com/Fabricators-of-Create/Create/files/9994446/crash-2022-11-12_15.17.21-client.txt

Just provides some info in the dev stage.

Thanks.

### Reproduction Steps

1. Install both twilight forest 1.19.2 and create dev1.19
2. Start the launcher, and try to create a new world
3. Error
...

### Expected Result

Fix the issue

### Operating System

Windows 11 & Debian 11

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

**Comment by AlphaMode** [comment]
Fixed in latest commit
