### ISSUE TITLE
1.19 Not Compatible With Wilder Wild

### ISSUE THREAD

**Issue by digitaltrucker** [Fabricators-of-Create/Create#585]
### Describe the Bug

Game crashes (mixin conflict, apparently).  Using Build 752.

### Reproduction Steps

1.Try to load game with Create and Wilder Wild.
2.
3.
...

### Expected Result

Game runs.

### Crash Report or Log

https://pastebin.com/6ybaY15L

### Operating System

Windows 10

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

	- advanced-xray-fabric 1.19-1.1.0-build.12
	- animal_feeding_trough 1.0.3+1.19.2
	- architectury 6.3.49
	- armorposer 1.2.0
	- autofish 0.9.5-SNAPSHOT
	- balm-fabric 4.5.2+0
	- bedspreads 6.0.0+1.19.2
	- beenfo 1.19.1-fabric0.58.5-1.3.3
	- betterf3 4.0.0
	- bitsandchisels 2.7.0
	- cherishedworlds 6.0.1+1.19.2
	- ciif 1.0.0+1.19
	- cleancut 1.19.2-5.1-fabric
	- clienttweaks 8.1.0
	- cloth-config 8.2.88
	- collective-fabric 5.15
	- companion 3.0.0
	- completeconfig 2.0.0
	- continuity 2.0.1+1.19
	- create 0.5.0f-752
	- customizableelytra 1.6.2-1.19
	- debugify 2.8.0
	- doubledoors-fabric 3.8
	- emi 0.4.1+1.19
	- enchantedshulkers 1.0.4
	- enchantinginfuser 4.2.2
	- endportalcraft 1.1.0
	- fabric-api 0.66.0+1.19.2
	- fabric-language-kotlin 1.8.6+kotlin.1.7.21
	- fabrication 3.1.3+1.19
	- fabricloader 0.14.10
	- faster_entity_animations 1.5.6
	- forgeconfigapiport 4.2.6
	- gildedarmor 1.5.0+fabric-1.19
	- guardvillagers 1.19.2-1.0.16
	- herdspanic 1.0.6
	- horsestatsvanilla 4.2.2
	- indium 1.0.9+mc1.19.2
	- interactic 0.1.11+1.19
	- iris 1.4.0
	- java 17
	- kiwi 8.1.2
	- krypton 0.2.1
	- lambdynlights 2.1.2+1.19
	- lazydfu 0.1.3
	- lightoverlay 7.0.0
	- litematica 0.12.4
	- litematicatool 1.0.0
	- lithium 0.10.2
	- lootr 0.4.22.61
	- malilib 0.13.0
	- memoryleakfix 1.19.1-0.7.0
	- minecraft 1.19.2
	- modmenu 4.1.0
	- moreculling 1.19.1-0.10.0
	- mousetweaks 2.22
	- netherportalfix 10.0.0
	- nochatreports 1.19.2-v1.13.11
	- notenoughanimations 1.6.2
	- polymorph 0.45.0+1.19.2
	- presencefootsteps 1.6.3
	- puzzleslib 4.3.12
	- raised 1.1.3
	- randomblockplacement 1.19.1-fabric0.58.5-1.1.4
	- reeses-sodium-options 1.4.7+mc1.19.2-build.59
	- registrate-fabric 1.1.39-MC1.19.2 via create
	- replaymod 1.19.1-2.6.8
	- rpg-hud 3.9.4
	- seasons 1.4-BETA+1.19
	- shulkerboxtooltip 3.2.2+1.19.2
	- skinned_lanterns 2.0.0
	- sleepwarp 1.2.0+1.19
	- sodium 0.4.4+build.18
	- sodium-extra 0.4.11+mc1.19.2-build.68
	- sound_physics_remastered 1.19.2-1.0.14
	- spyglass-improvements 1.4+mc1.19+fabric
	- starlight 1.1.1+fabric.ae22326
	- wandering_collector 1.1.3+mc1.19
	- wilderwild 1.1.1-Fabric+1.19.2
	- wiredredstone 0.4.8+1.19
	- worldedit 7.2.12+6240-87f4ae1
	- worldeditcui 1.19+01
	- xaeroworldmap 1.28.0

### Additional Context

Specifically, frozenblocklib from WIlder Wild conflicts with dripstone_fluid_lib according to Mixin Helper.

Note:  As stated earlier I am NOT using Create 0.50f, I'm using Build 752.

**Comment by JieningYu** [comment]
build 752 is in create 0.5.0f
and this should report to https://github.com/TropheusJ/dripstone-fluid-lib (I think)

**Comment by TropheusJ** [comment]
try with the latest build.

**Comment by digitaltrucker** [comment]
Seems to be working fine now.
