### ISSUE TITLE
[1.18.2] The Create mod crashes when creating the world

### ISSUE THREAD

**Issue by alazeprt** [Fabricators-of-Create/Create#587]
### Describe the Bug

When I was creating the world, the game crashed due to the Create module
Crash Report: 
[minecraft.log](https://github.com/Fabricators-of-Create/Create/files/9998567/minecraft.log)

### Expected Result

Can enter the world normally and use the Create mod

### Crash Report or Log

https://github.com/Fabricators-of-Create/Create/files/9998567/minecraft.log

### Operating System

Windows Server 2022

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

### Other Mods

- adapaxels 1.3.2+1.18.2
- additionalstructures 3.0.3
- advanced_runtime_resource_pack 0.5.5 via enhancedblockentities
- advancednetherite 1.5.1-1.18.2
- ae2 11.6.2
- ae2additions 3.1.2-fabric
- ae2things 1.1.1-beta.1
- aft_fabroads 1.0.1
- appleskin 2.4.1+mc1.18.2
- architectury 4.10.86
- basicshields 1.3.1-1.18.2
- bclib 1.4.7
- betteranimalsplus 1.18.2-11.0.5
- betterdroppeditems 1.3.2-1.18.2
- betterend 1.1.1
- betterf3 3.0.0
- betternether 6.1.2
- betterpingdisplay 1.1.1
- blue_endless_jankson 1.2.1 via jankson
- byg 1.4
- caffeineconfig 1.0.0+1.17 via sodium-extra
- chat_heads 0.6.0
- cloth-basic-math 0.6.1 via cloth-config
- cloth-config 7.0.69 via morevillagers
- collective-fabric 5.15
- com_electronwill_night-config_core 3.6.4 via terrablender
- com_electronwill_night-config_toml 3.6.4 via terrablender
- com_eliotlash_mclib_mclib 18 via geckolib3
- com_github_llamalad7_mixinextras 0.0.11 via porting_lib
- com_google_code_findbugs_jsr305 3.0.2 via create
- com_moandjiezana_toml_toml4j 0.7.2 via servertick
- create 0.5.0e-733
- createaddition ${version}
- crowdin-translate 1.4+1.18.2 via basicshields
- dripstone_fluid_lib 1.2.0 via milk
- durabilityviewer 1.18.2-fabric0.47.10-1.10.3
- emerald_tools 1.3.48
- enhancedblockentities 0.7.1+1.18.2
- error_notifier 1.0.9 via roughlyenoughitems
- expandeddelight 0.1.9.1
- fabric-api 0.66.0+1.18.2
- fabric-api-base 0.4.4+d7c144a860 via fabric-api
- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric-api
- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric-api
- fabric-block-api-v1 1.0.0+ee3621fc60 via fabric-api
- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric-api
- fabric-command-api-v1 1.1.9+d7c144a860 via fabric-api
- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric-api
- fabric-containers-v0 0.1.23+d7c144a860 via fabric-api
- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric-api
- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric-api
- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric-api
- fabric-data-generation-api-v1 3.0.2+9fcb91d260 via fabric-api
- fabric-dimensions-v1 2.1.20+489d6f8260 via fabric-api
- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric-api
- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric-api
- fabric-events-lifecycle-v0 0.2.19+d7c144a860 via fabric-api
- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric-api
- fabric-item-api-v1 1.5.2+17cbbd4360 via fabric-api
- fabric-item-groups-v0 0.3.14+91896a4960 via fabric-api
- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric-api
- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric-api
- fabric-language-kotlin 1.8.6+kotlin.1.7.21
- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric-api
- fabric-loot-api-v2 1.1.0+1997ad1260 via fabric-api
- fabric-loot-tables-v1 1.1.2+e747827960 via fabric-api
- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric-api
- fabric-models-v0 0.3.6+d7c144a860 via fabric-api
- fabric-networking-api-v1 1.0.23+2d30af4b60 via fabric-api
- fabric-networking-v0 0.3.10+b4f4f6cd60 via fabric-api
- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric-api
- fabric-particles-v1 0.2.12+526dc1ac60 via fabric-api
- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
- fabric-registry-sync-v0 0.9.11+bb2e047760 via fabric-api
- fabric-renderer-api-v1 0.4.15+ee3621fc60 via fabric-api
- fabric-renderer-indigo 0.5.5+41a02c8a60 via fabric-api
- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.8+ee3621fc60 via fabric-api
- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric-api
- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric-api
- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric-api
- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric-api
- fabric-resource-loader-v0 0.5.2+446e059560 via fabric-api
- fabric-screen-api-v1 1.0.10+d882b91560 via fabric-api
- fabric-screen-handler-api-v1 1.2.2+1f6558e860 via fabric-api
- fabric-textures-v0 1.0.12+3ac43d9560 via fabric-api
- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric-api
- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric-api
- fabricloader 0.14.10
- fabricshieldlib 1.5.3-1.18
- fake-player-api 0.3.0 via create
- fallingleaves 1.11.1+1.18.2
- farmersdelight 1.18.2-1.2.2
- fiber 0.23.0-2 via collective-fabric
- flywheel 0.6.4-30 via create
- forge_tags 2.1 via create
- forgeconfigapiport 3.2.0 via create
- gbfabrictools 1.3.4+1.18.2 via durabilityviewer
- geckolib3 3.0.77
- i18nupdatemod 3.0.0
- imm_ptl_core 1.3.5 via portalgun
- indium 1.0.7+mc1.18.2
- inventoryprofilesnext 1.8.5
- io_github_douira_glsl-transformer 1.0.0-pre21.2 via iris
- iris 1.4.0
- ironchests 1.7.4
- jankson 4.0.0+j1.2.0 via libgui
- java 18
- lambdynlights 2.1.0+1.17
- lanserverproperties 1.8
- libgui 5.4.2+1.18.2 via ironchests
- libipn 1.0.5
- libninepatch 1.1.0 via libgui
- litematica 0.11.3
- magna 1.7.0-1.18-pre1 via vanilla-hammers
- malilib 0.12.1
- maybe-data 1.3.0-1.18.2 via vanilla-hammers
- mcwbridges 2.0.5
- mcwfences 1.0.6
- mcwtrpdoors 1.0.7
- mcwwindows 2.0.3
- milk 0.3.2 via create
- minecraft 1.18.2
- minihud 0.22.1
- mm 2.3 via fabricshieldlib
- modmenu 3.2.4
- morevillagers 3.3.0
- mtr 1.18.2-3.1.8
- noindium 1.0.2+1.18.2 via ae2
- omega-config 1.2.3-1.18.1 via noindium
- ore_tree 1.0.0
- org_anarres_jcpp 1.4.14 via iris
- org_antlr_antlr4-runtime 4.10.1 via iris
- org_aperlambda_lambdajcommon 1.8.1 via spruceui
- org_jetbrains_kotlin_kotlin-reflect 1.7.21 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 1.7.21 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.21 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.21 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
- org_joml_joml 1.10.2 via sodium
- phosphor 0.8.1
- portalgun 3.0.2
- porting_lib 1.2.460-beta+1.18.2-dev.cca931b via create
- prefab 3.1.4
- pride 1.1.0+1.17 via lambdynlights
- pugh_tools 1.2.7 via emerald_tools
- q_misc_util 1.3.5 via portalgun
- randomshulkercolours-fabric 2.0
- reach-entity-attributes 2.1.1 via create
- reeses-sodium-options 1.4.7+mc1.18.2-build.58
- registrate-fabric MC1.18.2-1.1.4 via create
- reinfcore 3.0.3+1.18 via reinfshulker
- reinfshulker 2.2.0+1.18
- replaymod 1.18.2-2.6.8
- roughlyenoughitems 8.3.571
- roughlyenoughresources 2.5.0
- seasons 1.4-BETA+1.18
- serialization_hooks 0.3.23 via porting_lib
- servertick 1.6
- smoothboot 1.18.2-1.7.0
- sodium 0.4.1+replaymod.rev.23e83a1
- sodium-extra 0.4.11+mc1.18.2-build.67
- spark 1.9.11
- spruceui 3.3.0+1.17 via enhancedblockentities
- static-content 1.0.2-1.16.2 via vanilla-hammers
- staticdata 1.1.2 via static-content
- steel 1.3.0+1.18.2
- team_reborn_energy 2.2.0 via createaddition
- terrablender 1.2.0.126
- torcherino 16.0.1
- torohealth 1.18-fabric-2
- vanilla-hammers 3.4.0-1.18.2
- wi_zoom 1.4-MC1.18.2
- worldedit 7.2.10+1742f98
- worldeditcui 1.18.2+01
- xaerominimap 22.16.2
- xaeroworldmap 1.28.3

**Comment by ViceEye** [comment]
Caused by: java.lang.NullPointerException: Cannot invoke "org.spongepowered.asm.mixin.transformer.ClassInfo.hasSuperClass(org.spongepowered.asm.mixin.transformer.ClassInfo)" because the return value of "org.spongepowered.asm.mixin.transformer.ClassInfo.forType(org.objectweb.asm.Type, org.spongepowered.asm.mixin.transformer.ClassInfo$TypeLookup)" is null

Did your client crash with only Create?

It looks like one of your mod is crashed not Create

**Comment by JieningYu** [comment]
seems that porting lib's mixin conflict with immersive portals.

**Comment by alazeprt** [comment]
、

> 由：java.lang.NullPointerException： 无法调用“org.spongepowered.asm.mixin.transformer.ClassInfo.hasSuperClass（org.spongepowered.asm.mixin.transformer.ClassInfo）”，因为“org.spongepowered.asm.mixin.transformer.ClassInfo.forType（org.objectweb.asm.Type， org.spongepowered.asm.mixin.transformer.ClassInfo$TypeLookup）”的返回值为空
> 
> 您的客户端是否仅使用创建崩溃？
> 
> 看起来你的一个模组崩溃了而不是创建

After I uninstall Create, the game runs normally

**Comment by alazeprt** [comment]
> seems that porting lib's mixin conflict with immersive portals'.



> immersive portals'

I have not installed immersive portals

**Comment by JieningYu** [comment]
> > seems that porting lib's mixin conflict with immersive portals'.
> 
> > immersive portals'
> 
> I have not installed immersive portals

Portal Gun.

**Comment by alazeprt** [comment]
After uninstalling Portal Gun, the game runs successfully. Thank you for your help @JieningYu
