### ISSUE TITLE
The menu button is missing, when used with mods, that add their language files to minecraft namespace

### ISSUE THREAD

**Issue by SplendidAlakey** [Fabricators-of-Create/Create#588]
### Describe the Bug

The Create menu button is missing on 1.19.2, if any mod, that adds its own language files into the minecraft namespace, is also present.

### Reproduction Steps

1. Install [this build](https://github.com/Fabricators-of-Create/Create/actions/runs/3453518120) on Fabric
2. Install a mod, that adds its own language files to the minecraft namespace, e.g. [Incendium](https://www.curseforge.com/minecraft/mc-mods/incendium), [BetterBiomeBlend](https://modrinth.com/mod/better-biome-blend), [Consistency+](https://www.curseforge.com/minecraft/mc-mods/consistencyplus).
3. Run the game

### Expected Result

There should be a menu button.

### Operating System

Windows 10

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

[Incendium](https://www.curseforge.com/minecraft/mc-mods/incendium)
[BetterBiomeBlend](https://modrinth.com/mod/better-biome-blend)
[Consistency+](https://www.curseforge.com/minecraft/mc-mods/consistencyplus)

### Additional Context

~~The issue is exclusive to Fabric, Quilt is unaffected.~~

**Comment by JieningYu** [comment]
weird. Incendium is just a jarred datapack.

**Comment by AlphaMode** [comment]
The mod is closed source can't really do anything

**Comment by SplendidAlakey** [comment]
> The mod is closed source can't really do anything

Yeah, figured as much. Should I keep the issue open for visibility or nah?

**Comment by Skidamek** [comment]
Incendium is completely server-side, you can just remove it from client

**Comment by SplendidAlakey** [comment]
I'm not playing on a server, though.

**Comment by Skidamek** [comment]
Makes sense

**Comment by Skidamek** [comment]
However becouse Incendium mod is just a jarred datapack as JieningYu said, you can try to use a normal datapack version of Incendium https://www.planetminecraft.com/data-pack/incendium-nether-expansion/

**Comment by JieningYu** [comment]
No. there's a class in that mod

**Comment by AkashiiKun** [comment]
The class is just an event registry which does nothing.
(Blurred something as I'm not supposed to use a decompiler)
![image](https://user-images.githubusercontent.com/44606942/201678440-e60c6f5a-a8cc-4810-8835-e10ce051d4be.png)

And the only class is for forge.
Also, it doesn't even have the seed fix as is already in the vanilla game. So definitely with using the datapack is enough.

**Comment by JieningYu** [comment]
so.. why Incendium can cause that?

**Comment by SplendidAlakey** [comment]
It's caused by their language files somehow. I was wrong in my initial claim, that Quilt is unaffected by this bug, I just had my Incendium jar bootleg "patched". I moved their language files out of minecraft namespace to it's own to avoid a bug with Minekea. But I just tested a clean Incendium jar on Quilt and the bug occurred.

**Comment by SplendidAlakey** [comment]
I updated the issue to reflect the actual bug: the menu button disappears, if another mod adds its own language files to minecraft namespace. Removed the logs, because there's nothing in them anyway.

I've experienced a similar issue before with Minekea, except, in their case, blocks have broken translation strings: https://github.com/chimericdream/minekea-fabric/issues/67

**Comment by TropheusJ** [comment]
Issue is probably [this line](https://github.com/Fabricators-of-Create/Create/blob/50eaf4d1884d247a4f17126e251816fd9d21e867/src/main/java/com/simibubi/create/foundation/config/ui/OpenCreateMenuButton.java#L102)

**Comment by SplendidAlakey** [comment]
Not fixed. The issue became worse after the patch (build 766), the button now doesn't appear at all, no mods, en_us game language. But this time, the logs do seem to mention a related error: https://gist.github.com/SplendidAlakey/c2ad83bc17cbb5e3b7ea04cddddab941

**Comment by TropheusJ** [comment]
???

**Comment by TropheusJ** [comment]
Super weird. I've encountered this issue before with [Consistency+](https://github.com/ConsistencyPlus/ConsistencyPlus/issues/132). Somehow having lang in the vanilla namespace makes translations just not work at the stage the button is added.
