### ISSUE TITLE
1.19dev trains no highlighted tracks

### ISSUE THREAD

**Issue by Intiiii** [Fabricators-of-Create/Create#589]
### Describe the Bug

when creating a train, there is no highlighted tacks to place the train casing on.

### Reproduction Steps

1. place tracks
2. place the station
3. use the station
4. looking for highlighted track

### Expected Result

there will a highlighted tack appear

### Operating System

windows 10

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

**Comment by artemisSystem** [comment]
Cannot reproduce. It looks fine to me:
![2022-11-14_20 41 09](https://user-images.githubusercontent.com/39034386/201750846-20eed58c-8f7f-4fcd-8d8f-3ad26a6a49a3.png)

**Comment by Sheep7798** [comment]
Looks fine to me too

**Comment by AlphaMode** [comment]
Works fine. You probably forgot to assemble the station.
