### ISSUE TITLE
Virtual fluids do not render

### ISSUE THREAD

**Issue by PepperCode1** [Fabricators-of-Create/Create#59]
### Describe the Bug

Virtual fluids, like the potion and tea fluids, have no sprites, so they cannot be rendered.

### Reproduction Steps

1. Check uses for spout
2. Find a page that uses a potion or tea fluid, for example cinder flour -> redstone
3. See that the spout is empty

### Expected Result

The fluids should render as normal.

### Operating System

Windows 10

### Mod Version

0.4.0a

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
this was fixed at some point
