### ISSUE TITLE
(1.19dev) EMI support disabled but seems to work fine?

### ISSUE THREAD

**Issue by artemisSystem** [Fabricators-of-Create/Create#590]
### Describe the Bug

EMI support was removed in https://github.com/Fabricators-of-Create/Create/commit/77f25cc19ab35089dfeb93e88e12f1582f060d18, but reverting it seems to work completely fine, and i see no issues (apart from some untranslated tags, but those are unrelated to create and is the responsibility of EMI to fix, I've let her know). To me, it seems like this commit could be reverted again just fine?

### Reproduction Steps

Revert the mentioned commit

### Expected Result

Expect something to be wrong since the commit was reverted, but I'm seeing no errors in the log and everything seems to work fine.

### Operating System

macOS 13.1

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
Having EMI in dev but not enabled causes a crash and we haven’t looked into it yet
