### ISSUE TITLE
1.19dev Horizontal Rotating Contraptions Along East/West (X-Axis) provide wrong blockstates for wall items

### ISSUE THREAD

**Issue by Stereo528** [Fabricators-of-Create/Create#591]
### Describe the Bug

Horizontal Rotating Contraptions Along East/West (X-Axis) provide wrong blockstates for wall items. They end up floating in the air or looking as if they were placed on another block (they are still connected to the contraption and will rotate with it).

### Reproduction Steps

1. place mechanical bearing, andesite casing, and buttons (or any wall item like them) on all 4 sides.
2. rotate 90 degrees
3. buttons floating.

### Expected Result

buttons should stay attached the face of the contraption not "placed" on other blocks/air.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/52116771/201812570-f11a78d6-2edc-41c9-b3bc-120bc8ffcfe9.png) 
(shown: everything on the side is wrong blockstate)

![javaw_wvop1wsLeD](https://user-images.githubusercontent.com/52116771/201812580-778dcc41-5f7c-409c-a7e2-e848f533f554.png)
(shown: torches have wrong vertical blockstate, other items are correct)

![javaw_7OCYZB7ygk](https://user-images.githubusercontent.com/52116771/201812596-750db2f6-b0a2-4f70-8c81-8a2fe7660ce9.png) 
(shown: vertical & Z rotating contraptions do not have this problem)

### Operating System

Windows 11

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
identical to forge

**Comment by Stereo528** [comment]
will move it to there
