### ISSUE TITLE
TechReborn Zinc Ingot in mechanical press crashes the server

### ISSUE THREAD

**Issue by MSandro** [Fabricators-of-Create/Create#592]
### Describe the Bug

Hi,

when I try to press a Tech Reborn Zinc Ingot in a Create Mechanical Press the server crashes instantly.
not sure if its just modpack related but I hope someon can take a look.

### Reproduction Steps

1. try it in my Modpack Sky Fabrication 3 (v0.5.2 - 0.5.5) or use a unification script / mod which changes the recipe to use TechReborn Zinc
2. place Zinc on a Depot
3. place a Mechanical Press on top
4. Add some power to make it work
5. Crash

### Expected Result

should not crash the server

### Crash Report or Log

[crash-2022-11-15_20.05.52-server.txt](https://github.com/MSandro/sky_fabrication3/files/10015909/crash-2022-11-15_20.05.52-server.txt)

### Operating System

Linux

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

### Other Mods

many:
https://www.curseforge.com/minecraft/modpacks/sky-fabrication-3/files/4088157

**Comment by TropheusJ** [comment]
is this consistent? this shouldn't be able to happen.

**Comment by MSandro** [comment]
sorry it was just a misconfiguration on my side (I got empty output recipes in some create machines which caused the problem)

**Comment by TropheusJ** [comment]
What exactly did you change? Ignoring that this shouldn't happen in the first place, it *definitely* should not be fixed by data.

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/202985584-f0dcbc88-1f47-4ad3-98f1-46ca737ff0f9.png)
if there is a empty output recipe, it cause a crash.

I've added Zinc to the Unifikation List in a KubeJS Script, but forgot to undo my changes in the Datapack. It was a json file from Create Crafts & Addons.

**Comment by TropheusJ** [comment]
Okay, thanks.
