### ISSUE TITLE
[1.19dev] EMI Plugin Crashes & Burns

### ISSUE THREAD

**Issue by sylv256** [Fabricators-of-Create/Create#594]
### Describe the Bug

The EMI plugin fails to load *so hard* that EMI refuses to show any Create-based recipes. Furthermore, upon first creating a world, all recipes and items will disappear from EMI (this may be related to another mod).

### Reproduction Steps

1. EMI, QFAPI, and Create (dev)
2. Look at any Create-based recipe.
3.
...

### Expected Result

Instead of displaying Create recipes correctly, it straight up refuses to.

### Crash Report or Log

https://mclo.gs/pazSwiC

### Operating System

Linux 5.15.0-52-generic / Ubuntu 20.04

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

**Comment by CzechHek** [comment]
EMI support is intentionally disabled for now  because it caused crashes. Wait for final release.

**Comment by TropheusJ** [comment]
Due to a regression in loom it had to be disabled for the project to work in dev. I can get it into a release by temporarily re-adding it, but any unreleased version will be broken with EMI until loom fixes [this](https://github.com/FabricMC/fabric-loom/issues/725).

**Comment by sylv256** [comment]
classic loom moment...
