### ISSUE TITLE
1.19.2 Crash when loading world

### ISSUE THREAD

**Issue by Gamerbolts** [Fabricators-of-Create/Create#597]
### Describe the Bug

I am creating a rather large modpack, I have spent awhile going through all the mods and found that it seems to be something to due with the Global Data Packs mod.

### Reproduction Steps

1. Install Fabric 0.66.0 & Fabric 0.14.10
2. Install Create Fabric 0.5-0f-776
3. Install Global Packs 1.14.2
4. Try to create Single Player World
5. Crash to Desktop
...

### Expected Result

Load the world

### Crash Report or Log

https://pastebin.com/AcaLjDKm

### Operating System

Windows 10

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

Global Packs
Fabric API

### Additional Context

I have also posted this to the Global Packs github. Thanks!

**Comment by TropheusJ** [comment]
You had repurposed structures installed at one point and removed it. Now the game is crashing trying to find its structures.

**Comment by Gamerbolts** [comment]
I noticed that, I thought it was weird because I had removed the mod while testing. I will start from scratch with Global Packs and Create and see what happens
