### ISSUE TITLE
Incompatible with FabricaeExNihilo

### ISSUE THREAD

**Issue by EightBlade** [Fabricators-of-Create/Create#598]
### Describe the Bug

Installed the beta release of Create Fabric on my custom quilt modpack and get an immediate crash on start up. Log provided below.

### Reproduction Steps

1.Toggle Create on
2.Launch
3.
...

### Expected Result

The game to play. 

### Crash Report or Log

https://pastebin.com/AHvj8uLU

### Operating System

Windows 10

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

Included in crashlog.

**Comment by TropheusJ** [comment]
incompatibility with fabricaeexnihilo, [issue already made](https://github.com/LordDeatHunter/FabricaeExNihilo/issues/40)

**Comment by TropheusJ** [comment]
seems to have been resolved
