### ISSUE TITLE
Basin outputting to a chute causes a server crash on 1.19.2

### ISSUE THREAD

**Issue by CzechHek** [Fabricators-of-Create/Create#599]
### Describe the Bug

When basin outputs product of mixing or pressing into diagonally placed chute, it causes a server crash.

### Reproduction Steps

1. Make a contraption using Basin and Mechanical Press or Mixer.
2. Make Basin output item to a diagonally placed Chute.
3. The server will crash.

### Expected Result

Chute should transfer items without crashing server.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/42714212/202822328-12e0244f-0ba6-4c63-af63-a8551c63d398.png)

### Crash Report or Log

https://crashy.net/rNc4Y3teadNC3QYKcOHd

### Operating System

Windows 11

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

![image](https://user-images.githubusercontent.com/42714212/202822528-412c5d94-3aaf-4ff7-8b39-6e8df86bb544.png)

**Comment by CzechHek** [comment]
Additionally, while making the screenshot, I've noticed that if you remove the rotation source of a Mechanical Mixer while it is mixing the mixing animation doesn't stop. (can be seen on the screenshot)

**Comment by TropheusJ** [comment]
the mixing issue is known and happens on forge too.

**Comment by CzechHek** [comment]
Applies to Smart Chute as well btw.

**Comment by erisevaline** [comment]
Happens even with no other mods active.

**Comment by TheBigJHC2022** [comment]
It seems to be something specific to the spout part of outputting, was having the same issue, but placed a smart chute beneath with a filter item and it stopped crashing it. It's not a permanent solution but at least a workaround for the time being.

**Comment by CzechHek** [comment]
It doesn't crash anymore when trying it normally, however, my main world that was stuck in a crash loop is still stuck in the same crash loop with the same log.

**Comment by CzechHek** [comment]
Now it works, only thing I had to do was to replace the Basin that was causing the crash. Thank you for the additonal fix!
