### ISSUE TITLE
[TODO] Migrate to the official Mojang mappings

### ISSUE THREAD

**Issue by YTG1234** [Fabricators-of-Create/Create#6]
Assuming upstream does it too, it will massively help with compatibility, easier updating, and generally similarity to the Forge Create. There is no reason not to do it for the Forge version, it's even the default in newer Forge MDKs.  
You won't be able to contribute to Yarn if you saw Mojmap, and you'll need convert names to Yarn when asking for help in Fabricord, but those are the only reasons to not use Mojmap.

**When the time comes, how will we do it?**
- `gradle migrateMappings --mappings="net.minecraft:mappings:<version>"` will hopefully work, otherwise manual remapping or manual Mercury usage
- Apply the following patch to `build.gradle`:
```diff
--- build.gradle	2021-03-20 17:13:38.802497404 +0200
+++ build.gradle	2021-03-20 17:15:14.299166464 +0200
@@ -43,12 +43,7 @@
 
 dependencies {
 	minecraft("com.mojang:minecraft:${project.minecraft_version}")
-
-	/*
-	 *  TODO Mojmap
-	 *  mappings(minecraft.officialMojangMappings())
-	 */
-	mappings("net.fabricmc:yarn:${project.yarn_mappings}:v2")
+	mappings(minecraft.officialMojangMappings())
 	modImplementation("net.fabricmc:fabric-loader:${project.loader_version}")
 
 	// Fabric API. This is technically optional, but you probably want it anyway.

```
- And the following patch to `gradle.properties`:
```diff
--- gradle.properties	2021-03-16 20:50:35.858660233 +0200
+++ gradle.properties	2021-03-20 17:16:29.489168349 +0200
@@ -4,7 +4,6 @@
 # Fabric Properties
 # check these on https://fabricmc.net/use
 minecraft_version = 1.16.5
-yarn_mappings = 1.16.5+build.5
 loader_version = 0.11.3
 
 # Mod Properties

```

**Comment by machinesmith42** [comment]
Stay on yarn?

**Comment by PepperCode1** [comment]
> 
> 
> Stay on yarn?

While Yarn has the best names (IMO) out of the three main mapping sets (MCP, Mojang, and Yarn), it is not good for compatibility with upstream. If we stay on Yarn, then all upstream commits must be remapped to Yarn first before being merged. If Create switches to Mojang mappings and we switch to Mojang mappings, then no commits will have to be remapped, simplifying the job of maintaining this port significantly.

**Comment by machinesmith42** [comment]
auto remapper?

**Comment by PepperCode1** [comment]
I am not aware of any auto remappers, but if you're talking about something like YarnForge Plugin, that still takes a while to remap everything and setting it up to be automatic takes a lot of effort that should be spent on porting instead. Most of the code will be the same as in the Forge version anyway so I see no point in using Yarn specifically. We (the porting team members) discussed this a while ago and decided that there is no real benefit to using Yarn.

**Comment by YTG1234** [comment]
> decided that there is no real benefit to using Yarn.

...And if we need the Javadoc, we can just look it up in [Fabric Maven](https://maven.fabricmc.net/docs/yarn-1.16.5+build.5/).

**Comment by hYdos** [comment]
> You won't be able to contribute to Yarn if you saw Mojmap

You are making false statements of fact. i have contributed to yarn and have seen both Mojmap and Mcp.

**Comment by TropheusJ** [comment]
oh yeah this happened
