### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by Floris789** [Fabricators-of-Create/Create#600]
### Describe the Bug

it doesn't work. can you help me fix it? this is the error message:
![Schermafbeelding 2022-11-19 092344](https://user-images.githubusercontent.com/118595790/202841963-5fd4951a-b094-4459-9c06-71660a325387.png)

### Reproduction Steps

1. i downloaded the mod
2. I put the mod in the mods folder
3. The server works without the mod. and this is the error message

### Expected Result

I would expect it to work

### Screenshots and Videos

![Schermafbeelding 2022-11-19 092344](https://user-images.githubusercontent.com/118595790/202842346-e983b22f-7139-4945-94ef-cf0290c7633d.png)

### Crash Report or Log

19.11 08:07:34 [Server] Server thread/ERROR [worlds_together] Error for jar:file:///mods/create-1.19.2-0.5.0.f%20(1).jar: java.nio.file.NoSuchFileException: /fabric.mod.json

### Operating System

Windows 11

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

Oh The Biomes You'll Go
better end
origins
waystones
and some mods that is needed for them

**Comment by JieningYu** [comment]
what don't work

**Comment by AkashiiKun** [comment]
Most likely they downloaded the forge version. That's why it doesn't work.

**Comment by AkashiiKun** [comment]
The released jar for Fabric 1.19.2 is called "create-fabric-1.19.2-0.5.0f-776.jar" meanwhile the forge version is "create-1.19.2-0.5.0f.jar".
