### ISSUE TITLE
Blocks not loading properly when contraption stops on server

### ISSUE THREAD

**Issue by Rejfen** [Fabricators-of-Create/Create#602]
### Describe the Bug

When Create contraption stops moving and turns into blocks, they arent loaded properly and behave like blocks from unloaded chunk. However when contraption moves again it acts like it should. Re-logging into server loads blocks like it should. Reloading chunks in server also fixes it.

### Reproduction Steps

1.Activate glued create contraption on server
2.Stop It

### Expected Result

Blocks should load normally

### Screenshots and Videos

![2022-11-19_14 38 40](https://user-images.githubusercontent.com/117643234/202855229-b2665b3a-532d-47c4-b723-8b1bb108f71f.png)
![2022-11-19_14 38 46](https://user-images.githubusercontent.com/117643234/202855247-f5aaed34-0bab-483b-8770-466869f98f6c.png)
![2022-11-19_14 38 55](https://user-images.githubusercontent.com/117643234/202855250-f0f71b4c-30a2-4292-ba1f-d27e5ae3f81d.png)

### Operating System

Windows 10

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

### Other Mods

`
 ad_astra 1.0.4
	- additionaladditions 4.0.5
	- additionalentityattributes 1.0.0+1.18.2 via spectrum
	- adorn 3.5.0+1.18.2
	- advanced_reborn 1.1.0
	- advanced_runtime_resource_pack 0.5.7
	- advdebug 2.3.0
	- adventurez 1.4.11
	- alloy_forgery 2.0.13+1.18
	- almostunified 1.18.2-0.2.0
	- anchor 1.1.0
	- antiqueatlas 7.0.3-fabric-mc1.18.2
	- architects_palette 2.2
	- architectury 4.9.84
	- archon 0.3.2
	- artifacts 7.0.3+fabric
	- autoconfig1u 3.4.0 via advanced_reborn
	- automatone 0.7.0 via requiem
	- badpackets 0.1.2
	- balm-fabric 3.2.0+0
	- bannerpp 2.0.6-teb.1+mc.1.18.2 via spectrum
	- bclib 1.4.7
	- bedspreads 1.6.0-1.18
	- besmirchment 1.18.2-12
	- betteranimalsplus 1.18.2-11.0.5
	- betterdeserttemples 1.18.2-Fabric-1.3.1
	- betterdungeons 1.18.2-Fabric-2.1.0
	- betterend 1.1.1
	- betterfpsdist 1.18-1.8
	- betternether 6.1.2
	- betteroceanmonuments 1.18.2-Fabric-1.0.3
	- betterstrongholds 1.18.2-Fabric-2.1.1
	- bewitchment 1.18-23
	- biomemakeover 1.18.2-1.4.31
	- blabber 0.2.0 via requiem
	- blockus 2.4.8+1.18.2
	- blossom 1.0.5
	- blue_endless_jankson 1.2.1 via kyrptconfig
	- bookshelf 13.2.50
	- bosses_of_mass_destruction 1.3.9-1.18.2
	- botania 1.18.2-435-FABRIC
	- bwplus 1.18.2-17
	- byg 1.4
	- capybara 1.0.8
	- cardinal-components 4.2.0
	- cardinal-components-base 4.2.0 via cardinal-components
	- cardinal-components-block 4.2.0 via cardinal-components
	- cardinal-components-chunk 4.2.0 via cardinal-components
	- cardinal-components-entity 4.2.0 via cardinal-components
	- cardinal-components-item 4.2.0 via cardinal-components
	- cardinal-components-level 4.2.0 via cardinal-components
	- cardinal-components-scoreboard 4.2.0 via cardinal-components
	- cardinal-components-world 4.2.0 via cardinal-components
	- cauldronlib 1.2.2 via quicksand
	- cccbridge 1.3.0
	- ce 1.1.5
	- chime 1.2.1 via requiem
	- chipped 2.0.0
	- chisel 1.4.5
	- chord 1.8.0+1.18.2-fabric via wilderworld
	- cinderscapes 2.0.2
	- cinderscapes-common 2.0.2 via cinderscapes
	- cinderscapes-worldgen 2.0.2 via cinderscapes
	- cloth-api 3.2.64
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-client-events-v0 3.2.64 via cloth-api
	- cloth-common-events-v1 3.2.64 via cloth-api
	- cloth-config 6.4.87
	- cloth-config-lite 2.0.6 via mealapi
	- cloth-datagen-api-v1 3.2.64 via cloth-api
	- cloth-utils-v1 3.2.64 via cloth-api
	- com_electronwill_night-config_core 3.6.5 via couplings
	- com_electronwill_night-config_toml 3.6.5 via couplings
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 19 via geckolib3
	- com_fasterxml_jackson_core_jackson-annotations 2.13.1 via spoornpacks
	- com_fasterxml_jackson_core_jackson-core 2.13.1 via spoornpacks
	- com_fasterxml_jackson_core_jackson-databind 2.13.1 via spoornpacks
	- com_github_llamalad7_mixinextras 0.0.11 via porting_lib
	- com_github_shevek_parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6 via textile_backup
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_neovisionaries_nv-websocket-client 2.14 via mermod
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- comforts 1.1.3-1.18.2
	- computercraft 1.100.8
	- cosmetic-armor 1.3.1
	- couplings 1.8.0+1.18.2
	- create 0.5.0e-733
	- createaddition ${version}
	- createchunkloading 1.2.1
	- createplus 1.0
	- creeperoverhaul 1.3.1
	- crowdin-translate 1.4+1.18.2 via the_aether
	- ctov 2.9.2
	- customportalapi 0.0.1-beta50-1.18 via the_aether
	- customstars 1.1+1.18.2
	- cyti 1.0.6
	- dawn 3.3.2
	- dehydration 1.2.8
	- dragonfight 1.18.2-2.5
	- dragonloot 1.1.0
	- dripstone_fluid_lib 1.2.0 via milk
	- dustrial_decor 0.5
	- edenring 0.5.2
	- ellemes_container_lib 1.4.0-beta.2 via mythicmetals_decorations
	- enchanted-vertical-slabs 1.4.1
	- enderscape 0.3.4-1.18.2
	- endgoblintraders 1.5 (Re-upload)
	- endrem 5.1.0
	- enhancedcelestials 2.0.7
	- entitycollisionfpsfix 1.0.0
	- environmentz 1.2.2
	- error_notifier 1.0.9 via roughlyenoughitems
	- evs-betterend 1.0.0
	- expandability 6.0.0 via artifacts
	- expandeddelight 0.1.9.1
	- fabric-api 0.59.1+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric-api
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric-api
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric-api
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric-api
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric-api
	- fabric-containers-v0 0.1.23+d7c144a860 via fabric-api
	- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric-api
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric-api
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric-api
	- fabric-data-generation-api-v1 3.0.2+9fcb91d260 via fabric-api
	- fabric-dimensions-v1 2.1.20+489d6f8260 via fabric-api
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric-api
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric-api
	- fabric-events-lifecycle-v0 0.2.19+d7c144a860 via fabric-api
	- fabric-furnaces 2.1.1-1.18.2
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric-api
	- fabric-item-api-v1 1.5.2+17cbbd4360 via fabric-api
	- fabric-item-groups-v0 0.3.14+91896a4960 via fabric-api
	- fabric-language-kotlin 1.7.3+kotlin.1.6.20
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric-api
	- fabric-loot-api-v2 1.1.0+1997ad1260 via fabric-api
	- fabric-loot-tables-v1 1.1.2+e747827960 via fabric-api
	- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric-api
	- fabric-networking-api-v1 1.0.23+2d30af4b60 via fabric-api
	- fabric-networking-v0 0.3.10+b4f4f6cd60 via fabric-api
	- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric-api
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric-api
	- fabric-permissions-api-v0 0.1-SNAPSHOT via haema
	- fabric-registry-sync-v0 0.9.11+bb2e047760 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric-api
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric-api
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric-api
	- fabric-screen-handler-api-v1 1.2.2+1f6558e860 via fabric-api
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric-api
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric-api
	- fabricloader 0.14.10
	- factory_blocks 1.0.0+1.18.2
	- fake-player-api 0.3.0 via create
	- fallingtree 3.5.4
	- farmersdelight 1.18.2-1.2.1
	- farmersknives 1.3.1
	- farsight 1.18-1.9
	- farsighted-mobs 1.1-1.18
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via botania
	- forge_tags 2.1 via create
	- forgeconfigapiport 3.2.4
	- friendsandfoes 1.4.5
	- galosphere 1.18.2-1.1.1
	- gearreborn 1.18.2-0.1.14
	- geckolib3 3.0.67
	- geodes 1.4.2
	- go-fish 1.5.0-1.18.2
	- gobber2 2.5.80
	- goblintraders 1.5.1
	- graphlib 0.2.4+1.18.2 via wiredredstone
	- graveyard 1.9
	- guardvillagers 1.18.2-1.0.14
	- gud_recipe_confidence 1.0.2 via the_aether
	- haema 1.10.1+1.18.2
	- harvest_scythes 2.5.2+mc1.18.2
	- heartbond 1.3.0
	- icarus 1.11
	- iceberg 1.0.38
	- immersive_weathering 1.18.2-3.0.2
	- impersonate 2.5.0
	- incubus_core 1.7.1 via spectrum
	- infusion_table 1.1.0
	- interactic 0.1.10+1.18
	- inventorysorter 1.8.8-1.18
	- jamlib 0.0.5
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- jsonem 0.1.1 via phonos
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- kiwi 6.0.2
	- kleeslabs 11.1.1
	- krypton 0.1.9
	- kyrptconfig 1.4.6-1.18 via inventorysorter
	- lazydfu 0.1.2
	- libblockattributes_core 0.10.2 via libmultipart_deps_container
	- libgui 5.3.1+1.18 via mocolors
	- libmultipart 0.7.3-pre.4 via libmultipart_deps_container
	- libmultipart_deps_container 0.7.3-pre.4 via wiredredstone
	- libnetworkstack 0.6.0 via libmultipart_deps_container
	- libninepatch 1.1.0 via libgui
	- lithium 0.7.10
	- locki 0.7.0 via requiem
	- lovely_snails 1.0.4+1.18
	- maelstrom_library 1.2.4-1.18.2 via bosses_of_mass_destruction
	- magehand 1.1.2
	- magna 1.7.1-1.18-pre1 via mythicmetals
	- mantle 1.18.2-1.9.156 via tconstruct
	- mantori 1.0.0-1.18.2
	- mcwdoors 1.0.7
	- mcwfences 1.0.6
	- mcwlights 1.0.4
	- mcwpaintings 1.0.4
	- mcwpaths 1.0.1
	- mcwtrpdoors 1.0.7
	- mcwwindows 2.0.3
	- mealapi 0.3.1+1.18.2
	- medievalweapons 1.2.0
	- memoryleakfix 1.18.2-0.7.0
	- mermod 2.0
	- midnightlib 0.4.0 via puddles
	- milk 0.3.2 via create
	- minecraft 1.18.2
	- minekea 2.8.3
	- mm 2.3 via friendsandfoes
	- mobscarecrow 2.1.1
	- mocolors 1.4.0
	- moretags 3.0.4 via the_aether
	- mostructures 1.4.2+1.18.2
	- moyai 1.18.2-1.1.0
	- multipart_entities 1.1.5-1.18.2 via bosses_of_mass_destruction
	- mvs 2.2.5
	- myloot 2.1.4-1.18
	- mythicmetals 0.14.4
	- mythicmetals_decorations 0.2.2
	- mythicmounts 1.18.2-7.0
	- naturalist 1.1.0
	- nears 1.1.8
	- netherportalfix 9.0.0
	- notenoughcrashes 4.1.6+1.18.2
	- numismatic-overhaul 0.2.2+1.18
	- observable 2.2.3
	- omega-config 1.2.3-1.18.1 via mermod
	- org_apache_commons_commons-compress 1.21 via textile_backup
	- org_javassist_javassist 3.28.0-GA via yungsapi
	- org_jetbrains_kotlin_kotlin-reflect 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_reflections_reflections 0.10.2 via yungsapi
	- org_tukaani_xz 1.9 via textile_backup
	- owo 0.7.2-no-cme+1.18
	- pandemonium 2.0.0-beta.8
	- pandemoniumapi 2.0.0-beta.8 via pandemonium
	- patchouli 1.18.2-71.1-FABRIC
	- pehkui 3.5.0+1.14.4-1.19.2
	- pfm 1.1.1
	- phonos 0.3+1.18.2
	- platforms 1.2.5
	- playerabilitylib 1.5.1
	- pollen 1.5.0
	- polymorph 0.0.21-1.18.2
	- porting_lib 1.2.550-beta+1.18.2-stable via tconstruct
	- probablychests 0.5.5-1.18.2
	- programmerartinjector 1.2.1 via spectrum
	- promenade 2.6.3
	- puddles 1.2.1
	- pugh_lib 1.3.2 via gobber2
	- pugh_tools 1.2.7 via gobber2
	- quarrymod 0.7.3
	- quicksand 1.1.0
	- rare-ice 0.4.1
	- reach-entity-attributes 2.2.0 via mantle
	- reborncore 5.2.0
	- registrate-fabric MC1.18.2-1.1.4 via create
	- reinfbarrel 2.3.0+1.18
	- reinfchest 2.2.0+1.18
	- reinfcore 3.0.3+1.18 via reinfchest
	- reinfshulker 2.2.0+1.18
	- requiem 2.0.0-beta.9
	- requiem-core 2.0.0-beta.9 via requiem
	- requiemapi 2.0.0-beta.9 via requiem
	- revelationary 1.0.2
	- rightclickharvest 3.0.1+1.18
	- roughlyenoughitems 8.3.553
	- seasons 1.4-BETA+1.18
	- serialization_hooks 0.3.23 via tconstruct
	- shetiphiancore 1.2.14
	- skylorlib 1.5.1-1.18.2
	- smoothboot 1.18.2-1.7.0
	- snowrealmagic 4.1.3
	- someforgepatchesported 1.0.3
	- sound_physics_remastered 1.18.2-1.0.6
	- spectrum 1.5.7-1.18.2-magic
	- spirit 2.1.8
	- spoornpacks 4.2.3-1.18.2
	- stacc 1.3.0 via numismatic-overhaul
	- star 1.3+1.18.2 via mantle
	- starlight 1.0.2+fabric.89b8d9f
	- step-height-entity-attribute 1.0.0 via botania
	- stoneholm 1.4.3
	- structory 1.0.0
	- tconstruct 1.18.2-3.5.2.150
	- team_reborn_energy 2.2.0 via techreborn
	- techreborn 5.2.0
	- terrablender 1.2.0.126
	- terraform-biome-remapper-api-v1 3.1.0 via cinderscapes
	- terraform-config-api-v1 3.1.0 via terrestria
	- terraform-dirt-api-v1 3.1.0 via terrestria
	- terraform-shapes-api-v1 3.1.0 via cinderscapes
	- terraform-surfaces-api-v1 3.1.0 via terrestria
	- terraform-tree-api-v1 3.1.0 via terrestria
	- terraform-wood-api-v1 3.1.0 via cinderscapes
	- terrestria 4.0.3
	- terrestria-common 4.0.3 via terrestria
	- terrestria-worldgen 4.0.3 via terrestria
	- textile_backup 2.4.0-1.18
	- the_aether 1.6.9+1.18.2
	- things 0.2.18+1.18
	- thonkutil 2.14.1+1.18
	- thonkutil-base 1.12.2+23c1dc2c60 via thonkutil
	- thonkutil-capes-v1 1.3.2+9e23427060 via thonkutil
	- thonkutil-customization-v1 1.0.14+9b80223760 via thonkutil
	- thonkutil-legacy 1.0.20+9b80223760 via thonkutil
	- thonkutil-modchecker-v1 1.0.12+9b80223760 via thonkutil
	- thonkutil-potions-v0 1.4.1+9b80223760 via thonkutil
	- thonkutil-trades-v1 1.1.20+9b80223760 via thonkutil
	- timeoutout 1.0.1+1.18
	- tooltiprareness 1.0.4
	- trashslot 11.0.2
	- travelersbackpack 1.18.2-7.1.10
	- traverse 5.1.4
	- traverse-common 5.1.4 via traverse
	- traverse-worldgen 5.1.4 via traverse
	- trinkets 3.3.1
	- twigs 1.1.3-patch2+1.18.2
	- universal_ores 1.3.1
	- victus 0.1.11+1.18
	- waystones 2.5.5+mc1.18.2
	- wilderworld 2.2.2
	- windchimes 1.2.0
	- wiredredstone 0.3.7+1.18.2
	- wthit 4.13.3
	- yigd 1.3.10
	- yungsapi 1.18.2-Fabric-2.2.6
	- yungsextras 1.18.2-Fabric-2.1.0
`

### Additional Context

Bug only occured on server. Server is hosted on BisectHosting if that can be the issue

**Comment by TropheusJ** [comment]
Can't think of any known causes. Probably a mod incompat, can you try to narrow it down?

**Comment by Rejfen** [comment]
Sure but it might take some time.
