### ISSUE TITLE
Crash when creating a new world

### ISSUE THREAD

**Issue by Suntix06** [Fabricators-of-Create/Create#603]
### Describe the Bug

When trying to create a new world  the game crashes.

### Reproduction Steps

1. Press "Singleplayer" in the main menu
2. Press "Create New World"

### Expected Result

Opens the World Creation Menu.

### Screenshots and Videos

https://user-images.githubusercontent.com/111528555/202870444-50b6754e-def2-4d1c-907a-2b4e3e447c0c.mp4

### Crash Report or Log

https://gist.github.com/Suntix06/5ebeda4562069551cc7e6b114d66f1e7

### Operating System

Windows 11

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

3D Skin Layers
Accurate Block Placement
Appleskin
Architectury
BetterF3
Bookshelf Fabric
Boosted Brightness
Camera Utils
Fabric Capes
Custom Entity Models
Chat Heads
Chat Up!
CIT Resewn
Cloth Config
Complete Config
Continuity
Custom Crosshair Mod
Detailed Armor Bar
Effective
Enchantment Descriptions Fabric
Enhanced Block Entities
Entity Texture Features Fabric
Entity Culling Fabric
Essential
Fabric API
Carpet
Fabric Language Kotlin
Fabric Skyboxes
ForgetMeChunk
Illuminations
Indium
Iris
Item Model Fix
Lambda Better Grass
Lazy DFU
Litematica
Lithium
Malilib
Midnight Controlls
MiniHUD
ModMenu
NotEnoughAnimations
OptiGUI
Paperdoll Fabric
Pehkui
Plasmo Voice
Reeses Sodium Options
Roughly Enough Items
Sodium Extra
Sodium Fabric
Starlight
Tooltipfix
Tweakeroo
Ugly Scoreboard Fix
ViaFabric
Visuality
Wavey Capes
Worldedit
Xaeros Minimap
Xaeros Worldmap

**Comment by Suntix06** [comment]
It was not an issue caused by the create mod. I deleted it and the crash still happened.

**Comment by eizengan** [comment]
@Suntix06 are you using Sodium Extra; 0.4.12? That version causes a crash like the one shown. A patched version was made available earlier today
