### ISSUE TITLE
Mechanical Arm not keeping selection

### ISSUE THREAD

**Issue by AlexMessner** [Fabricators-of-Create/Create#608]
### Describe the Bug

When I hold the mechanical arm and right click blocks e.g. blaze burners for depositing items, it marks them, however when I place the arm down it always indicates "No targets".
No crash, mechanical arm just not working for me.

### Reproduction Steps

1. Hold mechanical arm
2. Right click blocks you want to deposit/pick up from
3. Place down mechanical arm

### Edit:
Only on server in survival
On Singleplayer creative, it works

### Expected Result

Mechanical arm to have selected blocks to deposit to

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/60109248/202897736-2cfc8fb9-f1cb-4ebe-a923-4c99ed74a267.png)
![image](https://user-images.githubusercontent.com/60109248/202897779-7dfd768e-9644-435e-bba7-e2b8b2087281.png)

### Operating System

Windows 11

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

**Comment by cplir-c** [comment]
Can confirm / Reproduced

**Comment by TropheusJ** [comment]
Can’t reproduce, please test patch G.

**Comment by Navinate** [comment]
On version create-fabric-1.19.2-0.5.0f-776 just tested this, works on single player.  Only worked once on multiplayer server out of maybe 40 tries.  Cannot reproduce it working on multiplayer.

**Comment by TropheusJ** [comment]
Please test 0.5.0g-791. If it still happens, provide your full mod list.

**Comment by bwhited** [comment]
Reproduced with 0.5.0g-791 installed on both client and server
Only other mods on both client/server:
fabric api 0.67.1
starlight-1.1.1

**Comment by saddomino** [comment]
Would like to butt in to say that I had this issue on patch F, and reduced my mods as much as possible to still have the same result. It worked properly on singleplayer, but wouldn't work on multiplayer.

I updated to patch G hoping it'd be fixed to have the same result. I tried a few different times and it wouldn't work at all. I wanted to contribute and record a video of it happening for a little proof. However, once I actually started recording, it miraculously started working.

I honestly have no idea what I did, but it works for me now after trying a few times. I'm now unable to reproduce the bug.

[Edit] Can verify Projector23's comment, I coincidentally had two mechanical arms when it suddenly "started working" for me.

**Comment by Projector23** [comment]
Can confirm, reproduced in singleplayer. it does work as intended in survival if you are holding 2+ mechanical arms and works in creative because you have infinite amount of them

**Comment by AlexMessner** [comment]
Reproduced in patch G, tried with holding 2+ as @Projector23 suggested, then also worked in survival.
Tried with a fresh mc fabric install with only fabric api 0.67.1 + create 0.5.0g-791

**Comment by TheGag96** [comment]
Confirming this also, just happened to me lol.
