### ISSUE TITLE
Tunnels not working in the Ponder.

### ISSUE THREAD

**Issue by OrvilleQ** [Fabricators-of-Create/Create#609]
### Describe the Bug

The Ponder page of Brass Tunnel and Andesite Tunnel's example are not working.

### Reproduction Steps

1. Ponder

### Expected Result

The demo should work.

### Screenshots and Videos

https://user-images.githubusercontent.com/21377465/202910963-72c24e10-32ec-4d99-ba4d-6293f43c2144.mp4

### Operating System

Windows 11

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

Mods:   [✔] 3dskinlayers-fabric-1.5.2-mc1.19.1   [✔] Adorn-3.7.0+1.19.2-fabric   [✔] antighost-1.19.1-fabric0.58.5-1.1.5   [✔] appleskin-fabric-mc1.19-2.4.1   [✔] appliedenergistics2-fabric-12.8.4   [✔] architectury-6.3.49-fabric   [✔] authme-mc1.19.2-4.2.0   [✔] badpackets-fabric-0.2.1   [✔] bclib-2.1.3   [✔] better-end-2.1.1   [✔] better-nether-7.1.2   [✔] BetterF3-4.0.0-Fabric-1.19.2   [✔] BetterPingDisplay-Fabric-1.19.2-1.1.1   [✔] cc-restitched-1.101.2   [✔] cloth-config-8.2.88-fabric   [✔] create-fabric-1.19.2-0.5.0f-776   [✔] cullleaves-fabric-3.0.0   [✔] dashloader-4.1.3+1.19   [✔] DistantHorizons-1.6.9a-1.19.2   [✔] dynamic-fps-2.2.0   [✔] enhancedblockentities-0.7.2+1.19.2   [✔] entityculling-fabric-1.5.2-mc1.19   [✔] expandeddelight-0.2.5   [✔] fabric-api-0.66.0+1.19.2   [✔] fabric-language-kotlin-1.8.6+kotlin.1.7.21   [✔] fabrishot-1.9.1   [✔] farmers-delight-fabric-1.19.X-1.3.5   [✔] ferritecore-5.0.0-fabric   [✔] gravestones-v1.13   [✔] indium-1.0.9+mc1.19.2   [✘] InventoryProfilesNext-fabric-1.19-1.8.5.jar (disabled)   [✔] iris-mc1.19.2-1.4.2   [✔] jmi-fabric-1.19.2-0.13-30   [✔] journeymap-1.19.2-5.9.0beta3-fabric   [✔] krypton-0.2.1   [✔] lazydfu-0.1.3   [✔] libIPN-fabric-1.19-1.0.6   [✔] lithium-fabric-mc1.19.2-0.10.2   [✔] mcwifipnp-1.5.6-1.19.1-fabric   [✔] memoryleakfix-1.19.1-0.7.0   [✔] midnightcontrols-1.7.1+1.19   [✔] modmenu-4.1.1   [✔] notenoughanimations-fabric-1.6.2-mc1.19.2   [✔] Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.11   [✔] owo-lib-0.8.5+1.19   [✔] Patchouli-1.19.2-77-FABRIC   [✔] PetOwner-1.8.3-1.19+   [✔] reeses_sodium_options-1.4.7+mc1.19.2-build.59   [✔] RoughlyEnoughItems-9.1.572   [✔] sodium-extra-0.4.13+mc1.19.2-build.76   [✔] sodium-fabric-mc1.19.2-0.4.4+build.18   [✔] spark-1.9.45-fabric   [✔] starlight-1.1.1+fabric.ae22326   [✔] TerraBlender-fabric-1.19.2-2.0.1.130   [✔] voicechat-fabric-1.19.2-2.3.15   [✔] wraith-waystones-3.0.5+mc1.19.2   [✔] wthit-fabric-5.13.4   [✔] YetAnotherConfigLib-1.7.1   [✔] Zoomify-2.8.0

**Comment by monkeybee11** [comment]
ah ok this is a bug was very confused XD
