### ISSUE TITLE
Cooking/Washing with a fan not working

### ISSUE THREAD

**Issue by BobBobson8** [Fabricators-of-Create/Create#611]
### Describe the Bug

Whenever i use a fan to cook/wash the item turns to air

### Reproduction Steps

1.have a item being cooked or wash
2.wait a few seconds
3.the item turns to air

### Expected Result

The item turns to air

### Screenshots and Videos

https://discord.com/channels/@me/1040434556353908816/1043956138590343301

### Operating System

Windows 11

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
Some items have chance based recipes, and they're working fine on my end. Without more information there's nothing I can do.
And your image/video is a link to a discord message in your DMs, which I do not have access to.
