### ISSUE TITLE
crashes with paradise lost on 1.18.2 newest

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [Fabricators-of-Create/Create#612]
### Describe the Bug

they crash on startup and i tried alternatively with a compatibility mod and they both crashed. i have tried multiple versions of create and they seemingly have the same issue.

### Reproduction Steps

1. install fabric, create, trinkets, and paradise lost.
2. crash instantly on startup
3.
...

### Expected Result

doesn't crash

### Crash Report or Log

https://gist.github.com/OrdinaryCloverOC/c5e31d8fb0b15a1be87faf67df56e498

### Operating System

ubuntu

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

### Other Mods

trinkets 3.3.1, paradise lost 1.6.9, fabric api 0.67.0

### Additional Context

prism launcher. i have also attempted separately with a compatibility mod that has been abandoned, same issue. all latest 1.18.2 versions. i tried using 1.19.2 versions up to date too, same problem. but paradise lost is beta 2.0 and that version may change soon.

**Comment by OrdinaryCloverOC** [comment]
it works with better mc fabric but not when only these mods are here. am i missing a mod?

**Comment by TropheusJ** [comment]
does it work if sodium is installed and Paradise Lost's compat is enabled?
