### ISSUE TITLE
Crash when launch

### ISSUE THREAD

**Issue by Zarpyk** [Fabricators-of-Create/Create#615]
### Describe the Bug

The game crash when launch if I use Create Fabric and Deep Mob Learning: Refabricated

### Reproduction Steps

1. Use these mods:
- create-fabric-1.19.2-0.5.0f-776.jar
- deepmoblearning-refabricated-0.5.7-BETA-build1.jar
- fabric-api-0.66.0+1.19.2.jar
- fabric-language-kotlin-1.8.6+kotlin.1.7.21.jar
2. Play game

### Expected Result

Join correctly to the game

### Crash Report or Log

https://gist.github.com/GuerreroBit/482b2b84062c1b74fd07781097a2b2ad

### Operating System

Windows 10

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

- deepmoblearning-refabricated-0.5.7-BETA-build1.jar
- fabric-api-0.66.0+1.19.2.jar
- fabric-language-kotlin-1.8.6+kotlin.1.7.21.jar

**Comment by drwoops** [comment]
i have the same issue. please just change the version number:
```Mod create uses the version 0.5.0f-776 which isn't compatible with Loader's extended semantic version format```

**Comment by TropheusJ** [comment]
that warning has nothing to do with the crash

**Comment by TropheusJ** [comment]
Can’t reproduce, please test patch G.

**Comment by Owl1001** [comment]
Even im having the same issue

**Comment by Zarpyk** [comment]
> Can’t reproduce, please test patch G.

Same error with patch G
More information:
- I'm using MultiMC 5 v0.6.16-3431
- Fabric 0.14.10
- Java v18.0.2.1
- (Now with fabric-api-0.67.1+1.19.2.jar)

Log: https://gist.github.com/GuerreroBit/0aee80c8046aa7376c6aa1335891a151#file-minecraft-latest-log
MultiMC Log: https://gist.github.com/GuerreroBit/0aee80c8046aa7376c6aa1335891a151#file-multimc-log

**Comment by TheSpiderDungeon** [comment]
Same issue. Load full mod list? Crash. Disable either Create or Deep Mob Learning? Works fine.

**Comment by Xetaxheb** [comment]
not remaking issue here but this: https://github.com/Creators-of-Create/Create/issues/4101#issuecomment-1340399094

**Comment by TropheusJ** [comment]
I believe this has been fixed in dev
