### ISSUE TITLE
milk bottles behave strangely on server 

### ISSUE THREAD

**Issue by kenshin33** [Fabricators-of-Create/Create#617]
### Describe the Bug

On multiplayer only.  When a bottle is used on a cow, it (bottle) gets filled with milk. 
In a single player world, drinking the milk is possible. In a server on the other hand, the drinking animation plays forever without draining said bottle. Also when a full bottle is thrown on the ground it is loses it's content (on a server only) 

### Reproduction Steps

1. start a new server 
2. get a bottle 
3. milk a cow
4. either try to drink the bottle or throw it away

### Expected Result

if thrown, the bottle should keep it's content.
if drunk, the bootle should be empty after a while.

on a server neither of the above outcomes happen.

### Operating System

linux

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

fabric-api (0.66.0), lithium(0.10.2), phosphor (0.8.1) ,  reeses_sodium_options (1.4.7)

**Comment by deli73** [comment]
Yeah this seems to be some kind of desync issue involving milklib, just experienced this ourselves yesterday while setting up a server.

**Comment by TropheusJ** [comment]
The bottle is supposed to be unobtainable unless a mod enables it, which create doesn’t. Guess the disable is only working on one side.

**Comment by deli73** [comment]
Yeah, it seems to be enabled on the client, oops!

**Comment by kenshin33** [comment]
I wasn't even aware of this, my son pointed it out when I upgraded our server to 1.19.2 
@deli73 you mean [this](https://github.com/TropheusJ/milk-lib/blob/fd683d0b444a564caf95a3b8bce0e822ace9e08b/src/main/java/io/github/tropheusj/milk/MilkClient.java#L37) ?

**Comment by deli73** [comment]
oh lmao that'd do it!

**Comment by TropheusJ** [comment]
how did I leave that in??? oops
