### ISSUE TITLE
[1.18.2] crash on start-up once updated FabricAPI and Create to newest Version

### ISSUE THREAD

**Issue by MSandro** [Fabricators-of-Create/Create#619]
### Describe the Bug

I have updated the Fabric API and Create to the newest versions in my Modpack Sky FABRICation 3.
Now it does not launch.
Fabric API: 0.67.0+1.18.2
Create-Fabric: 0.5.0g-788+1.18.2
Complete Modlist: https://www.curseforge.com/minecraft/modpacks/sky-fabrication-3/files/4088157

### Reproduction Steps

1. download & install my Modpack (v0.5.5): https://www.curseforge.com/minecraft/modpacks/sky-fabrication-3/files/4088157
2. update Create & FabricAPI
3. launch
4. crash

### Expected Result

it should load up like before

### Crash Report or Log

https://gist.github.com/MSandro/1b9b78a415c613310d55f9f8989c6d79

### Operating System

Linux

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

https://www.curseforge.com/minecraft/modpacks/sky-fabrication-3/files/4088157

**Comment by TropheusJ** [comment]
Please remove not enough crashes and try again

**Comment by MSandro** [comment]
thx now I see, it seems to be a issue with CreateAddition.
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	...
```
