### ISSUE TITLE
Crash with Iris

### ISSUE THREAD

**Issue by AeiouEnigma** [Fabricators-of-Create/Create#62]
### Describe the Bug

When Iris is installed, the game crashes upon placing a toolbox. Tested with magenta and blue toolboxes, presumably applies to all colors.

### Reproduction Steps

1. Install Create, Iris, and all dependencies thereof.
2. Place a toolbox (tested with blue and magenta, but again this almost certainly doesn't matter).
3. Experience crash.

### Expected Result

Crashn't

### Crash Report or Log

https://gist.github.com/AeiouEnigma/3f68ae11d161a457713149b871744000

### Operating System

Windows 11

### Mod Version

0.4.0b

### Minecraft Version

1.18.1

### Other Mods

Iris
Sodium

**Comment by AeiouEnigma** [comment]
Tested with Flywheel backend set to instancing.

**Comment by FoxieFlakey** [comment]
happen on Debian Linux 11 
but with large cogwheels for me

**Comment by soup587** [comment]
happens with me
win 11, latest nvidia drivers with sodium, iris, indium and create

on first placing a block the game outright crashes, reloading the world makes all flywheel based objects disappear
breaking and replacing whatever's invisible causes the game to lock up, the log printing the same error as the crash

**Comment by AlphaMode** [comment]
> happens with me win 11, latest nvidia drivers with sodium, iris, indium and create
> 
> on first placing a block the game outright crashes, reloading the world makes all flywheel based objects disappear breaking and replacing whatever's invisible causes the game to lock up, the log printing the same error as the crash

Could you try it without sodium installed and see if it still crashes

**Comment by TropheusJ** [comment]
iirc Iris does not allow you to launch the game without sodium installed.

**Comment by AlphaMode** [comment]
> iirc Iris does not allow you to launch the game without sodium installed.

There is builds without it; it just warns you that you should have it installed for performance

**Comment by AlsoSylv** [comment]
Iris without sodium displays a screen telling you to download sodium, prompting a link to CF or a Quit Game button, I think pepper talked to coderbot about iris compat in iriscord

**Comment by Noplace0** [comment]
In my case, I only uninstall iris then I would be able to place create a block in my world without crashing.

**Comment by RedWideWeb** [comment]
> In my case, I only uninstall iris then I would be able to place create a block in my world without crashing.

Please specify following versions:
Minecraft
Fabric

Mods versions:
Fabric API
Create
Sodium

**Comment by AeiouEnigma** [comment]
Fixed, though other Iris problems persist.
