### ISSUE TITLE
Mixer custom recipe misbehaving (1.19)

### ISSUE THREAD

**Issue by Abalieno** [Fabricators-of-Create/Create#620]
### Describe the Bug

I don't know if this is a skill issue, a probem of KubeJS, a problem with Create, or a problem with REI display of the recipe.

I'm trying to convert some kubejs scripts and recipes from 1.18. This one recipe works on 1.18.

On 1.19 I'm proceeding through a lot of trial and error since some things aren't working and KubeJS Create isn't out.

The script is currently working, but ignoring "count" on an item to be mixed (same for "compacting"). Same syntax on the "result" field instead works correctly. Only the inputs seem to ignore count.

The problem seems to be specific to Create mixing since using "count" elsewhere does work.

### Reproduction Steps

![ukik](https://user-images.githubusercontent.com/4656436/203500927-bb8be83f-7c82-4d20-a286-8d1776f53ac5.png)

This is the recipe I'm currently using. I commented out lines that were working on 1.18 but fail on 1.19

I've even tried other things but without success, the number of items is always ignored.

Same for the following, therefore I suspect it's a problem related to Create mixing recipes:

![iluil](https://user-images.githubusercontent.com/4656436/203501543-897f28b9-b99b-4ff7-b34d-84e5bf973fb7.png)

### Expected Result

The first image shows 1.19, the second 1.18

There should be 20 of those rotten flash items.

### Screenshots and Videos

![yikttluil](https://user-images.githubusercontent.com/4656436/203500216-b9fd2e85-956a-456d-abeb-0e9b8df3e880.png)
![tukyukrrr](https://user-images.githubusercontent.com/4656436/203500261-41c42354-0d1b-4402-a755-bfd9e820657f.png)

### Operating System

W10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by Abalieno** [comment]
bad bot, it's 1.19 only

**Comment by TropheusJ** [comment]
Try with a regular datapack recipe

**Comment by Abalieno** [comment]
I've added the following to a json under /kubejs/data/create/recipes

```{"type":"create:mixing","heatRequirement":"heated","ingredients":[{"count": 5, "item":"minecraft:obsidian"},{"item":"minecraft:ghast_tear"}],"results":[{"item":"minecraft:crying_obsidian"}]}```

With the same outcome.

I guess you want me to try entirely outside of kubejs but I tried moving the recipe under paxi without luck. Not sure how it's done with standard data packs, I've only used kubejs forms.

**Comment by Abalieno** [comment]
I managed to load the json through paxi, same behavior.

But then I also got a better idea, and added the json directly to the create.jar so it would be seen as a standard recipe.

...Same behavior.

**Comment by Abalieno** [comment]
I got a clever idea... and it works.

It should still be fixed properly I guess.

The following actually doesn't ignore count... since it doesn't use the count (can't ignore the count if it's not used...):

```"ingredients": [{"item": "minecraft:obsidian"},{"item": "minecraft:obsidian"},{"item": "minecraft:obsidian"},{"item": "minecraft:obsidian"},{"item": "minecraft:obsidian"},{"item": "minecraft:ghast_tear"}],```

This confirms it's not a display error, since this recipe shows properly in game.

**Comment by TropheusJ** [comment]
counts are not read for inputs, this is how it behaves on forge too
