### ISSUE TITLE
Ponder Keybind Conflict with InvMove Mod

### ISSUE THREAD

**Issue by BLOKBUSTR** [Fabricators-of-Create/Create#622]
### Describe the Bug

The current keybind for opening Ponder scenes interferes with the InvMove mod, causing unwanted player movement while holding the key to open a scene. Create automatically changes this keybind to match your own for forward movement, and InvMove follows this too. I tried searching through in-game configs and config files, but I could not find any way to change the keybind. Adding a config setting to customize the Ponder keybind would be the best solution.

I don't believe this issue is exclusive to any specific version of either mod.

### Reproduction Steps

1. Start game with the Create and InvMove mods, then enter a world;
2. Open inventory and hover over any Create item which has an associated Ponder scene;
3. Press and hold W, as instructed by the tooltip.

### Expected Result

Ponder will open normally, but InvMove will also respond to the W key, making the player move forward simultaneously. Player movement is not locked though, it stops when Ponder opens.

### Screenshots and Videos

Example video:
https://user-images.githubusercontent.com/118950712/203692878-1980914b-233e-4aae-8279-dc71452c78f3.mp4

### Operating System

MacOS

### Mod Version

0.5.0e

### Minecraft Version

1.18.2

### Other Mods

InvMove
https://www.curseforge.com/minecraft/mc-mods/invmove

**Comment by TropheusJ** [comment]
We don't change features, this should be suggested to the forge repo.
