### ISSUE TITLE
Possible incompatibility with Lithium 0.8.3

### ISSUE THREAD

**Issue by D0denT** [Fabricators-of-Create/Create#623]
### Describe the Bug

The game crashes whenever loading a world when Create is installed into mod folder with lithium

### Reproduction Steps

1.  Install create into mod folder that has lithium
2. load minecraft
3. try to create or load a world
4. the game crashes

### Expected Result

The game will crash immediately when the world is starting to load

### Crash Report or Log

https://bytebin.lucko.me/H9dWpWzMPO

### Operating System

Windows 10

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

- AdditionalStructures-1.19.x-(v.4.1.0)
- adventurez-1.4.16
- appleskin-fabric-mc1.19-2.4.1
- architectury-6.3.49-fabric
- badpackets-fabric-0.2.0
- balm-fabric-4.5.2+0
- BedBenefits-Fabric-1.19.2-9.1.2
- BetterAdvancements-Fabric-1.19.2-0.2.2.142
- BOMD-1.4.3-1.19.2
- Bookshelf-Fabric-1.19.2-16.1.5
- cardinal-components-api-5.0.2
- charm-fabric-1.19.2-4.4.4
- CITResewn-1.1.2+1.19.2
- cloth-config-8.2.88-fabric
- configured-fabric-2.0.0-1.19.2
- Controlling-fabric-1.19.2-10.0+6
- creeperoverhaul-2.0.3-fabric
- cullleaves-2.3.4
- dawn-3.5.0
- DungeonsArise-1.19-2.1.51-fabric-beta-hf
- EasyMagic-v4.3.2-1.19.2-Fabric
- ellemes-container-library-2.0.1+1.19-fabric
- elytraslot-fabric-6.0.0+1.19.2
- EnchantmentDescriptions-Fabric-1.19.2-13.0.3
- expandedstorage-8.0.1+1.19-fabric
- extended-armor-bars-1.2.1
- fabric-api-0.67.1+1.19.2
- fabric-language-kotlin-1.8.4+kotlin.1.7.20
- fabric-release-regrowth-1.19-31.0.0
- FallingTree-1.19.2-3.10.0
- farmers-delight-fabric-1.19.X-1.3.3
- ForgeConfigAPIPort-v4.2.6-1.19.2-Fabric
- forgetmechunk-1.0.4-1.18.X-1.19.X
- friendsandfoes-fabric-mc1.19.2-1.5.11
- geckolib-fabric-1.19-3.1.26
- goblin-traders-1.5.2
- guard-villagers-fabric-1.19.2-1.0.16
- Highlighter-1.19.1-fabric-1.1.4
- Iceberg-1.19.1-fabric-1.0.46
- indium-1.0.9+mc1.19.2
- inmis-2.7.1-1.19
- InventoryHUD-fabric-[1.19.1]+-3.4.2
- InventorySorter-1.8.10-1.19
- iris-mc1.19.2-1.4.0
- Jade-1.19.1-fabric-8.2.2
- jei-1.19.2-fabric-11.3.0.262
- JustEnoughProfessions-fabric-1.19-2.0.1
- JustEnoughResources-Fabric-1.19.2-1.1.0.179
- kleeslabs-fabric-1.19-12.1.0
- lambdabettergrass-1.3.0+1.19
- lambdynamiclights-2.1.2+1.19
- libIPN-fabric-1.19-1.0.3
- litematica-fabric-1.19.2-0.12.5
- lithium-fabric-mc1.19.2-0.8.3
- malilib-fabric-1.19.2-0.13.0
- midnightlib-0.6.1
- minihud-fabric-1.19.2-0.23.3
- modmenu-4.0.6
- morevillagers-fabric-1.19-4.0.2
- MouseTweaks-fabric-mc1.19-2.22
- netherportalfix-fabric-1.19-10.0.0
- NoChatReports-FABRIC-1.19.2-v1.13.9
- Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.13
- optigui-1.1.6
- PuzzlesLib-v4.3.12-1.19.2-Fabric
- shulkerboxtooltip-fabric-3.2.1+1.19.2
- sodium-fabric-mc1.19.2-0.4.4+build.18
- starlight-1.1.1+fabric.ae22326
- stoneholm-1.4.4
- TerraBlender-fabric-1.19.2-2.0.1.127
- Terralith_v2.3.5
- thonkutil-2.15.4+1.19
- Tips-Fabric-1.19.2-8.0.3
- TradingPost-v4.2.0-1.19.2-Fabric
- trinkets-3.4.0
- twilightforest-fabric-1.19.2-4.2.299
- universal_ores-1.4.2
- VanillaTweaks-fabric-1.19.2-1.5.63
- veinmining-fabric-1.0.0-beta.5+1.19.2
- villagernames-1.19.2-4.0.9
- voidtotem-fabric-1.19.2-2.1.0
- voidz-1.0.9
- worldedit-mod-7.2.12
- Xaeros_Minimap_22.16.0_Fabric_1.19.1
- XaerosWorldMap_1.28.1_Fabric_1.19.1
- YetAnotherConfigLib-1.6.0
- youre-in-grave-danger-1.4.4
- YungsApi-1.19.2-Fabric-3.8.2
- YungsBetterDesertTemples-1.19.2-Fabric-2.2.1
- YungsBetterDungeons-1.19.2-Fabric-3.2.1
- YungsBetterMineshafts-1.19.2-Fabric-3.2.0
- YungsBetterStrongholds-1.19.2-Fabric-3.2.0
- YungsBetterWitchHuts-1.19.2-Fabric-2.1.0
- YungsBridges-1.19.2-Fabric-3.1.0
- YungsExtras-1.19.2-Fabric-3.1.0
- Zoomify-2.8.0

**Comment by SplendidAlakey** [comment]
Lithium 0.8.3 is severely outdated, update it to 0.10.2. Also update Create to 0.5.0g.

**Comment by TropheusJ** [comment]
lithium works fine in my experience and you're using old versions. going to assume it's fixed.
