### ISSUE TITLE
Custom sequenced assembly recipe dosen't work in world

### ISSUE THREAD

**Issue by JieningYu** [Fabricators-of-Create/Create#624]
### Describe the Bug

I created a sequenced assembly recipe using qsl recipe api + `SequencedAssemblyRecipeBuilder` and it has been loaded into the game (can be shown in rei), but actually it dosen't work. ([source code](https://github.com/DM-Earth/Cabricality/blob/f60ae93522cee4a510029c725f5a55a21200372d/src/main/java/com/dm/earth/cabricality/content/core/threads/BrassThread.java))
The other create recipes added using qsl recipe api works fine.
The default Precision Mechanism recipe works fine, without overwriting using another mod.

### Reproduction Steps

1. add a sequenced assembly recipe using qsl recipe api + `SequencedAssemblyRecipeBuilder` that looks fine in rei.
2. can't make it work in world.

### Expected Result

It should work in world.

### Screenshots and Videos

<img width="404" alt="Screenshot@20221125202341" src="https://user-images.githubusercontent.com/61787533/203985658-c51e84f8-3edc-4028-bacb-adcfe45ecdcc.png">
<img width="360" alt="Screenshot@20221125202351" src="https://user-images.githubusercontent.com/61787533/203985677-d8f8a344-a431-4b0e-92b0-1e8ff11ae113.png">

The recipe:
<img width="781" alt="image" src="https://user-images.githubusercontent.com/61787533/203985796-cf78df9d-35f5-4d1b-8d61-a021aefcbb4f.png">

### Operating System

macOS 12.6.1

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

| Index | Mod                                               | ID                                                    | Version                      |
|------:|---------------------------------------------------|-------------------------------------------------------|------------------------------|
|   136 | Ad Astra!                                         | ad_astra                                              | 1.0.5                        |
|    19 | Amecs                                             | amecs                                                 | 1.3.8+mc.1.18.2              |
|    75 | Amecs API                                         | amecsapi                                              | 1.3.5+mc22w06a               |
|   113 | Applied Energistics 2                             | ae2                                                   | 11.6.2                       |
|   139 | Architect's Palette Fabric                        | architects_palette                                    | 2.2                          |
|   164 | Architectury                                      | architectury                                          | 4.10.86                      |
|    29 | Bad Packets                                       | badpackets                                            | 0.1.2                        |
|   106 | Better Runtime Resource Pack                      | better_runtime_resource_pack                          | 0.8.0                        |
|    14 | BitsAndChisels                                    | bitsandchisels                                        | 2.6.13                       |
|   165 | CC: Restitched                                    | computercraft                                         | 1.100.8                      |
|    86 | CC:C Bridge                                       | cccbridge                                             | 1.3.0                        |
|   170 | Cabricality                                       | cabricality                                           | 0.1-alpha2                   |
|    15 | CaffeineConfig                                    | caffeineconfig                                        | 1.0.0+1.17                   |
|    60 | Cardinal Components API (base)                    | cardinal-components-base                              | 4.1.3                        |
|    58 | Cardinal Components API (entities)                | cardinal-components-entity                            | 4.1.3                        |
|    22 | Cloth Config v6                                   | cloth-config                                          | 6.3.81                       |
|    16 | Cloth Utils v1                                    | cloth-utils-v1                                        | 2.0.54                       |
|    66 | CobbleGen                                         | cobblegen                                             | v2.1b57-BETA                 |
|    90 | ConnectedTexturesMod for Fabric                   | ctm                                                   | 1.0.0+1.18                   |
|    43 | Continuity                                        | continuity                                            | 2.0.1+1.18.2                 |
|   189 | Coxinha Utilities                                 | coxinhautilities                                      | 1.4.2+1.18.2                 |
|   178 | Create                                            | create                                                | 0.5.0g-792+1.18.2            |
|   166 | Create: Crystal Clear                             | create_crystal_clear                                  | 0.1e-1.18.2                  |
|   148 | CreatePlus                                        | createplus                                            | 1.0                          |
|     3 | CrowdinTranslate                                  | crowdin-translate                                     | 1.4+1.18.2                   |
|    74 | Custom Splash Screen                              | customsplashscreen                                    | 1.2.0                        |
|    13 | Dawn API                                          | dawn                                                  | 3.3.2                        |
|   105 | Dripstone Fluid Lib                               | dripstone_fluid_lib                                   | 1.2.0                        |
|    46 | Energy                                            | team_reborn_energy                                    | 2.2.0                        |
|    41 | EntityCulling-Fabric                              | entityculling                                         | 1.5.1                        |
|   100 | Error Notifier                                    | error_notifier                                        | 1.0.9                        |
|   138 | Extended Drawers                                  | extended_drawers                                      | 1.3.4+mc.1.18.2              |
|   112 | FTB Library                                       | ftblibrary                                            | 1802.3.7-build.154           |
|    36 | FTB Quests                                        | ftbquests                                             | 1802.3.8-build.106           |
|    53 | FTB Teams                                         | ftbteams                                              | 1802.2.7-build.71            |
|   190 | Fabric Data Generation API (v1)                   | fabric-data-generation-api-v1                         | 3.0.1+9fcb91d260             |
|   156 | Fabric Language Kotlin                            | fabric-language-kotlin                                | 1.8.5+kotlin.1.7.20          |
|    82 | Fake Player API                                   | fake-player-api                                       | 0.3.0                        |
|   149 | Farmer's Delight                                  | farmersdelight                                        | 1.18.2-1.2.2                 |
|   202 | FerriteCore                                       | ferritecore                                           | 4.2.1                        |
|    39 | Flywheel                                          | flywheel                                              | 0.6.8-32                     |
|   131 | Forge Config API Port                             | forgeconfigapiport                                    | 3.2.0                        |
|   101 | Forge Tags                                        | forge_tags                                            | 2.1                          |
|   108 | Graph Lib                                         | graphlib                                              | 0.2.4+1.18.2                 |
|   191 | Hephaestus                                        | tconstruct                                            | 1.18.2-3.5.2.155             |
|    59 | Here be no Dragons!                               | here-be-no-dragons                                    | 1.0.0                        |
|    79 | Indium                                            | indium                                                | 1.0.7+mc1.18.2               |
|    49 | Industrial Revolution                             | indrev                                                | 1.14.0-BETA                  |
|   158 | Inspecio                                          | inspecio                                              | 1.4.1+1.18                   |
|    72 | Interference API                                  | interference                                          | 1.4.1                        |
|    64 | Item Filters                                      | itemfilters                                           | 1802.2.7-build.33            |
|    54 | JMXL                                              | jmxl                                                  | 1.0                          |
|    35 | Jankson                                           | jankson                                  | 4.0.0+j1.2.0                 |
|    87 | Kibe                                              | kibe                                                  | 1.9.10-BETA+1.18             |
|    23 | Krypton                                           | krypton                                               | 0.1.9                        |
|    70 | LazyDFU                                           | lazydfu                                               | 0.1.2                        |
|   194 | Leaves Us In Peace                                | leaves_us_in_peace                                    | 1.0.11                       |
|    32 | LibBlockAttributes (Core)                         | libblockattributes_core                               | 0.10.0                       |
|    20 | LibBlockAttributes (Fluids)                       | libblockattributes_fluids                             | 0.10.0                       |
|    52 | LibBlockAttributes (Items)                        | libblockattributes_items                              | 0.10.0                       |
|   132 | LibGui                                            | libgui                                                | 5.3.2+1.18.2                 |
|    37 | LibNinePatch                                      | libninepatch                                          | 1.1.0                        |
|   102 | LibZoomer                                         | libzoomer                                             | 0.4.2+1.18.2                 |
|     5 | Light Emitting Diode                              | led                                                   | 1.2.4                        |
|   114 | Lithium                                           | lithium                                               | 0.7.10                       |
|   135 | Lootr                                             | lootr                                                 | 0.3.23.60                    |
|    21 | Magna                                             | magna                                                 | 1.7.0-1.18-pre1              |
|   196 | Malum (Quilt)                                     | malum                                                 | b1.0.10                      |
|    67 | Manningham Mills                                  | mm                                                    | 2.3                          |
|   133 | Mantle                                            | mantle                                                | 1.18.2-1.9.156               |
|   119 | Mconfig                                           | mconfig                                               | 1.2.0                        |
|    93 | Milk Lib                                          | milk                                                  | 0.3.2                        |
|   128 | Minecraft                                         | minecraft                                             | 1.18.2                       |
|   167 | Minecraft024                                      | m24                                                   | 0.1.0+1.18.2                 |
|    48 | MixinExtras                                       | com_github_llamalad7_mixinextras                      | 0.0.12                       |
|    96 | Mod Menu                                          | modmenu                                               | 3.2.4                        |
|   117 | Nature's Compass                                  | naturescompass                                        | 1.18.2-2.0.3-fabric          |
|    24 | No Indium?                                        | noindium                                              | 1.0.2+1.18.2                 |
|   125 | No Unused Chunks                                  | nounusedchunks                                        | 1.3                          |
|   146 | Ok Zoomer                                         | ok_zoomer                                             | 5.0.0-beta.7+1.18.2          |
|    81 | Omega Config GUI                                  | omega-config-gui                                      | 1.2.3-1.18.1                 |
|    40 | OmegaConfig                                       | omega-config                                          | 1.2.3-1.18.1                 |
|    88 | OpenJDK 64-Bit Server VM                          | java                                                  | 19                           |
|     8 | Pal                                               | playerabilitylib                                      | 1.5.0                        |
|   157 | Patchouli                                         | patchouli                                             | 1.18.2-66-FABRIC             |
|   163 | Porting Lib                                       | porting_lib                                           | 1.2.550-beta+1.18.2-stable   |
|    12 | Promenade                                         | promenade                                             | 2.6.3                        |
|   121 | Quests Additions                                  | questsadditions                                       | 1.4.0                        |
|   153 | Quilt Base API                                    | quilt_base                                            | 1.1.0-beta.26+1.18.2         |
|   169 | Quilt Biome API                                   | quilt_biome                                           | 1.1.0-beta.26+1.18.2         |
|   150 | Quilt Block Entity API                            | quilt_block_entity                                    | 1.1.0-beta.26+1.18.2         |
|    91 | Quilt Block Extensions API                        | quilt_block_extensions                                | 1.1.0-beta.26+1.18.2         |
|   168 | Quilt Client Command API                          | quilt_client_command                                  | 1.1.0-beta.26+1.18.2         |
|   141 | Quilt Command API                                 | quilt_command                                         | 1.1.0-beta.26+1.18.2         |
|   107 | Quilt Crash Info                                  | quilt_crash_info                                      | 1.1.0-beta.26+1.18.2         |
|   159 | Quilt DataFixerUpper API                          | quilt_datafixerupper                                  | 1.1.0-beta.26+1.18.2         |
|    95 | Quilt Dimension API                               | quilt_dimension                                       | 1.1.0-beta.26+1.18.2         |
|   111 | Quilt Item Group API                              | quilt_item_group                                      | 1.1.0-beta.26+1.18.2         |
|    83 | Quilt Item Setting API                            | quilt_item_setting                                    | 1.1.0-beta.26+1.18.2         |
|   192 | Quilt Lifecycle Events                            | quilt_lifecycle_events                                | 1.1.0-beta.26+1.18.2         |
|   171 | Quilt Loader                                      | quilt_loader                                          | 0.17.6                       |
|   183 | Quilt Networking                                  | quilt_networking                                      | 1.1.0-beta.26+1.18.2         |
|   186 | Quilt Recipe API                                  | quilt_recipe                                          | 1.1.0-beta.26+1.18.2         |
|   175 | Quilt Registry API                                | quilt_registry                                        | 1.1.0-beta.26+1.18.2         |
|   130 | Quilt Registry Entry Attachments                  | quilt_registry_entry_attachments                      | 1.1.0-beta.26+1.18.2         |
|   180 | Quilt Resource Loader                             | quilt_resource_loader                                 | 1.1.0-beta.26+1.18.2         |
|   177 | Quilt Screen API                                  | quilt_screen                                          | 1.1.0-beta.26+1.18.2         |
|   179 | Quilt Tags API                                    | quilt_tags                                            | 1.1.0-beta.26+1.18.2         |
|   126 | Quilt Tooltip API                                 | quilt_tooltip                                         | 1.1.0-beta.26+1.18.2         |
|   184 | Quilted Fabric API                                | quilted_fabric_api                                    | 1.0.0-beta.28+0.67.0-1.18.2  |
|   162 | Quilted Fabric API Base                           | quilted_fabric_api_base                               | 1.0.0-beta.28+0.67.0-1.18.2  |
|   173 | Quilted Fabric API Lookup API (v1)                | quilted_fabric_api_lookup_api_v1                      | 1.0.0-beta.28+0.67.0-1.18.2  |
|   161 | Quilted Fabric Biome API (v1)                     | quilted_fabric_biome_api_v1                           | 1.0.0-beta.28+0.67.0-1.18.2  |
|   204 | Quilted Fabric BlockRenderLayer Registration (v1) | quilted_fabric_blockrenderlayer_v1                    | 1.0.0-beta.28+0.67.0-1.18.2  |
|   145 | Quilted Fabric Command API (v1)                   | quilted_fabric_command_api_v1                         | 1.0.0-beta.28+0.67.0-1.18.2  |
|    92 | Quilted Fabric Commands (v0)                      | quilted_fabric_commands_v0                            | 1.0.0-beta.28+0.67.0-1.18.2  |
|   151 | Quilted Fabric Containers (v0)                    | quilted_fabric_containers_v0                          | 1.0.0-beta.28+0.67.0-1.18.2  |
|   198 | Quilted Fabric Content Registries (v0)            | quilted_fabric_content_registries_v0                  | 1.0.0-beta.28+0.67.0-1.18.2  |
|    99 | Quilted Fabric Convention Tags API (v1)           | quilted_fabric_convention_tags_api_v1                 | 1.0.0-beta.28+0.67.0-1.18.2  |
|    89 | Quilted Fabric Crash Report Info (v1)             | quilted_fabric_crash_report_info_v1                   | 1.0.0-beta.28+0.67.0-1.18.2  |
|   118 | Quilted Fabric Dimensions API (v1)                | quilted_fabric_dimensions_v1                          | 1.0.0-beta.28+0.67.0-1.18.2  |
|   152 | Quilted Fabric Entity Events (v1)                 | quilted_fabric_entity_events_v1                       | 1.0.0-beta.28+0.67.0-1.18.2  |
|   124 | Quilted Fabric Events Interaction (v0)            | quilted_fabric_events_interaction_v0                  | 1.0.0-beta.28+0.67.0-1.18.2  |
|   103 | Quilted Fabric Events Lifecycle (v0)              | quilted_fabric_events_lifecycle_v0                    | 1.0.0-beta.28+0.67.0-1.18.2  |
|   143 | Quilted Fabric Game Rule API (v1)                 | quilted_fabric_game_rule_api_v1                       | 1.0.0-beta.28+0.67.0-1.18.2  |
|   155 | Quilted Fabric Item API (v1)                      | quilted_fabric_item_api_v1                            | 1.0.0-beta.28+0.67.0-1.18.2  |
|   137 | Quilted Fabric Item Groups (v0)                   | quilted_fabric_item_groups_v0                         | 1.0.0-beta.28+0.67.0-1.18.2  |
|   205 | Quilted Fabric Key Binding API (v1)               | quilted_fabric_key_binding_api_v1                     | 1.0.0-beta.28+0.67.0-1.18.2  |
|   129 | Quilted Fabric Key Bindings (v0)                  | quilted_fabric_keybindings_v0                         | 1.0.0-beta.28+0.67.0-1.18.2  |
|   109 | Quilted Fabric Lifecycle Events (v1)              | quilted_fabric_lifecycle_events_v1                    | 1.0.0-beta.28+0.67.0-1.18.2  |
|   188 | Quilted Fabric Loot API (v2)                      | quilted_fabric_loot_api_v2                            | 1.0.0-beta.28+0.67.0-1.18.2  |
|    84 | Quilted Fabric Loot Tables (v1)                   | quilted_fabric_loot_tables_v1                         | 1.0.0-beta.28+0.67.0-1.18.2  |
|   201 | Quilted Fabric Mining Level API (v1)              | quilted_fabric_mining_level_api_v1                    | 1.0.0-beta.28+0.67.0-1.18.2  |
|   160 | Quilted Fabric Models (v0)                        | quilted_fabric_models_v0                              | 1.0.0-beta.28+0.67.0-1.18.2  |
|   142 | Quilted Fabric Networking (v0)                    | quilted_fabric_networking_v0                          | 1.0.0-beta.28+0.67.0-1.18.2  |
|   140 | Quilted Fabric Networking API (v1)                | quilted_fabric_networking_api_v1                      | 1.0.0-beta.28+0.67.0-1.18.2  |
|    98 | Quilted Fabric Object Builder API (v1)            | quilted_fabric_object_builder_api_v1                  | 1.0.0-beta.28+0.67.0-1.18.2  |
|   199 | Quilted Fabric Particles (v1)                     | quilted_fabric_particles_v1                           | 1.0.0-beta.28+0.67.0-1.18.2  |
|   127 | Quilted Fabric Registry Sync (v0)                 | quilted_fabric_registry_sync_v0                       | 1.0.0-beta.28+0.67.0-1.18.2  |
|   174 | Quilted Fabric Renderer - Indigo                  | quilted_fabric_renderer_indigo                        | 1.0.0-beta.28+0.67.0-1.18.2  |
|    85 | Quilted Fabric Renderer API (v1)                  | quilted_fabric_renderer_api_v1                        | 1.0.0-beta.28+0.67.0-1.18.2  |
|   144 | Quilted Fabric Renderer Registries (v1)           | quilted_fabric_renderer_registries_v1                 | 1.0.0-beta.28+0.67.0-1.18.2  |
|   115 | Quilted Fabric Rendering (v0)                     | quilted_fabric_rendering_v0                           | 1.0.0-beta.28+0.67.0-1.18.2  |
|   116 | Quilted Fabric Rendering (v1)                     | quilted_fabric_rendering_v1                           | 1.0.0-beta.28+0.67.0-1.18.2  |
|   147 | Quilted Fabric Rendering Data Attachment (v1)     | quilted_fabric_rendering_data_attachment_v1           | 1.0.0-beta.28+0.67.0-1.18.2  |
|   176 | Quilted Fabric Rendering Fluids (v1)              | quilted_fabric_rendering_fluids_v1                    | 1.0.0-beta.28+0.67.0-1.18.2  |
|    94 | Quilted Fabric Resource Conditions API (v1)       | quilted_fabric_resource_conditions_api_v1             | 1.0.0-beta.28+0.67.0-1.18.2  |
|   193 | Quilted Fabric Resource Loader (v0)               | quilted_fabric_resource_loader_v0                     | 1.0.0-beta.28+0.67.0-1.18.2  |
|   195 | Quilted Fabric Screen API (v1)                    | quilted_fabric_screen_api_v1                          | 1.0.0-beta.28+0.67.0-1.18.2  |
|   185 | Quilted Fabric Screen Handler API (v1)            | quilted_fabric_screen_handler_api_v1                  | 1.0.0-beta.28+0.67.0-1.18.2  |
|   187 | Quilted Fabric Textures (v0)                      | quilted_fabric_textures_v0                            | 1.0.0-beta.28+0.67.0-1.18.2  |
|   181 | Quilted Fabric Transfer API (v1)                  | quilted_fabric_transfer_api_v1                        | 1.0.0-beta.28+0.67.0-1.18.2  |
|   172 | Quilted Fabric Transitive Access Wideners (v1)    | quilted_fabric_transitive_access_wideners_v1          | 1.0.0-beta.28+0.67.0-1.18.2  |
|    31 | Reach Entity Attributes                           | reach-entity-attributes                               | 2.2.0                        |
|   182 | Registrate for Fabric                             | registrate-fabric                                     | MC1.18.2-1.1.5               |
|    77 | Roughly Enough Items                              | roughlyenoughitems                                    | 8.3.564                      |
|    47 | Satin                                             | satin                                                 | 1.7.2                        |
|   200 | Serialization Hooks                               | serialization_hooks                                   | 0.3.23                       |
|   123 | Sodium                                            | sodium                                                | 0.4.1+build.15               |
|    97 | Sodium Extra                                      | sodium-extra                                          | 0.4.11+mc1.18.2-build.67     |
|   203 | Splasher                                          | splasher                                              | 1.4.3                        |
|   197 | SpruceUI                                          | spruceui                                              | 3.3.3+1.18                   |
|     4 | Stacc                                             | stacc                                                 | 1.2.3                        |
|   104 | Star                                              | star                                                  | 1.3+1.18.2                   |
|   120 | Starlight                                         | starlight                                             | 1.0.2+fabric.89b8d9f         |
|     0 | Step Height Entity Attribute                      | step-height-entity-attribute                          | 1.0.0                        |
|   134 | Structures Compass                                | structures_compass                                    | 1.18.2-1.4.2                 |
|    34 | TerraBlender                                      | terrablender                                          | 1.1.0.102                    |
|    44 | Terraform Biome Remapper API (v1)                 | terraform-biome-remapper-api-v1                       | 3.1.0                        |
|    28 | Terraform Config API (v1)                         | terraform-config-api-v1                               | 3.1.0                        |
|     9 | Terraform Dirt API (v1)                           | terraform-dirt-api-v1                                 | 3.1.0                        |
|    25 | Terraform Shapes API (v1)                         | terraform-shapes-api-v1                               | 3.1.0                        |
|    30 | Terraform Surfaces API (v1)                       | terraform-surfaces-api-v1                             | 3.1.0                        |
|    55 | Terraform Tree API (v1)                           | terraform-tree-api-v1                                 | 3.1.0                        |
|    10 | Terraform Wood API (v1)                           | terraform-wood-api-v1                                 | 3.1.0                        |
|   110 | Terrestria                                        | terrestria                                            | 4.0.4                        |
|    78 | Terrestria: Client                                | terrestria-client                                     | 4.0.4                        |
|    71 | Terrestria: Common                                | terrestria-common                                     | 4.0.4                        |
|     6 | Terrestria: World Generation                      | terrestria-worldgen                                   | 4.0.4                        |
|     1 | Trinkets                                          | trinkets                                              | 3.3.1                        |
|    61 | apron                                             | de_poiu_apron_apron                                   | 2.1.1                        |
|    18 | atomicfu-jvm                                      | org_jetbrains_kotlinx_atomicfu-jvm                    | 0.18.4                       |
|    73 | cloth-basic-math                                  | cloth-basic-math                                      | 0.6.1                        |
|    33 | cloth-config-lite                                 | cloth-config-lite                                     | 2.0.6                        |
|    69 | core                                              | com_electronwill_night-config_core                    | 3.6.4                        |
|   122 | deferred_registries                               | deferred_registries                                   | 0.1.2                        |
|    80 | exp4j                                             | net_objecthunter_exp4j                                | 0.4.8                        |
|    65 | fabric-permissions-api                            | fabric-permissions-api-v0                             | 0.1-SNAPSHOT                 |
|    50 | fiber                                             | fiber                                                 | 0.23.0-2                     |
|    42 | jankson                                           | blue_endless_jankson                                  | 1.2.1                        |
|     7 | joml                                              | org_joml_joml                                         | 1.10.2                       |
|    62 | jsr305                                            | com_google_code_findbugs_jsr305                       | 3.0.2                        |
|    57 | kotlin-reflect                                    | org_jetbrains_kotlin_kotlin-reflect                   | 1.7.20                       |
|    51 | kotlin-stdlib                                     | org_jetbrains_kotlin_kotlin-stdlib                    | 1.7.20                       |
|    11 | kotlin-stdlib-jdk7                                | org_jetbrains_kotlin_kotlin-stdlib-jdk7               | 1.7.20                       |
|    17 | kotlin-stdlib-jdk8                                | org_jetbrains_kotlin_kotlin-stdlib-jdk8               | 1.7.20                       |
|    38 | kotlinx-coroutines-core-jvm                       | org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm     | 1.6.4                        |
|    56 | kotlinx-coroutines-jdk8                           | org_jetbrains_kotlinx_kotlinx-coroutines-jdk8         | 1.6.4                        |
|    27 | kotlinx-datetime-jvm                              | org_jetbrains_kotlinx_kotlinx-datetime-jvm            | 0.4.0                        |
|    45 | kotlinx-serialization-cbor-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm  | 1.4.1                        |
|    68 | kotlinx-serialization-core-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-core-jvm  | 1.4.1                        |
|     2 | kotlinx-serialization-json-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-json-jvm  | 1.4.1                        |
|    63 | oωo                                               | owo                                                   | 0.7.2+1.18                   |
|    76 | toml                                              | com_electronwill_night-config_toml                    | 3.6.4                        |
|    26 | velocity-native                                   | com_velocitypowered_velocity-native                   | 1.1.0-SNAPSHOT               |
|   154 | wthit                                             | wthit                                                 | 4.13.4                       |

**Comment by TropheusJ** [comment]
does it work as a JSON recipe?

**Comment by IThundxr** [comment]
If this still occurs on the latest version open a new issue
