### ISSUE TITLE
Crash with Iris on latest versions

### ISSUE THREAD

**Issue by Fourbo** [Fabricators-of-Create/Create#626]
When using Iris and Create Fabric together the game will not crash right away, but it will crash after several minutes. Not Enough Crashes identified these two as the conflicting mods.

**Mod Versions**
Create 0.5.0g
Iris Shaders 1.4.2
Fabric Loader 0.14.10
Fabric API 0.67.1

**Crash Report**
https://gist.github.com/Fourbo/9ca4ce92a0355ab4b521c666d61f3de3

**Comment by SplendidAlakey** [comment]
> Not Enough Crashes identified these two as the conflicting mods.

Which is most likely incorrect. Iris devs specifically tell uses to remove NEC before submitting any crash reports, because it incorrectly assumes Iris caused a crash, when it didn't.

**Comment by digitaltrucker** [comment]
I can confirm Iris works just fine with Ceate.

**Comment by TropheusJ** [comment]
Remove NEC and try again. If it still crashes send the new log.

**Comment by Fourbo** [comment]
I have played with for several hours after getting rid of NEC and no crash has ever happened again.
