### ISSUE TITLE
1.19.2 create breaks water physics

### ISSUE THREAD

**Issue by Khhs167** [Fabricators-of-Create/Create#630]
### Describe the Bug

When using the latest 1.19.2 build of the create fabric port, water physics for the player break. Swimming stops working, you sink like a rock, can't float upwards using space.

### Reproduction Steps

1. Create a fabric 1.19.2 server
2. Install the latest build of create, as of writing this it is 1.19.2 v0.5.0g
3. Try to swim

### Expected Result

That I am able to swim etc

### Screenshots and Videos

N/A

### Crash Report or Log

N/A

### Operating System

Linux

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Fabric API, other deps

### Additional Context

N/A

**Comment by artemisSystem** [comment]
i'm not experiencing this, is it happening with only create installed?

**Comment by Khhs167** [comment]
Correct

Den sön 27 nov. 2022 kl 09:47 skrev artemisSystem ***@***.***

**Comment by TropheusJ** [comment]
seems the water tag was invalid, need the log.

**Comment by Khhs167** [comment]
I managed to resolve this issue by disabling some mod on the client side, which I totally forgot about. Think it was Lithium that caused issues
