### ISSUE TITLE
boiler error with fluid

### ISSUE THREAD

**Issue by 3dguru** [Fabricators-of-Create/Create#633]
### Describe the Bug

any block attached to a boiler causes crash

### Reproduction Steps

1. created boiler
2. added blaze burner or any block
3. use pick to remove blaze burner or other blocks
...

### Expected Result

should remove block without crash

### Crash Report or Log

https://pastebin.com/FG57ATHi

### Operating System

macos 12 and windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by JieningYu** [comment]
try remove createaddition

**Comment by 3dguru** [comment]
That seem to be the problem ... thanks for the quick reply
