### ISSUE TITLE
Better End portals seem to have some interaction with trains, but error

### ISSUE THREAD

**Issue by Vexxen1** [Fabricators-of-Create/Create#634]
![2022-11-26_22 13 15](https://user-images.githubusercontent.com/59104027/204122231-d8944109-5ced-4977-8f07-e0de913ce74f.png)
![2022-11-26_22 13 37](https://user-images.githubusercontent.com/59104027/204122235-c9503e3b-abe2-4c4c-86ca-413e97050ead.png)

It would be great if this worked, but im not sure if you are willing too. If this did work, then multidimenonal lines would be a thing. Well into the end trains would work. I tryed the trains with a few other portal mods, and none worked, only better end did.

**Comment by TropheusJ** [comment]
adding compatibility should be pretty easy now

**Comment by butterflysky** [comment]
I added a pull request against the 1.20.1 branch here: https://github.com/Fabricators-of-Create/Create/pull/1626
