### ISSUE TITLE
Can't modify certain recipes with kubejs (1.19)

### ISSUE THREAD

**Issue by Abalieno** [Fabricators-of-Create/Create#638]
### Describe the Bug

I'm not sure if it's a problem in Create or KubeJS: https://github.com/KubeJS-Mods/KubeJS/issues/531#issuecomment-1328270758

I had vaguely similar problems with Modern Industrialization, and the last update of the mod fixed those issues: https://github.com/KubeJS-Mods/KubeJS/issues/544

As described:
I'm having issues in Create 1.19 even when a mod and type is specified. I've tried lots of combinations, none seem to work:

```
event.remove({id: "create:copper_sheet"})
event.replaceInput({mod: "create"}, "create:copper_sheet", "modern_industrialization:copper_plate")
event.replaceOutput({mod: "create"}, "create:copper_sheet", "modern_industrialization:copper_plate")
event.replaceOutput({id: "create:copper_ingot"}, "create:copper_sheet", "modern_industrialization:copper_plate")
event.replaceOutput({id: "create:pressing/copper_ingot"}, "create:copper_sheet", "modern_industrialization:copper_plate")
event.replaceOutput({type: "create:pressing"}, "create:copper_sheet", "modern_industrialization:copper_plate")
```

![iloil](https://user-images.githubusercontent.com/4656436/204143544-82087583-9b86-4d99-9c02-b717eafdded6.png)

### Reproduction Steps

Just trying to edit recipes.

### Expected Result

Recipes showing correctly.

### Operating System

W10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
Report to KubeJS.

**Comment by MaxNeedsSnacks** [comment]
replaceInput / replaceOutput needs explicit integration in 1.19 to stop us from having to guess inputs / outputs from recipe JSONs directly; this will likely be "fixed" when KubeJS Create comes out, which due to more major internal refactors coming up won't be for another couple of weeks.

@TropheusJ Feel free to close this issue, since it doesn't apply to Create Fabric
