### ISSUE TITLE
Create + REI Crash

### ISSUE THREAD

**Issue by spunchbop121** [Fabricators-of-Create/Create#639]
### Describe the Bug

Crash log: https://pastebin.com/8kD1PbC0

### Reproduction Steps

1. Join the world
2. Open the inventory
3. Start scrolling through the REI list of items.
4. Game crashes.

### Expected Result

The game should not have crashed while viewing the list of items.

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by SplendidAlakey** [comment]
Bubble blower is a Supplementaries' item. I'm unable to reproduce this, though, so I don't think it has anything to do with either Create or REI.

**Comment by AsheX1** [comment]
ya this does not seem to be a create problem

**Comment by TropheusJ** [comment]
Create is not mentioned in the log at all, I don't think it's our issue.
