### ISSUE TITLE
Crash on dedicated server

### ISSUE THREAD

**Issue by badgermemelord** [Fabricators-of-Create/Create#64]
### Describe the Bug

Near instant crash when trying to start a dedicated server with the latest build (and previous ones to my knowledge)
Mods: create v0.4b, fabric-API 0.45.0,
fabric loader 0.12.12

### Reproduction Steps

1. Create dedicated server with those mods
2. Start
3. Crash
...

### Expected Result

Working server

### Crash Report or Log

https://pastebin.com/ndxip6Bi

### Operating System

Windows 10

### Mod Version

0.4.0a

### Minecraft Version

1.18.1

### Other Mods

None

**Comment by Oliver-makes-code** [comment]
This issue occurs because Fabric doesn't load Flywheel due to it's environment being Client only.

Edit: The class that Create tries to access (com.jozufozu.flywheel.light.LightListener) uses Client only FAPI modules

**Comment by TheEpicBlock** [comment]
Flywheel appears to be made to be included into the client. As that's what Create Forge seems to do. Changing the fabric.mod.json environment seems to work. There are also some references to `FluidVariantRendering` in `AllFluids`

**Comment by TropheusJ** [comment]
this should be fixed, reopen if it is not.
