### ISSUE TITLE
Crashes whenever joining server

### ISSUE THREAD

**Issue by Bloopything** [Fabricators-of-Create/Create#640]
### Describe the Bug

game disconnects whenever joining server.

### Reproduction Steps

1. i dont know
2.
3.
...

### Expected Result

a

### Crash Report or Log

https://pastebin.com/LwgkafMZ

### Operating System

Windows 11

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

**Comment by terminal-cs** [comment]
i am having this issue too, if anyone can fix this it would be nice. OP should have added more information but the log itself is enough.

**Comment by AsheX1** [comment]
> ### Describe the Bug
> 
> game disconnects whenever joining server.
> ### Reproduction Steps
> 
>     1. i dont know
> 
> 
> ...
> ### Expected Result
> 
> a
> ### Screenshots and Videos
> 
> _No response_
> ### Crash Report or Log
> 
> https://pastebin.com/LwgkafMZ
> ### Operating System
> 
> Windows 11
> ### Mod Version
> 
> 0.5.0f
> ### Minecraft Version
> 
> 1.19.2
> ### Other Mods
> 
> _No response_
> ### Additional Context
> 
> _No response_

that not the crash log that just the console log....

go in the crash-reports folder and get the crash log from there not the console log

**Comment by TropheusJ** [comment]
Your versions of Create on the client and server do not match. Due to changes in contraption data, they need to.

**Comment by terminal-cs** [comment]
> Your versions of Create on the client and server do not match. Due to changes in contraption data, they need to.

I do not have create installed on the server and it still causes issues

**Comment by terminal-cs** [comment]
> Reference in new i

also why would you make it crash if it's a different version, very bad design imo

**Comment by TropheusJ** [comment]
> I do not have create installed on the server and it still causes issues

Well if you have it on the client and not server, then of course it won't work right.
If you have it on neither, then this is not a Create issue.

> also why would you make it crash if it's a different version, very bad design imo

The crash is not intentional. It's an unavoidable side effect of completely changing how contraption data is sent.

**Comment by terminal-cs** [comment]
> 

so basicly you are just saying that if I want to play a server that I need to go manually disable the mod because the developers can't make the program right?

**Comment by terminal-cs** [comment]
> > I do not have create installed on the server and it still causes issues
> 
> Well if you have it on the client and not server, then of course it won't work right. If you have it on neither, then this is not a Create issue.
> 
> > also why would you make it crash if it's a different version, very bad design imo
> 
> The crash is not intentional. It's an unavoidable side effect of completely changing how contraption data is sent.

why does it need to change that tho

**Comment by TropheusJ** [comment]
> so basicly you are just saying that if I want to play a server that I need to go manually disable

...yes? this is the case with all content mods. Things will not work correctly if you leave them on. If your game hasn't crashed from it, you've been lucky. No modder will support a desynchronized state.

> because the developers can't make the program right?

If you think you can do it better, PRs are accepted. 

> why does it need to change that tho

because the old way caused crashes.

**Comment by terminal-cs** [comment]
> > so basicly you are just saying that if I want to play a server that I need to go manually disable
> 
> ...yes? this is the case with all content mods. Things will not work correctly if you leave them on. If your game hasn't crashed from it, you've been lucky. No modder will support a desynchronized state.
> 
> > because the developers can't make the program right?
> 
> If you think you can do it better, PRs are accepted.
> 
> > why does it need to change that tho
> 
> because the old way caused crashes.

never in my experience of using mods have I ran into issues relating to the server not having them installed

I will not do better, because java is not my main language and this would be too big of a project for me to drastically change.
