### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by cyrxdzj** [Fabricators-of-Create/Create#641]
### Describe the Bug

I downloaded it, but it doesn't work.

### Reproduction Steps

1.Download the Minecraft 1.19.2 with Fabric 0.14.10
2.Download the Create and other mods into the mods directory
3.Launch Minecraft.
4.It doesn't work.
All the mod I downloaded:
![image](https://user-images.githubusercontent.com/63708985/204214879-e0c5dae8-dfcb-4019-b810-c56bb7ed2b38.png)

### Expected Result

I want it to work.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/63708985/204215534-f84ae4be-e24e-40d7-b9a1-8d4ffb9ba9f2.png)
As you can see, there are no Create objects here.

### Operating System

Windows 11

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

![image](https://user-images.githubusercontent.com/63708985/204214879-e0c5dae8-dfcb-4019-b810-c56bb7ed2b38.png)

**Comment by JieningYu** [comment]
you are using Create Forge 😆

**Comment by cyrxdzj** [comment]
@JieningYu Oh, it worked after I downloaded the Fabric version. Thank you.
