### ISSUE TITLE
Crash with Simple Shelves

### ISSUE THREAD

**Issue by Gatornator** [Fabricators-of-Create/Create#643]
### Describe the Bug

I have a schematic cannon in my world for building my house. It seems to cause a crash when I shift click a book into the slot for getting a material list. It may be another mod conflict on my end, but I wanted to share this just in case.

Thank you,
Hope you had a great thanksgiving and have a great day. Hope you can resolve this!

### Reproduction Steps

1.Place a schematic cannon
2.Get a regular book
3.Shift click a book into the cannon
...

### Expected Result

The schematic cannon to create a material list by shift clicking a regular book into the device.

### Crash Report or Log

https://gist.github.com/Gatornator/83f5150b1a3e6b4f4feaaf73728dd739

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by kenshin33** [comment]
not certain  but it looks like SimpleShelves is the problem here .

**Comment by SplendidAlakey** [comment]
Just tested in my own pack with both Create and SimpleShelves, can't reproduce. OP, upload the full log.

**Comment by kenshin33** [comment]
I just tried a schematic with  a block from  SimpleShelves.  The second the book is in the cannon  to get the material list the games crashes. 
Also tried with regular blocks (a tree) , didn't trigger the crash.  

[schematic I used and crash-report ](https://0.0g.gg/?a8989425e5ba90d8#ALcrtETj4HqTh1J52et5YhWGtvVicrERrGKQ1kP1hpmx)  
edit: 
sorry ticked the burn after reading and and visited the link :facepalm:

**Comment by Gatornator** [comment]
I’ll have to test this. Thanks for the advice

**Comment by TropheusJ** [comment]
yes, issue with Simple Shelves. opened an issue: https://github.com/Pinaz993/SimpleShelves/issues/5

**Comment by TropheusJ** [comment]
Simple Shelves has updated to fix this.
