### ISSUE TITLE
Better End Chandelier is not recognized as connected within a Super Glue selection.

### ISSUE THREAD

**Issue by LividJava** [Fabricators-of-Create/Create#645]
### Describe the Bug

The Better End chandeliers are not recognized as being connected to the adjacent blocks.

### Reproduction Steps

1. Using Create version 0.5.0g, BCLib 2.1.4, and Better End 2.1.2.
2. Place a Chandelier on a block.
3. Attempt to create a glue-up

### Expected Result

You should have to ability to successfully create a glue up with the blocks, as you would with vanilla torches or lanterns.

### Screenshots and Videos

Screenshot of inability to make a glue up

![image](https://user-images.githubusercontent.com/7604544/204497805-b01421dc-c0f0-4905-8904-9f8ef32fb3fd.png)

Screenshot of a successful glue up but the Chandelier is not a part of the glue up

![image](https://user-images.githubusercontent.com/7604544/204499124-d823ee06-540d-4727-9225-ce13cc64ebfb.png)

### Operating System

Endeavour OS, Kernel: 6.0.8-arch1-1

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

 - BCLib 2.1.4 (required for Better End)
 - Better End 2.1.2

### Additional Context

In the screenshots above the debug screen is open to show the block states, The chandelier only has a single editable block state, it uses "facing:" with 6 possible values.

I speculate that this *may* be the cause of the issues seen in this bug report but that could be very wrong.

**Comment by IThundxr** [comment]
Better end needs to tag their blocks properly

https://github.com/Creators-of-Create/Create/wiki/Useful-Tags
