### ISSUE TITLE
REI displays wrong chance to get Gold Nuggets when washing Soul Sand

### ISSUE THREAD

**Issue by CzechHek** [Fabricators-of-Create/Create#646]
### Describe the Bug

I noticed that gold nugget drop rate was too low when building a gold farm. REI says that there is the same chance to get quartz as to get gold nuggets, however, this isn't the case since the ratio is 12% : 2%.

Does this apply to other items as well?
Is this a REI issue?

### Reproduction Steps

1. Install Create, REI.
2. Look at Soul Sand usages, Bulk Washing category.

### Expected Result

REI should correctly state that chance to get gold nugget is 2%.

### Screenshots and Videos

REI:
![image](https://user-images.githubusercontent.com/42714212/204645250-0e013824-88ce-437a-8aee-5025cc9d92b3.png)

EMI:
![image](https://user-images.githubusercontent.com/42714212/204645274-6dfdc579-43ee-4f5d-b006-388069b75e01.png)

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Additional Context

Isn't the quartz chance also wrong, because there is 12% chance to get 4 quartz, however, you most commonly get only single one?

**Comment by CzechHek** [comment]
Could have something in common with https://github.com/Fabricators-of-Create/Create/issues/297.
It's a different issue, percentages are shown now perfectly fine, but:

        Update 2: The percentages are only shown for some recipes
https://youtu.be/0xUQ5rlIjIA

_Originally posted by @Notenoughmail in https://github.com/Fabricators-of-Create/Create/issues/297#issuecomment-1133531174_
      
You can see that the percentage is wrong there: https://youtu.be/0xUQ5rlIjIA?t=8

**Comment by TropheusJ** [comment]
should be fixed by #1342
