### ISSUE TITLE
Extracting from Item Vault causes major MSPT increase

### ISSUE THREAD

**Issue by PINPAL** [Fabricators-of-Create/Create#647]
### Describe the Bug

When extracing items from a Item Vault using a conveyor belt the MSPT increases greatly causing low TPS.

Spark Performance Profile:
https://spark.lucko.me/42UYqz9FsD

### Reproduction Steps

1. Build an item vault and setup a conveyer with a funnel to pull out items
2. Observe MSPT/TPS is fine.
3. Power the conveyer belt such that it will pull out items.
4. Observe MSPT increases greatly causing a TPS drop.

### Expected Result

Pulling items out of a Item Vault will cause minimal MSPT increase.

### Screenshots and Videos

![extracting](https://user-images.githubusercontent.com/18197217/204927437-a0a33c00-e373-4ab1-b0cf-ab581a87b987.png)
![off](https://user-images.githubusercontent.com/18197217/204927443-0d57f67e-6281-438e-a450-9ce43a20404d.png)

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

 - Malilib
- MiniHUD
- Carpet Mod

(Used for observing MSPT / TPS)

**Comment by TropheusJ** [comment]
I can't reproduce this, and the profile is not very useful.
does it happen if you build a new vault? new funnels? move it somewhere else? 
The vault is empty, right? I'd assume so since the belt is.

**Comment by PINPAL** [comment]
> I can't reproduce this, and the profile is not very useful. does it happen if you build a new vault? new funnels? move it somewhere else? The vault is empty, right? I'd assume so since the belt is.

It happens on all vaults. I have yet to build a vault that doesn't have the issue. I believe the effect is amplified by the storage value set in the config, the larger the number the greater the MSPT increase. This occurs on empty vaults and also full vaults. The funnel can also be filtered and the issue still occurs.

**Comment by TropheusJ** [comment]
What’s your vault size configured to be? 
Are Malilib, MiniHUD, and Carpet the only other mods you have installed?

**Comment by PINPAL** [comment]
> What’s your vault size configured to be? Are Malilib, MiniHUD, and Carpet the only other mods you have installed?

No other mods except for Malilib, MiniHUD and Carpet.
Vault Size was configured to 2000.
I have since updated my instance to 1.19.2 and when setting up a quick test world it seems this issue does not occur on 1.19.2

**Comment by TropheusJ** [comment]
2000… that’s why 
That amount is per vault block. 
A funnel would be querying 180,000 slots twice every tick for a 10 block long 3x3 vault.

**Comment by PINPAL** [comment]
> 2000… that’s why That amount is per vault block. A funnel would be querying 180,000 slots twice every tick for a 10 block long 3x3 vault.

Yeah it's my first time using Create and I had hoped the vaults would provide a bulk storage solution as an alternative to chests full of shulkers. I had thought they could only hold one item and didn't act as an entire inventory.

**Comment by TropheusJ** [comment]
This should now be handled much better when Create's blocks are used for item extraction. Other mods will still have issues.
In reality, you really, really should not have it set to 2000.
