### ISSUE TITLE
When interacting with a boiler the game crashes.

### ISSUE THREAD

**Issue by silo8811** [Fabricators-of-Create/Create#648]
### Describe the Bug

When in survival, adding magmablocks under a boiler with 4 steam engines on it, or\nadding steam engines onto the tank its self with any number of steam engines on it, the game freezes, then crashes.

### Reproduction Steps

1.Be in a survival world\n2.Make a 4x4 boiler\n3.Piss off the boiler by adding steam engines to it\n4.Crash\n5.Restart game and join world\n6.Repeat 3, 4, and 5 for 3 more times\n7.Quit and stop playing for a week\n8.Join the world again\n9.Find magma blocks and add some under the boiler\n10.Learn that you have offended the boiler\n11.Crash\n
...

### Expected Result

The game to not crash and for it actually build the boiler correctly

### Crash Report or Log

https://discord.com/channels/620934202875183104/976100492243501106/1047969430031827065

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Create crafts & Additions
Fabric API

**Comment by TropheusJ** [comment]
issue with CC&A

**Comment by silo8811** [comment]
Okay
