### ISSUE TITLE
Potato Cannon can only be enchanted with Unbreaking

### ISSUE THREAD

**Issue by KeyC-EU** [Fabricators-of-Create/Create#652]
### Describe the Bug

Potato Cannon can only be enchanted with Unbreaking 1-3. The enchanting table either gives me unbreaking or nothing at lower level. This issue is in single player and on my hosted server for both me and my brother.
Even after a handful of enchants, the potato cannon never recieved any extra enchants other than unbreaking during the enchanting process. 

### Reproduction Steps

Enchant any potato cannon

### Expected Result

Forge Potato Cannon offered all possible enchants at the enchanting table,

### Screenshots and Videos

https://user-images.githubusercontent.com/12752893/205464580-8a3f5e5e-bc9e-4ea4-af52-1d6cf45a8d34.mp4

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

fabric api 0.67.1

architectury 6.3.56
cloth config 8.2.88
RoughlyEnoughItems 9.1.574

Oh_The_Biomes_You'll_Go
TerraBlender

indium 
lithium 
phosphor
sodium

### Additional Context

We switched from forge to fabric to use mods for better performance.
Forge version had no issues with enchanting the cannon, fabric always had since the first time we tried.
Copper Backtank works as intended and can recieve capacity enchant. 
The cannon can still recieve create mod exclusive enchants like potato recovery by console command or books specifically bought from villagers. I couldn't find a single potato recovery at the enchanting table after enchanting multiple stacks of books, but this can be just unlucky.

**Comment by KeyC-EU** [comment]
I tried to enchant the potato cannon with all enchants that are listed in the wiki and I was able to enchant on the forge version, but neither over books or with command console /enchant it was possible to give the potato cannon any enchant other than Unbreaking and Potato Recovery. The error message is "The potato cannon cannot support this enchantment"

**Comment by KeyC-EU** [comment]
Well, after a lot of frustration I checked the wiki again and noticed that it changed with 0.5.0. There was barely any time between my forge and fabric world and I didn't realise that they were different versions. Forge 0.5.0f still had the enchants enabled, but fabric 0.5.0g has them removed. Too bad, really liked the looting on the cannon. Still had no potato recovery as enchanting option tho after hundreds of tries, so this might still be a problem, but this might just be very unlucky. 
Rest was just from pure coincidence, that it was so shortly changed between my first time playing and my 2nd world.

**Comment by RecyclingTiger** [comment]
Seems like this is just a difference between the forge and fabric versions as in the forge version its still enchantable with power/looting etc... in the latest version of forge at the time of this writing, forge 0.5.0h and fabric 0.5.0g

**Comment by TropheusJ** [comment]
it's already been fixed for the next update
