### ISSUE TITLE
Cogwheel, shaft and large cogwheel animation bug. 1.19.2

### ISSUE THREAD

**Issue by V01DW3B** [Fabricators-of-Create/Create#653]
### Describe the Bug

The Cogwheel animation is broaken and you can see the animation and the steall verso of the block .

### Reproduction Steps

if you place or use a Cogwheel.

### Expected Result

...

### Screenshots and Videos

![Screenshot 2022-12-04 022846](https://user-images.githubusercontent.com/68392877/205468014-ccacb270-d2d2-4d6c-9912-f7cfbd50870f.png)

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

![image](https://user-images.githubusercontent.com/68392877/205468020-9914a0dc-105f-427a-a086-67fd9eec4ad4.png)

### Additional Context

its not beacose of the sheaderspack :3

**Comment by V01DW3B** [comment]
sorry for my bad English

**Comment by TropheusJ** [comment]
install indium

**Comment by V01DW3B** [comment]
TH It works now
