### ISSUE TITLE
Game crashes immediately upon pondering an item (mod conflict?)

### ISSUE THREAD

**Issue by JediEdi** [Fabricators-of-Create/Create#655]
### Describe the Bug

I have a survival modded playthrough on Quilt 1.19.2 and everything works fine. However, once I decided to make a new creative world to do some experiments, pondering started crashing the game immediately, stating that the current screen is not creative inventory screen. 

### Reproduction Steps

1. Install mods with little regard for potential conflicts (mod list in crash log and below)
2. Go on creative mode
3. Open the inventory and navigate to page 2
4. Ponder an item. Once the bar gets full, the game crashes

### Expected Result

I was expecting the ponder window to pop up normally.

### Crash Report or Log

https://pastebin.com/ePsSksDq

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Additional enchanted miner
Advanced netherite
Architectury
Bookshelf
C2me
Camerautils
Charm
Cloth config
Comforts
Create
Darkutilities
Do a barrel roll
Extra sounds
Fabric smooth swapping
Forge config API port
Forgero
Frame
Geckolib
Iceberg
Indium
Iris
Item borders
Item swapper
Legendary tooltips
Lithium
Midnightlib
Mod menu
Mouse wheelie
Naturalist
No shield delay
Patchouli
Prism
Quilted fabric API
Repurposed structures
Roughly enough resources
Roughly enough items
Sodium
Stoneholm
Traveler's backpack
Trinkets
Twigs
Visuality
Wild tool access
You're in grave danger

**Comment by TropheusJ** [comment]
Frame is doing something weird, report to them
