### ISSUE TITLE
Extended reach is incorrect with Pehkui

### ISSUE THREAD

**Issue by ERBEpic** [Fabricators-of-Create/Create#656]
### Describe the Bug

When having Pehkui installed, the extendo grip attack range only gets extended by one block. Without Pehkui, it is extended to 3.

### Reproduction Steps

1. Install Pehkui
2. Install Create
3. Attempt to use Extendo Grip past normal attack range

### Expected Result

The extendo grip extends attack range as normal

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/70818523/205687093-f282c549-e134-4d72-a212-b54db243504b.png)

left is extendo without Pehkui, middle is extendo with Pehkui, and right is normal fist.

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Additional Context

https://github.com/Virtuoel/Pehkui/issues/346

I also have made an issue on Pehkui, as i was told to make an issue for both mods.

**Comment by TropheusJ** [comment]
Create uses Reach Entity Attributes to extend the player's reach. This library and Pehkui do not interact properly.

**Comment by Virtuoel** [comment]
Pehkui does have compat code for Reach Entity Attributes.
However, looking at the ExtendoGripItem, it seems it's using just the `ReachEntityAttributes.REACH` attribute, which only affects block reach. It should also make use of the `ReachEntityAttributes.ATTACK_RANGE` attribute. (similarly on the Forge version, it's only using `ForgeMod.REACH_DISTANCE` and not also `ForgeMod.ATTACK_RANGE`)
