### ISSUE TITLE
JEI not displaying unique recipes.

### ISSUE THREAD

**Issue by GameOnne** [Fabricators-of-Create/Create#657]
Hello! I've recently ran into a compatibility issue while using JEI with Create. JEI does not display any recipes outside of vanilla blocks, therefore viewing recipes unique to Create's blocks (like compressing, mixing, using auto-crafters, etc) is not possible.
I was using JEI 11.4.0.287 and Create 0.5.0g, both for Fabric 1.19.2.

**Comment by nerothe** [comment]
Im having the same issue

**Comment by FadedSA** [comment]
I have the same issue in Create version 0.5.0g and JEI 10.2.1.283 for Fabric 1.18.2

**Comment by LemmaEOF** [comment]
Do you all have Farmer's Delight in your pack? This may be the same issue as #660, just with the JEI plugin instead of the EMI plugin.

**Comment by GameOnne** [comment]
No, I do not. I'd also like to note something. I've been playing with 2 friends. One of them had the same issue as me, the other one could see some recipes (mixing, milling, etc), but not "complex" ones (assembly, mechanical crafting, etc).

**Comment by TropheusJ** [comment]
might be caused by https://github.com/mezz/JustEnoughItems/issues/3085

**Comment by MrBrax** [comment]
for me it is caused by farmer's delight

**Comment by sippeeey** [comment]
I have the same issue. Its very depressing but i hope it can be fixed. 
i have no farmer's delight.
i use the mods:
BetterAdvancements-Fabric-1.19.2-0.2.2.142.jar      fabric-api-0.72.0+1.19.2.jar
BlueMap-3.9-fabric-1.19.3.jar                       fabric-language-kotlin-1.9.0+kotlin.1.8.0.jar
BuildingWands_mc1.19.2-2.6.4_release-fabric.jar     ftb-chunks-fabric-1902.3.14-build.218.jar
Clumps-fabric-1.19.2-9.0.0+14.jar                   ftb-library-fabric-1902.3.11-build.166.jar
CraftTweaker-fabric-1.19.2-10.0.24.jar              ftb-ranks-fabric-1902.1.14-build.70.jar
CreativeCore_FABRIC_v2.9.3_mc1.19.2.jar             ftb-teams-fabric-1902.2.11-build.87.jar
Croptopia-1.19.2-FABRIC-2.2.0.jar                   ftb-ultimine-fabric-1902.3.5-build.65.jar
ExtendedDrawers-1.3.5+mc.1.19.2.jar                 ftbbackups2-fabric-1.19.2-1.0.17.jar
FallingTree-1.19.2-3.10.0.jar                       item-filters-fabric-1902.2.9-build.46.jar
FauxCustomEntityData-fabric-1.19.2-2.0.2.jar        jamlib-0.6.0+1.19.jar
IngredientExtensionAPI-fabric-1.19.2-3.0.6.jar      jei-1.19.2-fabric-11.5.0.297.jar
ItemPhysic_FABRIC_v1.6.6_mc1.19.2.jar               jmi-fabric-1.19.2-0.13-30.jar
Jade-1.19.1-fabric-8.7.0.jar                        journeymap-1.19.2-5.9.1-fabric.jar
JustEnoughResources-Fabric-1.19.2-1.2.1.189.jar     lazydfu-0.1.3.jar
LuckPerms-Fabric-5.4.57.jar                         lithium-fabric-mc1.19.2-0.10.4.jar
NaturesCompass-1.19.2-2.1.0-fabric.jar              
Patchouli-1.19.2-77-FABRIC.jar                      minecraft-command-permissions-1.6.1.jar
architectury-6.4.62-fabric.jar                      polylib-fabric-1900.0.2-build.42.jar
autowhitelist-1.1.2-compat-mcdiscordchat.2.1.0.jar  realisticsleep-1.6.0.jar-disabled
betterstats-2.1.1+1.19.2.jar                        realisticsleep-1.7.0.jar
cardinal-components-api-5.0.2.jar                   right-click-harvest-3.1.0+1.19-1.19.2.jar
carryon-fabric-1.19.2-2.0.2.3.jar                   spark-1.10.17-fabric.jar
cloth-config-8.2.88-fabric.jar                      travelers-backpack-1.19.2-8.2.10.jar
create-fabric-0.5.0g-796+1.19.2.jar                 worldedit-mod-7.2.12.jar
createaddition+1.19.2-1.19.2-20221218a.jar          youre-in-grave-danger-1.4.6.jar

**Comment by IThundxr** [comment]
If this still occurs feel free to open a new issue
