### ISSUE TITLE
Train station map markers crash servers

### ISSUE THREAD

**Issue by Sesshaku** [Fabricators-of-Create/Create#658]
### Describe the Bug

I'm trying to change my world from forge to fabric. Everything works fine, except for some ticking error produced by created and some "trainstations".

I would like some assistance in identifying which part is causing the error, and how to solve it without having to restart the whole world. That is, I'm asking if there's a way to delete the problematic parts and leave the rest.

### Reproduction Steps

1.
2.
3.
...
It's not really a bug (I think), I just couldn't find any assistance on the create discord for fabric.

### Expected Result

It's not really a bug (I think), I just couldn't find any assistance on the create discord for fabric.

### Crash Report or Log

https://gist.github.com/Sesshaku/4896a750d27b2cb2a48780e8a879cdf7

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
it seems train station map markers will crash servers. This occurs on Forge too.

**Comment by IThundxr** [comment]
Doesnt crash anymore but doesnt work either, will be tracked at https://github.com/Fabricators-of-Create/Create/issues/1333
