### ISSUE TITLE
Steam Engine Bug Crash

### ISSUE THREAD

**Issue by RedCocoon** [Fabricators-of-Create/Create#659]
### Describe the Bug

If you have air blocks underneath a steam engine, the game crashes.

### Reproduction Steps

1. Form a 2x2 tank
2. Place a steam engine on top, complete with the shaft
3. Break the blocks underneath the tank

### Expected Result

Expected Result: For the game to not crash.

### Crash Report or Log

https://pastebin.com/uCuYxx1j

### Operating System

PopOS

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

ae2: Applied Energistics 2 11.6.6
		ae2wtlib: AE2WTLib 11.6.3
		appleskin: AppleSkin 2.4.1+mc1.18.2
		architects_palette: Architect's Palette Fabric 2.2
		architectury: Architectury 4.10.86
		balm-fabric: Balm 3.2.0+0
		betteradvancements: Better Advancements 0.2.0.146
		carpenter: Carpenter 1.0.0
		chunky: Chunky 1.2.164
		cloth-config: Cloth Config v6 6.4.90
			cloth-basic-math: cloth-basic-math 0.6.1
		comforts: Comforts 1.1.3-1.18.2
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		connectiblechains: Connectible Chains 2.1.4+1.18.2
		connectivity: Connectivity Mod 1.18.2-3.3
		create: Create 0.5.0g-792+1.18.2
			com_electronwill_night-config_core: core 3.6.3
			com_electronwill_night-config_toml: toml 3.6.3
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			forge_tags: Forge Tags 2.1
			forgeconfigapiport: Forge Config API Port 3.2.0
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			porting_lib: Porting Lib 1.2.460-beta+1.18.2-dev.cca931b
				com_github_llamalad7_mixinextras: MixinExtras 0.0.11
				mm: Manningham Mills 2.3
				serialization_hooks: Serialization Hooks 0.3.23
			registrate-fabric: Registrate for Fabric MC1.18.2-1.1.5
		createaddition: Create Crafts & Additions ${version}
			team_reborn_energy: Energy 2.2.0
		createplus: CreatePlus 1.0
		debugify: Debugify 1.11.0
		decorative_blocks: Decorative Blocks 2.1.1
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		editsign: EditSign 2.3.1
		etched: Etched 2.2.0
			javazoom_jlayer: jlayer 1.0.1
		fabric-api: Fabric API 0.67.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.2+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.20+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.0+d8cf4e5a60
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.11+bb2e047760
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.8+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.6+kotlin.1.7.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.10
		farmersdelight: Farmer's Delight 1.18.2-1.2.5
		ferritecore: FerriteCore 4.2.1
		gravestones: Gravestones v1.11.1
		jade: Jade 5.99.7
		java: OpenJDK 64-Bit Server VM 17
		kubejs: KubeJS 1802.5.5-build.560
		litematicatool: Litematia Tool 1.3.2
		lithium: Lithium 0.10.2
		lootr: Lootr 0.3.23.60
		mannequins: Mannequins 2.1.0
		mcwbridges: Macaw's Bridges 2.0.5
		medievalweapons: Medieval Weapons 1.2.0
		memoryleakfix: Memory Leak Fix 1.18.2-0.7.0
		minecraft: Minecraft 1.18.2
		phosphor: Phosphor 0.8.1
		plasmo_voice: Plasmo Voice 1.2.19
		pollen: Pollen 1.5.0
		rhino: Rhino 1802.2.1-build.252
		roughly_enough_loot_tables: Roughly Enough Loot Tables (RELT) 1.18-1.1
		roughlyenoughitems: Roughly Enough Items 8.3.573
			error_notifier: Error Notifier 1.0.9
		roughlyenoughresources: Roughly Enough Resources 2.5.0
		servux: Servux 0.1.0
		simplyswords: Simply Swords 1.34-1.18.x
		spark: spark 1.9.11
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		textile_backup: Textile Backup 2.5.0-1.18
			com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
			org_apache_commons_commons-compress: commons-compress 1.21
			org_tukaani_xz: xz 1.9
		travelersbackpack: Traveler's Backpack 1.18.2-7.1.12
			reach-entity-attributes: Reach Entity Attributes 2.2.0
		trinkets: Trinkets 3.3.1
		vanityslots: Vanity Slots 1.1.2
		xaerominimap: Xaero's Minimap 22.16.2
		xaeroworldmap: Xaero's World Map 1.28.3

**Comment by SplendidAlakey** [comment]
Create Additions bug: https://github.com/mrh0/createaddition/issues/384
