### ISSUE TITLE
Incompatibility with custom chest models

### ISSUE THREAD

**Issue by Octelly** [Fabricators-of-Create/Create#663]
### Describe the Bug

Create (and or Flywheel, can't easily test since they're bundled together) forces the vanilla chest model to be rendered alongside any custom one.

I've tested this with both [Nostalgic Tweaks](https://modrinth.com/mod/nostalgic-tweaks) and [FastChest](https://github.com/FakeDomi/FastChest).

### Reproduction Steps

1. Click on chest
2. Observe intersecting models

### Expected Result

Only the custom model should be rendered (as seen in the attached video, Create disabled)

https://user-images.githubusercontent.com/29976879/206413024-5f34a3f3-c952-4324-8717-26bddb25dd38.mp4

### Screenshots and Videos

https://user-images.githubusercontent.com/29976879/206411453-760fbd4a-1690-438d-8193-e42191a43181.mp4

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

The following mods were present for both demonstrational videos (with no other changes besides Create being disabled in one of them)

- Architectury
- Cloth Config
- Cull Less Leaves
- Enhanced Block Entities
- Fabric API
- Fabric Language Kotlin
- Fabrication
- Hunger Remover
- Indium
- Iris
- Mod Menu
- Nostalgic Tweaks
- Reese's Sodium Options
- Roughly Enough Items
- Sodium
- Sodium Extra

**Comment by SplendidAlakey** [comment]
This is technically the same as https://github.com/Fabricators-of-Create/Create/issues/316. Create already optimizes block entity rendering, you don't need to add any extra mods for that.

If you absolutely insist on using FastChest, then type /flywheel backend off in chat and hit enter.

**Comment by Octelly** [comment]
> This is technically the same as #316. Create already optimizes block entity rendering, you don't need to add any extra mods for that.
> 
> If you absolutely insist on using FastChest, then type /flywheel backend off in chat and hit enter.

Well, perhaps, but optimisation wasn't the point, hence me mentioning this being a feature of [Nostalgic Tweaks](https://modrinth.com/mod/nostalgic-tweaks) as well.

I'm putting together a collection of mods and resource packs that bring back the look and feel of Beta 1.7.3 and I really wanted to add Create to it as well, because it's one of my favourite mods and I was looking forward to making beta-style textures for it.

**Comment by TropheusJ** [comment]
duplicate of #316
