### ISSUE TITLE
[1.19.2] Sandpaper's crafting recipe is broken

### ISSUE THREAD

**Issue by EzioisAwesome56** [Fabricators-of-Create/Create#665]
### Describe the Bug

Sandpaper's crafting recipe, according to the wiki, is paper and a block of sand. Both JEI and REI say it requires just a single sheet of paper. Neither recipe works.

Mod version: 0.5.0g-796

### Reproduction Steps

1. Attempt to craft sandpaper using either recipe

### Expected Result

you get sandpaper from the recipe

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/21185626/206552520-2b247a0c-f344-4b5e-9480-5eaf1c90cae4.png)
![image](https://user-images.githubusercontent.com/21185626/206552592-d09d065b-d27e-42aa-9f28-4bed9e7acd51.png)
![image](https://user-images.githubusercontent.com/21185626/206552614-498b5f47-72d8-486c-afd9-75a0e988a1be.png)

### Operating System

Ubuntu 20.04

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Just enough items 11.3.0.288
Quilted Fabric API 4.0.0-beta-24+0.68.0

### Additional Context

Launching using quilt instead of fabric, though I doubt that is part of the problem

Using Temurin Java 19 x64 from Adoptium

**Comment by SplendidAlakey** [comment]
> Launching using quilt instead of fabric, though I doubt that is part of the problem

Yes, it is. For some reason, Quilt Loader 0.17.7 fails to load these 2 recipes. 0.18.1-beta.23 doesn't have that issue.

**Comment by SplendidAlakey** [comment]
Hey, could you let me know, if updating your loader works for you? I can't reproduce this issue on 0.17.7 anymore, even though I didn't change a single thing.

**Comment by EzioisAwesome56** [comment]
@SplendidAlakey 
> Hey, could you let me know, if updating your loader works for you? I can't reproduce this issue on 0.17.7 anymore, even though I didn't change a single thing.

updating to quilt 1.18.1-beta-23 did appear to fix the issue
![image](https://user-images.githubusercontent.com/21185626/206791419-3eb3ef07-b706-439f-969f-19b5cd64ef3d.png)

downgrading back to 1.17.7 causes it to happen again on my end however
![image](https://user-images.githubusercontent.com/21185626/206791710-7b5ac95b-07e6-4e23-83da-0b82e3e7c1f4.png)
![image](https://user-images.githubusercontent.com/21185626/206791839-04cf31ae-f2aa-4fe4-8fa0-03eea5169a13.png)


altho since this appears to be a quilt loader bug and not a create bug, i guess this can get closed

**Comment by Mg138** [comment]
We're having this issue again, on Quilt 0.18.1-beta.27

The complete modpack info is at https://codeberg.org/madeline/gaycraft

**Comment by wingedseahorse** [comment]
Working fine on the latest beta 0.18.1-beta.59 after updating from 0.17.7
