### ISSUE TITLE
Mechanical Arm forgets configuration in survival, but not in creative

### ISSUE THREAD

**Issue by LinuxSquare** [Fabricators-of-Create/Create#666]
### Describe the Bug

**Disclaimer: It doesn't matter if placed in a sole survival world or in a LAN-World. The effect is the same.**

When configuring a mechanical arm in survival mode to take the items from a depot and then put them into a funnel, which leads into a barrel, it fails and says:

> No Targets
It appears this **Mechanical Arm** has not been assigned any **targets.** Select belts, depots, funnels and other blocks by **right-clicking** them while **holding** the **Mechanical Arm** in your **hand**.

When placed in creative mode with the exact same configuration on the exact same place, it works as intended.

### Reproduction Steps

1. Switch to Survival Mode
2. Configure the mechanical arm with depot as input and brass funnel that leads into a barrel as output.
3. Place the mechanical arm.
...

### Expected Result

The mechanical arm should pick up the items on the depot and should put them inside the barrel.

### Screenshots and Videos

[Click here for Video Proof](https://www.youtube.com/watch?v=iKfketL5C4M)

### Operating System

My OS: Manjaro GNU/Linux 5.15.81-1-MANJARO / Brothers OS: Windows 10 21H2

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

**Warning: Long list. 54 Mods**
**Selfmade Modpack using GDLauncher (Curseforge alternative for Linux)**

* AdvancementPlaques
* AmbientSounds
* balm-fabric
* BedBenefits
* BetterAdvancements
* BetterCompatibilityChecker
* blur
* Bookshelf-Fabric
* Bookshelf-Forge (dunno why forge, it's a full Fabric Modpack)
* clickadv-fabric
* cloth-config-8.2.88-fabric
* cloth-config-8.2.88-forge (same here again)
* collective-fabric
* create-fabric-0.5.0g-791
* CreativeCore
* dark-loading-screen
* DisableCustomWorldsAdvice
* dynamic-fps
* entityculling-fabric
* fabric-api-0.67.1
* fabric-api-0.68.0
* fabric-language-kotlin
* ForgeConfigAPIPort
* Iceberg
* indium
* iris-mc
* jei
* krypton
* lambdynamiclights
* lazydfu
* lithium-fabric
* memoryleakfix
* modmenu
* nether-coords
* netherportalfix-fabric
* opac-fabric-create-support
* open-parties-and-claims-fabric
* portal_accessibility
* PuzzlesLib
* realisticsleep
* reeses_sodium_options
* SimpleBackpack
* sodium-extra
* sodium-fabric-mc
* starlight
* ToolStats
* treeharvester
* VisualWorkbench
* Xaeros_Minimap
* XaerosWorldMap
* YetAnotherConfigLib
* youre-in-grave-danger
* zmedievalmusic-fabric
* Zoomify

**Comment by Cyklan** [comment]
For added context:
This only happens when you have a singular mechanical arm in your hotbar slot. The mechanical arm forgets its targets because your hand is now empty.

If instead you have multiple mechanical arms in your hand, select the target and place it down, the arm will remember its targets.

I created a demo video showing the bug and the current workaround: https://youtu.be/_Mn9mpbx5LA

**Comment by LinuxSquare** [comment]
Thank you @Cyklan for your answer.
Interesting, why this happens.

Do you know if there will be a fix in some upcoming releases?

Because as you say, I could use the workaround.

But when I don't have the materials to craft a second mechanical arm and only have the option to switch to creative mode, it wouldn't be possible to place a single mechanical arm on servers, without asking for creative or directly a mod/admin, who has access to creative.

**Comment by Cyklan** [comment]
Sorry, I don't work on this mod, I only had the same issue and posted it to reddit, where I was presented with the workaround

**Comment by worldllc** [comment]
the latest release (patch 1) fixed this problem for me. BUT, now crashes when opening a previously filled tool box. I think with the previous commenter solution of having multiple arms, I may go back to original 1.19.2 as that is better than no tool box. Or, perhaps it is just a mix of my other mods and versions that cause it? either way...

**Comment by LinuxSquare** [comment]
Thank you @worldllc 

I've tried it aswell, and it's working with Patch 1.
My Game didn't crash tho.

Maybe, because my mechanical arm takes items from a depot and then deposits into a blaze burner.

**Comment by LinuxSquare** [comment]
Duplicate of #608

**Comment by LinuxSquare** [comment]
Duplicate of #608
