### ISSUE TITLE
The game failed to load when loading Iris with Create

### ISSUE THREAD

**Issue by DL909** [Fabricators-of-Create/Create#670]
### Describe the Bug

The game failed to load when loading with mod Iris(1.2.4 build.38) and Create(0.5.0g-792), it stopped before game start to load and told me "Replace mod 'Create' (create) 0.5.0g-792+1.18.2 with any version that is compatible with: - iris 1.2.4-build.38"
I use Fabric 0.14.11 in minecraft 1.18.2 and Java 17.0.2
Every question solved after I delete Iris and I tried to only load Iris, Create, and other necessary coremods which gives me the same result so I'm sure the question is caused by Iris and Create

### Reproduction Steps

1.load Iris(1.2.4 build.38) and Create(0.5.0g-792) in minecraft 1.18.2 Fabric 0.14.11
2.start game

### Expected Result

game stopped loading and report as "Replace mod 'Create' (create) 0.5.0g-792+1.18.2 with any version that is compatible with: - iris 1.2.4-build.38"

### Operating System

macOS Monterey 12.6

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

Iris iris 1.2.4-build.38

**Comment by TropheusJ** [comment]
Update iris
