### ISSUE TITLE
Mechanical Crafter Deletes Items

### ISSUE THREAD

**Issue by ImpaledBerry** [Fabricators-of-Create/Create#671]
### Describe the Bug

When a crafter gets split into 2 sides because of misalignment, one side will start crafting despite it not having the full recipe, once you rotate it to align, it will delete the items currently crafting.

### Reproduction Steps

1. Make a Misaligned Mechanical Crafter
![image](https://user-images.githubusercontent.com/108269082/206860294-d61aef58-3e27-4bc2-bbf7-2daf821f4188.png)

2. Craft something on one of the sides
![image](https://user-images.githubusercontent.com/108269082/206860315-966d232f-c8a5-4845-a4a1-b8e943b6d0e1.png)

3. Rotate to align with other half
![image](https://user-images.githubusercontent.com/108269082/206860360-1d6a0d43-25f3-4f27-8cc7-02edaef4db2b.png)

4. Items dissapear
![image](https://user-images.githubusercontent.com/108269082/206860370-1cb6068f-4dbc-48ae-9ab8-3fbcb4a1fb6e.png)

### Expected Result

Items being crafted pop out instead of dissapearing, because it failed to craft 

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Flywheel, Jade, Sodium, Lithium, Phosphor

### Additional Context

LAN enabled

**Comment by TropheusJ** [comment]
can't reproduce. Could you record it?

**Comment by IThundxr** [comment]
If anyone is able to reproduce this issue on the latest patch feel free to make a new one
