### ISSUE TITLE
Blaze Burner = Fatal Serverside Crashes (Fabric)

### ISSUE THREAD

**Issue by Korulein** [Fabricators-of-Create/Create#672]
### Describe the Bug

The Bug consists mainly around Blaze Burners, Players had placed and used blaze burners in mod V0.5.0e, however when we updated the server to V0.5.0.g, all blaze burners and their associated blocks became corrupted, which lead to not only the burners themselves causing the server to crash but any interaction with the blocks they were located in to cause a crash after a few ticks. We have filled former spots with bedrock, as a temporary guard against crashes, any further interaction results in crashes. 

### Reproduction Steps

1. Launch Server with Create V0.5.0e -733
2. Place and use a Blaze Burner
3. Update Server to Create V0.5.0g-792 
4. Interact with the Blaze Burner or any blocks that used to contain the Blaze Burner. 

### Expected Result

Normal Interaction with the Blaze Burner Interface.

### Crash Report or Log

https://pastebin.com/xSntRDCX

### Operating System

Linux Ubuntu - version 5.13.0-52-generic

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

<img width="248" alt="Screenshot 2022-12-10 at 22 28 30" src="https://user-images.githubusercontent.com/107486718/206875940-646bba9d-3d5c-4709-8e77-cd29ba271dff.png">
<img width="297" alt="Screenshot 2022-12-10 at 22 28 39" src="https://user-images.githubusercontent.com/107486718/206875942-ff905d57-aeb5-4b51-8e13-61e51a625439.png">
<img width="338" alt="Screenshot 2022-12-10 at 22 28 49" src="https://user-images.githubusercontent.com/107486718/206875943-9adda471-9be8-4c77-af08-2c79ba50e64e.png">
<img width="277" alt="Screenshot 2022-12-10 at 22 28 59" src="https://user-images.githubusercontent.com/107486718/206875945-1b6f4f4a-f12e-4bea-ae94-b87de0837731.png">
<img width="331" alt="Screenshot 2022-12-10 at 22 29 08" src="https://user-images.githubusercontent.com/107486718/206875946-ee8ae444-9a6e-4acc-9d80-3cbca0bddf2f.png">

**Comment by TropheusJ** [comment]
issue with CC&A
