### ISSUE TITLE
Add the ability to view the contents of a filter on a brass funnel/tunnel when Engineer Goggles are equipped

### ISSUE THREAD

**Issue by ChristopherHaws** [Fabricators-of-Create/Create#673]
### Describe the Suggestion

Right now, when a filter is in a brass funnel/tunnel filter slot, the only way to see what is in the filter is to take the item out of the filter slot. It would be incredibly helpful if having the engineer goggles on made it so you can simply look at the filter to see the contents of it.

**Comment by TropheusJ** [comment]
We don't add features. You should suggest this on the forge repo.
