### ISSUE TITLE
Not Compatible With OptiFabric Mod

### ISSUE THREAD

**Issue by Sir-Capzalot** [Fabricators-of-Create/Create#675]
### Describe the Bug

Create Fabric 0.5.0g gives an incompatibility error when loading up Minecraft with OptiFabric.

### Reproduction Steps

1. Add [**Create Fabric 1.19.2**](https://www.curseforge.com/minecraft/mc-mods/create-fabric) to the mods folder.
2. Add [**OptiFabric 1.13.15/16**](https://www.curseforge.com/minecraft/mc-mods/optifabric) to the mods folder.
3. Add [**OptiFine 1.19.2**](https://optifine.net/adloadx?f=OptiFine_1.19.2_HD_U_H9.jar&x=0261) to the mods folder.
4. Run the game.

### Expected Result

I expected the game to run as normal just with better FPS.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/120346184/206939597-4156b5d0-1414-4ba8-8025-b962795f595e.png)

### Crash Report or Log

https://pastebin.com/WJReuuCv

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

As there are 80 mods I do not feel it is practical to give the whole list, especially considering the Fabric loader found no other issues. Upon request, I will happily provide the list of mods if it is necessary to the process.

**Comment by TropheusJ** [comment]
yes, they are incompatible. We will not be changing this. Use Sodium and the many other replacements on Fabric.

**Comment by Sir-Capzalot** [comment]
Perhaps put that in the information somewhere. It would be useful on many levels.
