### ISSUE TITLE
蒸汽引擎出现错误

### ISSUE THREAD

**Issue by RegulusSource** [Fabricators-of-Create/Create#676]
### Describe the Bug

当撤去蒸汽引擎下方的热源时导致游戏崩溃

### Reproduction Steps

1.放置流体储罐
2.将流体储罐变为蒸汽引擎
3.放置热源(在蒸汽引擎下方)
...

### Expected Result

修复bug

### Screenshots and Videos

[crash-2022-12-13_20.13.48-server.txt](https://github.com/Fabricators-of-Create/Create/files/10218038/crash-2022-12-13_20.13.48-server.txt)

### Operating System

win10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
issue with Create Crafts and Additions
