### ISSUE TITLE
Steam Engine Crashes Server when Placed on Fluid Tanks

### ISSUE THREAD

**Issue by Pitstik** [Fabricators-of-Create/Create#678]
### Describe the Bug

As the title says, the server is crashing when we place steam engines on the tanks. The tanks themselves can exist, but as soon as we put the engine on it, the server crashes.
Attached below is the crash log and relevant info. Please help, thanks.

### Reproduction Steps

1.Set up 4 fluid tanks
2.Place steam engine directly on them.
3. Disconnected.
...

### Expected Result

The server to NOT crash.

### Crash Report or Log

https://pastebin.com/0tsC0qqF

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Other mods are on the crash log.

**Comment by TropheusJ** [comment]
issue with Create Crafts and Additions
