### ISSUE TITLE
1.19.2 DimensionalThreading compatibility

### ISSUE THREAD

**Issue by LittleLigr** [Fabricators-of-Create/Create#679]
### Describe the Bug

If I have train with working schedule server will fall after launch.

### Reproduction Steps

1. Add Create and DimensionalThreading mod on server
2. Create train and launch it with schedule
3. Restart server and get error. (Or even without restart)

### Expected Result

Fix train tick logick behavior to make it compatible with DimensionalThreading mod

### Crash Report or Log

https://gist.github.com/LittleLigr/e407565bea422213cc17718523f6a382

### Operating System

Ubuntu 22.04

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

DimensionalThreading

**Comment by TropheusJ** [comment]
interdimensional trains would need significant work to be thread safe. DT is obsolete, so this is no longer a concern
