### ISSUE TITLE
Block broken under boiler crashes server.

### ISSUE THREAD

**Issue by Sir-Capzalot** [Fabricators-of-Create/Create#680]
### Describe the Bug

The boiler looks for a blaze burner everytime I break a block beneath it. It does not find it because I forgot to place it and because of that the server instantly crashes.

### Reproduction Steps

1. Make tank
2. Steam engines on top
3. Water in tank
4. Break block below tank
5. Game crashes

### Expected Result

Block breaks and server continues normally.

### Screenshots and Videos

https://www.mediafire.com/file/zvw68d8fjuime92/2022-12-14_18-33-56.mp4/file

### Crash Report or Log

https://pastebin.com/qipuJhDG

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Too many mods to list, but I will gladly provide them if it becomes necessary to the process.

**Comment by TropheusJ** [comment]
issue with CC&A
