### ISSUE TITLE
Game crashes when rope pully tries to go through immersive portals using telecreate

### ISSUE THREAD

**Issue by LKSDBsadjis** [Fabricators-of-Create/Create#681]
### Describe the Bug

I'm trying to make an elevator that connects two buildings that are not on top of each other, so I decided to use immersive portals, I installed the telecreate mod hoping it would work, but not as soon as the rope starts moving the game crashes.

### Reproduction Steps

1. make a 4 by 4 elevator with a creative gen and gear box
2.install immersive portals and telecreate
3. have the rope try and run through the portal
...

### Expected Result

I expected the rope to move through the portal, grab the block, and pull them up and through

### Crash Report or Log

https://gist.github.com/LKSDBsadjis/eaef23592361f33ea92788c89b89d7f1

### Operating System

Windows 10, 64-bit

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

applied energistics 2
architectury
auto config
building wands
chisel and bits 
cloth config
controlling
custom splash screen
fabric api
IKnowWhatImDoing
immersive portals
indium
Jade
jei
journey map
mod menu
mouse tweaks
pehkui
smooth chunk
sodium
telecreate
worldedit

**Comment by TropheusJ** [comment]
Telecreate needs to update for the new create version
