### ISSUE TITLE
Failure to load EMI plugins when using Farmer's Delight ver1.3.7 or later at the same time

### ISSUE THREAD

**Issue by g2b3d4f** [Fabricators-of-Create/Create#682]
### Describe the Bug

Failure to load EMI plugins when using Farmer's Delight ver1.3.7 or later at the same time. 
When using ver 1.3.5 or earlier, the plugin loaded without problems.

### Reproduction Steps

1. Install Fabric, Fabric API, EMI, Create, and Farmer's Delight (ver 1.3.7 or later)
2. Load a world in Minecraft
3. EMI plugin failed to load, so recipes such as Crushing Wheels cannot be displayed.

### Expected Result

Plugin should load correctly

### Crash Report or Log

https://gist.github.com/g2b3d4f/851f40c4ce4a07a49e58381207e25b96

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Fabric Loader 0.14.11
Fabric API 0.69.0
EMI 0.5.1
Farmer's Delight 1.3.7

**Comment by Chikage0o0** [comment]
https://github.com/newhoryzon/farmers-delight-fabric/pull/116
 
You should close this issues
