### ISSUE TITLE
Incompatibility with The Twilight Forest

### ISSUE THREAD

**Issue by BMAB2012** [Fabricators-of-Create/Create#683]
### Describe the Bug

When using the latest version of Create (0.5.0g), the portals from The Twilight Forest no longer work. After downgrading to 0.5.0f, the portals work as intended.

### Reproduction Steps

1. Install Fabric
2. Install The Twilight Forest 4.2.1468 and Create 0.5.0g
3. Open a portal to The Twilight Forest
4. The portal doesn't work

### Expected Result

The portal should work.

### Operating System

Win 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
fixed in dev builds of TF
