### ISSUE TITLE
Clicking on a placard does not call FabricAPI event

### ISSUE THREAD

**Issue by ChristopherHaws** [Fabricators-of-Create/Create#684]
### Describe the Bug

When I click on a placard, it does not fire a `UseBlockCallback` or `UseEntityCallback` event.

### Reproduction Steps

1. Create an event handler for both `UseBlockCallback` and `UseEntityCallback` and put a breakpoint in it
2. Place a placard and click (use) it
3. Notice that neither of the fabric api callbacks get called
...

### Expected Result

Depending on the block type, it should call either `UseBlockCallback` or `UseEntityCallback`

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
working perfectly fine for me. Set up a handler that prints the ID of the clicked block and it's working. Can I see your event handler?

**Comment by ChristopherHaws** [comment]
You are correct. I'm not sure what I was doing wrong before but it is working now. Sorry for wasting your time. Thanks! :)
