### ISSUE TITLE
Incompatible with Twilight Forest mod (portal doesn't work)

### ISSUE THREAD

**Issue by moitripa** [Fabricators-of-Create/Create#686]
### Describe the Bug

Twilight Forest mod portal doesn't work with Create 1.19.2 v0.5.0g Patch 1. It used to work just fine in the previous Create Fabric version, Create 1.19.2 v0.5.0g.

### Reproduction Steps

I try to create a Twilight Forest portal, it doesn't work.

### Expected Result

The portal was supposed to be created when I throw a diamond.

### Crash Report or Log

https://gist.github.com/moitripa/f2987315d93febf8a1d0c18bceecece0

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

[Twilight Forest - Fabric - MC 1.19.2 - 4.2.310](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest/files/4086723)
[[1.19.2] Fabric API 0.69.0+1.19.2](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4162908)

### Additional Context

I can still play with the previous version of your mod, but i thought it was important to report this.

**Comment by TropheusJ** [comment]
already fixed in dev builds of TF
