### ISSUE TITLE
Mixer Doesn't Craft Single Ingredient Shapeless Recipes

### ISSUE THREAD

**Issue by 00-Steven** [Fabricators-of-Create/Create#687]
### Describe the Bug

Attempting to craft single ingredient shapeless crafting recipes with the mixer does not work, the mixer does not start mixing.
Tested with: cornflower>blue dye, dandelion>yellow dye, oak log>planks, iron ingot>nugget.

Normal mixing recipes still seem to work.
Tested with: andesite&zinc nugget>andesite alloy.
Shapeless recipes with multiple ingredients also still seem to work.
Tested with: blaze powder&pearl>ender eye, green&blue dye>cyan dye.

### Reproduction Steps

1. Set up mixer&basin, power, test with andesite&zinc nuggets into andesite alloy recipe.
2. Throw in cornflower.
3. Watch as the mixer does not mix nor craft.

### Expected Result

The mixer should mix and craft the cornflower into blue dye.
Or, well, any single ingredient shapeless crafting recipe.

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Tried both on Quilt and Fabric
Quilt 0.17.8:
qfapi-4.0.0-beta.24_qsl-3.0.0-beta.24_fapi-0.68.0_mc-1.19.2.jar

Fabric 0.14.11:
fabric-api-0.69.0+1.19.2.jar

### Additional Context

Pondering the Mechanical Mixer notes:
_Available recipes include any Shapeless Crafting Recipe, plus a couple extra ones_

**Comment by 00-Steven** [comment]
On closer inspection, this seems to also be a problem on Forge.
Regardless, spinning up a dev instance to take a closer look.

**Comment by 00-Steven** [comment]
So it seems to be a case of `> 1` instead of `>= 1` in method `matchStaticFilters` in class `MechanicalMixerTileEntity` (ln 258) package `com.simibubi.create.content.contraptions.components.mixer`.

Replacing `r.getIngredients().size() > 1` with `r.getIngredients().size() >= 1` fixes it outright.

**Comment by 00-Steven** [comment]
Given it's also on Forge, addressed in pull request Creators-of-Create/Create#4161.

**Comment by JieningYu** [comment]
If this is an issue of Create Forge then close this one.

**Comment by TropheusJ** [comment]
don't, we track issues on both (in reference to a deleted comment)

**Comment by 00-Steven** [comment]
Was confused for a moment, but I see, deleted comment

**Comment by TropheusJ** [comment]
addressed in PR
