### ISSUE TITLE
Incompatibility with Carpet mod

### ISSUE THREAD

**Issue by Oliver-makes-code** [Fabricators-of-Create/Create#69]
### Describe the Bug

Loading worlds fail when Carpet mod is installed

### Reproduction Steps

1. Install Carpet mod, Create fabric, and Fabric API
2. Load up a world

### Expected Result

The world loads as intended

### Crash Report or Log

https://paste.ee/p/rGl0b

### Operating System

Windows 11

### Mod Version

0.4.0b

### Minecraft Version

1.18.1

**Comment by AeiouEnigma** [comment]
Mixin conflict, I'll take a look at it soon
