### ISSUE TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create'!

### ISSUE THREAD

**Issue by N1gachu** [Fabricators-of-Create/Create#691]
### Describe the Bug

While trying to launch minecraft 1.19.2 in fabric, [ 1.19.2 (0.14.11)], this the following message appears: 
The game crashed whilst initializing game 
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create'!
I've reinstaled fabric quite times and the same with create. I don't know what to do.

Thanks.

### Reproduction Steps

1.
2.
3.
...
Have minecraft.
Fabric.
Create mod
Wait until it crashes.
Post something in github
Wait response. 

### Expected Result

Someone helping me.

### Crash Report or Log

The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create'!

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

![Screenshot_1](https://user-images.githubusercontent.com/120969629/208311722-136dcb10-67c0-46c7-ad2b-4e4902a46f9c.png)

**Comment by TropheusJ** [comment]
can't do anything without the full log

**Comment by N1gachu** [comment]
There you have man, thanks!
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2022-12-19 07:31:42
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due
to errors, provided by 'create'!
at
net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
at
net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
at
net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
at
net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
at net.minecraft.class_310.<init>(class_310.java:459)
at net.minecraft.client.main.Main.method_44604(Main.java:205)
at net.minecraft.client.main.Main.main(Main.java:51)
at
net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by:
net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException:
Failed loading config file create-common.toml of type COMMON for modid
create
at
net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:57)
at
net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:74)
at
net.minecraftforge.fml.config.ConfigTracker.loadConfig(ConfigTracker.java:58)
at
net.minecraftforge.fml.config.ConfigTracker.trackConfig(ConfigTracker.java:51)
at net.minecraftforge.fml.config.ModConfig.<init>(ModConfig.java:36)
at net.minecraftforge.fml.config.ModConfig.<init>(ModConfig.java:41)
at
net.minecraftforge.api.ModLoadingContext.registerConfig(ModLoadingContext.java:25)
at
com.simibubi.create.foundation.config.AllConfigs.register(AllConfigs.java:49)
at com.simibubi.create.Create.onInitialize(Create.java:109)
at
net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
... 8 more
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not
enough data available
at
com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22)
at
com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36)
at
com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49)
at
com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123)
at
com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166)
at
com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145)
at
com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55)
at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44)
at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
at
com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
at
com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
at
com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
at
com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73)
at
com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85)
at
net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:53)
... 17 more


A detailed walkthrough of the error, its code path and all known details is
as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
at
net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
at
net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
at
net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
at
net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
Modules:
ADVAPI32.dll:API base de Windows 32 avanzado:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
COMCTL32.dll:Biblioteca de controles de la experiencia del usuario:6.10
(WinBuild.160101.0800):Microsoft Corporation
CRYPT32.dll:Crypto API32:10.0.19038.1 (WinBuild.160101.0800):Microsoft
Corporation
CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546
(WinBuild.160101.0800):Microsoft Corporation
CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546
(WinBuild.160101.0800):Microsoft Corporation
DBGHELP.DLL:Windows Image Helper:10.0.19041.867
(WinBuild.160101.0800):Microsoft Corporation
DNSAPI.dll:DLL de API de cliente DNS:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
GDI32.dll:GDI Client DLL:10.0.19041.2130 (WinBuild.160101.0800):Microsoft
Corporation
IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.2193
(WinBuild.160101.0800):Microsoft Corporation
IPHLPAPI.DLL:API auxiliar para IP:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
KERNEL32.DLL:Archivo DLL de cliente API BASE de Windows NT:10.0.19041.1741
(WinBuild.160101.0800):Microsoft Corporation
KERNELBASE.dll:Archivo DLL de cliente API BASE de Windows
NT:10.0.19041.1741 (WinBuild.160101.0800):Microsoft Corporation
MpOav.dll:IOfficeAntiVirus Module:4.18.2207.7
(WinBuild.160101.0800):Microsoft Corporation
NLAapi.dll:Network Location Awareness 2:10.0.19041.2193
(WinBuild.160101.0800):Microsoft Corporation
NSI.dll:NSI User-mode interface DLL:10.0.19041.610
(WinBuild.160101.0800):Microsoft Corporation
NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1
(WinBuild.160101.0800):Microsoft Corporation
Ole32.dll:Microsoft OLE para Windows:10.0.19041.1320
(WinBuild.160101.0800):Microsoft Corporation
OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft
Corporation
PSAPI.DLL:Process Status Helper:10.0.19041.546
(WinBuild.160101.0800):Microsoft Corporation
Pdh.dll:Ayudante de los datos de rendimiento DLL de Windows:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
RPCRT4.dll:Tiempo de ejecución de llamada a procedimiento
remoto:10.0.19038.1 (WinBuild.160101.0800):Microsoft Corporation
SHCORE.dll:SHCORE:10.0.19038.1 (WinBuild.160101.0800):Microsoft Corporation
SHELL32.dll:Archivo DLL común del shell de Windows:10.0.19041.964
(WinBuild.160101.0800):Microsoft Corporation
USER32.dll:Archivo DLL de cliente API USER de Windows
multiusuario:10.0.19038.1 (WinBuild.160101.0800):Microsoft Corporation
USERENV.dll:Userenv:10.0.19038.1 (WinBuild.160101.0800):Microsoft
Corporation
VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by:
vcwrkspc:Microsoft Corporation
VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546
(WinBuild.160101.0800):Microsoft Corporation
WINHTTP.dll:Servicios HTTP de Windows:10.0.19041.2075
(WinBuild.160101.0800):Microsoft Corporation
WINMM.dll:MCI API DLL:10.0.19038.1 (WinBuild.160101.0800):Microsoft
Corporation
WS2_32.dll:DLL de 32 bits de Windows Socket 2.0:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
Wldp.dll:Directiva de bloqueo de Windows:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
amsi.dll:Anti-Malware Scan Interface:10.0.19041.2075
(WinBuild.160101.0800):Microsoft Corporation
bcrypt.dll:Biblioteca de primitivas criptográficas de Windows:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
bcryptPrimitives.dll:Windows Cryptographic Primitives
Library:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384
(WinBuild.160101.0800):Microsoft Corporation
combase.dll:Microsoft COM para Windows:10.0.19041.1320
(WinBuild.160101.0800):Microsoft Corporation
dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.789
(WinBuild.160101.0800):Microsoft Corporation
dhcpcsvc.DLL:Servicio cliente DHCP:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
dhcpcsvc6.DLL:Cliente DHCPv6:10.0.19038.1 (WinBuild.160101.0800):Microsoft
Corporation
fwpuclnt.dll:API de modo usuario de FWP/IPsec:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
gdi32full.dll:GDI Client DLL:10.0.19041.2130
(WinBuild.160101.0800):Microsoft Corporation
java.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
javaw.exe:OpenJDK Platform binary:17.0.3.0:Microsoft
jemalloc.dll
jimage.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
jli.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
jna16303277565478104363.dll:JNA native library:6.1.2:Java(TM) Native Access
(JNA)
jsvml.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
jvm.dll:OpenJDK 64-Bit server VM:17.0.3.0:Microsoft
kernel.appcore.dll:AppModel API Host:10.0.19041.546
(WinBuild.160101.0800):Microsoft Corporation
lwjgl.dll
management.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
management_ext.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by:
vcwrkspc:Microsoft Corporation
msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789
(WinBuild.160101.0800):Microsoft Corporation
msvcrt.dll:Windows NT CRT DLL:7.0.19041.546
(WinBuild.160101.0800):Microsoft Corporation
mswsock.dll:Proveedor de servicios de Microsoft Windows Sockets
2.0:10.0.19038.1 (WinBuild.160101.0800):Microsoft Corporation
napinsp.dll:Proveedor de correcciones de compatibilidad (shim) de
nomenclaturas de correo electrónico:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
ncrypt.dll:Enrutador de Windows NCrypt:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
net.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
nio.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
ntdll.dll:DLL del nivel de Windows NT:10.0.19041.1741
(WinBuild.160101.0800):Microsoft Corporation
perfos.dll:DLL de objetos de rendimiento del sistema Windows:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
pnrpnsp.dll:Proveedor de espacio de nombres PNRP:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
profapi.dll:User Profile Basic API:10.0.19041.844
(WinBuild.160101.0800):Microsoft Corporation
rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546
(WinBuild.160101.0800):Microsoft Corporation
rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1
(WinBuild.160101.0800):Microsoft Corporation
sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1
(WinBuild.160101.0800):Microsoft Corporation
shlwapi.dll:Biblioteca de utilidades de Shell:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
sunmscapi.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789
(WinBuild.160101.0800):Microsoft Corporation
vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by:
vcwrkspc:Microsoft Corporation
verify.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
win32u.dll:Win32u:10.0.19041.2251 (WinBuild.160101.0800):Microsoft
Corporation
windows.storage.dll:API de almacenamiento de Microsoft WinRT:10.0.19038.1
(WinBuild.160101.0800):Microsoft Corporation
winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546
(WinBuild.160101.0800):Microsoft Corporation
wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546
(WinBuild.160101.0800):Microsoft Corporation
zip.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
Stacktrace:
at net.minecraft.client.main.Main.method_44604(Main.java:205)
at net.minecraft.client.main.Main.main(Main.java:51)
at
net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
Minecraft Version: 1.19.2
Minecraft Version ID: 1.19.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 17.0.3, Microsoft
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
Memory: 521773832 bytes (497 MiB) / 1577058304 bytes (1504 MiB) up to
2147483648 bytes (2048 MiB)
CPUs: 4
Processor Vendor: AuthenticAMD
Processor Name: AMD Ryzen 3 2200G with Radeon Vega Graphics
Identifier: AuthenticAMD Family 23 Model 17 Stepping 0
Microarchitecture: unknown
Frequency (GHz): 3.49
Number of physical packages: 1
Number of physical CPUs: 4
Number of logical CPUs: 4
Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
Graphics card #0 VRAM (MB): 2048.00
Graphics card #0 deviceId: 0x15dd
Graphics card #0 versionInfo: DriverVersion=30.0.13014.8
Graphics card #1 name: NVIDIA GeForce GTX 660
Graphics card #1 vendor: NVIDIA (0x10de)
Graphics card #1 VRAM (MB): 2048.00
Graphics card #1 deviceId: 0x11c0
Graphics card #1 versionInfo: DriverVersion=30.0.14.7381
Memory slot #0 capacity (MB): 8192.00
Memory slot #0 clockSpeed (GHz): 2.40
Memory slot #0 type: DDR4
Virtual memory max (MB): 15294.28
Virtual memory used (MB): 7058.53
Swap memory total (MB): 9216.00
Swap memory used (MB): 227.12
JVM Flags: 9 total;
-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
-Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC
-XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50
-XX:G1HeapRegionSize=32M
Fabric Mods:
create: Create 0.5.0g-796+1.19.2
com_google_code_findbugs_jsr305: jsr305 3.0.2
fake-player-api: Fake Player API 0.5.0
flywheel: Flywheel 0.6.8-1
forgeconfigapiport: Forge Config API Port 4.2.6
com_electronwill_night-config_core: core 3.6.5
com_electronwill_night-config_toml: toml 3.6.5
milk: Milk Lib 1.0.51
dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
noindium: No Indium? 1.1.0+1.19
porting_lib: Porting Lib 2.1.623+1.19.2
forge_tags: Porting Lib Tags 3.0
porting_lib_base: Porting Lib Base 2.1.623+1.19.2
com_github_llamalad7_mixinextras: MixinExtras 0.1.1
mm: Manningham Mills 2.3
serialization_hooks: Serialization Hooks 0.3.26
porting_lib_entity: Porting Lib Entity 2.1.623+1.19.2
porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.623+1.19.2
porting_lib_model_generators: Porting Lib Model Generators 2.1.623+1.19.2
porting_lib_models: Porting Lib Models 2.1.623+1.19.2
porting_lib_networking: Porting Lib Networking 2.1.623+1.19.2
porting_lib_obj_loader: Porting Lib Obj Loader 2.1.623+1.19.2
porting_lib_model_loader: Porting Lib Model Loader 2.1.623+1.19.2
porting_lib_transfer: Porting Lib Transfer 2.1.623+1.19.2
porting_lib_extensions: Porting Lib Extensions 2.1.623+1.19.2
porting_lib_accessors: Porting Lib Accessors 2.1.623+1.19.2
porting_lib_attributes: Porting Lib Attributes 2.1.623+1.19.2
porting_lib_constants: Porting Lib Constants 2.1.623+1.19.2
porting_lib_common: Porting Lib Common 2.1.623+1.19.2
reach-entity-attributes: Reach Entity Attributes 2.3.0
registrate-fabric: Registrate for Fabric 1.1.44-MC1.19.2
decorative_blocks: Decorative Blocks 3.0.0
fabric-api: Fabric API 0.69.0+1.19.2
fabric-api-base: Fabric API Base 0.4.13+0d0f210290
fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1)
1.1.22+c6af733c90
fabric-client-tags-api-v1: Fabric Client Tags 1.0.3+b35fea8390
fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
fabric-content-registries-v0: Fabric Content Registries (v0)
3.4.4+6064db2a90
fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+27265b3490
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
fabric-data-generation-api-v1: Fabric Data Generation API (v1)
5.3.3+ad31814d90
fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
fabric-events-interaction-v0: Fabric Events Interaction (v0)
0.4.31+6eb9a2a190
fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.36+9244241690
fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.23+aaaf9d3390
fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.21+df3654b390
fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
fabric-loot-api-v2: Fabric Loot API (v2) 1.1.10+83a8659290
fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.13+9e7660c690
fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.21+33fbc73890
fabric-models-v0: Fabric Models (v0) 0.3.19+c6af733c90
fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
fabric-object-builder-api-v1: Fabric Object Builder API (v1)
4.1.3+06e0e25190
fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
fabric-renderer-api-v1: Fabric Renderer API (v1) 1.1.0+e7aeff4590
fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.17+aeb40ebe90
fabric-renderer-registries-v1: Fabric Renderer Registries (v1)
3.2.22+df3654b390
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1)
0.3.17+0d0f210290
fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
fabric-rendering-v0: Fabric Rendering (v0) 1.1.25+df3654b390
fabric-rendering-v1: Fabric Rendering (v1) 1.11.1+73145abb90
fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1)
2.1.1+aae9039d90
fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.2+574a764890
fabric-screen-api-v1: Fabric Screen API (v1) 1.0.30+b0bc9a6790
fabric-screen-handler-api-v1: Fabric Screen Handler API (v1)
1.3.4+1cc24b1b90
fabric-sound-api-v1: Fabric Sound API (v1) 1.0.1+c4f28df590
fabric-textures-v0: Fabric Textures (v0) 1.0.22+aeb40ebe90
fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners
(v1) 1.3.2+42d99c3290
fabricloader: Fabric Loader 0.14.11
indium: Indium 1.0.9+mc1.19.2
java: OpenJDK 64-Bit Server VM 17
jei: Just Enough Items 11.4.0.290
minecraft: Minecraft 1.19.2
sodium: Sodium 0.4.4+build.18
org_joml_joml: joml 1.10.4
worldedit: WorldEdit 7.2.12+6240-87f4ae1
Flywheel Backend: Uninitialized
Launched Version: fabric-loader-0.14.11-1.19.2
Backend library: LWJGL version 3.3.1 SNAPSHOT
Backend API: Unknown
Window size: <not initialized>
GL Caps: Using framebuffer using OpenGL 3.2
GL debug messages: <disabled>
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fabric'
Type: Client (map_client.txt)
CPU: <unknown>

**Comment by TropheusJ** [comment]
Your config looks corrupted. Delete it so it regenerates

**Comment by N1gachu** [comment]
Where can I delete it?

**Comment by TropheusJ** [comment]
.minecraft/config

**Comment by N1gachu** [comment]
Got it, thanks!

**Comment by TropheusJ** [comment]
assuming it worked

**Comment by N1gachu** [comment]
Yes! It worked. Thank you so much for your help.
