### ISSUE TITLE
something wrong with mixin, i think

### ISSUE THREAD

**Issue by TNT4ME** [Fabricators-of-Create/Create#692]
### Describe the Bug

loading create crashes the game
version 1.19.3

### Reproduction Steps

[everything is the latest version]

1.load create using fabric
2. start the game
3. wait for it to crash

### Expected Result

game should run normally

### Crash Report or Log

https://paste.pythondiscord.com/sotijabina

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

![image](https://user-images.githubusercontent.com/110022489/208404812-78264922-07a4-49b9-8c14-b3bd4c753613.png)

**Comment by JieningYu** [comment]
Create fabric is not for 1.19.3 now.

**Comment by theoparis** [comment]
> Create fabric is not for 1.19.3 now.

Is there another issue for tracking the progresss for 1.19.3?

**Comment by JieningYu** [comment]
Please check Create Forge, but not here.
