### ISSUE TITLE
Issue with EMI?

### ISSUE THREAD

**Issue by ZUIXIIDE** [Fabricators-of-Create/Create#693]
### Describe the Bug

When I hold W to ponder the game immediately crash, I see the log file mention EMI but not very sure.

### Reproduction Steps

1. Using FSMP modpack
2. get into any world
3. find create's Item and hold W

### Expected Result

Be able to ponder again

### Crash Report or Log

https://gist.github.com/ZUIXIIDE/93d009a4eb8cdd6a1c1cb0480c7aedf5

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

[Dense Ores: Refabricated (by Luligabi12)](https://www.curseforge.com/minecraft/mc-mods/dense-ores-refabricated)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Smooth Swapping (Fabric) (by Schauweg)](https://www.curseforge.com/minecraft/mc-mods/smooth-swapping)
[Wavey Capes (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/waveycapes)
[Charm (by svenhjol)](https://www.curseforge.com/minecraft/mc-mods/charm)
[FTB Ultimine (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-fabric)
[What's That Slot? (by gegybeans)](https://www.curseforge.com/minecraft/mc-mods/whats-that-slot)
[Fabrishot (by ramidzkh)](https://www.curseforge.com/minecraft/mc-mods/fabrishot)
[Collective (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective-fabric)
[Better Mount HUD (by Lortseam_)](https://www.curseforge.com/minecraft/mc-mods/better-mount-hud)
[Origins: Classes (by Apace100)](https://www.curseforge.com/minecraft/mc-mods/origins-classes)
[YUNG's Better Mineshafts (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-fabric)
[Bad Wither No Cookie - Reloaded (by Kreezxil)](https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded)
[Snow Day (by itsmineblock11)](https://www.curseforge.com/minecraft/mc-mods/snowday)
[TrashSlot (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/trashslot-fabric-edition)
[Better minecart rotation (Fabric) (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/minecart-direction-follow)
[Falling Leaves (Fabric) (by RandomMcSomethin)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric)
[ToolTipFix (by Kyrptonaught)](https://www.curseforge.com/minecraft/mc-mods/tooltipfix)
[Content Creator Server Status (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/content-creator-server-status)
[Head Index (by potatoboy99999)](https://www.curseforge.com/minecraft/mc-mods/headindex)
[Portable Hole (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/portable-hole)
[HT's TreeChop (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechop)
[Simple Copper Pipes (by lunadedogs)](https://www.curseforge.com/minecraft/mc-mods/simple-copper-pipes)
[Nether Portal Accessibility [Forge/Fabric] [1.16-1.19.2] (by KxmischesDomi)](https://www.curseforge.com/minecraft/mc-mods/nether-portal-accessibility)
[Eating Animation [Fabric] (by theone_ss)](https://www.curseforge.com/minecraft/mc-mods/eating-animation-fabric)
[More Slabs, Stairs, and Walls (by Nibaru)](https://www.curseforge.com/minecraft/mc-mods/more-slabs-stairs-and-walls)
[More End Cities (by starbender_fr)](https://www.curseforge.com/minecraft/mc-mods/more-end-cities)
[TimeOutOut (Fabric) (by potatoboy99999)](https://www.curseforge.com/minecraft/mc-mods/timeoutout-fabric)
[Botany Pots (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/botany-pots)
[Nutritious Milk (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/nutritious-milk-fabric)
[Carpet Extra (by gnembon)](https://www.curseforge.com/minecraft/mc-mods/carpet-extra)
[TieredZ (by Globox_Z)](https://www.curseforge.com/minecraft/mc-mods/tieredz)
[Passive Endermen (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/passive-endermen-fabric)
[Comforts (Fabric 1.16.5 - 1.19.2) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts-fabric)
[Botany Pots Tiers (by Ultramegaaa)](https://www.curseforge.com/minecraft/mc-mods/botany-pots-tiers)
[Expanded Armor Enchanting (by SmushyTaco)](https://www.curseforge.com/minecraft/mc-mods/expanded-armor-enchanting)
[Hexalib (by itsmineblock11)](https://www.curseforge.com/minecraft/mc-mods/hexalib)
[Spyglass Improvements: Zoom, Quick Access... [Fabric/Forge] (by Im_JC52)](https://www.curseforge.com/minecraft/mc-mods/spyglass-improvements)
[Your Options Shall Be Respected (YOSBR) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/yosbr)
[Mouse Wheelie (Fabric) (by Siphalor)](https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie)
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[Raised (by yurisuika)](https://www.curseforge.com/minecraft/mc-mods/raised)
[Item Model Fix (Fabric) (by Pepper_Bell)](https://www.curseforge.com/minecraft/mc-mods/item-model-fix)
[Dark Paintings (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/dark-paintings)
[Block Runner (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/block-runner-forge)
[Materialisation (Fabric) [Fork] (by pitan76)](https://www.curseforge.com/minecraft/mc-mods/materialisation3)
[Iceberg [Fabric] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg-fabric)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Healing Campfire (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/healing-campfire-fabric)
[Create Fabric (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
[Accurate Maps (by D4rkness_King)](https://www.curseforge.com/minecraft/mc-mods/accurate-maps)
[Cloth API (Fabric) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-api)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Kambrik (by Ejektaflex)](https://www.curseforge.com/minecraft/mc-mods/kambrik)
[Entity Collision FPS Fix Refabricated (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix-fabric)
[CompleteConfig (by Lortseam_)](https://www.curseforge.com/minecraft/mc-mods/completeconfig)
[Environmental Creepers (by masady)](https://www.curseforge.com/minecraft/mc-mods/environmental-creepers)
[GeckoLib (by ThanosGecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[YUNG's Better Desert Temples (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples-fabric)
[Lithium (Fabric) (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/lithium)
[[Fabric/Forge] Market Crates (1.15 to 1.19) (by lfaoanl)](https://www.curseforge.com/minecraft/mc-mods/market-crates)
[MoreCulling (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/moreculling)
[Inventory Tabs (updated) (by Andrew6rant)](https://www.curseforge.com/minecraft/mc-mods/inventory-tabs-updated)
[AutoTag (by Apace100)](https://www.curseforge.com/minecraft/mc-mods/autotag)
[Customizable Player Models (Fabric) (by tom54541)](https://www.curseforge.com/minecraft/mc-mods/custom-player-models-fabric)
[Enchanting Infuser (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/enchanting-infuser-forge)
[oωo (owo-lib) (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
[Dynamic FPS (by juliand665)](https://www.curseforge.com/minecraft/mc-mods/dynamic-fps)
[Easy Anvils (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
[Extra Origins (by MoriyaShiine)](https://www.curseforge.com/minecraft/mc-mods/extra-origins)
[Cull Less Leaves (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/cull-less-leaves)
[Held Item Info (by Neecko5b84)](https://www.curseforge.com/minecraft/mc-mods/held-item-info)
[Building Wands (by nicguzzo)](https://www.curseforge.com/minecraft/mc-mods/building-wands)
[FerriteCore (Fabric) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric)
[ItemSwapper (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/itemswapper)
[FTB Library (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric)
[Particle Rain (by PigCart)](https://www.curseforge.com/minecraft/mc-mods/particle-rain)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[It Takes a Pillage (Fabric) (by izofar)](https://www.curseforge.com/minecraft/mc-mods/it-takes-a-pillage-fabric)
[Guard Villagers (Fabric/Quilt) (by MrSterner_)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers-fabric)
[Main Menu Credits (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/main-menu-credits)
[Armor Hud Redesign (by Klimat1k)](https://www.curseforge.com/minecraft/mc-mods/armor-hud-redesign)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[MaLiLib (by masady)](https://www.curseforge.com/minecraft/mc-mods/malilib)
[Jump Over Fences (by Kreezxil)](https://www.curseforge.com/minecraft/mc-mods/jump-over-fences-forge)
[Visual Workbench (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Naturalist (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/naturalist)
[Chime (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/chime-fabric)
[Colytra (Fabric) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/colytra-fabric)
[Another Furniture (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/another-furniture)
[Item Filters (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/item-filters)
[Goblin Traders [Fabric] (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblintraders-fabric)
[Extended Drawers (by MattiDragon_)](https://www.curseforge.com/minecraft/mc-mods/extended-drawers)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Wilder Wild [Fabric/Quilt] (by FrozenBlockMO)](https://www.curseforge.com/minecraft/mc-mods/wilder-wild)
[Continuity (by Pepper_Bell)](https://www.curseforge.com/minecraft/mc-mods/continuity)
[ServerCore (by Wesley8081)](https://www.curseforge.com/minecraft/mc-mods/servercore)
[Configured (Fabric) (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured-fabric)
[EMI (Item and Recipe Viewer) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/emi)
[Bountiful (Fabric) (by Ejektaflex)](https://www.curseforge.com/minecraft/mc-mods/bountiful-fabric)
[Reese's Sodium Options (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)
[Puzzles Lib (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Explorer's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/explorers-compass)
[Extra Classes - Origins (by proman468)](https://www.curseforge.com/minecraft/mc-mods/extra-classes-origins)
[Blur (Fabric) (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/blur-fabric)
[KleeSlabs (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/kleeslabs-fabric)
[Immersive Weathering [FABRIC] (by OrdanaryMods)](https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-fabric)
[Login Protection[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/login-protection)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Blossom (by yurisuika)](https://www.curseforge.com/minecraft/mc-mods/blossom)
[Connectible Chains [Fabric] (by legoatoom)](https://www.curseforge.com/minecraft/mc-mods/connectible-chains)
[Item Highlighter [Fabric] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/item-highlighter-fabric)
[Better Third Person (by Socolio)](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
[libIPN (by mirinimi)](https://www.curseforge.com/minecraft/mc-mods/libipn)
[Cammie's Minecart Tweaks (by Camellias_)](https://www.curseforge.com/minecraft/mc-mods/cammies-minecart-tweaks)
[Iris Shaders (by coderbot)](https://www.curseforge.com/minecraft/mc-mods/irisshaders)
[YUNG's API (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric)
[Chat Up! (by gnembon)](https://www.curseforge.com/minecraft/mc-mods/chat-up)
[Botany Trees (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/botany-trees)
[ExtraSounds (by stashymane)](https://www.curseforge.com/minecraft/mc-mods/extrasounds)
[Enhanced Block Entities (by FoundationGames)](https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities)
[Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[Highlight (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/highlight)
[Paxi (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/paxi-fabric)
[Rotten Creatures (by fusionstudiomc)](https://www.curseforge.com/minecraft/mc-mods/rotten-creatures)
[Auditory (by Sydokiddo)](https://www.curseforge.com/minecraft/mc-mods/auditory)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[YUNG's Better Ocean Monuments (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments-fabric)
[Language Reload (by Jerozgen)](https://www.curseforge.com/minecraft/mc-mods/language-reload)
[Spirit (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/spirit)
[Magnum Torch (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/magnum-torch-forge)
[Entity Texture Features - [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric)
[Skin Layers 3D (Fabric/Forge) (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
[Accurate Block Placement (by Clayborn)](https://www.curseforge.com/minecraft/mc-mods/accurate-block-placement)
[Trading Post (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/trading-post)
[OptiGUI (by opekope2)](https://www.curseforge.com/minecraft/mc-mods/optigui)
[Forge Config API Port (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[Universal Bone Meal (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/universal-bone-meal-forge)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Origins (Fabric) (by Apace100)](https://www.curseforge.com/minecraft/mc-mods/origins)
[Entity Culling Fabric/Forge (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Presence Footsteps [Fabric] (by S0llace)](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps)
[No Chat Reports (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports)
[Packet Size Doubler (by THESIIG)](https://www.curseforge.com/minecraft/mc-mods/packet-size-doubler)
[FTB Quests (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-quests-fabric)
[Smooth Boot (Fabric) (by UltimateBoomer)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot)
[Naturally Charged Creepers (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/naturally-charged-creepers-fabric)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[GUI Compass (Fabric Version) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/gui-compass-fabric-version)
[Food Effect Tooltips (by DaFuqsy)](https://www.curseforge.com/minecraft/mc-mods/food-effect-tooltips)
[Waystones (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones-fabric)
[Savage Ender Dragon[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/savage-ender-dragon)
[Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
[SlimyBoyos (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/slimyboyos)
[Excavator Mod (by DancZer1)](https://www.curseforge.com/minecraft/mc-mods/excavator)
[Sodium Extra (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/sodium-extra)
[No Fade (by UltimateBoomer)](https://www.curseforge.com/minecraft/mc-mods/no-fade)
[Fastload (by FluffyBumblebe3)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[Cyanide (Fabric) (by AlcatrazEscapee)](https://www.curseforge.com/minecraft/mc-mods/cyanide-fabric)
[Armor Statues (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/armor-statues)
[Advanced Netherite [FABRIC] (by AutovwDev)](https://www.curseforge.com/minecraft/mc-mods/advanced-netherite-fabric)
[Balm (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm-fabric)
[[FABRIC/QUILT] Disable Custom Worlds Advice (by rdvdev2)](https://www.curseforge.com/minecraft/mc-mods/fabric-disable-custom-worlds-advice)
[Client Side Noteblocks (by DaCubeKing)](https://www.curseforge.com/minecraft/mc-mods/client-side-noteblocks)
[Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
[Keep My Soil Tilled (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/keep-my-soil-tilled-fabric)
[GUI Clock (Fabric Version) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/gui-clock-fabric-version)
[MixinTrace (by comp500)](https://www.curseforge.com/minecraft/mc-mods/mixintrace)
[YUNG's Better Witch Huts (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts-fabric)
[OfflineSkins (Fabric) (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/offlineskins-fabric)
[Bartering Station (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/bartering-station)
[Too Fast (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/too-fast)
[Satin API (by PyrofabTheModsmith)](https://www.curseforge.com/minecraft/mc-mods/satin-api)
[TalkBubbles (by Globox_Z)](https://www.curseforge.com/minecraft/mc-mods/talkbubbles)
[CleanCut (by Rongmario)](https://www.curseforge.com/minecraft/mc-mods/cleancut)
[Clear Skies (by GrondagTheBarbarian)](https://www.curseforge.com/minecraft/mc-mods/clear-skies)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Immersive Paintings [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings)
[Easy Magic (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
[You're in Grave Danger (by b1n_ry)](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)
[Diagonal Fences (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences)
[TerraBlender (Fabric) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric)
[Jade Addons (Fabric) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade-addons-fabric)
[AntiGhost (by Giselbaer)](https://www.curseforge.com/minecraft/mc-mods/antighost)
[Entity View Distance (by Patbox)](https://www.curseforge.com/minecraft/mc-mods/entity-view-distance)
[Fabric Seasons (by D4rkness_King)](https://www.curseforge.com/minecraft/mc-mods/fabric-seasons)
[Very Many Players (Fabric) (by ishlandmc)](https://www.curseforge.com/minecraft/mc-mods/vmp-fabric)
[Better Climbing (by artemisSystem)](https://www.curseforge.com/minecraft/mc-mods/better-climbing)
[Sodium Shadowy Path Blocks (by Rynnavinx)](https://www.curseforge.com/minecraft/mc-mods/sodium-shadowy-path-blocks)
[YetAnotherConfigLib (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/yacl)
[YUNG's Better Strongholds (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds-fabric)
[LazyDFU (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/lazydfu)
[Recipe Cache (by biom4st3r1)](https://www.curseforge.com/minecraft/mc-mods/recipe-cache)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Farsight [Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight-fabric)
[Colormatic (by kwertiTheCats)](https://www.curseforge.com/minecraft/mc-mods/colormatic)
[Pick Up Notifier (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier)
[JamLib (by jamalam360)](https://www.curseforge.com/minecraft/mc-mods/jamlib)
[Borderless Mining (by comp500)](https://www.curseforge.com/minecraft/mc-mods/borderless-mining)
[Dusk[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dusk)
[On Soul Fire (by MoriyaShiine)](https://www.curseforge.com/minecraft/mc-mods/on-soul-fire)
[Automated Crafting (by supersaiyansubtlety)](https://www.curseforge.com/minecraft/mc-mods/automated-crafting)
[Better Tridents (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/better-tridents)
[Polymorph (Fabric) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric)
[Expanded Delight [Fabric] (by ianm1647)](https://www.curseforge.com/minecraft/mc-mods/expanded-delight)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Transparent (by Trikzon)](https://www.curseforge.com/minecraft/mc-mods/transparent)
[Nether Portal Spread (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread-fabric)
[BisectHosting Server Integration Menu [FABRIC] (by BisectHosting)](https://www.curseforge.com/minecraft/mc-mods/bisecthosting-server-integration-menu-fabric)
[Text Utilities (by chaws314)](https://www.curseforge.com/minecraft/mc-mods/text-utilities)
[MiniHUD (by masady)](https://www.curseforge.com/minecraft/mc-mods/minihud)
[Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[Probably Chests (by TheArcanePigeon)](https://www.curseforge.com/minecraft/mc-mods/probably-chests)
[Dark Loading Screen (by Neecko5b84)](https://www.curseforge.com/minecraft/mc-mods/dark-loading-screen)
[Why Am I on Fire? (by Ellivers)](https://www.curseforge.com/minecraft/mc-mods/why-am-i-on-fire)
[Better Animals Plus (by cybercat5555)](https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus)
[Show Me Your Skin! (by enjarai)](https://www.curseforge.com/minecraft/mc-mods/show-me-your-skin)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Friends&Foes (Fabric) (by faboslav)](https://www.curseforge.com/minecraft/mc-mods/friends-and-foes)
[Redstone Pen (by wilechaote)](https://www.curseforge.com/minecraft/mc-mods/redstone-pen)
[Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[Tom's Simple Storage Mod (Fabric) (by tom54541)](https://www.curseforge.com/minecraft/mc-mods/toms-storage-fabric)
[Alloy Forgery (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/alloy-forgery)
[Sodium (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/sodium)
[Emoji Type (Fabric) (by therealcyborgcabbage)](https://www.curseforge.com/minecraft/mc-mods/emoji-type-fabric)
[MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
[Krypton (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/krypton)
[Paintings ++ (by AbsolemJackdaw)](https://www.curseforge.com/minecraft/mc-mods/paintings)
[Custom Entity Models (CEM) (by dorianpb)](https://www.curseforge.com/minecraft/mc-mods/custom-entity-models-cem)
[Fast Furnace for Fabric (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/fast-furnace-for-fabric)
[Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
[Immersive Armors [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)
[Starlight (Fabric) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight)
[Name Pain (by naqaden)](https://www.curseforge.com/minecraft/mc-mods/name-pain)
[Not Enough Animations (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)
[Voice Chat Interaction (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/voice-chat-interaction)
[Mod Menu (by ProspectorDev)](https://www.curseforge.com/minecraft/mc-mods/modmenu)
[Shulker Drops Two (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/shulker-drops-two-fabric)
[Litematica (by masady)](https://www.curseforge.com/minecraft/mc-mods/litematica)
[Interactic (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/interactic)
[Better Safe Bed (by frankv_)](https://www.curseforge.com/minecraft/mc-mods/better-safe-bed)
[LambDynamicLights (by LambdAurora)](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights)
[Horse Stonks [Fabric/Forge] (by SanityCh3ck)](https://www.curseforge.com/minecraft/mc-mods/horse-stonks)
[FTB Teams (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric)
[Red Bits (by magistermaks)](https://www.curseforge.com/minecraft/mc-mods/red-bits)
[Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
[Expanded Axe Enchanting (by SmushyTaco)](https://www.curseforge.com/minecraft/mc-mods/expanded-axe-enchanting)
[Wolves Of Other Furs (W.O.O.F) (by itsmineblock11)](https://www.curseforge.com/minecraft/mc-mods/woof)
[ShulkerBoxTooltip [Fabric/Forge] (by MisterPeModder)](https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip)
[Carpet (by gnembon)](https://www.curseforge.com/minecraft/mc-mods/carpet)
[Cull Clouds (by yugamiineena)](https://www.curseforge.com/minecraft/mc-mods/cullclouds)
[Simple Backpack [FABRIC] (by kwpugh)](https://www.curseforge.com/minecraft/mc-mods/simple-backpack-fabric)

**Comment by SirMaxwellSmart** [comment]
I reported this issue to EMI, it was a bug on their end, and it should be patched in the latest version.
