### ISSUE TITLE
Bugs in the train

### ISSUE THREAD

**Issue by fangguan233** [Fabricators-of-Create/Create#694]
### Describe the Bug

The train made an error in front of the hell and the main world gate, causing the server to crash. The solution within the archive range (crash if the entity is loaded) is to delete the create-tracks.dat in the world folder data, but the train disappears (presumably the entity data is stored here

### Reproduction Steps

1.At the Hell Portal, put rails on both ends, and put rails on both ends of the main world. When the train passes, the train does not generate, the player card cannot move at the portal, and the vehicle model does not display. Then tp returns to the base, and walks to the main world again from the end of the world, the server crashes
2.When I try to open the map locally and load this block, the server crashes
3.When I try to change forge locally, open the map and load this block, the server crashes
4.When I use MCA to delete these blocks and enter this area, the server crashes (the bug still exists, and the track still reports an error)
...

### Expected Result

Fix the bug and create better create

### Screenshots and Videos

[](url)
[crash-2022-12-20_00.03.15-server.txt](https://github.com/Fabricators-of-Create/Create/files/10263841/crash-2022-12-20_00.03.15-server.txt)
[](url)
[create_tracks.txt](https://github.com/Fabricators-of-Create/Create/files/10263855/create_tracks.txt)
The later file can be modified to. dat (because it does not support uploading dat files), which is the file I deleted above

### Operating System

windows11 windows server 2016

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

When I only run create, the bug still exists
When I try to change to the forge version and switch the core, the bug also exists.
[all mods 2.zip](https://github.com/Fabricators-of-Create/Create/files/10263897/all.mods.2.zip)
[all mods 3.zip](https://github.com/Fabricators-of-Create/Create/files/10263898/all.mods.3.zip)
[all mods1.zip](https://github.com/Fabricators-of-Create/Create/files/10263899/all.mods1.zip)

**Comment by IThundxr** [comment]
If you can reproduce this on the latest version open a new issue
