### ISSUE TITLE
Mechanical saw visually is spinning only on 1 side with Sodium

### ISSUE THREAD

**Issue by SplendidAlakey** [Fabricators-of-Create/Create#695]
### Describe the Bug

Mechanical saw is visually not spinning, when viewed from some angles.

### Reproduction Steps

1. Place down a saw and power it
2. Walk around as you look at it

### Expected Result

Spinning animation no matter how you look at the saw.

### Screenshots and Videos

https://user-images.githubusercontent.com/86702831/208564171-bb963e05-4919-42aa-9df3-3713e0035323.mp4

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Sodium 0.4.4-build.18
Indium 1.0.9

**Comment by TropheusJ** [comment]
fixed by disabling Animate Only Visible Textures
