### ISSUE TITLE
[1.18.2] 0.5.0g Create Tank + MI Pipe = Crash

### ISSUE THREAD

**Issue by MSandro** [Fabricators-of-Create/Create#696]
### Describe the Bug

since I've updated to Create 0.5.0g I can't load my world.
tried on server and client.

### Reproduction Steps

1. place a Create Tank
2. place a filled fluid tank e.g. from MI
3. place and configure a MI pipe to transfer the fluid to the Create Tank
4. crash

### Expected Result

it should load up like bevore

### Crash Report or Log

https://gist.github.com/MSandro/234d148b8300ebe1dc8d7d4828374450

### Operating System

Linux

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

https://www.curseforge.com/minecraft/modpacks/sky-fabrication-3/files/4215918

**Comment by MSandro** [comment]
I've tried to reproduce the issue in a new world.
It is caused by combining Create Tanks with Pipes from Modern Industrialization.
1. place a Create Tank
2. place a filled fluid tank e.g. from MI
3. place and configure a MI pipe to transfer the fluid to the Create Tank
4. crash

**Comment by MSandro** [comment]
when will this fix be released on CurseForge?

**Comment by TropheusJ** [comment]
I'm aiming for about another week.

**Comment by MSandro** [comment]
Thanks, I hope it's stable again soon, I'm getting more and more crash reports from my community.
https://github.com/MSandro/sky_fabrication3/issues/59
