### ISSUE TITLE
Stockpile Switch and Fluid Tank

### ISSUE THREAD

**Issue by Nounejm** [Fabricators-of-Create/Create#697]
### Describe the Bug

If the fluid tank is 3 blocks tall, has to be 3 block tall, the stockpile switch will become buggy: wount jump from upper lane to lower lane.
Just noticed that the "pointer" on the side of the block is showing wrong.

### Reproduction Steps

1. Build a 3 block tall Fuild Tank
2. Put a Stockpile Switch on the side of the tank facing the tank.
3. Set the upper lane to 100%, set the lower lane to 25%.
4. Put a redstone next to the Stockpile Switch to see if there is a redstone output or not.
5. Start filling the tank with water.

As you are filling the trank, the "meter" should be in the upper lane moving to right side. When the "meter" reaches the end it should jump to lower lane , but it doest.

### Expected Result

The "meter" should jump from upper lane to lower lane when the "meter" reaches end.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/84151906/209018474-66701c38-2df0-4a98-8ac6-31ed51c6ea4b.png)
![image](https://user-images.githubusercontent.com/84151906/209018577-caa65604-129b-415a-bcad-36e2091bff7f.png)

### Crash Report or Log

No crash.

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Mods iam using:
create fabric
fabric api

### Additional Context

Enjoy your day.

**Comment by TropheusJ** [comment]
Since fluid amounts are internally 81x larger on fabric, we're losing floating point accuracy. This is supposed to be exactly 1.
![image](https://user-images.githubusercontent.com/60247969/209425062-ba2eccfe-9103-4c70-baac-456d0ad98a7f.png)
