### ISSUE TITLE
NullPointerException after placing deployer

### ISSUE THREAD

**Issue by ryleu** [Fabricators-of-Create/Create#698]
### Describe the Bug

My game crashed after placing a deployer. Whenever I load that chunk, the game crashes again.

### Reproduction Steps

1. Place a deployer

### Expected Result

The game does not crash.

### Crash Report or Log

https://pastebin.com/7aL8iAAn

### Operating System

Fedora 37

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

This is the pack I used:

[Winter Wonderland Bugged.zip](https://github.com/Fabricators-of-Create/Create/files/10283866/Winter.Wonderland.Bugged.zip)

And this is the world that's currently busted:

[world.zip](https://cdn.discordapp.com/attachments/810959625306243095/1055349549943762974/world.zip)

### Additional Context

The modpack works in Prism Launcher, MultiMC, and PolyMC and it uses packwiz to update things. If you're not comfortable with running that, I can upload a version with all of the mods already downloaded.

**Comment by TropheusJ** [comment]
duplicate of #503, remove tabtps

**Comment by ryleu** [comment]
Alright, thank you.
