### ISSUE TITLE
[Suggestion] Add is_fire, is_soul_fire, is_water, is_lava block tags for Fans Crafting System

### ISSUE THREAD

**Issue by kingkuys2123** [Fabricators-of-Create/Create#699]
### Describe the Suggestion

The title itself is self explanatory, It is to add compatibility with other mods that add their own fire blocks, soul fire blocks, and such.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/114457180/209154810-7bb766f0-f4da-47a4-8844-eaed26db7f0a.png)

**Comment by TropheusJ** [comment]
This should be suggested to the forge repo
