### ISSUE TITLE
Mechanical Arm will not refill Blaze Burner in time if fuel burn time exceeds max heat capacity

### ISSUE THREAD

**Issue by Cyklan** [Fabricators-of-Create/Create#700]
### Describe the Bug

When automatically filling a blaze burner with any fuel source (e.g. coal), a mechanical arm will always refill the blaze burner so that it never goes out. However lavas burn time ([1000 seconds or 20,000 ticks](https://minecraft.fandom.com/wiki/Lava_Bucket#Smelting)) exceeds the maximum heat capacity of a blaze burner ([10,000 ticks](https://github.com/Fabricators-of-Create/Create/blob/mc1.19/fabric/dev/src/main/java/com/simibubi/create/content/contraptions/processing/burner/BlazeBurnerTileEntity.java#L39)). The same happens for blocks of coal with a burn time of [800 seconds or 16,000 ticks](https://minecraft.fandom.com/wiki/Block_of_Coal#Fuel).

[This line](https://github.com/Fabricators-of-Create/Create/blob/88afd924f068cef53eb438dec648daf360969204/src/main/java/com/simibubi/create/content/contraptions/processing/burner/BlazeBurnerTileEntity.java#L215) probably causes the issue. The most plausible fix would probably be an extra check to see wether the fuel items burn time exceeds the max heat capacity and create an exception for it.

This causes the blaze burner to extinguish for a short time until the mechanical arm refills it with a new blaze burner, which will temporarily (if very shortly) lower the boilers level.

### Reproduction Steps

1. create a steam engine of any level over 1
2. add a mechanical arm that will fuel the blaze burners
3. wait for one of the blaze burners to run out (quick tip: `/data modify block x y z burnTimeRemaining set value 200`)
4. watch the level of the boiler go down until the mechanical arm refuels the blaze burner

### Expected Result

The mechanical arm should refuel the blaze burner so that it doesn't extinguish.

### Screenshots and Videos

I added a video showcasing the issue: https://youtu.be/jVBmlrIk6HU

EDIT: Here is another video showing the same contraption in forge without the described behaviour: https://www.youtube.com/watch?v=qjD2Hz8DpUU

### Operating System

Windows 10, Windows 11, Debian, MacOS 13

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
this has been fixed on forge and will be included in the next merge

**Comment by TropheusJ** [comment]
merged, fixed
