### ISSUE TITLE
Crashed when the basin output something

### ISSUE THREAD

**Issue by cyrxdzj** [Fabricators-of-Create/Create#704]
### Describe the Bug

I have a mechanical like this.
![image](https://user-images.githubusercontent.com/63708985/209484249-e39fa13e-7cd5-4f98-8828-6b32cc38640f.png)
When it output something(more exactly, Andesite Alloy), game crashed. Whenever it's single-player mode or multiplayer mode.
Even if I re-enter the game, the game will crash. 
Like this, the server crashes when it starts.
The bug is similar to #702 .

The MOD I installed:
![image](https://user-images.githubusercontent.com/63708985/209484609-0262dda7-1dd7-42a4-834c-8a588d5f6c6f.png)
![image](https://user-images.githubusercontent.com/63708985/209484611-bc3b0501-3e85-4909-92c2-3f5ce120d783.png)

https://user-images.githubusercontent.com/63708985/209484436-72012de6-6a26-4dc4-abab-91bfa76611e3.mp4

[错误报告-2022-12-26_07.25.06.zip](https://github.com/Fabricators-of-Create/Create/files/10300761/-2022-12-26_07.25.06.zip)
[crash-2022-12-25_22.29.31-server.txt](https://github.com/Fabricators-of-Create/Create/files/10300764/crash-2022-12-25_22.29.31-server.txt)
[crash-2022-12-25_22.30.14-server.txt](https://github.com/Fabricators-of-Create/Create/files/10300765/crash-2022-12-25_22.30.14-server.txt)
[crash-2022-12-25_22.32.24-server.txt](https://github.com/Fabricators-of-Create/Create/files/10300766/crash-2022-12-25_22.32.24-server.txt)

### Reproduction Steps

1. Assemble mechanical structures.
2. Launch it.
3. Crash.
4. Launch the game again.
5. Crash.

### Expected Result

Don't crash and the basin output the Andesite Alloy normally.

### Operating System

Windows 11

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
update, this should have already been fixed.
