### ISSUE TITLE
Brass tunnels not merging

### ISSUE THREAD

**Issue by redstonerti** [Fabricators-of-Create/Create#706]
### Describe the Bug

Not only do brass tunnels not merge when they are together in a conveyor line, but even If you do get them to work and split items(which is very finneky), they constantly stop the belt and ruin the throughput

### Reproduction Steps

1. Place a belt, ideally at least 4 blocks long
2. Place a few brass tunnels together
3. Watch them not merge

### Expected Result

Conveyors merging and having one setting to control them all (Or so i've been told from the forge discord)

### Screenshots and Videos

https://streamable.com/71l93i

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
They're working fine for me. Maybe fixed in dev, maybe a mod incompat.

**Comment by Vwriter** [comment]
i have the same issue

**Comment by Vwriter** [comment]
(they dont even merge in the animated tutorial)

**Comment by TropheusJ** [comment]
they have been fixed in ponder. If they don't work in-world it's a separate issue.

**Comment by Vwriter** [comment]
it's weird 'cause i think i've got the latest version presented on CurseForge ( 1.19.2 0.5.0g-796 (AKA 0.5.0g Patch 1) ). Or is there anything newer?

**Comment by Vwriter** [comment]
(and they're still not working in ponder for me)

**Comment by TropheusJ** [comment]
the ponder fix is not released yet.

**Comment by Vwriter** [comment]
oh okay. So it should be fixed in the upcoming update, right?

**Comment by TropheusJ** [comment]
yes

**Comment by Vwriter** [comment]
Thanks!

**Comment by TropheusJ** [comment]
hopefully fixed?
