### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by redstonerti** [Fabricators-of-Create/Create#707]
### Describe the Bug

When shaders are enabled, there is weird flickering happening when a contraption is moving.
Also, when a contraption is near the position where it becomes stationary, it appears as if it's going back and forth really quickly.
I'm using Iris 1.4.5
Complementary Reimagined 1.4

### Reproduction Steps

1. Make a moving contraption
2. Turn on shaders

### Expected Result

No flickering with shaders
No back and forth when a moving contraption is about to become stationary

### Screenshots and Videos

https://streamable.com/a4bpbs

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
The flickering looks like z-fighting. Can I have your full mod list?
The "stuttering" seen at the end is just the contraption turning back into blocks. The position doesn't perfectly overlap, so there's a bit of a jump. It's more apparent at higher speeds. Same thing happens on forge.

**Comment by redstonerti** [comment]
Full mod list:
https://printermc.com/downloads/printstaller/modpacks/main/mods
https://printermc.com/downloads/mods.zip

**Comment by TropheusJ** [comment]
you have EBE installed, duplicate of #316
