### ISSUE TITLE
Clutch isn't able to stop contraption moving at max speed

### ISSUE THREAD

**Issue by redstonerti** [Fabricators-of-Create/Create#708]
### Describe the Bug

I'm sorry, I really don't know how to explain this bug, you're just going to have to watch the video
https://streamable.com/7uiowr

### Reproduction Steps

Place a rope pulley with a redstone contact on the bottom.
Place another redstone contact a few blocks under it.
Place a redstone link set to sender mode on the redstone contact
Place a redstone link set to receiver mode on a clutch next to the rope pulley
Place gearshift next to the clutch
Place a creative motor set to 256 rpm
Watch it fail.

### Expected Result

The contraption should have stopped

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
If you use a regular redstone line, it works. The link adds a bit of latency. Weird that it stops temporarily. 
This happens on forge too.

**Comment by redstonerti** [comment]
I can't use redstone lines. I want to use it on an elevator that is over 100 blocks high. The repeaters necessary to do it with just redstone would add much more latency. Aslo, the fact that it stops temporarily means that the signal did actually have enough time to reach the clutch.
