### ISSUE TITLE
REI laundry list

### ISSUE THREAD

**Issue by AeiouEnigma** [Fabricators-of-Create/Create#71]
- [x] 1.) Automated Shapeless Crafting and Automated Brewing categories do not exist in-game.
- [x] 2.) Recipes display even if their output does not exist (see recipes such as bulk washing of crushed tin/silver/nickel/lead/aluminum/platinum/osmium/uranium/quicksilver ores)
- [x] 3.) Bulk Blasting recipes are all either duplicated or triplicated.
- [x] 4.) CrushingCategory displays both the Crusher recipe for processing wool _and_ the Millstone recipe for processing wool
- [x] 5.) Mixing recipe for Builder's Tea only shows Jungle Leaves as a valid leaves input.
- [x] 6.) Mixing recipes are triplicated.
- [x] 7.) Compacting recipes for producing Honey Block, Andesite, Diorite, Granite, Blaze Cake Base, and Bar of Chocolate are included in the Mixing category.
- [x] 8.) Sequenced Assembly subcategory deployer inputs are displayed far outside of the REI interface, in the top left corner of the screen.
- [x] 9.) Sequenced Assembly subcategories and arrows do not display tooltips.
- [x] 10.) Sequenced Assembly outputs do not display their probability text in their tooltips.
- [x] 11.) Compacting category includes all Mixing recipes.
- [x] 12.) Automated Packing category includes Mixing recipes, which should only be in the Mixing tab.
- [x] 13.) Deploying category is missing Sandpaper Polishing recipe, which displays on Forge.
- [x] 14.) Spout category doesn't display recipes for filling ~~fluid containers such as~~ buckets ~~and potion bottles~~.
- [x] 14a.) Similarly, Item Draining category lacks recipes for draining buckets.
- [x] 14b.) Spout tab recipes are duplicated.
- [x] 14c.) Similarly, Item Draining category only has recipes for draining Builder's Tea and Honey Bottle.
- [x] 15.) Shapeless crafting recipes are displayed in the Mechanical Crafting and Automated Shaped Crafting categories. On Forge, shapeless crafting recipes are only used for the Automated Shapeless Crafting recipe category with the Mixer. Shapeless crafting recipes should be excluded from Automated Shaped Crafting and Mechanical Crafting, and should only be visible in the Automated Shapeless Crafting tab.
- [x] 15a.) Automated Shaped Crafting recipes are included in the Mechanical Crafting category. The Mechanical Crafting category should only include recipes which specifically require Mechanical Crafting to produce.

**Comment by RedWideWeb** [comment]
I suppose it is manual work and don’t require a lot of programming skills. We can probably help if you let us know how

**Comment by AeiouEnigma** [comment]
> I suppose it is manual work and don’t require a lot of programming skills. We can probably help if you let us know how

You'd be surprised. It's all programming stuff.

**Comment by RedWideWeb** [comment]
> > I suppose it is manual work and don’t require a lot of programming skills. We can probably help if you let us know how
> 
> You'd be surprised. It's all programming stuff.

Can you show an example?

**Comment by AeiouEnigma** [comment]
There's not any sort of template or specific known thing that will resolve these problems, or else we would've already fixed them. There's a lot of code [in our compat.rei package](https://github.com/Fabricators-of-Create/Create/tree/mc1.18/fabric/dev/src/main/java/com/simibubi/create/compat/rei) that collectively handles this stuff.

**Comment by AlphaMode** [comment]
14a and 5 has been fixed

**Comment by RedWideWeb** [comment]
Where is this fixed. There is no build since this bug was closed

**Comment by TropheusJ** [comment]
builds are broken currently, you need to compile it yourself for now
