### ISSUE TITLE
Items get duplicated when smelted on belt

### ISSUE THREAD

**Issue by morceaudebois** [Fabricators-of-Create/Create#713]
### Describe the Bug

Hi!
I'm trying to make an automatic smelting system, but it seems to duplicate the items after they get smelted. The original item stays on the belt when the new one gets created. Items that should get destroyed just stay on the belt. It worked fine initially, but after some time (I didn't change anything), it started doing this.

I tried to completely destroy and then remake the belt/lava/fans contraption, and it worked normally again for a few hours only to go back to the glitched state. 

### Reproduction Steps

1. Create a smelting system with a belt, fans and lava
2. Wait for a few hours
3. Notice the duplication

### Expected Result

Items shouldn't get duplicated

### Screenshots and Videos

https://user-images.githubusercontent.com/50768582/209714480-9b53ceb1-cf7e-469e-ba8a-561a4ea1922c.mp4

### Crash Report or Log

No error in the server log when duplication happens.

### Operating System

Server

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

<img width="347" alt="Screenshot 2022-12-27 at 20 38 24" src="https://user-images.githubusercontent.com/50768582/209714775-ec2eafe6-cba5-4d25-9562-76cce2fe69a6.png">

**Comment by TropheusJ** [comment]
This issue makes no sense. You're going to need to narrow down the cause further. I've had servers running for days, so it's not purely time based. Try to see if a mod causes it.

**Comment by IThundxr** [comment]
Can't reproduce, if anyone is able to reproduce this issue on the latest patch feel free to open  anew one
