### ISSUE TITLE
Item Vault eats items when used with Applied Energistics 2 ME Storage

### ISSUE THREAD

**Issue by Fade-Alchemist** [Fabricators-of-Create/Create#714]
### Describe the Bug

I am using the item vault in conjunction with my ME storage system. At first, it seemed to be working perfectly, but after getting a fair amount of items in the vault I noticed things were going missing.  I did some tests with some diamond blocks. I placed several in the system and then tried to find them again using the ME Crafting terminal, they appeared as expected.  I then logged out and back in, the diamond blocks were still there. I then logged out and reset the server and logged back on. Now the diamond blocks were missing. I was able to repeat this several times. 

I am playing  FTB SToneblock 3 version 1.5.0

The specific mods interacting are:
 
appliedenergistics2-forge-11.7.0.jar
 create-1.18.2-05.0.g
 

### Reproduction Steps

1. Full sized Item valut
2. ME system connected to item vault via item bus
3. Once filled with a fair amount of items, I noticed some items missing after the server restarts. I don't know when the items first started vanishing, I did not notice until there were a good amount of things in there. I can tell you that the vault in question is reading level 4 from a comparator. 
...

### Expected Result

My items remain in the vault until removed. 

### Screenshots and Videos

none

### Crash Report or Log

none

### Operating System

windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

no crash

### Additional Context

Context provided above

**Comment by TropheusJ** [comment]
forge issues should be reported to the forge repo.

**Comment by Fade-Alchemist** [comment]
oops sorry
