### ISSUE TITLE
Encased Chain Drive incorrectly keeps the rotational direction when changing between horizontal and vertical facing blocks

### ISSUE THREAD

**Issue by ChristopherHaws** [Fabricators-of-Create/Create#716]
### Describe the Bug

On the forge version, encased chain drives change the rotational direction based on if they are vertical or horizontal.

On the fabric version, encased chain drives going west to east keeps the same rotational direction when changed between horizonal and vertical facing.

### Reproduction Steps
![EncasedChainDrive2](https://user-images.githubusercontent.com/5934505/209814054-9c002b38-80e1-419a-ab68-c794a42869fd.gif)

### Expected Result

The fabric version should behave the same as the forge version. Up/down facing chain drives should always rotate the opposite direction of horizontal facing chain drives.

### Screenshots and Videos
Here are some gifs of the same setup in forge vs fabric:
![EncasedChainDrive-Forge](https://user-images.githubusercontent.com/5934505/209889915-2caf72e9-e737-4bed-b8f3-e471a2fc4655.gif)

![EncasedChainDrive-Fabric3](https://user-images.githubusercontent.com/5934505/209890129-7375926a-8805-466d-9d3c-f6a647592e8e.gif)

### Crash Report or Log

N/A

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods
These gifs were taken with nothing but create mod installed on both mod loaders.

**Comment by TropheusJ** [comment]
Behaves the same as forge on latest commit
![thing](https://user-images.githubusercontent.com/60247969/209895984-9b4b383a-6d51-4aed-a89c-a9b9e7a19877.gif)

**Comment by ChristopherHaws** [comment]
Very strange, is it the intended behavior that the bottom two rotate clockwise horizontally but counter-clockwise when vertical but the top two always spin clockwise? My understanding was that encased chain drives change the axis of rotation, but not the direction of the rotation.

**Comment by TropheusJ** [comment]
I wouldn't say it's intended, just how it turned out. It's not specific to chain drives, ex. rotating mechanical pistons can change which rotation direction extends it.
