### ISSUE TITLE
Filling fluid tanks crashes the game

### ISSUE THREAD

**Issue by Piotatotio** [Fabricators-of-Create/Create#719]
### Describe the Bug

Every time I start to fill a fluid tank it crashes the game

### Reproduction Steps

1.Place fluid tank.
2.Place pump and pipes.
3.Activate pump.
4.Game crashes.

### Expected Result

The fluid tank is meant to be filled but it crashes the game

### Crash Report or Log

The game crashed whilst ticking block entity Error: java.lang.NullPointerException: Cannot invoke "java.util.function.Predicate.test(Object)" because "this.validator" is null

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

I have a lot of mods and im not bothered listing 100+ mods

**Comment by Piotatotio** [comment]
Thanks for the help hope theres a fix because that is stopping me from making steam engines and progressing in the game.

**Comment by TropheusJ** [comment]
duplicate of #696
