### ISSUE TITLE
Crash on dedicated server due to Mixin conflict probably.

### ISSUE THREAD

**Issue by frikinjay** [Fabricators-of-Create/Create#72]
### Describe the Bug

Running create alongside a lot of other mods on a server causes it to crash. I tried removing every mod that touches LivingEntityMixin or the class it says in the log but it still crashes.

### Reproduction Steps

1. Have the mods from the mod list on a fabric server environment. 1.18.1 loader version 12.12
2. Run the server.
3. Bam swoosh woosh crash
...

### Expected Result

For the server to run as it did while my testing with no other mods.

### Crash Report or Log

https://pastebin.com/D5uQkdhq

### Operating System

Windows 10

### Mod Version

0.4.0b

### Minecraft Version

1.18.1

### Other Mods

	- additionalbars 2.2.1
	- adorn 3.1.0+1.18.1
	- advanced_runtime_resource_pack 0.3.7 via chisel
	- advancednetherite 1.3.1-1.18.1
	- adventurez 1.4.6
	- ae2 10.0.0-beta.3
	- ae2things 1.0.0-beta.1
	- ae2wtlib 10.0.0-beta.3
	- agape_space 0.4.5
	- akashictomeoftools 1.2
	- alloy_forgery 2.0.8+1.18
	- alternatecurrent 1.1.0
	- amplified_nether 1.0.1
	- annotateddi 2.0.4+1.18 via fireplacelib
	- antishulkerdupe 1.0.0
	- aopalliance_aopalliance 1.0 via annotateddi
	- appleskin mc1.18-2.2.0
	- aqupdcaracal 1.18-1.3.5.1
	- aqupdgrizzly 1.18-1.2.2
	- architectury 3.4.9
	- armorposer 1.0.2
	- attributefix 1.0.3
	- auto_planter 18.1-fabric
	- autoconfig1u 3.3.1
	- autosmeltenchant 1.1.0
	- awesomedungeon_ocean 1.0.3
	- basicaiots 1.3.3+1.18.1
	- bcc fabric-1.0.4
	- bclib 1.2.1
	- better_wandering_trader 1.8.0
	- better_withered_mobs 1.7.0
	- betterbeacon 1.0.7
	- betternether 6.0.8
	- blockus 2.3.4+1.18.1
	- blue_endless_jankson 1.2.1 via jankson
	- bosses_of_mass_destruction 1.3.3-1.18
	- botania 1.18.1-427-FABRIC
	- bountiful 2.0.1
	- cacao 0.5
	- camp_fires_cook_mobs 1.2.3+MC1.18-1.18.1
	- cardinal-components-base 4.0.1 via golemancy
	- cardinal-components-block 4.0.1 via botania
	- cardinal-components-entity 4.0.1 via golemancy
	- cardinal-components-item 4.0.1 via polymorph
	- cardinal-components-world 4.0.0 via bosses_of_mass_destruction
	- chat_plus 2.1.6
	- chickensshed 1.18.1-1.3
	- chisel 1.4.4
	- chiselsandbits 1.2.62
	- cleanview 1.18.1-v1-fabric
	- clickadv 2.1
	- cloth-api 2.0.54
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-client-events-v0 2.0.54 via cloth-api
	- cloth-common-events-v1 2.0.54 via cloth-api
	- cloth-config 6.1.48
	- cloth-datagen-api-v1 2.0.54 via cloth-api
	- cloth-utils-v1 2.0.54 via computercraft
	- clumps 8.0.4
	- cmdspy 1.2.3
	- columns 1.2.0
	- com_electronwill_night-config_core 3.6.3 via computercraft
	- com_electronwill_night-config_toml 3.6.3 via computercraft
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.13.0 via essential_commands
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_google_inject_guice 5.0.1 via annotateddi
	- com_moandjiezana_toml_toml4j 0.7.2 via deepslatecutting
	- com_typesafe_config 1.4.1 via confabricate
	- comforts 1.0.0-1.18
	- completeconfig 1.3.3 via spatialharvesters
	- computercraft 1.99.1
	- confabricate 2.2.0-SNAPSHOT+4.1.1 via croptopia
	- connected-doors 1.1+1.18
	- create mc1.18.1_v0.4b
	- crimsonnbt 1.18.1-Fabric-v1.0.0
	- croptopia 1.8.0
	- crowdin-translate 1.4+1.18 via camp_fires_cook_mobs
	- customstars 0.7+1.18
	- dankstorage 1.18.1-3.3
	- dark-enchanting 0.6.3+1.18
	- darkpaintings 9.0.2
	- darkwaters 0.0.9
	- dawn 3.2.0
	- decorative_blocks 2.0.2
	- deepslatecutting 1.3.0
	- diggusmaximus 1.5.2-1.18
	- dimores 1.0.2
	- disenchanter 0.1.4+1.18
	- dispenser_configurator 1.2.1+MC1.18-1.18.1
	- dml-refabricated 0.5.0-beta2
	- dml-refabricated-base 0.5.0-beta2 via dml-refabricated
	- dml-refabricated-events 0.5.0-beta2 via dml-refabricated
	- dml-refabricated-modular-armor 0.5.0-beta2 via dml-refabricated
	- dml-refabricated-rei 0.5.0-beta2 via dml-refabricated
	- dmlsimulacrum 0.5.0-beta2
	- draggable-resource-packs 2.0.0
	- dripstone_fluid_lib 1.1.1 via milk_plus
	- ducts 1.1.5
	- dungeons_arise 2.1.49c-fabric
	- earthtojavamobs 1.7.4+1.18
	- easymagic 3.2.1
	- ec-core 1.0.1-mc1.18.1 via essential_commands
	- eights_economy_p 1.0.1
	- emerald_tools 1.3.33
	- emotecraft 2.1-SNAPSHOT-build.10
	- enchant_the_rainbow 1.0.0
	- enhanced_quarries 1.2.0_RC9
	- equivalence 1.2.3
	- essential_commands 0.19.0-mc1.18.1
	- expanded_armor_enchanting 1.0.2
	- expanded_axe_enchanting 1.0.3
	- expanded_trident_enchanting 1.0.3
	- expanded_weapon_enchanting 1.0.2
	- expandedstorage 7.3.6
	- extrasponges 1.2.0
	- ezpas 2.0.1
	- fabric 0.45.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cd65 via fabric
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-data-generation-api-v1 1.0.0+3fec4ad9c8 via registrate-fabric
	- fabric-dimensions-v1 2.1.7+43d2957165 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-language-scala 1.1.0+scala.2.13.6
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cd65 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.0+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.8+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via eights_economy_p
	- fabric-registry-sync-v0 0.8.6+533be9ba65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.0.8+295197a765 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f5565 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricenchantments 0.6.1
	- fabricloader 0.12.12
	- fabricshieldlib 1.4.5-1.18 via magicfungi
	- fake-player-api 0.3.0 via create
	- fallingtree 3.0.1
	- farmersdelight 1.18.1-0.2.0
	- feature_nbt_deadlock_be_gone $version
	- ferritecore 4.0.0
	- fiber 0.23.0-2 via botania
	- fireplacelib 6.2.2+1.18
	- flan 1.18-1.6.5
	- flight_rings 1.6.1b
	- flytre_lib 1.6.4
	- forge_tags 1.3 via create
	- forgeconfigapiport 3.1.0
	- forgottenrecipes 1.18.1-1.0.0
	- friendsandfoes 1.0.2
	- geckolib3 3.0.23
	- geodes 1.2.0
	- giftit 1.5.0+mc1.18-rc3
	- go-fish 1.4.1-1.18.1
	- goldenhoppers 1.2.0
	- golemancy 1.1.4
	- golemsgalore 1.1.1-1.18
	- grass_pass 1.1.0
	- greater_eye 1.3.19
	- guild 0.3.7
	- hardened-crops 1.0
	- health_levels 1.0.2
	- horseinfo 0.4.1-1.18
	- hoverpets 0.1.1
	- hplus 3.0.1
	- indrev 1.13.2-BETA
	- interactic 0.1.7+1.18
	- invview 1.4.8-1.18+
	- io_leangen_geantyref_geantyref 1.3.11 via confabricate
	- ironchests 1.5.3
	- jankson 4.0.0+j1.2.0 via adorn
	- java 17
	- javax_inject_javax_inject 1 via annotateddi
	- kambrik 3.0.0
	- konkrete 1.3.3
	- ktdatataglib 1.6.4-1 via dml-refabricated
	- kyrptconfig 1.2.4-1.18 via diggusmaximus
	- lazydfu 0.1.2
	- libblockattributes 0.10.0
	- libblockattributes_core 0.10.0 via indrev
	- libblockattributes_fluids 0.10.0 via indrev
	- libblockattributes_items 0.10.0 via indrev
	- libcd 3.0.3+1.16.3 via adorn
	- libgui 5.2.0+1.18 via ae2things
	- libninepatch 1.1.0 via libgui
	- libraryferret 1.0.2
	- lithium 0.7.7
	- logprot 1.18-1.5
	- lootcrates 2.6.0-1.18.1
	- lovely_snails 1.0.3+1.18
	- maelstrom_library 1.2.3-1.18-rc3 via bosses_of_mass_destruction
	- magicfungi 0.6.2-BETA+1.18.1
	- magna 1.7.0-1.18-pre1 via indrev
	- mavm 1.0.7a
	- maybe-more-data 1.0.0-1.18 via deepslatecutting
	- megane 6.2.0
	- megane-applied-energistics-2 6.2.0+10.0.0-alpha.1 via megane
	- megane-base 6.2.0 via megane
	- megane-dml-simulacrum 6.2.0+0.5.0-beta2 via megane
	- megane-fabric-transfer 6.2.0+1.5.4-b4f4f6cda9 via megane
	- megane-industrial-revolution 6.2.0+1.13.1-BETA via megane
	- megane-lib-block-attributes 6.2.0+0.10.0 via megane
	- megane-reborn-core 6.2.0+5.1.0-beta.2 via megane
	- megane-runtime 6.2.0 via megane
	- megane-team-reborn-energy 6.2.0+2.0.0-beta1 via megane
	- megane-tech-reborn 6.2.0+5.1.0-beta.2 via megane
	- megane-vanilla 6.2.0+1.18.1 via megane
	- megane-wireless-networks 6.2.0+1.4.0 via megane
	- midnightlib 0.3.1
	- milk 0.1.6 via create
	- milk_plus 2.0.1
	- minecraft 1.18.1
	- miningcooldownfix 1.18.1-1.0.0
	- mm 2.3 via shulkerboxtooltip
	- mob_catcher 1.1.20
	- more-axolotls 1.0.2
	- morevillagers-fabric 3.1.0-SNAPSHOT
	- mostructures 1.3.0-pre1+1.18
	- mousewheelie 1.8.0+mc1.18-pre5
	- multipart_entities 1.1.4-1.18-rc3 via bosses_of_mass_destruction
	- multisleep 1.2
	- myron 1.6.2+1.18.1 via golemsgalore
	- nameplate 1.0.2
	- naturescompass 1.18.1-2.0.2-fabric
	- nears 1.1.2
	- neutral_animals 1.1.1
	- ninjaphenix_container_lib 1.2.10
	- no_null_processors 2.0.0+1.18
	- noenchantcap 1.18.1-fabric-2.1.0
	- noooooo 1.0.0
	- octo-economy-api 1.0.0 via eights_economy_p
	- omega-config 1.1.0 via dark-enchanting
	- openloader 11.0.3
	- ore_tree 0.2.0
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_spongepowered_configurate-core 4.1.1 via confabricate
	- org_spongepowered_configurate-extra-dfu4 4.1.1 via confabricate
	- org_spongepowered_configurate-gson 4.1.1 via confabricate
	- org_spongepowered_configurate-hocon 4.1.1 via confabricate
	- owo 0.3.14+1.18
	- paradoxconfig 0.5.1-beta via randore
	- patchouli 1.18.1-63-FABRIC
	- physicsmod 2.6.4
	- pigsteel 1.7.0
	- pitch-dark 2.0.0
	- placeholder-api 1.1.3+1.17.1 via essential_commands
	- player-data-api 0.1.0+1.18 via styledplayerlist
	- player_events 2.2.1
	- player_events_api 2.2.1 via player_events
	- playerabilitylib 1.4.0
	- polymorph 0.0.18-1.18.1
	- proper-mobcap-modifier 3.1
	- pugh_tools 1.1.15 via emerald_tools
	- puzzleslib 3.1.3
	- quarrymod 0.5.3
	- quarryplus 18.1.0
	- randore 1.4.1-1.18
	- reach-entity-attributes 2.1.1 via botania
	- reborncore 5.1.0-beta.4 via techreborn
	- recipecache 0.2.1-1.17.1
	- redbits 1.11.0
	- registrate-fabric MC1.18.1-1.0.7 via create
	- reinfbarrel 1.0.5+1.18
	- reinfcore 1.1.2+1.18 via reinfbarrel
	- repurposed_structures 3.2.0+1.18.1
	- resclone 1.7.1
	- resourcemelons 2.2.3
	- resourcemelonstechreborn 1.0.0
	- resourceoverhaul 2.3
	- retail 0.3.5
	- rhino 1800.1.7-build.92
	- right-click-harvest 1.1.0
	- roughlyenoughitems 7.1.357
	- roughlysearchable 2.3.0+1.18.1
	- satako 0.1.0-1.18.1
	- sculk_worm 0.1.3
	- searchlight 1.1.5
	- seedfix 1.0.0 via amplified_nether
	- sgui 1.0.0-rc6+1.18-pre5 via invview
	- shoppy 1.0.1
	- shulkerboxtooltip 3.0.5+1.18
	- shwfox 1.2+fabric
	- simple_backpack 1.2.27
	- simple_cobblestone_generator 1.1.7
	- simplyplatinum 4.2
	- skyvillages 1.0.1-1.18.1-fabric
	- slotlink 4.0.4
	- smart_pipes 3.0.0-1.18.1
	- smoothboot 1.18-1.7.0
	- soaringstructures2 1.18 - 2.0
	- someforgepatchesported 1.0.2
	- sound_physics_remastered 1.18.1-1.0.3
	- spatialharvesters 0.11.12d
	- starlight 1.0.0+fabric.d0a3220
	- statues 1.1
	- step-height-entity-attribute 1.0.0 via botania
	- stoneholm 1.4.1
	- storagecabinet 1.4.2
	- structurized 1.4.0+1.18 via golemsgalore
	- styledplayerlist 2.1.3+1.18
	- talking-villagers 1.1.3
	- team_reborn_energy 2.1.0 via spatialharvesters
	- techreborn 5.1.0-beta.4
	- terraform-shapes-api-v1 2.1.0 via dawn
	- terraform-wood-api-v1 2.0.2 via blockus
	- terralith 2.0.8
	- thonkutil 2.6.0+1.18
	- thonkutil-base 1.4.0+6a7a08aec8 via thonkutil
	- thonkutil-capes-v1 1.2.0+a46c8f89c8 via thonkutil
	- thonkutil-customization 1.0.1+6a7a08aec8 via thonkutil
	- thonkutil-legacy 1.0.7+6fa117f8c8 via thonkutil
	- thonkutil-potions-v0 1.2.5+6a7a08aec8 via thonkutil
	- thonkutil-trades-v1 1.1.5+6a7a08aec8 via thonkutil
	- ticktock 1.3.0
	- timeoutout 1.0.0+1.18
	- tinyskeletons 3.1.0
	- toms_storage 1.1.19
	- tooltiprareness 1.0.3
	- totw_additions 1.1.0
	- towers_of_the_wild_reworked 2.1.0
	- trade 1.2.2
	- tradingpost 3.1.2
	- transportables 1.1
	- trapexpansion 1.3.3
	- trinkets 3.1.0
	- tweed 3.0.0-beta.22 via wandering_collector
	- tweed4_annotated 1.2.0 via giftit
	- tweed4_base 1.3.1 via giftit
	- tweed4_data 1.2.0 via giftit
	- tweed4_data_hjson 1.1.0 via giftit
	- twigs 1.1.2
	- twm 0.2
	- unforgivingvoid 3.1.1+1.18
	- untitledduckmod 0.3.0
	- unvotedandshelved 1.0.4
	- urns 1.0.1
	- vanilla_degus 1.3.0
	- villager_see_villager_do 1.1.3+MC1.18-1.18.1
	- visualoverhaul 4.0.0
	- visualworkbench 3.1.0
	- voidz 1.0.5
	- wandering_collector 1.0.2+mc1.17
	- wands 2.3.1
	- waystones 2.4.1
	- whereisit 1.14.4
	- wireless_redstone 2.0.0
	- wirelessnetworks 1.4.1
	- wthit 4.4.0
	- xaerominimap 21.23.0
	- xaeroworldmap 1.19.0
	- xlpackets 2.1-1.17.1
	- xp_storage 1.4.3+1.18
	- xp_storage_trinkets 0.1+1.18
	- zihlaunchpads 1.2.0

**Comment by AeiouEnigma** [comment]
It's a Mixin Redirect conflict with the the Fabric version of Chisels & Bits, thanks for reporting

**Comment by frikinjay** [comment]
No problem : )

**Comment by TropheusJ** [comment]
should have been fixed [here](https://github.com/Fabricators-of-Create/Create/commit/0b180cc8a212e4cc2a72c59f33e62bb10aa4eb9f), reopen if it persists.
