### ISSUE TITLE
Banners dont stick to creations using glue

### ISSUE THREAD

**Issue by Piotatotio** [Fabricators-of-Create/Create#720]
### Describe the Bug

Banners are not able to get stuck to walls using glue

### Reproduction Steps

1.place banner
2.try sticking to wall

### Expected Result

I expected that it would let me stick it.

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

Many mods

**Comment by IThundxr** [comment]
Will be fixed by patch g
