### ISSUE TITLE
ToolBox kick 1.19.2

### ISSUE THREAD

**Issue by LIUKRAST** [Fabricators-of-Create/Create#721]
### Describe the Bug

Im playing in a server (which is mine) and using create mod 1.19.2.

Some items kicks users when they open it.

### Reproduction Steps

1. Craft yourself a toolbox
2. Put some items inside (Example: those in the screnshot section of the issue
3. Open the toolbox
...

### Expected Result

The game not to crash?

### Screenshots and Videos

# Items i added to the toolbox:
![2022-12-29_21 44 37](https://user-images.githubusercontent.com/73425030/210009467-403f6ab4-eb06-493d-88b6-121daa32881b.png)

# what happened
![2022-12-29_21 44 48](https://user-images.githubusercontent.com/73425030/210009517-06305ad9-a569-4232-b0b1-0c4c3747076d.png)

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
need the log

**Comment by TropheusJ** [comment]
There's a contraption in that toolbox. I think it has too much data, so it can't be sent and kicks you. Installing XL Packets might fix it. These dangerous items should be unobtainable in the next update.
