### ISSUE TITLE
Extendo Grip range does not apply to entities

### ISSUE THREAD

**Issue by Timongcraft** [Fabricators-of-Create/Create#722]
### Describe the Bug

The Extendo Grip range only works for blocks, I can't interact with entities in the extended range.

### Reproduction Steps

1. Get a Extendo Grip
2. Punch/Interact with entities in the extended range

### Expected Result

You can interact

### Operating System

Win 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
need a log

**Comment by Timongcraft** [comment]
I'm sorry, but there is nothing in the log it and it does work if I only use create so it has to be another mod, I'll debug it myself and write the other mod author.

**Comment by TropheusJ** [comment]
I'm pretty sure it's pekhui, making this a duplicate of  #656, but I wanted to see the mod list to verify.

**Comment by Timongcraft** [comment]
I don't have that mod and I saw that isse but here:

- Alternate Current
- Appleskin
- Architectury
- BetterAdvancements
- BetterBiomeBlend
- Blockify
- Bobby
- Bookshelf
- Boosted Brightness
- Cardinal Components API
- ClickAdv
- Cloth Config
- Clumps
- Controlling
- Create: Crystal Clear
- Create Crafts & Additions
- Create Deco
- Create
- Create Sifter
- Dark Loading Screen
- Dark Mode Everywhere
- Dynamic FPS
- Elytra Slot
- Enchantment Description
- EntityCullling
- Expanded Drawers
- Fabric API
- Kotlin Fabric
- Ferrite Core
- Forget Me Chunks
- Freecam
- FTB Library
- FTB Ultimine
- Global Packs
- Here be no dragons
- Indium
- Inmis Retextured
- Item Filters
- Krypton
- Ksyxis
- Lazy DFU
- Leaf Decay
- Lithium
- MaLib
- Memory Leak Fix
- MiniHUD
- ModMenu
- Mouswheelie
- NaturesCompass
- NoChatReports
- No Telemetry
- NotEnoughCrashes
- RightClick Harvest
- REI
- ShulkerBox Tooltip
- SimpleChunkloader
- SmoothChunk
- Sodium
- Spark
- Starlight
- Terralith
- Theoneprobe
- Toms Storage
- Trinkets
- Simple Voicechat
- Xaeros Minimap
- Xaeros Worldmap
- YetAnotherConfigLib
- You're in grave danger
- Zoomify
