### ISSUE TITLE
Create train crash

### ISSUE THREAD

**Issue by Meaaaww** [Fabricators-of-Create/Create#723]
### Describe the Bug

My friend had built a 36 block long bullet train with 2 carts, it takes up 98% of CPU power the moment you manually drive it.

We had put a blaze burner in and made it go on schedule to the stronghold from 6000 blocks away. To shorten it, we built most of the track on the nether roof and only left the stations in the overworld. the train portal wasn't big enough for the train so i broke it to build another, not aware of where the train was at the time (still not aware where the train was now.) .

I've broken 2 portals and replaced them with bigger ones already before and it repeatedly crashed on the third one.

The train's fueled max speed was also set to 100 blocks/s, that probably had something to do with it.

The server is also hosted on Shockbyte with 9GB of ram with 6 players on the server if that's important.

	Cannot invoke "java.util.Map.get(Object)" because the return value of 

	"com.simibubi.create.content.logistics.trains.TrackGraph.getConnectionsFrom(com.simibubi.create.content.logistics.trains.TrackNode)" is null

and

	at com.simibubi.create.content.logistics.trains.entity.Navigation.search(Navigation.java:579)

	at com.simibubi.create.content.logistics.trains.entity.Navigation.findPathTo(Navigation.java:446)

	at com.simibubi.create.content.logistics.trains.entity.Navigation.startNavigation(Navigation.java:367)

seems to be the most important parts to me.

Below is the latest crash file.
https://pastebin.com/b6qtBat7

Below is the batch of 200 crash reports since 30/12/22 09:05:35 GMT
[Crash Reports.zip](https://github.com/Fabricators-of-Create/Create/files/10323936/Crash.Reports.zip)

### Reproduction Steps

The steps below are speculation of what happened.
1. build a gigantic game-breaking train
2. make it run 500 blocks through the nether roof
3. set the train max speed to 100 blocks per second
4. put it on schedule to move between the 2 stations after 2 minutes of waiting or if 1 or more passengers enter the train.
5. break one of the nether portals connecting the train

### Expected Result

Your game will crash and give you a _probably_ similar log to mine,
my world has been corrupted by this and it crashes upon launch every time with the same log.
Purging of affected chunks and killing @e does not fix it.
Only way to run the world without crashing is through the removal of Create.

### Screenshots and Videos

Sneak peek image we sent to the rest of the group (the second cart is the same length but without a tapered head.)
![image](https://user-images.githubusercontent.com/90111852/210057688-12e32345-c2c4-488c-b3d3-0f31c488749a.png)

### Crash Report or Log

https://pastebin.com/b6qtBat7

### Operating System

Linux (amd64) version 4.19.0-12-amd64

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

		alternate-current: Alternate Current 1.4.0
		appleskin: AppleSkin 2.4.1+mc1.19
		apugli: Apugli 1.11.2+1.19-fabric
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
		architects_palette: Architect's Palette Fabric 2.1.1
		architectury: Architectury 6.3.56
		attributefix: AttributeFix 17.1.2
		bclib: BCLib 2.1.4
		bettercombat: Better Combat 1.5.2+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.1
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		carrier: Carrier 1.11.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		continents: Continents 1.1
		create: Create 0.5.0g-796+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.5.0
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.1.623+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.623+1.19.2
					mm: Manningham Mills 2.3
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.1.623+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.623+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.623+1.19.2
				porting_lib_models: Porting Lib Models 2.1.623+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.623+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.623+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.1.623+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.623+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.1.623+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.1.623+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.1.623+1.19.2
							porting_lib_constants: Porting Lib Constants 2.1.623+1.19.2
						porting_lib_common: Porting Lib Common 2.1.623+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.44-MC1.19.2
		createchunkloading: Create Chunkloading 1.3.0
		decorative_blocks: Decorative Blocks 3.0.0
		disenchanter: Disenchanter 0.1.7+1.19
		dramaticdoors: Dramatic Doors (Fabric) 1.19.2-1.3.3
		dummmmmmy: MmmMmmMmmMmm 1.19-1.5.3
		easyanvils: Easy Anvils 4.0.6
		easymagic: Easy Magic 4.3.2
		fabric-api: Fabric API 0.69.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.4+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.3+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.36+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.10+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.13+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.21+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
			fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.3+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.2+574a764890
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabricloader: Fabric Loader 0.14.11
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		forgeconfigapiport: Forge Config API Port 4.2.9
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		incendium: Incendium 5.1.4
		java: OpenJDK 64-Bit Server VM 17
		kubejs: KubeJS 1902.6.0-build.132
			ingredient-extension-api: Ingredient Extension API 3.0.5
		lazydfu: LazyDFU 0.1.3
		leavesbegone: Leaves Be Gone 4.0.0
		lithium: Lithium 0.10.4
		medievalorigins: Medieval Origins 1.19.x-4.1.3
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		midnightlib: MidnightLib 1.0.0
		minecarttweaks: Cammie's Minecart Tweaks 1.7
		minecraft: Minecraft 1.19.2
		moonlight: Moonlight 1.19.2-2.1.12
		nullscape: Nullscape 1.2
		origin-cap: Origin Cap 1.2
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				cloth-config: Cloth Config v8 8.0.75
					cloth-basic-math: cloth-basic-math 0.6.1
				playerabilitylib: Pal 1.6.0
		origins-classes: Origins: Classes 1.4.0
		origins-minus: Origins Minus 1.0.3
		pehkui: Pehkui 3.6.0+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		player-animator: Player Animator 0.4.0
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		rhino: Rhino 1902.2.2-build.264
		sit: Sit 1.19-20
		starlight: Starlight 1.1.1+fabric.ae22326
		structory: Structory 1.0.1
		supplementaries: Supplementaries 1.19.2-2.2.23
		t_and_t: Towns and Towers 1.10
			blue_endless_jankson: jankson 1.2.1
		terralith: Terralith 2.3
		touhoublessings: Touhou Origins: Blessings 1.0.1-1.19.2
		touhouorigins: Touhou Origins 0.8.2-1.19.2
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.9
		universalenchants: Universal Enchants 4.2.9
			extensibleenums: Extensible Enums 4.0.0
		wolfarmorcompat: Wolf Armor Compat 1.0.2-1.19.2
		yigd: You're in Grave Danger 1.4.6
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2

### Additional Context

[Whole instance from server.](https://drive.google.com/file/d/1CG3NZ-a7YbQzkI8qWPfrKlGJi4F2waoe/view?usp=share_link)

**Comment by Meaaaww** [comment]
The train is still running on schedule...
![image](https://user-images.githubusercontent.com/90111852/210068149-8fc0976d-5b9b-4ebe-a2c6-c9fd4873790c.png)

**Comment by Meaaaww** [comment]
Random cylindrical holes in the ground has been generated.
![image](https://user-images.githubusercontent.com/90111852/210093971-d601ede0-23d5-44a9-901e-06552f659335.png)
![image](https://user-images.githubusercontent.com/90111852/210093978-3fb439de-de64-4bd1-80e0-cc09708a6142.png)
![image](https://user-images.githubusercontent.com/90111852/210093990-f065bcd9-dfee-4fdb-8f70-a39e1532d420.png)
![image](https://user-images.githubusercontent.com/90111852/210093984-4fde61e0-c4ee-4039-b6f0-ab27a9709231.png)
![image](https://user-images.githubusercontent.com/90111852/210093995-5963d453-bcfd-4298-a162-bb20d9c68581.png)
![image](https://user-images.githubusercontent.com/90111852/210094003-29beec1c-01e1-432e-a032-0d768a598456.png)

**Comment by TropheusJ** [comment]
you removed Create, I don't know what you expected.

**Comment by IThundxr** [comment]
If you can reproduce this issue on 0.5.1.f Patch 1 open a new issue
