### ISSUE TITLE
Comparator not updating container when Chute attached

### ISSUE THREAD

**Issue by Juhamer** [Fabricators-of-Create/Create#724]
If you have a chest with a comparator measuring the output the comparator stays on and doesn't de-power until you update it, ie click subtract mode. This also is directional; if the comparator is facing east, it works as intended.
This doesn't happen with smart chutes, it works correctly.
![image](https://user-images.githubusercontent.com/47513919/210069511-4572632e-5513-4e74-98f4-10b508c01a5e.png)

**Comment by TropheusJ** [comment]
Tested Modern Industrialization, and this is not unique to Create. I think it's a vanilla bug that hoppers hide. When extracted from, only one half of the chest is marked as changed, so only half of it gets comparator updates. The updated half is not guaranteed to be the same half that stuff is extracted from.

**Comment by TropheusJ** [comment]
FAPI fixed this
