### ISSUE TITLE
[1.19.2] Crash on launch

### ISSUE THREAD

**Issue by itsdinkd** [Fabricators-of-Create/Create#728]
### Describe the Bug

Updating my modpack, Another Quality Modpackj 2 to 1.19.2 from 1.18.2 and when launching it crashes due to porting lib.

I tried using the latest commit of porting_lib, and also tried the built in one from Create and it crashes either way. 

### Reproduction Steps

1. Launch Modpack
2. Crash
...

### Expected Result

To launch

### Crash Report or Log

https://gist.github.com/itsdinkd/94a8bb33b6222824f3887f70cfd8bccd

### Operating System

w11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by WHoFart** [comment]
I have the same issue

**Comment by TropheusJ** [comment]
this has been fixed
