### ISSUE TITLE
Looking railroad tracks causes significant lag

### ISSUE THREAD

**Issue by auracreepey** [Fabricators-of-Create/Create#729]
### Describe the Bug

When looking at the railroad tracks, the FPS drops considerably (from ~100 FPS to 10 FPS)

Also the more railroad tracks there are, the lower the FPS will be.
Curved rails cause more lag than straight rails

I made a private server, and I didn't notice any lag on its side, so it's probably a rendering problem.

Changing display settings doesn't help much.

### Reproduction Steps

1. Place railroad tracks
2. Stay near tracks
3. Lag
...

### Expected Result

A large FPS drop

### Screenshots and Videos

Near the tracks:
<img width="958" alt="createTrack" src="https://user-images.githubusercontent.com/77360773/210138993-ceb5a3d3-28f6-4012-9f68-422dc3fb68ee.png">

Usual case:
<img width="959" alt="noTrack" src="https://user-images.githubusercontent.com/77360773/210138999-faa679c9-9746-484c-bd87-1c497924973e.png">

### Operating System

Client: Windows 10   --   Server: Debian 11 (bullseye)

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

**Fabric version :** 0.14.12-1.18.2

alternate-current-mc1.18-1.2.1
sodium-fabric-mc1.18.2-0.4.1+build.15
sodium-extra-0.4.4+mc1.18.2-build.39
lithium-fabric-mc1.18.2-0.7.10
indium-1.0.3+mc1.18.2
krypton-0.1.9
entityculling-fabric-mc1.18-1.5.1
fabric-api-0.53.4+1.18.2
create-fabric-0.5.0g-792+1.18.2

*also tested with this fps booster modpack (doesn't help more) : https://www.curseforge.com/minecraft/modpacks/boosted-fps/files/3806118

**I tried to remove all the mods (except create), and there is always a lag spike when I am near the railroad track

### Additional Context

Hoping you find the bug 🙂

**Comment by ajgeiss0702** [comment]
I'm also having this issue. Was hoping to get some nice video of my create contraptions with shaders but I guess that cant happen until this is fixed.

I can also confirm it happens on 1.19.2 aswell.

**Comment by whatamaniac** [comment]
Same issue... first i thought it's just the train doors causing fps issues but this also happens with me... and it gets worse when a train reaches a station and all doors open or close. (https://github.com/Fabricators-of-Create/Create/issues/847#issue-1630746037)

**Comment by bangetto** [comment]
same here

Edit: 1.20.1

**Comment by TropheusJ** [comment]
curved tracks are rendered as block entities, or with flywheel when enabled.
You were using instancing, which performs worse on AMD. Switching to batching may help.
This will be resolved and batching will be removed with flywheel 1.0.
