### ISSUE TITLE
Create crashes while pasting schematics with trains using the Litematica mods

### ISSUE THREAD

**Issue by cyrxdzj** [Fabricators-of-Create/Create#730]
### Describe the Bug

Create crashes while pasting schematics using the Litematica mods
[crash-2023-01-01_10.31.08-server.txt](https://github.com/Fabricators-of-Create/Create/files/10328206/crash-2023-01-01_10.31.08-server.txt)

### Reproduction Steps

1. Load a Litematica file **containing a Create box (train casing)**
2. Paste it
3. Crash

### Expected Result

Paste it normally

### Crash Report or Log

Please see "Describe the bug"

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

![](https://user-images.githubusercontent.com/63708985/209484609-0262dda7-1dd7-42a4-834c-8a588d5f6c6f.png)
![](https://user-images.githubusercontent.com/63708985/209484611-bc3b0501-3e85-4909-92c2-3f5ce120d783.png)

**Comment by TropheusJ** [comment]
This also affects structures placed by structure blocks

**Comment by James103** [comment]
> 1. Load a Litematica file **containing a Create box (train casing)**

Do you still have the crashing schematic file? If so, can you please ZIP it first and post the resulting ZIP file here?

**Comment by cyrxdzj** [comment]
> > 1. Load a Litematica file **containing a Create box (train casing)**
> 
> Do you still have the crashing schematic file? If so, can you please ZIP it first and post the resulting ZIP file here?

Sorry, I am a residential student. I will send the file this Saturday.

**Comment by cyrxdzj** [comment]
> > 1. Load a Litematica file **containing a Create box (train casing)**
> 
> Do you still have the crashing schematic file? If so, can you please ZIP it first and post the resulting ZIP file here?

Here.
[CR400BF-WhiteSeat.zip](https://github.com/Fabricators-of-Create/Create/files/10713040/CR400BF-WhiteSeat.zip)
It's a litematics file, not schematics file.
