### ISSUE TITLE
Mechanical Arms losing their targets

### ISSUE THREAD

**Issue by Midnight-GHub** [Fabricators-of-Create/Create#731]
### Describe the Bug

Bug - The mechanical arm does not remember its targets. When the mechanical arm is assigned to an input and output depo, it shows that the arm was not assigned any targets.

### Reproduction Steps

1. Take the mechanical arm, right click on a depo and double right click on the other depo.
2. Place the arm near to the depos.
3. Give rotational force to the arm.

### Expected Result

The mechanical arm was supposed to transfer items from input depo to output depo.

### Screenshots and Videos

Video - https://user-images.githubusercontent.com/111125019/210166127-f13a8f10-0afa-4903-bf93-41f0dc9d05b2.mp4

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Mods used on the server - 
AdditionalAdditions-5.1.0.jar
3.99 MB
advancednetherite-fabric-1.6.5-1.19.2.jar
217.92 kB
artifacts-7.1.1+fabric.jar
585.82 kB
balm-fabric-4.5.2+0.jar
625.51 kB
cardinal-components-api-5.0.2.jar
326.92 kB
cc-restitched-1.101.2.jar
2.84 MB
charmofundying-fabric-6.0.0+1.19.2.jar
44.68 kB
cloth-config-8.2.88-fabric.jar
1.09 MB
collective-fabric-1.19.2-5.22.jar
539.47 kB
create-fabric-0.5.0g-796+1.19.2.jar
16.20 MB
creeperoverhaul-2.0.5-fabric.jar
638.09 kB
dehydration-1.3.2.jar
316.14 kB
elytraslot-fabric-6.0.0+1.19.2.jar
41.30 kB
EnchantingInfuser-v4.2.2-1.19.2-Fabric.jar
152.08 kB
fabric-api-0.67.0+1.19.2.jar
1.69 MB
fabric-end-remastered-5.2.0.jar
127.67 kB
fabric-lava_walker-1.19-0.3.1.jar
283.13 kB
farmers-delight-fabric-1.19.X-1.3.9.jar
2.58 MB
Fireplace-Lib-Fabric-7.0.3+1.19.2.jar
1.10 MB
ForgeConfigAPIPort-v4.2.9-1.19.2-Fabric.jar
422.75 kB
geckolib-fabric-1.19-3.1.38.jar
3.45 MB
hardcorerevival-fabric-1.19.2-9.0.1.jar
208.76 kB
Jade-1.19.1-fabric-8.6.3.jar
419.17 kB
midnightlib-0.5.2.jar
60.22 kB
NaturesCompass-1.19.2-2.1.0-fabric.jar
219.83 kB
Nullscape_v1.2a.jar
558.12 kB
polaroidcamera-1.4.0.jar
104.41 kB
PuzzlesLib-v4.3.12-1.19.2-Fabric.jar
397.58 kB
repurposed_structures_fabric-6.1.3+1.19.2.jar
7.17 MB
SimplyHouses-1.1.3-1.19-fabric.jar
709.31 kB
travelers-backpack-1.19.2-8.2.9.jar
563.36 kB
treeharvester-fabric_1.19.2-5.9.jar
57.79 kB
trinkets-3.4.1.jar
230.21 kB
Unforgiving-Void-Fabric-3.1.5+1.19.jar
109.39 kB
Xaeros_Minimap_22.17.0_Fabric_1.19.1.jar
1.26 MB
XaerosWorldMap_1.28.7_Fabric_1.19.1.jar
743.56 kB
YungsApi-1.19.2-Fabric-3.8.2.jar
1.08 MB
YungsBetterDesertTemples-1.19.2-Fabric-2.2.1.jar
0.97 MB
YungsBetterDungeons-1.19.2-Fabric-3.2.1.jar
1.11 MB
YungsBetterMineshafts-1.19.2-Fabric-3.2.0.jar
272.15 kB
YungsBetterOceanMonuments-1.19.2-Fabric-2.1.0.jar
1.35 MB
YungsBetterStrongholds-1.19.2-Fabric-3.2.0.jar
416.34 kB
YungsBetterWitchHuts-1.19.2-Fabric-2.1.0.jar
242.49 kB
YungsBridges-1.19.2-Fabric-3.1.0.jar
377.43 kB 

### Additional Context

This version stated that the bug was fixed (- fix Mechanical Arms losing their targets (#608)). But I face the same issue.

**Comment by TropheusJ** [comment]
fixed in dev

**Comment by Midnight-GHub** [comment]
Well why is it not working for me?

**Comment by TropheusJ** [comment]
because it is fixed in dev, not released versions.

**Comment by TropheusJ** [comment]
It was supposed to be fixed in the last version, but it wasn't actually.

**Comment by Midnight-GHub** [comment]
So what can I do now?

**Comment by TropheusJ** [comment]
for a workaround if you hold a stack of 2 or more arms it works.

**Comment by Midnight-GHub** [comment]
STACK! of 2. It's too many. Is there an alternative?

**Comment by Midnight-GHub** [comment]
If you plan to bring a new version then how long will it take?

**Comment by TropheusJ** [comment]
This is all you need.
![image](https://user-images.githubusercontent.com/60247969/210167054-6ed1b4d9-af43-4bdb-b54d-19fabf7af05f.png)
Alternatively, wait for an update in a week.

**Comment by Midnight-GHub** [comment]
oh I thought you meant 64 + 64. Thanks for the clarification.

**Comment by Midnight-GHub** [comment]
Any idea on why jei doesn't show create's extended recipes (mechanical crafting) and how to obtain stuff through create like we get gold nugget when we crush it.

**Comment by TropheusJ** [comment]
#657

**Comment by Midnight-GHub** [comment]
It's been 3 weeks, when will it release?

**Comment by Midnight-GHub** [comment]
@TropheusJ  When?

**Comment by CzechHek** [comment]
You can use dev builds for the time being: https://github.com/Fabricators-of-Create/Create/suites/10573855171/artifacts/526422824
