### ISSUE TITLE
Can't use a lead to pick up mobs sitting on a seat from Create mod.

### ISSUE THREAD

**Issue by James103** [Fabricators-of-Create/Create#732]
### Describe the Bug

When attempting to use a lead to pick up a mob that is currently sitting on a seat from the Create mod, the mob is forced out of the seat but then sits back in the same seat automatically and the lead breaks.

Workaround: Use an Extendo Grip and stand at least 5-6 blocks away from the mob before leashing in order to try to force it out of its seat.

### Reproduction Steps

1. Create a new instance with Minecraft 1.19.2 and Fabric Loader 0.14.12.
2. Install Fabric API 0.70.0 and Create mod 0.5.0g-796+1.19.2 for Fabric.
3. Create a new world with cheats enabled.
4. Give yourself an Extendo Grip, a Seat of any color, a leashable mob or spawn egg thereof, and a lead.
5. Place down the seat somewhere.
6. Spawn or find a leashable mob (chicken, pig, cow, sheep, iron golem etc).
7. Leash the mob, then click the seat to make the mob sit there.
8. Try to leash the mob again.
9. Watch as the mob remains stuck in the seat.

### Expected Result

A mob should not automatically sit in a seat while being leashed, even if the mob is standing directly on the seat or being moved across multiple seats. This applies for both seats in their block form and as part of a contraption such as a passenger train.

### Operating System

Windows 10, 64-bit

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

No Chat Reports was installed in the instance (for privacy reasons only); this should not affect reproducibility of the issue.

**Comment by IThundxr** [comment]
Upstream issue: https://github.com/Creators-of-Create/Create/issues/4549
