### ISSUE TITLE
Game crashed on multiplayer game

### ISSUE THREAD

**Issue by Rorke76753** [Fabricators-of-Create/Create#733]
### Describe the Bug

The game crash while connecting to multiplayer, but it goes all fine in single player.
And after crashing for few times the game work.

### Reproduction Steps

connecting to multiplayer server through ip and the game process crashed

### Expected Result

won't crash

### Crash Report or Log

 https://gist.github.com/Rorke76753/163a2390e6cc363d19fdfb0d874872cc

### Operating System

windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
What launcher are you using?

**Comment by IThundxr** [comment]
If you can reproduce this on the latest patch open a new issue
