### ISSUE TITLE
Train seats and Pehkui cause a server crash

### ISSUE THREAD

**Issue by ghost** [Fabricators-of-Create/Create#736]
### Describe the Bug

When using Create Fabric v.0.5.0g and Pehkui 3.6.1, an interaction with a seat attached to a train causes a server to crash. This crash only seems to apply when height is modified, and not width. This bug does not apply if height is not scaled, as exiting a train works as expected without height scaling. 

### Reproduction Steps

1. Build a train using a Create mod seat.
2. Scale your height using Pehkui.
3. Enter the train seat, and drive around
4. Exit the seat
5. Server Crash
...

### Expected Result

The server should not crash, and I should be able to exit the seat successfully. 

### Crash Report or Log

https://gist.github.com/laneium/ba00119c7e4dac3bf0117049aedfd021

### Operating System

Windows 10 on client, unknown Linux flavor on server

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Adorn 3.8.1
Another Furniture Fabric 2.1.2
bclib 2.1.5
better end 2.1.2
better nether 7.1.2
Bookshelf 16.2.16
Campanion 4.1.2
Capes 1.4.5
capybara 2.0.1
cinderscapes 3.0.3
cloth-config 8.2.84
comforts 6.0.3
crops love rain 1.3.0
Croptopia Fabric 2.1.2
Dark Paintings 13.0.1
Essential
Extra Origins
fabric api 0.69.0
fabric language kotlin 1.8.6+kotlin1.7.21
farmer delight fabric 1.3.9
ferritecore 5.0.3
graves 2.1.3
indium 1.0.9
iris 1.4.5
jei 11.5.0.297
lambdynamiclights 2.2.0
midnightlib 0.6.1
moborigins 1.9.0
modmenu 4.1.2
origins 1.7.1
origins classes 1.4.0
origins umbrellas 1.5.4
Pekhui 3.6.1+1.14.4

### Additional Context

A workaround is possible. Remove Pehkui version 3.6.1, and install 3.4.2 instead.

**Comment by Chikage0o0** [comment]
Pehkui has been updated to 3.6.3, has the problem been fixed on the latest version?

**Comment by Redd56** [comment]
can confirm still can confirm still crashes

**Comment by TropheusJ** [comment]
seems pekhui fixed it
