### ISSUE TITLE
Visual bug with shadows from windmill

### ISSUE THREAD

**Issue by jonask028** [Fabricators-of-Create/Create#740]
### Describe the Bug

When I looking at the shadow with the windmill in frame or barely out of frame, the shadow is very smooth and matches the speed of the windmill rotation. If I can only see the shadow and not the windmill it speeds up and flashes rapidly. 

### Reproduction Steps

1. Use 1.19.2 and install create with sodium, lithium, starlight, and iris
2. Install complimentary shaders reimagined and set entity shadows to off (same thing happens with on but the pictures i took have it set to off)
3. Build a windmill 10 blocks high with 4 sails each with 24 sail blocks in a 3x8
4. observe the shadow with the windmill in frame and compare it to the shadow without the windmill in frame. 
...

### Expected Result

The shadow to either render correctly or to disappear altogether. Ideally there's an option to toggle if contraptions case shadows but i'm not sure how that would work on your end.  

### Screenshots and Videos

https://user-images.githubusercontent.com/97471474/210647451-782c5b78-5ecb-47d0-8e8e-680f70def428.mp4

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

3dskinlayers-fabric-1.5.2-mc1.19.1.jar
AdditionalAdditions-5.1.0.jar
alternate-current-mc1.19-1.4.0.jar
animatica-0.5+1.19.jar
antighost-1.19.1-fabric0.58.5-1.1.5.jar
appleskin-fabric-mc1.19-2.4.1.jar
architectury-6.4.62-fabric.jar
AttributeFix-Fabric-1.19.2-17.1.3.jar
AxesAreWeapons-1.6.0-fabric-1.17.1.jar
badpackets-fabric-0.2.1.jar
BarteringStation-v4.0.3-1.19.2-Fabric.jar
BetterAdvancements-Fabric-1.19.2-0.3.0.148.jar
bettercrafting-1.19.2-14.jar
BetterF3-4.0.0-Fabric-1.19.2.jar
betterfpsdist-fabric-1.19.1-2.0.jar
Bookshelf-Fabric-1.19.2-16.2.16.jar
borderless-mining-1.1.5+1.19.jar
c2me-fabric-mc1.19.2-0.2.0+alpha.9.0.jar
Campanion-fabric-1.19.2-4.1.2+fabric.jar
Capes-1.4.5+1.19.jar
cem-0.7.1.jar
Chunky-1.3.38.jar
cinderscapes-3.0.3.jar
CITResewn-1.1.2+1.19.2.jar
cleancut-1.19.2-5.1-fabric.jar
cloth-config-8.2.88-fabric.jar
Clumps-fabric-1.19.2-9.0.0+14.jar
collective-fabric-1.19.2-5.22.jar
Companion-1.19.2-fabric-3.1.2.jar
continuity-2.0.1+1.19.jar
Controlling-fabric-1.19.2-10.0+7.jar
create-fabric-0.5.0g-796+1.19.2.jar
cullclouds-0.1.0.jar
CullLessLeaves-1.0.6.jar
dynamic-fps-2.2.0.jar
EasyAnvils-v4.0.6-1.19.2-Fabric.jar
EasyMagic-v4.3.2-1.19.2-Fabric.jar
EnchantmentDescriptions-Fabric-1.19.2-13.0.14.jar
enhancedblockentities-0.7.2+1.19.2.jar
entityculling-fabric-1.5.2-mc1.19.jar
Entity_Collision_FPS_Fix-fabric-1.19-2.0.0.0.jar
entity_texture_features_fabric_1.19.2-4.3.0.jar
FabriZoom-1.2.1.jar
Fastload+1.19.2-2.6.10.jar
ferritecore-5.0.3-fabric.jar
FixMySpawnR-fabric-1.19.2-1.1.3.jar
ForgeConfigAPIPort-v4.2.9-1.19.2-Fabric.jar
forgetmechunk-1.0.4-1.18.X-1.19.X.jar
indium-1.0.9+mc1.19.2.jar
InventorySorter-1.8.10-1.19.jar
iris-mc1.19.2-1.5.0.jar
item-model-fix-1.0.3+1.19.jar
krypton-0.2.1.jar
lambdynamiclights-2.2.0+1.19.2.jar
lazy-language-loader-0.3.1.jar
lazydfu-0.1.3.jar
LeavesBeGone-v4.0.0-1.19.2-Fabric.jar
lithium-fabric-mc1.19.2-0.10.4.jar
memoryleakfix-1.19.1-0.7.0.jar
MixinConflictHelper-1.2.0.jar
mixintrace-1.1.1+1.17.jar
modmenu-4.1.2.jar
MouseTweaks-fabric-mc1.19-2.22.jar
NoChatReports-FABRIC-1.19.2-v1.13.12.jar
OverpoweredMending-1.19.2-2.8.2.jar
PresenceFootsteps-1.6.4.jar
PuzzlesLib-v4.3.12-1.19.2-Fabric.jar
qfapi-4.0.0-beta.25_qsl-3.0.0-beta.24_fapi-0.70.0_mc-1.19.2.jar
quilt-kotlin-libraries-1.0.1+kt.1.7.22+flk.1.8.6.jar
raised-fabric-1.19.2-1.1.4.jar
reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
resounding-1.0.0-bc.19.x.jar
RoughlyEnoughItems-9.1.580.jar
RoughlyEnoughProfessions-fabric-1.19.2-1.1.3.jar
smoothboot-fabric-1.19-1.7.1.jar
sodium-extra-0.4.16+mc1.19.2-build.90.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
spark-1.10.17-fabric.jar
stack-to-nearby-chests-1.19.2-0.2.3.jar
starlight-1.1.1+fabric.ae22326.jar
TaxFreeLevels-1.3.3-fabric-1.19.jar
terrestria-5.0.8.jar
TradingPost-v4.2.0-1.19.2-Fabric.jar
travelers-backpack-1.19.2-8.2.9.jar
traverse-6.0.6.jar
treeharvester-fabric_1.19.2-5.9.jar
trinkets-3.4.1.jar
VisualWorkbench-v4.2.0-1.19.2-Fabric.jar
waveycapes-fabric-1.2.2-mc1.19.2.jar
wthit-quilt-5.13.4.jar
YetAnotherConfigLib-1.7.1.jar

### Additional Context

running on a 3070 ti with an 15 12600k

**Comment by TropheusJ** [comment]
pretty sure this is caused by entity culling
