### ISSUE TITLE
Not compatible with JEI

### ISSUE THREAD

**Issue by meishiffx** [Fabricators-of-Create/Create#741]
### Describe the Suggestion

REI frequently causes crashes, but JEI does not display recipes correctly.

**Comment by Skidamek** [comment]
Try using emi

**Comment by LyoGyo** [comment]
I tried changing JEI versions and using other mods like EMI and it's been wildly inconsistent with showing stuff like assembly line crafting recipes

**Comment by TropheusJ** [comment]
REI, JEI, and EMI are all supported.
If REI is crashing, report to REI.
Errors with all 3 should be mostly fixed in the next update.
