### ISSUE TITLE
"/create ponder " crashes multiplayer server when autocomplete attempts to return options

### ISSUE THREAD

**Issue by rydens** [Fabricators-of-Create/Create#743]
### Describe the Bug

Just like #613, didn't know if I should reply to that or open another issue. Server crashes when trying to get the autocomplete options for the command `/create ponder`. Doesn't appear to occur in single player.

### Reproduction Steps

1. On Multiplayer server, type `/create ponder` and hit space to get autocomplete's options
...

### Expected Result

Command autocomplete returns a list of items to ponder, as in Single Player

### Crash Report or Log

https://pastebin.com/XRLgbwaB

https://pastebin.com/wevGJuHg

### Operating System

Server on Linux, clients on Windows and macOS

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

See crash log

**Comment by blufish1234** [comment]
Same issue here

**Comment by jadonwright** [comment]
Happened on my server too

**Comment by HappiePlant** [comment]
Same issue

**Comment by TropheusJ** [comment]
fixed, but it doesn't actually suggest any completions. This matches forge.
