### ISSUE TITLE
Chute doesn't pick items from a water stream

### ISSUE THREAD

**Issue by liad-inon** [Fabricators-of-Create/Create#745]
### Describe the Bug

Chutes does not pick  items from a water stream.

### Reproduction Steps

1. Build a item Water stream with chutes at the bottom
2. Throw an item into the water stream

### Expected Result

None of the chutes will pick the item if the item wasn't thrown directly at them.

### Screenshots and Videos

full demonstration: [https://www.reddit.com/r/CreateMod/comments/105nkes/chute_doesnt_pick_items_from_a_water_stream_bug/](https://www.reddit.com/r/CreateMod/comments/105nkes/chute_doesnt_pick_items_from_a_water_stream_bug/)

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

All of my mods except carpet and gravestones are client side

**Comment by TropheusJ** [comment]
The comments on your post are correct, the items floated so the chute can't grab them.
