### ISSUE TITLE
Steam-Engine

### ISSUE THREAD

**Issue by ChaosZiege** [Fabricators-of-Create/Create#746]
### Describe the Bug

whenever I interact with the steam engine, my server crashes or kicks me out. in the crash.log of my server is the following

Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property class_2754{name=blaze, clazz=class com.simibubi.create.content.contraptions.processing.burner.BlazeBurnerBlock$HeatLevel, values=[NONE, SMOULDERING, FADING, KINDLED, SEETHING]} as it does not exist in Block{minecraft:air}
at net.minecraft.class_2688.method_11654(class_2688.java:98)
at com.mrh0.createaddition.CreateAddition.lambda$onInitialize$0(CreateAddition.java:42)

### Reproduction Steps

1.
2.
3.
...
.

### Expected Result

.

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

i´m playing the SKY FABRICation 3 mod from Curseforge

**Comment by TropheusJ** [comment]
issue with CC&A, needs to be updated
