### ISSUE TITLE
Flywheel instances do not render with Valkyrien Skies

### ISSUE THREAD

**Issue by aD-1337** [Fabricators-of-Create/Create#748]
### Describe the Bug

Most of the content in the create fabric (such as the creation motor, transmission rod, etc.) cannot work in the physical structure of the valkyrienskies ,which work in create forge

### Reproduction Steps

1.install the fabric edition of valkyrienskies
2.install the fabric edition of eureka ship(the addon of valkyrienskies)
3.enter game.create a physics structure of valkyrienskies
4.place some create fabric stuff,see whats going on
...

### Expected Result

Many contents in the create fabric (such as creating motors, transmission rods, etc.) can work normally in the physical structure of the valkyrienskies

### Screenshots and Videos

![微信截图_20230109000332](https://user-images.githubusercontent.com/85235186/211206753-986c2346-e3bf-4ac9-a7f0-8d5ce605c08e.png)

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

valkyrienskies-118-2.1.0-beta7.jar
eureka-1.1.0-beta2+59792d77ff.jar

**Comment by TropheusJ** [comment]
VS needs to implement their Flywheel compat on fabric. cannot be fixed by us.
