### ISSUE TITLE
Server crash when placing a mechanical bearing on a rotating shaft.

### ISSUE THREAD

**Issue by frikinjay** [Fabricators-of-Create/Create#75]
### Describe the Bug

Server crashes when placing a mechanical bearing facing upwards on a rotating shaft connected to a water wheel.
The crash report reports a watchdog crash and the below attached report is from the logs.

### Reproduction Steps

1. Place a water wheel horizontally and have it rotate with water.
2. Place a shaft on the wheel.
3. Place Mechanical Bearing on the shaft while its rotating.
...

### Expected Result

Mechanical bearing to be placed and for the server to not crash.

### Crash Report or Log

https://pastebin.com/80immwzk

### Operating System

Windows 10

### Mod Version

0.4.0b

### Minecraft Version

1.18.1

### Other Mods

Same list as #74 excluding iris. I've removed iris meanwhile.

**Comment by TropheusJ** [comment]
this was fixed upstream.
