### ISSUE TITLE
Deployer timing

### ISSUE THREAD

**Issue by Foxkid171** [Fabricators-of-Create/Create#750]
### Describe the Bug

The only thing I could think of would be a timing issue. Where a deployer with a lava bucket not able to use it on a blaze cage due to it being retracted when the initial power is lost. 

### Reproduction Steps

1.Deployer placed with lava bucket inserted and held
2.Blaze cage cold without fuel
3.Jump start with a log engines turn and deployer starts to smack the cage with the lava bucket
4.Log is used up and deployer fails to use bucket of lava on the cage as the boilers shut down

### Expected Result

Bucket of lava being fed into a deployer used to power the cage in a self reliant system

### Screenshots and Videos

![2023-01-09_14 58 35](https://user-images.githubusercontent.com/94150965/211396829-b27278ec-c65a-4834-a830-5d8c65333c3d.png)

### Operating System

Windows 10 64-bit

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

AOF6 Modpack and NA Server

### Additional Context

This world and setup can be viewed on AOF6 NA Server. My username on discord and in game is _Fauxx

**Comment by TropheusJ** [comment]
When heat stops, the power stops. there is no bug here.
However, in the next update, fuel will be used before blaze burners completely run out, avoiding this issue.
