### ISSUE TITLE
Some Steam Whistle Notes Are Out of Tune

### ISSUE THREAD

**Issue by FC-Creations** [Fabricators-of-Create/Create#751]
### Describe the Bug

All high octave notes from C up are out of key

### Reproduction Steps

1. Put down note block, set it to high C or above
2. Set up steam whistle and set it to high C or above
3. Run redstone to them both at the same time
4. Cringe

### Expected Result

Steam whistle notes to be in key with note blocks

### Screenshots and Videos

https://youtu.be/jn95_zjGEV0

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

Architectury
BetterF3
Better Third Person
bobby
chipped
Cit Resewn
Cloth config
Decorative Blocks
Freecam
Indium
Iris
Lazydfu
Light Overlay
MouseTweaks
Oh the biomes you'll go
REI
Sodium
Starlight
Theoneprobe
Zoomify

**Comment by FC-Creations** [comment]
I've looked into the code, and found that it seems as though it's currently attempting to compensate for a sample that is a bit off pitch.

If you guys will permit it, I can see if I can fix this myself, otherwise I'll just leave you with the 2 possible fixes I can think of.

Compensating the pitch with code would require more calculation than simply adding .75. As notes are based on ratios, it would eventually go out of pitch.

The other direction to take is to adjust the pitch of the sample itself, so that you don't need to compensate with code. 

Personally I would pursue the latter first, because I have the software that could tune the pitch.

Just let me know, I'd be happy to help.

**Comment by CzechHek** [comment]
Great post, video showcase and all, but this should be reported to Create Forge repository.

**Comment by FC-Creations** [comment]
They asked for the "forge version" when I went to make a post there, and I realized I was using the Fabric version. I'll just fudge that answer and make a post there. Thanks.  I'll report back here if there's any conclusions over there.

Link to my post on the Forge GitHub: https://github.com/Creators-of-Create/Create/issues/4303
