### ISSUE TITLE
Update to 1.19.3

### ISSUE THREAD

**Issue by OldisekT** [Fabricators-of-Create/Create#752]
### Describe the Suggestion

# Just update the mod to *1.19.3*

**Comment by DaveyL2013** [comment]
As far as I can tell the main issue preventing this from working is TropheusJ/dripstone-fluid-lib#3

**Comment by TropheusJ** [comment]
there's a lot more to updating than milk. We are keeping parity with forge. The update will come when it's ready.

**Comment by DaveyL2013** [comment]
Ah ok
