### ISSUE TITLE
1.19.2 Fabric encased fan not harnessing power from heat

### ISSUE THREAD

**Issue by aireishi** [Fabricators-of-Create/Create#753]
### Describe the Bug

Whenever i try to harness power from heat using encased fans it's not working (yes i tried using the lever to activate the fan)

### Reproduction Steps

Get an encased fan, Put encased fan above a magma block or any heat source.

### Expected Result

It will not give me any SU unit

### Screenshots and Videos

![2023-01-13_00 32 40](https://user-images.githubusercontent.com/122553227/212125427-4ca44a82-bd12-423f-910f-71a206ae5b61.png)

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Twilight Forest
fabulously optimized mod pack
litematica
tweakaroo
Naturalist
farmer's delight
scout
create crafts and additions
expanded delight
decorative blocks
xerco paint
another furniture

### Additional Context

My friend and i were trying to get a transportable? moveable? Energy source and we found out through YT that you can get it by encased fans but they won't work, i haven't tried other versions other than 1.19.2 Fabric.

**Comment by TropheusJ** [comment]
This feature was intentionally removed in 0.5

**Comment by aireishi** [comment]
> This feature was intentionally removed in 0.5

wait so there's no way to get any su unit from encased fans? or is there any other way?

**Comment by TropheusJ** [comment]
No, fans are no longer generators.
