### ISSUE TITLE
Weighted Ejectors won't Launch Minecarts to Seleected Target Area

### ISSUE THREAD

**Issue by Frankiscophil** [Fabricators-of-Create/Create#760]
### Describe the Bug

When tinkering with Weighted Ejectors, I found it could not launch Minecarts to the specified target block even at the max distance the Weighted Ejector can go. Minecarts get launched and land only seven blocks away from the Weighted Ejector if said machine is targetting the maximum distance.

### Reproduction Steps

1. Select the max distance of the Weighted Ejector and set it up.
2. Set up a rail system leading to the Weighted Ejector.
3. Let Minecarts run on the tracks towards the Weighted Ejector.

### Expected Result

I expected for the Minecart to be launched to the specified target block.

### Screenshots and Videos

[https://www.youtube.com/watch?v=V6D-eyF7fWY](url)

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

All of Fabric 6 - 1.3.0

**Comment by IThundxr** [comment]
Upstream report: https://github.com/Creators-of-Create/Create/issues/6133
