### ISSUE TITLE
Noticed some issues with a few recipes involving some other mods.

### ISSUE THREAD

**Issue by BowBoy1** [Fabricators-of-Create/Create#763]
### Describe the Bug

Crushed Silver doesn't have any outputs when it should use the common silver ingot and silver nugget tags as its outputs. Also a few of the AE2 recipes are broken currently (i specifically checked the milling/crushing recipes), as they use outdated AE2 input items such as Certus Quartz Ore, which no longer exists. 

### Reproduction Steps

1. View recipes relating to mods like Bewitchment (for the Crushed Silver issue) or AE2 using a mod like REI or EMI

### Expected Result

The recipes mentioned either do not show up when they should exist (for example, crushed silver being smelted to silver ingots or washed to silver nuggets) or they are incorrect (for example, some AE2 recipes use outdated inputs and therefore are invalid).

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by IThundxr** [comment]
Fixed in https://github.com/Fabricators-of-Create/Create/commit/2b7d1d367d8b98eea71c7efe4914266bb6eecda1 and https://github.com/Fabricators-of-Create/Create/commit/0f58b606f1301fc742367c8ed79d3fc080ee6610
