### ISSUE TITLE
Wrong Gear Rendering 

### ISSUE THREAD

**Issue by AubthurYoung** [Fabricators-of-Create/Create#764]
### Describe the Bug

The gear seems like rendering twice.
One of those moves with the drive rod, and another stay.

![M4G1Y}0 BS{0}85N`$OC%91](https://user-images.githubusercontent.com/117471583/213879558-51b1c43b-d0ab-4e6f-9dbc-93e2fbbb758a.png)

### Reproduction Steps

The bug happens every time when I log in to the game.

### Expected Result

The gear seems like rendering twice.

### Operating System

Windows 10

### Mod Version

0.5.0f

### Minecraft Version

1.19.2

### Other Mods

fabric-api-0.60.0+1.19.2
tweakeroo-fabric-1.19.2-0.14.3
TweakMyClient-3.2.268+fc2ad10-stable
minihud-fabric-1.19.2-0.23.3
malilib-fabric-1.19.2-0.13.0
itemscroller-fabric-1.19.2-0.17.1
litematica-fabric-1.19.2-0.12.4
plusls-carpet-addition-1.19.2-0.2.5-beta+827168a
carpet-tis-addition-mc1.19.2-v1.39.0+build.1219
fabric-carpet-1.19.1-1.4.83+v220727
carpet-extra-1.19.1-1.4.83
iris-mc1.19.1-1.2.6
gugle-carpet-addition-2.3.1-1.19
modmenu
sodium-extra-0.4.6+mc1.19-build.47
reeses_sodium_options-1.4.6+mc1.19.2-build.55
sodium-fabric-mc1.19-0.4.2 (replaymod compatible) (1)
appleskin-fabric-mc1.19-2.4.1
voxelmap-1.19.2-1.11.9
IKnowWhatImDoing-4.1.0-fabric
MasaGadget-3.0.0-beta+1bf6939
oh-my-minecraft-client-0.5-beta+8215759
easiervillagertrading-1.19.1-fabric0.58.5-1.5.4
gugle-carpet-addition-2.3.0-1.19
NoChatReports-FABRIC-1.19.2-v1.10.1
magiclib-0.5.39
wraith-colormeoutlines-1.1.1

BBOutlineReloaded-2.5-1.19.2-fabric
beenfo-1.19.1-forge42.0.1-1.2
bettercombat-fabric-1.5.4+1.19
cardinal-components-api-5.0.2
carpetskyadditions-1.19.2-4.1.2
cloth-config-8.2.88-fabric
CraftTweaker-fabric-1.19.2-10.0.25

create-fabric-1.19.2-0.5.0f-776
fabric-api-0.69.0+1.19.2

FauxCustomEntityData-fabric-1.19.2-2.0.2
gugle-carpet-addition-2.4.0-1.19
IngredientExtensionAPI-fabric-1.19.2-3.0.6
jei-1.19.2-fabric-11.5.2.1006
mcda-2.2.0
mcdw-5.0.4-1.19
player-animation-lib-fabric-0.4.0
replaymod-1.19.1-2.6.8
travelers-backpack-1.19.2-8.2.10
tweakermore-mc1.19.2-v3.7.1

**Comment by TropheusJ** [comment]
Install indium

**Comment by AubthurYoung** [comment]
That‘s worked！！！！！
Thank you very much！！
