### ISSUE TITLE
Signs and iron bars are crashing Minecraft with Create

### ISSUE THREAD

**Issue by Rynn-Lee** [Fabricators-of-Create/Create#767]
### Describe the Bug

Every time a sign or an iron bar get in my sight, the world crashes. I replicated the exact case that crashed my server in singleplayer. After this i can't join my world again, it instantly crashes.
The mod "Not enough crashes" says that the crash caused by Create and Iris, but it happens even without Iris and Sodium
Crash log is uploaded on crashy, it shows all the mods etc.

### Reproduction Steps

Every steps on video

### Expected Result

Not to crash

### Screenshots and Videos

Everything is on this video: https://youtu.be/VMjGEmyNmw8

### Crash Report or Log

https://crashy.net/YGE9MnRQL77uws6tPPtH

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
try without not enough crashes and send the new log if it still happens

**Comment by Rynn-Lee** [comment]
NEC just doesn't allow minecraft to close. I tried already

Crash report without NEC: https://pastebin.com/empD2A70

**Comment by TropheusJ** [comment]
yep, entirely new error.
Unfortunately, it's literally impossible to trace, and you'll need to find the problematic mod yourself. 
You can binary split. Start by copying the world to not ruin it.
Split the mods in half. Still happens? Repeat. Fixed? Try the other half. Repeat until you find the mod that causes it.

**Comment by Rynn-Lee** [comment]
Problem solved
"More Culling" mod doesn't respect wooden signs and iron bars, somehow NEC blames Create and Iris
(I had to blow up Encased Fan without seeing it because of More culling, thought that might help) :v
Thanks for immediate response 👍🏻
