### ISSUE TITLE
Update to 1.19.3

### ISSUE THREAD

**Issue by DeltaV-1** [Fabricators-of-Create/Create#768]
### Describe the Suggestion

I don't know if this is already in the works or just looked over, but on Modrinth it is currently on 1.19.2.
So, yeah, if you guys haven't read the title already please update to 1.19.3.

**Comment by TropheusJ** [comment]
The update will come when it’s ready. We are waiting for forge create first.

**Comment by DaveyL2013** [comment]
> The update will come when it’s ready. We are waiting for forge create first.

[https://github.com/Creators-of-Create/Create/tree/mc1.19.3/dev](https://github.com/Creators-of-Create/Create/tree/mc1.19.3/dev)?
