### ISSUE TITLE
Connection lost (i have create fabric) 

### ISSUE THREAD

**Issue by JakubDotGH** [Fabricators-of-Create/Create#771]
### Describe the Bug

Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Unknow recipe serializer create:milling

 pls help

### Reproduction Steps

1.
2.
3.
...

### Expected Result

I try to join to server

### Crash Report or Log

Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Unknow recipe serializer create:milling

### Operating System

Redmi, pojavlauncher

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Fabric api, jei

### Additional Context

I don't know

**Comment by TropheusJ** [comment]
this means you do not have Create installed

**Comment by JakubDotGH** [comment]
Do I need to install create and create fabric or just create fabric?

**Comment by TropheusJ** [comment]
just create fabric. If you think you have it, it might be because you don't have pojav set up right. I can't help with that though.
