### ISSUE TITLE
I can't build create.

### ISSUE THREAD

**Issue by jrapf32** [Fabricators-of-Create/Create#772]
### Describe the Bug

I can't build create because it can't get dependencies. 

### Reproduction Steps

1.   git clone https://github.com/Fabricators-of-Create/Create.git -b mc1.19/fabric/dev  
2.  ./gradlew assemble   

### Expected Result

Could not GET 'https://modmaven.dev/com/jamieswhiteshirt/reach-entity-attributes/2.3.0/reach-entity-attributes-2.3.0.pom'. Received status code 500 from server: Internal Server Error.

### Crash Report or Log

> Could not resolve all dependencies for configuration ':modImplementation'.    > Could not resolve com.jamieswhiteshirt:reach-entity-attributes:2.3.0.      Required by:          project :       > Could not resolve com.jamieswhiteshirt:reach-entity-attributes:2.3.0.          > Could not get resource 'https://modmaven.dev/com/jamieswhiteshirt/reach-entity-attributes/2.3.0/reach-entity-attributes-2.3.0.pom'.             > Could not GET 'https://modmaven.dev/com/jamieswhiteshirt/reach-entity-attributes/2.3.0/reach-entity-attributes-2.3.0.pom'. Received status code 500 from server: Internal Server Error

### Operating System

Macos

### Mod Version

0.5.0g

### Minecraft Version

1.19.3

**Comment by TropheusJ** [comment]
modmaven is down, nothing you can do but wait and try again later
