### ISSUE TITLE
Log Stripping Recipe Breaks JEI Integration at Random

### ISSUE THREAD

**Issue by JackEhttack** [Fabricators-of-Create/Create#773]
### Describe the Bug

At random, the JEI integration for Create recipes would disappear and the recipes would no longer be displayed, persisting until restarting the game.

I believe I found the error message which causes the integration to error out, and it has to do with JEI registering the LogStrippingFakeRecipe on this [line](https://github.com/Fabricators-of-Create/Create/blob/mc1.18/fabric/dev/src/main/java/com/simibubi/create/foundation/data/recipe/LogStrippingFakeRecipes.java#L40).

I temporarily resolved the problem by setting this to false:
`#Display vanilla Log-stripping interactions in JEI.`
`	displayLogStrippingRecipes = false`

### Reproduction Steps

It does not instantly trigger upon loading into the game and occurs at random.

It may occur when attempting to view the log-stripping recipe but I haven't tested it.

### Expected Result

When viewing the recipes for an item, being able to see mixing, crushing, etc. just Create recipes.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/69522615/214121743-6fe51bf3-eacf-4c4e-a17f-e52e4759affc.png)

### Crash Report or Log

https://pastebin.com/jATd43Ge

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

jei-1.19.2-fabric-11.5.0.297.jar
...

I don't think any other mods should be affecting this. There are no other mods with Create integration.

**Comment by TheAyes** [comment]
I have a similar issue.
It's regarding Sand in the Create recipes. Sometimes (seemingly random) all create recipes that involve sand are just not using sand anymore and thus uncraftable until server restart.

**Comment by TropheusJ** [comment]
this is caused by a bug in JEI. I have added a workaround so it won't crash the plugin, but log stripping recipes will be missing on servers.

The sand issue is unrelated.

**Comment by TheAyes** [comment]
I suppose I make a separate more detailed issue then?

**Comment by TropheusJ** [comment]
It's hopefully already fixed in the next update, so not right now.
