### ISSUE TITLE
crashing game Create 1.19.2 Fabric + TwillightForest mod

### ISSUE THREAD

**Issue by MrJorman** [Fabricators-of-Create/Create#777]
### Describe the Bug

[crash-2023-01-26_09.24.35-client.txt](https://github.com/Fabricators-of-Create/Create/files/10506833/crash-2023-01-26_09.24.35-client.txt)

### Reproduction Steps

1. Start game

### Expected Result

Start game

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

TwilightForest

**Comment by TropheusJ** [comment]
is this fixed when removing Create?

**Comment by MrJorman** [comment]
yes

**Comment by MrJorman** [comment]
@TropheusJ + crash with mod Frame API + Twigs. 
[crash-2023-01-20_17.53.43-client (2).txt](https://github.com/Fabricators-of-Create/Create/files/10514650/crash-2023-01-20_17.53.43-client.2.txt)
When I press the Create block or item information, I hold down the W button

**Comment by TropheusJ** [comment]
> `Create 0.5.0.g+1.19.2`

you seem to be using a dev build of Create. Does TF work with the release version?
Please open a separate issue for the Twigs crash.

**Comment by MrJorman** [comment]
no working. Twigs crash.

**Comment by TropheusJ** [comment]
fixed with porting lib update
