### ISSUE TITLE
Multilingual compatibility of blueprints

### ISSUE THREAD

**Issue by RegulusSource** [Fabricators-of-Create/Create#778]
### Describe the Bug

When using Chinese as the blueprint name, the name becomes garbled when using the blueprint and pen (e.g. __1).

### Reproduction Steps

1.Use blueprints and pens to highlight areas
2.Use Chinese as the name of the blueprint
3.Generate blueprint
...

### Expected Result

When using Chinese as the blueprint name, the name becomes garbled when using the blueprint and pen (e.g. __1).
Nothing more

### Operating System

win10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by IThundxr** [comment]
Upstream at https://github.com/Creators-of-Create/Create/issues/6134
