### ISSUE TITLE
Train Control HUD hidden behind XP bar

### ISSUE THREAD

**Issue by p4rty4nimAl** [Fabricators-of-Create/Create#783]
When controlling a train, the speed is hidden by the XP bar.

![image](https://user-images.githubusercontent.com/69524746/215351240-938574c2-615b-4f3d-9706-b9f3f25d75a5.png)

**Comment by TropheusJ** [comment]
Does it work with Create alone? If so, can you find the incompatibility?

**Comment by p4rty4nimAl** [comment]
It does not work with Create alone; the same issue persists.

**Comment by TropheusJ** [comment]
Can I have your log?

**Comment by p4rty4nimAl** [comment]
Sure: https://pastebin.com/LHjN7JYt
I also generated a crash log with F3 + C, if that helps: https://pastebin.com/NUXUQUEm

**Comment by TropheusJ** [comment]
might be fixed in next release, I was never able to reproduce this
