### ISSUE TITLE
server crashes after placing a Deployer

### ISSUE THREAD

**Issue by lgc2333** [Fabricators-of-Create/Create#784]
### Describe the Bug

error log -> [crash-2023-01-30_04.05.27-server.txt](https://github.com/Fabricators-of-Create/Create/files/10530715/crash-2023-01-30_04.05.27-server.txt)

### Reproduction Steps

i don't really know how to reproduce it. at that time, i placed a `deployer` and the server crashed. i restarted the server, but when i tried to join in, the server crashed immediately.

### Expected Result

server do not crash

### Crash Report or Log

see `Describe the Bug`

### Operating System

Win Server 2022

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

they are in the error log

### Additional Context

using Quilt 0.17.10 with `qfapi-1.0.0-beta.28_qsl-1.1.0-beta.26_fapi-0.67.0`

**Comment by lgc2333** [comment]
i removed MiniMOTD and the problem was solved
https://www.reddit.com/r/fabricmc/comments/10ojp63/need_help_the_delpoyer_crashes_the_server/
but i have no idea why this mod will crash the server

**Comment by LittleCircleOO** [comment]
reference #503
请参考 #503
