### ISSUE TITLE
Game Crashes when using Map/Treasure Map

### ISSUE THREAD

**Issue by SolacianAllie** [Fabricators-of-Create/Create#785]
### Describe the Bug

The game crashes as soon as one obtains a treasure map or regular map, closing the game or booting you from a server(varies, as running on vanilla servers but with mods loaded locally the game boots from server but when on the server with said mod it causes a full on game close)
ive been locked out of several servers i play on because of this, and i cannot even contact the owners on half of them to edit my inventory data to remove them

### Reproduction Steps

1.Open up with create fabric, plus other create expansion mods for 1.19.2
2.obtain a treasure map or regular map
3.game crashes or boots you from server
...

### Expected Result

map opens and no crash occurs

### Operating System

Windows 10

### Mod Version

0.5.0h

### Minecraft Version

1.19.2

### Other Mods

AmbientSounds 5
Architectury API
Cloth Config
Continual Music
Create Chunkloading
Create Crafts&Additions
Create Deco Fabric
Create Fabric(obv)
Create Extended Flywheels
Creative Core
Drip Sounds Dabric
Dynamic Surroundings Fabric
Fabric API
Indium
IRIS Shaders
Just Enough Items
ModMenu
Presence footsteps
Skin Layers3D
Sodium
World Edit
Server Core
Meteor Client

### Additional Context

havent yet tested a vanilla client, but id assume the bug wouldnt occur, the reason i play most vanilla servers with my modded game is because of my shaders and other stuff bundled in, its easier

**Comment by TropheusJ** [comment]
log?

**Comment by TropheusJ** [comment]
Can you test the latest release?

**Comment by SolacianAllie** [comment]
tested latest release and its still a issue, ill attempt to look through logs sometime soon when possible
![image](https://user-images.githubusercontent.com/74777689/218085182-9c2748fa-785c-409e-92f7-32778fb50ced.png)
thats the error ive been getting, others had similar issues pointing towards create mod, so i think its the same here

**Comment by aria1th** [comment]
This is Packet Size Limit issue, not directly create's fault but now vanilla has hardcoded limits for packet size, try using https://github.com/aria1th/XLPacketsFabric/releases/tag/1.0.0-1.19.2 (both in server and client)

**Comment by TropheusJ** [comment]
That’s not packet limits, that’s a broken one.
Send the entire client and server logs.

**Comment by SolacianAllie** [comment]
sadly the server isnt mine, so server logs are out of the question, but i cleared my logs and then rejoined the server, joined survival which gives a map automatically, and crashed immidiately
[latest.log](https://github.com/Fabricators-of-Create/Create/files/10711007/latest.log)

**Comment by TropheusJ** [comment]
Wait, does the server not have Create installed?

**Comment by SolacianAllie** [comment]
it doesnt, but even on my personal server with the create installed it crashes, my profile has some mods that add stuff but also majority of them are client only mods, so its easier to just use one profile

**Comment by TropheusJ** [comment]
Using content mods on servers without them will never work right and is not supported. Any issues with that will not be fixed. 

I would like to see the log of your server with Create. Put it on https://mclo.gs/ to automatically strip IPs.

**Comment by SolacianAllie** [comment]
i just loaded up a test server under my bungee and it seems to be fine, wierd, it appears fine now for some odd reason, ill continue trying over the next week or so, just to see if there was something else to it, atleast on my create servers atleast

**Comment by FreeMonoid** [comment]
I understand that this issue isn't directly related to Create, but I am seeking a workaround to address it. Any suggestions or guidance on potential solutions would be greatly appreciated!

For example, would a mod that entirely disables map rendering fix this, or would I need to modify the networking code, given that Netty appears in the stack trace?

To provide some additional context: I am operating several near-vanilla (Paper) servers and an industrial Fabric server behind a Velocity proxy, and I'm looking to add a Create server to this setup. My players are currently able to use the industrial modpack on vanilla servers (without ability to use any modded content, of course), and I would like to offer them a similar option with a Create modpack.

**Comment by IThundxr** [comment]
Can't reproduce, If someone is able to reproduce this issue please open a new issue with both the client and server logs attached.
