### ISSUE TITLE
[Incompatibility / Crash] Charm's Bookcase in Schematic causes problems. (read description)

### ISSUE THREAD

**Issue by acanthii** [Fabricators-of-Create/Create#789]
### Describe the Bug

Using a Bookcase from charm in a schematic will render that schematic unable to place in creative, and will crash when forced to print by a Schematicannon.

### Reproduction Steps

1. Have Charm Installed
2. Use the Bookcase in a Schematic.
3. Try, and fail, to print the Schematic.

### Expected Result

Print the bookcase.

### Crash Report or Log

https://mclo.gs/rYA3wut#L2433

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

  [✔] 3dskinlayers-fabric-1.5.2-mc1.19.1   [✔] Adorn-3.8.1+1.19.2-fabric   [✔] advancementinfo-1.19.1-fabric0.58.5-1.3.1   [✔] animatica-0.5+1.19   [✔] architectury-6.4.62-fabric   [✔] ArmorStatues-v4.0.2-1.19.2-Fabric   [✔] autoconfig1u-3.4.0   [✔] balm-fabric-4.5.2+0   [✔] bclib-2.1.5   [✔] beautify-1.0.0+fabric-1.19.2   [✔] bedrockJukebox-playExtract-1.2   [✔] better-end-2.1.2   [✔] bettermounthud-1.2.0   [✔] better-nether-7.1.2   [✔] blahaj-quilt-1.19-0.2.0   [✔] blockus-2.5.6+1.19.2   [✔] BlueMap-3.9-fabric-1.19   [✔] BOMD-1.4.6-1.19.2   [✔] borderless-mining-1.1.5+1.19   [✔] Capes-1.4.5+1.19   [✔] cardinal-components-api-5.0.2   [✔] cc-restitched-1.101.2   [✔] cem-0.7.1_S8_1.19-1.19.2   [✔] charm-fabric-1.19.2-4.4.4   [✔] charmonium-fabric-1.19.2-4.2.1   [✔] chatsounds-1.1.7   [✔] Chimes-1.1.4-1.19.2-Fabric   [✔] chunksfadein-v3.0.4-1.19   [✔] CITResewn-1.1.2+1.19.2   [✔] cloth-config-8.2.88-fabric   [✔] colormatic-3.1.2+mc.1.19   [✔] comforts-fabric-6.0.3+1.19.2   [✔] continuity-2.0.1+1.19   [✔] create_crystal_clear-1.0+1.19.2(1)   [✔] createaddition-fabric+1.19.2-20221128a   [✔] CreateDeco-Fabric-1.19.2-1.2.11   [✔] create-fabric-0.5.0g-796+1.19.2(1)   [✔] ctov-3.1.4   [✔] CullLessLeaves-1.0.6   [✔] Debugify-2.8.0   [✔] dynamic-fps-2.2.0   [✔] effective-1.6+1.19.2   [✔] enhancedblockentities-0.7.2+1.19.2   [✔] Entity_Collision_FPS_Fix-fabric-1.19-2.0.0.0   [✔] entity_texture_features_fabric_1.19.2-4.2.0   [✔] entityculling-fabric-1.5.2-mc1.19  [✔] fabric-language-kotlin-1.9.0+kotlin.1.8.0   [✔] fabricskyboxes-0.6.1+mc1.19.2   [✔] fabrishot-1.9.1   [✔] fancymenu_fabric_2.13.2_MC_1.19-1.19.2   [✔] farmers-delight-fabric-1.19.X-1.3.9   [✔] farmersknives-2.3   [✔] farsight-fabric-1.19-2.4   [✔] ferritecore-5.0.3-fabric   [✔] friendsandfoes-quilt-mc1.19.2-1.6.6   [✔] fsb-interop-1.1.3+mc1.19.2-build.25   [✔] geckolib-quilt-1.19-3.1.40   [✔] grasskiss-1.19.1-fabric0.58.5-0.5.0   [✔] horse-stats-vanilla-4.2.2   [✔] idwtialsimmoedm-0.2.0+1.19   [✔] immersive_paintings-0.4.4+1.19.2-fabric   [✔] indium-1.0.9+mc1.19.2   [✔] InGameAccountSwitcher-Fabric-1.19-8.0.1   [✔] inventorio-1.19-fabric-1.8.7   [✔] iris-mc1.19.2-1.4.5   [✔] iron-jetpacks-0.4.5   [✔] item-model-fix-1.0.3+1.19   [✔] Jade-1.19.1-fabric-8.7.3   [✔] konkrete_fabric_1.6.0_MC_1.19.1-1.19.2   [✔] lambdynamiclights-2.2.0+1.19.2   [✔] language-reload-1.4.1   [✔] lazydfu-0.1.3   [✔] leafre-v1.5.0   [✔] LetSleepingDogsLie-1.19.2-1.1.1   [✔] lithium-fabric-mc1.19.2-0.10.4   [✔] loadingscreentips-1.1.0   [✔] memoryleakfix-1.19.3-0.7.0   [✔] midnightcontrols-1.7.1+1.19   [✔] MixinConflictHelper-1.2.0   [✔] mixintrace-1.1.1+1.17   [✔] MmmMmmMmmMmm-FABRIC-1.18-1.5.3   [✔] modmenu-4.1.2   [✔] morechathistory-1.19.1-1.1.1   [✔] mossier-deepslate-1.19-2.0.1   [✔] mousewheelie-1.10.6+mc1.19.2   [✔] naturalist-fabric-2.1.1-1.19.2   [✔] NoChatReports-FABRIC-1.19.2-v1.13.12   [✔] notenoughanimations-fabric-1.6.2-mc1.19.2   [✔] OpenLoader-Fabric-1.19.2-15.0.1   [✔] optigui-1.1.6   [✔] Origins-1.19.2-1.7.1   [✔] particle-rain-2.0.1   [✔] pling-1.5.0   [✔] polymorph-fabric-0.46.1+1.19.2   [✔] PresenceFootsteps-1.6.4   [✔] puzzle-1.4.0-1.19   [✔] PuzzlesLib-v4.3.12-1.19.2-Fabric   [✔] qfapi-4.0.0-beta.25_qsl-3.0.0-beta.24_fapi-0.70.0_mc-1.19.2   [✔] raised-fabric-1.19.2-1.1.4   [✔] reeses_sodium_options-1.4.9+mc1.19.2-build.67   [✔] RoughlyEnoughItems-9.1.580   [✔] scannable-MC1.19.2-fabric-1.7.7+dc5ea09   [✔] screenshot-to-clipboard-1.0.9-fabric   [✔] skin-swapper-fabric-3.1.2   [✔] smoothboot-fabric-1.19-1.7.1   [✔] sodium-extra-0.4.16+mc1.19.2-build.90   [✔] sodium-fabric-mc1.19.2-0.4.4+build.18   [✔] stacker-3.0.2-1.19.x   [✔] starlight-1.1.1+fabric.ae22326   [✔] status-effect-bars-1.0.1+1.19   [✔] StrawStatues-v4.0.8-1.19.2-Fabric   [✔] tempad-fabric-1.19.2-1.4.3   [✔] toms_storage_fabric-1.19-1.4.6   [✔] TravelersTitles-1.19.2-Fabric-3.1.0   [✔] visuality-0.5.5   [✔] waystones-fabric-1.19-11.1.0   [✔] whoami-1.0   [✔] Xaeros_Minimap_FP22.16.3_Fabric_1.19.1   [✔] XaerosWorldMap_1.28.7_Fabric_1.19.1   [✔] YetAnotherConfigLib-1.7.1   [✔] youre-in-grave-danger-1.4.6   [✔] YungsApi-1.19.2-Fabric-3.8.2   [✔] YungsBetterDesertTemples-1.19.2-Fabric-2.2.1   [✔] YungsBetterDungeons-1.19.2-Fabric-3.2.1   [✔] YungsBetterMineshafts-1.19.2-Fabric-3.2.0   [✔] YungsBetterOceanMonuments-1.19.2-Fabric-2.1.0   [✔] YungsBetterStrongholds-1.19.2-Fabric-3.2.0   [✔] YungsBetterWitchHuts-1.19.2-Fabric-2.1.0   [✔] YungsBridges-1.19.2-Fabric-3.1.0   [✔] YungsExtras-1.19.2-Fabric-3.1.0

**Comment by TropheusJ** [comment]
Cannot be fixed by Create, reported to Charm.

**Comment by acanthii** [comment]
Thank you!
(Should I close this issue now since it's technically not Create's fault?)

**Comment by TropheusJ** [comment]
no, it's still an issue
