### ISSUE TITLE
Newest Version lets the game crash

### ISSUE THREAD

**Issue by TheRealPicasso** [Fabricators-of-Create/Create#793]
### Describe the Bug

Loading the newest version of the create fabric mod, lets the game crash. The version from before works fine.

MC Version:  1.18.2
Fabric loader: 0.14.13
Create fabric version: create-fabric-0.5.0.i-921+1.18.2.jar

### Reproduction Steps

1.
2.
3.
...

### Expected Result

Not let the game crash.

### Crash Report or Log

https://pastebin.com/L5k0YES9

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.18.2

### Other Mods

- ad_astra 1.0.5
	- additionalbanners 7.0.6
	- advanced_runtime_resource_pack 0.5.5 via enhancedblockentities
	- advancementplaques 1.4.6
	- adventurez 1.4.11
	- alloy_forgery 2.0.16+1.18.2
	- almostunified 1.18.2-0.3.3
	- animated_guns 1.1
	- animatica 0.5+1.18.2
	- another_furniture 1.2.2-1.18.2
	- antiqueatlas 7.0.3-fabric-mc1.18.2
	- appleskin 2.4.1+mc1.18.2
	- architectury 4.10.88
	- archon 0.3.2
	- arclight 0.2-1.18.2
	- artifacts 7.0.3+fabric
	- attributefix 14.0.2
	- balm-fabric 3.2.2+0
	- bclib 1.4.7
	- beautify 1.1.0+fabric-1.18.2
	- bendy-lib 2.1.2 via emotecraft
	- betteranimalmodels 1.18.2-5.6.0
	- betteranimalsplus 1.18.2-11.0.10
	- bettercombat 1.5.5+1.18.2
	- betterdeserttemples 1.18.2-Fabric-1.3.1
	- betterdungeons 1.18.2-Fabric-2.1.0
	- betterend 1.1.1
	- betterfpsdist 1.18-1.8
	- bettermineshafts 1.18.2-Fabric-2.2
	- betternether 6.1.2
	- betteroceanmonuments 1.18.2-Fabric-1.0.3
	- betterstrongholds 1.18.2-Fabric-2.1.1
	- betterwitchhuts 1.18.2-Fabric-1.0.1
	- bewitchment 1.18-23
	- blanket-client-tweaks 1.0.4
	- bookshelf 13.2.52
	- bosses_of_mass_destruction 1.3.9-1.18.2
	- bsvsb 2.0.5
	- bushierflowers 0.0.1-1.18.2
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- cardinal-components 4.2.0
	- cardinal-components-base 4.2.0 via cardinal-components
	- cardinal-components-block 4.2.0 via cardinal-components
	- cardinal-components-chunk 4.2.0 via cardinal-components
	- cardinal-components-entity 4.2.0 via cardinal-components
	- cardinal-components-item 4.2.0 via cardinal-components
	- cardinal-components-level 4.2.0 via cardinal-components
	- cardinal-components-scoreboard 4.2.0 via cardinal-components
	- cardinal-components-world 4.2.0 via cardinal-components
	- carpenter 1.0.0
	- cem 0.7.1
	- charm 4.4.4
	- charmonium 4.1.0
	- chipped 2.0.1
	- chisel 1.4.5
	- chunkpregen 0.3.3
	- cinderscapes 2.0.2
	- cinderscapes-client 2.0.2 via cinderscapes
	- cinderscapes-common 2.0.2 via cinderscapes
	- cinderscapes-worldgen 2.0.2 via cinderscapes
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 6.4.90
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_eliotlash_mclib_mclib 20 via geckolib3
	- com_github_llamalad7_mixinextras 0.1.1 via immediatelyfast
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_moandjiezana_toml_toml4j 0.7.2 via charm
	- com_typesafe_config 1.4.1 via croptopia
	- combatroll 1.1.2+1.18.2
	- completeconfig 1.0.0 via cem
	- conditional-mixin 0.3.0 via moreculling
	- connectiblechains 2.1.4+1.18.2
	- connectivity 1.18.2-3.7
	- continuity 2.0.1+1.18.2
	- controlling 9.0+22
	- cosmetic-armor 1.3.1
	- crawl 0.10.6
	- create 0.5.0.i-921+1.18.2
	- createaddition ${version}
	- createchunkloading 1.2.1
	- crittersandcompanions 1.18.2-1.0.2
	- croptopia 2.1.2
	- ctm 1.0.0+1.18
	- debugify 1.11.0
	- decorative 4.2.0
	- decorative_blocks 2.1.1
	- disable_custom_worlds_advice 2.0 via nethersdelight
	- doodads 0.1.2-1.18.2
	- drinkbeer 3.2.0
	- dripstone_fluid_lib 1.2.0 via milk
	- droplight 1.0.5
	- dsurround 0.0.4
	- dungeons_arise 2.1.50
	- dynview 1.18.2-2.1
	- eatinganimationid 1.8
	- effective 1.2.1
	- emi 0.6.3+1.18.2
	- emotecraft 2.2.5
	- enchant_giver 1.2.1 via mcdw
	- enhancedblockentities 0.7.1+1.18.2
	- entity_texture_features 4.3.1
	- entityculling 1.5.1
	- exlinefurniture 2.3.0
	- expandability 6.0.0 via artifacts
	- expandeddelight 0.1.9.2
	- experiencebugfix 18
	- extraalchemy 1.8.1
	- extrasounds 2.3.1+1.18.2
	- fabric-api 0.67.1+1.18.2
	- fabric-api-base 0.4.5+64b7c69360 via fabric-api
	- fabric-api-lookup-api-v1 1.6.3+2373a54560 via fabric-api
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric-api
	- fabric-block-api-v1 1.0.0+ee3621fc60 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.13+3ac43d9560 via fabric-api
	- fabric-command-api-v1 1.1.10+d7c144a860 via fabric-api
	- fabric-commands-v0 0.2.9+b4f4f6cd60 via fabric-api
	- fabric-containers-v0 0.1.24+d7c144a860 via fabric-api
	- fabric-content-registries-v0 3.1.2+c85f2e3860 via fabric-api
	- fabric-convention-tags-v1 1.0.2+474e4f7960 via fabric-api
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric-api
	- fabric-data-generation-api-v1 3.0.3+9fcb91d260 via fabric-api
	- fabric-dimensions-v1 2.1.21+489d6f8260 via fabric-api
	- fabric-entity-events-v1 1.4.9+d7c144a860 via fabric-api
	- fabric-events-interaction-v0 0.4.20+d7c144a860 via fabric-api
	- fabric-events-lifecycle-v0 0.2.21+d7c144a860 via fabric-api
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric-api
	- fabric-item-api-v1 1.6.1+a6f01b2660 via fabric-api
	- fabric-item-groups-v0 0.3.15+91896a4960 via fabric-api
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric-api
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric-api
	- fabric-language-kotlin 1.9.1+kotlin.1.8.10
	- fabric-lifecycle-events-v1 2.1.1+cc71601c60 via fabric-api
	- fabric-loot-api-v2 1.1.1+1997ad1260 via fabric-api
	- fabric-loot-tables-v1 1.1.3+e747827960 via fabric-api
	- fabric-mining-level-api-v1 2.1.5+cc71601c60 via fabric-api
	- fabric-models-v0 0.3.7+d7c144a860 via fabric-api
	- fabric-networking-api-v1 1.0.24+2d30af4b60 via fabric-api
	- fabric-networking-v0 0.3.11+b4f4f6cd60 via fabric-api
	- fabric-object-builder-api-v1 2.1.4+032c981d60 via fabric-api
	- fabric-particles-v1 0.2.13+526dc1ac60 via fabric-api
	- fabric-permissions-api-v0 0.1-SNAPSHOT via bewitchment
	- fabric-registry-sync-v0 0.9.12+bb2e047760 via fabric-api
	- fabric-renderer-api-v1 0.4.16+ee3621fc60 via fabric-api
	- fabric-renderer-indigo 0.5.6+41a02c8a60 via fabric-api
	- fabric-renderer-registries-v1 3.2.12+b4f4f6cd60 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.9+ee3621fc60 via fabric-api
	- fabric-rendering-fluids-v1 2.0.3+54e5b2ec60 via fabric-api
	- fabric-rendering-v0 1.1.14+b4f4f6cd60 via fabric-api
	- fabric-rendering-v1 1.10.8+54e5b2ec60 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric-api
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric-api
	- fabric-screen-api-v1 1.0.11+d882b91560 via fabric-api
	- fabric-screen-handler-api-v1 1.2.3+1f6558e860 via fabric-api
	- fabric-textures-v0 1.0.13+3ac43d9560 via fabric-api
	- fabric-transfer-api-v1 1.6.4+f4563ac860 via fabric-api
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric-api
	- fabricloader 0.14.13
	- fabricskyboxes 0.5.5
	- factory_blocks 1.0.0+1.18.2
	- fallingtree 3.5.4
	- farmersdelight 1.18.2-1.2.5
	- farmersknives 1.3.1
	- farsight 1.18-1.9
	- fastload 1.5.10
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via patchouli
	- flywheel 0.6.8.a-35 via create
	- forge_tags 2.1 via create
	- forgeconfigapiport 3.2.4
	- geckolib3 3.0.80
	- horizontal-glass-panes 1.0.1-1.18.2
	- hwg 1.1.12
	- iammusicplayer 3.16.2
	- iceberg 1.0.38
	- immediatelyfast 1.1.8
	- impactfulweather 4.0.21-1.18.2
	- impersonate 2.4.1 via bewitchment
	- indium 1.0.7+mc1.18.2
	- infinitybuttons 3.1.0-mc1.18.2
	- io_github_douira_glsl-transformer 2.0.0-pre8 via iris
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- iris 1.5.0
	- itemmodelfix 1.0.3+1.18
	- jade 5.99.10
	- java 17
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- kirin 1.10.0 via presencefootsteps
	- konkrete 1.6.0
	- languagereload 1.5.4+1.18.2
	- lazydfu 0.1.2
	- legendarytooltips 1.3.3
	- letmedespawn fabric-1.0.2
	- lithium 0.10.3
	- lod 1.6.5a
	- maelstrom_library 1.2.4-1.18.2 via bosses_of_mass_destruction
	- mantle 1.18.2-1.9.156 via tconstruct
	- mcda 2.0.7
	- mcdar 1.5.2-1.18
	- mcdw 5.0.4-1.18
	- mcsa 3.0.1
	- mcwbridges 1.0.6
	- mcwdoors 1.0.7
	- mcwfences 1.0.7
	- mcwlights 1.0.5
	- mcwpaintings 1.0.4
	- mcwpaths 1.0.2
	- mcwroofs 2.2.2
	- mcwtrpdoors 1.0.8
	- mcwwindows 2.1.2
	- memoryleakfix 1.18.2-0.7.0
	- midnightlib 0.4.4
	- milk 0.3.2 via create
	- minecells 0.3.0
	- minecraft 1.18.2
	- mixintrace 1.1.1+1.17
	- mm 2.3 via crawl
	- mobscarecrow 2.1.1
	- modid 1.0.0
	- modmenu 3.2.5
	- moreculling 1.18.2-0.8.2
	- morevillagers 3.3.2
	- mousetweaks 2.22
	- multipart_entities 1.1.5-1.18.2 via bosses_of_mass_destruction
	- mvs 2.2.6-1.18.2
	- mythicmetals 0.16.4+1.18.2
	- mythicmounts 1.18.2-7.1
	- naturescompass 1.18.2-2.0.3-fabric
	- nethersdelight 2.0.0
	- nicemod 1.2 - 1.18.2
	- notenoughanimations 1.6.0
	- omega-config 1.2.3-1.18.1 via archon
	- onsoulfire 1.18-3
	- org_aeonbits_owner_owner 1.0.12 via walljump
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.11.1 via iris
	- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_javassist_javassist 3.28.0-GA via yungsapi
	- org_jetbrains_kotlin_kotlin-reflect 1.8.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.8.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.19.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_openjdk_nashorn_nashorn-core 15.3 via dsurround
	- org_reflections_reflections 0.10.2 via yungsapi
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- otyacraftengine 2.14
	- owo 0.7.2-no-cme+1.18
	- paintings 9.1.2.1
	- patchouli 1.18.2-71-FABRIC
	- pehkui 3.6.3+1.14.4-1.19.3
	- pfm 1.1.1
	- physicsmod 2.10.1
	- playdate 2.2.4
	- player-animator 0.4.2+1.18
	- playerabilitylib 1.5.0 via bewitchment
	- pollen 1.6.1
	- polymorph 0.0.21-1.18.2
	- porting_lib 1.2.730-beta+1.18.2 via create
	- presencefootsteps 1.5.1
	- prism 1.0.3
	- reach-entity-attributes 2.2.0 via mcdw
	- reeses-sodium-options 1.4.9+mc1.18.2-build.66
	- registrate-fabric MC1.18.2-1.1.7 via create
	- rocks 1.6.0
	- rpg-hud 3.9.2
	- ruined_equipment 2.0.0
	- satin 1.7.2 via mantle
	- searchlight 1.1.7
	- seedfix 1.0.1
	- serialization_hooks 0.3.23 via tconstruct
	- shouldersurfing 2.3.0
	- simplehats 1.18.2-0.1.6
	- simplyswords 1.40-1.18.2
	- skinlayers 1.5.2-mc1.18.2
	- smoothswapping 0.6.1
	- sod 22.10.13
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.16+mc1.18.2-build.89
	- soulsweapons 0.9.7
	- soundcategories 1.2.4+1.18 via extrasounds
	- spark 1.9.11
	- spruceui 3.3.0+1.17 via enhancedblockentities
	- sspb 2.0.1
	- star 1.3+1.18.2 via mantle
	- starlight 1.0.2+fabric.89b8d9f
	- step-height-entity-attribute 1.0.0 via artifacts
	- structory 1.0.0
	- table_top_craft 1.18.2-1.0.3
	- tconstruct 1.18.2-3.5.2.155
	- team_reborn_energy 2.2.0 via ad_astra
	- terrablender 1.2.0.126
	- terraform-biome-remapper-api-v1 3.1.0 via cinderscapes
	- terraform-shapes-api-v1 3.1.0 via cinderscapes
	- terraform-wood-api-v1 3.1.0 via cinderscapes
	- transparent 4.1.0
	- travelersbackpack 1.18.2-7.1.17
	- trinkets 3.3.1
	- vinery 1.1.4
	- voidz 1.0.7
	- walljump 1.3.3+1.18.2
	- waystones 10.1.0
	- whisperwoods 1.18.2-2.1.0
	- wildbackport 1.2.3
	- winged 1.18.2-3.2.0
	- xps 0.4.7-r+1.18.2-Fabric
	- xps_additions 0.1.8-r+1.18.2-Fabric
	- yungsapi 1.18.2-Fabric-2.2.7
	- yungsbridges 1.18.2-Fabric-2.1.0
	- yungsextras 1.18.2-Fabric-2.1.0

**Comment by TropheusJ** [comment]
Need the crash log, this is the regular log.

**Comment by TheRealPicasso** [comment]
> Need the crash log, this is the regular log.

It might be some incompability issue or something, since i use a lot of mods, but its all working with the previous version.
okay i will send the crash report as a pastebin here: https://pastebin.com/VQXhQWMz

**Comment by SplendidAlakey** [comment]
You can't use Create versions newer than Create addons. You'll have to wait until it updates, too.

**Comment by TheRealPicasso** [comment]
> You can't use Create versions newer than Create addons. You'll have to wait until it updates, too.

when might it be updated?

**Comment by TropheusJ** [comment]
yep, createaddition is not updated. I don't know when it will be.
