### ISSUE TITLE
Block `create:metal_girder_encased_shaft` is waterlogged by default

### ISSUE THREAD

**Issue by James103** [Fabricators-of-Create/Create#796]
### Describe the Bug

Running the following command:
```mcfunction
setblock ~ ~ ~ create:metal_girder_encased_shaft
```
without specifying any block states produces a metal girder with a shaft through it **that is waterlogged**.
This suggests the block's default state has `waterlogged = true`.

### Reproduction Steps

1. Create a new instance, Minecraft 1.19.2, Fabric loader 0.14.13.
2. Install the Fabric version of Create mod, version `0.5.0.i-925`.
3. Install Fabric API `0.70.0`.
4. Create a new world with cheats enabled.
5. Run the command `setblock ~ ~ ~ create:metal_girder_encased_shaft` (without specifying any block states)
6. The resulting encased shaft is waterlogged.

### Expected Result

The block should not be waterlogged by default.

### Operating System

Windows 10, 64-bit

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by IThundxr** [comment]
Cannot reproduce on forge or fabric
