### ISSUE TITLE
Item Drain causing `java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads`

### ISSUE THREAD

**Issue by cwadrupldijjit** [Fabricators-of-Create/Create#797]
### Describe the Bug

I created an auto-harvesting honey farm that empties the bottles into an item drain, which then sucks the honey into a tank (as a buffer) and then sucks it into a spout so I can make honeyed apples.  The setup works just fine, but then the spout, tank, pipes, and item drain filled up and I get occasional crashes.  I wasn't sure at first what was causing it, but it seems like the item drain is the culprit per the crash report.

I'm not entirely sure how to reproduce the problem, but I can share a culled version of my world uploaded so that you can see it for yourself.  An annoying thing is that it doesn't always crash when the item drain is loaded, but it happens occasionally--not occasionally enough to be able to ignore it.

I am not using the latest version of the mod simply because my game won't run with it because of an incompatibility and subsequent crash on startup with a common dependency (or so I understand it) with the Twilight Forest mod which is also installed.  That is preventing me from testing it with the latest version of Create installed.  That also means that I can't verify if it's happening because of another mod or not.

### Reproduction Steps

1. Load up the provided world
2. Spend time in the vicinity/loading the item drain in question (it's the only one so far)
3. The bug surfaces and the game crashes suddenly and without too much warning

### Expected Result

It doesn't cause the game to crash.

### Crash Report or Log

https://1drv.ms/t/s!AtpBOFa0mPoVjN1c_wFTwGIssuwxtw?e=v9zDf6

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

Full list of CurseForge-installed mods:
----
appleskin-fabric-mc1.19-2.4.1.jar
architectury-6.4.62-fabric.jar
BetterAdvancements-Fabric-1.19.2-0.2.2.142.jar
BetterF3-4.0.0-Fabric-1.19.2.jar
bettermounthud-1.2.0.jar
betterstats-2.2.1+1.19.2.jar
Bookshelf-Fabric-1.19.2-16.2.17.jar
clickadv-fabric-3.0.jar
cloth-config-8.2.88-fabric.jar
Clumps-fabric-1.19.2-9.0.0+14.jar
Controlling-fabric-1.19.2-10.0+7.jar
create-fabric-0.5.0g-796+1.19.2.jar
Decorative Blocks-fabric-1.19.2-3.0.0.jar
fabric-api-0.73.2+1.19.2.jar
fabric-language-kotlin-1.9.1+kotlin.1.8.10.jar
freecam-1.1.6+1.19.jar
held-item-info-1.4.0.jar
indium-1.0.9+mc1.19.2.jar
InventoryProfilesNext-fabric-1.19-1.9.2.jar
iris-mc1.19.2-1.5.0.jar
Jade-1.19.1-fabric-8.7.3.jar
JadeAddons-1.19.2-fabric-3.0.0.jar
lambdynamiclights-2.2.0+1.19.2.jar
libIPN-fabric-1.19-2.0.2.jar
lithium-fabric-mc1.19.2-0.10.4.jar
malilib-fabric-1.19.2-0.13.0.jar
minihud-fabric-1.19.2-0.23.3.jar
modmenu-4.1.2.jar
MouseTweaks-fabric-mc1.19-2.22.jar
Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.13.jar
openblockselevator-0.0.2-1.19.X.jar
reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
rer-2.6.0.jar
RoughlyEnoughItems-9.1.587.jar
RoughlyEnoughLootTables-1.19-1.0.jar
RoughlyEnoughProfessions-fabric-1.19.2-1.1.3.jar
RoughlyEnoughTrades-1.19-1.0.jar
sodium-extra-0.4.16+mc1.19.2-build.90.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
spark-1.10.17-fabric.jar
TerraBlender-fabric-1.19.2-2.0.1.130.jar
ToolStats-Fabric-1.19.2-12.0.2.jar
twilightforest-fabric-1.19.2-4.2.333.jar
worldedit-mod-7.2.12.jar
YetAnotherConfigLib-2.2.0-for-1.19.2.jar
youre-in-grave-danger-1.4.8.jar
Zoomify-2.9.0.jar

**Comment by TropheusJ** [comment]
Please install [this](https://modrinth.com/mod/uwrad) and get it to happen again.

**Comment by cwadrupldijjit** [comment]
K.  The crash log I was given when the game crashed this time is here:
https://1drv.ms/t/s!AtpBOFa0mPoVjN1djrdWLpieZ-Nc1g?e=FskbNT

**Comment by TropheusJ** [comment]
Looking again, I see the issue, it's just Create.
