### ISSUE TITLE
Crash due to Twilight Forest

### ISSUE THREAD

**Issue by praecipitator** [Fabricators-of-Create/Create#798]
### Describe the Bug

Crash if both create 0.5.0i and Twilight Forest are loaded. Doesn't happen with 0.5.0g.

### Reproduction Steps

1. Install mod create-fabric-0.5.0.i-925+1.19.2.jar
2. Install mod twilightforest-fabric-1.19.2-4.2.333.jar
3. Try to start minecraft via the fabric loader
4. Observe crash

### Expected Result

Minecraft not crashing.

### Crash Report or Log

https://pastebin.com/U8S8v0Af

### Operating System

Ubuntu 22.04.1 LTS

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

	- ae2 12.9.2
	- ae2wtlib 12.8.4
	- amecsapi 1.3.7+mc22w17a via mousewheelie
	- appbot 1.4.1
	- architectury 6.4.62
	- badpackets 0.2.1
	- bclib 2.1.5
	- betterend 2.1.2
	- betternether 7.1.2
	- bewitchment 1.19-6
	- blue_endless_jankson 1.2.1 via owo
	- botania 1.19.2-437-FABRIC
	- bowinfinityfix 2.5.0
	- bwplus 1.19-9
	- byg 2.0.0.13
	- cardinal-components 5.0.2
	- cardinal-components-base 5.0.2 via cardinal-components
	- cardinal-components-block 5.0.2 via cardinal-components
	- cardinal-components-chunk 5.0.2 via cardinal-components
	- cardinal-components-entity 5.0.2 via cardinal-components
	- cardinal-components-item 5.0.2 via cardinal-components
	- cardinal-components-level 5.0.2 via cardinal-components
	- cardinal-components-scoreboard 5.0.2 via cardinal-components
	- cardinal-components-world 5.0.2 via cardinal-components
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.2.88
	- coat 1.0.0-beta.19+mc22w17a via mousewheelie
	- collective 6.43
	- com_electronwill_night-config_core 3.6.6 via byg
	- com_electronwill_night-config_toml 3.6.6 via byg
	- com_eliotlash_mclib_mclib 20 via geckolib3
	- com_github_llamalad7_mixinextras 0.1.1 via porting_lib
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_moandjiezana_toml_toml4j 0.7.2 via paragon
	- common-protection-api 1.0.0 via universal-graves
	- computercraft 1.101.2
	- continuity 2.0.1+1.19
	- convenient-mobgriefing 2.0.2
	- crafttweaker 10.0.29
	- create 0.5.0.i-925+1.19.2
	- customportalapi 0.0.1-beta54-1.19 via deeperdarker
	- de_poiu_apron_apron 2.1.1 via mconfig
	- deeperdarker 1.1.6
	- dripstone_fluid_lib 2.0.1 via milk
	- dungeons_arise 2.1.51
	- ellemes_container_lib 2.1.0-alpha.12 via expandedstorage
	- error_notifier 1.0.9 via roughlyenoughitems
	- expandedstorage 8.0.5
	- extended_drawers 1.3.6+mc.1.19.2
	- fabric-api 0.73.0+1.19.2
	- fabric-api-base 0.4.14+6e0787e690 via fabric-api
	- fabric-api-lookup-api-v1 1.6.13+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.1.0+82db024a90 via fabric-api
	- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.23+c6af733c90 via fabric-api
	- fabric-client-tags-api-v1 1.0.4+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.15+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.2.0+413cbbc790 via fabric-api
	- fabric-commands-v0 0.2.32+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.40+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.5.0+7c6cd14d90 via fabric-api
	- fabric-convention-tags-v1 1.2.1+27265b3490 via fabric-api
	- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.3.6+413cbbc790 via fabric-api
	- fabric-dimensions-v1 2.1.34+0d0f210290 via fabric-api
	- fabric-entity-events-v1 1.5.3+9244241690 via fabric-api
	- fabric-events-interaction-v0 0.4.33+562bff6e90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.34+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
	- fabric-item-api-v1 1.6.4+693ffc0590 via fabric-api
	- fabric-item-groups-v0 0.3.37+9244241690 via fabric-api
	- fabric-key-binding-api-v1 1.0.25+5c4fce2890 via fabric-api
	- fabric-keybindings-v0 0.2.23+df3654b390 via fabric-api
	- fabric-language-kotlin 1.8.6+kotlin.1.7.21
	- fabric-lifecycle-events-v1 2.2.3+1b46dc7890 via fabric-api
	- fabric-loot-api-v2 1.1.11+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.14+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.6+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.22+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.20+c6af733c90 via fabric-api
	- fabric-networking-api-v1 1.2.10+10eb22f490 via fabric-api
	- fabric-networking-v0 0.3.27+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.2.0+d8ef690890 via fabric-api
	- fabric-particles-v1 1.0.13+4d0d570390 via fabric-api
	- fabric-permissions-api-v0 0.1-SNAPSHOT via universal-graves
	- fabric-recipe-api-v1 1.0.0+413cbbc790 via fabric-api
	- fabric-registry-sync-v0 0.9.31+9244241690 via fabric-api
	- fabric-renderer-api-v1 1.2.0+2e5408b590 via fabric-api
	- fabric-renderer-indigo 0.7.0+2e5408b590 via fabric-api
	- fabric-renderer-registries-v1 3.2.23+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.18+6e0787e690 via fabric-api
	- fabric-rendering-fluids-v1 3.0.10+4d0d570390 via fabric-api
	- fabric-rendering-v0 1.1.26+df3654b390 via fabric-api
	- fabric-rendering-v1 1.12.0+d8ef690890 via fabric-api
	- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
	- fabric-resource-loader-v0 0.8.3+251d254a90 via fabric-api
	- fabric-screen-api-v1 1.0.31+4d0d570390 via fabric-api
	- fabric-screen-handler-api-v1 1.3.6+1cc24b1b90 via fabric-api
	- fabric-sound-api-v1 1.0.2+c4f28df590 via fabric-api
	- fabric-textures-v0 1.0.23+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.1.5+413cbbc790 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
	- fabricloader 0.14.13
	- fake-player-api 0.5.0 via the_bumblezone
	- fiber 0.23.0-2 via botania
	- flywheel 0.6.8.a-4 via create
	- forge_tags 3.0 via porting_lib
	- forgeconfigapiport 4.2.9
	- fwaystones 3.0.5+mc1.19.2
	- geckolib3 3.1.37
	- graphlib 0.3.6+1.19.2 via wiredredstone
	- graveyard 2.3
	- harvest_scythes 2.5.4+mc1.19.2
	- here-be-no-dragons 1.0.0 via twilightforest
	- hexcasting 0.10.3
	- hologram-api 0.2.2+1.19 via universal-graves
	- icarus 1.13
	- immersive_aircraft 0.3.0+1.19.2
	- impersonate 2.8.0 via bewitchment
	- indium 1.0.9+mc1.19.2
	- infusion_table 1.1.0
	- ingredient-extension-api 3.0.6
	- inmis 2.7.1-1.19
	- io_github_douira_glsl-transformer 2.0.0-pre8 via iris
	- io_netty_netty-codec-http 4.1.77.Final via computercraft
	- iris 1.5.0
	- jankson 4.1.1+j1.2.1 via libgui
	- java 17
	- javax_annotation_javax_annotation-api 1.3.2 via twilightforest
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- lambdynlights 2.2.0+1.19.2
	- lchunkloader 2.0.4
	- leavesbegone 4.0.0
	- libblockattributes_core 0.11.1 via libmultipart_deps_container
	- libgui 6.3.0+1.19 via multisleep
	- libmultipart 0.8.0 via libmultipart_deps_container
	- libmultipart_deps_container 0.8.0 via wiredredstone
	- libnetworkstack 0.7.1 via libmultipart_deps_container
	- libninepatch 1.1.0 via libgui
	- linkedstorage 1.5.1-1.19
	- lmp-compat 0.2.1+1.19 via wiredredstone
	- magnumtorch 4.2.1
	- mconfig 1.2.0+mc.1.19-rc1 via extended_drawers
	- midnightlib 0.6.1 via miskatonicmysteries
	- milk 1.0.51 via create
	- minecraft 1.19.2
	- miskatonicmysteries 0.1.6
	- mm 2.3 via harvest_scythes
	- mob_catcher 1.2.15
	- modmenu 4.1.2
	- moonlight 1.19.2-2.2.3
	- mooshroomtweaks 3.0
	- mousewheelie 1.10.7+mc1.19.2
	- multisleep 1.4
	- noindium 1.1.0+1.19 via ae2
	- omega-config 1.2.3-1.18.1 via inmis
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.11.1 via iris
	- org_javassist_javassist 3.29.0-GA via crafttweaker
	- org_jetbrains_kotlin_kotlin-reflect 1.7.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.21 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- org_reflections_reflections 0.10.2 via crafttweaker
	- org_squiddev_cobalt 0.5.5 via computercraft
	- org_yaml_snakeyaml 1.27 via paragon
	- owo 0.8.5+1.19
	- packet_tweaker 0.3.0+1.18.2 via polymer
	- paragon 3.0.2 via deeperdarker
	- patchouli 1.19.2-77-FABRIC
	- paucal 0.5.0
	- pehkui 3.6.3+1.14.4-1.19.3
	- placeholder-api 2.0.0-pre.1+1.19.2 via universal-graves
	- playerabilitylib 1.6.0 via bewitchment
	- polymer 0.2.17+1.19.2 via universal-graves
	- polymer-registry-sync-manipulator 0.0.3+1.19.2 via polymer
	- polymorph 0.46.1+1.19.2
	- portablehole 4.0.0
	- porting_lib 2.1.731+1.19.2 via create
	- porting_lib_accessors 2.1.731+1.19.2 via porting_lib
	- porting_lib_attributes 2.1.731+1.19.2 via porting_lib
	- porting_lib_base 2.1.731+1.19.2 via porting_lib
	- porting_lib_common 2.1.731+1.19.2 via porting_lib
	- porting_lib_constants 2.1.731+1.19.2 via porting_lib
	- porting_lib_entity 2.1.731+1.19.2 via porting_lib
	- porting_lib_extensions 2.1.731+1.19.2 via porting_lib
	- porting_lib_fake_players 2.1.731+1.19.2 via porting_lib
	- porting_lib_lazy_registration 2.1.731+1.19.2 via porting_lib
	- porting_lib_model_generators 2.1.731+1.19.2 via porting_lib
	- porting_lib_model_loader 2.1.731+1.19.2 via porting_lib
	- porting_lib_models 2.1.731+1.19.2 via porting_lib
	- porting_lib_networking 2.1.731+1.19.2 via porting_lib
	- porting_lib_obj_loader 2.1.731+1.19.2 via porting_lib
	- porting_lib_transfer 2.1.731+1.19.2 via porting_lib
	- powah 4.0.6
	- pride 1.1.2+1.19 via lambdynlights
	- probablychests 0.5.5-1.19.2
	- puzzleslib 4.3.12
	- reach-entity-attributes 2.3.0 via botania
	- registrate-fabric 1.1.50-MC1.19.2 via create
	- roughlyenoughitems 9.1.585
	- satin 1.9.0 via miskatonicmysteries
	- serialization_hooks 0.3.26 via porting_lib
	- server_translations_api 1.4.18+1.19.2 via universal-graves
	- sgui 1.1.5+1.19.1 via universal-graves
	- simplechunkloader 1.0.2
	- sodium 0.4.4+build.18
	- spectrelib 0.11.0+1.19 via polymorph
	- spruceui 4.1.0+1.19.2 via lambdynlights
	- step-height-entity-attribute 1.0.0 via bewitchment
	- supplementaries 1.19.2-2.2.46
	- team_reborn_energy 2.2.0 via powah
	- terrablender 2.0.1.130
	- terraform-wood-api-v1 4.2.0 via bewitchment
	- the_bumblezone 6.6.2+1.19.2
	- toms_storage 1.4.6
	- trinkets 3.4.2
	- tweed4_annotated 1.3.1+mc22w17a via mousewheelie
	- tweed4_base 1.7.1+mc22w17a via mousewheelie
	- tweed4_data 1.2.1+mc22w17a via mousewheelie
	- tweed4_data_hjson 1.1.1+mc22w17a via mousewheelie
	- tweed4_tailor_coat 1.1.3+mc22w17a via mousewheelie
	- tweed4_tailor_screen 1.1.3+mc22w17a via mousewheelie
	- twilightforest 4.2.333
	- universal-graves 2.1.3+1.19.2
	- wildlife 1.19.2-2.2
	- wiredredstone 0.4.14+1.19.2
	- wthit 5.13.4
	- xaerominimap 22.17.1
	- xaeroworldmap 1.28.8

**Comment by TropheusJ** [comment]
will be fixed in next TF update
