### ISSUE TITLE
Train Station Not Opening

### ISSUE THREAD

**Issue by N8rtot** [Fabricators-of-Create/Create#799]
### Describe the Bug

When I hold the track_station block and hover over any track, the arrow sign in the track doesnt appear til I place the station, and then I cant actually right click to open the ui for the station. 

### Reproduction Steps

1. Place tracks down
2. Right click on track while holding train station block
3. Place and right click on train station
...

### Expected Result

UI to open up and allow a new train to be assembled 

### Screenshots and Videos

![2023-02-06_14 42 36](https://user-images.githubusercontent.com/77558552/217069273-76dbdbea-926a-45a7-888e-d007ccc51d00.png)
![2023-02-06_14 42 47](https://user-images.githubusercontent.com/77558552/217069275-35bcf424-7661-44b8-93a9-27742f34c625.png)

### Crash Report or Log

https://mclo.gs/2ULmzfO

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

![image](https://user-images.githubusercontent.com/77558552/217073397-1e0eb331-a436-4ad0-ad55-eeea5485551d.png)
![image](https://user-images.githubusercontent.com/77558552/217073516-727a27c1-1fd8-4273-a4d7-37f7caa2e4e8.png)

**Comment by TropheusJ** [comment]
does it work with Create alone? If so, can you narrow down the incompat?

**Comment by N8rtot** [comment]
Turns out im dense as hell, server-side version of the mod was 0.5.0g and I was using 0.5.0i, switching to the same version as the server fixed it right up
