### ISSUE TITLE
Chute takes item from crushing wheel controller before it is properly processed

### ISSUE THREAD

**Issue by JHDev2006** [Fabricators-of-Create/Create#800]
### Describe the Bug

when a chute is placed underneath a vertical crushing wheel setup, any item that is being crushed will be extracted from the crushing wheels by the chute, before it can be properly crushed

### Reproduction Steps

1. make a standard crushing wheel setup vertically, with a chute ontop of a chest, and below a crushing wheel
2. place an item into the crushing wheel (cobblestone)
3. chute will take the item before it is processed.
4.
...

### Expected Result

chute should take the items AFTER the crushing process is completed, not while it is being crushed

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

  [✔] 3dskinlayers-fabric-1.5.2-mc1.19.1
  [✔] advancementinfo-1.19.1-fabric0.58.5-1.3.1
  [✔] antighost-1.19.1-fabric0.58.5-1.1.5
  [✔] appleskin-fabric-mc1.19-2.4.1
  [✔] architectury-6.5.69-fabric
  [✔] badpackets-fabric-0.2.1
  [✔] BetterF3-4.0.0-Fabric-1.19.2
  [✔] betterstats-2.2.1+1.19.2
  [✔] borderless-mining-1.1.5+1.19
  [✔] c2me-fabric-mc1.19.2-0.2.0+alpha.9.5
  [✔] cc-restitched-1.101.2
  [✔] charm-fabric-1.19.2-4.4.4
  [✔] charmonium-fabric-1.19.2-4.2.1
  [✔] CITResewn-1.1.2+1.19.2
  [✔] clickthrough-1.19.1-fabric0.58.5-0.4
  [✔] cloth-config-8.2.88-fabric
  [✔] Clumps-fabric-1.19.2-9.0.0+14
  [✔] Craftify-1.19-1.6.0-fabric
  [✔] createchunkloading-1.3.0-fabric
  [✔] create-fabric-0.5.0.i-925+1.19.2
  [✔] CullLessLeaves-1.0.6
  [✔] dashloader-4.1.3+1.19
  [✔] Debugify-2.8.0
  [✔] DetailArmorBar-2.6.2+1.19-fabric
  [✔] dynamiccrosshair-5.0+1.19.2-fabric
  [✔] dynamic-fps-2.2.0
  [✔] eating-animation-1.9
  [✔] entity_texture_features_fabric_1.19.2-4.3.1
  [✔] entityculling-fabric-1.5.2-mc1.19
  [✔] exordium-fabric-1.0.2-mc1.19.2
  [✔] extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2
  [✔] fabric-api-0.73.2+1.19.2
  [✔] fabric-language-kotlin-1.9.1+kotlin.1.8.10
  [✔] FallingTree-1.19.2-3.10.0
  [✔] Fastload+1.19.2-2.6.11
  [✔] ferritecore-5.0.3-fabric
  [✔] ftb-chunks-fabric-1902.3.15-build.233
  [✔] ftb-library-fabric-1902.3.11-build.166
  [✔] ftb-teams-fabric-1902.2.12-build.95
  [✔] ftb-ultimine-fabric-1902.3.5-build.65
  [✔] gravestones-v1.13
  [✔] indium-1.0.9+mc1.19.2
  [✔] irisflw-0.1.8-BETA
  [✔] iris-mc1.19.2-1.5.2
  [✔] item-model-fix-1.0.3+1.19
  [✔] krypton-0.2.1
  [✔] lambdabettergrass-1.3.0+1.19
  [✔] lambdynamiclights-2.2.0+1.19.2
  [✔] lazydfu-0.1.3
  [✔] lithium-fabric-mc1.19.2-0.10.4
  [✔] memoryleakfix-1.19.1-0.7.0
  [✔] modmenu-4.1.2
  [✔] mousewheelie-1.10.7+mc1.19.2
  [✔] notenoughanimations-fabric-1.6.2-mc1.19.2
  [✔] PresenceFootsteps-1.6.4
  [✔] puzzle-1.4.2-1.19
  [✔] raised-fabric-1.19.2-1.1.4
  [✔] reeses_sodium_options-1.4.9+mc1.19.2-build.67
  [✔] RoughlyEnoughItems-9.1.587
  [✔] smoothboot-fabric-1.19-1.7.1
  [✔] sodium-extra-0.4.16+mc1.19.2-build.90
  [✔] sodium-fabric-mc1.19.2-0.4.4+build.18
  [✔] starlight-1.1.1+fabric.ae22326
  [✔] trinkets-3.4.2
  [✔] visuality-0.5.5
  [✔] wthit-fabric-5.13.5
  [✔] Xaeros_Minimap_23.1.0_Fabric_1.19.1
  [✔] XaerosWorldMap_1.28.9_Fabric_1.19.1
  [✔] YetAnotherConfigLib-2.2.0-for-1.19.2

**Comment by TropheusJ** [comment]
Already fixed

**Comment by JHDev2006** [comment]
bug was fixed in the 1.18 fabric port. not the 1.19 fabric version, bug is still present.
