### ISSUE TITLE
Server crashes randomly?

### ISSUE THREAD

**Issue by gittibene** [Fabricators-of-Create/Create#801]
### Describe the Bug

Server crashes a few times a day getting this error:

 [Server thread/WARN]: Lithium Class Analysis Error: Class com.simibubi.create.content.logistics.trains.entity.CarriageContraptionEntity cannot be analysed, because getting declared methods crashes with NoClassDefFoundError: com/jozufozu/flywheel/api/instance/DynamicInstance. This is usually caused by modded entities declaring methods that have a return type or parameter type that is annotated with @Environment(value=EnvType.CLIENT). Loading the type is not possible, because it only exists in the CLIENT environment. The recommended fix is to annotate the method with this argument or return type with the same annotation. Lithium handles this error by assuming the class cannot be included in some optimizations. 

[Maybe related to this?
]( https://github.com/Creators-of-Create/Create/issues/4088)

### Reproduction Steps

1. Start Server
2. Wait for crash when train is nearby
3.crash
...

### Expected Result

Server not crashing

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Other Mods

	- ad_astra 1.12.1
- adorn 3.7.0+1.19.2
- advanced_runtime_resource_pack 0.6.2 via automobility
- advdebug 2.3.0
- adventurez 1.4.17
- ae2 12.8.5
- architectury 6.3.56
- artifacts 7.1.1+fabric
- attributefix 17.1.3
- automobility 0.4.1+1.19.2-fabric
- awesomedungeon 3.0.0
- awesomedungeonend 3.0.0
- awesomedungeonnether 3.0.0
- awesomedungeonocean 3.0.1
- balm-fabric 4.5.2+0
- bclib 2.1.5
- betteranimalsplus 1.19.2-11.0.10
- betterbeds 1.2.0
- betterdungeons 1.19.2-Fabric-3.2.1
- betterend 2.1.2
- bettermineshafts 1.19.2-Fabric-3.2.0
- betternether 7.1.2
- betterstrongholds 1.19.2-Fabric-3.2.0
- betterwitchhuts 1.19.2-Fabric-2.1.0
- blue_endless_jankson 1.2.1 via owo
- bosses_of_mass_destruction 1.4.6-1.19.2
- botarium 1.8.2
- brewinandchewin fabric-1.0.5+1.19.2
- buildinggadgets 1.0.30
- byg 2.0.0.7
- cardinal-components-base 5.0.0-beta.1 via artifacts
- cardinal-components-entity 5.0.0-beta.1 via artifacts
- cardinal-components-item 5.0.0-beta.1 via buildinggadgets
- cardinal-components-level 5.0.0-beta.1 via buildinggadgets
- cardinal-components-world 5.0.0-beta.1 via buildinggadgets
- charm 4.4.4
- chisel 1.4.5
- cloth-api 4.0.65
- cloth-basic-math 0.6.1 via cloth-api
- cloth-client-events-v0 4.0.65 via cloth-api
- cloth-common-events-v1 4.0.65 via cloth-api
- cloth-config 8.2.88
- cloth-utils-v1 4.0.65 via cloth-api
- collective-fabric 5.16
- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
- com_eliotlash_mclib_mclib 20 via geckolib3
- com_github_llamalad7_mixinextras 0.1.1 via friendsandfoes
- com_google_code_findbugs_jsr305 3.0.2 via create
- com_moandjiezana_toml_toml4j 0.7.2 via charm
- com_typesafe_config 1.4.1 via croptopia
- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
- create 0.5.0g-796+1.19.2
- createaddition ${version}
- createchunkloading 1.3.0
- createdeco 1.2.12-1.19.2
- creeperoverhaul 2.0.5
- crittersandcompanions 1.19.2-1.0.2
- croptopia 2.1.2
- culturaldelights 0.14.9+1.19.2
- customportalapi 0.0.1-beta54-1.19 via deeperdarker
- deeperdarker 1.1.4
- delightchef 1.0.1-1.19.2
- dramaticdoors 1.19.2-1.3.5_1
- dripstone_fluid_lib 2.0.1 via milk
- ecologics 2.1.10
- entitycollisionfpsfix 2.0.0.0
- error_notifier 1.0.9 via roughlyenoughitems
- expandability 6.0.0 via artifacts
- fabric-api 0.70.0+1.19.2
- fabric-api-base 0.4.14+6e0787e690 via fabric-api
- fabric-api-lookup-api-v1 1.6.13+93d8cb8290 via fabric-api
- fabric-biome-api-v1 9.0.21+4d0d570390 via fabric-api
- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
- fabric-command-api-v1 1.2.14+f71b366f90 via fabric-api
- fabric-command-api-v2 2.1.10+93d8cb8290 via fabric-api
- fabric-commands-v0 0.2.31+df3654b390 via fabric-api
- fabric-containers-v0 0.1.39+df3654b390 via fabric-api
- fabric-content-registries-v0 3.5.0+7c6cd14d90 via fabric-api
- fabric-convention-tags-v1 1.2.1+27265b3490 via fabric-api
- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
- fabric-data-generation-api-v1 5.3.4+ad31814d90 via fabric-api
- fabric-dimensions-v1 2.1.34+0d0f210290 via fabric-api
- fabric-entity-events-v1 1.5.3+9244241690 via fabric-api
- fabric-events-interaction-v0 0.4.32+4d0d570390 via fabric-api
- fabric-events-lifecycle-v0 0.2.32+df3654b390 via fabric-api
- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
- fabric-item-api-v1 1.6.2+fa140d5990 via fabric-api
- fabric-item-groups-v0 0.3.37+9244241690 via fabric-api
- fabric-language-kotlin 1.8.7+kotlin.1.7.22
- fabric-lifecycle-events-v1 2.2.3+1b46dc7890 via fabric-api
- fabric-loot-api-v2 1.1.11+83a8659290 via fabric-api
- fabric-loot-tables-v1 1.1.14+9e7660c690 via fabric-api
- fabric-message-api-v1 5.0.6+93d8cb8290 via fabric-api
- fabric-mining-level-api-v1 2.1.22+33fbc73890 via fabric-api
- fabric-networking-api-v1 1.2.9+6e0787e690 via fabric-api
- fabric-networking-v0 0.3.26+df3654b390 via fabric-api
- fabric-object-builder-api-v1 4.1.4+4d0d570390 via fabric-api
- fabric-particles-v1 1.0.13+4d0d570390 via fabric-api
- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
- fabric-registry-sync-v0 0.9.30+9244241690 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.18+6e0787e690 via fabric-api
- fabric-rendering-fluids-v1 3.0.10+4d0d570390 via fabric-api
- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
- fabric-resource-loader-v0 0.8.3+251d254a90 via fabric-api
- fabric-screen-handler-api-v1 1.3.5+1cc24b1b90 via fabric-api
- fabric-transfer-api-v1 2.1.4+4d0d570390 via fabric-api
- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
- fabricloader 0.14.12
- factory_blocks 1.0.1+1.19
- fake-player-api 0.5.0 via create
- fallingtree 3.10.0
- farmersdelight 1.19.2-1.3.9
- farmersknives 2.2
- ferritecore 5.0.3
- fiber 0.23.0-2 via collective-fabric
- fishofthieves 2.1.0-rc4
- forge_tags 3.0 via porting_lib
- forgeconfigapiport 4.2.9 via nethersdelight
- forgivingvoid 7.0.0
- friendsandfoes 1.6.8
- fwaystones 3.0.5+mc1.19.2
- geckolib3 3.1.37
- graveyard 2.3
- graveyard_biomes 1.6
- iceberg 1.0.46
- indypets 1.1.0-1.19.2
- inventoryessentials 5.0.0
- io_leangen_geantyref_geantyref 1.3.11 via croptopia
- java 17
- jsonem 0.1.2+1.19 via automobility
- krypton 0.2.1
- laserbridges 1.19.2-0
- lazydfu 0.1.3
- libraryferret 3.0.0
- lithium 0.10.4
- maelstrom_library 1.3-1.19-pre1 via bosses_of_mass_destruction
- maybe-data 1.3.2-1.19-rc2 via wolveswitharmor
- mca 7.4.0+1.19.2
- mcwbridges 2.0.5
- mcwdoors 1.0.7
- mcwfences 1.0.6
- mcwlights 1.0.4
- mcwpaintings 1.0.4
- mcwpaths 1.0.2
- mcwroofs 2.2.1
- mcwtrpdoors 1.0.7
- mcwwindows 2.1.0
- midnightlib 0.5.2 via rocks
- milk 1.0.51 via create
- minecraft 1.19.2
- mm 2.3 via buildinggadgets
- mobscarecrow 2.2.1-1.19.1
- moonlight 1.19.2-2.2.4
- moreleads 1.19.2-1.0.0
- multipart_entities 1.2-1.19-pre1 via bosses_of_mass_destruction
- mythicmounts 1.19.2-7.1
- nethersdelight 1.0.0
- notenoughbreeding 1.19.2-1.0.0-fabric
- omega-config 1.2.2-1.18.1 via graveyard_biomes
- openpartiesandclaims 0.16.4
- org_javassist_javassist 3.28.0-GA via yungsapi
- org_jetbrains_kotlin_kotlin-reflect 1.7.22 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 1.7.22 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.22 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.22 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
- org_reflections_reflections 0.10.2 via yungsapi
- org_spongepowered_configurate-core 4.1.2 via croptopia
- org_spongepowered_configurate-hocon 4.1.2 via croptopia
- overpoweredmending 2.8.2
- owo 0.8.2+1.19
- oxidized 1.7.2
- paragon 1.0.3 via deeperdarker
- patchouli 1.19.2-76-FABRIC
- porting_lib 2.1.623+1.19.2 via create
- porting_lib_accessors 2.1.623+1.19.2 via porting_lib_extensions
- porting_lib_attributes 2.1.623+1.19.2 via porting_lib_extensions
- porting_lib_base 2.1.623+1.19.2 via porting_lib
- porting_lib_common 2.1.623+1.19.2 via porting_lib_extensions
- porting_lib_constants 2.1.623+1.19.2 via porting_lib_attributes
- porting_lib_entity 2.1.623+1.19.2 via porting_lib
- porting_lib_extensions 2.1.623+1.19.2 via porting_lib_transfer
- porting_lib_lazy_registration 2.1.623+1.19.2 via porting_lib
- porting_lib_model_generators 2.1.623+1.19.2 via porting_lib
- porting_lib_model_loader 2.1.623+1.19.2 via porting_lib_obj_loader
- porting_lib_models 2.1.623+1.19.2 via porting_lib
- porting_lib_networking 2.1.623+1.19.2 via porting_lib
- porting_lib_obj_loader 2.1.623+1.19.2 via porting_lib
- porting_lib_transfer 2.1.623+1.19.2 via porting_lib
- quarryplus 19.1.672
- reach-entity-attributes 2.3.0 via create
- reborncore 5.4.0
- registrate-fabric 1.1.44-MC1.19.2 via create
- resourcefulconfig 1.0.17
- resourcefullib 1.1.19
- respawnablepets 1.19-2
- rocks 1.6.1
- rottencreatures 1.0.1
- roughlyenoughitems 9.1.574
- serialization_hooks 0.3.26 via porting_lib_base
- smoothchunk 1.19.1-2.0
- smwyg 1.0.3
- spark 1.9.45
- static-content 1.0.1-1.16.2 via wolveswitharmor
- staticdata 1.1.2 via static-content
- step-height-entity-attribute 1.0.0 via artifacts
- structurized-reborn 1.19-01 via delightchef
- supplementaries 1.19.2-2.2.46
- t_and_t 1.10
- tawct 1.4.3+1.19.2
- team_reborn_energy 2.3.0 via techreborn
- techreborn 5.4.0
- terrablender 2.0.1.130
- terraform-wood-api-v1 4.2.0 via vinery
- terralith 2.3
- timeoutout 1.0.3+1.19.1
- travelersbackpack 1.19.2-8.2.12
- trinkets 3.4.1

**Comment by TropheusJ** [comment]
That warning is not a crash. Send the full log.

**Comment by gittibene** [comment]
Sorry should have mentioned i dont get a crash report, this is just the last message that pops up, client crashes (no report), server freezes

**Comment by TropheusJ** [comment]
Still need the full log

**Comment by gittibene** [comment]
Log was clean but the latest create update fixed the crashes thank you
