### ISSUE TITLE
[Crash] CTD caused by java.lang.NoClassDefFoundError: dan200/computercraft/api/peripheral/IPeripheralProvider

### ISSUE THREAD

**Issue by Milajanh** [Fabricators-of-Create/Create#804]
### Describe the Bug

Game crashes whenever I try to boot up the game with the Create mod.

### Reproduction Steps

1. Add create mod and all of its addons
2. Boot the game up
3. CTD

### Expected Result

Crash to Desktop

### Crash Report or Log

https://pastebin.com/trxafcFX

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

[Krypton (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/krypton)
[WorldEdit (by sk89q)](https://www.curseforge.com/minecraft/mc-mods/worldedit)
[Vampiric Origin (by JustAFoxxo)](https://www.curseforge.com/minecraft/mc-mods/vampiric-origin)
[Health Overlay (Fabric) (by Terrails)](https://www.curseforge.com/minecraft/mc-mods/health-overlay-fabric)
[YUNG's API (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric)
[Rings of Ascension (Fabric) (by Focamacho)](https://www.curseforge.com/minecraft/mc-mods/fabric-rings-of-ascension)
[oωo (owo-lib) (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
[Smooth Swapping (Fabric) (by Schauweg)](https://www.curseforge.com/minecraft/mc-mods/smooth-swapping)
[[FABRIC/QUILT] Disable Custom Worlds Advice (by rdvdev2)](https://www.curseforge.com/minecraft/mc-mods/fabric-disable-custom-worlds-advice)
[Fabric Chunk Pregenerator (by SuperCoder79)](https://www.curseforge.com/minecraft/mc-mods/chunk-pregenerator-fabric)
[Oh The Biomes You'll Go Refabricated (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric)
[Amplified Nether (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/amplified-nether)
[Bed Benefits (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bed-benefits)
[Carpet Extra (by gnembon)](https://www.curseforge.com/minecraft/mc-mods/carpet-extra)
[Cloth API (Fabric) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-api)
[MmmMmmMmmMmm (Target Dummy) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm)
[Illuminations 🔥 (by doctor4t)](https://www.curseforge.com/minecraft/mc-mods/illuminations)
[YDM's Spellswords (by YourDailyModderx)](https://www.curseforge.com/minecraft/mc-mods/spellsword)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[WMITAF (by ShaksterNano)](https://www.curseforge.com/minecraft/mc-mods/wmitaf)
[Cull Leaves (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/cull-leaves)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[RPGStats (by silverthelesbian)](https://www.curseforge.com/minecraft/mc-mods/rpgstats)
[Blockus (by Brandcraft_)](https://www.curseforge.com/minecraft/mc-mods/blockus)
[Kitsune Origin (by TeyTey428)](https://www.curseforge.com/minecraft/mc-mods/kitsune-origin)
[Bad Wither No Cookie - Reloaded (by Kreezxil)](https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded)
[Dehydration (by Globox_Z)](https://www.curseforge.com/minecraft/mc-mods/dehydration)
[NoExpensive (by Enaium)](https://www.curseforge.com/minecraft/mc-mods/noexpensive)
[EnhancedVisuals (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/enhancedvisuals)
[Amethyst Imbuement (by fzzyhmstrs)](https://www.curseforge.com/minecraft/mc-mods/amethyst-imbuement)
[ToolTipFix (by Kyrptonaught)](https://www.curseforge.com/minecraft/mc-mods/tooltipfix)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Create Fabric (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
[Simple Discord Rich Presence (Forge / Fabric) (by Sunekaer)](https://www.curseforge.com/minecraft/mc-mods/simple-discord-rich-presence)
[Create Chunkloading (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/create-chunkloading)
[Mythic Metals Decorations (by Noaaan)](https://www.curseforge.com/minecraft/mc-mods/mythicmetals-decorations)
[Held Item Info (by Neecko5b84)](https://www.curseforge.com/minecraft/mc-mods/held-item-info)
[Logical Zoom (by LogicalGeekBoy)](https://www.curseforge.com/minecraft/mc-mods/logical-zoom)
[Guard Villagers (Fabric/Quilt) (by MrSterner_)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers-fabric)
[Better Mount HUD (by Lortseam_)](https://www.curseforge.com/minecraft/mc-mods/better-mount-hud)
[Harvest Scythes (by LordDeatHunter)](https://www.curseforge.com/minecraft/mc-mods/harvest-scythes)
[Trinkets (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/trinkets)
[Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[Boat Hud (by hibiscvs)](https://www.curseforge.com/minecraft/mc-mods/boathud)
[Gobber [FABRIC] (by kwpugh)](https://www.curseforge.com/minecraft/mc-mods/gobber-fabric)
[Inventory HUD+ (by dmitrylovin)](https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge)
[Limited Spawners (Fabric) (by StrikerRocker)](https://www.curseforge.com/minecraft/mc-mods/limited-spawners-fabric)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[CraftPresence (by CDAGaming_)](https://www.curseforge.com/minecraft/mc-mods/craftpresence)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Inventorio (Fabric) (by Lizard_OfOz)](https://www.curseforge.com/minecraft/mc-mods/inventorio)
[Cardinal Components (by UpcraftLP)](https://www.curseforge.com/minecraft/mc-mods/cardinal-components)
[Visual Workbench (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[MC Story Mode Armors [Forge / Fabric] (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcsa)
[EnvironmentZ (by Globox_Z)](https://www.curseforge.com/minecraft/mc-mods/environmentz)
[Skin Layers 3D (Fabric/Forge) (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
[DragonLoot (by pois1xlive)](https://www.curseforge.com/minecraft/mc-mods/dragonloot)
[Iris Shaders (by coderbot)](https://www.curseforge.com/minecraft/mc-mods/irisshaders)
[LazyDFU (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/lazydfu)
[Create: Extended Flywheels Fabric (by Rabbitminers)](https://www.curseforge.com/minecraft/mc-mods/create-extended-flywheels-fabric)
[Advanced XRay (Fabric Edition) (by Error_MiKeY)](https://www.curseforge.com/minecraft/mc-mods/advanced-xray-fabric-edition)
[Command Macros (by Kyrptonaught)](https://www.curseforge.com/minecraft/mc-mods/command-macros)
[MC Dungeons Armors (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcda)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Builtin Servers (by D4rkness_King)](https://www.curseforge.com/minecraft/mc-mods/builtin-servers)
[Don't Drop It! (by ADudeCalledLeo)](https://www.curseforge.com/minecraft/mc-mods/dont-drop-it)
[Traveler's Titles (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/travelers-titles-fabric)
[Inventory Sorting (by Kyrptonaught)](https://www.curseforge.com/minecraft/mc-mods/inventory-sorting)
[Simply Swords [Fabric & Forge] (by sweenuss)](https://www.curseforge.com/minecraft/mc-mods/simply-swords)
[Global Packs (by JTK222)](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack)
[Extra Alchemy (by zabi94)](https://www.curseforge.com/minecraft/mc-mods/extra-alchemy)
[Loading Screen Tips (by UltrusBot)](https://www.curseforge.com/minecraft/mc-mods/loading-screen-tips)
[Create Deco Fabric (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco-fabric)
[Configured Keep Inventory (by OverlordsIII)](https://www.curseforge.com/minecraft/mc-mods/configured-keep-inventory)
[Things [Fabric] (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/things-fabric)
[Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[DarkTides - Breathe Underwater (by GamerPotion)](https://www.curseforge.com/minecraft/mc-mods/darktides-breathe-underwater)
[MaLiLib (by masady)](https://www.curseforge.com/minecraft/mc-mods/malilib)
[Stacker (by Andrew6rant)](https://www.curseforge.com/minecraft/mc-mods/stacker)
[DarkCap - Cap Your XP! (by GamerPotion)](https://www.curseforge.com/minecraft/mc-mods/darkcap-cap-your-xp)
[Traveler's Backpack [Fabric] (by Tiviacz1337)](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric)
[More Villagers [Fabric] (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/more-villagers-fabric)
[Starlight (Fabric) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight)
[Extra Origins (by MoriyaShiine)](https://www.curseforge.com/minecraft/mc-mods/extra-origins)
[BetterNether (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betternether)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Item Model Fix (Fabric) (by Pepper_Bell)](https://www.curseforge.com/minecraft/mc-mods/item-model-fix)
[Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[MixinTrace (by comp500)](https://www.curseforge.com/minecraft/mc-mods/mixintrace)
[BetterEnd (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betterend)
[MCPitanLibarch (Fabric/Forge) (by pitan76)](https://www.curseforge.com/minecraft/mc-mods/mcpitanlibarch)
[Origins: Umbrellas (by Fusion_Flux)](https://www.curseforge.com/minecraft/mc-mods/origins-umbrellas)
[Alloy Forgery (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/alloy-forgery)
[Majo's Broom (by innkly)](https://www.curseforge.com/minecraft/mc-mods/majos-broom)
[Sculkling Origin (by RLLStudios)](https://www.curseforge.com/minecraft/mc-mods/sculkling-origin)
[Origins: Classes (by Apace100)](https://www.curseforge.com/minecraft/mc-mods/origins-classes)
[Presence Footsteps [Fabric] (by S0llace)](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps)
[Carpet (by gnembon)](https://www.curseforge.com/minecraft/mc-mods/carpet)
[Mod Menu (by ProspectorDev)](https://www.curseforge.com/minecraft/mc-mods/modmenu)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[ItemFlexer (by silverthelesbian)](https://www.curseforge.com/minecraft/mc-mods/itemflexer)
[Diamond Auction House (by IAmTheSneak)](https://www.curseforge.com/minecraft/mc-mods/diamond-auction-house)
[Create Support for Open Parties and Claims (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/opac-fabric-create-support)
[Numeral Ping (by TheKodeToad)](https://www.curseforge.com/minecraft/mc-mods/numeral-ping)
[DarkBindings - 100+ Recipes to Craft (by GamerPotion)](https://www.curseforge.com/minecraft/mc-mods/darkbindings-custom-recipes)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Open Parties and Claims (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims)
[Eating Animation [Fabric] (by theone_ss)](https://www.curseforge.com/minecraft/mc-mods/eating-animation-fabric)
[Simple Discord Link Bot [Forge/Fabric] (by hypherionsa)](https://www.curseforge.com/minecraft/mc-mods/simple-discord-link-bot-forge-fabric-spigot)
[FixMySpawnR (by AbsolemJackdaw)](https://www.curseforge.com/minecraft/mc-mods/fixmyspawnr)
[Better Third Person (by Socolio)](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
[Extra Thicc Packets (by JaselUmena)](https://www.curseforge.com/minecraft/mc-mods/extra-thicc-packets)
[Magic Combat Wands (by dmitrylovin)](https://www.curseforge.com/minecraft/mc-mods/magic-combat-wands)
[Mob Origins (by UltrusBot)](https://www.curseforge.com/minecraft/mc-mods/mob-origins)
[Let Me Despawn (by frikinjay1)](https://www.curseforge.com/minecraft/mc-mods/let-me-despawn)
[[Fabric] Tooltip Texts Scroller (by hamusuke2303)](https://www.curseforge.com/minecraft/mc-mods/fabric-tooltip-texts-scroller)
[No Report Button (by pices1237532)](https://www.curseforge.com/minecraft/mc-mods/no-report-button)
[RPG Origins (by DaBananaCat)](https://www.curseforge.com/minecraft/mc-mods/rpg-origins)
[TerraBlender (Fabric) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric)
[BackpackMod (by SpyMan1736)](https://www.curseforge.com/minecraft/mc-mods/backpackmod)
[Diamond Economy (by IAmTheSneak)](https://www.curseforge.com/minecraft/mc-mods/diamond-economy)
[Elytra Physics (by ImJ0shh_)](https://www.curseforge.com/minecraft/mc-mods/elytra-physics)
[Voice Chat Interaction (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/voice-chat-interaction)
[Patchouli (Fabric/Quilt) (by williewillus)](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
[IvyCore (by JustAFoxxo)](https://www.curseforge.com/minecraft/mc-mods/ivycore)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Arcanus: Legacy (by Camellias_)](https://www.curseforge.com/minecraft/mc-mods/arcanus)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Durability101 Forge/Fabric 1.12-1.19 (by シェイン)](https://www.curseforge.com/minecraft/mc-mods/durability101)
[Not Enough Animations (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)
[Diagonal Fences (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences)
[GeckoLib (by ThanosGecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Marium's Soulslike Weaponry (by mariumbacchus)](https://www.curseforge.com/minecraft/mc-mods/mariums-soulslike-weaponry)
[HT's TreeChop (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechop)
[Enhanced Mob Spawners (by BR4NDER5)](https://www.curseforge.com/minecraft/mc-mods/enhanced-mob-spawners)
[Lithium (Fabric) (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/lithium)
[Tiny PVP Swords and Tools (by GamerPotion)](https://www.curseforge.com/minecraft/texture-packs/tiny-pvp-swords-and-tools)
[Mixin Conflict Helper (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/mixin-conflict-helper)
[Connectible Chains [Fabric] (by legoatoom)](https://www.curseforge.com/minecraft/mc-mods/connectible-chains)
[LambDynamicLights (by LambdAurora)](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights)
[Physics Mod (by haubna)](https://www.curseforge.com/minecraft/mc-mods/physics-mod)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[Fabric Waystones (by LordDeatHunter)](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Create: Extended Cogwheels Fabric (by Rabbitminers)](https://www.curseforge.com/minecraft/mc-mods/create-extended-cogwheels-fabric)
[Adorn (by Juicebus)](https://www.curseforge.com/minecraft/mc-mods/adorn)
[Forge Config API Port (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[Classic 3D (16x) (by RyanGar46)](https://www.curseforge.com/minecraft/texture-packs/classic-3d)
[Iron Chests (Fabric) (by cyberanner)](https://www.curseforge.com/minecraft/mc-mods/iron-chests-for-fabric)
[Archon (by safrodev)](https://www.curseforge.com/minecraft/mc-mods/archon)
[Puzzles Lib (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[DarkSpins - XP Casino (by GamerPotion)](https://www.curseforge.com/minecraft/mc-mods/darkspins-xp-casino)
[Mythic Metals (by Noaaan)](https://www.curseforge.com/minecraft/mc-mods/mythicmetals)
[Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
[Fabric Seasons (by D4rkness_King)](https://www.curseforge.com/minecraft/mc-mods/fabric-seasons)
[DarkQuesting - Custom Quests (by GamerPotion)](https://www.curseforge.com/minecraft/mc-mods/darkquesting-a-quest-mod)
[Motschen's Better Leaves (by Motschen)](https://www.curseforge.com/minecraft/texture-packs/motschens-better-leaves)
[FPS Reducer (by bre2el)](https://www.curseforge.com/minecraft/mc-mods/fps-reducer)
[VanitySlots (by Nyakorita)](https://www.curseforge.com/minecraft/mc-mods/vanityslots)
[Cosmetica (by eyezah)](https://www.curseforge.com/minecraft/mc-mods/cosmetics)
[Fzzy Core (by fzzyhmstrs)](https://www.curseforge.com/minecraft/mc-mods/fzzy-core)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[ServerCore (by Wesley8081)](https://www.curseforge.com/minecraft/mc-mods/servercore)
[Bosses of Mass Destruction (by Barribob)](https://www.curseforge.com/minecraft/mc-mods/bosses-of-mass-destruction)
[Packet Size Doubler (by THESIIG)](https://www.curseforge.com/minecraft/mc-mods/packet-size-doubler)
[Kambrik (by Ejektaflex)](https://www.curseforge.com/minecraft/mc-mods/kambrik)
[Artifacts (Fabric) (by florensie)](https://www.curseforge.com/minecraft/mc-mods/artifacts-fabric)
[Mo's Grounded Origins [FABRIC] (by mo_shark)](https://www.curseforge.com/minecraft/mc-mods/grounded-origins-fabric)
[Amethyst Core (by fzzyhmstrs)](https://www.curseforge.com/minecraft/mc-mods/amethyst-core)
[Clickable advancements[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/clickable-advancements)
[RPG PVP Swords and Tools (by GamerPotion)](https://www.curseforge.com/minecraft/texture-packs/rpg-pvp-swords-and-tools)
[Roughly Enough Items Fabric/Forge (REI) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
[Polymorph (Fabric) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[FindMe (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/findme)
[Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
[Happiness (is a) Warm Gun (by cybercat5555)](https://www.curseforge.com/minecraft/mc-mods/happiness-is-a-warm-gun)
[Chunky (Fabric) (by pop4959)](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator)
[BCLib (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/bclib)
[Lootr (Fabric) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr-fabric)
[Taterzens [Fabric] (by samo_lego)](https://www.curseforge.com/minecraft/mc-mods/taterzens)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Better End Sky (by Jet_Mouse)](https://www.curseforge.com/minecraft/mc-mods/better-end-sky-fabric)
[Immersive Armors [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)
[DarkFlight - Simple Jetpack (by GamerPotion)](https://www.curseforge.com/minecraft/mc-mods/darkflight-simple-jetpack)
[Croptopia (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia)
[FerriteCore (Fabric) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric)
[Mouse Wheelie (Fabric) (by Siphalor)](https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie)
[DarkLoot - Better Mob Loot (by GamerPotion)](https://www.curseforge.com/minecraft/mc-mods/darkloot-better-mob-loot)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Sodium (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/sodium)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[ExtraSounds (by stashymane)](https://www.curseforge.com/minecraft/mc-mods/extrasounds)
[Bountiful (Fabric) (by Ejektaflex)](https://www.curseforge.com/minecraft/mc-mods/bountiful-fabric)
[Simple Uncrafting Table (Fabric/Forge) (by pitan76)](https://www.curseforge.com/minecraft/mc-mods/simple-uncrafting-table-fabric)
[Quick Stack [Fabric] (by TheArcanePigeon)](https://www.curseforge.com/minecraft/mc-mods/quick-stack-fabric)
[MC Dungeons Artifacts (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcdar)
[Create Deco Fabric Fixed (by manuthreecubed)](https://www.curseforge.com/minecraft/mc-mods/create-deco-fabric-fixed)
[Naturalist (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/naturalist)
[MC Dungeons Weapons (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcdw)
[DarkRTP - RTP Random Teleport (by GamerPotion)](https://www.curseforge.com/minecraft/mc-mods/darkrtp-rtp-random-teleport)
[Origins (Fabric) (by Apace100)](https://www.curseforge.com/minecraft/mc-mods/origins)
[Litematica (by masady)](https://www.curseforge.com/minecraft/mc-mods/litematica)
[Falling Leaves (Fabric) (by RandomMcSomethin)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric)
[CleanCut (by Rongmario)](https://www.curseforge.com/minecraft/mc-mods/cleancut)
[Carpet-Fixes (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/carpet-fixes)
[Dynamic Surroundings: Remastered Fabric Edition (by maksim789456)](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings-remastered-fabric-edition)
[When Dungeons Arise - Fabric! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise-fabric)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)

**Comment by TropheusJ** [comment]
Looks like CC&A

**Comment by Milajanh** [comment]
> Looks like CC&A

What does CC&A mean?

**Comment by TropheusJ** [comment]
Create crafts and additions

**Comment by Milajanh** [comment]
> Create crafts and additions

While deleting the mod did help with CTD, the game still doesn't work. It's stuck at the loading screen. Should I make a new thread or continue explaining the issue in this one?

**Comment by Milajanh** [comment]
Nevermind, I didn't have Indium installed which was stopping the Create mod from working
Thank you very much for your help!
