### ISSUE TITLE
Crash on game load (cannot invoke method)

### ISSUE THREAD

**Issue by Pentasis** [Fabricators-of-Create/Create#806]
### Describe the Bug

Game crashes during load. I suspect incompatibility with another mod but crashlog doesn't give (me) any clue as to which mod it might be.

### Reproduction Steps

1. Start the game
2.
3.
...

### Expected Result

It shouldn't crash.

### Crash Report or Log

https://pastebin.com/kwFZVm9g

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

catwalksinc: Catwalks Inc. 1.3.1
charm: Charm 4.4.4
	com_moandjiezana_toml_toml4j: toml4j 0.7.2
cloth-config: Cloth Config v8 8.2.88
	cloth-basic-math: cloth-basic-math 0.6.1
continuity: Continuity 2.0.1+1.19
create: Create 0.5.0.i-946+1.19.2
	com_google_code_findbugs_jsr305: jsr305 3.0.2
	flywheel: Flywheel 0.6.8.a-4
	milk: Milk Lib 1.0.51
		dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
	porting_lib: Porting Lib 2.1.766+1.19.2
		com_github_llamalad7_mixinextras: MixinExtras 0.1.1
		forge_tags: Porting Lib Tags 3.0
		mm: Manningham Mills 2.3
		porting_lib_accessors: Porting Lib Accessors 2.1.766+1.19.2
		porting_lib_attributes: Porting Lib Attributes 2.1.766+1.19.2
		porting_lib_base: Porting Lib Base 2.1.766+1.19.2
		porting_lib_common: Porting Lib Common 2.1.766+1.19.2
		porting_lib_constants: Porting Lib Constants 2.1.766+1.19.2
		porting_lib_entity: Porting Lib Entity 2.1.766+1.19.2
		porting_lib_extensions: Porting Lib Extensions 2.1.766+1.19.2
		porting_lib_fake_players: Porting Lib Fake Players 2.1.766+1.19.2
		porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.766+1.19.2
		porting_lib_model_generators: Porting Lib Model Generators 2.1.766+1.19.2
		porting_lib_model_loader: Porting Lib Model Loader 2.1.766+1.19.2
		porting_lib_models: Porting Lib Models 2.1.766+1.19.2
		porting_lib_networking: Porting Lib Networking 2.1.766+1.19.2
		porting_lib_obj_loader: Porting Lib Obj Loader 2.1.766+1.19.2
		porting_lib_transfer: Porting Lib Transfer 2.1.766+1.19.2
		serialization_hooks: Serialization Hooks 0.3.26
	reach-entity-attributes: Reach Entity Attributes 2.3.0
	registrate-fabric: Registrate for Fabric 1.1.50-MC1.19.2
decorative_blocks: Decorative Blocks 3.0.0
entityculling: EntityCulling-Fabric 1.5.2-mc1.19
	com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
environmentalcreepers: Environmental Creepers 1.6.0
fabric-api: Fabric API 0.73.2+1.19.2
	fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
	fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
	fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
	fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
	fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.24+c6af733c90
	fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
	fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
	fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
	fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
	fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
	fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+7c6cd14d90
	fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+27265b3490
	fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
	fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.7+413cbbc790
	fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
	fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
	fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
	fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.35+df3654b390
	fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
	fabric-item-api-v1: Fabric Item API (v1) 1.6.5+dce4603e90
	fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.38+9244241690
	fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
	fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
	fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
	fabric-loot-api-v2: Fabric Loot API (v2) 1.1.12+83a8659290
	fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.15+9e7660c690
	fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
	fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.23+33fbc73890
	fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
	fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
	fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
	fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.1+d8ef690890
	fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
	fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
	fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
	fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+2e5408b590
	fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.1+2e5408b590
	fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
	fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
	fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
	fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
	fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
	fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
	fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
	fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
	fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
	fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
	fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
	fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
	fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
fabricloader: Fabric Loader 0.14.14
fallingleaves: Falling Leaves 1.13.0+1.19.2
farmersdelight: Farmer's Delight 1.19.2-1.3.9
forgeconfigapiport: Forge Config API Port 4.2.10
	com_electronwill_night-config_core: core 3.6.5
	com_electronwill_night-config_toml: toml 3.6.5
iris: Iris 1.5.2
	io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
	org_anarres_jcpp: jcpp 1.4.14
	org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
java: OpenJDK 64-Bit Server VM 17
jei: Just Enough Items 11.5.2.1007
leavesbegone: Leaves Be Gone 4.0.1
lithium: Lithium 0.10.4
magnumtorch: Magnum Torch 4.2.1
minecraft: Minecraft 1.19.2
mousetweaks: Mouse Tweaks 2.22
puzzleslib: Puzzles Lib 4.3.12
	cardinal-components-base: Cardinal Components API (base) 5.0.2
	cardinal-components-block: Cardinal Components API (blocks) 5.0.2
	cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
	cardinal-components-entity: Cardinal Components API (entities) 5.0.2
	cardinal-components-world: Cardinal Components API (worlds) 5.0.2
reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
sodium: Sodium 0.4.4+build.18
	org_joml_joml: joml 1.10.4
sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
	caffeineconfig: CaffeineConfig 1.0.0+1.17
starlight: Starlight 1.1.1+fabric.ae22326
worldedit: WorldEdit 7.2.12+6240-87f4ae1
xaeroworldmap: Xaero's World Map 1.28.9
yigd: You're in Grave Danger 1.4.8

**Comment by drwoops** [comment]
Gogekka on discord found there seems to be an incompatibility between patch `i-946` and sodium 0.4.4
https://discord.com/channels/620934202875183104/620937113554124801/1074372467092639784

**Comment by Codebreakerblue** [comment]
Fixed for me by using Create patch `i-925` with sodium 0.4.4, in case anyone else has the same issue.

**Comment by TropheusJ** [comment]
Install indium.

**Comment by TropheusJ** [comment]
With my latest commit this crash will not occur, so you will see the chat message saying to install indium.

**Comment by greensad** [comment]
Crashes with indium installed: https://mclo.gs/RBRTVeZ

Tried release i-925 with sodium 0.4.4 build 18 but it still crashed, works on g-796 for me though.

**Comment by TropheusJ** [comment]
Unrelated issue. Update twilight forest.

**Comment by greensad** [comment]
> Unrelated issue. Update twilight forest.

My b, thanks for clearing that up, you didn't have to but I do really appreciate it <3 and also happy valentines day!
