### ISSUE TITLE
Deployers broken after patch 0.5.0i

### ISSUE THREAD

**Issue by CzechHek** [Fabricators-of-Create/Create#807]
### Describe the Bug

Applies to Create Fabric 1.18.2, 1.19.2: any 0.5.0i (including latest dev)
When a deployer kills a mob, **it gets achievement** "Monster Hunter" and **zombies** around that deployer **start pathfinding** to it.
Additionally, in **1.19.2** the **mob loot drops on the ground** instead of going into Deployers inventory, whereas in **1.18.2** it works **correctly**.

Everything **works correctly prior 0.5.0i** and also on **any** Create **Forge patch**, including 0.5.0i.

### Reproduction Steps

https://youtu.be/E_5w9QOCDGI

### Expected Result

Deployer should work like on Create Forge or Create Fabric 0.5.0g and prior.
* Mob loot should go to Deployers inventory.
* Mobs shouldn't be agroed on Deployers
* Deployers shouldn't get achievements

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/42714212/218279802-3eaa1e35-3f58-45aa-8030-651a361f4956.png)

https://youtu.be/E_5w9QOCDGI

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
attacking the deployer back is a feature, there's a config for it. Some reason, they're pathfinding to (0, 0, 0) instead of the actual pos though.
I want to keep the advancement granting because I think it's hilarious.

**Comment by CzechHek** [comment]
Well I think the biggest problem from these is in 1.19, that the loot drops on ground instead of going into deployers inventory.

**Comment by TropheusJ** [comment]
Actually, pathfinding to (0, 0, 0) is identical behavior to Forge on 1.18, and doesn't happen on 1.19.

**Comment by TropheusJ** [comment]
item collecting is fixed with my last 2 commits.

**Comment by CzechHek** [comment]
Yes, but should the zombies even pathfind to the deployers? It doesn't make much sense.

**Comment by TropheusJ** [comment]
yes, it's intentional.
