### ISSUE TITLE
Crash on Client Side (ArrayIndexOutOfBoundsException) 1.19.2

### ISSUE THREAD

**Issue by suerion** [Fabricators-of-Create/Create#808]
### Describe the Bug

Player moves in the near o Create Blocks, then it crash with Crahslog

### Reproduction Steps

We don't know how to reproduce, it appears only in the near of Create blocks, we thougt in the near of this blocks 

### Expected Result

no crashing

### Crash Report or Log

https://pastebin.com/WQPfiptp

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by suerion** [comment]
We had found the error, after using this, the client crash allways 
![7CC7CC47-1515-4D5D-9948-520880EDBDD4](https://user-images.githubusercontent.com/55131959/218311689-adb60763-11f8-476f-a156-dac82ad82cf3.png)

**Comment by aria1th** [comment]
can you try disabling 'async search' in REI options?

**Comment by suerion** [comment]
@aria1th since the last update of Create, the player does not crashing anymore.
