### ISSUE TITLE
Server Crash with "this.fluidHandlerProvider"

### ISSUE THREAD

**Issue by suerion** [Fabricators-of-Create/Create#809]
### Describe the Bug

We will start the server, but it crash instantly

### Reproduction Steps

Start the server, crash will apear

### Expected Result

Server will start normal

### Crash Report or Log

https://pastebin.com/JJ2X1cbJ

### Operating System

Look in Crash Log

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Additional Context

Please come with an resolve for this issue, our live server will not start anymore

**Comment by suerion** [comment]
Okey, i had deleted the Mechanical Pump with NBT Editor in the Chunk, now the server does load again

**Comment by TropheusJ** [comment]
already fixed in dev
