### ISSUE TITLE
Crash with Milkplus

### ISSUE THREAD

**Issue by Noplace0** [Fabricators-of-Create/Create#81]
Describe the Bug
When milk plus is installed, the game could not start and crash immediately.

Reproduction Steps
Install Create, milkplus and all dependencies thereof.
Press start minecraft
Experience crash.

Screenshots and Videos
No response

Crash Report or Log
No response

Operating System
Windows 10

Mod Version
0.4.0b

Minecraft Version
1.18.1

Other Mods
Milkplus

Additional Context
No response

**Comment by TropheusJ** [comment]
please provide a log, if you use the latest version of both mods they should work fine together.

**Comment by Noplace0** [comment]
log: https://gist.github.com/Noplace0/0ad6ede63c6eb50e8101f8c3745edac6#file-gistfile1-txt

**Comment by identithree** [comment]
What version of milk+ are you using? I want to try and recreate the error.
edit: i realized the issue includes cr version

**Comment by identithree** [comment]
I am on latest version of Fabric 1.18.1, Create Refabricated ([0.4.0b](https://github.com/Fabricators-of-Create/Create/actions/runs/1672902734)), Milk Plus (2.0.1), and Fabric API (0.45.2)

Only difference is I am running Fedora 35. Everything else has been recreated.
![image](https://user-images.githubusercontent.com/71232944/148673366-a1ddd429-827e-49cf-a39b-73790e8bfce1.png)

[Here is my log for the interested parties](https://i-am.coping.live/p/A4tqdOVu52P2)

**Comment by Noplace0** [comment]
I am using create-mc1.18.1_v0.4b and milk_plus-2.0.0, fabric-api-0.45.0+1.18. I can not start the game when milk and create is installed. If only one of them is installed then I can start the game.

The testing is using better Minecraft fabric 1.81 version, a mod pack. But it would not work anyway, when I place any create block the game will crash anyway.

**Comment by identithree** [comment]
The latest version of Milk+ is 2.0.1, which fixes this issue. You can find it on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/milk-plus/files/3581211)
