### ISSUE TITLE
Basin stops processing after single process

### ISSUE THREAD

**Issue by aria1th** [Fabricators-of-Create/Create#811]
### Describe the Bug

Happens in versions after this commit :
https://github.com/Fabricators-of-Create/Create/commit/456d604a06fbe0b5cc0c9c47d490099397877e81#diff-1431545e5918c84f5cf60dff82206a2ecc9b96861ef2faf0049d3f27024dd134

![2023-02-12_22 01 57](https://user-images.githubusercontent.com/35677394/218312614-6c61bbf7-7ed0-4a05-a040-751a2ce869d9.png)

### Reproduction Steps

1. Create andesite mixing, then sending to other basin setup as attached above.
2. Input cobblestone and diorite in upper basin, in any form.
3. Process then watch.

### Expected Result

Processing should not stop.

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Additional Context

If basin is broken (below), then basin can process again, but its inconsistent.

I suspect its something related to recipe caching invalidation problem.

**Comment by TropheusJ** [comment]
When a basin has a spoutput, it will only process when it can output. Since basins can only hold 16 of an item, it stops quickly. This is the same as on forge.
In my testing, this behavior is working fine. If you still think there is an issue, please elaborate. A video may help.
