### ISSUE TITLE
Create 1.18.2 Fluid Pipe Causing Ticking Block Entity Crash.

### ISSUE THREAD

**Issue by Fade-Alchemist** [Fabricators-of-Create/Create#813]
### Describe the Bug

After updating to the most recent patch create-fabric-0.5.0.i-944+1.18.2.jar crashes when i load my base in. A ticking block entity crash. I was able to get things to work by using a replace command on the glitched fluid pipe - but now another fluid pipe is glitched out. It looks like they are systematically failing. I have a few examples of the crash attached via the reports below. 

[crash-2023-02-12_20.19.19-server.txt](https://github.com/Fabricators-of-Create/Create/files/10717345/crash-2023-02-12_20.19.19-server.txt)
[crash-2023-02-12_19.56.36-server.txt](https://github.com/Fabricators-of-Create/Create/files/10717350/crash-2023-02-12_19.56.36-server.txt)

### Reproduction Steps

Not sure what trigged this event, I feel like I had been in this area since the update to create-fabric-0.5.0.i-944+1.18.2.jar and things worked... but now the pipe cancer seems to be spreading. 

### Expected Result

Game doesn't crash?

### Operating System

windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
fixed in dev, update later today

**Comment by Fade-Alchemist** [comment]
Neat :) Thanks
