### ISSUE TITLE
Chutes cause game crash

### ISSUE THREAD

**Issue by Rosenblack** [Fabricators-of-Create/Create#814]
### Describe the Bug

with the latest update placing a chute just crashes the client, closes any servers to the point they have to be reverted from backup

### Reproduction Steps

1. place chute
2. watch everything die

### Expected Result

to have chutes placed without crashing

### Crash Report or Log

https://pastebin.com/fq303tAv

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
I need the full crash log.

**Comment by Rosenblack** [comment]
after a bit of poking it seems to work fine in a fully vanilla environment so ima try to find the issue myself as well but here, just in case you can do anything about it too
https://mclo.gs/ZdplipX

**Comment by TropheusJ** [comment]
it seems you have porting lib manually installed. This forced the old version to load, so API that Create requires is missing. Remove it and use the built-in version.

**Comment by Rosenblack** [comment]
yeah i noticed that too after testing, i have it for a different mod that didnt embed it, updating to the newest fixes it tho, thanks for the help
