### ISSUE TITLE
Game crash when saw/place fluid tanks

### ISSUE THREAD

**Issue by Kookiejarz** [Fabricators-of-Create/Create#815]
### Describe the Bug

I'm using Create:Above&Beyond modpack on fabric 1.19.2, but when i logged in to my server and saw/place fluid tanks, the game always crash. Server was still operating, only the client crashed.
Run game on macos (arm64)
[crash-2023-02-15_21.38.08-client.txt](https://github.com/Fabricators-of-Create/Create/files/10743628/crash-2023-02-15_21.38.08-client.txt)

### Reproduction Steps

1.Join in the server
2.Saw/place down  fluid tanks
3.Game crash (client side)
...

### Expected Result

I've googled this issue but it seems that nobody have it before.
I really need some help to deal with this situation.
plz~

### Screenshots and Videos

https://user-images.githubusercontent.com/121078488/219046028-b50295d2-0da0-4ab5-ba2f-ebc881bc6804.mov

### Operating System

MacOS Monterey v12.6.1 

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
update Create
