### ISSUE TITLE
Item Duplication from Andesite Funnels+Conveyor Belt

### ISSUE THREAD

**Issue by Devons-Desk** [Fabricators-of-Create/Create#817]
### Describe the Bug

Currently have 2 andesite funnels on a belt hooked up to a Tom's Simple Storage inventory connector. Any item dispensed by the andesite funnel begins to duplicate? Have tried it so far with trapdoors, kelp, and waystones (modded item). Duplication stops if I completely clear the belt, manually right-clicking.

### Reproduction Steps

1.Simple straight kelp belt with andesite funnels on either end.
2.1 funnel is attached to a Tom's Simple Storage inventory connector. 1 funnel is attached to a chest next to a portal storage interface.
3.Place items into the chest that funnels the items onto the belt.

EDIT: Duplication seems to occur upon entering the collection andesite funnel.
...

### Expected Result

Duplicates items until belt is completely cleared manually by right-clicking.

### Screenshots and Videos

![2023-02-18_11 23 59](https://user-images.githubusercontent.com/84694284/219884729-3519a9b3-0f41-4ae2-8a36-b79d58ab2ae1.png)

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

https://pastebin.com/v9HxJgea

**Comment by TropheusJ** [comment]
Can't reproduce. Can I get a video of it happening or a schematic of something that causes it?

**Comment by tancop** [comment]
I have the same issue and made a schematic. 
[funnel_dupe.gz](https://github.com/Fabricators-of-Create/Create/files/10889145/funnel_dupe.gz) (renamed because GH restrictions)
To reproduce just place an item on the conveyor.

**Comment by tancop** [comment]
@TropheusJ I tested this on Forge, no bug there. The issue might be somewhere in `ItemHelper.extract`, for some reason the Forge and Fabric implementations of that method are completely different.

**Comment by TropheusJ** [comment]
Schematic helps a lot, this is a duplicate of #920
