### ISSUE TITLE
ArrayIndexOutOfBoundsException -> Rendering Screen Error -> Indium; AE2; Same Issue?

### ISSUE THREAD

**Issue by suerion** [Fabricators-of-Create/Create#818]
### Describe the Bug

Hey, our Player got again the Rendering Screen Error with Create, i think, it is a problem with the Schematic Table.

But the issue is not on all clients, only on one or two players, but not on my side

AE2 has also the same Issues, could it be, thats a Problem with Sodium and the Fabric Rendering Engine?
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5184
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6928

### Reproduction Steps

1.
2.
3.
...

### Expected Result

Client should not crash

### Crash Report or Log

https://pastebin.com/WaREqhVr

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
could you try installing [this mod](https://modrinth.com/mod/bugjump)? I'm not sure why this bug has suddenly appeared, but I'm 99% sure it's not Create's fault.

**Comment by suerion** [comment]
I will come back to you :)

**Comment by suerion** [comment]
We had tried the Mod, on my side it helps.

**Comment by suerion** [comment]
All other players are says the same. It works normal without rendering crashes
