### ISSUE TITLE
contraption does not turn into blocks

### ISSUE THREAD

**Issue by nothanksimgood** [Fabricators-of-Create/Create#819]
### Describe the Bug

In many ininstances, I've made a contraption and it wont turn into blocks or interact with the bearing it is attached to. /kill doesnt work, and I dont know what to do ;/

### Reproduction Steps

1. make a bearing contraption with another bearing somewhere on the axis the original one is facing, so the blocks on the second bearing will stay in place while being a contraption
2.
3.
...

### Expected Result

It should continue rotate 90˙ and then place again,

### Screenshots and Videos

https://user-images.githubusercontent.com/125825271/219968638-b3c6dac8-95c7-467e-b97e-ee7d42dce9db.mov

### Operating System

MacOS Ventura 13.0

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

oh the biomes youll go, minimap mod

### Additional Context

This is used in a cobblestone farm inspired by TangoTek's.

**Comment by TropheusJ** [comment]
Bearings on contraptions are stabilized and will not rotate with their parent contraption. You can see here that the first bearing rotates and rotates the second one, but the second one keeps its structure level to the ground. 
Just remove the 2nd bearing.
