### ISSUE TITLE
Handles Crash the game

### ISSUE THREAD

**Issue by HiroWu1** [Fabricators-of-Create/Create#82]
### Describe the Bug

By placing handles the game instantly crashes and shuts down

### Reproduction Steps

1.place a handle
2.
3.
...

### Expected Result

Crash

### Operating System

Windows 10

### Mod Version

0.4.0b

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
please give a log file.

**Comment by AeiouEnigma** [comment]
Closing this unless and until any actionable information is provided.
