### ISSUE TITLE
Inconsistent crash on server join.

### ISSUE THREAD

**Issue by ziat007** [Fabricators-of-Create/Create#821]
### Describe the Bug

Inconsistent crash on server join.

### Reproduction Steps

1. Join AQM2 1.4.1 server as me
2. does not seem to happen to friend in the same location. (he does not have goggles)

### Expected Result

60% chance to crash
40% chance to not crash and act completely normal

### Crash Report or Log

https://pastebin.com/jp8Jjf1H

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

https://pastebin.com/jp8Jjf1H

**Comment by CzechHek** [comment]
Seems like a flywheel renderer issue, which you could temporarily solve by disabling it.

Try `/flywheel backend off`

This will, however, decrease your framerate. You could also try different backend mode and see if that helps.

**Comment by ziat007** [comment]
That has stopped the crashing. I have not realized a framerate decrease. I will text other rendering methods.

**Comment by TropheusJ** [comment]
I haven't seen any other reports of this in the last 3 months. closing for now.
