### ISSUE TITLE
Client crashed after use Mechanical Saw and Mechanical Arm, But the server did not crash.

### ISSUE THREAD

**Issue by xiaofan7520** [Fabricators-of-Create/Create#822]
### Describe the Bug

I want to use the Mechanical Saw to output items and then use the Funnel to give them to the Mechanical Arm immediately, but once the items are output, the game will crash immediately, saying that the Mechanical Saw error, and the server didn't crash. It only showed that player was offline normally. If other players close to this Mechanical Saw, their game will also crash.

### Reproduction Steps

1.Place the machine as shown in the screenshot.
2.Drop a log.

### Expected Result

Mechanical Arm will place the output block.

### Screenshots and Videos

![Inked屏幕截图 2023-02-21 213331](https://user-images.githubusercontent.com/91411649/220364189-ff06d183-5827-467e-96fa-7e7eb0690890.jpg)

### Operating System

Client: win7;win10;win11  Server: Ubuntu 22.04.1 LTS

### Mod Version

0.5.0i-08ee655d7

### Minecraft Version

1.19.2

### Other Mods

	- advanced_runtime_resource_pack 0.6.2 via enhancedblockentities
	- architectury 6.4.62
	- armorsoundtweak 6.0.0
	- autofish 0.9.5-SNAPSHOT
	- better_end_sky 0.1.1
	- betterpingdisplay 1.1.1
	- betterthirdperson 1.8.1
	- blur 2.6.0
	- bobby 4.0.1
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- cardinal-components-base 5.0.0-beta.1 via overweight_farming
	- cardinal-components-entity 5.0.0-beta.1 via overweight_farming
	- chat_heads 0.7.1
	- cicada 0.1.1-alpha.1 via showmeyourskin
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.2.88
	- com_electronwill_night-config_core 3.6.5 via armorsoundtweak
	- com_electronwill_night-config_toml 3.6.5 via armorsoundtweak
	- com_github_llamalad7_mixinextras 0.1.1 via porting_lib
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_typesafe_config 1.4.2 via bobby
	- create 0.5.0.i-local+1.19.2
	- create_crystal_clear 1.0+1.19.2
	- createdeco 1.2.12-1.19.2
	- damagetilt 1.19-fabric-0.1.2
	- delightchef 1.0.1-1.19.2
	- detailab 2.6.2+1.19-fabric
	- dripstone_fluid_lib 2.0.1 via milk
	- dynamicsoundfilters 1.3.0+1.19
	- ears 1.4.6
	- effective 1.3
	- elytra_physics 1.1.1
	- enhancedblockentities 0.7.2+1.19.2
	- error_notifier 1.0.9 via roughlyenoughitems
	- fabric-api 0.73.2+1.19.2
	- fabric-api-base 0.4.15+8f4e8eb390 via fabric-api
	- fabric-api-lookup-api-v1 1.6.14+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.1.0+82db024a90 via fabric-api
	- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.24+c6af733c90 via fabric-api
	- fabric-client-tags-api-v1 1.0.5+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.16+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.2.1+413cbbc790 via fabric-api
	- fabric-commands-v0 0.2.33+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.41+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.5.1+7c6cd14d90 via fabric-api
	- fabric-convention-tags-v1 1.2.2+27265b3490 via fabric-api
	- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.3.7+413cbbc790 via fabric-api
	- fabric-dimensions-v1 2.1.35+0d0f210290 via fabric-api
	- fabric-entity-events-v1 1.5.4+9244241690 via fabric-api
	- fabric-events-interaction-v0 0.4.34+562bff6e90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.35+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
	- fabric-item-api-v1 1.6.5+dce4603e90 via fabric-api
	- fabric-item-groups-v0 0.3.38+9244241690 via fabric-api
	- fabric-key-binding-api-v1 1.0.25+5c4fce2890 via fabric-api
	- fabric-keybindings-v0 0.2.23+df3654b390 via fabric-api
	- fabric-lifecycle-events-v1 2.2.4+1b46dc7890 via fabric-api
	- fabric-loot-api-v2 1.1.12+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.15+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.7+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.23+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.21+c6af733c90 via fabric-api
	- fabric-networking-api-v1 1.2.11+10eb22f490 via fabric-api
	- fabric-networking-v0 0.3.28+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.2.1+d8ef690890 via fabric-api
	- fabric-particles-v1 1.0.14+4d0d570390 via fabric-api
	- fabric-recipe-api-v1 1.0.1+413cbbc790 via fabric-api
	- fabric-registry-sync-v0 0.9.32+9244241690 via fabric-api
	- fabric-renderer-api-v1 1.2.1+2e5408b590 via fabric-api
	- fabric-renderer-indigo 0.7.1+2e5408b590 via fabric-api
	- fabric-renderer-registries-v1 3.2.24+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690 via fabric-api
	- fabric-rendering-fluids-v1 3.0.11+4d0d570390 via fabric-api
	- fabric-rendering-v0 1.1.27+df3654b390 via fabric-api
	- fabric-rendering-v1 1.12.1+d8ef690890 via fabric-api
	- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
	- fabric-resource-loader-v0 0.8.3+251d254a90 via fabric-api
	- fabric-screen-api-v1 1.0.32+4d0d570390 via fabric-api
	- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90 via fabric-api
	- fabric-sound-api-v1 1.0.2+c4f28df590 via fabric-api
	- fabric-textures-v0 1.0.24+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.1.6+413cbbc790 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
	- fabricenchantments 0.9.0
	- fabricloader 0.14.11
	- farmersdelight 1.19.2-1.3.9
	- fireoverlaycontroller 1.0+1.18
	- firstperson 2.2.0
	- flywheel 0.6.8.a-4 via create
	- forge_tags 3.0 via porting_lib
	- forgeconfigapiport 4.2.7
	- indium 1.0.9+mc1.19.2
	- io_github_douira_glsl-transformer 1.0.1 via iris
	- io_leangen_geantyref_geantyref 1.3.13 via bobby
	- iris 1.4.3
	- java 19
	- kirin 1.11.1 via presencefootsteps
	- langfiles-plus 1.0.0 via cicada
	- make_bubbles_pop 0.0.2-1.19
	- malilib 0.13.0
	- midnightlib 1.0.0 via overweight_farming
	- milk 1.0.51 via create
	- minecraft 1.19.2
	- mm 2.3 via porting_lib
	- modmenu 4.1.1
	- moonlight 1.19.2-2.2.7
	- nbtcrafting 2.2.3+mc1.19
	- nbttooltip 1.7.0
	- notenoughanimations 1.6.2
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.10.1 via iris
	- org_joml_joml 1.10.4 via sodium
	- org_spongepowered_configurate-core 4.1.2 via bobby
	- org_spongepowered_configurate-hocon 4.1.2 via bobby
	- overweight_farming 1.19.2-2.0.2-fabric
	- paperdoll 1.1.1-mc1.19.1
	- physicsmod 2.10.2
	- playerabilitylib 1.6.0 via overweight_farming
	- porting_lib 2.1.811+1.19.2 via create
	- porting_lib_accessors 2.1.811+1.19.2 via porting_lib
	- porting_lib_attributes 2.1.811+1.19.2 via porting_lib
	- porting_lib_base 2.1.811+1.19.2 via porting_lib
	- porting_lib_common 2.1.811+1.19.2 via porting_lib
	- porting_lib_constants 2.1.811+1.19.2 via porting_lib
	- porting_lib_entity 2.1.811+1.19.2 via porting_lib
	- porting_lib_extensions 2.1.811+1.19.2 via porting_lib
	- porting_lib_fake_players 2.1.811+1.19.2 via porting_lib
	- porting_lib_lazy_registration 2.1.811+1.19.2 via porting_lib
	- porting_lib_model_generators 2.1.811+1.19.2 via porting_lib
	- porting_lib_model_loader 2.1.811+1.19.2 via porting_lib
	- porting_lib_models 2.1.811+1.19.2 via porting_lib
	- porting_lib_networking 2.1.811+1.19.2 via porting_lib
	- porting_lib_obj_loader 2.1.811+1.19.2 via porting_lib
	- porting_lib_transfer 2.1.811+1.19.2 via porting_lib
	- presencefootsteps 1.6.3
	- reach-entity-attributes 2.3.0 via create
	- reeses-sodium-options 1.4.9+mc1.19.2-build.67
	- registrate-fabric 1.1.50-MC1.19.2 via create
	- roughlyenoughitems 9.1.585
	- satin 1.8.0 via blur
	- serialization_hooks 0.3.26 via porting_lib
	- shouldersurfing 2.2.16
	- showmeyourskin 1.3.5+1.19
	- showyourself 1.19-1.1.1
	- sodium 0.4.4+build.18
	- sodium-extra 0.4.14+mc1.19.2-build.80
	- spruceui 4.0.0+1.19 via enhancedblockentities
	- structurized-reborn 1.19-01 via delightchef
	- supplementaries 1.19.2-2.2.50
	- terraform-wood-api-v1 4.2.0 via overweight_farming
	- tweakeroo 0.14.3
	- visuality 0.5.5
	- voicechat 1.19.2-2.3.28
	- waveycapes 1.2.2
	- xaerominimap 22.16.3
	- xaeroworldmap 1.28.4

### Additional Context

The create mod using latest dev build (both of server and client, git-08ee655d7).

**Comment by KLONOA9X6** [comment]
#795 
This issue is not fixed properly.

**Comment by TropheusJ** [comment]
Need the crash log

**Comment by KLONOA9X6** [comment]
> 

https://pastebin.com/cuUKYfNF

**Comment by KLONOA9X6** [comment]
> Need the crash log

https://pastebin.com/cuUKYfNF
