### ISSUE TITLE
Mechanical arm targetting the input of a belt causes mechanical assembly to be skipped.

### ISSUE THREAD

**Issue by bCalabrese** [Fabricators-of-Create/Create#823]
### Describe the Bug

Seeing an issue with mechanical arms, belts, and automated assembly. When the arm is moving items from one depot, to the end of the belt itself, it causes the automated assembly to cancel, and teleports the item to the depot at the end of the belt. The arm is configured.

### Reproduction Steps

1. Set a mechanical arm to target the input of a belt, and a depot the belt is outputting to. I also had it targeting a third depot in my example video, but the arm was set to prioritize the depot the belt output to as input.
2. Setup deployers for automated assembly above the belt.
3. Observe that automated assembly gets stopped while in progress, and the belt item is teleported to the end of the belt.

### Expected Result

The mechanical arm should not interrupt automated assembly.

### Screenshots and Videos

https://user-images.githubusercontent.com/32393772/220464944-4cc5fce4-e499-4a76-be97-bfc8d0b97fb5.mp4

### Operating System

Windows 10

### Mod Version

0.5.0g

### Minecraft Version

1.18.2

### Other Mods

I was running the latest version of the create astral pack. Mods listed below.

ad-astra-1.0.5-1.18.2.jar
adopt-a-floppa-1.1.0.jar
alternate-current-mc1.18-1.4.0.jar
AmbientEnvironment-fabric-1.18.2-7.0+19.jar
another_furniture-fabric-1.2.2-1.18.2.jar
appleskin-fabric-mc1.18.2-2.4.1.jar
appliedenergistics2-fabric-11.7.0.jar
architectury-4.10.88-fabric.jar
astraladditions-1.0.0.jar
autoconfig1u-3.4.0.jar
automobility-0.3+1.18.2.jar
auudio_fabric_1.0.3_MC_1.18-1.18.2.jar
badpackets-fabric-0.1.3.jar
balm-fabric-3.2.1+0.jar
BetterAdvancements-Fabric-1.18.2-0.2.0.146.jar
bettercombat-fabric-1.5.5+1.18.2.jar
campanion-3.0.3.jar
camsbackpacks-2.2.jar
cardinal-components-api-4.2.0.jar
catwalks-inc-1.3.0.jar
cc-restitched-1.100.8.jar
cccbridge-1.3.1-fabric.jar
cem-0.7.1_S8_1.18.jar
Chassis-Fabric-1.1.0.jar
chat_heads-0.6.0-fabric-1.18.1.jar
chipped-fabric-1.18.2-2.0.1.jar
Chunky-1.2.164.jar
CITResewn-1.1.1+1.18.2.jar
cloth-config-6.4.90-fabric.jar
Clumps-fabric-1.18.2-8.0.0+17.jar
cobblegen-v2.1b57-BETA.jar
Companion-1.18.2-fabric-2.0.1.jar
completeconfig-lib-1.4.1.jar
Compressor-Fabric-0.2.0.jar
continuity-2.0.1+1.18.2.jar
cookingforblockheads-fabric-1.18.2-12.2.0.jar
create-fabric-0.5.0g-792+1.18.2.jar
createaddition+1.18.2-fabric-1.18.2-20221218a.jar
createdeco-1.2.9-github-fabric-fork.jar
ctm-fabric-1.0.0+1.18.jar
CullLessLeaves-1.0.1.jar
CustomMachinery-fabric-1.18.2-0.7.5.jar
datapackportals-1.1.1-1.18.jar
debugify-1.11.0-fabric-1.18.2.jar
DisableCustomWorldsAdvice-2.0.jar
disableportals-0.2.0-1.18-github-fork.jar
doodads-0.1.2-github-fork.jar
drinkbeer-3.2.0-1.18.2.jar
drippyloadingscreen_fabric_1.6.6_MC_1.18-1.18.2.jar
dustrial-decor-fabric-0.5.jar
ears-fabric-1.17-1.4.5_01.jar
entityculling-fabric-mc1.18-1.5.1.jar
entity_texture_features_fabric_1.18.2-4.3.1.jar
environmentalcreepers-fabric-1.18.0-1.6.0.jar
ExplorersCompass-1.18.2-2.2.0-fabric.jar
extendedflywheels-1.18.2-0.5.0.g-1.2.5.1.jar
extractinator-fabric-1.18.2-2.0.1.jar
fabric-api-0.67.1+1.18.2.jar
fabric-carpet-1.18.2-1.4.69+v220331.jar
fabric-language-kotlin-1.9.0+kotlin.1.8.0.jar
fallingleaves-1.11.1+1.18.2.jar
fancymenu_fabric_2.13.3_MC_1.18.2.jar
farmers-delight-fabric-1.18.2-1.2.5.jar
fastbench-1.18.1-3.jar
fastfurnace-1.18.2-4.1.jar
Fastload+1.18.2-1.5.10.jar
ferritecore-4.2.1-fabric.jar
fm_audio_extension_fabric_1.1.1_MC_1.18-1.18.2.jar
ForgeConfigAPIPort-v3.2.4-1.18.2-Fabric.jar
ftb-library-fabric-1802.3.9-build.167.jar
ftb-quests-fabric-1802.3.13-build.175.jar
ftb-teams-fabric-1802.2.10-build.96.jar
GearReborn-1.18.2-0.1.14.jar
geckolib-fabric-1.18-3.0.80.jar
global_packs-fabric-1.18.2-1.12.3_fabric.jar
harvestwithease-1.18.2-4.0.0.2-fabric.jar
Hephaestus-1.18.2-3.5.2.150.jar
Iceberg-1.18.2-fabric-1.0.38.jar
idwtialsimmoedm-0.1.1+1.18.jar
immersive_aircraft-0.3.0+1.18.2-fabric.jar
indium-1.0.7+mc1.18.2.jar
InventoryProfilesNext-fabric-1.18.2-1.9.1.jar
iris-flywheel-compat-1.18.2-0.1.7-BETA.jar
iris-mc1.18.2-1.4.2.jar
item-filters-fabric-1802.2.8-build.47.jar
Jade-1.18.2-fabric-5.99.10.jar
JadeAddons-1.18.2-fabric-2.0.1.jar
keymap-0.7.0-beta.1+1.18.2-fabric.jar
konkrete_fabric_1.6.0_MC_1.18-1.18.2.jar
krypton-0.1.9.jar
kubejs-create-fabric-1802.2.2-build.28.jar
kubejs-fabric-1802.5.5-build.567.jar
lazydfu-0.1.2.jar
letmedespawn-1.18.x-1.19.x-fabric-1.0.2.jar
libIPN-fabric-1.18.2-2.0.1.jar
libraryferret-fabric-1.18.2-3.0.0.jar
limitedchunks.fabric-1.18.2-2.5.jar
lithium-fabric-mc1.18.2-0.10.3.jar
loadmyresources_fabric_1.0.4_MC_1.18-1.18.2.jar
lootr-1.18.2-0.3.24.61.jar
mcdw-5.0.4-1.18.jar
memoryleakfix-1.18.2-0.7.0.jar
midnightlib-0.4.4.jar
mixintrace-1.1.1+1.17.jar
modmenu-3.2.5.jar
mysticaloaktree-1.18.2-1.0-fabric.jar
naturalist-fabric-1.1.1-1.18.2.jar
numeralping-1.0.3.jar
packages-fabric-1.18.2-3.4.jar
packed-inventory-0.2.2+1.18.2.jar
passivepiglins-1.0.0.jar
phonos-0.3+1.18.2.jar
Ping-Wheel-1.2.0-fabric-1.18.2.jar
player-animation-lib-fabric-0.4.2+1.18.jar
polaroidcamera-1.2.9.jar
projectiledamage-fabric-2.2.0+1.18.2.jar
puzzle-1.4.1-1.18.jar
PuzzlesLib-v3.3.5-1.18.2-Fabric.jar
quarry-reborn-1.18.2-0.7.3.jar
questsadditions-fabric-1.18.2-1.4.1.jar
reeses_sodium_options-1.4.9+mc1.18.2-build.66.jar
reinforced-chests-2.2.0+1.18.jar
rhino-fabric-1802.2.1-build.255.jar
RoughlyEnoughItems-8.3.588.jar
searchlight-1.18-fabric-1.1.7.jar
servercore-1.2.9-1.18.2.jar
servertick-mc1.18-1.6.jar
ShowMeWhatYouGot-1.18-1.0.1.jar
smoothboot-fabric-1.18.2-1.7.0.jar
smoothchunk-fabric-1.18.2-1.9.jar
sniffer-fabric-1.18.2-1.1.2.jar
sodium-extra-0.4.16+mc1.18.2-build.89.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
spark-1.9.11-fabric.jar
starlight-1.0.2+fabric.89b8d9f.jar
subterrestrial-fabric-1.18.2-2.0.0.jar
suggestion-tweaker-1.18.2-1.3.0-fabric.jar
TechReborn-5.2.1.jar
tooltipfix-1.0.4-1.18.jar
towns_and_towers_fabric-1.10.0.1+1.18.2.jar
trinkets-3.3.1.jar
vinery-1.1.4.jar
WI-Zoom-1.4-MC1.18.2.jar
worldedit-mod-7.2.10.jar
XaerosWorldMap_1.28.9_Fabric_1.18.2.jar
Xaeros_Minimap_23.1.0_Fabric_1.18.2.jar
xlpackets-3.1-1.18.2.jar
youre-in-grave-danger-1.3.13.jar

**Comment by TropheusJ** [comment]
It works for me.
Does it require a specific recipe? Can you get it to happen with Create alone? Not sure what mod would interfere if any.

**Comment by TropheusJ** [comment]
Please try with the latest release

**Comment by TropheusJ** [comment]
Arms will stop their target belt so they can grab items. I've recently fixed several other arm related issues. Everything seems fine for me right now, and this is inactive. I'm going to close this for now.
