### ISSUE TITLE
GL Errors when changing either keybind 

### ISSUE THREAD

**Issue by MissPotato** [Fabricators-of-Create/Create#824]
### Describe the Bug

When unbinding or binding to the listed keys for either `Access Nearby Toolboxes` or `Focus Schematic Overlay` the game will throw a GL Error every tick. No other mods are installed.

You will also get a single GL Error upon viewing either keybind  in the controls screen even with default keybinds.

Unbound: Invalid key -1
Left Mouse: Invalid key 0
Right Mouse: Invalid key 1
Middle Mouse: Invalid key 2
Mouse 4: Invalid Key 3
So on and so forth

After some quick googling, it seems to be that GLFW shares a single key number array used across multiple input method calls. I noticed these tables aligned to the Invalid key error being thrown by Create. Not a skilled coder, so I don't really know how use this information.

https://www.glfw.org/docs/3.3/group__buttons.html
https://www.glfw.org/docs/3.3/group__keys.html

### Reproduction Steps

1. Load a world
2. Go to keybinds menu
3. Click either keybind
4.  Hit escape
5.  Get GL Errors

### Expected Result

To not get GL errors and be able to change these controls

### Crash Report or Log

https://mclo.gs/9gZbMbn

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

fabric-api-0.73.2+1.19.2.jar

**Comment by Atakku** [comment]
Can confirm
