### ISSUE TITLE
Needs an 1.19.2 update

### ISSUE THREAD

**Issue by JayBird0818** [Fabricators-of-Create/Create#828]
### Describe the Suggestion

The mod works well on its own but needs an all around update to be compatible with other modpacks. I use Create with the NewCraft modpack and its no longer compatible with the game version.

**Comment by TropheusJ** [comment]
updated: https://github.com/Fabricators-of-Create/Create/commit/5c6c284cb9630a3e0bc0aacc0a76a055ebdd4443

Seriously though, if you want bugs fixed you need to be specific. I have no idea what NewCraft is or what's wrong with adding Create to it.
