### ISSUE TITLE
Debug Stick doesn't work correctly

### ISSUE THREAD

**Issue by Koguri3108** [Fabricators-of-Create/Create#831]
### Describe the Bug

I am running a fabric based modded Minecraft server on my PC, one mod of which is create.
After adding the create mod the debug stick stopped functioning correctly. Instead of cycling through every property of a block that can be edited, it will now only cycle between a couple of them.
For example, when trying to edit a wall block it will only show me "north", "west" and "waterlogged" but not any of the remaining options, such as "south".
After removing the Create mod, the debug stick started working correctly again.

### Reproduction Steps

1. Give yourself the debug stick via the standard /give command
2. Use the debug stick on a block with multiple block states, such as walls or stairs
3. While cycling through the different block states that the debug stick can edit it becomes clear that some are not available
...

### Expected Result

Expected the Debug Stick to work normally, being able to cycle through every block state of a block that it is able to edit.

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
The debug stick is for debugging, and so it's not implemented the best. It cycles properties when `canAttackBlock` is called.
Porting Lib ends up calling this more than vanilla's once, so some get skipped. I'd like to clean up the bit of code that does this, so hopefully it will be fixed in the future.

**Comment by TropheusJ** [comment]
this will be fixed on 1.20+
