### ISSUE TITLE
Rope pulley crashes the server

### ISSUE THREAD

**Issue by 7z99** [Fabricators-of-Create/Create#833]
### Describe the Bug

The rope pulley seems to be repeatedly crashing my server due to something related to malformed JSON.

### Reproduction Steps

I'm not too sure about how to reproduce the issue but we do have a large rope pulley so I'm thinking it may have something to do with that. I can provide world download as well as mod pack if need be.

### Expected Result

I expect the server not to crash

### Crash Report or Log

https://gist.github.com/7z99/0f12b3d80982fd9da85dc2aba54d1169

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Here's a list of all mods on the server:
amethyst_core-1.0.4+1.19.jar
amethyst_imbuement-1.19-28.jar
another_furniture-fabric-2.1.2-1.19.2.jar
architectury-6.5.69-fabric.jar
balm-fabric-4.5.2+0 (1).jar
bclib-2.1.6.jar
better-end-2.1.4.jar
better-nether-7.1.3.jar
bettervillage-fabric-1.19.2-2.0.0.jar
BOMD-1.4.6-1.19.2.jar
cardinal-components-api-5.0.2.jar
chipped-fabric-1.19.2-2.1.0.jar
cloth-config-8.2.88-fabric.jar
create-fabric-0.5.0.i-961+1.19.2.jar
ctm-fabric-1.0.0+1.19.jar
Decorative Blocks-fabric-1.19.2-3.0.0.jar
DimThread-1.2.7.jar
dragonloot-1.1.2.jar
Dynmap-3.4-fabric-1.19.1.jar
ecologics-fabric-1.19.2-2.1.11.jar
fabric-api-0.73.2+1.19.2.jar
fabric-language-kotlin-1.9.1+kotlin.1.8.10.jar
fabric-tree-chopper-0.8.10.jar
farmers-delight-fabric-1.19.X-1.3.9.jar
fzzy_core-0.1.2+1.19.jar
geckolib-fabric-1.19-3.1.40.jar
icarus-1.13.jar
libraryferret-fabric-1.19.2-3.0.0.jar
lithium-fabric-mc1.19.2-0.10.4.jar
mcda-2.4.3.jar
mcdar-1.5.3-1.19.jar
mcdw-5.0.5-1.19.jar
mcw-doors-1.0.8fabric-mc1.19.2.jar
mcw-fences-1.0.7-mc1.19.2fabric.jar
mcw-paintings-1.0.4fabric-mc1.19.2.jar
mcw-trapdoors-1.0.8-mc1.19.2fabric.jar
mcw-windows-2.1.2-mc1.19.2fabric.jar
memoryleakfix-1.19.1-0.7.0.jar
moonlight-1.19.2-2.2.13-fabric.jar
morevillagers-fabric-1.19-4.0.2.jar
naturalist-fabric-2.1.1-1.19.2.jar
NaturesCompass-1.19.2-2.1.0-fabric.jar
netherportalfix-fabric-1.19-10.0.0.jar
Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.13.jar
owo-lib-0.8.5+1.19.jar
phosphor-fabric-mc1.19.x-0.8.1.jar
PuzzlesLib-v4.3.12-1.19.2-Fabric.jar
resourcefullib-fabric-1.19.2-1.1.22.jar
RoughlyEnoughItems-9.1.591.jar
styled-nicknames-1.1.2+1.19.jar
supplementaries-1.19.2-2.2.50-fabric.jar
TerraBlender-fabric-1.19.2-2.0.1.130.ja
toolleveling-fabric-1.19.2-1.4.1.jar
trade-cycling-fabric-1.19.2-1.0.5.jar
trinkets-3.4.2.jar
twilightforest-fabric-1.19.2-4.2.335.jar
UniversalEnchants-v4.2.15-1.19.2-Fabric.jar
wraith-waystones-3.0.5+mc1.19.2.jar

### Additional Context

I did make a mod dependency override for chipped to not require CTM so that may or may not be related.

Also we pay for a server so it's possible that OS on the server is different. Can get it if needed. Also can provide the full log instead of just the crashlog if needed.

**Comment by TropheusJ** [comment]
closing in favor of #892
