### ISSUE TITLE
not working when trying to launch sodium + origins 1.19.2

### ISSUE THREAD

**Issue by Artyx1** [Fabricators-of-Create/Create#834]
### Describe the Bug

when i try to launch create with sodium and origins it crashes

### Reproduction Steps

1. install fabric 1.19.2
2. install sodium fabric 1.19.2 0.4.4, create fabric 0.5.0 1.19.2 and origins 1.19.2 0.4.4
3. launch minecraft
...

### Expected Result

i expected it to launch and run normally

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/107992891/223494982-f75fdae3-e314-434f-ad94-0459b811ca2e.png)

### Operating System

windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

fabric api 0.73.2+1.19.2

### Additional Context

none

**Comment by ZestyBlaze** [comment]
Can you produce a full crash log? Upload it to a pastebin and then give the link here

**Comment by Artyx1** [comment]
@ZestyBlaze https://pastebin.com/jCgb8sG0

**Comment by TropheusJ** [comment]
Update Create and install Indium
