### ISSUE TITLE
Pipes place Modern Industrialization Steam

### ISSUE THREAD

**Issue by cplir-c** [Fabricators-of-Create/Create#837]
### Describe the Bug

Modern Industrialization (MI) adds steam as a fluid and does not let players place it as a block. Create pipes will place a `modern_industrialization:steam` block when pumping to an open block space.
The steam block looks and collides like a barrier block, but breaks in one hit in survival mode, like grass.

### Reproduction Steps

1. Put water and fuel in an MI boiler.
2. Pump steam out of the boiler to an open block space.
3. Create places a steam block.

### Expected Result

I expected either no block to be placed, or for a steam block that flows upward and deals fire damage to appear. Because MI doesn't allow players to place steam, Create should not place steam either.

### Operating System

Arch Linux

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Sodium, Sodium Extra, More Culling, Modern Industrialization, and many more that should be less relevant.

**Comment by TropheusJ** [comment]
I have reported this to MI, best solution would be on their end

**Comment by James103** [comment]
Per https://github.com/AztechMC/Modern-Industrialization/issues/493#issuecomment-1555955392:

> @TropheusJ you should check for `instanceof FlowingFluid`, see `BucketItem#emptyContents`.
