### ISSUE TITLE
Instant crash on startup with sodium

### ISSUE THREAD

**Issue by badgermemelord** [Fabricators-of-Create/Create#84]
### Describe the Bug

Latest build instantly crashes on startup when sodium is installed (previously it would only happen when placing/breaking create blocks)
(0.4c)

### Reproduction Steps

1. Install latest create build + sodium
2. Start
3. Crash
...

### Expected Result

No crash

### Crash Report or Log

https://pastebin.com/qVAfaafe

### Operating System

Windows 10

### Mod Version

0.4.0b

### Minecraft Version

1.18.1

### Other Mods

Sodium

**Comment by AeiouEnigma** [comment]
Should be fixed in the latest build
