### ISSUE TITLE
pipe and smart pipe texture bugs 1.19.2 (fabric)

### ISSUE THREAD

**Issue by Yuiro14** [Fabricators-of-Create/Create#840]
### Describe the Bug

The pipe and smart pipe textures are missing the ends of their textures and looks like a copper cube.
I may just be using an older version.
I will try to upgrade and see if it changes.

thank you I really love to mod!

### Reproduction Steps

1.Place a pipe
2.
3.
...

### Expected Result

For it to look normal

### Screenshots and Videos

<img width="1440" alt="Screenshot 2023-03-12 at 22 59 27" src="https://user-images.githubusercontent.com/112819671/224598953-f7f878c3-7cb4-4b99-a108-712f7a96fe2d.png">

### Operating System

MacOS ventura

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
install indium and update Create
