### ISSUE TITLE
Duplicating copper by using a deployer to wax it

### ISSUE THREAD

**Issue by Halex000** [Fabricators-of-Create/Create#843]
### Describe the Bug

When you use a deployer to wax a cut copper block with a honey comb block, it results in a block of copper, which can then be turned into 4 blocks of cut copper, allowing you to repeat the process infinitely. This bug exists because this recipe says it accepts any c:copper_blocks ingame; this is odd because the recipe json does not use a tag.

### Reproduction Steps

1. Use a deployer to wax a cut copper block with a honey comb block to make a waxed block of copper
2. Place the waxed copper block in the world and use an axe to remove the wax
3. Mine the block of copper and collect it
4. Use a stonecutter to turn the block of copper into 4 cut copper blocks
5. Repeat step 1, or turn the blocks of copper into ingots

### Expected Result

Using a deployer to wax a cut copper block should result in a waxed cut copper block.

### Screenshots and Videos

![Capture](https://user-images.githubusercontent.com/95841600/225127361-83bdd667-d738-477f-be52-7e9076c9148f.PNG)
![Capture](https://user-images.githubusercontent.com/95841600/225128710-83c6010f-5404-4ed9-89a8-0b67848555d9.PNG)

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
Correct for me. You might have a broken mod or datapack adding it.
![image](https://user-images.githubusercontent.com/60247969/230226289-0e72cbec-6f78-4d03-91cf-c905988b1174.png)
