### ISSUE TITLE
Pondering Fluid Pipe can cause crash

### ISSUE THREAD

**Issue by WastelandOasis** [Fabricators-of-Create/Create#853]
### Describe the Bug

Crash occures when pondering fluid pipe on page 2 section 4.

Edit: Further testing revealed this will occure without JEI as well

### Reproduction Steps

1.Ponder Fluid Piipe
2. wait or jump to page two section four
3. profit
...

### Expected Result

Expected ponder to work as intended and not crash.

### Crash Report or Log

https://pastebin.com/86np3yfh

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Only Create

**Comment by TropheusJ** [comment]
Please try with the latest release

**Comment by JustinHuPrime** [comment]
I can confirm this still happens with Create Fabric 1.19.2 v0.5.0.i Patch 4

**Comment by TropheusJ** [comment]
The problematic code has changed significantly, and I have never been able to reproduce this. Considering this fixed for now.
