### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.model.generators.ModelFile

### ISSUE THREAD

**Issue by ereese99** [Fabricators-of-Create/Create#854]
Seems like there's some missing files in the latest build.
9/10 times won't launch, 1/10 times it will but idk why it will sometimes and won't sometimes?
[crash-2023-03-22_14.11.06-client.txt](https://github.com/Fabricators-of-Create/Create/files/11043430/crash-2023-03-22_14.11.06-client.txt)

**Comment by ZestyBlaze** [comment]
I'd check Create Crafts and Additions, make sure you haven't accidently installed the Forge version, seems to be a crash related to that not Create

**Comment by ereese99** [comment]
Turns out Create (not the additions version) just isn't fully ready for Fabric 0.14.17, cuz it works perfectly on 0.14.16.

**Comment by Sunconure11** [comment]
Noticing this issue on Quilt too.

**Comment by TropheusJ** [comment]
duplicate of #845
