### ISSUE TITLE
Crash with FTB Chunks when deployer uses bucket

### ISSUE THREAD

**Issue by nanakisan** [Fabricators-of-Create/Create#855]
### Describe the Bug

Server owner recently installed FTB Chunks. When they attempted to make a claim on the server it crashed and continued to crash. This crash and the one reported here https://github.com/Fabricators-of-Create/Create/issues/850 seem to be related albeit different reasons. Appears to be centered on contraptions.

Crash log
https://pastebin.com/8GrLKK80

### Reproduction Steps

Install FTB Chunks
Crash

### Expected Result

Server to not crash

### Crash Report or Log

https://pastebin.com/8GrLKK80

### Operating System

Linux (amd64) version 5.4.0-121-generic

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

		ae2: Applied Energistics 2 12.9.2
			team_reborn_energy: Energy 2.0.0-beta1
		another_furniture: Another Furniture 2.1.2-1.19.2
		architectury: Architectury 6.5.69
		badpackets: Bad Packets 0.2.1
		balm-fabric: Balm 4.5.2+0
		bedrockwaters: BedrockWaters 1.7.3+1.19.2
		bitsandchisels: BitsAndChisels 2.7.0
			stacc: Stacc 1.3.4
		botania: Botania 1.19.2-438-FABRIC
			fiber: fiber 0.23.0-2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		command-block-ide: Command Block IDE 0.3.3
		convenient-mobgriefing: Convenient mobGriefing 2.0.2
		convenientdecor: Convenient Decor 0.1.0
		crawl: Crawl 0.11.1
			mm: Manningham Mills 2.3
		create: Create 0.5.0.i-961+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forgeconfigapiport: Forge Config API Port 4.2.9
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.1.784+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_accessors: Porting Lib Accessors 2.1.784+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.784+1.19.2
				porting_lib_base: Porting Lib Base 2.1.784+1.19.2
				porting_lib_common: Porting Lib Common 2.1.784+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.784+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.784+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.784+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.784+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.784+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.784+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.784+1.19.2
				porting_lib_models: Porting Lib Models 2.1.784+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.784+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.784+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.784+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			registrate-fabric: Registrate for Fabric 1.1.50-MC1.19.2
		extended_drawers: Extended Drawers 1.3.7+mc.1.19.2
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
			graphlib: Graph Lib 0.3.6+1.19.2
			mconfig: Mconfig 1.2.0+mc.1.19-rc1
				de_poiu_apron_apron: apron 2.1.1
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.2+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.15
		ftbchunks: FTB Chunks 1902.3.18-build.248
		ftblibrary: FTB Library 1902.3.15-build.188
		ftbteams: FTB Teams 1902.2.12-build.95
		image2map: Image2Map 0.3.0
			map-canvas-api: Map Canvas API 0.2.0+1.19.1
			sgui: sgui 1.1.5+1.19.1
		immersive_paintings: Immersive Paintings 0.5.1+1.19.2
		immersive_portals: Immersive Portals 2.3.1
			imm_ptl_core: Immersive Portals Core 2.3.1
			q_misc_util: QMiscUtil 2.3.1
		invview: InvView 1.4.9-1.19+
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		linkedstorage: Linked Storage 1.5.1-1.19
		lithium: Lithium 0.11.0
		megacells: MEGA Cells 2.0.0-beta.6-1.19.2
		minecraft: Minecraft 1.19.2
		minelib: mine11lib 0.1.3+1.19
			com_sksamuel_scrimage_scrimage-core: scrimage-core 4.0.31
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		patchouli: Patchouli 1.19.2-77-FABRIC
		pehkui: Pehkui 3.7.0+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		pfm: Paladin's Furniture 1.1.1
		phosphor: Phosphor 0.8.1
		reinfbarrel: Reinforced Barrels 2.3.0+1.19
		reinfchest: Reinforced Chests 2.2.0+1.19
		reinfshulker: Reinforced Shulker Boxes 2.2.0+1.19
			reinfcore: Reinforced Core 3.0.3+1.19
		roughlyenoughitems: Roughly Enough Items 9.1.591
			error_notifier: Error Notifier 1.0.9
		serversleep_mr: ServerSleep 1-datapack
		sit: Sit 1.19-20
		trinkets: Trinkets 3.4.2
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
		wands: Building Wands 2.6.5_beta
		waystones: Waystones 11.1.0
		woof: Woof 3.0.0-1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			owo: oωo 0.8.2+1.19
				blue_endless_jankson: jankson 1.2.1
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		worldedit_items: WorldEdit Items 1.2.1
		wthit: wthit 5.14.0
		xercapaint: Joy of Painting fabric-1.19.2-1.0.1
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2

**Comment by TropheusJ** [comment]
Tracked it down. FTB Chunks has a broken event listener [here](https://github.com/FTBTeam/FTB-Chunks/blob/1.18/main/common/src/main/java/dev/ftb/mods/ftbchunks/FTBChunks.java#L325).
This makes the empty/fill action return a null ItemStack, which should NEVER happen.

**Comment by TropheusJ** [comment]
has been fixed
