### ISSUE TITLE
[API Request] Make all types public

### ISSUE THREAD

**Issue by Phoupraw** [Fabricators-of-Create/Create#858]
### Describe the Suggestion

Make all classes and interfaces public. Because mixin can't do anything if the target type is not public, and access widener can't widen mod's classes and interfaces. So there is no way to access those types and related methods and fields.
- `com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.State`
- `com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.Mode`

**Comment by TropheusJ** [comment]
must be done on Forge first
