### ISSUE TITLE
DashLoader causing issues with gear model

### ISSUE THREAD

**Issue by Dr-WeiAL** [Fabricators-of-Create/Create#86]
### Describe the Bug

Problems with gear and tool models when both DashLoader and Create are installed

### Reproduction Steps

1.Install Create and DashLoader
2.place gear/take out items
3.There was a problem

### Expected Result

Return the model of the gear to normal

### Screenshots and Videos

![1](https://user-images.githubusercontent.com/47446553/149133310-4dd5404e-87a4-486d-b283-64a6a131908c.gif)

### Operating System

windows10

### Mod Version

0.4c

### Minecraft Version

1.18.1

### Other Mods

DashLoader

**Comment by Dr-WeiAL** [comment]
After testing it was found to have the same problem when installed with sodium
But sodium will only cause the gear model to go wrong, not the item model

**Comment by Dr-WeiAL** [comment]
Seems like more than that, they also seem to cause the textures of the item vault and fluid tank to not connect

**Comment by Dr-WeiAL** [comment]
All right, all the above problems have been solved after I installed indium

**Comment by Dr-WeiAL** [comment]
No, dashloader will also cause this problem, but the sodium problem has been solved

**Comment by Dr-WeiAL** [comment]
![image](https://user-images.githubusercontent.com/47446553/149949364-287208bc-6818-4823-b547-7bdd6ff2b636.png)

**Comment by PepperCode1** [comment]
This is no longer an issue with the latest DashLoader releases.
