### ISSUE TITLE
Crashing in Ponder Screen with Lithium installed

### ISSUE THREAD

**Issue by Ninjawolf0007** [Fabricators-of-Create/Create#860]
### Describe the Bug

When pondering some items in game, mainly the Chute, but happens with other blocks too, the game screen will freeze and the game will exit to desktop without any errors.

### Reproduction Steps

1. Install Better Minecraft [Fabric] mod pack version 16.5
2. Install Create [Fabric] version 0.5.0i Patch 2 for Minecraft version 1.19.2
3. Install Create: Extended Cogwheels [Fabric] version 0.5.0i
4. Run the game
5. Ponder various items
6. Crash (only occurs while in the Ponder UI)

### Expected Result

The game should not crash while pondering items.

### Crash Report or Log

https://pastebin.com/LaaBJTnC   https://pastebin.com/iNJYwNCc

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Better Minecraft [Fabric] mod pack (Version 16.5)
Create: Extended Cogwheels Fabric (Version 0.5.0.i-fabric)

**Comment by TropheusJ** [comment]
update Lithium
