### ISSUE TITLE
server crash error info "Exception occurred in netty pipeline"

### ISSUE THREAD

**Issue by galaxy-eye** [Fabricators-of-Create/Create#861]
### Describe the Bug

I try fabric loader.0.14.15~0.14.18 with create 0.5.0i-1.19.2, they alway crash after a few hours. Even I did not login the world.

### Reproduction Steps

1.start a server with create
2.wait a few hours
3.server crash

### Expected Result

server can always running.

### Crash Report or Log

https://github.com/galaxy-eye/log/blob/main/create-server-crash

### Operating System

win10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

in log

**Comment by TropheusJ** [comment]
the error spam in this is weird, but does not cause a crash. I need the actual crash report when the server crashes.

**Comment by galaxy-eye** [comment]
> the error spam in this is weird, but does not cause a crash. I need the actual crash report when the server crashes.

Yeap, server is still running, but I can not login the server with my client. The only way is restart the server.
I think it is caused by create. I also try forge version and this did not happen.
If you have time, you can try start a fabric server with create. In fabric loader 0.14.18 this may happen in a few minute.

**Comment by galaxy-eye** [comment]
> the error spam in this is weird, but does not cause a crash. I need the actual crash report when the server crashes.

The log in the server that is all. If you need the login failed log in the client, I will upload later.

**Comment by TropheusJ** [comment]
it works fine with Create alone. Client log might be useful.

**Comment by galaxy-eye** [comment]
here is the client log
https://github.com/galaxy-eye/log/blob/main/client-log

**Comment by TropheusJ** [comment]
Try installing this on the client: https://modrinth.com/mod/bugjump

**Comment by galaxy-eye** [comment]
I try some times again and found that this error doesn't matter.

**Comment by galaxy-eye** [comment]
I try some times again and found that this error doesn't matter.
