### ISSUE TITLE
Duplication glitch - deployer

### ISSUE THREAD

**Issue by Zer0Yield** [Fabricators-of-Create/Create#862]
Seeing this in AOF6:

Using a contraption that lays down *anything* (saplings, diamond blocks, etc.) just infinitely lays down said item even if none are supplied to the contraption

To recreate - set up a contraption and put 1 item into deployer. Activate contraption and deployer will continue to place held object, never depleting supply.

**Comment by TropheusJ** [comment]
works fine for me on fresh AOF6

**Comment by Zer0Yield** [comment]
This is possibly only a bug within FTB chunkloaded chunks (been trying to narrow things down)

**Comment by TropheusJ** [comment]
closing in favor of #876
