### ISSUE TITLE
Travelers Backpack / Create compat

### ISSUE THREAD

**Issue by schmensch** [Fabricators-of-Create/Create#863]
### Describe the Bug

When wearing a Backpack from the Traveler's Backpack mod (https://modrinth.com/mod/travelersbackpack) and backpackDeathPlace is set to true in the Traveler's Backpack config, when you die by being impaled by a moving drill, the backpack isn't placed on death but instead completely disappears.

### Reproduction Steps

1. Create a moving drill (e. g. with a sticky create piston, a creative motor and a drill)
2. Get a backpack and wear it (right click with the backpack, then click the arrow in the lower left of the menu. Confirm that you are wearing it by pressing B. It should open the backpack menu)
3. Get yourself to low health
4. Die by being impaled by the moving drill
5. The backpack isn't placed where it's supposed to be

### Expected Result

The backpack should be placed near the drill, or drop as an item if there's no space for it to be placed.

### Operating System

Arch Linux / Rocky Linux

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by schmensch** [comment]
I guess this is because create structures prohibit blocks from being placed in them, but aren't blocks themselves. This means that travelers backpacks thinks it can place the block there, but actually can't, leading to the loss of the backpack.

**Comment by TropheusJ** [comment]
Contraptions don’t stop block placing. The drill probably broke the backpack.

**Comment by schmensch** [comment]
Might also be the case. I added a chest on top of the drill the backpack didn't appear in it.

**Comment by TropheusJ** [comment]
tested, pretty sure the drill broke the backpack. When not broken by a player, the backpack doesn't drop. I'd say that's an oversight on their part, not Create's fault.
