### ISSUE TITLE
[Suggestion] Sync 1.18 c tags to 1.19 for Create Fabric.

### ISSUE THREAD

**Issue by EvanHsieh0415** [Fabricators-of-Create/Create#864]
### Describe the Suggestion

Create Fabric 1.19 is missing many tags from 1.18.

https://github.com/Fabricators-of-Create/Create/tree/mc1.18/fabric/dev/src/generated/resources/data/c/tags
->
https://github.com/Fabricators-of-Create/Create/tree/mc1.19/fabric/dev/src/generated/resources/data/c/tags

**Comment by TropheusJ** [comment]
all the tags are still there. the format changed.

**Comment by EvanHsieh0415** [comment]
> all the tags are still there. the format changed.

c tag doesn't

**Comment by TropheusJ** [comment]
All those tags are c tags. I don't understand what you mean.

**Comment by EvanHsieh0415** [comment]
missing `c:nuggets/...` `c:ingots/...`

**Comment by TropheusJ** [comment]
`c:x_nuggets`
