### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Sunconure11** [Fabricators-of-Create/Create#865]
### Describe the Bug

When I try to boot up Minecraft with this mod, I crash.

### Reproduction Steps

1. Start up minecraft
2. ???
3. Crash
...

### Expected Result

Game to boot up.

### Crash Report or Log

https://pastebin.com/NQL8uh6s

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Additional Context

Also affects addons

**Comment by TropheusJ** [comment]
`NoClassDefFoundError: Could not initialize class com.simibubi.create.Create`
Your computer may be haunted.
Try reinstalling Create? I really don't know, there's no info here. Try it alone too. If it works then, some mod is doing something really bad.

**Comment by Sunconure11** [comment]
I will investigate this when I fix an unrelated error

**Comment by TropheusJ** [comment]
maybe try the latest release

**Comment by Sunconure11** [comment]
I'll test within the next few days. I have found the cause of the serious bug I was having.

**Comment by Sunconure11** [comment]
Issue no longer appears to be present.
