### ISSUE TITLE
Crash with Water Walking Fix when assembling contraption

### ISSUE THREAD

**Issue by jitterdev** [Fabricators-of-Create/Create#866]
### Describe the Bug

you crash when you put a shulker box on a train or go near a train w/ a shulker box

### Reproduction Steps

1. make a train
2. put shulker box on train
3. crash

### Expected Result

train/shulker box doesnt cause a crash

### Screenshots and Videos

[crash log 1 (singleplayer)](https://github.com/Fabricators-of-Create/Create/files/11124297/message.2.txt)
[crash log 2 (multiplayer?)](https://github.com/Fabricators-of-Create/Create/files/11124298/message.1.txt)
[crash log 3 (multiplayer?](https://github.com/Fabricators-of-Create/Create/files/11124299/message.txt)

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

see the crash reports, its a pretty long list

### Additional Context

happens in singleplayer and multiplayer
ive tried to replace the `small_bogey` with air using fill, it did manage to fill the block with air supposedly, but it still crashes when you go near the area.
killing the train entity thing didnt seem to do anything

originally i thought raknetify was the issue but because this still happens on singleplayer i think its something else thats of cause. also removing raknetify on the client doesnt fix the issue

**Comment by jitterdev** [comment]
apparently it only crashes if you put a shulker box on the train, i misunderstood someones explanation of the issue

**Comment by TropheusJ** [comment]
This is a difficult issue. Kinda an incompatibility with Water Walking Fix, but it's not their fault.
When a contraption is assembled, the collision of blocks is combined into the contraption hitbox.
Normally, this all works fine. With Water Walking Fix, getting the collision involves an extra check for the fluid state.
This extra check will crash on contraptions. That vanilla code expects a LevelChunk, but a VirtualChunk is provided.

**Comment by IThundxr** [comment]
Fixed by https://github.com/MerchantPug/water-walking-fix/commit/9e1235d21b32866e2d40499c3f3e1799fdf83168
