### ISSUE TITLE
Funnels cannot be placed inside Placards

### ISSUE THREAD

**Issue by Nataly171** [Fabricators-of-Create/Create#867]
### Describe the Bug

Right-Clicking a Placard with an Andesite Funnel or Brass Funnel in hand will attempt to place the Funnel as a block onto the Placard, instead of inserting it as an item.

### Reproduction Steps

1. Place a Placard
2. Right Click the Placard with an Andesite Funnel or a Brass Funnel

### Expected Result

The Funnel should be placed inside the Placard as an item.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/109003930/229211586-36e593f3-6a4c-4234-be55-507d54ce8bb6.png)

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by IThundxr** [comment]
Upstream issue: https://github.com/Creators-of-Create/Create/issues/6086

**Comment by JordanL2** [comment]
> Upstream issue: [Creators-of-Create#6086](https://github.com/Creators-of-Create/Create/issues/6086)

Sorry for confusion, that was my bug ticket but I was using Create Fabric and didn't realise it has a separate big tracker. 

Unless someone reproduces this issue in Forge, this ticket should be re-opened.

**Comment by IThundxr** [comment]
It can be reproduced on forge and has been marked as a upstream issue correctly.
