### ISSUE TITLE
Items used in Sequenced Assembly recipes don't count as ingredients when using EMI

### ISSUE THREAD

**Issue by Nataly171** [Fabricators-of-Create/Create#868]
### Describe the Bug

Any item apart from the initial input item that is used in a Sequenced Assembly recipe doesn't count as an ingredient when using EMI. This means the recipes won't show when looking at the items' uses, and also the batch costs are inaccurate.

### Reproduction Steps

1. Load Create and EMI
2. Press "U" on a small Cogwheel
3. Note that the Sequenced Assembly tab is absent

4. Look at the recipe for Train Tracks
5. Press the Crafting Tree button
6. Note that the cost is simply displayed as one Sleeper and doesn't include the Nuggets

### Expected Result

The items used in Sequenced Assembly recipes, such as the Nuggets in Train Tracks and the Cogwheels in Precision Mechanisms should be treated as ingredients of their respective recipes.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/109003930/229314460-ba1d99cb-b1d0-46ae-82db-3218d2c6c213.png)

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
just fixed this on 1.18 + full chanced support. Will be merged to 1.19 and released eventually.
