### ISSUE TITLE
recipe sequenz shows invalid as item 

### ISSUE THREAD

**Issue by knopfklock338** [Fabricators-of-Create/Create#869]
### Describe the Bug

As i tried looking at the recipe for a precise mechanism , it showed the third step in the deployer was empty (or so i thought) . After a few minutes i found out that it should show iron nuggets ,but it didnt it showed as "invalid". 
(ps: english isnt my first language and i am sorry for spelling mistakes)

### Reproduction Steps

1. use create (and just enough items in the fabric modpack 
2. use jei to look at the precise mecheanism recipe 
3.try recreating the recipe and realize that it doesnt work 
4. ask friends if their recipe is the same 

### Expected Result

 I thought that the third step was empty ,and there were only 2 steps i needed to repeat 5 times .

### Screenshots and Videos

![Screenshot (28)](https://user-images.githubusercontent.com/129644037/229333171-6853d585-4b6c-44aa-b2e5-63030607a893.png)

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

[modlist.zip](https://github.com/Fabricators-of-Create/Create/files/11131202/modlist.zip)

**Comment by TropheusJ** [comment]
I need your full log from .minecraft/logs/latest.log.

**Comment by mike89732** [comment]
und was kann man dagegen machen?

**Comment by mike89732** [comment]
hab das gleiche problem

**Comment by TropheusJ** [comment]
this is a bug with Extended Cogwheels
