### ISSUE TITLE
Content Observer cause furnace stopped blasting

### ISSUE THREAD

**Issue by 1a2s3d4f1** [Fabricators-of-Create/Create#87]
### Describe the Bug

The furnace stop blasting when I put Content Observer at side of the furnace.
Smoker and Blast Furnace stop blasting , but it still using fuel.

### Reproduction Steps

1.Put a furnace(Blast Furnace or Somker).
2.Put Content Observer neared furnace.
3.Furnace stop blasting.
...

### Expected Result

Furnace can blasting.

### Screenshots and Videos

https://user-images.githubusercontent.com/40121560/149175312-51d91c26-e35c-4593-ba05-06bca98aee6e.mp4

### Operating System

Windows 7

### Mod Version

0.4.0b

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
[FAPI issue](https://github.com/FabricMC/fabric/issues/1972)
