### ISSUE TITLE
Milk bottle broken recipe.

### ISSUE THREAD

**Issue by MAGGen-hub** [Fabricators-of-Create/Create#873]
### Describe the Bug

Farmers Delight milk filling/emptying recipe broken (need to replace 27000 (1/3) to 20250(1/4))
If you use bucket of milk with 4 bottles in FarmersDelight you will get 4 bottles of milk.
But `create:basin` can be filled with 3 bottles (and emptied with 1 bucket) -> 1 free bottle of milk appeared from nowere...

### Reproduction Steps

1. Place `create:basin`
2. Get 1 bucket of milk
3. Turn it into 4 bottles of milk using Farmers Delight recipe
4. Fill `create:basin` with milk bottles
5. Take milk from `create:basin` with bucket

### Expected Result

We have 1 bucket of milk and 1 bottle of milk...
 Infinite milk "logic breaking" bug.

### Operating System

Arch Linux

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Farmers Delight

### Additional Context

Fixed recipes:
Filling:
```
{
  "type": "create:filling",
  "replace": true,
  "fabric:load_conditions": [
    {
      "condition": "fabric:all_mods_loaded",
      "values": [
        "farmersdelight"
      ]
    }
  ],
  "ingredients": [
    {
      "item": "minecraft:glass_bottle"
    },
    {
      "amount": 20250,
      "fluidTag": "c:milk"
    }
  ],
  "results": [
    {
      "item": "farmersdelight:milk_bottle"
    }
  ]
}
```
Emptying:
```
{
  "type": "create:emptying",
  "replace": true,
  "fabric:load_conditions": [
    {
      "condition": "fabric:all_mods_loaded",
      "values": [
        "farmersdelight"
      ]
    }
  ],
  "ingredients": [
    {
      "item": "farmersdelight:milk_bottle"
    }
  ],
  "results": [
    {
      "item": "minecraft:glass_bottle"
    },
    {
      "amount": 20250,
      "fluid": "milk:still_milk"
    }
  ]
}
```

**Comment by TropheusJ** [comment]
1 bucket is 3 bottles. Farmers delight is broken.

**Comment by TropheusJ** [comment]
Oh, this is with the compat recipes.

**Comment by TropheusJ** [comment]
Okay, I see what you mean. I was right at first, farmers delight *is* broken. One bucket = 3 bottles is standard on fabric. Their recipes should be changed to take/give 3 bottles.
