### ISSUE TITLE
Items dropping onto belts from chutes causes processing to be skipped

### ISSUE THREAD

**Issue by Chippit** [Fabricators-of-Create/Create#874]
### Describe the Bug

When feeding items onto belts in certain configurations using chutes, items will move down the belt and skip their assembly line processing steps.

### Reproduction Steps

1. Reproduce the contraption shown. [This schematic](https://github.com/Fabricators-of-Create/Create/files/11142711/chute_processing.nbt.zip) represents it exactly, if using the schematic is easier.
    - The motor is set to 128 RPM, but it seems to reproduce at any combination of speeds, even if the press is driven at a different speed from the belt
    -  Items dispense one at a time from chutes and funnels for ease of demonstration, but it works on all stack sizes (the schematic does not seem to save the smart chute's setting of 1, incidentally - this may be another bug)
2. Unpower the left lever powering the funnel. Watch the items entering the barrel. They will all be sheets, as expected.
3. Power the left lever and unpower the right. Watch the items entering the barrel. They will all be ingots.
    - Unpowering the right lever might cause the final stack already on the belt to be processed correctly, depending on the timing.

### Expected Result

All assembly line processing works at all times.

### Screenshots and Videos

![2023-04-03_23 28 12](https://user-images.githubusercontent.com/870779/229633034-0c902463-d178-47bf-9371-d075312f3662.png)

### Operating System

Windows 10 (server running on BSD)

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

### Additional Context

I have encountered similar behaviour with mechanical arms as well, but the reproduction of that issue was inconsistent in my setups. I see that is now logged as #823.

This one I describe here reproduces consistently, but may be related to the other one.

It also reproduces in both single player and on servers.

**Comment by TropheusJ** [comment]
Thanks for the good report! Hoping this fix fixes some other similar issues.

**Comment by Chippit** [comment]
Glad to see the fix was not too complex!
