### ISSUE TITLE
Crashing World at startup

### ISSUE THREAD

**Issue by Metry45tacos1** [Fabricators-of-Create/Create#875]
### Describe the Bug

Extracting water, using hose reel. Broke the attached tank by accident and now the world crashes my game. Can't get back into the world to remove anything or change it.  Im using a creative motor to power it as i wanted to test it before i ran the actual power units.

### Reproduction Steps

1. Hose reel above the source ( mine was infinite )
2. Attach proper attachments such as the mechanical pump and liquid tanks
3. Remove Tanks with wrench. 
...

### Expected Result

Nothing.. I expected the hose reel to stop or hold its liquid.

### Crash Report or Log

https://pastebin.com/JrFcKXaR

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

[🔨 Frame API](https://www.curseforge.com/minecraft/mc-mods/frame-api)
[Additional Additions | Fabric](https://www.curseforge.com/minecraft/mc-mods/additional-additions)
[AOF Emotes](https://www.curseforge.com/minecraft/mc-mods/aof-emotes)
[AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Archeology Mod](https://www.curseforge.com/minecraft/mc-mods/archeology)
[Architectury API (Fabric/Forge)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Artifacts (Fabric)](https://www.curseforge.com/minecraft/mc-mods/artifacts-fabric)
[Auto Config Updated API](https://www.curseforge.com/minecraft/mc-mods/auto-config-updated-api)
[BadStdOut](https://www.curseforge.com/minecraft/mc-mods/badstdout)
[BCLib](https://www.curseforge.com/minecraft/mc-mods/bclib)
[Better Advancements](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[Better Compatibility Checker](https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker)
[Better Lily Pads](https://www.curseforge.com/minecraft/mc-mods/better-lily-pads)
[Better Sodium Video Settings Button](https://www.curseforge.com/minecraft/mc-mods/better-sodium-video-settings-button)
[Better Villages - Fabric](https://www.curseforge.com/minecraft/mc-mods/better-village-fabric)
[BetterEnd](https://www.curseforge.com/minecraft/mc-mods/betterend)
[BetterNether](https://www.curseforge.com/minecraft/mc-mods/betternether)
[Bits And Chisels](https://www.curseforge.com/minecraft/mc-mods/bits-and-chisels)
[Bookshelf](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Bookshelf](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Bridging Mod (Quark/Bedrock) [Fabric/Quilt]](https://www.curseforge.com/minecraft/mc-mods/bridging-mod)
[Capybara [Fabric]](https://www.curseforge.com/minecraft/mc-mods/capybara-fabric)
[Cardinal Components](https://www.curseforge.com/minecraft/mc-mods/cardinal-components)
[Charm](https://www.curseforge.com/minecraft/mc-mods/charm) 
[Chassis](https://www.curseforge.com/minecraft/mc-mods/chassis)
[Chunky (Fabric)](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator)
[Cloth Config API](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Cloth Config API (UNUSED)](https://www.curseforge.com/minecraft/mc-mods/cloth-config-legacy)
[Clumps](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Coins JE](https://www.curseforge.com/minecraft/mc-mods/coins-je)
[Collective](https://www.curseforge.com/minecraft/mc-mods/collective)
[Collector's Album [Fabric | Forge]](https://www.curseforge.com/minecraft/mc-mods/collectors-album)
[Compressor (Fabric)](https://www.curseforge.com/minecraft/mc-mods/compressor)
[Configuration [Fabric | Forge]](https://www.curseforge.com/minecraft/mc-mods/configuration)
[Construction Deco](https://www.curseforge.com/minecraft/mc-mods/construction-site-deco)
[Continuity](https://www.curseforge.com/minecraft/mc-mods/continuity)
[Controlling](https://www.curseforge.com/minecraft/mc-mods/controlling)
[CraftTweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
[Create Crafts & Additions](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Create Fabric](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
[CreativeCore](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Custom Splash Screen](https://www.curseforge.com/minecraft/mc-mods/custom-splash-screen)
[Customizable Elytra (Fabric)](https://www.curseforge.com/minecraft/mc-mods/customizable-elytra-fabric)
[Data Attributes](https://www.curseforge.com/minecraft/mc-mods/data-attributes)
[Deeper and Darker](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)
[Default Dark Mode](https://www.curseforge.com/minecraft/texture-packs/default-dark-mode)
[Detail Armor Bar [Fabric]](https://www.curseforge.com/minecraft/mc-mods/detail-armor-bar)
[Display Case](https://www.curseforge.com/minecraft/mc-mods/displaycase)
[Doodads [Fabric]](https://www.curseforge.com/minecraft/mc-mods/doodads-fabric)
[Duckling](https://www.curseforge.com/minecraft/mc-mods/duckling)
[Emotecraft (Fabric)](https://www.curseforge.com/minecraft/mc-mods/emotecraft)
[Enchantment Descriptions](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Entity Culling Fabric/Forge](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Fabric Language Kotlin](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Fabric Waystones](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones)
[Farmer's Delight [Fabric]](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[Farmer's Respite (Fabric)](https://www.curseforge.com/minecraft/mc-mods/farmers-respite-fabric)
[Faux Custom Entity Data](https://www.curseforge.com/minecraft/mc-mods/faux-custom-entity-data)
[Forge Config API Port [Fabric]](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[GeckoLib](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Harvest with ease](https://www.curseforge.com/minecraft/mc-mods/harvest-with-ease)
[Iceberg [Fabric]](https://www.curseforge.com/minecraft/mc-mods/iceberg-fabric)
[Immersive Aircraft [Fabric/Forge]](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[Indium](https://www.curseforge.com/minecraft/mc-mods/indium)
[Infinity Buttons](https://www.curseforge.com/minecraft/mc-mods/infinity-buttons)
[Ingredient Extension API](https://www.curseforge.com/minecraft/mc-mods/ingredient-extension-api)
[Iris Shaders](https://www.curseforge.com/minecraft/mc-mods/irisshaders)
[Item Highlighter [Fabric]](https://www.curseforge.com/minecraft/mc-mods/item-highlighter-fabric)
[ItemLocks](https://www.curseforge.com/minecraft/mc-mods/itemlocks)
[Jade 🔍](https://www.curseforge.com/minecraft/mc-mods/jade)
[Joy of Painting](https://www.curseforge.com/minecraft/mc-mods/joy-of-painting)
[Just Enough Farmer's Recipes](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-jei-plugin)
[Just Enough Items (JEI)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Just Enough Professions (JEP)](https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep)
[Just Enough Resources (JER)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs)
[Let Me Despawn](https://www.curseforge.com/minecraft/mc-mods/let-me-despawn)
[Library Ferret - Fabric](https://www.curseforge.com/minecraft/mc-mods/library-ferret-fabric)
[Light Overlay (Rift/Forge/Fabric)](https://www.curseforge.com/minecraft/mc-mods/light-overlay)
[Litematica](https://www.curseforge.com/minecraft/mc-mods/litematica)
[Lithium (Fabric)](https://www.curseforge.com/minecraft/mc-mods/lithium)
[Logical Zoom](https://www.curseforge.com/minecraft/mc-mods/logical-zoom)
[Lootr (Fabric)](https://www.curseforge.com/minecraft/mc-mods/lootr-fabric)
[Macaw's Bridges](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Macaw's Doors](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Macaw's Fences and Walls](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Macaw's Lights and Lamps](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
[Macaw's Paintings](https://www.curseforge.com/minecraft/mc-mods/macaws-paintings)
[Macaw's Paths and Pavings](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[Macaw's Roofs](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs)
[Macaw's Trapdoors](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Macaw's Windows](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[Magnum Torch](https://www.curseforge.com/minecraft/mc-mods/magnum-torch-forge)
[MaLiLib](https://www.curseforge.com/minecraft/mc-mods/malilib)
[MegaParrot](https://www.curseforge.com/minecraft/mc-mods/megaparrot)
[Mining Gadgets Fabric](https://www.curseforge.com/minecraft/mc-mods/mining-gadgets-fabric)
[Mob Scarecrows](https://www.curseforge.com/minecraft/mc-mods/mob-scarecrows)
[Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu)
[Moonlight Lib](https://www.curseforge.com/minecraft/mc-mods/selene)
[Mouse Tweaks](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Music Maker Mod](https://www.curseforge.com/minecraft/mc-mods/music-maker-mod)
[Naturalist](https://www.curseforge.com/minecraft/mc-mods/naturalist)
[Nature's Compass](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Night Lights](https://www.curseforge.com/minecraft/mc-mods/nightlights)
[No Chat Reports](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports)
[oωo (owo-lib)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
[Patchouli (Fabric/Quilt)](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
[Pehkui](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[PlayerEx](https://www.curseforge.com/minecraft/mc-mods/playerex)
[Plushie Mod](https://www.curseforge.com/minecraft/mc-mods/plushie-mod)
[Polymorph (Fabric)](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric)
[Puzzles Lib [Forge & Fabric]](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Reese's Sodium Options](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)
[Replay Mod (Fabric)](https://www.curseforge.com/minecraft/mc-mods/replay-mod-fabric-and-forge)
[Revelationary](https://www.curseforge.com/minecraft/mc-mods/revelationary)
[Rhino](https://www.curseforge.com/minecraft/mc-mods/rhino)
[Shoppy](https://www.curseforge.com/minecraft/mc-mods/shoppy)
[Show Me What You Got](https://www.curseforge.com/minecraft/mc-mods/show-me-what-you-got)
[Show Me Your Skin!](https://www.curseforge.com/minecraft/mc-mods/show-me-your-skin)
[Shuffle](https://www.curseforge.com/minecraft/mc-mods/shuffle)
[Simple Voice Chat](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Simply Swords [Fabric & Forge]](https://www.curseforge.com/minecraft/mc-mods/simply-swords)
[SkyLib](https://www.curseforge.com/minecraft/mc-mods/skylib)
[Smooth Boot (Fabric)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot)
[Snowy Spirit](https://www.curseforge.com/minecraft/mc-mods/snowy-spirit)
[Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium)
[spark](https://www.curseforge.com/minecraft/mc-mods/spark)
[Spectrum](https://www.curseforge.com/minecraft/mc-mods/spectrum)
[Starlight (Fabric)](https://www.curseforge.com/minecraft/mc-mods/starlight)
[Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[TerraBlender (Fabric)](https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric)
[Terralith](https://www.curseforge.com/minecraft/mc-mods/terralith)
[The Mushroom Update - AnimalMace Edition](https://www.curseforge.com/minecraft/mc-mods/the-mushroom-update-animalmace-edition)
[The Twilight Forest](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Tom's Simple Storage Mod (Fabric)](https://www.curseforge.com/minecraft/mc-mods/toms-storage-fabric)
[Trade Cycling](https://www.curseforge.com/minecraft/mc-mods/trade-cycling)
[Traveler's Backpack [Fabric]](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric)
[Tree Harvester](https://www.curseforge.com/minecraft/mc-mods/tree-harvester)
[Trinkets (Fabric)](https://www.curseforge.com/minecraft/mc-mods/trinkets)
[Twigs](https://www.curseforge.com/minecraft/mc-mods/twigs)
[VanillaTweaks [Fabric & Forge]](https://www.curseforge.com/minecraft/mc-mods/vanillatweaks)
[Vein Mining (Fabric 1.16.4 - 1.19.2)](https://www.curseforge.com/minecraft/mc-mods/vein-mining-fabric)
[Vertical Slabs Compat](https://www.curseforge.com/minecraft/mc-mods/vertical-slabs-compat)
[Visual Workbench](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[When Dungeons Arise - Fabric!](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise-fabric)
[Xaero's Minimap](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Xaero's World Map](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[YetAnotherConfigLib](https://www.curseforge.com/minecraft/mc-mods/yacl)
[You're in Grave Danger](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)

**Comment by TropheusJ** [comment]
Are you able to get it to happen again in other worlds?

**Comment by Metry45tacos1** [comment]
No, I think it was a chunk error. I went through NBTeditor and removed the
hose pulley and it was fine.

**Comment by eingruenesbeb** [comment]
@TropheusJ 
Hey, I was able to recreate the issue. I've prepared a little test setup in form of [this region file](https://github.com/Fabricators-of-Create/Create/files/11300804/r.3.0.mca.zip). I should also note, that the world was created and played on in conjunction with the [Create Live 4](https://www.curseforge.com/minecraft/modpacks/create-live_4) modpack.

Here are the steps involved with recreating the bug:
1. Create a new world in singleplayer.
2. Exit the world, go back to singleplayer, select the world, click `Edit` and then `Open World Folder`.
3. Paste [the region file](https://github.com/Fabricators-of-Create/Create/files/11300804/r.3.0.mca.zip) into the world's `regions` folder.
4. Teleport to the setup with `/tp 1703 106 472`
5. Pull the lever on the Clutch and watch everything (quite literally) descend into chaos, once the Hose Pulley is deep enough.

The resulting crash-report should look roughly like [this one](https://bytebin.lucko.me/QSCgo6fi6U).

I hope this helps ^^

**Comment by eingruenesbeb** [comment]
Another odd behavior, I've noticed, is, that disabling infinite fluid sources for the Hose Pulley results in the fluid no longer being pumped, once a certain depth is reached.

**Comment by Greeenman999** [comment]
I have analyzed the problem further... When using @eingruenesbeb region file, the whole "water pool" was flowing. Because of that, the whole queue list gets emptied and therefore the first object is null. I have inserted an if statement in the while true loop to prevent the npe...
```diff
if (visited.size() > maxBlocks && canDrainInfinitely(fluid) && !queue.isEmpty()) {
	infinite = true;
	// Find first block with valid fluid
	while (true) {
+++		if(queue.isEmpty()) {
+++			infinite = false;
+++			return;
+++		}
		BlockPos first = queue.first().pos();
		if (canPullFluidsFrom(world.getBlockState(first), first) != FluidBlockType.SOURCE) {
			dequeue(queue);
			continue;
		}
		break;
	}
	BlockPos firstValid = queue.first().pos();
	frontier.clear();
	visited.clear();
	queue.clear();
	queue.add(new BlockPosEntry(firstValid, 0));
	tileEntity.sendData();
	return;
}
```
I don't know much about the rest of the code of the create mod so maybe you also need to call tileEntity.sendData() etc. @TropheusJ 
When using this fix everything seems to work, but i didnt check performance etc.

Thank you!

**Comment by TropheusJ** [comment]
This is a forge issue too: https://github.com/Creators-of-Create/Create/issues/4665
I've added your fix for now, it seems to work fine.
