### ISSUE TITLE
Fail to Initializing game 0.4c

### ISSUE THREAD

**Issue by Noplace0** [Fabricators-of-Create/Create#88]
### Describe the Bug

---- Minecraft Crash Report ----
// This doesn't make any sense!

The latest build instantly crashes on startup when sodium is installed 
(0.4c)

### Reproduction Steps

1. Open the game
2. Crash
3. Log
...

### Expected Result

start and be able to run the game

### Crash Report or Log

https://gist.github.com/Noplace0/bf4825cb795bfabac47a0df895f9b45b

### Operating System

Win 10

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

Sodium

**Comment by AeiouEnigma** [comment]
It's a known, high priority issue. We'll fix it soon :)

**Comment by RedWideWeb** [comment]
> It's a known, high priority issue. We'll fix it soon :)

Please make an announcement once it's fixed. Thank you for your amazing work!

**Comment by RedWideWeb** [comment]
Partially fixed in builds 343 and 344. Still crashes occasionally but it works now. World launches, belts and entities are rendered properly. Even Shaders are partially working. Great job, @AeiouEnigma

**Comment by AeiouEnigma** [comment]
The problem at hand was fixed, though other sodium and iris-related issues remain to be resolved. Closing this.
