### ISSUE TITLE
Undocumented change - Encased shafts and chain drives can no longer be strongly powered

### ISSUE THREAD

**Issue by Chippit** [Fabricators-of-Create/Create#880]
### Describe the Bug

In Create 0,5.0g, it was possible to strongly power encased shafts, chain drives, adjustable gearshifts (and probably other similar items like encased gears). In 0.5.0i (in patch 3 at least), this is no longer possible.

This change was not documented in either the Fabric or Forge side, so I expect this might have been unintentional?

### Reproduction Steps

1. Attempt to strongly power encased shafts

### Expected Result

Encased Shafts and other similar blocks, like Andesite Casings, can be strongly powered

### Screenshots and Videos

![2023-04-06_21 40 48](https://user-images.githubusercontent.com/870779/230478517-9b369eec-d736-43a4-bbb0-178404c34be4.png)

### Operating System

Windows 10 (server running on BSD)

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
This was intentional and fixed parity with forge
