### ISSUE TITLE
Crash on start-up 1.19.2

### ISSUE THREAD

**Issue by pokesmells** [Fabricators-of-Create/Create#881]
### Describe the Bug

When updating to the latest version, it collides with **Twilight Forest** twilightforest-fabric-1.19.2-4.2.335

It crashes on start-up promptly.

MC Version - 1.19.2
Fabric Version - 0.14.19

### Reproduction Steps

1. Update the mod to **create-fabric-0.5.0.i-989+1.19.2**
2. Have the latest Twilight Forest - **twilightforest-fabric-1.19.2-4.2.335** installed as well.
3. Crash on start-up
...

### Expected Result

To not crash, suspect it has something to do with **Porting Lib** as seen in the mixin stack trace.

### Crash Report or Log

https://mclo.gs/2Xwblw9

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Twilight Forest.. etc crash log should list.

**Comment by Sewdohe** [comment]
Same issue, still getting it on the latest version

**Comment by TropheusJ** [comment]
need your log

**Comment by Sewdohe** [comment]
Okay found the issue - when installing SOME mod (idk what) curseforge puts porting lib into the mods folder and that causes the issue.

Delete porting lib mod and everything is good!
