### ISSUE TITLE
Unconnected pipes and structures.

### ISSUE THREAD

**Issue by MAGGen-hub** [Fabricators-of-Create/Create#885]
### Describe the Bug

Well... Pipes were not connected to sides of spout(other blocks)... I mean they work but looks weird...

### Reproduction Steps

1. Place pipe
2. Place fluid dispancer near it (at the same height)

### Expected Result

Pain in eyes

### Screenshots and Videos

![2023-04-08_15 36 10](https://user-images.githubusercontent.com/56871670/230721391-03c22333-edc0-48f5-ba4a-c398d45dc86f.png)

### Operating System

Arch Linux

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Tested with and without sodium/indium/ctm/continuty - same result

**Comment by TropheusJ** [comment]
Not a bug

**Comment by MAGGen-hub** [comment]
> Not a bug

Wait! How can I fix it? On forge pipe textures/models works normal in 1.16.5, but not work on fabric 1.19.2!
Why it's not supported on fabric and when it will be supported? Beta-1.5?
Please, any info?

**Comment by TropheusJ** [comment]
I don’t understand what you mean. There is no bug in your screenshot, and it looks the same as forge.

**Comment by MAGGen-hub** [comment]
> I don’t understand what you mean. There is no bug in your screenshot, and it looks the same as forge.

Okey. Other screenshot: 
![image](https://user-images.githubusercontent.com/56871670/230743490-1165c9d6-1351-4e04-b63f-f08ebe6f741c.png)
On this pic you can see that pipe model "merged" into fluid tank.
![image](https://user-images.githubusercontent.com/56871670/230743618-4298ca08-dfa3-4829-b393-50f14e111d96.png)

BUT:
![2023-04-09_00 38 11](https://user-images.githubusercontent.com/56871670/230743538-f6b7a6f1-7698-4c10-9f73-09d147323cc3.png)
![2023-04-09_00 38 18](https://user-images.githubusercontent.com/56871670/230743545-b2fce352-6db7-44f2-a0e7-9342c6cdb320.png)

On these two pics pipe have no model conection to fluid tank. It's not rendered for some reason.

**Comment by MAGGen-hub** [comment]
Air gape bettwen spout and pipe. That what I talked about. It's a rendering bug.
![2023-04-09_00 41 27](https://user-images.githubusercontent.com/56871670/230743703-885133ba-4dcb-457d-b4dc-e07009407da8.png)

**Comment by MAGGen-hub** [comment]
Forge version:
![2023-04-09_00 57 10](https://user-images.githubusercontent.com/56871670/230744339-c62d0fc0-e677-4347-9ef0-169a46dc7571.png)

**Comment by TropheusJ** [comment]
I never noticed that exists actually. Thanks for clarifying.

**Comment by MAGGen-hub** [comment]
> I never noticed that exists actually. Thanks for clarifying.

Thank you for reopening the issue. The pipe has spesial connection models with: fluid tanks/spouts/basins/drains/some-things-from-other-mods.

Need to say that supplementaries mod for fabric 1.19.2 has the same issue with faucets: in forge they easily connect to `supplementaries:jar` and things from other mods (`create:basins` for ex.) but in fabric it not work...

I think both of these bugs have the same causes...
