### ISSUE TITLE
Create mod train door causes a lot of lag

### ISSUE THREAD

**Issue by V43-Cirmos** [Fabricators-of-Create/Create#886]
### Describe the Bug

Hey! I build trains that have a lot of doors (about 25 with a full model train). When the train starts/stops it causes a lot of lag.

### Reproduction Steps

Build a train, that has a minimum of 20 or 30 doors

### Expected Result

A way to turn off train door animation or turning off automatic closing/opening

### Operating System

Windows 11

### Mod Version

0.5.0g

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
duplicate of #847
