### ISSUE TITLE
Train Conductors do not navigate to alternate stations that are preceded inline by 2 other stations

### ISSUE THREAD

**Issue by Chippit** [Fabricators-of-Create/Create#887]
### Describe the Bug

Given a train network with two other possible destinations that are unreachable, and a third that is reachable but preceded inline by two other stations, trains will not navigate to the reachable station.

### Reproduction Steps

1. Load the world [attached](https://github.com/Fabricators-of-Create/Create/files/11189374/TrainTest.zip)
2. Press the button on the green wool.
    a. The train will navigate to the first available station
3. Pull the left-most lever on the yellow wool (closing the route to the first station). 
4. Wait for the train to return to its original station then press the button on the green wool again to dispatch the train.
    a. The train will navigate to the second station.
5. Pull the second lever on the yellow wool, keeping the first on as well. This closes the routes to both the first two stations. 
6. Wait for the train to return to its original station, then press the button on the green wool to dispatch the train.
7. The train will wait at the chain signal indefinitely instead of proceeding down the available path.

### Expected Result

The train proceeds to the third station.

### Screenshots and Videos

![2023-04-10_11 10 24](https://user-images.githubusercontent.com/870779/230873047-a23c0227-5ab3-4fe6-9fa5-cc7019b6e21e.png)
![2023-04-10_11 10 38](https://user-images.githubusercontent.com/870779/230873062-6ff71982-450e-4fc3-bac9-d8d1e37a3dcd.png)

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

None

### Additional Context

- Removing any one of the two inline dummy stations on the third track (right-most stations on red wool) will allow the train to continue.
- Removing the first target station (blue wool) also allows the train to continue. Removing the second does not.
- If you manually drive the train onto the third track, and then resume the automatic navigation, the train will proceed to the third station.

**Comment by TropheusJ** [comment]
behaves the same on Forge

**Comment by Chippit** [comment]
Should I open the issue on the Forge side as well, or is tracking it here sufficient?

**Comment by TropheusJ** [comment]
you should if there isn't one there already

**Comment by TropheusJ** [comment]
should be fixed in newer versions
