### ISSUE TITLE
Portable Storage Interface with hopper underneath gets stuck in extraction mode

### ISSUE THREAD

**Issue by Munchy907** [Fabricators-of-Create/Create#888]
### Describe the Bug

When you put a hopper underneath a Portable Storage Interface, when a wind mill that is being used for a tree farm and so rotating. When they connect, it will extract the items that the farm has collected but even when there is no items it will stay trying to extract items

### Reproduction Steps

I'm terrible at describing so just see the video demonstrating how to reproduce it 

### Expected Result

For it to extract the items then once done the farm would go on about its business 

### Screenshots and Videos

https://youtu.be/1hP9unn2hv4

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.18.2

**Comment by TropheusJ** [comment]
This is only an issue on 1.18 with hoppers, and would be very difficult to fix. Either update or use a chute.
