### ISSUE TITLE
Specific RPM in drills breaks cobblestone generators

### ISSUE THREAD

**Issue by EzequielDM** [Fabricators-of-Create/Create#889]
### Describe the Bug

Whenever you set a drill to mine a cobblestone generator at ~64RPM it breaks and a cobblestone block is instantly generated instead of stone after a delay.
Setting it to >48RPM or >80RPM fixes it.

### Reproduction Steps

1. Use the same setup as below, using waterlogged drills.
2. Set drills to 64RPM
3. That's it

### Expected Result

Stone should be generated and there should be a small delay between the block being broken and the next block being generated.
Currently it generates a cobblestone instantly after the block is broken and depending on speed it generates it in a pattern of stone (normal) > cobblestone (abnormal) > repeat

### Screenshots and Videos

The setup being used:
![Setup](https://i.imgur.com/T1nEcO2.png)
![Speed](https://i.imgur.com/Q1YGa1o.png)

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Modpack: Create Optimized [Fabric]

[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Roughly Enough Professions (REP) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-professions-rep)
[Iris Shaders (by coderbot)](https://www.curseforge.com/minecraft/mc-mods/irisshaders)
[Mod Menu (by Prospector)](https://www.curseforge.com/minecraft/mc-mods/modmenu)
[Roughly Enough Loot Tables (by GrigLog)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-loot-tables)
[Roughly Enough Resources (by theorbagain)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-resources)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Tom's Simple Storage Mod (Fabric) (by tom54541)](https://www.curseforge.com/minecraft/mc-mods/toms-storage-fabric)
[ServerCore (by Wesley8081)](https://www.curseforge.com/minecraft/mc-mods/servercore)
[MemoryLeakFix (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Debugify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/debugify)
[Fabric Waystones (by LordDeatHunter)](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones)
[FerriteCore (Fabric) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric)
[BCLib (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/bclib)
[FTB Teams (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric)
[Starlight (Fabric) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight)
[Sodium Extra (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/sodium-extra)
[YetAnotherConfigLib (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/yacl)
[BetterNether (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betternether)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Ingredient Extension API (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/ingredient-extension-api)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Inventory Sorting (by Kyrptonaught)](https://www.curseforge.com/minecraft/mc-mods/inventory-sorting)
[Farmer's Knives [Fabric] (by ianm1647)](https://www.curseforge.com/minecraft/mc-mods/farmers-knives)
[Zoomify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/zoomify)
[Terralith (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
[Vanilla Hammers (by Draylar1)](https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers)
[Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Dark Loading Screen (by Neecko5b84)](https://www.curseforge.com/minecraft/mc-mods/dark-loading-screen)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Smoke Suppression (by supersaiyansubtlety)](https://www.curseforge.com/minecraft/mc-mods/smoke-suppression)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Reese's Sodium Options (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)
[Origins (Fabric) (by Apace100)](https://www.curseforge.com/minecraft/mc-mods/origins)
[Dynamic FPS (by juliand665)](https://www.curseforge.com/minecraft/mc-mods/dynamic-fps)
[Patchouli (Fabric/Quilt) (by williewillus)](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
[TerraBlender (Fabric) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric)
[FTB Library (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[FTB Ultimine (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-fabric)
[Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[DeepslateCutting (by NoComment1105)](https://www.curseforge.com/minecraft/mc-mods/deepslatecutting)
[Lithium (Fabric) (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/lithium)
[Extra Thicc Packets (by JaselUmena)](https://www.curseforge.com/minecraft/mc-mods/extra-thicc-packets)
[Expanded Storage (by Ellemss)](https://www.curseforge.com/minecraft/mc-mods/expanded-storage)
[Rhino (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/rhino)
[FTB Chunks (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-fabric)
[oωo (owo-lib) (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
[FallingTree (Forge&Fabric) (by rakambda)](https://www.curseforge.com/minecraft/mc-mods/falling-tree)
[Cull Leaves (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/cull-leaves)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[WTHIT (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Falling Leaves (Fabric) (by RandomMcSomethin)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric)
[BetterEnd (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betterend)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[FastAnim (by AViewFromTheTop)](https://www.curseforge.com/minecraft/mc-mods/fastanim)
[You're in Grave Danger (by b1n_ry)](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)
[Sodium (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/sodium)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[LazyDFU (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/lazydfu)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[Roughly Enough Items Fabric/Forge (REI) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
[Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
[Create Fabric (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
[Krypton (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/krypton)
[Expanded Delight [Fabric] (by ianm1647)](https://www.curseforge.com/minecraft/mc-mods/expanded-delight)
[Building Wands (by nicguzzo)](https://www.curseforge.com/minecraft/mc-mods/building-wands)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)

**Comment by KeithTsao** [comment]
seems caused by vanilla minecraft...when breaking stone costs between 25ticks and 30ticks, the lava falls before the water flows.
