### ISSUE TITLE
Two items with an identical recipe and only one can be produced

### ISSUE THREAD

**Issue by IWantSomeThings** [Fabricators-of-Create/Create#890]
### Describe the Bug

If you set up a fan and a soul fire to convert Stone to Netherrack, it will always convert to Infested stone, because both recipes are identical. That leads to the problem that you can't create Netherrack with this specific recipe.

### Reproduction Steps

1. Place an Encased Fan before a Soul Fire and get the Fan working, so that the particles are going through the soul fire and at least two blocks further.
2. Throw stone in the area behind the soul fire but still in the particle flow.
3. The stone should convert to Infested stone after a few seconds

### Expected Result

The stone is always converting to Infested stone, but never to Netherrack. If you look in the recipe list, the recipes for Infested stone and Netherrack including a fan and a soul fire are the same but with different outcomes.

### Screenshots and Videos

![2023-04-15_20 04 37](https://user-images.githubusercontent.com/130861491/232246165-77caa738-484b-4c26-baf0-67a94ce36622.png)
![2023-04-15_20 04 42](https://user-images.githubusercontent.com/130861491/232246162-64183bb1-58c7-44f8-802c-453087451f6c.png)

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Modpack: Create Live 4

**Comment by TropheusJ** [comment]
Stone to netherrack is not a recipe added by Create
