### ISSUE TITLE
Ticking Entity crash when pushing a contraption containing a lectern with an unsigned book in it

### ISSUE THREAD

**Issue by Game-Log** [Fabricators-of-Create/Create#892]
### Describe the Bug

The crash occurs as soon as the contraption stops moving. If there is an unsigned book within a lectern that is part of a contraption, and said contraption is pushed via a mechanical piston, then the game will constantly crash, and the world will refuse to reload.

### Reproduction Steps

1. Make a contraption that contains a lectern. (Like a simple elevator held together with glue)
2. Move the new contraption with a mechanical piston
3. Once the piston reaches the end of it's length, the game crashes when it tries to set the contraption to its new location

4. If you try to reload the world, it crashes at startup, softlocking the world.

### Expected Result

The contraption is supposed to behave as it would normally. (example: an elevator would move up and down without any crashes.)

### Crash Report or Log

https://pastebin.com/hH8MVdZt

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
happens on forge too: https://github.com/Creators-of-Create/Create/issues/3032

**Comment by TropheusJ** [comment]
Issues that occur on Forge as well are no longer being tracked on this repo. Please follow the respective issue on the Forge repo instead: https://github.com/Creators-of-Create/Create/issues/3032

**Comment by Shoes4Clues** [comment]
Despite this being fixed on Forge, this is still an issue on Fabric.
