### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by GalaxyBlueFlame** [Fabricators-of-Create/Create#896]
### Describe the Bug

This happens when you run a betterx mod with create I didn't know that until I went to betterx for help once I got there they told me that i can report that to Create dev team, probably this is just a small mistake in one library mixin

### Reproduction Steps

1.run a betterx mod(example better end) with create mod
2.
3.
...

### Expected Result

Crash on startup

### Screenshots and Videos

![Screenshot_20230422_032647](https://user-images.githubusercontent.com/80208643/233752767-0e7ec7b5-79f6-4615-9fd1-0dde90dd5be4.jpg)

### Crash Report or Log

https://pastebin.com/54ycYCcq

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
incompatibility with simple planes. it’s abandoned and we can’t fix  it.
