### ISSUE TITLE
Minecart Coupling disappeared when player save world

### ISSUE THREAD

**Issue by 1a2s3d4f1** [Fabricators-of-Create/Create#90]
### Describe the Bug

Minecart Coupling lose texture when I go to the nether. It disappeared when I save and quit world.

### Reproduction Steps

Lost texture:
1.Use Minecart Coupling to link minecart.
2. Go to the nether.
3. back to the overworld.

Lost coupling:
1.Use Minecart Coupling to link minecart
2.Save world.
3.Load world.
...

### Expected Result

Minecart Coupling not disappear while save world.

### Screenshots and Videos

https://user-images.githubusercontent.com/40121560/149625875-d5dce9dd-bdb6-4f1f-91af-88b43843dfb5.mp4

https://user-images.githubusercontent.com/40121560/149625985-dc45281a-3481-434d-8a70-94daff0f1431.mp4

### Operating System

Windows 7

### Mod Version

0.4.0b

### Minecraft Version

1.18.1

**Comment by TropheusJ** [comment]
This is mostly fixed, remaining issue is covered by #104
