### ISSUE TITLE
Soul sand washing recipe results don't match the recipe from REI.

### ISSUE THREAD

**Issue by liad-inon** [Fabricators-of-Create/Create#902]
### Describe the Bug

The results of the recipe according to REI the chance to get 1 gold nugget and the chance to get 4 quarts is 12%, but in reality the result closer to 2% for 1 gold nugget.

### Reproduction Steps

Wash a large amount of soul sand and compare to the expected result.

### Expected Result

Right representation of the recipe in REI.

### Screenshots and Videos

My result of washing a double chest of soul sand:
![2023-04-29_14 26 53](https://user-images.githubusercontent.com/52380897/235300142-647c4cda-943f-4ef7-b5a8-aa26c7853f65.png)

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by supersaiyansubtlety** [comment]
Here's a workaround datapack that makes it output gold 12% of the time like it says in REI.
[soul_sand_washing_gold_fix.zip](https://github.com/Fabricators-of-Create/Create/files/11369838/soul_sand_washing_gold_fix.zip)

**Comment by TropheusJ** [comment]
REI is wrong, not the recipe.

**Comment by supersaiyansubtlety** [comment]
This is also affecting the iron output of gravel washing. The recipe json says 0.125 but REI says 25%.

Is REI just using the chance of the first output for all outputs in washing recipes?

**Comment by TropheusJ** [comment]
should be fixed by #1342
