### ISSUE TITLE
Destroying tracks opens ponder window

### ISSUE THREAD

**Issue by SerenModz21** [Fabricators-of-Create/Create#904]
### Describe the Bug

Whilst destroying train tracks and picking them up, Create keeps opening the ponder screen for train tracks. This occurs whilst running or walking whilst destroying them. This issue has been happening to most, if not all of our users.

I believe it's occurring W is being pressed and Create is thinking that we want to ponder the tracks, however, that is only my guess.

Update: after watching back the video below, I noticed that Jade was displaying the ponder progress bar.. I'm not sure if Jade is causing the ponder or if it is just passing along the progress bar from Create. However, not all our users have Jade and it occurs to them also.

Our server is running Minecraft 1.19.2 with Fabric Loader 0.14.12.

Create version: `0.5.0.i-961`
Fabric API version: `0.76.0`
Jade version: `8.7.3`
JadeAddons version: `3.1.0`

### Reproduction Steps

1. Place down a lot of tracks
2. Walk or run forward whilst destroying them
3. Ponder window is displayed

### Expected Result

Tracks should be destroyed and pickup, without the ponder window.

### Screenshots and Videos

https://user-images.githubusercontent.com/41450647/235388351-ac689c62-9e30-4bcc-a095-472b6a57fb6d.mp4

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by Cart3r1234** [comment]
I've seen this bug before - when using a mod that shows the block/item you are looking at (WAILA, WTHIH, Jade, etc), you can activate ponder by holding W to walk forward while you are looking at an item entity.

**Comment by SerenModz21** [comment]
> I've seen this bug before - when using a mod that shows the block/item you are looking at (WAILA, WTHIH, Jade, etc), you can activate ponder by holding W to walk forward while you are looking at an item entity.

Thank you for your reply! So would this bug be something to report to Jade, or is reporting it here the correct place?

**Comment by Cart3r1234** [comment]
After leaving my reply I noticed that in your report you mentioned

> However, not all our users have Jade and it occurs to them also.

Before reporting it to Jade, check to make sure that it doesn't happen without it, because I might be wrong in that its something caused by those mods.  It may just be something that happens when you look at an item that can be pondered, but Jade and other similar mods make the cause more visible by showing the ponder progress bar.  

Also check to see if it happens on the Forge version of create.  If it does, you'll want to report it to the forge repository (or see if there's already a report for it) instead of this one, assuming it isn't caused by the item/block viewer mods.

**Comment by SerenModz21** [comment]
> However, not all our users have Jade and it occurs to them also.

My apologies. In this part, the user that also had this issue thought they didn't have Jade. However, after checking, they in fact did.

After using Jade's "Show Overlay" hotkey to disable the overlay, this issue stopped occurring. This shows that Jade is indeed the culprit for this issue. Therefore, I will forward this issue to Jade.

Thank you for altering me of Jade being the cause of the issue, @Cart3r1234!
