### ISSUE TITLE
Incompatibility with FirstPersonModel

### ISSUE THREAD

**Issue by natrow** [Fabricators-of-Create/Create#905]
### Describe the Bug

Some items are rendered onto the screen when they shouldn't be while using the FirstPersonModel mod, causing an obnoxious visual glitch.

Affected items:
 - Creative Worldshaper
 - Potato Cannon
 - Extendo Grip

See https://github.com/tr7zw/FirstPersonModel/issues/352

### Reproduction Steps

1. Install Create Fabric
2. Install FirstPersonModel
3. Hold any of the affected items

### Expected Result

Items shouldn't be rendered, allowing the FirstPersonModel mod to display correctly.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/60853993/235503836-7e2da30a-94fa-46bc-8dba-31065deaa57a.png)

### Operating System

Arch Linux

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

FirstPersonModel

**Comment by TropheusJ** [comment]
With these items, Create completely replaces the hand rendering. This probably should not be the case.

**Comment by electricsteve** [comment]
create needs to add a tag to the item i think and it's probably a glitch on forge too.

**Comment by milkev** [comment]
This is the case for goggles as well ,-, this ones extremely obnoxious
Im on version  0.5.1-d-build.1161 for 1.20.1
A simple toggle in creates client side config for rendering these should be a good solution. This is what some other mods do for FirstPersonModel compatability.
![image](https://github.com/Fabricators-of-Create/Create/assets/22010128/445e7a00-9a4c-4190-a4e5-32eab07edc58)

**Comment by IThundxr** [comment]
Seems to be fixed, the world shaper renders a bit wonky but that's purely because it takes over hand rendering, any further fixes should be suggested to Create Forge in the create discord server
