### ISSUE TITLE
Sandpaper animation bug

### ISSUE THREAD

**Issue by Atakku** [Fabricators-of-Create/Create#906]
### Describe the Bug

Minor rendering bug involving sandpaper and the sanding animation
This probably occurs in the forge version too, but I haven't tested that

### Reproduction Steps

1. Take multiple sandpapers and start sanding rose quartz
2. Switch between sandpapers while still sanding
3. Animation glitches and stays, until you switch back to that sandpaper, start sanding and stop sanding

### Expected Result

Sandpaper shouldn't render as being used if not used

### Screenshots and Videos

https://user-images.githubusercontent.com/57140941/235560981-029ed6ef-ab83-44e3-b29e-3146d150f334.mp4

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by Atakku** [comment]
This bug also occurs when switching to any item while sanding
You can drop the sandpaper afterwards, and the bug will still persist

**Comment by TropheusJ** [comment]
same as forge

**Comment by IThundxr** [comment]
Upstream issue created at: https://github.com/Creators-of-Create/Create/issues/6115
