### ISSUE TITLE
Server crashes on startup with `java.lang.ClassNotFoundException`

### ISSUE THREAD

**Issue by hadrizi** [Fabricators-of-Create/Create#907]
### Describe the Bug

When starting server with `create-fabric-0.5.0.i-1003+1.19.2` it crashes
Singleplayer world works normally

It is worth noting that I add create to BetterMC 1.19.2 Fabric modpack

### Reproduction Steps

1. Install BetterMC 1.19.2 Fabric server
2. Add create-fabric-0.5.0.i-1003+1.19.2 to mods folder
3. Run server

### Expected Result

I expect server to launch without errors

### Screenshots and Videos

None

### Crash Report or Log

https://pastebin.com/yqJx6eyb

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Other mods are listed in the log file

**Comment by TropheusJ** [comment]
Every Compat problem
