### ISSUE TITLE
Vertical belt item transport weirdness

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Fabricators-of-Create/Create#908]
### Describe the Bug

I've noticed a few interactions with both kinds of vertical belts (1: the kind between two horizontal shafts vertically offset from each other, and 2: the kind between two vertical shafts horizontally offset from each other).

The items visually float off into the air next to or pass through the first kind of belt, or travel along the edge of the second kind of belt.

### Reproduction Steps

I think the videos make it clear, and it would be cumbersome to put into words.

### Expected Result

I would expect things to simply not output to vertical belts, but I'm not sure what the intention in these cases is. 

### Screenshots and Videos

https://user-images.githubusercontent.com/618276/235826220-7d8fbbb6-2386-4c99-bb4e-88b923245638.mp4

https://user-images.githubusercontent.com/618276/235828774-4858d30a-d251-4c28-8c68-70dc8cf9d0e8.mp4

https://user-images.githubusercontent.com/618276/235828695-265b861c-83f5-4cb4-957b-14ebd6dc6ece.mp4

https://user-images.githubusercontent.com/618276/235828696-032cec35-5f02-4c1a-8b85-3326ce3fb3e5.mp4

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by DarianLStephens** [comment]
I could see the top one _maybe_ working a little with some changes, but yeah, the others definitely shouldn't be possible without a new item added to Create attached to belts or something.

**Comment by TropheusJ** [comment]
Happens on Forge too

**Comment by electricsteve** [comment]
wth weirdest shit i've ever seen

**Comment by IThundxr** [comment]
Upstream report: https://github.com/Creators-of-Create/Create/issues/6114
