### ISSUE TITLE
Super Glue does not work with non-default key binds

### ISSUE THREAD

**Issue by aerieworks** [Fabricators-of-Create/Create#910]
### Describe the Bug

If the key binds for "Attack/Destroy" and/or "Use Item/Place Block" have been changed, the Super Glue item cannot be used properly:

* If "Attack/Destroy" is bound to anything other than "Left Button", pressing that key with Super Glue selected results in a default attack animation that does nothing.
* "Use Item/Place Block" is bound to either "Left Button" or "Right Button", Super Glue works as expected. If it is bound to any other key, pressing the key with Super Glue selected has no effect.

### Reproduction Steps

1. With default key bindings, use Super Glue to glue two blocks together.
2. Edit key bindings and assign both "Attack/Destroy" and "Use Item/Place Block" to unbound letter keys.
3. Attempt to remove the Super Glue.
4. Attempt to glue two other blocks together.

### Expected Result

Pressing the key bound to "Attack/Destroy" while holding Super Glue over glued together blocks causes the glue to be removed. Pressing the key bound to "Use Item/Place Block" while holding Super Glue starts, and then finishes applying glue to a set of blocks.

### Operating System

macOS Ventura 13.3.1

### Mod Version

0.5.0i

### Minecraft Version

1.18.2

### Other Mods

* Create 0.5.0i
* Fabric API 0.76.0

**Comment by TropheusJ** [comment]
This has been fixed on 1.19
