### ISSUE TITLE
Game doesn't start past world generation screen

### ISSUE THREAD

**Issue by Zevyrus** [Fabricators-of-Create/Create#911]
### Describe the Bug

Game is able to start but I cannot enter any worlds, and the game crashes soon after world generation is loaded. I attempted to check the logs on my own but it just says something about minecart capability, I may be doing something wrong here

### Reproduction Steps

1.  Mods in list loaded
2. Create a world

### Expected Result

The game crashes soon after and I cannot find exactly why

### Crash Report or Log

https://pastebin.com/v3Xe71CZ

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

- adaptedorigins 1.19-2.3.0-FABRIC
	- additionalstructures 4.1.1
	- adorn 3.8.2+1.19.2
	- adventurez 1.4.17
	- amethyst_core 1.1.0+1.19
	   \-- common-protection-api 1.0.0
	- amethyst_imbuement 1.19-31
	   |-- common-protection-api 1.0.0
	   |-- conditional-mixin 0.3.2
	   |-- fzzy_config 0.1.0+1.19
	   |-- playerabilitylib 1.6.0
	   \-- structurized-reborn 1.19-01
	- architectury 6.5.77
	- artifacts 7.1.1+fabric
	   \-- step-height-entity-attribute 1.0.0
	- autoconfig1u 3.4.0
	- baby_dont_herd_me BETA_1.1.1_1.19.2
	- badpackets 0.2.1
	- balm-fabric 4.5.7
	- beautify 1.1.1+fabric-1.19.2
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cardinal-components-world 5.0.2
	- bettercombat 1.6.2+1.19
	- betterfpsdist 1.19-2.4
	- betterthirdperson 1.9.0
	- bewitchment 1.19-6
	   |-- fabric-permissions-api-v0 0.1-SNAPSHOT
	   |-- impersonate 2.8.0
	   |-- playerabilitylib 1.6.0
	   |-- reach-entity-attributes 2.3.0
	   \-- terraform-wood-api-v1 4.2.0
	- bookshelf 16.2.18
	- botania 1.19.2-438-FABRIC
	   |-- fiber 0.23.0-2
	   |-- reach-entity-attributes 2.3.0
	   \-- step-height-entity-attribute 1.0.0
	- botanypots 9.0.33
	- bountiful 3.0.0
	- brewinandchewin fabric-1.0.6+1.19.2
	- bushierflowers 0.0.1-1.19.2
	- bwplus 1.19-10
	   |-- playerabilitylib 1.6.0
	   |-- reach-entity-attributes 2.3.0
	   \-- terraform-wood-api-v1 4.2.0
	- byg 2.0.0.13
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- cardinal-components 5.0.2
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   |-- cardinal-components-item 5.0.2
	   |-- cardinal-components-level 5.0.2
	   |-- cardinal-components-scoreboard 5.0.2
	   \-- cardinal-components-world 5.0.2
	- catalogue 1.7.0-1.19.2
	- chalk 2.1.0+1.19
	- charm 4.4.4
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- charm_fixer 1.0.0
	- charmonium 4.2.1
	- chefsdelight 1.0.2-fabric-1.19.2
	   \-- structurized-reborn 1.19-01
	- clarks_classes 1.19-4.0.2-FABRIC
	- cloth-config 8.2.88
	   \-- cloth-basic-math 0.6.1
	- comforts 6.0.4+1.19.2
	   \-- spectrelib 0.12.4+1.19.2
	- companion_bats 1.19.3
	   \-- static-content 1.0.1-1.16.2
	        \-- staticdata 1.1.2
	- configured 2.0.0
	- connectivity 1.19.2-4.0
	- corgilib 1.0.0.32
	- cosmetica 1.2.4
	   |-- com_github_cosmetica-cc_cosmeticadotjava 1.11.2
	   \-- sulphate 1.1.1
	- create 0.5.0.i-1003+1.19.2
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.8.a-4
	   |-- milk 1.0.51
	   |    \-- dripstone_fluid_lib 2.0.1
	   |-- porting_lib 2.1.926+1.19.2
	   |    |-- forge_tags 3.0
	   |    |-- mm 2.3
	   |    |-- porting_lib_accessors 2.1.926+1.19.2
	   |    |-- porting_lib_attributes 2.1.926+1.19.2
	   |    |-- porting_lib_base 2.1.926+1.19.2
	   |    |-- porting_lib_common 2.1.926+1.19.2
	   |    |-- porting_lib_constants 2.1.926+1.19.2
	   |    |-- porting_lib_entity 2.1.926+1.19.2
	   |    |-- porting_lib_extensions 2.1.926+1.19.2
	   |    |-- porting_lib_fake_players 2.1.926+1.19.2
	   |    |-- porting_lib_lazy_registration 2.1.926+1.19.2
	   |    |-- porting_lib_loot 2.1.926+1.19.2
	   |    |-- porting_lib_model_generators 2.1.926+1.19.2
	   |    |-- porting_lib_model_loader 2.1.926+1.19.2
	   |    |-- porting_lib_models 2.1.926+1.19.2
	   |    |-- porting_lib_networking 2.1.926+1.19.2
	   |    |-- porting_lib_obj_loader 2.1.926+1.19.2
	   |    |-- porting_lib_transfer 2.1.926+1.19.2
	   |    \-- serialization_hooks 0.3.26
	   |-- reach-entity-attributes 2.3.0
	   \-- registrate-fabric 1.1.57-MC1.19.2
	- createaddition 20230211a
	   \-- team_reborn_energy 2.2.0
	- createoreexcavation 1.1.2
	   \-- chunk-storage-api-fabric 1.0.2
	- creeperoverhaul 2.0.9
	- crittersandcompanions 1.19.2-1.0.3
	- culturaldelights 0.14.9+1.19.2
	   \-- terraform-wood-api-v1 4.2.0
	- darkquesting 1.1.0
	- deeperdarker 1.1.6
	   |-- customportalapi 0.0.1-beta54-1.19
	   \-- paragon 3.0.2
	        \-- org_yaml_snakeyaml 1.27
	- deftulib 1.5.6
	   |-- com_github_ben-manes_caffeine_caffeine 3.1.3
	   |-- com_squareup_okhttp3_okhttp 4.9.3
	   |-- com_squareup_okio_okio 3.0.0
	   |-- com_squareup_okio_okio-jvm 3.0.0
	   |-- elementa 578
	   |-- universalcraft 262
	   |-- vigilance 281+pull-78
	   |-- xyz_deftu_deftils_deftils 2.0.0
	   \-- xyz_deftu_enhancedeventbus 1.0.0
	- doodads 0.1.2-1.19.2
	- dustrial_decor 0.5
	- ecologics 2.1.11
	- endgoblintraders 1.5.2
	- entitycollisionfpsfix 2.0.0.0
	- entityculling 1.6.1-mc1.19.2
	- expandability 7.0.0
	- expandeddelight 0.2.5.2
	- extrakeybinds 0.4.0+1.17-1.19.2
	- fabric-api 0.76.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.41+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.8+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.11+10eb22f490
	   |-- fabric-networking-v0 0.3.28+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.1+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.32+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.19
	- farmersdelight 1.19.2-1.3.9
	- farmersrespite 2.2.4
	- fdjei 1.0.1
	- flowerymooblooms 1.0.0
	- forgeconfigapiport 4.2.11
	- forgero 0.10.9-pre2+1.19.2
	   |-- forgero-common 0.10.9-pre2+1.19.2
	   |-- forgero-compat 0.10.9-pre2+1.19.2
	   |-- forgero-core 0.10.9-pre2+1.19.2
	   |-- forgero-extended 0.10.9-pre2+1.19.2
	   |-- forgero-fabric-compat 0.10.9-pre2+1.19.2
	   |-- forgero-fabric-core 0.10.9-pre2+1.19.2
	   |    \-- advanced_runtime_resource_pack 0.6.4
	   |-- forgero-structures 0.10.9-pre2+1.19.2
	   \-- forgero-vanilla 0.10.9-pre2+1.19.2
	- friendsandfoes 1.8.1
	- ftblibrary 1902.3.18-build.208
	- ftbquests 1902.4.13-build.219
	   \-- team_reborn_energy 2.2.0
	- ftbteams 1902.2.13-build.100
	- fzzy_core 0.2.0+1.19
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.6
	- geckolib3 3.1.40
	   \-- com_eliotlash_mclib_mclib 20
	- globalpacks 1.14.3.1_fabric
	- go-fish 1.6.0-1.19.1
	- goblintraders 1.8.1
	- guardiansgalore 1.19.2-3.0
	- handcrafted 2.0.6
	- harvestwithease 6.0.1.2-final
	- hexcasting 0.10.3
	   \-- reach-entity-attributes 2.3.0
	- illuminations 1.10.11
	- indium 1.0.9+mc1.19.2
	- iris 1.6.2
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- irisflw 0.1.9-BETA
	- itemfilters 1902.2.9-build.46
	- jade 8.7.3
	- jadeaddons 3.1.0
	- jamlib 0.6.0+1.19
	- java 17
	- jei 11.6.0.1015
	- jeresources 1.2.2.200
	- jmi 0.13-33
	- journeymap 5.9.5
	   \-- journeymap-api-fabric 1.19.1-1.9-fabric-SNAPSHOT
	- kambrik 4.0-1.19.2
	- leavesbegone 4.0.1
	- letmedespawn fabric-1.0.2
	- levelz 1.4.8
	   \-- libgui 6.0.1+1.19
	        |-- jankson 4.1.1+j1.2.1
	        \-- libninepatch 1.1.0
	- libraryferret 4.0.0
	- libz 1.0.0
	- majobroom 1.2.2
	- mca 7.5.0-rc.2+1.19.2
	- midnightlib 1.0.0
	- minecraft 1.19.2
	- mobscarecrow 2.2.1-1.19.1
	- moonlight 1.19.2-2.2.31
	- mru 0.1.5+1.19.2
	   \-- com_sksamuel_scrimage_scrimage-core 4.0.31
	- mythicmounts 1.19.2-7.2
	- naturalist 3.0.2
	- naturescompass 1.19.2-2.1.0-fabric
	- nethersdelight 1.0.1
	   \-- disable_custom_worlds_advice 3.0
	- numismatic-overhaul 0.2.8+1.19
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- stacc 1.3.3
	- nyfsquiver Fabric-0.5.1-1.19.2
	- oceansdelight 1.0.0
	- opaccreatesupport 1.1.1
	- openpartiesandclaims 0.17.3
	- origins 1.7.1
	   |-- apoli 2.6.1
	   |    |-- calio 1.7.0
	   |    \-- playerabilitylib 1.6.0
	   \-- reach-entity-attributes 2.3.0
	- origins-classes 1.4.0
	- originsumbrellas 1.5.4
	- overweight_farming 1.19.2-2.0.2-fabric
	   |-- playerabilitylib 1.6.0
	   |-- reach-entity-attributes 2.3.0
	   \-- terraform-wood-api-v1 4.2.0
	- owo 0.9.3+1.19
	   \-- blue_endless_jankson 1.2.1
	- patchouli 1.19.2-77-FABRIC
	   \-- fiber 0.23.0-2
	- paucal 0.5.0
	   \-- fiber 0.23.0-2
	- pehkui 3.7.3+1.14.4-1.20
	   \-- kanos_config 0.4.0+1.14.4-1.19.4
	- player-animator 1.0.2
	- plushies 1.2
	- polymorph 0.46.1+1.19.2
	- probablychests 0.5.5-1.19.2
	- puzzleslib 4.4.0
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cardinal-components-world 5.0.2
	- questsadditions 1.4.1
	   \-- team_reborn_energy 2.2.0
	- railways 1.2.6+fabric-mc1.19.2
	- realisticsleep 1.7.0
	- resourcefulconfig 1.0.20
	- resourcefullib 1.1.24
	- revelationary 1.3.5
	- rightclickharvest 3.1.0+1.19-1.19.2
	- satin 1.9.0
	- simplyswords 1.44.0-1.19.2
	- skinlayers 1.5.2-mc1.19.1
	- sodium 0.4.4+build.18
	   \-- org_joml_joml 1.10.4
	- spectrum 1.6.10-1.19.2-leisure_time
	   |-- additionalentityattributes 1.2.0+1.19.2
	   |-- arrowhead 1.2.0-1.19.2
	   |-- incubus_core 1.9.4
	   \-- reach-entity-attributes 2.3.0
	- strawgolem 2.0.0-beta.5
	- supplementaries 1.19.2-2.3.8
	- suppsquared 1.19.2-1.0.14
	- t_and_t 1.10
	- terrablender 2.0.1.136
	- terralith 2.3
	- the_bumblezone 6.7.14+1.19.2
	   \-- fake-player-api 0.5.0
	- thonkutil 2.15.4+1.19
	   |-- thonkutil-base 1.13.2+4a8c408a57
	   |-- thonkutil-capes-v1 1.4.2+3eb2749857
	   |-- thonkutil-coords-v1 1.1.2+8ff533c957
	   |-- thonkutil-customization-v1 1.1.2+8ff533c957
	   |-- thonkutil-legacy 1.1.2+5d4263f557
	   |-- thonkutil-modchecker-v1 1.1.3+bd4b387957
	   |-- thonkutil-potions-v0 1.5.2+8ff533c957
	   |-- thonkutil-titlescreen-v1 1.2.2+8ff533c957
	   \-- thonkutil-trades-v1 1.2.2+8ff533c957
	- tooltipscroller 1.0.0
	- touhoublessings 1.0.1-1.19.2
	- touhouorigins 0.8.3-1.19.2
	   \-- apugli 1.11.2+1.19-fabric
	- travelersbackpack 1.19.2-8.2.19
	   \-- reach-entity-attributes 2.3.0
	- trinkets 3.4.2
	- waystones 11.4.0
	- windchimes 1.2.1
	- xercamusic fabric-1.19.2-1.0.2
	- xercapaint fabric-1.19.2-1.0.2
	- xlpackets 1.19.2-4

**Comment by TropheusJ** [comment]
Connectivity is crashing, Create is unrelated
