### ISSUE TITLE
Deployer doesn't work

### ISSUE THREAD

**Issue by LeonManex** [Fabricators-of-Create/Create#914]
### Describe the Bug

While trying to create a precision mechanism, my deployer stopped working. At the beginning, everything worked, but then, for no apparent reason, it stopped working.

### Reproduction Steps

1. Building the machine (see photo).
2. Placing gold sheet onto the depot.
3. Putting the materials in order one at a time in the barrel.
4. Stopped working after some time.

![2023-05-06_09 44 24_2](https://user-images.githubusercontent.com/132741954/236611960-94b7cd90-a7f7-476b-b38f-d2688d591036.png)

### Expected Result

I expected that the deployer would work like it thit before (even after rebuilding it, it doesn't work).

### Screenshots and Videos

![2023-05-06_10 14 18](https://user-images.githubusercontent.com/132741954/236612189-f83131f3-4277-454f-8bd6-7837aed853ba.png)

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Additional Context

The world is on a Nitrado server.

**Comment by TropheusJ** [comment]
extended cogwheels supposedly breaks the recipe, and it looks like you have it installed.
