### ISSUE TITLE
everycomp crashes server with create mod installed (Fabric)

### ISSUE THREAD

**Issue by Gustiviy** [Fabricators-of-Create/Create#916]
### Describe the Bug

adding the create mod to my server conflicts with everycomp.

### Reproduction Steps

1. have better minecraft installed
2. add create mod
3. crash
...

### Expected Result

server starts normally with mods loaded

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/79268434/236688602-f04b7053-667b-42d1-b2ea-48ef5c798133.png)

### Crash Report or Log

https://pastebin.com/ufUjseJm

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

all mods from the better minecraft 1.19.2 modpack version v17.5 HF
also listed in the logs

**Comment by TropheusJ** [comment]
cvery compat's issue
