### ISSUE TITLE
Concrete farm runs without being powered

### ISSUE THREAD

**Issue by EllieSkird** [Fabricators-of-Create/Create#917]
### Describe the Bug

Basically, my steam powered concrete farm keeps running even if I manually break the shaft connecting the steam engine to the concrete farm. We tried relogging my account, rebooting the server and breaking a few things. It just keeps working. How can I fix this? I don't know how to reproduce this since it seems like a glitch. but you're welcome to come and see for yourselves. the world download is available for you. they turned off fine two days ago. 

### Reproduction Steps

1. I can't reproduce it. 
2. It's weird
3. Tried everything I could think of

### Expected Result

Please stop my errand farm. 

### Screenshots and Videos

https://user-images.githubusercontent.com/121561149/236806852-e2564e46-a6b3-43e2-a270-3a8efd69f539.mp4

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

[11:56:47] [main/INFO]: Loading 218 mods:
	- additionaladditions 5.1.0
	   \-- libgui 6.0.0-beta.5+1.19-pre1
	        |-- jankson 4.1.1+j1.2.1
	        |    \-- blue_endless_jankson 1.2.1
	        \-- libninepatch 1.1.0
- advdebug 2.3.0
	- appleskin 2.4.1+mc1.19
	- architectury 6.5.77
	- audioplayer 1.19.2-1.4.5
	- bcc 2.0.2-build.16+mc1.19.1
	- blockus 2.5.9+1.19.2
	   \-- terraform-wood-api-v1 4.2.0
	- bookshelf 16.2.18
	- byg 2.0.1.1
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- c2me 0.2.0+alpha.9.9
	   |-- c2me-base 0.2.0+alpha.9.9
	   |-- c2me-client-uncapvd 0.2.0+alpha.9.9
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.9.9
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.9.9
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.9.9
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.9.9
	   |-- c2me-notickvd 0.2.0+alpha.9.9
	   |-- c2me-opts-allocs 0.2.0+alpha.9.9
	   |-- c2me-opts-chunk-access 0.2.0+alpha.9.9
	   |-- c2me-opts-chunkio 0.2.0+alpha.9.9
	   |-- c2me-opts-math 0.2.0+alpha.9.9
	   |-- c2me-opts-scheduling 0.2.0+alpha.9.9
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.9.9
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.9.9
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.9.9
	   |-- c2me-server-utils 0.2.0+alpha.9.9
	   |-- c2me-threading-chunkio 0.2.0+alpha.9.9
	   |-- c2me-threading-lighting 0.2.0+alpha.9.9
	   |-- c2me-threading-scheduling 0.2.0+alpha.9.9
	   |-- c2me-threading-worldgen 0.2.0+alpha.9.9
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- carpet 1.4.84
	- chunky 1.3.38
	- cloth-config 8.2.88
	   \-- cloth-basic-math 0.6.1
	- clumps 9.0.0+14
	- collective 6.53
	- comforts 6.0.4+1.19.2
	   \-- spectrelib 0.12.4+1.19.2
	- connectivity 1.19.2-3.8
	- corgilib 1.0.0.32
	- create 0.5.0.i-1003+1.19.2
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.8.a-4
	   |-- milk 1.0.51
	   |    \-- dripstone_fluid_lib 2.0.1
	   |-- porting_lib 2.1.926+1.19.2
	   |    |-- com_github_llamalad7_mixinextras 0.1.1
	   |    |-- forge_tags 3.0
	   |    |-- porting_lib_accessors 2.1.926+1.19.2
	   |    |-- porting_lib_attributes 2.1.926+1.19.2
	   |    |-- porting_lib_base 2.1.926+1.19.2
	   |    |-- porting_lib_common 2.1.926+1.19.2
	   |    |-- porting_lib_constants 2.1.926+1.19.2
	   |    |-- porting_lib_entity 2.1.926+1.19.2
	   |    |-- porting_lib_extensions 2.1.926+1.19.2
	   |    |-- porting_lib_fake_players 2.1.926+1.19.2
	   |    |-- porting_lib_lazy_registration 2.1.926+1.19.2
	   |    |-- porting_lib_loot 2.1.926+1.19.2
	   |    |-- porting_lib_model_generators 2.1.926+1.19.2
	   |    |-- porting_lib_model_loader 2.1.926+1.19.2
	   |    |-- porting_lib_models 2.1.926+1.19.2
	   |    |-- porting_lib_networking 2.1.926+1.19.2
	   |    |-- porting_lib_obj_loader 2.1.926+1.19.2
	   |    |-- porting_lib_transfer 2.1.926+1.19.2
	   |    \-- serialization_hooks 0.3.26
	   |-- reach-entity-attributes 2.3.0
	   \-- registrate-fabric 1.1.57-MC1.19.2
	- croptopia 2.2.2
	   |-- com_typesafe_config 1.4.1
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- cyclepaintings 3.2
	- darkpaintings 13.1.5
	- decorative_blocks 3.0.0
	- diagonalfences 4.2.3
	- emotecraft 2.2.7-b.build.48
	   |-- bendy-lib 2.1.3-test2
	   \-- player-animator 1.0.2
	- enchanted-vertical-slabs 1.6.2
	- fabric-api 0.76.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.41+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.8+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.11+10eb22f490
	   |-- fabric-networking-v0 0.3.28+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.1+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.32+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.19
	- ferritecore 5.0.3
	- forgeconfigapiport 4.2.11
	- geckolib3 3.1.40
	   \-- com_eliotlash_mclib_mclib 20
	- globalpacks 1.14.3.1_fabric
	- hopobettermineshaft 1.1.6
	- image2map 0.3.0
	   |-- map-canvas-api 0.2.0+1.19.1
	   \-- sgui 1.1.5+1.19.1
	- java 17
	- krypton 0.2.1
	   \-- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT
	- kubejs 1902.6.0-build.142
	- lazydfu 0.1.3
	- lithium 0.11.1
	- minecraft 1.19.2
	- nightlights 1.1
	- notenoughcrashes 4.2.1+1.19.2
	- patchouli 1.19.2-77-FABRIC
	   \-- fiber 0.23.0-2
	- pfm 1.1.1
	- polaroidcamera 1.4.1
	- polymer-all 0.2.25+1.19.2
	   |-- polymer 0.2.25+1.19.2
	   |    |-- packet_tweaker 0.3.0+1.18.2
	   |    \-- polymer-registry-sync-manipulator 0.0.3+1.19.2
	   |-- polymer-autohost 0.1.4+1.19.2
	   |    \-- polymer-registry-sync-manipulator 0.0.3+1.19.2
	   \-- polymer-blocks-ext 0.1.0-alpha.9+1.19.2
	- puzzleslib 4.4.0
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cardinal-components-world 5.0.2
	- reinfbarrel 2.3.0+1.19
	   \-- reinfcore 3.0.3+1.19
	- reinfchest 2.2.0+1.19
	   \-- reinfcore 3.0.3+1.19
	- reinfshulker 2.2.0+1.19
	   \-- reinfcore 3.0.3+1.19
	- rhino 1902.2.2-build.268
	- roughlyenoughitems 9.1.595
	   \-- error_notifier 1.0.9
	- servercore 1.3.3-1.19.2
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- me_lucko_spark-api 0.1-SNAPSHOT
	   \-- placeholder-api 2.0.0-pre.1+1.19.2
	- skinshine 1.1.9
	- spark 1.10.37
	- spiceoffabric 1.6.0-beta.4+1.19.2
	   |-- capsaicin 1.3.1+mc1.19.3
	   |-- coat 1.0.0-beta.18+mc22w17a
	   |-- tweed4_annotated 1.3.1+mc22w17a
	   |-- tweed4_base 1.7.1+mc22w17a
	   |-- tweed4_data 1.2.1+mc22w17a
	   |-- tweed4_data_hjson 1.1.1+mc22w17a
	   |-- tweed4_tailor_coat 1.1.3+mc22w17a
	   \-- tweed4_tailor_screen 1.1.1+mc22w17a
	- squaremap 1.1.8
	   |-- adventure-platform-fabric 5.5.0-SNAPSHOT
	   |    |-- net_kyori_adventure-api 4.11.0
	   |    |-- net_kyori_adventure-key 4.11.0
	   |    |-- net_kyori_adventure-platform-api 4.1.2
	   |    |-- net_kyori_adventure-text-logger-slf4j 4.11.0
	   |    |-- net_kyori_adventure-text-minimessage 4.11.0
	   |    |-- net_kyori_adventure-text-serializer-gson 4.11.0
	   |    |-- net_kyori_adventure-text-serializer-plain 4.11.0
	   |    |-- net_kyori_examination-api 1.3.0
	   |    \-- net_kyori_examination-string 1.3.0
	   |-- cloud 1.8.0-SNAPSHOT
	   |    |-- cloud_commandframework_cloud-brigadier_ 1.8.0-SNAPSHOT
	   |    |-- cloud_commandframework_cloud-core_ 1.8.0-SNAPSHOT
	   |    |-- cloud_commandframework_cloud-services_ 1.8.0-SNAPSHOT
	   |    \-- io_leangen_geantyref_geantyref 1.3.13
	   \-- cloud_commandframework_cloud-minecraft-extras 1.8.0-SNAPSHOT
	- starbidous_more_end_cities 1.0.0
	- starlight 1.1.1+fabric.ae22326
	- status 1.19.2-1.0.1
	- strawstatues 4.0.10
	- terrablender 2.0.1.136
	- twilightforest 4.2.357
	   |-- here-be-no-dragons 1.0.0
	   |-- javax_annotation_javax_annotation-api 1.3.2
	   |-- mm 2.3
	   \-- reach-entity-attributes 2.3.0
	- voicechat 1.19.2-2.4.5
	   \-- fabric-key-binding-api-v1 1.0.18+9ff28f4095
	- worldedit 7.2.12+6240-87f4ae1
	- zombieproofdoors 3.0

### Additional Context

See video. If you have questions you're welcome to ask, I also have a better verion of the video (had to compress it 4x in order to post it) prefer email or discord since this is my first time on github.

**Comment by NLMulti** [comment]
Issue plays on a 1.19.2 server, for the dev's I can whitelist somebody when needed. A world download (including mods) is available also for you!

We love the Create MOD, it helps techy people but also people that just want to build. Keep up the good work!

**Comment by TropheusJ** [comment]
ghost power has been a long-running issue with Create. You'll need to find which two blocks are powering each other.
With f3 open, each block's source will be highlighted when looked at.

**Comment by NLMulti** [comment]
Conformed! Thnx for the help!
