### ISSUE TITLE
Precision mechanism uncraftable

### ISSUE THREAD

**Issue by elvancuc** [Fabricators-of-Create/Create#919]
### Describe the Bug

I'm unable to create a precision mechanism, as the third step, requiring a iron nugget displays nothing and it's called invalid; If you continue on with the process regardless, it will not add the iron nugget into the mechanism, (I saw the recipe from the mod JEI)

### Reproduction Steps

1.JEI check recipe 
2. III step invalid
3. unable to create precision mechanism normally.
...

### Expected Result

![Screenshot 2023-05-08 092159](https://user-images.githubusercontent.com/132277574/236863782-cfe482f7-332d-44d4-9ce3-e27ed2b26675.png)

### Operating System

windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
I've heard this is an issue with extended cogwheels.
