### ISSUE TITLE
io.netty.handler.codec.DecoderException: net.minecraft.class_148: Loading NBT data

### ISSUE THREAD

**Issue by onePlaceholder** [Fabricators-of-Create/Create#921]
### Describe the Bug

Cannot connect to server.

### Reproduction Steps

1. Make a server
2. Connect to the server

### Expected Result

Connection Successful 

### Operating System

Debian 11

### Mod Version

0.5.0i

### Minecraft Version

1.18.2

### Other Mods

https://docs.google.com/spreadsheets/d/1IV8iqAf08u1WOwfulISgIuajnOlUdwRU9udK4QIndnY/edit?usp=sharing

**Comment by TropheusJ** [comment]
can't do anything without the full log

**Comment by onePlaceholder** [comment]
here's the full log https://mclo.gs/EUS866d

**Comment by TropheusJ** [comment]
weird, I don't know. It's probably an incompatibility.

**Comment by electricsteve** [comment]
something to do with recipes on contraptions

**Comment by AmogusAzul** [comment]
a shame that this issue hasn't been fixed yet

**Comment by TropheusJ** [comment]
This is probably some incompatibility, but there's nothing to go off of.
