### ISSUE TITLE
Item Vault item deletion

### ISSUE THREAD

**Issue by Crockerdime** [Fabricators-of-Create/Create#922]
### Describe the Bug

the item vault is suppose to store items forever until world file deletion but i after relogging all me items were erased.

Potential causes:
Mods:
Stackers mod by Andrew6rant - Custom max item stacks.
Menulogue mod by MrCrayfish - Config settings .
Create mod coding non-sacrifices for storage and item vault

### Reproduction Steps

1.
2.
3.
...

### Expected Result

all item no matter how many stay in vault even after logging into the next day

### Operating System

Windows 11, Cures forge and Minecraft launcher

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Mods:
Stackers mod by Andrew6rant - Custom max item stacks.
Menulogue mod by MrCrayfish - Config settings .

### Additional Context

maybe i went over the limit in the item vault and dus deleted all items in the process due to the other mods mentioned Stackers mod by Andrew6rant and Menulogue mod by MrCrayfish.

**Comment by TropheusJ** [comment]
Try removing Stacker

**Comment by IThundxr** [comment]
If you are able to reproduce this on the latest version feel free to open a new issue
