### ISSUE TITLE
Velocity Compatibility

### ISSUE THREAD

**Issue by UnperishedFoods** [Fabricators-of-Create/Create#925]
### Describe the Bug

Loading into a Velocity server network with Create causes an exception in the netty pipeline.

### Reproduction Steps

1. Install the Create mod.
2. Attempt to load into a Velocity server.
3. Receive the error.

### Expected Result

I expected to load into the proxy server and get redirected to a Paper 1.19.4 server (with ViaVersion). This was not the case.

### Crash Report or Log

https://gist.github.com/UnperishedDev/816525e4d0c5a0d6b1aa75df65f390e5

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

A lot of other mods (77 others).

**Comment by TropheusJ** [comment]
joining a paper server with Create installed is not going to work, is not supported, and will not be fixed. If there's still an issue when connecting to a fabric one, it may be looked into, but I haven't heard good things about velocity compat with mods.

**Comment by TropheusJ** [comment]
especially when the server is using 1.19.4 and Create is on 1.19..2
