### ISSUE TITLE
Dropz doesnt work with create

### ISSUE THREAD

**Issue by Mrgaton** [Fabricators-of-Create/Create#926]
### Describe the Bug

I believe dropz uses custom entity for drops, would be great to support it!

https://github.com/LazuriteMC/Dropz/issues/25

See dropz issue, i don't think they can do it on their end.

Additional Context
Dropz uses the rayon physics api.

### Reproduction Steps

throwing items to basin doest work

### Expected Result

Items interact with mod

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
Duplicate of #595
