### ISSUE TITLE
Station Marker Does Not Appear on Map

### ISSUE THREAD

**Issue by Koi-Jiang** [Fabricators-of-Create/Create#929]
### Describe the Bug

When right-clicking a train station with a map, no marker appears on the map.

### Reproduction Steps

1. Place down a track and a train station
2. Create a new map near the station
3. Right-click the station with the map

### Expected Result

There should be a red marker appearing on the map, with the name of the station under it.

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

I was able to reproduce this bug with only Create and Fabric API installed.

### Additional Context

This feature works correctly on the Forge version.

**Comment by electricsteve** [comment]
I can confirm, doesn't work

**Comment by electricsteve** [comment]
can confirm, doesn't work. even with the current code

**Comment by TropheusJ** [comment]
this was fixed recently
