### ISSUE TITLE
Dough to Slimeball not working on a crafting table

### ISSUE THREAD

**Issue by AwesomeDude091** [Fabricators-of-Create/Create#931]
### Describe the Bug

Dough to Slimeball as a crafting recipe is not working

### Reproduction Steps

1. Take Create Dough
2. Place in Crafting Table
3. No craft ouput
...

### Expected Result

I get a slimeball

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Additional Context

I am fairly certain this is due to a incorrect tagging issue. JEI is showing that the recipe accepts any forge:dough/wheat, but its the fabric mod loader...

This also applies to the Automated Shapless Crafting Recipe

Also in case the it is important the exact version is 0.5.0i-1003

**Comment by TropheusJ** [comment]
The recipe is dough + lime dye. You probably have other mods breaking the tags, it works with Create alone.
