### ISSUE TITLE
SmallShips conflict causing world to be un-loadable (Invalid player data)

### ISSUE THREAD

**Issue by Winoys** [Fabricators-of-Create/Create#936]
**Describe the Bug**
Creating a minecart contraption while having the "Small Ships" mod installed causes the world to become un-loadable and produce the "Invalid player data" mod

**Reproduction Steps**
1. Have both Create and Small Ships mod installed
2. Build a minecart contraption and leave the world
3. Try to start the world again
4. Profit - or in this case - "Invalid player data" error shows and leaves you at the server-select screen

**Operating System**
Windows 11

**Mod Version**
0.5.0i for fabric

**Minecraft Version**
1.19.2

**Other Mods**
Error occured no matter which mods were installed.

**Misc**
I searched through and tested my 183 mods to find this conflict, and along the way discovered that it has something to do with the entity of the minecart contraption through NBT- and chunk editors. The only thing needed to do to "fix" the issue is to remove the Small Ships mod, or not use minecart contraptions.

I apologize in advance if I have missed any information regarding this, but otherwise hope this is useful.

**Comment by TropheusJ** [comment]
Need the log
