### ISSUE TITLE
Not compatible with cardboard

### ISSUE THREAD

**Issue by ghost** [Fabricators-of-Create/Create#939]
### Describe the Bug

Error when loading mixins

### Reproduction Steps

1. Server start
2. Loading mixins
3. Mixins error

### Expected Result

I really wanted to use mod create on my server with plugins

### Crash Report or Log

https://pastebin.com/gcKrDTku

### Operating System

Windows 11

### Mod Version

0.5.1a

### Minecraft Version

1.18.2

### Other Mods

[13:51:32] [main/INFO]: Loading 213 mods:
	- ad_astra 1.0.9
	   \-- team_reborn_energy 2.2.0
	- animal_feeding_trough 1.0.3+1.18.2
	- architectury 4.11.93
	- balm-fabric 3.2.6
	- bclib 1.4.7
	- betterdeserttemples 1.18.2-Fabric-1.3
	- betterdungeons 1.18.2-Fabric-2.1.0
	- betterend 1.1.1
	- betterfortresses 1.18.2-Fabric-1.0.0
	   \-- org_reflections_reflections 0.10.2
	- bettermineshafts 1.18.2-Fabric-2.2
	- betteroceanmonuments 1.18.2-Fabric-1.0.3
	- betterstrongholds 1.18.2-Fabric-2.1.1
	- bettervillage 3.0.0
	- c2me 0.2.0+alpha.7.35
	   |-- c2me-base 0.2.0+alpha.7.35
	   |-- c2me-client-uncapvd 0.2.0+alpha.7.35
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.7.35
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.7.35
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.7.35
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.7.35
	   |-- c2me-notickvd 0.2.0+alpha.7.35
	   |-- c2me-opts-allocs 0.2.0+alpha.7.35
	   |-- c2me-opts-chunk-access 0.2.0+alpha.7.35
	   |-- c2me-opts-chunkio 0.2.0+alpha.7.35
	   |-- c2me-opts-math 0.2.0+alpha.7.35
	   |-- c2me-opts-scheduling 0.2.0+alpha.7.35
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.7.35
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.7.35
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.7.35
	   |-- c2me-server-utils 0.2.0+alpha.7.35
	   |-- c2me-threading-chunkio 0.2.0+alpha.7.35
	   |-- c2me-threading-lighting 0.2.0+alpha.7.35
	   |-- c2me-threading-scheduling 0.2.0+alpha.7.35
	   |-- c2me-threading-worldgen 0.2.0+alpha.7.35
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   \-- org_threadly_threadly 6.6
	- cardboard 64
	   \-- com_github_isaiahpatton_specialsource master-SNAPSHOT
	- carpenter 1.1.1
	- cloth-config 6.4.90
	   \-- cloth-basic-math 0.6.1
	- coffee_delight 1.3
	- collective 6.53
	- colorfulenchantments 1.1.1+fabric_1.18.2
	- create 0.5.0.i-1016+1.18.2
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.8.a-36
	   |-- forge_tags 2.1
	   |-- milk 0.3.2
	   |    \-- dripstone_fluid_lib 1.2.0
	   |-- porting_lib 1.2.955-beta+1.18.2
	   |    |-- forge_tags 2.1
	   |    |-- mm 2.3
	   |    \-- serialization_hooks 0.3.23
	   |-- reach-entity-attributes 2.1.1
	   \-- registrate-fabric MC1.18.2-1.1.11
	        \-- forge_tags 2.1
	- creativecore 2.6.12
	- croptopia 2.1.2
	   |-- com_typesafe_config 1.4.1
	   |-- io_leangen_geantyref_geantyref 1.3.11
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- debugify 1.11.0
	- dyeallthethings 1.3.0
	- ecologics 1.7.11
	- emerald_tools 1.3.47
	   \-- pugh_tools 1.2.7
	- emi 0.5.3+1.18.2
	- enchantinginfuser 3.2.0
	   |-- cardinal-components-base 4.1.4
	   \-- cardinal-components-entity 4.1.4
	- endrem 5.1.0
	- expert_armor 1.7.5
	- fabric-api 0.76.0+1.18.2
	   |-- fabric-api-base 0.4.5+64b7c69360
	   |-- fabric-api-lookup-api-v1 1.6.3+2373a54560
	   |-- fabric-biome-api-v1 8.0.7+e83becad60
	   |-- fabric-block-api-v1 1.0.0+ee3621fc60
	   |-- fabric-blockrenderlayer-v1 1.1.13+3ac43d9560
	   |-- fabric-command-api-v1 1.1.10+d7c144a860
	   |-- fabric-commands-v0 0.2.9+b4f4f6cd60
	   |-- fabric-containers-v0 0.1.24+d7c144a860
	   |-- fabric-content-registries-v0 3.1.3+c85f2e3860
	   |-- fabric-convention-tags-v1 1.1.0+43ce63a460
	   |-- fabric-crash-report-info-v1 0.2.1+ee261a3e60
	   |-- fabric-data-generation-api-v1 3.1.0+6c70b68e60
	   |-- fabric-dimensions-v1 2.1.21+489d6f8260
	   |-- fabric-entity-events-v1 1.4.9+d7c144a860
	   |-- fabric-events-interaction-v0 0.4.20+d7c144a860
	   |-- fabric-events-lifecycle-v0 0.2.22+d7c144a860
	   |-- fabric-game-rule-api-v1 1.0.13+d7c144a860
	   |-- fabric-item-api-v1 1.6.2+8165403660
	   |-- fabric-item-groups-v0 0.3.16+91896a4960
	   |-- fabric-key-binding-api-v1 1.0.12+54e5b2ec60
	   |-- fabric-keybindings-v0 0.2.10+b4f4f6cd60
	   |-- fabric-lifecycle-events-v1 2.1.1+cc71601c60
	   |-- fabric-loot-api-v2 1.1.2+1997ad1260
	   |-- fabric-loot-tables-v1 1.1.4+e747827960
	   |-- fabric-mining-level-api-v1 2.1.6+cc71601c60
	   |-- fabric-models-v0 0.3.7+d7c144a860
	   |-- fabric-networking-api-v1 1.0.24+2d30af4b60
	   |-- fabric-networking-v0 0.3.11+b4f4f6cd60
	   |-- fabric-object-builder-api-v1 2.1.5+032c981d60
	   |-- fabric-particles-v1 0.2.13+526dc1ac60
	   |-- fabric-registry-sync-v0 0.9.12+bb2e047760
	   |-- fabric-renderer-api-v1 0.5.0+bf48649860
	   |-- fabric-renderer-indigo 0.6.1+03e2b68760
	   |-- fabric-renderer-registries-v1 3.2.12+b4f4f6cd60
	   |-- fabric-rendering-data-attachment-v1 0.3.9+ee3621fc60
	   |-- fabric-rendering-fluids-v1 2.0.3+54e5b2ec60
	   |-- fabric-rendering-v0 1.1.14+b4f4f6cd60
	   |-- fabric-rendering-v1 1.10.8+54e5b2ec60
	   |-- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660
	   |-- fabric-resource-loader-v0 0.5.3+047a5ecb60
	   |-- fabric-screen-api-v1 1.0.11+d882b91560
	   |-- fabric-screen-handler-api-v1 1.2.3+1f6558e860
	   |-- fabric-textures-v0 1.0.13+3ac43d9560
	   |-- fabric-transfer-api-v1 1.6.4+f4563ac860
	   \-- fabric-transitive-access-wideners-v1 1.1.0+e747827960
	- fabric-language-kotlin 1.9.0+kotlin.1.8.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1
	- fabricloader 0.14.19
	- fallingthrough 1.18.2-2.5
	- fallingtree 3.5.4
	- farmersdelight 1.18.2-1.2.5
	- fastload 1.5.9
	- ferritecore 4.2.1
	- finitewater 4.0-1.18.2
	- forgeconfigapiport 3.2.3
	- geckolib3 3.0.80
	   \-- com_eliotlash_mclib_mclib 20
	- gifts 1.18.1-1.1.0
	- iceberg 1.0.38
	- icommon 1.18
	- immersive_armors 1.5.2+1.18.2
	- immersive_weathering 1.18.2-3.0.2
	   \-- modmenu 3.2.3
	- impaled 1.1.3
	- incendium 5.0.4
	   \-- seedfix 1.0.2
	- invplus 1.1.1
	- itemphysiclite 1.5.0
	- java 20
	- krypton 0.1.9
	   \-- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT
	- lazydfu 0.1.2
	- libraryferret 4.0.0
	- mcwfences 1.0.7
	- medievalweapons 1.2.0
	   \-- reach-entity-attributes 2.1.1
	- memoryleakfix 1.0.0
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.6
	- minecraft 1.18.2
	- moderndynamics 0.2.6-beta
	   \-- team_reborn_energy 2.2.0
	- museumcurator 1.1.1
	- naturalist 1.1.1
	- nbtcrafting 2.2.3+mc1.18.2
	- netherportalspread 7.5
	- onceuponastroll 1.4.0
	- patchouli 1.18.2-71.1-FABRIC
	   \-- fiber 0.23.0-2
	- piercingpaxels 1.0.3+1.18.x
	- plasmo_voice 1.2.17
	- pollen 1.6.0
	   |-- cardinal-components-base 4.1.4
	   \-- cardinal-components-entity 4.1.4
	- polymorph 0.0.21-1.18.2
	   |-- cardinal-components-base 4.1.4
	   |-- cardinal-components-block 4.1.4
	   |-- cardinal-components-entity 4.1.4
	   \-- cardinal-components-item 4.1.4
	- potionblender 1.0.2
	- purpeille 2.3.3+fabric-1.18.2
	   |-- cmods 1.2.0
	   \-- voidcrafting 1.6.4+fabric-1.18.2
	- puzzleslib 3.3.5
	   |-- cardinal-components-base 4.1.4
	   \-- cardinal-components-entity 4.1.4
	- reborncore 5.2.1
	   \-- team_reborn_energy 2.2.0
	- riding_partners 1.0.0
	- seafoamsdyeableblocks 1.3.0
	- seasons 1.4-BETA+1.18
	- shoppy 1.0.5
	   |-- fabric-permissions-api-v0 0.1-SNAPSHOT
	   \-- octo-economy-api 1.1.0
	- simplyswords 1.40-1.18.2
	- sit 1.18.2-19
	- sound_physics_remastered 1.18.2-1.0.6
	- starlight 1.0.2+fabric.89b8d9f
	- structory 1.0.0
	- supermartijn642configlib 1.1.6
	- supermartijn642corelib 1.1.7
	- t_and_t 1.10.0.1
	   \-- blue_endless_jankson 1.2.1
	- techreborn 5.2.1
	   \-- team_reborn_energy 2.2.0
	- tinkerers-smithing 0.0.1
	- tree-hollows 1.3.3
	   \-- tree-hollows-core 1.3.3
	- trinkets 3.3.1
	- unstructured 0.4+1.18.2
	- vinery 1.1.4
	   \-- terraform-wood-api-v1 3.1.0
	- vmp 0.2.0+beta.3.120
	- waystones 10.2.0
	- wiredredstone 0.3.11+1.18.2
	   |-- graphlib 0.2.5+1.18.2
	   |-- libmultipart_deps_container 0.7.5-pre.0.2+kneelawk
	   |    |-- libblockattributes_core 0.10.2
	   |    |-- libmultipart 0.7.5-pre.0.2+kneelawk
	   |    \-- libnetworkstack 0.6.3
	   |-- lmp-compat 0.1.2+1.18.2
	   \-- team_reborn_energy 2.2.0
	- wolveswitharmor 1.7.1-1.18.2
	   |-- maybe-data 1.2.1-1.18.2
	   \-- static-content 1.0.1-1.16.2
	        \-- staticdata 1.1.2
	- woof 3.0.0-1.18
	   \-- advanced_runtime_resource_pack 0.5.7
	- wwoo 2.6.2+1.18.2
	- yungsapi 1.18.2-Fabric-2.2.9
	   \-- org_javassist_javassist 3.28.0-GA
	- yungsextras 1.18.2-Fabric-2.1.0

### Additional Context

The creator of the cardboard does not update the mod, and the server in the discord is gone.

**Comment by AkashiiKun** [comment]
You have Create Fabric 0.5.0i not 0.5.1a (apart that there's no such version for fabric).
Do not use Cardboard, here are the reasons why:
https://gist.github.com/Patbox/e44844294c358b614d347d369b0fc3bf
