### ISSUE TITLE
Entity models cant be rendered with canvas renderer

### ISSUE THREAD

**Issue by JieningYu** [Fabricators-of-Create/Create#94]
### Describe the Bug

Entity models cant be rendered when canvas renderer installed in any pipelines.
Switching Flywheel backend dosent take any  effort.

### Reproduction Steps

1.install canvas renderer
2.place a cogwheel

### Expected Result

Entity models should be rendered correctly

### Screenshots and Videos

<img width="854" alt="Screenshot@20220120161500" src="https://user-images.githubusercontent.com/61787533/150299689-8165e7c1-063b-4e59-8639-a6dfee279ca5.png">

### Operating System

macOS 12.2 Beta (21D5039d)

### Mod Version

0.4.0b

### Minecraft Version

1.18.1

### Other Mods

Canvas Renderer
Concurrent Chunk Management Engine
Fabric API
Flywheel
LazyDFU
Lithium
Mod Menu
Smooth Boot
Starlight(fixed so can be used with Create)

**Comment by JieningYu** [comment]
Will the "hacky canvas support" branch be merged into main branch?

**Comment by AlphaMode** [comment]
Probably not, its mostly just me playing around with canvas compat

**Comment by JieningYu** [comment]
Why it won't merge

**Comment by JieningYu** [comment]
Is there a proper date about supporting canvas?

**Comment by AlphaMode** [comment]
Canvas has recently released there flywheel compat which means this issue can Finally be closed. It's worth noting the there are plans to refactor flywheel.
