### ISSUE TITLE
Something is locking up our server?

### ISSUE THREAD

**Issue by ThePlagueDoctor** [Fabricators-of-Create/Create#940]
### Describe the Bug

We aren't exactly sure what's actually happening, can be just playing normally and things will crash. 

### Reproduction Steps

I'm not entirely sure to be honest! I was hoping the logs might tell but I don't know how to read them. 

### Expected Result

For things not to crash? (Sorry, not sure what to say here)

### Crash Report or Log

https://gist.github.com/ThePlagueDoctor/84c5f126c38fc39c4d1ffb8d902f497b

### Operating System

Windows Server

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Amethyst Core
Amethyst Imbuement
Architectury
Balm Fabric
BCLIB
Better End
Better Nether
Better Third Person
Bewitchment
Bewitchment Plus
Biome Makeover
BOMD
Bookshelf Fabric
Botania
Botany Pots
Cardinal Componets
Catalogue Fabric
Chimes
Cloth Config
Critters and Companions
Decorative Blocks
Duckling
Dungeons Arise
Elytra Physics
Elytraslot
Enhanctment Descriptions
Fabric API
Fabric Language
Falling Tree
Farmers Delight
Forge Config API Port
Fzzy Core
Gecko Lib Fabric
Hexcasting 
Immersive Pantings
Inmist Retextured
Iris MC
Jade
JEI
Journey Map
Lootr
MCDA
MCDAR
MCW Bridges
MCW Fences
MCW Lights
MCW Paintings
MCW Roofs
Moonlight
Mythic Metals
Mythic Metals Decorations
Mythic Mounts
Natures Compass
Nightlights
Oh the Biomes You'll Go
Origins
OWO Lib
Patchouli
Paucal
Pehkui
Puzzles Lib
Sodium 
Sound Physics
Terra Blender
Trinkets
Visual Workbench
Voicechat
Witches of Origins
Wraith Alloy Forgery
Wraith Waystones
Yungs API
Yungs Better Dungeons
Yungs Better Mineshafts
Yungs Better Strongholds
Yungs Bridges
Yungs Extras

**Comment by TropheusJ** [comment]
seems to be locking up when a player disconnects. Could you try that and see if that's true? If not, next time it happens, get another log with [this](https://modrinth.com/mod/fullstack-watchdog) installed.

**Comment by ThePlagueDoctor** [comment]
Alright, new log is:
https://gist.github.com/ThePlagueDoctor/578e33ab6d773d112119fc6c481f3d47

**Comment by TropheusJ** [comment]
seems to be stuck in loading a class from a file. I am pretty confident this is not a Create issue. Is it fixed when it's removed?

**Comment by ThePlagueDoctor** [comment]
I can confirm that the issue goes away if we remove Create.

**Comment by IThundxr** [comment]
If this still occurs feel free to open a new issue
