### ISSUE TITLE
Belt (i think) is crashing server whenever its chunks are loaded

### ISSUE THREAD

**Issue by SuccBT** [Fabricators-of-Create/Create#941]
### Describe the Bug

Someone on my server was building a device to put ore from a belt into crushing wheels and when they sped-up the belt the server crashed  and will now crash whenever the chunks around the belt are loaded.

### Reproduction Steps

1. Walk near area with the device
2. crash

### Expected Result

The chunks around the belt should not crash the server and just work normally

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/127024548/9ece2ecc-4e4b-456d-afdb-cba7b4c71fa6)

### Crash Report or Log

https://pastebin.com/AqYPvj0d

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/127024548/c3973b21-e29c-4083-8933-0f397abdb65d)

**Comment by electricsteve** [comment]
can you narrow it down by removing the funnel above the crushing wheel? it has something to do with the interaction between ufnnels and belts.

**Comment by TropheusJ** [comment]
This is a weird rare issue that can't really be reproduced. I've added an extra check that may catch it if it ever happens again.
