### ISSUE TITLE
Map update packet causes error

### ISSUE THREAD

**Issue by Elzeha** [Fabricators-of-Create/Create#943]
### Describe the Bug

Receiving the following when I try and enter into my server, originally it was working fine with other mods but now seeing this error
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(16397) + length(1) exceeds writerIndex(16397): PooledUnsafeDirectByteBuf(ridx: 16397, widx: 16397, cap: 16397)

### Reproduction Steps

1.Open minecraft with mods
2.connect to server

### Expected Result

Able to connect to server

### Screenshots and Videos

Logs:https://pastebin.com/ZG7wFMVZ

### Operating System

Windows 11

### Mod Version

0.5.1a

### Minecraft Version

1.19.2

### Other Mods

https://www.curseforge.com/minecraft/modpacks/better-mc-fabric modpack 17.5hf (everything was working fine for a bit then is not)

### Additional Context

Other people seem to be able to login it is only affecting my client (have tried full reinstalling everything with no luck

**Comment by cwse1** [comment]
are you admin on your server? i had a similar problem and the fix was killing item entities in the console. for some reason there were 93,000+ item entities bricking the game. not sure why tho

**Comment by DarianLStephens** [comment]
Woah, that sounds similar to a problem I had on my server.
Some part of the world had ballooned in size to several dozen megabytes, to the point where the game started saving entities separately from the chunk.
Thankfully, this allowed me to delete that file and let that part of the world load normally again without affecting people's bases, but we never found the root cause of it.
The best guess we have is that it _might_ have been caused by some weirdness chunkloading some items being thrown in to a disposal lavafall?

**Comment by TropheusJ** [comment]
Happens when updating a map

**Comment by TropheusJ** [comment]
Create modifies the map update packet, so this is probably a conflict with another mod also doing that

**Comment by cwse1** [comment]
> Create modifies the map update packet, so this is probably a conflict with another mod also doing that

im only playing with a few mods my thoughts are that maybe it has to do with the caffeineMC mods im using in fabric 1.19.2?

**Comment by TropheusJ** [comment]
definitely not. mod list might help

**Comment by cwse1** [comment]
create-fabric-0.5.0.i-1003+1.19.2.jar      ferritecore-5.0.3-fabric.jar        memoryleakfix-fabric-1.17+-1.0.0.jar
Decorative+Blocks-fabric-1.19.2-3.0.0.jar  krypton-0.2.1.jar                   starlight-1.1.1+fabric.ae22326.jar
fabric-api-0.76.0+1.19.2.jar               lithium-fabric-mc1.19.2-0.11.1.jar  Steam_Rails-1.2.6+fabric-mc1.19.2.jar

these are the server side mods, i cant access my client side mods at the moment but if they are necessary i can send them

**Comment by IThundxr** [comment]
I'm closing this assuming it's fixed, if it isn't feel free to open a new issue
