### ISSUE TITLE
Crash by Schematicannon involving Mechanical Pump and dimension switching

### ISSUE THREAD

**Issue by Davvv1** [Fabricators-of-Create/Create#944]
### Describe the Bug

it is a crash involving the Schematicannon, traveling between dimensions, and the Mechanical Pump

### Reproduction Steps

1. Retrieve a Schematicannon
2. Produce a filled schematic with a Mechanical Pump as part of the schematic loaded
3. Start the Schematicannon with said schematic
4. Provide the Schematicannon with all the items required except the Mechanical Pump
5. Exit the dimension once the Schematicannon is looking for the Mechanical Pump
6. Return to the dimension the Schematicannon is in
7. Provide the Schematicannon with the Mechanical Pump
8. Stop the Schematicannon, and restart it
9. Crash

If it didn't crash, try producing the bug within the Dimensional Quartz Door dimension provided by the Dimensional Doors mod

### Expected Result

I expected the Schematicannon to restart normally.

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/110253374/8f3f9367-ac69-4d0d-96b5-ed62b5f0080a

### Crash Report or Log

https://gist.github.com/Davvv1/5d24e6ae2774a4afa244ab110f63898a

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

_**All mods are for MC version 1.19(.2) and the Fabric mod loader**_
Appleskin 2.4.1
Couplings 1.9.1
[Create Crafts & Additions 20230508b](https://www.curseforge.com/minecraft/mc-mods/createaddition/files/4528919)
Create 0.5.0.i
Dimensional Doors 5.0.2
Equipment Compare 1.3.1
Fabric API 0.76.0
Iceberg 1.0.46
Illuminations 1.10.11
Indium 1.0.9
JEI 11.6.0.1015
Legendary Tooltips 1.3.3
Map Atlases 2.3.1
Physics Mod 2.12.3
Prism 1.0.3
Sodium 0.4.4
Sound Physics Remastered 1.0.18

### Additional Context

Fabric Version: 0.14.20
The Mechanical Pump is placed after loading the save again.

**Comment by electricsteve** [comment]
can you disable/delete indium and try again, maybe that fixes it.

**Comment by TropheusJ** [comment]
This has been fixed in dev
