### ISSUE TITLE
Following up to version 0.5.1 Forge, the latest version of Forge can create elevators, but Fabric cannot

### ISSUE THREAD

**Issue by YxlNotFound** [Fabricators-of-Create/Create#945]
### Describe the Suggestion

Following up to version 0.5.1 Forge, the latest version of Forge can create elevators, but Fabric cannot

### Screenshots and Videos

Following up to version 0.5.1 Forge, the latest version of Forge can create elevators, but Fabric cannot

### Additional Context

Following up to version 0.5.1 Forge, the latest version of Forge can create elevators, but Fabric cannot

**Comment by cisc0disco** [comment]
No shit, it's not been ported yet. Do you know how much time it takes?
