### ISSUE TITLE
Deployer doesn't deal sweeping damage

### ISSUE THREAD

**Issue by liadinon** [Fabricators-of-Create/Create#946]
### Describe the Bug

Deployer doesn't deal sweeping damage, and only hit one target at a time

### Reproduction Steps

Try to attack multiple targets on the same block with a deployer

### Expected Result

That the deployer would deal sweeping damage

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
same as forge

**Comment by TropheusJ** [comment]
Issues that occur on Forge as well are no longer being tracked on this repo. Please follow the respective issue on the Forge repo instead: https://github.com/Creators-of-Create/Create/issues/5142
