### ISSUE TITLE
[1.19.2] [Client Crash] NPE on Create Track logistic

### ISSUE THREAD

**Issue by suerion** [Fabricators-of-Create/Create#947]
### Describe the Bug

Don't get the error again, don't know how to reproduce. Only one Crash report

### Reproduction Steps

Only Playing on Server with Create Modpack

### Expected Result

Don't Crash

### Crash Report or Log

https://pastebin.com/qiufudnk

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by IThundxr** [comment]
Fixed in https://github.com/Creators-of-Create/Create/commit/7f60ae95f6e97d8fbae292ea34b1cc12223ba02d
