### ISSUE TITLE
complete server / client crash when pasting schematicannons with schematicannons

### ISSUE THREAD

**Issue by gabgab01** [Fabricators-of-Create/Create#949]
### Describe the Bug

trying to paste a blueprint containing a schematicannon with a schematicannon will crash the game, sometimes so far that it also corrupts the world as teh schematicannon keeps trying to place the block on game load

### Reproduction Steps

1. make a new schematic containing a schematicannon
2. put a schematic of that into an existing schematicannon
3. start the schematicannon
...
profit?

### Expected Result

the schematicannon should place the schematicannon without issue, or at bleast skip iti f this action is illegal

### Crash Report or Log

https://pastebin.com/C7cjtqJ2

### Operating System

Windows

### Mod Version

0.5.0i

### Minecraft Version

1.18.2

### Other Mods

hermit builders create on modrinth

**Comment by gabgab01** [comment]
on our own private server, this bug managed to corrupt the save so hard that the server now instantly crashes on startup, meaning we currently can't really play anymore

**Comment by electricsteve** [comment]
maybe you could try to delete the chunck file or smt?

**Comment by gabgab01** [comment]
> maybe you could try to delete the chunck file or smt?

we ended up loading a backup. i'm more worried about other people encountering this bug and accidentally deleting the world.
also the shcematicannon was in a different chunk than the schematic, so you might have to delete multiple chunks, which sucks if you already got some heavy infrastructure built there

**Comment by electricsteve** [comment]
yea, i think there are ways to just delete blocks.

**Comment by TropheusJ** [comment]
This should be fixed in 0.5.1
