### ISSUE TITLE
Incompatibility with Starlight 1.0.0

### ISSUE THREAD

**Issue by RedWideWeb** [Fabricators-of-Create/Create#95]
### Describe the Bug

Game crashed when Flywheel objects are placed in the world.

### Reproduction Steps

1. Install required mods
2. Launch game and enter a world
3. Place any block from Create

### Expected Result

Blocks are placed and rendered properly

### Crash Report or Log

https://gist.github.com/RedWideWeb/2a57fa4b04127c6aef19b50744bb5ca5

### Operating System

Windows 10 1809

### Mod Version

0.4.0b

### Minecraft Version

1.18.1

### Other Mods

Fabric API 0.46.1
Starlight 1.0.0

**Comment by AeiouEnigma** [comment]
Update Starlight to 1.0.1.

**Comment by AeiouEnigma** [comment]
Which is available only on CurseForge: https://www.curseforge.com/minecraft/mc-mods/starlight/files/3599857

**Comment by RedWideWeb** [comment]
> Which is available only on CurseForge: https://www.curseforge.com/minecraft/mc-mods/starlight/files/3599857

THANK YOU!
