### ISSUE TITLE
Mod description page on modrinth gives a dead link

### ISSUE THREAD

**Issue by PRO-2684** [Fabricators-of-Create/Create#950]
If you visit [mod description page on modrinth](https://modrinth.com/mod/create-fabric), and click the "[REI](https://modrinth.com/mod/roughly-enough-items)" link at "About" section, you'd get an error. It seems that REI has changed their project id. (from `roughly-enough-items` to `rei`)

You might want to update the link to this: https://modrinth.com/mod/rei.

**Comment by electricsteve** [comment]
TropheusJ is currently finalizing the 0.5.1 update, so after that i think he has time.

**Comment by TropheusJ** [comment]
fixed
