### ISSUE TITLE
1.19.2 Quilt Crash on Startup

### ISSUE THREAD

**Issue by dogman309** [Fabricators-of-Create/Create#952]
### Describe the Bug

Game crashes on startup.
this is the exit code I get.
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create'! 

### Reproduction Steps

1. download quilt
2. download create
3. other mods
4. open quilt launcher
5.wait for crash
6.it crashes
...

### Expected Result

i expected it to not crash

### Screenshots and Videos

![mods2](https://github.com/Fabricators-of-Create/Create/assets/135499242/053a8dfa-8ac8-49e2-882b-4f9afe91cf5c)

### Crash Report or Log

https://pastebin.com/Zh98E47G

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

jpg of mods folder

**Comment by Sunconure11** [comment]
https://github.com/Fabricators-of-Create/Porting-Lib/issues/49

By any chance, could this be connected?

**Comment by dogman309** [comment]
No idea, sorry. Still don't have a fix for my issue anyways.

**Comment by electricsteve** [comment]
Maybe ferrritcore has smt to do with it, remove it and try again.

**Comment by dogman309** [comment]
That fixed the issue with the crash, but now I have an issue where the game doesn't load, instead getting stuck on this screen. (I waited over an hour before alt f4ing)

**Comment by dogman309** [comment]
![mojanbg](https://github.com/Fabricators-of-Create/Create/assets/135499242/e9dc33d7-6c1c-4f94-8ddc-d91572fdec75)

**Comment by electricsteve** [comment]
can you send your latest.log?

**Comment by dogman309** [comment]
The game didn't crash in this instance, so there isn't a crash log

**Comment by dogman309** [comment]
It just got stuck loading

**Comment by ZestyBlaze** [comment]
Still send your latest.log from that loading. It will still be logging events during startup and if its failing a startup (Even if not crashing), it will still log what's wrong

**Comment by electricsteve** [comment]
yea the crashes are located in Crash-Reports, the latest.log is located in logs. So please send it

**Comment by dogman309** [comment]
My bad, but the only issue is the latest.log is literally too big for notepad to open lmao. It's 1.5 gb

**Comment by electricsteve** [comment]
then you have run minecraft for too long. Launch minecraft and if you get stuck on the loading screen just wait 5 minutes then quit. in the instance folder you need to look at the latest.log and if it's still too big, just upload the file to something like pastebin and share the link with us.

**Comment by dogman309** [comment]
I don't have access to my pc atm but will get the latest.log file asap. Thanks for bearing with me!

**Comment by dogman309** [comment]
https://pastebin.com/81BrpRJ1  This is everything from the latest.log up until minecraft launched and I had to alt f4 (it gets stuck on the red mojang loading screen). If I need to let it run longer lmk.

**Comment by electricsteve** [comment]
looks like it works fine, but it's just taking long to start. may I ask how much RAM you have allocated and how much RAM your system has. I have loading times of over 15 minutes on heavy modpacks all the time.

**Comment by dogman309** [comment]
It's definitely not just a long load time. I let it load overnight and still was stuck on just a red mojang loading screen after 9+ hours.... I'll try and get a more accurate latest.log

**Comment by dogman309** [comment]
https://gist.github.com/dogman309/f5197f9c5e44d41554de61cb4485f462  This might be more clear, not sure

**Comment by dogman309** [comment]
Also it shouldn't be a RAM issue I don't think, I have 40gb in my pc and have allocated 16

**Comment by electricsteve** [comment]
Ok, well first: you should NEVER allocate over 8 GB RAM (unless you allocate for a server). second: can you send the log from the 9 hour wait? cause in the log you sent you closed it just 1 minute after the last thing was loaded/happened.

**Comment by dogman309** [comment]
I can try and get the 9 hour log but the file size is so big it doesn't open in notebook, and probably will be too long for any kind of pastebin alternative. I can maybe get the last lines though to see where the error is. Also, for what it's worth I'm almost positive I closed it at around 12:05 after that last update at 11:59.

**Comment by electricsteve** [comment]
Hmmmm...... For the reason that the log is so big, i'm thinking that OR it has too many things to load (what isn't likely) OR it's constantly spitting out errors. Maybe you could try uploading the file to a site overnight.

**Comment by TropheusJ** [comment]
Is it fixed if you remove Create?

**Comment by dogman309** [comment]
Yeah, I've decided to just play without it for the time being

**Comment by TropheusJ** [comment]
is this still an issue? make sure everything is fully up to date.

**Comment by TropheusJ** [comment]
this is old, there's no leads, and no updates. closing
