### ISSUE TITLE
Crash with Improved Signs

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Fabricators-of-Create/Create#954]
### Describe the Bug

If a sign is part of one of Create Fabric's moving block formation entities (tested gantry and minecart contraptions), and that entity becomes blocks again while a block is in the space where the sign will be placed, the game crashes.

### Reproduction Steps

1) place a rail
2) place a minecart assembler
3) place a minecart in the assembler
4) place a lever on the side of the assembler
5) place a sign on top of the assembler
6) pull the lever to assembler the contraption
7) place any block on top of the assembler (inside the entity form of the sign)
8) pull the lever again

This causes the game to crash.

### Expected Result

The game doesn't crash

### Crash Report or Log

https://paste.myst.rs/nne33a9a

### Operating System

Windows 10

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

fabric-api 0.76.0+1.19.2
improved-signs 1.2.0

### Additional Context

Corresponding issue on Improved Sign's github project: https://github.com/CraftyCorvid/ImprovedSigns/issues/31

**Comment by electricsteve** [comment]
I think the game is trying to break the sign and doesn't know what text is on the sign and improved signs has a thing where if you break a sign it retains it's text so it just crashes. Idk if its a thing on their end or create's end.

**Comment by TropheusJ** [comment]
Commented on the other issue. Create can't fix this.
