### ISSUE TITLE
Train Track & Metal Girder Setup

### ISSUE THREAD

**Issue by SvCpu** [Fabricators-of-Create/Create#957]
### Describe the Bug

This is what I have tried dozens of times
![image](https://github.com/Fabricators-of-Create/Create/assets/38872133/f656163e-9a34-4108-9093-a642949a7912)
This is what happens most of the time when I put Metal Girder in the off-hand position and place Train Track
![image](https://github.com/Fabricators-of-Create/Create/assets/38872133/ec6ef81e-7c6d-4c94-b68e-6f88d0eb7575)
I tried holding down the ctrl key but it didn't work as expected

Can someone tell me what should I do to make him achieve the effect of photo1?
I submitted this issue on Forge version create Mod lssues
But this problem seems to only happen in the fabric version
https://github.com/Creators-of-Create/Create/issues/4945#issue-1754676690

### Reproduction Steps

look "Describe the Bug"

### Expected Result

look "Describe the Bug"

### Operating System

Win 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

**Comment by electricsteve** [comment]
Turn shaders off and try without performance optimization mods.

**Comment by TropheusJ** [comment]
this also occurs on forge

**Comment by IThundxr** [comment]
Upstream issue made at: https://github.com/Creators-of-Create/Create/issues/6113
