### ISSUE TITLE
Minecraft Create Mod 10 fps on iMac with AMD GPU

### ISSUE THREAD

**Issue by dan55304** [Fabricators-of-Create/Create#958]
### Describe the Bug

I'm including screenshots for the world with no create contraption and 1 contraption for each device. I also included a shot of my Mods.

My setup:
Windows 10 running Minecraft 1.19.2 server running create-fabric-0.5.0.i-1003+1.19.2. 
Dell Optiplex, see images Dell a and Dell b where I ran Minecraft client and server on the same machine
iMac 27 with NVIDIA GPU, see images iMac 27a a and iMac27a b 
iMac 27 with AMD GPU, see images iMac27b a and iMac27b b
MacBook Pro, see images MacBook a and MacBook b 

All computers except the iMac27 with AMD GPU can stay around 60 fps with a single create contraption. The iMac27 with AMD drops to below 10 fps but it is also the fastest computer with the best GPU. It gets over 100 fps with no create contraption deployed.

I have removed all mods except fabric and create with the same results. I’ve also adjusted java ram to no effect. Sodium makes some difference but only brings it up to about 13 fps.

### Reproduction Steps

1. Run on computer with AMD GPU
2.Deploy one contraption. Mine was a 8x8 drill
3.
...

### Expected Result

fps would not go from 100+ to 10 fps

### Screenshots and Videos

![Dell a](https://github.com/Fabricators-of-Create/Create/assets/1891134/a1117e04-b16b-4e3a-8c3c-1c82aeaccfd1)
![Dell b](https://github.com/Fabricators-of-Create/Create/assets/1891134/aa6a0817-139a-4c5a-acd7-d40582a35a81)
![iMac 27a a](https://github.com/Fabricators-of-Create/Create/assets/1891134/95a8b60a-9809-4032-acf9-a8f3012e2a95)
![iMac 27a b](https://github.com/Fabricators-of-Create/Create/assets/1891134/02792606-4731-4a2e-8790-1a38c4033624)
<img width="1168" alt="iMac 27b a" src="https://github.com/Fabricators-of-Create/Create/assets/1891134/5bbb10df-6cf3-4244-9e88-d53ca3562f22">
<img width="1165" alt="iMac 27b b" src="https://github.com/Fabricators-of-Create/Create/assets/1891134/71403eea-935b-4daa-8461-f22fa3902529">
<img width="1305" alt="MacBook a" src="https://github.com/Fabricators-of-Create/Create/assets/1891134/5d61bf55-f528-4ce0-b4a9-ebe43491e4aa">
<img width="1304" alt="MacBook b" src="https://github.com/Fabricators-of-Create/Create/assets/1891134/f9d9e500-9867-4085-9dca-f67fd8285222">
<img width="886" alt="Mods" src="https://github.com/Fabricators-of-Create/Create/assets/1891134/a44426fe-0289-4fb5-9b7e-acb72d367def">

### Operating System

MacOS 13.3.1

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

sodium-fabric-mc1.19.2-0.4.4+build.18.jar
modmenu-4.1.2.jar
RoughlyEnoughItems-9.1.595.jar
light-overlay-7.0.0.jar
indium-1.0.9+mc1.19.2.jar
freecam-modrinth-1.1.6+1.19.jar
fabric-api-0.76.0+1.19.2.jar
fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar
create-fabric-0.5.0.i-1003+1.19.2.jar
cloth-config-8.2.88-fabric.jar
architectury-6.5.77-fabric.jar

**Comment by electricsteve** [comment]
first, turn vsync off and see the video settings and send screenshot. If you have a second screen, check that it is plugged into the right port. And your describing of the machines and the screenshots from them is really bad.

**Comment by TropheusJ** [comment]
try `/flywheel backend batching`

**Comment by ShadowRocks2** [comment]
> try `/flywheel backend batching`

this has greatly helped my amd gpu fps in the past

**Comment by dan55304** [comment]
> first, turn vsync off and see the video settings and send screenshot. If you have a second screen, check that it is plugged into the right port. And your describing of the machines and the screenshots from them is really bad.

I had tried vsync before with no success. I don't understand the second screen comment for Macs. I also don't understand your machines and screenshots bad comment either.

**Comment by dan55304** [comment]
> try `/flywheel backend batching

Thanks for the help!

I executed this on the client and my fps went from 9 to 83 with a Create contraption in place. Removing the contraption brought me back to 120 fps. This seems to be working but I'd appreciate further help.
* Any explanation of what this does regarding AMD GPUs? IOW, did this help?
* Is there a way to automate issuing this command or is it a one-time thing?

**Comment by TropheusJ** [comment]
batching is sometimes better on amd

**Comment by ShadowRocks2** [comment]
> 

im pretty sure its permanent, atleast for that profile

**Comment by dan55304** [comment]
Thanks folks for the help. I saw another AMD owner post a request for help with low fps. I passed on the flywheel command. It would be nice if folks didn't have to spend days/weeks looking for an answer like I did. Still, I don't know if there's anything that can be done code-wise to make it easier for AMD owners.

**Comment by electricsteve** [comment]
maybe by displaying it as tip or in video settings or smt

**Comment by TropheusJ** [comment]
I think this is more an issue with flywheel, closing
