### ISSUE TITLE
Schematic Cannon Crashes Game - placing copper pipes

### ISSUE THREAD

**Issue by corfoto4** [Fabricators-of-Create/Create#959]
### Describe the Bug

The minecraft game crashes when the schematic cannon tries to place copper pipes

### Reproduction Steps

1. Create a schematic with copper pipes.
2. Use the cannon to place the schematic.
3. Game crashes

### Expected Result

Game does not crash and pipe is placed.

### Crash Report or Log

https://pastebin.com/wTjcEMLN

### Operating System

Windows 11

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Ambient Sounds
Appleskin
Applied Energistics
Architectury
Backpacked
Balm
Better F3
Camera
Chat Heads
Chipped
Chunky
cloth-config
Clumps
Colourful Azaleas
Configured
Controlling
Corpse
Crafting Tweaks
Create
Creative Core
ctm-refabricated
Decorative Blocks
Dynamic FPS
Enhanced Block Entities
Entity Culling
Fabric API
Kotlin
Farmers Delight
Farmers Respite
Fastload
Ferrite COre
Framework
Immediately Fast
Indium
Iris
Jade
Krypton
Kubejs
Lamb Dynamic Lights
Lazydfu
Lithium
Memory Leak Fix
Mod Menu
Moonlight
Mouse Tweaks
Powah
Sodium
rer-2.6.0.jar
Resourcefullib
Rhino
REI
Shulker Box tool tip
Slice and Dice
Smooth Swapping
Smooth Boost
Sodium Extra
Starlight
Steam-n-rails
Supplementaries
Terralith
Trinkets
Voicechat
Xaeros Minimap
Xaeros World Map

**Comment by Flyte-less** [comment]
Can confirm this issue exists with only Create and Fabric API loaded. Pumps will also cause a crash when launched from the cannon.

My log: https://mclo.gs/hWbfg90

**Comment by corfoto4** [comment]
Yes, I found this too last night. I removed the pipes from my schematic but left the pumps. Game still crashed

**Comment by TropheusJ** [comment]
this will be fixed in 0.5.1
