### ISSUE TITLE
Sodium Rendering issues

### ISSUE THREAD

**Issue by RedWideWeb** [Fabricators-of-Create/Create#96]
### Describe the Bug

Overall contraptions are handled poorly right now. All Flywheel based objects seem to have duplicated model and it's clearly see-able in motion.

/flywheel backend is off

### Reproduction Steps

1. Construct windmill with sails
2. Right click it to start moving
3. Massive frame drops and strangely rendered model
...

### Expected Result

Normal rendering

### Screenshots and Videos

![2022-01-21_00 07 39_2](https://user-images.githubusercontent.com/58992150/150431842-64ee28ea-670d-42ad-9cb4-a0d785c787da.png)

### Operating System

Windows 10 1809

### Mod Version

0.4.0b

### Minecraft Version

1.18.1

### Other Mods

Fabric API 0.46.1
Sodium 0.4.0 Alpha 6 Build 14

**Comment by AeiouEnigma** [comment]
Is this issue present when using Indium?

**Comment by RedWideWeb** [comment]
> Is this issue present when using Indium?

Haven’t tried it. Didn’t know it’s a thing

**Comment by RedWideWeb** [comment]
Also please add 0.4.0c version in bug report wizard

**Comment by DarianLStephens** [comment]
I just so happen to be using Indium, and everything seems to render perfectly normally, even in Ponder mode.

**Comment by RedWideWeb** [comment]
No issues with Indium. On the same contraption from screenshot got 15 fps.

**Comment by AeiouEnigma** [comment]
> Also please add 0.4.0c version in bug report wizard

We have a strict policy that any change which should also be implemented upstream (on the Forge version) will not be implemented here first. We wait until we can merge Forge changes.

Fortunately we've just done that, and you can now select version 0.4.0c when opening an issue :)

**Comment by RedWideWeb** [comment]
> > Also please add 0.4.0c version in bug report wizard
> 
> We have a strict policy that any change which should also be implemented upstream (on the Forge version) will not be implemented here first. We wait until we can merge Forge changes.
> 
> Fortunately we've just done that, and you can now select version 0.4.0c when opening an issue :)

Haha, nice. If Forge are Slowpokes doesn’t mean we need to be :) 

And thanks a lot❤️
