### ISSUE TITLE
Mechanical Crafter dupe

### ISSUE THREAD

**Issue by Chubblezap** [Fabricators-of-Create/Create#962]
### Describe the Bug

When a mechanical crafter successfully crafts and item, but doesn't have a proper output container and drops it on the floor, unloading and reloading the area causes another of the output item to appear on the floor. Tested and this did not happen when an output container was present.

### Reproduction Steps

1. Craft something in the mechanical crafter (tested with Extendo Grip outputting at the bottom-most block, into the floor)
2. Pick up the item
3. Leave the area, far enough to unload the chunk
4. Return, there should be another crafted item on the floor

### Expected Result

No duplicate item, I assume the crafter is for some reason still holding the data from the uncrafted items

### Operating System

CentOS 8 Stream / Rocky Linux 8 (server)

### Mod Version

0.5.0i

### Minecraft Version

1.19.2

### Other Mods

Servercore may affect it due to limiting various tick ranges, but no other mods are involved in the interaction and all of the crafting is done in the immediate area, so it shouldn't be unloading anything pre-emptively.

### Additional Context

The crafter was the minimum shape to build the extendo grip, outputting down from the bottom-most block into stone (thus dropping on the floor)

**Comment by electricsteve** [comment]
Can you provide the latest.log?

**Comment by TropheusJ** [comment]
can't reproduce, maybe fixed already
