### ISSUE TITLE
Underwater rendering bug and no underwater fog

### ISSUE THREAD

**Issue by hewxle** [Fabricators-of-Create/Create#967]
### Describe the Bug

In any gamemode but spectator mode, there is no underwater fog and there are visual bugs with nearby chunks (within the render distance). They fade in very slowly and the render distance considerably drops.

There are similar issues when using Sodium 0.4.4 + Indium 1.0.9 except the chunks pop in instead of the slow fade.

On Forge with Create 0.5.1.b, there is also no water fog (?) but there is not a render distance/terrain loading issue.

### Reproduction Steps

1. Enter water in creative, survival, or adventure mode.
2. There will be no fog and rendering bugs.

### Expected Result

Expect underwater rendering to appear as it does in vanilla (which seems to be matched by spectator mode even with this bug).

### Screenshots and Videos

Creative mode:
![image](https://github.com/Fabricators-of-Create/Create/assets/109231756/08b1efef-1596-45cc-905e-12cc51008090)

Survival mode:
![image](https://github.com/Fabricators-of-Create/Create/assets/109231756/158410ef-4d06-4740-a7eb-62687fcab977)

Spectator mode:
![image](https://github.com/Fabricators-of-Create/Create/assets/109231756/7c27066d-a5a4-435b-96dd-5e8af6c26d21)

### Crash Report or Log

https://0x0.st/HQHS.txt

### Operating System

Linux

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

Fabric API

### Additional Context

The same issue does not occur with Create Fabric 0.5.0.i Patch 6.

**Comment by hewxle** [comment]
Possibly related to https://github.com/Creators-of-Create/Create/issues/4826; see this issue for more details.

**Comment by ghost** [comment]
the fog is a create bug but the rendering one you need to disable fog occlusion or something similar, it makes chunks that should be covered by fog not render

**Comment by Sprillet** [comment]
I think it's caused by the new lava diving gear, because it gives you visibility in lava :P

**Comment by electricsteve** [comment]
> I think it's caused by the new lava diving gear, because it gives you visibility in lava :P

probably first look in the forge issue before commenting this

**Comment by pyrosparker** [comment]
With only Quilt, QFAPI and Create involved, and with no items equipped in any of the shots:
![create_water_vision_bug](https://github.com/Fabricators-of-Create/Create/assets/388677/782daa0f-07be-491b-93a2-3d50fa37f3b8)

The odd culling can be seen here in addition to the lack of fog. It doesn't appear the Forge issues had the culling problem, perhaps just the lack-of-fog problem.
