### ISSUE TITLE
5.1 Patch 1 Crashes with Crafts and Additions 20230508b

### ISSUE THREAD

**Issue by 1215-tech** [Fabricators-of-Create/Create#968]
### Describe the Bug

The name lol, crash report linked. I'm not sure it's because crafts and additions, but the report mentions it. 

### Reproduction Steps

1. Updated from 0.5.0 Patch 6 to 0.5.1 Patch 1
2. Launched and got the report linked 
3. Rolled back to 0.5.0 6 everything is fine again 

### Expected Result

Well not to crash with crafts and additons I guess

### Crash Report or Log

https://pastebin.com/bnyHqG5G

### Operating System

Windows 11

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

**Comment by TropheusJ** [comment]
all addons are going to need updating

**Comment by 1215-tech** [comment]
Got it, thanks!
