### ISSUE TITLE
[Iris compatibility] Contraptions do not render properly when shader shadows are enabled

### ISSUE THREAD

**Issue by AeiouEnigma** [Fabricators-of-Create/Create#97]
Not sure of the best way to word the title. Some shaderpacks completely break contraption rendering. In some cases, this can be 'resolved' by disabling shadows if the shaderpack offers an option to do so.

**Comment by AeiouEnigma** [comment]
Complementary shaders is probably a good shaderpack to use for troubleshooting of this issue.

**Comment by RedWideWeb** [comment]
> Complementary shaders is probably a good shaderpack to use for troubleshooting of this issue.

Definitely

**Comment by sybershot** [comment]
Can confirm the issue.
Using any shaderpack with shadows enabled makes multiblock Entity contraptions disappear. Iris 1.2.0 allows turning all shadows off for the current shaderpack. 

**Mods used:**
- Create 0.4c, build 347;
- Sodium 0.4.0-alpha-6;
- Sodium Extra 0.3.8;
- Iris 1.2.0;
- Indium 1.0.2-alpha-2;
- Phosphor 0.8.1.

**Shaderpacks tested:**
- BSL_v7.2.01pre2;
- Continuum 2.0.4;
- Prismarine 4.0a (rewrite stage 4);
- ProjectLUMA v1.32;
- Sildur's Vibrant Shaders v1.32 Medium;
- Sildur's Enhanced Default v.1.131 Fancy.
![2022-01-22_09 57 13](https://user-images.githubusercontent.com/5563058/150628902-46db6872-eb49-4975-883b-a7db66e16ab8.png)
![2022-01-22_09 59 36](https://user-images.githubusercontent.com/5563058/150628903-0b5f1b5d-a8f4-4e66-aa97-3ac23bdf57f2.png)

**Comment by sybershot** [comment]
This behavior also applies to ponder mechanic. I did not create separate issues as they have common root cause.

**Comment by mixolydianmel** [comment]
I  have done some more testing for this issue.

(1) Without Indium installed, the behaviour changes; Without shaders on, the shaft appears to rotate, but there is also a copy of it
in the same location that does not. This is not the case for gearboxes, which seem to work fine without duplicate model components.
![2022-01-27_12 54 56](https://user-images.githubusercontent.com/62853938/151416820-2668e6ba-6891-4e35-8fdd-2f3837d0d4f2.png)
![2022-01-27_12 54 54](https://user-images.githubusercontent.com/62853938/151416884-e31e124f-1f22-43f3-9e01-56aae43e1f13.png)
There is z-fighting on the ends of these that is not visible in the images.

(2) With the same configuration, turning shaders on results in the rotating copy of the shaft disappearing, leaving only the static copy. On a gearbox, this looks like the little rotating mini-shafts completely disappearing, but leaving the rest of the gearbox model present.
![2022-01-27_12 55 02](https://user-images.githubusercontent.com/62853938/151417178-5a14bb81-76cd-4109-a631-799e4680d051.png)
This is a static shaft; it doesn't move.

(3) Once turning shaders off again, the rotating copies still are not present. This persists through block updates, unloading/loading the chunks, and logging out/into the world. The only way to get them to rotate again is to replace them.
![2022-01-27_12 55 06](https://user-images.githubusercontent.com/62853938/151417440-e5b6b6cb-4419-4409-9489-ac5767e461ca.png)
The same static shaft, but with shaders off. This persisted until a replacement of the block.

Additionally, updating a line of shafts does not result in them starting to turn; each shaft must be replaced individually.

Hope this helps!

**Comment by mixolydianmel** [comment]
I have also just tested this with sails.

Following the same process, I get:

Shaders off —
![2022-01-27_13 08 26](https://user-images.githubusercontent.com/62853938/151418361-cde42eaa-15c2-4ef4-b2c0-cc85e095fd15.png)
Shaders on —
![2022-01-27_13 08 33](https://user-images.githubusercontent.com/62853938/151418419-17acf7d4-ffb8-44e9-8491-84e6b04185dd.png)
Shaders off again —
![2022-01-27_13 08 47](https://user-images.githubusercontent.com/62853938/151418447-0f3fb0d8-3ae5-44d2-8e6c-787a804a3e89.png)

**Comment by AeiouEnigma** [comment]
Thank you for your testing, but I feel that we're at a point where we fully understand the nature of these issues. You don't have to keep testing 😄

**Comment by mixolydianmel** [comment]
Cool, just thought I'd post my findings :\)

**Comment by JieningYu** [comment]
> I have also just tested this with sails.
> 
> Following the same process, I get:
> 
> Shaders off — ![2022-01-27_13 08 26](https://user-images.githubusercontent.com/62853938/151418361-cde42eaa-15c2-4ef4-b2c0-cc85e095fd15.png) Shaders on — ![2022-01-27_13 08 33](https://user-images.githubusercontent.com/62853938/151418419-17acf7d4-ffb8-44e9-8491-84e6b04185dd.png) Shaders off again — ![2022-01-27_13 08 47](https://user-images.githubusercontent.com/62853938/151418447-0f3fb0d8-3ae5-44d2-8e6c-787a804a3e89.png)

Probably caused by this(
https://github.com/Fabricators-of-Create/Create/issues/54
Try turning off flywheel backend by
/flywheel backend off

**Comment by mixolydianmel** [comment]
> Probably caused by this( #54 Try turning off flywheel backend by /flywheel backend off

This works with Indium, shafts and the head of the windmill bearing render!

The actual turning sails, however, still do not render with shaders.

**Comment by JieningYu** [comment]
> > Probably caused by this( #54 Try turning off flywheel backend by /flywheel backend off
> 
> This works with Indium, shafts and the head of the windmill bearing render!
> 
> The actual turning sails, however, still do not render with shaders.

Actually you can turn the shadows off in shaders settings(iris has shaders settings from 1.2.0) just like what the title pointed

**Comment by IMS212** [comment]
My current suspicion is unfortunate timing between Iris and flywheel causing beginFrame’s info to get overridden with the shadow one, **even during normal rendering**.

**Comment by IMS212** [comment]
The cause behind this has been found, and multiple ways of fixing it are being investigated.

**Comment by DragonWoven** [comment]
something I've seen that I don't thinks been mentioned is that, with shadows enable, moving contraptions don't simply not render they appear in the sky where your crosshair is

**Comment by IMS212** [comment]
This is due to an overwrite of the render buffers, so yes, this is expected.

**Comment by soup587** [comment]
Any news on a fix?

**Comment by JieningYu** [comment]
> Any news on a fix?

There's a branch in iris github named"create"

**Comment by soup587** [comment]
i think that was merged into the latest version but refabricated isn't working right now so

**Comment by soup587** [comment]
now we wait for a 1.18.2 build

**Comment by michlbro** [comment]
> i think that was merged into the latest version but refabricated isn't working right now so

The "fix" on the iris side has been merged into the latest version, however the fix for flywheel hasn't (The PR) - which kind of works. (Renders some shadows 👀 ).

**Comment by sybershot** [comment]
So, here we are once again...
I'm currently testing build 495 with iris shaders installed.
Moving multiblock contraptions still do not render, though, cast shadows. Turning off shadows in the pack's setting fixes the problen.
Upd: This also applies to minecart contraptions.
Side note: turning off indium causes visual glitches on the models with animation, such as cogwheels.
Everything else seem to work properly, even the ponder scenes.
Full mod list:
- Create 0.4.1 Build 495
- Fabric API 0.48.0 1.18.2
- Indium 1.0.2
- Iris 1.2.2 Build 32
- Phosphor 0.8.1
- Reese's Sodium Options 1.4.2
- Sodium 0.4.1 Build 15
- Sodium Extra 0.4.3

Shaderpack used:
Sildur's Enhanced Default 1.131 (using default settings)

**Comment by michlbro** [comment]
If you check out the flywheel github page, you can check if they have merged the iris stuff that fixes this (PR). Currently I don’t think they have fully fixed it yet as they are still trying to resolve it.

**Comment by weegeeluigi** [comment]
Yep, can confirm shadows render but the contraptions will still render on crosshair in random locations.

**Comment by IMS212** [comment]
This has been fixed on Iris’ side in the new commits, but there are new issues pertaining to rendering entities + contraptions in the same scene now.

**Comment by IMS212** [comment]
![2022-04-12_22 28 51](https://user-images.githubusercontent.com/31803019/163048267-bfb73d5b-1f94-4c3d-a584-3edc652d7830.png)
Iris 1.2.3 pre-alpha, with some support for contraptions: (Please do not report anything using this to the Iris support channel, but rather directly to me.)
https://cdn.discordapp.com/attachments/774353381057495061/963536834758053972/iris-mc1.18.2-1.2.3-pre-6a7bd8b2-dirty.jar

**Comment by weegeeluigi** [comment]
Did a quick test, rendered pretty well I would say that 1.2.3 will be a nice update.  Performance also matched so I would say it's looking good without sacrificing anything.

Keep up the great work!

**Comment by IMS212** [comment]
Fixed in 1.2.3.
