### ISSUE TITLE
Create 0.5.1-b , Copycat Panel , Crash game

### ISSUE THREAD

**Issue by VictorGuten** [Fabricators-of-Create/Create#971]
### Describe the Bug

Installing a Composter block in the Copycat Panel causes the game to crash

### Reproduction Steps

1.Take blocks : Copycat Panel And Composter
2.Place the block Copycat Panel in the world
3.Install Composter in Copycat Panel
...

### Expected Result

Crash game

### Screenshots and Videos

After entering the world there are graphic bugs

![изображение](https://github.com/Fabricators-of-Create/Create/assets/122190297/e85768ef-49e0-4302-a22e-0c983ef7ac07)
![изображение](https://github.com/Fabricators-of-Create/Create/assets/122190297/6bb37ab2-8763-4795-8d06-e5b2094fa58a)

### Crash Report or Log

https://gist.githubusercontent.com/VictorGuten/7c4010d0b22f4e481a35af8d878739c4/raw/92f1c6ba23dcb132e8dbe86ef4a65d4bb59e854c/Create%25200.5.1-b%2520Crach.txt

### Operating System

Windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.18.2

### Other Mods

Full mod list:
- fabric api 0.76.0+1.18.2
- modmenu 3.2.2
- create-fabric-0.5.1-b-build.1078

**Comment by electricsteve** [comment]
i think you shouldnt be able to put composters in copycats

**Comment by VictorGuten** [comment]
but it's works on Forge

![изображение](https://github.com/Fabricators-of-Create/Create/assets/122190297/c4bea4dc-2d59-4c97-b4ad-7ac99c864720)

**Comment by electricsteve** [comment]
weird
