### ISSUE TITLE
Create crashed on startup with Sodium and Supplementaries

### ISSUE THREAD

**Issue by BlazeHunterVN1610** [Fabricators-of-Create/Create#972]
### Describe the Bug

Install Create v0.5.1.b or v0.5.1.b Patch 1,and both Sodium and Supplementaries in the mods folder, the game will crash on startup
If Create is installed without Sodium or Supplementaries or both of them, the game will not crash
Although Moonlight Lib is requred for Supplementaries to run, it does not affect the game

### Reproduction Steps

1.Install Create, Sodium and Supplementaries
2. Wait
3. Crash
...

### Expected Result

No crashes appear

### Crash Report or Log

https://gist.github.com/BlazeHunterVN1610/1ea6dd98c2d17409d3ecee0ee45a603b

### Operating System

Windows 11

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

		fabricloader: Fabric Loader 0.14.21
		java: Java HotSpot(TM) 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
		moonlight: Moonlight 1.19.2-2.2.39
		sodium: Sodium 0.4.4+build.18
		supplementaries: Supplementaries 1.19.2-2.3.19

**Comment by TropheusJ** [comment]
straight from the log: `You seem to have installed Sodium which breaks fabric rendering API.To fix you must install Indium as Supplementaries, as many other mods, rely on said API`
It might still crash, as I think Supplementaries has compatibility with Create that broke with 0.5.1. Don't know if it updated yet.
