### ISSUE TITLE
0.5.1-b crash with addons

### ISSUE THREAD

**Issue by thekrugers** [Fabricators-of-Create/Create#973]
### Describe the Bug

When adding commonly used addons such as Create Crafts & Additions (updated for 0.5.1), Create Deco (updated for 0.5.1) or Steam & Rails (but never mind this one, it doesn't say which Create version it's for and I suspect 0.5.0 because it's an older build), the client crashes on startup with an exception "Could not execute entrypoint stage 'main' due to errors, provided by " followed by the addon mod name.

### Reproduction Steps

1. Install Create 0.5.1 or 0.5.1b
2. Install any of the addons listed above
3. Try to start the game and get a crash report instead

### Expected Result

A running game.

### Crash Report or Log

https://gist.github.com/thekrugers/f4965d5c0aa4ed058e09e8bdf1429aaf

### Operating System

Windows 11

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

createaddition-fabric-1.19.2-20230508b.jar
OR
createdeco-1.3.3-1.19.2.jar
OR
Steam_Rails-1.3.5+forge-mc1.19.2.jar (but probably not a 0.5.1 compatible version, so less important)

**Comment by thekrugers** [comment]
According to a comment here - https://github.com/Layers-of-Railways/Railway/issues/116
Create Steam & Rails has been fixed to work with 0.5.1

**Comment by electricsteve** [comment]
think its a fault on createadditions side as i see in the error, because i think it is calling for a class that doesn't exist

**Comment by thekrugers** [comment]
The two crash report files I provide are from two different runs and two different configuratons. One has createadditions installed and one has createdeco installed. Neiter has both installed. Same error, two different addons. Do the math.

**Comment by purejosh** [comment]
> Do the math.

Being rude isn't gonna help you get what you're after.

**Comment by TropheusJ** [comment]
CC&A has not been updated on fabric in a long time. You are using a version of Deco that was released before 0.5.1.
