### ISSUE TITLE
Giving a lava bucket to a deployer causes server to crash

### ISSUE THREAD

**Issue by purejosh** [Fabricators-of-Create/Create#974]
### Describe the Bug

Giving a lava bucket to a deployer causes server to crash, repeatable. 

### Reproduction Steps

Give a lava bucket to a deployer. 

### Expected Result

Not crash...

### Crash Report or Log

https://gist.github.com/purejosh/caee3aa7f9e62e336774c4d6a1b9659a

### Operating System

n/a

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

There's a lot of mods, but I'm not using any create addons at this time.

**Comment by TropheusJ** [comment]
This is an incompatibility with Open Parties and Claims that has been fixed by them. Don't know if the fix has been released yet.

**Comment by purejosh** [comment]
Yeah... I shoulda seen that. Sorry, I too quickly assumed this was just create being create.
