### ISSUE TITLE
BlockCulling EntityCulling Create mod

### ISSUE THREAD

**Issue by GitJhopa** [Fabricators-of-Create/Create#975]
### Describe the Suggestion

Blocks and mechanisms from Create are displayed from too far away, is it possible to make them EntityCulling? So that they are displayed only from a distance of 16-32 blocks?

**Comment by DarianLStephens** [comment]
Pretty sure that's due to Flywheel, which is meant to make this sort of thing much more performant than vanilla.

**Comment by tr7zw** [comment]
Please close this issue. EntityCulling on purpose excludes some Create stuff, and Flywheel-rendered stuff is also not touched. Added to that, in your reports you are using the Forge version, this is Fabric. Nothing here to fix/look into.
