### ISSUE TITLE
List Filter in Brass Tunnel

### ISSUE THREAD

**Issue by SuperRick1** [Fabricators-of-Create/Create#980]
### Describe the Bug

When I want to get a list filter out of a brass tunnel it disappears and I am not getting the list filter that was in the brass tunnel (the filter slot).

### Reproduction Steps

1. There is a list filter in the filter slot of a brass tunnel.
2. I click on the filter to remove the list filter.
3. The list filter disappears from the brass tunnel and I am not getting the list filter in my inventory.

### Expected Result

I expected to get the filter that was in the brass tunnel.

### Operating System

Windows 11

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

Fabric

**Comment by electricsteve** [comment]
Pls provide other mods that are in your mods folder, maybe also the latest.log or a video of you reproducing it
