### ISSUE TITLE
Issues with Spout Filling Recipes

### ISSUE THREAD

**Issue by Squidney64** [Fabricators-of-Create/Create#983]
### Describe the Bug

I have a modpack with my friends that uses both the Create and Dehydration mods. Now, Dehydration adds the Purified Water liquid, which is used in the thirst system. Since we wanted to automate the water I got to work on a datapack that adds compatibility recipes. Specifically draining the liquid with an Item Drain (works just fine), and filling an empty bucket with the liquid.
This is where I ran into trouble. The recipe I made works just fine, but it breaks the filling recipe for normal water. Whenever the spout is filled with good old "minecraft:water" it will fill the empty buckets into purified water, even though I didn't add that recipe to the game. I tried making a new recipe of what the water _should_ do, but that didn't fix it. When I rename the fluid in the filling recipe to any liquid except "dehydration:purified_water" then it works fine. But for some reason, the spouts can't tell the difference between normal water and purified water when filling the buckets.

Recipe In Question:
`{
  "type": "create:filling",
  "ingredients": [
    {
      "item": "minecraft:bucket"
    },
    {
      "fluid": "dehydration:purified_water",
      "amount": 81000
    }
  ],
  "results": [
    {
      "item": "dehydration:purified_water_bucket"
    }
  ]
}`

### Reproduction Steps

1. Have a spout pulling minecraft:water from a fluid tank
2. Have a belt taking empty buckets under it
3. Spout should fill up buckets with water
4. With Dehydration mod on, apply the custom recipe above
5. If the spout has Purified Water, it fills the bucket with purified water. If the spout has ordinary water, it still fills it with purified water.

### Expected Result

The spouts should fill the bucket with purified water if the spout has purified water in it. If the spout has normal water in it, it should fill it with normal water.

### Screenshots and Videos

![2023-06-30_17 50 55](https://github.com/Fabricators-of-Create/Create/assets/20098059/590da801-6f49-41b4-ad27-c1989b208827)
![2023-06-30_17 51 05](https://github.com/Fabricators-of-Create/Create/assets/20098059/40c98afe-4037-4185-afde-59a881598dcd)
![2023-06-30_17 51 29](https://github.com/Fabricators-of-Create/Create/assets/20098059/dc995187-a820-4873-8c45-3d16794f6854)

### Operating System

Windows 11

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

Dehydration is the only mod directly involved mod but the modpack has several others mods running

**Comment by Squidney64** [comment]
This could also be considered a suggestion for Dehydration compatibility

**Comment by TropheusJ** [comment]
This is caused by Dehydration making water considered equal to purified water [here](https://github.com/Globox1997/Dehydration/blob/6c1c075468a80c1d4de707e5c5f704060a82031f/src/main/java/net/dehydration/mixin/WaterFluidMixin.java#L35).

**Comment by TropheusJ** [comment]
Has been reported.
