### ISSUE TITLE
Version number does not follow semver

### ISSUE THREAD

**Issue by embeddedt** [Fabricators-of-Create/Create#986]
See https://github.com/embeddedt/CreateChunkloading/issues/28. I have set my mod to depend on v0.5.1 or later, but because the version number is `0.5.1-b` it is seen as a prerelease by Fabric, which causes it to incorrectly report my mod as being incompatible.

**Comment by TropheusJ** [comment]
You should be able to depend on `>=0.5.1-a` from my testing.

The version number must obviously match a corresponding forge version, and semver makes this quite difficult. This format has issues, but is the best I could figure out.
