### ISSUE TITLE
Create Launch iwrenchable crash?

### ISSUE THREAD

**Issue by netcore10** [Fabricators-of-Create/Create#989]
### Describe the Bug

Not sure if it's an addon, but it was working until the latest fabric version

### Reproduction Steps

Not sure.

### Expected Result

To launch

### Crash Report or Log

https://mclo.gs/WsMy31K
https://paste.atlauncher.com/view/96ba5b1d-fc8c-4d6a-948b-9b82a05c8aed

### Operating System

windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

https://docs.google.com/spreadsheets/d/1ZdEam3wHHv2gXmtVdvq8Mwbfn-mXYH2lpDZeA9ezqOE/edit#gid=0

### Additional Context

It could be a create addon, but i'm having trouble knuckling down the issue.

**Comment by TropheusJ** [comment]
addons
