### ISSUE TITLE
some items in ValueBox dosent be rederered properly

### ISSUE THREAD

**Issue by JieningYu** [Fabricators-of-Create/Create#99]
### Describe the Bug

Some items(like torches) in ValueBox for filtering have a wrong offset. They "fall into" the machine(like deployer) and they can be rendered.
(look at the picture)

### Reproduction Steps

1.Put a Deployer(or brass funnel).
2.Put a torch into the "filter" box.
3.It cant be seen.

### Expected Result

It could be seen properly like bone meal.

### Screenshots and Videos

<img width="399" alt="Screenshot@20220121180448" src="https://user-images.githubusercontent.com/61787533/150508308-d886599f-21e5-41dd-97bd-605181dc50a6.png">

### Operating System

macOS 12.2 Beta (21D5039d)

### Mod Version

0.4.0c

### Minecraft Version

1.18.1

### Other Mods

Sodium
Indium
Iris
Flywheel
Phosphor

**Comment by TropheusJ** [comment]
most likely caused by [this line](https://github.com/Fabricators-of-Create/Create/blob/4f861fc79f1c0e35674746d8a8391b76a3a0b715/src/main/java/com/simibubi/create/foundation/tileEntity/behaviour/ValueBoxRenderer.java#L25)

**Comment by stesoma** [comment]
Isn't this the same as #89 ?

**Comment by TropheusJ** [comment]
oh. yeah.
