### ISSUE TITLE
When setting and releasing the filter in the brass tunnel, it does not return the filter.

### ISSUE THREAD

**Issue by kimmk1533** [Fabricators-of-Create/Create#990]
### Describe the Bug

I apologize in advance for my poor English skills.
When setting and releasing the filter in the brass tunnel, it does not return the filter. I also checked the inventory, but the results were the same.

windows10
mc-version: 1.19.2
mod-version: Create fabric 1.19.2 v0.5.1.b Patch 2

Thank you for creating a fun mod.

### Reproduction Steps

1. Place the brass tunnel on the belt
2. Set up a filter on the brass tunnel
3. Unfilter (set filter with bare hands)

### Expected Result

Filter should be returned when right-clicked with bare hands.

### Screenshots and Videos

When setting filters on a funnel:
1.
![image](https://github.com/Fabricators-of-Create/Create/assets/55845465/660c43e5-3273-450a-a642-0bf22b55469b)
2.
![image](https://github.com/Fabricators-of-Create/Create/assets/55845465/926f1cb8-0b85-49c7-ad43-c58cf0dd801e)
3.
![image](https://github.com/Fabricators-of-Create/Create/assets/55845465/367a70d0-9424-4dc3-bfbb-ea8ab545d401)

On the other hand, when setting filters on a tunnel:
1.
![image](https://github.com/Fabricators-of-Create/Create/assets/55845465/c4714fd6-d9bf-4bf5-a07e-c4ab927564af)
2.
![image](https://github.com/Fabricators-of-Create/Create/assets/55845465/9b6f1063-6d82-4d5f-8173-3526e485a213)
3.
![image](https://github.com/Fabricators-of-Create/Create/assets/55845465/8434dae3-8332-49a9-b0f9-09462e277378)

### Operating System

Windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

**Comment by GW-Dev** [comment]
I am also having this issue

**Comment by RemyKap** [comment]
This issue is appearing for me as well. When attempting to remove filter from at least brass tunnels it does not return and instead seems to void the item.

**Comment by TropheusJ** [comment]
this has been fixed
