### ISSUE TITLE
Porting lib error

### ISSUE THREAD

**Issue by wool25** [Fabricators-of-Create/Create#993]
### Describe the Bug

No matter what version of create fabric 0.5.1b or porting lib we install, they wont work together and minecraft refuses to launch

### Reproduction Steps

1. install create fabric
2. install porting lib
3. launch minecraft
...

### Expected Result

minecraft should be launching correctly?? we have the correct mods, there might be other issues though

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/108700081/2ccf6d91-f56d-42c7-b535-bcf77e8df322)

### Crash Report or Log

https://pastebin.com/DT8zBd6p

### Operating System

Windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

![image](https://github.com/Fabricators-of-Create/Create/assets/108700081/b8ebe719-448b-4370-9892-bc4cb3d0511f)
![image](https://github.com/Fabricators-of-Create/Create/assets/108700081/d599e70f-19c8-430d-9fb2-26ca26f3e616)
![image](https://github.com/Fabricators-of-Create/Create/assets/108700081/6364751a-0534-47a6-b765-0ddb818e142f)
![image](https://github.com/Fabricators-of-Create/Create/assets/108700081/bb0242e6-a481-4494-aa8f-4e34d49cac51)

### Additional Context

this is also happening to my friends on the same modpack, same error

**Comment by TropheusJ** [comment]
update fabric api
