### ISSUE TITLE
connection error due to mod on server

### ISSUE THREAD

**Issue by Nilus001** [Fabricators-of-Create/Create#994]
### Describe the Bug

I can't connect with the mod on the "minehut" server (a big hosting service server) with the mod 
The error : 
Connection Lost
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(16399) + length(1) exceeds writerIndexC16399): UnpooledHeapByteBufCridx: 16399, uidx: 16399, cap: 16399/16399) 

### Reproduction Steps

1. try to connect to Minehut with mc.minehut.com
...

### Expected Result

be able to play with the mod on minehut

### Screenshots and Videos

![Capre](https://github.com/Fabricators-of-Create/Create/assets/138899938/4cf4bc2b-0cd8-4abf-ad6a-500fb4aedc91)

### Operating System

Windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

architectury-6.5.85-fabric
bclib-2.1.5
cloth-config-8.2.88-fabric
ContainerSearcher-0.1.6+mc1.19.2
dynamic-fps-2.1.0
fabric-language-kotlin-1.9.0+kotlin.1.8.0
FabricProxy-Lite
FpsReducer2-fabric-1.19.2-2.1
freecam-1.1.6+1.19
InventoryProfilesNext-fabric-1.19-1.8.5
journeymap-1.19.1-5.9.0beta2-fabric
libIPN-fabric-1.19-1.0.5
litematica-fabric-1.19.2-0.12.5
malilib-fabric-1.19.2-0.13.0
MouseTweaks-fabric-mc1.19-2.22
shulkerboxtooltip-fabric-3.2.2+1.19.2

**Comment by electricsteve** [comment]
Don't get it, do you have Create installed on the server that you're joining? Otherwise, you can't play on vanilla servers with mods installed. If you have Create installed on the server, make sure its the right version, version of other mods and so on.

**Comment by TropheusJ** [comment]
feather is not supported
