### ISSUE TITLE
Display Link: Value Display Options

### ISSUE THREAD

**Issue by Damdrara** [Fabricators-of-Create/Create#995]
### Describe the Bug

When selecting "List matching Items", the Value display option on the Fabric version gives the following options:

![image](https://github.com/Fabricators-of-Create/Create/assets/54811051/380ed6a8-fee2-4ce1-8926-28b2426fa6f3)

...which doesn't make a whole lot of sense for items.

### Reproduction Steps

1. Put a content observer / smart observer on a vault
2. put a display link on the observer
3. check the options

### Expected Result

The forge version gives these:

![image](https://github.com/Fabricators-of-Create/Create/assets/54811051/f26bc6bc-5ad9-411c-bffe-bcfc9e59d8da)

### Operating System

Windows 11

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Additional Context

also happens on 0.5.0i

**Comment by electricsteve** [comment]
first, make sure it is pointing at a container with items in it, second, the forge screenshot is taken in older version, so maybe it isn't rellevent in the newest version.

**Comment by Damdrara** [comment]
It definitely has items in it, that's not the issue.

I tested the bug on various versions, with the exact same world. it occures on Fabric on both 0.5.0i with the Content Observer and 0.5.1b with the Smart Observer, and it did not occur on Forge on either version.

**Comment by Damdrara** [comment]
Without digging too deep, super quick code search finds the related change:

https://github.com/Fabricators-of-Create/Create/commit/c9114f1c8dbf360f767d04fef1e2c3a13a0aaf9d

It seems this was specifically changed for the Fabric version due to different fluid mechanics, but it wasn't taken into account that the same label is used for items as well, not just fluids.

**Comment by MrGreenTea** [comment]
Yeah I've come across this as well. It seems to be an issue with the translation as it does not differentiate between the Item List and Fluid list:

Here is the key in the [Translation file Source](https://github.com/Fabricators-of-Create/Create/blob/49cc17e3de33c965b1c409130abe436821f7410c/src/main/resources/assets/create/lang/default/interface.json#L948)

Here it is used for the ValueList: [ValueListDisplaySource.java](https://github.com/Fabricators-of-Create/Create/blob/49cc17e3de33c965b1c409130abe436821f7410c/src/main/java/com/simibubi/create/content/redstone/displayLink/source/ValueListDisplaySource.java#L166)

It is the same as used in FluidList: [FluidListDisplaySource.java](https://github.com/Fabricators-of-Create/Create/blob/49cc17e3de33c965b1c409130abe436821f7410c/src/main/java/com/simibubi/create/content/redstone/displayLink/source/FluidListDisplaySource.java#L128)

**Comment by nicolas-rabault** [comment]
I experience the same problem on V0.5.1f
