### ISSUE TITLE
Contraption breaks Supplementaries' Hanging Sign

### ISSUE THREAD

**Issue by BlazeHunterVN1610** [Fabricators-of-Create/Create#997]
### Describe the Bug

Whenever you activate a contraption controller block such as Mechanical Bearing or Piston, it will instantly break Supplementaries Hanging Sign
This doesn't happen in v0.5.0

### Reproduction Steps

1. Build any kind of contraption and glue the sign to it
2. Activate it
3. The sign break

### Expected Result

The sign will not be broken and moves along with the contraption

### Screenshots and Videos

https://github.com/Fabricators-of-Create/Create/assets/111768452/df426cae-8a8d-4566-9a34-61fd2216b23e

### Operating System

Windows 11

### Mod Version

0.5.1b

### Minecraft Version

1.19.2

### Other Mods

![Screenshot (60)](https://github.com/Fabricators-of-Create/Create/assets/111768452/04a48158-305a-4bf4-bdc4-891a6bcd95fd)

**Comment by electricsteve** [comment]
proably need fixing on their side

**Comment by IThundxr** [comment]
Supplementaries needs to tag their blocks that have this issue with `create:movable_empty_collider`
