### ISSUE TITLE
Broken texture for brass/andesite parts for certain blocks

### ISSUE THREAD

**Issue by Golden-Apple-SRD** [Fabricators-of-Create/Create#999]
### Describe the Bug

Brass/andesite part of certain Create blocks show the broken texture.
Affected blocks:
- Smart Chute
- Andesite/Brass Tunnel
- Mechanical Crafter

### Reproduction Steps

1. Install Create Fabric and the mods in the list below
2. Load a random Singleplayer map
3. Get the items with broken textures from the inventory

### Expected Result

Broken textures (magenta and black squares, see attached screenshot for details) would appear at the andesite/brass part of the block.

### Screenshots and Videos

![image](https://github.com/Fabricators-of-Create/Create/assets/88383431/1adac754-8edb-4840-9b5b-34a1191357d6)

### Operating System

Windows 10

### Mod Version

0.5.1b

### Minecraft Version

1.18.2

### Other Mods

- Essential
- Indium (v1.0.7)
- Sodium (v0.4.1)
- Iris (v1.6.4)
- Lithium (v0.10.3)
- Starlight (v1.0.2)
(other mods do not affect block/texture rendering)

### Additional Context

Bug also appears in the pondering menu.
Mechanical Crafter does not seem to have any broken textures when placed down.

**Comment by electricsteve** [comment]
do you have any texture packs installed and can you share your instance?

**Comment by Golden-Apple-SRD** [comment]
It is fixed after removing this resource pack:
https://www.curseforge.com/minecraft/texture-packs/xekr-redstone-display

**Comment by electricsteve** [comment]
Ok, now you can close the issue
